### ISSUE TITLE
Storage with custom file names

### ISSUE THREAD

**Issue by rnybergh** [strongloop/loopback#1002]
We are implementing a solution where the user can upload files that are related to a certain group. Using the storage-connector and Container, there does not seem to be any way of changing the incoming filename. Thus there seems to be no other way of naturally grouping the files together than creating a container for each group. This would work nicely on the local filesystem, since the container is a folder/directory. But we plan to migrate the system to Amazon S3, where container=bucket and there can only be a limited amount of buckets.
Is there some way to rename the file with Container.upload that we have missed? If not, is creating something like that on the roadmap for the near future?
I saw somewhere a mention of doing metadata for files uploaded, perhaps that is related/will solve the issue?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. You will get a quicker response there as we have a very active community willing to help out.

Please let me know when you've copied the question over there so I can close this issue.
