### ISSUE TITLE
Disable dynamic ACL checks via setting

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1003]
Many LB apps aren't using dynamic ACLs... yet the access control pipeline can't know this. It still will query the `dataSource` for dynamically defined access controls. What if we added something like:

```
MyModel.settings.dynamicAccessControls = false
```

When false we would just skip the query for dynamic ACLs...

@raymondfeng @bajtos

**Comment by raymondfeng** [comment]
+1. On top of that, we should allow static roles/roleMappings, global ACLs across models in json.

**Comment by rawrmaan** [comment]
This should be a bigger priority. ACL.find contributes to a significant percentage of each requests's latency in my app

**Comment by bajtos** [comment]
@rawrmaan thank you for chiming in. Would you mind contributing this improvement yourself? I am happy to help you along the way.

**Comment by rawrmaan** [comment]
@bajtos Thanks for the offer. Normally I would accept but I realized I'm unfortunately going to have to ditch Loopback entirely due to the unstable nature of `loopback-context`. :(

**Comment by bajtos** [comment]
>  I'm unfortunately going to have to ditch Loopback entirely due to the unstable nature of loopback-context.

Well, loopback-context is unstable because there is no reliable implementation of a thread-local-storage for Node.js. We have a more reliable alternative available now, see http://loopback.io/doc/en/lb3/Using-current-context.html
