### ISSUE TITLE
Feature Proposal: Facilities for monitoring Model local state

### ISSUE THREAD

**Issue by bitmage** [strongloop/loopback#1006]
I wanted to kick around an idea and see what others think.

Most other model systems (Mongoose, Backbone, ActiveRecord) have facilities for monitoring dirty state of objects and provide hooks that can activate when the values change.  Loopback seems to be taking a different path - it's building out towards rich replication features on collections, but doesn't have much in the way of events and status for local state changes in a model instance.

In my case I'm using Loopback models on the client in unison with React.  It would be really handy for me to use a Loopback object directly as the state for my view.  But without the events and dirty status this is impractical.  So I'm ending up rewriting the dirty and events functionality as a view mixin in order to get the job done.  Ideally though, I could bind directly to a model that supports this functionality.

It seems like maybe this was low priority for the models as server side entities, but may become more of a desirable trait as client side models become a major use case.

Thoughts on whether this would be useful/desirable?  Other local state functionality that would be useful?  Is it already implemented and I've just passed over it?

Thanks!

**Comment by ritch** [comment]
> Most other model systems (Mongoose, Backbone, ActiveRecord) have facilities for monitoring dirty state of objects and provide hooks that can activate when the values change.

We used to have this... but it involved defining a lot of redundant properties (`Object.defineProperty()`). You should be able to do dirty checking / change notification with `setter`s.

```js
MyModel.setters.myField = function(val) {
  if(isDifferent(this.__data.myField)) this.hasChanged('myField');
  this.__data.myField = val;
}

var myModel = new MyModel({myField: 'old'});

myModel.hasChanged = function() {
  console.log('model has changed');
}

myModel.myField = 'new'; // => model has changed
```

> Ideally though, I could bind directly to a model that supports this functionality.

If we do this - it will probably be as an external module / mixin.

**Comment by bitmage** [comment]
Would you mind pointing me to the commit when this used to be implemented?  Maybe it can be factored out as a mixin.

I'm concerned though that implementing this functionality externally will be hacky and subject to breaking with subsequent releases.

It seems like functionality that should be standardized rather than everyone rolling their own.

**Comment by bajtos** [comment]
Hello, as part of our triage process, I am closing issues that have been inactive for extended period of time. Feel free to reopen if you think this issue is still relevant.
