### ISSUE TITLE
isSet query operator

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1009]
We should add support for something like this:

``` js
{
  where: {
    someField: {
      isSet: false
    }
  }
}
```

This would allow you to query for undefined fields using `$isset` in mongodb and `NULL` in SQL databases.

**Comment by ritch** [comment]
@kraman @bajtos @raymondfeng @fabien

**Comment by bajtos** [comment]
Well if we can't use `{ where: { someField: null } }`, then `isSet` makes sense.

**Comment by raymondfeng** [comment]
We can use `{ where: { someField: null } }` today but the semantics is different for NoSQL DBs. For example, in Mongo,

 someField: null ==> someField: {$type: 10}
 someField: {isSet: false} ==> someField: {$exists: 10}

I'm fine to introduce connector specific extensions. Each connector should validate such extensions and report errors if a given operator or syntax is not supported.

**Comment by bajtos** [comment]
We can use `{ where: { someField: null } }` today but the semantics is different for NoSQL DBs. 

Yeah, I was sort of expecting that, in wich case `null` is not a solution. Since LoopBack is promising to provide single API working on all databases, we need a solution that works consistently in all supported databases.

**Comment by marcellodesales** [comment]
@bajtos @raymondfeng is there any timeframe when this feature makes the cut?

**Comment by bajtos** [comment]
@marcellodesales not really. Can you contribute the feature yourself?

**Comment by jsheely** [comment]
This already works using the exists method. 

```javascript
// REST Url
// /api/<modelName>?filter[where][<propertyName>][exists]=<true|false>

modelName.find({
    where: {
        propertyName: {
            exists: true
        }
    }
}, callback)
```

The key is https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L488 where it will apply the $ sign to any property it doesn't understand as an else case.

**Comment by kraman** [comment]
@jsheely That is specific to mongodb. would be nice if this could be generalized to all dbs.

**Comment by jsheely** [comment]
@kraman Agreed. I just wanted to be clear that this feature technically can work today. This and the related issues make it seem like it wasn't possible.

While it is not a **baked** part of the abstracted API it is very nice that it can fall down into the specific implementations of the provider and still be handled.

**Comment by raymondfeng** [comment]
@kraman What's your expectation for relational DBs? Do you interpret `exists: true` as `IS NOT NULL`?

**Comment by kraman** [comment]
@raymondfeng yes, typically it would be `IS NOT NULL`

**Comment by marcellodesales** [comment]
@jsheely I agree with that being available in the API, as well as with @kraman around "IS NOT NULL" on relational db...

**Comment by kblcuk** [comment]
@jsheely, the approach you mentioned doesn't work with current datasource-juggler when it coerces where clause:
https://github.com/strongloop/loopback-datasource-juggler/blob/128665f1bd403b94a08a55a230a496e838c47347/lib/dao.js#L926

**Comment by dhirenderbp** [comment]
nothing is working for the existence of a field in a document.

**Comment by AlmaasAre** [comment]
+1. Having the same probem as @kblcuk

**Comment by pmoelgaard** [comment]
Isn't this a very common use case, I cant believe there is no solution ?

**Comment by kblcuk** [comment]
@pmoelgaard we've worked around it by introducing `isDateSet` property for model (defaulting to `false` since default for date in question is `null`), with which we can search for models which don't have date set.
This is suboptimal, though, and hopefully this issue will be eventually resolved.

**Comment by rawrmaan** [comment]
This is redonk. High priority for my team +5

**Comment by gausie** [comment]
The automatic passthrough of unrecognised properties actually doesn't work for this on MongoDB.

**Comment by gausie** [comment]
The reason for this bug lies with this line

https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1238

In my case, the property I am inspecting is of boolean type. My `{ exists: true/false }` object will be converted to `true` by this line because `DataType` is the `Boolean` constructor.

**Comment by gausie** [comment]
A possible solution for this would be to have the coercion skipped if the value is an object?

**Comment by barocsi** [comment]
I believe we should go with native mongodb queries with a hydrating approach, instead of reproducing and generalizing a nosql query structure which is way more efficient than this. Mongodb queries were designed to be crafted for a specific problem thus this connector struggles reproducing the same in a generalized yet on a high cost path

**Comment by barocsi** [comment]
For example see this
```
{last_vote_date: {exists: true}
```
throws an error
```
stack: "Error: Invalid date: [object Object]↵    at DateType 
```
So how should this be resolved? Any workaround?

**Comment by kblcuk** [comment]
@barocsi https://github.com/strongloop/loopback/issues/1009#issuecomment-138228604

Another option I guess would be to init that date during `beforeSave` hook to be 0 ('1970-01-01', or something like that), and make your code to treat it like null.

**Comment by barocsi** [comment]
Thanks! But pre-filling the with database with unneeded data, just for the sake of a inappropriate  (re-)implementation of an efficient mongodb query wrapper.

**Comment by jsheely** [comment]
Currently the DAO breaks this functionality for the mongoDB fall through $exists check.

```
} else if (!((operator === 'like' || operator === 'nlike') && val instanceof RegExp)) {
          //val = DataType(val);  // Remove this use the object instead of passing "[object Object]" as the value
}
```
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1496

**Comment by lautarodragan** [comment]
This is needed for couchbase aswell! Any updates on the implementation of this feature?

**Comment by pratheekrebala** [comment]
FWIW, this ended up working for me: `Filing.Find({"downloaded": {'neq': true}})` on Model attached to a MongoDB source returns same results as `db.getCollection('Filing').find({"downloaded": {$exists: false}})`

**Comment by sundeepgupta** [comment]
I'm finding that the `nlike` operator is working as a workaround in my particular case, which is for a MongoDB connector and `string` type property.

`Account.find({where: {analyticsId: {nlike: ''}}})`

**Comment by Ijmir** [comment]
+1
can't query date field with exists - throws error when trying to cast it to date.
any update on this?

**Comment by tamitutor** [comment]
+1 
Trying to send a query via the REST api.  Want to return Mongo documents where a particular field does NOT exist.

**Comment by Sanbornzhang** [comment]
maybe sometime filter have `$` should continue ?
cause I always need `field:{$operator: value}` 
`if field instanceof Model and key match ^$ then continue `?
I think there will not convert to '[object Object]' ,should return to mongoDB. let mongo to do .

**Comment by idushes** [comment]
`module.exports = function(server) {
  let APIConnector;
  APIConnector = server.datasources.mongo.connector;
  return APIConnector.observe('before execute', function(ctx, next) {
    if (ctx && ctx.req && Array.isArray(ctx.req.params)) {
      ctx.req.params.forEach(function (param) {
        Object.keys(param).forEach(function (key) {
          if (param[key] && param[key]["$type"] === 10) param[key] = null;
        });
      })
    }
    next();
  });
};
`

**Comment by idushes** [comment]
<img width="791" alt="screenshot 2017-05-14 11 15 16" src="https://cloud.githubusercontent.com/assets/13415220/26035735/a7ba4014-3896-11e7-9352-6ea3bb6e2d82.png">

**Comment by jawadrehman** [comment]
got this error with a date type as well. Have to add null data :(

**Comment by akvaliya** [comment]
I am also getting this issue.
Works for exists:true, but doesn't work for exists:false

**Comment by frankorama** [comment]
Using Loopback 2, this worked for me:

`{where: {property: undefined}}`

The query returned all documents that did not have the property specified and left out documents that did.

**Comment by bartlettpsj** [comment]
It is still an issue!

**Comment by SippieCup** [comment]
Guessing now that we are in active LTS this wont be fixed :(
