### ISSUE TITLE
Update Android SDK Getting Started Guide

### ISSUE THREAD

**Issue by steve-the-edwards** [strongloop/loopback#1012]
SDK 'Getting Started' guide uses deprecated object-wrappers and callbacks.

**Comment by crandmck** [comment]
@steve-the-edwards It would be great if you would tackle this.  GH is not letting me assign the issue to you, though.  But I'll assume you're going to address it, unless I hear otherwise from you.  Thanks!

Please let me know if you have any questions about using Confluence.

**Comment by steve-the-edwards** [comment]
Basic update is done now.  I think reviewed?  Please review again if necessary.  Otherwise, can close.

**Comment by crandmck** [comment]
I approved your edits. Thanks for your contribution!
