### ISSUE TITLE
Review and revise loopback-example-remote

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1013]
Review https://github.com/strongloop/loopback-example-remote and make it consistent with other examples.

Amir:
Connect to : https://github.com/strongloop/loopback-example-remote/pull/7

**Comment by superkhau** [comment]
@crandmck This should be created in scrum-loopback.

**Comment by crandmck** [comment]
@superkhau Why?  It shows up in the [Waffle board](https://waffle.io/strongloop-internal/scrum-loopback). 
 
Unless there a reason for it to be private, we should keep doc issues in the public repo.

**Comment by superkhau** [comment]
Sounds good, I didn't know example refactors fall under doc issues so I assumed it was in the wrong repo.

**Comment by crandmck** [comment]
np -- if  https://github.com/strongloop/loopback-example-remote were included in the scrum-loopback Waffle board, then I would create the issue there.  But it isn't, and not sure if Chanda would want to add it.

**Comment by superkhau** [comment]
@chandadharap ^

**Comment by Amir-61** [comment]
Hey @crandmck,

Could you please clarify that by `make it consistent with other examples.` you mean I should follow your instructions at [here](https://github.com/strongloop-internal/scrum-loopback/issues/495)

Thanks!

**Comment by crandmck** [comment]
@Amir-61 Yes, that is correct.
