### ISSUE TITLE
Long running boot scripts may break the sequence of mounting middleware.

### ISSUE THREAD

**Issue by ih2502mk** [strongloop/loopback#1016]
Just pointing this out here in case someone encounters similar issue.

In a `server.js` file, that normally gets generated by `slc loopback` there is a set of middleware mounted on the app like this:
```javascript
app.use(loopback.favicon());
app.use(loopback.compress());

boot(app, __dirname); 

app.use(loopback.urlNotFound());
app.use(loopback.errorHandler());

app.start = function() {
  return app.listen(function() {
    app.emit('started');
    console.log('Web server listening at: %s', app.get('url'));    
  });
};

if (require.main === module) {
  app.start();
}
```
The problem that I've encountered happens when I have some long running asynchronous boot script in my `./boot` directory. The actual reason I believe is my boot script `process.nextTick()`ing its callback. I'm not using `process.nextTick()` directly but some module that I use — does. 

What happens is while `boot()` function is doing its thing `server.js` goes on further and mounts `loopback.urlNotFound()` and `loopback.errorHandler()` prior to mounting whatever else should get mounted in other boot scripts.

`boot()` function accepts a callback and also makes `app` emit `'booted'` event reliably once boot scripts finish. One of the solutions is to use `'booted'` event on the `app` object like this:

```javascript
app.use(loopback.favicon());
app.use(loopback.compress());

boot(app, __dirname); 

app.once('booted', function() {

  app.use(loopback.urlNotFound());
  app.use(loopback.errorHandler());

  app.start = function() {
    return app.listen(function() {
      app.emit('started');
      console.log('Web server listening at: %s', app.get('url'));    
    });
  };

  if (require.main === module) {
    app.start();
  }
})
```

**Comment by raymondfeng** [comment]
If you have async boot scripts, `boot(app, __dirname, function(err) {...});` should be used to wrap the rest. 

@bajtos Have we updated the generator-loopback to scaffold server.js?

**Comment by superkhau** [comment]
@raymondfeng not yet, that one is on my list

**Comment by superkhau** [comment]
@ih2502mk There is an example of the async boot script @raymondfeng mentioned here: https://github.com/strongloop/loopback-example-app-logic/blob/master/examples/async-boot-script/server.js#L16-L23

**Comment by ih2502mk** [comment]
Yes, actually doing the rest in callback is apparently better because `app.once('booted', ...)` may execute later than the `'booted'` event emits.

**Comment by bajtos** [comment]
See https://github.com/strongloop/loopback-workspace/issues/170 and the related pull requests, most notably https://github.com/strongloop/loopback-workspace/pull/172.

**Comment by bajtos** [comment]
Also note that the new template registers middleware via `middleware.json` using phases.

Another solution (workaround) is to rewrite your code to use phases too:

```js
boot(app, __dirname); 

app.middleware('final', loopback.urlNotFound());
app.middleware('final:after', loopback.errorHandler());
```

**Comment by raymondfeng** [comment]
I'm closing the issue based on the solutions proposed.
