### ISSUE TITLE
Setting idInjection:true and a property with id:true?

### ISSUE THREAD

**Issue by Metux-ClicRDV** [strongloop/loopback#1017]
Hey there! 

Here is what I would like to achieve and what i am struggling with to find a way to do it:

I  have a model in which I create a randomized unique "uid" property (with hat).
``` uid: {type: String, id: true}```
I would like also the model to generate an id (_id) with the mongoDb connector thanks to 
``` idInjection: true ```

Now I can GET any newly created instances using their uid as the id (which is the _id in mongoDB), but I have lost the uid property in the saved object.
Even if the API responses to queries with the uid property(which is good) , I also need it in my document.

Is it possible to keep the "uid" as a property in the document, doing get queuries with it from the explorer API, and at the same time generate a new _id?

Thanks !!

**Comment by raymondfeng** [comment]
The mongodb connector maps ‘id’ to ‘_id’ (and that’s why you saw the mongodb documents with _id). You should use ‘uid’ for your code in LoopBack.

We also plan to allow custom mapping of LoopBack model properties to mongodb fields in the future.

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by Metux-ClicRDV** [comment]
Thanks @raymondfeng , do you have any roadmap where I can check this feature?
