### ISSUE TITLE
Add connect-flash to loopback app

### ISSUE THREAD

**Issue by britztopher** [strongloop/loopback#1019]
Right now there is no express middleware to handle flash messages. It would be nice to add connect-flash to express app.  I found this issue out while using `loopback-component-passport`, and couldnt figure out why the `failureRedirect` kept being called.  The providers.json allows for failureFlash, however, when set to true I get an error from express stating that no 'flash' method is available, and looking through passport-configurator and server-app.js in loopback I have found no flash middleware.  I have this already implemented this in my own application, and if this is what the group wants,  I can issue a PR.

**Comment by raymondfeng** [comment]
@britztopher It probably doesn't belong to `loopback`. Maybe `loopback-component-passport`?

**Comment by britztopher** [comment]
@raymondfeng There is no connect-flash in either loopback-component-passport or loopback.  Like I said, I had to add it then require it.

**Comment by raymondfeng** [comment]
I understand. I was wondering if the dependency of `connect-flash` could be added to `loopback-component-passport` instead of `loopback`.

**Comment by britztopher** [comment]
@raymondfeng Yeah, it really depends, do we want to have just flash messaging in passport, or do we want to be able to use it throughout all express.  I find flash messaging very useful, but some may find it just as more noise.  It can be added to either.

**Comment by britztopher** [comment]
Any more thoughts on this.  If not I am going to add this to loopback project and submit a PR.

**Comment by raymondfeng** [comment]
Please submit a PR to loopback-component-passport and make it a `optionalDependency`.
