### ISSUE TITLE
RethinkDB Connector

### ISSUE THREAD

**Issue by zephyr4434** [strongloop/loopback#1021]
Are there plans for adding a connector to RethinkDB?

**Comment by AvivLander** [comment]
@zephyr4434, check this out: https://github.com/fuwaneko/jugglingdb-rethink 

With version two of Loopback, there is currently an issue with parsing when an Int type comes back as NaN. I mentioned it in a previous issue: https://github.com/strongloop/loopback/issues/1023

**Comment by wallace** [comment]
Does http://thinky.io/ work?

**Comment by listepo** [comment]
+1

**Comment by listepo** [comment]
on when this feature is planned?

**Comment by raymondfeng** [comment]
The author of https://github.com/fuwaneko/jugglingdb-rethink has the following disclaimer. 

> Attention! JugglingDB is awfully maintained. I fix bugs and update this adapter for newer RethinkDB versions if requested, but I suggest you to use other ORM for Node. If you know good one which does not have RethinkDB support yet -- let me know.

The module is mostly compatible with LB. Can some of you reach out to @fuwaneko? Maybe he can port it to LB.

**Comment by fuwaneko** [comment]
@raymondfeng Sure I can :)

**Comment by raymondfeng** [comment]
@fuwaneko That's great! See https://github.com/strongloop/loopback/issues/1023#issuecomment-75265962. I look forward to a fully functional rethinkdb connector for LB.

**Comment by listepo** [comment]
+1

**Comment by bajtos** [comment]
Closing as a duplicate of https://github.com/strongloop/loopback/issues/957
