### ISSUE TITLE
lb-ng cli command continuously generates lb-sevices.js

### ISSUE THREAD

**Issue by brillout** [strongloop/loopback#1026]
The cli command is `lb-ng server/server.js client/generated/lb-services.js`.

It is expected that the node process generates `lb-services.js` once to then terminate itself.

Instead the node process generates `lb-services.js` over and over again and does not terminate.

```
~/code/review-sys slc -v
strongloop v2.10.1 (node v1.0.0-pre)
├── strong-arc@1.0.3 (0fbac2c)
├── strong-build@1.0.2 (b698551)
├─┬ strong-supervisor@1.3.0 (85c2a79)
│ └── strong-agent@1.2.1
├── node-inspector@0.7.4
├── strong-deploy@1.1.1 (dba6165)
├── strong-pm@1.5.1 (2a9b727)
├── strong-registry@1.1.3 (3138d24)
├── nodefly-register@0.3.3
└── generator-loopback@1.7.0 (f72c607)
```

**Comment by superkhau** [comment]
I can't reproduce this. Can you post some steps to reproduce?

**Comment by brillout** [comment]
My bad; I made `lb-ng` execute at server start and because `lb-ng` starts the server it results in an infinite loop.

Checking `require.main.exports.loopback` before executing `lb-ng` avoids the infinite loop.
