### ISSUE TITLE
Register global beforeRemote hook?

### ISSUE THREAD

**Issue by aymeba** [strongloop/loopback#1027]
Hi,
i'm trying to register a hook 'beforeRemote' globally valid for all model and actions. Registering hook global : 

```javascript
loopback.Model.beforeRemote('**', function(ctx, model, next) {
				console.log('Executing:', this);
				next();
			});
```

But my remote hook is never called.

**Comment by aymeba** [comment]
Solved.

I've created a hook to iterate all models and add a remote Hook.

**Comment by clarkorz** [comment]
check this line: 
https://github.com/strongloop/loopback/blob/master/lib/application.js#L295
