### ISSUE TITLE
Overriding remote method metadata

### ISSUE THREAD

**Issue by dossorio** [strongloop/loopback#1028]
Hello !

I am overriding built in user remote method login successfully, but I can't override its metadata. 

I have tried with:

``` javascript
User.disableRemoteMethod('login', true);
```

without success.

In my user.js file:

``` javascript
User.login = function (req, next) {
  //do stuff
};
User.remoteMethod(
'login',
  {
    accepts: [{arg: 'req', type: 'object', required: true, http: {source: 'req'}}],
    returns: [{arg: 'token', type: 'object'}],
    http: {path: '/login', verb: 'post'}
  }
);
```

Debugging **User.sharedClass._methods** I have both definitions, the built-in and my metadata, this causes an undesirable behaviour and the custom remote method login is called following built-in metadata.

Is there any way to do this ?

Thanks!

**Comment by dossorio** [comment]
This behaviour causes that explorer shows both endpoints definitions, so you see inside /users, /confirm and /login (These are the endpoints I wanted to overwrite) shown twice.

I have added this function to my user.js as a workaround:
```javascript
  function overwriteRemoteMethod(name, options, fn) {
    if (options.isStatic === undefined) {
      options.isStatic = true;
    }
    var sharedMethod = new SharedMethod(fn, name, User.sharedClass, options);

    for (var i = 0; i < User.sharedClass._methods.length; i++) {
      var method = User.sharedClass._methods[i];

      if (method.name === name) {
        User.sharedClass._methods[i] = sharedMethod;
      }
    }
  }
```
and instead adding the remoteMethod via:
```javascript
User.remoteMethod(
'login',
  {
    accepts: [{arg: 'req', type: 'object', required: true, http: {source: 'req'}}],
    returns: [{arg: 'token', type: 'object'}],
    http: {path: '/login', verb: 'post'}
  }
);
```
I do:
```javascript
overwriteRemoteMethod(
'login',
  {
    accepts: [{arg: 'req', type: 'object', required: true, http: {source: 'req'}}],
    returns: [{arg: 'token', type: 'object'}],
    http: {path: '/login', verb: 'post'}
  }
);
```

I hope it helps.

Thanks !

**Comment by EthraZa** [comment]
var sharedMethod = new SharedMethod(fn, name, User.sharedClass, options);
		                       ^
ReferenceError: SharedMethod is not defined

It's not working anymore?
I too want to override the deleteById endpoint with my own.

**Comment by gkTim** [comment]
The method from @dossorio is working great (Thanks for that workaround).

@EthraZa to avoid the reference error you must include the SharedMethod into your model.
SharedMethod is part of the 'strong-remoting' module.

In my case I was able to do it with:

``` javascript
var SharedMethod = require('../../node_modules/strong-remoting/lib/shared-method');
```

**Comment by superkhau** [comment]
Connect to #443 because it looks related

**Comment by deepakrkris** [comment]
timeboxed to 3 points

**Comment by bajtos** [comment]
IMO, we should be promoting/documenting the approach presented in https://github.com/strongloop/loopback/issues/1028#issuecomment-116134548 - the built-in method should be disabled, and a different new method should be mapped to the HTTP endpoint of the disabled built-in method.

The example in the issue description may break code that's expecting certain signatures of built-in model methods.

```js
User.login = function (req, next) {
  //do stuff
};

// somewhere in a component, or even inside LoopBack
User.login({ email, password }, { include: ['user'] }, function(err, result) {
  // boom, this won't work
});
```
