### ISSUE TITLE
Create tagged releases for Getting Started part 2

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1029]
Initially, we need at least one tagged release for loopback-getting-started-intermediate. It should include everything EXCEPT `client/js/services/lb-services.js`, because the tutorial walks them through creating this file (see http://docs.strongloop.com/display/LB/Create+AngularJS+client).

**Comment by superkhau** [comment]
Before finalizing, we can just link to specific SHA's instead of creating tags. I will do that once we decide on that the steps are.

**Comment by crandmck** [comment]
At this point, I only have the one step that needs a release.

@altsang Do you want us to have tags for each step of GS2, as we did for part 1?  Currently, the tutorial _doesn't_ have the text like:

>If you followed the previous steps in the tutorial, go to xxxx.
>If you're just jumping in, follow the steps below to catch up...

Let us know if you want us to add that.

**Comment by crandmck** [comment]
Per Al, we want to have tags at each of the following points:
1. After creating the data sources - result of following  http://docs.strongloop.com/display/LB/Create+new+data+source
1. After creating new models - result of http://docs.strongloop.com/display/LB/Create+new+models
1. After defining relations - result of http://docs.strongloop.com/display/LB/Define+model+relations
1. After defining ACLs - result of http://docs.strongloop.com/display/LB/Define+access+controls
1. After defining remote hook - result of http://docs.strongloop.com/display/LB/Define+a+remote+hook
1. The last tag is all the above plus the Angular client stuff EXCEPT for `lb-services.js` which the reader should generate themselves as part of following http://docs.strongloop.com/display/LB/Create+AngularJS+client

Let me know if you have questions.

**Comment by superkhau** [comment]
I ran through GS2 and it's mostly good. I fixed a few typos, but there is major change required. We need to add a step to copy the updated boot script to insert additional sample data (ie. `/server/boot/sample-data.js`).

**Comment by superkhau** [comment]
@cranmck Please review.

**Comment by crandmck** [comment]
In GS1, the boot script to create db tables and add data is `server/boot/create-sample-models.js` (https://github.com/strongloop/loopback-getting-started/blob/master/server/boot/create-sample-models.js) 
But in GS2, it's called `server/boot/sample-models.js`  (https://github.com/strongloop/loopback-getting-started-intermediate/blob/master/server/boot/sample-models.js).

They should have the same name.  Please rename the one in GS2 to `create-sample-models.js`.

In `review.json` "accessType" should be "EXECUTE" for the ACL entry to allow authenticated users to write to the create property per https://github.com/strongloop/generator-loopback/issues/79

So the entry should look like
````
{
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": "create"
    },
```

**Comment by superkhau** [comment]
@crandmck Done. See https://github.com/strongloop/loopback-getting-started-intermediate/commit/a5a59c8a9ae2c9480110919d214f0fa1fe9bccf3#diff-3bdc4a9c11a151bf268bc3b59bf6ec1eR1

Please review again.

**Comment by crandmck** [comment]
Looks good.  Closing.
