### ISSUE TITLE
Improve Dynamic Remoting Docs

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1030]
Below is an example that is becoming a common use case... We should document this and add examples to the [loopback-example-remote](https://github.com/strongloop/loopback-example-remote) project.

What I think we should highlight:

 - How to create a client with a dynamic url / config 
 - **...and or...** How to correctly configure dynamic datasources
 - Making authenticated requests
 - Modifying the request before it is sent

/cc @crandmck @bajtos @rmg @superkhau 

```js
function createClient(url) {
  var client = loopback();
  boot(client, {
    modelSources: ['my-model-directory']
  });

  var ds = client.dataSource('myserver', {
    url: url
  });

  ds.connector.remotes.before('**', function(ctx, next) {
    ctx.req.headers.Authorization = ADMIN_ACCESS_TOKEN;
    next();
  });

  client.models.Store.destroyAll();
}
```
@bajtos feel free to edit the example if you have ideas on improving it...

**Comment by rmg** [comment]
Is your `Authorization` header example for sending credentials? That will work for Basic auth and Bearer auth, but not Digest.

**Comment by pulkitsinghal** [comment]
@rmg will it work for session token that has already been issued for a user who logged in?

**Comment by rmg** [comment]
@pulkitsinghal That depends on the backend and actual contents of `ADMIN_ACCESS_TOKEN`. I don't know the full background of this issue/proposal (I was probably mentioned because I recently landed #1015 and strongloop/strong-remoting#163).

LoopBack will accept a plain token in the `Authorization` header, but that's not really part of the HTTP spec as far as I know, which specifies a `$scheme $credentials` format for "real" HTTP authentication. In that case, though, you can do `ctx.req.headers['X-Access-Token'] = ADMIN_ACCESS_TOKEN;` instead.

**Comment by bajtos** [comment]
The datasource config is IMO missing a connector property.

Ad Authorization - is there a way how to configure the authorization via datasource config, instead of a beforeRemote hook? It may turn out to be not viable, so treat this just like an idea to consider.

**Comment by bajtos** [comment]
> How to correctly configure dynamic datasources

This can be achieved via `datasources.local.js`.

```js
// datasources.json
{
  myserver: {
    connector: 'remote'
  }
}

// datasource.local.js
module.exports = {
  myserver: {
    url: /* dynamically computed value */
  }
};
```

**Comment by rmg** [comment]
Authorization can be set in the URL if the backend supports Basic auth. If the backend is loopback, the next release of loopback will support using access tokens via Basic auth if your URL looks like `http://token:YOUR_TOKEN_HERE@backend-server/api`. That would allow the credentials to be set without using a hook, but would require the URL to be reconfigured any time the credentials changed (such as when the access token expires).

**Comment by ritch** [comment]
> This can be achieved via datasources.local.js.

@bajtos I still consider this static. The use case that keeps coming up is the ability to dynamically create a client that points at a given URL.

**Comment by bajtos** [comment]
Note that the current implementation does not allow you to have multiple instances of the isomorphic client (multiple loopback apps), because all apps share the same set of models and each model can be attached to a single datasource only. When you create the second client with a new URL, it will reconfigure models used by the first client to use this new URL too.

This is the old "singleton model registry" pain point discussed for example in #313.

Assuming the problem above is fixed, we can extend loopback-boot to allow developers to pass a set of config overrides in the options passed to `boot()`. Example:

```js
// client.js
function createClient(url) {
  var client = loopback();
  boot(client, {
    extraConfig: {
      dataSources: {
        myserver: { url: url }
      }
    }
  });

  // etc.
}

// datasource.json
{
  myserver: {
    connector: "remote"
  }
}
```

**Comment by pulkitsinghal** [comment]
@ritch @crandmck - are the docs for setting up the client side ... part of the strong-remoting README or somewhere else?

**Comment by bajtos** [comment]
> Note that the current implementation does not allow you to have multiple instances of the isomorphic client (multiple loopback apps), because all apps share the same set of models and each model can be attached to a single datasource only. When you create the second client with a new URL, it will reconfigure models used by the first client to use this new URL too.

This should have been fixed by https://github.com/strongloop/loopback/pull/1212.

**Comment by pulkitsinghal** [comment]
@bajtos and @ritch  - if I replace

```
var app = module.exports = loopback();

// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname);
```

with this instead:

```
function createClient(url) {
  var client = loopback();
  boot(client, {
    modelSources: ['my-model-directory']
  });

  var ds = client.dataSource('myserver', {
    url: url
  });

  ds.connector.remotes.before('**', function(ctx, next) {
    ctx.req.headers.Authorization = ADMIN_ACCESS_TOKEN;
    next();
  });

  client.models.Store.destroyAll();
}
```

will it just work? or is this pseudo code?

**Comment by ritch** [comment]
This:

```js
  ds.connector.remotes.before('**', function(ctx, next) {
    ctx.req.headers.Authorization = ADMIN_ACCESS_TOKEN;
    next();
  });
```

Is legace from a proposal. You can set your auth using the [auth](http://apidocs.strongloop.com/strong-remoting/#remoteobjects) object.

```js
ds.connector.remotes.auth = {bearer: new Buffer(MY_ACCESS_TOKEN).toString('base64')}
```

**Comment by pulkitsinghal** [comment]
I gathered that from the super-useful example, thanks! but what about
configuring a dynamic URL?

**Comment by ritch** [comment]
> will it just work? or is this pseudo code?

It is really just illustrative. Like I mentioned the `Authorization` part should be done a bit differently.

**Comment by ritch** [comment]
Here's an example setting dynamic URLs:

https://github.com/strongloop/strong-mesh-client/blob/master/proxy/boot/load-balancer.js#L48

**Comment by pulkitsinghal** [comment]
i really just want to set it up once during startup dev/staging/prod

**Comment by ritch** [comment]
> i really just want to set it up once during startup dev/staging/prod

You can use a `datasources.*.js` file for this and specify the url in the data source definition.

http://docs.strongloop.com/display/LB/Environment-specific+configuration#Environment-specificconfiguration-Datasourceconfiguration

For each file you would have something very close to this:

```json
{
  "remote": {
    "connector": "remote",
    "url": "http://...URL...HERE..."
  }
}
```

**Comment by pulkitsinghal** [comment]
@ritch I also have worker processes that are brought up and torn down so the need to configure their clients based on the `loopbackServerUrl` passed in as payload.

**Comment by pulkitsinghal** [comment]
It is mandatory to copy/paste this in my client?
`appRootDir: path.join(path.dirname(require.resolve('strong-nginx-controller')))`
I'm not sure what role if any `strong-nginx-controller` plays for my client. @ritch

**Comment by ritch** [comment]
No don't use that part. You can copy "boot()" from server.js.

**Comment by pulkitsinghal** [comment]
So looking at https://github.com/strongloop/strong-mesh-client/blob/master/proxy/server.js#L17 .. .yo uwant me to copy the entire folder: https://github.com/strongloop/strong-mesh-client/tree/master/proxy/boot

Right?

**Comment by bajtos** [comment]
Hello, as part of our triage process, I am closing issues that have been inactive for extended period of time. It also looks to me that the discussion has diverged quite a lot from the original issue description. Please open new issue(s) if there are still questions/problems to address.
