### ISSUE TITLE
Missing ID when POST Multiple models with custom hook

### ISSUE THREAD

**Issue by glesage** [strongloop/loopback#1031]
No idea how to name this issue properly ;P

Based on this thread: https://groups.google.com/forum/#!topic/loopbackjs/MjAND8jVFvc

The error can be reproduced using this repo: https://github.com/superkhau/zipcode (from @superkhau)

--> I have a custom hook for beforeCreate for a model which basically checks to see if an object with the same data already exists and return it if it does.

Here is the hook:

```
MyModel.beforeCreate = function(next, data)
{
        MyModel.findOne({where: {name: data.name}}, function(err, result)
        {
            if (err) return next(err);
            if (result) return next(null, result);
            return next();
        });
};
```

And when I POST a single model, the response is good: `{ "name": "my_name", "id": 1 }`

SOOO, when I POST 2 models that don't exist, the response is good: 
`[{ "name": "my_name_1", "id": 1 }, { "name": "my_name_2", "id": 2 }]`

BUT, when I POST 2 models that do exist, the response is:
`[{ "name": "my_name_3" }, { "name": "my_name_4" }]`

AND, when I POST 2 models with one that exists and the other does not, the response is:
`[{ "name": "my_name_4" }, { "name": "my_name_5", "id": 6 }]`

So, when I post multiple models, if the data exists I get NO ID but the others do... Let me know if I'm missing anything (:

I'm willing to attempt a fix but I have no clue where to look. Feel free to direct me to the various places of Loopback and I'll try to figure something out.

Thanks!

**Comment by glesage** [comment]
No one has any pointers?

**Comment by raymondfeng** [comment]
I found a bug in juggler. Will fix it.

**Comment by glesage** [comment]
oOo perfect thanks!

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback-datasource-juggler/issues/413
