### ISSUE TITLE
Boot corrupts session store object in middleware params

### ISSUE THREAD

**Issue by clarkorz** [strongloop/loopback#1032]
`express-session` middleware require a _Store_ instance in production env. Obviously it can't be config in `middleware.json`. So I want to take the advantage of **Environment-specific configuration**, which is config a _Store_ instance in `middleware.local.js`.

But the merging function seams break the _Store_ instance: it lose its prototype.

The workaround might be use `middleware.js` in the first place. But do you have a better solution?

**Comment by bajtos** [comment]
@clarkorz could you please provide steps for reproducing the problem on my machine? E.g. what is in your `middleware.local.js` file, what extra modules to install, etc.

**Comment by clarkorz** [comment]
@bajtos steps:

1. create a new loopback app and install modules
> $ slc loopback
> $ npm install express-session connect-redis

2. alter `server/middleware.json` (snippet)
```json
...
  "session": {
     "loopback#session": {
      "params": {
        "saveUninitialized": true,
        "resave": true,
        "secret": "keyboard cat"
      }
    }
  },
...
```

3. add `server/middleware.local.js`
```js
var session = require('express-session');
var RedisStore = require('connect-redis')(session);

module.exports = {
  "session": {
    "loopback#session": {
      "params": {
        "store": new RedisStore({ host: '127.0.0.1' })
      }
    }
  }
};
```

**Result**
```
/Developer/Projects/WebStormProjects/DemoProjects/LoopBackProjects/lb2100/node_modules/express-session/index.js:133
  store.on('disconnect', function(){ storeReady = false; });
        ^
TypeError: Object #<Object> has no method 'on'
    at session (/Developer/Projects/WebStormProjects/DemoProjects/LoopBackProjects/lb2100/node_modules/express-session/index.js:133:9)
    at EventEmitter.proto.middlewareFromConfig (/Developer/Projects/WebStormProjects/DemoProjects/LoopBackProjects/lb2100/node_modules/loopback/lib/server-app.js:67:25)
    at /Developer/Projects/WebStormProjects/DemoProjects/LoopBackProjects/lb2100/node_modules/loopback-boot/lib/executor.js:287:9
    at Array.forEach (native)
    at setupMiddleware (/Developer/Projects/WebStormProjects/DemoProjects/LoopBackProjects/lb2100/node_modules/loopback-boot/lib/executor.js:278:14)
    at execute (/Developer/Projects/WebStormProjects/DemoProjects/LoopBackProjects/lb2100/node_modules/loopback-boot/lib/executor.js:34:3)
    at bootLoopBackApp (/Developer/Projects/WebStormProjects/DemoProjects/LoopBackProjects/lb2100/node_modules/loopback-boot/index.js:129:3)
    at Object.<anonymous> (/Developer/Projects/WebStormProjects/DemoProjects/LoopBackProjects/lb2100/server/server.js:8:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by bajtos** [comment]
I managed to track the problem down to `resolveMiddlewareParams()` in `loopback-boot/lib/compiler.js`. My impression is that `cloneDeep(val)` preserves the methods like `store.on`, while `cloneDeep(val, transformFn)` does not.

I don't have time to investigate this further. Would you mind to take a look yourself and perhaps contribute a fix?

**Comment by bajtos** [comment]
Possible workaround: move the middleware configuration to a boot script.

```js
// server/boot/session.js
module.exports = function(app) {
  var session = require('express-session');
  var RedisStore = require('connect-redis')(session);
  var store = new RedisStore({ host: '127.0.0.1' });
  app.middleware('session', session({
    "store": store,
    "saveUninitialized": true,
    "resave": true,
    "secret": "keyboard cat"
  }));
}
```

**Comment by clarkorz** [comment]
@bajtos ok, I will continue base on your investigation

**Comment by kuskov** [comment]
Is it possible to set the store attribute to one datasources element? I am trying to save the sessions to the MongoDB database, that we provided in the datasources.json.

**Comment by gausie** [comment]
I've just done some testing and the functions seem tog et stripped on `buildMiddlewareInstructions()` at the line `var middlewareConfig = cloneDeep(config);`.

If you inspect the value either side of that you'll see that cloneDeep causing it even without a customizer (contrary to the findings by @bajtos). I'll look into alternative cloning strategies as a fix for this.
