### ISSUE TITLE
AWS DynamoDB Connector ?

### ISSUE THREAD

**Issue by docoder** [strongloop/loopback#1033]
I want to use AWS DynamoDB, so how I will get AWS DynamoDB Connector ?

**Comment by raymondfeng** [comment]
Do you want to give https://github.com/tmpaul/jugglingdb-dynamodb a try? I'm not the developer, but it probably requires minimal effort to get it working with LB.

**Comment by AvivLander** [comment]
@raymondfeng is right. Anything JugglingDB should be compatible or near compatible.

**Comment by marcellodesales** [comment]
Has anyone tried this? 

https://github.com/claylo/loopback-connector-dynamodb

We decided to use StrongLoop, but without DynamoDB we can't go to EC2

**Comment by simonguest** [comment]
Looking through the repo (https://github.com/claylo/loopback-connector-dynamodb), it appears to be an early/partial implementation. Supports creating objects, but no other methods at this time.

**Comment by dpurrington** [comment]
@raymondfeng can you explain what you mean by "give it a try?" Is it possible just to plug in the jugglingdb-dynamodb package directly? If so, I can't find the info I need to try that. Or does the code need to be ported to the loopback-connector-dynamodb package?

**Comment by alemhnan** [comment]
Any news on this or hints on this? They both (https://github.com/claylo/loopback-connector-dynamodb and https://github.com/claylo/loopback-connector-dynamodb) are not actively maintaned.
There are npm library actively maintained (https://github.com/victorquinn/dynasty), could a connector be built based on that?

**Comment by ahmed-abdulmoniem** [comment]
Any news on that guys?

**Comment by aggied** [comment]
Bump. Taking a cursory look at Loopback for potential use in an upcoming project, but the lack of a dynamoDB connector is causing me to take a pause.

**Comment by demsey2** [comment]
any update on this one

**Comment by aaronjhoffman** [comment]
Also interested in this, has anyone found a solution?

**Comment by demsey2** [comment]
can anyone from IBM confirm if there is a plan to include that

**Comment by fizzl** [comment]
Seeing how IBM is integrating LoopBack into their api connect solution, it seems unlikely that they are interested in DynamoDB integration.

So, I guess we are waiting for some individual to do it.

**Comment by pbrain19** [comment]
Ok guys looks like we will just have to use the one originally mentioned on top. According to the details I see it appears to be working.

**Comment by emtiazahmed** [comment]
Any progress on this? I want to go with loopback but without this connector it would be impossible.

**Comment by superkhau** [comment]
We do not have any current plans to support the connector on the roadmap.

Would any of you guys like to make a community connector? We could add it to strongloop-community like https://github.com/strongloop-community/loopback-connector-elastic-search (which is actively maintained by one of our community members @pulkitsinghal).

**Comment by mandarzope** [comment]
I have created [loopback-connector-dynamodb](https://github.com/mandarzope/loopback-connector-dynamodb)

Its was forked from [juggling-dynamo](https://github.com/tmpaul/jugglingdb-dynamodb) it is still in under progress.

We are using it in our production. It currently does not support String and Number sets. Support will be added in few days.
If someone wants to try it out then please try.
I am sure you will find few bugs. 

Thanks.
Mandar

**Comment by bajtos** [comment]
@mandarzope this is awesome! Would you mind adding a mention of your project to our "Community projects" section on loopback.io, see http://loopback.io/doc/en/community/How-to-add-a-project.html. Possibly to "Community connectors" section in https://loopback.io/doc/en/lb2/Community-connectors.html too.

@crandmck I think there is a bit of overlap between those two doc pages, is it perhaps worth either unifying them, or at least adding a link from "Community projects" to "Community connectors"?

I am closing this issue as done.

**Comment by crandmck** [comment]
> there is a bit of overlap between those two doc pages, is it perhaps worth either unifying them, or at least adding a link from "Community projects" to "Community connectors"?

I don't see any overlap , unless I'm misunderstanding.  "How to add a project" gives instructions on how to add a project to the [LoopBack community](http://loopback.io/doc/en/community/index.html) section in the docs, while "Community connectors" is just a list of some of the data source connectors developed by the LB community.

But adding a link from "Community projects" to "Community connectors" makes sense, so I'll do that.

**Comment by crandmck** [comment]
Added by https://github.com/strongloop/loopback.io/commit/1115f425c0f8af9d78173f4552050773a722af7c

**Comment by bajtos** [comment]
@crandmck thank you for adding the link, should we perhaps add it to the sidebar too?

Sorry for not being clear in my comment. What I meant is that the sidebar on http://loopback.io/doc/en/community/index.html lists a single community-maintained connector "Elasticsearch connector", which seems a bit random to me. What is the criteria used to decide which community connectors should be listed in the sidebar?

**Comment by crandmck** [comment]
Oh, I see.

Yes, you are correct that the [community projects](http://loopback.io/doc/en/community/index.html) listed are fairly random.  When I created the site, I just picked a few prominent ones. Frankly, I don't recall the rationale for adding the Elasticsearch connector.  

In general, the idea of this part of the site is to provide a place for open-source projects to promote themselves, so it's up to the project contributors to add their page as described in http://loopback.io/doc/en/community/How-to-add-a-project.html.  The ones I added are just examples.  I suppose I should post on the GG to get more people to add their projects... 

Anyway.... I could certainly duplicate http://loopback.io/doc/en/lb3/Community-connectors.html in the "community" area, but that not really a "project page" but rather a list of (some) connectors aimed more at someone who just wants to use them rather than as a promotion of the projects.

If you nevertheless think that would be worthwhile to include there, I don't have a big objection. LMK.

**Comment by bajtos** [comment]
On the second though, I think the current status is good enough, let's focus our energy on improving other things.

**Comment by SippieCup** [comment]
@mandarzope How do you querying a table that has both hash & sort key attributes by just the hash key using your connector in loopback.

I keep getting a PKMissingError for the model if I do not include a sort key.

**Comment by levantoanbkit** [comment]
We are a startup team, we are excited about LoopBack + DynamoDB to run on the AWS Elastic Beanstalk. @mandarzope Do you have a plan for distribution your loopback-connecter-dynamodb to popular developer? Can you share something about the detail information in README.md?
Thank you so much!

**Comment by SippieCup** [comment]
@levantoanbkit 

You might want to consider looking at my fork of the dynamodb connector at @UnisonoInc/loopback-connector-dynamodb. Unlike mamdarzope's, It has full composite key support to take advantage of dybamodbs performance benefits and is about ready for production.

**Comment by mandarzope** [comment]
@SippieCup 
thanks for developing dynamodb connector.  Unfortunately we couldn't develop it further.

@levantoanbkit 
From our experience with dynamodb, we choose to use DocumentClient from aws-sdk. It gave us better flexibility to execute dynamo queries. It's convenient and safe to use if there is no future migration from dynamodb to other database.

**Comment by levantoanbkit** [comment]
Thank you @SippieCup and @mandarzope so much! We will try to use your connectors and improve it when we detect a bug.

**Comment by SippieCup** [comment]
Hi Town,

It won't be hard as mine is not fully production ready at this time, please
list any issues you find and I'll get them fixed or just send me a pull
request.

@mandarzope: would you mind allowing me to take over the npm entry for
loopback-connector-dynamodb for my connector at this time?

**Comment by mandarzope** [comment]
@SippieCup 
Sure. You can take up loopback-connector-dynamodb

**Comment by SippieCup** [comment]
@mandarzope,

Great to here, thanks. When possible, please add my npm account - andrewsidhu - as an owner to the NPM package.

`npm owner add andrewsidhu loopback-connector-dynamodb`


Thanks once again for providing the framework for me to get started on it.

**Comment by duongNA** [comment]
@SippieCup
Your repository seems more complicated to mandarzope's repo.
There are a lot of new files and classes.
Does we have unit tests for those files and new functions?

**Comment by SippieCup** [comment]
@duongNA 

I have backported the test cases from our private repo to the public connector repo.

Keep in mind sharding still has a few issues when generating the table programatically, However if you generate the tables in dynamodb's CLI or on AWS console it works fine.

I will put together a readme for others to be able to easily adopt the new DAO and be able to use the DynamoDB connector.

Once again, it is not 100% ready for production but is in a position that it can easily be brought to that point.

**Comment by eduar2** [comment]
Is there any recent works on this?

**Comment by eduar2** [comment]
any works on this?

**Comment by johndpope** [comment]
@eduar2 - https://github.com/letsfullstack/loopback-connector-dynamodb

**Comment by SippieCup** [comment]
That's awesome to see!
