### ISSUE TITLE
loopback saves data, not defined on model

### ISSUE THREAD

**Issue by aantipov** [strongloop/loopback#1034]
Hi,
I use loopback version 2.10.2.
I have a model with a base "PersistedModel" and defined some properties on it.
In article [Validating model data] (http://docs.strongloop.com/display/public/LB/Validating+model+data) I've found this:
>If a client tries to save a product with extra properties (for example, description), those properties are removed before the app saves the data in the model. 

But when I tried to save 'extra' data through api explorer, those data have been successfully saved in my MongoDB database.

Is it a bug?

**Comment by raymondfeng** [comment]
You can configure the `strict` mode. See http://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Top-levelproperties. By default, mongodb will take the extra properties.

**Comment by aantipov** [comment]
Thanks, @raymondfeng 
Shouldn't this mode to be a default one?
