### ISSUE TITLE
Document using "this" instead of "data" args in beforeValidate model hook

### ISSUE THREAD

**Issue by aantipov** [strongloop/loopback#1036]
Hi,
I use loopback version 2.10.2.
I have a model with a base "PersistedModel" and defined some properties on it.
```
{
  "name": "Hike",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "title": {
      "type": "string",
      "required": true
    },
    "desc": {
      "type": "string"
    },
    "created": {
      "type": "date",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "author": {
      "type": "belongsTo",
      "model": "Account",
      "foreignKey": "authorId"
    }
  },
  "acls": [],
  "methods": []
}
```
Note that property `created` is required.

Then in model hook I try to set `created` value before validation:
```
Hike.beforeValidate = function (next, data) {
    data.created = new Date();
    next();
  };
```
After this I try to save a new object without `created` property & get validation error:
```
{
  "error": {
    "name": "ValidationError",
    "status": 422,
    "message": "The `Hike` instance is not valid. Details: `created` can't be blank (value: undefined).",
    "statusCode": 422,
    "details": {
      "context": "Hike",
      "codes": {
        "created": [
          "presence"
        ]
      },
      "messages": {
        "created": [
          "can't be blank"
        ]
      }
    },
    "stack": "ValidationError: The `Hike` instance is not valid. Details: `created` can't be blank (value: undefined)..."
  }
}
```

Here is a screenshot from api explorer with a post operation http://take.ms/iQdeV

Why was my model not actually changed before validation?

**Comment by raymondfeng** [comment]
@superkhau Can you try to reproduce it?

**Comment by raymondfeng** [comment]
@aantipov You need to update `this` instead:

```js
Hike.beforeValidate = function (next, data) {
   // this is the model instance you are validating
    this.created = new Date();
    next();
  };
```

Please note data is original data object from the create().

**Comment by aantipov** [comment]
Thanks, @raymondfeng 
But what is the purpose of the data object then?

**Comment by superkhau** [comment]
@aantipov You can use the data object is the model instance you're about to create. You can do whatever you need to do before the validation happens in your case (ie. change a property, etc)

**Comment by aantipov** [comment]
@superkhau But we have found out above that changing a property of a `data` object do not change the model data that are eventually saved - changing `data` object really matters nothing.
@raymondfeng advised to change `this` object instead. 
Thus I'm confused about the purpose of `data` object.

**Comment by superkhau** [comment]
@aantipov I see what you mean now. That is a good question.

**Comment by raymondfeng** [comment]
There is some legacy code we inherited from [jugglingdb[(https://github.com/1602/jugglingdb). We are cleaning up over time. In some case, we have to introduce breaking changes.

**Comment by superkhau** [comment]
@raymondfeng Maybe we should document this up front and say the recommended way is to use "this" amd ignore the "data" args due to legacy reasons?

/cc @crandmck

**Comment by crandmck** [comment]
OK, rather than open a new issue, I'm just going to reopen this as a doc issue.  Will change title, lable, etc., accordingly.

**Comment by aantipov** [comment]
Hi, @raymondfeng , @superkhau 
I've just tried to change a `modelInstance` in `Account.beforeCreate` and it works fine:
```
Account.beforeCreate = function(next, modelInstance) {
    modelInstance.name = 'some-name';
    next();
};
```
So the questions emerged are:
- is this behavior a bug?
- should I use `this.name = 'some-name'` instead of `modelInstance.name = 'some-name'`
- if this hook initiates a call `next(null, someObject)` which data will be finally used in the method?

**Comment by ritch** [comment]
I would not use `data` (the second arg to the hook's "work" function). It isn't consistent in all the hooks. Eg. calling `save()` will give you the `inst.toObject()` version and create will give you `inst`.

You should always (@bajtos / @raymondfeng please correct me here) use `this`.

**Comment by crandmck** [comment]
I believe in the particular case of `beforeCreate` (above), one could use either `this` or `modelInstance` but I don't know if there is any advantage of one vs. the other.

@bajtos Pending confirmation, I will add a note to the docs.  If we can just say "always use `this` in model hooks," that would simplify things.

**Comment by superkhau** [comment]
^
I could also remove the "data/modelnstance" param out of the examples to make sure people don't get confused.

**Comment by bajtos** [comment]
Since we are going to deprecate these hooks in favour of https://github.com/strongloop/loopback-datasource-juggler/pull/403 in the near future, I don't think it's worth investing our time into investigating how exactly are the old hooks implemented and when to use `this` and when `data`.

I am proposing to fix the docs for this particular case only (`beforeValidate` hook).

**Comment by crandmck** [comment]
OK, I added a note to the [beforeValidate docs](http://docs.strongloop.com/display/LB/Model+hooks#Modelhooks-beforeValidate).  Is that sufficient?

**Comment by bajtos** [comment]
LGTM.
