### ISSUE TITLE
package.json gets corrupted when adding model 'Package'

### ISSUE THREAD

**Issue by jellekralt** [strongloop/loopback#1037]
Hi,

When adding a model with 'slc loopback:model Package', the package.json in the root folder gets corrupted. The generator basically tries to save the Package model in the package.json file in the root (which is understandable). 

```json
{
  "name": "Package",
  "plural": "Packages",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": [],
  "facetName": "common"
}
ack": "^2.8.0",
    "loopback-boot": "^2.4.0",
    "loopback-connector-mssql": "^1.3.0",
    "loopback-datasource-juggler": "^2.7.0",
    "serve-favicon": "^2.0.1",
    "strongloop": "^2.10.2"
  },
  "optionalDependencies": {
    "loopback-explorer": "^1.1.0"
  },
  "devDependencies": {
    "jshint": "^2.5.6"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "engines": {
    "node": "0.10.x"
  }
}
```

Is there a way to avoid this?

**Comment by raymondfeng** [comment]
This should have been fixed by https://github.com/strongloop/loopback-workspace/pull/183. Please upgrade strongloop using `npm uninstall -g strongloop; npm install -g strongloop`.
