### ISSUE TITLE
API documentation bug

### ISSUE THREAD

**Issue by aantipov** [strongloop/loopback#1041]
Hi
I found a bug with documentation of `PersistedModel.find` method here http://apidocs.strongloop.com/loopback/#persistedmodel-find & here http://docs.strongloop.com/display/public/LB/PersistedModel+class#persistedmodel-find
According to the docs the `PersistedModel.find` method should return some object, but it actually returns `undefined`.
It is an asynchronous method, so it can't return 'Array of model instances that match the filter; or Error'.
There are similar errors in other methods too, for example `http://apidocs.strongloop.com/loopback/#persistedmodel-findone`

**Comment by ritch** [comment]
@crandmck can you take a look?

**Comment by crandmck** [comment]
Yes, I believe @aantipov is correct.  We should remove the "Returns" sections and note instead that the returned-instances callback parameter will contain the array of matching instances (in the case of find).  I'll go through all the PersistedModel APIs to check for similar errors.

**Comment by crandmck** [comment]
This is addressed in the JSdoc comments in `PersistedModel.js` and `Model.js`.  The API docs will be updated the next time loopback is published to npm.
