### ISSUE TITLE
LoopBack - net::ERR_CONNECTION_REFUSED from LAN Network

### ISSUE THREAD

**Issue by b96705008** [strongloop/loopback#1042]
I have a problem. I just create a loopback project, and I add a client web page in client folder and socketio that listen with the server. 

I can connect to my server in loclhost, but I can't connect it from other LAN network ip source, 
like  GET http://192.168.1.119:3000/ net::ERR_CONNECTION_REFUSED

Is there any security issue that I neglect?

**Comment by ritch** [comment]
In your `server.js` file are you listening on all hosts? Do you not have this issue with express?

I'm guessing this is not a LoopBack issue... Please post some code to reproduce this. There are many factors outside of LoopBack that can cause this (eg. your computer / router / networks settings).

**Comment by ritch** [comment]
I'm closing this for now... If you have some repro steps (outside the context of your network) or code we can re-open.
