### ISSUE TITLE
AngularJS JavaScript SDK doesn't rightfully translates `filter`

### ISSUE THREAD

**Issue by brillout** [strongloop/loopback#1043]
I'm trying to retrieve filtered entries.

Following the example in http://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK

```
$scope.pen = Product.findOne({ 
  filter: { name: 'Pen' }
});
```

the SDK translates this to

`http://localhost:3000/api/product/findOne?filter=%7B%22name%22:%22Pen%22%7D`

and the backend replies results without the filter applied.

The following corresponding request URL works though

`http://localhost:3000/api/product/findOne?filter[where][name]=Pen`

**Comment by brillout** [comment]
the problem is the missing where clause and the following works;

```
$scope.pen = Product.findOne({ 
  filter: { where: { name: 'Pen' } }
});
```

It would be nice to have a consistent documentation:)

**Comment by brillout** [comment]
and I can't find a repository holding the docs.
Otherwise I'd submit a PR

**Comment by crandmck** [comment]
Thanks for catching this.  I updated the doc.  Please [take a quick look](http://docs.strongloop.com/display/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-Read(querying)) to be sure I got it correct.

For future reference, the docs are not on GitHub, but rather in a Confluence wiki.  We welcome community contributions.  See http://docs.strongloop.com/display/LB/Contributing+to+LoopBack+documentation

Thanks!

**Comment by brillout** [comment]
looks good :)
