### ISSUE TITLE
HEAD requests return invalid data

### ISSUE THREAD

**Issue by billinghamj** [strongloop/loopback#1045]
In the documentation & API explorer, the `HEAD` method is incorrectly described as a way to check for the existence of an object. In fact, it is actually meant to return exactly the same as a `GET` request does, but without the body.

The `Content-Length` and `Etag` headers return different values for GET & HEAD requests.

#### `HEAD`

```
$ curl -v -X HEAD /1/users/1
> HEAD /1/users/1 HTTP/1.1
> User-Agent: curl/7.37.1
> 
< HTTP/1.1 200 OK
< Date: Sun, 25 Jan 2015 09:25:54 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 15
< Etag: W/"f-ff3fd5b5"
< 
```

#### `GET`

```
$ curl -v -X GET /1/users/1
> GET /1/users/1 HTTP/1.1
> User-Agent: curl/7.37.1
> 
< HTTP/1.1 200 OK
< Date: Sun, 25 Jan 2015 09:26:02 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 125
< Etag: W/"7d-538934c6"
<
{"first_name":"James","last_name":"Billingham","mobile_number":"[redacted]","email_address":"[redacted]","id":1}
```

It is really important that `HEAD` requests return data matching `GET` requests - particularly in the case of the `Etag` header, which is a hash used for checking if caches are still up-to-date.

**Comment by raymondfeng** [comment]
http://stackoverflow.com/questions/3854842/content-length-header-with-head-requests/18925736#18925736

**Comment by raymondfeng** [comment]
`curl -X HEAD` doesn't behave as you expect. Please use `curl --head` or `curl -I` instead. 
See http://serverfault.com/questions/140149/difference-between-curl-i-and-curl-x-head

**Comment by billinghamj** [comment]
You could do the same thing in Telnet and it would exhibit the same issue. This is nothing to do with curl. You can read the exact request data it is sending to the server above.

And for reference, this is the result with the command you suggested:

```

$ curl -v --head /1/users/1
> HEAD /1/users/1 HTTP/1.1
> User-Agent: curl/7.37.1
> 
< HTTP/1.1 200 OK
< Date: Sat, 31 Jan 2015 18:26:47 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 15
< Etag: W/"f-ff3fd5b5"
< 
```

**Comment by billinghamj** [comment]
And with telnet:

```
$ telnet localhost 3000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
HEAD /1/users/1 HTTP/1.1

HTTP/1.1 200 OK
X-Powered-By: Express
Vary: Origin, Accept-Encoding
Access-Control-Allow-Credentials: true
Content-Type: application/json; charset=utf-8
Content-Length: 15
ETag: W/"f-ff3fd5b5"
Date: Sat, 31 Jan 2015 18:31:12 GMT
Connection: keep-alive
```

**Comment by billinghamj** [comment]
And having done a quick check, the length of 15 characters comes from this:

`{"exists":true}`

This bug is that `HEAD /resource` is not equivalent to `GET /resource/exists`.

**Comment by billinghamj** [comment]
@raymondfeng Please reopen this. It is a valid bug.
