### ISSUE TITLE
Request: add metadata to HEAD response headers

### ISSUE THREAD

**Issue by billinghamj** [strongloop/loopback#1046]
Hey,

It'd be good if `HEAD` requests allowed you to get more data about the resource you're pointing at.

More specifically, I'd like to be able to see the instance count. e.g. `Collection-Length: 1000`

This would also allow for eventual deprecation of the non-RESTful routes like `count`, `findOne`, etc. if you wanted to do that.

Thanks

**Comment by AvivLander** [comment]
+1
