### ISSUE TITLE
Model on(changed gives old data

### ISSUE THREAD

**Issue by psi-4ward** [strongloop/loopback#1050]
```javascript
app.models.Car.on('changed', console.log.bind(console));
```

When i create a new Car using the explorer i get
```javascript
{ color: 'blue', id: '1' } // correct
```

But when i PUT `{"color": "red"}` to `/api/Cars/1` the callback gets the old data:
```javascript
{ color: 'blue', id: '1' } // color should be red now
```

**Comment by superkhau** [comment]
Can you submit a PR to loopback-sandbox so I can try to reproduce it?

**Comment by psi-4ward** [comment]
Thanks for your answer, suprisingly i couldn't reproduce it using the sandbox or a new app.
After removing `node_modules` and a `npm cache clean && npm install` it works now.

**Comment by superkhau** [comment]
Cool, glad you got it working.
