### ISSUE TITLE
Default column for `ORDER BY ` in PersistedModel.find() is not reliable

### ISSUE THREAD

**Issue by ih2502mk** [strongloop/loopback#1051]
In my model definition `properties` look like this: 

``` javascript
{
  "name": "MyUsers",
  ... 
  "properties": {
    "uid" : {      
      "id": true,
      "mysql" : {
        "columnName": "USER_ID",        
      }
    },
    ...
  },
  ...
}
```

When I make a request to find all users like this `MyUsers.find({}, function(err, users) {})` the query builder inserts `ORDER BY` statement in sql request but the column that it will use for the example above will be `uid` not `USER_ID`. 

I only experienced this when using MySQL. Looks like this issue occurs in `MySQL.prototype.all` method https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/mysql.js#L550.

The workaround for now is to specify order filter when making a request like this `MyUsers.find({order : "USER_ID DESC"}, function(err, users) {})`.

**Comment by raymondfeng** [comment]
The filter.order is set to ['uid'] but it should be mapped to the column name by https://github.com/strongloop/loopback-connector-mysql/blob/master/lib/mysql.js#L520. Can you check if the mapping code is executed?

**Comment by ih2502mk** [comment]
Mapping code — you mean `order.map(...)`?

**Comment by raymondfeng** [comment]
Yes. 

I cannot reproduce your problem. A similar model with mysql column name works for me. The generated SQL is:
```
SQL: SELECT `USER_ID`, `email`, `createdAt`, `lastModifiedAt` FROM `Account` ORDER BY `USER_ID`
```

You can see the SQLs using `DEBUG=loopback:connector:mysql node .`

**Comment by ih2502mk** [comment]
I think the problem is actually in this part of `MySQL.prototype.all()` method: 
```javascript
//...
  if (!filter.order) {
    var idNames = this.idNames(model);
    if (idNames && idNames.length) {
      filter.order = idNames;
    }
  }
//...
```
There is no implementation of `this.idNames()` specific to mysql-connector, such that it would return the right column name. And that's why `filter.order` may end up assigned a wrong value (again only if you have different column name in `'mysql'` property of the property definition).
