### ISSUE TITLE
Configured for Amazon S3 storageService.getContainer() returns error

### ISSUE THREAD

**Issue by aantipov** [strongloop/loopback#1052]
Hey there!
I want to implement a remote method for uploading images to Amazon S3.
According to the article http://docs.strongloop.com/display/public/LB/Storage+service I defined amazon's credentials in `/server/datasources.json`.
Then in my model's code I am trying to implement a remote method:
```
Hike.uploadImage = uploadImage;
Hike.remoteMethod(
  'uploadImage',
  {
    description: 'Upload hike\'s image',
    http: {verb: 'post'},
    returns: {arg: 'data', type: 'Object', root: true}
  }
);

function uploadImage(next) {
  var s3 = Hike.app.datasources.s3.createModel('HikeFile');
  s3.getContainers(function (err, data) {
    err && next (err, {});
    next(null, data);
  });
}
```
At this stage this method only returns S3 buckets info & it works fine.
But if I replace `s3.getContainers()` call by s3.getContainer('myBucket`, fn), then this method return Error:
```
{
  "error": {
    "name": "InvalidRequest",
    "status": 400,
    "message": "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.",
    "code": "InvalidRequest",
    "time": "2015-01-27T07:59:28.751Z",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 30,
    "stack": "InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.\n    at Request.extractError ..."
  }
}
```
I've made some research & found out that this error is caused by my bucket region requirement to use AWS Signature Version 4 for authentication.
If I use aws-sdk for Node.js to make requests to Amazon S3 API then I need to specify `signatureVersion` parameter: `var s3 = new AWS.S3({signatureVersion: 'v4', region: 'eu-central-1'});`.

How can I circumvent the problem in LoopBack?

**Comment by ekussberg** [comment]
+1 i have the same error right now and can't do anything in the S3

**Comment by philippdhh** [comment]
Any news on this topic?

I've got the same problem and just opened a related issue here: https://github.com/strongloop/loopback-component-storage/issues/101

I hope this fix should be quite simple for a loopback guru, but unfortunately I don't know where and how to fix it yet. It really seems to be related with the signature version which should be set to v4...

This problem only occurs when using region Frankfurt and other new created aws regions. In old us and ireland regions the problem does not occur.

**Comment by ataraxus** [comment]
Same issue here, Frankfurt region: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256

**Comment by kgoedecke** [comment]
+1 from me for the frankfurt region.

**Comment by ataraxus** [comment]
@kgoedecke

**Comment by ataraxus** [comment]
@kgoedecke I've resolved it for myself, just try this: 

See here whats was the issue: aws/aws-sdk-js#829
for Frankfurt you have just to set the "correct" region:

 var publicHandler = new StorageService(
    {
      provider: 'amazon',
      region: "eu-central-1",
      keyId: "",
      key: ""
    });

https://github.com/strongloop/loopback-component-storage/issues/101#issuecomment-169002646

**Comment by gunjpan** [comment]
@aantipov : Looks like @ataraxus solution may have resolved the issue. Closing this for now. If you the case still persists for you, please shout out at myself in a comment and I'll reopen it. Thank you.

**Comment by jdforsythe** [comment]
@gunjpan This isn't really solved. It's only solved if your region doesn't require V4 and you set your region. Regions like `us-east-2` only support V4 and so this is still an issue for me

**Comment by gunjpan** [comment]
@jdforsythe : Hi, could you please open a new issue with detailed description of the problem you face, along with a reference to this issue.
