### ISSUE TITLE
iCars front end for investor pitches

### ISSUE THREAD

**Issue by altsang** [strongloop/loopback#1053]

**Comment by altsang** [comment]
I have a LB 2.x backend that shows the RDMBS schema for iCars in Oracle.  In my demo I'm creating an OracleDB data source and showing the discovery flow and the API create on the fly.

To round out the demo, I need to show the front end in an iPhone emulator.  Minimally it should show a map with the rental locations.  If I click on a rental location it should show the inventory.  The more functions that work - the better, but minimally I can get by with a map with rental locations and showing inventory for any location.

**Comment by superkhau** [comment]
@altsang Which iPhone emulator are you using?

**Comment by altsang** [comment]
I can run whatever is required to show it best. Way back when it was iPhone 5 emulator.  I think we should shoot for a iPhone 6 emulator just to look current.

**Comment by superkhau** [comment]
Sounds good.
