### ISSUE TITLE
Model doesn't inherit hooks defined on Mixin

### ISSUE THREAD

**Issue by brillout** [strongloop/loopback#1055]
I would expect a hook like `MixinModel.beforeUpdate` to be inherited

**Comment by pthieu** [comment]
@brillout: This might take a while for us to get to. To speed up the process, you can do one of two things:
 1. If you still require this, open a new issue using the `New issue` button and fill in the template provided to you
 2. Open a PR adding this functionality yourself and we will review and merge.

Will close this issue now as it's been over a year. Please use option `#1` if you still require this.
