### ISSUE TITLE
Possible bug: Model's type not honored by update()

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback#1058]
I'm using loopback@2.8.6 and I just noticed that calling the update method on a model in a boot script changes the id from number to string and persists it ... anyone else run across something like this before?

with create db.json:
```
"models": {
  "StoreConfigModel": {
      "1": "{\"objectId\":1,\"country\":\"US\"}"
  }
}
```

after update db.json:
```
"models": {
  "StoreConfigModel": {
      "1": "{\"objectId\":\"1\",\"country\":\"USA\"}"
  }
}
```

datasources:
```
"db": {
    "name": "db",
    "connector": "memory",
    "file": "db.json"
  }
```

model:
```
"properties": {
    "objectId": {
      "type": "number",
      "id": true,
      "generated": true
    }
 }
```

boot script:
```
UserModel.findOrCreateAsync(...)
.then(function(user){
  user.storeConfigModels.create(
    {"country": "US"},
    function(err, storeConfig){
      return StoreConfigModel.updateAsync(
        {objectId:Number(storeConfig.objectId)}, // where
        {"country": "USA"}// data
      );
    }
  );
});
```

**Comment by raymondfeng** [comment]
I couldn't reproduce the problem as follows:

1. Define a model:
```
 {
  "name": "note",
  "base": "PersistedModel",
  "properties": {
    "objectId": {
      "type": "number",
      "id": true,
      "generated": true
    },
    "title": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```
2. Go to the explorer, create a new note with title ‘t1'
db.json:
```
"note": {
      "1": "{\"objectId\":1,\"title\":\"t1\"}"
    }
```
3. Update note (id=1) with {title: 't2'}
db.json:
```
"note": {
      "1": "{\"objectId\":1,\"title\":\"t2\"}"
    }
```
db.json has the correct content before/after the update.

Please provide a working app to reproduce the problem.

**Comment by pulkitsinghal** [comment]
Ok I did my best to shrink wrap the dependencies and deleted all the proprietary source code ... it should be self-evident as the updated entry has a string instead of a number:

```
    "NoteModel": {
      "1": "{\"objectId\":\"1\",\"title\":\"blah\"}",
      "2": "{\"objectId\":2,\"title\":\"two\"}"
    }
```

Here's the repo: https://github.com/pulkitsinghal/loopback-issues-1058

**Comment by pulkitsinghal** [comment]
@raymondfeng - i don't see that fix in the master https://github.com/strongloop/loopback-datasource-juggler/commits/master branch ... should I just go ahead and get the branch you created and put into my package.json as the source? Also is there a doc page on what versions of juggler go hand in hand with what versions of loopback core?
