### ISSUE TITLE
Testing best practices / guide / docs

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1059]
We should provide some guidance on how to test loopback applications. `loopback-testing` is really not well designed or documented for external usage.

/cc @bajtos @crandmck

**Comment by jolafrite** [comment]
Hi
There is no +1 button on Github but I definitely would be interested by this feature
Is there a place where I can start to have a look ?

**Comment by OwenBrotherwood** [comment]
@crandmck I think this is important: Google Docs with use of r/w access and comments

**Comment by OwenBrotherwood** [comment]
@crandmck What about some short mention of tests in https://github.com/strongloop/loopback/blob/8d851e8b5f574a16ee480251b1d5b5fc2d989913/CONTRIBUTING.md

**Comment by crandmck** [comment]
@rmg what do you think?

**Comment by OwenBrotherwood** [comment]
(Yep: I noted it was @rmg that was last on the CONTRIBUTING.md: so I agree with anything he says .... almost)

**Comment by rmg** [comment]
As far as I can tell, this issue is about guidelines for testing loopback _applications_, not writing tests for loopback _contributions_.

@crandmck @OwenBrotherwood I'm not sure what you are asking for my opinion on.

**Comment by OwenBrotherwood** [comment]
@rmg : yep, I know
@crandmck fills in the details as to "why are we 'here' now"

**Comment by crandmck** [comment]
OK, I think the two issues of testing applications and testing contributions have gotten somewhat conflated here. 

@rmg you are right that this issue was for the former, and the above query seems to be about the latter.  Since I had nothing to do with `CONTRIBUTING.md`, I just punted it to you.  Perhaps it makes sense to suggest that any contributions to LoopBack have corresponding tests--I don't know.  That's the gist, and perhaps it does deserve a separate issue, but I will leave it to others if so.

**Comment by bajtos** [comment]
> We should provide some guidance on how to test loopback applications. loopback-testing is really not well designed or documented for external usage.

My two cents: developers should use `supertest` together with whatever testing framework they prefer (mocha, tap, etc.) If they find data-builders helpful, then they can use that part of loopback-testing too. For everything else, they should write their own helpers specific to the application they are developing.

**Comment by crandmck** [comment]
The `loopback-testing` repo has been removed.  If there is still a desire to cover testing best practices in docs, lets open a separate issue.
