### ISSUE TITLE
Document model "settings" property

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1060]
Example: https://github.com/strongloop/strong-scheduler/blob/master/lib/api-server/lb-models/executor-ext.js#L16-L22

@ritch Need more info and examples. What is this for?  Any other info would be helpful.

**Comment by ritch** [comment]
> What is this for?

This stores all the input passed to the juggler's model builder. It was the object used to define the model. Its a fairly complex object that contains definitions for relations and access controls... @raymondfeng should also chime in here.

**Comment by crandmck** [comment]
@raymondfeng Should we document the model settings?  Which (if any) of these settings are writeable?

**Comment by amenadiel** [comment]
at some parts of my app I must clone an existing model (let's say it's *Wasp*), modify its properties and attach it to the dataSource as a new model *Hornet*

```js
var existingmodel = app.models.Wasp;
var options= existingmodel.settings;
var properties = existingmodel.definition.properties;
var dataSource = existingmodel.getDatasource();
// I change the plural endpoint
options.plural = "Hornets";

// and add it to the datasource
dataSource.createModel("Hornet", properties, options);
```

I might be a lame example, but I'm using something very similar in an app.

**Comment by crandmck** [comment]
Thanks @amenadiel.  It's helpful for me to see a "real world" use case.

**Comment by ritch** [comment]
@amenadiel I'm not sure what you are talking about exactly. The code you have should be fine... but I'm not sure what it is reference to.
