### ISSUE TITLE
How to get Length of Relation Array?

### ISSUE THREAD

**Issue by benmarten** [strongloop/loopback#1064]
Hello, I am trying to get the length/count of the relation array, but it returns 2 which is not correct...

		Item.find({
			where: {
				userId: userId
			},
			include: 'orders'
		}, function(err, items) {
			var result = _.remove(items, function(item) {
				console.log(item.orders.length);  // 2
				console.log(typeof(item.orders)); // function
				if (item.orders.length > 0) {
					return false;
				} else {
					return true;
				}
			});
			return fn(err, result);
		});

not sure why the typ of the array containing the relation is of type function?

**Comment by raymondfeng** [comment]
You'll need to call item.toObject().orders.length.

**Comment by benmarten** [comment]
Perfect! Thanks :)
