### ISSUE TITLE
"Display" property for facebook auth provider doesn't work

### ISSUE THREAD

**Issue by aantipov** [strongloop/loopback#1068]
Hi
I try to implement a login via facebook in a modal window, so I should specify `display` option as `'popup'` (see https://github.com/jaredhanson/passport-facebook#display-mode)
I've specified config properties in `providers.json`:
```
"facebook-login": {
    "provider": "facebook",
    "module": "passport-facebook",
    "clientID": "***",
    "clientSecret": "***",
    "callbackURL": "http://localhost:3001/auth/facebook/callback",
    "authPath": "/auth/facebook",
    "callbackPath": "/auth/facebook/callback",
    "successRedirect": "http://localhost:3000",
    "scope": ["email"],
    "display": "popup"
  }
```
All works fine but the specified `display` property doesn't applied.
Is it a bug or I do something wrong?

**Comment by raymondfeng** [comment]
Which version of `loopback-component-passport` do you have?

**Comment by aantipov** [comment]
1.1.2

**Comment by raymondfeng** [comment]
Can you try the following?
```json
"facebook-login": {
    "provider": "facebook",
    "module": "passport-facebook",
    "clientID": "***",
    "clientSecret": "***",
    "callbackURL": "http://localhost:3001/auth/facebook/callback",
    "authPath": "/auth/facebook",
    "callbackPath": "/auth/facebook/callback",
    "successRedirect": "http://localhost:3000",
    "scope": ["email"],
    "authOptions": {"display": "popup"}
  }
```

**Comment by aantipov** [comment]
@raymondfeng Thanks, it helped! Now that works fine!
It should be documented somewhere

**Comment by crandmck** [comment]
@raymondfeng I added authOptions to http://docs.strongloop.com/display/LB/Configuring+providers.json#Configuringproviders.json-OAuth2, but I need a general description and list of all the supported properties of `authOptions `-- is there anything other than `display` ?

**Comment by raymondfeng** [comment]
`authOptions` is specific to each passport provider's implementation. For example, the passport-facebook supports the following options in `authenticate` method:

https://github.com/jaredhanson/passport-facebook#display-mode
https://github.com/jaredhanson/passport-facebook#extended-permissions

**Comment by crandmck** [comment]
OK, I added a note to http://docs.strongloop.com/display/LB/Configuring+providers.json#Configuringproviders.json-OAuth2 Closing.  @raymondfeng you can review if you wish.
