### ISSUE TITLE
Document `Model.settings`

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1069]
We need to document the base `settings` object. Use this syntax:

```txt
 * @property {Object} settings ...
 * @property {Array} settings.acls ...
```

**Comment by crandmck** [comment]
The following models have settings:

Base Model - modelClass.settings.acls - array of ACLs

[Change](https://github.com/strongloop/loopback/blob/master/common/models/change.js)
 - `hashAlgorithm` : crypto.createHash default is sha1
 - `ignoreErrors`:  if true then when changes are rectified, will throw unless it is true.

[ACL](https://github.com/strongloop/loopback/blob/master/common/models/acl.js)
 - `defaultPermission` by default is ALLOW - Set to DENY to shut down all API perms 

[Access Token](https://github.com/strongloop/loopback/blob/master/common/models/access-token.js)
 - `accessTokenIdLength` - How long you want the access token to be - by default is 64.  A set of bytes encoded as a base64 string.  This is the length of the base64 string.

**Comment by crandmck** [comment]
@ritch I added docs in the above commit.  PTAL, or close if you prefer.

**Comment by ritch** [comment]
Looks good...
