### ISSUE TITLE
I'm able to get another user data (not $owner)

### ISSUE THREAD

**Issue by droig** [strongloop/loopback#1074]
Is this normal?

#### How to reproduce
The app I'm testing uses angular SDK to generate client $resource.

1. Login with user which has ID = 2
2. With using $resource from lbServices do the following request:
```javascript
User.findOne({id = 2});
//this get first user no matter if is $owner
```
```javascript
User.findOne({id = 2, filter: { id:1 } });
//this successfully get user with ID = 1 which clearly is not $owner

**Comment by raymondfeng** [comment]
At the moment, ACLs checks the permission before invoking an API. It doesn’t aggressively inspect the results. You should use a afterRemote hook to enforce it.

See: http://docs.strongloop.com/display/LB/Remote+hooks <http://docs.strongloop.com/display/LB/Remote+hooks>

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by clarkorz** [comment]
@raymondfeng I think @droig 's code snippet is calling angular sdk api, not server side.

@droig `findOne` is a static method, and `$owner` protects only instance methods. `findOne` method is **DENY** by default, do you customize acls of user model? And please check that you have enabled authentication in `server/boot/authentication.js`.

**Comment by 0candy** [comment]
@droig Did the above comment resolve your issue?

**Comment by loay** [comment]
Hello,
Closing this issue.  If you are still running into problems, feel free to leave a comment and I will reopen the issue.
