### ISSUE TITLE
Creating model without sudo clears package.json

### ISSUE THREAD

**Issue by inawlaljar** [strongloop/loopback#1075]
Hi, 

I created a loopback app using sudo. So now every time I want to add new model (say) to it, Terminal in my mac forces me to run the command with "sudo". 
If I don't run the command (slc loopback:model) with sudo (by mistake), I have noticed that loopback cls fails (permission denied) but it also wipes out package.json, config.json, and model-config.json clean.

May like to check. 

Thanks,
Raj

**Comment by OwenBrotherwood** [comment]
https://github.com/strongloop/loopback/issues/1061#issuecomment-75981938
"not bug"?

**Comment by gunjpan** [comment]
This looks like a permission issue with the machine. 
closing this now. if the problem still persists, please feel free to leave a comment with my GH handle and I'll reopen it.
