### ISSUE TITLE
hasAndBelongsToMany related array has only "null" entry when limiting fields

### ISSUE THREAD

**Issue by technicallyfeasible** [strongloop/loopback#1076]
I have a model which is related to another model (countries) through hasAndBelongsToMany. When I do a filter with include like this
{
    "include": [{
        "relation": "countries",
        "scope": {
            "fields": ["name"]
        }
    }]
}

then in my response I get something like this
    "countries": [
      null
    ]

and without the scope
    "countries": [
      {
        "name": "Argentina",
        "id": "54d11335123c16580c55e0c8",
        "continentId": "54d11333123c16580c55e0c7"
      }
    ]

**Comment by raymondfeng** [comment]
Please create a test project on github to reproduce the issue per https://github.com/strongloop/loopback/wiki/Issues.

**Comment by technicallyfeasible** [comment]
I created a test repository as described in the link:
https://github.com/technicallyfeasible/loopback-sandbox

Just start it and use the explorer __get__Companies with the following filter:
{"include":{"relation":"countries", "scope":{"fields":["name"]}}}

I expect the list of companies with the linked countries for each one but only the "name" property. Instead for each linked Country there is only "null" in the countries array.

**Comment by superkhau** [comment]
The inclusion filter is erroneous applied to the association table. As a result, the queries on related tables all become null. @raymondfeng has a fix in the works at https://github.com/strongloop/loopback-datasource-juggler/pull/476. Track progress on that issue instead, closing this one.
