### ISSUE TITLE
Problem with min & max length validation on model

### ISSUE THREAD

**Issue by vishal171991** [strongloop/loopback#1078]
I am trying to attach length validation to name description field of name field like 

  City.validatesLengthOf('name', { min: 0, max: 10 });  

But when I am trying to save blank name field its give length validation error.

So how can I validate it could be blank or max 10 length.

Thanks,
Vishal

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by esco** [comment]
@superkhau I ran into the same issue as @vishalgarale  https://github.com/strongloop/loopback-datasource-juggler/issues/675

**Comment by vaibhavmagon** [comment]
I am also facing the same issue. It does not work.

**Comment by esco** [comment]
@vaibhavmagon the solution is to use the allowBlank config. More details here:
https://github.com/strongloop/loopback-datasource-juggler/issues/675
