### ISSUE TITLE
Create benchmarks & fail on leaks

### ISSUE THREAD

**Issue by STRML** [strongloop/loopback#1084]
Continuation of [this discussion](https://github.com/strongloop/loopback/pull/1083#issuecomment-73628853) on the critical leak that affected `2.8.7` to `2.12.1`.

We need a way to detect if something like this happens again. 

It would be a good idea IMO to have general benchmarks in any case, so we can detect how our changes affect loopback's throughput. We could also fail the benchmark outright if a `leak` event is caught by [node-memwatch](https://github.com/lloyd/node-memwatch).

**Comment by bajtos** [comment]
Relabelled per our discussion with @raymondfeng, @ritch and @superkhau

**Comment by raymondfeng** [comment]
@superkhau Would you like to create a simple benchmark test that leverages https://github.com/lloyd/node-memwatch to see if it helps?

**Comment by superkhau** [comment]
Sure, adding to TOB for planning.

**Comment by superkhau** [comment]
@raymondfeng What do you want to test in the benchmark? I'm thinking we should make loopback-benchmark public and get some community input on this. Opinions?

**Comment by superkhau** [comment]
As discussed with @raymondfeng and @ritch, it has been decided that we will add benchmarks to various perspectives of LoopBack (module/unit level, integration level, etc). The purpose of this issue has now changed to a spike on how to move forward with regards to tooling and statistics gathering. The findings will be captured in a [wiki](https://github.com/strongloop/loopback/wiki/Benchmarks).

**Comment by superkhau** [comment]
Closing this in favour of https://github.com/strongloop/loopback/issues/1291
