### ISSUE TITLE
Extend remote method documentation

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback#1088]
Let's assume we have build in user model or any model with pre-defined methods like create.

And in Explorer/Swagger there is good API description of methods. But what if I want to change description or notes? 

Basically question is how can I extend/override default remote methods?

something like 

```
  User.remoteMethodExtend('create', {
    notes: 'Here should be some example of how to user User create model.'
  })
```

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
