### ISSUE TITLE
Transaction Support

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#109]
/to @raymondfeng @altsang 
/cc @bajtos

In the interest of LoopBack reliability, I'd like to start a discussion on making LoopBack ACID compliant. After brushing off earlier attempts to look into the issue I had an idea.

I think Transactions + Multiversioning will get us 80% or more to ACID.

**Transactions**

```js
function Transaction(dataSource) {
  this.domain = domain.create();
  this.dataSource = dataSource;
  this.id = this.getHashCode();
  this.snapshots = [];
  
  domain.transaction = this;
  domain.on('error', this.onError.bind(this));
}

Transaction.prototype.commit = function(callback) {
  this.domain.run(function run() {
    this.dataSource.startTransaction(this);
  }.bind(this));
}

Transaction.prototype.snapshot = function(name, callback) {
  this.snapshots.push(this.dataSource.snapshot(name, this, callback));
}

Transaction.prototype.rollback = function(name, fn) {
  this.currentSnapshot = name ? this.getSnapshot(name) : this.snapshots.pop();
  if(this.currentSnapshot) {
    this.dataSource.applySnapshot(this.currentSnapshot)
  }
}

Transaction.prototype.onError = function() {
  this.rollback(function rollback(err) {
    this.dispose();
    throw err;
    
  }.bind(this));
}

Transaction.prototype.dispose = function(callback) {
  this.domain.dispose();
  this.dataSource.endTransaction(this, callback);
}

Transaction.getCurrent = function() {
  return domain.active.transaction;
}

// strong-remoting hooking
remotes.before('**', function(ctx, next, method) {
  var t = ctx.transaction = new Transaction(method.constructor.dataSource);
  t.domain.add(ctx.req);
  t.domain.add(ctx.res);
  t.commit(next);
});

remotes.after('**', function(ctx, next) {
  ctx.transaction.dispose(next);
});
```

The above requires the  `dataSource` / `connector` to implement methods that delegate to driver transactions, or multiversioning. To support multiversioning, an outer wrapper of the connector could be devised that essentially tracks each method call and model instance. As well as changing the behavior slightly.

**Multiversioning**

By default all update operations during a transaction would create copies of the given model instance and tag them with the `transaction.id`. Model's created during the transaction would also be tagged with the `transaction.id`.

By default, all queries would exlclude instances tagged with `transaction.id`s.

**Failure / Cleanup**

If the transaction fails. All models tagged with a `transaction.id` are removed. This could also be ensured on startup / by a job of some sort to essentially garbage collect tagged instances.

If the transaction completes without error all tagged model instances would replace matching untagged models.

**Concerns**
During the final phase of a succesful transaction, since transactions aren't isolated by locking, there is a potential for cleanup to happen out of order. If the `transaction.id` is sortable we might be able to avoid this.

**Comment by FelipeAguayo** [comment]
Have you implemented this? (transactions). because, I really need to implement this in my project

**Comment by bajtos** [comment]
> Have you implemented this?

Not yet, it hasn't been a priority for us.

**Comment by FelipeAguayo** [comment]
Uhmmm, the data consistency should be a priority. Especially if the framework works with databases.

**Comment by altsang** [comment]
If the DB driver supports transactions you should be able to call natively from the LB connector.  We're not implementing transactions at the Juggler level at this time.  2PC is difficult enough when the multiple instances of a data source support it, let alone across multiple disparate data sources.

Our priorities for @bajtos and the rest of the very small team are being driven by our customer obligations and community feedback such as yours.  We appreciate the +1 in this area.  If there's an urgent commercial need or support please feel free to contact our sales team.

**Comment by FelipeAguayo** [comment]
ok, thanks for the answers. I'll wait later versions.

**Comment by vladmiller** [comment]
Absence of transactions is a pain.

**Comment by violet-day** [comment]
:+1:

**Comment by javiboo** [comment]
+1

**Comment by melote** [comment]
+1

**Comment by SnehalAmbab** [comment]
Hello,

Have you implemented "Transactions" yet?

**Comment by raymondfeng** [comment]
Not yet. I'm in the process of refactoring the RDBMS connector implementations and it will become easier to add the transaction support.

**Comment by antoineverger** [comment]
+1

**Comment by richardaum** [comment]
At Strongloop, is possible only attach a transaction to a Model? Is possible to use multiple models operations inside a Transaction block without chaining transactions, as in SQL?

**Comment by raymondfeng** [comment]
There is no reliable way in Node to implicitly propagate the transaction context over the async invocation chain. As a result, we choose to use `options` arg to control the transaction scope.

**Comment by visusharma** [comment]
is there any to pass this options to native sql query also ?

**Comment by bajtos** [comment]
> is there any to pass this options to native sql query also ?
@visusharma please open a new issue to discuss that use case.
