### ISSUE TITLE
Review and improve docs for polymorphic, embeded, and through relations

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1090]

**Comment by crandmck** [comment]
Some overlap with #928

**Comment by crandmck** [comment]
We have http://docs.strongloop.com/display/public/LB/Polymorphic+relations, http://docs.strongloop.com/display/LB/Embedded+models+and+relations, and http://docs.strongloop.com/display/LB/HasManyThrough+relations. 
Review these to see if they are sufficient.

**Comment by hacksparrow** [comment]
@crandmck as discussed, those docs need work. Some content are outdated and the examples need more context.

**Comment by crandmck** [comment]
@hacksparrow Can you fix the outdated content and provide context for the examples?  Please do what you can and note anything you can't do (so I can address it).  I've done a bit of work on those docs last week.  Ping me if you want to discuss.

**Comment by hacksparrow** [comment]
@crandmck yes, I will.

**Comment by crandmck** [comment]
@hacksparrow What's the status of this work?

**Comment by crandmck** [comment]
@hacksparrow Can this be closed?

**Comment by Sequoia** [comment]
Please close when ready.
