### ISSUE TITLE
Extract User / Authentication into a plugin / component

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1091]
This issue is a placeholder to start talking about extracting the opinionated User model into another module. I'd like to allow dropping in a totally different user implementation without copying any User model code. This means we need some sort of base / abstract `User` that these opinionated implementations can be based on.

**Comment by seriousben** [comment]
Would definitely be useful, we ended up not inheriting from the User model and creating our own. But still use accessTokens and other related models.
