### ISSUE TITLE
Rework existing examples to use the new operation hooks

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1092]

**Comment by clarkbw** [comment]
Looking into this I couldn't find an easy way to search for all instances at once.  There are limits on the length of searches and the number of ORs you can use.  So these links offer some redundant results but at the same time some good places to start.

`afterInitialize OR beforeValidate OR afterValidate OR beforeSave OR afterSave user:strongloop language:JavaScript`

https://github.com/search?utf8=%E2%9C%93&q=afterInitialize+OR+beforeValidate+OR+afterValidate+OR+beforeSave+OR+afterSave+user%3Astrongloop+language%3AJavaScript&type=Code&ref=searchresults

`beforeCreate OR afterCreate OR beforeUpdate OR afterUpdate user:strongloop language:JavaScript`

https://github.com/search?utf8=%E2%9C%93&q=beforeCreate+OR+afterCreate+OR+beforeUpdate+OR+afterUpdate+user%3Astrongloop+language%3AJavaScript&type=Code&ref=searchresults

`beforeDestroy OR afterDestroy user:strongloop language:JavaScript`

https://github.com/search?utf8=%E2%9C%93&q=beforeDestroy+OR+afterDestroy+user%3Astrongloop+language%3AJavaScript&type=Code&ref=searchresults

**Comment by crandmck** [comment]
Not sure whether this should get its own issue, but https://github.com/strongloop/loopback-faq-model-hooks should also be converted and renamed to loopback-faq-operation-hooks with some explanation of the difference and an example of the sole model hook that is not deprecated, afterInitialize.

**Comment by crandmck** [comment]
@bajtos Would you be OK if we asked @hacksparrow to work on this?  He's going to work on #1352 to convert the remaining examples to use MW phases.

**Comment by bajtos** [comment]
> Would you be OK if we asked @hacksparrow to work on this? He's going to work on #1352 to convert the remaining examples to use MW phases.

Yes, that's a great idea!

**Comment by hacksparrow** [comment]
I have updated all the relevant examples listed in https://github.com/strongloop/loopback-example to use operation hooks.

https://github.com/strongloop/loopback-faq-operation-hooks
https://github.com/strongloop/loopback-example-app
https://github.com/strongloop/loopback-example-recipes
https://github.com/strongloop/loopback-example-recipes
https://github.com/strongloop/loopback-faq-rest-connector
https://github.com/strongloop/loopback-component-push
https://github.com/strongloop/loopback-component-storage
https://github.com/strongloop/loopback-example-offline-sync
https://github.com/strongloop/loopback-example-passport
https://github.com/strongloop/loopback-faq-model-relations

A repository for operation hooks FAQ has been created at https://github.com/strongloop/loopback-faq-operation-hooks.

With the PRs reviewed and merged, could we close this issue?

**Comment by crandmck** [comment]
I've reviewed a couple of these PRs.  Some may need others to weigh in.  
Let's keep this issue open until all the PRs in the above repos are merged.

**Comment by crandmck** [comment]
All the PRs have been merged, so this can be closed now.
