### ISSUE TITLE
Autoupdate blocks entry for 'required':false values

### ISSUE THREAD

**Issue by ayhoung** [strongloop/loopback#1093]
When autoupdate migration is enabled and new "required:false" fields are added to the json model, it updates the database (postgres) successfully, but everything passed into the new columns results in null values.

**Comment by raymondfeng** [comment]
@ayhoung Can you provide a simple test case and link to the github repo?

**Comment by loay** [comment]
Hi @ayhoung 
Closing due inactivity. If you are still running into the same issue, please advise with a comment and I will re-open the issue. Thanks.
