### ISSUE TITLE
npm WARN engine async-listener

### ISSUE THREAD

**Issue by TofPlay** [strongloop/loopback#1096]
Hi
When I run this command:
```
$ slc loopback myapp
```
I have this message:
```
npm WARN engine async-listener@0.4.7: wanted: {"node":"<=0.11.8"} (current: {"node":"0.12.0","npm":"2.5.0"})
```

**Comment by raymondfeng** [comment]
It's safe to ignore the warning. You can open an issue against https://github.com/othiym23/async-listener too.

**Comment by TofPlay** [comment]
> You can open an issue against https://github.com/othiym23/async-listener too.
Done :smile:
