### ISSUE TITLE
HEAD requests return wrong data in headers

### ISSUE THREAD

**Issue by billinghamj** [strongloop/loopback#1097]
Follows on from #1045, which was incorrectly closed.

In the documentation & API explorer, the `HEAD` method is incorrectly described as a way to check for the existence of an object. In fact, it is actually meant to return exactly the same as a `GET` request does, but without the body.

The `Content-Length` and `Etag` headers return different values for GET & HEAD requests.
#### HEAD

```
$ telnet localhost 3000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
HEAD /1/users/1 HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 15
ETag: W/"f-ff3fd5b5"
Date: Sat, 14 Feb 2015 08:33:45 GMT
```
#### GET

```
$ telnet localhost 3000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /1/users/1

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 90
ETag: W/"5a-e7884b23"
Date: Sat, 14 Feb 2015 08:33:58 GMT

{"firstName":"James","lastName":"Billingham","emailAddress":"james@billingham.net","id":1}
Connection closed by foreign host.
```

It is very important that `HEAD` requests return data matching `GET` requests - particularly in the case of the `Etag` header, which is a hash used for checking if caches are still up-to-date.

The content length of 15 in the `HEAD` request comes from the 'exists' action:

```
$ telnet localhost 3000
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /1/users/1/exists HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Content-Length: 15
ETag: W/"f-ff3fd5b5"
Date: Sat, 14 Feb 2015 08:36:36 GMT

{"exists":true}
```

This behavior violates the [HTTP 1.1 RFC](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13):

> The Content-Length entity-header field indicates the size of the entity-body, in decimal number of OCTETs, sent to the recipient or, **in the case of the HEAD method, the size of the entity-body that would have been sent had the request been a GET**.

**Comment by billinghamj** [comment]
This is what causes the issue:

https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L542

`HEAD /:id` should be part of the `findById` remote - not the `exists` remote. I can fix this, but I don't know exactly how you want to proceed with changes like this - compatibility-wise.

This could be considered a breaking change, if anyone was relying on the `Content-Length` and `Etag` headers. However, their values are *always* wrong already. So I think this would be safe to release as a non-breaking change, because it's really just a patch.

**Comment by billinghamj** [comment]
A similar issue is exhibited here:

https://github.com/strongloop/loopback/blob/master/lib/model.js#L567

However in this case, the correct solution is a bit different. Currently, `HEAD /:pathName/rel/:fk` is used to check for existence. However, `GET /:pathName/rel/:fk` doesn't exist, so the equivelent `HEAD` should not exist either.

The correct path to check for existence in this case is `HEAD /:pathName/:fk`, matching `__findById__`. The existing `HEAD /:pathName/rel/:fk` could be kept for compatibility reasons though.

`belongsToRemoting` and `hasOneRemoting` are both missing `HEAD` routes entirely. It would be a good opportunity to add these at the same time.

**Comment by raymondfeng** [comment]
@billinghamj Are you willing to contribute a patch?

**Comment by billinghamj** [comment]
@raymondfeng Yes absolutely, would be happy to. Just want to make sure there is a chance to discuss it first.

**Comment by bajtos** [comment]
> > Are you willing to contribute a patch?

> Yes absolutely, would be happy to. Just want to make sure there is a chance to discuss it first.

@billinghamj hello, I'd like to check with you what's the status, since I don't see any pull request linked to this issue.

Unfortunately the code links in the comments above are no longer valid, since they point to `master` branch, which has changed quite a bit since the time you wrote your comments. We usually press `y` in the GH UI before copying a link, it tells GH to create a permalink using a commit sha1.

**Comment by billinghamj** [comment]
I don't use Loopback any more I'm afraid, due to many issues like this one.
