### ISSUE TITLE
Polymorphic relation messes up delete for $owner of model

### ISSUE THREAD

**Issue by zanemcca** [strongloop/loopback#1099]
Getting the following error
 ```events.js:72
            throw er; // Unhandled 'error' event
    TypeError: Cannot read property 'prototype' of null
        at isUserClass /node_modules/loopback/common/models/role.js
```
When I looked at it it appears to be getting called with a null modelTo from within modelClass.findById in role.js. I have a polymorphic belongTo relation that I think is causing the problem. I modified isUserClass to return false if the passed in modelClass is null and it cleared the issue up for me.

**Comment by raymondfeng** [comment]
Would you like to submit a patch?

**Comment by zanemcca** [comment]
Submitted a patch. The build is failing due to issue #1103 though. I will await a fix for it.
