### ISSUE TITLE
Trailing whitespace in lib/persisted-model.js

### ISSUE THREAD

**Issue by zanemcca** [strongloop/loopback#1103]
I am getting build failures due to trailing whitespace. I believe it is related to 538e9f0c625b81f338d1f9125dcc086c329cc218 any idea on this @crandmck?

**Comment by crandmck** [comment]
All my changes in that commit were in doc. comments.  Can trailing whitespace in a comment cause a build failure?  Also, AFAIK, our CI tests continue to pass.
@ritch any idea?

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback/pull/1104 <https://github.com/strongloop/loopback/pull/1104>

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by raymondfeng** [comment]
Fixed by https://github.com/strongloop/loopback/pull/1104

**Comment by crandmck** [comment]
@zanemcca Apologies.  I didn't even realize my commit had trailing whitespaces.  Apparently, our build framework does not consider these checks fatal.  I just configured my editor to trim trailing whitespace, so this shouldn't happen again.

**Comment by zanemcca** [comment]
@crandmck No problem I figured it was something minor like that.
