### ISSUE TITLE
Inherit remote method from base class or through hasOne or embedsOne

### ISSUE THREAD

**Issue by zanemcca** [strongloop/loopback#1105]
Essentially I have a vote model that has upvote and downvote remoteMethods and I wish to have the vote model contained within multiple other models and I do not want to rewrite the remote methods so it would be better if I could inherit them through model inheritence, hasOne or embedsOne relations.

Is this possible somehow?

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
