### ISSUE TITLE
Can't add attachments to user verification email

### ISSUE THREAD

**Issue by reichert621** [strongloop/loopback#1107]
When using the `User.prototype.verify` function (http://docs.strongloop.com/display/public/LB/User#user-prototype-verify), I'd like to include `attachments` in the options. The verification email we're sending includes an image, and this image can't be displayed with adding it as an attachment. See https://github.com/andris9/Nodemailer#attachments

I've created a pull request for this issue here: https://github.com/strongloop/loopback/pull/1106

**Comment by superkhau** [comment]
Connected to #1106
