### ISSUE TITLE
include in default scope does not work in model returned after created

### ISSUE THREAD

**Issue by kidwm** [strongloop/loopback#1110]
It seemed to be not able to include data of other model in json gotten after sending POST to /api/models ?

**Comment by raymondfeng** [comment]
Can you elaborate what you are trying to do?

**Comment by Nutelac** [comment]
It is the same problem described here https://github.com/strongloop/loopback/issues/1094?

**Comment by kidwm** [comment]
@Nutelac Yes, thank you!

**Comment by superkhau** [comment]
Closing as duplicate of #1094. @kidwm Repoen if this is still an issue.
