### ISSUE TITLE
User Model API Docs vs User Model Config

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback#1115]
There seems to be a difference in the [properties documented](http://apidocs.strongloop.com/loopback/v/2.12.1/#user) for the User model and those actually present in the [model configuration](https://github.com/strongloop/loopback/blob/b57cd3e40936ee40a03465391b2aeb024cb07d30/common/models/user.json#L3-L31).

In Documentation:
* `username`
* `password`
* `email`
* `emailVerified`
* `verificationToken`

In Config:
* `username` - documented ✓
* `password` - documented ✓
* `email` - documented ✓
* `emailVerified` - documented ✓
* `verificationToken` - documented ✓
* `credentials` - flagged as deprecated, no problem ✓
* `challenges` - flagged as deprecated, no problem ✓
* `realm` - undocumented
* `status` - undocumented
* `created` - undocumented
* `lastUpdated` - undocumented

What has prompted this is that I extend the User model and make use of the `status`, `created` and `lastUpdated` properties. I'm curious as to their intended usage and if they are deprecated as well (in which case I shouldn't be using them).

Worth noting as well, the [Application model](http://apidocs.strongloop.com/loopback/v/2.12.1/#application) uses a `modified` property which likely serves the same function as to what `lastUpdated` was intended for. If `lastUpdated` is something that will be sticking  around, probably a good idea to normalize the field name in a future .

**Comment by ritch** [comment]
@raymondfeng any thoughts?

**Comment by bajtos** [comment]
I believe `created` and `lastUpdated` field are not populated ATM. If it was my call, I would simply remove it in LB 3.0, possibly in favour of a mixing that LB users can add if they like.

AFAICT, `status` is not used either, I would personally remove it too.

`realm` is the only undocumented property that is used by the current code, it allows to namespace user accounts into realms (think of multitenancy). I think it deserves to be documented.

@raymondfeng @ritch @superkhau thoughts?

**Comment by bajtos** [comment]
> @greaterweb I'm curious as to their intended usage and if they are deprecated as well (in which case I shouldn't be using them).

I think they were added with the intention to use them in the future, which obviously never happened. I think it's ok to use them in your app, I am not aware of any immediate plans to use them in LoopBack core.

**Comment by greaterweb** [comment]
@bajtos thanks for the update! 

Not sure what to treat as resolution to this issue but I think some sort of documentation update would be helpful in case anyone else in the future had the same sort of question.

**Comment by davidcheung** [comment]
As of the [`apidocs@2.25`](https://apidocs.strongloop.com/loopback/v/2.25.0/#user) it is listed in the properties now under settings, but I do think it would be helpful if the `apidocs` can somehow link with https://docs.strongloop.com/display/public/LB/Partitioning+users+with+realms as a reference

**Comment by superkhau** [comment]
>I believe created and lastUpdated field are not populated ATM. If it was my call, I would simply remove >it in LB 3.0, possibly in favour of a mixing that LB users can add if they like.
>
>AFAICT, status is not used either, I would personally remove it too.
>
>realm is the only undocumented property that is used by the current code, it allows to namespace user >accounts into realms (think of multitenancy). I think it deserves to be documented.

+1 to all these comments

**Comment by bajtos** [comment]
I'm proposing the following actions:
 - Update apidocs, describe `realm` property and link to https://docs.strongloop.com/display/public/LB/Partitioning+users+with+realms
 - Update apidocs, describe `created`, `lastUpdated` and `status` as unused properties that will be removed in the future.
 - Remove these three unused properties in LoopBack 3.0 - see https://github.com/strongloop/loopback/issues/1854

**Comment by bajtos** [comment]
> As of the apidocs@2.25 it is listed in the properties now under settings, but I do think it would be helpful if the apidocs can somehow link with https://docs.strongloop.com/display/public/LB/Partitioning+users+with+realms as a referencev

@davidcheung I could not find any docs for `realm` property, I can see only `settings.realmRequired` and `settings.realmDelimiter`. Is that what you meant?

I agree it would be helpful to include a link to the "big" docs in the description of these two settings.

**Comment by davidcheung** [comment]
@bajtos you're right, I have created a pull request, and did the first two action you proposed.

**Comment by davidcheung** [comment]
The undocumented `User` properties are now documented in the [updated docs @ `2.26.0`](https://apidocs.strongloop.com/loopback/#user)
Closing issue now.
