### ISSUE TITLE
Example of `defaultFn` in model property definition

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1118]
See https://github.com/strongloop/loopback-datasource-juggler/pull/458.

I am not sure if there is an example app that can be updated to show this new feature.

**Comment by crandmck** [comment]
This is documented per #388.   If/when we add it to an example app, then we can reference that in the docs as we..

**Comment by chandadharap** [comment]
@bajtos Am not sure if there is an example, perhaps you can follow up with Simon but update the example yourself.

**Comment by bajtos** [comment]
IMO we don't need an example app for this, the feature is simple enough to be understood even without any example.

**Comment by mike-aungsan** [comment]
@bajtos  
This is my model.json . lastupdated Property does not added automatically. Am I missing something?

{
  "name": "test",
  "description": ["A Test model"],
  "base": "PersistedModel",
  "strict": true,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "description": ["Name of this template"],
      "required": true
    },
    "lastupdated": {
      "type": "date",
      "description": ["Created Time"],
      "defaultFn": "$now",
      "required": false
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

**Comment by bajtos** [comment]
@mike-aungsan isn't your app reporting `Unknown default value provider $now` to the console? The correct value for `defaultFn` is `"now"` (no dollar sign). See https://github.com/strongloop/loopback-datasource-juggler/pull/458/files

**Comment by mike-aungsan** [comment]
Thanks @bajtos   I figure it out a while later :)

**Comment by nitishmca** [comment]
is there any way to access "description" field in another model?
