### ISSUE TITLE
Unable to retrieve contents of a many-to-many relationship using through model API

### ISSUE THREAD

**Issue by kocsenc** [strongloop/loopback#1119]
I ran into a **reproducible**  problem with the created API. I am not sure if it’s a configuration issue or an actual bug.

As an example let’s use `Company` and `Major`. We made a many-to-many relationship using a **through model** called `CompanyMajor`.  Here are the model definitions (simplified):

`company.json`:
```js
{
  "name": "Company",
  "plural": "Companies",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
  },
  "validations": [],
  "relations": {
    "majors": {
      "type": "hasMany",
      "model": "Major",
      "foreignKey": "majorId",
      "through": "CompanyMajor"
    }
  },
  "acls": [],
  "methods": []
}
```

`major.json`:
```js
{
  "name": "Major",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
  },
  "validations": [],
  "relations": {
    "companies": {
      "type": "hasMany",
      "model": "Company",
      "foreignKey": "companyId",
      "through": "CompanyMajor"
    }
  },
  "acls": [],
  "methods": []
}
```

`company-major.json`:
```js
{
  "name": "CompanyMajor",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {},
  "validations": [],
  "relations": {
    "company": {
      "type": "belongsTo",
      "model": "Company",
      "foreignKey": "companyId"
    },
    "major": {
      "type": "belongsTo",
      "model": "Major",
      "foreignKey": "majorId"
    }
  },
  "acls": [],
  "methods": []
}
```

Steps to reproduce (using these definitions):

1. Create a `Company` instance:
`POST /api/Companies`

2. Create **two** `Major` instances (so that the `id` differs):
`POST /api/Majors`
`POST /api/Majors`

3. Define a relation between `Company` and `Major`:
`PUT /api/Companies/1/majors/rel/2`

4. Get list of `Major` instances related with `Company`:
`GET /api/Companies/1/majors`

**Expected**: a JSON list of `Major` instances related with the `Company` instance:
```javascript
[
  {
    "id": 2
  }
]
```

**Actual**: Empty JSON list:
```js
[]
```

Things to note:
* Same result on both in memory db and mysql connector
* loopback version: `^2.8.0`
* `GET`ting the relation **is** successful if you explicit in which relationship you want to retrieve:
`GET /api/companies/1/majors/2`
* Happens with more than just this example, appears to happen with all many-to-many relationships using a through model

The database schema and contents for `CompanyMajor` shows the expected relationships.

**Comment by raymondfeng** [comment]
Thank you for reporting the issue. Would you please check in the example to a github repo and provide the link?

**Comment by craigcabrey** [comment]
I'm working on this with @kocsenc, I'll create a repo and link it here in a few minutes.

**Comment by craigcabrey** [comment]
Repo with reproducible issue: [craigcabrey/loopback-many-to-many-bug-example](https://github.com/craigcabrey/loopback-many-to-many-bug-example)

**Comment by craigcabrey** [comment]
I think the source of the issue is defining the `foreignKey`s. Removing those attributes results in the expected functionality working.

**Comment by raymondfeng** [comment]
The `foreignKey` for `hasMany` relation was wrong. For example,
```json
"relations": {
    "majors": {
      "type": "hasMany",
      "model": "Major",
      "foreignKey": "majorId",
      "through": "CompanyMajor"
    }
  },
```

The `foreignKey` is the key on the target model `Major` and it should be `companyId`.

Please fix the app as follows:
```json
"relations": {
    "majors": {
      "type": "hasMany",
      "model": "Major",
      "foreignKey": "companyId",
      "through": "CompanyMajor"
    }
  },
```

Same for Major.companies.

**Comment by kocsenc** [comment]
Well that's embarrassing. Thanks for the very rapid response. 

Very much appreciated

**Comment by Pentiado** [comment]
I found an error in docs: http://docs.strongloop.com/display/public/LB/HasManyThrough+relations
There is no way to contribute to documentation right now?

**Comment by superkhau** [comment]
@Pentiado http://docs.strongloop.com/display/public/LB/Contributing+to+LoopBack+documentation

**Comment by Pentiado** [comment]
Thanks! Somehow I missed that. I just contributed to docs.

**Comment by superkhau** [comment]
@Pentiado NP and thanks for the contribution. ;)

**Comment by crandmck** [comment]
@Pentiado I approved your edit per the [community workflow](http://docs.strongloop.com/display/public/LB/Contributing+to+LoopBack+documentation#ContributingtoLoopBackdocumentation-Communityworkflow).  Thanks!
