### ISSUE TITLE
Non-collection resources

### ISSUE THREAD

**Issue by billinghamj** [strongloop/loopback#1122]
Does Loopback support models where the resource it represents is a single object, rather than a collection? If so, how do you go about doing this?

The reason I wonder about this is because a lot of the base model docs reference instance object IDs. In the event of non-collection resources, there would be no ID.

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
