### ISSUE TITLE
hasOne relationship does not populate foreignKey

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback#1125]
If `UserModel` `hasOne` of `GlobalConfigModel` then should something like `adminUser.globalConfigModels.create(...` should result in an instance of `GlobalConfigModel` which  has a foreignKey pointing back to UserModel ... right?

```
  "name": "UserModel",
  "relations": {
    "globalConfigModels": {
      "type": "hasOne",
      "model": "GlobalConfigModel",
      "foreignKey": "userModelToGlobalConfigModelId"
    }
```

```
  "name": "GlobalConfigModel",
  "relations": {
    "userModel": {
      "type": "belongsTo",
      "model": "UserModel",
      "foreignKey": "userModelToGlobalConfigModelId"
    }
```

**Comment by pulkitsinghal** [comment]
here's a repo to demonstrate the problem: https://github.com/pulkitsinghal/loopback-issues-1125

**Comment by raymondfeng** [comment]
There is a user error at https://github.com/pulkitsinghal/loopback-issues-1125/blob/master/server/boot/create-model-instances.js#L47. The arg should be `devGlobalConfig`. Array is not supported here.

**Comment by pulkitsinghal** [comment]
should i reopen the issue and change the title to make it about better validation of args?

**Comment by raymondfeng** [comment]
Maybe open a new one with the same link to your repo?
