### ISSUE TITLE
Missing methods when extending User as user

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1130]
[edited for detail]
I have a model called `user` which extends the built-in `User` model. I create a simple remoteMethod called `greeting` following all the standard reference material (this method works on other, non extended models). However, the new remote method does not work on the `user` model unless the `User` model is set to `"public": false` in the `model-config.json`.

Note, this is related to #397.

/cc @jakerella

**Comment by bajtos** [comment]
My guess is that the problem is caused by having two models exposed at the same path `/users`. In which case, I am proposing to improve strong-remoting to detect this situation and print a warning to the user.
