### ISSUE TITLE
Discriminative orders of events in Operation hooks

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#1136]
Base on this document, i want to convert from Model Hooks to Operation hooks but i got problem.
http://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-Migrationguide

In the document, check "before save" description, we will see that "The hook is triggered before the validation" so i want to validation model data, before call the hook so how can i do this ?

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
