### ISSUE TITLE
Indexes not auto updated

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback#1139]
I've created model without indexes (only ID by default). Put in some data.

To enable autoupdate In code I have

```
app.dataSources.db.isActual(app.models, function(err, actual) {
  console.log(actual);
    if (!actual) {
        app.dataSources.db.autoupdate(app.models, function(err, result) {
        
        });
    }
});
```

Where actual is true.

I've updated model and for one field I've added index

```
    "someId": {
      "type": "string",
      "index": true,
      "unique": true
    },
```

After restart server autoupdate still shows that database is actual and mongodb collection has not been updated.

**Comment by raymondfeng** [comment]
I don’t think mongodb connector implements isActual(). autoupdate calls ensureIndex(). So it should be safe to call it without checking the existence of indexes.

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by cajoy** [comment]
So just call autoupdate on all "restarts"?

**Comment by cajoy** [comment]
So I've removed isActual() but no indexes was updated in Mongodb collection

**Comment by cajoy** [comment]
I've found where is the issue.

autoupdate expects list of model names but not list of models.

I've fixed code and it works fine. But docs should be improved

**Comment by uzyn** [comment]
Also realized you can simply call

```
db.autoupdate(function(err, result) {});
```

to update for all models/collections.

**Comment by spencerfdavis** [comment]
:+1: @uzyn
