### ISSUE TITLE
ViewModels

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#114]
**ViewModels**

We should support some form of ViewModel. A very simple implementation could depend explicitly on MongoDB. I'm struggling to come up with the exact js API, but the features would be:
- readonly 
- aggregate data from multiple data sources based on model relations
- focus on read performance (and local caching config?)
- able to be created without DBAs / sql / etc
- avoid joins and slow SQL operations
- query the aggregated data

A real use case for this is illustrated in the access control example app. The client currently makes a single http request and the server calculates the account balance on demand.

With a ViewModel, the app would make the request to the ViewModel which would be backed by an aggregation (including caluclations) of all the transaction data.

**Comment by violet-day** [comment]
Great!

**Comment by seanbrookes** [comment]
I like ViewModel, ViewDataModel

On Tue, Feb 10, 2015 at 5:55 AM, Nemo <notifications@github.com> wrote:

> Great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback/issues/114#issuecomment-73702131>.
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by dregre** [comment]
+1
