### ISSUE TITLE
How to save ObjectId in an array?

### ISSUE THREAD

**Issue by brunocascio** [strongloop/loopback#1141]
For example, i have to model "likes", then:

```
"properties": {
    "title": {
      "type": "string",
      "required": true,
      "index": true,
      "comments": "Title of recipe"
    },
    "description": {
      "type": "string"
    },
    "servings": {
      "type": "number",
      "required": true,
      "comments": "Cant. of servings"
    },
    "likes": [
        { "type": ObjectId, "ref": User }
    ]
  ...
  },
```

Is that possible like above?

Note: I use mongoDB

**Comment by fabien** [comment]
I think you should look into `referencesMany` relations, it does exactly what you need.

**Comment by brunocascio** [comment]
Could you show me some example?

```
"relations": {
    "ingredients": {
      "type": "embedsMany",
      "model": "Ingredient",
      "options": {
        "validate": true
      }
    },
    "author": {
      "type": "belongsTo",
      "model": "User"
    },
    "likes": {
      "type": "referencesMany",
      "model": "User"
    }
  },
```


But in api explorer, i have to complete ALL fields of user...

**Comment by brunocascio** [comment]
Also, I can to define the model as: 

`likes:[ {type: String, unique: true} ]`

and create remote methods for handle this property, but don't like generate more code. 

Any ideas?

**Comment by superkhau** [comment]
Did you check the docs @fabien mentioned? For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by miltonguty** [comment]
hi brunocascio ,I need do the same please could you tell  me if you found a solution , thanks
