### ISSUE TITLE
Update loopback-boot dependency

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#1143]
Currently, `loopback` has the following devDependency in package.json: 

```
"loopback-boot": "^1.1.0",
```

Updating to:

```
"loopback-boot": "^2.6.5",
```

Causes 14 failures:

325 passing (9s)
1 pending
14 failing

1) access control - integration /users "before each" hook:
2) access control - integration /users "after each" hook:
3) access control - integration /banks "before each" hook:
4) access control - integration /banks "after each" hook:
5) access control - integration /accounts "before each" hook:
6) access control - integration /accounts "after each" hook:
7) relations - integration "before each" hook:
8) relations - integration "after each" hook:
9) remoting - integration "before each" hook:
10) remoting - integration "after each" hook:
11) loopback.rest includes loopback.token when necessary:
12) loopback.rest context propagation should enable context using loopback.context:
13) loopback.rest context propagation should enable context with loopback.rest:
14) loopback.rest context propagation should support explicit context:

**Comment by fabien** [comment]
It appears that the issues have been presents from `loopback-boot 2.0.0` onwards.

**Comment by raymondfeng** [comment]
@fabien `loopback-boot` has two active releases:

1.x.x is for LoopBack 1.x project layout
2.x.x is for LoopBack 2.x project layout

The reason we use `loopback-boot@1.x` as dev dep for `loopback` is that we still have some test fixures in LB 1.x layout.

Based on the above, this issue is not a critical bug.

**Comment by ritch** [comment]
I don't think we want to make boot@2 BC. @bajtos re-open if you think we should.

**Comment by bajtos** [comment]
IIRC, we are dev-depending on `loopback-boot@1` to verify that `loopback@2` apps can be bootstrapped using `loopback-boot@1`. The goal was to simplify upgrade from `loopback@1` to `loopback@2`, i.e. make sure that applications created with `loopback@1` project layout can be upgraded to `loopback@2` runtime without the need to upgrade the project layout too.

To be honest, I think we can drop the backwards-compatibility tests now, together with the dev-dependency on `loopback-boot@1`.

Having said that, I see it as a rather unimportant change that we won't be making ourselves, unless somebody is willing to contribute this change. Let's create a `#patch-welcome` label to mark issues like this one (cc @superkhau).
