### ISSUE TITLE
Filtering Issue with AND and INQ

### ISSUE THREAD

**Issue by benmarten** [strongloop/loopback#1144]
Hi, I am encountering an issue when sending requests like this from iOS/Android SDK:

	NSArray:
	{
	    filter =     {
	        where =         {
	            and =             (
	                                {
	                    name =                     {
	                        like = Spaghetti;
	                    };
	                },
	                                {
	                    pickupAddressZip = 12345;
	                }
	            );
	        };
	    };
	}

	URL:
	dishes?
	filter[where][name][like]=Spaghetti&
	filter[where][and][][pickupAddressZip]=12345

	Request: 200

	NSArray:
	{
	    filter =     {
	        where =         {
	            and =             (
	                                {
	                    name =                     {
	                        like = Spaghetti;
	                    };
	                },
	                                {
	                    pickupAddressZip = 12345;
	                },
	                                {
	                    categories =                     {
	                        inq =                         (
	                            Scharf,
	                            Vegetarisch
	                        );
	                    };
	                }
	            );
	        };
	    };
	}

	URL:
	dishes?
	filter[where][and][][name][like]=Spaghetti&
	filter[where][and][][categories][inq][]=Scharf&
	filter[where][and][][categories][inq][]=Vegetarisch

	Request: 400
	{"error":{"name":"Error","status":400,"message":"The categories property has invalid clause {\"inq\":{\"[]\":[\"Scharf\",\"Vegetarisch\"]}}","statusCode":400,"stack":"Error: The categories property has invalid clause {\"inq\":{\"[]\":[\"Scharf\",\"Vegetarisch\"]}}\n    at Function.DataAccessObject._coerce (/app/node_modules/loopback-datasource-juggler/lib/dao.js:686:23)\n    at Function.DataAccessObject._coerce (/app/node_modules/loopback-datasource-juggler/lib/dao.js:620:16)\n    at Function.DataAccessObject._normalize (/app/node_modules/loopback-datasource-juggler/lib/dao.js:571:8)\n    at Function.find (/app/node_modules/loopback-datasource-juggler/lib/dao.js:811:10)\n    at Object.eval [as forward] (eval at recompile (/app/vendor/node/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:237:15), <anonymous>:4:32)\n    at Function.find (eval at wrap (/app/vendor/node/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:193:20), <anonymous>:3:21)\n    at SharedMethod.invoke (/app/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:246:19)\n    at HttpContext.invoke (/app/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:280:12)\n    at /app/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:515:9\n    at execStack (/app/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:368:7)"}}

The combination of AND and INQ operator does not seem to work. Any ideas?

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by benmarten** [comment]
Created it: https://github.com/benmarten/loopback-sandbox

To reproduce the issue, please pull code, npm install and 'slc run .'
Then try:
- Works: 0.0.0.0:3000/api/Dishes?filter[where][name][like]=Spaghetti&filter[where][and][][pickupAddressZip]=12345
  Result: []
- Does not work: http://0.0.0.0:3000/api/Dishes?filter?filter[where][and][][categories][inq][]=Scharf&filter[where][and][][categories][inq][]=Vegetarisch
  Result: Error....

These REST style queries, are actually generated by the iOS Loopback SDK. When "translating" the above mentioned NSArray, to json and trying it in the api explorer, it actually works!
{
    "filter": {
        "where": {
            "and": [
                {
                    "name": {
                        "like": "Spaghetti"
                    }
                },
                {
                    "pickupAddressZip": "12345"
                },
                {
                    "categories": {
                        "inq": [
                            "Scharf",
                            "Vegetarisch"
                        ]
                    }
                }
            ]
        }
    }
}

**Comment by raymondfeng** [comment]
One workaround is to send in the `filter` as stringfied json.

**Comment by benmarten** [comment]
thanks a lot! this worked :)

sth like that: 
http://stackoverflow.com/a/9020923/2302437
[_dishRepository invokeStaticMethod:@"filter" parameters:@{@"filter":jsonString} success....
