### ISSUE TITLE
EmbedsMany with selected properties

### ISSUE THREAD

**Issue by brunocascio** [strongloop/loopback#1146]
Is this possible?

For example:

```
"likes": {
      "type": "embedsMany",
      "model": "User",
      "properties":{
        "userId": "id"
      }
    }
```

where only get `id` from `User` :

Expected result:

```
likes: [
 {"userId": "s76fa7688s7fa8df7a89s"}
]
```

Or much better:

```
likes: [ "s76fa7688s7fa8df7a89s",  "7ds8687s96ga879s87fas87sa7"]
```

which is the correct form?

**Comment by loay** [comment]
@brunocascio 
So to ensure that I follow:
You are asking to implement a feature, so when you GET query your model, the expected results to show as:
```
likes: [ "s76fa7688s7fa8df7a89s",  "7ds8687s96ga879s87fas87sa7"]
```
instead of:
```
likes: [
 {"userId": "s76fa7688s7fa8df7a89s"},
 {"userId": "7ds8687s96ga879s87fas87sa7"}
]
```
Correct?

**Comment by loay** [comment]
Hi @brunocascio 
I will close this issue for now. If you are still running into problems or you think there is an added value to a feature, feel free to leave a comment and I will reopen the issue and see if we can implement the feature. Thanks.
