### ISSUE TITLE
Possibility to add "count()" in scope

### ISSUE THREAD

**Issue by brunocascio** [strongloop/loopback#1149]
For Example, some like this:

```
{
  "name": "Recipe",
  "properties": {
    ...
  }
  "scope": {
    "likes": "$count"
    "where": {
      "deleted": false
    }
  }
}
```

Reponse:

```
[{
 name: "name of recipe",
 likes: 5
}]
```

**Comment by JonnyBGod** [comment]
+1

**Comment by pthieu** [comment]
@brunocascio: This might take a while for us to get to. To speed up the process, you can do one of two things:
 1. If you still require this, open a new issue using the `New issue` button and fill in the template provided to you
 2. Open a PR adding this functionality yourself and we will review and merge.

Will close this issue now. Please use `#1` if you still require this.

**Comment by engrwaqasali** [comment]
need this +1
is it available in loopback4?
