### ISSUE TITLE
role.users doesn't invoke callback

### ISSUE THREAD

**Issue by esco** [strongloop/loopback#1151]
The role.users function doesn't invoke the callback if the query succeeds. Check comments in the code below to see where...

```javascript
Role.prototype.users = function(callback) {
  roleMappingModel.find({where: {roleId: this.id,
    principalType: RoleMapping.USER}}, function(err, mappings) {
    if (err) {
      if (callback) callback(err); // callback is invoked on error, good
      return;
    }
    return mappings.map(function(m) {
      return m.principalId;
    });
   // callback is never invoked...hangs
  });
};
```
Should this just be returning the array via callback? 

Another thing I noticed is that its checking for the existence of the callback
```javascript
if (err) {
  if (callback) callback(err);
  return;
}
```
Since this is happening within a an anonymous function after a call to `roleMappingModel.find` which is not being returned, shouldn't a callback be required?

https://github.com/strongloop/loopback/blob/d24da8c37d9b5ba26c7572f5cc950698c0831e3d/common/models/role.js#L39

The `Role.prototype.applications` and `Role.prototype.roles` functions have the same issue.

**Comment by raymondfeng** [comment]
Patches are welcome.

**Comment by esco** [comment]
@raymondfeng sure, I had basically made another function that does with this was intended to do in the interest of using it now. I'll move that logic over to roles.js and submit a patch this week.
