### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by brunocascio** [strongloop/loopback#1154]
I override `create`method:

```
Recipe.on('attached', function() {

		Recipe.create = function( data, cb ) {

			console.log("call to create");
			this.create(data, function(err, recipe) {
				console.log("run inside");
				if ( err ) return cb(err);

				cb(null, recipe)	
			});
		}
	});
```

And returns:
```
{
  "error": {
    "name": "RangeError",
    "status": 500,
    "message": "Maximum call stack size exceeded"
  }
}
```

In console log, `call to create` is repeated infinitely.

**Comment by seriousben** [comment]
I think you might want to use `once` and not `on`


--Benjamin Boudreau
    http://seriousben.com/

**Comment by brunocascio** [comment]
Yes, but i think call stack happens because Recipe.create() calls recursive with remote method.

**Comment by seriousben** [comment]
Well in your code you are calling the same create twice. Recipe.create and
this.create ends up being the same method.

Also I would not override create.


--Benjamin Boudreau
    http://seriousben.com/

**Comment by brunocascio** [comment]
I tried to change `create` for `upsert`, and same problem. 
```
Recipe.create = function( data, cb ) {
			console.log('call stack')
			this.upsert(data, function(err, recipe) {
				if ( err ) return cb(err);

				cb(null, recipe)	
			});
		}
```

I need override this method because i need add more logic (for example, image processing)

**Comment by seriousben** [comment]
In loopback you would use hooks to add logic:
http://docs.strongloop.com/display/LB/Adding+logic+to+models


--Benjamin Boudreau
    http://seriousben.com/

**Comment by brunocascio** [comment]
Great! Thanks!
