### ISSUE TITLE
Loopback examples dated from README.md

### ISSUE THREAD

**Issue by jasonsturges** [strongloop/loopback#1158]
Loopback [examples section of the README.md](https://github.com/strongloop/loopback/blob/master/README.md#examples) appears dated, such as:

### Missing / broken links
- [loopback-example-todo](https://github.com/strongloop/loopback-example-todo)

### Projects marked deprecated
- [loopback-example-database](https://github.com/strongloop/loopback-example-database)
- [loopback-example-datagraph](https://github.com/strongloop/loopback-example-relations-basic)

### Projects renamed:
- [loopback-example-datagraph](https://github.com/strongloop/loopback-example-datagraph) is actually [loopback-example-relations-basic](https://github.com/strongloop/loopback-example-relations-basic)

### [Examples under StrongLoop](https://github.com/strongloop?page=1&query=example) organization not included:

- https://github.com/strongloop/loopback-example
- https://github.com/strongloop/loopback-example-access-control
- https://github.com/strongloop/loopback-example-angular
- https://github.com/strongloop/loopback-example-APIClientApp
- https://github.com/strongloop/loopback-example-app-cookbook
- https://github.com/strongloop/loopback-example-app-logic
- https://github.com/strongloop/loopback-example-component
- https://github.com/strongloop/loopback-example-datasourceAPI
- https://github.com/strongloop/loopback-example-file-storage
- https://github.com/strongloop/loopback-example-model-relations
- https://github.com/strongloop/loopback-example-mongodb
- https://github.com/strongloop/loopback-example-mssql
- https://github.com/strongloop/loopback-example-mysql
- https://github.com/strongloop/loopback-example-oracle
- https://github.com/strongloop/loopback-example-passport
- https://github.com/strongloop/loopback-example-postgresql
- https://github.com/strongloop/loopback-example-remote
- https://github.com/strongloop/loopback-example-recipes
- https://github.com/strongloop/loopback-example-two-factor
- https://github.com/strongloop/sn-example-blog
- https://github.com/strongloop/sn-example-chat
- https://github.com/strongloop/sn-example-urlsaver
- https://github.com/strongloop/express_example
- https://github.com/strongloop/example-generators

**Comment by superkhau** [comment]
Thanks for the report, all the examples are now at strongloopback/loopback-example. We should change the readme and link to that repo directly. Would you like to submit a PR?

**Comment by jasonsturges** [comment]
Pull request in progress.  Thanks.

**Comment by superkhau** [comment]
Thanks, looking forward to it. :+1:
