### ISSUE TITLE
Documentation: Model.remoteMethod incomplete

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#1161]
I find it rather alarming that non-static/prototype based remote methods are silently being phased out. At least that's my impression. Being able to piggy-back on the existing `findById` behavior and then work from that still strikes me as being essential.

To my surprise, the documentation doesn't even mention the `isStatic` option, which allows this: http://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-AddingACLstoremotemethods

Also, the `http` `source` properties can also include `res` - which is mandatory if you need to handle direct output the client (think, file downloads, and such).

**Comment by rus0000** [comment]
Same to me. `isStatic` is very important but absolutely missing from docs. Is it intentional?

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
It's included in API docs for `disableRemoteMethod` - http://apidocs.strongloop.com/loopback/#model-disableremotemethod.  I'll talk with @ritch about adding it to the [table of options](http://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Options) for `remoteMethod()` as well.  Also API docs should link to this table.

**Comment by crandmck** [comment]
@ritch I added `isStatic` to the [options table](http://docs.strongloop.com/display/LB/Remote+methods#Remotemethods-Options).  I need to discuss this with you:

> the http source properties can also include res - which is mandatory if you need to handle direct output the client (think, file downloads, and such).

**Comment by crandmck** [comment]
Since docs now include `isStatic` in several places, I'll close this.
