### ISSUE TITLE
Support for Calculated Attributes dependent on related models

### ISSUE THREAD

**Issue by michael-lumley** [strongloop/loopback#1164]
I was disappointed with the lack of support for calculated attributes dependent on related models and <a href="http://stackoverflow.com/a/28860988/2102695">wrote a plugin to implement that functionality</a>.  I wanted to bring that plugin to the attention of the developers in the event that they were interested in implementing that functionality in future releases. I'm confident that there are others out there who would find the functionality useful as well.

**Comment by smehrbrodt** [comment]
Would be great to have this in Loopback.

@michael-lumley would you mind creating a pull request with your plugin?

**Comment by michael-lumley** [comment]
@smehrbrodt I'm a little hesitant to do that, for a couple of reasons - first and foremost, I'm a lawyer by training, programming is just a hobby for me, so I'm not totally confident that the plugin won't break under certain use cases. Second, I don't want to step on the toes of the project leads - I don't want to muck up the project with some unconventional code. Finally, the code is available at the link above to those who'd like to implement it for themselves, and by including it in a module or a bootscript, you can make sure that it doesn't get overwritten by subsequent releases of the main loopback project.

Thanks for the thought, though!

**Comment by MikeSpock** [comment]
@smehrbrodt In my opinion this is a must-have & indispensible feature for Loopback. Having a simple case of needing something in a project like `events` that hasMany `users` through `invitations` does require an aggregator function to return how many ppl are attending with each GET /api/events request. This is such a simple case, and it'd be awesome if this could be a feature of Loopback core.

**Comment by gausie** [comment]
Would definitely use this if it were merged.

**Comment by mastertinner** [comment]
+1

**Comment by superkhau** [comment]
@michael-lumley Feel free to submit a PR, if anything looks odd, we'll give you feedback. ;)

**Comment by shuckepco** [comment]
:-1: Would be a great feature.

**Comment by mastertinner** [comment]
I just figured out that this can actually be solved pretty conveniently with operational hooks. I posted a sample here: https://stackoverflow.com/questions/25438663/dynamic-properties-or-aggregate-functions-in-loopback-models/32285839#32285839

From my point of view this solves this issue and it can therefore be closed.

**Comment by mrfelton** [comment]
You can also use our computed property mixin - https://github.com/fullcube/loopback-ds-computed-mixin

**Comment by pthieu** [comment]
@michael-lumley: looks like you can use the two work arounds above or open a PR for us to merge (to speed up the process). Going to close, please re-open if you still require this.
