### ISSUE TITLE
Expose context.instance in `before delete` operation hook

### ISSUE THREAD

**Issue by kidwm** [strongloop/loopback#1165]
Or how to delete related items when a specific model is deleted ?

http://stackoverflow.com/questions/28607543/how-to-access-the-modal-instances-that-will-be-deleted-in-the-before-delete

**Comment by ritch** [comment]
We would have to change the way `deleteById` and friends behave to achieve this. I don't think we can really do that. Something to consider in loopback.next thought @raymondfeng.
