### ISSUE TITLE
Replication and ACLs

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1166]
The replication algorithm should check that the user invoking the action has permissions to modify the model instances replicated.

**Tasks**

 - [x] replication #1270
 - [x] conflict resolution #1294
 - [x] documentation update

**Comment by chandadharap** [comment]
link PR

**Comment by bajtos** [comment]
@chandadharap @ritch I'd like to check with you what's the status of this story? It's assigned to Sync v1.0 milestone, but not in the current sprint 67.

**Comment by bajtos** [comment]
Related: https://github.com/strongloop/loopback-connector-remote/issues/3

**Comment by bajtos** [comment]
Done.
