### ISSUE TITLE
Remote method accepts arguments undefined

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#1168]
When passing parameters into a remote method, the accepted arguments are not provided to the handler function.

Reproduce by running http://github.com/strongloop/loopback-example-app-logic and performing a curl request (`curl localhost:3000/api/cars/rev-engine -d '{"sound":"vroom"}'`). Another option is to simply try out the Person example in the docs, the output will be `"Greetings... undefined"`.

**Comment by raymondfeng** [comment]
Can you specify the `Content-Type` header to be `application/json`?

**Comment by superkhau** [comment]
That works! Closing. ;)

For anyone else reading, it should be `curl localhost:3000/api/cars/rev-engine -H "content-type:application/json" -d '{"sound":"vrooom"}'`
