### ISSUE TITLE
Improve docs for Operation hooks

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1173]
Judging by the recent discussions in GitHub issues, the current minimal documentation does not make it clear how to correctly use the hooks and why they are designed in a seemingly unintuitive way.

The goal of this task is to write down all knowledge that's in Miroslav's head at the moment, add information from comments in the issues linked below, and beef up the doc page [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks).

A list of pain-points can be found here:
 - https://github.com/strongloop/loopback-datasource-juggler/issues/482

Related issues:
 - https://github.com/strongloop/loopback-datasource-juggler/issues/481
 - https://github.com/strongloop/loopback-datasource-juggler/issues/474
 - https://github.com/strongloop/loopback-datasource-juggler/pull/483
 - https://github.com/strongloop/loopback-datasource-juggler/issues/484
 - https://github.com/strongloop/loopback-datasource-juggler/pull/488/files#r25886292

**Comment by chandadharap** [comment]
I'd rather that Rand sit with you and get the info to update and improve docs, rather than you write this.

**Comment by crandmck** [comment]
Miroslav, I will go through the above issues and try to extract the pertinent info.  I will likely have questions as a result.... Then let's meet and you can give me a brain dump, as Chanda suggests.  You could also jot down some notes if you have some specific things you know you'd like to add to or change in the docs.

**Comment by crandmck** [comment]
This may not be completed this sprint, since the feature is being significantly reworked.  

Miroslav said:
> there are still pull requests in progress that will improve certain areas, so this docs work may be a longer term affair.

**Comment by bajtos** [comment]
@crandmck first few things that are ready to be documented.

Document "hookState" - see https://github.com/strongloop/loopback-datasource-juggler/pull/485 and https://github.com/strongloop/loopback-datasource-juggler/issues/484

Capture the information from https://github.com/strongloop/loopback-datasource-juggler/pull/483#issuecomment-77332635. The first part explains why there is "instance" object instead of providing always a "data" object. The second part explains different use cases of hooks.

Explain why the "before delete" and "after delete" hooks don't receive a list of deleted ids, see the discussion in https://github.com/strongloop/loopback-datasource-juggler/issues/474. Explain that a naive implementation of hooks creates a race condition (https://github.com/strongloop/loopback-datasource-juggler/issues/474#issuecomment-77338067) and describe how it can be avoided (https://github.com/strongloop/loopback-datasource-juggler/issues/474#issuecomment-77338379).

NOTE: https://github.com/strongloop/loopback-datasource-juggler/pull/488 is adding `ctx.instance` to both "delete" hooks when they are deleting a single model, we will need to describe that once the PR is landed. Because batch delete is not exposed via REST API by default (IIRC), in most cases `ctx.instance` should be a good solution for getting data of the deleted model (including the `id`).

https://github.com/strongloop/loopback-datasource-juggler/issues/481 contains useful information too, e.g. the first part of https://github.com/strongloop/loopback-datasource-juggler/issues/481#issuecomment-77314954 explains why "updateAttributes" does not have `ctx.instance`.

NOTE: https://github.com/strongloop/loopback-datasource-juggler/pull/488 is adding `ctx.currentInstance` to "before save" hook triggered by "updateAttributes", this should somewhat alleviate the problem.

**Comment by bajtos** [comment]
Some material for starting a FAQ section: https://github.com/strongloop/loopback-datasource-juggler/issues/482#issuecomment-77327772

**Comment by bajtos** [comment]
Re-estimating to 1 story point. I'll only gather more pointers to relevant comments and pull requests, so that @crandmck can write the content himself.

**Comment by crandmck** [comment]
@bajtos Added a note about `ctx.options` that Fabien added.  However, we really need an example.  See http://docs.strongloop.com/display/LB/Operation+hooks#Operationhooks-Operationhookcontextobject.

**Comment by bajtos** [comment]
> @crandmck Can we get an example of how `ctx.options` might be used?

Here is a code snippet based on https://github.com/strongloop/loopback-datasource-juggler/pull/549#issuecomment-87673015. 

```js
var FILTERED_PROPERTIES = ['immutable', 'birthday'];
MyModel.observe('before save', function filterProperties(ctx, next) {
  if (ctx.options && ctx.options.skipPropertyFilter) return next();
  if (ctx.instance) {
    FILTERED_PROPERTIES.forEach(function(p) { ctx.instance.unsetAttribute(p); });
  } else {
    FILTERED_PROPERTIES.forEach(function(p) { delete ctx.data[p]; });
  }
  next();
});

// immutable is not updated
MyModel.updateOrCreate({ id: 1, immutable: 'new value' }, cb);

// immutable is changed
MyModel.updateOrCreate({ id: 2, immutable: 'new value' }, { skipPropertyFilter: true }, cb);
```

**Comment by crandmck** [comment]
Added the example code..thanks.

We still need to add all the items noted in the [comment above](https://github.com/strongloop/loopback/issues/1173#issuecomment-77890296).  

@bajtos Were you planning to do this, or did you want me to do it?

**Comment by bajtos** [comment]
> Were you planning to do this, or did you want me to do it?

Please do it yourself. My plan was only to collect a list of pointers for you.

**Comment by bajtos** [comment]
Actually there are no more features to add to the list in the comment above, I am reassigning this issue to you, @crandmck.

**Comment by crandmck** [comment]
OK, here is what I have for this (finally):
-  [ ] Document "hookState" - http://docs.strongloop.com/display/LB/Operation+hooks#Operationhooks-SharedhookStateproperty
- [ ] Explain why there is "instance" object instead of providing always a "data" object. etc. Explain why the "before delete" and "after delete" hooks don't receive a list of deleted ids, etc
- [ ] Doc ctx.instance for both "delete" hooks when they are deleting a single model. 
- [ ] strongloop/loopback-datasource-juggler#481 contains useful information too

**Comment by bajtos** [comment]
> OK, here is what I have for this:
> (...)

Sounds good! 

FYI, there were two more hooks added recently, see https://github.com/strongloop/loopback-datasource-juggler/pull/599 and https://github.com/strongloop/loopback-datasource-juggler/pull/586. I am afraid the task of (fully) documenting operation hooks will be a long one.

**Comment by crandmck** [comment]
@bajtos It was difficult for me to sort out from the _very_ lengthy discussions across multiple PRs what was actually done and needs to be documented.  I gave it my best shot, but apologies if I missed something.  I admit to still being somewhat confused.

Please review the updates referenced in the [comment above](https://github.com/strongloop/loopback/issues/1173#issuecomment-116875296) and let me know what more needs to be added or changed.  Some illustrative examples would help.

Re the two new hooks, see http://docs.strongloop.com/display/LB/Operation+hooks#Operationhooks-newhooks.  Note this information is "hidden" until the new features are released to production.

**Comment by bajtos** [comment]
@crandmck thank you for updating the doc page. I am afraid I don't have enough time to review the changes now, I have created a new sprint story so that we can plan this task: https://github.com/strongloop-internal/scrum-loopback/issues/376 Sorry for the delay :(

**Comment by crandmck** [comment]
OK, np.  It took me quite a while to get around to working on this myself.

**Comment by crandmck** [comment]
Closed in favor of https://github.com/strongloop-internal/scrum-loopback/issues/376.

**Comment by mike-aungsan** [comment]
Is it possible to terminate the invocation from Operation hooks?
I cannot find in doc. I try ctx.end() and it raise err.

**Comment by bajtos** [comment]
@mike-aungsan 
> Is it possible to terminate the invocation from Operation hooks?
> I cannot find in doc. I try ctx.end() and it raise err.

You can terminate the invocation by raising an error via `next(err)`.

In the future, please post questions to our mailing list and/or community forums, see https://github.com/strongloop/loopback/wiki/Questions.
