### ISSUE TITLE
Loosing context after external request

### ISSUE THREAD

**Issue by umbrella-ivan-zhukov** [strongloop/loopback#1177]
In external request callback loopback.getCurrenrContext() returns 'null'. 
Is this an expected behavior?

**Comment by BerkeleyTrue** [comment]
Have you set the remoting context setting as [here](http://docs.strongloop.com/display/public/LB/Using+current+context). If so, then this is likely a bug.

**Comment by umbrella-ivan-zhukov** [comment]
Yes, I have this setting.
It seems, while the response has not been sent, external request rewrites the current context with the new one. And I really need the initial context throughout the request processing.

**Comment by BerkeleyTrue** [comment]
Context is within a domain of each request so each request has its own context. Additional request should not overwrite the others. 

If there is no request there is no context to create. 

How exactly are you trying to use it. Maybe I am just misunderstanding your use case. Can you provide some example code?

**Comment by umbrella-ivan-zhukov** [comment]
@BerkeleyTrue , thanks for your response! Here is the simplified code: 
```
var loopback = require('loopback'),
    thirdPartyService = require('thirdPartyService');

module.exports = function(User) {

  User.cardDetails = function(callback) {
    // Fetch user data
    thirdPartyService.fetchUser({
      userId: loopback.getCurrentContext().get('user').id  /* works as expected */
    }, function(error, user) {
      if (error) throw error;

      // Fetch card details
      thirdPartyService.fetchCard({
        cardId: user.default_card,
        userId: loopback.getCurrentContext().get('user').id  /* throw error, because getCurrentContext returns null */
      }, function(error, card) {
        if (error) throw error;

        // Respond with card data
        callback(null, card);
      })
    })
  };

  User.remoteMethod('cardDetails', {
    http: { path: '/cardDetails', verb: 'get' }
  });
}
```

**Comment by BerkeleyTrue** [comment]
Yes, that seems like a bug. The domain for the fetchUser callback should be the same as the domain for cardDetails callback. 

It may also be that the callback for thirdPartyService is loosing the domain since it's outside of loopback? Not sure on that one. Will need a Strongloop Dev or someone more familiar with Domains to chime in here.

Here is a quick work around for you.

```js
var loopback = require('loopback'),
    thirdPartyService = require('thirdPartyService');

module.exports = function(User) {

  User.cardDetails = function(callback) {
     var userId  = loopback.getCurrentContext().get('user').id;
     // Now userId is in the closure for this function.
    // Fetch user data
    thirdPartyService.fetchUser({
      userId: userId
    }, function(error, user) {
      if (error) throw error;

      // Fetch card details
      thirdPartyService.fetchCard({
        cardId: user.default_card,
        userId: userId
      }, function(error, card) {
        if (error) throw error;

        // Respond with card data
        callback(null, card);
      })
    })
  };

  User.remoteMethod('cardDetails', {
    http: { path: '/cardDetails', verb: 'get' }
  });
}
```

**Comment by umbrella-ivan-zhukov** [comment]
Unfortunately it does not work for model hooks, that called after external request.

**Comment by umbrella-ivan-zhukov** [comment]
Do anybody have suggestions why context gets null after external http request?
I'm stucked with this bug, also tried to use node.js domains directly, but failed.

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by loay** [comment]
getCurrentContext is deprecated: https://github.com/strongloop/loopback/issues/1676 but I am not sure if it is related to your case, so if you are still running into the same issue, can you please provide a link to your test project to reproduce? Thanks.

**Comment by umbrella-ivan-zhukov** [comment]
@loay , thanks for information.
Yes, seems like my issue:

> It seems to me that most of the issues are caused by the fact that any connector using connection pool must be CLS aware and include few lines of code to switch to the right CLS context. 


You can view my fix [here](https://github.com/umbrella-web/node-continuation-local-storage/commit/710174dd0c75c9b4dd95678813db01d82af121e1), where I'm looking data through all available contexts.
