### ISSUE TITLE
Multiple POST on an embedsMany relation loses data

### ISSUE THREAD

**Issue by PuKoren** [strongloop/loopback#1178]
Using an embedsMany relation:

``` js
"actions": {
  "type": "embedsMany",
  "model": "empty",
  "property": "events"
}
```

If I send multiple `[POST] /MyDocument/{id}/actions` quickly on the same document ID or if the DB is slow, some data are lost. I suppose embedsMany POST fetches from DB, appends data, and save back to DB. If there is multiple operations at the same time, the saved value does not contains every posted actions.

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by davebcn87** [comment]
This is happening to me also. When trying to create an embedded model through the API Explorer I get a validation error like this:

    ...contains invalid item at index `0`: `id` is blank (value:...

**Comment by bajtos** [comment]
Quoting @fabien, the author of embeded relations:

> The race condition is nothing new - I'd be the first to admit that the implementation is a bit naive. Perhaps we should open a ticket: perform true partial - granular - updates for embedded models?

See https://github.com/strongloop/loopback-datasource-juggler/pull/516#issuecomment-83972147, I hope I did not put the quote too much out of the original context.

**Comment by kjdelisle** [comment]
Closing this due to age.
