### ISSUE TITLE
bug: limitations of middleware.json

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback#1179]
By using `middleware.json` to configure your middleware you are unable to use the same middleware twice within a phase as the property names would conflict.

For example, if you wish to serve static assets from multiple locations you would be unable to configure this through `middleware.json`. The second instance of `"loopback#static"` would overwrite the first.

```json
{
  "files": {
    "loopback#static": {
      "params": "$!../static"
    },
    "loopback#static": {
      "params": "$!../client"
    }
  }
}
```

This may seem like a trivial example but it's a valid limitation of using the `middleware.json` approach.

## Continued Thoughts
Sorry, a little long winded but if some of my ramblings could improve the implementation of the middleware loading I'm happy to contribute. We can extract these notes and place in another area if anyone feels it is more appropriate.

In my (unsolicited) humble opinion, of all of the configurations loopback uses, the middleware config approach is harder than it should be. I totally understand the importance of the phases but I think trying to squeeze your middleware configuration into JSON seems to be harder than it should be. 

With the other config files loopback consumes, you are supplying basic values. With the middleware config file you are replacing things you would normally code and it feels awkward.

Not related to the bug but I'll offer up some input from my experience. I'm trying to use the `middleware.json` approach in a project but find myself bending the rules a bit. 

My config looks something like this:
```json
{
  "initial": {
    "./middleware/initial": {}
  },
  "session": {
    "./middleware/session": {}
  },
  "files": {
    "./middleware/files": {}
  },
  ...
}
```

Loopback expects these to be a reference to a single middleware handler but I get around that creating and returning an express router. For that particular phase I attach all the middleware I need to the router that is returned. 

Taking the files example above, it can be solved like this (not my actual source but you get the idea):

```js
'use strict';
var app = require('../server');
var loopback = app.loopback;

module.exports = function () {
    var router = loopback.Router();

    router.use(loopback.static('../../static'));
    router.use(loopback.static('../../client'));

    return router;
};
```

## Possible Improvement
I think an alternate implementation of the middleware bootstraping could borrow some of the approach used with the boot directory as well as some of the concepts I currently employ. Specifically, if we have a `/middleware` directory which includes files named to match their respective phase name (eg. `/middleware/files.js`), Loopback could load these modules passing in a router to which middleware is attached.

Some mock/pseudo code to illustrate the concept.

In loopback have something like this:
```js
'use strict';

var builtInPhases = [
    'initial',
    'session',
    'auth',
    'parse',
    'routes',
    'files',
    'final'
];

builtInPhases.forEach(function (phase) {
    // the file naming convention for before and after is certainly debateable
    // the before and after subphases could even be exposed as methods from
    // the main phase config
    var beforePhaseConfig = pathToMiddleware + phase + '.before.js';
    var phaseConfig = pathToMiddleware + phase + '.js';
    var afterPhaseConfig = pathToMiddleware + phase + '.after.js';

    if (configExists(beforePhaseConfig)) {
        var beforeRouter = loopback.Router();
        require(beforePhaseConfig)(beforeRouter, app);
        app.middleware(phase + ':before', beforeRouter);
    }

    if (configExists(phaseConfig)) {
        var router = loopback.Router();
        require(phaseConfig)(router, app);
        app.middleware(phase, router);
    }

    if (configExists(afterPhaseConfig)) {
        var afterRouter = loopback.Router();
        require(afterPhaseConfig)(afterRouter, app);
        app.middleware(phase + ':after', afterRouter);
    }
});
```

In the app have something like this:
```js
'use strict';

module.exports = function (router, app) {
    router.use(loopback.static('../../static'));
    router.use(loopback.static('../../client'));
};
```

This allows the developer to easily work with the middleware phases without having to learn proprietary patterns in the middleware json.

Thanks for making it through this lengthy message :+1:

**Comment by bajtos** [comment]
The current implementation already provides solution for you. The value for each middleware key can be an array, in which case a new middleware instance will be registered for each item.

```json
{
  "files": {
    "loopback#static": [
      { "params": "$!../static" },
      { "params": "$!../client" }
    ]
  }
}
```

As for code-based registration, you can always call `app.middleware` to register your middleware in the appropriate phase. So for example, you can create a following boot script:

```js
module.exports = function(app, next) {
  app.middleware('files', app.loopback.static('../../static'));
  app.middleware('files', app.loopback.static('../../client'));
}
```

The point of moving the middleware configuration to a JSON file is to allow IDEs like StrongArc to build an interactive editor. (It's not implemented yet.) If you don't need IDE support, then you can always fall back to registering the middleware in `server/server.js`.

>  Loopback could load these modules passing in a router to which middleware is attached.

Note that each Router level adds about 100-200ms overhead to the request-processing time. We must keep the number of Routers as low as possible.

---

I am closing this issue as resolved, feel free to reopen it if you feel the current implementation still needs improvement.

**Comment by greaterweb** [comment]
Missed that part in the docs that you could use an Array, thanks for pointing it out.

I now see how the use of Router in the proposed solution can be a bit expensive. I employ a similar solution so I'll certainly refactor it a bit.

Thanks again!
