### ISSUE TITLE
.random() API Call for ORM

### ISSUE THREAD

**Issue by rdegges** [strongloop/loopback#1180]
Hi all, started using loopback recently, and am loving it.

One thing I'd love to see is a `.random()` model method. It'd be nice to occasionally select a random item from the datababase.

I know that in active record / Django / most other ORMs, it's possible to execute these sort of queries in different ways, and I figured it'd be worth a github issue.

Best,

-Randall

**Comment by NickvdMeij** [comment]
+1

**Comment by triniwiz** [comment]
:+1:  same here

**Comment by SyRenity** [comment]
+1

**Comment by pmoelgaard** [comment]
+1

**Comment by pmoelgaard** [comment]
for what it's worth, I solved it on my side by creating a mixin, it's by far the easiest way... I'm right now only using MySQL, so didn't add support for other connectors, but it would be easily done...

https://gist.github.com/bf1091d5827e85d5a27f.git

**Comment by go1dfish** [comment]
+1

**Comment by rdegges** [comment]
Well, that's definitely one way to close out issues.
