### ISSUE TITLE
Cannot create model without id property

### ISSUE THREAD

**Issue by komarik0** [strongloop/loopback#1181]
Model has id property by default so it's not possible to create model without id.

**Comment by prashantbaid** [comment]
+1 Same problem for me. @komarik0 your solution works. Wonder when this will be fixed.

**Comment by loay** [comment]
Hi @komarik0 @prashantbaid 
in order to create a model without a default id, you need to do the following:

in the model json file, please add the following
1)  "idInjection": false,
2) in your property that is not the defaulted id, add  "id": true

Example: 
```
  "name": "myModelName",
  "base": "PersistedModel",
  "idInjection": false,
  "properties": {
    "myModelFirstProperty": {
      "type": "string",
      "required": true,
            "id": true
    }
  },
```
_

**Comment by loay** [comment]
I am closing the issue. If you are still having a problem with that fix, please feel free to leave a comment and I will re-open. Thanks.
