### ISSUE TITLE
Removing attributes/values

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#1183]
As a result of https://github.com/strongloop/loopback/issues/1162#issuecomment-77481675 - I would like to raise the following concern: because `updateAttributes` performs a partial update, you'll risk not actually removing a property from the dataSource itself. I cannot really tell if this already works or not.

In any case, this should be properly tested.

**Comment by bajtos** [comment]
Yes, this is a real problem affecting offline sync (change replication) too.

**Comment by bajtos** [comment]
Here is a test case that works in MongoDB but does not work with Memory nor MySQL, the code is assuming the Person model from [test/manipulation.test.js](https://github.com/strongloop/loopback-datasource-juggler/blob/7dc0fcd26fc670a7dde76a39a76ce9885da96e8a/test/manipulation.test.js#L12-L23):

```js
// put this code to juggler's test/manipulation.test.js
Person.create({ name: 'a-name', gender: 'X' }, function(err, p) {
  if (err) return done(err);
  p.unsetAttribute('gender');
  p.save(function(err, px) {
    if (err) return done(err);
    Person.findById(p.id, function(err, found) {
      if (err) return done(err);
      (found.toObject().gender === undefined).should.be.true;
      done();
    });
  });
});
```

When I replace `p.unsetAttribute('gender')` with `p.gender = null`, the test passes in all three connectors mentioned above.

**Comment by bajtos** [comment]
To address this issue, @Amir-61 has implemented two new methods `replaceById` and `replaceOrCreate` that always replace all model properties. See https://github.com/strongloop/loopback/pull/2316 for the patch exposing them via REST API.
