### ISSUE TITLE
feature request: app.middleware handler only accepts function

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback#1190]
LoopBack's [`app.middleware`](http://apidocs.strongloop.com/loopback/#app-middleware) only [accepts a function](https://github.com/strongloop/loopback/blob/9a0267e87a51fc17109416a87f017956be3cac17/lib/server-app.js#L143) value for the `handler` parameter. As `handler` is ultimately passed to an [`app.use`](https://github.com/strongloop/loopback/blob/9a0267e87a51fc17109416a87f017956be3cac17/lib/server-app.js#L163) call it would be nice if the handler supported an `Array` of handlers much like [Express does](https://github.com/strongloop/express/blob/bf1980f1b4f863bf89db2d3066f79bd813bcfe05/test/app.use.js#L170-L196).

Poking around the code I see that this challenges the current implementation a bit but adding this feature could simplify defining custom middleware in the `middleware.json` file.

For example you could have:

`middleware.json`

``` json
{
  "initial": {
    "./middleware/initial": {}
  }
}
```

`./middleware/initial.js`

``` js
'use strict';
var app = require('../server');
var loopback = app.loopback;

module.exports = function initialPhaseMiddleware() {
    var middleware = [];

    if (app.get('env') === 'local') {
        middleware.push(app.loopback.logger('dev'));
    }

    middleware.push(loopback.compress());

    return middleware;
};
```

Related #1179

**Comment by ritch** [comment]
Closing because stale :(. Please speak up if you think this should be prioritize higher.
