### ISSUE TITLE
Return an object instead of an array for get collections

### ISSUE THREAD

**Issue by theofidry** [strongloop/loopback#1193]
Comment after reading [OWASP Security Guidelines](https://www.owasp.org/index.php/OWASP_AJAX_Security_Guidelines#Always_return_JSON_with_an_Object_on_the_outside).

I do not know if it's necessary, so I ask just in case.

**Comment by pthieu** [comment]
@theofidry: I believe for JSON returns, we always return as an object. If you see the server return JSON that's not enclosed in `{}`, please open a new issue with repro steps.

Going to close, thanks for the heads up on this.
