### ISSUE TITLE
Inconsistent API endpoint description.

### ISSUE THREAD

**Issue by theofidry** [strongloop/loopback#1195]
In the explorer, for a a model without any relation, all the API endpoints description are sentences without a dot at the end. For instance:

`PUT /Toys Update an existing model instance or insert a new one into the data source`

However, when I add a relation like the `hasMany` for instances, the new API endpoints added for my model have a dot at the end for some, and none for others. For instance:

`GET /Toys/{id}/exists Check whether a model instance exists in the data source`
`GET /Toys/{id}/prices Queries prices of Toy.`

Granted that it's a very small issue^^

**Comment by digitalsadhu** [comment]
I'm not seeing quite the same thing. Regardless of whether there is a relationship or not I'm seeing, for the most part, all descriptions displaying with a . at the end.

The exception I'm seeing is in the built in User model where:
`GET /Users/confirm Confirm a user registration with email verification token`
`POST /Users/logout Logout a user with access token`
and
`/Users/reset Reset password for a user with email`
are all missing the . at the end of the description.

I'm using loopback v2.18.0, perhaps something has changed?

**Comment by digitalsadhu** [comment]
yes, reverting loopback to v2.14.0 dramatically changes how many descriptions have . at the end. (not many)

So a full inventory of cases that still need to have a . added before we can close out this issue look to be:

GET /Users/confirm Confirm a user registration with email verification token
POST /Users/logout Logout a user with access token
POST /Users/reset Reset password for a user with email
