### ISSUE TITLE
REST API for creating REST APIs?

### ISSUE THREAD

**Issue by timbur** [strongloop/loopback#1197]
I apologize if this is the wrong place to ask about this.  I dove head first into LoopBack just yesterday and one of the things I would like to use it for is to allow users to specify models, relations, validation, acl, etc. for their own resources at somewhat arbitrary endpoints.

Arc does this, right?  So it's obviously something built into the core of the platform.  I was planning on seeing how Arc does it but for some reason it never loads beyond the header.

I previously achieved this functionality with my own home-brewed REST API, but I would like to make the switch to LB.  Previously, users would include an additional property called "addProps" when creating or updating the resource, which would of course describe additional properties that would work exactly as any other.  So for example, users could POST {name: 'foo', bar: 123, addProps: {bar: {type: 'number'}}} to /api/stuff and then query via /api/stuff?bar=123.  It's also preferable that users can store different additional properties at the same endpoint.

I feel like this functionality (or something like it) almost certainly exists within LoopBack somehow, but I can't seem to find it.

**Comment by raymondfeng** [comment]
Please check out https://github.com/strongloop/loopback-workspace. The module has metadata models and REST apis. It's the backend for [StrongLoop Arc](https://strongloop.com/node-js/arc/).

**Comment by timbur** [comment]
Thanks!  I've checked everything out and performed a few tests to see how feasible it would be to use the workspace API for my use-case, and so far it doesn't seem feasible in a live environment; i.e., when some model is created/updated/deleted, those changes aren't reflected until restarting the server.  So it looks like I'll need to figure out how to live-reload the models as they're changed, or possibly add some middleware that retrieves the proper models every time they're accessed.  Assuming the models are cached into memory upon booting, I feel like the middleware approach might scale better for thousands of custom models in the future?  

Also, Arc works now (had to disable ad blockers) but I didn't see any place to specify relations or ACL through that interface.  Is this only available for paying customers or is it just something not yet implemented?  I really like the step-by-step simplicity of modifying models via SLC, and if it doesn't exist already, I would like to transfer that process or something like it to the browser.  I realize Arc's Composer essentially does this, but Arc's web interface seems unnecessarily slow and clunky, though it could just be because I'm running everything on my laptop.

My gut tells me that the best approach here would be to configure everything such that all model definitions, properties, etc. are stored within a database rather than as flat JSON files.  This functionality already exists within LB, right?  Or is the workspace API only designed to work with JSON files?  I actually tried  adding a "db" key with a mongodb connector to loopback-workspace's datasources.json to see what would happen, and I get an error that seems to show the connector trying to use some non-existent method to read from JSON files (or just the default in-memory "db"?) rather than Mongo.

It would help me out a ton if someone could point me in the right direction, maybe through a handful of examples, plus explaining what Facets, PackageDefinitions, and ViewDefinitions are (or where the docs are for stuff like that), since I'm not 100% clear on how exactly the workspace API affects the main models.  For one, I've mounted the workspace onto my LB app at `/workspace`, but it doesn't seem to be detecting the models - e.g., `/workspace/api/ModelDefinitions` returns an empty array.

Also, any security caveats I should look out for when exposing this API to users?

**Comment by timbur** [comment]
Oh, forgot to mention, the following post shows a couple of nice examples that should help me with live reloads of models, but I guess my concern is whether or not it will scale to thousands of custom models and brings me back to my gut feeling that all of the model definitions, properties, relations, validation, acl, etc. should be stored in a database.

https://groups.google.com/d/msg/loopbackjs/8VvtawKHTpU/ymvJHbjxZ_YJ
