### ISSUE TITLE
adding indexes property in model.json causes mysql error in automigrate

### ISSUE THREAD

**Issue by chadvanklompenburg** [strongloop/loopback#1198]
Taken from common/models/campsite.json
```javascript
{
  "name": "Campsite",
  "plural": "Campsites",
  "base": "PersistedModel",
  "idInjection": false,
  "properties": {
    "code": {
      "type": "string",
      "required": true
    },
    "name": {
      "type": "string",
      "required": true
    },
    "description": {
      "type": "string",
      "required": true
    },
    "created": {
      "type": "date",
      "required": true,
      "defaultFn": "now"
    },
    "modified": {
      "type": "date",
      "required": true,
      "defaultFn": "now"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": [],
  "indexes": {
    "code_index": {
      "keys": { "code": 1 }
    }
  }
}
```
running automigrate triggers this error if indexes property is set in the model.

`Error: ER_KEY_COLUMN_DOES_NOT_EXITS: Key column 'undefined' doesn't exist in table`

Without indexes it runs/instantiates the database/tables as expected.

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by chadvanklompenburg** [comment]
Test project.  Mysql connection will have to be modified.
In the project directory running this should duplicate the potential bug I'm seeing. 
`node server/bin/automigrate.js`

https://github.com/chadvanklompenburg/loopback-test.git

**Comment by ernie58** [comment]
Is there any news on this? I'm having this issue as wel.
I've created a gist with my model definition files:
https://gist.github.com/ernie58/db2016996d3c7508e5c2

Running auto-migrate gives me this error:
{ [Error: ER_KEY_COLUMN_DOES_NOT_EXITS: Key column 'undefined' doesn't exist in table]
  code: 'ER_KEY_COLUMN_DOES_NOT_EXITS',
  errno: 1072,
  sqlState: '42000',
  index: 0 }

I'm using a has-many-through-model, to be able to set a unique index on the 2 foreign keys
I could have used a hasAndBelongsToMany, but then I don't have a model definition file to set the indexes

**Comment by raymondfeng** [comment]
It seems to be a bug in the loopback-connector-mysql that doesn't handle the index metadata correctly.

**Comment by sgilligan** [comment]
This looks like a workaround: https://github.com/strongloop/loopback-connector-mysql/issues/80

**Comment by raymondfeng** [comment]
Close as a dup of strongloop/loopback-connector-mysql#80
