### ISSUE TITLE
Add scope pagination features

### ISSUE THREAD

**Issue by mamboer** [strongloop/loopback#1200]
I'm trying to add pagination features to specified model's related scope object,
so i override the scopeRemoting method in model.js, line 598 , add some magic codes as the gist below:
https://gist.github.com/mamboer/d416af722a7f8c252fc0

This code snippet add a '__paginate__XXX' prototype method on models, cheers.

Hope that cool guys from loopback can integrate this feature, thanks!

**Comment by mamboer** [comment]
BTW:
This is only an enhancement on loopback's default pagination feature ,
the enhanced pagination method will response back a data structure like {"total":20,"items":[item1,item2]} to the client side, which is more friendly to most of the client side pagination components such as jquery.twbsPagination.js.

**Comment by pthieu** [comment]
@mamboer: Do you still need this enhancement officially merged? We have a template for enhancement feature request now, just click the `New issue` button. It might take a while to get to this, but you can speed up the process by opening your own PR.

Please re-open if you still need this.
