### ISSUE TITLE
MSSQL StoredProc support

### ISSUE THREAD

**Issue by dashby3000** [strongloop/loopback#1206]
The ability to "import" a StoredProc into a Model attached to MSSQL, so the following would work `MyModel.StoredProcName(param1, ... paramN, function(error, result))?`

**Comment by chandadharap** [comment]
TD Bank

**Comment by chandadharap** [comment]
Needs update from @dashby3000

**Comment by raymondfeng** [comment]
@dashby3000 Confirmed that native SQL approach is good for now.
