### ISSUE TITLE
geopoint radius filter

### ISSUE THREAD

**Issue by rptally** [strongloop/loopback#1207]
Currently the API supports a [near] filter relative to a lat, lng geopoint, such as

```
/homes?filter[where][location][near]=lat,lng
```

You can additionally support a result count, such as

```
/homes?filter[where][location][near]=lat,lng&filter[limit]=3
```

I'd like to request adding a filter by radius capability as follows:

```
filter[where][location][radius]=lat,lng,10m
```

where m indicates miles and k indicates kilometers ( 10m = 10 miles; 10k = 10 kilometers; default 10 = 10 miles).  This assumes you can continue to filter[limit] the result count.

![geo-radius-search](https://cloud.githubusercontent.com/assets/4174985/6625782/3e7ee9ee-c8c0-11e4-9aff-08b04be57d78.png)

Another approach could be

```
/homes?filter[where][location][near]=lat,lng&filter[radius]=10m&filter[limit]=25
```

The filter[radius] would be ignored if there wasn't a prior geopoint filter [near].

**Comment by ritch** [comment]
This has been suggested elsewhere (I think in a [PR to the mongo connector](https://github.com/strongloop/loopback-connector-mongodb/pull/68)). I don't think `radius` is appropriate though. I'd suggest something similar to `mongo`'s `$maxDistance`.

**Comment by rptally** [comment]
I can see that and it simplifies the request to better match existing db support.

    /homes?filter[where][location][near]=lat,lng&filter[distance]=10&filter[limit]=25

**Comment by eugenehp** [comment]
@rptally @ritch hey guys, what else needs to be done to have this merged to master?

**Comment by ritch** [comment]
> @rptally @ritch hey guys, what else needs to be done to have this merged to master?

@eugenehp 

Which PR are you referring to? I'm not aware of a PR that implements `$maxDistance` as discussed here. If you can point me to one I'll try and get it merged.

**Comment by voitau** [comment]
It seems like `maxDistance` is already available: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/geo.js#L17

And as far as I understood from the code: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1448-L1450 and https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/geo.js#L28-L79 filtering by distance is done as a post-processing step after retrieving all the results using other filters. Unless `buildNearFilter` is implemented for data source.

Here is a question then, for mongodb in particular, which seems not to have `buildNearFilter` implementation yet. If database has undefined number of records matching other filtering criterias (may be two, or may be millions), and only two of them are matching distance criteria, what would be the proper way to get only them and not others without damaging performance?

**Comment by eugenehp** [comment]
@voitau :+1: 

@ritch let us know, what do you think about previous comment. thanks!

**Comment by ritch** [comment]
> filtering by distance is done as a post-processing step after retrieving all the results using other filters. Unless buildNearFilter is implemented for data source

 I think you've nailed it here: mongo needs to implement buildNearFilter

@superkhau

**Comment by cfjedimaster** [comment]
So I hate to ask a tech question here - but apparently maxDistance is supported - but I'm not sure we actually document *how* you would use it in a REST-based URL filter. Got an example?

**Comment by ask10000** [comment]
@cfjedimaster 
I avoided going via a REST URL query method. Rather I have four URL parameters (lat,lng,radius and radiusType) to a remote method call - radius defaulted to `2000` and radiusType to `meters`, it works.

```

var loopback = require('loopback');

module.exports = function(Cafe) {
  Cafe.remoteMethod('nearLocation',
  {
    accepts:  [
                {arg: 'lat', type: 'number', required: true},
                {arg: 'lng', type: 'number', required: true},
                {arg: 'radius', type:'number', required: false, default:2000},
                {arg: 'radiusType', type:'string', required: false, default:'meters'}
              ],
    http:     {path: '/nearLocation', verb: 'get'},
    returns:  {arg: 'cafes', type: 'Object'}
  });

  Cafe.nearLocation = function(lat, lng, radius, radiusType, cb){
    var here = new loopback.GeoPoint({lat, lng});
    Cafe.find( {where: {location: {near: here, maxDistance:radius, unit:radiusType}}, limit:10},
                function(err, nearbyCafes) {
                      console.info(nearbyCafes); // [CoffeeShop, ...]
                      cb(null, nearbyCafes);
                }
             );
  }
};

```

**Comment by cfjedimaster** [comment]
Thanks - I finally figured it out myself. :)

**Comment by terehov** [comment]
@cfjedimaster Would you mind to share it with us? ;-)

**Comment by ask10000** [comment]
@terehov I have given an example above. It has worked for me. In my app I let the caller define the radius type (meters,  miles etc as distance unit) and radius value ( actual max distance in specified units), while picking up the lat long from phone's geolocation

**Comment by cfjedimaster** [comment]
@terehov I blogged about it here: https://strongloop.com/strongblog/working-with-geographical-data-in-your-api/

**Comment by loay** [comment]
Hi, is this issue fixed? I see the PR merged and also @cfjedimaster blog.
If not, please let me know. Thanks.

**Comment by pthieu** [comment]
Closing. Issue looks resolved. Please re-open if https://github.com/strongloop/loopback-connector-mongodb/pull/68 did not resolve this.
