### ISSUE TITLE
Client plug-ability for browser based HTTP agents

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1211]
It would be nice to be able to use angular's `$http` service (and other similar http clients provided by framworks such as ember, jquery, backbone, perhaps even plain browser xhr).

/cc @bajtos @kraman

**Comment by bajtos** [comment]
FWIW, this is important as it should help us to reduce the browser bundle size. For example, when running in Angular, we can use built-in `$http` and don't have to include the [request](https://www.npmjs.com/package/request) module.

**Comment by kraman** [comment]
+1
