### ISSUE TITLE
Replicate unset attributes

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1215]
- At the moment, DAO strips undefined attributes from the data sent to the database, see #1183.
 - Because we are encoding data sent to `bulkUpdate` as JSON, the update instructions don't contain undefined properties.

As a result, there is no way how to replicate the instance `{ name: 'foo' }` to a server that has an instance like `{ name: 'foo', custom: 'extra' }`.

**Comment by bajtos** [comment]
Workaround: enable `strict:true` for all replicated models, set `null` as the default value for all optional fields and never call `inst.unsetAttribute`.

**Comment by bajtos** [comment]
Note that this issue is simpler than #1183 because it is enough to fix `updateAll` to allow the caller to request that specific named properties should be removed (set to undefined). Once we have that available, we can modify `bulkUpdate` to remove any properties that are in the database but not in the updated data, because we already have the current data from the database.

**Comment by bajtos** [comment]
> It is enough to fix `updateAll` to allow the caller to request that specific named properties should be removed (set to undefined). Once we have that available, we can modify `bulkUpdate` to remove any properties that are in the database but not in the updated data, because we already have the current data from the database.

The fix described in my comment has a flaw: SQL connectors cannot distinguish between "undefined" and "null" values. When replicating changes from between a memory-backed datasource and an SQL-backed datasource, we have to convert any undefined values to null values. This conversion will modify the data and thus the checksum/revision, which will cause conflicts in the subsequent replication runs.

I am proposing to introduce a new mode called "superstrict":
 - Models can have only properties described in LDL - same as in the strict mode.
 - Properties cannot have `undefined` values. When property value is not provided, LoopBack will use `null`.

The important point is that models in the "superstrict" mode will treat undefined properties in the same way regardless of the connector used.

@ritch @raymondfeng @BerkeleyTrue thoughts?

**Comment by ritch** [comment]
> treat undefined properties in the same way regardless of the connector used.

Really we need to support the least common denominator functionality required by the combination of connectors you'd like to replicate between. Essentially this means we need to support treating properties the way SQL does. Meaning...

```js
// MyModel has a property b that is **NOT** nullable
MyModel.create({b: undefined}) // or null obviously
```
should error during validation.

> Cannot create model with value "undefined" for property b (not nullable)

Really what this means is that we need something like what you are proposing but specifically it should enforce SQL nullable validation (and property definition). Eg you must set `nullable` to `true` or `false`.

**Comment by ritch** [comment]
For the record I am a big **-1** on the name `superstrict`. Something less vague would be preferred.

Maybe `requireNullability` (stupid name but thats the idea).

**Comment by bajtos** [comment]
> Meaning...
> ```
// MyModel has a property b that is **NOT** nullable
MyModel.create({b: undefined}) // or null obviously
```
> should error during validation.

This is already implemented, "not nullable" = "required:true" and "nullable" = "required:false".

Here is what I need instead:

```js
// MyModel has a nullable (not required) property "b"
MyModel.create({}, function(err, inst) {
  expect(inst).to.have.property('b', null); // even when using Memory or MongoDB
});
```

I'll try to think about a better option name than superstrict. For the record, my idea was to extend the range of `strict` values with `strict: 'super'`. We already have `strict: 'throw'`. On the other hand, if we create a new setting independent of `strict`, then users can use this new setting in non-strict mode too, which may be an interesting feature too.

**Comment by bajtos** [comment]
@raymondfeng @ritch I am pondering the idea of forcing the users to enable both "strict" and "persistUndefinedAsNull" when tracking changes, what is your opinion on that?

**Comment by bajtos** [comment]
If we don't do the above, then I am proposing to implement the following:

> Fix updateAll to allow the caller to request that specific named properties should be removed (set to undefined). Once we have that available, we can modify bulkUpdate to remove any properties that are in the database but not in the updated data, because we already have the current data from the database.

Using the example above, when we are applying `{ name: 'bar' }` to an instance `{ name: 'foo', custom: 'extra' }`, I'd like to be able to call the following:

```js
MyModel.updateAll({ name: 'foo', custom: 'extra' }, {name: 'bar', custom: undefined }, { removeUndefined: false }, cb);
```

Unfortunately this will require support in connectors (MySQL, possibly Memory) too, so I am not sure if it's worth the effort.

Thoughts?

**Comment by bajtos** [comment]
We have agreed with @ritch and @raymondfeng that the current implementation is good enough for v1.0 release.
