### ISSUE TITLE
updateAttributes remote hook

### ISSUE THREAD

**Issue by thaiat** [strongloop/loopback#1216]
I don't seem to find a way to run a beforeRemote hook for the `updateAttributes` operation
Is this possible ?

**Comment by fabien** [comment]
`updateAttributes` is on the prototype: `beforeRemote('prototype.updateAttributes', ...)`

**Comment by superkhau** [comment]
See [`operation hooks`](http://docs.strongloop.com/display/LB/Operation+hooks). For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
