### ISSUE TITLE
SubClassing a Model

### ISSUE THREAD

**Issue by dashby3000** [strongloop/loopback#1220]
The process of using the `setup` method to allow a `Model` to inherit remote methods of another `Model` is not documented.

This pattern is seen in the `User` Model within LoopBack.

**Comment by crandmck** [comment]
I don't understand why you would want to use `Model.setup()` vs. `Model.extend()` which is [how we currently document](http://docs.strongloop.com/display/LB/Extending+built-in+models#Extendingbuilt-inmodels-ExtendingamodelinJavaScript) to extend a model programmatically.  What's the rationale?

**Comment by ritch** [comment]
@crandmck there is certainly a difference...

```
// extend
var MyModel = Model.extend('MyModel'); // will create a new Model (MyModel) extending properties, settings, and methods of the parent

Model.setup() // is called for you by loopback
```

You can implement `setup()` to do additional `Model` setup when a model is extended. Since `extend()` calls `setup()` this ensures that any extended model will be "setup". Here is an example where this is required:

```js
MyModel = Model.extend('MyModel');

MyModel.on('myEvent', function() {
  console.log('meep meep!');
});

MyExtendedModel = MyModel.extend('MyExtendedModel');

MyModel.emit('myEvent'); // nothing happens (no event listener)

// this is where `setup()` becomes handy

MyModel.setup = function() {
  var MyModel = this;
  // since setup is called for every extended model
  // the extended model will also have the event listener
  MyModel.on('myEvent', function() {
    MyModel.printModelName();
  });
}
```

**Comment by crandmck** [comment]
@ritch So presumably, we should also add `setup()` to the API docs, then as well, right?

**Comment by ritch** [comment]
No params.

**Comment by crandmck** [comment]
Added [Setting up a custom model](http://docs.strongloop.com/display/LB/Extending+built-in+models#Extendingbuilt-inmodels-Settingupacustommodel).  @ritch @dashby3000  PTAL
