### ISSUE TITLE
Remote methods break for models with long numerical ids

### ISSUE THREAD

**Issue by kblcuk** [strongloop/loopback#1230]
We use tweet ids as identifiers for tweets stored in our system.
Currently GETs fail, because remote methods try to deduct id type. So for instance /api/Tweets/576329482765791232 returns 404, whereas the tweet with that id is actually present.

Shouldn't remote methods creator (for instance here: https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L571) respect id type defined in model? I.o.w. I would expect that having

```
  "properties": {
    "id": {
      "type": "string",
      "id": true
    },
   ...
  }
```
in model definition json file would also be taken into account in remote methods.
Thanks!

**Comment by leolannenmaki** [comment]
Chiming in as well (I also work on the project in question).

Our current workaround is pretty ugly. We patch `any` to `string` in a couple of places. For example:

```
_.find(TweetModel.sharedCtor.accepts, {arg: 'id'}).type = 'string';
```

And then we overwrite remote methods like `findById` to `accept` `id` of type `string` instead of `any`.

So at least `PersistedModel.setupRemoting` and `ModelCtor.sharedCtor` should be made awere of the desired type of `id` instead of using `any`.

**Comment by fabien** [comment]
See: #1217 - probably a duplicate

**Comment by leolannenmaki** [comment]
Very nice! It's probably a duplicate and looks like this might be fixed already. We'll try out the fix. Thank you!

**Comment by kblcuk** [comment]
Yep, fix from #1217 works, as in the string type is respected. However, the #1217 seem to cause other problem -- id's not explicitly defined in model definition are treated as Number right now, whereas with version we're using (2.8.4) and with latest release they are passed as is to MongoDB (which then properly stores them as ObjectIds). 

I'll comment on this in the linked issue.

**Comment by superkhau** [comment]
@kblcuk Can I close this or do you still see other issues?

**Comment by kblcuk** [comment]
No, nothing apart from what I commented on in #1217 already (id's default to Number rather than whatever DB provides); since this is marked as duplicate, I guess it should be save to close it; I'll keep an  eye on the other issue for progress.
Thanks!

**Comment by superkhau** [comment]
No problem! Feel free to open this issue again if you run into issues again.
