### ISSUE TITLE
Built-in models: no indexes?

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#1231]
I've been scratching my head a bit, but is it actually true that none of the built-in models use indexes?

/cc @raymondfeng @bajtos

**Comment by Neil-UWA** [comment]
try this:
```
{
    ...
    "properties": {
        "email": {
            "type": "string",
            "index": {"unique": true}
        }
    }
    ...
}
```
also, you should run `autoupdate` to create `indexes`

**Comment by bajtos** [comment]
@fabien Can you be more specific please and describe which indices are you expecting on the builtin models?

**Comment by fabien** [comment]
Well, I would expect indices on any of the properties that get queried often, think ACL lookups, User `username` - things like that. How about relations, are we indexing foreign keys, for example?

**Comment by raymondfeng** [comment]
@fabien +1. We should by default mark foreign keys to be indexed.

**Comment by alemhnan** [comment]
@raymondfeng , any update for the indexes in the foreign keys?

**Comment by bajtos** [comment]
Possibly related, maybe a partial duplicate: https://github.com/strongloop/loopback/issues/3011

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be adding any new features.
