### ISSUE TITLE
`routes` middleware phase not firing?

### ISSUE THREAD

**Issue by jakerella** [strongloop/loopback#1232]
Hi! I generated a fresh LoopBack app using slc v3.0.4, then added the following to middleware.json:

```js
"routes": {
  "./middleware/status": {
    "enabled": true
  }
},
```

In the `/server/middleware/status.js` file I have the following:

```js
module.exports = function(options) {
    return function (req, res, next) {
        console.log('examining response!');
        next();
    };
};
```

I would expect that for each route hit the server console would display that message. I am following the [instructions in the docs](http://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Middlewarephases).

Unfortunately, that log message never shows up after navigating to `http://localhost:3000/explorer` and hitting "Try it out!" on GET /Users). However, if I place the middleware in the `initial` phase it does fire... a lot. So... I'm not sure what I'm missing here.

One side note, I'm actually trying to use the `routes:after` subphase, but I can't get either to work.

**Comment by raymondfeng** [comment]
Please use 'routes:before'. The `rest` middleware is added by `server/boot/rest-api.js` using `app.use()` which in turn registers the middleware using `routes` phase. Handlers in the same phase are executed by order of registration.

**Comment by bajtos** [comment]
This is expected behaviour. You are effectively doing this:

```js
app.get('/Users', function(req, res) {
  /* strong-remoting code call & return result of Users.find() */
});
app.use(require('./middleware/status')());
```

Routes don't call `next`, therefore your middleware is never executed by express.

This is a know express issue (feature?).

**Comment by bajtos** [comment]
However, if you were hitting a URL that does not exist, your middleware will be executed just before the 404 handler kicks in.

**Comment by bajtos** [comment]
In general, we point LoopBack users to ask questions in the mailing list. I am closing this issue as resolved. Feel free to add "needs doc" label if you think this is something to capture in the docs. Or even better, submit the docs change yourself :)

**Comment by jakerella** [comment]
@bajtos I see... that makes some amount of sense, but then how can I hook into the outgoing response object post-route handling?

**Comment by bajtos** [comment]
Regarding http://stackoverflow.com/questions/29169519/strongloop-loopback-how-to-customize-http-response-code-and-header - we would like to fix the 200 vs. 201 code for loopback 3.0. It's a breaking change, see https://github.com/strongloop/loopback/issues/360.

In the meantime, you can setup an "afterRemote" hook (per model).

AFAIK, Express (and thus LoopBack) don't provide any direct way how to modify the response object. You may be able to override Node's internal http response object to achieve what you need, but that's hacky. Below is a mockup code to illustrate the idea, I did not try it myself.

```js
module.exports = function(options) {
    return function (req, res, next) {
      if (/*this is NOT a request that should return 201 instead 200*/) {
        return next();
      }

      var statusCode = res.statusCode;
      Object.defineProperty(res, 'statusCode', {
        set: function(value) { statusCode = value === 200 ? 201 : value; },
        get function() { return statusCode; }
     });
     next();
   };
};

**Comment by crandmck** [comment]
@jakerella If I need to update docs for any of above, please reopen this and re-label as "doc".  N.B. the "needs doc" issue is for software issues that need associated doc work (vs. the issue to actually track the doc work).  I'm engulfed in work around Strong PM at the moment, otherwise I'd try to sort it out myself... :-)

**Comment by jakerella** [comment]
FYI, I implemented what I needed with a boot script:

```js
module.exports = function(app) {

  function modifyResponse(ctx, model, next) {
    var status = ctx.res.statusCode;
    if (status && status === 200) {
      status = 201;
    }
    ctx.res.set('Content-Location', 'the internet');
    ctx.res.status(status).end();
  }

  app.models.ModelOne.afterRemote('**', modifyResponse);
  app.models.ModelTwo.afterRemote('**', modifyResponse);
};
```

**Comment by jakerella** [comment]
@crandmck I'll open a new issue for documentation.

**Comment by lespacedunmatin** [comment]
Proposed this update to the documentation : https://github.com/strongloop/loopback.io/pull/828.
