### ISSUE TITLE
Document the functionality for middleware `route` phase better

### ISSUE THREAD

**Issue by jakerella** [strongloop/loopback#1234]
This pertains to the [documentation about using phases in middleware](http://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Middlewarephases). I've discovered through testing and discussions with people on issue #1232 that using the `route` phase is a bit tricky. Because of how LoopBack processes routes, if a route is matched to a path, then any middleware set on the `route` or `route:after` phase will never be reached. Thus there is no way to modify the result of a route using middleware. If the route is _not matched_, then the middleware will be hit, so the phase (and subphase) is valid, but not for valid model API endpoints.

However, if a developer does need to alter the response prior to the request being sent to the client, they can use an `afterRemote` hook on the model through a boot script:

```js
module.exports = function(app) {
  function modifyResponse(ctx, model, next) {
    var status = ctx.res.statusCode;
    if (status && status === 200) {
      status = 201;
    }
    ctx.res.set('Content-Location', 'the internet');
    ctx.res.status(status).end();
  }

  app.models.ModelOne.afterRemote('**', modifyResponse);
  app.models.ModelTwo.afterRemote('**', modifyResponse);
};
```

**Comment by hacksparrow** [comment]
@crandmck this issue is not confined to middleware, it involves components too. In fact, the issue faced by @jakerella is caused by the `loopback-component-explorer` component "hijacking" the request.

I have created a page  titled "Creating  components" under "Adding application logic", to document components in a Loopback app. It is different from https://docs.strongloop.com/display/LB/LoopBack+components, which documents built-in components. This one will talk about how components works, how to write one, and how to load them, like how middleware is explained in "Defining middleware".

I feel that routing details, which is a factor in both middleware and components, is best documented on a page of its own, instead including the details in the middleware and/or component docs.

**Comment by crandmck** [comment]
I think that makes sense.  We might want to consider putting the new article under "LoopBack components" in the navigation hierarchy, though.

**Comment by jakerella** [comment]
+1

**Comment by hacksparrow** [comment]
@crandmck let me get the docs done, then we can discuss where in the hierarchy they best fit in.

**Comment by crandmck** [comment]
OK... I just saw this, but I already moved it as I suggested.  It's easy enough to reorg if need be.

**Comment by hacksparrow** [comment]
@crandmck alright, no problem.

**Comment by crandmck** [comment]
Reviewed and edited https://docs.strongloop.com/display/LB/Routing

**Comment by jakerella** [comment]
@crandmck Looking at that URL, it doesn't seem like there is any information about the original issue here. Additionally, looking through this page: https://docs.strongloop.com/display/public/LB/Defining+middleware I don't see any information on the inability to do post-processing or a warning about middleware on `routes:after`.

Unless this issue has been addressed within the framework, I think we still need some information documented. basically, we need to warn people that they cannot add middleware on the `route` or `route:after` phase and expect it to execute _after_ the route is matched. Instead, it will be ignored because the route was already matched.

**Comment by crandmck** [comment]
OK, I didn't realize it worked that way.  Definitely seems odd.

Anyway, I added the following note:

> If you add middleware on the route or route:after phase, it will not execute after the route is matched. Instead, it will be ignored because the route was already matched.

To https://docs.strongloop.com/display/LB/Routing and https://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Routingmiddleware.  

Also,@hacksparrow added the following clarification to https://docs.strongloop.com/display/LB/Routing:
> Multiple middleware can be matched to handle the requests to a route, these matched middleware make up the middleware chain for the request. The request will pass through each middleware in the order they were loaded, unless one of the middleware in the chain terminates the propagation.

Does that take care of the issue?

**Comment by jakerella** [comment]
I think it would be nice to mention how to alter an outbound response, but that might be better in another section. I think what you have above is sufficient for this ticket.
