### ISSUE TITLE
[Error: Cannot find module 'loopback'] code: 'MODULE_NOT_FOUND' 

### ISSUE THREAD

**Issue by smusa** [strongloop/loopback#1236]
I am trying to get the API server on Openshift. I used "rhc app create MyApi https://raw.github.com/strongloop/openshift-cartridge-strongloop/master/metadata/manifest.yml mongodb-2.4" to create the API app on Openshift. It's up and running fine and i can explore the API fine. 

When i try to create the data model using "slc loopback:model" then i am getting following error:
Error loading module "loopback":
 { [Error: Cannot find module 'loopback'] code: 'MODULE_NOT_FOUND' }

ls -al app-root/repo/node_modules/ lists these modules "compression  errorhandler  loopback  loopback-boot  loopback-datasource-juggler  loopback-explorer  serve-favicon". 

What am i missing here?
thanks

**Comment by superkhau** [comment]
Is `strongloop` installed on the remote server? `npm install -g strongloop`. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
