### ISSUE TITLE
Move replication & sync to a standalone module

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1237]
Move replication & sync to a standalone module, this will enable us to version this component independently of the loopback core.

**Comment by ritch** [comment]
+1

@bajtos I'd like to do the initial creation of this module when the time comes.

**Comment by bajtos** [comment]
@ritch shall I assign the issue to you then? I am anticipating that this move will require some changes in loopback-boot , so that components can decide whether they should be called before the models are defined (new) or after all models and datasources and boot scripts were booted (current behaviour).
