### ISSUE TITLE
Update usage of "slc run" in docs.

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1239]
In most places where we use `slc run` currently in LoopBack docs, we should change to either:
- `slc start`
- `node .`

@sam-github to advise when one or the other makes sense.

**Comment by crandmck** [comment]
In most cases, we should just use `node .` in LB docs.

**Comment by sam-github** [comment]
I agree with @crandmck, we should always use `node .`, unless specifically discussing wanting to use the UI (arc) with the running app.

**Comment by superkhau** [comment]
@sam-github Should use the same recommendations for all the example apps (ie. use `node .` vs `slc run`)?

**Comment by DeniseLee** [comment]
hi @superkhau. I am a contract tech writer here. I am working to change the sample app docs to conform to use node . instead of slc run.

**Comment by superkhau** [comment]
@DeniseLee Sounds good. I will follow this convention when writing new examples.

**Comment by crandmck** [comment]
This is completed for docs (mostly).  I made one change on loopback.io.
Denise finishing up corresponding changes in READMEs.
