### ISSUE TITLE
How to use include filter and where filter in single query.

### ISSUE THREAD

**Issue by gowram** [strongloop/loopback#1240]
Hello there, 

I have some use case, that i want to query with two filters "include" and "where", i tried many ways but i did not get any result so far.

it's actually i need to get logged-in users role.

is there any other simple way to have it with?

Thanks & Regards
Rama

**Comment by raymondfeng** [comment]
Have you checked out http://docs.strongloop.com/display/LB/Include+filter#Includefilter-Includewithfilters? <http://docs.strongloop.com/display/LB/Include+filter#Includefilter-Includewithfilters?>
 
Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by raymondfeng** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs instead of github issues.
