### ISSUE TITLE
Make `loopback.template` server-side only

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1248]
Make `loopback.template` a server-only API, so that we can avoid including `ejs` in the browser bundle. This should save about 24kb from the un-minified bundle size.

See also #1256.

**Comment by ritch** [comment]
What if we had a module for generating a loopback app browserify bundle... It would allow you to opt out of certain features. Something like this:

```js
require('loopback-browserify').bundle({
  template: false, // false by default?
  ...
});
```

**Comment by ritch** [comment]
Either way I like the idea of removing this in the browser bundle... I doubt anyone uses it.
