### ISSUE TITLE
Scaffold a webapp project including website resources/assets

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/loopback#1253]
I find myself copying and pasting the following code into each project:

```
var express = require('express');
var path = require('path');
...
app.use(express.static(path.join(__dirname, '../client/www')));
```

Express and path used to be included by default. Is it possible to reinstate them or at least have a 'web app' flag on the slc loopback CLI?

**Comment by bajtos** [comment]
If you are using the recent project template, then you should configure your static middleware in `server/middleware.json`.

```json
{
  "files": {
    "loopback#static": {
      "params": "$!../client/www"
    }
  }
}
```

FWIW, you can also use `loopback.static` instead of `express.static` in your code.

> have a 'web app' flag on the slc loopback CLI?

Yes, that's the solution I like most.

**Comment by seanbrookes** [comment]
is the above documented somewhere?  I couldn't find it at the time

**Comment by seanbrookes** [comment]
out of curiosity why was express removed?  

- seems like loopback/express is like chocolate/peanut butter : they just go together

- are most LB projects non-express

**Comment by bajtos** [comment]
> is the above documented somewhere? I couldn't find it at the time

http://docs.strongloop.com/display/LB/Defining+middleware#Definingmiddleware-Usingbuilt-inmiddleware

`loopback.static` was always available.

> out of curiosity why was express removed?

loopback provides the same properties/methods as express does, we are copying everything from the express object to the loopback object. Even better, loopback 2.x includes properties that have been removed in express 4.x, e.g. `loopback.errorHandler` works in both LB 1.x and 2.x, while `express.errorHandler` works in 3.x only.

**Comment by digitalsadhu** [comment]
It's unclear to me what it would take to close this issue.

Is the requirement here to add:
```js
var express = require('express');
var path = require('path');
```
to the project template if and only if the user makes use of a cli flag?
eg.
```
slc loopback --express
```
?

**Comment by bajtos** [comment]
@seanbrookes What's your take? Do you consider this as still relevant?

I would rather tell users to configure their static middleware via json config file, instead of using `express` and `path`. However, I am biased as an author of that mechanism, that's why I'd like to hear from somebody with the user perspective.

**Comment by superkhau** [comment]
IMO, we should add a flag to the yeoman generator to scaffold new "webapp" projects that sets up the middleware automatically:

```
slc loopback --webapp
```

This in turn scaffolds the default loopback project, with the static section configured in `middleware.json` to point at the `client` dir, remove `/server/boot/root.js` and create and serve up `index.html` by default.

Thoughts?

**Comment by superkhau** [comment]
In addition, we could probably add another flag like:

```
slc loopback --angular
```

This could do the same as the `--webapp` flag and scaffold out the project, include the Angular SDK out of the box, etc.

**Comment by seanbrookes** [comment]
+1 on both thos suggestions

On Tue, Jul 7, 2015 at 1:04 PM, Simon Ho <notifications@github.com> wrote:

> In addition, we could probably add another flag like:
>
> slc loopback --angular
>
> This could do the same as the --webapp flag and scaffold out the project,
> include the Angular SDK out of the box, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback/issues/1253#issuecomment-119319827>
> .
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by bajtos** [comment]
+1 for supporting different project types in `slc loopback`.

FWIW, loopback-workspace already supports the concept of project templates (API server, HTML5 SPA, etc.), but there was only one template implemented so far.

Related issue: https://github.com/strongloop/generator-loopback/issues/85 Prompt for generation of basic client side assets
