### ISSUE TITLE
No 'Access-Control-Allow-Origin' header on 413 (Request Entity Too Large)

### ISSUE THREAD

**Issue by jcsmesquita** [strongloop/loopback#1257]
**1. Some info**
This might not be a loopback issue but I'm wondering if someone can point me in the right direction.
I have an AngularJS 1.3.15 client-side app making requests to my loopback api.

In the app, I intercept request results (with $httpProvider.interceptors) and interpret the status codes to display meaningful messages when the user does something - for example I intercept 401 responses telling the user he doesn't have authorization, 200 for when he saves something successfully and so on.

**2. The problem**
For example if the user tries to upload an image that's too big, the request payload will exceed my remoting limit and I am able to intercept a requestError but the status code always shows 0. Looking at the browser's console I see this:

```
PUT http://localhost:3000/api/Modules?id=9 413 (Request Entity Too Large)
XMLHttpRequest cannot load http://localhost:3000/api/Modules?id=9. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. The response had HTTP status code 413.
```

The problem is that if the server is offline, I also get status code 0 when intercepting requestError, so there's no way for me to distinguish an error connecting to the server between an error sending too much data. 

Is there any chance there's an issue with the express router middleware? I can't seem to find anyone that's having the same problem...

**Comment by bajtos** [comment]
First of all, try to setup a global CORS middeware in your server, that may prevent the  "Access-Control-Allow-Origin" problem. See https://github.com/strongloop/loopback-workspace/pull/192 for some inspiration and https://github.com/strongloop/loopback/issues/575 for related discussion.

However, I suspect the problem will be somewhere else. As you can see, the PUT request was sent to the server, is it possible that the second message is being printed from another (GET) request sent to the same URL?

If none of the above helps you to figure out the source of the problem, then we'll need you to provide a small application to reproduce the issue on our machines, see [Reporting Issues](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

**Comment by jcsmesquita** [comment]
Thank you so much @bajtos !! It works now!
I followed your advice about setting up global CORS - specifically I used the recommendation from @pasindud in https://github.com/strongloop/loopback/issues/575.

**Comment by bajtos** [comment]
Cool, I am closing this issue then.

**Comment by superkhau** [comment]
@bajtos I am closing this as its still left open.
