### ISSUE TITLE
Enable remoting of new scope methods

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#1258]
Recently `scope.findById`, `scope.findOne` and `scope.updateAll` have been added, this is a reminder to implement the corresponding remoting endpoint as needed. Suggestions for the REST API are welcome.

Also, documentation should be added - in both projects.

https://github.com/strongloop/loopback-datasource-juggler/pull/520
https://github.com/strongloop/loopback-datasource-juggler/pull/524
https://github.com/strongloop/loopback-datasource-juggler/pull/546

/cc @raymondfeng @ritch @crandmck

**Comment by crandmck** [comment]
@fabien  Currently, [scope.js](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/scope.js) is not in the API docs.  Should it be?  Are you talking about just API doc, or more than that?

Also: do you have an example of how to use this?

**Comment by bajtos** [comment]
@strongloop/loopback-dev I think this issue needs re-triage to find out whether it's still relevant. Could somebody take a look please?

**Comment by richardpringle** [comment]
@jannyHou, @Amir-61, @loay? You guys probably have the most experience with juggler.

**Comment by jannyHou** [comment]
@richardpringle I think it's more like exposing some existed APIs to remote endpoint. I am not quite familiar with exposing an endpoint, does that happen in strong-remoting or loopback core module?

**Comment by richardpringle** [comment]
@Amir-61 what does `scope.js` do? Is that for querying with the `{include: {where: scope:...` if so, we just need to check to see if you can use that filter from the api explorer.

**Comment by Amir-61** [comment]
>I am not quite familiar with exposing an endpoint, does that happen in strong-remoting or loopback core module?

Hey @jannyHou, Endpoints are exposed [here](https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js)

>@Amir-61 what does scope.js do? Is that for querying with the {include: {where: scope:... if so, we just need to check to see if you can use that filter from the api explorer.

Hey @richardpringle I have not worked on `scope.js` so I'm not sure if we have support for `{include: {where: scope:...`,  but it has support for `named scopes` and `default scopes`. Lets say you define `top5` named scope:

```
User.scope('top5': {limit: 5, order: 'age'});
```
Later on you can use your named scope and say:

```
User.top5(function(err, top5) {
...
});
```

would be equivalent to: 

```
User.find({limit: 5, order: `age`}, cb)
```

Also it seems you can can have default scopes in `package.json` which affect all your CRUD operations.

All of the above scope behaviour is [documented](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes). Also, I agree with @fabien that we need to document `scope.findById`, `scope.findOne` and `scope.updateAll`; I was not aware of these methods until now that I went through the mentioned PRs.

About enabling remote endpoints of them we can have discussion to see what team thinks about this... I'm not sure how useful they would be...Lets discuss it here

**Comment by richardpringle** [comment]
Interesting. I really think the REST API could use a little more clean-up before adding "scope" endpoints. For now, a user could add them manually. <- @bajtos, what do you think?

@crandmck, looks like @Amir-61 is the best person to team up with on this for documenting. My initial thought is not to include API docs since scope.js is in its own file but I could be wrong.

**Comment by bajtos** [comment]
> Interesting. I really think the REST API could use a little more clean-up before adding "scope" endpoints. For now, a user could add them manually. <- @bajtos, what do you think?

I am fine with that, especially since no LoopBack user was requesting this feature yet AFAIK.

**Comment by crandmck** [comment]
So @Amir-61 please let me know what you think we should add to the docs.  From this comment:

> we need to document `scope.findById`, `scope.findOne` and `scope.updateAll`.

We should add those along perhaps with examples (?)

**Comment by Amir-61** [comment]
Hey @crandmck,

Yes I believe at the very minimum we should have some examples of `scope.findById`, `scope.findOne` and `scope.updateAll` and explaining what they do; IMO they should be added in our documentation [here](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes). I put in planning and will take care of the documentation.

Thanks!

**Comment by crandmck** [comment]
Doesn't look like this was ever addressed.
