### ISSUE TITLE
principalId $owner has a security error?

### ISSUE THREAD

**Issue by dv3000** [strongloop/loopback#1259]
I think I found a bug, but I'm not 100% sure if it is my mistake ...

according to this line of code https://github.com/strongloop/loopback/blob/master/lib/application.js#L301-L306

I can do something like this:
http://localhost:8001/v1/collection/findOne?access_token=mycurrenttoken&filter[where][id]=id-2&id=id-1
or
http://localhost:8001/v1/collection?access_token=mycurrenttoken&filter[where][id]=id-2&id=id-1
and get a list
That makes the "findOne" validate the id 1 and the "filters" I seek the id 2

the model has this ACL:
{
"accessType": "*",
"principalType": "ROLE",
"principalId": "$everyone",
"permission": "DENY"
},
{
"accessType": "EXECUTE",
"principalType": "ROLE",
"principalId": "$owner",
"permission": "ALLOW"
}

someone else can reproduce the error??

sorry my english is verry poor

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by fabien** [comment]
@superkhau I'm pretty sure I posted an answer to this - did you delete it?

**Comment by superkhau** [comment]
@fabien No, but I may have closed it? Can you reference your fix to this issue?

**Comment by fabien** [comment]
@superkhau wish I could find it ... I searched for other issues by @dv3000 to see if I I posted to a duplicate, but apparently this is the only issue sofar.

**Comment by superkhau** [comment]
Ok, well it will show up eventually. I will leave it open for now until its found and referenced properly. TY.

**Comment by fabien** [comment]
@superkhau found it: https://github.com/strongloop/loopback/issues/238#issuecomment-87349410

**Comment by superkhau** [comment]
@fabien Thanks for finding the reference. I will close it since it is a duplicate of the issue you referenced.
