### ISSUE TITLE
Store property values encrypted

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1260]
We should provide an easy way how to encrypt property values on "save" and decrypt then on "load". At the moment, users have to implement operation hooks as a workaround.

Optionally, we can provide support for one-way encryption too, think of `User.password`.

https://github.com/strongloop/loopback-datasource-juggler/issues/441

> The reason is: I need to encrypt/decrypt data in database.
> So basically before save I can encrypt data with the key.
> But I can't decrypt data after find.
> I've tried with getter/setter but it doesn't work.

https://github.com/strongloop/loopback/issues/1226

> I need to manipulate data after it is validated ?
> For example, after all my fields are validated I'd like to encrypt some of them and persist into datastore.

**Comment by bajtos** [comment]
One of many possible implementations:

```json
{
  "name": "MyModel",
  "properties": {
    "name": { "type": "string", "encrypted": true }
  }
}
```

```js
module.exports = function(MyModel) {
  MyModel._encryptPropertyValue = function(propertyName, value, cb) {
    // custom encryption algorithm
    cb(null, encryptedPropertyValue);
  };

  MyModel._decryptPropertyValue = function(propertyName, encryptedValue, cb) {
    // custom encryption algorithm
    cb(null, value);
  };
}
```

**Comment by fabien** [comment]
As pointed out here https://github.com/strongloop/loopback/issues/1226#issuecomment-88398832 I think we should aim for an Encrypt mixin. Suggestion:

```
Model.mixin('Encrypt'); // will check property definitions for encrypted: true

// the above will use Model.encryptAttribute(attr, data, options, cb); which will have a default implementation (once you run the mixin), which you can then override

Model.mixin('Encrypt', { properties: ['data'] , encrypt: function(attr, data, options, cb) { ... } }');

// use the given properties; when an encrypt function is given, define Model.encryptAttribute with it.
```

**Comment by jmls** [comment]
has there been any more work on this ?

**Comment by bajtos** [comment]
@jmls https://github.com/strongloop/loopback-datasource-juggler/pull/599 added "loaded" hook and https://github.com/strongloop/loopback-datasource-juggler/pull/586 added "persist" hook. These two new hooks should allow you to implement encryption yourself. We don't have a higher-level support (like a mixin outlined above) yet.

**Comment by bajtos** [comment]
Let me add more context for anybody who may come across this closed issue: I personally think agree with @fabien that encrypted properties can and thus should be implemented as a mixin. Additionally, I think it's best to keep this mixin outside of loopback core, to allow independent versioning and easier maintenance.

If it turns out that the two hooks "loaded" and "persist" are not enough to support property encryption/decryption, then please open a new issue describing what is needed from LoopBack core to support this feature.
