### ISSUE TITLE
Examples missing for middleware documentation

### ISSUE THREAD

**Issue by jakerella** [strongloop/loopback#1261]
The [documentation page for middleware](http://docs.strongloop.com/display/public/LB/Defining+middleware) lists four examples in the TOC, but the actual content only has one (the "Static middleware"). Do we have these other examples? If not, we should remove them from the TOC:

> * Examples
  * Static middleware
  * Pre-processing middleware
  * Routing middleware
  * Error-handling middleware

**Comment by crandmck** [comment]
There are examples of all four at the end of the article.  I added links in the Overview section.  http://docs.strongloop.com/display/LB/Defining+middleware#Definingmiddleware-Overview

Does that help?

**Comment by jakerella** [comment]
Huh... was that there before? I'm sure that I didn't enter this issue without checking the rest of the article... oh well, it's there now. :)
