### ISSUE TITLE
Spike: pub sub connector

### ISSUE THREAD

**Issue by altsang** [strongloop/loopback#1266]
As an IBM developer using LoopBack, messaging and event driven interfaces are important to me so that I can do model logic based on pushed data. 

spike: a generalized pub-sub connector that meets IBM's use case:
- [ ] need to select message bus as a reference implementation - MQTT?
- [ ] reference implementation that extends the hook infrastructure for model mixin behaviors

**Comment by chandadharap** [comment]
Implementation spike, with details under SPike and stories in backlog.
