### ISSUE TITLE
Override Model.create method

### ISSUE THREAD

**Issue by saubhagyab** [strongloop/loopback#1274]
I have done my code like this 

module.exports = function(Model) {

  Model.on('attached',function(){
    Model.create = function(data,cb){
      cb(null,createPush(data));
    }
  });

  function createPush(data) {
         // some work to update the data now after that I want to post it but if I do the below code it will obviously go back to the hook. Any idea how can I post it after making my changes.
         Model.create(data, function callback(error,data){
         });
       }
};

**Comment by clarkorz** [comment]
If you want to do some work before creating model instance, then you should use `before save` hook, see http://docs.strongloop.com/display/public/LB/Operation+hooks

**Comment by saubhagyab** [comment]
Awesome Thanks a Ton @clarkorz .
