### ISSUE TITLE
Bulk Insert/Create

### ISSUE THREAD

**Issue by billinghamj** [strongloop/loopback#1275]
It'd be good if Loopback supported inserting many records at once. Many data sources would be able to insert records into their datasets far more efficiently. e.g. SQL databases can import all the records at once

Efficiency improvements could also be realized in validations. For example, where a model checks for uniqueness, all the instances could be checked at once rather than individually.

**Comment by mattapperson** [comment]
+1

**Comment by vladmiller** [comment]
+1

**Comment by mrbatista** [comment]
+1

Il giorno mar 19 mag 2015 21:21 Vlad Miller <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
+1

**Comment by ainesophaur** [comment]
+1

**Comment by GaryTowers** [comment]
+1

**Comment by csbenjamin** [comment]
I'm implementing a mixin #1435  that insert lft and rgt values (a tree table) based on others records in database. When I try insert several records at once, for example, suppose that the database is empty:

```js
Category.create([
    {name: 'category 1'},
    {name: 'category 2'}], function (err, categories) {
    console.log(categories);
});
```

The expected values for lft and rgt values are 
```js
[
  { name: 'category 1', lft: 1, rgt: 2, id: 1 },
  { name: 'category 2', lft: 3, rgt: 4, id: 2 }
]
```

but the `before save` event is triggered 2 times. The second time is for `{name:'category2'}` and in this moment the `category 1` is not in database yet and I don't know that the `category 1` is going to be inserted. So I can't calculate the right lft and rgt values. So what I got is

```js
[
  { name: 'category 1', lft: 1, rgt: 2, id: 1 },
  { name: 'category 2', lft: 1, rgt: 2, id: 2 }
]
```

I can see several ways to solve this problems. I'm listing them below:

* The `before save` hook to be called only 1 time with a array of instances
* When the `before save` is called for the second time, the first record is already in database
* Everything remains as it is, but pass more one property in ctx with all instances to be inserted, so I will know what is happening.

OBS: If there is something wrong with my English, please correct me.

**Comment by Neil-UWA** [comment]
+1

**Comment by dthib** [comment]
+1

**Comment by gruzilla** [comment]
+1

**Comment by sklyukin** [comment]
+1

**Comment by aiampogi** [comment]
+ 1
I tried inserting 999 records with a medium sized document and looping for 100 times inside to insert related documents. It took more than 30 minutes to accomplish.

**Comment by andirotter** [comment]
+1

**Comment by felipetoffolo1** [comment]
+1

**Comment by diaswrd** [comment]
+1

**Comment by djkoell** [comment]
+1

**Comment by ernie58** [comment]
+1

**Comment by demeyr** [comment]
+1

**Comment by psmarcin** [comment]
+1

**Comment by helsont** [comment]
+1

**Comment by senorcris** [comment]
+1

**Comment by esco** [comment]
+1

**Comment by AvivLander** [comment]
+1

**Comment by gustavomick** [comment]
+1

**Comment by akshayKrSingh** [comment]
+1

**Comment by mrkswrnr** [comment]
+1

**Comment by tnithinreddy** [comment]
+1

**Comment by dansterrett** [comment]
+1

**Comment by bialikover** [comment]
+1

**Comment by princecharmx** [comment]
bulk create is possible by passing the array of json models as,
var corporatePark1 = {"name": "one", "address":"mumbai"};
var corporatePark2 = {"name": "two", "address":"pune"};
app.models.CorporatePark.create(
    [corporatePark1, corporatePark2]
    , function (err, createdModel, created) {
      if (err) {
        console.error('error creating Model', err);
      } else {
        console.log("successfully created:" + createdModel);
      }

**Comment by Neil-UWA** [comment]
@princecharmx  loopback iterates each instance in the array and persist them into database one by one.

**Comment by princecharmx** [comment]
oh so @billinghamj  was pointing at the behind the scene processing, gottcha :)

**Comment by billinghamj** [comment]
Also specifically when you're using the REST API, it's very inefficient to open so many connections.

**Comment by jmwohl** [comment]
+1

**Comment by krissell** [comment]
+1

**Comment by groge** [comment]
+1

**Comment by achadha235** [comment]
+1

**Comment by elfazzo** [comment]
+1

**Comment by always-akshat** [comment]
+1

**Comment by ahmetcetin** [comment]
+1

**Comment by zbarbuto** [comment]
+1

**Comment by jannyHou** [comment]
@pantaluna Let's move our discussion here:
@bajtos suggests to use `Promise.all()` in https://github.com/strongloop/loopback/issues/2164#issuecomment-215645590
but when I run it I get this error:
```
jannyHous-MacBook-Pro:testPrimise jannyhou$ node .
/Users/jannyhou/lb/triage/testPrimise/node_modules/loopback-datasource-juggler/lib/dao.js:206
  var connectionPromise = stillConnecting(this.getDataSource(), this, arguments);
                                               ^

TypeError: this.getDataSource is not a function
    at DataAccessObject.create (/Users/jannyhou/lb/triage/testPrimise/node_modules/loopback-datasource-juggler/lib/dao.js:206:48)
    at Array.map (native)
    at Object.module.exports.app [as func] (/Users/jannyhou/lb/triage/testPrimise/server/boot/sample.js:22:20)
    at /Users/jannyhou/lb/triage/testPrimise/node_modules/loopback-boot/lib/executor.js:303:9
    at iterate (/Users/jannyhou/lb/triage/testPrimise/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at /Users/jannyhou/lb/triage/testPrimise/node_modules/loopback-boot/node_modules/async/lib/async.js:157:25
    at /Users/jannyhou/lb/triage/testPrimise/node_modules/loopback-boot/lib/executor.js:305:7
    at iterate (/Users/jannyhou/lb/triage/testPrimise/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at Object.async.eachSeries (/Users/jannyhou/lb/triage/testPrimise/node_modules/loopback-boot/node_modules/async/lib/async.js:162:9)
    at runScripts (/Users/jannyhou/lb/triage/testPrimise/node_modules/loopback-boot/lib/executor.js:293:9)
```

The whole sample script:
```js
module.exports = function(app) {
  "use strict";
  let Job = app.models.myuser;

  let jobs = [{
   "username": "me",
   "password": "hah",
   "email": "haha@gmail.com"
  }, {
   "username": "mee",
   "password": "hah",
   "email": "hahah@gmail.com"
  }];

  //let Job = app.models.Job;
  let jobsP = Job.create(jobs);

  // jobsP.then(jobs => {
  //   console.log('num jobs' + jobs.length);
  // });

  Promise.all(jobs.map(Job.create)).then(jobs => {
    console.log('num jobs' + jobs.length);
  });
};
```

I will take a look then.

**Comment by jannyHou** [comment]
@pantaluna I get `Promise.all()` work in a very tedious way:
```js
var mydata = jobs.map(function(job) {
    Job.create(job).then(function(job){ return job });
 });
Promise.all(mydata).then(jobs => {
   console.log('num jobs' + jobs.length);
});
```

**Comment by pantaluna** [comment]
@jannyHou Nice. But the actions are not executed "in parallel" in your example (I think - note I'm not an expert on Bluebird).

The Bluebird .mapSeries(), which I'm currently using in my project, is more compact and also works fine as shown in my sandbox project:
```
    Promise.mapSeries(inputDataSet, function (data) {
        return cl.create(data);
      })
      .then(results => {
         console.info('num results:' + results.length);
      })
      .catch(function (error) {
        console.error('ERROR Promise.mapSeries cl.create() FAILED.');
      });
```

It still does not explain the original issue.

**Comment by drdeath2609** [comment]
+1

**Comment by petrlyapin** [comment]
+1

**Comment by alexjoverm** [comment]
Just to simplify a bit @jannyHou answer code, it's also possible to do it in this way:

```javascript
Promise.all(
  jobs.map((job) => Job.create(job))
).then(jobsCreated => {
  console.log(jobsCreated)
})
```

**Comment by JaCkIsO** [comment]
+1

**Comment by yotamsha** [comment]
+1

**Comment by JoeShi** [comment]
+1

**Comment by chule143** [comment]
+1

**Comment by robertjamesmiller** [comment]
+1

**Comment by hieuit7** [comment]
+1

**Comment by WardBeullens** [comment]
+1

**Comment by MartinCerny-awin** [comment]
+1

**Comment by bajtos** [comment]
Please stop posting `+1` comments, they only spam the discussion. Click on the big yellow "thumbs up" button below the issue description instead, it will also allow us to filter issues by popularity.

You can also click on "Subscribe" button in the right menu-bar if you would like to be notified about updates. (I am not sure if up-voting an issue subscribes to notifications too.)

**Comment by superkhau** [comment]
Or even better, would someone like to submit a PR instead since there are quite a bit of +1's here.

**Comment by yagobski** [comment]
Any progress on this ?

I want to do something like this:

> Task.files.create(
                    { id: task.id },
                    filesObj,

                    function(response) { /* success */
.....

**Comment by nVitius** [comment]
Bulk importing of items is a really important feature, IMO. You can already pass in a JSON collection to the POST method on a PersistedModel, so there shouldn't be any interface changes.

**Comment by iliraga** [comment]
I just checked, it seems to work rightnow.


`
POST https://api.whatever.ch/students
[{
  "name": "refki"
}, {
  "name": "xhevdahire"
}, {
  "name": "peter fischli"
}]
`

and as a result, something like this is retrieved:

`
[
{ "id": "asdfasdfasdfsdf", name: "refki" },
{ "id": "some_id", "name": "xhevdahire" },
{ "id": "some_id", "name": "peter fischli" }
]
`

So it seems to work. Maybe this issue should be closed, and docs updated, otherwhise it leads to confusion. I luckily tested it, I already prepared to start implementing an own remote method to cover this.

**Comment by ahmetcetin** [comment]
@iliraga which version of loopback you're using? @superkhau can this issue be closed if it's already merged?

**Comment by iliraga** [comment]
@ahmetcetin Selam, this is what i have in my package.json:

```json
{
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-connector-mongodb": "^1.15.2",
    "loopback-datasource-juggler": "^2.39.0"
}
```

So loopback version **2.22.0**.

**Comment by ahmetcetin** [comment]
@iliraga tesekkurler, i'll give at a shot, i should update my loopback finally, this will be a good reason to update.

**Comment by alexjoverm** [comment]
@iliraga If you read the thread, this is about the under the good, when you pass an array of entities loopback iterates and creates them one by one instead of doing a bulk update. So the problem still remains.

**Comment by kjdelisle** [comment]
We'll be deferring this to the next major version of LoopBack, which will support batch operations.

**Comment by nVitius** [comment]
@kjdelisle Is there a roadmap for when that is planned to be released?

**Comment by kjdelisle** [comment]
It's still very much in the planning phase as far as I'm aware. @raymondfeng Do we have a rough timeline for 4.x?

**Comment by zbarbuto** [comment]
Would also love to see a roadmap of upcoming and future features/fixes

**Comment by eslynunez** [comment]
+1

**Comment by vegham** [comment]
+1

**Comment by bajtos** [comment]
Cross-posting https://github.com/strongloop/loopback/issues/2164#issuecomment-296859742
> @BoLaMN commented 4 days ago
> I believe this should be handled at the connector as most drivers allow for inserting an array in one database call but instead the dao layer does one by one

**Comment by bajtos** [comment]
FYI: https://github.com/strongloop/loopback-datasource-juggler/pull/1380 modified `create()` function to return Promise in batch mode too.

**Comment by konrad-garus** [comment]
`create([])` does not seem to be transactional, which pretty much makes it useless.

**Comment by lewie6** [comment]
is batch update currently possible in v4 ?

**Comment by marcoklein** [comment]
+1
