### ISSUE TITLE
strong-express-metrics: need to add more data to capture

### ISSUE THREAD

**Issue by altsang** [strongloop/loopback#1276]
As a Arc user using API Usage module, I'd like be able to see  Level 1, 2 and 3 data based on this design - https://strongloop.atlassian.net/wiki/display/SL/2015/03/09/API+Usage+Metrics+-+Arc+UX,

the raw data metrics - https://gist.github.com/cgole/05988b7d764327aa941f
needs to have:
- [ ] model
- [ ] instance ID (optional)
- [ ] remote Method (optional)

ex)
/api/car/1

would have the following keys added to the JSON...
model: car
instanceID: 1
remoteMethod:none

@kraman will be doing the aggregations to support 1 and 2, we will take a wait and see approach to level 3 drill down

**Comment by chandadharap** [comment]
To be clear, Level 1 and Level 2 are MVP for this first release.

**Comment by altsang** [comment]
no, actually just Level 2

On Fri, Apr 3, 2015 at 2:22 PM, chandadharap <notifications@github.com>
wrote:

> To be clear, Level 1 and Level 2 are MVP for this first release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback/issues/1276#issuecomment-89423474>
> .
>



-- 
Al Tsang
Co-Founder and CTO @ StrongLoop, Inc.

*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by bajtos** [comment]
> example
> /api/car/1
>
> would have the following keys added to the JSON...
> model: car
> instanceID: 1
> remoteMethod:none

The way how I am envisioning the implementation in https://github.com/strongloop/strong-remoting/pull/197, the field `remoteMethod` will be set to `findById`. I hope that's ok.

**Comment by bajtos** [comment]
For applications using `strong-remoting@2.16.0` or newer, `strong-express-metrics@1.1.0` is reporting the following loopback metadata via `record.loopback` object:

```
POST /api/Cars
  modelName: Car
  remoteMethod: create
  (instanceId not available)

PUT /api/Cars/123
  modelName: Car
  remoteMethod: prototype.updateOrCreate
  instanceId: 123

GET /api/Cars/123
  modelName: Car
  remoteMethod: findById
  instanceId: 123
```

I am calling this story done and assigning to @altsang for verification.

**Comment by altsang** [comment]
:+1: good to go here
