### ISSUE TITLE
Unhandled Exception when validating poorly formatted date strings

### ISSUE THREAD

**Issue by superdave2u** [strongloop/loopback#1277]
Loopback does not have validation for improperly formatted date strings. 

Returns a 500 error and not in the regular validation context with messages, status code, etc. 

Example of issue can be found here
https://github.com/superdave2u/loopback-bad-date-examples

**Comment by loay** [comment]
Hi, 
you can set your format validation. 
For example:
```
var formatValidation= /^(0[1-9]|1[0-2])\/(0[1-9]|1\d|2\d|3[01])\/(19|20)\d{2}$/ ;
UserModel.validatesFormatOf('date', {with: formatValidation, message: 'Must provide a valid date'});
```
More on validation in this document. Also, your link is not working anymore. 
Thanks. 

https://docs.strongloop.com/display/LB/Validating+model+data

**Comment by loay** [comment]
hi  @superdave2u 
I am closing this issue. If you are still running into the same issue, please feel free to leave a comment and I will re-open the issue. Thanks.
