### ISSUE TITLE
BelongsTo model synchronous get method return undefined

### ISSUE THREAD

**Issue by kidwm** [strongloop/loopback#1280]
In the end of this doc:
http://docs.strongloop.com/display/public/LB/BelongsTo+relations
```
var customer = order.customer();
Synchronously get the results of a previous get call to customer(...)
```
this synchronous function call return undefined, but another asynchronous one works.

**Comment by coodoo** [comment]
The synchronous one was returning result from cache in memory, if your app was restarted, you will have to use the async one.

**Comment by kidwm** [comment]
@coodoo Thanks! I've noticed that it says `Synchronously get the results of a previous get call to customer`
