### ISSUE TITLE
hide model properties for special remote mothod

### ISSUE THREAD

**Issue by jebai0521** [strongloop/loopback#1283]
Was there any way to hide properties for specific remote mothod, so i can get proper data for list request and instance request.

for example, a book model define like this
```
{
  "name": "book",
  "plural": "books",
  "base": "PersistedModel",
  "description" : "Redriect url for track",
  "properties": {
    "id" : {
      "type": "String",
      "id": true,
      "generated": true
    },
    "title": {
      "type": "Array",
      "required": true
    },
    "author": {
      "type": "Array",
      "required": true
    },
    "publisher": {
      "type": "String",
      "required": true
    },
    "publishDate": {
      "type": "Date",
      "required": true
    },
    "catalog": {
      "type": "Array",
      "required": true
    },
    "created": "date",
    "modified": "date"
  },
  "validations": [],
  "relations": {
  },
  "acls": [],
  "methods": []
}

```

for books request, i just want id and title property, just like 
```
[
    {
        id : 55234b63e5e1a48d67253f39,
        name : title1
    },
    {
        id : 55234b63e5e1a48d67253f40,
        name : title2
    },
    {
        id : 55234b63e5e1a48d67253f41,
        name : title3
    },
    {
        id : 55234b63e5e1a48d67253f42,
        name : title4
    }
]
```
for books/:id request, i want all properties.
 just like 
```
{
    id : 55234b63e5e1a48d67253f39,
    name : title1,
    author : [
        'jack',
        'rose'
    ],
    publisher : 'yellow river publisher',
    publishDate : '2015-04-07 11:13:39.760+08:00',
    catalog : [
        'chapter1',
        'chapter2',
        'chapter3',
        'chapter4',
        'chapter5'
    ]
}
```

i know, there was [hidden][1] section, it can hide some properties for remote method, but can not custom for different remote method.

thank you.

  [1]: http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Hiddenproperties

**Comment by clarkorz** [comment]
You can use `fields` option in filter, see http://docs.strongloop.com/display/public/LB/Fields+filter

You could also define a `scope` with `fields` option for your books request, see http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes

**Comment by superkhau** [comment]
@clarkorz's answer is correct. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
