### ISSUE TITLE
Using cloud database as a datasource

### ISSUE THREAD

**Issue by ketanbhatt** [strongloop/loopback#1286]
I came across this while developing an application myself. 
I am using a Database as a service (Orchestrate.io) which is supposed to be handling all my data. I wanted to build a REST API using Loopback and Orchestrate. 
Loopback because the model validations and scaffolded models are very useful.

There seemed to be no straightforward way to connect Orchestrate with Loopback, the one way I see is to overwrite EVERY function which makes a DB call.

**Comment by superkhau** [comment]
You can write your own connector for unofficial data sources. See http://docs.strongloop.com/display/LB/Building+a+connector

Closing.
