### ISSUE TITLE
Passing next URL into resetPassword function

### ISSUE THREAD

**Issue by daveh957** [strongloop/loopback#1288]
It would be great if when emitting the resetPasswordRequest event from User.resetPassword, you included all of the options in the event.  All of my login/registration processing includes the concept of a next URL, and I want to be able to send the user to wherever he was trying to go after doing a password reset.  If I could pass it into resetPassword in the body of the remote call and then get it back in the event handler, I could easily do that.

**Comment by simoami** [comment]
If you're using sessions, you could store a returnTo property into the session from the moment the user gets redirected to the login. from that point on the property is maintained in the session until you receive the forgotPassword event and then you can fetch this property back from the session.

fyi: there's already a middleware which does that for you:
https://github.com/jaredhanson/connect-ensure-login

**Comment by superkhau** [comment]
@daveh957 I believe @simoami's solution is a good suggestions. `connect-ensure-login` is good for situations like the one you describe.

**Comment by daveh957** [comment]
It's okay, but does not work if the user follows the reset link from a different browser or device.

**Comment by superkhau** [comment]
Have you seen my reset password example at https://github.com/strongloop/loopback-faq-user-management/blob/master/server/boot/routes.js#L76-L99? You can do whatever you want after you verify the user's password (I render a redirect link in this case, but you redirect the user without rendering anything).

**Comment by daveh957** [comment]
Yes, I saw the example when I originally wrote my code.  It was quite helpful.  Thank You.

My problem is at the point where I call User.resetPassword I know where the user wants to go next.  I need to put that information into an email so that when he completes the reset process I can send him on his way where he originially wanted to go.  So I would like to get that information from the resetPasswordRequest event that is triggered by the resetPassword method.  

This is literally one line of code.

Change 
```
              UserModel.emit('resetPasswordRequest', {
                email: options.email,
                accessToken: accessToken,
                user: user
              });
to
```
              UserModel.emit('resetPasswordRequest', {
                options: options,
                email: options.email,
                accessToken: accessToken,
                user: user
              });

in the function User.resetPassword in user.js.

Then I can do this when the event is fired:
~~~

  User.on('resetPasswordRequest', function(info) {
    var url = app.settings.baseUrl + '/reset-password' + '?access_token=' + info.accessToken.id;
    if (info.options.next) {
      url += ('&next=' + encodeURIComponent(next));
    }
    var html = 'Click <a href="' + url
      + '">here</a> to reset your password';

**Comment by simoami** [comment]
@daveh957 

Did you look into using the application's [current context](http://docs.strongloop.com/display/public/LB/Using+current+context)? You can store data temporarily and retrieve it at various execution points.

```
var ctx = loopback.getCurrentContext();
if(ctx) {
      ctx.set('returnTo', req.originalUrl || req.url || 'http://localhost:3000/');
}

// and then when you receive the event
User.on('resetPasswordRequest', function(info) {

    var url = app.settings.baseUrl + '/reset-password' + '?access_token=' + info.accessToken.id;
    var returnTo = ctx && ctx.get('returnTo');

    if (returnTo) {
      url += ('&next=' + encodeURIComponent(returnTo));
    }

    ...
  });

```

**Comment by superkhau** [comment]
@simoami's solution is a good alternative.

@raymondfeng @bajtos @ritch Thoughts?

**Comment by daveh957** [comment]
@simoami's solution works
