### ISSUE TITLE
OData compliance

### ISSUE THREAD

**Issue by prabhu** [strongloop/loopback#1290]
Any plans to make the REST interface OData (http://www.odata.org/) compatible?

**Comment by raymondfeng** [comment]
We have been watching OData. But there is no immediate plan to support it. One idea is to have a pluggable serializer/deserializer layer so that the HTTP req/res can be mediated based on the Content-Type/Accept headers.

**Comment by prabhu** [comment]
Thanks for the prompt reply. Its high on the list for an enterprise client of mine and is one of the reason why loopback (and node.js) was rejected completely from the proposal. It definitely looked like lot of work for one developer to add it.

**Comment by superkhau** [comment]
@raymondfeng Is this good to close?
