### ISSUE TITLE
aggregate $match need parsed into ObjectID

### ISSUE THREAD

**Issue by nvcken** [strongloop/loopback#1292]
I implenent code below to get sum group by productDetailId Id
productDetailId is function parameter is a string get from body post mehod 
example : var productDetailId = body.productDetailId = "5524d3157a5122c618933968"
```
var ObjectID = Product.getDataSource().ObjectID;
      var productCollect = Product.app.models.ProductDetail.getDataSource().connector
                  .collection(Product.app.models.ProductDetail.modelName);
      productCollect.aggregate([
        { $match : { productDetailId: ObjectID(productDetailId) }},
        {
          $group: {
            _id: { index: "$productDetailId" },
            sum: { $sum: "$price" }
          }
        }
      ], function(err, duration) {
```
My question is if         { $match : { productDetailId: ObjectID(productDetailId) }}    has no parse to ObjectID wrapper, It will not find out my productDetailId ( avalaible)

**Comment by superkhau** [comment]
Can you provide a sample repo to reproduce the issue?

**Comment by nvcken** [comment]
I had get rid by manua pre-process parse ObjectID.
