### ISSUE TITLE
Problem with composite keys

### ISSUE THREAD

**Issue by brunocascio** [strongloop/loopback#1295]
I have this model:

```
{
  "name": "Like",
  "base": "PersistedModel",
  "properties": {
    "recipeId": {
      "type": "number",
      "id": 1,
      "required": true
    },
    "userId": {
      "type": "number",
      "id": 2,
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "recipe": {
      "type": "belongsTo",
      "model": "Recipe"
    },
    "user": {
      "type": "belongsTo",
      "model": "User"
    }
  },
  "acls": [],
  "methods": []
}
```

and this SQL dump:

```
mysql> describe `Like`;
+----------+---------+------+-----+---------+-------+
| Field    | Type    | Null | Key | Default | Extra |
+----------+---------+------+-----+---------+-------+
| recipeId | int(11) | NO   | PRI | NULL    |       |
| userId   | int(11) | NO   | PRI | NULL    |       |
+----------+---------+------+-----+---------+-------+
2 rows in set (0.12 sec)
```

I found some errors when try to delete a model or getId.

```
Like.findById(1, function(err, like){
  like.getId() // this return only "recipeId" as id, bad.
})
```

Also, when destroying for example:

```
mysql> select * from `Like`;
+----------+--------+
| recipeId | userId |
+----------+--------+
|        1 |      1 |
|        1 |      2 |
+----------+--------+
2 rows in set (0.00 sec)
```

```
LikeModel.findOne({
                "where": {
                    "recipeId": rid, // 1
                    "userId": uid // 1
                }
            }, function(err, like){
                if (err) return fn(err)

                console.log(like) // here print { recipeId: 1, userId: 1 }

                like.destroy(fn); // this destroy ALL likes
            }); 
```

`like.destroy(..)` destroy ALL likes. I think it's related with `getId()`, because `getIdName()` only returned `recipeId`

**Comment by berill** [comment]
I'm also experiencing the same issue.

I have a model with the following properties:
```
"properties": { "userId": { "type": "string", "id": 1 }, "date": { "type": "date", "id": 2 },
```

and I'm trying to use findOrCreate:
```
const dayBlockId = {
      userId: userId,
      date: date,
    };
    const key = {
      and:
        [
          { userId: userId },
          { date: date },
        ],
    };
    DayBlock.findOrCreate(key, dayBlockId)
```

However, if I call multiple time the above code with same userId, but different date, the same DayBlock is returned.
As per the OP, calling getId() on the object return only the value of my first id column (i.e. userId)

**Comment by ericalves** [comment]
+1
the same problem.

**Comment by ericalves** [comment]
i saw persisted-model's source.. and the problem begin in getId() method.. because return away one column!

` PersistedModel.prototype.getId = function() {
    var data = this.toObject();
    if (!data) return;
    return data[this.getIdName()];
  };`

**Comment by nelsonec87** [comment]
+1

**Comment by perkd** [comment]
+1

**Comment by bajtos** [comment]
Possibly related: https://github.com/strongloop/loopback/issues/2046

**Comment by bajtos** [comment]
And also https://github.com/strongloop/loopback/issues/126

**Comment by biruks** [comment]
I am still seeing the issue. Even ```automigrate``` is not generating the right key combination  table even if you defined the model to be a composite key. FYI,  My backend is SQL server database

**Comment by bajtos** [comment]
I am afraid this is a limitation of LoopBack design and as such won't be fixed in 2.x/3.x versions. Please join the LoopBack 4 discussion here: https://github.com/strongloop/loopback-next/issues/1830
