### ISSUE TITLE
How re use model object got by Create

### ISSUE THREAD

**Issue by nvcken** [strongloop/loopback#1298]
Example
```
ModelA.create(obj, function(err, createdModelA){
    how to use createdModelA.find({ .....
    ..........
}
```

**Comment by clarkorz** [comment]
`Model.create()` and `Model.find()` are static method. `createdModelA` is an instance of `ModelA`, you can use `createdModelA.updateAttributes()` and `createdModelA.save()` on it.

Please check http://apidocs.strongloop.com/loopback/#persistedmodel for full API list.

**Comment by superkhau** [comment]
@clarkorz's answer is correct. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

Closing.
