### ISSUE TITLE
[3.0] strict mode cleanup

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1299]
I am proposing to make a following change in 3.0:

 - `strict` is not defined or is `false` - dynamic properties are supported (no change from 2.0)

 - `strict` is `true` - dynamic properties are stripped and a validation error is reported (same as `strict: 'validate'` in 2.0)

 - The other two modes from 2.0 (`strict: true` silently discarding values and  `strict: 'throw'`) should be removed.

@ritch @raymondfeng @fabien @clarkorz thoughts?

Tasks:
 - [ ] make the change
 - [ ] describe it in 3.0-RELEASE-NOTES.md
 - [ ] update https://docs.strongloop.com/display/LB/Model+definition+JSON+file

**Comment by clarkorz** [comment]
Does `strict: true` strip dynamic properties for schemaless datasource like mongodb?

**Comment by bajtos** [comment]
AFAIK, `strict: true` strips dynamic properties for all datasources, including mongodb. Note that the default value is connector-specific and defaults to `false`. SQL connectors set the value to `true` by default.

**Comment by davidcheung** [comment]
Info Placeholder
https://github.com/strongloop/loopback-datasource-juggler/blob/f102f6302b62640824584f50af3be52cdf7b27cd/lib/dao.js#L84-L104
