### ISSUE TITLE
The property does not exist in my model but is saved in the database when added via POST

### ISSUE THREAD

**Issue by GustavoRPS** [strongloop/loopback#1302]
Model Exemple:

    {
      "name": "Record",
      "base": "PersistedModel",
      "idInjection": true,
      "properties": {
        "date": {
          "type": "date",
          "required": true
        },
        "components": {
          "type": ["object"],
          "required": true
        }
      },
      "validations": [],
      "relations": {},
      "acls": [],
      "methods": []
    }

POST exemple:

    {
      "date": 23213310,
      "components": [["gps", true], [led, 0]],
      "asdasd": "12313123" // This property not exist but is saved in database
    }

MongoDB record

    {
      "date": 23213310,
      "components": [["gps", true], [led, 0]],
      "asdasd": "12313123" // This should not be here as it was not defined in the model
    }

**Comment by Neil-UWA** [comment]
set `strict` to `true` in your model.json

**Comment by GustavoRPS** [comment]
THX!

Failure on my part. Sorry.
