### ISSUE TITLE
conflict Stripe vs Loopback + getCurrentContext() return null

### ISSUE THREAD

**Issue by nvcken** [strongloop/loopback#1303]
https://github.com/stripe/stripe-node/issues/167

When I call Stripe charge, I can not get userInfo by loopback.getCurrentContext() in Stripe charge callback
```
console.log(currentContext.get('userInfo'));  <<<    // before stripe charge , it works
stripe.charges.create({
            amount: total_price, //convert to Cents
            currency: cur,
            source: token, 
            description: ""
          }, function(err, charge) {
              console.log(currentContext.get('userInfo'));  <<<    // Got undefined       
          });
```
Conclusion : getCurrentContext() return null so all Model query return null

**Comment by bajtos** [comment]
Please create a small application that we can use to reproduce the problem on our machine, see the [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

**Comment by loay** [comment]
Hi @nvcken 
Still having problem with the same issue?

**Comment by nvcken** [comment]
Hi @loay 
I worked around this by some trick at hook, I got conflict CurrentContext not only when integrate Stripe but also with another third-party like Google Cloud Storage.
But my loopback project had been pending long ago so I am not sure now.

**Comment by loay** [comment]
Thanks @nvcken 
Closing the issue for now. If you are still having any troubles, please feel free to leave a comment and I will re-open the issue.
