### ISSUE TITLE
error: has no method 'forEach'

### ISSUE THREAD

**Issue by codeyad** [strongloop/loopback#1307]
im trying to use a foreach in  the success callback of a relational query, i use someting like: 

modelObject.finOne({where:{id:myid},{include:{relation:'modelrel1', scope:{include:['modelrel2', 'modelrel3']}}}, function(succ){
  succ.modelrel1.forEach(data, i){
 ...  
}
})

when im triying this im getting this error even when this is an array, i don't know what really happen here

**Comment by raymondfeng** [comment]
Try `succ.toJSON().modelrel1.forEach(data, i) { ... }`

**Comment by codeyad** [comment]
thanks, that was solution.
