### ISSUE TITLE
Model relation link persisting body data.

### ISSUE THREAD

**Issue by watzing** [strongloop/loopback#1308]
Hi I've been using loopback for a week now and quite like it.

I've come across one issue when I was incorrectly using the link method produced in loopback-sdk-angular generated service. (After manually adding the fk params to the method, I hope a fix is on the way for this!) I was not passing in a separate empty object to the link method, so the id and fk params were being sent in the body, and interestingly these are being persisted to the Model1Model2 table. Both models are in strict mode, but any data can be added to the relation table via the body.

PUT /Model1/id/Model2/rel/fk with no body seems to work correctly.

PUT /Model1/id/Model2/rel/fk with body {id: id, fk: fk}
Produces this result in the Model1Model2 table:
````
{
    "Model1Id" : ObjectId("A"),
    "Model2Id" : ObjectId("B"),
    "fk" : "B",
    "_id" : ObjectId("A")
}
````
This creates a conflict on adding the second relation for a Model1Id. As a test I tried adding other data to the body, and this was also persisted to the relation table.

Thanks,
Dylan

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by loay** [comment]
Hi @watzing 
Closing this issue for now. If you are still having problems with the same issue, please provide a link to a test project so we can reproduce the issue and help out, and re-open the issue. 

Thanks
