### ISSUE TITLE
Login throws 401

### ISSUE THREAD

**Issue by rkmax** [strongloop/loopback#1314]
I'm using version 2.14.0. I have a Model without properties using `User` as base.

When I do a POST to /api/Model/login
```
{"email": "me@example.com", "password": "password", "ttl": 1209600000}
```
I get

```
{
  "error": {
    "name": "Error",
    "status": 401,
    "message": "login failed",
    "statusCode": 401,
    "code": "LOGIN_FAILED",
    "stack": "Error: login failed\n    at /home/julian/Development/example/node_modules/loopback/common/models/user.js:204:26\n    at /home/julian/Development/example/node_modules/loopback-datasource-juggler/lib/dao.js:1352:5\n    at allCb (/home/julian/Development/example/node_modules/loopback-datasource-juggler/lib/dao.js:1291:7)\n    at PostgreSQL.<anonymous> (/home/julian/Development/example/node_modules/loopback-connector-postgresql/lib/postgresql.js:741:7)\n    at null.<anonymous> (/home/julian/Development/example/node_modules/loopback-connector-postgresql/lib/postgresql.js:133:7)\n    at null.<anonymous> (/home/julian/Development/example/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17)\n    at bound (domain.js:254:14)\n    at runBound (domain.js:267:12)\n    at Query.handleReadyForQuery (/home/julian/Development/example/node_modules/loopback-connector-postgresql/node_modules/pg/lib/query.js:80:10)\n    at null.<anonymous> (/home/julian/Development/example/node_modules/loopback-connector-postgresql/node_modules/pg/lib/client.js:158:19)"
  }
}
```

**Comment by rkmax** [comment]
I found the problem here https://github.com/strongloop/loopback/blob/master/common/models/user.js#L116-L145, the function only returns the username or email but never the password

**Comment by rkmax** [comment]
the problem persist with the version 2.16.3

**Comment by raymondfeng** [comment]
The problem has nothing to do with https://github.com/strongloop/loopback/blob/master/common/models/user.js#L116-L145. The query is only used to find matching users with `username` or `email`. Then the password is checked against the found record.

Please run your app with `DEBUG=loopback:user node .` to see what causes the login failure.

**Comment by rkmax** [comment]
@raymondfeng Console returns

    loopback:user The password is invalid for user me@example.com +36s

I have in the following boot-script

```
  datasource.autoupdate('Model', function(err) {
     if (err) {
       console.log(err);
       return;
     }

     app.models.Model.create([
      {"email": "me@example.com", "password": "password"}
     ]);
   });
```

**Comment by rkmax** [comment]
@raymondfeng  thanks for all your help, was doing several things wrong. and everything works as it should

**Comment by paulespinosa** [comment]
@rkmax Do you remember what your issue was and how you resolved it? I'm getting the same error, and I'm wondering if I was doing the same wrong things.

**Comment by rkmax** [comment]
@paulespinosa I don't recall in this moment. but try with the debug string that Raymond said, it gave me clues to solve the issue

**Comment by amazinggadget** [comment]
Hai,
   I am getting the same as you have posted @rkmax . I followed what @raymondfeng have told. But I am getting the following in the console.

 loopback:user No matching record is found for user **foo@bar.com** 

But I have created this user already. I dont no what I am missing. Can someone help?
Thanks

**Comment by ihr-it-projekt** [comment]
@amazinggadget  i have the same problem. My user exists in mongo db an i get the message no record found at login process... . Have you solve the problem?

**Comment by angelo24983** [comment]
@amazinggadget any news on this topic? I am facing the same problem :(

**Comment by chrischnweiss** [comment]
Same probleme here. :-/
Any suggestions to resolve it?

**Comment by JulsRicketti** [comment]
I'm having a similar problem.
However I am able to make the first login, but then after I logout, on the second time I attempt to login I get the 401. Have no clue what's going on and it's been quite a frustrating journey.

**Comment by ZeeAzmat** [comment]
same error... any suggestions?

**Comment by wasiddiqui** [comment]
same error

**Comment by RJ-Fynydd** [comment]
I am getting the same error... I can't find anything on this issue to fix it. I installed loopback globally, made a new project with the cli, ran it without changing any files, posted a new user object to POST api/Users, got a 200 response back, and when I try to login with the same email and password I get Error "401 Error: login failed EVERY TIME." What am I doing wrong?

**Comment by ramirus** [comment]
Same probleme...
I find that POST api/Users don't save password to db
![image](https://user-images.githubusercontent.com/7149367/47642819-b3924200-db7a-11e8-892c-ef7cffb6fff3.png)
I don't understand why, so I recreated project with 2.x version of LoopBack and everything works as it should.

**Comment by matteo-pennisi** [comment]
I confirm, as @ramirus said, that _password_ is not saved into DB. Also _verificationToken_ is not present.
If I run from my pc everything works well, verificationToken and password are correctly created and inserted into DB. What's is going on? It worked a week ago :/

**Comment by matteo-pennisi** [comment]
**UPDATE**
I've found the reason why is working on local and not on the server. I think that is a problem with some packages from packages.json. It was using the dependencies from _yarn.lock_ file. Now I've set dependencies in packages.json without ^ and using the same version as .lock file and now is working. This is my packages.json file:
```
"dependencies": {
    "@google-cloud/storage": "^1.7.0",
    "algoliasearch": "^3.30.0",
    "compression": "^1.7.3",
    "cors": "^2.8.4",
    "helmet": "^3.13.0",
    "loopback": "^3.22.2",
    "loopback-boot": "2.27.1",
    "loopback-cascade-delete-mixin": "2.0.0",
    "loopback-component-explorer": "6.2.0",
    "loopback-component-storage": "3.5.0",
    "loopback-connector-mongodb": "3.6.0",
    "loopback-ds-timestamp-mixin": "3.4.1",
    "loopback-connector-remote":"3.4.0",
    "loopback-connector":"4.5.1",
    "loopback-datasource-juggler":"3.23.0",
    "loopback-phase":"3.3.0",
    "loopback-swagger":"5.7.0",
    "loopback3-xtotalcount": "^0.1.2",
    "redis": "^2.8.0",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^3.2.0"
  },
```
These is something wrong with one of these dependencies. However try to modify the file and write back if is working.

**Comment by errepy** [comment]
Thank you matteo, so the problem is the dependencies and you solvet only appling modifications to this file? so i need to erase the ^ on the file?

**Comment by matteo-pennisi** [comment]
Try to put in your packages.json exactly my versions (without ^), you can copy/paste it. Let me know if this solves :)

**Comment by errepy** [comment]
Ok. in my console some message apear  : 
Potential security alert: hidden/protected properties ["password","verificationToken"] are used in query.

then i see this,  somehow i think is related to this
User create default user is not working #1645

**Comment by errepy** [comment]
sorry this:
https://github.com/strongloop/loopback-datasource-juggler/issues/1645

**Comment by errepy** [comment]
i think my issue is this:
Hidden properties
A hidden property is not sent in the JSON data in the application’s HTTP response. The property value is an array of strings, and each string in the array must match a property name defined for the model.

An example of a hidden property is User.password:

common/models/user.json

{
  ...
  "properties": {
    ...
    "password": {
      "type": "string",
      "required": true
    },
    ...
  },
  "hidden": ["password", "verificationToken"],
  ...
}
If you want to white-list the fields returned instead of black-listing them, consider:

Applying the fields of the model’s defaultscope. This will operate at the database response layer so limiting your ability to check a field in the database that you otherwise would not wish exposed to the outside world (a private flag, for example).
Overriding your model’s toJSON method
See discussion of white-listing on GitHub.

**Comment by matteo-pennisi** [comment]
So the problem is related to loopback-datasource-juggler package. Actually I've made a rollback to "3.23.0" and is working.

**Comment by errepy** [comment]
In the file node_modules/loopback/common/users.json there is a place where 2 properties are setup as Hiden, this two properties are password and verification token, i erase this property and now it store the password, but , i don't know what kind of security issue i will have. for some reason if this two properties are setup as hiden it does not send on the json HTTP request.

**Comment by errepy** [comment]
now i can login and do stuff but i don't now what could be the security issue..

**Comment by RJ-Fynydd** [comment]
Okay new problem... After logging in and getting a token I am getting a 401 Authorization Required for `GET /api/Users` with the token in the header or using a token in the explorer.

**Comment by errepy** [comment]
> > So the problem is related to loopback-datasource-juggler package. Actually I've made a rollback to "3.23.0" and is working.
> 
> So after using the lb cli init (`lb`), I removed the node_modules folder and installed loopback-datasource-juggler at version 3.23.0 (`npm i -S loopback-datasource-juggler@3.23.0`) then did a final `npm i` and everything seem to be working correctly.

there we go!! this is the solution.. ok!! thank to all of you

**Comment by SeanFacer** [comment]
Downgraded loopback 3.24.0 -> 3.23.0 as you can't downgrade juggler otherwise
(https://github.com/strongloop/loopback/commit/f1c613ac07f686610702a7f36f13b40c643c91b2#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)

Downgraded loopback-datasource-juggler -> 3.23.0

Still getting same issue
