### ISSUE TITLE
Question: where are stored the ACL

### ISSUE THREAD

**Issue by rkmax** [strongloop/loopback#1315]
I recently start with loopback and testing I've defined the following ACL for a Model

```
"acls": [
  {
    "accessType": "*",
    "principalType": "ROLE",
    "principalId": "$unauthenticated",
    "permission": "DENY"
  },
  {
    "accessType": "EXECUTE",
    "principalType": "ROLE",
    "principalId": "$authenticated",
    "permission": "ALLOW",
    "property": "create"
  },
  {
    "accessType": "*",
    "principalType": "ROLE",
    "principalId": "$owner",
    "permission": "ALLOW"
  }
]
```

My question is: when I've created a new instance of that model, No records should be stored in the ACL table?

Because when I call manually 'SELECT * FROM acl;' I dont see any records

I'm using postgres as datasource and this are my model-config settings

```
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ]
  },
  "User": {
    "dataSource": "db",
    "public": false
  },
  "AccessToken": {
    "dataSource": "postgres",
    "public": false
  },
  "ACL": {
    "dataSource": "postgres",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "postgres",
    "public": false
  },
  "Role": {
    "dataSource": "postgres",
    "public": false
  },
  "Income": {
    "dataSource": "postgres",
    "public": true
  },
  "Expense": {
    "dataSource": "postgres",
    "public": true
  },
  "RegisteredUser": {
    "dataSource": "postgres",
    "public": true
  }
}
```

When I stored a Income model, the row is created in the table income but I can't see ACL. I'm pretty sure I'm doing something wrong, but what?

**Comment by superkhau** [comment]
They are stored in those corresponding tables, but may not be there yet until you actually execute something to trigger the creation. (ie. Log in a user and you will see the access token, but not before you actually logging a user in, etc). For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
