### ISSUE TITLE
Split model-config.json into multiple files

### ISSUE THREAD

**Issue by mamboer** [strongloop/loopback#1316]
model-config.json become too complex when having tons of models to be configured.
imagine that we have 30 to 50 models to be configured in 'model-config.json',
the file will become complex and hard to read.

I think loop-back should separate the model configurations by model, just like how we define the model itself. 

**Tasks**
- [ ] implement the feature in loopback-boot
- [ ] modify loopback-workspace to support this new project layout

**Comment by mamboer** [comment]
Someone post the same question at stackoverflow
http://stackoverflow.com/questions/27850297/loopback-spliting-model-config-json

**Comment by bajtos** [comment]
Thank you for reporting this idea, it makes sense to me. Perhaps we can modify loopback-boot to load model configuration from `server/model-config/*.json` files. Would that work for you?

**Comment by mamboer** [comment]
@bajtos 
That will be cool!

**Comment by juanscolari** [comment]
+1

**Comment by alexjoverm** [comment]
Looking forward to having this. What's the status?

**Comment by imravichaudhary** [comment]
+1

**Comment by leonllll** [comment]
+1
