### ISSUE TITLE
Disable remote method "deleteById"

### ISSUE THREAD

**Issue by jaulz** [strongloop/loopback#1317]
The following line of code does not work as expected:
` User.disableRemoteMethod('__deleteById__incomingRequests', false);`

In contrast this works:
` User.disableRemoteMethod('__create__incomingRequests', false);`

**Comment by raymondfeng** [comment]
Please try `User.disableRemoteMethod('__destroy__incomingRequests', false);`

**Comment by jaulz** [comment]
Okay, I got it. This one works:
```
  User.disableRemoteMethod('__delete__incomingRequests', false);
  User.disableRemoteMethod('__destroyById__incomingRequests', false);
```

Thanks anyway :)
