### ISSUE TITLE
lb-ng throws an error while generating lb-services.js

### ISSUE THREAD

**Issue by wzup** [strongloop/loopback#1320]
`Generate lb-services.js` throws an error.
I do what is written here: http://docs.strongloop.com/display/public/LB/Create+AngularJS+client#CreateAngularJSclient-Generatelb-services.js
I'm following your this tutorial step by step  http://docs.strongloop.com/display/LB/Getting+started+part+II

Here is my command line typing with error thrown. What is wrong? How to solve?

```
C:\Users\user\sbox\strongloop\hi>lb-ng server/server.js client/js/services/lb-services.js
Loading LoopBack app "C:\\Users\\user\\sbox\\strongloop\\hi\\server\\server.js"
__dirname: C:\Users\user\sbox\strongloop\hi\server
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
Generating "lbServices" for the API endpoint "/api"
Warning: scope User.accessTokens targets class "AccessToken", which is not exposed
via remoting. The Angular code for this scope won't be generated.
Warning: scope Reviewer.accessTokens targets class "AccessToken", which is not exposed
via remoting. The Angular code for this scope won't be generated.
Saving the generated services source to "C:\\Users\\user\\sbox\\strongloop\\hi\\client\\js\\services\\lb-services.js"
fs.js:568
  function strWrapper(err, written) {
                ^
Error: ENOENT, no such file or directory 'C:\Users\user\sbox\strongloop\hi\client\js\services\lb-services.js'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.writeFileSync (fs.js:1103:15)
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-sdk-angular-cli\bin\lb-ng:36:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

**Comment by seanbrookes** [comment]
check to make sure the directory exists that you want to write the output
to.

On Mon, Apr 20, 2015 at 11:21 PM, wzup <notifications@github.com> wrote:

> Generate lb-services.js throws an error.
> I do what is written here:
>
> Here is my command line typing with error thrown. What is wrong? How to
> solve? I'm following your tutorial
> http://docs.strongloop.com/display/LB/Getting+started+part+II
>
> C:\Users\user\sbox\strongloop\hi>lb-ng server/server.js client/js/services/lb-services.js
> Loading LoopBack app "C:\\Users\\user\\sbox\\strongloop\\hi\\server\\server.js"
> __dirname: C:\Users\user\sbox\strongloop\hi\server
> { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
> js-bson: Failed to load c++ bson extension, using pure JS version
> { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
> js-bson: Failed to load c++ bson extension, using pure JS version
> { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
> js-bson: Failed to load c++ bson extension, using pure JS version
> { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
> js-bson: Failed to load c++ bson extension, using pure JS version
> Generating "lbServices" for the API endpoint "/api"
> Warning: scope User.accessTokens targets class "AccessToken", which is not exposed
> via remoting. The Angular code for this scope won't be generated.
> Warning: scope Reviewer.accessTokens targets class "AccessToken", which is not exposed
> via remoting. The Angular code for this scope won't be generated.
> Saving the generated services source to "C:\\Users\\user\\sbox\\strongloop\\hi\\client\\js\\services\\lb-services.js"
> fs.js:568
>   function strWrapper(err, written) {
>                 ^
> Error: ENOENT, no such file or directory 'C:\Users\user\sbox\strongloop\hi\client\js\services\lb-services.js'
>     at Error (native)
>     at Object.fs.openSync (fs.js:502:18)
>     at Object.fs.writeFileSync (fs.js:1103:15)
>     at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-sdk-angular-cli\bin\lb-ng:36:6)
>     at Module._compile (module.js:460:26)
>     at Object.Module._extensions..js (module.js:478:10)
>     at Module.load (module.js:355:32)
>     at Function.Module._load (module.js:310:12)
>     at Function.Module.runMain (module.js:501:10)
>     at startup (node.js:129:16)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback/issues/1320>.
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by superkhau** [comment]
Here is a good explanation in the Angular example: https://github.com/strongloop/loopback-example-angular#11-generate-lb-servicesjs

Are you on the latest version of LoopBack? Run `slc update` and try the `lb-ng` command again.

**Comment by wzup** [comment]
Yes, the issue was because there was no `client/js/services` directory. When I manually created it, `lb-ng server/server.js client/js/services/lb-services.js` command finished successfully.

But in tutorial it is said:

> This command creates `client/js/services/lb-services.js`

so it is not clear whether  the command creates the directory or you have to create it explicitly manually.

**Comment by superkhau** [comment]
@crandmck Can we change the wording in the tutorial to be more explicit?

**Comment by crandmck** [comment]
Added `mkdir` command to the tutorial to create the dir: http://docs.strongloop.com/display/LB/Create+AngularJS+client#CreateAngularJSclient-Generatelb-services.js

**Comment by superkhau** [comment]
@crandmck TY

@wzup ^
