### ISSUE TITLE
Rest API: DELETE method always returns 204

### ISSUE THREAD

**Issue by Kampfgnom** [strongloop/loopback#1322]
When calling DELETE on a resource, the response code is always 204 with an empty body, independently from whether the resource exists or not, or if it has been deleted or not (headers omitted for brevity):

````
$ curl -i http://localhost:3000/api/TodoLists
HTTP/1.1 200 OK
[]

$ curl -i -X PUT http://localhost:3000/api/TodoLists
HTTP/1.1 200 OK
{"id":"27e2ea50-e814-11e4-8782-29c27147e8f9"}

$ curl -i http://localhost:3000/api/TodoLists
HTTP/1.1 200 OK
[{"title":null,"id":"27e2ea50-e814-11e4-8782-29c27147e8f9","systemUserId":null}]

$ curl -i -X DELETE http://localhost:3000/api/TodoLists/asd
HTTP/1.1 204 No Content

$ curl -i http://localhost:3000/api/TodoLists
HTTP/1.1 200 OK
[{"title":null,"id":"27e2ea50-e814-11e4-8782-29c27147e8f9","systemUserId":null}]

$ curl -i -X DELETE http://localhost:3000/api/TodoLists/27e2ea50-e814-11e4-8782-29c27147e8f9
HTTP/1.1 204 No Content

$ curl -i http://localhost:3000/api/TodoLists
HTTP/1.1 200 OK
[]

$ curl -i -X DELETE http://localhost:3000/api/TodoLists/27e2ea50-e814-11e4-8782-29c27147e8f9
HTTP/1.1 204 No Content
````

I see the same behaviour in the API-explorer and my (currently in development) Qt-Client.

Thanks for any help.

**Comment by superkhau** [comment]
@Kampfgnom I've verified your observations and 204 is always returned as you described. Escalating to "bug" status.

**Comment by fabien** [comment]
@raymondfeng we should really get this fixed, see also: https://github.com/strongloop/loopback/issues/1543#issuecomment-124330089

I would suggest a config option: `deleteInfo` as well as `Model.settings.deleteInfo` or something like that to enable it. Ideally I would like such option to work like this: https://github.com/strongloop/loopback-connector-mongodb/pull/164#issue-96759406

**Comment by raymondfeng** [comment]
Sure. @superkhau Can you take this one? It's very similar as the work you did for update.

**Comment by superkhau** [comment]
Assigned to myself so we can prioritize during sprint planning.

/cc @chandadharap

**Comment by superkhau** [comment]
- [ ] Functional test the above endpoints
- [ ] Escalate to bug status depending on the results of the functional tests
- [ ] Make functional tests pass
  - [ ] Isolate where the error is coming from
  - [ ] Add the fix
