### ISSUE TITLE
Use Case: ability to disable that Access Tokens are accepted when in an URL

### ISSUE THREAD

**Issue by OwenBrotherwood** [strongloop/loopback#1326]
Use Case: 
- ability to disable that Access Tokens are accepted when in an URL
- alternativly, possibility to enforce elsewhere as an alternative

It may be such that it is not possible to disable the use of Access Tokens when sent in an URL.
As to if one can enforce in a model is unknown.

Addresses a case if the use of URL (or cookie) based Access Tokens are not allowed.

---

### Implementation for options.searchDefaultTokenKeys

---

```
$ mocha -g 'api.*token'

  api:loopback:middleware:token(options)
    loopback.token({})
      V header (125ms)
      Breaking change
        V None
    options
      searchDefaultTokenKeys:[true|false]
        Normal usage: false for use case, restrict location of token
          Example, token in header
            V options.headers is empty, true (46ms)
            V options.headers has header, false
        Unormal usage: testing or unknown usage
          Example, token in header
searchDefaultTokenKeys is false and no headers: no token keys will be found
            V options.headers is empty, false
        Breaking change
          V None

  6 passing (297ms)
```

---

### Compare master

https://github.com/strongloop/loopback/compare/master...sloopback:loopback-issue-1326?expand=1

**Comment by OwenBrotherwood** [comment]
The Use Case is possible input to https://github.com/strongloop/loopback/issues/1091

**Comment by bajtos** [comment]
This should be relatively easy to implement as a new configuration option for `loopback#token` middleware. The options are processed in [common/models/access-token.js](https://github.com/strongloop/loopback/blob/f93590de1bab0b19c00f2c0a5956243e2776d58e/common/models/access-token.js#L163-L173).

**Comment by OwenBrotherwood** [comment]
@bajtos 
I will probably try an option.noConcat around the concats.
This means specific enablement of type/value with enableAuthentication (also for previous default values)

Exposing the parameter that are used in enableAuthentication could also allow a better audit of a (future) loopback AAA model that contains the type and text used for tokens in the Authentication /Authorization

Effected doc
- http://docs.strongloop.com/display/public/LB/Introduction+to+User+model+authentication
  -- investigate how set token works ie cookie/url/header ...
- http://docs.strongloop.com/display/public/LB/Making+authenticated+requests

**Comment by OwenBrotherwood** [comment]
@bajtos 
On the pull train @ https://github.com/strongloop/loopback/pull/1347
@crandmck 
with a small doc example in the pull :)

**Comment by OwenBrotherwood** [comment]
@crandmck 
FYI : I wanted to add a small remark about the use of [npm/git behind a firewall](http://stackoverflow.com/questions/15903275/git-is-blocked-how-to-install-npm-modules)  which caused me a delay when I first started in the wiki. 

Although _some_ pages can be Edit(-ed) by community, [installationtroubleshooting](http://docs.strongloop.com/display/SL/Installation+troubleshooting#Installationtroubleshooting-Errorswithnpm) was not one of them

**Comment by crandmck** [comment]
@OwenBrotherwood Yes, we only allow editing of articles in the LoopBack (LB) space.  I added a note about this: http://docs.strongloop.com/display/SL/Installation+troubleshooting#Installationtroubleshooting-Firewallissues
Have a look and let me know if I got it right--thanks.

**Comment by OwenBrotherwood** [comment]
@crandmck 
Looks good :)

**Comment by crandmck** [comment]
ty!

**Comment by bajtos** [comment]
Reopening, this GH issue is tracking a feature request, not a doc update. See also #1347

**Comment by crandmck** [comment]
Oops, sorry!

**Comment by OwenBrotherwood** [comment]
The pull request for this option is closed (https://github.com/strongloop/loopback/pull/1347#issuecomment-100115673)
Work continues https://github.com/OwenBrotherwood/loopback and this issue is used if I need help.
ETA for the review of a possible pull request is within the next few days.

**Comment by OwenBrotherwood** [comment]
```
$ diff loopback/common/models/access-token.js LOOPBACK.SAFE/loopback/common/mod
els/access-token.js
171,173c171,176
<     params = params.concat(['access_token']);
<     headers = headers.concat(['X-Access-Token', 'authorization']);
<     cookies = cookies.concat(['access_token', 'authorization']);
---
>     // https://github.com/strongloop/loopback/issues/1326
>     if (options.searchDefaultTokenKeys !== false) {
>       params = params.concat(['access_token']);
>       headers = headers.concat(['X-Access-Token', 'authorization']);
>       cookies = cookies.concat(['access_token', 'authorization']);
>     }
```

**Comment by OwenBrotherwood** [comment]
@bajtos 
Can you check my repo before I create a pull request?

- Implement options.searchDefaultTokenKeys
  - https://github.com/OwenBrotherwood/loopback-pr/blob/1917cbcf578624a99c6b150de6395424dc0c3910/common/models/access-token.js?#L171-176
- Marker a problem
  - https://github.com/OwenBrotherwood/loopback-pr/blob/loopback-issue-1326/server/middleware/token.js?#L82-84
- Tests
  - https://github.com/OwenBrotherwood/loopback-pr/blob/1917cbcf578624a99c6b150de6395424dc0c3910/test/api-loopback-token-searchDefaultTokenKeys.test.js
    - https://github.com/OwenBrotherwood/loopback-pr/blob/1917cbcf578624a99c6b150de6395424dc0c3910/test/lib/lib-loopback-token-searchDefaultTokenKeys.js

**Comment by OwenBrotherwood** [comment]
FIXME?
https://github.com/OwenBrotherwood/loopback-pr/blob/00996fc41fc6716973cb75f8eba2cd4407a5796d/server/middleware/token.js?#L84-L88

FIXME
https://github.com/OwenBrotherwood/loopback-pr/blob/00996fc41fc6716973cb75f8eba2cd4407a5796d/server/middleware/token.js?#L59-69

**Comment by OwenBrotherwood** [comment]
- https://github.com/strongloop/loopback/compare/master...OwenBrotherwood:loopback-issue-1326
  - Output of Debug=*.*.*.token mocha -g AccessToken
    - https://github.com/strongloop/loopback/blob/8c2b4b9ed619d3eb391475432a6f019b4ed5e351/test.txt

```
$ mocha -g AccessToken


  AccessToken
    V should auto-generate id
    V should auto-generate created date
    V should be validateable
    .findForRequest()
      V supports two-arg variant with no options

  AccessToken api:loopback:middleware:token(options)
    loopback.token({})
      V header authorization (109ms)
    options.searchDefaultTokenKeys:[true|false]
      normal usage for options.searchDefaultTokenKeys
        V header, headers has header, searchDefaultTokenKeys is false (47ms)
        V header, headers is empty, searchDefaultTokenKeys is true
      normal usage when not using options.searchDefaultTokenKeys
        V header, headers is empty, searchDefaultTokenKeys is undefined
      unnormal usage: for testing purposes, or other strange usages
        V header, headers is empty, searchDefaultTokenKeys is false

  User
    User.login
      V Login a user using a custom createAccessToken
      V Login a user using a custom createAccessToken with options
    ctor
      V exports default AccessToken model


  12 passing (438ms)
```

**Comment by OwenBrotherwood** [comment]
@bajtos I think we need you on https://github.com/strongloop/loopback/pull/1373

**Comment by OwenBrotherwood** [comment]
Implementation patch for options.searchDefaultTokenKeys
```
diff --git a/common/models/access-token.js b/common/models/access-token.js
index 7313712..27cf520 100644
--- a/common/models/access-token.js
+++ b/common/models/access-token.js
@@ -168,9 +168,12 @@ module.exports = function(AccessToken) {
     var length;
     var id;
 
-    params = params.concat(['access_token']);
-    headers = headers.concat(['X-Access-Token', 'authorization']);
-    cookies = cookies.concat(['access_token', 'authorization']);
+    // https://github.com/strongloop/loopback/issues/1326
+    if (options.searchDefaultTokenKeys !== false) {
+      params = params.concat(['access_token']);
+      headers = headers.concat(['X-Access-Token', 'authorization']);
+      cookies = cookies.concat(['access_token', 'authorization']);
+    }
 
     for (length = params.length; i < length; i++) {
       var param = params[i];
diff --git a/server/middleware/token.js b/server/middleware/token.js
index d9e0c1a..e80eb56 100644
--- a/server/middleware/token.js
+++ b/server/middleware/token.js
@@ -61,6 +61,7 @@ function escapeRegExp(str) {
  * @property {Array} [cookies] Array of cookie names.
  * @property {Array} [headers] Array of header names.
  * @property {Array} [params] Array of param names.
+ * @property {Boolean} [searchDefaultTokenKeys] Use the default search locations for Token in request
  * @property {Function|String} [model] AccessToken model name or class to use.
  * @property {String} [currentUserLiteral] String literal for the current user.
  * @header loopback.token([options]) 
```

**Comment by OwenBrotherwood** [comment]
option is available.
either merge or ask for a pull request

https://github.com/sloopback/sloopback-issues/issues/4

**Comment by bajtos** [comment]
@OwenBrotherwood please submit a regular pull request against the loopback repository (strongloop/loopback). Include unit-tests covering your changes, keep these unit-tests consistent with the style of existing tests we have in LoopBack now. This is the easiest way for me to review your changes and land them in LoopBack master.

I appreciate the effort you are making to start contributing to LoopBack and I hope you will continue to do so :)

If I may offer you a piece of general advice: when starting to contribute to a new project, please begin with small fixes/features (like the one described in this issue) and keep the amount of changes as small as possible, always honour the coding and testing style that the project currently uses. More often than not, there are reasons why the project has decided on the current rules, even though these reasons are not immediately obvious to new contributors. By playing by the project rules, you show respect to the maintainers and the decisions they have made in the past. As a result, you make it easier for the maintainers to trust & respect your opinions in return.

I know it's not easy, I went through this pain myself when I started contributing to Node core and other existing projects in the npm ecosystem. I took me quite some time to realise that many times it's better to contribute a patch that I consider imperfect, rather than to try to convince project maintainers that they should be doing things in a different way. That's at least my experience.

**Comment by OwenBrotherwood** [comment]
@bajtos I understand. Please state 
if the tests are ok for a pull request, the actual implementation code is _very_ little.

**Comment by bajtos** [comment]
> Please state if the tests are ok for a pull request, the actual implementation code is very little.

Please rework the tests to be consistent with the current test suite in [test/access-token.test.js](https://github.com/strongloop/loopback/blob/242bcec539abe3fadac475d7fa60a67f7c7b34a3/test/access-token.test.js). Your original PR #1347 started in the right direction, probably up to https://github.com/strongloop/loopback/commit/c20cefd21bd7e52ccc4286e4ab2764e67d0163dd.

I agree the actual implementation code is very little, but we still need a test suite:
 - to verify that the changes work as intended and
 - to ensure the code will stay working this way in the future too.

**Comment by OwenBrotherwood** [comment]
@bajtos I am afraid the access-token.test.js has several issues, and if I was to add something in it, I would have to address these. I do not have this time.

**Comment by bajtos** [comment]
> I am afraid the access-token.test.js has several issues, and if I was to add something in it, I would have to address these. I do not have this time.

I see, that's unfortunate. Can you please list the issues in the test, perhaps somebody else will be willing to fix them?
