### ISSUE TITLE
Calling count on related model fails with 401 if there are no related models present

### ISSUE THREAD

**Issue by kblcuk** [strongloop/loopback#1328]
Consider a model (for instance `Bus`) that has a `hasMany` relation to another model (for instance `Passenger`).
If it so happens that we query passengers for bus without ones, then
* `/api/Bus/{id}/passengers` returns `[]` (as expected)
* `/api/Bus/{id}/passengers/count` throws 401; shouldn't it return 0?

Thanks!

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by raymondfeng** [comment]
@kblcuk You probably miss ACLs for the related `count`. See http://docs.strongloop.com/display/LB/Accessing+related+models

**Comment by kblcuk** [comment]
@raymondfeng, good catch! I had the `__get__passengers` ACL defined, but not `__count__passengers`; once I added it, 401s stopped appearing. Strange though, shouldn't then it 401 also the counts for cases when there were related models to count? I mimic my current setup in test project, see below.

@superkhau, got test project setup, but found a possible cause on the way; however, I fail to reproduce exact, erm, actual issue (missing 'count' acl allows for count) in the test project, since for some reason $owner permission doesn't let me get passengers even though acl is there... Maybe I'm missing something?

So if you could comment on that, that would be awesome: https://github.com/kblcuk/loopback-sandbox
But as I mentioned already, @raymondfeng guess was correct, so my issue here is resolved.

Thanks!

**Comment by superkhau** [comment]
@kblcuk Glad you got it working. As for your test project, try running it with `DEBUG=loopback:security:role` and see what the ACL says for you. Create a new issue if you notice something and I will try to reproduce it there. Closing this issue as resolved.
