### ISSUE TITLE
Docs for conflict resolution

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1333]
A follow-up for #988, #1233 and https://github.com/strongloop/loopback-example-offline-sync/pull/60#discussion_r29024958

Extend the section [Conflict resolution](http://docs.strongloop.com/display/LB/Synchronization#Synchronization-Conflictresolution) and provide more information for users.

@superkhau please provide @crandmck with details on what you would like to see in the docs.

**Comment by crandmck** [comment]
@bajtos Just a heads up that Simon is on PTO for approx. 2 weeks.  If you want to see any progress on this issue in that time, someone else will need to get involved.

**Comment by crandmck** [comment]
@superkhau this fell through the cracks.  Is it still something that we need to add to docs?  If so, can you provide some more info here?  If not, then we should close it.

**Comment by superkhau** [comment]
@crandmck They've all been merged in and I believe they are done. Feel free to close after confirming it's in the docs.

**Comment by crandmck** [comment]
> please provide @crandmck with details on what you would like to see in the docs.

@superkhau Could you do this please.

**Comment by superkhau** [comment]
@crandmck You've already updated the docs based on the updated example. Closing as this is already done.
