### ISSUE TITLE
HasAndBelongsToMany relation Model.relationName.link() method not working with angular sdk client lib

### ISSUE THREAD

**Issue by mikamboo** [strongloop/loopback#1334]
Hello strong team, 

I created two models Car and Tag linked with ___hasAndBelongsToMany__ relation. Trying to link to instances of these models issue a 404 error message. Because ```fk``` paramater is not setted propoerly by angular sdk client lib.
 
* __Car model :__ ```car.json```

```javascript

{
  "name": "Car",
  "plural": "cars",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "tags": {
      "type": "hasAndBelongsToMany",
      "model": "Tag"
    }
  },
  "acls": [],
  "methods": []
}
```

* __Tag model :__ ```tag.json```

```javascript
{
  "name": "Tag ",
  "plural": "tags",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "acls": [],
  "methods": []
}
```
I created some sample data (cars and tags) on database (tested with memory and mongodb connectors).
When i call api on client side, angular lib must make a PUT http request to link my to models instances. Infortunately, ng-lib seems make a bad request.

```javascript
"error":{
  "name":"Error","status":404,"message":"No relation found in CarTag for (Car.1,Tag.rel)",
  "statusCode":404,
  "stack":"Error: No relation found in CarTag for (Car.1,Tag.rel)
}
```

When I spying the request I can see : 
 
```
Remote Address:127.0.0.1:3000
Request URL:http://localhost:3000/api/cars/1/tags/rel
Request Method:PUT
Status Code:404 Not Found
Request Playload : {"id":1,"fk":1}
```

Doing the same taks on api explorer works and reveals that correct PUT Request should be : 

```
Request URL:http://localhost:3000/api/cars/1/tags/rel/1
```

I don't understant why my ```fk``` paramater is not defined by angular sdk client lib.

* My Angular app client code : not working !

```javascript

var carID = 1;
var tagID = 1;

Car.tags.link({id:carID, fk:tagID}).$promise.then(
    function(sucess){
      console.log(sucess);
    },
    function(error){
        console.log(error);
        //-- 404 error retuned
     }
 );
```

**Comment by Overdrivr** [comment]
@mikamboo Why did you close this ticket ? Some feedback would be appreciated.

**Comment by mikamboo** [comment]
Hi @Overdrivr !

Look at the ticket nuùber [#145](https://github.com/strongloop/loopback-sdk-angular/issues/145), hope that will solve your problem.

**Comment by Overdrivr** [comment]
Thanks for the heads up :) Appreciate it.
