### ISSUE TITLE
Resetting user password

### ISSUE THREAD

**Issue by Karabi-Choudhury** [strongloop/loopback#1335]
Hi,

I have inherited the user model to myUsers to be a collection in my mongodb. Now i was trying to change the password.How can i do it in strongloop?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

See https://github.com/strongloop/loopback-faq-user-management#how-do-you-perform-a-password-reset-for-a-registered-user

**Comment by divyachandana** [comment]
**https://github.com/strongloop/loopback-example-user-management**

Neatly given in this example by loopback . you have to change `email and password`
