### ISSUE TITLE
Some question about access control for records

### ISSUE THREAD

**Issue by iorikingdom** [strongloop/loopback#1339]
I like strongloop.I want do write all of the business logic in client side
But i have some question about the acls
The access control it seem just working for tables but i want it work for records.
Such as [A,B,C] three persons in the user table. [A] could access user table and have a privilege to write user table. Because A person want to change his email address or something belong to her. It mean [A]
person could also change [B,C] persons's properties (Email or others)?
Can i set the ACLs for record not for the tables?
Sorry for my poor English

**Comment by superkhau** [comment]
@iorikingdom I don't believe we support that level of granularity out of the box. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

@raymondfeng Please confirm.
