### ISSUE TITLE
User model restrict "create" with ACLs

### ISSUE THREAD

**Issue by kuskov** [strongloop/loopback#1340]
Hello,
i have create a model "Employee" that is a subclass of "User" and is used only for internal usage. I added the ACL's as following:

"acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": "logout"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "login"
    }
  ]

It is still possible to create an "Employee" using the POST method "/api/Employee".

**Comment by kuskov** [comment]
Restriction of "create" method works only explicit, if i use:
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "property": "create"
    }

**Comment by raymondfeng** [comment]
There is a `defaultPermission` property for the model settings to control what default permission is if there are no matching ACL rules. You can configure it to be `ALLOW` or `DENY`

**Comment by riteshvish** [comment]
@raymondfeng how we can change defaultPremission of usersModel

I have created a model "Customer" with a base of "User" Model.
We have some dynamic field to save in Customer like customer profile where a customer can add any type of data.

Problem
when I am trying to update, put dynamic fields I am getting 
{
  "error": {
    "statusCode": 401,
    "name": "Error",
    "message": "Authorization Required",
    "code": "AUTHORIZATION_REQUIRED",
 }
}

Please help I stuck
