### ISSUE TITLE
Can't include role when I put it in Mongodb

### ISSUE THREAD

**Issue by HelloCui** [strongloop/loopback#1342]
my user model's relation is
```javascript
"roles": {
      "type": "hasMany",
      "model": "Role",
      "foreignKey": "principalId",
      "through": "RoleMapping"
}
```
In memory db, it work well:
![1](https://cloud.githubusercontent.com/assets/4626117/7366470/10871112-edcb-11e4-89e0-913585ce559a.png)
But when I put the Role and RoleMapping to a mongodb, it get sick
![2](https://cloud.githubusercontent.com/assets/4626117/7366474/165cc5aa-edcb-11e4-91c1-405da83c8898.png)

What's wrong with that?

**Comment by HelloCui** [comment]
It seems the cause by the ObjectId. When I define a string id to user, work.
![image](https://cloud.githubusercontent.com/assets/4626117/7366975/c1f75292-edce-11e4-9ea2-4cb7c76f95fd.png)

I don't know if this is a bug. If not. Please close it.

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by mneil** [comment]
Likely related to https://github.com/strongloop/loopback/issues/274 and here's a duplicate issue https://github.com/strongloop/loopback/issues/1441

**Comment by superkhau** [comment]
@mneil Thanks for looking it up, will close this this is a duplicate for #1441.

**Comment by IgorVieira** [comment]
I have another problem, my server return a error for authentication 

```

  "error": {
    "name": "Error",
    "status": 401,
    "message": "Autorização Necessária",
    "statusCode": 401,
    "code": "AUTHORIZATION_REQUIRED",
    "stack": "Error: Autorização Necessária\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/lib/application.js:399:21\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/lib/model.js:349:7\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/common/models/acl.js:472:23\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/node_modules/async/dist/async.js:3799:9\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/node_modules/async/dist/async.js:360:16\n    at iteratorCallback (/home/igor/Bitbucket/dashboard-server/node_modules/loopback/node_modules/async/dist/async.js:936:13)\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/node_modules/async/dist/async.js:844:16\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/node_modules/async/dist/async.js:3796:13\n    at apply (/home/igor/Bitbucket/dashboard-server/node_modules/loopback/node_modules/async/dist/async.js:21:25)\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/node_modules/async/dist/async.js:56:12\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/common/models/acl.js:454:17\n    at /home/igor/Bitbucket/dashboard-server/node_modules/loopback/common/models/role.js:273:21\n    at _combinedTickCallback (internal/process/next_tick.js:67:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:122:9)"
  }
}

```

**Comment by IgorVieira** [comment]
I will write in other issue.

**Comment by joshuaai** [comment]
@IgorVieira you need to set the ACL on your custom user model to grant READ access to the get roles method (or all methods), to the owner.
