### ISSUE TITLE
3.0 remove `Model.setup()`

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1344]
I'd like to propose removing `Model.setup()` in favor of the following:

``` js
// common/models/my-model.js
module.exports = function(Model) {
  // this is now the setup function
  // it is called once when MyModel is initial created and each time it is extended
  // passing the extended Model as the argument
}
```

``` js
// if you want the same behavior as 2.x Model.setup() in JS land
MyModel.extend = function() {
  var ExtendedModel = this._extend(); // new alias
  mySetupFn.apply(ExtendedModel);
  return ExtendedModel;
}
```

/cc @bajtos @raymondfeng @fabien

**Comment by bajtos** [comment]
I don't think this is possible in the current design, where loobpack core does not dictate any project layout, thus there is no "common/models/my-model.js" as far as loopback & juggler are concerned.

**Comment by raymondfeng** [comment]
The real question is how to deal with model inheritance, especially for the class level set up. When model A extends from B, we inherit the prototype methods/properties from B. We also copy static methods/properties (such as find/create) from B to A. The `setup` is used to invoke super class (B)'s class level initialization. If we turn the model class into an instance of `Collection<A>`, we can simply call the super constructor. 

Another idea is to keep the static `setup` methods (which can be annotated similarly as remote methods) to models and LB will automatically calls these methods during the model configuration.

**Comment by bajtos** [comment]
> Another idea is to keep the static setup methods (which can be annotated similarly as remote methods) to models and LB will automatically calls these methods during the model configuration.

I think this is in line with my older idea described in #550.

Perhaps we can modify loopback-boot to assign `module.exports` from the model script to the `setup` function?

Having said that, I am wondering what are the use cases where the developer needs a custom `setup` function? Can we improve the implementation of model subclassing in such way that a custom `setup` function is no longer needed?

**Comment by ritch** [comment]
> Having said that, I am wondering what are the use cases where the developer needs a custom setup function?

mostly stateful constructors (anti-pattern I know)... eg. event listeners on multiple levels of inheritence

**Comment by bajtos** [comment]
> mostly stateful constructors (anti-pattern I know)... eg. event listeners

Isn't that solved by the new hook infrastructure (`observer` and `notifyObserversOf`)? It respects inheritance. In fact, one must not install the same observer callback again on subclassed models, because that way the callback will be triggered multiple times.

**Comment by alFReD-NSH** [comment]
One reason setup is used in here, is for the [problem described in here](http://stackoverflow.com/q/31539987/774086) and it's used for example in [user model](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L567-L693). Without it, the remote methods wouldn't be created for the extended models.

If we "modify loopback-boot to assign module.exports from the model script to the setup", that would fix the problem(though it can be solved with other ways), but might break some existing code in edge cases.
