### ISSUE TITLE
datasources.local.js can't load properly

### ISSUE THREAD

**Issue by transedward** [strongloop/loopback#1345]
as in #174 
I do as @bajtos said, and still get like this:
`AssertionError: User is referencing a dataSource that does not exist: "pg"`
I created an minimal [sanbox-repo](https://github.com/transedward/loopback-sandbox) to represent my problem
I check the loopback-boot, not sure if I have to config every options property?

**Comment by transedward** [comment]
btw, I already export DATABASE_URL locally, which I used in datasources.local.js

**Comment by bajtos** [comment]
You cannot add new datasources in environment-specific files, you can only modify the configuration of datasources already defined in the main `datasources.json` file.

In your sandbox-repo, [server/datasources.json](https://github.com/transedward/loopback-sandbox/blob/ff668046d6aac51ad890a9a70c31bcf4908b2d7d/server/datasources.json) defines a datasource called "db", while [server/datasources.local.js](https://github.com/transedward/loopback-sandbox/blob/ff668046d6aac51ad890a9a70c31bcf4908b2d7d/server/datasources.local.js) defines "pg".

Here is the fixed `server/datasources.json`:

```json
{
  "pg": {
    "name": "pg",
    "connector": "postgresql"
  }
}
```

I am closing the issue as resolved, feel free to reopen it if the problem persists.

**Comment by transedward** [comment]
thanks, maybe I misunderstood the loopback-boot doc
