### ISSUE TITLE
Download file through storage api

### ISSUE THREAD

**Issue by Karabi-Choudhury** [strongloop/loopback#1348]
Hi,

I am using storage service to upload in S3.i have uploaded my file in the path <container>/user/user1/1.png.To get the file i am calling the download api. How do i specify the path in the GET /api/containers/container-name/download/file-name call?

Thanks,
Karabi

**Comment by Karabi-Choudhury** [comment]
Or is there anyway that while uploading file in S3 via storage API i make it public?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
