### ISSUE TITLE
LoopBack Mixins Example

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1349]
Create an example that demonstrates the power of mixins.

/cc @fabien @bajtos @raymondfeng

**Comment by robotiko** [comment]
+1

**Comment by clarkbw** [comment]
FYI, I started one here: https://github.com/clarkbw/loopback-mixins-example

**Comment by vespertilian** [comment]
@clarkbw Thanks for the sample.

**Comment by superkhau** [comment]
@clarkbw Do you want me to add that example to the rest of the list at https://github.com/strongloop/loopback-demo? I can add it under community since you're maintaining it. ;)

**Comment by clarkbw** [comment]
Sure, if there's anything I can do to improve it let me know.
