### ISSUE TITLE
Controllingdataaccess-Useraccesstypes: other methods example or explanation

### ISSUE THREAD

**Issue by OwenBrotherwood** [strongloop/loopback#1351]
[For other methods, the default access type is EXECUTE; for example, a custom method maps to the EXECUTE access type.](http://docs.strongloop.com/display/public/LB/Controlling+data+access#Controllingdataaccess-Useraccesstypes)
Example or explaination of other methods ...?

The question came from gitter.im

[it](http://docs.strongloop.com/display/public/LB/Controlling+data+access#Controllingdataaccess-Useraccesstypes)  says just this:
For other methods, the default access type is EXECUTE; for example, a custom method maps to the EXECUTE access type.
but what else include those other methods

**Comment by ningsuhen** [comment]
That would include remaining methods (exposed via rest api) in http://docs.strongloop.com/display/public/LB/User (login,logout) & http://docs.strongloop.com/display/public/LB/PersistedModel+class, custom methods (methods you define) and the relation methods - __get__followers, __get__{relationName}

**Comment by OwenBrotherwood** [comment]
:) Thanks, let us hope the person who wrote on gitter im read the reply
