### ISSUE TITLE
Are there plans to add aggregate operators to the query selectors?

### ISSUE THREAD

**Issue by mikesimkin** [strongloop/loopback#1353]
Hey I would love to use loopback for my project but I need to do a lot of aggregate operators (sum, count, prod, etc) to generate statistics from raw data. 

Are there any plans to add aggregate operators to the query selectors?

Thanks!

**Comment by superkhau** [comment]
@mikesimkin Not sure when, but I believe this feature is on the roadmap. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

/cc @raymondfeng
