### ISSUE TITLE
Demo app with login / signup / reset pages

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback#1356]
I wanted to know if there are any reference implementations that utilize amd map ui driven login sessions in express and uses loopback apis to perform login actions. 

I'm particularly curious how you would map an accessToken for authenticated users to a user session. do you just store the token as session property? how about synchronizing accessToken ttl vs session maxAge?

Thanks for clarifying any of these points.

**Comment by cleas** [comment]
https://github.com/strongloop/loopback-faq-user-management

**Comment by superkhau** [comment]
+1 @cleas's answer

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by penzhan8451** [comment]
Hi, 
I defined a method in the Connector." function all(model, filter, callback){...}", this method will handle incoming Get request with model name ,filter.  My question is  can I change the model name Before the request comes into the Connector method? 
Thanks.

**Comment by penzhan8451** [comment]
Sorry!, I  Post a wrong position.
