### ISSUE TITLE
updateOrCreate and $setOnInsert

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1360]
Consider the example from https://github.com/strongloop/loopback-datasource-juggler/issues/570:

```
    DeviceSDKRelation.upsert({
      id: 'compositeid1',
      '$set': {
        sdkVersion: '1.0.0',
        enabled: true,
        updatedAt: new Date()
      },
      '$setOnInsert': {
        deviceId: 'deviceid1',
        applicationId: 'appid1',
        createdAt: new Date()
      }
    });
```

We should extend `updateOrCreate` to support "setOnInsert" and "setOnUpdate" for all connectors, this will allow us to validate the data too.

**Comment by jasiedu** [comment]
You guys should really just find a way to use mongoose.
