### ISSUE TITLE
Unbundle remote connector

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1361]
Remove loopback-connector-remote from loopback dependencies, let the users to install it explicitly.

Benefits: we can version loopback-connector-remote independently on loopback core. Smaller browser bundle size for applications using local storage only.

**Tasks**
- [ ] improve `boot.compileToBrowserify` to include connectors in the browser bundle
- [ ] remove `loopback-connector-remote` from loopback dependencies

**Comment by ritch** [comment]
**+1**

**Comment by bajtos** [comment]
I am afraid we don't have bandwidth to implement this feature in v3.0, removing from the milestone.
