### ISSUE TITLE
Sending sms

### ISSUE THREAD

**Issue by Karabi-Choudhury** [strongloop/loopback#1365]
Hi,

My frontend angular application wants to send sms to user for certain changes.
How can i do it? We are using sms package of some provider.I have the api's

Thanks,
Karabi

**Comment by raymondfeng** [comment]
Check this out - https://github.com/dashby3000/loopback-connector-twilio <https://github.com/dashby3000/loopback-connector-twilio>
Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by Karabi-Choudhury** [comment]
I had already seen that.But that is specific to twilio.I am using different provider

**Comment by Karabi-Choudhury** [comment]
Can i make http GET/POST calls withing operation hooks?

**Comment by superkhau** [comment]
>Can i make http GET/POST calls withing operation hooks?

You can use a library like `request` to make GET/POST requests to third party apps in your operation hooks. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
