### ISSUE TITLE
[Questions] Override built-in method of related model

### ISSUE THREAD

**Issue by b-barry** [strongloop/loopback#1369]
Hello,

I have two models: **A** and **B**.
*  **A**  hasMany  **B**
*  **B** belongsTo  **A** 

I would like to override the **destroyAll**  of the relation A to B and  be able to not delete All B records of A but  just change a boolean to true of false. Like **a soft delete**.
I find in documentation that we can override built-in methods.
I created a file into the boot folder and try to access the prototype functions:
1.A.prototype.nameRelationToB
2.A.prototype.__destroyAll__nameRelationToB 

I was not able to block the destroyAll.

Thanks you for your help

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

Not sure if this is related, but you may want to check https://github.com/strongloop/loopback/issues/1372.

**Comment by Kitanotori** [comment]
Also searching for solution to this...
