### ISSUE TITLE
How to create hasManyThrough polymorphic relation?

### ISSUE THREAD

**Issue by Spark-star** [strongloop/loopback#1371]
I have models like User, Vote, Toic, and some models inheritted from Topic.

I want create relation: User  hasMany models which inheritted from Topic,  through Vote.

How can I do?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by upupzealot** [comment]
@superkhau It's seems that there is no doc teach users how to create hasManyThrough polymorphic relation.
I think it's more a bug(or missing) than a question in the doc.

**Comment by superkhau** [comment]
@upupzealot I think polymorphic relations were contributed by @fabien awhile back, I'm not sure if the proper docs came along with the feature. @crandmck Can you give us some insight here?

**Comment by crandmck** [comment]
We have docs for "regular" [HasManyThrough relations](https://docs.strongloop.com/display/LB/HasManyThrough+relations) but not for _polymorphic_ hasManyThrough relations.  In fact, I didn't even know that was possible.  I welcome any information on examples on that.

**Comment by superkhau** [comment]
@fabien Can you help out @crandmck with some documentation? I believe you implemented this feature awhile back?

**Comment by upupzealot** [comment]
@crandmck I just tried things out.
It seems that polymorphic on hasManyThrough works like this:
```js
User.hasAndBelongsToMany(Topic, {
  as: 'followingTopics',
  polymorphic: {
    foreignKey: 'followableId',
    discriminator: 'followableType'
  },
  through: Follow
});

Topic.hasMany(User, {
  as: 'followers',
  polymorphic: {
    foreignKey: 'followableId',
    discriminator: 'followableType'
  },
  through: Follow
});
```
I did this in a mixin script, but it also works in model json(tried).
Hope this would be helpful :-)

**Comment by superkhau** [comment]
@upupzealot Thanks for the input! Always appreciated when the community helps out with issues like this. Ideally, we should have an example dedicated to this topic.

**Comment by crandmck** [comment]
Thanks @upupzealot I added https://docs.strongloop.com/display/APIC/Polymorphic+relations#Polymorphicrelations-HasManyThroughpolymorphicrelations.  Could you also paste the corresponding model JSON?

**Comment by upupzealot** [comment]
@crandmck I used the Author and Picture model in the page you give, not well tested but it should work. I will update this issue if I find out something new.
the **ImageLink** model
```json
{
  "name": "ImageLink",
  "base": "PersistedModel",
  ...
  "relations": {
    "author": {
      "type": "belongsTo",
      "model": "Author",
      "foreignKey": "authorId"
    },
    "pictures": {
      "type": "hasMany",
      "model": "Picture",
      "polymorphic": {
        "foreignKey": "imageableId",
        "discriminator": "imageableType"
      }
    }
  },
...
}
```
in javascript:
```js
Author.hasMany(Picture, {
  as: 'pictures',
  polymorphic: {
    foreignKey: 'imageableId',
    discriminator: 'imageableType'
  },
  through: ImageLink,
  keyThrough: 'authorId'
});
```
in json file
```json
{
  "name": "Author",
  "base": "PersistedModel",
  ...
  "relations": {
    "pictures": {
      "type": "hasMany",
      "model": "Picture",
      "polymorphic": {
        "foreignKey": "imageableId",
        "discriminator": "imageableType"
      },
      "through": "ImageLink",
      "keyThrough": "authorId"
    }
  },
...
}
```

**Comment by crandmck** [comment]
That's great, thanks very much @upupzealot !
It's always better to stick with the same example models, etc.  

I updated https://docs.strongloop.com/display/APIC/Polymorphic+relations#Polymorphicrelations-HasManyThroughpolymorphicrelations

I'm going to close this issue, since there's not at least minimal documentation, but if anyone wants to suggest additions or modifications to ^ please do so!
