### ISSUE TITLE
How to make case insensitive query to relational database

### ISSUE THREAD

**Issue by solenovex** [strongloop/loopback#1375]
How to make case insensitive query to relational database? like mssql, mysql or postgresql.
Does it support regexp?
I really cannot find an example of that.
Could you guys give me an example?
Thank you very much.

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by superkhau** [comment]
See https://groups.google.com/forum/#!searchin/loopbackjs/case$20insensitive$20query/loopbackjs/wibZSfLLyAo/lJnBGRxikOkJ
