### ISSUE TITLE
table 'users' wrong model (mysql-connector)

### ISSUE THREAD

**Issue by Sogl** [strongloop/loopback#1376]
Hi!

If you already have table 'users' in your mysql DB, autodiscover models creates two models with wrong columns. No previous model creating from console.

Model in ARC (right):
![loopback](https://cloud.githubusercontent.com/assets/7556290/7561765/0fe3dbea-f812-11e4-8fd8-89442e8b7629.JPG)

Models in explorer (wrong, one become two):
![loopback2](https://cloud.githubusercontent.com/assets/7556290/7561814/51edd28e-f812-11e4-8375-3220ca94cbf8.JPG)

Model schema (wrong):
```
[
  {
    "realm": "",
    "username": "",
    "credentials": "object",
    "challenges": "object",
    "email": "",
    "emailVerified": false,
    "verificationToken": "",
    "status": "",
    "created": "",
    "lastUpdated": "",
    "id": 0
  }
]
```

GET responce body:
```
{
  "error": {
    "name": "Error",
    "status": 401,
    "message": "Authorization Required",
    "statusCode": 401,
    "code": "AUTHORIZATION_REQUIRED",
    "stack": "Error: Authorization Required\n    at c:\\projects\\zit\\node_modules\\loopback\\lib\\application.js:347:21\n    at c:\\projects\\zit\\node_modules\\loopback\\lib\\model.js:311:7\n    at c:\\projects\\zit\\node_modules\\loopback\\common\\models\\acl.js:465:23\n    at c:\\projects\\zit\\node_modules\\loopback\\node_modules\\async\\lib\\async.js:254:17\n    at done (c:\\projects\\zit\\node_modules\\loopback\\node_modules\\async\\lib\\async.js:135:19)\n    at c:\\projects\\zit\\node_modules\\loopback\\node_modules\\async\\lib\\async.js:32:16\n    at c:\\projects\\zit\\node_modules\\loopback\\node_modules\\async\\lib\\async.js:251:21\n    at c:\\projects\\zit\\node_modules\\loopback\\node_modules\\async\\lib\\async.js:575:34\n    at c:\\projects\\zit\\node_modules\\loopback\\common\\models\\acl.js:447:17\n    at c:\\projects\\zit\\node_modules\\loopback\\common\\models\\role.js:227:21"
  }
}
```

**Comment by divitoDBA** [comment]
"Users" model is a built-in model. Every new loopback application has this model created by default.

**Comment by Sogl** [comment]
@divitoDBA , but I have both "Users" models and all of them is wrong (same schema).

**Comment by divitoDBA** [comment]
yes, once discovered LB adds the built-in model instead of your table. As workaround, just rename the model that corresponds to your MySQL table in common/models. - eg: "UsersApp" or any other name rather than "Users".

**Comment by Sogl** [comment]
If I rename my model - how to rebuild that? (autodiscover)

**Comment by divitoDBA** [comment]
You can use "discoverSchema" API in this way:

1.- Create a JS file in your server/boot directory (eg: "Usersdiscover.js") and add the following content:

fs = require('fs'); 

 var DataSource = require('loopback-datasource-juggler').DataSource;
    var ds = new DataSource('mysql', {
        host: 'hostname',
        port: 3306,
        database: 'dbname',   
        username: 'owner',     
        password: 'pass'         
    });

var tablename='users' ; 

 ds.discoverSchema(tablename, {owner: 'dbname'}, function (err, schema) {
           var message = JSON.stringify(schema, null, '  ') ; 
fs.writeFile('/tmp/'+tablename+'.json', message, function (err) {
  if (err) {
    return console.log(err);
  }
  console.log(tablename+' OK');
});
    });

Note: change dbname + owner + pass + hostname according to your DB settings.

2.- edit /tmp/users.json and modify:
from:
{
  "name": "Users",
  "options": {
    "idInjection": false,
    "mysql": {
...
to:
{
  "name": "UsersApp",
  "options": {
    "idInjection": false,
    "mysql": {
...

3.- cp /tmp/users.json  common/models/usersapp.json

4.- Add to server/model-config.json

  "UsersApp": {
    "dataSource": "MYSQLDS",
    "public": true
  }

Note: Replace "MYSQLDS" with the name of your current MySQL datasource.

5.- Restart node, UsersApps model will be displayed and ready to use.

I performed this workaround successfully in one of my MySQL projects.

I hope didn't forget any step. Any problem let me know.

**Comment by Sogl** [comment]
Ok, i try.

How to not create Users model in every project? I don't need it.

**Comment by divitoDBA** [comment]
I don't think it's possible. Open a new issue related to this question. Regards

**Comment by superkhau** [comment]
@Sogl Can I close this? It seems like @divitoDBA resolved your issue.

**Comment by Sogl** [comment]
>Can I close this? It seems like @divitoDBA resolved your issue.

Yep. I'm reopen it if needed.

**Comment by superkhau** [comment]
@Sogl TY. Closing.
