### ISSUE TITLE
Get some fields from MongoDB

### ISSUE THREAD

**Issue by SnehalAmbab** [strongloop/loopback#1377]
Hello,

I want to query some fields from the document of mongodb.
For eg. I want only name and price field values of product collection which has name, price, sku, attributes as a fields.

I try to do it with find() function provided by loopback mongodb connector.

but it still returns all the fields of the documents.

My code is like

Products.find({}, {'name':1, 'price':1}, function(err, response) {
});

where "Products" is a model object.

Someone please help me with this.

**Comment by raymondfeng** [comment]
> Products.find({fields: {'name':1, 'price':1}}, function(err, response) {
> });
> 

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by superkhau** [comment]
For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by superkhau** [comment]
@SnehalAmbab Can I close this? Did you try what @raymondfeng suggested?

**Comment by superkhau** [comment]
Actually I'll just close it. @SnehalAmbab Please reopen if you are still having issues.

**Comment by massilvaLaz** [comment]
Hi, 
I want  want to query some fields , one from the subdocument  but I have no result  for the subdocument fields .

My code:
`Products.find({"fields": ["id","fields.name"]};`

Response/
[
  { "id": "585ab055578ee31431df8bf4"},
  {"id": "585ab055578ee31431df8bf5"}
]
Someone can help me please!
