### ISSUE TITLE
PUT fails when updating an array of instances

### ISSUE THREAD

**Issue by antoineverger** [strongloop/loopback#1378]
Hi guys,

PUT method for models fails when trying to PUT an array of existing values. For some reasons, it does recognize the array elements as existing ones and tries to add them again which results in a "key already exists" error.

Do you need more input ?

Cheers,

Antoine

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by loay** [comment]
Hi @antoineverger 
when you do an upsert operation, the data argument must be an object, unlike the create operation that supports both object and array.

**Comment by loay** [comment]
Hi @antoineverger 
closing this issue for now. If you still have a related question, please feel free to leave a comment and I will investigate further.
