### ISSUE TITLE
Enhance the app.middleware() method

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback#1379]
Currently, have to do this:

```
app.middleware('initial:before', loopback.favicon());
app.middleware('initial:before', loopback.compress());
```

Would be great, if this is possible:

```
app.middleware('initial:before', function () {
  loopback.favicon();
  loopback.compress();
})
```

**Comment by pthieu** [comment]
@hacksparrow: 
```
app.middleware('initial:before', loopback.favicon());
app.middleware('initial:before', loopback.compress());
```
When middleware methods are invoked, they usually return a function with the prototype `function(req, res, next){})` where `next()` is invoked to trigger the next middleware in the chain.

```
app.middleware('initial:before', function () {
  loopback.favicon();
  loopback.compress();
})
```
Would not work with this architecture, as you're invoking `.favicon()` and `.compress()` simultaneously, without knowing when to trigger the next middleware in the chain. It would be possible to write it with async or promises along the lines of:

```
app.middleware('initial:before', function (req, res, next) {
  var tasks = [
    loopback.favicon(),
    loopback.compress(),
  ];
  async.waterfall(tasks, function(err, results){ next(); })
})
```
