### ISSUE TITLE
How get the postdata in a custom Express route with strongloop ?

### ISSUE THREAD

**Issue by PanYuntao** [strongloop/loopback#1382]
How get the post data In a custom Express route with strongloop .
like this don't get postdata
```
module.exports = function(app) {
    var router = app.loopback.Router();
    router.post('/ping', function(req, res) {
        console.log(req.body);
        res.send('pongaroo');
    });
    app.use(router);
};
```

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
