### ISSUE TITLE
RFC Patch and dependancy management

### ISSUE THREAD

**Issue by OwenBrotherwood** [strongloop/loopback#1384]
# RPC Patch and dependancy management

One thing I am "concerned" with is the actual driving force of node and npm sucess, flexibility doability and the ease of creation. The Node of Things (NoT) is intresting, and has survived the first years of it's birth.

This RFC starts with the enterprise and ends in Git,how these items _can_ be connected for a next step.

### Enterprise environment
Let us start with something I have wanted to add in connection to AAA: in an enterprise environment, patch and dependacy management matters. 
It is not inconceivable that a security breach at some major repository allows for, if only a brief time, the injection of malignent code into an otherwise well functioning node_module. 
This is "worst case scenario" and really needs some Googling to discover the node solution to this, for which I have not had time but is stated here as a concern, while the rest of this RFC addresses another issue in the Loopback of Things (LoT),

### Day after day normal  node dependancy management
Let us bring the tone down to "ordinary" dependancy management, and one now knows the versions of well functioning node_modules that one may or may not have pulled locally due to company politics. 
This is _probably_ some well known problem/solution in the NoT and/or LoT and/or SoT (Strongloop of Things), 
Refering back to AAA, Audit of software is a major concern to ensure things don't stop working from day to day: a subject that is that has been bloged about at nodejs.com (ref needed: think it was in 2012)

### Quick fix / feature
It is  thinkable that the NoT has some of method that does not involve  "clone my version of a node_module"  to get some quicker moving branch/feature that one just needs. 
The point being, the cloned version is not from the normal node_module maintainer and would really require more examination if one had to ensure it's contents are valid/true to function/free from 'gifts', without the possibility of some tool like that used for in the compiled world aka virus protection program.
 As node is blessed with "just text" and node_modules directory, the contents of what is being used are highly examinable together with package.json and it's contents.

#### Diff of Things
In the LoT (Linux of Things), there is a patch method that is a diff to some kernel or device driver. This has a great advantage as that one can use the mainline code, and dependant on the size of the diff, quickly assertain that the diff is "ok" and it can be applied with few risks.
Organisation and disipline allow for back ports with the diffs applied to the current stable repository.

##### Fast track
For fast moving branches, a community can ensure that diffs of nice features are available, while not compromising the user of the nice feature (audit of software) but allowing for the safe usage of the feature.
It is conceivable that a faster convergence of feature/requirements/peace and understanding can be achieved using some of the available experiences in the IoT.

##### Backporting
A new feature in fast track, that can easily come into the main track is one of the nice things with software (hardware needs a soldering iron) which require some thought in connection with the methods/tools used.

#### Above all
Keep the developers happy and productive with their imagination and drive. @bajtos @ritch

## Git of Things
The world got Git, from the biggest git in the world. How a project uses git is probably the biggest decision a project can have.
Although I have a to google a bit more, one can look round at other projects and find out how they are using Git with sucess and evaluate against the pains and pleasures of how a project, or related projects, have used or abused Git. 
Concepts such as a patch as a diff from the community to be committed by developers or a developer has downstream developers they use, can be key components to obtain a clean Git repository for a project within the same repo where only lead developers hit the big ~~red~~ green button.
Views are many, but a project can come to a conclussion "there can only be one" and discipline is a main factor for successfull use of a git repository.
Moving forward is a hard task, any projects next step is ultimatly a question of research, and a decision, in order to keep momentem. However, stepping back and assessing is a good starting point. @altsang @raymondfeng

### Github
Wow.
A project can have maintainers with their fork of the master and branches of a project. As a project can have several mainainers, each in a group (sometime of one) with a resposibility for a specific area of a project, the possibility of a Hub and Spoke cooperation with the community is possible as indicated with Git with downstream developers with clear visibility of Fast Tracks in the pipeline that can complement the main master stable and main fast track branches.
One can also ponder the effects on the issues that such a configuration would have. Fast track issues would be confinable to the maintaner fork: the main repository for issues for mainstream. 
Cross reference is possible, information can flow both ways.
Some tools/hooks are necessary: new issue === polite request for correct issue submital with possible automatic close if no information given within a certain time. The maintainers have better things to do than look at non-responsive/dead in the water issues. But allways: politeness and language should not be a barrier (google translate)
A lot more could be written but I want to do a little commit to something (or other).

#### User story: a Point of View
Hmmm...The above is a POV. As to if I have something more, the night is young in Denmark.

### Disclaimer
Please note, the author of this issue has only been googling node for about 6 weeks now (last time the author looked at node was some years ago, I remember that I noted I wanted to get back to node at some time) and the issue (or rather idea/question/thought) can be closed without prejudice if wished.

#### GiP
Please also not that this "header" for the issue is editted a lot: GiP (Googling in Progress) while watching another issue.

**Comment by ritch** [comment]
I don't think this is the right place for this. I don't see anything really actionable and thats what we like to keep the issue list populated with.

**Comment by OwenBrotherwood** [comment]
No problem :)
I finished the edit (had to put it through a spelling check, so it was a bit more readable

**Comment by OwenBrotherwood** [comment]
Added the comment that the issue should be read in context with issue 1380

**Comment by OwenBrotherwood** [comment]
#### A Story Example: Opinionated
_A project wishes to use a hub and spoke model for Github_
  - _the main repo should be clean for PR's from the community_
  - An issue, bug or feature, is created in sloopback/loopback by a community user
  - A hook automatically adds comment with referance to information of the next step and what is ususally needed
    - this usually will mean the community would add more info
      - indicates a positive flow in information: the issue is interesting
  - The issue is picked up or assigned to a project member
    - if a PR request then information to the user with a repo they should clone
      -  the process of ensuring a PR of quality
    - final PR to main repository
      - the PR is visible and perhaps with several OK's, is committed

**Comment by OwenBrotherwood** [comment]
#### Roles in a project Github
  - owner 
  - lead
  - maintaner 
  - developer
  - tester
  - community contributor

**Comment by OwenBrotherwood** [comment]
User Story: community contributor

**Comment by OwenBrotherwood** [comment]
#### User Stroy: community contribor helps another contributor
_A PR fails with test: another community contributor helps with a diff and what is otherwise wrong_
https://github.com/strongloop/loopback/pull/1388

**Comment by OwenBrotherwood** [comment]
- [strongloop/loopback](https://github.com/strongloop) (company stable) contra [loopback/loopback](https://github.com/loopback) (community fasttrack)
        - Github organisation contra repro contra branches for stabel, fasttrack

**Comment by OwenBrotherwood** [comment]
### loopback-component-something
The whole repo for a component situation is "interesting": and probably _could_ be revised.
In an enterprise, a loopback without a loopback-component-passport is basically unusable,

The reason for making a seperate repo can be many, but in clear terms, the loopback repo should contain this (and other?) component's as standard. Components does not even warrant a branch, it should "just be there". 
The use of branch to introduce a new component is possible

**Comment by OwenBrotherwood** [comment]
_As a maintaner of a Github Repository, I would like to ensure that issues are not long lived, either by resolution or clear indication of a head issue_

Long issues are not nice, unless they are some form of bearer issue that matches the goals of the project.

---

An issue in Github has 3 states, open closed and closed but watched.
An issue can be closed but input can still be given and watched and a cherry picking of issues and issue comments can be referrenced by other issues or internal documentation

**Comment by OwenBrotherwood** [comment]
--- 

http://semver.org/

---

npm as a tool contra github/git as a tool

---

https://github.com/strongloop/loopback/issues/1380#issuecomment-103976583

---

**Comment by OwenBrotherwood** [comment]
![loopback issue 1384](https://cloud.githubusercontent.com/assets/866122/7733374/e991629a-ff2e-11e4-9fc8-3054cb611722.jpg)

**Comment by OwenBrotherwood** [comment]
https://github.com/mikedeboer/node-github

**Comment by OwenBrotherwood** [comment]
### Homework 
https://youtu.be/PSv7GIX-XQ0?t=30m

**Comment by OwenBrotherwood** [comment]
http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/

**Comment by OwenBrotherwood** [comment]
On my Windows 8.1 with 1.9.5.msysgit.1
Note: change coolPlask/lookback to example loopback/loopback ( see https://github.com/loopback )

```
# create empty repto, coolPlask/loopback
git clone https://github.com/coolPlask/loopback.git
cd loopback
git remote add upstream https://github.com/OwenBrotherwood/loopback
git fetch upstream
git branch --unset-upstream
git merge upstream/master
git push origin master # or other branches
# create issues on both repos and refer issues to each other
```

**Comment by OwenBrotherwood** [comment]
triag to https://github.com/coolPlask/loopback/issues/1

**Comment by OwenBrotherwood** [comment]
It worked.

Overheads of having a break in the chain.....minimum????

**Comment by OwenBrotherwood** [comment]
https://github.com/sloopback/sloopback-issues/wiki

Shows the process tags I use as a community developer.
There is a special issues repro that is the only place for issues https://github.com/sloopback/sloopback-issues
With only ONE place for issues, multi-repo hell for where to place an issue is avoided.
