### ISSUE TITLE
Build failed on build server behind corprate firewall (http://blip.strongloop.com/loopback@2.17.3)

### ISSUE THREAD

**Issue by javefang** [strongloop/loopback#1389]
OS: Red Hat Enterprise Linux Server release 6.6
Node: 0.10.36
Strongloop: 4.0.2

I'm building a loopback project on our build server, the build server is behind the firewall and it has limited access to the internet (it fetches npm packages via the companies private npm server). I see loads of failures regarding failed to fetch files from http://blip.strongloop.com/*. 

Checked npm and found there is an sl-blip package, which is a dependency of almost all loopback packages. But there is no description nor source code. Could you tell me what is it and why it needs to fetch files from blip.strongloop.com? 

Thanks,
Jave

**Comment by OwenBrotherwood** [comment]
http://docs.strongloop.com/display/SL/Installation+troubleshooting#Installationtroubleshooting-Firewallissues

@crandmck +1 for me :) I knew it would come up
There may be a need for a common troubleshooting
http://docs.strongloop.com/display/SL/Installing+Node+and+StrongLoop+on+Windows#InstallingNodeandStrongLooponWindows-Troubleshooting

**Comment by javefang** [comment]
@OwenBrotherwood Hi, thanks for the answer. It make sense now. I know I can ignore optional dependencies by doing `npm install --no-optional`, which will isgnore the `sl-blip` package.

I should probably open an issue in `strong-pm`. The builds on our build server are always trying to access http://blip.strongloop.com (our build server has no internet access, so the access failed after timeout), this makes the whole build process much slower. This is probably because `slc build` always call `npm install` to install the packages, which will try to install optional dependencies as well. Ideally it should provide a parameter to support `--no-optional`?

**Comment by OwenBrotherwood** [comment]
@javefang Please note, I am just a community member _not_ a developer. 
As the issue is _probably_ something strong-pm should look at, an issue in strong-pm could be best.
Make sure you describe the environment: enterprise and company policies for build server and access to the internet

**Comment by javefang** [comment]
@OwenBrotherwood no problem mate, thanks for the help :)

**Comment by OwenBrotherwood** [comment]
https://github.com/strongloop/loopback/issues/1079
