### ISSUE TITLE
How to change the model name before Get request goes into  the Connector 'all' method?

### ISSUE THREAD

**Issue by penzhan8451** [strongloop/loopback#1392]
Hi, 
I defined a method in the Connector." function all(model, filter, callback){...}", this method will handle incoming Get request with model name ,filter. My question is can I change the model name Before the request comes into the Connector 'all' method? 
Thanks.

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
