### ISSUE TITLE
inq and near filters conflict.

### ISSUE THREAD

**Issue by sakhisoufiane** [strongloop/loopback#1395]
I run into an issue while trying get some documents from a mongo database using the inq and near filters. I want to get users with certain skills that are close to an other user's location.

Near works, inq works also, but when I try to make a combination of both to get those users it just doesn't work.

Here's what I'm using :

```
User.find({where: {and: [{ skills : {inq :nearby_skills}, location: {near: user_location}, id:{neq : user_id}}]}, limit:10, skip:10*n }, function(err, users){
    cb(null, users);
});
```
skills is an array of the user's skills. Ex: ['nodejs', 'JavaScript'] nearby_skills is the filter, it could be something like : ['databases', 'nodejs'] location and user_location are GeoPoints.

For the example I gave, the result would be to get all people that have databases and nodejs as skills, and get them ASC based on how far they are from the user sending the request.

**Comment by npedrini** [comment]
I'm seeing a similar issue where includes specified in the includes filters are not included if a near query is specified in the where filter.

**Comment by sakhisoufiane** [comment]
Just switched back to express/mongoose, did way I'm free to do whatever I
want with my data

**Comment by rkmax** [comment]
I have a issue I dont know if it's related. in my records I have a `field: [string]` but when I query always get 0 records but in the database exists records than match with that query

## Loopback version it does not works
```js
Model.find({where: {field: {inq: ['valuea', 'valueb']}}}); // returns 0 results
```

## Mongo version working
```js
db.Model.find({field: {$in: ['valuea', 'valueb']}}); // returns 18 results
```

**Comment by FreakTheMighty** [comment]
I believe I'm seeing a related issue, I'm doing a query like so through the angular sdk:

```javascript
        filter: {
          where: {
            location: {
              near: coords,
              maxDistance: 290,
              unit: 'kilometers'
            },
            startAt: {
              gt: moment().startOf('day').toDate()
            }
          },
          skip: skip || 0,
          limit: limit || 20,
          order: 'startAt ASC'
        }
 ```

When I use the `near` query, the `order` is no longer respected, and the results are ordered by distance. It seems like `near` doesn't behave well with other filters.

**Comment by 0candy** [comment]
Same issue: https://github.com/strongloop/loopback-datasource-juggler/issues/931

**Comment by 0candy** [comment]
Closing as dup
