### ISSUE TITLE
Remoting 'get' of belongsTo should return 404 when missing

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#1396]
Currently an empty object `{}` is returned and status is 200, even though the relation has not been established.

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github for me to reproduce it? I tried scaffolding a new project and just creating a model (ie. cars) and doing `curl localhost:3000/api/cars/1/bob` and it returns 404.

**Comment by fabien** [comment]
@superkhau I don't really have a test project, all I know is that this does not work in any of my unit tests, not even in the most basic setup. What's `bob` in your case?

**Comment by superkhau** [comment]
`bob` doesn't exist, I'm just trying to show that I queried a relation that was not defined.

**Comment by loay** [comment]
@fabien 
Is this issue good to close or still persisting?

**Comment by loay** [comment]
Closing issue. If still persisting, please feel free to leave a message and I will re-open the issue.
