### ISSUE TITLE
body is null when rest builder invoke..

### ISSUE THREAD

**Issue by penzhan8451** [strongloop/loopback#1397]
var testdata = {
name: 'Kobe',
age: '38'
};
var tostr = JSON.stringify(testdata);
var access_token = 'xxxxxxx';

var restbuilder = require("loopback-connector-rest");
var builder = new restbuilder('POST','https://<url>/test2.json')
  .header({"Accept": "application/json","Content-Type": "application/json","Authorization": "Bearer " + access_token,"Content-Length": tostr.length})
  .body(tostr);

builder.invoke(processResponse);

when builder invoke, I found the body is null by debug, who knows what is wrong?  Thanks.

**Comment by raymondfeng** [comment]
Since you have the `Content-Type` set to `application/json`, the body should be a json object without stringify.

**Comment by penzhan8451** [comment]
Hi raymondfeng，  thanks very much!  I will try it.

**Comment by penzhan8451** [comment]
Yes, It works.  Thanks.
