### ISSUE TITLE
POST operation fails - 500 Invalid date 

### ISSUE THREAD

**Issue by divitoDBA** [strongloop/loopback#1402]
When connected to MySQL: GET operations performed OK but POST operations fail with: 

Response Body:
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Invalid date: ",
    "stack": "Error: Invalid date: \n    at DateType ...

Response Header:

{
  "Date": "Wed, 20 May 2015 23:33:57 GMT",
  "Content-Encoding": "gzip",
  "X-Powered-By": "Express",
  "Etag": "W/\"1TEQs8r5oWeten7lh1qsBw==\"",
  "Vary": "Origin, Accept-Encoding",
  "Content-Type": "application/json; charset=utf-8",
  "Access-Control-Allow-Origin": "http://mean.node.com:3000",
  "Access-Control-Allow-Credentials": "true",
  "Connection": "keep-alive",
  "Transfer-Encoding": "chunked"
}

package.json: 
..
  "dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "errorhandler": "^1.1.1",
    "loopback": "^2.14.0",
    "loopback-boot": "^2.6.5",
    "loopback-connector-mysql": "^2.1.0",
    "loopback-datasource-juggler": "^2.19.0",
    "serve-favicon": "^2.0.1"
  }

Is this a bug ?

Let me know if further information is necessary.
Regards,

**Comment by raymondfeng** [comment]
What's your post data? Does it contain `null` date?

**Comment by divitoDBA** [comment]
My mistake,  I was using "" instead of null.

My original post data not working: 
{
  "id": 2,
  "address": "test record",
  "city": "",
  "stateProvince": "",
  "postalCode": "",
  "country": "",
  "lat": "",
  "long": "",
  "buildingId": 0,
  "created": "",
  "updated": ""
}

My new post data - now working as expected:

{
  "id": 2,
  "address": "test record",
  "city": "",
  "stateProvince": "",
  "postalCode": "",
  "country": "",
  "lat": "",
  "long": "",
  "buildingId": 0,
  "created": "",
  "updated": ""
}

I'm closing this issue. Thanks a lot for your help !

Regards
