### ISSUE TITLE
Do not use BodyParser (unsafe)

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback#1405]
There's a security threat on using bodyParser as middleware. It's described in full details here:

http://andrewkelley.me/post/do-not-use-bodyparser-with-express-js.html

If you need to process forms there are other options.

**Comment by raymondfeng** [comment]
@simoami It doesn't apply to LoopBack as we don't enable the multipart. The file upload is handled by loopback-component-storage which uses the formidable that bypasses the temp files.

**Comment by simoami** [comment]
thanks for clarifying!
