### ISSUE TITLE
Different configurations depending on the http hosts

### ISSUE THREAD

**Issue by csbenjamin** [strongloop/loopback#1406]
I have a shopping app used by several stores. Each store has its own database. I can make one copy of the application folder for each store, put the right configuration in each application folder and run each application in different ports.

Is there some approach that allows me run only one instance of my application and it decides what database to use depending what is the value in http host (eg. www.store1.com or www.store2.com)?

**Comment by OwenBrotherwood** [comment]
_Might_ not be a good idea with one instance: depending what one instance means for you.

http://blog.mixu.net/2011/02/01/understanding-the-node-js-event-loop/ was one google link I found when thinking about your question..

---

I am not a developer: just a comment

**Comment by OwenBrotherwood** [comment]
- Each store has it's own database.
- application is started multiple times, but have an environment value set

---

I am not a developer: the above is a comment.

**Comment by OwenBrotherwood** [comment]
:+1:
