### ISSUE TITLE
Question: obtain user model from token

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback#1407]
Hello,
This is just a question for best practices on how to obtain the user model instance from the token. 

Upon successful authentication, User.login() returns a token instance. I need the user model instance so I can query some related models. I noticed that the token.__data.user is what I need. Should I directly rely on this reference or is it better to use User.findById() with the token.userId. I've prefer not to query the db more than necessary.

```
var user = token.__data.user;
user.vendors.count(function(count) { 
  console.log(count);  
});

// or

app.models.user.findById(token.userId, function(err, user) {
  user.vendors.count(function(err, count) { 
    console.log(count);  
  })
});
```

Thanks

**Comment by superkhau** [comment]
Both ways work fine, but I would do it the 2nd way for clarity. 1st seems like a premature optimization to me, unless you've done the tests to quantify needing that extra performance from not performing the extra round trip. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by simoami** [comment]
Thanks Simon!
