### ISSUE TITLE
Update API docs for Promises

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1409]
Per #418, we will need to update API docs for Promise support.  

This issue is for Promise API docs specifically.  It will require additional work on strong-docs to support automated API doc generation.  This may require https://github.com/strongloop-internal/strong-docs/issues/63 (unless there is a workaround that doesn't require the `@promises` annotation.)

Related #1575 and #1576

**Comment by chandadharap** [comment]
@raymond's input here:

**Comment by ritch** [comment]
I don't think we should close this issue. For the short term (this current sprint) I think we should do https://github.com/strongloop/loopback/issues/1575 (I think this was @raymondfeng 's suggestion).

Long term I think we need to add this support and documentation to individual methods.

**Comment by bajtos** [comment]
I think we should postpone this until https://github.com/strongloop-internal/strong-docs/issues/63 is implemented first.

**Comment by bajtos** [comment]
@jannyHou built a list of places where we need to update API docs - it's about 80 methods. See the following comments: 
 - https://github.com/strongloop-internal/scrum-loopback/issues/615#issuecomment-165314984 
 - https://github.com/strongloop-internal/scrum-loopback/issues/615#issuecomment-165546746 
 - https://github.com/strongloop-internal/scrum-loopback/issues/615#issuecomment-166174401
 - https://github.com/strongloop-internal/scrum-loopback/issues/615#issuecomment-166323493

**Comment by crandmck** [comment]
Note that @hacksparrow told me he expects to complete https://github.com/strongloop-internal/strong-docs/issues/63 by end of next week.  Then it will be possible to start on this issue.

**Comment by hacksparrow** [comment]
Support for `@promise` has been implemented along with tests on the [feature/promise](https://github.com/strongloop-internal/strong-docs/tree/feature/promise) branch.

**Comment by davidcheung** [comment]
Placeholder for split up issues of the task
- [ ] [loopback-datasource-juggler](strongloop-internal/scrum-loopback/issues/747)
- [ ] [loopback-core](strongloop-internal/scrum-loopback/issues/748)
- [ ] [strong-remoting](strongloop-internal/scrum-loopback/issues/749)
- [ ] [loopback-connector-rest](strongloop-internal/scrum-loopback/issues/750)

**Comment by bajtos** [comment]
Closing in favour of the issues above.
