### ISSUE TITLE
disableStackTrace bool from config.json is not working for top level URL

### ISSUE THREAD

**Issue by superdave2u** [strongloop/loopback#1410]
#bug - disableStackTrace: true not working

1. clone the repo with:

        git clone -b issue/stacktrace --single-branch https://github.com/superdave2u/loopback-sandbox.git issue-stacktrace

2. cd issue-stacktrace

3. npm install

4. npm test

5. navigate to http://localhost:3000/SomeUnknownUrl and see the stack trace

Note that the command npm start is a shortcut to set the environment to production and run the server. 

Following the documentation both setting the env and changing the bool flag should disable the stack trace but neither seem to do so for *top level urls above the API prefix*

* npm start: NODE_ENV='production' node server/server.js

**Comment by superdave2u** [comment]
I want to point out that this issue is pointing out that the naked URL, not the one prefixed by /api/ is returning this trace. Nested URLs behind /api/ function correctly

**Comment by superdave2u** [comment]
I've updated my first post with updated testing instructions STR from my forked repo

**Comment by loay** [comment]
Hi @superdave2u 
Are you still experiencing the same issue?
Now, you can use the new error handler: https://github.com/strongloop/strong-error-handler
To disable stack and other sensitive info, please set `debug:false`
Thanks.
