### ISSUE TITLE
Operation hook after save not triggered in batch create

### ISSUE THREAD

**Issue by erikverheij** [strongloop/loopback#1413]
Test case; 
![Test case](http://s17.postimg.org/4g7e5tnu7/Screenshot_038.png)

    var q = require('q');
    var loopback = require('loopback');
    var app = require('../server');
    var _ = require('lodash');
    var should = require('chai').should();

    var users = [
      {email: 'foo1@bar.com', password: 'bar1'},
      {email: 'foo2@bar.com', password: 'bar2'}
    ];

    var observerCalled = {
      beforeSave: false,
      afterSave: false
    };

    var User = app.models.User;

    User.observe('before save', function(ctx, next) {
      observerCalled.beforeSave = true;
      next();
    });

    User.observe('after save', function(ctx, next) {
      observerCalled.afterSave = true;
      next();
    });

    beforeEach( function (done) {
      User.destroyAll(function(){
        done();
      });
    });

    describe('Operation hooks on (batch) create', function() {

      it('should trigger before save on single item create.', function(done) {
        observerCalled.beforeSave = false;
        q.invoke(User, 'create', users[0])
          .then(function(){
            try {
              observerCalled.beforeSave.should.be.true;
              done();
            } catch(e){ done(e); }
          });
      });

      it('should trigger before save on batch create.', function(done) {
        observerCalled.beforeSave = false;
        q.invoke(User, 'create', users)
          .then(function(){
            try {
              observerCalled.beforeSave.should.be.true;
              done();
            } catch(e){ done(e); }
          });
      });

      it('should trigger after save on single item create.', function(done) {
        observerCalled.afterSave = false;
        q.invoke(User, 'create', users[0])
          .then(function(){
            try {
              observerCalled.afterSave.should.be.true;
              done();
            } catch(e){ done(e); }
          });
      });

      it('should trigger after save on batch create.', function(done) {
        observerCalled.afterSave = false;
        q.invoke(User, 'create', users)
          .then(function(){
            try {
              observerCalled.afterSave.should.be.true;
              done();
            } catch(e){ done(e); }
          });
      });

    });

**Comment by erikverheij** [comment]
Another issue; When using batch create with 'before save' I do have access to the ctx.instance. However modifications on this object are not persisted. This is working fine on creating a single object.

**Comment by loay** [comment]
Hi @erikverheij 
Are you still experiencing the same issue? Thanks.

**Comment by erikverheij** [comment]
Hi @loay, at the moment I'm not using batch operations in my loopback apps.

**Comment by loay** [comment]
Hi @erikverheij Thanks for your prompt response. 
If you re-use them or run to similar issue, please feel free to leave a comment, so I can investigate further. Thanks.
