### ISSUE TITLE
TypeScript type definition

### ISSUE THREAD

**Issue by davetayls** [strongloop/loopback#1415]
Before I build one manually is it possible to create a TypeScript definitions file from your api docs, even one to then edit and tweak manually?

**Comment by ritch** [comment]
It should be possible to write a script that uses our doc module to build up a TypeScript definition. Unfortunately our doc module isn't open source. You can most likely parse our docs with `dox` and use that output.

Keep us updated, sounds like an interesting idea. Maybe we can automate it?

**Comment by davetayls** [comment]
Thanks @ritch I'll have a go, I would love it if you were able to automate it to keep it up to date with changes. Let me know if you guys would be willing to have a go

**Comment by kierer** [comment]
This is a great idea. I see the issue was closed- is a TypeScript definition file now available somewhere? Thanks

**Comment by davetayls** [comment]
I never managed to get this sorted but would love to hear if someone does

**Comment by tangledpixel** [comment]
I would love to see this. Anybody seen a TSD around for loopback?

**Comment by rob3c** [comment]
Why was this closed? I don't see a definition file in the DefinitelyTyped repo. Can we reopen this?

**Comment by kierer** [comment]
This is becoming a bigger issue by the day around here; encouraged all the more by Google's own adoption of TS in Angular2, our team has pretty much committed to "TS-wherever-possible" and there's a push by some team members to re-evaluate other options (e.g., Meteor) which we had previously passed on in favor of LB for projects that are on-deck. ... not the call I'd make, but the availability of  a TSD (preferably one maintained by the LB team) would certainly help those of us making the case for LB in the near term.

**Comment by superkhau** [comment]
@ritch Was this meant to be closed? Should we reopen it?

**Comment by raymondfeng** [comment]
What about generating the TSD for shared methods only? We have all the information for such signatures as part of the remoting metadata.

**Comment by ritch** [comment]
I've created a new issue to track the development of this feature. +1 in that thread would be nice if you want to see it done (helps us prioritize).

https://github.com/strongloop/loopback/issues/1692

**Comment by tjosbon** [comment]
+1

**Comment by RichardJECooke** [comment]
+1. Both hapi & koa have TS definitions. Our firm is thinking of choosing these instead of loopback.

**Comment by superkhau** [comment]
@RichardJECooke Please +1 at #1692

**Comment by lucaslopez** [comment]
+1

**Comment by zkuang** [comment]
+1

**Comment by mjerez-radical** [comment]
+1

**Comment by amay0048** [comment]
+1

**Comment by k1ng440** [comment]
+1

**Comment by tallesborges** [comment]
+1

**Comment by matts310** [comment]
+1

**Comment by shugi-bugi** [comment]
+1

**Comment by jordialborch** [comment]
+1
