### ISSUE TITLE
dot in id of persistedmodel causes 404

### ISSUE THREAD

**Issue by wouterkwakernaak** [strongloop/loopback#1422]
In my project we have a persisted model where instances of this model are migrated from an existing (non-loopback) project. These model instances already have ids. This is working fine for normal ids but the models that have a dot in the id are causing 404 errors when trying to fetch them by id, while they actually are present in the underlying persistent storage.

The error message is as follows:

{"error":{"name":"Error","status":404,"message":"Unknown \"mymodel\" id \"10.2\".","statusCode":404,"code":"MODEL_NOT_FOUND","stack":"Error: Unknown \"mymodel\" id \"10.2\".\n    at Function.convertNullToNotFoundError (/myproject/node_modules/loopback/lib/persisted-model.js:79:17)\n    at invokeRestAfter (/myproject/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:444:25)\n    at async.series.results (/myproject/node_modules/loopback/node_modules/async/lib/async.js:610:21)\n    at _asyncMap /myproject/node_modules/loopback/node_modules/async/lib/async.js:249:17)\n    at async.eachSeries.iterate (/myproject/node_modules/loopback/node_modules/async/lib/async.js:149:13)\n    at async.eachSeries.iterate (/myproject/node_modules/loopback/node_modules/async/lib/async.js:160:25)\n    at _asyncMap (/myproject/node_modules/loopback/node_modules/async/lib/async.js:251:21)\n    at async.series.results (/myproject/node_modules/loopback/node_modules/async/lib/async.js:615:34)\n    at RemoteObjects.invokeMethodInContext.ctx.error (/myproject/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:601:9)\n    at execStack (/myproject/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:448:7)"}}

Any ideas?

**Comment by raymondfeng** [comment]
What DB do you use? It might be related to the type coercion (10.2 --> number)?

**Comment by wouterkwakernaak** [comment]
Using MongoDB

**Comment by raymondfeng** [comment]
It's probably related to https://github.com/strongloop/loopback/pull/1221

**Comment by davidcheung** [comment]
We no longer allow model names to contain dots, future applications shouldnt face this issue now ,closing issue

**Comment by Amir-61** [comment]
>We no longer allow model names to contain dots, future applications shouldnt face this issue now ,closing issue

Just to add ore info this is the LB 3.0 behaviour; it was a breaking change so we introduced it in LB 3.0
