### ISSUE TITLE
Explore a simpler/more performed way for context propagation

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback#1423]
At the moment, LoopBack uses https://github.com/othiym23/node-continuation-local-storage for implicit context propagation across the async invocation paths. The CLS module has some issues:
1. It adds a lot of overhead
2. Some of the drivers (especially the ones with connection pooling) are not friendly with CLS
   - https://github.com/strongloop/loopback/issues/878
   - https://github.com/strongloop-community/loopback-connector-elastic-search/issues/15

We should explore a simpler/more performed way for context propagation. One idea is to use the `options` argument which is now supported for all CRUD operations. `strong-remoting` can introduce a notation to express the need in remoting metadata to receive the context.

**Comment by seriousben** [comment]
:+1:

**Comment by ritch** [comment]
Here is my proposal: https://github.com/strongloop/loopback/issues/1495

**Comment by bajtos** [comment]
Closing in favour of #1495.
