### ISSUE TITLE
Transaction rollback error

### ISSUE THREAD

**Issue by rus0000** [strongloop/loopback#1426]
I'm using recent Loopback and Juggler with postgresql connector.
In a remoteMethod I'm creating model instance inside a transaction and receive duplicate id error from PK constrain - which is OK.
Trying to handle this error I call `tx.rollback()` and receive connection closed error or sometimes EPIPE error.

**Comment by raymondfeng** [comment]
Please share your test case.

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by bosco-li** [comment]
@rus0000 we will close this issue since it's been inactive for over a year, please feel free to reopen  if you can help provide a test case.  Thank you
