### ISSUE TITLE
Replication and instance-level ACL

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1427]
#1270 implemented support for replicating models that use model-level ACL (i.e. a user can either access all instances or no instances). However, this is not enough for many real-world use cases, where the model is configured with a instance-level ACL (e.g. a user can access only the instances he created himself).

We should improve the replication implementation and support instance-level access permissions too.

**Comment by sachinhub** [comment]
Dear all,

What is the status of "instance-level" ACLs? Is it already implemented or planned to be implemented as enhancement ?

**Comment by jesperbruunhansen** [comment]
Any news on this feature? Or does anybody have ideas how to handle this in a custom build? Our dev-team has been trying off a few ways of doing this, but having native support out the box would be amazing!

**Comment by riterrani** [comment]
Any news on this feature? Anybody have implemented this in a custom build?

Thanks!

**Comment by antoinebrault** [comment]
Any ETA on this feature? This is blocking for a lot of real world applications.

No progress on https://github.com/strongloop/loopback/milestone/17 for a long time.

**Comment by jesperbruunhansen** [comment]
Hi everyone.

My team has open sourced our approach to a custom build of this functionality. Any feedback or help is highly appreciated. Repo: [loopback-object-acl](https://github.com/jesperbruunhansen/loopback-object-acl)

Note: the state of this project is currently in early alpha release and is only tested with Loopback v3.x and MongoDb as datasource.
