### ISSUE TITLE
strong-agent 'failed to instrument mysql' message

### ISSUE THREAD

**Issue by yagobski** [strongloop/loopback#1430]
Hy,

When i start with slc start my application run but i have this error message : 
strong-agent 'failed to instrument mysql' message

I don't know if it is a bug. My application is using mysql connector and all is working fine.

Please see the trace error : 

$ slc run
INFO strong-agent dashboard is at https://strongops.strongloop.com
INFO strong-agent using collector https://collector.strongloop.com:443
INFO strong-agent v1.5.1 profiling app 'App' pid '30292'
INFO strong-agent[30292] started profiling agent
INFO supervisor reporting metrics to `internal:`
supervisor running without clustering (unsupervised)
ERROR strong-agent error: failed to instrument mysql
{ close: [Function],
  transport: 
   { _config: 
      { host: 'localhost:7000',
        __reused: true,
        log: [Object],
        hosts: 'localhost:7000',
        keepAlive: true,
        minSockets: 10,
        maxSockets: 11 },
     log: { _events: [Object] },
     connectionPool: 
      { bound: [Object],
        log: [Object],
        _config: [Object],
        selector: [Function],
        Connection: [Object],
        deadTimeout: 60000,
        maxDeadTimeout: 1800000,
        calcDeadTimeout: [Function],
        index: [Object],
        _conns: [Object],
        _timeouts: [] },
     serializer: {},
     nodesToHostCallback: { [Function] thrift: [Function] },
     maxRetries: 3,
     sniffEndpoint: '/_nodes/_all/clear',
     requestTimeout: 30000 },
  cat: 
   { transport: 
      { _config: [Object],
        log: [Object],
        connectionPool: [Object],
        serializer: {},
        nodesToHostCallback: [Object],
        maxRetries: 3,
        sniffEndpoint: '/_nodes/_all/clear',
        requestTimeout: 30000 } },
  cluster: 
   { transport: 
      { _config: [Object],
        log: [Object],
        connectionPool: [Object],
        serializer: {},
        nodesToHostCallback: [Object],
        maxRetries: 3,
        sniffEndpoint: '/_nodes/_all/clear',
        requestTimeout: 30000 } },
  indices: 
   { transport: 
      { _config: [Object],
        log: [Object],
        connectionPool: [Object],
        serializer: {},
        nodesToHostCallback: [Object],
        maxRetries: 3,
        sniffEndpoint: '/_nodes/_all/clear',
        requestTimeout: 30000 } },
  nodes: 
   { transport: 
      { _config: [Object],
        log: [Object],
        connectionPool: [Object],
        serializer: {},
        nodesToHostCallback: [Object],
        maxRetries: 3,
        sniffEndpoint: '/_nodes/_all/clear',
        requestTimeout: 30000 } },
  snapshot: 
   { transport: 
      { _config: [Object],
        log: [Object],
        connectionPool: [Object],
        serializer: {},
        nodesToHostCallback: [Object],
        maxRetries: 3,
        sniffEndpoint: '/_nodes/_all/clear',
        requestTimeout: 30000 } } }
Browse your REST API at http://localhost:3000/explorer
Web server listening at: http://localhost:3000/
INFO strong-agent[30292] connected to collector

**Comment by gbourgeat** [comment]
I have same problem, please help.

Thanks

**Comment by bistmaster** [comment]
Got the same issue too. Hope this will resolve.

**Comment by astralmedia** [comment]
Also getting the same issue when trying to use mysql.

**Comment by ValeriySoglaev** [comment]
I have same problem

slc run
INFO strong-agent v1.6.0 profiling app 'Wifi-Api' pid '33813'
INFO strong-agent[33813] started profiling agent
INFO supervisor reporting metrics to `internal:`
supervisor running without clustering (unsupervised)
ERROR strong-agent error: failed to instrument mysql
INFO strong-agent not profiling, agent metrics requires a valid license.
Please contact sales@strongloop.com for assistance.
Browse your REST API at http://0.0.0.0:3000/explorer
Web server listening at: http://0.0.0.0:3000/
> models created sucessfully

**Comment by yagobski** [comment]
No body from strongloop team can help to fix this issue?

**Comment by adnanshatil** [comment]
I don't know whether you have the same issue ... I faced the same and solved it in below way 
In server/boot/datasources.json I had below things ... 

  "appDB": {
    "host": "localhost",
    "port": 3306,
    "database": "***",
    "password": "***",
    "name": "***",
    "user": "***",
    "connector": "mysql"
  }

No "username" element was there. So I have added it manually and it solves the whole problem. So finally it looks like this- 

  "appDB": {
    "host": "localhost",
    "port": 3306,
    "database": "***",
    "password": "***",
    "name": "***",
    "user": "***",
    "connector": "mysql",
    "username": "***"
  }

**Comment by bossyang** [comment]
Yes, I have the same issue. I add datasource.production.js  for production environment but without "user" property. The strong-pm  server started and models created successfully.
````javascript
module.exports = {
  db: {
    connector: 'mysql',
    database: 'demo',
    host: '127.0.0.1',
    username: process.env.DB_USERNAME,
    password: process.env.DB_PASSWORD
  }
}

````

Jun 22 09:40:44 api ntpd[1023]: 0.0.0.0 c012 02 freq_set kernel 34.530 PPM
Jun 22 09:40:45 api strong-pm: sl-pm.js: StrongLoop PM v4.3.1 (API v6.1.0) listening on port `8701`
Jun 22 09:40:45 api strong-pm: sl-pm.js: control listening on path `/var/lib/strong-pm/pmctl`
Jun 22 09:40:47 api strong-pm: Request (set-size) of current (none)
Jun 22 09:40:47 api strong-pm: Request (tracing) of current (none)
Jun 22 09:40:47 api strong-pm: Request (set-size) of current (none)
Jun 22 09:40:47 api strong-pm: sl-pm.js: listen on 8701, work base is `/var/lib/strong-pm`, driver i
s `direct-driver`
Jun 22 09:40:47 api strong-pm: Run request for commit "1/default" on current (none)
Jun 22 09:40:47 api strong-pm: Start Runner: commit 1/default
Jun 22 09:40:48 api strong-pm: 2015-06-22T01:40:48.332Z pid:1209 worker:0 INFO strong-agent v1.6.0 p
rofiling app 'loopback-example-access-control' pid '1209'
Jun 22 09:40:48 api strong-pm: 2015-06-22T01:40:48.338Z pid:1209 worker:0 INFO strong-agent[1209] st
arted profiling agent
Jun 22 09:40:48 api strong-pm: 2015-06-22T01:40:48.339Z pid:1209 worker:0 INFO supervisor starting (
pid 1209)
Jun 22 09:40:48 api strong-pm: 2015-06-22T01:40:48.340Z pid:1209 worker:0 INFO strong-agent strong-a
gent using strong-cluster-control v2.1.1
Jun 22 09:40:48 api strong-pm: 2015-06-22T01:40:48.341Z pid:1209 worker:0 INFO supervisor reporting
metrics to `internal:`
Jun 22 09:40:48 api strong-pm: 2015-06-22T01:40:48.343Z pid:1209 worker:0 INFO strong-agent not prof
iling, agent metrics requires a valid license.
Jun 22 09:40:48 api strong-pm: 2015-06-22T01:40:48.343Z pid:1209 worker:0 Please contact sales@stron
gloop.com for assistance.
Jun 22 09:40:48 api strong-pm: 2015-06-22T01:40:48.346Z pid:1209 worker:0 INFO supervisor size set t
o 1
Jun 22 09:40:49 api strong-pm: 2015-06-22T01:40:48.373Z pid:1209 worker:0 INFO supervisor listening
on 'runctl'
Jun 22 09:40:49 api strong-pm: 2015-06-22T01:40:48.657Z pid:1209 worker:0 INFO supervisor started wo
rker 1 (pid 1261)
Jun 22 09:40:49 api strong-pm: 2015-06-22T01:40:48.658Z pid:1209 worker:0 INFO supervisor resized to
 1
Jun 22 09:40:49 api strong-pm: Request (status) of current Runner: child 1209 commit 1/default
Jun 22 09:40:49 api strong-pm: Request {"cmd":"status"} of Runner: child 1209 commit 1/default
Jun 22 09:40:49 api strong-pm: 2015-06-22T01:40:49.432Z pid:1261 worker:1 INFO strong-agent v1.6.0 p
rofiling app 'loopback-example-access-control' pid '1261'
Jun 22 09:40:49 api strong-pm: 2015-06-22T01:40:49.440Z pid:1261 worker:1 INFO strong-agent[1261] st
arted profiling agent
Jun 22 09:40:52 api strong-pm: 2015-06-22T01:40:52.349Z pid:1261 worker:1 ERROR strong-agent error:
failed to instrument mysql
Jun 22 09:40:53 api strong-pm: 2015-06-22T01:40:53.408Z pid:1261 worker:1 INFO strong-agent not prof
iling, agent metrics requires a valid license.
Jun 22 09:40:53 api strong-pm: 2015-06-22T01:40:53.408Z pid:1261 worker:1 Please contact sales@stron
gloop.com for assistance.
Jun 22 09:40:53 api strong-pm: 2015-06-22T01:40:53.436Z pid:1261 worker:1 Browse your REST API at ht
tp://0.0.0.0:3001/explorer
Jun 22 09:40:53 api strong-pm: 2015-06-22T01:40:53.437Z pid:1261 worker:1 Web server listening at: h
ttp://0.0.0.0:3001/
Jun 22 09:40:53 api strong-pm: sl-pm.js: Service "1" listening on 0.0.0.0:3001
Jun 22 09:40:54 api strong-pm: 2015-06-22T01:40:53.545Z pid:1261 worker:1 AccessToken model migrated
...

**Comment by delbekio** [comment]
same issue, although i can use the model from the api explorer.
$ slc run .
INFO strong-agent native addon missing, install a compiler
INFO strong-agent v1.6.0 profiling app 'Givesomebody' pid '25344'
INFO strong-agent[25344] started profiling agent
INFO supervisor reporting metrics to `internal:`
supervisor running without clustering (unsupervised)
ERROR strong-agent error: failed to instrument mysql
INFO strong-agent not profiling, agent metrics requires a valid license.
Please contact sales@strongloop.com for assistance.
Browse your REST API at http://localhost:3000/explorer
Web server listening at: http://localhost:3000/
null

**Comment by adnanshatil** [comment]
if you use $ slc run . and mysql at the same time then loopback expects some license for monitoring purposes. I don't know whether they have any plan to remove this message for non license version. But if you want to avoid this then just simply do $ node . 

It is perfectly alright ...

**Comment by delbekio** [comment]
Thanks @adnanshatil for your reply.
so the "failed to instrument" error is related to monitoring only, right?

**Comment by adnanshatil** [comment]
Yes, you can consider this just as an warning message that strong-agent requires a valid license to report monitoring to StrongLoop Arc. https://strongloop.com/node-js/performance-monitoring/

**Comment by delbekio** [comment]
Thanks for the clarification.

**Comment by yagobski** [comment]
Hi,

Even with license this message still displayed in log system.
I still not found solution for this problem

Thanks for your help

2015-06-26 19:46 GMT+02:00 delbekio <notifications@github.com>:

**Comment by superkhau** [comment]
Please post PM related issues at https://github.com/strongloop/strong-pm/issues.

/cc @rmg @sam-github

**Comment by sam-github** [comment]
Re-opened in correct repo, thanks for reporting, please follow along there.

https://github.com/strongloop/strong-pm/issues/258
