### ISSUE TITLE
any plans for defining validation on model.json

### ISSUE THREAD

**Issue by csbenjamin** [strongloop/loopback#1433]
I saw that in model.json there is a validations properties, but the [doc](http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Validations) says "This is not yet implemented". Any plans to implement this nice feature?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
