### ISSUE TITLE
err:  { [Error: ETIMEDOUT] code: 'ETIMEDOUT' } if using  'Model.invoke({}, function(err, result, response){...}'

### ISSUE THREAD

**Issue by penzhan8451** [strongloop/loopback#1434]
Hi,

I use loopback rest connector by using Model.invoke() method like below code.  But I got an error:
err:  `{ [Error: ETIMEDOUT] code: 'ETIMEDOUT' }`.

```
var restConn = require("loopback-connector-rest");
      var dsCfg = {
              connector: restConn,
              debug: true,
              operations: [
                {
                  template: {
                    "method": "POST",
                    "url": posturl,
                    "headers": {
                      "accepts": "application/json",
                      "content-type": "application/json",
                      "Content-Length": payload_str.length,
                      "Authorization": "Bearer " + access_token
                    },
                    "body": payload
                  },
                  functions: {
                    "putToDropbox":[]
                  }
                }
              ]};

    var ds = server.dataSource(dsName, dsCfg);

    var newModel = server.loopback.createModel(boxName,mcfg);
          newModel.attachTo(ds);
          server.model(newModel);
      };

      newModel.invoke({}, function(err, result, response){
         if(err) {
          console.log('err: ', err);
          res.status(400).json({code:-1,msg:'upload file fail.'}).end();
        } else {
          console.log('Result: %j', result);
          res.status(200).json({code:0,msg:'upload file done.'}).end();
        }

      });
```

But If I use   POST directly to ''https://api-content.dropbox.com/1/files_put/auto/' like below code,  It can be successful.
------------------------------
var options = {
        method: 'post',
        url: 'https://api-content.dropbox.com/1/files_put/auto/',
        headers: {
            'Content-Type': 'application/json',
            'Accept':'application/json',
            'Content-Length': payload_str.length,
            'Authorization': 'Bearer ' + access_token
        },
        body: payload_str
    };

    request(options, cb);
------------------------------

Could you please help have a look ?  Thanks.

**Comment by penzhan8451** [comment]
When Invoke the data (about 28k), this error will occurred.   If invoke a very simple data like {name:'xxx',address:'xxxx'},  no errors happened.

**Comment by raymondfeng** [comment]
Please try to add `timeout` property to the data source settings to control the timeout of the underlying request module.

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by penzhan8451** [comment]
Hi Raymond,

Thanks for your prompt reply!   I added 'timeout' property like below:
----------------------
var restConn = require("loopback-connector-rest");
      var dsCfg = {
              connector: restConn,
              debug: true,
              operations: [
                {
                  template: {
                    "method": "POST",
                    "url": posturl,
                    "headers": {
                      "accepts": "application/json",
                      "content-type": "application/json",
                      "Content-Length": payload_str.length,
                      "Authorization": "Bearer " + access_token
                    },
                    "body": payload
                  },
                  timeout: 10000,
                  functions: {
                    "putToDropbox":[]
                  }
                }
              ]};
----------------------

The 'ETIMEOUT' error disappear,  but another error occurred:
'err:  { [Error: socket hang up] code: 'ECONNRESET' }'

I am not sure If this is a network issue (I tried it many times),  DO you have any idea or  Is there  alternative way to do it by  loopback rest connector, typically for the size 1M data ?

Thanks in advance.

**Comment by loay** [comment]
Hi @penzhan8451 that's a connection error, and it means that the other side has closed the connection. Are you still experiencing the same issue?
There are couple of fixes here: http://stackoverflow.com/questions/17245881/node-js-econnreset

**Comment by loay** [comment]
Closing this case for inactivity. If you are still experiencing the same issue, please feel free to leave a comment and the case will be re-opened. Thanks.
