### ISSUE TITLE
Tree mixin

### ISSUE THREAD

**Issue by csbenjamin** [strongloop/loopback#1435]
I'm looking for a tree model, like [this](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/tree.md) doctrine extension. Is there something like that already implemented? If there is not nothing, I would like to implement a base model to extend my nested models from it. Also, I would like to write a open source code. any advice? any tip?

**Comment by csbenjamin** [comment]
well, I'm coding a mixin. When it has been deployed, I will post the link here

**Comment by csbenjamin** [comment]
Here is the tree mixin repository https://github.com/csbenjamin/loopback-tree-mixin
If someone wants to contribute, he will be welcome. For now, this mixin only add `lft` and `rgt` properties and a relation `belongsTo` called `parent` to the model. It automatically adds the `lft` and `rgt` values according with the `parentId` value when `before save` event is triggered.

**Comment by fabien** [comment]
@csbenjamin thanks, this looks interesting! A small suggestion: perhaps you can use `ctx.options.__treeDoNothing` instead of `instance.__treeDoNothing`. You'd have to pass that option at https://github.com/csbenjamin/loopback-tree-mixin/blob/master/tree.js#L200 to `save` for it to work.

**Comment by csbenjamin** [comment]
@fabien Thanks for the suggestion. I changed that.
