### ISSUE TITLE
MongoDB long numbers are saved as double

### ISSUE THREAD

**Issue by ekussberg** [strongloop/loopback#1439]
I have tried to save the EAN code to mongodb and the loopback is saving the value as "double", but actually it is a NumberLong type. "1234567890123" - for example will go to "1234567890123.000000". Do i do something wrong or it is a bug?

**Comment by raymondfeng** [comment]
What is the JavaScript type do you have for the EAN code?

**Comment by kuskov** [comment]
In the model I defined it as a "number" and the number is generated by chance library, so it's a number.

**Comment by raymondfeng** [comment]
[BSON](http://bsonspec.org/spec.html) supports 64 bit numbers but JavaScript/JSON doesn't. One potential solution is to allow custom property types.

**Comment by kuskov** [comment]
You mean to create a new property type like "bigInt" and create a custom validation?

**Comment by projectxmaker** [comment]
is there any final answer for this question ?
