### ISSUE TITLE
Making stream as argument in remote method

### ISSUE THREAD

**Issue by Karabi-Choudhury** [strongloop/loopback#1440]
I wanted to design a remote method to take in a stream as input .Further more i want to parse the stream.For the parsing part i have taken help of some external library.

But how do i make stream as input arguement in remote method

**Comment by Karabi-Choudhury** [comment]
What is exactly happening is a csv gets uploaded and my remote method should take the csv as input and do some operations

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
