### ISSUE TITLE
Seems there is no way to access Roles from User Object/API

### ISSUE THREAD

**Issue by valllabh** [strongloop/loopback#1441]
It seems there is no way to access `User` `Roles` in user query.

I tried to create relation `roles` in `User`

```
"relations": {
    "roles": {
      "type": "hasAndBelongsToMany",
      "model": "Role",
      "through": "RoleMapping",
      "polymorphic": "principal"
    }
}
```

adding roles to user `userObj.roles.add(roleObj)` works and create following entry in `RoleMapping`

```
{
    "_id" : ObjectId("5576deca062655136bdb154c"),
    "principalType" : "user",
    "principalId" : "5576dec9062655136bdb154a",
    "roleId" : ObjectId("5576deca062655136bdb154b")
}
```

but when I try to query in `user/{id}/roles` output comes blank/empty array. 
I also tried updating `"principalType" : "user"` to `"principalType" : "USER"` but nothing works.

**Comment by mneil** [comment]
I just ran into this issue as well. Roles are always empty when using include on users with Mongo DB. Might be related to https://github.com/strongloop/loopback/issues/274.

**Comment by alFReD-NSH** [comment]
I followed this [gist](https://gist.github.com/spencermefford/bc73812f216e0e254ad1) and it works perfectly for me.

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by valllabh** [comment]
@superkhau is this for me?

**Comment by superkhau** [comment]
@valllabh Yes please, I would like to try to reproduce the issue on my end to confirm the bug.

**Comment by valllabh** [comment]
@superkhau alright give me some time to extract and prepare test project.

**Comment by superkhau** [comment]
Thanks.

**Comment by khashayar** [comment]
It only happens with MongoDB as a datasource.

@superkhau 
1) Create a custom 'user' model based on 'User' model
2) Add following relation to it:

```json
  "relations": {
    "roles": {
      "type": "hasMany",
      "model": "Role",
      "foreignKey": "principalId",
      "through": "RoleMapping"
    }
  }
```
3) Create a boot script with following code

```javascript
module.exports = function(server) {
  var User = server.models.User;
  var Role = server.models.Role;
  var RoleMapping = server.models.RoleMapping;

  var users = [
    {firstName: 'John', lastName: 'John', email: 'john@example.com', password: 'opensesame'},
    {firstName: 'Jane', lastName: 'John', email: 'jane@example.com', password: 'opensesame'},
    {firstName: 'Bob',  lastName: 'John', email: 'bob@example.com', password: 'opensesame'}
  ];

  User.create(users, function(err, users) {
      if (err) {return console.log(err);}

      //create the admin role
      Role.create({
        name: 'admin'
      }, function(err, role) {
        if (err) {console.log(err);}

        //make bob an admin
        role.principals.create({
          principalType: RoleMapping.USER,
          principalId: users[0].id
        }, function(err, principal) {
          console.log(err, principal);
        });
      });
    });
};

```

Now check the [GET} /users result with `{include: "roles"}`, the roles array for first user is empty!


Adding the following lines would inside the boot script would solve the problem:

```javascript
RoleMapping.belongsTo(User);
User.hasMany(RoleMapping, {foreignKey: 'principalId'});
Role.hasMany(User, {through: RoleMapping, foreignKey: 'roleId'});
```

**Comment by alFReD-NSH** [comment]
@khashayar that happens because you're using th e built in `User` model which doesn't have the relationships defined for it and not your custom built `user` model I believe.

**Comment by khashayar** [comment]
@alFReD-NSH Actually I'm using my custom `user` model. It was a typo once I entered the sample code here on Github. I updated the actual sample code.

**Comment by AurelieV** [comment]
OK @jannyHou let's continue the discussion here.
I have try this on my production server, and still not working

db version v3.2.1
node version: v4.2.4

**Comment by AurelieV** [comment]
@jannyHou I made some investigation today.
The error is on the include.js, for the request how search RoleMapping corresponding to users.
The request is a find with where: principalId inq ['id_user_1', 'id_user_2].
This request find nothing, despite the fact that there is some matching in the database.
I try to make the request manually via the explorer, and there is the same problem. When finding RoleMapping with filter where and inq with some id, nothing is found.

May be it's because id are translated into objectId and principalId is a string type?

But I have no idea why it works for you and not for me. Maybe the different version of connector and data-source-juggler are important. But I can't obtain your version by npm install. Maybe I will fetch it manually and try

**Comment by AurelieV** [comment]
So, to be more precise, in GET RoleMappings/, value of filter

- {"where":{"principalId":{"inq":["56af806cf7dcf2983bb8c64d"]}}} not working
- {"where":{"principalId":"56af806cf7dcf2983bb8c64d"}} working

I think the problem is with ObjectId/String not handle for tab?

**Comment by alFReD-NSH** [comment]
The problem is that, mongo connector automatically converts strings in queries(in `inq` in this case) to ObjectId if they look like it(if it is 24 hex characters), but `principalId` in `roleMapping` is a string. There's already an issue for this: strongloop/loopback-connector-mongodb/#128

**Comment by AurelieV** [comment]
@alFReD-NSH but in this case, why the simple filter works? Normally this has to be the same problem no?
And why @jannyHou has not the same problem with the same configuration?
I will try to force the principalId to ObjectId

**Comment by alFReD-NSH** [comment]
It only converts `inq` and `nin`: https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L587-L597

If the roleMappings are inserted with principalId as ObjectId it would be fine, which is why I think he's not experiencing the problem.

**Comment by AurelieV** [comment]
But we ran the exact same code ...
Nevermind, I may try to force the ObjectId type, but I think that is Loopback which converts it internally at insertion.
So waiting for the merge. Thanks for your explanations

**Comment by AurelieV** [comment]
An other solution may be to use polymorphic relation for principal rather than string type no?

**Comment by alFReD-NSH** [comment]
I think with polymorphic we'll end up with the same thing, given that it will use `inq` to query stuff.

**Comment by AurelieV** [comment]
Yeah but the type of principalId will change from string to ObjectId no?

**Comment by alFReD-NSH** [comment]
You can do that with `RoleMapping.defineProperty('principalId', { type: 'ObjectID' });`. I'm gonna try this later.

**Comment by AurelieV** [comment]
I will try this this morning, but this is not a permanent solution because we need to not be dependant of the database type.

**Comment by noderat** [comment]
Something similar to the following seems to be working for me.
```javascript
RoleMapping.defineProperty('principalId', { type: require('mongodb').ObjectId });
```

**Comment by AurelieV** [comment]
@noderat with your solution, I have error 500 because sometime it's try to convert objectId into Id, which fail (objectId only accept string)
@alFReD-NSH with your solution I have "Error: Model ObjectID is not defined."

**Comment by AurelieV** [comment]
This is what finally work for me

`RoleMapping.defineProperty('principalId', { type: function(id) {return require('mongodb').ObjectId('' + id)}`

**Comment by alFReD-NSH** [comment]
Here's what I ended up doing:

```
      RoleMapping.defineProperty('principalId', {
        type: function(string) {
          return RoleMapping.getDataSource().ObjectID(string);
        }
      });
```

It uses the [`ObjectID` defined by the mongodb connector](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L15-L34) which will handle the cases where the input cannot be converted to ObjectID.

**Comment by AurelieV** [comment]
@jannyHou any update for this issue?

**Comment by leftclickben** [comment]
I've hit this issue too, and in my case I've found that using a different version of the `loopback-connector-mongodb` module made the difference.  With `v1.13.2`, doing `GET /Users` with a filter that has `{"include":"roles"}` works correctly.  With exactly the same code base, apart from upgrading `loopback-connector-mongodb` to `v1.13.3`, the `roles` is always returned as an empty array.

This cannot be the full story, because this issue pre-dates `v1.13.3` however it worked for me and might for others.

This is the difference between the two versions: https://github.com/strongloop/loopback-connector-mongodb/compare/v1.13.2...v1.13.3

**Comment by KaanErkol** [comment]
Is there any update?

**Comment by hussainak** [comment]
I believe the project is probably dead due to a recent restructure in IBM.

**Comment by superkhau** [comment]
>I believe the project is probably dead due to a recent restructure in IBM.

@hussainak The project is not dead, we are all very busy working on various projects. If you need immediate support, we offer a variety of subscriptions. See https://strongloop.com/node-js/subscription-plans/.

That said, can someone provide sample project with some instructions so I can reproduce on my end? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report. For now, I will bump this up to a major so someone can take a look at it sooner, but it would definitely help if someone can set up a sample project please.

**Comment by AurelieV** [comment]
@superkhau I have provided a repo wich reproduces the error in issue #1986.

**Comment by superkhau** [comment]
@AurelieV Can you provide a link to the sample project and not the closed issue so I don't have to dig through the discussion please?

**Comment by AurelieV** [comment]
Sorry, was on mobile, and couldn't do it easliy. Moreover the conversation is interessting because it provide the way to reproduce (or not) the problem.

The repo https://github.com/AurelieV/loopback-sandbox

**Comment by jannyHou** [comment]
@AurelieV feel very sorry for replying you late, I was working on another deadline after talked with you about this issue one month before, now I am back on loopback issue and trying to debug your repo.

I still get the right response:
```
{
    "username": "admin",
    "email": "test@test.com",
    "id": "56aa774c0daba22c21e54d6b",
    "roles": [
      {
        "id": "56aa774a0daba22c21e54d67",
        "name": "admin",
        "created": "2016-01-28T20:17:14.858Z",
        "modified": "2016-01-28T20:17:14.858Z"
      }
    ]
  }
```
I run `npm install` from npmjs registry so I should have the same version of dependants as you.
mongodb:3.2 
strongloop: "version": "5.0.1"
loopback-connector-mongodb: 1.13.3
loopback-datasource-juggler:   "version": "2.45.2",

**Comment by alFReD-NSH** [comment]
Actually it works because it contains [the workaround](https://github.com/AurelieV/loopback-sandbox/commit/cbea3fbe8d14d3037ff3449da3968c4bdc4d0a42#diff-96763114acceee670bf46aa969ed0126R14).

**Comment by AurelieV** [comment]
Yes sorry, I have forgotten I have put it here :s

**Comment by jannyHou** [comment]
Good. After clearing my mongodb database, I can reproduce the error now.

**Comment by AurelieV** [comment]
@jannyHou  Wonderful \o/.
It seems to be connected to the fact that principalId is a string, rather an ObjectId.

**Comment by jannyHou** [comment]
@AurelieV I keep failing to reproduce it because if the data existed in db, it always contains `roles` no matter using the workaround line or not.
 4 scenarios:
- [x] Empty db. With workaround
- [ ] Empty db. Without workaround
- [x] db with data. With workaround
- [x] db with data. Without workaround

I check the scenarios that work fine.
 
So do you also fail to include roles in scenario no.4?

BTW, someone also reports that mongo seems using `toString()`, which causes problem: https://github.com/strongloop/loopback/issues/1994#issuecomment-206310037

**Comment by AurelieV** [comment]
@jannyHou  In which way do you create the data in DB?

**Comment by jannyHou** [comment]
@AurelieV 
1. run app with `node .` it will create data into empty db
2. try filter without workaround, roles in response is empty [ ] (but data should be in db, this confused me)
3. terminate app, run it again with `node .`,  the data should exist in db
4. try filter with or without workaround, response contains roles

**Comment by AurelieV** [comment]
I run the app, previously I erase all my database to have a clean one.
Filter not work, even if RoleMapping show that the relation exist.
Restart the app does not change the result :s

**Comment by AurelieV** [comment]
@jannyHou but if one time I run it with the workaround, all the time after, even without workaround; it works

**Comment by AurelieV** [comment]
@jannyHou And this is because with the workaround, a new RoleMapping is created in the database, with an ObjectId rather than a string for principalID. When you see RoleMapping, two objects exist, and the role is retrieved by the one with an objectId as principalId

**Comment by jannyHou** [comment]
@AurelieV nice it makes sense! thank you

**Comment by younes200** [comment]
Hi,
Any updates on this issue ? the related [#128](https://github.com/strongloop/loopback-connector-mongodb/issues/128#issuecomment-180768180) issue on loopback-connector-mongodb was fixed but the bug still exists and need  @alFReD-NSH workaround.
Thank you.

**Comment by sschimmel** [comment]
Even with the workaround and a fresh database I can't get this to work. Looking at the security debug output it seems that no RoleMapping can be found.

There is a role and a user present and the role mapping record contains the corrects id's as an Object() instead of as string.

Debug output:
```
2016-08-19 12:21:29.555   loopback:security:access-context ---AccessContext--- +0ms
2016-08-19 12:21:29.555   loopback:security:access-context principals: +0ms
2016-08-19 12:21:29.556   loopback:security:access-context principal: {"type":"USER","id":"123456789a00000000000000"} +1ms
2016-08-19 12:21:29.556   loopback:security:access-context modelName InviteRequest +0ms
2016-08-19 12:21:29.557   loopback:security:access-context modelId undefined +1ms
2016-08-19 12:21:29.557   loopback:security:access-context property find +0ms
2016-08-19 12:21:29.557   loopback:security:access-context method find +0ms
2016-08-19 12:21:29.557   loopback:security:access-context accessType READ +0ms
2016-08-19 12:21:29.557   loopback:security:access-context accessToken: +0ms
2016-08-19 12:21:29.558   loopback:security:access-context   id "V9ya2rC9u3vmTknJ5ZrCIl8puFNTQWCDMJo9VZA9WjzXKT1tMmunpY5zziorLFhG" +1ms
2016-08-19 12:21:29.558   loopback:security:access-context   ttl 1209600 +0ms
2016-08-19 12:21:29.558   loopback:security:access-context getUserId() 123456789a00000000000000 +0ms
2016-08-19 12:21:29.558   loopback:security:access-context isAuthenticated() true +0ms
2016-08-19 12:21:29.558   loopback:security:role Custom resolver found for role $everyone +0ms
2016-08-19 12:21:29.558   loopback:security:role isInRole(): admin +0ms
2016-08-19 12:21:29.558   loopback:security:access-context ---AccessContext--- +0ms
2016-08-19 12:21:29.558   loopback:security:access-context principals: +0ms
2016-08-19 12:21:29.558   loopback:security:access-context principal: {"type":"USER","id":"123456789a00000000000000"} +0ms
2016-08-19 12:21:29.559   loopback:security:access-context modelName InviteRequest +0ms
2016-08-19 12:21:29.559   loopback:security:access-context modelId undefined +1ms
2016-08-19 12:21:29.559   loopback:security:access-context property find +0ms
2016-08-19 12:21:29.559   loopback:security:access-context method find +0ms
2016-08-19 12:21:29.559   loopback:security:access-context accessType READ +0ms
2016-08-19 12:21:29.559   loopback:security:access-context accessToken: +0ms
2016-08-19 12:21:29.559   loopback:security:access-context   id "V9ya2rC9u3vmTknJ5ZrCIl8puFNTQWCDMJo9VZA9WjzXKT1tMmunpY5zziorLFhG" +0ms
2016-08-19 12:21:29.560   loopback:security:access-context   ttl 1209600 +1ms
2016-08-19 12:21:29.560   loopback:security:access-context getUserId() 123456789a00000000000000 +0ms
2016-08-19 12:21:29.560   loopback:security:access-context isAuthenticated() true +0ms
2016-08-19 12:21:29.562   loopback:security:role Role found: {"id":"57b6d236fe6478355e180818","name":"admin","created":"2016-08-19T09:32:37.599Z","modified":"2016-08-19T09:32:37.599Z"} +2ms
2016-08-19 12:21:29.564   loopback:security:role Role mapping found: null +2ms
2016-08-19 12:21:29.564   loopback:security:role isInRole() returns: false +0ms
```

User database record:
```json
{
    "_id" : ObjectId("123456789a00000000000000"),
    "name" : "masteradmin",
    "locale" : "nl-NL",
    "state" : {},
    "password" : "$2a$10$Sv.onOFY4aVO21r4AZbBs.fYL1l7jlPwszWXUW5.Hyc5yrGuJjWZu",
    "emailVerified" : true
}
```

Roles:
```json
{
    "_id" : ObjectId("57b6d236fe6478355e180818"),
    "name" : "admin",
    "created" : ISODate("2016-08-19T09:32:37.599Z"),
    "modified" : ISODate("2016-08-19T09:32:37.599Z")
}
```

RoleMapping:
```json
{
    "_id" : ObjectId("57b6d237fe6478355e180846"),
    "principalType" : "USER",
    "principalId" : ObjectId("123456789a00000000000000"),
    "roleId" : ObjectId("57b6d236fe6478355e180818")
}
```

**Comment by mpycio** [comment]
I've been struggling with this for some time now as well, but what worked for me after updating to 2.38.0 was adding a 'role-mapping.json' file with updated props as follows:

```
{
  "name": "RoleMapping",
  "description": "Map principals to roles",
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "generated": true
    },
    "principalType": {
      "type": "string",
      "description": "The principal type, such as user, application, or role"
    }
  },
  "relations": {
    "role": {
      "type": "belongsTo",
      "model": "Role",
      "foreignKey": "roleId"
    },
    "user": {
      "type": "belongsTo",
      "model": "User",
      "foreignKey": "principalId"
    }
  }
}

```

**Comment by bajtos** [comment]
A possible workaround is described in https://github.com/strongloop/loopback/issues/3121#issuecomment-280635105.

**Comment by rashmihunt** [comment]
@valllabh Are you good with the workaround suggested by @bajtos ?https://github.com/strongloop/loopback/issues/3121#issuecomment-280635105 If yes, we like to close this item.

**Comment by jmereaux** [comment]
Is there a working solution for this issue now?
I have defined a "roles" relation on my custom user model (as described by @khashayar), but when querying a user's roles, the returned array is still empty.

**Comment by jmereaux** [comment]
Seems like adding the following does the trick:
* `"keyThrough": "roleId"` on the `roles` relation in the custom user model
* `"keyThrough": "principalId"`on the `users` relation in the custom role model

**Comment by Amenocy** [comment]
I think this problem already exist :((
using mongodb
I have this relationship in my custom user model : 
```
 "relations": { 
    "roles": {
      "type": "hasMany",
      "model": "Role",
      "foreignKey": "principalId",
      "keyThrough": "roleId",
      "through": "RoleMapping"
    }
  }
```
and in database rolemapping "principalType:"USER"
http://localhost:8080/api/users/5c03ba0876f1bf22845bf2c9/roles return empty array .
