### ISSUE TITLE
loopback.getCurrentContext() is null on Node 0.12.x in Operational Hooks

### ISSUE THREAD

**Issue by nicolasembleton** [strongloop/loopback#1442]
Whenever I call loopback.getCurrentContext() in operational hooks `Model.observer('before save',`, I get this error:

```
      var user = loopback.getCurrentContext().get('currentUser');
                                             ^
TypeError: Cannot read property 'get' of null
```

It seems to only happen with Node 0.12.x (0.10.3X+ is ok) and it also started to happen in Loopback 2.18. It was working before we upgrade our NPM packages to the latest versions.

Downgrading to Node 0.10.XX solved our problem for now.

**Comment by nicolasembleton** [comment]
Also, the loopback package versions:
```
├─┬ gulp-loopback-sdk-angular@0.1.3
│ ├─┬ loopback-sdk-angular@1.3.7
├─┬ loopback@2.18.0
│ ├── loopback-connector-remote@1.0.3
│ ├── loopback-phase@1.2.0
├─┬ loopback-boot@2.8.0
├─┬ loopback-component-storage@1.5.0
├─┬ loopback-connector-mongodb@1.11.0
│ ├── loopback-connector@2.2.1
├─┬ loopback-connector-postgresql@2.1.0
│ ├─┬ loopback-connector@2.2.1
├─┬ loopback-datasource-juggler@2.29.2
│ ├── loopback-connector@2.2.1
├─┬ loopback-explorer@1.7.2
├─┬ loopback-testing@1.0.3
```

**Comment by fabien** [comment]
@bajtos @raymondfeng I had the same issue on 0.10.2x, but 0.10.3x seems to be OK indeed.

**Comment by seriousben** [comment]
Had the same problem, rolling back async to 1.0.0 fixed it.

**Comment by fabien** [comment]
Thanks @seriousben did async cause any other issues for you?

**Comment by seriousben** [comment]
No, everything worked perfectly for me, @fabien

**Comment by kblcuk** [comment]
Having same issue, but reverting async to 1.0.0 did nothing. :-/

**Comment by seriousben** [comment]
I had to use a npm-shrinkwrap to revert async of datasource-juggler.

**Comment by kblcuk** [comment]
Ah, didn't understand that it was async specific to datasource juggler rolled back. Good to know!

**Comment by loay** [comment]
@nicolasembleton 
It looks like issue is fixed. If you are still having troubles, please leave a comment and I will re-open the issue. Thanks
