### ISSUE TITLE
FeatureRequest: Add a Model which has `hasMany` as a `hasMany` relation to a other Model 

### ISSUE THREAD

**Issue by cebor** [strongloop/loopback#1443]
Im looking for a method to do something like that:

User has many Librarys.
Library has many Books.

Is it possible to get all Books belong to a User over a Library:
For Example: `http://api/Users/1/Librarys/2/books`

My workaround for this is, add a extra `hasMany` for `Books` into the `User` and then filter for `libraryId` in the URL.

I also opend a Question on StackOverflow: http://stackoverflow.com/questions/30697212/create-a-hasmany-which-has-a-hasmany-with-loopback/30713942#30713942

**Comment by superkhau** [comment]
Can I close this? It looks like you got some good answers on SO.
