### ISSUE TITLE
New Method: PersistedModel.subscribe

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1444]
This new method should callback with a readable (object mode) stream flowing with `Change` objects. A `Change` object should be added to the stream when a change is made to the `PersistedModel` that matches the provided `filter`.

It should be made remote-able using this: https://github.com/strongloop/strong-remoting/issues/214

```js
// Score is a PersistedModel
Score.subscribe({
  where: {
    views: {gt: 100}
  }
}, function(err, changes) {
  changes.on('data', function(change) {
    console.log('score changed', change.data);
  });
});
```

The source of the `Change` stream is configurable.

 - local
   - only uses hooks to observe changes on the local model
 - pubsub
   - subscribes to a default topic (model name) or a configurable topic
   - must provide a data source name for connecting to a broker

**Comment by ritch** [comment]
This approach has been re-worked: see the new issue https://github.com/strongloop/loopback/issues/1419

**Comment by BerkeleyTrue** [comment]
Wow cool! @ritch what are your thoughts on following the observable pattern established by RxJS instead? It could be made extendable to include composable methods similar in fashion to RxJS and it's already a well established pattern.

**Comment by ritch** [comment]
> what are your thoughts on following the observable pattern established by RxJS instead?

This is actually a great idea. The reason I am using the `Stream` interface is purely because its compose-ability in node land. Eg. if we support `Stream`s in strong-remoting you can do things like upload and download files like this:

```js
// streaming upload
function handleUpload(function(path) {
  cb(null, fs.createWriteStream(path));
}

// streaming download
function download(path) {
  cb(null, fs.createReadStream(path));
}
```

I think the important point is that `Stream`s are not for reactive programming. They are for moving data and in a way that doesn't overload consumers (and handling other tricky cases).

It probably makes sense to only support streams at the `strong-remoting` layer. In your application code it would be nice to have an rxjs compatible api. Implementing this is fairly similar to supporting both callbacks and promises.

I think the advantage of using rxjs is the compatibility / compose-ability, so it doesn't make sense to force users to use that style API if they don't intend to use it in the rest of their application.   

What if we have a low-level api in loopback core (like what I've outlined here) and a wrapper library that provides an rxjs api on top of the low level stream+callback api?

So I guess what is important for the low level API is it should have enough to be wrapped by a `Observerable`. AFAICT all that really means is implementing the [`Observable` interface](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/exploring.md#observable--observer):
Which can actually be adapted fairly easily from a `ReadableStream`.

```js
// something like this
Observable.prototype.subscribe = function (observer) { 
  stream.on('readable', function() {
    var data = stream.read();

    if(data === null) {
      observer.onCompleted();
    } else {
      observer.onNext(data);
    }
  });
}
```

**Comment by ritch** [comment]
Another option is just returning an `Observable` in the core implementation.

**Comment by BerkeleyTrue** [comment]
Here is what I was thinking

```js
Score
  .observable() //
  .where({ views: { gt: 100 }) // custom operator for loopback
  .subscribe(
     function(change) { console.log('score changed', change.data); },
     function (err) { console.log(err);
     function() { console.log('subscription closed); }
  );
```

Since we already have a callback pattern with observer method I don't see much value adding by creating a second subscribe method that takes a callback.

under the hood
```js
Store.observable = function observable() {
  return new Observable(observer => {
    stream.on('readable', function() {
      var data = stream.read();
      if (data === null) {
        return observer.onCompleted();
      }
      observer.onNext(data);
  });
  stream.on('error', function(err) { observer.onError(err) });
}
```

This could be done with a barebones Observable object for loopback and then transition to RxJS when the new modular version comes out.

**Comment by ritch** [comment]
@BerkeleyTrue 

> Since we already have a callback pattern with observer method I don't see much value adding by creating a second subscribe method that takes a callback.

Are you referring to `Model.observe()` ? I agree there is redundancy between `Model.observe()` and `PersistedModel.subscribe()`.

Regarding your proposal, I actually like it from an API perspective. How do we make this a remote method? That is really the important feature. My answer to this is supporting readable object mode streams in strong-remoting and returning those from remote methods.

**Comment by BerkeleyTrue** [comment]
It seems odd to return observables in callbacks or promises since observables themselves are asynchronous but can be defined synchronously. Whatever internal mechanism that is used in strong-remote that is used to determine if the return from a `remoteMethod` is a  promise can be extended to detect observables (a simple `typeof someReturned.subscribe === 'function'` should suffice). That would be the best approach if possible.

If the method is being used remotely and converting it (in strong-remote) to a stream also using strong-remote to convert it back to an observable on the other end?
