### ISSUE TITLE
before save ctx instance inconsistant

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback#1446]
Currently working on three different computers and seeing inconsistent instances on 'before save' hook.

Some of us see 'ctx.currentInstance' with 'ctx.instance' undefined, others see the opposite.

Kind of a pain and seems like a breaking change as this code worked for us a couple of months ago.

my version (getting 'ctx.currentInstance' but not 'ctx.instance')
![1__tmux](https://cloud.githubusercontent.com/assets/6775919/8115713/1adf16e4-1032-11e5-8c00-e46353b7e8d0.png)

Their version (getting `ctx.instance` and not `ctx.currentInstance`)
![screenshot_6_11_15__12_06_pm](https://cloud.githubusercontent.com/assets/6775919/8115761/7664f588-1032-11e5-814f-c21a6667f41c.png)

```js
// common/models/user-identity.js
var debug = require('debug')('freecc:models:userIdent');

var defaultProfileImage =
  require('../utils/constantStrings.json').defaultProfileImage;

module.exports = function(UserIdent) {

 UserIdent.observe('before save', function(ctx, next) {
  var userIdent = ctx.currentInstance; // sometimes undefined
  // ctx.instance somtimes undefined as well
  // treat userIdent as immutable
  userIdent.user(function(err, user) {
    if (err) { return next(err); }
    debug('got user', user.username);

    var picture = userIdent.profile && userIdent.profile[0] ?
      userIdent.profile[0].value :
      null;

    // check if user has picture
    //  set user.picture from twitter
    if (picture && !user.picture || user.picture === defaultProfileImage) {
      debug('use has no pic');
      user.picture = userIdent.profile.photos[0].value;
      user.save(function(err) {
        if (err) { return next(err); }
        next();
      });
    } else {
      debug('exiting after user ident');
      next();
    }
  });
 });
};
```
cc @terakilobyte @quincylarson

**Comment by bajtos** [comment]
Which CRUD methods are you calling? `UserIdent.create` sets `ctx.instance`, `UserIdent.prototype.updateAttributes` sets `ctx.data` and `ctx.currentInstance`. Could that explain the differences you are seeing?

**Comment by BerkeleyTrue** [comment]
We where all using the create method.

**Comment by bajtos** [comment]
@BerkeleyTrue is this issue still present? Could you please provide an example app reproducing the problem, per [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report)?

**Comment by BerkeleyTrue** [comment]
Ended up checking both for existence.

**Comment by Dragomir-Ivanov** [comment]
+1
In my `before save` operation hook, I don't have ctx.instance, nor ctx.currentInstance. I was forced to use ctx.data. loopback.2.12.1. Any ideas? Thanks.

**Comment by bajtos** [comment]
> In my before save operation hook, I don't have ctx.instance, nor ctx.currentInstance. I was forced to use ctx.data. loopback.2.12.1.

An example of a method that does not provide `ctx.instance` nor `ctx.currentInstance`: `MyModel.updateAll`.

**Comment by Dragomir-Ivanov** [comment]
@bajtos Thanks for the response. This happens on MyModel.upsert with only one object. The interesting thing is that on the `after save` operation hook, I don't have `ctx.data` anymore, but have `ctx.instance`. Maybe my understanding of how things work is wrong.

**Comment by bajtos** [comment]
> @Dragomir-Ivanov This happens on MyModel.upsert with only one object. The interesting thing is that on the after save operation hook, I don't have ctx.data anymore, but have ctx.instance. Maybe my understanding of how things work is wrong.

Oh, that's correct too. Let me explain.

When the connector provides optimised implementation of the "upsert" method, it receives only the request data in arguments, not the full model instance. That's why you see "ctx.data" instead of "ctx.instance". Now because we cannot tell in advance whether the operation will result in UPDATE or CREATE, we cannot tell whether there is any existing "currentInstance" affected by the operation.

As for the "after save" hook, we have the full instance which was updated or created, thus the hook gets "ctx.instance" set.

**Comment by Dragomir-Ivanov** [comment]
Thanks, that explains a lot. I didn't do anything special to use the optimized implementation, though. I though updateAttributes() was needed for this.

**Comment by dakotahNorth** [comment]
Why was this closed? 

I just ran into this problem tonight ... and it appears to be much bigger than just a question of optimization since once I hit this issue, validate no longer works. For example ... 

    Question.validatesLengthOf('text', {max: 0, message: {max: 'Question is too long'}})

Now does nothing.
