### ISSUE TITLE
Combining roles

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback#1448]
Is it possible to combine two roles and test against them? 

I want to be able to define an ACL based on whether a user has a combination of a dynamic role *and* a static role, and there are enough combinations that it’s not worth defining a new dynamic role for each one. 

Ideally you'd be able to specify an array for `principalId` in the ACL definition. I don't think there'd be a need for an "or" syntax as you can already achieve that by duplicating the ACL (although that's not ideal).

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
