### ISSUE TITLE
Model name with underscore creates unexpected issue with standalone scripts

### ISSUE THREAD

**Issue by alexxgathp** [strongloop/loopback#1449]
I have a few standalone scripts that a cron runs periodically.

I found out that I was unable to access models with an underscore, while others work.

```javascript
var server = require('../server/server'); // To access models and database

console.log(server.models.project_category); // Model named with underscore is inaccessible
console.log(server.models.projectcategory); // Model named without underscore is accessible
```

**Comment by superkhau** [comment]
@alexxgathp Are you still running into issues? Can you provide a sample repo for me to reproduce the issue?

**Comment by alexxgathp** [comment]
I tested it today on a new project I have. Issue appears to be gone.
