### ISSUE TITLE
Server crashes in createAccessToken

### ISSUE THREAD

**Issue by Rajan** [strongloop/loopback#1450]
/var/www/dealmap-server/node_modules/loopback/common/models/user.js:91
    this.accessTokens.create({
                     ^
TypeError: Cannot read property 'create' of undefined
    at ModelConstructor.User.createAccessToken (/var/www/dealmap-server/node_modules/loopback/common/models/user.js:91:22)
    at /var/www/dealmap-server/node_modules/loopback/common/models/user.js:242:22
    at /var/www/dealmap-server/node_modules/loopback/common/models/user.js:294:9
    at /var/www/dealmap-server/node_modules/loopback/node_modules/bcryptjs/dist/bcrypt.js:230:13
    at /var/www/dealmap-server/node_modules/loopback/node_modules/bcryptjs/dist/bcrypt.js:1167:21
    at Immediate.next (/var/www/dealmap-server/node_modules/loopback/node_modules/bcryptjs/dist/bcrypt.js:1047:21)
    at Immediate._onImmediate (/var/www/dealmap-server/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31)
    at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by Rajan** [comment]
I removed relations from the sub-class and this happened. 
Put them back and it's working.

**Comment by lesterzone** [comment]
@Rajan I have exact same issue, but I'm not sure what do you mean with put relations back...

**Comment by ataraxus** [comment]
Same issue here, could you elaborate whats exactly you fix?

**Comment by mariohmol** [comment]
same thing here.. any helps?

**Comment by amejias101** [comment]
having the same issue with my AppUser class which extends User, but it doesnt have any other fields nor relations, so I'm not sure what is happening

**Comment by raymondfeng** [comment]
For your sub-model json, try to add the following relation definition:
```
"relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "AccessToken",
      "foreignKey": "userId",
      "options": {
        "disableInclude": true
      }
    }
  }
```

**Comment by Royedc4** [comment]
Extended Models loss the base relations? 
```
"relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "accessToken",
      "foreignKey": "userId"
    }
  }
```
It worked without the //options with disableInclude=true
Thanks @raymondfeng
