### ISSUE TITLE
Is it possible to create a Common/Global Hook?

### ISSUE THREAD

**Issue by f0ysal** [strongloop/loopback#1451]
I can define hooks for each model like the following and it works:

```
MyModel.observe('before save', function (ctx, next) {
    if (!ctx.instance) {
      return next();
    }
  ..........
}
```

But is it possible to Create a Global hook so that all models will have a generic hook? 

I tried to access the PersistedModel as in doc

```
var app = require('../server');
var models = app.models;

var persistedModel = models.PersistedModel;
//or
var persistedModel = new PersistedModel
```

But can not access the PersistedModel. 

**So what is the solution for this can anyone help?** 

**Should I make a hook for PersistedModel in that case how to require PersistedModel?** 

**Or what is the best practice to make a global hook for which will intercept every model?**

**Comment by violet-day** [comment]
You can define a parent model.And other child model will inherit parent hook.

**Comment by superkhau** [comment]
There is no global hook, but as @violet-day suggested, you can define hooks in parent models and extend them to child models. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
