### ISSUE TITLE
Unique validation not working?

### ISSUE THREAD

**Issue by zjuasmn** [strongloop/loopback#1452]
Hi all, I am new to strongloop and I am confused about the validation.

The boot script is as follows and it should produce an error when the second user created, but it come out with two users with same email without error. How could it pass the uniqueness validation?

server/boot/script.js

```
module.exports = function (app) {
var User = app.models.User;
  for (var i = 0; i < 2; ++i) {
    User.create({email: "a@b.com", password: "abc"}, function (err, data) {
      console.log(arguments);
    });
  }
}
```

console

```
{ '0': null,
  '1': 
   { email: 'a@b.com',
     password: '$2a$10$0uBsY.q.lodScZ8a4S.V5.UKJivTdvtNM8pwc7ZfVGAg89t6sxx1y',
     id: 557f14d9026532e716c091b2 } }
{ '0': null,
  '1': 
   { email: 'a@b.com',
     password: '$2a$10$KWN6MgidS41KnOxs1HRCKePk9XJLkybtQr.nFT/tv95UYecM2.DXq',
     id: 557f14d9026532e716c091b3 } }
```

Looking forward to your response.

**Comment by lukewendling** [comment]
+1 same problem for me.

**Comment by fabien** [comment]
The reason is that your calling `User.create` in a synchronous `for` loop, instead asynchronously (using the `async` module for example).

**Comment by seminice** [comment]
Same here, I used the validatesUniquenessOf method, tried it both ways, creating users in boot, and using my front end ... updates existing ones..  it doesnt seem to do anything at all while all other validation options work just fine..

`U.validatesUniquenessOf('name', {message: 'name already exists'});`

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by superkhau** [comment]
Escalating to bug status. Reproduced at https://github.com/strongloop/loopback/issues/1637

**Comment by fablife** [comment]
Also seems to fail on property level declaration:

`
  "properties": {
    "name": {
      "type": "string",
      "required": true,
      "index": {"unique": true}
    },  
`
This is being ignored, I can create as many instances with the identical `name`property as I want.

**Comment by Morriz** [comment]
Any progress on this? It's been 5 months

**Comment by superkhau** [comment]
@Morriz It has not been a priority for awhile and probably won't be in the near future. Would any of you guys like to take this on? I can bump the review if someone submits a PR.

**Comment by Morriz** [comment]
I now believe it's inherently impossible to guarantee uniqueness without enforcing it on the db index, and it should be accepted that the code thus throws errors due to concurrent posting with the same creds. So I think this thread may be closed unless somebody can prove otherwise

**Comment by necevil** [comment]
@deepakrkris I am working on a project where I am trying to add a second unique index (right now I am only using the in-memory datasource, but will be moving to mongoDB).  I have been having trouble getting Loopback to enforce unqiueness on anything other than the ID fields that it auto-creates.

Right now I am using the in-model index declaration something along these lines:
```
  "properties": {
    "lengthDays": {
      "type": "number",
      "index": {"unique": true},
      "required": true
    },
}
```

But I can't seem to make things work.  I saw that you self assigned this last month and figured I would see if there is a work around?
