### ISSUE TITLE
Rename subscribe() to createChangeStream()

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1453]
This allows us to have a higher level, `Observable` compliant API later.

/cc @bajtos @BerkeleyTrue

**Comment by BerkeleyTrue** [comment]
Sweet!

**Comment by bajtos** [comment]
:+1:

**Comment by bajtos** [comment]
Can we make this change before the version with `subscribe()` is published to npmjs.org?

**Comment by ritch** [comment]
> Can we make this change before the version with subscribe() is published to npmjs.org?

done and done.
