### ISSUE TITLE
Support creating change streams sourced from all servers in a cluster

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1455]
This requires the ability to publish a change stream to a broker, and convert the incoming messages into a change stream. Ideally this should be initiated from `createChangeStream()` instead of on server start.

**Comment by mcasimir** [comment]
+1

**Comment by thaiat** [comment]
+1

**Comment by jamesjjk** [comment]
@ritch I have implement a change-stream using SSE which works in a cluster using broker (pubsub). It would be great to understand why you think it should be initiated from createChangeStream or equivalent model method?
