### ISSUE TITLE
Middleware does not run properly in development and staging environment

### ISSUE THREAD

**Issue by zanemcca** [strongloop/loopback#1457]
I think there could be a bug somewhere that is preventing middleware from routes:after and on from being run.

I have created a reproduction of the bug in this [repo](https://github.com/zanemcca/noMiddleware)

It appears when there is a 404 error on an endpoint that has the correct restApiRoot.

**Comment by satyadeepk** [comment]
This happens for me too even in production environment. `final` and `final:after` middlewares are run. 
Have you found any workarounds?

**Comment by superkhau** [comment]
@bajtos ^

**Comment by bajtos** [comment]
AFAIK, `loopback.rest` is handling any errors itself by sending back an error response and NOT calling `next()`. As a result, no middleware other middleware is called for routes handled by `loopback.rest` (anything under `/api`).

The behaviour described in the repro repo is therefore expected:

> ```
GET /api/nonexistent - Will not call middleware
GET /another/nonexistent - Will call the middleware properly
```

You have two options how to disable this behaviour:

If you are interested in 404 errors only, then you can set `remoting.handleUnknownPaths` to `false` in your `server/config.json` file:

```json
{
  "remoting": {
    "handleUnknownPaths": false
  }
}
```

If you would like to customize all error responses, then you need to customize the error handler as described in [docs](https://docs.strongloop.com/display/LB/Environment-specific+configuration#Environment-specificconfiguration-CustomizingRESTerrorhandling).

**Comment by johannesjo** [comment]
This is still an issue for me with loopback 2.3.4 when configuring staticc files. The middleware.env.js is not being loaded at all.

**Comment by bajtos** [comment]
@johannesjo please open a new issue and provide us with a small application reproducing the problem - see https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
