### ISSUE TITLE
Model is saved despite of validation errors

### ISSUE THREAD

**Issue by smehrbrodt** [strongloop/loopback#1458]
The [docs](http://docs.strongloop.com/display/public/LB/Validating+model+data) say:

> To add validation to model for creation or saving you do not need to call isValid() in the MyModel.js file. You can add validation by simply adding the validator calls:

This works when creating a new data, but when updating an existing data set, I get the following message (the model is still being saved):

> Ignoring validation errors in updateOrCreate():
  The `Person` instance is not valid. Details: `firstName` can't be blank (value: undefined); `lastName` can't be blank (value: undefined); `gender` is not included in the list (value: "bla").

According to the docs, the model should not have been saved.

**Comment by smehrbrodt** [comment]
I found out that you need to add `"validateUpsert": true` in the model.json file. Maybe this could be clarified in the docs?

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Added a note to http://docs.strongloop.com/display/LB/Validating+model+data#Validatingmodeldata-Usingvalidationmethods.  Ritchie also opened a related issue ^.
