### ISSUE TITLE
remote method input is not cast to GeoPoint

### ISSUE THREAD

**Issue by bitmage** [strongloop/loopback#1459]
I have a remote method that accepts a GeoPoint.  I can successfully send the value:

```javascript
[5, 4]
```

But the value arriving in my method is an array, not a GeoPoint.  Assuming successful validation, I would expect the input to my method to always be cast to a GeoPoint.

**Comment by jorrit** [comment]
I think the code that handles mapping the input/output data of remote methods is in the strong-remoting project. It doesn't seem to have any support for custom models.

**Comment by loay** [comment]
Hi @bitmage 
are you still experiencing the same issue?
Thanks

**Comment by bitmage** [comment]
I'm not working on the project where I encountered this any more.  Sorry.

**Comment by loay** [comment]
Thanks for your reply. I will close for now. If the same issue is encountered, please leave a comment so I can re-open. Thanks
