### ISSUE TITLE
Question:Use Observe to Warp Existed Function to change argument and result and error

### ISSUE THREAD

**Issue by violet-day** [strongloop/loopback#1461]
I have exist function based with promise.
For example:

```js
//UserService is an existed class
var UserService = {};
UserService.getById = function () {
  var random = Math.random();
  if (random > 0.5) {
    return Promise.resolve(true);
  } else {
    return Promise.reject(new Error('value is less than 0.5'))
  }
};

UserService.getById()
  .then(function (result) {
    //result to be true
    console.log(result);
  })
  .catch(function (err) {
    //error message to be `value is less than 0.5`
    console.log(err);
  });
```

I want to add method `getById` and *other function* to `User` model.
The easiest way it `User.getById=UserService.getById`;
But I prefer to use `observe` and `notifyObserversOf` to add some hook to change the `arguments` and `function execute result` and even occur error to add my http `statusCode`.
Can anyone give me an sample code?
tks

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
