### ISSUE TITLE
Not able to get buffer data in remote method while uploading file of conent-type multipart-form data

### ISSUE THREAD

**Issue by tusharjain352** [strongloop/loopback#1462]
In my model's code I am trying to implement a remote method:

```
UploadProfilePic.remoteMethod('uploadPic', {
    accepts: {
        arg: 'input',
        type: 'Buffer', // I have also use Object and array as well
        http:function(ctx) {
           var req = ctx.req;
          console.log("Request object",req);//show whole request
          console.log("Request object",req.buffer);// show undefined
        }
    },
    returns: {
        arg: 'Image uploaded',
        type: 'string'
    }
});
```

I created the above remote method & using rest client to upload file using multipart form data by post request & in remote method,i am getting req object &content-type: "multipart/form-data" ,but not able to get buffer data in req object.How can i get that image file data in my remote method???

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
