### ISSUE TITLE
Role and RoleMapping diificulties

### ISSUE THREAD

**Issue by josepe36** [strongloop/loopback#1466]
Hello

I m new in loopback development and there are two weeks ago i ve started learning about it.
So i ve difficulties with the Role/RoleMapping mechanism.

This i would like to do is the following:
- models:
   myuser inherit of User
   myrole inherit of Role
   myrole will have a property of object type

And finally have the capacity to do an "include": "roles" in myuser.find
I was inspired by this exemple https://github.com/beeman/loopback-angular-playground which work fine and does the job, but this dont work if i replace in myuser the relation Role by myrole.
Is there a way to keep the Role mechanism with my custom property ?

Also in the exemple above, if we change the data source in model-config.json Role for mongodb the roles are not recorded.

Please sorry for my poor english.

Best regards

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
