### ISSUE TITLE
Question: What is the programatic equivalent to checking ACL access for a given model method? e.g. Model.findById()

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback#1468]
This is not an issue but I'm not sure if there's a forum or group where to ask. My question is straightforward:

I'm handling a custom route to update multiple models. but by programmatically calling methods on various models, I'm automatically skipping the ACL security rules. How do I replicate the ACL security checks for any method, say find(), findById(), update()...etc. Also is it the same for related models, say __updateById__modelNamePlural?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by simoami** [comment]
Thanks Simon!

**Comment by superkhau** [comment]
No problem, not sure how to answer your question, but you could probably use the ACL methods directly. See http://docs.strongloop.com/display/LB/ACL

**Comment by simoami** [comment]
Cool, I'll experiment with those!
