### ISSUE TITLE
Docs: "or" example

### ISSUE THREAD

**Issue by rus0000** [strongloop/loopback#1472]
http://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-and/or
This is, actually, not supported:
```
{
  "or": {
    "and": [ {"field1": "foo"}, {"field2": "bar"}  ],
    "field1": "morefoo"
   }
}
```
`or` has to be an array:
https://github.com/strongloop/loopback-datasource-juggler/blob/019705d32f9f6cff2ccca856214ad20854f46af9/lib/dao.js#L1047

It looks like documentation for Loopback is allways coming late. There are numerous talks in issues between team members: `... We need to update docs ...`, but during months nothing changes. Is there any way to contribute in docs? Why to use Atlassian for docs and not github for an open source project?

**Comment by rus0000** [comment]
Found http://docs.strongloop.com/display/public/LB/Contributing+to+LoopBack+documentation

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Thanks for fixing @rus0000 .  I approved your edit a few days ago -- normally I would get an email to alert me of the change, but there was a problem with the email server that Confluence uses.  This is fixed, so I'll be able to approve future edits more quickly.
