### ISSUE TITLE
Bug mongodb connector

### ISSUE THREAD

**Issue by josepe36** [strongloop/loopback#1473]
Hello

I ve a project with user model which has many role, all works fine if i use memory db but relation is lost then i use mongodb.

So i decided to write my own crud method for user model, because an user should not be created without role and it s not a good idea to call the role api for assign my new user.

I ve trie to write my method, i thought than this would be simple, but nodejs remembered me than js is asynchonous !!!

So what to do now ?
Is there a way to call models method synchrnonously or should i hack my code whith magic libs like async ?

What are the arguments for developping web apps on nodejs and not in procedural langages ?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
