### ISSUE TITLE
slc loopback produces unformatted json files

### ISSUE THREAD

**Issue by rmayhue** [strongloop/loopback#1474]
I just updated strongloop to v4.0.5 and now all JSON files produced are un-formatted. Everything is now all on a single line (e.g.):

```javascript
{"_meta":{"sources":["loopback/common/models","loopback/server/models"," ... }
```

Even if you manually format a file, adding models, relations etc., via slc will place everything back on a single line.

**Comment by ghislainf** [comment]
+1. Same problem

**Comment by OOPMan** [comment]
Argh, me too! This is very annoying!

**Comment by ivishwas-s** [comment]
+1 Very annoying indeed!!

**Comment by spacemonkey** [comment]
+1

Going back to 4.0.4 until this is fixed, just not possible to make a useful screencast! :-(

**Comment by spacemonkey** [comment]
Ok looks like it was something else, as going back to 4.0.4 also produces the pre-minified JSON.

Anybody got a quick fix for now?

**Comment by raymondfeng** [comment]
Duplicate of https://github.com/strongloop/strongloop/issues/238
