### ISSUE TITLE
Can't set model 'id' "before save"

### ISSUE THREAD

**Issue by davibe** [strongloop/loopback#1476]
I registered an observe on "before save" that does

    ctx.instance.id = ctx.instance.id || ctx.instance.ref

This is because i want to be backward compatible with a client based on an older implementation of the backend. This works as expected for creating object but it fails for updates (put). It looks like lookback decides wether the operation is a creation of a new object or an update BEFORE the "before save" call where i inject the 'id' attribute. Therefore it then tries to create a new object with an already existing id while its supposed to update.

How can i work-around this ?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by davibe** [comment]
I think this is a bug.
