### ISSUE TITLE
Find Request Error - filter and included model

### ISSUE THREAD

**Issue by kiritoc** [strongloop/loopback#1478]
I'm using a "loopback-connector-rest" connector (& my loopback API is using MongoDB).

I have 2 classes
- ClassA hasAndBelongsToMany ClassB
- ClassB properties : {author: {uid: 'string', ...}, ...}

When I use the request below, I get the error: 
_MongoError_
_statusCode 500_
_Can't canonicalize query: BadValue $nin needs an array_

```
ClassA.find({
    'filter': {
        'include': {
            'relation': 'classB',
            'scope': {
                'where': {
                    'author.uid': {
                        'nin': ['test1', 'test2']
                    }
                }
            }
        }
    }
}, cb);
```

From the mongo log, I found the error occurs at:
_$query: { author.uid: { $nin: { [0]: "test1", [1]: "test2" } }_

The array should not be parsed ?!

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by vespertilian** [comment]
@superkhau 

I believe issues I am having are the same 

Sample app with tests for Postgres and the in memory connector assume it's the same for mongodb:

https://github.com/vespertilian/loopback_filter_test
Should be able to just update the connector in datasources (With your own DB values) and run NPM test to see the bug.

  1) People route should allow you to count people with a "where" using an "and" via group relation:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at net.js:1409:10

  2) People route should allow you to request people in an ascending age via the group relation:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at net.js:1409:10

  3) People route should allow you to request people in an descending age via the group relation:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at net.js:1409:10

  4) People route should allow you to request people in an ascending age via the group relation with a limit:
     Error: expected 200 "OK", got 500 "Internal Server Error"
      at net.js:1409:10

  5) People route should allow you to request people in an descending age via the group relation wiht a limit:
     Error: expected 200 "OK", got 500 "Internal Server Error"

Originally reported this issue as a bug with count on the google group. 

https://groups.google.com/forum/#!searchin/loopbackjs/vespertilian/loopbackjs/jqmtqaB8k-M/DL9IHx63recJ
