### ISSUE TITLE
Model.destroyAll() error: "unknown operator: $permitId".

### ISSUE THREAD

**Issue by TonyLuo** [strongloop/loopback#1479]
I try to use destroyAll in my application, got an error message:"unknown operator: $permitId".
It looks like the db connector insert "$" into where condition .
Could someone tell me what is going on here? thanks

Usage:

OrgService.app.models.Dept_Permit.destroyAll( {where: {"permitId": id}},
          function (err, data) {
            if (err) {

              logger.error(err);
              return cb(err);

            } else {

              cb(err, data);

            }

          });

Error message:
{
  "error": {
    "name": "MongoError",
    "status": 500,
    "message": "unknown operator: $permitId",
    "index": 0,
    "code": 2,
    "errmsg": "unknown operator: $permitId",
    "stack": "MongoError: unknown operator: $permitId\n    at toError (/Users/Tony/dev/loopback-angular-admin/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:113:11)\n    at /Users/Tony/dev/loopback-angular-admin/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/collection.js:761:67\n    at /Users/Tony/dev/loopback-angular-admin/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:795:13\n    at /Users/Tony/dev/loopback-angular-admin/node_modules/loopback/node_modules

Debug log:
loopback:connector:mongodb destroyAll +2ms Dept_Permit { where: { permitId: 'permitA' } }
  loopback:connector:mongodb MongoDB: model=Dept_Permit command=remove +0ms [ { where: { '$permitId': 'permitA' } }, [Function] ]
  loopback:connector:mongodb Error:  +1ms { [MongoError: unknown operator: $permitId]
  name: 'MongoError',
  message: 'unknown operator: $permitId',
  index: 0,
  code: 2,
  errmsg: 'unknown operator: $permitId' }

**Comment by raymondfeng** [comment]
Please note that destroyAll takes `where` instead of `filter`. Call `destroyAll( {"permitId": id}, ... )` instead.
