### ISSUE TITLE
Ability to define a bulk ALLOW once a wildcard DENY is in place.

### ISSUE THREAD

**Issue by arlaneenalra** [strongloop/loopback#148]
The way permissions are presently defined, a wildcard ```DENY``` trumps any acl does not exactly match on ```model```, ```property```, and ```accessType```.  While this is the technically correct solution, it would be nice to be able to setup a wildcard ```DENY``` for ```$everyone``` and then do a wildcard ```ALLOW``` for other roles.

I know this presents a problem with deciding which acl should have priority as there is currently nothing to assign a weight to roles or the acls themselves.  Adding that should make this pretty simple to do.

**Comment by bajtos** [comment]
As part of our issue triage process, I am closing items that have been inactive for an extended period of time. If anybody thinks the feature proposed here is still relevant and should be prioritised, then please leave a comment to let us know.
