### ISSUE TITLE
Authentication failed for User model extension for mysql DB

### ISSUE THREAD

**Issue by adnanshatil** [strongloop/loopback#1480]
I don't know whether anyone had the same problem. I have extended one model (People) from User and create some identical (same as common/models/user.json) table structure in mysql DB. Then I have used loopback POST method for creating People. It worked nicely and storing to database. Then I came across the real problem. When I have used People.login() method for login then it can't able to authenticate. I went deep inside user.js and found the problem is in User.prototype.hasPassword function. Precisely in bcrypt.compare(plain, this.password, function(err, isMatch). It is always returning false. 

But if I use the User (built-in) normally with memory db then it is working. But not with my People model. I really don't know what is the problem. Is there anyone who can guide me? Thanks in advance.

**Comment by raymondfeng** [comment]
Can you provide an isolated test?

**Comment by adnanshatil** [comment]
Okay ... here is my test result. This might be a long one but I am giving every steps I followed- 

STEP 1- Creating project user-test
$ slc loopback

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |  Let's create a LoopBack |
   `---------´   |       application!       |
    ( _´U`_ )    '--------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What's the name of your application? user-test
? Enter name of the directory to contain the project: user-test
   create user-test/
     info change the working directory to user-test

Generating .yo-rc.json


I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.


   create .editorconfig
   create .jshintignore
   create .jshintrc
   create README.md
   create server/boot/authentication.js
   create server/boot/explorer.js
   create server/boot/rest-api.js
   create server/boot/root.js
   create server/middleware.json
   create server/server.js
   create .gitignore
   create client/README.md
npm WARN package.json user-test@1.0.0 No license field.
npm WARN prefer global jshint@2.8.0 should be installed with -g
cors@2.7.1 node_modules/cors
└── vary@1.0.0

serve-favicon@2.3.0 node_modules/serve-favicon
├── ms@0.7.1
├── parseurl@1.3.0
├── fresh@0.3.0
└── etag@1.7.0

compression@1.5.0 node_modules/compression
├── bytes@2.1.0
├── vary@1.0.0
├── on-headers@1.0.0
├── debug@2.2.0 (ms@0.7.1)
├── compressible@2.0.3 (mime-db@1.13.0)
└── accepts@1.2.9 (negotiator@0.5.3, mime-types@2.1.1)

errorhandler@1.4.0 node_modules/errorhandler
├── escape-html@1.0.2
└── accepts@1.2.9 (negotiator@0.5.3, mime-types@2.1.1)

loopback-datasource-juggler@2.30.1 node_modules/loopback-datasource-juggler
├── depd@1.0.1
├── inflection@1.7.1
├── node-uuid@1.4.3
├── qs@3.1.0
├── async@1.0.0
├── debug@2.2.0 (ms@0.7.1)
├── traverse@0.6.6
└── loopback-connector@2.2.2

loopback-boot@2.8.2 node_modules/loopback-boot
├── commondir@0.0.1
├── toposort@0.2.10
├── async@0.9.2
├── debug@2.2.0 (ms@0.7.1)
├── semver@4.3.6
└── lodash@3.9.3

jshint@2.8.0 node_modules/jshint
├── strip-json-comments@1.0.2
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shelljs@0.3.0
├── minimatch@2.0.8 (brace-expansion@1.1.0)
├── cli@0.6.6 (glob@3.2.11)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
└── lodash@3.7.0

loopback@2.18.0 node_modules/loopback
├── sl-blip@1.0.0
├── uid2@0.0.3
├── nodemailer-stub-transport@0.1.5
├── stable@0.1.5
├── canonical-json@0.0.4
├── depd@1.0.1
├── inflection@1.7.1
├── async@0.9.2
├── loopback-phase@1.2.0
├── debug@2.2.0 (ms@0.7.1)
├── loopback-connector-remote@1.0.3
├── bcryptjs@2.1.0
├── ejs@2.3.1
├── underscore.string@3.1.1
├── body-parser@1.13.1 (bytes@2.1.0, content-type@1.0.1, on-finished@2.3.0, http-errors@1.3.1, raw-body@2.1.1, qs@2.4.2, type-is@1.6.3, iconv-lite@0.4.10)
├── continuation-local-storage@3.1.4 (emitter-listener@1.0.1, async-listener@0.5.5)
├── express@4.13.0 (escape-html@1.0.2, merge-descriptors@1.0.0, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, array-flatten@1.1.0, etag@1.7.0, content-type@1.0.1, vary@1.0.0, parseurl@1.3.0, path-to-regexp@0.1.6, content-disposition@0.5.0, serve-static@1.10.0, finalhandler@0.4.0, qs@2.4.2, on-finished@2.3.0, proxy-addr@1.0.8, send@0.13.0, type-is@1.6.3, accepts@1.2.9)
├── nodemailer@1.3.4 (nodemailer-smtp-transport@1.0.3, nodemailer-direct-transport@1.0.2, buildmail@1.2.4, hyperquest@1.2.0, libmime@1.0.0)
└── strong-remoting@2.19.0 (eventemitter2@0.4.14, qs@2.4.2, js2xmlparser@0.1.9, traverse@0.6.6, request@2.58.0, jayson@1.2.0, xml2js@0.4.9)

loopback-explorer@1.7.2 node_modules/loopback-explorer
├── debug@1.0.4 (ms@0.6.2)
├── lodash@2.4.2
├── express@3.21.0 (cookie-signature@1.0.6, merge-descriptors@1.0.0, escape-html@1.0.2, utils-merge@1.0.0, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, etag@1.7.0, content-type@1.0.1, vary@1.0.0, cookie@0.1.3, parseurl@1.3.0, basic-auth@1.0.2, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.2.0, proxy-addr@1.0.8, mkdirp@0.5.1, send@0.13.0, connect@2.30.0)
└── swagger-ui@2.0.24 (coffee-script@1.6.3, swagger-client@2.0.36, handlebars@1.0.12, less@1.4.2)


Next steps:

  Change directory to your app
    $ cd user-test

  Create a model in your app
    $ slc loopback:model

  Optional: Enable StrongOps monitoring
    $ slc strongops

  Run the app
    $ slc run .

STEP 2- Running the project user-test

$ slc run .
INFO strong-agent v1.5.1 profiling app 'user-test' pid '9017'
INFO strong-agent[9017] started profiling agent
INFO supervisor reporting metrics to `internal:`
supervisor running without clustering (unsupervised)
INFO strong-agent not profiling, agent metrics requires a valid license.
Please contact sales@strongloop.com for assistance.
Browse your REST API at http://0.0.0.0:3000/explorer
Web server listening at: http://0.0.0.0:3000/

STEP 3- Creating an User (User is in memory db)
![loopback1](https://cloud.githubusercontent.com/assets/1823009/8343334/eb1622d0-1adc-11e5-9ded-20fc787d6b8e.png)

STEP 4- Login with User (User is in memory db)
![loopback2](https://cloud.githubusercontent.com/assets/1823009/8343353/0786366c-1add-11e5-912b-c336291a09dd.png)

STEP 5- Creating People model from User
$ slc loopback:model 
? Enter the model name: People
? Select the data-source to attach People to: db (memory)
? Select model's base class: User
? Expose People via the REST API? Yes
? Custom plural form (used to build REST URL): 
Let's add some People properties now.

Enter an empty property name when done.
? Property name: 

STEP 6- Running the project user-test again
$ slc run .
INFO strong-agent v1.5.1 profiling app 'user-test' pid '9017'
INFO strong-agent[9017] started profiling agent
INFO supervisor reporting metrics to `internal:`
supervisor running without clustering (unsupervised)
INFO strong-agent not profiling, agent metrics requires a valid license.
Please contact sales@strongloop.com for assistance.
Browse your REST API at http://0.0.0.0:3000/explorer
Web server listening at: http://0.0.0.0:3000/

STEP 7- Creating a People (People is in memory db)
![loopback3](https://cloud.githubusercontent.com/assets/1823009/8343397/7e22bfa2-1add-11e5-9e14-6d492c647d87.png)

STEP 8- Login with People (People is in memory db)
![loopback4](https://cloud.githubusercontent.com/assets/1823009/8343401/85accfc4-1add-11e5-8cd5-5a651c606f4c.png)

STEP 9- Installing mysql in user-test project
$ npm install --save loopback-connector-mysql
npm WARN package.json user-test@1.0.0 No license field.
loopback-connector-mysql@2.1.1 node_modules/loopback-connector-mysql
├── sl-blip@1.0.0
├── async@0.9.2
├── debug@2.2.0 (ms@0.7.1)
├── loopback-connector@2.2.2 (async@1.2.1)
└── mysql@2.7.0 (require-all@1.0.0, bignumber.js@2.0.7, readable-stream@1.1.13)

$ slc loopback:datasource
? Enter the data-source name: mysqlconn
? Select the connector for mysqlconn: MySQL (supported by StrongLoop)

STEP 10- Table created in mysql DB according to User model specification
User Model:
{
  "id": 0,
  "username": "",
  "password": "",
  "email": "",
  "emailVerified": false,
  "created": "",
  "realm": "",
  "lastUpdated": "",
  "status": "",
  "verificationToken": "",
  "credentials": "object",
  "challenges": "object"
}

mysql> desc People;
+-------------------+-------------+------+-----+-------------------+----------------+
| Field             | Type        | Null | Key | Default           | Extra          |
+-------------------+-------------+------+-----+-------------------+----------------+
| id                | int(11)     | NO   | PRI | NULL              | auto_increment |
| username          | varchar(45) | NO   | MUL | NULL              |                |
| password          | varchar(45) | NO   |     | NULL              |                |
| email             | varchar(45) | NO   | MUL | NULL              |                |
| emailVerified     | tinyint(1)  | YES  |     | NULL              |                |
| created           | timestamp   | NO   |     | CURRENT_TIMESTAMP |                |
| realm             | varchar(45) | YES  |     | NULL              |                |
| lastUpdated       | timestamp   | YES  |     | NULL              |                |
| status            | varchar(45) | YES  |     | NULL              |                |
| verificationToken | varchar(45) | YES  |     | NULL              |                |
| credentials       | text        | YES  |     | NULL              |                |
| challenges        | text        | YES  |     | NULL              |                |
+-------------------+-------------+------+-----+-------------------+----------------+
12 rows in set (0.00 sec)

STEP 11- Updating datasources.json
$ more datasources.json 
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "mysqlconn": {
    "name": "mysqlconn",
    "connector": "mysql",
    "host": "localhost",
    "port": 3306,
    "database": "appDB",
    "username": "root",
    "password": "root",
    "name": "appDB"
  }
}

STEP 12- Updating model-config.json
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "User": {
    "dataSource": "db"
  },
  "AccessToken": {
    "dataSource": "db",
    "public": false
  },
  "ACL": {
    "dataSource": "db",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "db",
    "public": false
  },
  "Role": {
    "dataSource": "db",
    "public": false
  },
  "People": {
    "dataSource": "mysqlconn",
    "public": true
  }
}

STEP 13- update in core user.js file for output hash

$ cd user-test/node_modules/loopback/common/models/user.js

  User.prototype.hasPassword = function(plain, fn) {
    if (this.password && plain) {
      var testPass = this.constructor.hashPassword(plain);
      console.log(testPass);

      bcrypt.compare(plain, this.password, function(err, isMatch) {
        if (err) return fn(err);
        fn(null, isMatch);
      });
    } else {
      fn(null, false);
    }
  };

STEP 14- Staring project user-test and and weird Error message appeared in the log
$ slc run .
INFO strong-agent v1.5.1 profiling app 'user-test' pid '9387'
INFO strong-agent[9387] started profiling agent
INFO supervisor reporting metrics to `internal:`
supervisor running without clustering (unsupervised)
ERROR strong-agent error: failed to instrument mysql
INFO strong-agent not profiling, agent metrics requires a valid license.
Please contact sales@strongloop.com for assistance.
Browse your REST API at http://0.0.0.0:3000/explorer
Web server listening at: http://0.0.0.0:3000/

STEP 15- Creating People 
![loopback5](https://cloud.githubusercontent.com/assets/1823009/8343486/6a57cba6-1ade-11e5-817d-1c3a1711b74b.png)

STEP 16- MySQL output
mysql> select * from People;
+----+----------+-----------------------------------------------+------------------------+---------------+---------------------+-------+-------------+--------+-------------------+-------------+------------+
| id | username | password                                      | email                  | emailVerified | created             | realm | lastUpdated | status | verificationToken | credentials | challenges |
+----+----------+-----------------------------------------------+------------------------+---------------+---------------------+-------+-------------+--------+-------------------+-------------+------------+
|  1 | tmpuser  | $2a$10$83cQCRhIxmFgvxaZ6iP1kOYNcQEz1Hhs8MRL4E | tmpuser@strongloop.com |          NULL | 2015-06-25 01:23:53 | NULL  | NULL        | NULL   | NULL              | NULL        | NULL       |
+----+----------+-----------------------------------------------+------------------------+---------------+---------------------+-------+-------------+--------+-------------------+-------------+------------+
1 row in set (0.00 sec)

STEP 17- But login failed
![loopback6](https://cloud.githubusercontent.com/assets/1823009/8343496/8b423e14-1ade-11e5-8071-570016128aca.png)

STEP 18- Hash password output
$2a$10$51txHESsDFZzZk2EjqtuyuosIrvkZoTKiSk7Ulvkk6A3vK7o/IkEq

STEP 18- Modification in datasources.json to output memory db
$ more datasources.json 
{
  "db": {
    "name": "db",
    "connector": "memory",
    "file": "json.db"
  },
  "mysqlconn": {
    "name": "mysqlconn",
    "connector": "mysql",
    "host": "localhost",
    "port": 3306,
    "database": "appDB",
    "username": "root",
    "password": "root",
    "name": "appDB"
  }
}

STEP 19- Creating User again (not People)
![loopback7](https://cloud.githubusercontent.com/assets/1823009/8343516/cae4dac2-1ade-11e5-8230-b0841a6bf761.png)

STEP 20- json.db output 
$ more json.db 
{
  "ids": {
    "User": 2,
    "AccessToken": 1,
    "ACL": 1,
    "RoleMapping": 1,
    "Role": 1
  },
  "models": {
    "User": {
      "1": "{\"username\":\"user1\",\"password\":\"$2a$10$zNErtvnCIqHSbR5MyR2EGe/pld
zq8V75vmlvn3.r05iVkZVkXljkO\",\"email\":\"user1@loopback.com\",\"id\":1}"
    },
    "AccessToken": {},
    "ACL": {},
    "RoleMapping": {},
    "Role": {}
  }
}

STEP 21- Login with User (not People)
![loopback8](https://cloud.githubusercontent.com/assets/1823009/8343524/e7d9f6b2-1ade-11e5-99c1-66cf87ec8c29.png)

STEP 20- Hash password output while login
$2a$10$UbAWSWXjpNZLem7xA2n8MeShwAsORnBj/LvKmiEz51xyKOOPFlSH.

**Comment by raymondfeng** [comment]
The column length is probably too short for ( password | varchar(45)). Can you increase the length?

**Comment by adnanshatil** [comment]
Oooo yes ... this is awesome ... After altering the table it is working. 

But can you tell me what is the ERROR after installing mySQL to the project .... 

$ slc run .
INFO strong-agent v1.5.1 profiling app 'user-test' pid '9387'
INFO strong-agent[9387] started profiling agent
INFO supervisor reporting metrics to internal:
supervisor running without clustering (unsupervised)
__ERROR strong-agent error: failed to instrument mysql__
INFO strong-agent not profiling, agent metrics requires a valid license.
Please contact sales@strongloop.com for assistance.
Browse your REST API at http://0.0.0.0:3000/explorer
Web server listening at: http://0.0.0.0:3000/

**Comment by raymondfeng** [comment]
That's just a warning that `strong-agent` requires a valid license to report [monitoring to StrongLoop Arc](https://strongloop.com/node-js/performance-monitoring/). If you don't need monitoring, you can ignore it or run with `node .`.
