### ISSUE TITLE
Creating / Updating Related Model through "parent" Model

### ISSUE THREAD

**Issue by dcarter5804** [strongloop/loopback#1481]
Lets say you have a "User" model and an "Address" model with the following relationship:  The "Address" model has foreignKey of userId.

```
"relations" : {
  "address" : {
    "type" : "hasMany",
    "model" : "Address",
    "foreignKey" : "userId"
  }
}
```

Is it possible to create a new address through the basic "user" endpoint as follows:

POST /api/user/1
Post Body:
```
{
  "address" : [
    {
      "street1" : "street1",
      "street2" : "street2",
      "city" : "city",
      "state" : "state",
      "zip" : "zip",
    }
 ]
}
```

If not, is this something the team is planning on implementing?  This would be a great feature that would allow developers to create and maintain atomic data models in an AngularJS application and perform a one step, all inclusive create / update of that model and its related models without having to write any custom code, or make multiple calls.  Please note that this is a generic question, and is not necessarily coupled to the built-in user model.

**Comment by Neil-UWA** [comment]
you will be able to create an address by calling POST /api/users/{id}/address, you can view all routes using loopback-explorer. localhost:3000/explorer

**Comment by dcarter5804** [comment]
I already gave my opinion this support through a feedback requets, but this
does not address my question, as your "support" never does.  This is
pathetic.

**Comment by superkhau** [comment]
@dcarter5804 See http://docs.strongloop.com/display/LB/Embedded+models+and+relations. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by Malkiat-Singh** [comment]
@dcarter5804 You can use remote hook after create for this 
Model.afterRemote('create',function(ctx,modellnstance,next){
modelInstance.address.create(ctx.reg.body.address,function(err,result){
if(err){
modelInstance,destroy();
next(err);
}
next();
});
});
