### ISSUE TITLE
No Instance Object in Context of Operation Hooks

### ISSUE THREAD

**Issue by ivishwas-s** [strongloop/loopback#1486]
There seems to be no instance object inside context of an operation hook (i tried with before save) and instead, there is a "data" object which seems to be the instance.

As per the docs, there is an instance object and not a data object.
```
MyModel.observe('before save', function updateTimestamp(ctx, next) {
  if (ctx.instance) {
    ctx.instance.updated = new Date();
  } else {
    ctx.data.updated = new Date();
  }
next(); });
```
Please update the docs.

**Comment by superkhau** [comment]
@crandmck

**Comment by crandmck** [comment]
For both [before save](http://docs.strongloop.com/display/LB/Operation+hooks#Operationhooks-beforesave) and [after save](http://docs.strongloop.com/display/LB/Operation+hooks#Operationhooks-aftersave), docs say: 
> Depending on which method triggered this hook, the context will have one of the following sets of properties:
- Single model:
 - `Model` - the constructor of the model that will be saved.
 - `instance` - the model instance that was saved. The value is an instance of Model class and contains updated values computed by datastore (for example, auto-generated ID).
- Partial update of one or more models:
  - `Model` - the constructor of the model that will be saved.
  - `where` - the where filter describing which instances were queried.  See caveat below.
  - `data` - the (partial) data applied during the update.

@ivishwas-s  When you noticed the lack of `instance` object, were you doing update of a single or multiple models?

**Comment by ivishwas-s** [comment]
@crandmck I was doing an update on a single model.

**Comment by crandmck** [comment]
@bajtos - Is this a bug or are the docs wrong?

**Comment by bajtos** [comment]
@ivishwas-s could you please be more specific, what kind of an update did you perform? If it was `updateAttributes` (`POST /api/my-model/my-id`), then such operation is a partial update and `ctx.data` is expected.

@crandmck I need more info, I think this may be a misunderstanding at @ivishwas-s' side.

**Comment by crandmck** [comment]
@ivishwas-s Can you respond to the question above?  Without more info, we can't address this...

**Comment by ivishwas-s** [comment]
You are right, for a partial update, the context just holds a data object. And that's mentioned in the latest documentation, my bad!! Everything is fine, thanks.

-
Vishwas

**Comment by crandmck** [comment]
Thanks for the follow-up!

**Comment by lazzyms** [comment]
Hey @bajtos, I'm using express-session with loopback and I want to access the session inside the operation hook. How can I do that?
