### ISSUE TITLE
License error

### ISSUE THREAD

**Issue by Sogl** [strongloop/loopback#1487]
Today I updated loopback globally and saw this in ARC:
![screenshot_5](https://cloud.githubusercontent.com/assets/7556290/8371397/661b9ac6-1c1a-11e5-867b-5685cfbcc630.jpg)
This error has not been in the previous version.

What I did (OS Windows):
1. `npm update -g`
https://docs.npmjs.com/getting-started/updating-global-packages
2. `npm install -g strongloop`
http://loopback.io/getting-started/
3. `slc loopback` ang gave project name
4. `node .` in one console window, `slc arc` in another
5. After clicking on Composer page I see this error

I did't enter into my Strongloop account in ARC.
What's wrong?

p.s. Also 'Staus' must be 'Status'.

**Comment by superkhau** [comment]
@seanbrookes ^
@Sogl I think this should be posted on the Arc issues instead of Loopback: https://github.com/strongloop/strong-arc/issues
