### ISSUE TITLE
work with other application and customer relation fetch data?

### ISSUE THREAD

**Issue by violet-day** [strongloop/loopback#1491]
I will use LB to work with other system.
The `User` model is stored in `HR System`.I can fetch data with http api.
As example,I create `Post` and `HRUser` model.And define relation `BelongsTo` with `HRUser`.
I try to overwrite `HRUser.findById`.But it don't work.
Why i use relation is we can use `include` query.I think is beautiful~
Can anyone give me a suggestion or tell me how to work with models has been stored in other system?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
