### ISSUE TITLE
Model Validation on inheritance

### ISSUE THREAD

**Issue by Kr0san89** [strongloop/loopback#1500]
Hello,

i'm wondering why the validation is not working on inheritance of Models

I have two models one inheritance from the other. The Overall inheritance is fine, but the validation rules are not working on the inheritanced Model. Can you implement this? Would spare a lot of Code duplication.

thanks

**Comment by Nutelac** [comment]
Duplicate of https://github.com/strongloop/loopback/issues/1485.
