### ISSUE TITLE
validateUpsert should be true by default

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1506]
I think we should default `validateUpsert` to `true` at the application level.

I'm not sure when you would want `validateUpsert` to be false... but IMO its an exception or edge case. Right now I think you can only control this at the model level...

@raymondfeng @bajtos

**Comment by crandmck** [comment]
See related doc issue #1458

**Comment by bajtos** [comment]
I have added the flag to preserve backwards compatibility, I am more than happy to get rid of it in LoopBack 3.0. BTW new models scaffolded by `slc loopback` have this flag turned on - see https://github.com/strongloop/loopback-workspace/pull/194

**Comment by bajtos** [comment]
> I am more than happy to get rid of it in LoopBack 3.0.

This change did not make it into 3.0 release. See https://github.com/strongloop/loopback/issues/2418
