### ISSUE TITLE
Issue with helper function undefined

### ISSUE THREAD

**Issue by shankarregmi** [strongloop/loopback#1509]
I have problem accessing helper method :
If I have two models A and B
A has relations as : 
`"relationName": {
      "type": "hasMany",
      "model": "B",
      "foreignKey": "keyThrough"
    }`
I cannot add instance B to A as 
`A.relationName.create(doc, function(){
   })`
http://stackoverflow.com/questions/31297947/strongloop-add-related-model-instance-to-a-database#

**Comment by raymondfeng** [comment]
You need to have an instance of `A`, for example, `a`:

a.relationName.create(doc, function(){ })
