### ISSUE TITLE
explorer is displaying date fields as string 

### ISSUE THREAD

**Issue by ezraroi** [strongloop/loopback#1510]
When you define a property of type date and you use the explorer to explore it's schema, it will be displayed as string type and not date

**Comment by loay** [comment]
Hi @ezraroi 
It is displayed as for example: `"2016-12-25T00:00:00.000Z", `
is that what you are getting?

**Comment by ezraroi** [comment]
No, the type is specified as String

**Comment by loay** [comment]
Hi @ezraroi 
Sorry I can't reproduce that. Can you create a test project with steps to reproduce so I can debug?
Thanks.
