### ISSUE TITLE
autoupdate not update options of index in mongodb

### ISSUE THREAD

**Issue by nvcken** [strongloop/loopback#1511]
step 1 : code_idx have existed in mongodb from Model JSON defined by first time autoupdate()
```
// Model JSON defined
"code_idx": {
      "keys": {
        "code": 1
      }
    }
```
step 2 : Edit code_idx, add options key with unique and value is true
```
"code_idx": {
      "keys": {
        "code": 1
      },
      "options": {
        "unique": true
      }
    }
```
step 3 : run ds.autoupdate() without errors
step 4 : check in mongodb , code_idx still have no unique set true.

if I drop this index before call ds.autoupdate (step 3), then it works.

**Comment by fabien** [comment]
I seem to recall this issue as well.

**Comment by mrfelton** [comment]
I also have the same problem when trying to edit an existing index. It doesn't get updated by calling `autoupdate`.

**Comment by loay** [comment]
I thought that issue was fixed as per this case: https://github.com/strongloop/loopback/issues/1139

Is it still persisting?

**Comment by loay** [comment]
Closing issue for now. If it still persisting, please leave a comment and I will re-open the case. Thanks.

**Comment by akvaliya** [comment]
I have used below code
```
'use strict';
global.Promise = require('bluebird');

module.exports = function(server) {

    Promise.each(server.models(), function(model) {

        if (model.dataSource) {
            var autoupdate = Promise.promisify(model.dataSource.autoupdate);
            if (autoupdate) {
                return autoupdate.call(model.dataSource, model.modelName);
            }
        }
    });
};
```

When i modified existing index like 
From 
```
 "indexes": {
    "textSearch": {
      "name": "text"
    }
  }
```
to

```
"indexes": {
    "textSearch": {
      "$**": "text"
    }
  }
```
I got below error

**Unhandled rejection MongoError: Index with name: textSearch already exists with different options**

Does anyone have any idea how to resolve this?
