### ISSUE TITLE
common model method User.login always returns 401 (LOGIN_FAILED) and hides real error

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback#1512]
The logic in [user.js](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L224), assumes we developers are only interested in whether the user actually logged in or not. I have a case where the login call fails because the db connection is down. The error code is "ECONNREFUSED" but the login function simply ignores this error and return 401 "LOGIN_FAILED" instead. This has impact in the user experience as they keep trying other passwords thinking that they forgot their password. I'd would help to relay the real error instead of the default one of at least determine the real conditions for when you need to return the default error.

**Comment by jannyHou** [comment]
hey @simoami I am trying to reproduce your issue. I run a sample app on my local server and yes, when I stop my server and login, the error is 401. Thanks for your suggestion and we will look into it!

**Comment by bajtos** [comment]
I think we should return `500 Internal Error` when it was not possible to verify the supplied credentials because of a database connection error.

**Comment by superkhau** [comment]
>I think we should return 500 Internal Error when it was not possible to verify the supplied credentials because of a database connection error.

+1

**Comment by barocsi** [comment]
Any updates? Still swallowing the real errors for example next({error}) from an observe 'access' or 'loaded' funtion.

**Comment by bajtos** [comment]
@barocsi I am afraid this issue is not a priority for us right now. Would you like to contribute this change yourself? I am happy to help you along the way, just mention my handle in the pull request description. See this page to get you started: http://loopback.io/doc/en/contrib/code-contrib.html
