### ISSUE TITLE
model.update calls updateAll

### ISSUE THREAD

**Issue by seminice** [strongloop/loopback#1515]
Im having this issue where I have a hasMany and belongs to relationship , user has many posts and post belongs to user, here is my acl for the Post model

` "acls": [  `                                                                    
      {                                                                            
      `  "accessType": "*",     `                                                    
     `   "principalType": "ROLE",    `                                               
   `     "principalId": "$everyone", `                                               
    `    "permission": "DENY"       `                                                
      },                                                                           
      {                                                                            
       ` "accessType": "READ",         `                                             
      `  "principalType": "ROLE",            `                                       
    `    "principalId": "$everyone",       `                                         
     `   "permission": "ALLOW"           `                                           
      },                                                                           
      {                                                                            
       ` "accessType": "EXECUTE",       `                                            
       ` "principalType": "ROLE",       `                                            
      `  "principalId": "$authenticated",           `                                
      `  "permission": "ALLOW",     `                                                
      `  "property": "create"     `                                                  
      },                                                                           
      {                                                                            
      `  "accessType": "WRITE",  `                                                   
     `   "principalType": "ROLE",   `                                                
     `   "principalId": "$owner", `                                                                           
        `"permission": "ALLOW"           `                                           
      }                                                                            
],

I'm calling the Update method using angular
            `Post`
                `.update({`
                    `where: {`
                        `id: postId`
                    `}`
                `}, $scope.post)`
                `.$promise`
                `.then(function() {`
                    `// resolved`
                    `console.log('updated');`
                `}, function(err){`
                    `console.log(err);`
                `});`

The foregin key is the userId

Now I noticed using when debugging security that this is might be the problem 

`loopback:security:access-context ---AccessRequest--- +0ms`
`loopback:security:access-context  model Post +0ms`
`loopback:security:access-context  property updateAll +0ms`
`loopback:security:access-context  accessType WRITE +0ms`
`loopback:security:access-context  permission DENY +0ms`
`loopback:security:access-context  isWildcard() false +0ms`
`loopback:security:access-context  isAllowed() false +0ms `

Should I allow all $authenticated to access updateAll? or am I missing anything.

Thank you so much for your efforts.

**Comment by gunjpan** [comment]
@seminice : Please refer to: https://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-Update for manipulating Model data with Angular.
For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
