### ISSUE TITLE
default User model acl problem

### ISSUE THREAD

**Issue by starbassma** [strongloop/loopback#1518]
Hello,
When i create a User based model i can't access the findById method ,

the User model documentation page say :
     Default User ACLs.
           DENY EVERYONE *
          ALLOW EVERYONE create
          ALLOW OWNER deleteById
          ALLOW EVERYONE login
          ALLOW EVERYONE logout
          ALLOW EVERYONE findById  <-----------------------------------
         ALLOW OWNER updateAttributes

the probleme is with the method  findById because it require authorization and it's not accessible for EVERYONE.

**Comment by jannyHou** [comment]
hey @starbassma, I checked this [document page](https://docs.strongloop.com/display/public/LB/User+REST+API)(is it the user model doc page you mentioned?), but I didn't see the table you copied here.
And there is no such table [here](https://docs.strongloop.com/display/public/LB/Controlling+data+access).

But thank you @starbassma I think it's right to document those ACL rules clearly somewhere. 
Hi @crandmck do you have any idea where is the document page mentioned in this issue? If there is no such page, should I add the User Model ACL Rules in doc? Thanks!

**Comment by richardpringle** [comment]
Hey @starbassma, I don't believe you should be allowed default access to `findById()` (so it looks like a doc issue). One user definitely cannot find another user and shouldn't be able to unless you extend the user model and change the ACLs. 

Let me know if that helps, but as @jannyHou said, the docs should be fixed if it isn't clear.

**Comment by richardpringle** [comment]
@starbassma do you have a link to where you read that? 
I found the correct [doc](https://docs.strongloop.com/display/public/LB/Managing+users#Managingusers-Defaultaccesscontrols) where there is a piece of the loopback-core code which can also be found on  [line 67](https://github.com/strongloop/loopback/blob/master/common/models/user.json#L36) of the user.json file.

It only allows the `$owner`...

**Comment by starbassma** [comment]
Hello, @richardpringle  

this is the link :  https://docs.strongloop.com/display/LB/User

**Comment by richardpringle** [comment]
Thanks @starbassma, you found an issue! We'll get that fixed as soon as possible. 

For future reference, I wouldn't use those reference tabs if you are looking for loopback APIs. Instead, use https://apidocs.strongloop.com/.

Happy coding!

**Comment by richardpringle** [comment]
@crandmck, could you please take a look at this: https://docs.strongloop.com/display/LB/User?

**Comment by jannyHou** [comment]
@richardpringle Thanks! I will correct it today!

**Comment by crandmck** [comment]
So https://docs.strongloop.com/display/LB/User was supposed to reflect exactly the same content as https://apidocs.strongloop.com/loopback/#user but due to a bug in strong-docs, it was not being updated when loopback was versioned and so occasionally had mistakes (as it did here).  Anyway, in discussion with @richardpringle we decided to just remove all the replicated API docs from http://docs.strongloop.com, and instead rely http://apidocs.strongloop.com, which is generated from source code comments.

Sorry for the inconvenience.

**Comment by starbassma** [comment]
thank you for the clarification
