### ISSUE TITLE
Many-to-one relationship?

### ISSUE THREAD

**Issue by samzhao** [strongloop/loopback#1522]
Hi,

I was wondering if there is a way to create something like a many-to-one relationship?

Here's what I'm trying to achieve:

2 Models: Project and Status; there will be several preset statuses like "Planning", "In Progress", and "Completed".

For a new project, I will pass along the desired `statusId` so Project knows how to reference Status.

The only way I've found to achieve this is by specifying that Status `hasMany` Projects and Project `belongsTo` Status. That works because a `statusId` will be generated on the Project model and I'll be able to set a default scope to include the whole status object in the project response. However, the problem is that this logically doesn't make sense because in reality Project owns Status and not the other way around.

Please let me know if I'm doing something wrong or if there is a way to achieve this.

Thanks!

**Comment by fabien** [comment]
Hi @samzhao, your approach correct, even through semantically it doesn't really make sense to call it `belongsTo`. I've noticed this myself, but there's no other way right now to declare it in a more meaningful way.

**Comment by raymondfeng** [comment]
Agreed. Ideally, we can introduce `referencesOne` to model `many-to-one` relation. It's very similar as `belongsTo` in many aspects. Maybe `referencesOne` can even be internally handled as `belongsTo`.

**Comment by samzhao** [comment]
Thanks @fabien! I thought I was crazy after looking every where in the docs.

@raymondfeng YES!! I saw `referencesMany` and thought there should be a `referencesOne`, that would make things a lot easier.

I'm surprised that no one has brought it up, yet, or maybe I didn't spend enough time looking for other people's mentions on this feature. To be fair though, other ORM libraries also don't seem to implement a `many-to-one` relation. I thought this is a common use case where you want to link a record to a predefined enum.

**Comment by jmwohl** [comment]
This is closed... but did anything ever happen with it? Was just searching for a `referencesOne`, nothing in the docs. Is using the reverse `hasMany` still the best way to accomplish this type of relationship?

**Comment by jannyHou** [comment]
@jmwohl We have a plan to add `referenceOne` in the future, but I am afraid currently you still need to use the reverse `hasMany`.
