### ISSUE TITLE
multiple hasMany through relations to same model

### ISSUE THREAD

**Issue by Silvercast** [strongloop/loopback#1524]
Hi,
I'm trying to modelize a graph of nodes. One node has many parent nodes. it can also have many sub nodes. I'm quite new to loopback so I use JSON files to define models.

in `node.json` I define

```
   "subnodes": {
      "type": "hasMany",
      "model": "Node",
      "foreignKey": "idparent",
      "through": "NodeRelation"
    },
    "parentnodes": {
      "type": "hasMany",
      "model": "Node",
      "foreignKey": "idchild",
      "through": "NodeRelation"
    }
```

in `noderelation.json` I define 
```
"relations": {
    "node": {
      "type": "belongsTo",
      "model": "Node",
      "foreignKey": "idparent"
    },
    "node": {
      "type": "belongsTo",
      "model": "Node",
      "foreignKey": "idchild"
    }
  }
```

I can query sub nodes but parent nodes return incorrect results. If I change duplicated `node` relations to something like `parent`, `child` I get error 500, `node` relation is not defined in NodeRelation model.

Any hint? I really appreciate your helps.

**Comment by jewelsjacobs** [comment]
I have the same need to do this. I have a group model with a oneToMany relationship to subgroups with the same model. Any advice?

**Comment by jannyHou** [comment]
Hey @Silvercast , I think you did the right thing in `node.json`, but don't use through model (delete `noderelation.json` as well). Just use one model called node and build two relations to itself would be enough. And I also recommend name a foreign key with `id` appended after the `name`, check [relation doc](https://docs.strongloop.com/display/public/LB/HasMany+relations) for more details.
For future reference, please ask questions on [google group](https://groups.google.com/forum/#!forum/loopbackjs).
