### ISSUE TITLE
how to access config variables from middleware.local.js

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback#1526]
I want to dynamically change the path of statically loaded files depending on our environment...

however, in the middleware.local.js file I'm not sure how to access my config variables from app.get('someConfig')

i can require in the app, but the config variables dont seem to have been loaded in for some reason. 

how can i do this?

**Comment by gunjpan** [comment]
Hi @stringbeans, if you are still looking for an answer:
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by tamilvendhank** [comment]
Welldone @gunjpan

**Comment by ORESoftware** [comment]
good lord, I really want the answer to the original question, but now I have to go to google groups? :/

**Comment by superkhau** [comment]
@ORESoftware We do not answer questions using GitHub issues -- see http://loopback.io/doc/en/contrib/Reporting-issues.html#asking-questions. Gitter and Google Groups should be used for questions. If you need immediate support, see https://strongloop.com/node-js/subscription-plans/.

**Comment by ORESoftware** [comment]
ok I see, thank you

**Comment by gunjpan** [comment]
@stringbeans , @ORESoftware : You can use one of the following approaches in your `middleware.<env>.json` file to dynamically update the path serving static files, considering you set your env. variable `STAT` before running the application:
```json
{
   "files": {
    "loopback#static":{
      "params": "${STAT}"
    }
  }
}
```
or 

```json
{
   "files": {
    "loopback#static":{
      "params": "process.env.STAT"
    }
  }
}
```
