### ISSUE TITLE
Unable to override/extend `fields` defined inside `scope` of model definition

### ISSUE THREAD

**Issue by valllabh** [strongloop/loopback#1530]
Unable to override/extend fields defined inside scope of model definition.

Model Defination JSON

```
"scope": {
    "fields": {
      "_deleted": false
    }
 }
```

Querying

```
var filter = {
  fields : {
    _deleted : false,
    created : false,
    updated : false,
    status : false
  },
  where : {
      // conditions
  }
};

MeasureRecord.find(filter, function(err, data){
    console.log(filter)
});

```

Console Prints

```
{
  fields : {
    _deleted : false,
  },
  where : {
      // conditions
  }
}
```

**Comment by raymondfeng** [comment]
The purpose of `scope` to preset a filter that constrain certain clauses.  See https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/utils.js#L188-L193. In your case, I see your intention is to further constrain the visible fields, which seems to be reasonable. Do you want to submit a patch to allow the field exclusion to be added?

**Comment by valllabh** [comment]
correct me if I am wrong, juggler should ideally extend the fields from model?
