### ISSUE TITLE
Logout error

### ISSUE THREAD

**Issue by adanielyan** [strongloop/loopback#1531]
I have a SystemUser model that is inherited from User. The dataSource is mongodb

Trying /SystemUsers/logout in my API explorer I get this error:
```
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Model::findById requires the id argument",
    "stack": "Error: Model::findById requires the id argument\n    at /var/www/jjform/node_modules/loopback-datasource-juggler/lib/dao.js:741:10\n    at /var/www/jjform/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at /var/www/jjform/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31\n    at process._tickDomainCallback (node.js:486:13)\n    at process.<anonymous> (/var/www/jjform/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)"
  }
}
```

Can't figure out what I am doing wrong. Please help.

**Comment by raymondfeng** [comment]
What versions do you have for loopback-connector-mongodb, loopback-connector and loopback-datasource-juggler? Please make sure they are all 2.x.

You can try User.logout from the api explorer.

**Comment by adanielyan** [comment]
Hi Raymond, thank you for responding. I updated the loopback as well as the loopback-connector-mongodb and loopback-datasource-juggler. In fact the latest version of loopback-connector-mongodb I could find was 1.11.3. In the API explorer I still get the error when try the logout. I don't have Users there to try. 

Interestingly in my angular app I the logout works sometimes and sometimes gives me that error. I couldn't determine the pattern though.

**Comment by raymondfeng** [comment]
loopback-connector-mongodb1.11.3 is good. Please make sure the logout() takes an access token.

**Comment by adanielyan** [comment]
Ah, I didn't realize I have to provide a token for logout API to work. After setting it in the explorer the logout worked! Now I know what the issue is related to to troubleshoot it in my angular code. Thank you!

**Comment by mattietea** [comment]
Did you end up figuring out a solution adanielyan? I'm getting a 500 error. I have the token in the header and I'm calling it on Users/logout but still getting error. 

```
header = new Headers({
        'Content-Type': 'application/json',
        'Authorization': this.getToken()
    });
```

**Comment by adanielyan** [comment]
@mattietea it's been a while ago, I can't find that code now. But I believe you shouldn't provide token in a header but should rather provide it as an argument to User.logout() function. Check out this docs: https://apidocs.strongloop.com/loopback/#user-logout
