### ISSUE TITLE
type ['any'] or array not working as expected

### ISSUE THREAD

**Issue by codeyad** [strongloop/loopback#1532]
i tried to use this to get a multiple array like ["one", "two"] but this type just give one single array like this: ['"one", "two"'], i think this is a bug, if not please tell me how i can make this work.

**Comment by codeyad** [comment]
I found that there is a type that work as i need, this is ```['string']```, please can you write that in your doc?, it's almos impossible to find that kind of things.

**Comment by crandmck** [comment]
Hi @codeyad This is documented here (I think) http://docs.strongloop.com/display/LB/LoopBack+types#LoopBacktypes-Arraytypes but I agree it should be cross-referenced better.  Can you suggest where in the docs we should highlight it?

**Comment by crandmck** [comment]
OK, I added xrefs in several places in the docs.  Going to close this since I haven't heard from the OP.
