### ISSUE TITLE
Cannot find module node_sqlite3.node

### ISSUE THREAD

**Issue by AleksMeshkov** [strongloop/loopback#1534]
Hi! I'v just installed strongloop with ```npm install -g strongloop```
Installation went without errors or smth but when I try to do ```slc arc``` I get 
```
slc start
module.js:338
    throw err;
    ^
Error: Cannot find module '/usr/local/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node'
```

I'm using NVM. Node ver. is v0.12.7

Thanks!

**Comment by simoami** [comment]
getting the same error running node v0.12. any ideas?

**Comment by superkhau** [comment]
@rmg ^

**Comment by simoami** [comment]
this is directly reproducible with `slc pm`

running `slc pm` on node v0.12, and getting the following error:

```
$ slc pm
module.js:338
    throw err;
    ^
Error: Cannot find module '/usr/local/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/minkelite/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by simoami** [comment]
SOLVED:

I reran  `npm install -g strongloop` and it worked. In my case this must have happened from upgrading to node v12 but the strongloop package dependencies where compiled under v0.10.

**Comment by rmg** [comment]
@simoami that would do it!

**Comment by rmg** [comment]
@AleksMeshkov there have been a couple releases of not only strongloop but node-sqlite3 since you reported this issue. Is it still a problem for you after re-running `npm install -g strongloop`?

**Comment by simoami** [comment]
no more problems for me at this point. thank you.

**Comment by loay** [comment]
Is this issue good to close?
