### ISSUE TITLE
Add Role '$verified'  (Feature Request)

### ISSUE THREAD

**Issue by mercuriete** [strongloop/loopback#1535]
Im am trying to know if a given user has the email verified.

I know that i can get the context object and then look for the user object and then check if is verified but i want to do something like this:

```
let ctx = Something.app.loopback.getCurrentContext();
let Role = Something.app.models.Role;

Role.isInRole('$verified', ctx.active, function(err,isVerified) {
```

.....
}

or something more useful ....
directly using the '$verified' Role to use ACL
like this:

  {
    model: '*',
    property: 'find',
    accessType: 'EXECUTE',
    principalType: 'ROLE',
    principalId: '$verified',
    permission: 'ALLOW'
  }

I thing that having a generic role for a verified user is really useful.

thanks in advance.

**Comment by raymondfeng** [comment]
For the User model, you can configure it in `server/model-config.json` to set `emailVerificationRequired` to `true`. If so, the `User.login()` will fail if the email is not verified.

**Comment by mercuriete** [comment]
this doesnt fit in my needs.

I want to have an endpoint that behaves different if you are a email-verified user.
for example to give better items or special items only to this users.
I dont want to fail in login at all.

thanks anyway, your product is very useful ^_^

**Comment by barboni** [comment]
@mercuriete how did you solve your problem? I'm currently considering adding a custom "$verified" dynamic role when booting the custom user model Role.registerResolver('verified', function(role, context, cb) {...})

@raymondfeng is there a better way to do this? I don't want to force the user verification right after registration, but later, after the registration process (during which user-relevant data is collected, therefore the user needs to exist and has to be able to log in).

**Comment by raymondfeng** [comment]
`User.login()` fails if `emailVerificationRequired` flag is set to `true` for the `User` model and the user hasn't finished email verification. There is no need to add the `$verified` role.

**Comment by barboni** [comment]
And that is exactly the behavior I do not want. I want the user to be able to log in even if she's not verified. I want to permit specific remote methods only to verified users, while other remote methods are available to all authenticated users, verified or not.

**Comment by raymondfeng** [comment]
@barboni You can create custom role resolver for `$verified` and implement it by looking up the user id from the User model to see if `emailVerified` flag is set. See https://docs.strongloop.com/display/LB/Defining+and+using+roles#Definingandusingroles-Dynamicroles
