### ISSUE TITLE
Mssql connector no longer detected

### ISSUE THREAD

**Issue by digitalsadhu** [strongloop/loopback#1537]
This was working until I reinstalled node_modules today. Suddenly, I get this warning and I can't seem to find a way around it.

I found this issue regarding the oracle connector, strongloop/loopback-connector-oracle#27 which seems related.

Any ideas? The connector is installed and there were no installation errors that I could see. 

Full error message below:

```
WARNING: LoopBack connector "mssql" is not installed as any of the following modules:

 ./connectors/mssql
loopback-connector-mssql

To fix, run:

    npm install loopback-connector-mssql

Application has thrown an uncaught exception and is terminated:
Error: 
WARNING: LoopBack connector "mssql" is not installed as any of the following modules:

 ./connectors/mssql
loopback-connector-mssql

To fix, run:

    npm install loopback-connector-mssql

    at DataSource.setup (C:\Program Files\iisnode\www\contracts-proxy\api\node_modules\loopback-datasource-juggler\lib\datasource.js:304:28)
    at new DataSource (C:\Program Files\iisnode\www\contracts-proxy\api\node_modules\loopback-datasource-juggler\lib\datasource.js:109:8)
    at Registry.createDataSource (C:\Program Files\iisnode\www\contracts-proxy\api\node_modules\loopback\lib\registry.js:349:12)
    at dataSourcesFromConfig (C:\Program Files\iisnode\www\contracts-proxy\api\node_modules\loopback\lib\application.js:414:19)
    at EventEmitter.app.dataSource (C:\Program Files\iisnode\www\contracts-proxy\api\node_modules\loopback\lib\application.js:221:12)
    at C:\Program Files\iisnode\www\contracts-proxy\api\node_modules\loopback-boot\lib\executor.js:160:9
    at C:\Program Files\iisnode\www\contracts-proxy\api\node_modules\loopback-boot\lib\executor.js:251:5
    at Array.forEach (native)
    at forEachKeyedObject (C:\Program Files\iisnode\www\contracts-proxy\api\node_modules\loopback-boot\lib\executor.js:250:20)
    at setupDataSources (C:\Program Files\iisnode\www\contracts-proxy\api\node_modules\loopback-boot\lib\executor.js:159:3)
```

**Comment by raymondfeng** [comment]
Are loopback-connector-mssql listed in your package.json? If not, run:

npm i loopback-connector-mssql --save

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by digitalsadhu** [comment]
Yea, it was working, then I wiped node_modules and reinstalled. Saw that error and checked that the connector is both in package.json and in the node_modules folder. Then ran `npm i loopback-connector-mssql --save` but alas, no change. I have been switching back and forth between memory, mysql and mssql for testing this out. Only mssql is not detected.

**Comment by raymondfeng** [comment]
In the app root dir, try the following command to see what you get:

$ node

> var mssql = require('loopback-connector-mssql');
undefined
> console.log(mssql);
{ name: 'mssql', initialize: [Function: initializeSchema] }

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by digitalsadhu** [comment]
Unsure exactly what I did to fix this but all is well now. May have been a rookie mistake or it may have been a new version of something not sure. Closing the issue.

**Comment by jgwinner** [comment]
I just stumbled into the exact same issue, except with mysql. I had indeed reloaded node_modules. Interestingly, the discovery (building the models from MySQL) worked perfectly. 

Here's the equivalent output to the above:

```
> var mssql = require('loopback-connector-mysql');
undefined
> console.log(mysql);
ReferenceError: mysql is not defined
>
```

**Comment by jgwinner** [comment]
I just double checked, package-json has not changed. 

Taking a look at a 'working' and 'nonworking' directory, other than all the package.json's in the node_modules (which are quite, quite different), the actual node_modules only has one small difference.

dtrace-provider has a `./node_modules/dtrace-provider/build/Release` directory, and a bunch of VC stuff in it. I had indeed switched for Visual Studio Code to Visual Studio 2019 a couple of days before. The timing might be germane. 

I did not intentionally do anything with this, although I might have switched on debugging in loopback.

I just removed that directory but there was no change to the app. With debug on, I still get:
```

  loopback:datasource Settings: {"name":"memdb","debug":true} +0ms
  loopback:datasource Initializing connector Memory +3ms
  loopback:datasource Settings: {"host":"192.168.0.201","port":3306,"url":"","database":"healthcare_db","password":"Sanitized!","name":"healthcare_db","user":"root","connector":"mysql","debug":true} +1ms
  loopback:datasource Module ./connectors/mysql not found, will try another candidate. +1ms
  loopback:datasource Initializing connector undefined +17ms
  loopback:datasource Settings: {"host":"192.168.0.201","port":3306,"url":"","database":"users_db","password":"Sanitized!","name":"users_db","user":"root","connector":"mysql","debug":true} +64ms
  loopback:datasource Module ./connectors/mysql not found, will try another candidate. +1ms
  loopback:datasource Initializing connector undefined +0ms
F:\CareLabsTest\care-device-web2\node_modules\loopback\lib\registry.js:319
  throw new Error(g.f('Model not found: %s', modelName));
  ^

Error: Model not found: deviceInfo
    at Registry.getModel (F:\CareLabsTest\care-device-web2\node_modules\loopback\lib\registry.js:319:9)
    at F:\CareLabsTest\care-device-web2\node_modules\loopback-boot\lib\executor.js:234:24
    at Array.forEach (<anonymous>)
    at defineModels (F:\CareLabsTest\care-device-web2\node_modules\loopback-boot\lib\executor.js:229:23)
    at setupModels (F:\CareLabsTest\care-device-web2\node_modules\loopback-boot\lib\executor.js:197:3)
    at execute (F:\CareLabsTest\care-device-web2\node_modules\loopback-boot\lib\executor.js:40:3)
    at bootLoopBackApp (F:\CareLabsTest\care-device-web2\node_modules\loopback-boot\index.js:154:3)
    at Object.<anonymous> (F:\CareLabsTest\care-device-web2\server\server.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

**Comment by jgwinner** [comment]
After CONSIDERABLE effort, I've found that this preamble happens both when the connection does occur, and when it does not.

The lines at the beginning, including the admonition that mysql is not found, repeat.

```
When Loopback DOES connect, it essentially just keeps going.

  loopback:datasource Settings: {"name":"memdb","debug":true} +0ms
  loopback:datasource Initializing connector Memory +3ms
  loopback:datasource Settings: {"name":"healthcare_db","host":"192.168.0.201","port":3306,"database":"healthcare_db","p
assword":"NatchoPassword","user":"root","connector":"mysql","debug":true} +1ms
  loopback:datasource Module ./connectors/mysql not found, will try another candidate. +1ms
  loopback:datasource Initializing connector undefined +15ms
  loopback:datasource Settings: {"name":"users_db","host":"192.168.0.201","port":3306,"database":"users_db","password":"
Natchpassword","user":"root","connector":"mysql","debug":true} +47ms
  loopback:datasource Module ./connectors/mysql not found, will try another candidate. +1ms
  loopback:datasource Initializing connector undefined +0ms
Second callback
Swagger: skipping unknown type "Binary".
  loopback:datasource Connector is initialized for dataSource memdb +106ms
  loopback:datasource DataSource memdb is now connected to memory +0ms
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
<-- HandshakeInitializationPacket
HandshakeInitializationPacket {
  protocolVersion: 10,
  serverVersion: '5.5.5-10.1.23-MariaDB-9+deb9u1',
... snip ...
  pluginData: 'mysql_native_password',
  protocol41: true }

--> ClientAuthenticationPacket
ClientAuthenticationPacket {
... snip ...
<-- HandshakeInitializationPacket
... snip ...
  pluginData: 'mysql_native_password',
  protocol41: true }

--> ClientAuthenticationPacket
ClientAuthenticationPacket {
... snip ...
  database: 'users_db',
  protocol41: true }

<-- (242) OkPacket
OkPacket {
... snip ...
  protocol41: true,
  changedRows: 0 }

  loopback:datasource Connector is initialized for dataSource healthcare_db +26ms
  loopback:datasource DataSource healthcare_db is now connected to mysql +0ms
<-- (243) OkPacket
  loopback:datasource Connector is initialized for dataSource healthcare_db +26ms
  loopback:datasource DataSource healthcare_db is now connected to mysql +0ms
<-- (243) OkPacket
OkPacket {
... snip ...
  loopback:datasource Connector is initialized for dataSource users_db +3ms
  loopback:datasource DataSource users_db is now connected to mysql +0ms

```

So, the missing MySql provider is a red herring. I'm digging into it more.

**Comment by jgwinner** [comment]
Ok, I found the problem. It was an IO error - BUT Loopback needs a LOT more and better error messages.

The fact that a running app can give several errors, then work OK, shows something is really weird down in there!

**Comment by jgwinner** [comment]
The IO error (Idiot Operator), was that in my discover-schema.js (can't believe I have to build this all by hand, that there isn't a better auto-discover), I had the following lines:

```
  const deviceInfo = await healthcare_db.discoverSchemas('device_info', options);
... snip ...
await writeFile(
    'common/models/deviceInfo.json',
    JSON.stringify(deviceInfo['healthcare_db.device_info'], null, 2)
  );
... snip ...
config.deviceInfo = {dataSource: DATASOURCE_DEVICE, public: true};
... snip ...
  await writeFile(
    'server/model-config.json',
    JSON.stringify(config, null, 2)
  );
}
```

and, in the model-config.js that was built by the stringify, we get:

```
 "deviceInfo": {
    "dataSource": "healthcare_db",
    "public": true
  },
```

Yet, in the actual ./common/models/deviceinfo, we get:

```
{
  "name": "DeviceInfo",
  "options": {
    "idInjection": false,
    "mysql": {
      "schema": "healthcare_db",
      "table": "device_info"
    },
    "relations": {}
  },
  "properties": {
    "id": {
      "type": "String",

```

So the fact that in the MACHINE GENERATED ./common/models, we find "Name": "
**_D_** eviceInfo", turns out to have killed the load. The error message was quite literally correct ... I guess I was tired and didn't think to check the machine generated files.

What's odd ... Loopback needs the ./common/models to load, but when told to load the original database, it doesn't need ./common/models, and knows enough about the database tables to persist their structure, but in the end persists the models with incorrect case.

_### ARG!_
 
I'll add a manual workflow step to auto-generate the models, then go through and correct the case by hand.

         == John ==

**Comment by clementohNZ** [comment]
For me, when I was creating a custom connector, I accidentally deleted the output folder `dist` so when I installed it into another package, the entry file was no longer present (i.e. `index.js`).

After recompiling the code for the custom connector package and re-installing the new package, it worked well 😁

**Comment by ankitCodeDoner** [comment]
/usr/src/app # node .

WARNING: LoopBack connector "DB" is not installed as any of the following modules:

 ./connectors/DB
loopback-connector-DB
DB

To fix, run:

    npm install DB --save

/usr/src/app/node_modules/loopback/lib/application.js:280
    throw err;
    ^

Error: Cannot create data source "DB":
WARNING: LoopBack connector "DB" is not installed as any of the following modules:

 ./connectors/DB
loopback-connector-DB
DB

To fix, run:

    npm install DB --save

    at DataSource.setu
