### ISSUE TITLE
elemMatch include ObjectId not work in REST API filter 

### ISSUE THREAD

**Issue by nvcken** [strongloop/loopback#1539]
Below filter condition not work
```
?filter={"where":{"stores":{"elemMatch":{"code":"wh1","memberId":"551cfeb676cce6df0f3536b1"}}}}
```
If I edit memberId data type from ObjectId to String, It works

**Comment by NelsonBrandao** [comment]
:+1:

**Comment by joaoveiga** [comment]
:+1:

**Comment by bluestaralone** [comment]
:+1:

**Comment by jannyHou** [comment]
hey @nvcken thanks for your suggestion, we are going to support `ObjectId` in the future, for more details please check here: https://github.com/strongloop/loopback-datasource-juggler/pull/778

**Comment by jannyHou** [comment]
This issue is a duplicate feature request as https://github.com/strongloop/loopback-datasource-juggler/pull/778.
I am closing it here. Thanks!
