### ISSUE TITLE
find({ limit: 0 }) means no limit.

### ISSUE THREAD

**Issue by Izhaki** [strongloop/loopback#1540]
This may not be an issue per-se, but I think at least the docs should mention this.

When you set a limit of 0, you get the full result set instead of nothing (see code below).

In our case, we calculate how many new records has to be fetched, which sometimes works out to be 0.

It's an odd one, I admit - is a limit of 0 a valid one?

            this.jobModel.find({
                where: { status: 'pending' },
                order: 'created ASC',
                limit: 0
            },
                aCallback.bind( this )
            );

**Comment by BerkeleyTrue** [comment]
`0` is not valid. Whats probably happening is it's detecting falsey value and ignoring the limit filter.

**Comment by raymondfeng** [comment]
@BerkeleyTrue You are right.

**Comment by Izhaki** [comment]
Hmmm...

So if we have an invalid argument, instead of telling so to the developer somehow (exception/log/docs) we are fine with returning a completely unexpected result? @raymondfeng

**Comment by raymondfeng** [comment]
We can either document it or enhance the code to deal with `limit === 0`. Please note a lot of JS code treat `0` as false.

**Comment by BerkeleyTrue** [comment]
That is the expect result. Without a limit field loopback returns an unlimited query. A query with limit 0 is the same as a limit: undefined.

**Comment by BerkeleyTrue** [comment]
Why would you try do make a query with a limit 0 anyways? Why not do a noop instead when the program sets limit 0?

**Comment by Izhaki** [comment]
@BerkeleyTrue 

You can argue that if a property can be a number, than 0 is much more a number than an undefined value.

In our case we check for the amount of jobs to fetch from the db based on `currentlyRunning - maxConcurrent`, which most of the time is 0.

And anyway, shouldn't the check be `hasOwnProperty` and if it does check that the value is valid?

What will happen with `limit: -2` or `limit: "five"`?

**Comment by johnsoftek** [comment]
There are two points to consider here: what should Loopback do? and what should @Izhaki do?

I think Loopback should not consider limit 0 === unlimited. A falsey test is inappropriate for a numeric parameter to test whether the parameter was supplied.

@Izhaki I suggest that if it is easy to handle a library bug, just do it. Why wait for the library to be fixed? In this case, if limit computes as zero, set the result to [] and don't make the API call.

**Comment by BerkeleyTrue** [comment]
@johnsoftek Good points.

**Comment by raymondfeng** [comment]
Can one of you contribute a patch to `loopback-datasource-juggler/lib/dao.js`?

**Comment by Izhaki** [comment]
@johnsoftek 

I won't mind patching, but I'm unsure what is the correct behaviour in such case.

Although I am the one starting this whole thing, I'm still not sure what `limit: 0` should do.

The problem is that we are accustomed for 0 considered false in many cases, and that a limit of 0 is (despite me arriving at it) a tiny bit senseless.

My line of thinking is simple:
- Any number greater than 0 is a valid limit value.
- Any other value is invalid, and should raise an exception/log message.

I think this way we are not trying to reach a common logical conclusion where logic fails on the premises level (zero is false).

---

On a separate note, I believe that no results returns `null` and not `[]`? This is another thing that surprised me a bit... you often want a forEach loop on the returned set rather than introducing a conditional; but I guess there's a reason for `null`.

**Comment by Izhaki** [comment]
By the way,

With PostgreSQL, a statement with LIMIT 0 returns a blank set.

**Comment by johnsoftek** [comment]
@Izhaki 

Is limit 0 valid? Yes. MySQL and SQLite also accept limit 0 and return an empty set. 

The fact that Javascript considers 0 as falsey is irrelevant here. It just means that a falsey test cannot be used to determine if a value has been supplied when 0 is a legitimate value.

Imo, Loopback should consider limit 0 valid. Should it execute the query using the connector? I think it should to check that the query is valid: limit is meant to affect the output of a query.

Btw, If you test the Loopback API using Explorer, no results returns an empty array, not null.

**Comment by BerkeleyTrue** [comment]
return empty array is standard practice.

**Comment by raymondfeng** [comment]
+1 to callback with `(null, [])`.

**Comment by Tronix117** [comment]
This issue should be reopened. `{limit: 0}` is not the same as `{limit: null}` or `{limit: undefined}`. It's not because JavaScript is very compliant with types, that they do not mean anything.

`{limit: 0}` should return an empty SET, it could be useful when the total count is always returned with the collection, and we need only this information.
