### ISSUE TITLE
Default scope include only partially including associated model for hasOne relationship

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback#1542]
I have set a non-public model content to be including content type by default. The problem is when I do a GET /api/**OTHER_MODEL**/:id/contents : It only includes contentType for the three first results in the set, the rest are left with only the id on the returned json.

There are btw three different contentTypes in the database.
I am using the memory connector.

content.json
```js
{
  "name": "Content",
  "plural": "Contents",
  "base": "PersistedModel",
  "strict": true,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "mixins": {
  },
  "scope": {
    "include": "contentType"
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "contentTypeId": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "contentType": {
      "type": "hasOne",
      "model": "ContentType",
      "foreignKey": "id",
      "description": "The content type"
    }
  },
  "acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }
  ],
  "methods": []
}
```

content-type.json
```js
{
  "name": "ContentType",
  "base": "PersistedModel",
  "strict": true,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

**Comment by kennethlynne** [comment]
And it maps the relations incorrectly. 
I added a custom afterRemote method that attached the relation manually as _contentType.

Interesting to see that it just iterates through the related model (id 1-3) 
```
[
  {
    "name": "something",
    "ownerId": 2,
    "contentTypeId": "1",
    "id": 1,
    "_contentType": {
      "name": "stack",
      "id": 1
    },
    "contentType": {
      "name": "stack",
      "id": 1
    }
  },
  {
    "name": "something",
    "contentTypeId": "3",
    "id": 2,
    "_contentType": {
      "name": "file",
      "id": 3
    },
    "contentType": {
      "name": "link",
      "id": 2
    }
  },
  {
    "name": "something",
    "contentTypeId": "3",
    "id": 3,
    "_contentType": {
      "name": "file",
      "id": 3
    },
    "contentType": {
      "name": "file",
      "id": 3
    }
  },
  {
    "name": "something",
    "contentTypeId": "1",
    "id": 4,
    "_contentType": {
      "name": "stack",
      "id": 1
    }
  },
  {
    "name": "something",
    "contentTypeId": "3",
    "id": 5,
    "_contentType": {
      "name": "file",
      "id": 3
    }
  }
]
```

**Comment by raymondfeng** [comment]
Can you share a github repo with your test case?

**Comment by kennethlynne** [comment]
I will look into it at a later point, as we are swamped to get finished for a deadline due in a couple of weeks. We have worked around it by creating a custom afterRemote method that gets the related content. Interestingly we could not place the data on the "contentType" property, even when the default scope was removed, as the property was overwritten somewhere in the pipeline. It might be a bug on our side, but we could not find any apparent methods from our part that could have done this.

**Comment by richardpringle** [comment]
Hey @kennethlynne, did you ever resolve your issue (with more than a workaround)? I want to make sure this isn't an issue with loopback itself.

**Comment by kennethlynne** [comment]
Only with a workaround sadly. We did not get it to work out of the box. If no one else reports anything similar I would guess it is a bug in our code base, and the issue can be closed. We can rather reopen if something similar occurs with a more recent version of loopback.
