### ISSUE TITLE
Delete `Application` object in explorer or tests returns `204` No Content

### ISSUE THREAD

**Issue by mikesparr** [strongloop/loopback#1543]
During functional test creation I create, read, update, list, delete record(s) for each model, plus any remote methods added to app. The delete operation seems to fail both in Explorer and in my tests, but no error and just returns 204 code. I checked the `node_modules/loopback/common/models/application.json` and JS file and don't see any ACL restrictions so wondering why the DELETE call does not work.

```
✓ GET /apps should return list of (2) records
✓ DELETE /apps/0879faee008cb10eb47174e4f994426c should delete record
⨯ GET /apps should return list of (1) record
  not ok 4 should be equal
    ---
      operator: equal
      expected: 1
      actual:   2
      at: Test.<anonymous> (/Users/mike/Work/identity-service/src/test/functional/main/app.test.js:200:49)
    ...
✓ apps functional tests teardown
# tests 4
# pass  3
⨯ fail  1
```

**It is not just my tests because Explorer app yields same result**
<img width="972" alt="screen shot 2015-07-23 at 10 02 37 pm" src="https://cloud.githubusercontent.com/assets/5553105/8867556/f6f37802-3187-11e5-8e93-d7f746cdb1e3.png">

**Comment by mikesparr** [comment]
In setup I create a record using the `app.create(obj, cb)` and then have functional tests for CRUD. I add one additional test after the DELETE to verify 1 record deleted and list now only 1 record.  The delete doesn't work but no errors returned.

**full test console output**
~~~
Running "jshint:files" (jshint) task
>> 48 files lint free.

Running "tape:files" (tape) task
✓ -- apps functional tests setup ---------------
✓ POST /apps should create new record
✓ GET /apps/8d1c328daf5c859177c703eedcaf369f should return record
✓ PUT /apps/8d1c328daf5c859177c703eedcaf369f should update record
✓ GET /apps should return list of (2) records
✓ DELETE /apps/8d1c328daf5c859177c703eedcaf369f should delete record
⨯ GET /apps should return list of (1) record
  not ok 5 should be equal
    ---
      operator: equal
      expected: 1
      actual:   2
      at: Test.<anonymous> (/Users/mike/Work/identity-service/src/test/functional/main/app.test.js:204:36)
    ...
✓ apps functional tests teardown
# tests 5
# pass  4
⨯ fail  1
Warning: TAP test failure. Exited with code 1 Use --force to continue.

Aborted due to warnings.
npm ERR! Test failed.  See above for more details.
~~~

**database check after test run**
~~~
mysql> select count(1) from app;
+----------+
| count(1) |
+----------+
|        2 |
+----------+
1 row in set (0.00 sec)

mysql> select id, name, description from app;
+----------------------------------+----------+----------------------+
| id                               | name     | description          |
+----------------------------------+----------+----------------------+
| 8d1c328daf5c859177c703eedcaf369f | Test App | New description      |
| c4695b96a56ba9bc43d74dcec4e926c2 | Test App | Test app description |
+----------------------------------+----------+----------------------+
2 rows in set (0.00 sec)

mysql> 
~~~

**Comment by mikesparr** [comment]
## Test code snippet
After getting `204` codes I figured it was some built-in for DELETE so added assertion for it but thankfully I also added a test to verify record count reduced and that is when I caught this. Thanks for any suggestions or explanation.
~~~
                // delete
                t.test('DELETE /' + apiPath + '/' + result.id + 
                  ' should delete record', 
                  function (st) {
                    // Arrange
                    var req = request(app);
                    st.plan(1);

                    // Act
                    var resp = req.del(restApiRoot + '/' + apiPath + '/' + 
                      result.id)
                        .set('Accept',  'application/json');

                    // Assert
                    resp.expect(204)
                        .end(function(err, res) {
                            if (err) t.error(err);

                            st.pass(); // 4
                        });
                });
~~~

**Comment by fabien** [comment]
@mikesparr see: 
- https://github.com/strongloop/loopback/issues/1322
- https://github.com/strongloop/loopback/issues/723
- https://github.com/strongloop/loopback/issues/502#issuecomment-58161710

I think I first reported this back in October last year. In the meantime the deleted item count was indeed gathered from the connector. If you do `App.deleteAll(function(err, info) { ... })` in your app (not the REST API), you'll see that info is something like `{ count: 3 }`. But for REST this is never returned.

The remaining piece of the puzzle is updating Loopback`s shared method declarations for deletes, which currently don't have any `returns` declared. We should add this, and use a flag for backwards compatibility. Perhaps both a global flag/config option as well as a per-model setting for cases where you don't want to disclose this information in your response.

/cc @raymondfeng thoughts?

**Comment by mikesparr** [comment]
Thanks @fabien for confirmation I'm not crazy. ;-)  I wonder if I will have to add remote methods for each model to implement DELETE if LB is not working?

**Comment by fabien** [comment]
Heh, you're welcome @mikesparr - I know the feeling ...

Here are some examples of these shareds method definition where `returns` is missing:
- https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L637
- https://github.com/strongloop/loopback/blob/master/lib/model.js#L498

I think this should be fixed there. DELETE *is* working, you just don't get any feedback with REST.

**Comment by mikesparr** [comment]
I wondered that which is why I perform `mysql` check in comments above and the record was never deleted from database either. Granted we will likely never delete records and just set deleted flag, but it doesn't appear to be working at all.

**Comment by fabien** [comment]
@mikesparr wait, delete is not working at the database level either? This definitely warrants a separate ticket (for the mysql connector?) then.

**Comment by mikesparr** [comment]
I'll create a from-scratch app with mysql connector and try the DELETE from Explorer just to verify. If not, then will add ticket but unsure if LB issues, juggler issue, or connector issue.  CRU work, just no D.

**Comment by mikesparr** [comment]
Database DELETE appears to work with a from-scratch app with new model. Unsure if something different with the built-in model `Application` causing that issue but I didn't see any ACL restrictions.

Simple test worked so I think this is two-fold:
 * why is `Application` model not deleting in database on DELETE call?
 * why is REST response for DELETE returning 204?

**Independent DB test**
~~~
mysql> create database lb_rest_test;
Query OK, 1 row affected (0.00 sec)

mysql> grant all privileges on lb_rest_test.* to 'lb_rest_user'@'%' identified by 'dba';
Query OK, 0 rows affected (0.03 sec)

mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)

mysql> use lb_rest_test;

Database changed
mysql> select * from TestModel;
+----+-------+-------------------------+
| id | name  | description             |
+----+-------+-------------------------+
|  1 | Test1 | Description about test1 |
+----+-------+-------------------------+
1 row in set (0.00 sec)
~~~

**After DELETE in Explorer**
~~~
mysql> select * from TestModel;
Empty set (0.00 sec)
~~~
The record was deleted in database for a newly-created model, but doesn't seem to work when I extend `Application` in my app and delete it.

<img width="973" alt="screen shot 2015-07-23 at 11 37 57 pm" src="https://cloud.githubusercontent.com/assets/5553105/8868314/e2fa41bc-3193-11e5-9755-c0065047677b.png">

**Comment by mikesparr** [comment]
`Application` doesn't seem to be the issue. I added to model-config with mysql DS does delete too in from-scratch test app. I am unsure why my app delete even from Explorer fails. My app extends `Application` with model called `app` so I'll test that next.

**record exists in DB**
~~~
mysql> select id, name, description, owner from Application;
+----------------------------------+-----------+----------------------------+-------+
| id                               | name      | description                | owner |
+----------------------------------+-----------+----------------------------+-------+
| 15c618157c0357a61b5bd4041ad69af8 | Test App1 | Description for test app 1 | 0     |
+----------------------------------+-----------+----------------------------+-------+
1 row in set (0.00 sec)
~~~

**after DELETE in Explorer**
~~~
mysql> select id, name, description, owner from Application;
Empty set (0.00 sec)

mysql> 
~~~

<img width="969" alt="screen shot 2015-07-23 at 11 50 29 pm" src="https://cloud.githubusercontent.com/assets/5553105/8868435/a339e3a0-3195-11e5-82c3-7ddd1e5e1f69.png">

**Comment by mikesparr** [comment]
Even extending `Application` seems to work in from-scratch app. I'll have to dig why DB not deleting for those it seems. The `204` error is the only issue then it appears.

**Comment by mikesparr** [comment]
I found the database delete issue was re-using the ID variable from one test to another and the **listApps** returned array and not object so the **id** param was null and thus destroyById had no ID. Fixed the deleting issue. For now I'll expect `204` response in tests from REST.
