### ISSUE TITLE
Model schema update

### ISSUE THREAD

**Issue by dzdidi** [strongloop/loopback#1544]
I would like to update persisted model with given mongoose schema with passport options plugged in it. 

What is the best way to do it? 
And how to set `isStatic` flag for methods from this schema?

**Comment by dustin-H** [comment]
You may better ask this on [stackoverflow](http://stackoverflow.com).
Cheers
Dustin

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
