### ISSUE TITLE
linkManyToMany with scope issue since 2.19

### ISSUE THREAD

**Issue by ainesophaur** [strongloop/loopback#1546]
I believe this issue is specifically related to loopback-datasource-juggler include.js:471 which I'm using v2.34.0 however I've only tested it with loopback v2.19.0

I'd be happy to raise this issue with loopback-datasource-juggler issues but this area seems to get more traction.

I have a referencesMany relationship between two models that stopped working after upgrading to 2.19. I was able to narrow the issue down to the "scope" definition in the relation. On all of my models I have idInjection set to false and I manually define _id as an ObjectId

BoomOffer
```
"relations": {
    "locations": {
      "type": "referencesMany",
      "model": "BoomStore",
      "foreignKey": "boomStoreIds",
      "scope": {
        "fields": {
          "_id": true,
          "storeLabel": true,
          "storePhoneNumber": true,
          "loc": true,
          "primaryAddress": true,
          "merchantId": true
        }
      }
```

When scope is included the property '_id' is no longer being returned

Below is the output in my debugging session for loopback-datasource-juggler

```
relation.keyTo
   "_id"

target.__data
   Object
      loc: Object
      merchantId: ObjectID
      primaryAddress: ModelConstructor
      storeLabel: "Jo-Ann Fabric and Craft Hollywood"
     storePhoneNumber: "9545556654"
     __proto__: Object
```

When I remove my scope.fields on the relationship, target__data includes _id and everything works properly. However I need to be able to use the field filter and I would prefer to only mark the fields I need as true.

**Comment by loay** [comment]
Hi @ainesophaur 
Is this issue resolved?
If not, did you try a later version than 2.19? 
If you are still experiencing an issue with that, please include your repo so I can test it and have a look at the issue. Thanks.

**Comment by ainesophaur** [comment]
Ill put together a repo which highlights the issue if it still persists.

**Comment by loay** [comment]
Hello, I will close the issue for now.  If you are still running into problems, feel free to leave a comment and I will reopen the issue. Thanks.
