### ISSUE TITLE
error:version not found:path-to-regexp@0.1.7

### ISSUE THREAD

**Issue by TNT-Likely** [strongloop/loopback#1556]
when i create a app,i use npm install,it reports error version not found:path-to-regexp@0.1.7
![qq20150801-2 2x](https://cloud.githubusercontent.com/assets/9278923/9020436/7ee28976-383e-11e5-97e3-6f0b4359092a.png)

**Comment by gunjpan** [comment]
@TNT-Likely : Hi, it looks like an issue with npm unable to find the version. Could you please let me know if this error still exist.

**Comment by gunjpan** [comment]
@TNT-Likely : Can you please advise if you're still experience this issue?

**Comment by gunjpan** [comment]
@TNT-Likely : Hi, Just following up on this issue. Could you please let me know if you're still expereince this issue. IMO, it is not an issue with Loopback itself. Your take on it would be appreciated.
Thank you.

**Comment by TNT-Likely** [comment]
yeah,it isn't an issue with loopback itself,i resolve it .

**Comment by TNT-Likely** [comment]
@gunjpan

**Comment by gunjpan** [comment]
@TNT-Likely : Thank you for your reply and I'm glad that it is resolved for you.. Please feel free to report any bugs you stumble upon or features you would like to see in Loopback by opening a new issue here.
For any questions: we encourage them to be posted on:
Please feel free to ask on:
- Google Groups
- StackOverflow
- Gitter (supported, but we prefer posting to Google Groups so others may benefit from the discussions)
Please see: https://github.com/strongloop/loopback/wiki/Questions for the links.
