### ISSUE TITLE
List remote methods added by relations

### ISSUE THREAD

**Issue by framp** [strongloop/loopback#1557]
Hi guys,
I'm trying to find a way to list remote methods added by relations (eg: `__get__models`, `__create_models`)

The method below is working and let me filter the normal methods.
```
Model.sharedClass.methods().forEach((method) => {
  if (method.name === "create" && method.http) {
    method.http.status = 201;
  }
  method.shared = methods.indexOf(method.name) > -1;
});
```

How can I work with the other remote methods?

Thanks

**Comment by ritch** [comment]
`methods()` returns all  (including relation) remote methods of a given `Model` in an array.

If you had a relationship: **Customer hasMany Order** 

```js
// you could search for __get_orders in the results
Customer.sharedClass.methods()

// or use the sharedClass find method
var isStatic = false;
var method = Customer.sharedClass.find('__get_orders', isStatic);
```

**Comment by framp** [comment]
Thanks for the response @ritch, 
The code is not working in `model.js`, I guess that code is called before relationships are set up.

**Comment by framp** [comment]
You can bypass the problem by using `process.nextTick`

**Comment by Aibier** [comment]
function getAllRemoteMethods(signal, modelName) {
            const activeRemoteMethods = model.sharedClass
                .methods({ includeDisabled: signal })
                .reduce((result, sharedMethod) => {
                    Object.assign(result, {
                        [sharedMethod.name]: sharedMethod.isStatic
                    });
                    return result;
                }, {});

            return activeRemoteMethods;
        }
 signal only takes true or false; modelName is name of model. 
EX: getAllRemoteMethods(false, User) will list all remote methods without disabled remote methods. If you want to include u can call getAllRemoteMethods(true, User).
Hope it helps.
