### ISSUE TITLE
Are there some differences between the following 2 ways to define remote methods?

### ISSUE THREAD

**Issue by yorkie** [strongloop/loopback#1562]
Hey I found a big performance issue, I defined the accepts some of remote methods in the following way:

```js
{
  type: 'object',
  http: function (ctx) { return ctx.req; }
}
```

And when the server is up and I make some parallel requests to this remote port, only parts of requests can get reached and completed, and seriously all the later requests are timeout. I have addressed this by exporting sub fields(`headers`, `status` and etc.) of `req` and `res`(yes, `res` has the same issue in this case).

I guess we at first need to notify user don't make remote definition like this, then find the reason and fix it in the end. Or this is a known issue?

/cc @raymondfeng (Ah I don't know who i should catch with this and think this is really serious in production).

**Comment by yorkie** [comment]
BTW, I have no time to verify if `source` could fix this issue.

**Comment by raymondfeng** [comment]
@ritch Any idea why?

**Comment by yorkie** [comment]
@raymondfeng @ritch I guess I have tracked the bug reason at https://github.com/strongloop/strong-remoting/blob/master/lib/shared-method.js#L478, which does use `traverse` deeply with any objects even included `req` and `res`, and these operation would consumes the CPU resources and blocks the I/O in parallels.

And I created a PR(https://github.com/strongloop/strong-remoting/pull/233) and closing this issue (move there). Thanks Feng :)
