### ISSUE TITLE
Document how to to reject the deletion of a model

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1563]
From the [Google Group post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/loopbackjs/before$20delete/loopbackjs/aBKyf0AmJ-A/yHpI01yBBQAJ)

> you need to call done() with an error to abort the delete, or whatever op...(Document me!) 
.. maybe it should be explicitly mentioned that passing an error to "done" will abort... 

Example given is 
```
if (subscriptions.length > 0) {
  //Stop the deletion of this Client 
  var err = new Error("Client has an active subscription, cannot delete");
  err.statusCode = 400;
  console.log(err.toString());
  next(err);
}else{
  next();
}
```
This confuses me, though, because I don't see a call to `done()`.  I'm obviously missing something...

@bajtos Can you please verify that this is the right approach and/or clarify.

**Comment by bajtos** [comment]
I think you can safely change the instructions to "you need to call next() with an error". Variable names "next", "done", "cb" and "callback" are often used interchangeably. The code example looks good to me.

**Comment by crandmck** [comment]
Thanks.  Added to http://docs.strongloop.com/display/LB/Operation+hooks#Operationhooks-beforedelete.

**Comment by mike-aungsan** [comment]
@crandmck 
I am looking a way to terminate without error message and response obj. Is it possible and how can I do it from operation hooks?

**Comment by crandmck** [comment]
@mike-aungsan Please ask your question on the forum: https://groups.google.com/forum/#!forum/loopbackjs.  Thanks!
