### ISSUE TITLE
Multiple instances on the same proccess

### ISSUE THREAD

**Issue by ericprieto** [strongloop/loopback#1567]
I want to develop a modular application, built by N loopback applications.

Is there a easy way to develop this modules? Maybe with multiple instances on the same proccess?

**Comment by raymondfeng** [comment]
Please check out http://strong-pm.io/. It will give you out-of-box cluster control.

**Comment by ericprieto** [comment]
I guess I explained myself poorly... I'd like to do something like this...

Or maybe create each app module as an node_module package, each running its own loopback instance.

```
-app-+
     +-server-+
     |        +-server.js
     |        +-config.json
     |         
     +-modules-+
               +-module1-+
               |         +-datasources.json
               |         +-model-config.json
               |         +-models-+
               |                  +-model1.js
               |                  +-model1.json
               |                  +-model2.js
               |                  +-model2.json
               +-module2-+
                         +-datasources.json
                         +-model-config.json
                         +-models-+
                                  +-model1.js
                                  +-model1.json
                                  +-model2.js
                                  +-model2.json
```

Bottomline, what I'd like is to use loopback and loopback-juggler without strong-remoting, to build modules for my platform

**Comment by raymondfeng** [comment]
You can find a similar use case at https://github.com/strongloop/strong-arc/blob/master/server/server.js. Basically, we develop sub-apps as modules and mount them to the main app.

**Comment by ericprieto** [comment]
I'll give a look, thanks!!
