### ISSUE TITLE
Create React Full Stack Example

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1568]
@LucaColonnello

I think we should create a React example similar to https://github.com/strongloop/loopback-example-offline-sync

The first step would be getting the basic todo application built without any offline sync capability. This would demonstrate how to build a react + flux app using loopback on the back end and loopback in the browser.

**Comment by LucaColonnello** [comment]
Yeah @ritch , I think this could be enough.
Can you build the server or have we to use the same code of the repo you link?
Then I could create all the components based on the ToDo example, with Flux implementation from Facebook in ES 6 or 5 as you prefer.

**Comment by ritch** [comment]
You can re-use the LoopBack client and server... You can ditch the angular code altogether.

**Comment by LucaColonnello** [comment]
Ok, I would use Webpack for compilation and React 0.13 with ES 6 (Babel).
Now I start from learning from the angular repo.
If have particular questions, please let me know.

**Comment by LucaColonnello** [comment]
Could I create my own repo or you have one yet?

**Comment by ritch** [comment]
https://github.com/strongloop/loopback-example-react

**Comment by LucaColonnello** [comment]
Could we remove Grunt? Or is needed for the test?
I'm using Webpack for compilation, that can inlcude the build script of lbclient..

**Comment by ritch** [comment]
Grunt is used to build the browserify bundle.

**Comment by ritch** [comment]
Grunt specifically is not required though... something that builds the client and runs the tests **is required**.

**Comment by LucaColonnello** [comment]
Hi @ritch ,
do you want to have Jest test for react, or we could do this without them?

**Comment by ritch** [comment]
Tests have been really helpful in the past. We usually use mocha, since our CI is setup to handle coverage and other things. Though I'm not sure exactly what we support as far as front end tests.

**Comment by LucaColonnello** [comment]
Ok Ritchie,
in order to make a first release of this example, I'll mantain the models
test.
For the Front End in the future we could integrate jest with grunt-jest
(from leebyron).
I'm using browserify and webpack, because compiling lbclient with webpack
give a lot of errors.
Have you an end planned date for this project?
If so I have to move fast!
Il giorno lun 10 ago 2015 alle 20:46 Ritchie Martori <
notifications@github.com> ha scritto:

**Comment by ritch** [comment]
Closing and moving discussions to new repo

**Comment by pe3** [comment]
Any interest for building an example with [create-react-ap](https://github.com/facebookincubator/create-react-app) integration?
