### ISSUE TITLE
LoopBack models should inherit config.options from the parent

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#157]
When LB developer wants to access built-in LB models via app.models, he has to define subclasses in models.json. The current implementation requires that a lot of config options of the base model must be repeated in the subclass definition.

This has several disadvantages:
1. It's difficult to add a built-in model to your app, especially if you are new to loopback.
2. If we modify the built-in model (e.g. by adding another relation), existing application will break after upgrade.

Below are the use cases I discovered while writing E2E tests for loopback-angular.
### datasource

``` js
app.model('MyUser', {
  options: { base: 'User' },
  dataSource: 'db'
});
```

Result:

```
assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: MyUser is referencing a dataSource that does not exist: "undefined"
    at modelFromConfig (/Users/bajtos/src/loopback/loopback/node_modules/loopback/lib/application.js:545:3)
    at Function.app.model (/Users/bajtos/src/loopback/loopback/node_modules/loopback/lib/application.js:115:38)
    [etc.]
```

Since the new model is a subclass of a built-in model, it should use the same datasource that was configured for the User model.

If the datasource of the base class was not resolved yet, but it has `autoAttach` property, then the process of attaching the subclass to a datasource should be deferred to `loopback.autoAttach`.
### relations

``` js
var user = app.model('user', {
  options: {
    base: 'User',
  },
  dataSource: 'db'
});

app.enableAuth();

var credentials = { email: 'foo@foo.com', password: 'password'};
user.create(credentials, function(err) {
  if (err) throw err;
  user.login(credentials, function(err) {
    if (err) throw err;
    console.log('login passed');
  });
});
```

Result:

```
/Users/bajtos/src/loopback/loopback/lib/models/user.js:152
          user.accessTokens.create({
                            ^
TypeError: Cannot call method 'create' of undefined
    at /Users/bajtos/src/loopback/loopback/lib/models/user.js:152:29
    at /Users/bajtos/src/loopback/loopback/lib/models/user.js:202:7
    at /Users/bajtos/src/loopback/loopback/node_modules/bcryptjs/bcrypt.min.js:40:101
    [etc]
```

To fix this problem, one has to re-define User relations:

``` js
var user = app.model('user', {
  options: {
    base: 'User',
    relations: {
      accessTokens: {
        model: 'AccessToken',
        type: 'hasMany',
        foreignKey: 'userId'
      }
    }
  },
  dataSource: 'db'
});
```

**Comment by shyd0w** [comment]
Is this still and issue? Where can I find the documentation to override these connections? Thank you!

**Comment by bajtos** [comment]
Let's bring this issue back to life. For the upcoming 3.0 release, I am proposing to modify juggler's model builder to inherit model settings when subclassing a new model.

```js
app.model('MyUser', {
  options: { base: 'User' },
  dataSource: 'db'
});
// expected outcome:
assert(MyUser.settings.__proto__ === User.settings);
```

**Comment by shyd0w** [comment]
I think that would be great! Options is the inheritance of the setting?

**Comment by davidcheung** [comment]
Loosely related https://github.com/strongloop/loopback/issues/1485

**Comment by bajtos** [comment]
ACLs are not inherited either, see #2270.

As for inheriting relations, pure prototypal inheritance may not be enough. Consider this scenario:

We have a parent model `User` which has a relation

  ```js
accessTokens: {
  model: 'AccessToken',
  type: 'hasMany',
  // this is omitted: foreignKey: 'userId'
}
```

When attached to a datasource, `foreignKey` property is automatically inferred and `AccessToken.userId` property is defined by juggler.

Now when we create `Customer` extending `User`, the foreign key for relation `accessTokens` will be generated as `AccessToken.customerId`, which may break code relying on `userId` property name.

A possible solution is to always fill in `foreignKey` before inheriting model settings.

**Comment by bajtos** [comment]
We agreed this required a bit of research to find out what and how should be inherited when subclassing a model. We don't have bandwidth to address it in 3.0 time.
