### ISSUE TITLE
Misleading documentation regarding loopback context

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback#1570]
The documentation at http://docs.strongloop.com/display/LB/Using+current+context contains the following example,

```javascript
var count = 0;
MyModel.myMethod = function(cb) {
  var ctx = loopback.getCurrentContext();
  // Get the current access token
  var accessToken = ctx.get('accessToken');
  ...
  // Set more information to the current context
  ctx.counter = count++;
}
```

The **counter** code is at best misleading. This will produce a sort of global property, unlike the request-scoped properties that `get` and `set` methods work with. Is it normal/recommended for the context object to be used in this way? 

I'm happy to update the documentation to clarify this, but wanted to understand whether this counter code example should exist there at all.

**Comment by ritch** [comment]
It should just be removed.

`ctx.set()` can be used to set per context data...

Updates to the docs would be great.

**Comment by doublemarked** [comment]
@ritch thanks for your feedback. I cut out the counter example and stuck in a generic `set` example. @crandmck can check and confirm that he's satisfied with it.

**Comment by crandmck** [comment]
@doublemarked  I approved it. Thanks for the correction!
