### ISSUE TITLE
middleware config is not merged properly

### ISSUE THREAD

**Issue by rkmax** [strongloop/loopback#1572]
I have the following settings

## `middleware.json`
```json
{
  "initial:before": {
    "loopback#favicon": {}
  },
  "initial": {
    "compression": {}
  },
  "session": {},
  "auth": {},
  "parse": {},
  "files": {
    "loopback#static": [
      {"params": "$!../client/ngapp/"},
      {"params": "$!../"}
    ]
  },
  "final": {
    "loopback#urlNotFound": {}
  },
  "final:after": {
    "errorhandler": {}
  }
}
```

## `middleware.production.js`
```js
module.exports = {
  files: {
    'loopback#static': [
      {params: '$!../client/dist/'}
    ]
  }
};
```

You can see here config-loader are merging the two files but the result is not the expected

![captura de pantalla de 2015-08-07 08-48-53](https://cloud.githubusercontent.com/assets/395707/9137111/2cec13b0-3ce1-11e5-9c5f-11fae4aa846e.png)

I want replace the `files` phase totally

**Comment by rkmax** [comment]
I dont see that the issue was resolve when I change from passing an object to array in the `middleware.production.js`

**Comment by rkmax** [comment]
I'll reopen this issue because after update to loopback@2.21.0 my app stop working on production

## `2.20.0`
![captura de pantalla de 2015-08-14 18-15-53](https://cloud.githubusercontent.com/assets/395707/9285929/a4181a04-42b0-11e5-8382-1a713a09c135.png)

## `2.21.0`
![captura de pantalla de 2015-08-14 18-16-19](https://cloud.githubusercontent.com/assets/395707/9285930/aa34790a-42b0-11e5-8ac2-887c59bfa5ad.png)


Obviously my app stop working because is serving the development files

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback-boot/pull/147 and https://github.com/strongloop/loopback-boot/pull/148. We now introduced an optional `name` attribute on the middleware config objects under the same phase/module-path. To merge matching objects, you need to put the same name on different sources.

**Comment by rkmax** [comment]
@raymondfeng this it's correct

## `middleware.json`
```
{
  "initial:before": {
    "loopback#favicon": {}
  },
  "initial": {
    "compression": {}
  },
  "session": {},
  "auth": {},
  "parse": {},
  "files": {
    "loopback#static": [{
      "name": "myfiles",
      "params": ["$!../client/ngapp/", "$!../"]
    }]
  },
  "final": {
    "loopback#urlNotFound": {}
  },
  "final:after": {
    "errorhandler": {}
  }
}
```
## `middleware.production.js`

```
module.exports = {
  files: {
    'loopback#static': [
      {"name": "myfiles", params: '$!../client/dist/'}
    ]
  }
};
```

**Comment by richardpringle** [comment]
Hey @rkmax, did @raymondfeng's suggestion work?

**Comment by rkmax** [comment]
@richardpringle yes it works but I have another issue when I ran some slc command the files are edited and the Middleware settings are losed. Maybe I need open a different issue for that

**Comment by richardpringle** [comment]
@rkmax, I am going to close this issue and you can open up another issue. Feel free to mention me in the new issue if you want someone to take a look at it right away.
