### ISSUE TITLE
Install failed due to the "shasum check failed"

### ISSUE THREAD

**Issue by iamgyz** [strongloop/loopback#1574]
Dear,
I run command `$ npm install -g strongloop`  
And it was always failed, here is my err message  

```
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "strongloop" "--verbose"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! shasum check failed for /var/folders/mb/y9k9jzk138lg8hhvq3gtq5080000gn/T/npm-2114-97692008/registry.npmjs.org/docular/-/docular-0.6.6.tgz
npm ERR! Expected: 3913c9ddf4afd1edf986dda4ce8e1e18205cba15
npm ERR! Actual:   3c53f53a777301b16ea2ba44b97ba352b213462a
npm ERR! From:     https://registry.npmjs.org/docular/-/docular-0.6.6.tgz
``` 

I aslo try to run `$ npm cache clear ` and unluckily, it still got failed :(

Thanks!

**Comment by JaminFarr** [comment]
I'm getting the same issue on a windows machine,

```
browser bundle successfully generated
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2

npm ERR! shasum check failed for C:\Users\BENFAR~1\AppData\Local\Temp\npm-7928-6e59cc59\registry.npmjs.org\docular\-\docular-0.6.6.tgz
npm ERR! Expected: 3913c9ddf4afd1edf986dda4ce8e1e18205cba15
npm ERR! Actual:   781f718bb5c35c2d10b36dcbcf4f11a4ff88e579
npm ERR! From:     https://registry.npmjs.org/docular/-/docular-0.6.6.tgz
```

Also cleared the npm cache with no luck.

**Comment by superkhau** [comment]
@rmg @sam-github ^

**Comment by rmg** [comment]
This appears to be corruption of the docular module, either in your local cache or in the registry. Clearing your cache with `npm cache clean` and trying again is the easiest solution - but it won't help any if the corruption is in the registry itself. The docular module author may need to republish.

**Comment by iamgyz** [comment]
@rmg Hello rmg, as you can see in my first post, I've already tried `npm cache clean`. But unluckily, it failed.

**Comment by rmg** [comment]
@iamgyz like I said, if that doesn't solve the problem then the corruption may be in the registry itself.

It is interesting that both of these occurrences have different shasums for the downloaded file. Unfortunately, I am unable to reproduce the error:
```
$ npm info docular@0.6.6 dist

{ shasum: '3913c9ddf4afd1edf986dda4ce8e1e18205cba15',
  tarball: 'http://registry.npmjs.org/docular/-/docular-0.6.6.tgz' }

$ wget http://registry.npmjs.org/docular/-/docular-0.6.6.tgz
--2015-08-13 16:01:01--  http://registry.npmjs.org/docular/-/docular-0.6.6.tgz
Resolving registry.npmjs.org... 199.27.79.162
Connecting to registry.npmjs.org|199.27.79.162|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8775285 (8.4M) [application/octet-stream]
Saving to: 'docular-0.6.6.tgz'

2015-08-13 16:04:08 (45.9 KB/s) - 'docular-0.6.6.tgz' saved [8775285/8775285]

$ shasum docular-0.6.6.tgz
3913c9ddf4afd1edf986dda4ce8e1e18205cba15  docular-0.6.6.tgz
```

When I download the file manually and verify it, I get the correct file. It did download incredibly slowly, though, so it clearly had not been distributed to the CDN endpoint I hit. Downloading it a second time was literally 100x faster. The second download also validated correctly.

You could try downloading the file directly and verifying it like I did, and then manually adding it to your npm cache with `npm cache add ./docular-0.6.6.tgz` to see if that helps any.

Also, just to rule it out.. @JaminFarr @iamgyz are either of you behind http proxies of any kind?

**Comment by iamgyz** [comment]
@rmg Thank you for your very-detailed explanation! I tried to install again on my mac but unluckily it still not works :( 
But I tried to install on my other notebook, it works. That's really weird.

BTW, I do not using any http proxy.

**Comment by rmg** [comment]
@iamgyz perhaps an antivirus tool of some kind? Did the direct download and `npm cache add` work?

**Comment by richardpringle** [comment]
@iamgyz, I hope you solved your issue! If you have any further issues to do with installing strongloop, please refer to the [issues tab](https://github.com/strongloop/strongloop/issues) of the strongloop repo
