### ISSUE TITLE
Concept / task docs for using LB Promise APIs

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1575]
This task is to write documentation (in Confluence primarily) on how to use LoopBack's Promise APIs.  We closed #1409 which was to document the Promise API, the thinking being that we can describe at a high level how the Promise-based API corresponds to the standard callback-based API.

Therefore, this document takes on even more significance because it will be essentially the only place that explains how to use Promises w LB.

**Comment by crandmck** [comment]
Working draft (mostly notes atm): http://docs.strongloop.com/display/LB/Using+Promises.

**Comment by crandmck** [comment]
@miroslav @ritch - It would be extremely helpful if there were some basic examples or tests of the currently-implement Promise APIs that I could look at.  Is there anything?

May I suggest that in the long run, it would be nice to have at least one full example app that uses the Promise APIs that are implemented?

**Comment by bajtos** [comment]
The story covering work on our examples: #1576
