### ISSUE TITLE
Host the documentation on GitHub and add a link to let people send PRs

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback#1580]
Just like the "improve this doc" button on https://docs.angularjs.org/api

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
You can edit the LoopBack documentation simply by logging in to the Confluence wiki and editing the page.  See http://docs.strongloop.com/display/LB/Contributing+to+LoopBack+documentation

I realize there may be other advantages to using GitHub as a doc repository / source, but at this point we are using Confluence and migrating to a different platform would be a _huge_ undertaking.  While I'm open to looking into that in the long run, we are too short on resources and have too many other higher-priority tasks to consider it in the short term.

In the meantime, we welcome contributions and edits to the docs using the above process.  You're also invited to make specific requests/comments/issues via GH issues.  Just label it as a "doc" issue.
Thanks!
