### ISSUE TITLE
middleware.json does not get merged into middleware.development.json

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback#1581]
Here is a snippet from my middleware.json:
```
"routes:before": {
    "loopback#static": [
      {
        "enabled": true,
        "params": "$!../client/build"
      },
      {
        "enabled": false,
        "paths": "/agency/vendor",
        "params": "$!../client/agency/vendor"
      },
      {
        "enabled": false,
        "params": "$!../client/agency/.tmp"
      },
      {
        "enabled": false,
        "paths": "/agency/bower_components",
        "params": "$!../client/agency/bower_components"
      },
      {
        "enabled": false,
        "paths": "/node_modules",
        "params": "$!../client/node_modules"
      },
      {
        "enabled": false,
        "paths": "/apidoc",
        "params": "$!../client/apidoc"
      },
      {
        "enabled": true,
        "paths": "/ZeroClipboard.swf",
        "params": "$!../client/build/ZeroClipboard.swf"
      }
    ],
    "./middleware/rate-limit": {
      "enabled": true,
      "params" : {
        "limit": 5,
        "interval": 1
      },
      "paths" : "/api/v1((?!/quote-option-file|/invoice-file/upload|/student/\\d+/file/upload))"
    }
  }
```

Here is a snippet of the same routes:before block from middleware.development.json:
```
"routes:before": {
    "loopback#static": [
      {
        "enabled": true
      },
      {
        "enabled": true
      },
      {
        "enabled": true
      },
      {
        "enabled": true
      },
      {
        "enabled": true
      },
      {
        "enabled": true
      },
      {
        "enabled": true,
        "paths": "/ZeroClipboard.swf",
        "params": "$!../client/bower_components/zeroclipboard/dist/ZeroClipboard.swf"
      }
    ],
    "./middleware/rate-limit": {
      "enabled": true
    }
  },
```

In Loopback 2.20.0, when trying to start my server using `slc run` I get the error `TypeError: root path required`.

However, when I downgrade to 2.18.0 I no longer get the error. After playing around with it a bit I noticed that in Loopback 2.20.0 I need to redeclare the loopback#static phases, whereas in Loopback 2.18.0 the phases are properly merged together.

Please fix.

**Comment by raymondfeng** [comment]
The change is probably introduced by https://github.com/strongloop/loopback-boot/commit/32276c79d4833e723e3d2e58b35d2df07308f5c3. We have some conflicts of interest here:

For example, if middleware.json has 
```json
"routes:before": {
    "loopback#static": [
      { "paths": "/x" },
      { "paths": "/y" },
..
```
1. To override existing entries in middleware.json
2. To add new entries to middleware.json

How can I tell whether the intention is 1 or 2?

**Comment by stringbeans** [comment]
Hi Raymond,

I understand the conflict of interest here. I would assume however that the functionality is intention 1, as that is has been working for a while now. 

Intention 2 seems like a new feature...

What do you think? I mean, ideally a minor revision upgrade would not change an existing feature/behaviour unless its documented somewhere.

**Comment by raymondfeng** [comment]
Putting aside the `semver`, maybe the following is a better way to fix this issue.

1. Each middleware entry can have an optional name.
2. During merge, if the name matches, we'll override, otherwise append.

**Comment by stringbeans** [comment]
ooh actually i do like that solution... ive been wishing for a way to name the different middleware/phases :)

**Comment by raymondfeng** [comment]
@stringbeans Can you migrate to https://github.com/strongloop/loopback-boot/issues/148? We have released it as part loopback-boot@2.11.0.

**Comment by richardpringle** [comment]
@raymondfeng, did this issue get resolved with https://github.com/strongloop/loopback-boot/issues/148?

**Comment by richardpringle** [comment]
closing the issue as it looks like https://github.com/strongloop/loopback-boot/pull/148 was landed
