### ISSUE TITLE
How to use Application Model in Loopback?

### ISSUE THREAD

**Issue by shankscoder** [strongloop/loopback#1583]
I'm trying to understand the Application model that's part of the built-in models in LoopbackJS. From what I've understood, it's a way to allow for programatic access to a Loopback instance, as an alternative to user logins.

What I'm not able to fathom is how to actually use it. Is this something that can be done standalone or has to be done with the API Gateway only?

If the former, can someone share some examples of how to use the client application workflow? How do you validate an Application key? How does an application work with realms? There's very little documentation related to how to use Loopback with Realms and Client Applications.

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See ht    tps://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by ernest-okot** [comment]
I must agree with @superkhau, even three years later, a Google search on this yields next to nothing. I think a lot of people would be happy to see an example of how to use the Application Model
