### ISSUE TITLE
duplicate primary key in api explorer

### ISSUE THREAD

**Issue by daddybh** [strongloop/loopback#1585]
Hi, I wrote a script to generate model from mysql database. 
The table is like:

| Column Name        | PK       |   TYPE  | NN
| ------------- |:-------------:| -----:| -----:|
| ThreadID | primary key | int | not null
| TopicID |      | int | not null 

My script is simply use `discoverSchema` api and write scheme to file.
```
ds.discoverModelDefinitions({
        all: false,
        schema: 'db_uc_quan',
        views: false
    },
    function(err, models) {
        models.forEach(function(def) {
            ds.discoverSchema(def.name, null, function(err, schema) {
                fs.writeFileSync(path, JSON.stringify(schme, null, 2));
            })
        })
    });
```
Checking the api explorer, there is a duplicate primary key in the schema. Why is this happening?
I have to manually change the `threadid` field to `ThreadID` to solve this issue.

But some tables do not have this issue.

![1](https://cloud.githubusercontent.com/assets/3275603/9220909/9334c802-4118-11e5-9a72-ccc2e4f4a6b7.png)

**Comment by jannyHou** [comment]
Hey @daddybh , I tried to reproduce your problem but in my case, the primary key works fine.
I will paste my snippet and config stuff here, if you still have problem, please contact me.
This is my script file, exactly the same code as you post:
```
var fs = require('fs');
var path = 'common/models/person.json';
module.exports = function(app) {
	var ds = app.dataSources.mysqlDs;

    ds.discoverModelDefinitions({
        all: false,
        schema: 'testtest',
        views: false
    },
    function(err, models) {
        models.forEach(function(def) {
            ds.discoverSchema(def.name, null, function(err, schema) {
                fs.writeFileSync(path, JSON.stringify(schema, null, 2));
            })
        })
    });
};
```
And I created the table in MySQL as :
```
CREATE TABLE testtest.thread
(
ThreadID int NOT NULL,
LastName varchar(255) NOT NULL,
FirstName varchar(255),
Address varchar(255),
City varchar(255),
PRIMARY KEY (ThreadID)
)
```

My explore api looks like:
```
{
  "threadid": 0,
  "lastname": "string",
  "firstname": "string",
  "address": "string",
  "city": "string"
}
```
(please ignore unnecessary property names :p)
