### ISSUE TITLE
How to query only with included models?

### ISSUE THREAD

**Issue by dodiego** [strongloop/loopback#1591]
I have a query that looks like this:

```
User.find({
	include: {
		relation: 'Comment',
		scope: {
			where: {
				text: {
					like: '%some text'
				}
			}
		}
	}
}, function (err, users) {
	...
})
```

Everything works great, but i want to be able to query only the users that commented "some text", like a inner join. 

How can i do that?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
