### ISSUE TITLE
Query with inq with like and nlike

### ISSUE THREAD

**Issue by GustavoRPS** [strongloop/loopback#1592]
I would like to make a query in an array with inq and like.
```
API_URL/v1/tweets?filter={ "where": { "categories":  { "inq": ["%profile%", "%content%"] } } }
```
It's possible?

**Comment by superkhau** [comment]
See https://docs.strongloop.com/display/public/LB/Where+filter. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by GustavoRPS** [comment]
Thank you for your quick reply.
It was for the group to know if it is possible to use inq and like to query at an array.

**Comment by superkhau** [comment]
What do you mean for the group to know?

**Comment by GustavoRPS** [comment]
The group at Google https://groups.google.com/forum/#!forum/loopbackjs.

**Comment by superkhau** [comment]
I see, please let the group know at the forums as we use issues mainly for bug reports and feature requests, but not questions.

**Comment by GustavoRPS** [comment]
Got it. I will remember it.
