### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by ianseyer** [strongloop/loopback#1594]
https://docs.strongloop.com/display/LB/Email

![screen shot 2015-08-14 at 12 48 00 pm](https://cloud.githubusercontent.com/assets/4384951/9280264/be3790dc-4282-11e5-8be1-799305411f16.png)

**Comment by crandmck** [comment]
Thanks, this has already been reported on the forum: https://groups.google.com/forum/#!topic/loopbackjs/0VtlFCiJ76g

We're working on a fix.  Meantime, please use https://apidocs.strongloop.com/.
