### ISSUE TITLE
Setters not applied for updateAll()

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1595]
`MyModel.updateAll()` should apply setters.

Simple repro script:

``` js
var loopback = require('loopback');

var app = loopback();

app.model('Test', {
  base: 'PersistedModel',
  properties: {
    foo: String
  }
});

var Test = app.models.Test;

Test.attachTo(loopback.memory());

Test.setter.foo = function(value) {
  this.$foo = 'X';
}

Test.create({
  foo: 'bar'
}, function(err, inst) {
  console.log(inst);
});

Test.create(new Test({
  foo: 'bar'
}), function(err, inst) {
  console.log(inst);
});

var d = new Test({
  foo: 'bar'
});

d.foo = 'bar';

Test.updateAll({}, {foo: 'bar'}, function() {
  Test.find(console.log);
});
```

**Potential Fix:**

If the `data` argument is coerced into a model instance before calling the method - you will not have this issue. This is something we should be able to do when this method is invoked remotely (eg. `POST /api/my-models`).

**Comment by ritch** [comment]
> If the `data` argument is coerced into a model instance before calling the method - you will not have this issue. This is something we should be able to do when this method is invoked remotely (eg. `POST /api/my-models`).

This won't work since we cannot coerce the argument (`data`, which is an object of partial data) into a `Model` instance without side effects.

**We should apply setters** when data is modified though. Otherwise setters are not really useful at all...

**Comment by EthraZa** [comment]
Hi, I came to the point in my project where I need to update an user password. 
Was this fixed already?
