### ISSUE TITLE
Cannot get related models via strong-remoting

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback#1596]
My remoting calls connect to my loopback server which uses mongodb. Both the `.json` files for ReportModel and StockOrderLineitemModel have:
`"id": {"type": "string", "generated": true, "id": true},`

Now, if I try something basic like:
`ReportModel.findById('55cc99bb3b52a6ebdeed394f', { include: {relation: 'stockOrderLineitemModels', scope: {skip:0,limit:5} } }).then(function(result){ console.log(result) })`

On the server-side ... it works fine:

```
{ created: Thu Aug 13 2015 08:20:59 GMT-0500 (CDT),
  id: 55cc99bb3b52a6ebdeed394f,
  stockOrderLineitemModels: 
   [ { sku: '10078',
       orderQuantity: 3,
       updatedAt: Thu Aug 13 2015 08:20:59 GMT-0500 (CDT),
       supplyPrice: 3.614,
       userId: 55c8b2d59d10891101148398,
       reportId: 55cc99bb3b52a6ebdeed394f,
       id: 55cc99bb3b52a6ebdeed3950 },
     { sku: '10145',
       orderQuantity: 2,
       updatedAt: Thu Aug 13 2015 08:20:59 GMT-0500 (CDT),
       supplyPrice: 2.796,
       userId: 55c8b2d59d10891101148398,
       reportId: 55cc99bb3b52a6ebdeed394f,
       id: 55cc99bb3b52a6ebdeed3951 },
     { sku: '10148',
       orderQuantity: 2,
       updatedAt: Thu Aug 13 2015 08:20:59 GMT-0500 (CDT),
       supplyPrice: 2.227,
       userId: 55c8b2d59d10891101148398,
       reportId: 55cc99bb3b52a6ebdeed394f,
       id: 55cc99bb3b52a6ebdeed3952 },
     { sku: '102301',
       orderQuantity: 2,
       updatedAt: Thu Aug 13 2015 08:20:59 GMT-0500 (CDT),
       supplyPrice: 3.103,
       userId: 55c8b2d59d10891101148398,
       reportId: 55cc99bb3b52a6ebdeed394f,
       id: 55cc99bb3b52a6ebdeed3953 },
     { sku: '10278',
       orderQuantity: 2,
       updatedAt: Thu Aug 13 2015 08:20:59 GMT-0500 (CDT),
       supplyPrice: 2.285,
       userId: 55c8b2d59d10891101148398,
       reportId: 55cc99bb3b52a6ebdeed394f,
       id: 55cc99bb3b52a6ebdeed3954 } ] }
```

But if I use similar code over the wire via strong-remoting: 

```
return client.models.ReportModel.findByIdAsync(
  params.reportId,
  { include: {relation: 'stockOrderLineitemModels', scope: {skip:0,limit:5} } }
)
.then(function (reportModelInstance) {
  console.log('reportModelInstance:', reportModelInstance);
});
```

Then I don't see the related model's results, instead I get **NaN**:

```
{
  id: '55cc99bb3b52a6ebdeed394f', 
  created: Thu Aug 13 2015 08:20:59 GMT-0500 (CDT), 
  userModelToReportModelId: NaN // <-- doesn't work?
}
```

This may be a bug, thoughts?

**Comment by pulkitsinghal** [comment]
cc @ritch - created as requested by you, please let me know of any and all additional details that you might need from me.

**Comment by pulkitsinghal** [comment]
Just went through the same shock & awe again ... only to realize that I had already filed this bug here ... any update on where it is in the roadmap?

**Comment by richardpringle** [comment]
Hey @pulkitsinghal, our resources are wearing thin over here. I tried to reproduce the issue but wasn't able to quickly do so and ended up moving on to something else.

Is it possible for you to fork [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) to make it easier for me to reproduce and narrow down the issue.

I believe that @ritch is swamped at the moment, so he might not have had a chance to take a look.

**Comment by pratheekrebala** [comment]
+1

**Comment by jannyHou** [comment]
@pulkitsinghal there is an example repo https://github.com/strongloop/loopback-example-relations that contains basic relations to try, in your case, I believe it's `hasMany` or `embedsMany`, but both of them return related items in the above sample repo.

We are closing it, feel free to reopen it with your sample code. Thanks for understanding.
