### ISSUE TITLE
How can I retrieve data from REST api with constraint on its manyToMany model?

### ISSUE THREAD

**Issue by mahadazad** [strongloop/loopback#1600]
I have `Post` model and `Categories` Model. I have defined their relation with `HasAndBelongsToMany` relation.

Now I want to retrieve Posts using `GET Posts` API with constraint on `Categories` and Posts ordered by their created date.

This does not work:
`/api/Posts?filter[include]=categories&filter[where][categories]=food`

This works but posts are not ordered by their created date:
`/api/PostCategories/food/posts?filter[order]=createdAt DESC`

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
