### ISSUE TITLE
Cannot use isomorphic client in nw.js or electron.js. Shows "Cannot set 'Title' of undefined" error

### ISSUE THREAD

**Issue by acao** [strongloop/loopback#1603]
This seems to be an issue for a lot of folks using nw.js or electron.js.

See https://github.com/strongloop/loopback/issues/961#issuecomment-131990658 for the solution to the problem.

Pay mind to the way that the offline sync example bundles the client first:

https://github.com/strongloop/loopback-example-offline-sync/blob/master/client/lbclient/build.js

Our runtimes allow us to just try and require() or import the file without bundling first, which causes a failure in loopback-boot, thus why folks with only the desktop node runtimes are having this issue.

Please tag this as 'support' or something of the like, as my intention is for it to be a waypoint for other befuddled node.js desktop framework developers.

**Comment by jannyHou** [comment]
hey @acao thanks for your [solution](https://github.com/strongloop/loopback/issues/961#issuecomment-131990658)! 
I will label it and people who also google this question can see the solution for it!
