### ISSUE TITLE
Memory leak when using more than one worker in production

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback#1604]
`slc run --cluster 1` runs fine, with a completely flat memory usage.
`slc run --cluster 2` has a minor memory leak

![image](https://cloud.githubusercontent.com/assets/390817/9330550/6fa89e4e-45ba-11e5-8fb4-a46ac7faa199.png)

`slc run --cluster 4` introduces a even faster memory drain.

**Comment by superkhau** [comment]
Can you try scaffolding a new project and running it with the settings above? Then provide a link to a test project on GitHuh so I can try to reproduce it on my end? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by superkhau** [comment]
@kennethlynne Not sure if you're still running into this issue, but please post at https://github.com/strongloop/strongloop/issues for `slc` related issues. Closing.
