### ISSUE TITLE
Make it easier to understand ACL 

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1606]
- Create a simple DSL / syntax for defining access controls as a string. Something like

```
ALLOW $everyone READ
```
- Remove complex extension / allow extended models to override ACL

**Comment by bajtos** [comment]
Sounds good to me! :+1:

**Comment by taoyuan** [comment]
+1

**Comment by superkhau** [comment]
+1

**Comment by shuckepco** [comment]
+1
Great idea!

**Comment by xangy** [comment]
+1
