### ISSUE TITLE
Add Meteor to loopback.io comparison

### ISSUE THREAD

**Issue by tenzan** [strongloop/loopback#1607]
Hello!

Will add Meteor to here ?
http://loopback.io/resources/#compare

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
I'd be happy to add it, but would need assent (and probably help) from @ritch @ijroth @chandadharap .

**Comment by tenzan** [comment]
+1

**Comment by crandmck** [comment]
Created https://github.com/strongloop/loopback.io/issues/25.  Closing this in favor of it.
