### ISSUE TITLE
Delete some property of the request body doesn't work

### ISSUE THREAD

**Issue by onnoll** [strongloop/loopback#1608]
I tried the next sentences and no work ("grant" is the property I'm trying delete)
```
User.beforeRemote('prototype.__create__guides', function(ctx, user, next) {
  ...
  // I tried these
  delete ctx.req.body.grant; // not working
  delete ctx.args.data.grant; // not working
  ...
```

**Comment by h2non** [comment]
`http.IncomingMessage` fields are not processed in the data model phase (to do that it should be done at middleware level).

It works with the following (note that using I'm `lodash` to clone and omit certain properties):
```js
User.beforeRemote('prototype.__create__guides', function (ctx, user, next) {
  ctx.args.data = _.omit(ctx.args.data, 'grant')
  next()
})
```

**Comment by superkhau** [comment]
@onnoll Hav eyou tried @h2non's solution? Is this issue good to close?

**Comment by Nivl** [comment]
I have the same issue, @h2non solution didn't work for me.

**Comment by mrbatista** [comment]
When create related model, ctx.args.data is a model instance. For delete property use mdelInstance.unsetAttribute(propertyName).

**Comment by mrbatista** [comment]
@Nivl @h2non @onnoll see [this](https://github.com/mrbatista/loopback-ds-readonly-mixin/blob/master/lib/read-only.js) for more informations.

**Comment by superkhau** [comment]
Are you guys still running into this issue? Can I close this?

**Comment by Nivl** [comment]
@mrbatista solution was good for me.

**Comment by superkhau** [comment]
Cool. Gonna close this. Please open a new issue if you are still running into problems.
