### ISSUE TITLE
The quest for a better User.login

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#161]
While implementing client SDKs consuming the new ACL/Auth features, we have found that client apps usually need to get details of the currently logged in user. At the moment, clients have to send two requests: User.login and User.get.

We should modify User.login so that it optionally adds the user data to the response.
#### Objectives
1. Backwards compatibility. `/users/login` should return the same response as before this change.
2. Opt-in scheme. Clients have to explicitly request the inclusion of user data.

/to @raymondfeng @ritch @Schoonology let's discuss what's the best solution. I'll describe few of them in a comment.

**Comment by lukewendling** [comment]
So, if I want to get the user from the access token, I should use ``` accessToken.__data.user``` ?

**Comment by HarisHashim** [comment]
I have the same question. Using `accessToken.__data.user` as in 

``` console.log("User: %j", accessToken.__data.user);```

Did give me the json for user. But why not  `accessToken.user` ?

**Comment by rahulrsingh09** [comment]
@bajtos @ritch Loopback says include.toLowerCase is not a function\

**Comment by bajtos** [comment]
@lukewendling @HarisHashim 

> But is there better or less hackish way to do this instead of accessToken.__data.user ?

I think if the related user data has been already stored in `accessToken.__data.user`, then you may be able to retrieve it by calling `accessToken.user()`. I am not sure though. Let's move this discussion to #165 please.

@rahulrsingh09
> Loopback says include.toLowerCase is not a function\

I am afraid I have no idea what you are writing about. Please open a new issue and provide us with enough details to reproduce the problem you are encountering, see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
