### ISSUE TITLE
Inadequate documentation of how to set response headers in custom remote methods

### ISSUE THREAD

**Issue by immo-huneke-zuhlke** [strongloop/loopback#1611]
I have been staring at https://strongloop.com/strongblog/whats-new-in-the-loopback-node-js-framework-june-2015/ (section: "Header and Status Argument Targets") and https://docs.strongloop.com/display/public/LB/Remote+methods (section: "Argument Descriptions") until I am blue in the face, but whatever I do I cannot seem to set the Content-Type header of my response correctly.

The particular remote method accepts an XML payload and sends an XML response, so I need to set the Content-Type header to "application/xml". Here are the options of my remoteMethod definition:
```
{
    http   : {path: '/xyzzy', verb: 'post', status: 201},
    accepts: [
        {arg: 'ctx', type: 'object', http: {source: 'context'}}
    ],
    returns: [
        {arg: 'response', type: 'string', root: true},
        {arg: 'contentType', type: 'string', http: {target: 'header', header: 'Content-Type'}}
    ]
}
```

And here is how I try to invoke it (where myXmlResponse is a complete XML body, including the <?xml...> line at the top):
```
return cb (null, myXmlResponse, 'application/xml');
```

The result is an exception thrown by Express:
```
TypeError: invalid media type
    at Object.parse (.../node_modules/express/node_modules/content-type/index.js:128:11)
    at setCharset (.../node_modules/express/lib/utils.js:268:28)
    at ServerResponse.send (.../node_modules/express/lib/response.js:163:32)
    at ServerResponse.json (.../node_modules/express/lib/response.js:249:15)
    at HttpContext.done (.../node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:565:13)
etc.
```

I can bodge the code to make it work, by omitting the third argument to the callback and instead setting the content-type header explicitly like this before invoking the callback:
```
ctx.res.set ('Content-Type', 'application/xml');
```

However, this seems extremely inelegant. Any better suggestions?

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
@immo-huneke-zuhlke If all your REST endpoints will send/receive XML, then you should follow the instructions in the FAQ [Can an application respond with XML instead of JSON?](https://docs.strongloop.com/display/LB/LoopBack+FAQ#LoopBackFAQ-CananapplicationrespondwithXMLinsteadofJSON?)   You may also want to look at the `rest.xml` and `rest.supportedtypes` properties in [config.json](https://docs.strongloop.com/display/LB/config.json).
Setting those properties

If it's just the remote method that needs to use XML, then I'll have to look into it.

**Comment by crandmck** [comment]
@immo-huneke-zuhlke I'm going to go ahead and close this issue.  If you feel that the docs need some specific additions or clarification, please re-open with pertinent details.  Thanks.

**Comment by immo-huneke-zuhlke** [comment]
I found that if you set both Content-type and Accept headers on the HTTP request to "text/xml" or "application/xml", then the correct Content-type header is automatically put on the HTTP response.

Moreover, you might consider documenting the fact that it's possible to provide your own XML encoder, which provides a lot greater flexibility. What I now do is this:
```
            var xmlResponder = {
                STATUS: 0,
                toXML: function () {
                    return '<?xml version="1.0" encoding="utf-8"?>\r\n' +
                        '<ANSWER>\r\n' +
                        '  <STATUS>' + this.STATUS + '</STATUS>\r\n' +
                        '</ANSWER>\r\n';
                }
            };
...
                        xmlResponder.STATUS = 20; // Bad Request
                        return cb (null, xmlResponder);
```
I also use express-xml-bodyparser to decode the incoming request body instead of relying on loopback, because I wasn't able to find a way to specify that the request body was XML instead of JSON for this one remote method (all the others are JSON).
