### ISSUE TITLE
Support returning promises in registerResolver instead of using "done" callback

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback#1612]
As in title, this would be a great alternative.

**Comment by superkhau** [comment]
Would you like to submit a pull request?

**Comment by ritch** [comment]
The offending line: https://github.com/strongloop/loopback/blob/06cece038ec39db1fd61184aef3a9a0ca2140d3a/common/models/role.js#L295

Also added to the promise support issue: https://github.com/strongloop/loopback/issues/418

**Comment by bajtos** [comment]
Relabelled as "Beginner Friendly" + "Feature".

@gausie I am afraid this particular issue is not very high in our list of priorities, would you mind contributing the improvement yourself? See https://github.com/strongloop/strong-remoting/commit/a7f5d12c0129932236cfcc7dc6fb824edf40d8a4 for inspiration.

**Comment by gausie** [comment]
Yeah I'll take a look into it, I understand that it's not super important.

**Comment by superkhau** [comment]
@jannyHou Reassigning to you as this may be related to the promise work you're doing.

**Comment by jannyHou** [comment]
@superkhau Thank you I am choosing the model to be promisified next, then I will take `Role`.

**Comment by jannyHou** [comment]
@gausie @bajtos @superkhau @ritch I am trying to implement this feature but got confused by it's requirement, could anyone take a look? Thanks a lot:

From my understanding promisify means a function either executes the callback or create a promise then return the promise, like:
```js
myFunction(param1, param2, callback) {
  callback = callback || createPromise();
  callback;
  return callback.promise;
}
```
So I feel reasonable to promisify functions in model `Role` like:
[Roles.isOwner](https://github.com/strongloop/loopback/blob/88d41f84fd8eac997a31388ccdbd3ce026ab0dfe/common/models/role.js#L177)
[Roles.isInRole](https://github.com/strongloop/loopback/blob/88d41f84fd8eac997a31388ccdbd3ce026ab0dfe/common/models/role.js#L279)
[Roles.getRoles](https://github.com/strongloop/loopback/blob/88d41f84fd8eac997a31388ccdbd3ce026ab0dfe/common/models/role.js#L370)

But I am confused with how to promisify [registerResolver](https://github.com/strongloop/loopback/blob/88d41f84fd8eac997a31388ccdbd3ce026ab0dfe/common/models/role.js#L126)

```js
Roles.registerResolver(role, resolver) {
    The resolver function is defined by user, and from the doc, 
    it only supports signature resolver(role, context, callback),
    Does promisify means we also need to support resolver(role, context).then(next)?
}
```

**Comment by ritch** [comment]
```js
// an example resolver
function myResolver(role, ctx, cb) {
  return myPromise; // ignore cb
}

// support promise and callbacks
var promise = myResolver(role, ctx, done);
if (isPromise(promise)) {
  promise
    .then(done)
    .catch(done);
} else {
  // the resolver will call done
}
```

**Comment by ritch** [comment]
> But I am confused with how to promisify [registerResolver]:

Don't promisify registerResolver, just support the resolver returning a promise here:

https://github.com/strongloop/loopback/blob/06cece038ec39db1fd61184aef3a9a0ca2140d3a/common/models/role.js#L295

**Comment by jannyHou** [comment]
@ritch thank you I got it:)

**Comment by bajtos** [comment]
@jannyHou @gausie Here is a quick outline of a possible implementation:

```js
    if (resolver) {
      debug('Custom resolver found for role %s', role);
      var result = resolver(role, context, callback);
      if (result && typeof result.then === 'function') {
        result.then(function() { next(); }, next);
      }
      return;
    }
```

See also how we allowed remote hooks and remote methods to return a promise instead of calling the callback: https://github.com/strongloop/strong-remoting/commit/a7f5d12c0129932236cfcc7dc6fb824edf40d8a4

**Comment by jannyHou** [comment]
Pr merged. I am closing it now. Will merge it and another doc pr into 2.x branch ASAP
