### ISSUE TITLE
Feature: automatically remove non-property data prior to persistence

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback#1613]
In many workflows, client-side resources will be mutated in ways that introduce properties other than those present in their server-side model definitions. For example, a Company instance which normally only has string properties Name and Street may be assigned helper-properties such as Selected, Priority, etc, before an operation such as $save() in the AngularJS SDK (for example) is called.

The problem is that Loopback, by default, saves these properties to persistent storage, at least on MongoDB. This can be worked around by writing manual filter operations in operation hooks, but this rapidly becomes tedious and difficult to maintain if model definitions change over time.

It would be great if there was a single option telling Loopback to delete all properties which are not explicitly defined in the Models JSON file, before any instances are persisted.

**Comment by h2non** [comment]
For now it seems like you have to do it manually, for instance, inside a hook. See #1608

**Comment by johnsoftek** [comment]
https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Top-levelproperties
 
The strict option should do what you want. It is false by default for MongoDB; true by default for SQL databases.

**Comment by csvan** [comment]
@johnsoftek is right, this options does exactly what I was looking for, though I don't understand why it is false by default on MongoDB. Closing this.

**Comment by johnsoftek** [comment]
@csvan In many situations, MongoDB is used without a schema definition. I guess Loopback is reflecting that norm.
