### ISSUE TITLE
(mongoDB) How to filter elemMatch in Fields output 

### ISSUE THREAD

**Issue by buithanh82** [strongloop/loopback#1615]
How to fetch correct element in array output from find() command in loopback?

**Comment by superkhau** [comment]
Please see https://docs.strongloop.com/display/public/LB/Fields+filter. For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
