### ISSUE TITLE
Swagger Error: Type is Undefined

### ISSUE THREAD

**Issue by ianseyer** [strongloop/loopback#1617]
Attempting to run `DEBUG=loopback node .` after pulling a live, functional copy from Heroku and `npm install`ing yields no errors.

However, going to `/explorer` yields a list of my models, but each list does not expand into anything as if nothing is present.

![screen shot 2015-08-22 at 12 34 30 pm](https://cloud.githubusercontent.com/assets/4384951/9425127/6c8eb9ba-48ca-11e5-9335-472b1e2e3001.png)

Those are the in-browser errors.

It says it is a Swagger error, but I suspect it might be something else.

**Comment by framp** [comment]
Check your models' properties

Chances are that some of the properties are wrong.
It happened to me as well after I ran the the scaffolding tool and it messed up some properties, completely unrelated models.

I had a property with:
```
 type: {
   type: {
    "string"
  }
}
```
or something similar.

**Comment by richardpringle** [comment]
Hey @ianseyer, did you manage to resolve your issue? If not can you follow [steps to reproduce your issue](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) and I'll see if I can help!

**Comment by raymondfeng** [comment]
`type` is a keyword for the model definition. You can work around it using a different name, such as:
```
type: {
   xType: {
    "string"
  }
}
```
We could add support for escaped type, such as `$type`.
