### ISSUE TITLE
Changes made in afterRemote hooks are discarded

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#162]
Consider the following hook:

``` js
User.afterRemote('**', function(ctx, result, next) {
  delete result.password;
  result.newProp = 'new-value';
  result.email = 'modified:' + result.email;
  next();
});

// Result of POST /users
{
  password: '$2a$10$6Ck1zg3NgKLrsRHelaV9MuwwbOFbfxVnSccTcWvODRAC16c85/r0i',
  email: 'modified:foo@foo.com',
  credentials: [],
  challenges: [],
  id: 1 
}
```

In other words, `password` property was not removed, `newProp` was not added, only the modification of an existing property was applied.

Partial workaround based on the internal details of ModelBaseClass:

``` js
user.afterRemote('**', function(ctx, result, next) {
  delete result.__data.password;
  result.__data.newProp = 'new-value';
  result.email = 'modified:' + result.email;
  next();
});

// Result of POST /users
{
  password: null,
  email: 'modified:foo@foo.com',
  credentials: [],
  challenges: [],
  id: 1,
  newProp: 'new-value'
}
```

Related and/or affected issues: #160, #161.

/cc @raymond @ritchie

**Comment by ulion** [comment]
It seems "delete result.field" still not affect the final response?

**Comment by bajtos** [comment]
AFAIK, you need to call `result.unsetAttribute('field')` for that.

**Comment by ulion** [comment]
Thx for the tip, hope it can be put on the remote hook doc.

**Comment by bajtos** [comment]
> Thx for the tip, hope it can be put on the remote hook doc.

/cc @crandmck

**Comment by sachinhub** [comment]
I have a remote hook as follows -

Model.afterRemote ('**', function (ctx, result, next){
   console.log ('afterRemote hook called.');

   next ();
});

This hook gets called when GET is invoked from /explorer. However when a Model.find ({}) is executed from unit test case, the above hook is not getting called.

Any inputs on why remote hooks are not getting called when find is executed in unit tests?

**Comment by darior87** [comment]
Have this problem on remote hook intercepting a relationship get call.

```Band.afterRemote('**.__get__proposals',function(ctx,inst,next) {
      //i.e. inst = {};
      inst.concert(function(err, concert){
          inst = {concert : concert};
          next(null,inst);//the same with next();
        }
      });
}```

when I'm getting this relationship I have the `{}` json as return as I'm expecting `{concert:concert} `

**Comment by darior87** [comment]
it works by replacing the result in the context

ctx.result = {concert:concert};

before the next(); to be called

**Comment by kartsims** [comment]
Just found out this old issue and definetely :+1:  to @ulion : the `unsetAttribute` method should go in the doc regarding `afterRemote` hook

**Comment by bajtos** [comment]
> Just found out this old issue and definetely 👍 to @ulion : the unsetAttribute method should go in the doc regarding afterRemote hook

@kartsims would you like to contribute that improvement yourself? Here are the instructions to get you started: http://loopback.io/doc/en/contrib/doc-contrib.html
