### ISSUE TITLE
Replace or edit a remote method

### ISSUE THREAD

**Issue by framp** [strongloop/loopback#1625]
I'm looking for a way to replace a remote method 

```
export default function(Model) {
  const methods = [
    "create",
    "findById",
    "find",
    "deleteById",
    "updateAttributes",
    "login",
    "logout",
    "confirm",
    "resetPassword"
  ];
  process.nextTick(() => {
    Model.sharedClass.methods().forEach((method) => {
      if ((method.name === "create" || 
          method.name.substr(2, 6) === "create") && 
          method.http) {
        method.http.status = 201;
      }
      if (method.name.substr(2, 8) === "findById") {
        method.accepts.push({ 
          arg: 'filter',
          type: 'object',
          description: 'Filter defining fields and include' 
        });
        //Not sure what to do here
      }
      method.shared = methods.indexOf(method.name) > -1;
    });
  });
}
```

There are a couple of issues:
 - Setting the `method.http.status` is working for `create` but not for remoteMethods like `__create__resources`. In the example I'm trying to set the status code to 201 for create requests.
 - I'm not sure what the best idea to replace a remote method. Here I'm trying to add filter support to the remote findById method

Any help will be greatly appreciated

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
