### ISSUE TITLE
Grunt to gulp

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1626]
Let's refactor our gruntfile using gulp. 

/cc @bajtos

**Comment by superkhau** [comment]
+1

**Comment by hacksparrow** [comment]
Totally agree. I'd say that for the example apps too, grunt is just too slow and its config file cumbersome.

**Comment by BerkeleyTrue** [comment]
Yes! Finally!

**Comment by bajtos** [comment]
To be honest, I don't really care. If we have somebody willing to contribute the change then I am fine with landing it.

**Comment by ritch** [comment]
> its config file cumbersome

Yeah... its really hard to understand what is going on. Gulp isn't perfect, but IMO its substantially easier to maintain.

**Comment by superkhau** [comment]
>...its substantially easier to maintain.

+1

**Comment by pmoelgaard** [comment]
+1
