### ISSUE TITLE
why is eslint in both dependencies and devdependecies in package.json for strongloop?

### ISSUE THREAD

**Issue by smartmouse** [strongloop/loopback#1627]
Why is eslint in both dependencies and dev dependencies in your package.json?
Is it because you need different versions? One for production environment and one for your test environment?

Are there any recommended best practices?

**Comment by raymondfeng** [comment]
It should be deduped. Which module has it?

**Comment by smartmouse** [comment]
in the strongloop package.json

 "dependencies": {
    "async": "^0.9.0",
    "debug": "^2.1.0",
    "eslint": "^0.24.1",

  "devDependencies": {
    "eslint": "^0.21.0",
    "jscs": "^1.11.3",
    "tap": "^1.3.1"
  },

**Comment by superkhau** [comment]
Can you link to the GitHub repo?

**Comment by superkhau** [comment]
I only see one eslint in devDeps in the strongloop repo: https://github.com/strongloop/strongloop/blob/master/package.json#L102

**Comment by ritch** [comment]
Closing for now... I don't see the duplicate entry.
