### ISSUE TITLE
MongoDB: Queries against Model without instantiated collection hangs

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback#1634]
Say you have defined some model named MyModel. Normally, when you invoke a `Write` method (`create` etc) for this model, Loopback will create the corresponding MongoDB collection in conjunction with this. This can be verified by inspecting the database from the Mongo shell after Loopback has started - no collections will be present for models who have not yet had instances created for them.

However, this does not seem to be true for `Read` (`find` etc) operations. Instead, trying to execute a Read operation before any Writes have been done causes the request to stall until it times out. There are no errors raised whatsoever.

**Comment by raymondfeng** [comment]
I cannot reproduce the problem locally. After dropping a collection, `find()` works fine and returns `[]`. Can you provide a test case and steps to reproduce the problem?

**Comment by loay** [comment]
Hi @csvan Closing the issue due to inactivity. If you are still experiencing the same issue, please leave a comment and I will re-open the case. Also, please provide a test project to reproduce the issue as per the previous comment. Thanks.
