### ISSUE TITLE
MongoDB: Can't canonicalize query on hasManyThrough#add()

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback#1635]
I have the models `Task` and `Activity`, which are in a hasManyThrough relationship via model `TaskActivity`. The relevant relations definitions are below:

Activity:

```
    "tasks": {
      "type": "hasMany",
      "model": "Task",
      "foreignKey": "activityId",
      "through": "TaskActivity"
    },
```

Task:

```
    "activities": {
      "type": "hasMany",
      "model": "Activity",
      "foreignKey": "taskId",
      "through": "TaskActivity"
    }
```

TaskActivity:

```
    "task": {
      "type": "belongsTo",
      "model": "Task",
      "foreignKey": "taskId"
    },
    "activity": {
      "type": "belongsTo",
      "model": "Activity",
      "foreignKey": "activityId"
    }
```

Given that I have some previously created instances of both Activity and Task, running `task.activities.add(activity` for some existing instances `task` and `activity` currently fails with the following error:

```
{ [MongoError: Can't canonicalize query: BadValue unknown operator: $name]
  name: 'MongoError',
  message: 'Can\'t canonicalize query: BadValue unknown operator: $name',
  '$err': 'Can\'t canonicalize query: BadValue unknown operator: $name',
  code: 17287 }
```

**Comment by masalinas** [comment]
Do you know what is the error? I have the same problem

**Comment by raymondfeng** [comment]
Can you track down what MongoDB command is sent using `DEBUG=loopback:connector:mongodb node .`?

**Comment by masalinas** [comment]
I resolve the problem with other way, first query the organization from id and adding the new administrator to this organization with this code:

Organization.findById(credentials.organizationId, function(err, organization) {
            if (err) return cb(err);

            console.log('Organization: find is:', organization.name);

            organization.administrators.create(credentials.administrator, function(err, administrator) {
                if (err) return cb(err);

                console.log('administrator ' + administrator.name + ' registered');

                // return administrator created
                cb(err, administrator);
            });
        });

but I would like to know if is possible link a organization with a administrator in only one procedure and not with two that I used.

Regards.
