### ISSUE TITLE
Unable to impersonate authenticated user from remote method

### ISSUE THREAD

**Issue by simonguest** [strongloop/loopback#1636]
I have a model that implements an ACL so that access is restricted to authenticated users:

```
{
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
}
```

I am trying to create a remote method called public that returns a subset of this data, available for public viewing. I have defined it as follows:

```
  Car.public = function (code, cb) {
    Car.find({where: {code: code}}, function (err, instance) {
      // logic goes here to determine whether the instance is for public consumption
      cb(err, instance);
    });
  };

  Car.remoteMethod(
    'public',
    {
      http: {path: '/public/:code', verb: 'get'},
      accepts: {arg: 'code', type: 'string', http: {source: 'path'}},
      returns: {root: true, type: 'array'}
    }
  );
```

I have defined an ACL to let public users access the remote method:

```
{
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "public"
}
```

However the lookup fails as the underlying 'find' implementation for the model is restricted to authenticated users only (as it should be).

Is there a way of creating a public remote method that has the ability to impersonate a particular user/role or make calls into the model bypassing the default ACLs? If not, should there be?

**Comment by loay** [comment]
Would it be possible to provide a link for the repo so I can reproduce the error where it fails?
Thanks

**Comment by loay** [comment]
Hi @simonguest 

Did you have a look at this part here: Read-Only endpoints example in the following document. 

https://docs.strongloop.com/display/public/LB/Authentication%2C+authorization%2C+and+permissions

is that what you are looking for? If not, would it be possible to provide more info a repo so I can reproduce your issue? Thanks.

**Comment by simonguest** [comment]
Hi @loay - give me a couple of days, and I'll setup a test repo that demonstrates the current behavior. Thanks!

**Comment by loay** [comment]
Hello, Is this issue still persisting? 
If you are still having troubles with the same issue, please leave a comment and I will re-open the issue. Thanks.
