### ISSUE TITLE
validateUniquenessOf allows non-unique values

### ISSUE THREAD

**Issue by dgitsio** [strongloop/loopback#1637]
We create a model and enable ```validateUniquenessOf``` for one of the properties, e.g.:

```javascript
module.exports = function(Site) {
  Site.validatesUniquenessOf('domain', {message: 'Domain already exists'});
};
```
But notice that callers can still create multiple objects with the same value for that property when passing an array of data argument objects:

```javascript
 Site.create([
  {domain: 'shouldbeunique.com'},
  {domain: 'shouldbeunique.com'}
],
//...
```

Or using something like ```async.parallel```:

```javascript
      for (var i=0; i <= 1; i++) {
        creations.push(function(cb) {
          Site.create({domain: 'shouldbeunique.com'}, function(err, site) {
            if (err) {
              cb(err);
              return;
            }
            cb();
          });
        });
      }

      async.parallel(creations, function() {
        Site.find(function (err, sites) {
          if (err) throw (err);
          console.log(sites);
          done();
        });
      });
```

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by dgitsio** [comment]
Yes!  Please see:

https://github.com/dgitsio/loopback-sandbox

Thanks in advance.

**Comment by superkhau** [comment]
Verified. Escalating to `bug` status.

**Comment by dgitsio** [comment]
Maybe a dupe of #1452.

**Comment by superkhau** [comment]
I think so, let's close this and track it over there.
