### ISSUE TITLE
Rename faq example repos

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1638]
Rename `loopback-faq-*` to `loopback-example-*` to align with the naming scheme of other example repos:
- [x] [loopback-faq-email](https://github.com/strongloop/loopback-faq-email)
- [x]  [loopback-faq-middleware](https://github.com/strongloop/loopback-faq-middleware)
- [x]  [loopback-faq-operation-hooks](https://github.com/strongloop/loopback-faq-operation-hooks)
- [x]  [loopback-faq-rest-connector](https://github.com/strongloop/loopback-faq-rest-connector)
- [x]  [loopback-faq-user-management](https://github.com/strongloop/loopback-faq-user-management)

**Comment by crandmck** [comment]
This work is done. Simon, could you please review and close this...?

**Comment by superkhau** [comment]
LGTM, GJ with updating `loopback-example` even thought it wasn't mentioned on this issue. ;)
