### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by h2non** [strongloop/loopback#1639]
I'm pretty sure you already thought about this for a while, however I guess it worth to mention it again since it will be particularly useful in the context of a framework. Also for testing simplifies the things.

I found it very handy especially for models and remote methods, where they might look like this:

``` js

  User.followers = function (userId, $req, $app, $UserFollowsModel, next) {
    var data = { where: { toUser: userId } }
    UserFollowsModel.find(data, next)
  }

  User.remoteMethod('followers', {
    returns: { root: true },
    accepts: { arg: 'id', type: 'string', required: true },
    http: {
      path: '/:id/followers',
      verb: 'GET',
      status: 200,
      errorStatus: 400
    }
  })
```

There're a [bunch](https://www.npmjs.com/search?q=dependency+injection) of packages that can suit properly, or may be writing [your own](https://github.com/h2non/injecty) DI container is also simple.
I'd vote take some inspiration from [Angular DI](https://github.com/angular/di.js/), they've done well.

**Comment by raymondfeng** [comment]
Yeah, it's always on our radar. There are quite a few interesting use cases (including the one you illustrate) that requires some sort of DI. We'll evaluate it as part the next major release.

**Comment by Porrni** [comment]
+1

**Comment by yellowred** [comment]
+1, any updates so far?

**Comment by simoami** [comment]
+1
