### ISSUE TITLE
Implement loopback-example-component

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1642]

**Comment by doublemarked** [comment]
Hey @ritch - I'm quite curious about what will come out of this, as there are a number of things we're doing that would benefit from some formalization around components. I've looked through the code of the existing documented components (https://docs.strongloop.com/display/LB/LoopBack+components) but have found that the actual implementation of all of these are different (though a bit similar).

Has there been any talk about making a more configuration-oriented mechanism for integrating/activating components into LB? Something like how the mixins work, for instance.
