### ISSUE TITLE
upsert doesn't return auto id

### ISSUE THREAD

**Issue by oscar-espada** [strongloop/loopback#1643]
The upsert() method, in case of insert, doesn't return the auto id value. I'm using MySQL.
The documentation says the callback gets the "updated model instance":
https://apidocs.strongloop.com/loopback/#persistedmodel-upsert

Is it possible that in case of insert the callback gets the auto id value?

**Comment by davidcheung** [comment]
Would you be able to provide a [sample repo](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) for me to reproduce the issue. Thanks

**Comment by davidcheung** [comment]
Cleaning up stale issues, please [reopen](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) if this issue still persist, thanks!
