### ISSUE TITLE
Document loopback app and strongloop tooling deployments for Google

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback#1644]
Who can I speak to for contributing here:
<img width="259" alt="screen shot 2015-09-03 at 5 54 26 pm" src="https://cloud.githubusercontent.com/assets/821963/9672976/1dc02ec8-5265-11e5-8869-0659d3e16a08.png">

I've a bit of experience deploying our loopback app to GCE/GCP: https://github.com/ShoppinPal/gcp-scripts/wiki

**Comment by davidcheung** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Hi @pulkitsinghal I can certainly help you with the logistics, but I will need to get approval from @chandadharap before adding this.  She is on vacation now, but I'll try to get a moment of her time to discuss this when she returns.

**Comment by crandmck** [comment]
@pulkitsinghal I created https://docs.strongloop.com/display/SL/Google+Cloud+Platform where you can add your content.  NOTE: You must be logged in to the Confluence wiki to see this page.  Let me know if you need any help editing.

Here is some basic info:
- https://docs.strongloop.com/display/LB/Translating+documentation
- https://docs.strongloop.com/display/LB/Contributing+to+LoopBack+documentation
