### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by henryzp** [strongloop/loopback#1646]
fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz

**Comment by superkhau** [comment]
Are you still running into this issue? Can you provide the steps to reproduce this?

**Comment by lozery** [comment]
`react-native init AwesomeProject`，and then :

```
fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz
npm ERR! fetch failed http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```
and no resource found when click [http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz](http://registry.cnpmjs.org/esprima-fb/download/esprima-fb-3001.1.0-dev-harmony-fb.tgz)

**Comment by superkhau** [comment]
What version of NPM are you using?

**Comment by lozery** [comment]
npm v3.3.3 and v3.3.4
node v4.1.0

**Comment by superkhau** [comment]
@lozery Is this related to LoopBack?

**Comment by superkhau** [comment]
Closing as this appears to be unrelated to LoopBack. Feel free to comment again if you disagree and I will reopen the issue.
