### ISSUE TITLE
JSON Model

### ISSUE THREAD

**Issue by groupsvkg** [strongloop/loopback#1647]
Hi Team,

After so many trials i am unable to create model json schema for below json instance

```json
{
  "k1": {
      "k2": "v2",
      "k3": "v3",    // here k3 is ID
      "k4": "v4"
  }
}
```
=====================
JSON Model definition i have come up with is as below.
```json
{
  "name": "test",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true,
    "idInjection": false
  },
  "http": {
    "path": "/test1/test2"
  },
  "properties": { 
    "k1": {
            "k2": {
                "type": "string",
                "required": true
            },
            "k3": {
                "type": "string",
                "id": true,
                "required": true
            },
            "k4": {
                "type": "string",
                "required": true
            }
        }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```
Need help.

Regards,

**Comment by superkhau** [comment]
What database are you using? Are you trying to embed an object into a property? See https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations.

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
