### ISSUE TITLE
Where filter explanation

### ISSUE THREAD

**Issue by jorgeramos** [strongloop/loopback#1648]
Please explain how I should structure the query based on some condition on a related model. Given the FlightReservation and FlightModel below, I would like to search all FlightReservation where the flightReservation.flight().kind == 'D'

### Would like to filter the equivalent of this
```javascript
FlightReservation.find({
  where: {
    flight: {
      kind: 'D'
    }
  }
})
```

### FlightReservation
```json
{
  "name": "FlightReservation",
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "relations": {
    "flight": {
      "type": "belongsTo",
      "model": "Flight",
      "foreignKey": ""
    }
  }
}
```

###  Flight
```json
{
  "name": "Flight",
  "properties": {
    "kind": {
      "type": "string"
    }
  }
}
```
*btw, my real models have a lot more properties, I'm just showing the bare minimum here to explain what I'm looking for...*

**Comment by superkhau** [comment]
Create a relation between `FlightReservation` and `Flight`, then query your data through the relation:

```
FlightReservation.flight.find({
  where: {
    kind: ...
  }
}
```
 
`...` can be a like filter or a regex filter depending on your use case. See https://docs.strongloop.com/display/public/LB/Where+filter for more info.

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by jorgeramos** [comment]
This is not the case... I understand how to query on a field using regex
etc.. as per the reference info. The problem is that I cannot filter based
on the property of a related model.


---
Jorge Ramos
305-281-6051
