### ISSUE TITLE
beforeRemote hooks on related object methods not executing at correct point

### ISSUE THREAD

**Issue by akshayrangnekar** [strongloop/loopback#1649]
I'm new to loopback so apologies if this is a stupid question.

I've defined my own User model, with a relationship to a Device class:

```
{
  "name": "LocTocUser",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "hidden": [
    "oauthToken"
  ],
  "properties": {
    "provider": {
      "type": "string",
      "required": true
    },
    "providerId": {
      "type": "string",
      "required": true
    },
    "oauthToken": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "devices": {
      "type": "hasMany",
      "model": "Device",
      "foreignKey": ""
    }
  },
  "acls": [
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    },
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "__create__devices"
    }
  ],
  "methods": {}
}
```

Device requires a field called dateCreated, and in the beforeRemote hook for Device.create I'm setting it without a problem (along with the locTocUserId). I want to do the same for the method on the LocToc user. I've got a beforeRemote hook in my User model method:

```
  LocTocUser.beforeRemote('prototype.__create__devices', function(context, user, next) {
    // console.log("HEREREHEHREHREHRERHEHRHE");
    var req = context.req;
    // console.log("Body is: " + JSON.stringify(req.body, null, 2));
    req.body.dateCreated = Date.now();
    // req.body.locTocUserId = req.accessToken.userId;
    console.log("POST beforeRemote" + JSON.stringify(req.body, null, 2));
    next();
  });
```

This seems to run fine, and the output is what I would expect on the command line: 

```
POST beforeRemote{
  "type": "android",
  "identifier": "happy3",
  "snsUrn": "joy3",
  "dateCreated": 1441611950109
}
```

But the client still gets a validation error saying that dateCreated is required. I'm assuming this means that the beforeRemote method is run too late, but that's just a guess.

**Comment by davidcheung** [comment]
Would you be able to provide a [sample repo](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) for me to reproduce the issue. Thanks

**Comment by davidcheung** [comment]
Cleaning up stale issues, please [reopen](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) if this issue still persist, thanks!

**Comment by dktan** [comment]
facing the same issue

**Comment by MarkAndrewJohnson** [comment]
@dktan it may or may not help you but I had this issue too but fixed it with an npm update on the loopback module.
