### ISSUE TITLE
Recommended Updated to Documentation

### ISSUE THREAD

**Issue by njcaruso** [strongloop/loopback#1654]
I was trying to hide some model APIs using the table 'Predefined remote methods' at this link:
https://docs.strongloop.com/display/LB/Exposing+models+over+REST

The table does not have an exhaustive list, so I would recommend you encourage the developer to review the source code of  `persisted-model.js`.

It does seem however that the below are common and should be added to your documentation:
* `updateAll`
* `createChangeStream`

Thanks,

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Thanks @njcaruso.

You're right, the table in that doc is not intended to be exhaustively complete.
However, you should not have to read the source code.  The [API documentation](https://apidocs.strongloop.com/loopback/#persistedmodel) is meant to be a complete reference to the Node API and [PersistedModel REST API](https://docs.strongloop.com/display/LB/PersistedModel+REST+API) should have a complete reference to the REST API.

I added `updateAll` and `createChangeStream` to [the table](https://docs.strongloop.com/display/LB/Exposing+models+over+REST#ExposingmodelsoverREST-Predefinedremotemethods) and I also linked the **Model API** column entries to the API docs.

Let me know if you have further suggestions.

**Comment by njcaruso** [comment]
perfect, thanks!
