### ISSUE TITLE
Allow filter fields on nested properties

### ISSUE THREAD

**Issue by rkmax** [strongloop/loopback#1655]
https://docs.strongloop.com/display/public/LB/Fields+filter

If I have example a location property composed by
- city
- state
- address
- zip

and I want show only city and state in the results

``` js
Person.find({
  fields: {
    id: true,
    location: {
      city: true,
      state: true
    }
  }
}, function(err, people){ ... })
```

this will returns the whole location property

**Comment by superkhau** [comment]
@raymondfeng Is this feature supported yet?

**Comment by GustavoRPS** [comment]
+1

**Comment by vko-online** [comment]
This would be very useful

    fields: {
        id: true,
        'user.id': false
     }

**Comment by FredericLeuba** [comment]
+1

**Comment by ebourmalo** [comment]
After some investigation, [this commit](https://github.com/strongloop/loopback-datasource-juggler/commit/e7a108efdb01783260c5176ea77f62bb7b09ac84) is in part responsible.

With the 2 blocks: 
```js
+  if (Array.isArray(options.fields)) {
 +    keys = keys.filter(function(k) {
 +      return (options.fields.indexOf(k) != -1);
 +    });
 +  }
```

It filters the fields (looking for the field `aaa.bbb.ccc` in the document and got only the first-depth field `aaa`) so it won't play well with nested fields. 

A right solution would be to check with lodash if the path `aaa.bbb.ccc` exists in the document, 
```js
options.fields = options.fields.forEach(k => {
  return _.has(data, k)
})
```

And use `_.get` to filter the returned data.

**Comment by erikverheij** [comment]
I think this is possible with the following syntax;

```javascript
Post.find({
  include: {
    relation: 'owner', // include the owner object
    scope: { // further filter the owner object
      fields: ['username', 'email'], // only show two fields
      include: { // include orders for the owner
        relation: 'orders', 
        scope: {
          where: {orderId: 5} // only select order with id 5
        }
      }
    }
  }
}, function() { /* ... */ });
```

http://loopback.io/doc/en/lb2/Include-filter.html

**Comment by gonzo09** [comment]
@rkmax I know it's been a while but did you find a way to soluce this ?
