### ISSUE TITLE
IBM acquisition and the future of Loopback

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback#1661]
First of all, a big congrats to everyone in Strongloop on the acquisition!! It is yet another testimony to the amazing work you have done and continue to do.

However, I would like to know if this will affect Loopback or the surrounding ecosystem in any way that would be detrimental to current, non-enterprise users. Specifically, is there any risk that the main Loopback distribution will be closed-sourced in the near future, or that certain upcoming features will only be offered to enterprise customers?

**Comment by raymondfeng** [comment]
@csvan Thank you! Check this out: https://strongloop.com/strongblog/ibm-express-loopback-node-js/?utm_source=StrongLoop+Newsletter&utm_campaign=db34b1e22a-August_2015_Newsletter4_6_2015&utm_medium=email&utm_term=0_5cdaff72d5-db34b1e22a-141033293

**Comment by csvan** [comment]
@raymondfeng no idea how I missed this, thanks!!
