### ISSUE TITLE
Logging all Loopback Calls

### ISSUE THREAD

**Issue by mayur-arora** [strongloop/loopback#1662]
Is there a way to log all calls originating from the  loopback layer to the backend system ? Logging requests to loopback is easy, but from loopback seems a bit tricky. I need to log REST calls in a file.

**Comment by superkhau** [comment]
You can log requests in your LoopBack application like any other Node.js app. I suggest looking up `fs.writeFile` in the Node.js docs to get an idea of how to write data to the filesystem.

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by mayur-arora** [comment]
@superkhau Thanks I actually have been writing data to file systems for the calls coming to loopback. What I am actually looking for a place in my code to log all calls. Basically, I want to log all operations  written in the data sources file.

**Comment by superkhau** [comment]
Try using an [operation hook](https://docs.strongloop.com/display/public/LB/Operation+hooks) and do the logging at the desired operation.
