### ISSUE TITLE
how to direct update user password? 

### ISSUE THREAD

**Issue by makersu** [strongloop/loopback#1664]
Hi:
how to direct update user password? 
I found User.resetPassword, but I'd like to update db directly.
Thank you very much.

**Comment by csvan** [comment]
You can use $save on your user model for this - if password is provided it is automatically hashed.

**Comment by superkhau** [comment]
@makersu Did @csvan solution work for you? Can I close this?

**Comment by makersu** [comment]
Many thanks.
