### ISSUE TITLE
Suggestion - login should ignore email casing

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback#1665]
Generally, it is safe to assume that email addresses are not case sensitive, even if the standard says they are (http://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive).

Loopback is currently case sensitive when it comes to checking email as a login credential, however. It would make sense to turn this off, since in reality any email should be considered unique, regardless of casing.

**Comment by superkhau** [comment]
Closing, duplicate of https://github.com/strongloop/loopback/issues/1150.
