### ISSUE TITLE
How to get current context path in loopback

### ISSUE THREAD

**Issue by bdqnghi** [strongloop/loopback#1671]
I have try many one to get the context path from the model.
Something like :    loopback.getCurrentContext();

But in that object there is nothing like the path. How can I get the context path of current http request?

**Comment by superkhau** [comment]
@bajtos ^

Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by bajtos** [comment]
@bdqnghi what are you trying to accomplish? what do you mean by "context path"? Please post a link to the loopbackjs forum thread so that I can follow up there.
