### ISSUE TITLE
updateall doesn't return count in remote connector

### ISSUE THREAD

**Issue by oscar-espada** [strongloop/loopback#1674]
The updateAll() method return in the info parameter of the callback the property "info.count" the "number of instances (rows, documents) updated" (https://apidocs.strongloop.com/loopback/#persistedmodel-updateall). I'm using MySQL and it works well.
But if I use the Remote Connector, I will get "undefined" into the info paramater of the callback.

**Comment by ritch** [comment]
Is this for a relation method?

**Comment by oscar-espada** [comment]
No, the model is a PersistedModel connected to a simple table.

**Comment by superkhau** [comment]
A fix is in the works at #1667.

**Comment by Amir-61** [comment]
@oscar-espada Could you please confirm if you still have the same issue? It seems this should have been solved by [this fix](https://github.com/strongloop/loopback/pull/1667)

Thanks!

**Comment by Amir-61** [comment]
Since this issue seems to be solved by this fix(https://github.com/strongloop/loopback/pull/1667) and no activities for a while, I'm closing this ticket.

Thanks!
