### ISSUE TITLE
Document how to override default scope

### ISSUE THREAD

**Issue by kennethlynne** [strongloop/loopback#1675]
We have implemented soft delete on a model, so it has a deletedAt property and a default scope excluding items with truthy deletedAt. But how can I override the default scope to actually find deleted data?

**Comment by kennethlynne** [comment]
```js
Content.find({where: {deletedAt: {neq: null}}}, ... );
```
does not seem to work

**Comment by raymondfeng** [comment]
We don't have the `unscope` support yet. The workaround is to define a similar model that points to the same collection/table and not expose it to REST.

**Comment by kennethlynne** [comment]
Thank you, I did everything, only missing one detail: How can I point it to the same collection?

**Comment by raymondfeng** [comment]
What DB do you use? For mongodb, you should add the following the model settings:

```
mongodb: {
  collection: 'myCollection'
}
```

**Comment by ritch** [comment]
> We don't have the unscope support yet. The workaround is to define a similar model that points to the same collection/table and not expose it to REST.

Hmm... I don't think `unscope` is really what we need. Contextual scoping is probably more useful.

**Comment by kennethlynne** [comment]
MongoDB, thanks!

**Comment by superkhau** [comment]
@kennethlynne Is this good to close?

**Comment by kennethlynne** [comment]
Well, it is not documented just yet, but my problem is solved yes! Thanks!

**Comment by superkhau** [comment]
@kennethlynne TY

@crandmck ^

**Comment by crandmck** [comment]
@superkhau It's unclear to me exactly what needs to be documented here.  Can you please clarify?

**Comment by kennethlynne** [comment]
To override it you have to create a second scopeless model, would be a nice
example

**Comment by superkhau** [comment]
@kennethlynne Can you please clarify what needs to be documented?

**Comment by kennethlynne** [comment]
In this exact case it was not clear how one could get access to deleted data. More abstract: How to override a models default scope. It should mention the current work around (creating a second model targeting the same table/collection).

**Comment by kennethlynne** [comment]
Our quick and dirty fix:

```js
var loopback = require('loopback');
var _ = require('lodash');

module.exports = function (Model) {
  // Workaround for https://github.com/strongloop/loopback/issues/1675#issuecomment-140481246
  // So that we can access deleted data
  var deletedModelName = 'Deleted' + Model.modelName;
  var deletedModelDefinition = _.cloneDeep(Model.definition);
  deletedModelDefinition.name = deletedModelName;
  delete deletedModelDefinition.scope; // Remove default scope that filters deleted items
  deletedModelDefinition.mongodb = {
    collection: Model.modelName // Target original model collection
  };

  loopback.createModel(deletedModelDefinition);

  Model.findDeleted = function (query, done) {
    var DeletedModel = Model.app.models[deletedModelName];
    DeletedModel.find(query, function (err, result) {
      if (err) {
        return done(err);
      }
      result = result || [];
      done(null, result.map(function (instance) {
        // Return model instances, not DeletedModel instances
        // Dereference original model
        return new Model(JSON.parse(JSON.stringify(instance)));
      }));
    });
  };

  Model.findDeletedById = function (id, done) {
    Model.findDeleted({where: {id: id}}, function (err, result) {
      if (err) {
        return done(err);
      }
      done(null, result[0] || null);
    });
  };
};

```

**Comment by crandmck** [comment]
OK, thanks.  I'll add this info to the docs -- it's in my work queue.

**Comment by Neil-UWA** [comment]
by setting default scope, it's impossible to update the deleted attribute to other values.....

**Comment by dbansch** [comment]
> What DB do you use? For mongodb, you should add the following to model settings:
> 
> ```
> mongodb: {
>   collection: 'myCollection'
> }
> ```

@raymondfeng How would I do this in db2?
