### ISSUE TITLE
order in model-config result in different model names when defining hasAndBelongsTo many relation

### ISSUE THREAD

**Issue by Neil-UWA** [strongloop/loopback#1677]
assume you have a model-config.json:
```javascript
case 1: 
{
  "item": {
    "datasource": "pg"
    "public": true
  },
  "tag": {
    "datasource": "pg",
    "public": true
  }
}
```
and the relation between item and tag model is hasandbelongs to many . By default, Loopback will create a third table named 'TagItem', However, when you reorder the model-config.json to 
```javascript
case 2:
{
  "tag": {},
  "item": {}
}
```
a new middle table will be created, named as 'ItemTag'.

Most of the time, people will not to reorder the model-config file. However, If I want to access  the tag model in /common/model/item.js in the first case, 
```javascript
var loopback = require('loopback');

module.export = function(Item) {
  var Tag = loopback.getModel('tag');
}
```

This will not work, since at this moment tag model hasn't been created yet, so I have to reorder model-config file by moving tag model on top of item model. In this scenario, a new table will be created.  I think the way to generate the third table of `hasandbelongsto many` relation should be consistent.   Either sort model names first and then concat them, or can define the middle table name in model.json.

ps. I am using postgresql datasouce connector

**Comment by superkhau** [comment]
Sounds like a legitimate concern. @raymondfeng Any suggestions here? Maybe an alias property in the model configurations?

**Comment by raymondfeng** [comment]
By default `hasAndBelongsTo` derive a name for the connection model and it is sensitive to the order. You should be able to override it with `through` property.

**Comment by Neil-UWA** [comment]
@raymondfeng I tried to add the `through` property in both models' relation definition and it didn't create the through model.

```javascript

//category 
{
  relations: {
    "tags": {
      "type": "hasAndBelongsToMany",
      "model": "tag",
     "through": "somemodel",
      "foreignKey": ""
    }
  }
}

//tag 
{
  relations: {
    "categories": {
      "type": "hasAndBelongsToMany",
      "model": "category",
     "through": "somemodel"
      "foreignKey": ""
    }
  }
}
```

I assume that you are suggesting to change the relation to `has many through` and create the third model, right?
