### ISSUE TITLE
how do i use passport login for api login

### ISSUE THREAD

**Issue by gshireesh** [strongloop/loopback#1678]
hi,
i am trying to use passport component of strongloop to login into my application, is there any way to use that login to get token for api use?

thanks,
Shireesh.

**Comment by csvan** [comment]
Please see:

https://github.com/strongloop/loopback-component-passport
https://github.com/strongloop/loopback-example-passport

By the way, I do not mean to sound critical, but Googling your question first is a much faster way to resolve questions like this.

**Comment by gshireesh** [comment]
Hi,
Thanks for the advise.
what i actually meant was related to issue running on loopback-passport-component

https://github.com/strongloop/loopback-component-passport/issues/57

we can login using sessions but its is becoming difficult to get access token in passports local login.
we are not having that functionality in current loppbacks passport-local.


I found a temporary solution which i posted in the issue. But if time permits ill make a pull request to the code that might be generic as well. 

thanks,
Shireesh.

**Comment by superkhau** [comment]
@gshireesh Are you still running into issues? Can I close this? Also, please feel free to submit a PR and I'll try to get it bumped up in priority.

**Comment by gshireesh** [comment]
Not facing issue. I already posted a pull request. Please verify it. Thank
you

**Comment by superkhau** [comment]
@gshireesh Can you paste a link to the related PR?

**Comment by gshireesh** [comment]
Hi,

Sorry for delay,
here is the link,
https://github.com/strongloop/loopback-component-passport/pull/88

please  see if any of that code can bee used. and please get back to me if
anything can be done to improve
my improvement.

thanks,
Shireesh.

**Comment by superkhau** [comment]
@raymondfeng Assigning to you for the code review in the PR mentioned above.
