### ISSUE TITLE
where clause doesn't work with has many through relation

### ISSUE THREAD

**Issue by Neil-UWA** [strongloop/loopback#1679]
Model relations:  

```javascript
user.json 
{
  relations: {
    "collected_items": {
      "type": "hasMany",
      "model": "item",
      "foreignKey": "userId",
      "keyThrough": "itemId",
      "through": "collection"
    }
  }
}

item.json

{
  "relations": {
    "collectors": {
      "type": "hasMany",
      "model": "user",
      "foreignKey": "",
      "through": "collection",
      "keyThrough": "userId"
    }
  }
}

collection.json
{
"relations": {
    "item": {
      "type": "belongsTo",
      "model": "item",
      "foreignKey": ""
    },
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": ""
    }
  },
}
```

with this relation declaration, user model will have  `user.collected_items` method and a restful endpoint `/api/users/{id}/collected_items`.   When try to specify where clause, for example, {where: {id: 7}}, to retrieve collected_item that id matches 7,  either in the request url or nodejs code, the where clause doesn't affect the result, the endpoints will return all collected_items belongs to the users rather than matched data.

├── loopback@2.22.0
├── loopback-boot@2.12.2
├── loopback-connector-postgresql@2.3.0
├── loopback-datasource-juggler@2.40.1
├── loopback-explorer@1.8.0

**Comment by enco164** [comment]
try 
    user.findById({
        id: 7, 
        filter:{
            include: {
                relation: 'collected_items'
            }
        }
    }, function successCb(valute, responseHeaders){...}, function error(error){} );

**Comment by csvan** [comment]
If you want to filter based on the related models, you need to perform an `include` query. See the following: https://docs.strongloop.com/display/public/LB/Include+filter#Includefilter-Includewithfilters

**Comment by Neil-UWA** [comment]
Thx @csvan ,@enco164. I know that,  and that works on endpoint /api/users/{I'd} to get related resources , but what I am talking about is the restful endpoint /api/users/{id}/collected_items, and the where clause won't work to filter specified items. Maybe I am missing something.

**Comment by kamal0808** [comment]
@Neil-UWA - did you find the solution to your problem? going through the same issue here.

**Comment by ajbeach2** [comment]
this is still an issue.

**Comment by AntoinedeChassey** [comment]
Any update on this ?
