### ISSUE TITLE
remote methods defined in code on a method can't be seen when model is linked via relationship.

### ISSUE THREAD

**Issue by henryhardy** [strongloop/loopback#1682]
If you create a model, then create a remoteMethod in code, then link it to another model through relations generator, only the standard CRUD methods of the model are found on the relation, not the custom ones.

Ideally, when relation generator is run after remoteMethods are defined, it should include these too.

**Comment by superkhau** [comment]
@ritch Please confirm if this feature is already implemented.

**Comment by loay** [comment]
@henryhardy is this issue fixed on your end? Thanks

**Comment by loay** [comment]
Closing this case for inactivity. If you are still experiencing the same issue, please feel free to leave a comment and the case will be re-opened. Thanks.
