### ISSUE TITLE
attachTo() doesn't execute callback function upon success.

### ISSUE THREAD

**Issue by Superv1sion** [strongloop/loopback#1683]
This function:
```
myModel.attachTo(app.datasources.db_slave, function(err){
      console.log(err);
});
```
Doesn't execute callback function if model is attached to datasource.
Actually, when i used wrong datasource name or change parameters in datasources.json order to prevent connection to mysql - callback also wasn't executed, just appeared node's error which terminated process.

**Comment by superkhau** [comment]
`attachTo` doesn't take a callback. See https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L330
