### ISSUE TITLE
Unique Key in embed model does not work

### ISSUE THREAD

**Issue by wesleymilan** [strongloop/loopback#1687]
I'm trying to control the insertion of duplicate values inside a embed model, but when I've set the field as a Primary Key it allow just one row, even when the value of primary key is different.  When I've set this field as unique it does not check duplicity.

PS: In any case it does not check for the userId exists in User table

**This is the main MongoDB model example**
```
{
  "name": "device",
  "base": "PersistedModel",
  "strict": true,
  "properties": {
    ...
  },
  "acls": [],
  "relations": {
    "rel_permission": {
      "type": "embedsMany",
      "model": "permission",
      "scope": {
        "include": "userId"
      }
    }
  }
}
```
**This is the primary key example**
```
{
  "name": "permission",
  "base": "Model",
  "idInjection": false,
  "strict": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "userType": {
      "type": "string",
      "required": true
    },
    "userId": {
      "type": "string",
      "required": true,
      "id": true
    }
  },
  "validations": [],
  "acls": [],
  "relations": {
    "userId": {
      "type": "belongsTo",
      "model": "User",
      "foreignKey": "userId"
    }
  }
}
```
**This is the unique example**
```
{
  "name": "permission",
  "base": "Model",
  "idInjection": false,
  "strict": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "userType": {
      "type": "string",
      "required": true
    },
    "userId": {
      "type": "string",
      "required": true,
      "index": {"unique": true}
    }
  },
  "validations": [],
  "acls": [],
  "relations": {
    "userId": {
      "type": "belongsTo",
      "model": "User",
      "foreignKey": "userId"
    }
  }
}
```

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by wesleymilan** [comment]
Sorry, but this is a private project and I'm not able to open it.  
In the next weekend I'll try to build a new repo just to demonstrate this issue, and post the URL here.

Thanks

**Comment by superkhau** [comment]
@wesleymilan Are you still running into issues? Is this good to close?
