### ISSUE TITLE
model with embedsOne relation is not saved on db [sandbox attached]

### ISSUE THREAD

**Issue by kranthitech** [strongloop/loopback#1688]
I have created an example of an Author having a pen name using embedsOne relationship. Here is the attached sandbox for this example - https://github.com/kranthitech/loopback-sandbox

When I create a new Author with a pen name, the corresponding pen name object gets attached to the author along with a generated id. But when I try to list out all the created pen names using find, I get an empty array.

Expected behaviour:
Should list the newly created pen name

Actual Behaviour:
Showing list of pen names as empty

Sandbox:
https://github.com/kranthitech/loopback-sandbox

**Comment by csvan** [comment]
What happens if you set `strict: false` in Author?

**Comment by kranthitech** [comment]
Result is still the same.

Setting strict:false is allowing me to add additional properties like popularBook to author, but it has no effect on creation of PenName instances.

**Comment by kranthitech** [comment]
@bajtos - Can any one from the strongloop team confirm if this is the expected behavior or a bug? Thanks :)

**Comment by bajtos** [comment]
I am not familiar with embedded relations. @raymondfeng or @fabien could you please check this issue yourself?

**Comment by kranthitech** [comment]
Thanks @bajtos . @raymondfeng , @fabien - Can you please confirm is this is the expected behaviour or a bug? THanks.

**Comment by loay** [comment]
Hi @kranthitech 
I checked your sandbox. You still need to create both the parent and child separately.
Quoting from the documents:
`
Treat embedsMany as an actual relation, no different from hasMany, for example. This means that you cannot just POST the full object with embedded/nested data to create everything all at once. So using the example above to add a Customer and multiple email addresses would require two POST operations, one for the Customer record and one for the multiple email address data.
`
In your case it is embedsOne, which is the same behavior. 

More reference: 

https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations#Embeddedmodelsandrelations-EmbedsMany

Let me know if you need any further assistance. Thanks

**Comment by loay** [comment]
Closing this case for now. If you are still experiencing the same issue, please feel free to leave a comment and the case will be re-opened. Thanks.
