### ISSUE TITLE
Application.resetKeys will create a new instance instead of updating a record

### ISSUE THREAD

**Issue by wusuopu** [strongloop/loopback#1689]
When I want to reset keys for a application use `Application.resetKeys`. It will create a new instance instead of updating this instance.

This caused by 'before save' operation hook.
https://github.com/strongloop/loopback/blob/master/common/models/application.js#L95

Maybe it should set the id property just it's empty.

**Comment by superkhau** [comment]
@bajtos ^

**Comment by bajtos** [comment]
This looks like a bug to me, I think we should generate the `id` property only if it's not set.

**Comment by wusuopu** [comment]
@bajtos May I submit a PR to fix it.
