### ISSUE TITLE
How to define a virtual property

### ISSUE THREAD

**Issue by rkmax** [strongloop/loopback#1690]
Example my model have the properties `firstName` and `lastName`, I can do

```js
Object.defineProperty(Profile.prototype, 'fullName', {
  get: function() {
    return [this.firstName || '', this.lastName || ''].join(' ').trim();
  }
});
```

but the `fullName` property is available only on the server, how I can send the property fullName when my model is fetched through the API.

this also makes me wonder how to avoid save the property `fullName` if it is sent back to the API

**Comment by superkhau** [comment]
Can you provide more details? Is this a LoopBack question or an Angular question or more specifically, how are you sending the POST request to the LoopBack server?

**Comment by rkmax** [comment]
sure @superkhau it's a question for LoopBack

Example. on GET /api/Model/:id I want able to serve

```json
{
 "id": "1234",
  "firstName": "Julian",
  "lastName": "Reyes",
  "fullName": "Julian Reyes"
}
```

and if you PUT /api/Model/1234

```json
{
 "id": "1234",
  "firstName": "Julian",
  "lastName": "Reyes",
  "fullName": "Julian Reyes"
}
```

ignore `fullName` virtual property instead of saving `fullName`

**Comment by superkhau** [comment]
I don't believe we support virtual properties (ie. mongooose style virtual properties - @raymondfeng please confirm). However, you can achieve what you want by using an before save operation hook. Just delete the properly from the model before it's persisted. See https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-beforesave.

**Comment by superkhau** [comment]
For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details. Going to close this, if you have any more issues, feel free to comment and I will reopen if necessary.
