### ISSUE TITLE
Generate a TypeScript Definition file as part of the build

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1692]
This should be possible using either the `JSDoc` comments or remoting metadata.

See https://github.com/strongloop/loopback/issues/1415 for original question that sparked this feature request.

**Comment by kierer** [comment]
+1

**Comment by rob3c** [comment]
+1

**Comment by lambrojos** [comment]
+1

**Comment by gustavomick** [comment]
+1

**Comment by proreact-mj** [comment]
+1

**Comment by dregre** [comment]
+1

**Comment by vargo** [comment]
+1

**Comment by GauSim** [comment]
+1

**Comment by SynerG** [comment]
+1

**Comment by pmoelgaard** [comment]
+1

**Comment by nitintutlani** [comment]
+1

**Comment by f0ysal** [comment]
+1

**Comment by malotur** [comment]
+1

**Comment by xiangmeng4geo** [comment]
+1

**Comment by enicholson** [comment]
+1

**Comment by dtomasi** [comment]
+1

**Comment by tuomastanner** [comment]
+1

**Comment by Yaojian** [comment]
+1

**Comment by tesenwein** [comment]
+1

**Comment by saaa-hsjgrobler** [comment]
+1

**Comment by jay-soeur** [comment]
+1

**Comment by drywolf** [comment]
+1

**Comment by rodamora** [comment]
+1

**Comment by dansterrett** [comment]
+1

**Comment by cajoy** [comment]
+1

**Comment by bwillacker** [comment]
+1

**Comment by dzsessona** [comment]
+1

**Comment by gaurav21r** [comment]
+1 :+1: Infact, the loopback API https://apidocs.strongloop.com/loopback/ is so vast, has the core team considered moving to Typescript?

**Comment by htammen** [comment]
+1

**Comment by d-asensio** [comment]
+1

**Comment by syntonyze** [comment]
+1

**Comment by barbasa** [comment]
+1

**Comment by DarynHolmes** [comment]
+1

**Comment by Cheater912** [comment]
+1

**Comment by marni** [comment]
+1

**Comment by ShaharHD** [comment]
+1

**Comment by harroot** [comment]
+1

**Comment by micmro** [comment]
+1

**Comment by jeremysik** [comment]
+1

**Comment by rizvanhaider** [comment]
+1

**Comment by gruzilla** [comment]
+1

**Comment by nwwatson** [comment]
+1

**Comment by tjosbon** [comment]
+1

**Comment by ritch** [comment]
> has the core team considered moving to Typescript?

Yes, but not seriously. I had many discussions with @raymondfeng (loopback) and @jeffbcross (angular) about it, but it is not an easy thing to do while maintaining backwards compatability. I think it would make a lot of sense though. @raymondfeng maybe we should think about it for 3.x?

**Comment by ritch** [comment]
Regarding this issue... I'm going to make sure this gets planned soon, as it is one of the most requested features.

**Comment by gaurav21r** [comment]
@ritch Thanks for updating!

> but it is not an easy thing to do while maintaining backwards compatibility.

 Can you explain this a bit further? Typescript is basically type annotations on top of JavaScript and it compiles down to plain JS; which, in my opinion, should be backward compatible as its the same code + type annotations.

Also one of the best features about TS is that its **optionally** typed. We can get started from converting JS to TS simply by renaming the file extension! I've tried it on a large project and it works.

Would be really interested to know your point of view @ritch @raymondfeng @jeffbcross

**Comment by SurealCereal** [comment]
+1

**Comment by listepo** [comment]
+1

**Comment by mathewmeconry** [comment]
+1

**Comment by terehov** [comment]
+1

**Comment by gaurav21r** [comment]
@ritch Any updates? :)

**Comment by christophla** [comment]
+1

**Comment by StanFisher** [comment]
+1

**Comment by bangonkali** [comment]
+1

**Comment by pstinghua** [comment]
+1

**Comment by gaurav21r** [comment]
@all GitHUb now has Reactions! Use the thumbs up `+1`s instead of a new comment!

**Comment by orlandoibm** [comment]
+1

**Comment by raymondfeng** [comment]
I started to draft the definitions at https://gist.github.com/raymondfeng/4d71d6e04e3d3a810b2f90c28859d496

**Comment by geminiyellow** [comment]
+ 1

**Comment by xinbenlv** [comment]
+1

**Comment by timbophillips** [comment]
++1

**Comment by scottmcdonnell** [comment]
+1

**Comment by demakrated** [comment]
+1

**Comment by Yorkst** [comment]
+1

**Comment by Ulfasaar** [comment]
+1

**Comment by zkuang** [comment]
+1

**Comment by bfv** [comment]
A lot +1's (gave a thumb up myself). My point of view is pretty simple, if there are no typings available I will not use it. So no loopback for the next project.

**Comment by bbmn1** [comment]
+1

**Comment by cajoy** [comment]
@bfv Do you know any typescript friendly alternatives?

**Comment by interisti** [comment]
+1

**Comment by petrlyapin** [comment]
+1

**Comment by ivanproskuryakov** [comment]
+1

**Comment by prashantghimire** [comment]
+1

**Comment by mjerez-radical** [comment]
+1

**Comment by hkashlan** [comment]
+1

**Comment by morentin** [comment]
+1

**Comment by jcroldan** [comment]
+1

**Comment by M-jerez** [comment]
@ritch @all, microsoft is working On dts-gen, that might help to anyone working On this https://github.com/Microsoft/dts-gen

**Comment by jorgeramos** [comment]
+1

**Comment by raymondfeng** [comment]
@M-jerez Good pointer. I'll take a look. 

BTW, our tooling team has built the following plugin for Visual Studio code:

https://github.com/IBM-Bluemix/vscode-extension-api-connect

It generates the following typescript d.ts file:

[apiConnect.d.ts.txt](https://github.com/strongloop/loopback/files/466520/apiConnect.d.ts.txt)

**Comment by shairez** [comment]
+1

**Comment by jeffbcross** [comment]
Stay out of this, @shairez

**Comment by jcroldan** [comment]
Hi,

i tried Qeti's fork of loopback-sdk-angular & loopback-sdk-angular-cli who generates typescript files.

You can take a look here: 
https://github.com/qeti/loopback-sdk-angular
https://github.com/Qeti/loopback-sdk-angular-cli

**Comment by sylvaindumont** [comment]
Based on the work on the qeti fork, there is : 
https://github.com/mean-expert-official/loopback-sdk-builder

**Comment by lailavinson** [comment]
+1

**Comment by sushilks** [comment]
+1

**Comment by matts310** [comment]
+1

**Comment by jordialborch** [comment]
+1

**Comment by TangMonk** [comment]
+1

**Comment by rsingh25** [comment]
+1

**Comment by AnthonyLabaere** [comment]
+1

**Comment by ShimiBaliti** [comment]
+1

**Comment by dasoli** [comment]
+1

**Comment by dasoli** [comment]
I dont know why everytime the same people rate down the post, Beeman or somebody else - feel free to tell us why you don't like that people want to keep this issue alive?

**Comment by beeman** [comment]
@dasoli it's annoying to see just an `+1` added to an issue. Everybody gets notified without any news, that kind of defeats the purpose of keeping the issue alive because nothing changed.

If you want to express that you'd like to see this issue solved you can use the thumbs up icon on the opening post.

**Comment by kattsushi** [comment]
1+

**Comment by geminiyellow** [comment]
@beeman no no, `Reactions` not send a notification, single comment dose. that means, everybody want to know the status about this issues.they push this project move. if you dont like it, you can set  no watch , or, if maintainer dont like it, they can lock this issue.

**Comment by bdharrington7** [comment]
Sooo given the number of +1's (both reactions and comments) is this being prioritized at all?

**Comment by zbarbuto** [comment]
@bdharrington7 Given that the [Loopback Angular 2 SDK Builder](https://github.com/mean-expert-official/loopback-sdk-builder) exists, probably not.

**Comment by bdharrington7** [comment]
@zbarbuto what if I don't want to use Angular?

**Comment by movibe** [comment]
+1

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be adding any new features.
