### ISSUE TITLE
Improve API Versioining Documentation and Features

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1693]
This is an issue to spark a discussion on how to improve support for versioning LoopBack APIs.

@kraman @sam-github - could you guys comment on issues you have run into and or ideas for what we can do to improve support (even if its just documentation / guides).

**Comment by sam-github** [comment]
There just doesn't seem to be any support for versioning. We can talk about tomorrow. I would start by looking around to see what other REST APIs do before inventing a new variant, that said:

- versions can just be incompatible major versions: /api/v1, /api/v2
- loopback scaffolding tools (arc, generator-loopback) don't support that, or anything else
- versions could also be semantic versions (probably overkill)
- checking of versions right now is something we do by hand using a version command after connecting, and we use semver, but the mesh-models only supports a single api version at a time
- maybe that is reasonable, and the only thing possible
- some version changes are compatible (adding new fields in a model), so maybe semantic versioning isn't overkill

**Comment by mghaderyan-macys-com** [comment]
Hi guys. Any update on this?
