### ISSUE TITLE
how to use the object of the root key

### ISSUE THREAD

**Issue by oliveiradev** [strongloop/loopback#1697]
Example:
```javascript
 {
     "person": {
         "name": "Foo"
     }
 }
```

send key root **"person"**

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

Also, could you be more clear? Is this question related to LoopBack?

**Comment by oliveiradev** [comment]
Ok @superkhau , sorry.

**Comment by superkhau** [comment]
@oliveiradev No problem. It is recommended because you'll probably get an answer faster there since the community is much more active on those channels. Good luck! ;)
