### ISSUE TITLE
validateAsync does not work

### ISSUE THREAD

**Issue by ciokan** [strongloop/loopback#1703]
I have an `async` validation in one of my models in which I query for a related object to validate it's existence. The problem is that the request is timing out on this validation and the server never responds.

    module.exports = function(Ip) {
          // Required fields
          Ip.validatesPresenceOf('server_id');
    
          ...
    
          Ip.validateAsync('server_id', isExistingServer, {
                message: 'invalid server'
          });
    
          function isExistingServer(err, done) {
                var ServerModel = Ip.app.models.Server;
                var self = this;
                ServerModel.findById(self.server_id, function(e, server) {
                      console.log(_.isNull(server));// this actually prints false
                      return _.isNull(server) ? err() : done();
                });
          }
    };

**Comment by vroudge** [comment]
What was the fix for this?
