### ISSUE TITLE
problems when using fields filter in include filters 

### ISSUE THREAD

**Issue by windyinwind** [strongloop/loopback#1705]
I want get multiple model info by relations, and I want to use fields filter while using include filter. 

Here is my  model defination:
job  has a  "has many" with contact through job_contact

-------------------------------
job.json
```
{
     "name": "job",
     "base": "PersistedModel",  
    "properties": {
    "id": {
      "type": "string",
      "id": true,
      "required": true,
      "index": true,
      "mysql": {
        "columnName": "id"
      },
      "name": {
      "type": "string",
      "mysql": {
        "columnName": "name"
      }
    },
     "relations": {
      "contacts": {
      "type": "hasMany",
      "model": "contact",
      "foreignKey": "jobId",
      "through": "job_contact"
    }
  }
```
--------------------------
contact.json
```
{
     "name": "contact",
     "base": "PersistedModel",  
      "properties": {
       "id": {
      "type": "string",
      "id": true,
      "required": true,
      "index": true,
      "mysql": {
        "columnName": "id"
      },
      "name": {
      "type": "string",
      "mysql": {
        "columnName": "name"
      }
    },
     "relations": {
      "jobs": {
      "type": "hasMany",
      "model": "job",
      "foreignKey": "contactId",
      "through": "job_contact"
    }
  }
}
```
----------------------------
job_contact.json
```
{
     "name": "job_contact",
     "base": "PersistedModel",  
     "id": {
      "type": "string",
      "index": true
    },
    "contactId": {
      "type": "string",
      "index": false
    },
    "opportunityId": {
      "type": "string",
      "index": false
    },
     "relations": {
      "job": {
      "type": "belongsTo", 
      "model": "job",
      "foreignKey": "jobId"
      },
      "contact": {
      "type": "belongsTo", 
      "model": "contact",
      "foreignKey": "contactId"
      }
  }
}
```
=============================
when I try to use  the code below, it works fine 
```
contact.find({
             where: {id : id},
             fields: {id: true},
             include:{
                relation:'jobs',              
                scope:{
                //   fields: ["id","name"]
                }
             }
        },function(err, result){
        if(!err){
           cb(null,result);
        }else{
            cb("error : "+err,null);   
        } });
```
=========================================
but when I try to use  the code below(uncomment fields filter), 
```
contact.find({
             where: {id : id},
             fields: {id: true},
             include:{
                relation:'jobs',              
                scope:{
                   fields: ["id","name"]
                }
             }
        },function(err, result){
        if(!err){
           cb(null,result);
        }else{
            cb("error : "+err,null);   
        }
   });
```

I get an error  "Error: ER_BAD_FIELD_ERROR: Unknown column 'contactId' in 'field list'"
according to the log ,  the error occur when trying to select fields from jobs table, somthing like:
select id, name, contactId from jobs from where .........................

The problem is why "contactId" field show up in this sql, I spend a lot of time on this, could some offer help on this?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by superkhau** [comment]
Actually, can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

I would like to confirm whether it's a bug or not. But for future questions, please follow the instructions from the previous comment.

**Comment by loay** [comment]
Issue is fixed as per this https://github.com/strongloop/loopback-datasource-juggler/issues/733

Closing
