### ISSUE TITLE
hasAndBelongsToMany deleted objects

### ISSUE THREAD

**Issue by MarkAndrewJohnson** [strongloop/loopback#1709]
We have a new app server that is mostly running fine.  We have however encountered one problem.

We have among others, two models - Member (extends User) and Product.

As a two-way relationship a member can like a product and for that product you can see it's likes, so we used hasAndBelongsToMany relationship.

Now where the problem exists is we can delete a product (but not a member).  The problem that occurs is when a product has been deleted and you attempt to get the likes for the user, the connections throws a timeout error.  It would appear something's not being handled appropriately if a deleted object can't be found for the join.

To get over this handle we added a "before delete" event which access the product and empties the relation with product.likes.remove({} , function(err) { ... })

This leads to two possible outcomes for loopback:
1.  Update the delete event to also remove this data from the relationship table
2.  Correctly handle missing objects

**Comment by superkhau** [comment]
Can you provide a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by loay** [comment]
Hi @MarkAndrewJohnson I am closing this issue. If you are still experiencing the same issue, please feel free to leave a comment and I will re-open the case. Also, please provide a test project as per the previous comment. Thanks
