### ISSUE TITLE
`app.enableAuth` should fail when models are not configured correctly

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#171]
The access control code requires that the following models are present & attached to a datasource:

``` js
loopback.User
loopback.AccessToken
loopback.Role
loopback.ACL
```

Additionally `User` model must have a `hasMany` relationship with `AccessToken`.

**Expected behaviour**
`app.enableAuth()` should check that these models are correctly configured, otherwise throw an error.

It would be nice if the pre-build User and AccessToken models have the relationship already defined.

**Notes**
It's possible the list is not complete, how about `RoleMapping` or `Scope`?

**Comment by bajtos** [comment]
In #1323, we added an option to `enableAuth` to auto-attach any missing auth models to a given data-source. When this option is set, `enableAuth` will validate that all required models are present and attached to a data source.

However, when the option is not present, the validation is skipped.

I am proposing to modify `enableAuth` to run the validation even when the new option is not set. This may break existing applications (although it's not very likely), let's make this change in 3.0 only.

**Comment by jjhesk** [comment]
how about the User extended models?

**Comment by bajtos** [comment]
@ebarault PTAL, this may be something to consider in your current work on verifying auth setup.

**Comment by ebarault** [comment]
@bajtos
> Expected behaviour
app.enableAuth() should check that these models are correctly configured, otherwise throw an error.

:+1:
(Gosh we are traveling through time here! 3 years back you were discussing this already, seems like things happen eventually :-) )
