### ISSUE TITLE
Calculated properties stripped from remote method in production

### ISSUE THREAD

**Issue by mastertinner** [strongloop/loopback#1711]
I have created a hook which calculates some additional properties for a model and then adds them to the response as follows:

```javascript
  // calculate average rating and total number of ratings
  Business.observe('loaded', (ctx, next) => {
    if (ctx.instance) {
      let sum = 0;

      Business.app.models.Review.find({
        where: {
          businessId: ctx.instance.id
        },
        fields: {
          rating: true
        }
      }, (err, reviews) => {
        if (err) return next(err);

        if (reviews.length) {
          reviews.forEach((review) => {
            sum += review.rating;
          });

          ctx.instance.avgRating = sum / reviews.length;
        } else {
          ctx.instance.avgRating = 0;
        }

        ctx.instance.numRatings = reviews.length;

        return next();
      });

    } else {
      return next();
    }
  });
```

This works fine. Also I created a remote method to return all the businesses nearby a user's location:

```javascript
  Business.nearby = function (lat, lng, page, max, fn) {
    const here = new loopback.GeoPoint({lat, lng});

    if (typeof page === 'function') {
      fn = page;
      page = 0;
      max = 0;
    }

    if (typeof max === 'function') {
      fn = max;
      max = 0;
    }

    const limit = 10;
    
    page = page || 0;
    max = Number(max || 100);

    Business.find({
      // find locations near the provided GeoPoint
      where: {
        geolocation: {
          near: here,
          maxDistance: max
        }
      },

      // paging
      skip: limit * page,
      limit
    }, fn);
  };

  Business.remoteMethod('nearby', {
    description: 'Find nearby businesses around the geo point',
    accepts: [
      {
        arg: 'lat',
        type: 'number',
        required: true,
        description: 'geo location latitude'
      },
      {
        arg: 'lng',
        type: 'number',
        required: true,
        description: 'geo location latitude'
      },
      {
        arg: 'page',
        type: 'Number',
        description: 'number of pages (page size=10)'
      },
      {
        arg: 'max',
        type: 'Number',
        description: 'max distance in miles'
      }
    ],
    returns: {
      arg: 'locations',
      type: 'array',
      root: true
    },
    http: {
      verb: 'GET'
    }
  });
```

This also works fine as long as `NODE_ENV` is set to `development`. As soon as I set `ENV_NODE=production`, a `GET` to my remote method doesn't return the two calculated properties anymore. I'm not sure if the hook is not triggered or if the properties just get stripped from the object.

**Comment by superkhau** [comment]
Can you provide a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by mastertinner** [comment]
Thanks @superkhau and sorry for not reading the reporting instructions. Here's my test project: https://github.com/mastertinner/loopback-sandbox

**Comment by mastertinner** [comment]
I just noticed that it only happens when I use mongodb. So that's probably the main difference between my production and local development. So I added a datasource for a mongodb in production.

**Comment by mastertinner** [comment]
After some further research I have figured out that my remote method doesn't even trigger the
```javascript
Business.observe('loaded', callback);
```
event even though it has a
```javascript
Business.find()
```
in it. Do you know why that might be?

Again, this didn't happen when I was using the memory db but only when using MongoDB.

**Comment by loay** [comment]
Hi @mastertinner 
Still having trouble with the same issue?
Thanks

**Comment by mastertinner** [comment]
Hi @loay
I restructured my app back then to not depend on this anymore so I cannot tell you if the error would still occur. For me, the issue can be closed.

**Comment by loay** [comment]
Thanks. I will double check if any updates are done within Mongo to see if that has been addressed or not. If you encounter the same issue again, please leave a comment here and I will re-open the case.
