### ISSUE TITLE
Not Able to update dynamic fields

### ISSUE THREAD

**Issue by blackvirus18** [strongloop/loopback#1712]
I have a model with the following structure
{
firstName: "deepesh",
lastName: "naini",
email: "theinvincible975@gmail.com"
question: {
5611662e337ae3605046f0d5: false,
5611662e337ae3605046f0d7: false
},
}

Now what I want is based on a condition I want to update the boolean values to 
{
firstName: "deepesh",
lastName: "naini",
email: "theinvincible975@gmail.com"
question: {
5611662e337ae3605046f0d5: true,
5611662e337ae3605046f0d7: true
},
}

But when I am calling the save function on my model after changing the boolean values to true it's not getting updated in DB.

**Comment by blackvirus18** [comment]
@raymondfeng Any inputs on this would be much appreciated.

**Comment by loay** [comment]
What kind of db are you using?
is there an error that you are getting or empty tuple in the table ?
any repo where I can reproduce the error?

**Comment by loay** [comment]
@blackvirus18 
Did you get that sorted out?
if not, can you please share the save model function that you are using with the type of db?
Even better, if you have a repo that I can use to reproduce the issue so I can help out?
Thanks.

**Comment by loay** [comment]
Hello,
I am closing this issue for now. 
If you are still running into problems, feel free to leave a comment and I will reopen the issue.
closes#1712
