### ISSUE TITLE
How to reterive entire schema in response using loopback

### ISSUE THREAD

**Issue by chandrasekhark** [strongloop/loopback#1713]
When i execute post method in loopback using rest api, i am getting response success with data including id (primary key) and parameters which i send as input.

I want entire table schema in response. How to achieve it?

![screenshot from 2015-10-06 16 33 38](https://cloud.githubusercontent.com/assets/8915614/10307790/0fb94e96-6c4f-11e5-880d-1dc6640bfe20.png)

**Comment by superkhau** [comment]
You will have to create a remote method that returns the schema. There is no specific example to show you how, but maybe @crandmck can point you at the docs that can get you started.

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
