### ISSUE TITLE
Deleting a relation

### ISSUE THREAD

**Issue by dh376** [strongloop/loopback#1718]
I have tried to make a relation between models: A hasMany B.
Something is not right and I tried to delete that relation,
1. I have changed json file to get rid of the relation. 
2. In the API Explorer, when I try to run any get or post method, it gives me error "column "userid" of relation "pictorials" does not exits.
The database indeed does not have userid column. But I don't know why loopback still requires that column since I have deleted the relation.
Is there something I am missing in the process, I have checked and cannot find any information on deleting a relation.

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

@crandmck Do we have docs for this issue?

**Comment by crandmck** [comment]
The docs don't currently explain how to delete a relation.  I think it would be a good addition.

My understanding is that you should be able to delete the relation by editing the model JSON file, as @dh376 says.  You just have to remove all the content from the key
``` "relations": {},```

However, if there is a through model, you might have to edit a second model JSON file.  I think that should do the trick, but I'll need to confirm with @raymondfeng .
