### ISSUE TITLE
slc loopback > "The program 'slc' is currently not installed."

### ISSUE THREAD

**Issue by ogrotten** [strongloop/loopback#1719]
Installed without errors via npm: https://gist.github.com/ogrotten/c4bebc6e9bcaebefc194

What gives?

**Comment by achintverma** [comment]
It was happening to me too. Please make sure you have enough memory and / or swap space. I was setting up on AWS and it was not showing any error. 

Can you paste the console output?

**Comment by cgole** [comment]
Did you install it globally?  - npm install -g strongloop

**Comment by ogrotten** [comment]
It was on a managed vagrant appliance. I mentioned it to the 'manager' and he set up loopback to be pushed with the next update . . . and now I don't have the problem and can't revert to it.

Sorry.

**Comment by superkhau** [comment]
@ogrotten Are you still running into issues? Can I close this?

**Comment by ogrotten** [comment]
I am not.
