### ISSUE TITLE
model hooks beforeUpdate not work

### ISSUE THREAD

**Issue by TNT-Likely** [strongloop/loopback#1721]
model hooks beforeUpdate not work

hope somebody can help me ,thanks.

**Comment by Neil-UWA** [comment]
user operation hooks instead. model hooks are deprecated.

**Comment by TNT-Likely** [comment]
@Neil-UWA it work,but how i can set some attribute?

this.xx='' not work

**Comment by Neil-UWA** [comment]
You can still use model hooks, but they are not recommended since they are deprecated. I suggest you to migrate from model hooks to operation hooks.

**Comment by superkhau** [comment]
>use operation hooks instead. model hooks are deprecated.

This is correct. See https://docs.strongloop.com/display/public/LB/Operation+hooks
