### ISSUE TITLE
ES6(Babel) Support

### ISSUE THREAD

**Issue by listepo** [strongloop/loopback#1724]
Hi guys, how soon will support es6?

**Comment by Pentiado** [comment]
I'm using es6 in production with LoopbackJS for half a year, maybe more.

**Comment by listepo** [comment]
```require('babel/register');``` will work with any node.js framework, but few support inheritance of modules,models and components like:

> for example:

> /api/components/odm-component/collection.js

```javascript

import CollectionComponent from 'odm-component/collection';

class Collection extends CollectionComponent {
    loadDocument (doc) {
        ...
        //Code here
        ...
        return super(doc);
    }
}

export default Collection;
```

> /api/components/odm-component/index.js

```javascript
import ODMComponent from 'odm-component';
import Collection from './collection';

class ODM extends ODMComponent {
    constructor (...arguments) {
        this.Collection = Collection;
        return super(...arguments);
    }
    afterLoad () {
        ...
        //Code here
        ...
    }
}

export default ODM;
```

**Comment by listepo** [comment]
I like how it is done in ember.js http://stackoverflow.com/questions/28654662/how-to-extend-an-ember-cli-addon

**Comment by violet-day** [comment]
+1

**Comment by seanfuture** [comment]
+1, naturally - would prefer loopback over custom / alternate solutions .. ty

**Comment by rflipo-dev** [comment]
👍

**Comment by wikiziner** [comment]
+1

**Comment by NormanColoma** [comment]
So, are you working on this?

**Comment by Sanbornzhang** [comment]
+1
