### ISSUE TITLE
[Relations]No check that the model does not exist

### ISSUE THREAD

**Issue by listepo** [strongloop/loopback#1725]
``` json
  "relations": {
    "statuses": {
      "type": "referencesMany",
      "model": "sfveververv3rv3",
      "property": "statuses"
    }
  },
```

`sfveververv3rv3` is not model, but not errors, not messages in console

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by listepo** [comment]
@superkhau yes https://github.com/listepo/loopback-model-not-exists

**Comment by superkhau** [comment]
@listepo This is more of a feature request when I think about it. Would you like to submit a PR?

**Comment by pthieu** [comment]
@listepo: This might take a while for us to get to. To speed up the process, you can do one of two things:
 1. If you still require this, open a new issue using the `New issue` button and fill in the template provided to you
 2. Open a PR adding this functionality yourself and we will review and merge.

Will close this issue now as it's been over a year. Please use option `#1` if you still require this.
