### ISSUE TITLE
afterRemote hook intermittently failing

### ISSUE THREAD

**Issue by uooq** [strongloop/loopback#1726]
I have an afterRemote hook on a model that extends the built-in User model. Under some circumstances, the afterRemote hook fails to run.

Here's how we can trip it up: we run test automation in mocha that starts up a server, issues requests, tears down the server, then in a different test case starts another server.  If I run the second test case on its own, it passes (and the afterRemote hook runs).  If I run the second test case after the first one (as a part of the same mocha run), then the hook fails to run.

I've got a suspicion this has something to do with having the same process around through two server lifecycles-- that by spawning the server twice on the same process that there's something getting wired up wrong. 

A few comments/notes:
- I am using loopback.context() [as described in the docs](https://docs.strongloop.com/display/public/LB/Using+current+context) to populate an authenticated user onto the context object, and this is all working perfectly. 
- I'm 100% sure that the first server is fully terminated before the second one is started. 
- I'm using the memory database for tests and emptying it between individual tests by running automigrate, (i.e. I start up a server instance in a "before" then in the beforeEach, I automigrate the db to have a clean start).

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by uooq** [comment]
Thanks for the response.

I'll do what I can. It's a private repo. I'll need to build out a separate project that exhibits the same behavior but doesn't have our business guts...

**Comment by davidcheung** [comment]
closing inactive issues, @uooq are you still facing this problem?  
Please feel free to ping me on this issue or reopen a new one.
