### ISSUE TITLE
Generated API is missing getCurrent

### ISSUE THREAD

**Issue by ekussberg** [strongloop/loopback#1727]
Hello,

we have a problem, that when we generate ng-lb for our project, there are missing getCurrent methods for our Users classes (Customer & Employee). They both have "base": "User" and it is generating them only on macs.

Any suggestions?

**Comment by superkhau** [comment]
@bajtos ^

**Comment by bajtos** [comment]
Hi @ekussberg, could you please provide us with steps how to reproduce the problem on our machine? Start by forking loopback-sandbox as described in [wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report), then add your Customer and Employee models, then keep adding other bits of your app until your sandbox app reproduces the problem.

**Comment by bosco-li** [comment]
@ekussberg We will close this issue for now, feel free to reopen this when you can provide show us how to reproduce this.  Thanks.
