### ISSUE TITLE
Is there a way how to programatically stop the Loopback App?

### ISSUE THREAD

**Issue by petermilan** [strongloop/loopback#1729]
I could not find any possibility how to stop the loopback server. Is there some functionality like app.stop() like there is app.start() ?

**Comment by Pentiado** [comment]
It sounds like "xy problem" - http://mywiki.wooledge.org/XyProblem. Killing the process is not going to work for you?
process.exit()

**Comment by petermilan** [comment]
well there could be situations when you don't want to do that for example sending logs to some service (like logstash, graylog etc) and then stop the loopback app. I think doing this:
```
log.error('data');
process.exit();
```

will kill the process before the log will be sent to the logging service.

**Comment by seanbrookes** [comment]
consider using the loopback-workspace module.  It has a
stop()/start()/restart() api

On Wed, Oct 14, 2015 at 2:07 AM, Peter Milan <notifications@github.com>
wrote:

> well there could be situations when you don't want to do that for example
> sending logs to some service (like logstash, graylog etc) and then stop the
> loopback app. I think doing this:
>
> log.error('data');
> process.exit();
>
> will kill the process before the log will be sent to the logging service.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback/issues/1729#issuecomment-147984253>
> .
>



-- 
*StrongLoop <http://strongloop.com/>** makes it easy to **develop APIs
<http://strongloop.com/mobile-application-development/loopback/>** in Node,
plus get DevOps capabilities
<http://strongloop.com/node-js-performance/strongops/> like monitoring,
debugging and clustering**.*

**Comment by superkhau** [comment]
@petermilan There is no app.start either. It is defined at runtime via `app.start = function()...`. You can use `process.exit()` as suggested by @Pentiado. As for the logging situation, you can create your own function that calls process.exit **after** you finish logging (ie. via callback, event emitter, etc).

That said, for now I will escalate this issue to a feature request.

**Comment by jbcpollak** [comment]
this would be useful for unit testing as well. some tests want the app running, some tests don't. Some tests modify the app, some don't. Being able to stop it would let us clear state.

**Comment by lkappeler** [comment]
The app.listen function is returning the server instance which is called in the server/server.js script.
You can assign returned the server instance to a variable and the simply call server.close() to stop the lb server.

server/server.js
```
var server;
var loopback = require('loopback');
var boot = require('loopback-boot');

var app = module.exports = loopback();

app.start ...

app.stop = () => {
  server.close();
}

boot(... ,(err) => {
  ...
  server = app.start();
}
```

**Comment by molok** [comment]
I had to define and call a function like this, otherwise the server never exists

<pre>
app.disconnectDatasources = function() {
    Object.values(app.dataSources)
        .forEach(ds => {
            if (ds.disconnect) {
                ds.disconnect();
            }
        });
}
</pre>
