### ISSUE TITLE
Wildcard for Operation Hooks

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1732]
Do we support wildcard for operation hooks? If we do where is it in the docs?

We should add support for this as it is really nice to be able to write a generic hook (see `createChangeStream()` for one example.

@bajtos @Setogit

**Comment by bajtos** [comment]
@ritch could you please describe the problems you are trying to solve in more detail, so that we can come up with the best solution? What does wildcard refer to - a wildcard on model names or a wildcard on hook names?

**Comment by ritch** [comment]
@Setogit can you elaborate a bit on the problem?

My take on it is fairly brief: operation hooks are too hard to understand and use.

**Comment by Neil-UWA** [comment]
I also have this needs for this feature
