### ISSUE TITLE
Make loopback apps secure out of the box

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1733]
Review the best practices to secure Node.js applications in production and update the project template to implement necessary measures.

Further reading:
 - https://blog.risingstack.com/node-js-security-checklist/

**Comment by raymondfeng** [comment]
+1. We should add it to the LB 3.0 roadmap too.

**Comment by superkhau** [comment]
I believe this is a duplicate, someone on the TO team is working on something like this already.

@0candy @jannyHou @richardpringle @gunjpan @Amir-61 @loay @davidcheung ^

**Comment by loay** [comment]
@superkhau  I was recently working on a security issue but related to component passport, so not sure if that's what you meant.

**Comment by gunjpan** [comment]
Closing as it's a duplicate of: https://github.com/strongloop-internal/scrum-loopback/issues/583
