### ISSUE TITLE
Isomorphic client use on React Native

### ISSUE THREAD

**Issue by TimPerry** [strongloop/loopback#1734]
Hey, I'm looking to use loopbackjs client (isomorphic) with react native. Seen as loopback uses core node modules I have followed the browserify guide to pull all them into a bundled file. However I'm not sure how I would go about using a browserified file in the app as you can only require files in?? Any ideas how you would do this?

Maybe a better question would be: is there any interest in creating a react/non angular javascript client?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

>...is there any interest in creating a react/non angular javascript client?

There is definitely interest, but we do not have the resources at the moment to take this on. I will leave this issue open and set it as a feature request.

**Comment by TimPerry** [comment]
My apologies @superkhau. If you have any suggestions on how this would work I wouldn't mind giving it a go and if I get something working submit a PR.

**Comment by superkhau** [comment]
Unfortunately, I do not know enough about this area. However, we can ask some of the other team members to get their thoughts.

@bajtos @anthonyettinger @jtary Any of you guys have experience with React Native?

**Comment by bajtos** [comment]
I don't know much about React Native either, but I would like LoopBack to support React Native at some point in the future. According to React Native [docs](https://facebook.github.io/react-native/docs/network.html#content), it provides a polyfill for XMLHttpRequest API implemented via native networking libraries, so that's a good start.

As for loading the loopback app via `require`, have you tried to not run browserify at all and require directly your loopback app file? For example:

```js
require('client/client.js');
```

**Comment by TimPerry** [comment]
@bajtos Sorry I'm not entirely sure what you mean.

In terms of the browserify approach I've replaced the react native packager with a webpack one, this has allowed me to use the loopback webpack plugin and I seem to have something working. However I had to skip using loopback-boot and it was throwing that cannot find loopback-boot#instructions error like (https://github.com/strongloop/loopback-boot/issues/53) and finally I had to remove the middleware from the instructions. 

This is my client.js:

```
'use strict';

var loopback = require('loopback');
var execute = require('loopback-boot/lib/executor');
var instructions = require('loopback-boot#instructions');
delete instructions.middleware

var app = module.exports = loopback();
execute(app, instructions);
```

Not sure why it works at this level and not in the browser.js file in the loopback-boot module?

**Comment by bajtos** [comment]
To support loopback-boot in the browser, you have to add boot instructions to your browser bundle, this is done by [compileToBrowserify](https://github.com/strongloop/loopback-boot/blob/638368844d840ac412417596362cd9092200f658/index.js#L154). Instructions are stored in a virtual JSON file called `loopback-boot#instructions`. When running in a browser, there is a thin wrapper which loads instructions via a single `require` call and calls the universal executor - see [bootBrowserApp](https://github.com/strongloop/loopback-boot/blob/638368844d840ac412417596362cd9092200f658/browser.js#L19-L30).

Hopefully this information will help you to get back on track. It looks to me like you already know more about this problem than I do! I am afraid I don't have enough time to dig into this deeper and give you more specific help. If you happen to be on a paid support plan, then please reach out to your StrongLoop support contact, they will be able to get me time to look into this.

**Comment by jeffcressman** [comment]
@TimPerry do you have any code samples around of how you got this working? Would be greatly appreciated. 

I'm trying to do the same thing and have been doing a lot of head banging. In particular I'm wanting to set up offline sync but I'm not sure if I'm going to be able to do that yet as the browser client is expecting to use local storage. I'm guessing I might have to write a connector for React Native Async Storage.

**Comment by TimPerry** [comment]
@jeffcressman The solution I got working (which I'm not happy with so still holding out for a better solution) was to use https://github.com/mjohnston/react-native-webpack-server this allowed me to use the https://www.npmjs.com/package/loopback-webpack-plugin plugin but it appears that react-native-webpkac-server isnt going to be maintained any longer. To get that far I spend a whole week of messing around in my spare time. My next plan of attack is to try and use the default packager that comes with react native. If you get any further than I have or have any questions feel free to hit me up and maybe we can workout something together?

**Comment by TimPerry** [comment]
This is my webpack config file: https://gist.github.com/TimPerry/522234ee4de8534496ff

**Comment by jeffcressman** [comment]
Thanks @TimPerry, much appreciated. I'll let you know how I go. Cheers.

**Comment by jeffcressman** [comment]
@TimPerry I've had an awful time trying to get this sorted out. Tried a number of approaches. Need to move on from React Native for this project but I hope to circle back later and try and figure this out.

It seems like React Native + Webpack is very temperamental. Some folks can get projects to build/run and some can't and the difference in environments is difficult to pin down. For example, I can't get the example app for https://github.com/jhabdas/react-native-webpack-starter-kit to build.

**Comment by TimPerry** [comment]
@jeffcressman I'm off from Christmas now so should have a couple of days to have a play around with this :) If I get anywhere I shall update everyone on here. I think my approach is going to be to try and avoid webpack, as like you have mentioned it is temperamental with react native.

**Comment by TimPerry** [comment]
So finally got around to having another play with this. I did what @bajtos suggested and didn't use browserify or webpack for that matter and just tried to require the client in. However I get a fs module not found error. Trying to see if I can shim it out but is there any other way I could stop loopback from using it?
