### ISSUE TITLE
Error while installing loopback on elementary os 

### ISSUE THREAD

**Issue by sandipp** [strongloop/loopback#1735]
Error while installing loopback on elementary os 

I'm trying to install loopback framework on local machine using following command and I got error while doing so.

    sudo npm install -g strongloop

Error 

    npm WARN deprecated jsonstream@1.0.3: use JSONStream instead
    npm WARN deprecated showdown@0.3.1: IMPORTANT hotfix
    npm WARN install Couldn't install optional dependency: shasum check failed for /tmp/npm-7640-57dc8433/registry.npmjs.org/strong-trace-waterfalldata/-/strong-trace-waterfalldata-1.0.1.tgz
    npm WARN install Expected: ed7d7b77895a5168b67aa48dc11c487e387207bf
    npm WARN install Actual:   2ef84601c1de84c020ac2eb96b05751e0e24cc85
    npm WARN install From:     https://registry.npmjs.org/strong-trace-waterfalldata/-/strong-trace-waterfalldata-1.0.1.tgz

Configurations of the machine

    OS - Elementary Freya, Ubunutu 14.04 based 
    
    Node - v4.1.2

**Comment by superkhau** [comment]
@rmg ^

**Comment by rmg** [comment]
@sandipp this looks like an npm issue. You could try `npm cache clean` or simply retrying the install to see if the checksum error goes away. If none of that works, you might have to go to [npm](https://github.com/npm/npm) for help.

Ultimately, however, these are just _warnings_ not errors and should not be preventing you from installing strongloop.
