### ISSUE TITLE
Permissions changes on user roles from an interfaces

### ISSUE THREAD

**Issue by LucaColonnello** [strongloop/loopback#1736]
Hi,
I have to build an app with an users module that manage roles and users, making possible to set the permissions (permissions are static) for each role.

How can I do this with ACL?

Thank you!

**Comment by raymondfeng** [comment]
User/Role/RoleMapping/ACL are loopback models that can be persisted into DBs and exposed as REST APIs. Your UI should be able to use such APIs or Angular SDK to interact with these models.

**Comment by superkhau** [comment]
@LucaColonnello Take a look at https://github.com/strongloop/loopback-example-access-control

For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
