### ISSUE TITLE
Server hangs when using a where filter on subresource in hasManyThrough

### ISSUE THREAD

**Issue by framp** [strongloop/loopback#1737]
Given the models:
```
Item
Customer
CustomerItem
```
where Customer has many Items through CustomerItem

If you try to request `/api/Customers/1/Items?filter[where][property]=10` the server will hang

Repo to reproduce the issue here: https://github.com/framp/loopback-bug-1737

**Comment by framp** [comment]
@superkhau I'll be happy to jump on it, fix the issue and prepare a PR but I'm getting a little bit lost while debugging the issue.

Is there some document I'm missing which describes the request flow and what loopback components are being used?

**Comment by superkhau** [comment]
@crandmck ^ Do we have such a doc?

**Comment by crandmck** [comment]
No, I don't think so.  If we can get this info, it would be a nice addition to docs... Perhaps @raymondfeng could provide it?  It might not even be practical... flow for Node/async operations can become rather complex (which is why it's hard to debug).

**Comment by framp** [comment]
Got some more time to debug it and tracked it down to the `DataAccessObject.find` in `loopback-datasource-juggler/lib/dao.js#L1309`.
The function is called 4 times, the third time it's not calling `allCb` and consequently `cb`.

Following the callback:
 - `connector.all(self.modelName, ctx.query, options, allCb)` which goes to `lib/connectors/memory.js#L315`.
- `self._models[model].model.include(nodes, filter.include, options, callback);` which goes to `lib/include.js#L154`

**Comment by framp** [comment]
Fixed the bug, it was a missing callback in loopback-datasource-juggler.

I opened a PR on that repo
