### ISSUE TITLE
hateoas support

### ISSUE THREAD

**Issue by type0lang** [strongloop/loopback#1739]
Strong need to add jsonapi support, maybe pluggable support to other paradigms like hal.

slc loopback:jsonapi
slc loopback:hal

**Comment by javierfdr** [comment]
+1

**Comment by Octopixell** [comment]
+1

**Comment by type0lang** [comment]
Since it would be hard to provide a hateoas facace after a well scaffolded project was created
maybe a wizard can assist you to create the project:

*Do you want to provide hateoas support?*
[y] yes
[n] no

*Which paradigm do you prefer for hateoas interface ?*
[1] jsonapi (http://jsonapi.org/)
[2] hal (http://stateless.co/hal_specification.html)
[...]

**Comment by jbcpollak** [comment]
+1

**Comment by rmartins90** [comment]
:+1:

**Comment by stalinkay** [comment]
+1

**Comment by geruiz** [comment]
:+1:

**Comment by oguzhanyalcin** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by aliemrahpekesen** [comment]
👍

**Comment by gitman** [comment]
👍 

When do I expect this to be scheduled?
And what can I do right now to add Support for hateoas in my API today?

**Comment by isuruAb** [comment]
is this available now ?

**Comment by stalinkay** [comment]
@Isuru, this is nothing official but I think this is what you are looking for, till there’s an official implementation. [loopback-j <https://github.com/backstage/loopback-jsonschema>sonschema](https://github.com/backstage/loopback-jsonschema).

**Comment by sorokh** [comment]
@Isure, you have jsonapi support via https://github.com/digitalsadhu/loopback-component-jsonapi.
