### ISSUE TITLE
support configuration of datasources/models from environment variables and other sources

### ISSUE THREAD

**Issue by seanbrookes** [strongloop/loopback#174]
the current LB datasource configuration makes it awkward to deploy a mongo (mongolab) db based app to Heroku.  

LB datasources:

```
  "mongodb": {
    "defaultForType": "mongodb",
    "connector": "loopback-connector-mongodb",
    "database": "dbname",
    "host": "localhost",
    "port": "27017"
  },
```

The instructions on Heroku are to use a process.env variable  to dynamically assign the url value eg:

```
var mongoUri = process.env.MONGOLAB_URI ||
  process.env.MONGOHQ_URL ||
  'mongodb://localhost/mydb';
```

A pseudo work-around is to configure the LB datasource to use the 'url' property instead of database/host/port and then get Heroku to spit out the connection string
https://devcenter.heroku.com/articles/mongolab#getting-your-connection-uri
 eg:

```
$ heroku config | grep MONGOLAB_URI
MONGOLAB_URI => mongodb://heroku_app1234:random_password@ds029017.mongolab.com:29017/heroku_app1234
```

and then reset the datasources.js to this:

```
  "mongodb": {
    "defaultForType": "mongodb",
    "connector": "loopback-connector-mongodb", 
    "url":"mongodb://heroku_app1234:random_password@ds029017.mongolab.com:29017/heroku_app1234"
  },
```

this kind of works but is a bit awkward.  It would be good if I could just plug in my environment vars.

**Comment by transedward** [comment]
@bajtos 
how should I configure my boot options in order to use datasources.local.js?
I like this solution, but I still got this
`AssertionError: User is referencing a dataSource that does not exist: "pg"`
currently, I still use `boot(app, __dirname);` in my server.js
as the loopback generator configures

**Comment by bajtos** [comment]
@transedward Run your app with `DEBUG=loopback*` and check the output for any messages that may explain what's happening under the hood. If that does not show you how to fix the problem, then I'll need a sample project reproducing the problem per [bug reporting instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

**Comment by transedward** [comment]
@bajtos , #1345
