### ISSUE TITLE
automigrate and autoupdate doesn't work for AccssToken if utf8mb4 is used (MySQL / MariaDB)

### ISSUE THREAD

**Issue by danieltrautmann** [strongloop/loopback#1740]
Hi,

I created a database with utf8mb4 encoding and tried the automigrate and autoupdate feature.
All tables were created successfully except the AccessToken table.

After that I turned on the debug mode and saw the following error:
`Specified key was too long; max key length is 767 bytes`

- Database: MariaDB 10.0.21
- Encoding: utf8mb4
- Collation: utf8mb4_general_ci
- Loopback Version: 2.22.2

Regards,
Daniel

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

And can you try the same using MySQL instead of MariaDB.

**Comment by danieltrautmann** [comment]
You can find the repository here:
https://github.com/danieltrautmann/loopback-sandbox-issue-1740-1741

STR:
1. Setup database with encoding utf8mb4 and collation utf8mb4_general_ci
2. Change `datasources.json` according to your database
3. Run `node .`
4. Check if table AccessToken was created

NOTE: Datasource debug mode is needed to see the error message!

Same behaviour with MySQL 5.6.26

**Comment by superkhau** [comment]
@danieltrautmann Did you happen to install MySQL/Maria via homebrew by any chance? I ran into the same issue before. Fixed itself when I installed the official off the MySQL site.

**Comment by danieltrautmann** [comment]
Yes I installed it via homebrew. I'll try the original sources in the next days and give feedback to you.

**Comment by danieltrautmann** [comment]
Now I tried the current versions of MySQL and MariaDB.
Instead of using homebrew, I created two virtual machines, one with MySQL 5.7.9 and one with MariaDB 10.1.8.

It works well with MySQL, but not with MariaDB.
Unfortunately I have to use MariaDB.

**Comment by superkhau** [comment]
@raymondfeng Do we support MariaDB officially?

**Comment by danieltrautmann** [comment]
@superkhau, @raymondfeng Any updates on this?

**Comment by superkhau** [comment]
@raymondfeng ^

@danieltrautmann From what I know, we do not officially support MariaDB. If you require further assistance, we have paid offerings. See https://strongloop.com/node-js/subscription-plans/

Closing as I do not see any issue with the current MySQL implementation. If you believe there are more issues, I will reopen this.

**Comment by jcolemorrison** [comment]
This is still an issue, even with MySQL (5.6 and 5.7).  It fails on auto migrating Access Tokens with the `ER_TOO_LONG_KEY`.  Though some have found a work around by overriding the AccessToken model directly, obviously this the best solution.
