### ISSUE TITLE
AccessToken ttl is NaN (MySQL / MariaDB)

### ISSUE THREAD

**Issue by danieltrautmann** [strongloop/loopback#1741]
Hi,

if I try to login, the access token cannot be created.
It seems, that the default value for `ttl` is not set in the database.

The login request results in the following SQL statement:
`INSERT INTO `AccessToken`(`id`,`ttl`,`created`,`userId`) VALUES(\'C6y9sbi4v5BqL7spRKM0SqNak84GBoRzA3jBes7YVTC2vI9FIXzHBLXRGtp7HAo4\',NaN,\'2015-10-18 13:01:08\',1)`

As you can see, it's trying to insert NaN into column `ttl`, which datatype is `INT`.

The database was created using the automigrate feature.

- Database: MariaDB 10.0.21
- Loopback Version: 2.22.2
- MySQL Connector Version: 2.2.0

Regards,
Daniel

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

Also, can you using MySQL and not MariaDB to see if you run into the same problem?

**Comment by danieltrautmann** [comment]
You can find the repository here:
https://github.com/danieltrautmann/loopback-sandbox-issue-1740-1741

I narrowed down the issue to this part of the account model:
```javascript
Account.settings = {
  emailVerificationRequired: false
}
```

I also tried it with MySQL 5.6.26... same issue.

**Comment by loay** [comment]
Hi @danieltrautmann 
Still facing the same issue? 
If so, can you please re-upload the sandbox repo as it doesn't exist anymore?
Thanks.

**Comment by danieltrautmann** [comment]
Hi @loay 

the project was canceled, so I stopped investigating.
Maybe it was an issue with the encoding and/or collation. I used utf8mb4 and saw that MariaDB provides some collation with a "mysql" suffix, but I didn't tried it.

**Comment by loay** [comment]
@danieltrautmann Thanks. 
It is just that I couldn't reproduce it. if you run to the same issue again, please leave a comment here so we can re-investigate.
