### ISSUE TITLE
loopback.getCurrentContext() is null when setting the accessToken from a cookie.

### ISSUE THREAD

**Issue by julien-sarazin** [strongloop/loopback#1747]
I had to dig into the sources to understand why the accessToken was available from req.signedCookies but not set on the current context, even after adding : 

```javascript
app.use(loopback.token({
        model: app.models.AuthToken
}));
```

And i came to this (middleware/token.js)
```javascript
 TokenModel.findForRequest(req, options, function(err, token) {
      req.accessToken = token || null;
      rewriteUserLiteral(req, currentUserLiteral);
      var ctx = loopback.getCurrentContext();
      if (ctx) ctx.set('accessToken', token);
      next(err);
    });
```
The token is properly fetched but the context is always null.

I tried to understand the context creation flow and it seems that you initialize the context during the routes:loopback#rest which is (i think) too late for those who we need to bind something to the context before the route execution.

I'm pretty new to loopback so i might have missed something.
EDIT: Still looking for a solution to make the accessToken available from the context. Thanks.

**Comment by julien-sarazin** [comment]
I've found a hacky solution that fit with my needs for now but doesn't work with ACL. : 
1 - enabling HTTP in context in config.json
````json
"remoting": {
    "context": {
      "enableHttpContext": true
    }
}
````
2 - using the ctx.http.req.accessToken
```` javascript
    Coder.current = function(cb){
        var context = loopback.getCurrentContext().active;
        return Coder.findById(context.http.req.accessToken.coderId)
    };
````
3 - ACL restrictions does not work (401 even when i'm authenticated)
```json
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "current",
      "accessType": "EXECUTE"
    }
```
My question: It is possible to combine Passport + Built-in ACL ? If so, can someone tells me how, cause it's driving me crazy.

Thanks!

**Comment by barboni** [comment]
+ 1

**Comment by julien-sarazin** [comment]
Found the solution to get the accessToken from the cookie.
Force the context creation in the *middleware.json* file
```json
  "session": {},
  "session:after":{
    "loopback#context": {}
  },
  "auth": {},
  "parse": {},
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  }
````
And set the custom AccessToken model (AuthToken for me) **after** the boot 
```javascript    
app.use(loopback.token({model: app.models.AuthToken}));
```
i'm still having an issue with ACL that does not work. But i'll open another issue.

**Comment by julien-sarazin** [comment]
Last message, fixed the problem with ACL, the relation between my custom User model (Coder) had a foreign key with my custom AccessToken (AuthToken) named ```coderId```. Built-in ACL won't work if the key is different from userId.

**Comment by davidcheung** [comment]
@julien-sarazin would you be able to provide a [sample repo](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) for me to reproduce the issue. Thanks

**Comment by davidcheung** [comment]
related : https://github.com/strongloop/loopback/issues/1676

**Comment by davidcheung** [comment]
>Last message, fixed the problem with ACL, the relation between my custom User model (Coder) had a foreign key with my custom AccessToken (AuthToken) named coderId. Built-in ACL won't work if the key is different from userId.

Going to keep discussion on #1676 and close this issue, thanks.
