### ISSUE TITLE
Use eslint instead of jshint

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1749]
I'm not so opinionated on which of these we use, but @sam-github mentioned that eslint is better, and I tend to believe him.

@bajtos @sam-github

**Comment by BerkeleyTrue** [comment]
:+1:

**Comment by bajtos** [comment]
I don't mind either, as long as we can configure eslint to support the current coding style in our codebase.

**Comment by superkhau** [comment]
+1 for eslint

**Comment by BerkeleyTrue** [comment]
ESlint is able to replace JSCS as well. 

It would also be trivial to implement a loopback specific config package that all loopback pages can npm install.

**Comment by listepo** [comment]
:+1:

**Comment by sam-github** [comment]
We have a common style for non-loopback code: https://github.com/strongloop/strong-supervisor/blob/master/.eslintrc and https://github.com/strongloop/strong-supervisor/blob/master/package.json#L59 and 
```
  "scripts": {
    "pretest": "eslint --ignore-path .gitignore ./",
```

Is our basic setup. Loopback probably has a slightly different style, but the integration pattern above would remain the same.

I've found a few things in jscs that eslint < 1.0 didn't catch, but it wasn't enough to be valuable, we are starting to only use eslint, where we used to use eslint and jscs.

jshint didn't find anything that eslint didn't also find, in my testing, and it had more false positives, things it found that eslint did not... but that weren't actually problems.

The biggest lack of eslint, IMO, is it lacks a rule to enforce 80 columns in source files.

**Comment by superkhau** [comment]
>The biggest lack of eslint, IMO, is it lacks a rule to enforce 80 columns in source files.

Boo.

**Comment by BerkeleyTrue** [comment]
http://eslint.org/docs/rules/max-len

**Comment by superkhau** [comment]
@BerkeleyTrue Nice.

**Comment by sam-github** [comment]
@BerkeleyTrue Thanks! I swear, just last week I scoured the userdocs and didn't find that!

**Comment by superkhau** [comment]
Connect to strongloop-internal/scrum-loopback/issues/687.

**Comment by superkhau** [comment]
My impl is done at https://github.com/strongloop/eslint-config-loopback. Please send PRs with your opinions everyone! ;)

**Comment by ndaidong** [comment]
Yes. ESLint is better than all its alternatives.

**Comment by listepo** [comment]
Cool

**Comment by superkhau** [comment]
We won't be able to publish this repo until after Feb. 1, but once that happens, I'll get it into all official LoopBack repos ASAP.

**Comment by digitalsadhu** [comment]
:+1:

**Comment by bajtos** [comment]
@bajtos to review current defaults, so that we can fix any defaults that don't work with current code base before we publish the first version to npmjs.org.

We have also agreed to move style checkers to `posttest`, so that we check for functionality (failing tests) before we check for stylistic details (eslint).

**Comment by bajtos** [comment]
I am testing the presets now, I am pretty impressed by eslint capabilities. I discovered an issue along the way, see https://github.com/eslint/eslint/issues/5744

**Comment by bajtos** [comment]
As part of this GH issue, we are adding `eslint` into the following repositories: `loopback`, `loopback-datasource-juggler`, `strong-remoting` and `loopback-boot`.

Eventually, we should add it to all other loopback repositories too (there are over 60 of them!). The plan is to create follow-up issues, grouping multiple repos in one issue - either by a "repo expert" or by functional areas (connectors, components + swagger, Angular SDK, workspace/generator/api-def). @0candy agreed to create & assign the stories herself.

**Comment by bajtos** [comment]
> As part of this GH issue, we are adding `eslint` into the following repositories: `loopback`, `loopback-datasource-juggler`, `strong-remoting` and `loopback-boot`.

Done, I am closing this issue.
