### ISSUE TITLE
Can't access stronglooop loopback application which is running on a subfolder on live server

### ISSUE THREAD

**Issue by rizvanhaider** [strongloop/loopback#1751]
I have installed strongloop loopback application on a live server on domain e.g: www.mydomain.com . I have created stronglooop loopback project in a subfolder called "lb" After successfull creation I executed the command "slc run" the terminal logs that your loopback app is running on http://mydomain:3000 but when I opened www.mydomain.com/lb or www.mydomain.com:3000/lb... it was not running there ... How to access running app?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
