### ISSUE TITLE
Override user get

### ISSUE THREAD

**Issue by h2non** [strongloop/loopback#1756]
I would like to override the default endpoint created by loopback, e.g: `GET /api/users/:id`.

I'm defining a remote method with the same path, but it doesn't work.

**Comment by superkhau** [comment]
https://github.com/strongloop/loopback/issues/1077

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by h2non** [comment]
Thank you! I saw that issue, but I was expecting another more convenient solution.

**Comment by superkhau** [comment]
I don't believe there is one ATM, we accept PR's if you're willing to propose a solution. ;)

**Comment by h2non** [comment]
Ideally, the framework should provide a decoupled layer between HTTP protocol top interface and data layer with a convenient interface to programmatically bind those layers, and handle them properly.
For instance, you can declare your HTTP interface explicitly, but al protocol level, and then bind it to model layer. Loopback actually does something similar internally, but that logic is not exposed though an API to deal with it. Remove methods are not too much convenient and are confusing.

For instance, I'm missing something like:
```js
UserResource.getEntries() // -> Retrieve all the configured HTTP-level resources = verb + path
```

Then, you can for instance attach and override the default action, which should be a `function`:
 ```js
GetUserResource.attachAction(function (req) { ... })
```

This is just a idea that just come to my mind right now without thinking too much, but as brief example.

**Comment by h2non** [comment]
This could be done now with:
```js
User.disableRemoteMethod('findById', false) // -> GET
User.disableRemoteMethod('updateAttributes', false) // -> PUT
```
