### ISSUE TITLE
Querying nested included models isn't using the foreignKey and not using the scope filters

### ISSUE THREAD

**Issue by berill** [strongloop/loopback#1760]
Hi,

Trying to include model and related sub-model, but it doesn't seem to be taking into consideration the foreign key, nor the filter in sub-model scope.

Test to reproduce is:

1. a Writer model inheriting from User
2. the Writer has a relation hasMany towards Book (that inherits from PersistedModel)
3. the Writer has a relation hasMany towards SocialNetwork (that inherits from PersistedModel)

Writer's json:
```
{
  "name": "Writer",
  "base": "User",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "books": {
      "type": "hasMany",
      "model": "Book",
      "foreignKey": "id"
    },
    "socialNetworks": {
      "type": "hasMany",
      "model": "SocialNetwork",
      "foreignKey": "id"
    }
  },
  "acls": [],
  "methods": {}
}
```

Book's json:
```
{
  "name": "Book",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "from": {
      "type": "date"
    },
    "to": {
      "type": "date"
    },
    "userId": {
      "type": "string"
    },
    "title": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "writer": {
      "type": "belongsTo",
      "model": "Writer",
      "foreignKey": "userId"
    }
  },
  "acls": [],
  "methods": {}
}
```

SocialNetwork's json:
```
{
  "name": "SocialNetwork",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "userId": {
      "type": "string"
    },
    "network": {
      "type": "string"
    },
    "networkHandle": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "socialWriter": {
      "type": "belongsTo",
      "model": "Writer",
      "foreignKey": "userId"
    }
  },
  "acls": [],
  "methods": {}
}
```  

Sample code to try and retrieve all the books initiated and finished in the last year, plus their owner and their owner's facebook accounts if joined in the same time:

```javascript
	const network = 'Facebook';
	const initialDate = moment('2014-11-01T00:00:00.000Z');
	const endDate = moment('2015-10-01T00:00:00.000Z');


    app.models.Book.find({
      where: {
        and: [
          {from: {gte: initialDate}},
          {to: {lte: endDate}},
        ],
      },
      include: {
        relation: 'writer',
        scope: {
          include: {
            relation: 'socialNetworks',
            where: {
              and: [
                {network: network },
                {joined: {between: [initialDate, endDate]}},
              ],
            },
          },
        },
      },
    });
```

Using mysql connector, the above results in the following queries being called:

```
loopback:connector:mysql SQL: SELECT from,to,userId,title,id FROM Book WHERE (from>=?) AND (to<=?) ORDER BY id, params: ["2014-11-01 00:00:00","2015-10-01 00:00:00"] +313ms
  loopback:connector:mysql Data:  +16ms [ RowDataPacket {
    from: Mon Dec 01 2014 00:00:00 GMT+0000 (GMT),
    to: Thu Jan 01 2015 00:00:00 GMT+0000 (GMT),
    userId: 5,
    title: 'Test Book',
    id: 10 } ]
```
```
loopback:connector:mysql SQL: SELECT firstName,lastName,realm,username,password,credentials,challenges,email,emailVerified,verificationToken,status,created,lastUpdated,id FROM Writer WHERE id IN (?) ORDER BY id, params: [5] +9ms
  loopback:connector:mysql Data:  +3ms [ RowDataPacket {
    firstName: 'First',
    lastName: 'Name',
    realm: 'Realm',
    username: 'firstname',
    password: '',
    credentials: null,
    challenges: null,
    email: '',
    emailVerified: null,
    verificationToken: null,
    status: null,
    created: null,
    lastUpdated: null,
    id: 5 } ]
```
```
loopback:connector:mysql SQL: SELECT userId,network,networkHandle,id FROM SocialNetwork WHERE id IN (?) ORDER BY id, params: [5] +4ms
  loopback:connector:mysql Data:  +2ms []
```

So it looks like the scope for the sub-model's relation 'socialNetworks'  is actually loaded up without:
1. taking into consideration the filter in the scope 
2. using the foreignKey defined for the SocialNetwork model

**Comment by berill** [comment]
Hi guys,
sorry had reported the bug late at night and forgot to actually check your reporting issue guideline. doh.

Here is the forked repo: https://github.com/berill/loopback-sandbox/

Steps to reproduce are included in the commit, but copied here anyway:
- npm update && npm install
- node_modules/mocha/bin/mocha test/sub-model-test.js

I'd say it is a datasource-juggler problem, seeing that the test above reproduce it in the memory connector too.

Let me know if you want me to re-open the issue there or what.

**Comment by berill** [comment]
After a chat in the gitter channel, it turns out the subquery was wrong as it was missing the scope { } around the where.

I've pushed the correct commit in the forked repo, and that now works with the mysql connector. 

However the unit test with the memory connector is still failing.

Correct query:
```
app.models.Book.find({
        where: {
          and: [
          {from: {gte: initialDate}},
          {to: {lte: endDate}},
          ],
        },
        include: {
          relation: 'writer',
          scope: {
            include: {
              relation: 'socialNetworks',
              scope: {
                where: {
                  and: [
                  {network: network },
                  {joined: {between: [initialDate, endDate]}},
                  ],
                },
              },
            },
          },
        },
      });
```

**Comment by 0candy** [comment]
Hi,

It appears that what you're trying to do is not supported:
https://github.com/strongloop/loopback/issues/517#issuecomment-71796806

Can you confirm whether that's what you're encountering?  If so, I will close this as a dup of that issue.

Thanks!

**Comment by berill** [comment]
Hi Candy,
as far as I can see, it sort of does. feel free to close this up and mark as a dup of the other one.

Sorry for not picking it up before. I will like to point out though, that this particular query does work for mysql connector, as in: it doesn't filter it if the nested query doesn't have the related item, but at least it returns it when it exists.

**Comment by 0candy** [comment]
Hi Berill,
Interesting that it works for you. I tried running your code and the nested query still doesn't return the social network item for me.

I will close this as a dup of the other issue. https://github.com/strongloop/loopback/issues/517

Thanks.
