### ISSUE TITLE
access tokens in the query parameter 

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback#1764]
Is there anyway to disable access tokens passed in the query parameter ?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by mike-aungsan** [comment]
https://groups.google.com/forum/#!topic/loopbackjs/ehQyypHegLw
