### ISSUE TITLE
Not getting parent relation in Angular SDK

### ISSUE THREAD

**Issue by djaney** [strongloop/loopback#1765]
I'm trying to query the UserIdentitiy and include the user model. but the user data does not appear in the result. It works If I query User and include identity but not the other way around.

The Query:

                    return UserIdentity.find({
                        filter:{
                            include:'user',
                            limit:params.count(),
                            skip:(params.page() - 1) * params.count(),
                            order:params.orderBy()[0].substring(1) + (params.orderBy()[0][0]==='+' ? ' ASC' : ' DESC')
                        }

                    });

User Model:

    "relations": {
        "identity": {
            "type": "hasOne",
            "model": "UserIdentity",
            "foreignKey": "userId"
        },
    }

UserIdentity Model:

    "relations": {
        "user": {
            "type": "belongsTo",
            "model": "User"
        }
    },

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongl    oop/loopback/wiki/Reporting-issues#bug-report
