### ISSUE TITLE
Document nestRemoting

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1767]
Need to add [nestRemoting](https://github.com/strongloop/loopback/blob/master/lib/model.js#L663) both to API docs and to relations docs.  See http://blog.brainfock.org/2015/10/23/loopback-tip-of-the-day-nest-remoting/

Also see test at https://github.com/strongloop/loopback/blob/master/test/relations.integration.js#L1326

Also:
nestRemoting is a function, and you call it like this:
`Book.nestRemoting('pages');`
you can dig around in the unit tests for examples. I believe what this function does is enable nested remoting for a specific relation.  For example, if you have `User/Orders/Products/Parts`
you might call `User.nestRemoting(‘orders’)` and then you would get your remotes extended to include `/api/Users/123/orders/456/products`
I believe you have to do it for each level, it doesn’t automatically cascade

**Comment by crandmck** [comment]
Review Amir's draft in https://docs.strongloop.com/display/LB/New+doc+for+nestRemoting

**Comment by Amir-61** [comment]
I need to add doc for API doc as well

**Comment by crandmck** [comment]
@Amir-61 Please see https://github.com/strongloop/loopback/pull/1847.

**Comment by Amir-61** [comment]
Hey @crandmck,

I have applied changes for [nested queries doc](https://docs.strongloop.com/display/LB/Nested+queries) and added info for [Loopback API doc](https://github.com/strongloop/loopback/pull/1847) as well; please close this ticket if you think they are all good.

Thanks!

**Comment by crandmck** [comment]
Doc changes look good, and I have opened up that doc to pubic access.
API doc changes also look good, but I want to confirm that the CI failures are not a problem.  Should be able to merge that soon.
