### ISSUE TITLE
Error! Process out of memory.... Do Strongloop loopback app by default uses multiple processes? 

### ISSUE THREAD

**Issue by rizvanhaider** [strongloop/loopback#1772]
I have created a loopback.io project which creates rest API of a MySQL table which contains more than 150,000 records, the rest API takes 30 seconds to retrieve specific(3) columns, I also have more two tables which are also big like this table, after combining these all the rest will go too slow.. Now I have 4 questions

Is this loopback project bydefault uses multiple process/threads?
If I have to separately do this step (i.e. process management) then how I will do it? (I have gone through documentation I am confused...)
is Strongloop Process Manager free for commercial use?
What should I do to increase the performance of REST

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

>Is this loopback project bydefault uses multiple process/threads?

Node.js is single threaded.

>is Strongloop Process Manager free for commercial use?

See https://strongloop.com/node-js/subscription-plans/ for pricing.
