### ISSUE TITLE
node.js 4.1.2 support

### ISSUE THREAD

**Issue by topazas** [strongloop/loopback#1773]
For simple testing in Ubuntu 14 and node.js 4.1.2 LTS it does not work with multiple problems. Any plan to support newer version of node.js?

**Comment by raymondfeng** [comment]
Can you elaborate the problems?

**Comment by Pentiado** [comment]
I'm running LoopbackJS on 4.2.1 on few different OSes including Ubuntu and works perfectly fine

**Comment by topazas** [comment]
Please close. I think it was some misconfiguration in systems. It works.
