### ISSUE TITLE
loopback-component-explorer production disabling cause error

### ISSUE THREAD

**Issue by echmykhun** [strongloop/loopback#1774]
Hello!
I just wanted to test production config of my application. I set NODE_ENV to "production" and called node server/server.js and it returned me this:

>/vagrant/node_modules/loopback-boot/lib/config-loader.js:239
    throw new Error('Cannot apply ' + fileName + ': ' + err);
    ^
Error: Cannot apply /vagrant/server/component-config.production.json: Cannot merge values of incompatible types for the option `loopback-component-explorer`.
    at mergeComponentConfig (/vagrant/node_modules/loopback-boot/lib/config-loader.js:239:11)
    at mergeConfigurations (/vagrant/node_modules/loopback-boot/lib/config-loader.js:138:5)
    at loadNamed (/vagrant/node_modules/loopback-boot/lib/config-loader.js:76:16)
    at Object.ConfigLoader.loadComponents (/vagrant/node_modules/loopback-boot/lib/config-loader.js:56:10)
    at compile (/vagrant/node_modules/loopback-boot/lib/compiler.js:60:20)
    at bootLoopBackApp (/vagrant/node_modules/loopback-boot/index.js:139:22)
    at Object.<anonymous> (/vagrant/server/server.js:21:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

here is my component-config.production.json
```javascript
{
  "loopback-component-explorer": false
}
```

and middleware.production.json
```javascript
{
  "final:after": {
    "loopback#errorHandler": {
      "params": {
        "includeStack": false
      }
    }
  }
}
```

Here is my slc -v

>slc -v
strongloop v5.0.1 (node v4.2.1)
├── strong-arc@1.8.3 (d95b140)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.0 (46b06b4)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.12.1 (a374136)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

And i failed to understand why it crushes and why it shows stacktrace on it's crush

Could you help, please?

UPD: same problem with node v4.0.0

**Comment by Neil-UWA** [comment]
I suppose in your component-config.json, looks like :

```
{
  "loopback-component-explorer": {
    "mountPath": 'xxxx'
  }
}
```

The problem here is that when you set NODE_ENV to production, the merge utility of loopback will try to merge a boolean (in this case , false in your component-config.production.json) with Object and it fails to merge them. 

The simplest way to disable explorer is to remove explorer.js and the component-config.{}.json file entirely in your production server. That is what I do.

**Comment by pavlin99th** [comment]
Another workaround:

- **component-config.production.json** as suggested:
```json
{
  "loopback-component-explorer": false
}
```
- rename **component-config.json** to **component-config.development.json**:
```json
{
  "loopback-component-explorer": {
    "mountPath": "/explorer"
  }
}
```
- create **component-config.json** with just:
```json
{
}
```

**Comment by richardpringle** [comment]
Hey @echmykhun can you provide a sample repo for me to reproduce the issue, please? https://github.com/strongloop/loopback/wiki/Reporting-issues

**Comment by mastertinner** [comment]
I'm having the same problem. While @pavlin99th's solution provides a temporary fix (thanks for that!), I think the right solution would be to completely replace the config object if the value in the production file is a boolean with the value ```false``` as in:
```json
{
  "loopback-component-explorer": false
}
```

**Comment by gausie** [comment]
@mastertinner's idea is a good one!

**Comment by Neil-UWA** [comment]
@mastertinner  agreed +1

**Comment by Ijmir** [comment]
+1

**Comment by johannesjo** [comment]
Why is this closed? How @mastertinner describes it, is how it should actually work in general when merging configurations.

**Comment by Neil-UWA** [comment]
@echmykhun so you don't think this is a  problem that loopback need to solve?

**Comment by 255kb** [comment]
same problem here, no need for a repo to reproduce the issue, just follow the documentation: https://docs.strongloop.com/display/public/LB/Environment-specific+configuration#Environment-specificconfiguration-DisablingAPIExplorer

**Comment by jamesjjk** [comment]
@echmykhun Should re-open and accept PR.
