### ISSUE TITLE
dynamic relationship by code not working with random model

### ISSUE THREAD

**Issue by nasihere** [strongloop/loopback#1776]
When i removed relations from Customer.Json and Review.json and try to do the same relationship by code. Why isn't showing me expected results? What i am doing wrong

  var Customer = app.models.Customer;
  var Review = app.models.Review;

   Customer.hasMany(Review, { as: 'customer', foreignKey: "authorId" })
   Review.belongsTo(Customer, { as: 'review', foreignKey: "authorId" })
     Customer.find({}, function (err, accts) {
        console.log(accts)
    });
Output:
[ { name: 'Customer A', age: 21, id: 1 },
  { name: 'Customer B', age: 22, id: 2 },
  { name: 'Customer C', age: 23, id: 3 },
  { name: 'Customer D', age: 24, id: 4 },
  { name: 'Customer E', age: 25, id: 5 } ]

Expecting 
[ { name: 'Customer A', age: 21, id: 1, review: { product: 'Product1', star: 3, authorId: 1, id: 1 } },            
  { name: 'Customer B', age: 22, id: 2, review: { product: 'Product2', star: 2, authorId: 2, id: 2 }},            
  { name: 'Customer C', age: 23, id: 3, review: { product: 'Product5', star: 5, id: 3 } },            
  { name: 'Customer D', age: 24, id: 4, review: {}},            
  { name: 'Customer E', age: 25, id: 5, review: {}} ]           
                                                     
Can somebody please help do to relationship by code. bcoz my repository class has to two parameter one it accept any model and other param accept relationship name (hasmany,belongsto) but simple relationship not works when i don't defined relations in model.json

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
