### ISSUE TITLE
adding route specific middleware

### ISSUE THREAD

**Issue by iblazevic** [strongloop/loopback#1777]
I've read through documentation and couldn't find a solid example on how to exactly add route specific middleware.

To illustrate what that means, we have custom authorization middleware that we had to make for this specific project and its configurable for specific routes.

In express it would look something like this:

    router.route('/someRoute')
      .get(
        customAuthorize(customParams1),
        someController1
      )
      .post(
        customAuthorize(customParams2),
        someController2
      );

However, in the documentation its not really clear whats the best way to do it.

Most obvious way seems to be to use remote hooks, I'm just wondering is that the best approach for this is something like this:

    module.exports = function(Review) {
      Review.beforeRemote('create', customAuthorize(customParams1));
    };

Can someone please confirm this is the right way, and could we put it somewhere in the documentation for future.

Thanks

**Comment by superkhau** [comment]
@crandmck ^

**Comment by superkhau** [comment]
Oops, accidentally closed it.

**Comment by crandmck** [comment]
IIUC, docs currently say to do it the same as in Express: https://docs.strongloop.com/display/LB/Defining+middleware#Definingmiddleware-Routingmiddleware.

@bajtos Is the above a good way to add route-specific mw?  Should we add an example like that to docs?

**Comment by bajtos** [comment]
My recommendation is to configure all middleware via `server/middleware.json`. The file format allows configuration of multiple middleware instances limited to a list of paths and verbs.

```json
{
  "auth": {
    "customAuthorize": [
      {
        "paths": ["/someRoute"],
        "verbs": ["GET"],
        "params": ["customParams1"]
      },
      {
        "paths": ["/someRoute"],
        "verbs": ["POST"],
        "params": ["customParams2"]
      }
    ]
  }
}
```

**Comment by crandmck** [comment]
@bajtos If that's the best practice recommendation for _all_ middleware, then I will change [the doc section](https://docs.strongloop.com/display/LB/Defining+middleware#Definingmiddleware-Routingmiddleware) that says to define routes the "Express way".  OK?  

Also, this example is for authorization, but normally routing would be set in the `routes` phase, right?

**Comment by iblazevic** [comment]
Can it somehow be divided into multiple files, doing it this way may cause middleware.json to become really big and hard to manage?

**Comment by bajtos** [comment]
@crandmck routes serving non-JSON responses should be defined the "Express way". For routes serving JSON, I would recommend creating a new `Model` and implementing these routes as regular remote methods.

As I understand this issue (the original question), @iblazevic is asking how to configure additional middleware that should be limited to certain routes only. I feel this may be a very specific use case that may not need documentation entry. Both solutions - declarative configuration in `server/middleware.json` and code-first setup described in the issue description - are valid.

@iblazevic Not really. You can create `server/middleware.local.js` and load & combine multiple config sources there, but that's far from ideal. If you have many routes with a lot of per-route middleware, then it's probably the best to use the approach you have described in the issue description above.

**Comment by crandmck** [comment]
OK, thanks @bajtos, I clarfied the statement in the docs to reflect this.  I'm going to close this now as I believe we've addressed it.
