### ISSUE TITLE
Password data type

### ISSUE THREAD

**Issue by ghost** [strongloop/loopback#1778]
Perhaps loopback should support Password data type off the box since doing this in connector level means cleartext passwords end up to query logging.

Many apps do not encrypt their passwords and for the average joe user writing custom hooks/queries within loopback to do this would be beyond their depth level especially if the dev is non-security focused as typically is the case.

Ideal candidate to me would be built-in User model to support using bcrypt with properly salted hashes for any Passwords off the box, thus having separate datatype would be great.

I raised separate Postgres connector related feature request here for wrapping pgcrypto/other funcs etc. into ?'s placeholders:
https://github.com/strongloop/loopback-connector-postgresql/issues/113

**Comment by titusfoo** [comment]
Thinking around this beyond the box.. would be great to have custom type hooks that are cast'able.. e.g. if custom type "Passwords" is cast into certain connector/use, thing happens for which one can write .js and off the box there is Password - where also cast back to presentation would just overwrite with 'hidden' or something if somebody forgot to hide the property in first place.

**Comment by FluxAugur** [comment]
:+1:
