### ISSUE TITLE
Custom Cast'hook'able Data Types

### ISSUE THREAD

**Issue by ghost** [strongloop/loopback#1779]
Continuing from #1778 Password Data Type, raising this as separate for more versatile solution where Password could be reference implementation;

Would be great to have application wide custom types that are hookable when casted around difference places (presentation, data stores etc.)..

e.g. if custom type "Passwords" is cast into certain connector/use, translation happens from type cast hook(s) for which one can write .js just like hooks in general but in type level globally app wide.

off the box where there could be Password type as an example - that has two cast hooks:

into hash form could be triggered when persistency is done (data store) per connector
and presentation with static 'hidden' String if somebody forgot to hide the property in first place instead of providing the raw hash (bad bad) or cleartext password like now

Perhaps something like that calls .toString() for any string target etc.

Other Custom data types that come to mind are:

Base64, MD5, CRC32 etc common stuff which can have .toString() when casted to JSON String and data store

Naturally when doing a hook, it would be bad to assume the original form e.g. hash could be hashed again so source data type "form" must be known?

**Comment by FluxAugur** [comment]
:+1:

**Comment by EthraZa** [comment]
I was just searching for this. 
I just created a model to hold credentials for another web APIs to integrate with and found there is no easy way to hash my password fields. That is sad because I now Loopback knows how to do that since it have it builtin in the User model.
So, +1
