### ISSUE TITLE
creating entity with relation stores the foreign key as plaintext instead of ObjectID

### ISSUE THREAD

**Issue by Ijmir** [strongloop/loopback#1781]
I have feeds and comments models.
comments belongsTo feeds with foreign key **feedRef** and relation name **feed**.
feedRef field is an ObjectID - defined in boot script.

```javascript
{
  "name": "comments",
  "base": "PersistedModel",
  "idInjection": true,
  "validations": [],
  "relations": {
    "feed": {
      "type": "belongsTo",
      "model": "feeds",
      "foreignKey": "feedRef"
    }
  },
  "acls": [],
  "methods": [] 
}
```

1) When I save a comment with **feed** object (with _id) attached I see that in mongodb feedRef is stored as plaintext and **feed** is discarded
2) When I save a comment with **feedRef** attached I see that in mongodb feedRef is stored as ObjectID

From 1) I understand that create handles the relation because it translates feed to feedRef, but the ObjectID is plaintext. In 2) I can see that ObjectID is stored correctly.

Is it a bug? or create method with relations shouldn't have been working in the first place?
*maybe related to loopback-connector-mongodb or loopback-datasource-juggler

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by Ijmir** [comment]
I'll recreate the issue in loopback-connector-mongodb with the forked repo

**Comment by loay** [comment]
Hi @Ijmir I will close this issue in favor of this one: https://github.com/strongloop/loopback-connector-mongodb/issues/186
Thanks
