### ISSUE TITLE
Command line for printing swagger.json

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#1783]
As a LoopBack dev, I should be able to export my api def as swagger, so that I do not have to run my app and curl http://localhost:3000/explorer/swagger.json.

```
$ slc loopback:export-api-definition
```

By default it should output the swagger document as yaml.

It should take a couple opts.

```
$ slc loopback:export-api-definition --json
```

That would output JSON instead of yaml.

Also, I should be able to use the output of the api-def tool as the input of another tool.

```
slc loopback:api-definition | apim publish-api-definition
```

**Comment by bajtos** [comment]
Sounds like a useful feature to me! :+1:

**Comment by chandadharap** [comment]
Need to assign to Candy

**Comment by bajtos** [comment]
Proposed implementation:
 - implement a command-line tool in loopback-swagger repository
 - add this tool as a new slc command, e.g. `slc export-swagger`
