### ISSUE TITLE
REST naming conventions and consistency

### ISSUE THREAD

**Issue by sinedied** [strongloop/loopback#1785]
It there a way to setup the default naming convention for REST API exposition? I did not find in documentation, in this case this may be a possible evolution.

I am bothered as by default, `PascalCase`, `camelCase` and `snake-case` is mixed in exposed endpoints. For example, any *PersistedModel* has the `/findOne` and `/change-stream` endpoints. Is there a way to uniformize that?

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
The remoting property `rest.normalizeHttpPath` controls the naming convention for model REST endpoints. See 
See https://docs.strongloop.com/display/LB/config.json#config.json-Remotingproperties

As far as the naming convention for PersistedModel endpoints, that is a design choice/eng. feature, not a doc issue.  Not sure what I'm supposed to do with this. @superkhau is there something else that needs to be added to docs?

**Comment by superkhau** [comment]
@crandmck Thanks. One thing we should note is the naming convention for persisted model endpoints are not changeable and a design/engineering choice. I believe one of the todo items for LB3 is to make this more flexible (ie. user customizable).

**Comment by sinedied** [comment]
Thanks, `rest.normalizeHttpPath` should mame me happy ;)

I agree that the naming convention are design choices, it is sad though that the same convention are not consistently applied everywhere for the base model. But since the normalization option should fix it, it is more a matter of polish than a real issue then.

**Comment by crandmck** [comment]
> we should note is the naming convention for persisted model endpoints are not changeable

Added a note to https://docs.strongloop.com/display/LB/PersistedModel+REST+API.

**Comment by sinedied** [comment]
I used the `rest.normalizeHttpPath` option but this did not fix the `findOne` endpoint, where it should be transformed to `find-one`. This bug may be related to #608 .

**Comment by Cisneiros** [comment]
Sorry for bumping an old issue, but I've searching the whole repo for a solution and I cannot find. The docs say to set `remoting.rest.normalizeHttpPath = true` to change the URL naming convention to small-caps-with-dashes, but this seems to change nothing at all. Setting it at model level only changes the model name part of the URL to small-caps, but method names stay camelCased.

Is there something I'm doing wrong, or is this a known issue?

**Comment by crandmck** [comment]
@0candy PTAL.  Not sure if this is a bug or not.... If a bug, then we should probably open a new issue, or maybe just remove the "doc" label and change assignee for this one.

**Comment by 0candy** [comment]
@Cisneiros  Are you setting this in config.json?

Have you tried this? https://github.com/strongloop/loopback/issues/608#issuecomment-121836496

**Comment by 0candy** [comment]
@Cisneiros Looks like this flag is only applied to class and not methods.
https://github.com/strongloop/strong-remoting/blob/192ee9b74c150f7ec5a02e9b027187638b0eba2e/lib/shared-class.js#L38

**Comment by Cisneiros** [comment]
@0candy Basically I'd like to have routes like `/users/find-one` instead of `/Users/findOne`. According to the documentation (emphasis added):

> You can't customize the routes to PersistedModel REST API endpoints. However, **you can control how REST API endpoints are constructed** from custom models with the rest.normalizeHttpPath property in server/config.json; for more information, see config.json (Remoting properties).
[https://docs.strongloop.com/display/public/LB/PersistedModel+REST+API]

My understanding is that setting `rest.normalizeHttpPath` to `true` would change all the persisted model generated routes from PascalCase and camelCase to lower-case-with-dashes.

When I set this to `true` at `server/config.json`, nothing changes on the app. I think I'm either missing something obvious or I didn't understand what this flag means.

**Comment by 0candy** [comment]
You did not misunderstand the flag. However, there is an issue already for that flag not working. https://github.com/strongloop/loopback/issues/608

You can at the moment set it in model.json, but that only works on the model name not on the method itself.

`properties: { ... },
remoting: {
  normalizeHttpPath: true
}
`

**Comment by Cisneiros** [comment]
@0candy I see. Quick question: is the behaviour of only working on the model name and not the method itself when you define the flag at model level expected, or is it a bug?

**Comment by 0candy** [comment]
Its not a bug, just that the code was not implemented. https://github.com/strongloop/loopback/issues/608 is requesting the feature for setting `rest.normalizeHttpPath` to work so this doesn't have to be done at the model level.
