### ISSUE TITLE
Admin page after login

### ISSUE THREAD

**Issue by groupsvkg** [strongloop/loopback#1786]
Hi Team,

I have created a boot script to create admin role and assigned it to a user.

Am using angularjs sdk on client side. Trying to figure out how land a user to different page when user is "admin".

Not able to get role associated with user on client side after login.

Regards,
vishal

**Comment by superkhau** [comment]
Can you provide a link to a test project on GitHub? See https://github.com/strongl    oop/loopback/wiki/Reporting-issues#bug-report

**Comment by groupsvkg** [comment]
Hi superkhau,
i will share the test project but ......basically i want to know the correct syntax of clientside login api to inclues role in response

in login response i want to know user's role so that i can render correct page.

```javascript
User.login({include: ['user', 'roles']}, {username: username, password: password})
        .$promise
        .then(function(response) {
             ................here i need role in response.......
        }
```

**Comment by superkhau** [comment]
Login: https://github.com/strongloop/loopback-getting-started-intermediate/blob/master/client/js/services/auth.js#L5

Including other models using Angular SDK: https://github.com/strongloop/loopback-getting-started-intermediate/blob/master/client/js/controllers/review.js#L6-L11

Combine the two together and see if it works for you. Let me know if you run into more issues.

Also, for future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
