### ISSUE TITLE
Loopback creates a domain with no error handler

### ISSUE THREAD

**Issue by priyavivek1** [strongloop/loopback#1787]
It does that here: https://github.com/strongloop/loopback/blob/9a33602458712afecedd25062f02bd8b5c4e01a5/server/current-context.js#L35

And that's a problem, because node doesn't invoke the uncaughtException handler when a Domain error goes uncaught. See https://github.com/nodejs/node/issues/3607.

Loopback should have a reasonable default error handler, or provide me with an API to install one.

cc @piscisaureus

**Comment by ironbuzz-ilya** [comment]
Domains are deprecated according to the Node.js docs - https://nodejs.org/api/domain.html.

Will Loopback implement an alternative? We are using domains to pass request into entity classes
