### ISSUE TITLE
Remote method request PENDING

### ISSUE THREAD

**Issue by seminice** [strongloop/loopback#1788]
I'm using remote method like this 
```
   Reply.rate = function(req,res,cb){
      var Rate = Reply.app.models.Rate;
      var userId = req.accessToken.userId;
      var replyId = req.body.replyId;
      Rate.create({
         "userId": userId,
         "replyId": replyId
      }, function(err, rate){
         console.log(rate);
      });
   };
   Reply.remoteMethod (
      'rate',
      {
         http: {path: '/rate', verb: 'post'},
         accepts: [
            { arg: 'req', type: 'object', 'http': {source: 'req'}},
            { arg: 'res', type: 'object', 'http': {source: 'res'}},
         ],
         returns: {arg: 'stats', type: 'string'}
      }
   );
```

when I call the method from my angular app
```Reply.rate({replyId: replyId}, cb);```
The request hangs pending, it works and adds a rate to the reply model , but it stuck pending,
I'm using a similar remote method to upload videos and images and its the same, the request is pending.
Anything Im missing here?

**Comment by superkhau** [comment]
```
...
}, function(err, rate){
  console.log(rate);
  cb() // you didn't call the callback
});
```

For future reference, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by seminice** [comment]
Thank you! and I'm really sorry I thought it was an issue since I implemented that after upgrading to the latest loopback.

**Comment by superkhau** [comment]
NP, next time try checking out the forums, Google search, etc. You can also get some live support from the community at our [Gitter channel](https://gitter.im/strongloop/loopback). Worse case is you ask here and one of the LoopBackers will let you know if its really an issue. Have fun. ;)
