### ISSUE TITLE
Why LoopbackJS doesn't set values for emailVerified and verificationToken?

### ISSUE THREAD

**Issue by wzup** [strongloop/loopback#1796]
I have created a custom `Client` model whose base class is a built-in `User` model. I used command-line tool `slc loopback:model` for it. An automatically created config for the model is as follows (`common/models/client.json`):

    {
      "name": "Client",
      "plural": "Clients",
      "base": "User",
      "idInjection": true,
      "properties": {},
      "validations": [],
      "relations": {},
      "acls": [],
      "methods": []
    }

So as I understand my custom `Client` model has all the properties and behavior of `User` model.

Now I want to create some `Client` instances and insert them in MongoDB. The docs says about `POST` `/users` HTML requests for creating a new DB entry that Loopback sets some values automatically (https://docs.strongloop.com/display/public/LB/User+REST+API):

> JSON object (in request body) providing User object properties:
> username, password, email. **LoopBack sets values for emailVerified and
> verificationToken**.

But when I run my script, niether `emailVerified`, nor `verificationToken` are set. DB is populated only with the values I pass as a `POST` body. Here is my code:

    ds.automigrate(collections, function(er) {
        if (er) throw er;
        console.log('Looback tables [' + collections + '] created in ', ds.adapter
            .name);
    
        server.models.Client.create([{
            username: 'admin',
            password: "admin",
            email: 'admin@gmail.com',
            dtCrt: new Date()
        }, {
            username: 'admin2',
            password: "admin2",
            email: 'admin2@gmail.com',
            dtCrt: new Date()
        }], function(err, newClient) {
            ds.disconnect();
            process.exit();
        });
    });

And here is a result. No `emailVerified` and `verificationToken` values are set:

    [ { username: 'admin',
        password: '$2a$10$EdyVnfIATxoOzI6vUeV3POIgKGomY/gtKRXfoWcrTRWZDm0dKl41y',
        email: 'admin@gmail.com',
        dtCrt: Sun Nov 01 2015 20:08:23 GMT+0800,
        id: 563600b85e1c289829390e48 },
      { username: 'admin2',
        password: '$2a$10$ya6yf7iGraPGPvhjtVunZeug1i7/aTF8aSn.mYlqF0zUNVO73DJ8e',
        email: 'admin2@gmail.com',
        dtCrt: Sun Nov 01 2015 20:08:23 GMT+0800,
        id: 563600b85e1c289829390e49 } ]

Why? How to make Loopback set those values as its docs says?

**Comment by richardpringle** [comment]
@crandmck ^

**Comment by Smileo** [comment]
Hello @0candy  ) Any information about status for task? I can investigate and fix it. Please assign it to me.

**Comment by crandmck** [comment]
@loay Perhaps you could advise on this issue?  Is it a bug or an issue with docs?

**Comment by loay** [comment]
Hi @crandmck @Smileo @wzup 

Actually the documents are correct. Loopback does create both `emailVerified` and `verificationToken`.

We can use this repo as a perfect example for that: https://github.com/strongloop/loopback-example-user-management
I will type it step by step so you can see how both got created. 

1) in `server/datasource.json`, please add ` "file":"db.json" ` in db so you can see the users being created in a file called db.json in the root directory. 
```
  "db": {
    "name": "db",
    "connector": "memory",
    "file":"db.json"
  },
```

2) run the app: `node .`
3) go to the browser and in the sign-up form, please type in your email and password. 
4) in `db.json`, you should see something similar to that. 
```
 "user": {
      "1": "{\"password\":\"$2a$10$8DDZPKQMzX2GkpGhpANO2.Znoq/nf1rWxq4bj6xxdJmjgk6q9QD5i\",\"email\":\"myEmail@gmail.com\",\"id\":1,\"verificationToken\":\"e9426e4a57b895a19615d537bf1ccfe57a450a9826a6e3f40a47172f1b80d357579673bd3e2854c5d2094d5be4fa62f104e232722ad7a66b4b68ee2ecb08e9ad\"}",
  }
```

5) If you use the login form, it will give an error since the email has not been verified. 
6) Now, you can setup the email connector and verify the email and things then you will see something similar to 

```
 "user": {
      "1": "{\"password\":\"$2a$10$8DDZPKQMzX2GkpGhpANO2.Znoq/nf1rWxq4bj6xxdJmjgk6q9QD5i\",\"email\":\"myEmail@gmail.com\",\"id\":1,\"verificationToken\":\"e9426e4a57b895a19615d537bf1ccfe57a450a9826a6e3f40a47172f1b80d357579673bd3e2854c5d2094d5be4fa62f104e232722ad7a66b4b68ee2ecb08e9ad\", \"emailVerified\":1}"
  }
```
7) You can simply add the \"emailVerified\":1 part and you will see that it will work fine and give a welcome message with the accessToken. 


Please let me know if that answers your  question.

**Comment by loay** [comment]
@wzup 
Did the previous comment clarify things a bit? 
Has the issue been fixed or do you require more assistance? Please let me know. Thanks

**Comment by loay** [comment]
Also, I am assuming that this part below is already done. emailVerificationRequired needs to be set to true as per the docs here: https://docs.strongloop.com/display/public/LB/Registering+users

```
...
"user": {
    "dataSource": "db",
    "public": true,
    "options": {
      "emailVerificationRequired": true
    }
...
```
 If All that is done and the previous steps still show no data in your db file, can you please provide a sample of your repo so I can have a look. 

Thanks.
