### ISSUE TITLE
Encrypt a persistedModel property

### ISSUE THREAD

**Issue by shbhsngh** [strongloop/loopback#1798]
I have a property which need to be stored in encrypted format.
Note: this property is not a part of built-in User model and it is not a password

**Comment by jannyHou** [comment]
https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-beforesave

**Comment by shbhsngh** [comment]
Can you please explain how encryption can be done in loopback?

**Comment by superkhau** [comment]
LoopBack does not provide built-in encryption for properties. You can however use an operation hook (ie.`before save` to run some logic to encrypt the data) before persisting it to your data store.

As for the actual encryption, a Google search should give you some candidates such as https://nodejs.org/api/crypto.html.

If you need more support, try asking on our Google Groups or Gitter channel (check the links provided by @jannyHou above). If the matter is urgent, we offer paid support as part of our offerings (see https://strongloop.com/node-js/subscription-plans/).
