### ISSUE TITLE
Integrating Middle Gear with Loopback

### ISSUE THREAD

**Issue by behzadeshan** [strongloop/loopback#1801]
Hi,
I have released a new view engine named `Middle Gear`. Take look at it here https://www.npmjs.com/package/middle-gear
How can I integrate it with loopback?

**Comment by superkhau** [comment]
LoopBack only provides APIs. The view engine is up to the user to implement. What are you trying to do? Are you new to LoopBack?

**Comment by behzadeshan** [comment]
@superkhau Thanks. No I am not new to LoopBack. I know it only provides REST APIs. My intention is extending `Middle Gear` as it should be as a Middle Gear between application Logic and Presentation layers. After a couple of hours researching I found that LoopBack is the best option for handling the Logic layer. Now I want to merge LoopBack with Middle Gear and before doing, I need some advice and suggestions. I asked this question here because I know LoopBack team has expertise about such things, I am looking for a documentation to help me with this: what features a presentation framework(with MVC architecture) should have, to be used in enterprise graded applications. For example I know it should support `Routing`, `Server Side Rendering`, what else?

**Comment by superkhau** [comment]
Thanks for the clarifying. I think we can find the right people to chime in.

>I am looking for a documentation to help me with this...

With regards to docs, @crandmck can give you some pointers if you have specific questions.

>what features a presentation framework(with MVC architecture) should have, to be used in enterprise graded applications. For example I know it should support Routing, Server Side Rendering, what else?

It would be hard to come up with an exhaustive list of features as it really depends on what features you want to support. For example, not every enterprise graded framework needs to support "server-side rendering" (ie. LoopBack doesn't really besides EJS).

Anyways, I suggest you decide on what features you want to support (ie. a google search for other enterprise frameworks will tell you what you want to support), and then we can probably give you pointers on how to connect that particular feature to LoopBack. I'm going close this issue as it's too open ended and has no reasonable resolution. Feel free to open a new issue when you have a specific LoopBack question and I'll answer there instead.

**Comment by behzadeshan** [comment]
Ok. Thank you.
