### ISSUE TITLE
401 errors for User Model

### ISSUE THREAD

**Issue by vabnirvana** [strongloop/loopback#1809]
I am receiving login failed error and am not able to understand how should i proceed. I have inherited User as base for my model user. I am receiving:
{
  "error": {
    "name": "Error",
    "status": 401,
    "message": "login failed",
    "statusCode": 401,
    "code": "LOGIN_FAILED",
    "stack": "Error: login failed"
}

Any leads would be awesome. Thanks

**Comment by Amir-61** [comment]
Could you please provide a sample repo to re-produce the issue?
SEE: https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by vabnirvana** [comment]
I am facing this issue in the latest version of strongloop on mac that is "loopback": "^2.22.0".

**Comment by Amir-61** [comment]
@vabnirvana We need to see how you defined ACL and your models; please provide a sample repo to see how you defined them; that way we can give more precise feedback of what is defined wrong. Thanks!

**Comment by vabnirvana** [comment]
The User.json is as follow. It is a private repo so ill not be able to share it.

{
  "name": "user",
  "plural": "users",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "mongodb": {
    "collection": "User"
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "email": {
      "type": "string",
      "required": true
    },
    "password": {
      "type": "string",
      "required": true
    },
    "phone": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "question": {
      "type": "hasMany",
      "model": "question",
      "foreignKey": ""
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}

**Comment by Amir-61** [comment]
Hi @vabnirvana,

I tried your model and it works fine for me!

Some notes meriting consideration though:

1)You are defining email, password,.. properties, although they are already defined exactly the same way in the parent `User` model; please see: https://github.com/strongloop/loopback/blob/master/common/models/user.json;

2)For `ACL`s you are missing `accesstype`s, they are not right, but they do not break anything...For more info about ACL please see: https://docs.strongloop.com/display/public/LB/Define+access+controls

3)Also when you login please make sure you have posted a user and it is DB already.

4)My suggestion would be reproduce the issue using loopback-sandbox (Please see: https://github.com/strongloop/loopback-sandbox) and share it with us and open a new issue, if you cannot share the whole project in public.

Please let us know if that works and we can close this issue.

Thanks!

**Comment by vabnirvana** [comment]
Hi, Thanks following ur instructions make it work for me.

**Comment by ihebski** [comment]
While trying to parse the data using the GET method always failed .
Here is my solution to solve it .

You need to setup an access key in order to request the server for the data ,there is a user model when u access /explorer
![screen_1](https://i.imgur.com/94hAABA.png)

go to post and add a new user
![screen_1](https://i.imgur.com/bspYUXL.png)
`Note : delete id replace it with "password":"YOUR_PASS_HERE"`

Now go to POST /Users/login
past `{"username":"","password":""}`
![screen_1](https://i.imgur.com/6gpfACi.png)

now past the token in id field into Token set
![screen_1](https://i.imgur.com/AQxnmmb.png)
Everything is 200 ok now ! Happy hacking
