### ISSUE TITLE
can sl supports auto-generated createdAt and UpdatedAt ?

### ISSUE THREAD

**Issue by bboalimoe** [strongloop/loopback#1814]
Actually, I can do this job in the before save hook.but that's lame i think 
did loopback framework support this?
thanks

**Comment by jannyHou** [comment]
Hi @bboalimoe , we have no support for this features now. And yes as you mentioned, you can define the custom hook for your model. Thanks for your suggestion, I labeled it as feature.

**Comment by bboalimoe** [comment]
ok~ thanks and 
I know that IBM acquire strongloop. I wonder if sl would still be open source and continuously maintained ?

**Comment by Neil-UWA** [comment]
u can using mixins

**Comment by bboalimoe** [comment]
@Neil-UWA thanks~ great addon！

**Comment by jannyHou** [comment]
@bboalimoe hope this article would be useful to you:) https://strongloop.com/strongblog/ibm-express-loopback-node-js/

**Comment by superkhau** [comment]
@jannyHou Should the triage label be removed here?

**Comment by jannyHou** [comment]
@superkhau Sure, I removed it. Thank you for reminding me!
