### ISSUE TITLE
Strongloop Remote API changes

### ISSUE THREAD

**Issue by rmoetwil** [strongloop/loopback#1815]
A few days ago v2.23.0 was released.

We encountered differences in response for DELETE and POST update?where calls.
Returning 200 i.o. 204.

Can you update the online documentation and inform such changes in the release notes?

**Comment by kraman** [comment]
@superkhau Was this due to your fix?

**Comment by bajtos** [comment]
Here are the relevant commits:
 - REST API change: https://github.com/strongloop/loopback/commit/26af1472e75f98269fb5c10b31d39320958a8930
 - Node.js API change (one of several relevant commits): https://github.com/strongloop/loopback-datasource-juggler/commit/2120e53f7f64135dc5a97cf4425a0c41d4778493

**Comment by jannyHou** [comment]
Please check https://github.com/strongloop/loopback-datasource-juggler/blob/master/CHANGES.md for other related update

**Comment by crandmck** [comment]
Updated docs 
- [POST/update operation](https://docs.strongloop.com/display/LB/PersistedModel+REST+API#PersistedModelRESTAPI-Updatematchingmodelinstances)
- [DELETE operation](https://docs.strongloop.com/display/LB/PersistedModel+REST+API#PersistedModelRESTAPI-Deleteallmatchinginstances)

By default, `destroyAll` is not exposed over REST
