### ISSUE TITLE
Deprecate persistedModel.updateAttribute method in LB3

### ISSUE THREAD

**Issue by richardpringle** [strongloop/loopback#1817]
The `updateAttribute()` method of the persistedModel instance methods should be deprecated since it is redundant. The same functionality can be accomplished by using `updateAttributes()` (plural) and simply passing in an object with a single property `updateAttributes({name: 'value'}, cb)` as noted in the [api docs](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattribute).

**Comment by fabien** [comment]
Sure, it's redundant, but why deprecate it because of that? It's actually quite similar to: http://backbonejs.org/#Model-set

**Comment by richardpringle** [comment]
Hey @fabien, in the backbone example they actually have two different argument options for a single method. Right now, we have two different methods that can do the same thing. Having multiple arguments is okay but having two methods (especially that only differ by an 's') isn't necessary. 

Make sense?

**Comment by fabien** [comment]
@richardpringle sure, makes sense - which means you'd deprecate `setAttribute` as well then?
