### ISSUE TITLE
Why is ChainedContext.get private?

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback#1818]
For some reason ChainedContext.get is marked as private in the doc block:

https://github.com/strongloop/loopback/blob/master/server/current-context.js#L89

However, it is used in the documentation

https://docs.strongloop.com/display/JA/Using+current+context

Is it incorrectly marked?

**Comment by crandmck** [comment]
current context is exposed through [loopback.getCurrentContext()](https://apidocs.strongloop.com/loopback/#loopback-getcurrentcontext).

See https://github.com/strongloop/loopback/blob/master/server/current-context.js#L14

Doc is correct AFAICT.
