### ISSUE TITLE
Default scope condition overrides default value

### ISSUE THREAD

**Issue by geekguy** [strongloop/loopback#1821]
https://github.com/geekguy/loopback-sandbox/commit/adef36ff4d7d2ebf987f8d5e0f10649f2d49ba29

Remove db.json and restart server.

`checkDefault` should be "Default String" but its "Scope Condition String". 

Looks like a bug or am I missing something here?

**Comment by loay** [comment]
Hi @geekguy,

It doesn't look to be a bug. It is the property of the model definition JSON file. 
If you have a look at the Default scope part in the following document: 

https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes

The scope condition in m1.JSON does override any value.
For example,

So back to your case: 

In m1.json , if we do the same thing for the name, it will do the same thing even if we default the name string and it doesn't take the data-test.js function values either. 
```
  "scope": {
      "where": {
        "name":"scope Name",
        "checkDefault": "Scope Condition String"
      }
    }

```
it will give 
```
    "M1": {
      "1": "{\"name\":\"scope Name\",\"checkDefault\":\"Scope Condition String\",\"id\":1}",
      "2": "{\"name\":\"scope Name\",\"checkDefault\":\"Scope Condition String\",\"id\":2}",
      "3": "{\"name\":\"scope Name\",\"checkDefault\":\"Scope Condition String\",\"id\":3}"
    },
```

**Comment by geekguy** [comment]
@loay : This is little confusing.

Let me give you a real life example. 

Let's say I have a `Product` model and one field is 'isActive'. By default this field will be false. 
So product.json will look this this.

```
{
  "name": "Product",
  "base": "PersistedModel",
  "properties": {
    "isActive": {
      "type": "boolean",

    },
    "checkDefault": {
      "type": "string",
      "default": "Default String"
    }
  },
  "relations": {
    "m2s": {
      "type": "hasMany",
      "model": "M2"
    }
  },
  "scope": {
      "where": {
        "checkDefault": "Scope Condition String"
      }
    }
}

```

**Comment by geekguy** [comment]
@loay : This is little confusing.

Let me give you a real life example. 

Let's say I have a `Product` model and one field is 'isActive'. By default this field will be `false` and whenever I am querying, I ll append `where: {isActive: true}` because I only want to display active products.

So product.json will look this this.

```
{
  "name": "Product",
  "base": "PersistedModel",
  "properties": {
    "isActive": {
      "type": "boolean",
      "default": false
    }
  }
}
```

This will work fine. `isActive` will be `false` by default and I will add `isActive: true` for all of the queries on this model.
Now as per the [documentation](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes), default scope makes perfect sense so I ll add default scope like this.

```
  "scope": {
      "where": {
        "isActive": true
      }
    }
```

I thought it will just add default where condition on all my queries. but to my surprise 'isActive' is true by default ??

Its not mentioned in the documentation that scope will override field's default value and I don't think that's expected behaviour. 

Let me know if I am not clear about this or missing something here.

**Comment by loay** [comment]
@geekguy 
let's remove the default scope for the sake of testing .. the values created in test-data.js override the values in property default. 
So the order of power as I see it: 
1) default scope. 
2) test-data.js or any testing data in general. 
3) property default. 

So the scope default enforces the value in queries but if you remove the scope default .. the values fed in your data will have the upper hand .. if not, then it will go back to the default property.

**Comment by bajtos** [comment]
I think I know what is happening here.

The idea behind (non-default) scopes is to create a nested endpoint that always applies a set of filters to both READ and WRITE operations.

Relations are a typical example - both `GET /api/products/1/category` and `POST /api/products/1/category` will modify the query/post data by adding `productId: 1`.

Let's modify the `Product.isActive` example above to make an explicit scope:

```json
{
  "name": "Product",
  "base": "PersistedModel",
  "properties": {
    "isActive": {
      "type": "boolean",
      "default": false
    }
  },
  "scopes": {
     "active": {"where": {"isActive": true} }
  }
}
```

This will create a set of endpoints at `/api/products/active`, where `GET /api/products/active` queries active products and `POST /api/products/active` creates a new active product.

When the scope is set as default, the same implementation is used, i.e. `POST /api/products` applies all `where` properties to the model data and always creates active products.

@raymondfeng @fabien You are much more familiar with scopes than I am. What do you think about this issue? Is it intended behaviour? A bug?

I personally think @geekguy's use case is valid and we should support it. Perhaps we can add a new scope option allowing users to opt-out from applying the scope `where` filter on writes?

**Comment by raymondfeng** [comment]
@bajtos +1 to introduce a new option to control if the `where` clause should be used for `writes`. See https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/scope.js#L328. We can even add a `properties` for fixed values.

**Comment by bajtos** [comment]
@raymondfeng thanks. I am proposing to label this issue as an enhancement then. /cc @loay

**Comment by geekguy** [comment]
@bajtos : Now its clear to me from your comment
```
This will create a set of endpoints at /api/products/active, where GET /api/products/active queries active products and POST /api/products/active creates a new active product.
```

I couldn't find that kind of documentation [here](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes). Is it documented anywhere else?

I come from a rails background so I thought loopback's scope would be similar to [rails default scope](http://apidock.com/rails/ActiveRecord/Base/default_scope/class) (kind of read only).

Making this as an enhancement makes sense.

**Comment by Neil-UWA** [comment]
I think this problem also related to this one https://github.com/strongloop/loopback/issues/1701

**Comment by fabien** [comment]
IIRC I initially implemented `defaultScope` and I can confirm that it expected that scope will indeed enforce its values, both during READ as well as WRITE operations. The idea behind this decision is that one should not be able to bypass the scope (think ownership/multi-tenancy and similar scenarios).

I agree, an option to change this default behavior perhaps makes sense. However, some time after `defaultScope` was implemented, a more powerful concept was added: Operation hooks, and the `access` hook in particular. I suggest to use this if you need more control, and don't need API endpoints like `scopes` will give you.

**Comment by bajtos** [comment]
> I couldn't find that kind of documentation here. Is it documented anywhere else?

I'm adding a `doc` label to remind us to update the docs too.

**Comment by bajtos** [comment]
@fabien thank you for explaining the background of the `defaultScope` feature!

> I agree, an option to change this default behavior perhaps makes sense. However, some time after defaultScope was implemented, a more powerful concept was added: Operation hooks, and the access hook in particular. I suggest to use this if you need more control, and don't need API endpoints like scopes will give you.

@geekguy does the suggestion above work for you? I it does, then I would prefer to not make any changes and instead update the documentation to describe caveats of scopes together with a hook-based alternative for implementing a default scope that applies filters on reads only.

**Comment by geekguy** [comment]
@bajtos : Tried `access` hook. works for me.

Thanks @fabien for the information.

**Comment by bajtos** [comment]
Thank you @geekguy for the confirmation.

In which case I am labelling this bug as a doc task.

> update the documentation to describe caveats of scopes together with a hook-based alternative for implementing a default scope that applies filters on reads only.

**Comment by slgoldberg** [comment]
Can someone mark #1018 as a duplicate of this issue and/or otherwise link the two issues? I wrote up a proposed section to the documentation (though it assumes there's no flag; if there's a flag, it should be easy enough to replace the code sample in my write-up with the flag setting instead). Thanks a lot.

**Comment by hq-mobile** [comment]
This took me a while to understand but now it makes sense. It has however made implementing soft delete problematic.  Ideally I would like to have had the scope applied only to the read operation too i.e.

```
scope: {
  where: {
    is_deleted: false
  }
}
```

and have been able to set is_deleted in the delete (effectively update) operation.  However the documentation's current suggestion of:
```
var defaultScope = Report.defaultScope;
  Report.defaultScope = function(){};
  Report.upsert({id: reportId, 'deleted': true}, function(...) {
    Report.defaultScope = defaultScope;
    ...
  });
```

feels pretty hacky as it is incredibly hard to test. In the end the best solution for me was to unfortunately leak the details of soft delete to the client and have it query for the objects using the filter:

`filter[where][is_deleted]=false`

Is there a nicer way to handle this scenario?

**Comment by geekguy** [comment]
Hey @hq-mobile 

Take a look at https://github.com/strongloop/loopback/issues/1821#issuecomment-158466751

I tried that solution and it worked for me. 

My implementation:

```javascript
MyModel.observe('access', function(ctx, next) {
  if (!ctx.query.where) {
    ctx.query.where = {};
  }
  if (!ctx.query.where.hasOwnProperty('active') && ctx.Model.definition.properties.active) {
    ctx.query.where.active = true;
  }
  return next();
});
```

This will work as default scope. Each database query will have `active=true` condition. 

Let me if this is what you are looking for.

**Comment by hq-mobile** [comment]
That is exactly what I am looking for! Clearly did not spend enough time thinking about the problem, but you did! Nice one!!!

**Comment by MarkAndrewJohnson** [comment]
I'm now looking at this type of scenario as well.  However setting on 'access' is problematic because we just want to set the default on all find() queries, not findOne, findById, or similar.  In practise administrators need to be able to find drafts but users should never see them in the list (as just one example).  It would be great to have a default scope where option that was ONLY for the WHERE clause, allowing create/update to be independent.  This would certainly be cleaner allowing a relatively simple tweak to the model.json file.
