### ISSUE TITLE
Can you create a ChangeStream for a single item?

### ISSUE THREAD

**Issue by jbcpollak** [strongloop/loopback#1823]
The [documentation](https://docs.strongloop.com/display/public/LB/Realtime+server-sent+events) says you can watch a model for changes from the client like this:

```
var urlToChangeStream = '/api/MyModels/change-stream?_format=event-stream';
var src = new EventSource(urlToChangeStream);
src.addEventListener('data', function(msg) {
  var data = JSON.parse(msg.data);
  console.log(data); // the change object
});
```

But what if you want to watch just a single item for updates? Is the following possible?

```
var urlToChangeStream = '/api/MyModels/1/change-stream?_format=event-stream';
```

If this isn't automatic, is there a best-practices way to implement this with loopback?

**Comment by gunjpan** [comment]
@jbcpollak: Hi Joshua, I'm looking into this request. I am investigating a watch can be placed on a single model instance. Will udpate you soon with the outcome. Thank you.

**Comment by gunjpan** [comment]
Hi, apologies for a delayed reply! Current implementation of `change-stream` doesn't seem to be helping with tracking a single item from client. This can be a feature and there is a similar issue for it:
https://github.com/strongloop/angular-live-set/issues/11

Closing it for now. Please track the progress on above issue.
