### ISSUE TITLE
AccessToken.destroyAll doesn't work for "connector": "memory"

### ISSUE THREAD

**Issue by wzup** [strongloop/loopback#1830]
`AccessToken.destroyAll({ where: {userId: 1}})` doesn't work for `"connector": "memory"`. Doesn't delete entries.

**Comment by Amir-61** [comment]
Hi @wzup,

Thanks for reporting this bug! For now as a work around you can use `destroyById` to destroy a model instance with passing the ID, until this bug is fixed...

Thanks for reporting!

**Comment by Amir-61** [comment]
Hi @wzup,

The correct syntax is the following:

```
  AccessToken.destroyAll({userId: 3}, function(err, data){
    console.log("destroyAl, ERR:", err, ",number of Deleted items:", data.count);
  })
```

I tried it and it is working for memory connector as well. I will be closing this ticket...

Thanks!
