### ISSUE TITLE
api is user list

### ISSUE THREAD

**Issue by zanjs** [strongloop/loopback#1832]
List sorting and filtering criteria

**Comment by gunjpan** [comment]
@zanjs : Hi, Could you please provide me some more information on what you're trying to achieve here (i.e. is that a suggestion for a new feature, if yes, please provide more info.)
 Please see: https://github.com/strongloop/loopback/wiki/Reporting-issues

**Comment by gunjpan** [comment]
@zanjs : Hi, just following up on this issue. Could you please provide me with more information so that I can help you.

**Comment by gunjpan** [comment]
@zanjs : Hi, can you please provide me more information to help you out here. Thank you.

**Comment by zanjs** [comment]
@gunjpan  Interface data sorting and data filtering through url 

demo (https://github.com/api/user/list?age=18&sex=1)

. Thank you.

**Comment by gunjpan** [comment]
@zanjs : for your scenario, you can do it as follows as querying data is possible through LoopBack filters:
[REST Syntax:](https://docs.strongloop.com/display/public/LB/Querying+data#Queryingdata-RESTsyntax)
`https://localhost:3000/api/users/list?filter[where][age]=18&filter[where][sex]=1`

Also, [stringified JSON](https://docs.strongloop.com/display/public/LB/Querying+data#Queryingdata-Using%22stringified%22JSONinRESTqueries) can be used to query as follows:
`http://localhost:3000/api/users/list?filter={"where":{"age":18, "sex": 1}}`

Hope that answers your concern. 
 Should you have any questions/concerns, please feel free to open this again and would be glad to assist you.

**Comment by zanjs** [comment]
yes ! thinks :+1:
