### ISSUE TITLE
slc loopback:model damage my middleware configuration

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#1833]
I'm using the following middleware setup
## `middleware.json`

```
{
  ...
  "files": {
    "loopback#static": [
       {"params": "$!../.tmp/", "name": "styles"},
       {"params": "$!../client/", "name": "assets"},
       {"params": "$!../", "name": "vendors"}
     ]
  }
}
```
## `middleware.production.js`

```
module.exports = {
  files: {
    'loopback#static': [
      {name: 'assets', params: '$!../dist/'},
      {name: 'vendors', params: null}
    ]
  }
};
```

as you can see i'm using the name to avoid serving files from some routes if my app it's on production

Now when I ran commands like `slc loopbck:model` my middleware.json left in this state

```
{
  ...
  "files": {
    "loopback#static": [
      {
        "params": "$!../.tmp/"
      },
      {
        "params": "$!../client/ngapp/"
      },
      {
        "params": "$!../"
      }
    ]
  },
}
```

I can omit this before commit but it's a bit annoying

**Comment by superkhau** [comment]
from https://github.com/strongloop/strongloop/issues/254

**Comment by gunjpan** [comment]
@rkmax: I tried to reproduce the issue and it seems an issue with the only `"name"` option in `middleware.json` file that gets updated whenever a new model is created. I'm changing the label to `bug` and we will cover it in our sprint planning soon to resolve.

**Comment by davidcheung** [comment]
It seems any keys in the following object are removed if the user uses them, `middleware.json` is only re-written and loses data from `workspace-api`, keys in the following object seems to be problematic. [Possibly related code](https://github.com/strongloop/loopback-workspace/blob/master/common/models/middleware.js#L284-L292)
```
{
        "configFile": "server/middleware.json",
        "phase": "initial",
        "facetName": "server",
        "name": "compression",
        "order": 2049,
        "index": 0,
        "id": "initial.compression"
}
```
-----------------
Just to note some behaviors in my investigation of the current version. 
- collection with only one object becomes an object
- parameters such as `configFile`,`name`,`order`,`index`,`id` are reserved and does not preserve upon  `middleware.json` rewrite from `Middleware.seralize()`
- parameters such as `phase`, `subPhase` in a `loopback#static` entry seems to break the code.
- `file`->`loopback#static` entries pointing to non-existent folders do preserve
