### ISSUE TITLE
Field of type number and Date keeps returning 4294967295 when I use Date.now()

### ISSUE THREAD

**Issue by RayFerr000** [strongloop/loopback#1835]
So I know that the largest value a 32-bit number can represent is 4294967295, Is there anyway around this to store Date.now() in a integer field?

**Comment by loay** [comment]
@RayFerr000 
Thanks for your question. 
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
