### ISSUE TITLE
how do i retain sessions between deployments?

### ISSUE THREAD

**Issue by debianmaster** [strongloop/loopback#1838]
I'm loosing user sessions on mobile devices when performing loopback deployments.

Where is session data stores on loopback  ?   users-api

**Comment by BerkeleyTrue** [comment]
Try using something like https://github.com/kcbanner/connect-mongo to store sessions. This is outside of loopbacks domain.

**Comment by loay** [comment]
Hello @debianmaster 
Thanks for your questions. I am not sure if you meant the passport session or what type of session?
That link should answer your question:

https://groups.google.com/forum/#!topic/loopbackjs/SBAmhCkZwkc

For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
