### ISSUE TITLE
Error fetching user model from Access Tokens

### ISSUE THREAD

**Issue by robinskumar73** [strongloop/loopback#1839]
I am trying to get the username after a user has logged in. I've followed this example from the docs. However, when I try to access the user relation, I am unsuccessful. What am I doing wrong?

Below is some code. You can assume that my data store contains a User with the username 'foo' and password 'bar'.

```
User.login(
    {username: 'foo', password: 'bar'},
    'user',
    function(err, accessToken) {
        console.log(accessToken);
        // This prints out a serialization of the accessToken and
        // interestingly the user is in there as well, as expected.

        // But note the following:
        accessToken.user(function(err, user){
            console.log(err);
            // null

            console.log(user);
            // null
            // How come this is null?  Should it not be the user?
        });

        // After poking around with a debugger, I came across a private API
        // through which I can get to the user.  But surely there must
        // be a better way to do it?
        console.log(accessToken.__data.user);
        // This prints out a serialization of the user

        console.log(accessToken.__data.user.username);
        // This prints out 'foo'
    }
);
```

**Comment by robinskumar73** [comment]
Also asked on stackoverflow
http://stackoverflow.com/questions/30359463/how-do-i-use-the-access-token-in-loopback

**Comment by Amir-61** [comment]
Hi @robinskumar73,

Could you please ask your question in our [Google Community](https://groups.google.com/forum/#!forum/loopbackjs)? That way people can comment on your code easily; also just a side note, [user.login](https://docs.strongloop.com/display/public/LB/Logging+in+users) returns `accessToken.userId`, by which you can query user information from the user model.

I will close this ticket; please ask your question in our google community to discuss it better.

Thanks

**Comment by Amir-61** [comment]
I pushed the code to a [sample repo](https://github.com/Amir-61/loopback-issue-1839), used file based database and included the file `db.json` which saves user info in the repo so you should be able to see how `test.js` script under `boot` folder fetches user object after using `user.login`.

I hope this solves your question...
Thanks!

**Comment by Amir-61** [comment]
@robinskumar73, I will be closing this ticket since it seems there is no issue and I already pushed a sample code to Github showing how you can get user object after `user.login`. Please see how I did it in [this sample Github repo](https://github.com/Amir-61/loopback-issue-1839) I just created for you... 

Thanks!
