### ISSUE TITLE
GraphQL transport

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1841]
Make it easy to expose GrapQL APIs in addition (or instead of) traditional REST API.

See https://github.com/facebook/graphql/issues/3

@raymondfeng could you please share the result of your discussion with @leebyron and what are the next steps we need to take in order to make this happen?

**Comment by bajtos** [comment]
@leebyron You have locked facebook/graphql#3 for collaborators only. Would you mind adding a comment linking to this new issue, so that people can find the place where the discussion is continuing?

**Comment by AshleyAitken** [comment]
I'm interested in this too...

**Comment by JohnCoppa** [comment]
👍

**Comment by gaurav21r** [comment]
+1 Any updates?

**Comment by Industrial** [comment]
:+1:

**Comment by ainesophaur** [comment]
Very interested in having graphql support

**Comment by Industrial** [comment]
https://github.com/RisingStack/graffiti looks like a promisig project. If an adapter could be written between this and the Loopback model layer, then you could just use it as an express plugin.

**Comment by GauSim** [comment]
+1

**Comment by violet-day** [comment]
:+1:

**Comment by adanielyan** [comment]
Would love to see GraphQL support in loopback!

**Comment by terehov** [comment]
+1

**Comment by esco** [comment]
:+1:

**Comment by Taik** [comment]
:+1:

**Comment by Peege151** [comment]
+1

**Comment by jordan112** [comment]
+1 any updates on progress?

**Comment by dligthart** [comment]
Love to see graphql support

**Comment by GauSim** [comment]
+1

**Comment by PhearZero** [comment]
:+1:

**Comment by DFranch** [comment]
:+1:

**Comment by gaurav21r** [comment]
Guys there are *reactions* now in Github. Lets use them instead of a new comment for `+1`

**Comment by sbacem** [comment]
:+1:

**Comment by jeff3yan** [comment]
:+1:

**Comment by bedomo** [comment]
any news about this functionality ? would be nice if is working or not in this feature.

**Comment by seefeld** [comment]
👍

**Comment by mraak** [comment]
+1

**Comment by marcelorl** [comment]
+1

**Comment by romulocintra** [comment]
+1

**Comment by shSina** [comment]
does it need a change to all datasources or a transmission layer graphql query to json?

**Comment by mraak** [comment]
@shSina Transmission layer is enough. You can even resolve from existing rest end points. Wouldn't be a huge task to make something basic.

**Comment by shSina** [comment]
@mraak I'm thinking of the way we can manage ACL inside transmission layer, we can check the request token on all requested relations before transmission and handling the errors... , 
and I should test whether it's possible to override user predefined relations scope (in json) in js dynamically to separate the effect of graphQL endpoint from REST one.

**Comment by kerwynrg** [comment]
👍

**Comment by caoer** [comment]
+1

**Comment by osenvosem** [comment]
👍🏻

**Comment by Tallyb** [comment]
Anyone feels like checking this and providing feedback? It is still in infancy. 
https://github.com/Tallyb/loopback-graphql

**Comment by thiago-soliveira** [comment]
Any news on this?

**Comment by ae1080** [comment]
any Updates?

**Comment by rblalock** [comment]
+100000 on this

**Comment by beeman** [comment]
This is another option based on @Tallyb's project https://github.com/BlueEastCode/loopback-graphql-relay

**Comment by smshuja** [comment]
Has there been any progress on this?

**Comment by abdonrd** [comment]
Any progress? 🙂

**Comment by bajtos** [comment]
See https://github.com/strongloop/loopback-next/issues/656 and https://github.com/strongloop/loopback-next/issues/656
