### ISSUE TITLE
Swagger: skipping unknown type "geopoint".

### ISSUE THREAD

**Issue by lionel-bijaoui** [strongloop/loopback#1842]
I'm totally new to strongloop, and I was following the getting started guide.

Instead of "CoffeShop", I used my model (named "event"), which require geopoint among other things and I'm using postgresql as my data source.
When I launch the server on my local machine (Windows 7, nodejs 0.12.6, strongloop 5.0.1), I get this warning : `Swagger: skipping unknown type "geopoint".`
And so when I launch the API explorer, I can see my sample data that contain the "latlong" property with GET, but the PUT model doesn't list it. I can PUT a new event manually, but it seem like the API is not complete and not working properly.
I really need geopoint for my app, as I will request event data based on their geolocation.

Thank you for your help.
##### common/models/event.json
```json
{
  "name": "event",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "title": {
      "type": "string",
      "required": true
    },
    "description": {
      "type": "string"
    },
    "tel": {
      "type": "string"
    },
    "web": {
      "type": "string"
    },
    "mail": {
      "type": "string"
    },
    "more_info": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "tags": {
      "type": [
        "string"
      ]
    },
    "date_start": {
      "type": "date",
      "required": true
    },
    "date_end": {
      "type": "date",
      "required": true
    },
    "latlong": {
      "type": "geopoint",
      "required": true
    },
    "source": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**Comment by gunjpan** [comment]
@lionel-bijaoui : Hi, I was able to reproduce the issue and have flagged it as a bug. There is similar issue reported at: https://github.com/strongloop/loopback-component-explorer/issues/126
Meanwhile, you could use `latlang` as an array of integers. Hope that helps, please let me know if you have any questions/concerns.
Will update you when it is fixed

**Comment by lionel-bijaoui** [comment]
Thank you very much !

**Comment by GregAujay** [comment]
I had the same issue but it vanished after I changed the type declaration from `geopoint` to `GeoPoint`.

**Comment by 0candy** [comment]
@lionel-bijaoui  Type "GeoPoint" has been added to loopback. Could you please try and let me know if that works for you? Thanks!

https://github.com/strongloop/loopback-component-explorer/issues/136

**Comment by lionel-bijaoui** [comment]
when I launch `node .`, I still get the error.
I have updated both strongloop and nodejs for this.
The update was full of red log message but in the end it said that everything was fine.
`slc --version` give me this

```
strongloop v6.0.0 (node v4.2.4)
├── strong-arc@1.8.5 (d01942e)
├── strong-build@2.1.0 (47dd24a)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.1.0 (eb2f788)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```
Should I rebuild my schema with the cli ?

**Comment by 0candy** [comment]
@lionel-bijaoui  What version of loopback-swagger are you using? Go into node modules in your project to check the version.

**Comment by lionel-bijaoui** [comment]
`"loopback-component-explorer": "^2.1.0",`
`"loopback-swagger": "^2.1.0",`
It's clear i need to update them, but how ?

**Comment by lionel-bijaoui** [comment]
I have recreated my project from scratch and I still get the problem...

**Comment by 0candy** [comment]
Sorry to hear that you're still having problems. I haven't updated my strongloop to the latest version yet. Could you provide a sample repo of your project for me to reproduce the issue? See link:
https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

Thanks!

**Comment by lionel-bijaoui** [comment]
Using git, I have installed the project on a new machine (surface pro 4).
Using "geopoint", the error appear.
Using "GeoPoint", everything is good.
It seem like you found the problem :+1: 
Should I close the issue right now, or wait for the value to be case insensitive ?
Thank you very much for your help.

**Comment by 0candy** [comment]
You can leave the issue open. I will close it when I fix the case insensitive issue.
Thanks for the follow up!
