### ISSUE TITLE
"loaded" opertation observer -- either docs are incorrect or implementation is buggy

### ISSUE THREAD

**Issue by dregre** [strongloop/loopback#1843]
[The docs say](https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-loaded), in relation to the `loaded` operation hook:

> LoopBack invokes this hook after the connector fetches data, but __before creating a model instance from that data__. This enables hooks to decrypt data (for example). NOTE: __This hook is called with the raw database data, not a full model instance.__ *(My emphasis)*

However, after attaching a debugger and inspecting the `ctx` returned to my `loaded` callback, I've noticed that:

1. The `ctx` object has no `data` property at all;
1. Contrary to what the description says, it __does__ contain a model instance.

E.g.:

    MyModel.observe('loaded', function(ctx, next){
        console.log(ctx); // Added a breakpoint here.  Inspected `ctx`.
                          // Does contain `instance`.  Doesn't contain `data`.
        next();
    });

I'm not sure whether the documentation is incorrect or the implementation is buggy?

**Comment by dregre** [comment]
I think this might be a bug.  I've noticed varying behavior:

1. When my `loaded` hook is called incident to one of my auto migrations (`app.dataSources.db.automigrate`), whose callback calls `create` on the model, then `ctx` has `data` but no `instance`.
1. When my `loaded` hook is called afterwards, e.g., when I `find` a record, the `ctx` has an `instance` but no `data`.

Could this varying behavior be due to the fact that the first one is called on `create` and the second one is called on `find`?  Is this intentional?

**Comment by richardpringle** [comment]
hmm.. @dregre, do you have a sample repo that I can clone and see what's going on? See [the wiki](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.) for details on how to do this.

To me, it looks like you've found a bug but I would like to confirm.

**Comment by bajtos** [comment]
Yep, this looks like a bug in the implementation of `find` to me, see the [source code](https://github.com/strongloop/loopback-datasource-juggler/blob/80c3bd9d419e501d5b7beb0a623c8b1eaefdc258/lib/dao.js#L1490-L1499).

**Comment by richardpringle** [comment]
@dregre, it looks like @bajtos made the fix in https://github.com/strongloop/loopback-datasource-juggler/pull/796. 

Thanks for pointing out the bug!
