### ISSUE TITLE
Inifinity Loading in discovering models

### ISSUE THREAD

**Issue by mariohmol** [strongloop/loopback#1846]
Hy there

I'm using slc arc to open the console, using root user, and trying to generate a model.

I tested in 2 different  machines (OSx and ubuntu server), both using mysql (mysqld  Ver 5.6.22 for osx10.8 on x86_64)
It shows the tables and generate all except for one table it stays in a inifinty loading..

I used 3 different browsers to run as well (ff, chrome and safari)

Here are my versions of slc:

strongloop v5.0.1 (node v4.2.2)
├── strong-arc@1.8.4 (b7b568d)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

I tested left just this table on database, with same problem. Here is the create table:

CREATE TABLE `Usuario` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `password` varchar(255) DEFAULT NULL,
  `nickname` varchar(64) DEFAULT NULL,
  `email` varchar(120) DEFAULT NULL,
  `fullname` varchar(200) DEFAULT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `website` varchar(150) DEFAULT NULL,
  `role` smallint(6) DEFAULT NULL,
  `bio` varchar(500) DEFAULT NULL,
  `image` varchar(256) DEFAULT NULL,
  `last_seen` datetime DEFAULT NULL,
  `invite` int(11) DEFAULT NULL,
  `endereco` int(11) DEFAULT NULL,
  `status` smallint(6) DEFAULT NULL,
  `borndate` date DEFAULT NULL,
  `planodesaude` int(11) DEFAULT NULL,
  `numerocarteira` varchar(255) DEFAULT NULL,
  `validadecarteira` varchar(50) DEFAULT NULL,
  `viacarteira` varchar(50) DEFAULT NULL,
  `realm` varchar(512) DEFAULT NULL,
  `username` varchar(512) DEFAULT NULL,
  `credentials` text,
  `challenges` text,
  `emailVerified` tinyint(1) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `lastUpdated` datetime DEFAULT NULL,
  `nomePai` varchar(255) DEFAULT NULL,
  `nomeMae` varchar(255) DEFAULT NULL,
  `dataAtivacao` datetime DEFAULT NULL,
  `dataInativacao` datetime DEFAULT NULL,
  `matricula` varchar(255) DEFAULT NULL,
  `dependencia` varchar(255) DEFAULT NULL,
  `codigoANS` varchar(255) DEFAULT NULL,
  `verificadorANS` varchar(255) DEFAULT NULL,
  `cns` varchar(255) DEFAULT NULL,
  `cpf` varchar(255) DEFAULT NULL,
  `identidade` varchar(255) DEFAULT NULL,
  `dataExpedicao` datetime DEFAULT NULL,
  `orgaoExpedidor` varchar(255) DEFAULT NULL,
  `pis` varchar(255) DEFAULT NULL,
  `inss` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

This table had more fields, I deleted some columns just to check.. and the problem persists..
The console where I ran the slc arc do not show erros.. neither the console.. it stays in running in discoverModelDefinition in network console (browser)

Any ideas?  
Thanks!

**Comment by mariohmol** [comment]
If i reduce the table to this size it works


CREATE TABLE `Usuario` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `password` varchar(255) DEFAULT NULL,
  `email` varchar(120) DEFAULT NULL,
  `nome` varchar(200) DEFAULT NULL,
  `genero` varchar(10) DEFAULT NULL,
  `image` varchar(256) DEFAULT NULL,
  `endereco` int(11) DEFAULT NULL,
  `status` smallint(6) DEFAULT NULL,
  `borndate` date DEFAULT NULL,
  `realm` varchar(512) DEFAULT NULL,
  `username` varchar(512) DEFAULT NULL,
  `credentials` text,
  `challenges` text,
  `emailVerified` tinyint(1) DEFAULT NULL,
  `verificationToken` varchar(512) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `lastUpdated` datetime DEFAULT NULL,
	`nomePai` varchar(255) DEFAULT NULL,
	`nomeMae` varchar(255) DEFAULT NULL,
	`dataAtivacao` datetime DEFAULT NULL,
	`dataInativacao` datetime DEFAULT NULL,
	`matricula` varchar(255) DEFAULT NULL,
	`dependencia` varchar(255) DEFAULT NULL,
	`codigoANS` varchar(255) DEFAULT NULL,
	`verificadorANS` varchar(255) DEFAULT NULL,
	`cns` varchar(255) DEFAULT NULL,
    `cpf` varchar(255) DEFAULT NULL,
    `identidade` varchar(255) DEFAULT NULL,
    `dataExpedicao` datetime DEFAULT NULL,
    `orgaoExpedidor` varchar(255) DEFAULT NULL,
    `pis` varchar(255) DEFAULT NULL,
    `inss` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by loay** [comment]
Hi @mariohmol 
Thanks for reporting the issue. Having a look and getting back to you.

**Comment by loay** [comment]
@mariohmol 

I tested using my local mysql as well as using phpMyAdmin. I cannot reproduce the issue. 
Is your repo available online so I can reproduce?
Thanks.

**Comment by loay** [comment]
@mariohmol I tested on one machine and I cannot reproduce it. 
I will test on another machine and get back to you.

**Comment by loay** [comment]
Hi @mariohmol 
Any chance you can create a repo so I can use it to reproduce?
Thanks.

**Comment by mariohmol** [comment]
yes.. i had this same error in another project.. i will create a sandbox today

**Comment by loay** [comment]
Awesome. Thanks.

**Comment by mariohmol** [comment]
sorry, running out of time.. 
I dont know if it helps.. but i'm using a remote database.. 

can u tell me if this admin console has timeout to connect to databasse?

**Comment by loay** [comment]
@mariohmol remote as in phpmyadmin or you mean remote mysql?
I tried phpmyadmin and i tried the sql insert and it worked fine. 
I don't recall seeing a timeout connection to db, unless the db doesn't allow you to. In other words. I have seen cases where the db will let u establish connection if you are using localhost but nothing external. I am not sure if this is your case or not. 
if you are still experiencing the same issue, please leave a comment so we can investigate further. Make sure you add your own repo, as it could be something in your tables, which will make things easier for me. Thanks.

**Comment by mariohmol** [comment]
I'm connected to the database using mysqladmin. (external server)
Most of the tables it works good, just in case of tables with too many columns, it takes too long time.

I did the map manually, this was my workaround.. thanks

**Comment by eddiemonge** [comment]
This is still a problem
