### ISSUE TITLE
JSON based query param filtering is not parsed by loopback

### ISSUE THREAD

**Issue by h2non** [strongloop/loopback#1852]
If we use the bracket notation to define filters, such as:

``` bash
?filter[where][language]=es
```

it's properly parsed and mapped into a raw JS object, which is perfect.

However, we had troubles passing JSON based queries since they're not properly parsed as JS object in the `parse` middleware phase, so we have to infer the type and try to parse it accordingly, so we've been forced to implement that on a custom middleware phase. 

I believe that since both query notations are natively supported by loopback, interface should be consistent and provide the same interface in lower layers, for instance in remote methods.

I'm running the latest version of loopback.

**Comment by richardpringle** [comment]
Thanks @h2non, going to throw the `feature` label on this issue and we'll take a look where it fits on the priority list.

**Comment by h2non** [comment]
No worries. The implementation is not hard, tough. Here it's my own:
```json
/**
 * Generic middleware to parse query filter using JSON notation
 * providing a consistent interface in lower layers.
*
 * See: https://github.com/strongloop/loopback/issues/1852
 *
 * @param {http.IncomingMessage} req
 * @param {http.ServerResponse} res
 * @param {Function} next
 * @function queryParser
 */

module.exports = function queryParser (req, res, next) {
  const query = req.query
  const filter = query.filter

  // Just ignore if not a JSON (probably here you should do additional checks)
  if (typeof filter !== 'string') return next()

  try {
    query.filter = JSON.parse(filter)
  } catch (e) {
    return res.status(400).send({ error: { message: 'Bad formed JSON query filter' }}) // or perhaps reply with 422
  }

  next()
}
```

**Comment by richardpringle** [comment]
@h2non, did you submit a PR?

**Comment by h2non** [comment]
I don't have plans to do it, but feel free to take that code, make the proper improvements and push it if you want.

**Comment by amenadiel** [comment]
@h2non how are you sending said JSON based queries? 

I went through trial and error for a bit until I saw that the parameter [must be stringified beforehand](https://docs.strongloop.com/display/public/LB/Querying+data#Queryingdata-UsingstringifiedJSONinRESTqueries) I guess this allows from proper escaping. 

For example, I have a frontend backbone model whose current status can be described as:

```js
    var currentStatus = {
					"fields": {
						"theGeomGoogle": false
					},
					"limit": 50,
					"skip": 0,
					"order": "idInstagis ASC",
					"where": {
						"and": [{
							"local": {
								"gte": "2"
							}
						}, {
							"comuna": {
								"neq": "Santiago"
							}
						}, {
							"comuna": {
								"neq": "Independencia"
							}
						}]
					}:
```

so I send my request to

```js
var endpoint = `/api/Model/{id}?filter='+JSON.stringify(currentStatus);
```

Which in devtools looks like

```sh
/api/Model/123?filter=%7B%22fields%22%3A%7B%22theGeomGoogle%22%3Afalse%7D%2C%22limit%22%3A50%2C%22skip%22%3A0%2C%22order%22%3A%22idInstagis+ASC%22%2C%22where%22%3A%7B%22and%22%3A%5B%7B%22local%22%3A%7B%22gte%22%3A%222%22%7D%7D%2C%7B%22comuna%22%3A%7B%22neq%22%3A%22Santiago%22%7D%7D%2C%7B%22comuna%22%3A%7B%22neq%22%3A%22Independencia%22%7D%7D%5D%7D%7D
```

If I paste the same query decoding curly braces and double quotes, the query fails.

**Comment by h2non** [comment]
I'm just sending a raw JSON as filter param value, like you are doing.

**Comment by h2non** [comment]
Just for your reference, this is the final implementation I'm using to fix this as simple middleware in the `parse` phase. 

It's working in production for a couple of months without troubles. A bit rudimentary and should be improved if merged into the framework, but works for me.

```js
const merge = require('lodash').merge

/**
 * Generic middleware to parse query filter using JSON notation
 * providing a consistent interface in lower layers.
 *
 * This should be inferred by loopback internall, as it does with braces
 * query notation, but seems like it does not.
 *
 * See: https://github.com/strongloop/loopback/issues/1852
 *
 * @param {http.IncomingMessage} req
 * @param {http.ServerResponse} res
 * @param {Function} next
 * @function queryParser
 */

module.exports = function queryParser (req, res, next) {
  const query = req.query
  const filter = query.filter

  // If empty filter, just continue
  if (!filter) {
    return next()
  }

  // Just ignore if not a JSON
  if (typeof filter !== 'string') {
    parseNestedFilters(query, res)
    return next()
  }

  // Otherwise parse it properly
  try {
    query.filter = JSON.parse(filter)
  } catch (e) {
    return parseError(res)
  }

  next()
}

function parseNestedFilters (query, res) {
  Object.keys(query.filter)
  .filter(key => query.filter[key] === true)
  .filter(key => (/^\{\"/i.test(key)))
  .forEach(key => {
    try {
      merge(query.filter, JSON.parse(key))
      delete query.filter[key]
    } catch (e) {
      return parseError(res)
    }
  })
}

function parseError (res) {
  if (res.headersSent) return
  res
    .status(400)
    .send({ error: { message: 'Bad formed JSON query filter' } })
}
```
