### ISSUE TITLE
Remove unused User properties: created, lastUpdated, status

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1854]

**Comment by davidcheung** [comment]
Task: 
- [ ] Remove properties `credentials`, `challenges` `status`, `created`, `lastUpdated`  [link](https://github.com/strongloop/loopback/blob/524058d8fce3f6e47ae2eb14213df2913b59a71b/common/models/user.json#L14-L21)
- [ ] search documentation to see if there are references 
- [ ] udpate `3.0-RELEASE-NOTES.md`
