### ISSUE TITLE
Feature: remote method locks

### ISSUE THREAD

**Issue by csvan** [strongloop/loopback#1857]
There are certain use cases where the server should not allow two invocations of a single method to be accepted at the same time. For example, a remote method may cause the server to run through sequential updates of several models based on a single set of data, which should later be discarded. If the user (or several users) is/are able to invoke the same remote method several times with the same data, the models will be corrupted.

To solve this, it would be cool if a remote method can be configured to "lock" until it yields a response of any kind. Any attempted invocation of the remote method before it returns should be immediately answered with a suitable error response, or queued for subsequent execution.

Even if this isn't on the roadmap, does anyone have a suggestion of how it could be implemented? For example, does Loopback provide some kind of global object where one could store flags that could be checked in a `beforeRemote` hook?

**Comment by fabien** [comment]
Implementing this in a `beforeRemote` hook should be pretty easy. The hard part is dealing with a global lock, especially in a clustered environment. A plain per-process global variable would otherwise be enough to keep track of this locked state.

However, in order to prevent corruption of data, I would first look into the database layer and transactions specifically.

**Comment by csvan** [comment]
> The hard part is dealing with a global lock, especially in a clustered environment

Was just going to add this as an edit, thanks for beating me to it ;)

**Comment by csvan** [comment]
For anyone interested in a current workaround for clusters, the following provides a semaphore implementation based on Redis:

https://github.com/danmactough/halocksmith

It is not optimal, but the timeout can be set to avoid blocking in cases where you only want one execution of the method to be active in the cluster at any given time.
