### ISSUE TITLE
persistentModel.find() returns wrappedPromise { <pending> }

### ISSUE THREAD

**Issue by nkhaitan** [strongloop/loopback#1858]
Hello,

A simple .find() on a persistentModel returns  wrappedPromise { <pending> } instead of the result. The following code still renders the same issue:

	$categories = app.models.Category.find({order: 'name ASC'})
	.then(function(result){
		return result
	})
	.catch(function(err){
		return err
	});

However, the only exception here is that console.log(result) outputs the desired result. However, in no other situation am I able to extract and store the object. Please help ASAP!!

Thanks,

Nilesh

**Comment by nkhaitan** [comment]
Hi can anyone please look into this ASAP? I'm using a remote MongoDB in my project. If you need any other information about this issue, please let me know. Thanks!

**Comment by seriousben** [comment]
categories = results; in your then function.
This is async so the results are only available when the promise has been
resolved.

**Comment by gunjpan** [comment]
@nkhaitan : I tried to reproduce it. But, in my case, I was able to get the `object` in `result` and pass it along as follows:
``` 
    Researcher.find({ 'where': {id:ctx.instance.researcherId} })
			.then(function(res){
			    printIt(res, function(err, cbr){
				 console.log(cbr.username);
			    });
			})
			.catch( function(err){
			    throw(err);
			});
 		});
 function printIt(obj, cb){
		 cb(null, obj);
 }
	 	
 ``` 

and agree with @seriousben. So if you try to use `categories` on the next line, you will get `wrappedPromise{}`

**Comment by nkhaitan** [comment]
Thanks guys that worked! But how do I go about making several queries asynchronously? This is what I intend to do:

Category.find({order: 'name ASC'})
	.then(function(result){
		Researcher.find({ 'where': {id:ctx.instance.researcherId} })
		.then(function(res){
			res.render('index', {
				research: res,
				categories: result
			});
		})
	})
	.catch(function(err){
		throw(err)
	});

**Comment by gunjpan** [comment]
@nkhaitan : I'm glad that helped. To further the discussion, could you please re-post it to our Google groups at: https://groups.google.com/forum/#!forum/loopbackjs as we are trying to use this space for reporting bugs/features in order to improve Loopback for the community.
( See https://github.com/strongloop/loopback/wiki/Questions for more details.) 
Thank you!
