### ISSUE TITLE
Multiple models with same plural name - only one model shown in Swagger UI

### ISSUE THREAD

**Issue by pktippa** [strongloop/loopback#1863]
When we have multiple models with same plural name, only one model getting shown in the Swagger UI(explorer).

common\models\sample-a.json
```json
{
  "name": "SampleA",
  "plural": "Samples",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```
common\models\sample-b.json

```json
{
  "name": "SampleB",
  "plural": "Samples",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**Comment by richardpringle** [comment]
Hey @pktippa, the REST endpoint is the plural name of the model unless you create a custom path with the `http` object.
```
{
  "name": "SampleB",
  "plural": "Samples",
  "http": {
    "path": "/customPathName"
  }
...
```
Make sense?
I don't know your particular use case but to me, it looks like you should create a `Sample` model in which `SampleA` and `SampleB` can inherit from, then use a polymorphic relationship.
[Docs for polymorphic relationships](https://docs.strongloop.com/display/public/LB/Polymorphic+relations)
[An example from the community](http://codiphany.blogspot.ca/2015/05/polymorphic-relations-in-loopback-using.html)

**Comment by pktippa** [comment]
Hi @richardpringle 

Actually we are creating models using [loopback-workspace](https://github.com/strongloop/loopback-workspace) api, if we POST /ModelDefintions multiple models with same plural name it is getting accepted and only one model is getting shown in the swagger UI.

**Comment by richardpringle** [comment]
@pktippa, yes it will be accepted as you have experienced but the behavior is as expected. If you want, you can open up a new issue asking for a feature that stops you (or at least warns you from doing so).
Here is [the wiki](https://github.com/strongloop/loopback/wiki/Reporting-issues#feature-request) for requesting a feature.

**Comment by pktippa** [comment]
@richardpringle Thanks for responding the request. As suggested I created the issue #1873
