### ISSUE TITLE
Speed up Checkpoint implementation

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#1864]
The current `Checkpoint` implementation keeps all past checkpoints around. When looking up the current checkpoint, we run the query `this.find({ limit: 1, order: 'seq DESC' })` which is not backed up by any index and thus triggers a full table scan.

We should rework the implementation to keep a single global `Checkpoint` instance and update it in-place when bumping up `seq`.

Related: strongloop-internal/scrum-cs#397

**Comment by bajtos** [comment]
Workaround: schedule a regular cleanup of old checkpoints.

Code example:

```js
var app = require('./');
var Model = app.models.Todo; // the change-tracked model
var Change = Model.getChangeModel();
var Checkpoint = Change.getCheckpointModel();

Checkpoint.current(function(err, cp) {
  if (err) return console.error('Cannot obtain current checkpoint:', err);
  console.log('Current checkpoint:', cp);

  Checkpoint.deleteAll({ seq: { lt: cp } }, function(err, info) {
    if (err) return console.error('Cannot delete old checkpoints:', err);
    console.log('Deleted %s old checkpoints', info.count);
  });
});
```

**Comment by Amir-61** [comment]
Connect to: https://github.com/strongloop/loopback/pull/1908
