### ISSUE TITLE
Validation of model data does not work on models defined as server only.

### ISSUE THREAD

**Issue by wajidmehraj** [strongloop/loopback#1868]
Validation rules written on models work only when the model is created as a common model and resides in 
folder
**common/models/MyModel.js**
module.exports = function(MyModel) {
  MyModel.validatesLengthOf('name', { min: 5, message: { min: 'Name should be 5+ characters' } });
  ...
};

**server/models/MyModel.js**
*Any validation rule written on server models do not trigger.*

Is it intended to work that way or does this feature need to be incorporated yet?

**Comment by gunjpan** [comment]
@wajidmehraj : Any model created, regardless of being in server or common directory, in Loopback gets the base [`Model` object](https://docs.strongloop.com/display/public/LB/Basic+model+object).
>By default, the basic LoopBack Model object has properties and methods "mixed in" from:
    Inclusion object - Enables you to load relations of several objects and optimize numbers of requests.
    Validateable object - provides validation methods; see Validating model data.

Thus, `validation` methods (i.e. `Model.validatesLengthOf()`) is available to `models` in `/server/models/` as well. 

I've created a sample repo for you to take a look at: https://github.com/gunjpan/sandbox/tree/lb-1868

Please verify to close it if it resolved your query.
Thank you :)

**Comment by gunjpan** [comment]
@wajidmehraj : Closing this. If you are still facing this issue, please comment here and I will reopen it.
Thank you :)
