### ISSUE TITLE
the explorer and documentation regarding filtered queries are inaccurate / broken 

### ISSUE THREAD

**Issue by pvijeh** [strongloop/loopback#1875]
I constructed this GET query using the API explorer:

curl -X GET --header "Accept: application/json" "http://0.0.0.0:3000/api/Votes?filter=%5Bwhere%5D%5BUserId%5D%3D0"

which returns this error:

{
  "error": {
    "name": "Error",
    "status": 400,
    "message": "invalid value for argument 'filter' of type 'object': [where][UserID]=0. Received type was string. Error: Unexpected token w",
    "statusCode": 400,
    "stack": "Error: invalid value for argument 'filter' of type 'object': [where][UserID]=0. Received type was string. Error: Unexpected token w\n    at new badArgumentError (/Users/pvijeh/projects/loopback/places-api/node_modules/strong-remoting/lib/shared-method.js:268:13)\n    at coerceAccepts (/Users/pvijeh/projects/loopback/places-api/node_modules/strong-remoting/lib/shared-method.js:324:13)\n    at SharedMethod.invoke (/Users/pvijeh/projects/loopback/places-api/node_modules/strong-remoting/lib/shared-method.js:217:16)\n    at HttpContext.invoke (/Users/pvijeh/projects/loopback/places-api/node_modules/strong-remoting/lib/http-context.js:384:12)\n    at /Users/pvijeh/projects/loopback/places-api/node_modules/strong-remoting/lib/remote-objects.js:620:11\n    at execStack (/Users/pvijeh/projects/loopback/places-api/node_modules/strong-remoting/lib/remote-objects.js:460:7)\n    at RemoteObjects.execHooks (/Users/pvijeh/projects/loopback/places-api/node_modules/strong-remoting/lib/remote-objects.js:464:10)\n    at /Users/pvijeh/projects/loopback/places-api/node_modules/strong-remoting/lib/remote-objects.js:617:10\n    at /Users/pvijeh/projects/loopback/places-api/node_modules/loopback/lib/application.js:358:13\n    at /Users/pvijeh/projects/loopback/places-api/node_modules/loopback/lib/model.js:313:7"
  }
}

The bare query (without a filter) returns a normal response: 

curl -X GET --header "Accept: application/json" "http://0.0.0.0:3000/api/Votes"

Response:

[
  {
    "Is-Yes": true,
    "VoteCatId": 0,
    "PlaceId": 1,
    "DateAdded": "2015-12-10T00:00:00.000Z",
    "DateModified": "2015-12-10T00:00:00.000Z",
    "UserId": 0,
    "Id": 0
  },
  {
    "Is-Yes": true,
    "VoteCatId": 0,
    "PlaceId": 1,
    "DateAdded": "2015-12-10T00:00:00.000Z",
    "DateModified": "2015-12-10T00:00:00.000Z",
    "UserId": 0,
    "Id": 1
  },
  {
    "Is-Yes": true,
    "VoteCatId": 0,
    "PlaceId": 1,
    "DateAdded": "2015-12-10T00:00:00.000Z",
    "DateModified": "2015-12-10T00:00:00.000Z",
    "UserId": 0,
    "Id": 2
  },
  {
    "Is-Yes": true,
    "VoteCatId": 0,
    "PlaceId": 1,
    "DateAdded": "2015-12-10T00:00:00.000Z",
    "DateModified": "2015-12-10T00:00:00.000Z",
    "UserId": 0,
    "Id": 3
  }
]

**Comment by pvijeh** [comment]
I eventually figured out that the request should look like this: 

http://0.0.0.0:3000/api/Votes?where=%5BUserId%5D%3D0

the explorer and documentation regarding filtered queries are inaccurate / broken

**Comment by raymondfeng** [comment]
The url should be one of the following:

http://0.0.0.0:3000/api/Votes?filter[where][UserId]=0 // qs syntax
or 
http://0.0.0.0:3000/api/Votes?filter={"where":{"UserId":0}} // stringified json
