### ISSUE TITLE
Document case-sensitive email option for User model

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#1877]
Implemented in https://github.com/strongloop/loopback/pull/1804.
Should be fairly trivial.

@richardpringle Please provide basic explanation, and I'll add to docs.

**Comment by mrfelton** [comment]
This does not appear to be documented on https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html

**Comment by richardpringle** [comment]
@mrfelton, you should probably open up a new issue. I'm not working on LoopBack anymore but feel free to mention me as I'm the one who implemented the change and I can probably help @crandmck with the documentation if he needs help.
