### ISSUE TITLE
Set userId relation based on accessToken?

### ISSUE THREAD

**Issue by remotevision** [strongloop/loopback#1878]
I have a one-to-many relationship between ```User``` and ```Thing```. I have a foreignKey defined on each object and I was hoping that when creating a new ```Thing```, it would assign the ```userId``` foreignKey based on the user principle from the ```accessToken```.

Relationship defined on ```Thing```:
``` 
"relations": {
    ...
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    }
  },
```

What is the best way to assign ```thing.userId``` based on the user principle?

**Comment by remotevision** [comment]
I wrote a ```beforeRemote``` which adds it. This solution worked out nice.

```
  Thing.beforeRemote('create', function(ctx, thing, next) {
    ctx.req.body.userId = ctx.req.accessToken.userId;
    next();
  });
```

**Comment by jannyHou** [comment]
hey @remotevision glad to see you have figured out the solution, I suppose you find the proper usage of `ctx.req.accessToken` in [doc here](https://docs.strongloop.com/display/public/LB/Remote+hooks#Remotehooks-ctx.req.accessToken), it includes more details of remotehooks.

Just in case you will need it, we also explained how to get current user in [remote method](https://docs.strongloop.com/display/public/LB/Using+current+context#Usingcurrentcontext-Usecurrentauthenticateduserinremotemethods) 

 And for future references, please ask questions on [google group](https://groups.google.com/forum/#!forum/loopbackjs) Thanks!
