### ISSUE TITLE
Problem with remote-method boolean arg and strong-remoting 2.23.0

### ISSUE THREAD

**Issue by matohawk** [strongloop/loopback#1881]
loopback : 2.2.26

Here my remote Method definition :
Auction.remoteMethod('allAuctions', {
    description: 'Get all Auctions',
    accepts: [ {
      arg: 'franchised',
      type: 'boolean',
      http: {
        source: 'query'
      },
      description: 'Get only franchised Account'
    }

When I pass : 
api/v1.1/Auctions/All?franchised=false

I retrieve :
true for the franchised after the remote method

I downgrade the version of strong-remoting to 2.22.0 and now it's fixed.
Can you have a look?

**Comment by jannyHou** [comment]
hey @matohawk  I am trying to reproduce your issue, however the description above is a little vague. Can you please provide me the whole definition of your remote method (eg: at least contains http path)? 
And for a better review we would appreciate it if you can fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and upload your own project, with the code I can help you more easily and quickly.
Thanks!

**Comment by matohawk** [comment]
* 2 descriptions is one for the remote method and one for the argument
* I will try to reproduce this bug in your sandbox

**Comment by jannyHou** [comment]
@matohawk  Cool! thank you.

**Comment by matohawk** [comment]
Sorry it's too long for us to do that.
We will just use the 2.22.0 of the strong-remoting for now.

The only things I can say it's a boolean arg problem with custom remote method. When we pass false we retireve true.

**Comment by jannyHou** [comment]
@matohawk no worries, that doesn't matter, I reproduced your issue and yes you are right, we will look into this bug ASAP! Thank you very much!

**Comment by jannyHou** [comment]
hey @superkhau @bajtos , as the user said above, "there is a boolean arg problem with custom remote method. When we pass false we retireve true."

I reproduced this issue with [sample](https://github.com/jannyHou/loopback-sandbox/tree/bug/strong-remoting-boolean-arg) here.

I defined a remote method for model `game`. It takes one input argument called `isMature` and the value of `isMature` is printed in the method:

```js
module.exports = function(Game) {
  Game.mature = function(isMature, callback) {
    if(isMature) {
      console.log("Mature is ", isMature);
      callback(null);
    } else {
      console.log("Mature is ", isMature);
      //when use the latest 'strong-remoting' 2.23.0,
      //it logs "Mature is true", which is not expected,
      //while 'strong-remoting' 2.22.0 logs expected result "Mature is false" 
      callback(null);
    }
  }

  Game.remoteMethod(
  	'mature', {
  		accepts: [
        {
          arg: "isMature",
          type: "boolean",
          required: true,
          http: {
            source: 'query'
          },
          "description:": "set mature to be true"
        }
      ],
  		returns: [],
  		http: {
  			path: '/mature',
  			verb: 'post'
  		}
  	}
  );
};
```

Could you please take a look when you have time? Thanks!

**Comment by superkhau** [comment]
@jannyHou Sounds like a bug to me. Check the git history to see what changes were recently commited.

**Comment by jannyHou** [comment]
@superkhau I think it's fixed now, miroslav reverted that commit:
please see https://github.com/strongloop/strong-remoting/pull/269 for more details.

**Comment by bajtos** [comment]
Yes, I have landed a pull request that was approved by @ritch but accidentally lost by `git push -f`. Unfortunately it turned out the pull request introduced regressions (like the one described here), so I have reverted it back.

@matohawk could you please try `strong-remoting@2.23.1` and let us know if the bug is still present?

**Comment by bajtos** [comment]
Actually, to simplify our process, I am going to close this issue as fixed. @matohawk please reopen if the problem still persists.
