### ISSUE TITLE
method count seems not work correct.

### ISSUE THREAD

**Issue by TNT-Likely** [strongloop/loopback#1883]
i use same filter in method find,it work.

i wish somebody can help me

thanks!

![1](https://cloud.githubusercontent.com/assets/9278923/11801560/0ff63c16-a322-11e5-9c48-80364821b31a.png)

**Comment by TNT-Likely** [comment]
![2](https://cloud.githubusercontent.com/assets/9278923/11801606/5e9bf89c-a322-11e5-8e0b-375d9c815e24.png)

**Comment by Neil-UWA** [comment]
you are passing wrong query parameters, no filter only where query. You can check the format in your explorer. Also provide details when you have any issues, otherwise others need to take time to analysis the problem.

**Comment by TNT-Likely** [comment]
thanks,it work.
