### ISSUE TITLE
How to change datasource of Models dynamicly ?

### ISSUE THREAD

**Issue by toplinuxsir** [strongloop/loopback#1885]
How to change datasource of Models dynamicly ?

**Comment by toplinuxsir** [comment]
For example: a model Product , at runtime I want to change the datasource of model Product from pgsql to mysql , how to ?
Thanks !

**Comment by jannyHou** [comment]
hey @toplinuxsir , I think the functionality you are looking for is [`attachTo()`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L330)
Please check this (example)[http://stackoverflow.com/questions/31173302/how-to-configure-two-different-datasource-for-a-model-in-strongloop-loopback-fra] for more details about how to use it, not complicate as far as I see.
Does is solve your problem? Thanks!

**Comment by toplinuxsir** [comment]
Yes, it dose,
Thanks !


2015-12-15 22:49 GMT+08:00 Janny <notifications@github.com>:

**Comment by jannyHou** [comment]
No problem :) Glad to hear that!
And for future references, we welcome users to ask questions on [google group](https://groups.google.com/forum/#!forum/loopbackjs) Thanks!

**Comment by Overdrivr** [comment]
Using this example, what happens if multiple requests are processed concurrently ?

One request may set the `datasource1`, and the second request may expect to write to `datasource2` but (since `attachTo` is static and not per instance) then it will use `datasource1` instead.

**Comment by haoxy0** [comment]
I have the same question as @Overdrivr, any answer for that? Thanks.

**Comment by san2code** [comment]
I have a similar use case and same question as @Overdrivr ,  Any help? @haoxy0 Did you get a solution?
