### ISSUE TITLE
Process Manager have running pretty heavily sending out the data,  which causing Amazon abuse report

### ISSUE THREAD

**Issue by chandrasekhark** [strongloop/loopback#1891]
I installed process manager and deployed my application in live server. After few days i got mail from client team like below.

"I saw the node have running pretty heavily sending out the data,  which causing Amazon abuse report come out."

![ieicjccd](https://cloud.githubusercontent.com/assets/8915614/11869298/bf93311a-a4e4-11e5-8e2f-4dd38d3a9377.png)

I checked the progress
sudo ps -aux |grep node

strong-+  2353  180  1.1 818676 89956 ?        Rsl  07:16   0:01 /usr/local/bin node /usr/local/lib/node_modules/strong-pm/bin/sl-pm.js --listen 6510 --base /var/lib/strong-pm --base-port 6511 --driver direct

![eegieecb](https://cloud.githubusercontent.com/assets/8915614/11869497/4abe79a6-a4e6-11e5-9ee3-cfdef408d2e7.png)

I followed basic steps. slc build, slc deploy http://localhost:6512.

Please help me, how to fix this issue?

**Comment by superkhau** [comment]
@cgole Can you look into this?

**Comment by superkhau** [comment]
@chandrasekhark Are you still running into issues? Can I close this?

**Comment by chandrasekhark** [comment]
Thanks and close it.

Thanks,
Chandrasekhar.K
