### ISSUE TITLE
Fails to Install on Ubuntu 14.04.3

### ISSUE THREAD

**Issue by pvijeh** [strongloop/loopback#1895]
Strong loop fails to install on Ubuntu 14.04.3. 

I tried installing it on a fresh Digital Ocean Ubuntu instance using the following steps: 

sudo apt-get install nodejs
sudo apt-get install npm 
npm install -g strong-pm

Which results in the following failure: 

> sqlite3@3.1.1 install /usr/local/lib/node_modules/strong-pm/node_modules/minkelite/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! weird error 127
npm ERR! not ok code 0

**Comment by pvijeh** [comment]
I discovered that there was a problem with my path variable.  I fixed it with the following command:

"update-alternatives --install /usr/bin/node node /usr/bin/nodejs 99"

maybe we should add something about this in the documentation?

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
@pvijeh Will all Ubuntu users need to use this command?   Or was there something particular about your configuration?  

Does it apply to all versions of Ubuntu or just Ubuntu 14._x_ or 14.04._x_ ?

**Comment by pvijeh** [comment]
I can't say for sure where it is version specific or not, but if people
plan to install it on the current LTS version of Ubuntu they will certainly
encounter this problem.

**Comment by crandmck** [comment]
Added https://docs.strongloop.com/display/SL/Installation+troubleshooting#Installationtroubleshooting-ErrorsonUbuntu

Also added to https://docs.strongloop.com/display/SL/Installing+on+Linux
