### ISSUE TITLE
models.json API Error - ignored "plural" config

### ISSUE THREAD

**Issue by lsdriscoll** [strongloop/loopback#190]
**Affects**

Loopback 1.6.2

**Outline**

A typical model JSON config looks like:

```json
{
    "modelName": {
        "public": true,
        "dataSource": "gold",
        "plural": "modelNames",
        "options": {},
        "properties": {}
    }
}
```

Options are added under the "options" property. 
Properties are added under the "properties" property.

The models are generated using the following code:

```javascript
function modelFromConfig(name, config, app) {

  // Here you see which configs are used for model creation

  var ModelCtor = require('./loopback').createModel(name, config.properties, config.options);
  var dataSource = app.dataSources[config.dataSource];

  assert(isDataSource(dataSource), name + ' is referencing a dataSource that does not exist: "'+ config.dataSource +'"');

  ModelCtor.attachTo(dataSource);
  return ModelCtor;
}
```

As you can see, only the `config.properties` & `config.options` are passed in to `createModel`.

Changing the `public` and `dataSource` property values has the desired result, so these properties are correctly accessed as part of another routine, but changing the `plural` property value has no effect on the generated REST API.

This following code at https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L114-L118 attempts to consume the `plural` property:

```
ModelBuilder.prototype.define = function defineClass(className, properties, settings, parent) {
  var modelBuilder = this;
  var args = slice.call(arguments);
  var pluralName = (settings && settings.plural) ||
    inflection.pluralize(className);
```

Here is clearly shows that it check inside `settings` for the `plural` property. The `settings` object is a direct reference to `config.options`.

The easiest fix for this was change my model config by moving the `plural` property inside `options`:

```json
{
    "modelName": {
        "public": true,
        "dataSource": "remote",
        "options": {
            "plural": "modelName"
        }
    }
}
```

=== 

**Proposed Changes**

Semantically speaking, every model config that's not a property should be considered an "option" and placed accordingly - but moving the `plural` config under `options` is a potentially a quick, clean fix.

**Comment by loay** [comment]
@lsdriscoll,  Since issue is fixed, closing case. 
If issue still persisting, please let us know. Thanks.
closes #190
