### ISSUE TITLE
url encoded accented characters break the filter

### ISSUE THREAD

**Issue by vl4dt** [strongloop/loopback#1900]
This condition occurs when I have to query any list or call the findOne method and specify a filter with some accented character in any string value, I don't know if there is another way to send the filter, maybe as a json payload but it doesn't work either.

Example:

**This works:**
Original object:
```json
{"filter":{"where":{"name":"John Doe"}}}
```

http://localhost:3000/api/organizacions?**_filter=%7B%22where%22%3A+%7B%22nombre%22%3A+%22John+Doe%22%7D%7D_**

**This fails**
Original object:
```json
{"filter":{"where":{"name":"John Doé"}}}
```
**_filter=%7B%22where%22%3A+%7B%22name%22%3A+%22John+Do%5Cxc3%5Cxa9%22%7D%7D_**

Error stack trace:

```json
{"error":{"name":"Error","status":400,"message":"invalid value for argument \'filter\' of type \'object\': where. Received type was string. Error: Unexpected token w","statusCode":400,"stack":"Error: invalid value for argument \'filter\' of type \'object\': where. Received type was string. Error: Unexpected token w\\n    at new badArgumentError (/Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/strong-remoting/lib/shared-method.js:268:13)\\n    at coerceAccepts (/Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/strong-remoting/lib/shared-method.js:324:13)\\n    at SharedMethod.invoke (/Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/strong-remoting/lib/shared-method.js:217:16)\\n    at HttpContext.invoke (/Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/strong-remoting/lib/http-context.js:384:12)\\n    at /Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/strong-remoting/lib/remote-objects.js:620:11\\n    at execStack (/Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/strong-remoting/lib/remote-objects.js:460:7)\\n    at RemoteObjects.execHooks (/Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/strong-remoting/lib/remote-objects.js:464:10)\\n    at /Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/strong-remoting/lib/remote-objects.js:617:10\\n    at /Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/loopback/lib/application.js:358:13\\n    at /Users/vl4dt/Projects/progetti/api/sfapvsdb/node_modules/loopback/lib/model.js:313:7"}}
```

I'm calling the service from Python, I notice the api explorer handles this differently, different encoded url:
**_filter=%7B%22where%22%3A%7B%22nombre%22%3A%22John%20Do%C3%A9%22%7D%7D_**

I'm using **urllib.urlencode**, how should I encode the params, one difference I noticed right away was that urlencode was using **%27** instead of **%22**, had to have it replaced before using the url.

The call is being made through urlfetch.

Any thoughts?

**Comment by loay** [comment]
Hi @vl4dt 
I tried to reproduce using the rest api or with node. It works fine and it doesn't fail. I am not sure if it is related to the usage  of **urllib.urlencode**
I think this thread should help you:
http://stackoverflow.com/questions/3315095/problem-encoding-accented-characters-with-python
Please let me know. Thanks.

**Comment by loay** [comment]
Hello, Is this issue still persisting? 
If you are still having troubles with the same issue, please leave a comment and I will re-open the issue. Thanks.

**Comment by Cu4rach4** [comment]
i have allmost the same problem, i'm using http for request on the same Strongloop server (i dont know how to call internal), but returns:

[SyntaxError: Unexpected token w]

This is the code:

`
GetDevicebyChannel: function  (channelId, callback){

		var filter = {
			"where":{
				"idchannelsts": channelId
			}
		};

		// console.log(JSON.stringify(filter));
		// http://localhost:3000/api/Channelsts?filter={"where":{"idchannelsts":218200}}&access_token=panky

			options = {
				hostname: 'localhost',
				port: 3000,
				path: '/api/Channelsts?filter=' +  JSON.stringify(filter) + '&access_token=' + token_API,
				method: 'GET',
				headers: {
					'Accept': 'application/json',
				    'Content-Type': 'application/json'
				  }
				// protocol: 'https'
			}

			console.log (options.path);

			http.request(options, callbackHttp).end(function () {
				 callback(Respjson);
			});

			console.log(JSON.stringify(filter));
`

when i use console.log (options.path) on browser works without any throuble!..

> 
http://localhost:3000/api/Channelsts?filter={"where":{"idchannelsts":218200}}&access_token=Panky

Returns: 

> [{"idchannelsts":218200,"namechannel":"AgroDoc_llahuen_piloto","usuariosIdusuarios":1,"iddevice":"d0001p"}]

**Comment by estebanconstante** [comment]
Having similar issues when saving a user's name that contains accents. I get RangeError: Invalid status code: 0
