### ISSUE TITLE
unscope method

### ISSUE THREAD

**Issue by Neil-UWA** [strongloop/loopback#1912]
Will loopback provide a unscope method, just like ruby on rails' `unscope` method.

currently, we can unscope by define `Model.defaultScope = function(){}`, and restore it when necessary. But doing this is dangerous.

**Comment by 0candy** [comment]
We don't have plans to add an unscope method ATM. Would you like to submit a patch?

**Comment by Neil-UWA** [comment]
@0candy I will look into it when I have time.

**Comment by pthieu** [comment]
@Neil-UWA: This might take a while for us to get to. To speed up the process, you can do one of two things:
 1. If you still require this, open a new issue using the `New issue` button and fill in the template provided to you
 2. Open a PR adding this functionality yourself and we will review and merge.

Will close this issue now as it's been almost a year. Please use option `#1` if you still require this.
