### ISSUE TITLE
Provide a way to override the default description of scope remote mehtods.

### ISSUE THREAD

**Issue by alFReD-NSH** [strongloop/loopback#1913]
Currently the description(for documenation/api explorer) is auto-generated for the remote method of a scope, it'd be nice to override it or be able to add more information.

**Comment by pthieu** [comment]
@alFReD-NSH: This might take a while for us to get to. To speed up the process, you can do one of two things:
 1. If you still require this, open a new issue using the `New issue` button and fill in the template provided to you
 2. Open a PR adding this functionality yourself and we will review and merge.

Will close this issue now as it's been over a year. Please use option `#1` if you still require this.
