### ISSUE TITLE
Using scopes methods with the angular SDK

### ISSUE THREAD

**Issue by alFReD-NSH** [strongloop/loopback#1914]
Right now, methods are generated for the defined scopes but they are not documented and also the generated methods don't seem to be meant to be used directly, because for example a method generated for the scope `topAdmins` is `__get__topAdmins`. Why isn't it just `getTopAdmins`?

**Comment by davidcheung** [comment]
Hi @alFReD-NSH,
Not sure if I understand your'e question correctly, are you talking about the retrieved related model? 
I believe only the CRUD methods are exposed with the nested model. 

Can you repost your question in our Google Groups? as we only accept Bug reports and Feature requests under Github Issues, Please see [link](https://github.com/strongloop/loopback/wiki/Questions).

and If you feel this is a bug please follow the [these steps](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) under the [`Loopback-sdk-angular`](https://github.com/strongloop/loopback-sdk-angular)
