### ISSUE TITLE
run command 'slc ctl' failed !!

### ISSUE THREAD

**Issue by joneqian** [strongloop/loopback#1917]
I run command 'slc ctl' in linux, but it is failed!!
I can run this command yesterday.

This error message is : Command "status" on "http://127.0.0.1:8701" failed with Error: connect ECONNREFUSED 127.0.0.1:8701

The port 8701 is free!!

Why?

Thanks!

**Comment by superkhau** [comment]
@cgole ^

**Comment by darior87** [comment]
up

**Comment by superkhau** [comment]
@cgole ^

**Comment by superkhau** [comment]
@joneqian @darior87 Are you still running into issues? Can I close this?

**Comment by darior87** [comment]
you can close it

**Comment by superkhau** [comment]
@joneqian Please create a new issue if you are still having problems.
