### ISSUE TITLE
disabled `User` methods still appear in explorer

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback#1918]
Following [this documentation](https://docs.strongloop.com/display/public/LB/Authentication%2C+authorization%2C+and+permissions), I am disabling all User methods except ```login``` and ```logout```. I don't need extra behavior so I'm using the User model as-is. 

However, disabled methods still appear in the explorer, but are not accessible.

![untitled](https://cloud.githubusercontent.com/assets/1294805/12016939/163981b2-ad51-11e5-8696-51d2992e9579.png)

I disable all the methods in the following boot script:
```
module.exports = function(app, cb){
  var User = app.models.User;

  User.disableRemoteMethod("create", true);
  User.disableRemoteMethod("upsert", true);
  User.disableRemoteMethod("updateAll", true);
  User.disableRemoteMethod("updateAttributes", false);

  User.disableRemoteMethod("find", true);
  User.disableRemoteMethod("findById", true);
  User.disableRemoteMethod("findOne", true);

  User.disableRemoteMethod("deleteById", true);

  User.disableRemoteMethod("confirm", true);
  User.disableRemoteMethod("count", true);
  User.disableRemoteMethod("exists", true);
  User.disableRemoteMethod("resetPassword", true);

  User.disableRemoteMethod('__count__accessTokens', false);
  User.disableRemoteMethod('__create__accessTokens', false);
  User.disableRemoteMethod('__delete__accessTokens', false);
  User.disableRemoteMethod('__destroyById__accessTokens', false);
  User.disableRemoteMethod('__findById__accessTokens', false);
  User.disableRemoteMethod('__get__accessTokens', false);
  User.disableRemoteMethod('__updateById__accessTokens', false);

  User.create({email: `***@***.***`, password: `***`},function(err,user){
    if(err){
      console.log(err);
      cb();
    }
    console.log("Created admin credentials.");
    cb();
  });
}; 

```
I checked at least 10 times I've restarted the server, just in case you're wondering.
Is there any way to update the swagger doc ? Is it related to the fact that I am disabling methods in a boot script rather than a model.js file ? (Since User is built-in and I cannot modifiy this file)

Thank you for the support

**Comment by mike-aungsan** [comment]
https://github.com/strongloop/loopback/issues/465#issuecomment-151640492

**Comment by richardpringle** [comment]
@Overdrivr, did @mike-aungsan's comment answer your question?

You should extend the _*User*_ model and call your extended model _*user*_ (lowercase 'u') for instance, then disable all the other remote methods from it. The default models are not designed to be customized.

Let me know if that helps!

**Comment by Overdrivr** [comment]
Allright, I didn't know it was mandatory to do that.
Then I suppose I just have to set ```public = false``` for built-in user
Thanks for the support.

**Comment by Overdrivr** [comment]
Maybe a one-liner in the doc (https://docs.strongloop.com/display/public/LB/Exposing+models+over+REST#ExposingmodelsoverREST-HidingmethodsandRESTendpoints)
 could be helpful so that other users are warned.

**Comment by richardpringle** [comment]
@Overdrivr, there is a mention somewhere that you should not/can not customize the default models but I agree, there could be a little reminder on that page. 

@crandmck, thoughts?

**Comment by crandmck** [comment]
I added a note to https://docs.strongloop.com/display/LB/Exposing+models+over+REST#ExposingmodelsoverREST-HidingmethodsandRESTendpoints.
