### ISSUE TITLE
Collaborative Documentation using Markdown

### ISSUE THREAD

**Issue by gaurav21r** [strongloop/loopback#1922]
This issue was spurred on through https://github.com/strongloop/loopback/issues/418#issuecomment-167625725 . It looks like the core developers are documenting using Atlassian Tools. https://docs.strongloop.com/display/public/LB/LoopBack

While the UI and the search functionality and all is great, most modern projects in the JS community have a separate repo to generate static documentation on a beautiful template.

Eg: 
Polymer https://github.com/polymer/docs
Bower https://github.com/bower/bower.github.io
And strongloop's own https://github.com/strongloop/expressjs.com :stuck_out_tongue_winking_eye: 

This will encourage:
  - Bleeding edge documentation. We can read about new features as an when tiny commits are pushed rather than wait for the entire documentation to come.

  - Greater community involvement. I myself have contributed to the above repos though I'm not a core committer. This will ease the pressure on the core team.

  - Markdown is ubiquitous and pretty much an **informal standard** now for documenting projects!

We can build our own static site generate or there are tons of options to choose from:
https://www.staticgen.com/

If there is consensus regarding this. I'd like to help out by atleast contributing something that can automatically migrate current docs to markdown.

**Comment by gaurav21r** [comment]
@bajtos @raymondfeng @crandmck @ritch @superkhau @sam-github Would love to hear your thoughts!

**Comment by crandmck** [comment]
In principle, I think this is a reasonable suggestion.  However, it would be _very_ significant effort to (1) create a new documentation infrastructure (even using something existing like Jekyll) and (2) migrate the existing docs to it.  We have well over 500 pages of docs in Confluence.  While we could undoubtedly come up with some kind of automated process (script) to help with the migration, it would still be a significant undertaking.  (See https://docs.strongloop.com/display/SL/Page+and+word+counts for details on scoping.)  Unfortunately, we don't have the resources to commit to this--I am the only doc person, and time I spent on this would take away from keeping the docs up-to-date.  I doubt the engineering team would be willing to devote significant resources to this effort either.

Up until recently, we allowed community editing of the Confluence docs.  Unfortunately, we had to discontinue this.  

@gaurav21r All the [API documentation](https://apidocs.strongloop.com/) is created from source code comments, to which you can contribute just as you would code (via PR).  This is where most small, incremental changes would initially be reflected anyway.  Please _do_ open PRs for such contributions!

**Comment by superkhau** [comment]
I am +1 for markdown docs, but as stated by @crandmck, it would be a huge undertaking to change from where we are now.

**Comment by sam-github** [comment]
Since I was at-mentioned... I agree with @superkhau and @crandmck . Just not reasonable right now. Lets let the express docs continue to fly, and if we can get out of that tooling to make markdown docs well for large multi-lingual doc projects, then maybe one day there will be resource to apply them to loopback. This isn't the time.

**Comment by crandmck** [comment]
@gaurav21r Thanks for the suggestion, but I'm going to close this now, since we're going to proceed with the existing Confluence doc infrastructure for now.  I have some ideas on how we can reinstate community input, and I will keep you apprised.

**Comment by gaurav21r** [comment]
@crandmck I am going to attempt my hand at this. Step 1 would be to write a script that can *reasonably* parse the Confluence doc format to markdown. There seems to be a few tools in the wild which do this and I want to try them out.

It'll be good if you can tell me if you and the members will actually be open to do this if I can convert it as expected. Don't want to start anything which won't be accepted by you guys. In the same vein, any gotchas you think I should look out for?

**Comment by crandmck** [comment]
@gaurav21r It's a reasonable approach.  However, I can tell you from experience that it's rarely as easy as it seems.   There will always be some manual editing required, which is time-consuming.  Also, you'll have to figure out how to handle images (Confluence attachments), and undoubtedly there will be many other "gotchas".

Also, since we're now a part of IBM, everything has to be approved by IBM management.  Please don't waste your time on this until we can get approval.  Of course, I'll let you know if/when that occurs.
