### ISSUE TITLE
Customize the data returned by api/user/ID?access_token

### ISSUE THREAD

**Issue by yadavji83** [strongloop/loopback#1924]
hi can anyone tell me how can i customise the data returned when calling:
api/users/ID/?access_token=ACCESSTOKEN
i want to get more data from some other model named: UserIdentity

**Comment by alFReD-NSH** [comment]
If you have [defined the relationships](https://docs.strongloop.com/display/public/LB/Creating+model+relations) properly, you can use the [include filter](https://docs.strongloop.com/display/public/LB/Include+filter): `api/users/ID/filter[include]=userIndentities`.

And for the future references, please ask questions on google group.
Thanks

**Comment by superkhau** [comment]
@alFReD-NSH Thanks for helping out. As stated, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
