### ISSUE TITLE
Nested Queries documentation contains bad/unworking example configuration

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback#1925]
@crandmck  The following documentation contains JSON with poorly chosen relation names:

  https://docs.strongloop.com/display/public/LB/Nested+queries

The relations (node, chapter, page) are non-plural, and yet the tables reference URLs that use plural names (pages). These endpoints won't work. The example JSON should be changed to use plural relations.

**Comment by crandmck** [comment]
OK, I changed the relations to `pages`, `chapters`, and `notes`.  Please let me know if that addresses the issue.

**Comment by doublemarked** [comment]
Almost - the last JSON snippet (Page model) still has a singular `note` relation and should be pluralized to `notes`. 

Two other changes you might consider for this document, 

   - I believe in the bullet list at the top you should change the 2nd bullet point to mention page too: *Chapters and pages each have many notes*
   - You mention an Image model and relations but provide no reference to it in the configuration snippets.

**Comment by crandmck** [comment]
Thanks again @doublemarked!  I made the changes you suggest.

Except I don't have the code for the image model.  @Amir-61 Do you have that?

**Comment by crandmck** [comment]
OK, I added the snippet for the image model.  I'm going to close this... 

Thanks again @doublemarked I really appreciate your constructive input!

**Comment by doublemarked** [comment]
You're welcome!
