### ISSUE TITLE
Handle body-parser errors

### ISSUE THREAD

**Issue by kpasokhi** [strongloop/loopback#1926]
I've added `body-parser` to `middleware.json` and it works correctly. 
```javascript
  "parse": {    
    "body-parser#json": {},
    "body-parser#urlencoded": {
      "params": {
        "extended": true
      }
    }
  },
```
I tried to handle all app errors with [Customizing REST error handling](https://docs.strongloop.com/display/public/LB/Environment-specific+configuration#Environment-specificconfiguration-CustomizingRESTerrorhandling) but it fails to handle `body-parser` errors when `json` syntax is not valid and bypasses it.
Any help is appreciated.

**Comment by Amir-61** [comment]
Hey @kpasokhi,

Could you please provide a sample repo using our [loopback-sandbox](https://github.com/sharkinsspatial/loopback-sandbox) to reproduce the issue?

Thanks a lot!

**Comment by Amir-61** [comment]
I'm closing this ticket due to inactivity... Please feel free to re-open the issue if the problem persists with a sample repo using our [loopback-sandbox](https://github.com/sharkinsspatial/loopback-sandbox) to reproduce the issue...

Thanks!
