### ISSUE TITLE
I want to import model into my project!

### ISSUE THREAD

**Issue by joneqian** [strongloop/loopback#1928]
I use bower to manage my model.
I can import model into my project by bower and gulp.

Does loopback api or slc provide this feature?

Thanks!!

**Comment by 0candy** [comment]
If you have swagger specs, you can import into loopback:
https://docs.strongloop.com/display/public/LB/Swagger+generator

If this is not what you are looking for, could you please provide more details as to what you are trying to do?  Thanks!

**Comment by superkhau** [comment]
@joneqian LoopBack does not provide direct migration from a bower model to a LoopBack model. However, you can use the [automigrate](https://docs.strongloop.com/display/public/LB/Creating+a+database+schema+from+models) feature to build a database schema from existing LoopBack models. You would of course need to convert your bower model definitions to LoopBack model definitions first.

The other way is to get your bower models into a supported database and use discovery to build LoopBack models from the persisted bower models. See [discovery](https://docs.strongloop.com/display/public/LB/Database+discovery+API).

**Comment by superkhau** [comment]
For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.
