### ISSUE TITLE
mongodb populate in loopback

### ISSUE THREAD

**Issue by muditsatija1** [strongloop/loopback#1930]
Hey i am new to loopback though i have been using mongoose for mongodb and express for a while now.
I could not find anything in loopback docs to populate a field if there is no relation between two models, so i'm opening an issue here.

**Comment by rawrmaan** [comment]
This is very vague, you'll need to be more specific. What exactly are you trying to do?

**Comment by muditsatija1** [comment]
model name: 'md1",
properties: {
    "post": {
      "type": "string"
    }
 }

model name: 'md2',
properties: {
   "username": {
        "type": "string"
    }
    "md1_id": {
       "type": "objectId"
    }
}

These are my two models, so now i want to populate the name from the md2 model. In mongoose i use to do the following to populate :-
md1.populate('md2object', {'path': md1_id, 'select': 'name'}, function(err, resp) {....}

i hope i have explained my query correctly.

**Comment by richardpringle** [comment]
Hey @muditsatija1, you can find all the MongoDB docs [here](https://docs.strongloop.com/display/public/LB/MongoDB+connector). 

For future reference, please use [fenced code blocks](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) to make your code easier to read. Also, we have a dedicated forum for questions: https://groups.google.com/forum/#!forum/loopbackjs. 

See https://github.com/strongloop/loopback/wiki/Questions for more details on asking questions about LoopBack.

Good luck!
