### ISSUE TITLE
I want destroyAll token by user, but it is failed.

### ISSUE THREAD

**Issue by joneqian** [strongloop/loopback#1933]
my code is:
Access.destroyAll({where: {userId: user}}, function(){});

error msg is:
no indexes found for where impossible to sort and filter using redis connector

please help me check it!
Thanks!

**Comment by joneqian** [comment]
I fix it, should be {userId: user},  no 'where'!
Please update loopback document, thanks!

**Comment by 0candy** [comment]
Thanks for pointing this out, in the doc description column, you can see that it says you can add an Optional where filter, like: {key: val, key2: {gt: 'val2'}, ...} . Don't have to include the word where.

https://apidocs.strongloop.com/loopback/#persistedmodel-destroyall
