### ISSUE TITLE
Authentication through Social Login 

### ISSUE THREAD

**Issue by J0N47H4N** [strongloop/loopback#1937]
I am starting to gain grounds with `loopback api`. Currently I am trying to integrate authentication through social logins for my app. I have found three pages that indicate how to accommplish this but they all show this a bit differently and unclear: [github-loopback-component-passport](https://github.com/strongloop/loopback-component-passport) & [npmjs-loopback-component-passport](https://www.npmjs.com/package/loopback-passport) & [github-loopback-component-passport-example](https://github.com/strongloop/loopback-example-passport). I am bit confused as to what is the most up to date process. Can anyone shed some light in how to best integrate social login with loopback? Also, how to test it for routes that may require access tokens? Here is the [Github Repo](https://github.com/J0N47H4N/games-strongloop-api) of the project.

Current Dependencies

 

    "dependencies": {
        "compression": "^1.0.3",
        "cors": "^2.5.2",
        "lodash": "^3.10.1",
        "loopback": "^2.26.2",
        "loopback-boot": "^2.6.5",
        "loopback-component-explorer": "^2.1.0",
        "loopback-connector-mysql": "^2.2.0",
        "loopback-datasource-juggler": "^2.19.0",
        "loopback-stormpath": "0.0.1",
        "serve-favicon": "^2.0.1",
        "passport": "^0.3.2",
        "underscore": "^1.8.2"
      }

**Comment by BerkeleyTrue** [comment]
@J0N47H4N loopback-component-passport replaces loopback-passport. 

To see an example in production checkout https://github.com/freecodecamp/freecodecamp

Here is where we configure the social logins https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/passport-providers.js

Here is where we actually set it up with the server https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/server.js#L88

**Comment by J0N47H4N** [comment]
@BerkeleyTrue great will look into that!

**Comment by J0N47H4N** [comment]
@BerkeleyTrue a noob question, but where do I find my `process.env` file or how do I set that up?

**Comment by BerkeleyTrue** [comment]
Great. I think this issue can be closed now.

**Comment by davidcheung** [comment]
Closing issue, looks like it has been resolved.
