### ISSUE TITLE
How do I use RequestBuilder ?

### ISSUE THREAD

**Issue by joneqian** [strongloop/loopback#1938]
Has RequestBuilder been abandoned in the latest version?
How do I use RequestBuilder ?

Thanks!!

**Comment by richardpringle** [comment]
Hey @joneqian, Request Builder is a part of [the LoopBack-connector-rest module](https://github.com/strongloop/loopback-connector-rest)

As for how to use it, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

Good luck!
