### ISSUE TITLE
loopback-testing module was deprecated?

### ISSUE THREAD

**Issue by philarmour** [strongloop/loopback#1940]
Hi Loopback team,

The repository for loopback-testing (https://github.com/strongloop/loopback-testing) appears to be gone and @bajtos has informed me that the module was recently deprecated (late December 2015). Was this decision documented/announced somewhere?  Is there a good (or standard) way to review a deprecated project?

I see some references to the deprecation here: https://github.com/strongloop/loopback/issues/1059 and here: https://github.com/strongloop/loopback/pull/1935

I see that this repo (https://github.com/karlmikko/loopback-testing) that appears to have some of the history (possibly a fork or maybe the original), but appears to be old (depends on "loopback": "^1.6.1") and also doesn't have the history of issues and PRs.  I don't think that repo will work for me, and the latest release version in the npm repo doesn't have some resolved PRs like #56 and #57 which dealt with bugs around logged in-users and custom user models.

I had some code that was dependent on the latest source (I was hoping to switch to the next npm release). Given these developments, I will probably just revisit my decision to use the library for my test cases.

This may also be a good forum to discuss the rationale  behind the decision to deprecate if it wasn't documented elsewhere.

**Comment by superkhau** [comment]
https://groups.google.com/forum/#!topic/loopbackjs/w038RvqHeYI

**Comment by superkhau** [comment]
We announced the deprecation notice in the Google group.

>Is there a good (or standard) way to review a deprecated project?

The standard we use ATM is to announce it the Google Group and then leave a notice stickied at the top for awhile (I think we should set a standard time like you say though - typically it's been a week or 2, but should probably be like a month). The LoopBack wiki sounds like a good place for this. I will create an issue for our sprint planning.

I will unarchive the repo so you can do what you need to do and close it officially on Feb 1st to give the community more time to do what they need to do. ;)

**Comment by superkhau** [comment]
https://github.com/strongloop/loopback/issues/1941
