### ISSUE TITLE
Official deprecation notice guidelines for deprecating a GH repository

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#1941]
I would like to start a discussion on what the community thinks about deprecation notice and times. The current unofficial procedure is:
- Post a notice on Google Groups (stickied at top) for 2 weeks
- Add DEPRECATED to the GitHub repo description (ie. DEPRECATED An example that demonstrates...)
- Archive the repo after 2 weeks

I'm thinking we should increase this to 4 weeks. I want to gather some ideas and make it official at https://github.com/strongloop/loopback/wiki/WIP-Deprecated-projects.

Thoughts?

---

Steps so far:
- Post a notice on Google Groups (stickied at top) for 2 weeks
- Add the deprecation notice to the GitHub repo description
- Add the deprecation notice to the README
- Run `npm deprecate $repoName '$deprecationNotice'
- Mark the repo as private after 4 weeks

**Comment by philarmour** [comment]
This appears to be the current answer (at least according to SO) for "retiring" a project: http://stackoverflow.com/a/22597985/4413888

Also, you reference "Archiving the repo", but I'm not really clear on what you mean.  As best I can tell, Github doesn't provide an archive feature: https://help.github.com/articles/can-i-archive-a-repository/  (although there does appear to be 3rd-party support for such functionality.)

**Comment by superkhau** [comment]
>This appears to be the current answer (at least according to SO) for "retiring" a project: http://stackoverflow.com/a/22597985/4413888

Good ideas, will add them to the list in the first comment.

>Also, you reference "Archiving the repo", but I'm not really clear on what you mean. As best I can tell, Github doesn't provide an archive feature: https://help.github.com/articles/can-i-archive-a-repository/ (although there does appear to be 3rd-party support for such functionality.)

The procedure here at StrongLoop is not to "delete" any repos. We just mark the as private and keep the code in case a need comes up later (like in your case I made the public again).

**Comment by bajtos** [comment]
In my opinion, we should not hide (mark as private) any public repositories that are deprecated. It confuses users, especially since the npmjs.org website will still contain a link to the GitHub repository. It also makes it more difficult for community members to take over the project, as they cannot simply fork the project with full git history.

What is the original motivation for archiving deprecated projects? What are the downsides of keeping them around, considering they are public and thus don't incur any GitHub charges?

@ritch @raymondfeng @sam-github @rmg @piscisaureus

**Comment by bajtos** [comment]
> Add DEPRECATED to the GitHub repo description (ie. DEPRECATED An example that demonstrates...)

For projects published to any registry (npmjs.org, Maven, nuget, etc.), I think we should offer community members a chance to take over the maintenance, so that the project can live on.

**Comment by sam-github** [comment]
I agree with @bajtos, why would we make a repo private once its published?

**Comment by rmg** [comment]
Seconded, we shouldn't be making them private unless there's a very good reason to do so (legal issues, for example). If we are simply retiring a module, **and** the goal is to de-clutter, we should just be moving it to strongloop-community and leaving it public.

**Comment by superkhau** [comment]
>What is the original motivation for archiving deprecated projects?

It was decided awhile back from a discussion with @altsang to mark repos as private, then move them to the strongloop-archive org. I originally wanted to keep the code public (so people can still reference the code if they need, etc), but @altsang said we don't want any comments/maintenance on the old projects, just mark them as private and move them there. Then he gave me perms (and @crandmck) to archive projects via that process. Anyways, the movtivation for this new discussion is I don't agree with the current procedures (just like you @sam-github and @rmg), so I want to formalize official procedures in the LoopBack wiki and make it public for the community to see.

> It confuses users, especially since the npmjs.org website will still contain a link to the GitHub repository. It also makes it more difficult for community members to take over the project, as they cannot simply fork the project with full git history.

+1

>why would we make a repo private once its published?

I agree this has no benefit to the open source community.

>Seconded, we shouldn't be making them private unless there's a very good reason to do so (legal issues, for example). If we are simply retiring a module, and the goal is to de-clutter, we should just be moving it to strongloop-community and leaving it public.

+1 for only privating for legal or executive decisions.
+1 for decluttering and moving to strongloop-community

In addition to those comments, if we want to declutter private repos (that are legal/executive decisions) in the strongloop org, we should move those specific ones to the strongloop-archive org.

Thanks everyone for the comments so far.

**Comment by rmg** [comment]
@superkhau I think that discussion with @altsang was around example repositories, not published modules, which seems to be what is being discussed here.

**Comment by sam-github** [comment]
I don't know about the original discussion, but for example modules, I've no problem with making them private. But for a package that has been published to npmjs.org, even if we eventually publish a version saying "we don't maintain this anymore", we should leave the package with a valid link to a public github repo, so others have the opportunity to fork and maintain the code, if they want (though they'd have to  publish under a new name). Or at least, so they can read the code easily and troubleshoot bugs.

Sounds like we are all in agreement on this!

**Comment by superkhau** [comment]
>I think that discussion with @altsang was around example repositories, not published modules, which seems to be what is being discussed here.

I'm talking about all repos, but I get the point that published modules should be left pointing to an accessible public repo.

>Sounds like we are all in agreement on this!

Yes, we are. I will create a task to formalize this in the wiki. I'll ping you guys again for review when its done.

**Comment by gaurav21r** [comment]
I would suggest this (No new Ideas here just a compilation):

1. I really appreciate @superkhau to ask for community involvement in a matter which is usually dictated by the company! Similarly, as much as possible, ask for community feedback before deprecating a module. Strongloop employees can describe *why* they are deprecating a module and the community could not only participate but can also *empathise* why its being done. 

2. Move all deprecated projects to a public organisation called, maybe **strong-archived** or something. This will / should remove all legal / moral obligations of StrongLoop to support this project.
This is how **facebook** does this : https://github.com/facebookarchive So I guess it is OK for organisations of the size of IBM / Facebook to do this from all standpoints (legal etc.)

3. Code should always be open! There are *TONS* of repos on github that are doing well that were originally forks of archived projects. Why stop the innovation, after doing all the hard work to create it in the first place? Why spend money on keeping them private no matter how small the amount? :)

4. Incase old commits / comments are causing an issue, why not erase the git history and add the archived project to the new GitHub Organisation as a fresh repo with a single commit?

@altsang has been referenced a lot of times in this thread, maybe he can weigh in on this here only?

**Comment by superkhau** [comment]
Connect to https://github.com/strongloop-internal/scrum-loopback/issues/698

**Comment by superkhau** [comment]
@gaurav21r Thanks for the kind words. It's my goal to make sure everyone in the LB community are getting what you need from us (there is always room for improvement -- we listen and are very flexible regarding change). That said:

1. Will add these considerations to the guidelines
2. We have a private org for archiving (strongloop-archive), but I will bring it up and try to see if we can make it public.
3. Agreed, we are an open source project. However, there are some things that take a bit more work to manage before releasing it out to the wild (ie. configs, old policies, etc).
4. Not a bad idea, I will bring this up with the team too.

Regarding @altsang, he is no longer with the compnay so we'll have to continue the without him from hereon out.
