### ISSUE TITLE
post-processing middleware

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback#1947]
I have read this page.
https://docs.strongloop.com/display/public/LB/Defining+middleware

"I need to register middleware that will be called after all the rest API route."

I tried at final phase. Look like it is only for error.
I tried at "routes:after" phase. It does not trigger.

I am looking for something like Event: 'after' in restify.
http://mcavage.me/node-restify/#server-api-2

**Comment by gunjpan** [comment]
@mike-aungsan : Hi Mike, 
> I tried at "routes:after" phase. It does not trigger.

yes, it won't trigger: See this ([Routing middleware](https://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Routingmiddleware)):

>If you add middleware on the route or route:after phase, it will not execute after the route is matched. Instead, it will be ignored because the route was already matched.

You can add a `Custom Phase` in `middleware.json`, after `routes` phase and register your `middleware` within that phase like:
```
   "routes":{ 
    ...
   },
   "yourCustomPhase": {
     "yourMiddleware": {}
   }
...
```
Custom phases can be defined in any position of the middleware chain, and maybe be used to prioritize over LoopBack's built-in middleware phases. More about LoopBack middleware chain [here](https://docs.strongloop.com/display/public/LB/Routing#Routing-LoopBackmiddlewarechain)

Hope that helps. Please let me know if you need any further assistance, please let me know.

**Comment by mike-aungsan** [comment]
Pretty sure I did keep trying that yesterday.

    "routes":{ 
        ...
    },
    "routesAfter": {
        "./middleware/record": {}
    },

It works now :) :+1: 

Thanks

**Comment by gunjpan** [comment]
@mike-aungsan : Awesome! :+1:

**Comment by mike-aungsan** [comment]
@gunjpan  My bad. It does not work.

It is actually triggered from server middleware.

    var record = require('./middleware/record')
    app.middleware('parse:after', record());

**Comment by gunjpan** [comment]
@mike-aungsan : Interesting. Could you please share a sample repo so that I can recreate the issue on myside and investigate further. Thank you.

**Comment by gunjpan** [comment]
@mike-aungsan : Hi Mike, are you still facing the above issue or had it resolved? I couldn't reproduce it :(

**Comment by mike-aungsan** [comment]
@gunjpan  Still having the issue. Did you insert after route ?

**Comment by mike-aungsan** [comment]
It is very wired. We can close it now... Something cause that problem, but same like you, I cannot reproduce in the empty project.
