### ISSUE TITLE
error doc using Date as function in lt and gt filter

### ISSUE THREAD

**Issue by Neil-UWA** [strongloop/loopback#1948]
https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-gtandlt
```
Employees.find({
  where: { 
    date: {gt: Date('2014-04-01T18:30:00.000Z')}
  }
});
```
When Date is called as a function, it returns a String representing current date and time. Therefore the above example should be : 

```
Employees.find({
  where: { 
    date: {gt: new Date('2014-04-01T18:30:00.000Z')}
  }
});
```

**Comment by gunjpan** [comment]
@Neil-UWA : Hi Neil, thank you for bringing this to our attention. It has been corrected now.
Thanks again and have a great weekend :)
