### ISSUE TITLE
RemoteMethods can return html?

### ISSUE THREAD

**Issue by darior87** [strongloop/loopback#1949]
I know that if I expose a model's remote method I can set the return value type, but can I do something like this (have tried but not working for me)?

```javascript
Modelname.remoteMethod(
    'foo',
    {
      http: {path: '/my-url', verb: 'post'},
      accepts: [
        {arg: 'myobj' type: 'object'}
      ],
      returns: {root: true, type: 'html'}
    }
  );
```
```javascript
Modelname.foo = function(myobj,cb){
    cb(null,"<html><head></head><body>HTML PAGE</body></html>")
);
```

It returns (as a plain string)
```
"<html><head></head><body>HTML PAGE</body></html>"
```

**Comment by richardpringle** [comment]
Hey Dario, the return type must be a [LoopBack Type](https://docs.strongloop.com/display/public/LB/LoopBack+types).

For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

Happy programming!

**Comment by jmdiego** [comment]
@darior87 the easiest way to do that is to pass the "res" parameter into the method via the accepts parameter {arg: 'res', description: 'Request\'s response object', type: 'object', required: true, http: { source: 'res'}} and use that as res.send(yourHtml);

That way you will avoid any parsing, handling and type-checking loopback forces in the response.

**Comment by samih-dev** [comment]
Thanks jmdiego, 

just needed to take care of one more thing - remote the `returns: [...]` in the model definition - as with it, an error is being thrown related to the headers set.

hope this helps someone, and keeping this as reference to me :)
