### ISSUE TITLE
Documentation on ReferencesMany relationship

### ISSUE THREAD

**Issue by dmisdm** [strongloop/loopback#1952]
The parameters for the definition of ReferencesMany type relationship lacks foreignKey.

Quote:
Parameters for the definition
* methods
* properties
* scope
* options
* default
* property
* as

Knowing that we could define what the name of the foreignKey was really useful.

**Comment by jannyHou** [comment]
hey @dmisdm thanks for your suggestion! It's reasonable to add it to parameters list. We will apply change in the near future and see if there is somewhere similar to mention it as well!

**Comment by dmisdm** [comment]
Hey Thanks!

My team and i were having some issues with understanding relationships and
the fact that it wasn't there confused us a bit. We understand it now
though! And really useful being able to use that parameter in references
many.

Cheers!

**Comment by jannyHou** [comment]
I am closing it since doc has been updated:
https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations#Embeddedmodelsandrelations-ReferencesMany
Thanks.
