### ISSUE TITLE
belongsTo API is unclear, cannot get it to work

### ISSUE THREAD

**Issue by jbcpollak** [strongloop/loopback#1962]
The [documentation for `belongsTo`](https://docs.strongloop.com/display/public/LB/BelongsTo+relations) is vague, and I am having trouble getting it to work as expected.

I have something like what is shown in the documentation:

    {
      "name": "Item",
      "base": "PersistedModel",
      ...
      "relations": {
        "curPerson": {
          "type": "belongsTo",
          "model": "Person",
          "foreignKey": "curPersonId"
        },
        "people": {
          "type": "hasMany",
          "model": "Person",
          "foreignKey": "itemId"
        },
      },

I am using a memory datastore, and `customerId` is not defined anywhere else in the `Item` model. In addition, there is no reciprocal `hasMany` or `hasOne` link from `Person` to `Item`. There _is_ a second reference to the `Person` model, since an `Item` can be associated with multiple people at the same time, but only has one person currently.

Calling this code works fine:

    item.curPerson(newPerson);
    item.save();

I can verify the curPersonId is updated in the database.

However, _retrieving_ the current person does not seem to work correctly. If I make this call:

    item.curPerson(function(err, person) {
        console.log('Person: ', person);
    }

The callback is not executed, but curPerson seems to _return_ the Person's id (but not the object).

If I call this:

    person = item.curPerson();

`person` will be undefined.

I wanted to dig into the code of how these methods were generated, but I couldn't figure out where they are in the loopback code.

**Comment by jbcpollak** [comment]
I should add that the REST API seems to work fine:

http://localhost:3000/api/Items/53/curPerson

returns the person I was expecting.

This makes this probably all the more frustrating, because apparently it DOES work, but I can't find the code to demonstrate how to do it.

**Comment by jbcpollak** [comment]
I was able to get the callback form of the function to work. I'm not sure why it wasn't working for me before.

I will say the documentation for the synchronous form of the getter could explain itself better. 

"Synchronously get the results of a previous get call to customer(...)"

That seems to imply it only works once you've done the callback version successfully once. This seems like a dangerous method to include.

**Comment by richardpringle** [comment]
Hey @jbcpollak, glad you were able to figure everything out (even with the troubles). The LoopBack framework is pretty complex and therefore difficult to document. I will say that there are teams continuously working to improve both.

Is it safe for me to close the issue? If not, you can reopen with a comment and I will take a look.

**Comment by jbcpollak** [comment]
Please close it, thanks!
