### ISSUE TITLE
Built-in User model email validation have issue with new loopback-component-passport with LDAP provider

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback#1963]
For LDAP provider, user email become username@domain.com@loopback.provider.com  and validation fail.

loopback-component-passport:
All third party accounts will login with an email of uniqueID@loopback.provider.com example 123456@loopback.facebook.com

Line 702:

    // email validation regex
    var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    
    //UserModel.validatesFormatOf('email', {with: re, message: 'Must provide a valid email'});

**Comment by loay** [comment]
Thanks for reporting the issue. Checking now..

**Comment by loay** [comment]
Issue is fixed.
a test case is added as well. 
Closing. If you still see an issue, please leave a comment and we will re-open. Thanks.

**Comment by mike-aungsan** [comment]
@loay 

I have email address like this. fname.midname.lastname@domain.co.uk

You test case need to run with LDAP authentication and loopback-component-passport.

Let's say I am authenticating with LDAP domain github.com

What loopback-component-passport does is that, it added authentication provider to email address.

So email address become fname.midname.lastname@github.com@github.com
I forgot the line of the code it does. Pretty sure I have read source which does.
This ticket really making me to stop upgrade to latest version.

Oh, I just found the link. 
https://github.com/strongloop/loopback-component-passport/issues/119

==============

For LDAP provider, user email become username@domain.com@loopback.provider.com and validation fail.

loopback-component-passport:
All third party accounts will login with an email of uniqueID@loopback.provider.com example 123456@loopback.facebook.com

=============

Nothing wrong with email validation regex. We need to fix "loopback-component-passport": "2.0.0"

Why loopback-component-passport add provider.com ???

Problem still exists in the following version.

"loopback": "2.27.0",
"loopback-boot": "2.17.0",
"loopback-component-explorer": "2.3.0",
"loopback-datasource-juggler": "2.45.2",
"loopback-component-passport": "2.0.0",

**Comment by loay** [comment]
Hi @mike-aungsan,
I am having a look at that.

**Comment by mike-aungsan** [comment]
Thanks
