### ISSUE TITLE
Not able to use $in at AngularJS SDK

### ISSUE THREAD

**Issue by csmtcy** [strongloop/loopback#1965]
I'm trying to use the $in command from mongodb ... but i found that it doesn't work. 
It doesn't give me any error, but the result was wrong. It return all records from that collections. 

Feed.find({
   accountId : { $in : ["569a9fc898e6f58b0329eefc", "569a9fa098e6f58b0329eefb"] }
});

Hope can get a solution for this. Thanks.

**Comment by 0candy** [comment]
Can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by csmtcy** [comment]
Hi sorry about that, i have wrote the condition in codepen. 
http://codepen.io/anon/pen/MKObVj

**Comment by gunjpan** [comment]
@csmtcy : Hi, I played around with the code at link above... `inq` operator should be used with `where` filter as follows, in LoopBack:
 
```
$scope.inFeeds = Feed.find({
    filter: {
      where: {
        accountId: {
          inq: ["5698802351285f64077a9d20", "569a9fa098e6f58b0329eefb"]
        }
      }
    }
  });
```
`inq` operator in `where` filter checks whether the value of the specified property matches any of the values provided in an array.
More about on how to query using `inq` [HERE](https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-inq)
Hope that helps!

**Comment by csmtcy** [comment]
@gunjpan Hi, is that not able to use any mongodb native function ? like $in ? Thanks for the reply.

**Comment by gunjpan** [comment]
@csmtcy : As MongoDB connector for LoopBack supports [Logical Operators](https://docs.strongloop.com/display/public/LB/MongoDB+connector#MongoDBconnector-Querywithlogicaloperators%28sincev1.2.3%29), it may support Comparison Operators like `$in` (though, docs doesn't mention it).
Can you please try `$in` without `$` (same synatx as logical operators) and see if it works.

Apart from that FYI: if you need to run `native` query, you would have to do something like:
`dataSource.connector.execute(sql, params, cb);` 
See [here](https://docs.strongloop.com/display/public/LB/Executing+native+SQL)

**Comment by csmtcy** [comment]
I see, finally get it now.. i'm trying the previous solution ... thanks for the solution and information ... appreciate it

**Comment by gunjpan** [comment]
@csmtcy : glad that I could be of help. Can this be closed now?

**Comment by csmtcy** [comment]
@gunjpan Hi, i tried the first solution and create it at the server model, but i'm still not getting the correct result. It always return the empty array. Please give me some advise. Thanks. 
```
Feed.groupfeed = function(id_array, cb) {
    Feed.find({where: {accountId: {inq: ["569a9fc898e6f58b0329eefc", "569a9fa098e6f58b0329eefb"]}}},
    function (err, feeds){
      cb(null, feeds);
    });

  };
```

**Comment by alFReD-NSH** [comment]
It could be possible that your ids are not converted to ObjectId but they are stored as ObjectId in the database.

**Comment by csmtcy** [comment]
@alFReD-NSH Hi, i stored the accountId as string. Thanks for the reply.

**Comment by gunjpan** [comment]
@csmtcy : Hi, I'm not sure what's happening with your code. It would be great if you could please upload your repo on GH (or a sandbox with this problem only) and I would take a look.

Meanwhile, I created a sample app with LoopBack and I was able to get `inq` operator work. [See this branch](https://github.com/gunjpan/AQuery/blob/lb-1965/client/js/controllers/question.js#L8)
To see it in action, first clone the project from master and run it.. check `All Questions` tab and compare it with app run from branch, and see what's missing for your code.

Hope that helps!

**Comment by csmtcy** [comment]
@gunjpan Hi, i'm guessing that it was the server script problem, because i can't even get the result by using the explorer. I upload the server scripts to github. (Latest is in development branch)
https://github.com/csmtcy/hbelp

I cloned your repo but i get authentication issue when start the node app.

**Comment by gunjpan** [comment]
@csmtcy : Hi, my apologies for a delayed reply. Are you still facing this issue?
I tried to access the link you posted and I get `404`.

**Comment by gunjpan** [comment]
@csmtcy : Hi, closing this issue for now due to inactivity. Should you need any further assistance, please feel free to reopen it and mention me in the comments, will be happy to assist :)
