### ISSUE TITLE
Broken links to 'sample data' generation scripts in 'model relations' tutorial

### ISSUE THREAD

**Issue by tebs1200** [strongloop/loopback#1968]
The tutorial on [model relations](https://docs.strongloop.com/display/public/LB/Tutorial%3A+model+relations) links to some JavaScript  files that will generate sample reviews and orders, but these resources 404.

**Comment by jannyHou** [comment]
hey @tebs1200 We merged two loopback relation examples:
loopback-example-relations
and
loopback-example-embedded-relations

Therefore causing some code refactoring. The doc for that hasn't updated. Please follow this new example [loopback-example-relations](https://github.com/strongloop/loopback-example-relations) to get started with loopback. The tutorial explains how to build that example step by step. Hope it would be helpful!

**Comment by superkhau** [comment]
@crandmck ^

**Comment by superkhau** [comment]
https://github.com/strongloop/loopback-example-relations/issues/14

**Comment by crandmck** [comment]
Fixed those links.
