### ISSUE TITLE
loopback-getting-started tutorial: Use API Explorer needs update?

### ISSUE THREAD

**Issue by davidhbrown** [strongloop/loopback#1969]
Working through the [Getting Started with LoopBack](https://docs.strongloop.com/display/LB/Getting+started+with+LoopBack) tutorial, I noticed a few things in the [second page] (https://docs.strongloop.com/display/public/LB/Use+API+Explorer), last edited 2015-11-19 that seems to be out-of-date relative to the [first page](https://docs.strongloop.com/display/LB/Create+a+simple+API), edited 2015-12-14, about a month later. I just updated LoopBack today; it says it's version 2.26.2.

The StrongLoop API Explorer (loopback-component-explorer v 2.2.0) is displaying a bit differently, including the application name and the Model names in singular, not plural. I'm attaching a screen capture from my computer; there are also minor text changes. There are also some new APIs, so I've attached a screen capture of the API endpoints. I did not continue as there are some helpful overlays on the next screen capture.

The CoffeeShop schema defined on the first page now includes a required "**city**" field as well as the name; all of the screen captures, code sample, and text on page two show only "name".

<img width="427" alt="api explorer" src="https://cloud.githubusercontent.com/assets/749520/12382252/ffc61e0c-bd65-11e5-8540-ddbf5e1c8855.png">
<img width="430" alt="gs-first-api-explorer" src="https://cloud.githubusercontent.com/assets/749520/12382253/ffc80b54-bd65-11e5-9610-f8def1ea60bd.png">

Urgh... how do I label this "doc"? Yes, I'll go search for [Github's help](https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/) but I don't see the checkboxes it talks about, maybe because it's not my repository? Sorry if I'm being clueless; really tried to find it.

**Comment by crandmck** [comment]
@davidhbrown Thanks for catching this.  You're right, it does appear that some things in Explorer changed, but docs have not yet caught up.

**Comment by crandmck** [comment]
I updated the screenshots in https://docs.strongloop.com/display/LB/Use+API+Explorer.
Thanks again @davidhbrown
