### ISSUE TITLE
it is not possible find users with different realms from tokenId

### ISSUE THREAD

**Issue by shSina** [strongloop/loopback#1970]
Hi , I used realm to partition users and administrators , they have different models that inherits from base User model ,  
**the use case** : administrators don't need users api end point (need of the same tokenid source) , but need access to all (include user) models throw app.models... , ACL and Roles based access.

**the problem** : by partitioning users using realms , I can't differentiate between users and admins in endpoints (may be I didn't understand realms usage..), because the token doesn't keep realm that I can query the right model (ex. attach the user to ctx is not possible , not related to my use case only).

**possible solutions**: 
1- I can use different models that inherits from User , but with different tokenId source (where should I specify different model source for AccessTokens?)
2- use totally different app , I need some events that needed by same process(possible but not good idea)

**what is the best solution?**

**Comment by shSina** [comment]
I found a solution in [issues](https://github.com/strongloop/loopback/issues/527#issuecomment-60557619) to solve the problem like this , by adding extra property to tokens:
update the inherited user models in ex. user.js file :
```
	user.prototype.createAccessToken = function(ttl, options, cb) {
	    if (cb === undefined && typeof options === 'function') {
	      // createAccessToken(ttl, cb)
	      cb = options;
	      options = undefined;
	    }

	    cb = cb || utils.createPromiseCallback();

	    if (typeof ttl === 'object' && !options) {
	      // createAccessToken(options, cb)
	      options = ttl;
	      ttl = options.ttl;
	    }
	    options = options || {};
	    var userModel = this.constructor;
	    ttl = Math.min(ttl || userModel.settings.ttl, userModel.settings.maxTTL);
	    this.accessTokens.create({
	      ttl: ttl,
	      model: userModel.modelName
	    }, cb);
	    return cb.promise;
	};
```

**Comment by poupougnac** [comment]
Thank you, but this issue it is not *solved* as those lines still don't work if you don't patch the access-oken model in the loopback core code, isn't ?

**Comment by shSina** [comment]
no you can add the above code in your model inherited from User and solve it just now, I think adding extra attribute to accessTokens need more discussion, if there is more people facing the same problem , I will make a patch and pull request the main repo :+1: 
just remember to require this util.js file that required in core loopback User model  :
```js
exports.createPromiseCallback = createPromiseCallback;

function createPromiseCallback() {
  var cb;

  if (!global.Promise) {
    cb = function() {};
    cb.promise = {};
    Object.defineProperty(cb.promise, 'then', { get: throwPromiseNotDefined });
    Object.defineProperty(cb.promise, 'catch', { get: throwPromiseNotDefined });
    return cb;
  }

  var promise = new global.Promise(function(resolve, reject) {
    cb = function(err, data) {
      if (err) return reject(err);
      return resolve(data);
    };
  });
  cb.promise = promise;
  return cb;
}

function throwPromiseNotDefined() {
  throw new Error(
    'Your Node runtime does support ES6 Promises. ' +
    'Set "global.Promise" to your preferred implementation of promises.');
}

```

**Comment by shSina** [comment]
there may be other solutions , the realm stored in user instance , every where you need to determine user type , you can query the userId accessed from token in ctx , and get the realm, in fact if the realm store in both user and access token , may be the best solution(fast access but duplicated data).

but I think querying the user model when ever needed to determine the realm may has less tradeoffs,
if you need realm or user type for every request , attaching the realm or user type to token has better performance , if most of the requests just need authentication but in less routings need authorization , better to query the user model.

I needed to authorize every request. after all as a framework , it's better loopback keep realms in both token and user to fulfill performance issues (querying the data base to both authenticate and authorize at once)

**Comment by sebastianfelipe** [comment]
Thanks! Same problem. I think a lot of users has the same problem, really is very useful to have the model account which has been used to log in a user. Thanks. I read the answer, I haven't implemented yet, but I know that is the answer I was looking for. :)

**Comment by sebastianfelipe** [comment]
One last thing. The problem still affecting the implementation of solutions. Because the ACL doesn't discriminate between the model. It would be very good if the ACL can add a new feature called model or something. For example "authenticate" with model "model", or something simila, and for behind, compare the model of the that was added in the "createAccesstoken" with that added in the ACL. In case that no model has been set in the ACL, then is useful every account. I don't know, I'm thinking out loud. But really, it would be very useful, I think a lot of programmers have been thinking in this.

Thanks.

**Comment by shSina** [comment]
it is possible to handle the issue by creating new admin role in server boot scripts folder as below ,
```js
module.exports = function(app) {
		var Role = app.models.Role;
		Role.registerResolver('admin', function(role, context, cb) {
				function reject(err) {
					if(err) {
						return cb(err);
					}
					cb(null, false);
				}
				if(!context.accessToken.userId) {
					return reject(); // do not allow anonymous users
				}
				if(context.accessToken.model == 'admin') {
					return cb(null, true);
				}
				reject();
		});
};
```
and use it like this(in models acls ):
```js
{
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "create"
}
```

**Comment by sebastianfelipe** [comment]
Thanks, yes, I was thinking in implement that option. Thanks. I made the changes you posted above, and when I log in with a user, I have the model name feedback as we wanted. The problem I have, is that when I migrate the database I won't have the "model" column. That has to be added by hand? I mean, is there any way to add the physical column to the database by automigration or similar? Thanks.

**Comment by sebastianfelipe** [comment]
With MongoDB, I don't have problems, but with relational databases, I've tried and I haven't found a good implementation. I'm trying with Mysql :/

**Comment by sebastianfelipe** [comment]
I thought in a solution, I already tested. In case that we use relational databases, like MySql, to migrate without a problem. We can create an AccessTokenCustom, extendind from Accesstoken like this:
`
{
  "name": "AccessTokenCustom",
  "base": "AccessToken",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "model": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
`
As you can see, there is the "model" attribute added, that's all. Then, when you already have this model customized, is possible to this relation in the user model, like this:
`
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "AccessTokenCustom",
      "foreignKey": "userId"
    }
  }
`

Finally, we replaced the "accessToken" by the custom. That means, that the REST url will be the same. I think that comment can complement the solution given above.

I hope it worth :)

**Comment by viniciusgomes** [comment]
I like the solution for using a customToken cause helpus to use more information..

But guys if do u need some fast solution what i did for simple test i create a different TTL for types of  logins, so that way i could use to check also set a diff times to keep logged ;)
