### ISSUE TITLE
updateById filling "ctx.data" object with "default" property values

### ISSUE THREAD

**Issue by GlennMurphy** [strongloop/loopback#1976]
If I have a model defined using the "default" property on some of it's properties, when I do an updateById with any data, loopback seems to insert all the properties that have a "default" into the "ctx.data".

This can be seen by logging "ctx.data" inside the "before save" hook.

So everytime I do an updateById with a any attribute to update, loopback resets all default properties to default on that model. 

I understand this may be fixed by just sending the whole object with the PUT. However according to the loopback documentation we should be able to update single properties using updateById.

https://docs.strongloop.com/display/public/LB/PersistedModel+REST+API#PersistedModelRESTAPI-Updatemodelinstanceattributes

**Comment by jannyHou** [comment]
hey @GlennMurphy I am trying to reproduce your issue but the default values are not reset. Can you explain more about the default properties? maybe I misunderstood you question. And I'd appreciate it if you can provide your code in [sandbox](https://github.com/strongloop/loopback-sandbox) (fork it and upload yours). Thanks.

---
Details:

https://github.com/jannyHou/loopback-sandbox/tree/UpdateById

model `test` has 3 properties:
- name1 (default: myDefault)
- name2
- name3

And I use endpoint `PUT/ tests` to test it:
1) Try it out with data:
```
{
  "name1": "newDefault",
  "id": 1
}
```
console.log(ctx.data):
```
{
  name1: newDefault,
  id: 1
}
```
response body:
```
{
  "name1": "newDefault",
  "name2": "secondname",
  "name3": "thirdname",
  "id": 1
}
```
2) Try it out with data:
```
{
  "name2": "newname2",
  "id": 1
}
```
console.log(ctx.data):
```
{
  "name2": "newname2",
  "id": 1
}
```
response body:
```
{
  "name1": "newDefault",
  "name2": "newname2",
  "name3": "thirdname",
  "id": 1
}
```
so `name1` is `newDefault`, not reset.

**Comment by jannyHou** [comment]
I am closing it since info provided is not enough to reproduce the issue.
If anyone run into similar issue or could provide more details, please feel free to reopen it:)
Thanks for understanding.

**Comment by zealseeker** [comment]
@jannyHou  I got the similar issue.  And made a pull request, please check whether its a bug.

**Comment by jannyHou** [comment]
@zealseeker Thank you I will take a look and label it bug if necessary.

**Comment by xvrcorp** [comment]
I got same issue when a property is defined with a default value, "ctx.data" comes with the properties (with default value),

somebody has a solution?

**Comment by zealseeker** [comment]
@xvrcorp Is it same to me that it happens when using a related model's prototype function like `auser.__update__test` mentioned here: https://github.com/jannyHou/loopback-sandbox/pull/1 
@jannyHou Please spare time to take a look :smile:

**Comment by jannyHou** [comment]
@zealseeker @xvrcorp Thanks for your update. And @zealseeker your sandbox is able to reproduce the bug. Really appreciate it!
