### ISSUE TITLE
Losing currentContext after installing Newrelic agent

### ISSUE THREAD

**Issue by olivierl** [strongloop/loopback#1984]
When I add Newrelic agent on top of the server.js, the currentContext "lose" the accessToken in my operation hook...

Check [this sandbox](https://github.com/olivierl/loopback-newrelic-issue)

`server/server.js`

``` javascript
require('newrelic');

var loopback = require('loopback');
var boot = require('loopback-boot');

var app = module.exports = loopback();

app.use(loopback.context());
app.use(loopback.token({
  model: app.models.accessToken,
  currentUserLiteral: 'me'
}));
```

`common/models/customer.js`

``` javascript
Customer.observe('access', function limitToOwner(ctx, next) {
  var accessToken = loopback.getCurrentContext().get('accessToken');
  console.log(accessToken); // display 'undefined' in the console
  ctx.query = _.merge({where: {ownerId: accessToken.userId}}, ctx.query);
  next();
});
```

`package.json`

``` json
"loopback": "^2.26.2",
"loopback-boot": "^2.16.0",
"loopback-connector-postgresql": "^2.4.0",
"loopback-datasource-juggler": "^2.44.0",
"newrelic": "^1.25.0",
```
- OS: Mac OS X El Capitain (10.11.3)
- Node.js: 4.2.6 (with NVM 0.29.0)

> REM: Everything is working fine on Node.js 0.12.x (tested on 0.12.7 and 0.12.9), so I only have the issue on Node.js 4.2.x (tested on 4.2.4 and 4.2.6)

**Comment by esopian** [comment]
+1

**Comment by jannyHou** [comment]
hey @olivierl do you get the error from postgresql only or from the default db as well?

**Comment by olivierl** [comment]
hi @jannyHou, I've made the test with the default db (memory) and it's worst,  `loopback.getCurrentContext()` returns `undefined`

**Comment by jannyHou** [comment]
Thanks @olivierl  I created a [sandbox](https://github.com/jannyHou/loopback-sandbox/tree/newrelic-losing-currentContext) to simplify your example and test it with default db:

When I hit the endpoint `GET/ customers` I got 
```
"error": {
    "name": "TypeError",
    "status": 500,
    "message": "Cannot read property 'get' of null",
    "stack": "TypeError: Cannot read property 'get' of null\n    at limitToOwner (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\common\\models\\customer.js:7:51)\n    at notifySingleObserver (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:98:22)\n    at iterate (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:181:13)\n    at Object.async.eachSeries (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\node_modules\\loopback-datasource-juggler\\node_modules\\async\\lib\\async.js:197:9)\n    at doNotify (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:95:11)\n    at doNotify (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:93:49)\n    at doNotify (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:93:49)\n    at doNotify (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:93:49)\n    at Function.ObserverMixin._notifyBaseObservers (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:116:5)\n    at Function.ObserverMixin.notifyObserversOf (C:\\Users\\IBM_ADMIN\\Desktop\\triage3\\loopback-newrelic-issue\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:91:8)"
  }
```

We will look into the problem!

**Comment by andressrg** [comment]
+1

**Comment by jannyHou** [comment]
Thank you @esopian @andressrg for reporting this, we will take a look. One more question for better debug: are you also getting this error with newrelic or even without using newrelic?

**Comment by barocsi** [comment]
could be same origin as https://github.com/strongloop/loopback/issues/1807

**Comment by jfurie** [comment]
+1

**Comment by Valko54** [comment]
+1

**Comment by a-c-m** [comment]
+1

**Comment by viczam** [comment]
-1

**Comment by odlevakp** [comment]
+1

**Comment by bajtos** [comment]
Hi, loopback-context is know to loose the context in many cases. We have deprecated it in favour of explicit context passing via the "options" argument, see https://github.com/strongloop/loopback/issues/1495.

There is also an alternative approach being explored in https://github.com/strongloop/loopback-context, feel free to give it a try. If you do, then please report any issues found in loopback-context's issue tracker.

I am closing this issue.
