### ISSUE TITLE
Issue of Amazon server configurations

### ISSUE THREAD

**Issue by ImanMh** [strongloop/loopback#1985]
When I want to read the documentation of `loopback`, I get the following error: 

![screen shot 1394-11-04 at 11 31 05](https://cloud.githubusercontent.com/assets/4482199/12535147/2bba0582-c28e-11e5-9438-da78619b3a52.png)

Why is there IP filters on documents of an open source project?

**Comment by pirisok** [comment]
+1

**Comment by richardpringle** [comment]
@crandmck, I know we've run into this before but I couldn't find the old issue. Did we ever resolve this?

**Comment by crandmck** [comment]
Docs are now on http://loopback.io/doc/ so we should not have this issue.

**Comment by ImanMh** [comment]
Very nice, congratulations and thanks a lot.
