### ISSUE TITLE
include HasManyThrough relation not working

### ISSUE THREAD

**Issue by AurelieV** [strongloop/loopback#1986]
Hi,

I define this relation,
```
MyUser.hasMany(Role, {foreignKey: 'principalId', through: RoleMapping});
```

When I use explorer, and try to fetch MyUser with roles includes, roles property is always an empty array. Checking RoleMapping, and everythink is ok, roles exists.

It seems that the query which fetches Through Model in data-source-juggler/includes.js always return empty in my case

Any clue?

```
"loopback": "^2.22.0",
"loopback-boot": "^2.6.5",
"loopback-component-explorer": "^2.1.0",
"loopback-connector-mongodb": "^1.13.3",
"loopback-datasource-juggler": "^2.39.0",
```

**Comment by AurelieV** [comment]
At first, I think it was due to [this issue](https://github.com/strongloop/loopback-connector-mongodb/issues/197) of mongodb connector, but rollbacking to previous version does not change the behavior

**Comment by jannyHou** [comment]
hey @AurelieV I am trying to reproduce your problem, for a better debug, can you fork this repository:
https://github.com/strongloop/loopback-sandbox/tree/master/server
and replace it by your code? Thanks!

**Comment by AurelieV** [comment]
hey @jannyHou 
Here is the [my fork](https://github.com/AurelieV/loopback-sandbox)
You have to configure a mongo database with standard port.
Go to the explorer, login as admin ({"username":"admin","password":"admin"}), set your access token.
Get RoleMapping, you see that admin has role admin.
Get MyUsers, including roles ({"includes":"roles"}), roles is always empty.
Go to MyUsers/findByRole with param role=admin, the user is here.

The problem only occurs with mongo database. With memory, everything works fine.

**Comment by jannyHou** [comment]
Thanks for your repo @AurelieV , I run it on my local but actually it works with mongodb(I also verified memory). I guess you should use
`{"include": "roles"}`
instead of `includes`

In additional, you can also customize the relation name using `as: 'your_relation_name'` in
'User.hasMany(Role, {foreignKey: 'principalId', through: RoleMapping, keyThrough: 'roleId'});'

**Comment by AurelieV** [comment]
Hey,
this is exactly what I am doing, and not having the same result.
Do you think it may be relative to the version of node (v4.2.4 for me) or mongo (2.6.3)?
I remember I have some warnings when installing connector can it be related?
`CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: Aucun fichier ou dossier de ce type
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:94: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
`

**Comment by AurelieV** [comment]
I resolve the compile warning by installing a missing directory (see [here](https://github.com/christkv/kerberos/issues/33)) but still have roles empty.
So may be mongo version?

**Comment by jannyHou** [comment]
Seems a duplidate issue with this one: https://github.com/strongloop/loopback/issues/1441
My settings:
OS: Windows 64bit
Mongodb: 3.2
strongloop: 5.0.1
loopback-datasource-juggler: 2.44.23
loopback-connector-mongodb: 1.13.46

**Comment by AurelieV** [comment]
System: Ubuntu 15.04 64bit.
strongloop v6.0.0

I try to update packages, but your versions are not available through npm.
The most recent versions available are what I use: 
loopback-datasource-juggler: 2.44.0
loopback-connector-mongodb: 1.13.3

Still not working, so probably the mongodb version. I will try to update it tommorow.

And yes it is a duplicate of the issue you pointed, but it was created 8 months ago, and no answer was found. Some other person may not be able to update mongo to 3.x, so maybe we have to continue investigation.

**Comment by jannyHou** [comment]
@AurelieV I tried your version 
loopback-datasource-juggler: 2.44.0
loopback-connector-mongodb: 1.13.3

Still works on my local.

Sure I will do more investigation. Shall we move the discussion to https://github.com/strongloop/loopback/issues/1441 so more people could see it? then we can gather more related information. Thanks.

**Comment by AurelieV** [comment]
Yes sure, I will move to the other issue.

**Comment by jannyHou** [comment]
Good. After clearing my mongodb database, I can reproduce the error now.
