### ISSUE TITLE
hasMany through with self relation returns the object itself

### ISSUE THREAD

**Issue by shSina** [strongloop/loopback#1993]
I created a user model(inherited from User) , the user may have many friends , I managed this by using hasMany through relation and friend model for keep the relations. but when I fetch user friends , it returns the user itself , the [forked repo] (https://github.com/shSina/loopback-sandbox) , I created the relations as below :
```js
//user relations  
"relations": {
    "friends": {
      "type": "hasMany",
      "model": "user",
      "foreignKey": "userId",
      "through": "friend",
      "keyThrough": "friendId"
    }
}
//friend relations 
"relations": {
    "firend": {
      "type": "belongsTo",
      "model": "user"
    },
    "user":{
      "type": "belongsTo",
      "model": "user"
    }
}
```
the users collection :
<img width="608" alt="users collection" src="https://cloud.githubusercontent.com/assets/478063/12574482/6188552e-c419-11e5-959b-1ed144940408.png">

the relation created in friend collection :
<img width="549" alt="friends collection" src="https://cloud.githubusercontent.com/assets/478063/12574506/88003abe-c419-11e5-80d9-32959ce2aeee.png">
the get friends result (as you can see it has returned the user itself , if I link for ex. 3 users , it returns 3 the same user itself objects):
<img width="970" alt="get friends after" src="https://cloud.githubusercontent.com/assets/478063/12574561/214ceeec-c41a-11e5-816d-add507b56324.png">

**Comment by loay** [comment]
Hi @shSina 
There is a typo in `friend.json`
```
  "relations": {
    "friend": {
```
Please fix the typo. Thanks.

**Comment by loay** [comment]
if that doesn't fix the issue, please feel free to leave a comment and I will re-open the case. Thanks.

**Comment by shSina** [comment]
Hi @loay , Just fixed.
thanks

**Comment by loay** [comment]
@shSina Did that fix the issue?

**Comment by shSina** [comment]
yes , I didn't mind a typo could be cause of it :)
