### ISSUE TITLE
Avoid the use of toString()

### ISSUE THREAD

**Issue by Nivl** [strongloop/loopback#1994]
This is more a discussion than a actual bug.

I realized that Loopback use toString to "hide" objects, which makes it very complicated to debug/understand what is happening. He are some examples:

`console.log(accessToken.uid)` gonna display `MyUserId`. One might think that `accessToken.uid` is a string when it actually is an object using toString() to return the actual value, which makes the following fail: `accessToken.uid === "MyUserId"`

An other issue is while performing a create and an update:

```
if (ctx.isNewInstance) {
    console.log(ctx.instance);
  } else {
    console.log(ctx.data);
  }
```

In both cases the console.log will display a simple object with my data. The issue is that `ctx.instance` is _not_ a simple object. `delete ctx.instance.foobar` will not work, instead we need to use `ctx.instance.unsetAttribute('foobar')`.

I think it would be better to stay away from the magic. I actually lost a lot of time trying to understand what was wrong with my code, until I realized there was probably a toString() somewhere. It is probably written somewhere in the documentation about it, but I think it's more efficient having people not to _have_ to read it for simple things, as a simple `console.log` would show us what to do.

**Comment by amenadiel** [comment]
On a mildly related issue, if you have a model field of type Object, persisting a récord will resort to `toJSON` method, which might yield unexpected results if you tried to persist for example a buffer. Which is an object, but not quite as one would expect.

If you take, for example, geoPoint, that's an example of an object whose stringification isn't just the escaped raw properties. 

Every object behavior should be customizable as well, or none should be. Either choice should be thoroughtly documentos.

**Comment by jannyHou** [comment]
@bajtos @raymondfeng @superkhau @ritch Any thought?

**Comment by bajtos** [comment]
@Nivl thank you for starting this discussion.

> `console.log(accessToken.uid)` gonna display `MyUserId`. One might think that `accessToken.uid` is a string when it actually is an object using toString() to return the actual value, which makes the following fail: `accessToken.uid === "MyUserId"`

I am little bit confused, because the built-in AccessToken model ([see source](https://github.com/strongloop/loopback/blob/2a86e9535b08fc85eb129c87c11c58510c4cfccd/common/models/access-token.json)) does not defined any `uid` property.

What database are you using? For example, if you are using MongoDB, Could it be that `uid` is an ID value, which is of `ObjectID` type? I am afraid that's a bit out of our control, as the `toString()` method is provided by the mongodb driver we use (by [bson.ObjectID](https://github.com/mongodb/js-bson/blob/66bbd418c711d8b5a7f3510933fe0840a3e12b53/lib/bson/objectid.js#L130-L132)) to be more precise).

**Comment by Nivl** [comment]
@bajtos It seems like you're right, `accessToken.uid` is from Mongo and it's an ObjectID.

**Comment by jannyHou** [comment]
The conversion between String and Object in mongodb could be similar issue of this one https://github.com/strongloop/loopback/issues/1441

**Comment by jannyHou** [comment]
@Nivl Since it's a mongodb's ObjectId, shall we close this issue now? I am glad to help if you still have other questions :)

**Comment by jannyHou** [comment]
I am closing the issue, please feel free to reopen it if you have further questions. Thanks.
