### ISSUE TITLE
Can we have a relation across Models living in multiple data sources / connectors?

### ISSUE THREAD

**Issue by gaurav21r** [strongloop/loopback#1995]
**Loopback relations are fantaastic!** I wanted to know if there could be a relation between 2 models living in different sources?

Eg: I have a `User` model say in a MySQL Database and a `Profile` in a schemaless MongoDB Database. So both have different data-connectors and obviously different data-sources.

Can I just do `User.hasOne(Profile, {as: 'profile'})`?

The docs at https://docs.strongloop.com/display/public/LB/Creating+model+relations don't really detail this point.

**Comment by richardpringle** [comment]
@gaurav21r, try it out! I'm sure you'll be happy with the result... (Yes)

Can I ask a huge favor though? Could you post any future questions at https://groups.google.com/forum/#!forum/loopbackjs.

There are a lot of open issues right now and we are trying to get everything fixed and bring that number down! We want to keep questions separate from actual issues.

Thanks for understanding!

**Comment by gaurav21r** [comment]
@richardpringle Sorry! Will do that from now on. Actually The way I was thinking of this was...
Incase this isn't implemented then this can be the issue for further discussions. If it has been, I strongly feel you should add it to the docs and this issue can track that. :exclamation:  

Do you think i can open a separate issue to add this to the docs? Or at least we should include at least one example of this to the test cases.

I am considering moving our giant project from **Waterline (from Sails.js)** as an ORM to Loopback and this was one of the major points to evaluate. I searched through test cases and docs but couldn't find anything related to this! Maybe this should be *advertised* more by **StrongLoop** ? I know it will help many architects evaluating loopback as a component.

Thanks for the answer. Loopback continues to delight me :smile:

**Comment by richardpringle** [comment]
>Do you think i can open a separate issue to add this to the docs? Or at least we should include at least one example of this to the test cases.

@crandmck, what do you think?

You would have to strategically document this as you wouldn't want someone really new to LoopBack trying to do this without any reason to... but as @gaurav21r says, could be good for people migrating over.

I'm not going to reopen the issue but if it makes sense, we could open a new doc issue.

**Comment by crandmck** [comment]
Yes, I think it's worth mentioning that:
- An app can have models backed by heterogeneous data sources; ie. you can have one model backed by Mongo, another by MySQL, and another by (say) REST.
- You can create relations between models with heterogeneous data sources; ie. models in the example above could have relations among them.

Does that summarize it?

**Comment by richardpringle** [comment]
Yeah, that makes perfect sense. I still find that this is a tricky subject though. What the LoopBack user really needs to be aware of is that all models inherit from the [*Model Class*](https://apidocs.strongloop.com/loopback/#model) and relations can be built between anything that inherits from the *Model Class* (for example: *Persisted Model*, etc), in other words, anything that goes in one of your "model" folders. The *type* of model or its *DataSource* are irrelevant.

I hope I described that clearly...

**Comment by crandmck** [comment]
Yes, thanks, that's a good clarification.  Docs do mention the model "inheritance" hierarchy, but not in the relations area, which I agree seems to be consistently the source of issues / confusion.

**Comment by crandmck** [comment]
OK I added an "Info" note at the end of https://docs.strongloop.com/display/LB/Creating+model+relations#Creatingmodelrelations-Overviewofmodelrelations section.

@richardpringle PTAL.

**Comment by gaurav21r** [comment]
@crandmck @richardpringle Thanks for adding this to the docs, a couple of points more!

1. Waterline has a the notion of [a `dominant` property](https://github.com/balderdashy/waterline-docs/blob/master/models/associations/dominance.md). Incase of a `hasAndBelongsToMany` relation, in which DataSource does the Relation live?

2. Don't you guys think the ability for related models to live across data sources and connectors warrants at least one test case? It is feature that can have many edge cases?

**Comment by richardpringle** [comment]
@gaurav21r, good question. @loay, you know the answer to this? If I am not mistaken, the relation is declared as a property of the model, so both models would contain their own data in their respective datasources. The relation itself actually lives in the ORM level and is built upon the relation data from both models.

I will confirm the above but I am pretty sure it is correct.

**Comment by gaurav21r** [comment]
@richardpringle @loay What about the test case? You guys feel it needs a few? Also can we keep the issue open until this is answered and probably added to docs? cc @crandmck

**Comment by richardpringle** [comment]
@gaurav21r, I assume that you are going to have a test case for your specific application... Would it be too much to ask that you try writing a test case and opening a PR for loopback itself? 

I'm not sure that it is necessary that it is tested so directly though. If the model is functioning properly, the datasource should not be relevant to the relation and thus you should not need to test it. Does that make sense?

@bajtos, what do you think?

**Comment by gaurav21r** [comment]
@richardpringle I don't know how the tests are structured here, but I'd surely like to contribute :) Would go over the other tests and post doubts (if any)!

**Comment by bajtos** [comment]
> Waterline has a the notion of a dominant property. Incase of a hasAndBelongsToMany relation, in which DataSource does the Relation live?

Ha, this is a good question. For `Employee hasAndBelongsToMany Meeting` relation, we need to create a new table (we call it "through model") that keeps a list of pairs `[Employee.id, Meeting.id]`. 

AFAICT, `Employee hasAndBelongsToMany Meeting` creates the "through" model in the datasource storing `Employee` model.

See [loopback-datasource-juggler/lib/relation-definition.js](https://github.com/strongloop/loopback-datasource-juggler/blob/2e0f496713e6593c459d51cd2866220c03f02fd0/lib/relation-definition.js) for more details.

@crandmck Could you please include this information in the docs too?

> Don't you guys think the ability for related models to live across data sources and connectors warrants at least one test case? It is feature that can have many edge cases? 

I agree we should have test cases for models persisted in different datasources that would cover all relation types. Ideally, there should be a single parameterised test suite that can be run two times - the first time using the same datasource for both models, the second time using two different datasources.

However, our current test suite (see [loopback-datasource-juggler/test/relations.test.js](https://github.com/strongloop/loopback-datasource-juggler/blob/2e0f496713e6593c459d51cd2866220c03f02fd0/test/relations.test.js)) may be too difficult to extend in such way, in which case I am ok to write a small set of new unit-tests targeted at the specifics of multi-datasource relations.

**Comment by crandmck** [comment]
>  `Employee hasAndBelongsToMany Meeting` creates the "through" model in the datasource storing `Employee` model.

@bajtos  To make sure I understand -- the [HasManyThrough](https://docs.strongloop.com/display/LB/HasManyThrough+relations) doc should state the above? 
To be clear, LoopBack creates this model is created at runtime (i.e. it doesn't show up in the JSON or .js files anywhere).

Can you give an example of this that I can use in the doc?

**Comment by gaurav21r** [comment]
@bajtos Thanks for your response. From what I can gather, `Employee hasAndBelongsToMany Meeting` without writing any `through` key will automatically create a `through` model ( a **JOIN** table in the SQL World). Question is where does it create it if no `through` is specified.

As described in the docs, The `Doctor hasAndBelongsToMany Patient through Appointment` has a specially mentioned `through` model called `Appointment` where we can give different attribute names and a custom name for the `through` model. In this case, you are absolutely right, wherever we mention `through`, that's the `DataSource` that gets picked up for the `through` model.

**Comment by nvartolomei** [comment]
Can this work with rest connector?
