### ISSUE TITLE
Create new instance

### ISSUE THREAD

**Issue by fmelk** [strongloop/loopback#1996]
i'm trying to add new model instance but i didn't find how to make it without erasing the old instances in my db 
i tried with create and upsert and always i face the same result:

module.exports = function(app) {
app.dataSources.HiringDb.automigrate('UserRh', function(err) {
    if (err) throw err;
  	  app.models.UserRh.create([
      {Email: 'aa@gmail.com', CompanyName: 'google' , Password:'2016',PhoneNumber:21441497},
      {Email: 'bb@gmail.com', CompanyName: 'google' , Password:'2016',PhoneNumber:21441498},
      ], function(err, UserRhs) {
      if (err) throw err;
      console.log(UserRhs);
    });
    app.models.UserRh.count(function(err, UserRhs) {
      if (err) throw err;
      console.log('Models number: \n', UserRhs);
    });
    app.models.UserRh.find(function(err, UserRhs) {
      if (err) throw err;
      console.log('Models : \n', UserRhs);
    });
  });
};

**Comment by gunjpan** [comment]
@fmelk : Hi, in the following line:
>`app.dataSources.HiringDb.automigrate('UserRh', function(err)`{...}

Auto-migration, i.e. `automigrate()`, will drop an existing table if its name matches a model name. When tables with data exist, use auto-update to avoid data loss. To avoid this, please use: `autoupdate()` as follows:
`app.dataSources.HiringDb.autoupdate('UserRh', function(err)`{...}

`autoupdate()` will preserve the existing tables in the d/b. Read more [here](https://docs.strongloop.com/display/public/LB/Creating+database+tables+for+built-in+models) and [here](https://docs.strongloop.com/display/public/LB/Creating+a+database+schema+from+models#Creatingadatabaseschemafrommodels-Auto-update).
Hope that resolves your issue.

For future reference, we would greatly appreciate if you could please direct your questions (you may find similar questions) to our Google group at:  https://groups.google.com/forum/#!forum/loopbackjs
See [Project Guidelines](https://github.com/strongloop/loopback/wiki).

Thank you!

**Comment by fmelk** [comment]
Thanks a lot ,it works.

**Comment by gunjpan** [comment]
@fmelk glad to hear that. Enjoy loopbacking :)

**Comment by fmelk** [comment]
Sorry for disturbing you , i want to send data from a form(client side) to
the create-sample-model.js with just ejs (no angular) , how can i get the
data from the ejs form to the create-sample-model.js to store it in the db.
is there an example ?!
