### ISSUE TITLE
Call server boot from Mocha + Chai

### ISSUE THREAD

**Issue by moimael** [strongloop/loopback#1997]
Hi,

I have the following test : 
```javascript
var chai = require('chai');
var chaiHttp = require('chai-http');
var app = require('../server/server.js').start;
var loginUser = require('./login.js');
var auth = {token: ''};

chai.use(chaiHttp);
chai.should();

describe('/users', function() {

  beforeEach(function(done) {
    loginUser(auth, done);
  });

  it('returns users as JSON', function(done) {
    chai.request(app)
    .get('/users')
    .set('Authorization', auth.token)
    .then(function (res) {
      res.should.have.status(200);
      res.should.be.json;
      res.body.should.be.instanceof(Array).and.have.length(1);
      res.body[0].should.have.property('username').equal('admin');
      done();
    })
    .catch(function (err) {
      return done(err);
    });
  });
});
```

Server is launched but request fail, probably because I call start directly and not the boot function. What would be the right way to call it ?

Thanks !

**Comment by Overdrivr** [comment]
As long as you have in server/server.js
```
var app = module.exports = loopback();
```
Then in your test file you just need to 
```
var app = require('../server/server');
```

**Comment by superkhau** [comment]
@moimael Did @Overdrivr's solution work for you? Can I close this?

**Comment by moimael** [comment]
@Overdrivr @superkhau No, if I do that server do not start and I always get an error : 
```javascript
TypeError: Cannot read property 'address' of undefined
```

**Comment by moimael** [comment]
Ok if I change this part:

```javascript
  if (require.main === module) {
    app.start();
  }
```

to this : 
```javascript
app.start();
```
in my server.js, server start, but I get the same error. Probably because of host + port not being found correctly.

**Comment by Overdrivr** [comment]
I don't believe this is related to the way you setup test. Your server should not be started prior to run the tests (see [https://github.com/chaijs/chai-http#application--server]). Also, it's better to not modify the server.js script so that tests run in real conditions 

It just seems you are trying to post to an non-existing route. To confirm, please run
`set DEBUG=strong-remoting:* && mocha .`

**Comment by moimael** [comment]
Ok you are completely right, I forgot the versioning part... My bad. 

Thanks for your help, now I have proper API testing :)

**Comment by superkhau** [comment]
@Overdrivr Thanks for helping out. ;) @moimael Now is this good to close?

**Comment by moimael** [comment]
@superkhau Yes go ahead :)
