### ISSUE TITLE
Update loopback-core API docs for promises

### ISSUE THREAD

**Issue by davidcheung** [strongloop/loopback#1998]
Parent: strongloop/loopback/issues/1409
Related: strongloop-internal/strong-docs/issues/63, strongloop-internal/scrum-loopback/issues/615

`common/models/user.js`
Instance Methods
- [x] [User.prototype.hasPassword](https://apidocs.strongloop.com/loopback/#user-prototype-haspassword)
- [x] [User.prototype.verify](https://apidocs.strongloop.com/loopback/#user-prototype-verify) Need update callback fn
- [x] [User.prototype.createAccessToken](https://apidocs.strongloop.com/loopback/#user-prototype-createaccesstoken)

Static Methods
- [x] [User.login](https://apidocs.strongloop.com/loopback/#user-login)
- [x] [User.logout](https://apidocs.strongloop.com/loopback/#user-logout) no param except err
- [x] [User.confirm](https://apidocs.strongloop.com/loopback/#user-confirm) no param except err
- [x] [User.resetPassword](https://apidocs.strongloop.com/loopback/#user-resetpassword) no param except err

`common/models/application.js`
- [x] [Application.register](https://apidocs.strongloop.com/loopback/#application-register) Need update callback fn, `this.create(props, cb);`
- [x] [Application.resetKeys](https://apidocs.strongloop.com/loopback/#application-resetkeys) no param except err, `this.save(cb);`
- [x] [Application.authenticate](https://apidocs.strongloop.com/loopback/#application-authenticate)

`lib/persisted-model.js`
- [x] [PersistedModel.replicate](https://apidocs.strongloop.com/loopback/#persistedmodel-replicate) how to read Array with datatype like `Change []` from callback?

**Comment by jannyHou** [comment]
I am closing it since https://github.com/strongloop/loopback/pull/2040 merged.
