### ISSUE TITLE
How to make application auto start after OS reboot

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback#2003]
Run on ubuntu. 

    sudo npm install -g strongloop
    sudo npm install -g strong-pm
    sudo sl-pm-install
    sudo /sbin/initctl restart strong-pm

Start App with slc from App Root Dir. But slc does not auto start app after os reboot.
    
    sudo slc start

Using Arc
  
    export HOST=0.0.0.0
    PORT=8080 slc arc
    
Then start app from browser by start App Controller. Again this does not auto start app after os reboot.    

Typo at this link:
https://docs.strongloop.com/display/SLC/Deploying+apps+to+Process+Manager

Port number should be 3002

And the second application is available at:
http://prod.foo.com:3002

**Comment by mike-aungsan** [comment]
After OS reboot, try to start the app with slc, but none of the following command work.

    sudo slc start
    sudo slc start app_name

Then I remove the service and shutdown the service.

    sudo slc ctl remove app_name
    sudo slc ctl shutdown

Still does not work. Then restart strong-pm
    sudo /sbin/initctl restart strong-pm

Then sudo slc start still does not work.

Also try to reload config sudo /sbin/initctl reload-configuration

Still does not work. If I stop strong-pm and start again. Then run sudo slc start it work sometimes.

**Comment by sam-github** [comment]
Try using `slc deploy` instead of `slc start`.

**Comment by 0candy** [comment]
@mike-aungsan Did that resolve your issue?

**Comment by mike-aungsan** [comment]
@sam-github 
@0candy 

Branch `deploy` is not available in this repository
Failed to deploy `deploy` as `project_report` to `http://127.0.0.1:8701/` via `http://127.0.0.1:8701/`

**Comment by mike-aungsan** [comment]
I got another error. I setup two machine. Follow the same note. First one work. 2nd machine fail.

sudo npm install -g strongloop
sudo npm install -g strong-pm
sudo /sbin/initctl start strong-pm
sudo /sbin/initctl restart strong-pm
sudo slc start


Local deploy failed: `/home/user/project` does not exist
assert.js:340
assert.ifError = function(err) { if (err) throw err; };
                                          ^

Error: HTTP error 400
    at Error (native)
    at /usr/lib/node_modules/strongloop/node_modules/strong-deploy/lib/post-json.js:67:16
    at ConcatStream.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/strong-deploy/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/usr/lib/node_modules/strongloop/node_modules/readable-stream/lib/_stream_writable.js:511:14)
    at afterWrite (/usr/lib/node_modules/strongloop/node_modules/readable-stream/lib/_stream_writable.js:390:3)
    at nextTickCallbackWithManyArgs (node.js:463:18)
    at process._tickDomainCallback (node.js:402:17)
    at process.<anonymous> (/usr/lib/node_modules/strongloop/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)

**Comment by sam-github** [comment]
`sudo slc start`... try without sudo

**Comment by loay** [comment]
Hi @mike-aungsan .. did the above comment fix the issue? ^^

**Comment by loay** [comment]
Hi @mike-aungsan please leave a comment if you still require further assistance and I will reopen the issue. Thanks.
