### ISSUE TITLE
context.get('currentUser'); is not accessible from User.observe hook

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#2004]
I was trying to implement an access filter for my User method depending on the currently logged in user.
However, when I try to access, it is undefined:

``` javascript
User.observe('access', function inspectRoles(ctx, next) {
    var loopback = require('loopback');
    var context = loopback.getCurrentContext();
    var user = context.get('currentUser');
}
```

It works with other presistedModels operation hooks.

**Comment by jannyHou** [comment]
Hi @barocsi  thanks for your contribution! And any question or suggestion are welcomed! 
I am trying to reproduce the issue with access hook, are you adding it to your custom user model or the build-in User model in loopback?

Could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace it with your code to prove the problem? Thanks!

**Comment by barocsi** [comment]
This is a custom user model. I will check against the sandbox repo.

**Comment by KaanErkol** [comment]
any solutions ?

**Comment by bajtos** [comment]
Possibly related: https://github.com/strongloop/loopback/issues/2397

**Comment by jannyHou** [comment]
i am able to reproduce it with the snippet above:
```
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
user: undefined
```

**Comment by bajtos** [comment]
Issue moved to [strongloop/loopback-context #23](https://github.com/strongloop/loopback-context/issues/23) via [**ZenHub**](https://www.zenhub.com/)
