### ISSUE TITLE
MongoDB shell command execution

### ISSUE THREAD

**Issue by sureshkoduri** [strongloop/loopback#2007]
Hi,

how do I  execute mongodb shell command like getCollectionNames(), using strongloop?

**Comment by jannyHou** [comment]
hey @sureshkoduri , for `getCollectionNames()`, do you mean discover models from mongodb or discover models from loopback app?

1) discover from mongodb:
we have APIs for model discovering in relational databases but not mongodb, please check doc to see details:
https://docs.strongloop.com/display/public/LB/Discovering+models+from+relational+databases

2) get models from loopback app:
this depends on the path of your code, this doc page explains how to getting references to models:
https://docs.strongloop.com/display/public/LB/Working+with+LoopBack+objects#WorkingwithLoopBackobjects-Gettingreferencestomodels

**Comment by sureshkoduri** [comment]
Hey jannyHou, Thanks for your reply. 

I used `MongoClient`, code like this in strongloop and got all the collections in mongodb.

```
MongoClient.connect(url, function(err, db) {
      assert.equal(null, err);
      getAllCollections(db, function(result) {
          var dataJSON = JSON.parse(JSON.stringifyOnce(result));
          console.log(dataJSON);
          var data = [];
          for(var res in dataJSON){
            data.push(dataJSON[res].s.name);
          }
          db.close();
          cb(null, data);

      });
    });
```
