### ISSUE TITLE
Use API Explorer - Documentation and example code issues

### ISSUE THREAD

**Issue by TrySpace** [strongloop/loopback#2009]
Following this first example: https://docs.strongloop.com/display/public/LB/Create+a+simple+API

```
loopback deprecated Routes "/methods" and "/models" are considered dangerous and should not be used.
Disable them by setting "legacyExplorer=false" in "server/config.json" or via "app.set()". node_modules\express\lib\rout
er\layer.js:95:5
```

Secondly the example code: 

```
{
  "name": "My Coffee Shop",
  "id": 0
}

```
Does not match with the sentence: `Add some text for the name property.  You don't have to put anything for the id property, because LoopBack will automatically manage it to ensure there is always a unique ID for each model instance.`

I will continue to report the mistakes on every Documentation page, unless I should do this elsewhere, but I can't find any other place for it. Because the footer on `docs.strongloop.com` has a link to `Report a Bug` but this is a link to the Atlassian Confluence bug reports..

**Comment by crandmck** [comment]
This deprecation notice does appear and the app has been that way for a while.  I don't recall why we left it there.
@superkhau We should probably fix it by setting `legacyExplorer=false` in `server/config.json`.  

@TrySpace The code you are referring to is added automatically by API Explorer.  It adds the `id` property even though it's not required and is overwritten by an automatically-generated ID when the model instance is added.   I'll clarify that in the docs.

@TrySpace Please do continue to report doc issues here.  Please mention me @crandmck as I am primarily responsible for the docs.

**Comment by crandmck** [comment]
@gunjpan Are you responsible for loopback-getting-started?  If so, could you address the issue noted above?

**Comment by juodumas** [comment]
Also re. `legacyExplorer`, https://docs.strongloop.com/display/public/LB/config.json#config.json-Top-levelproperties says that `legacyExplorer` defaults to `false`. So leaving it undefined in `config.json` should prevent the deprecation warning reported by @TrySpace, shouldn't it?

**Comment by crandmck** [comment]
@superkhau I tried it and I don't see the above warning when `legacyExplorer` is set to false, but I _do_ see it when it is removed from `server/config.json`, so it appears that the default might not in fact be false.  When I just log it from `server.js` or a boot script and it's not defined, it shows up as 'undefined`.

Can you confirm, and I'll change the docs accordingly.

**Comment by superkhau** [comment]
https://github.com/strongloop/loopback/blob/master/server/middleware/rest.js#L34

Probably a bug in the logic here. We probably need to check for undefined values and print the msg accordingly. @juoduma @TrySpace Would one of you like to submit a patch?

**Comment by juodumas** [comment]
While at first this looks like a bug in the logic, actually such handling of `undefined` is intentional: [#1134](https://github.com/strongloop/loopback/issues/1134#issuecomment-77447454). So either the code block in [server/middleware/rest.js#L34](https://github.com/strongloop/loopback/blob/master/server/middleware/rest.js#L34) should to be removed, because it was added in `v2.14.0` for backwards compatibility, or the https://docs.strongloop.com/display/public/LB/config.json#config.json-Top-levelproperties table should state that the default is `true`.

**Comment by crandmck** [comment]
@bajtos ^

**Comment by bajtos** [comment]
The default value is `true` for backwards compatibility.

Let's remove `legacyExplorer` in the upcoming 3.0 release. @davidcheung could you please create a GH issue to track this task?

**Comment by bajtos** [comment]
@crandmck could you please fix the docs  and state the correct default value?

**Comment by superkhau** [comment]
Reassigning to rand for the doc issue. @crandmck Please close this after you update the docs.

@TrySpace Please track the progress of removing the legacyExplorer option at https://github.com/strongloop/loopback/issues/2037

**Comment by crandmck** [comment]
Updated [the doc](https://docs.strongloop.com/display/LB/config.json#config.json-Top-levelproperties) to state that default value is **true**.
