### ISSUE TITLE
Connect your API to a data source - Documentation issue

### ISSUE THREAD

**Issue by TrySpace** [strongloop/loopback#2010]
It says `git checkout step1` but that should be `step2` ( https://docs.strongloop.com/display/LB/Connect+your+API+to+a+data+source )

I can't find the documentation in this repo, is it somewhere else? I'd rather make pull-requests for these minor mistakes.

**Comment by gunjpan** [comment]
@TrySpace: `step1` refers to the earlier commit in the tutorial flow: i.e. step1: `Create a Simple API` as nothing was committed in the step: [`Use API Explorer`](https://docs.strongloop.com/display/LB/Use+API+Explorer).

Also, `git checkout step1` will setup the project for you to continue with making changes in the step: **Connect your API to a datasource**. 
Thus, no change is required in the docs.

For:
>I can't find the documentation in this repo, is it somewhere else? I'd rather make pull-requests for these minor mistakes.

 LoopBack documentation is hosted on Confluence wiki, and for now, reporting doc issues via GitHub is the way to go. See more on [Contributing to LoopBack documentation](https://docs.strongloop.com/display/public/LB/Contributing+to+LoopBack+documentation).

Hope that answers your concern. Closing this issue.If you need any further assistance with it, please reopen it and I will be happy to assist. Thank you :)
