### ISSUE TITLE
Extend your API - Documentation issue

### ISSUE THREAD

**Issue by TrySpace** [strongloop/loopback#2011]
It says `git checkout step2` but this should be `step3` ( https://docs.strongloop.com/display/LB/Extend+your+API )

**Comment by gunjpan** [comment]
@TrySpace : Same issue as: https://github.com/strongloop/loopback/issues/2010 ,

Please note that: `step2`, `step3` and so on are referring to **releases** on the repo: https://github.com/strongloop/loopback-getting-started

Closing it as no alteration is required. Thank you!
