### ISSUE TITLE
Couchdb connector views are created too late

### ISSUE THREAD

**Issue by moimael** [strongloop/loopback#2014]
When using couchdb connector when testing or creating a user with boot script, it fails because couchdb view is not yet created.

I tried digging in the connector code but can't understand how to wait for view creation. I tried adding a callback but it seems that loopback doesn't wait for it to be complete. (look at the helpers.updateDesign(this._nanoAdmin, '_design/loopback', design); ) in couchdb.js

see https://github.com/mattange/loopback-connector-couch/issues/11

Any pointers ?

**Comment by Amir-61** [comment]
Hi @moimael,

Please don't create duplicate issues; You asked your question here: https://github.com/mattange/loopback-connector-couch/issues/11 which is the right place; so I'm closing this ticket in favor of the other one.

Thanks for understanding!
