### ISSUE TITLE
model default scope. include relation, issue with "belongsTo"

### ISSUE THREAD

**Issue by giowe** [strongloop/loopback#2015]
Hi, this is my example model

```
"name": "Book",
  "plural": "Books",
  "base": "PersistedModel",
  "options": {
    "validateUpsert": true,
    "mysql": {
      "table": "Books"
    }
  },
  "scope": {
    "include": [
      "langs",
      "basePublication"
    ]
  },
  "properties": {
    "id": {
      "type": "number",
      "id": true
    },
    "alias": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "langs": {
      "type": "hasMany",
      "model": "BookLang",
      "foreignKey": "langOwnerId"
    },
    "basePublication": {
      "type":"belongsTo",
      "model": "BasePublication",
      "foreignKey": "id"
    }
  }
```

I want my "get" REST endpoint to return all the information related to basePublication (publishing date for example). With my "lang" relations all goes well but nothing shows up with the basePublication relation... what am I missing?

**Comment by jannyHou** [comment]
hey @giowe I am trying to reproduce your issue, can you fork this sandbox and replace it with your code? Then I can debug what's wrong with your code, thanks!
https://github.com/strongloop/loopback-sandbox/tree/master/server

**Comment by giowe** [comment]
[https://github.com/giowe/loopback-sandbox](url)
this is my project with a readonly db user. 
if you check in the article.json or in the acrivity.json model i have this default scope
```
"scope": {
    "include": [
      "publication",
      "langs",
      "category"
    ]
  }
```

but if test the "/articles" endpoint i got only the publication and the langs data, no category field at all.

**Comment by jannyHou** [comment]
@giowe you create a `belongsTo` relation from `Activity` to `ActivityCategory` but without a `hasMany` relation from `ActivityCategory` to `Activity`, the relation should be established in double directions.

I have a [repo](https://github.com/jannyHou/loopback-sandbox) with a simple hasMany relation:
when you run the app and try
GET Games/
{"include": "category"}
you will see it works.

I tried to add the `hasMany` relation for you and I just got:
>ER_BAD_FIELD_ERROR: Unknown column 'activityCategoryId' in 'field list'
I don't know where is your other settings but your app looks too complex lol

**Comment by giowe** [comment]
ooh ok ! i fixed it :+1: tnx very much
