### ISSUE TITLE
Docs: "Customizing REST error handling" section should use server/config.local.js

### ISSUE THREAD

**Issue by juodumas** [strongloop/loopback#2019]
This `config.json`, `config.local.js` stuff is confusing. Even the one who wrote the docs confused 
`server/config.local.js` with `sever/config.js`:

https://docs.strongloop.com/display/public/LB/Environment-specific+configuration#Environment-specificconfiguration-CustomizingRESTerrorhandling

**Comment by 0candy** [comment]
@crandmck ^

**Comment by crandmck** [comment]
@juodumas I agree, it is very confusing.  In fact, I think it's way to complicated and a poor design in general, but I just document it.  

Fixed, thanks!
