### ISSUE TITLE
Unable to 'npm install' from master branch

### ISSUE THREAD

**Issue by AurelieV** [strongloop/loopback#2021]
I try to do a npm install for writing a PR from the master branch of loopback, but npm install is impossible

```
npm ERR! node v4.2.4
npm ERR! npm  v3.6.0
npm ERR! No compatible version found: strong-remoting@^3.0.0-alpha.1
npm ERR! Valid install targets:
npm ERR! 2.25.0, 2.24.0, 2.23.2, 2.23.1, 2.22.2, 2.22.1, 2.22.0, 2.21.0, 2.20.3, 2.20.2, 2.20.1, 2.20.0, 2.19.0, 2.18.1, 2.18.0, 2.17.0, 2.16.3, 2.16.2, 2.16.1, 2.16.0, 2.15.0, 2.14.1, 2.14.0, 2.13.2, 2.13.1, 2.13.0, 2.12.1, 2.12.0, 2.11.1, 2.11.0, 2.10.1, 2.10.0, 2.9.0, 2.8.2, 2.8.1, 2.8.0, 2.7.1, 2.7.0, 2.6.0, 2.5.0, 2.4.0, 2.3.0, 2.2.2, 2.2.1, 2.1.1, 2.1.0, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 2.0.0-beta5, 2.0.0-beta4, 2.0.0-beta3, 2.0.0-beta2, 1.6.0, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.7, 1.2.6, 1.2.5, 1.2.4, 1.2.3, 1.2.2, 1.2.1, 1.1.8, 1.1.7, 1.1.6, 1.1.5, 1.1.4, 1.1.3, 1.1.2, 1.1.0, 1.0.0
```

Also happen for 
```
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
```

Any idea?

**Comment by jannyHou** [comment]
Hi @AurelieV loopback is doing its transiiton from 2.x to 3.x hence has something to set regarding the versions. 
As a workaround please install it from npm org:
`npm config set registry https://registry.npmjs.org/`

And I am a little busy these days so haven't got a chance to take a further investigation into your issue of mongodb, sorry for that, I will see if I can find more guys to reproduce your issue.

**Comment by AurelieV** [comment]
@jannyHou thanks for taking time to answer.

For npm install problem: setting the registry does not change the problem. Do you know when version will be set correctly or maybe the branch I can take for a clean install?

For mongo problem: keep me inform, I will continue using a workaround until we found a solution.

**Comment by jannyHou** [comment]
^@rmg could you take a look? Thanks!

**Comment by rmg** [comment]
The problem is that version of strong-remoting has not been published to the published to the public npmjs.com registry yet, likely due to some red tape around releasing things. I'll see what I can find out.

**Comment by bajtos** [comment]
@AurelieV sorry for the troubles. I have published `strong-remoting@3.0.0-alpha.1` few moments ago. Please let us know if you run into any more issues.

**Comment by AurelieV** [comment]
@bajtos hey, thank you npm install runs fine now.
But npm test fails now. Do I open an other issue?

**Comment by jannyHou** [comment]
thank you @AurelieV  but we already created a PR to fix the test failures:
https://github.com/strongloop/loopback/pull/1946

We are digging into it :)

**Comment by AurelieV** [comment]
Hey, I have the same problems as the one you mentionned on this PR. I will wait for the merge so.
Thanks for your work
