### ISSUE TITLE
can user that has not email register?  I tried allowing blank of email but failed.

### ISSUE THREAD

**Issue by zealseeker** [strongloop/loopback#2022]
In loopback's User model, a user has to push his email to register. or else the server will response "`email` is null" error. 
But now since registering via phone number is prevalent, so I want to create a inherited model from user that need not input email.
What I did is:
I created an model (my-user) which is inherited from loopback'User. I don't want to use email. so I set both User and my-user model as
```
"email":{
  "type":"string",
  "required":false
}
```
but when I created a user(in both models), error still threw that:
```
"name": "ValidationError",
    "status": 422,
    "message": "The `myUser` instance is not valid. Details: `email` is null (value: undefined).",
```
Even I commented the two lines in user.js: 
```
//UserModel.validatesFormatOf('email', {with: re, message: 'Must provide a valid email'});
//UserModel.validatesUniquenessOf('email', {message: 'Email already exists'});
```
I still could not register an account with the same error.

So I wonder how to modify the original User model in which the email is not necessary?

This is the trace of stack. I could not yet find who validate the email...
```
"stack": "ValidationError: The `myUser` instance is not valid. Details: `email` is null (value: undefined).
    at /home/vcap/app/node_modules/loopback-datasource-juggler/lib/dao.js:265:12
    at ModelConstructor.<anonymous> (/home/vcap/app/node_modules/loopback-datasource-juggler/lib/validations.js:487:13)
    at ModelConstructor.next (/home/vcap/app/node_modules/loopback-datasource-juggler/lib/hooks.js:75:12)
    at done (/home/vcap/app/node_modules/loopback-datasource-juggler/lib/validations.js:484:25)
	at /home/vcap/app/node_modules/loopback-datasource-juggler/lib/validations.js:558:7
    at ModelConstructor.<anonymous> (/home/vcap/app/node_modules/loopback-datasource-juggler/lib/validations.js:357:5)
    at /home/vcap/app/node_modules/loopback-datasource-juggler/lib/dao.js:1456:9
    at Object.async.each (/home/vcap/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:153:20)
    at allCb (/home/vcap/app/node_modules/loopback-datasource-juggler/lib/dao.js:1394:13)
    at /home/vcap/app/node_modules/loopback-connector-mongodb/lib/mongodb.js:753:9"
```

**Comment by 0candy** [comment]
Unfortunately, the email and password field are required properties for the user model.

The validation is done here:
https://github.com/strongloop/loopback/blob/27c9e263e0a1b003f8c0a7969119ea66f18c2bb4/common/models/user.js#L707

**Comment by zealseeker** [comment]
@0candy I mentioned that I have commented the line 707(see the third code pool I posted) but it still rejected me . I cannot even find the code which outputs the error : 😂
```
"message": "The `myUser` instance is not valid. Details: `email` is null (value: undefined)."
```

**Comment by 0candy** [comment]
The code that outputs the error is here:
https://github.com/strongloop/loopback-datasource-juggler/blob/934786200b0180ed3d3cf45f78986b2019511e79/lib/validations.js#L751

**Comment by zealseeker** [comment]
@0candy Sorry, I made a mistake that I didn't deployed the version in which the line 707 is commented. Now it works.  Thank you :smile:

**Comment by 0candy** [comment]
@zealseeker Glad it works for you now. I am closing this issue.
