### ISSUE TITLE
Unclear instructions on building to a git repository

### ISSUE THREAD

**Issue by seanmangar** [strongloop/loopback#2024]
https://docs.strongloop.com/display/SLC/Committing+a+build+to+Git

- The language on this page is unclear and a bit confusing. 
- This command is not properly explained in the context: slc build --onto deploy --install --commit
- "git checkout production" It isn't explained why a production branch is needed

**Comment by superkhau** [comment]
Please post SLC related issues at https://github.com/strongloop/strongloop/issues.

**Comment by superkhau** [comment]
@crandmck This is a doc issue though. PTAL.

**Comment by crandmck** [comment]
> The language on this page is unclear and a bit confusing.

Sorry about that.  I adapted this doc from a blog post by one of the developers.  It was actually quite a bit more unclear and confusing before I edited it!  I'm happy to clarify if you can be more specific (as you were below).
 
> This command is not properly explained in the context: slc build --onto deploy --install --commit

I added some explanation (below the command).  

>   "git checkout production" It isn't explained why a production branch is needed

I also tried to clarify/explain this in the text preceding the command block.

**Comment by crandmck** [comment]
@seanmangar PTAL and see if my changes address your comments.  Thanks!

**Comment by seanmangar** [comment]
@crandmck Thanks! I use a different git workflow with develop as the main development branch and master as the production stable branch. That helped clarify things.

**Comment by crandmck** [comment]
Glad it helped.  I'll go ahead and close this issue.  Thanks for the input...
