### ISSUE TITLE
Model schema and model not showing for login

### ISSUE THREAD

**Issue by seanmangar** [strongloop/loopback#2025]
Noticed that the json schema to be sent for login does not show up on the API explorer - I'm currently using a model that extends User called APIConsumer. 

Any idea how to display this? It would help to display meaningful API documentation.

<img width="1013" alt="screen shot 2016-02-03 at 16 04 59" src="https://cloud.githubusercontent.com/assets/6080053/12781822/41081afa-ca90-11e5-9e20-f9949834291c.png">

**Comment by 0candy** [comment]
Thank you for point it out.  It should display like in the doc here:

https://docs.strongloop.com/display/public/LB/Introduction+to+User+model+authentication#IntroductiontoUsermodelauthentication-Loginasthenewuser
