### ISSUE TITLE
hetting User is referencing a dataSource that does not exist: "db" while testing connection for DataSource

### ISSUE THREAD

**Issue by AnupDeshpande23** [strongloop/loopback#2026]
Hi all,

I'm new to StrongLoop & trying to create an application, for same I'm creating Datasource & after entering all details I'm getting following Exception

Oops! Something is wrong
User is referencing a dataSource that does not exist: "db"
Name: AssertionError
Message: User is referencing a dataSource that does not exist: "db"
Request: /workspace/api/DataSourceDefinitions/server.DS1/testConnection
status: 500

[Scrn Shot.docx](https://github.com/strongloop/loopback/files/115745/Scrn.Shot.docx)

Thanks in advance

**Comment by 0candy** [comment]
Did you install the connector?
npm install --save loopback-connector-mysql

https://docs.strongloop.com/display/APIS/Creating+and+editing+data+sources

**Comment by archenroot** [comment]
Same here with postgreSQL connector.. I fill the name of connection and all working data, the file \server\datasources.json is filled with follwing data(which are correct):
{
  "hb_automation_framework": {
    "host": "192.168.99.100",
    "port": 5432,
    "database": "postgres",
    "password": "zangetsu",
    "name": "hb_automation_framework",
    "user": "zangetsu",
    "connector": "postgresql"
  }
}

I will search for string "db" if it is refered somewhere in project...

**Comment by archenroot** [comment]
Ok, I found the root cause, maybe, there is file: /server/model-config.json, the project has been created by scl command probably and here is the content:
`{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "User": {
    "dataSource": "db"
  },
  "AccessToken": {
    "dataSource": "db",
    "public": false
  },
  "ACL": {
    "dataSource": "db",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "db",
    "public": false
  },
  "Role": {
    "dataSource": "db",
    "public": false
  }
}
`

I changed all dataSource entries to reflect my datasource name a then testing datasource in ARC finished with success.

**Comment by jjhesk** [comment]
hi @archenroot @0candy same in here.  here is my setup

├── loopback@3.8.0
├── loopback-boot@3.0.0
├── loopback-component-explorer@4.2.0
├── loopback-component-push@3.0.0
├── loopback-component-storage@3.2.0
├── loopback-connector-mongodb@3.1.0
├── loopback-connector-mysql@3.0.0
├── loopback-connector-postgresql@3.0.1
├── loopback-connector-redis@0.1.0
├── loopback-connector-rest@2.1.0
├── loopback-context@3.1.0
├── loopback-datasource-juggler@3.6.1



I also got the error from loading datasources
I have set NODE_ENV=production

I have setup mode-config.production.json with the correct configurations but it still failed. 
The datasource file is [here](https://github.com/ONode/salisgallia/blob/preproduction/server/datasources.production.js)

Unhandled rejection AssertionError: AccessToken is referencing a dataSource that does not exist: "rocket_us_east"
