### ISSUE TITLE
When updating the user password, the password is stored in not hashed

### ISSUE THREAD

**Issue by LoicMahieu** [strongloop/loopback#2029]
##### Step to reproduce:
- Create a sample app `slc loopback`
- Expose `User` model with `public: true`
- Create a new user: `POST /Users` `{ "password": "foo", "email": "foo@bar.com" }`
- Try to authenticate with password `foo`
- It success
- Update the user with new password: `PUT /Users/1` `{ "password": "bar" }`
- Try to authenticate with password `bar`
- **It fails**

##### Diagnostic:

It seems that the setter results (see [UserModel.setter.password](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L591-L602)) is not used as "data" for the connector, see: [DataAccessObject.prototype.updateAttributes](https://github.com/strongloop/loopback-datasource-juggler/blob/486c1de1ba4572f810606be1aa148db4d272e52c/lib/dao.js#L2499-L2505) . So I think that setter results is never saved in db.

It is really critic because it causes the User model not usable.

###### Versions:
```
├─┬ loopback@2.26.2
│ ├── loopback-connector-remote@1.0.3
│ ├── loopback-phase@1.3.0
│ └── strong-remoting@2.25.0
├── loopback-boot@2.16.0
├── loopback-component-explorer@2.3.0
├── loopback-connector-mysql@2.2.0
└── loopback-datasource-juggler@2.45.0
```

**Comment by 0candy** [comment]
I am not sure if you are using explorer. But if you are, after you authenticate the first time, you need to set the access token at the top of the explorer page before you can update the password.
https://docs.strongloop.com/display/public/LB/Introduction+to+User+model+authentication

Same with if you do it in the code, you need to have the authorization token for the user to submit the request.
https://docs.strongloop.com/display/public/LB/Logging+in+users

**Comment by ianbelcher** [comment]
I'm seeing this same issue as well. The POST method hashes the password field and saves the entry correctly. The PUT method calls the UserModel.setter.password method on the User which hashes the password but the database entry is stored in plain text. This obviously breaks the users ability to log into the system.

Loopback version 2.26.2

**Comment by LoicMahieu** [comment]
@0candy Sorry if it wasn't clear. I describe a "login" procedure to illustrate the problem. I am aware about token mechanism of loopback.

To simplify:
- Update the user with new password: PUT /Users/1 { "password": "bar" }
- Look at the DB, the password is stored in clear.

**Comment by JonathanSilva** [comment]
+1

**Comment by 0candy** [comment]
@LoicMahieu  Thank you for pointing out the issue. We will take a look.

**Comment by AlmaasAre** [comment]
+1

**Comment by glesage** [comment]
Something in this commit: https://github.com/strongloop/loopback-datasource-juggler/commit/8ca67c3d48952b972bc2e2c1ee4c8c93b389f99c

**Comment by jnowland** [comment]
+1 It's locking out users.

**Comment by shuckepco** [comment]
+1

Worked around this issue by calling hashPassword prior to updateAttributes in the remote method.

**Comment by juanscolari** [comment]
+1

**Comment by notbrain** [comment]
+1 this is Really Bad. How did this pass tests?

**Comment by AlmaasAre** [comment]
2.44.0 should work as well.

**Comment by ebarault** [comment]
god, we just hist this issue, anyone trying to reset his password is locked out...

**Comment by bajtos** [comment]
This is an unintended regression, please accept our apologies. I have published `loopback-datasource-juggler@2.45.1` that should fix the problem.

> +1 this is Really Bad. How did this pass tests?

As it turns out, there is no test for this specific use case. I'd say this whole situation is a good educational example for all of us (both maintainers and community contributors), why it's important to maintain high test coverage.

I'd like to keep this issue open until we add unit-tests that would have failed on 2.45.0, @Amir-61 offered to write them.

**Comment by LoicMahieu** [comment]
@bajtos Thanks for having fixed the issue.
I suppose the commit solving the issue is: https://github.com/strongloop/loopback-datasource-juggler/commit/dbdf9153346ed3aabc925eddf6280e19df519cd3

Yes, it demonstrate well that coverage is essential. Furthermore when it's related to core feature of loopback.

**Comment by vicky-gonsalves** [comment]
+1

**Comment by Amir-61** [comment]
Connect to https://github.com/strongloop/loopback-datasource-juggler/pull/893
