### ISSUE TITLE
embedsMany helper methods not defined/accessible

### ISSUE THREAD

**Issue by TrySpace** [strongloop/loopback#2031]
Whatever I try, I cannot get the helper methods working like described here: https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations#Embeddedmodelsandrelations-EmbedsMany

node.js:

```
  Node.remoteMethod (
      'pushMovements',
      {
        isStatic: false,
        http: {path: '/pushMovements', verb: 'post'},
        accepts: [
          { arg: 'data', type: 'array', http: { source: 'body' } }
        ],
        returns: {arg: 'put', type: 'string'},
        description: 'pushMovements'
      }
  );

  Node.prototype.pushMovements = function(revision, cb) {
    console.log('id:',this.id)
    console.log('rev:',revision)
     revision.forEach(function (result) {     
       Node.movements.add(result)    
      });
     cb(null, revision)
   };
```

node.json:

```
{
  "name": "Node",
  "plural": "Nodes",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "address": {
      "type": "string"
    },
    "status": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "movements": {
      "type": "embedsMany",
      "model": "Movement",
      "foreignKey": "nodeId",
      "keyThrough": "movementId",
      "through": "Movement",
      "property": "movementData",
      "options": {
          "validate": true,
          "autoId": true
      }
    }
  },
  "acls": [],
  "methods": {}
}
```

movment.json:

```
{
  "name": "Movement",
  "plural": "Movements",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "nodeId": {
      "type": "String"
      },
    "ts": {
      "type": "Date"
    },
    "battery": {
      "type": "String"
    },
    "movement": {
      "type": "String"
    }
  },
  "validations": [],
  "relations": {
    "node": {
      "type": "belongsTo",
      "model": "Node",
      "foreignKey": "nodeId"
    }
  },
  "acls": [],
  "methods": {}
}
```

Whenever I post: `[ {"id" : "xyz" }, {"id" : "zyx" } ]` to `/Nodes/{id}/pushMovements` it outputs:

```
id: 56b351934a286a0820b50c1e
rev: [ { id: 'xyz' }, { id: 'zyx' } ]
[TypeError: Cannot read property 'add' of undefined]
```

I've tried all kinds of combinations of `foreignKeys` and with or without `through` etc, it just won't work... I've been at this for several days now :'(

I've also cloned:  https://github.com/strongloop/loopback-example-relations and indeed `.create` works (https://github.com/strongloop/loopback-example-relations/blob/master/server/boot/z-customer-emails.js) , but only in the bootscript but not in the method I'm using. 

(I posted A similar question on stackoverflow: https://stackoverflow.com/questions/35081213/strongloop-embedsmany-helper-methods-not-found i've put a bounty on it for 100 rep points ;p...)

**Comment by loay** [comment]
Hi @TrySpace 
Do you have a link for your own repo? It is better if I test the error there. Thanks

**Comment by cookinclude** [comment]
Hi, I've the same problem. I'm making unit tests and I want to populate some fake data but I've this problem when I'm adding objects in a relation "referencesMany".

I'm not sure if I'm missing something in the initialisation of my tests :

```
var loopback = require('loopback');
var app = require('../server/server');
var ds = loopback.createDataSource('memory');
var Filter = ds.createModel('Filter', app.models.Filter);
var Package = ds.createModel('Package', app.models.Package);
```

So a Package have this relation : 
```
"relations": {
    "filters": {
      "type": "referencesMany",
      "model": "Filter",
      "property": "filtersIds",
      "options": {
        "forceId": false,
        "validate": true
      }
    }
  }
```

Thanks for your help

**Comment by loay** [comment]
@cookinclude 
I would be more than happy to help. Would it be possible to refer me to a link to your repo? 
Here is how to report a bug : please use this one as a reference? Thanks. 
https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by loay** [comment]
Hi, I am closing this issue for now. If you are still experiencing the same problem, please feel free to leave a comment and I will re-open the issue. Thanks.

**Comment by hackerunet** [comment]
Sorry but I have to request to reopen this issue, I have the same problem, and for me if the answer is not posted the issue cannot be closed. Please post some hints about this issue, how to solve it or how to woraround it.
I have exactly the same problem, I have declared an embedsmany relation and no matter what I do I get this:
```
Error: Invalid reference: undefined
    at EmbedsMany.add (/var/www/FOLDER/node_modules/loopback-datasource-juggler/lib/relation-definition.js:2935:11)
    at ModelConstructor.method [as __link__sentinelPlans] (/var/www/sentineltrack/node_modules/loopback-datasource-juggler/lib/relation-definition.js:732:33)
```

**Comment by frankorama** [comment]
I'm having the same problem with the .remove() and the .destroyById().  According to the documentation these helper-methods should be available for embedded relations but I'm getting error messages.

I've forked the loopback-example-relations repository to illustrate the problems:

To run the example, start the loopback application.

Navigate to 
```
http://0.0.0.0:3000/email
```

Each email address will have a remove link which calls a remoteMethod I created the code is commented and located in the /common/models/customer.js file

**Comment by frankorama** [comment]
@TrySpace I know this is old, but I just had another look at your code.  You are attempting to add a new child instance (result) to the parent model (Node).  You need to add the children to a parent **_instance_**

Change your code as follows:
```
  Node.prototype.pushMovements = function(revision, cb) {
    console.log('id:',this.id)
    console.log('rev:',revision)
    Node.findById(parentId, function(parentFindErr, parentNode){
       revision.forEach(function (result) {     
         parentNode.movements.add(result)    
        });
       cb(null, revision)
    });
   };
```
