### ISSUE TITLE
export-api-def: /PersistedModels/count output doesn't look correct?

### ISSUE THREAD

**Issue by hideya** [strongloop/loopback#2043]
Although https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L677-L683 says:
```js
    setRemoting(PersistedModel, 'count', {
      description: 'Count instances of the model matched by where from the data source.',
      accessType: 'READ',
      accepts: {arg: 'where', type: 'object', description: 'Criteria to match model instances'},
      returns: {arg: 'count', type: 'number'},
      http: {verb: 'get', path: '/count'}
    });
```
`slc loopback:export-api-def` output for the `count` method of PersistedModels becomes like the following:
```yaml
  /Users/count:
    get:
      tags:
        - User
      summary: Count instances of the model matched by where from the data source.
      description: !<tag:yaml.org,2002:js/undefined> ''
      operationId: User.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
```
This output causes following two issues when to use with [swagger codegen](https://github.com/swagger-api/swagger-codegen):

 1. Type for parameter `where` becomes `string`, with which I don't see a way to specify a filter like `/api/users?filter[where][property]=[value]` as the string parameter is processed to generate a URL in this way: `/api/users?filter=escaped-param-string`.

 2. Response type becomes `object` instead of `number`, which prevents [swagger codegen](https://github.com/swagger-api/swagger-codegen) to generate a client-side method to receive the counted number as the response.

Are these conversions working as expected?

**Comment by bajtos** [comment]
1) There are two ways how to encode "filter" parameter. The format you described is intended for users building the URL manually. The other option is to encode the entire "filter" value in JSON, e.g. `/api/users?filter={"where":{"property":"value"}}` (the filter value must be url-encoded of course).

2) This is a known limitation of our current swagger-spec generator, see https://github.com/strongloop/loopback-swagger/blob/6d13c8c75978e88ed31c0921765f0b6959f36fdb/lib/specgen/route-helper.js#L104-L111 I have created a new issue to improve this - see https://github.com/strongloop/loopback-swagger/issues/27

**Comment by bajtos** [comment]
@hideya please check with the maintainers of the swagger swift code generator how to handle operations that return arbitrary object (not described by any swagger definition). I believe this is valid swagger and thus the code generator should be fixed to support this use case.

I am closing this issue, we will track the work on changing the description of `Count` response in a different issue (strongloop/loopback-swagger#27).

**Comment by hideya** [comment]
@bajtos sounds good!  I'll check about the arbitrary object handling with the maintainers and keep you updated.

**Comment by hideya** [comment]
@bajtos I've filed an Issue against Swift codegen: https://github.com/swagger-api/swagger-codegen/issues/2093 to discuss how to deal with such a case where the server API returns a plain JS object.
