### ISSUE TITLE
[doc] Incorrect example for building and running the loopback-example-storage repo

### ISSUE THREAD

**Issue by noderat** [strongloop/loopback#2045]
[This shell example](https://docs.strongloop.com/display/public/LB/Storage+component#Storagecomponent-Example) in Confluence of how to build the [loopback-example-storage](https://github.com/strongloop/loopback-example-storage) is outdated and could be confusing to new users.

The repo now has either [example](https://github.com/strongloop/loopback-example-storage/tree/master/example) or [example-2.0](https://github.com/strongloop/loopback-example-storage/tree/master/example-2.0) that the user would need to `cd` into before they can run `npm install`

Perhaps an explanation that `2.0` is referencing the version of Loopback and that the other directory is for legacy Loopback in both the repository's README.md as well as in the Confluence document?

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Oops, my bad.  I did realize that but somehow forgot to put it in the docs.  I updated the doc and the README.

@noderat Thanks for bringing it to my attention!
