### ISSUE TITLE
Idea: always encode `id` as a string

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2046]
While discussing iOS/Swift client generated from Swagger spec with @hideya in https://github.com/strongloop/loopback/issues/2042, we discovered a problem in the current design of `id` property.

At the moment, the `id` property is usually added by the backing datasource and the type depends on the backing database. In-memory and SQL databases use numeric ids, MongoDB uses ObjectId serialized as a string.

While this makes it easy to quickly switch between different datasources (e.g. use in-memory for fast prototyping, then switch to MongoDB), it creates a lot of work for clients using a statically-typed language (e.g. ObjC). All variable & argument declarations has to be changed from type `int` to type `string (`char*`) when the server switches from integer to string ids.

I am proposing to modify loopback and juggler to always encode id properties and arguments as strings, regardless of the real type of the encoded value.

``` js
// memory, SQL
{ "id": "123" }
// MongoDB
{ "id": "507f191e810c19729de860ea" }
```

I believe this should also greatly simplify the solution for ObjectID handling: (see https://github.com/strongloop/loopback/issues/1217 and https://github.com/strongloop/loopback/issues/1874):
- foreign keys can always use string type, e.g. when a MySQL-stored model references a MongoDB model
- strong-remoting metadata can explicitly mark all `id` arguments as strings and thus prevent coercion issues when strong-remoting cannot decide whether `123` should be treated as a number or as a string.

@raymondfeng @ritch @superkhau @fabien @clarkorz @STRML thoughts?

**Comment by bajtos** [comment]
See also https://github.com/strongloop/loopback/issues/126

**Comment by STRML** [comment]
This would be good for guid IDs as well; however I don't think that changing ID formats (say, from autoincrement to guid or objectid) could possibly be a non-breaking change and is a relatively uncommon use case. However, forcing all existing clients with numeric IDs to change to strings absolutely is a breaking change. If done it will need to be at a major bump and opt-out.

**Comment by bajtos** [comment]
> However, forcing all existing clients with numeric IDs to change to strings absolutely is a breaking change. If done it will need to be at a major bump and opt-out.

I totally agree 👍 The issue is already labelled as `breaking-change`.
