### ISSUE TITLE
remote methods of related items don't get triggered

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback#2047]
This:

```
  MyModel.beforeRemote('**', (ctx, data, next) => {
    log.debug('MyModel.beforeRemote method: ', ctx.method.name)
    next()
  })
```

gives me the method name `__create__relatedModel`, which I want to see triggered by:

```
MyModel.beforeRemote('__create__relatedModel', ... )
```

But that does not work, and there is no documentation to be found on how to set remote hooks on such calls. Please help by providing examples and documentation. This is essential.

**Comment by richardpringle** [comment]
Hi @Morriz, you should be able to trigger the remote hook with:
```relatedModel.beforeRemote('create', ...)```
is there any reason why you are trying to attach the hook to the parent model?

**Comment by Morriz** [comment]
Yea, that I know now. I hade to put a '*.'  in front of it.

**Comment by Morriz** [comment]
But the docs are unclear on the matter, why not write it up good some time? Docs are getrjng better but lots is not updated or missing. It's those things that make ppl go to another solution after a while...shame.

**Comment by richardpringle** [comment]
@Morriz, I actual have found the remoteHook docs to be pretty clear but my opinion is quite biased. Can you point out some particular parts/sentences that are unclear so we can take a look and possibly reword them?

We don't want anyone switching products because of docs! We rely on community members like you to point out specific issues so we can make the docs better. So thanks in advance.

**Comment by Morriz** [comment]
Ha, tnx for the quick attention. But I mean mostly like I mentioned: hooking into related model operations is not described. All I found was somebody saying "I just log ctx.method.name in a '**' hook to see it's name". And that was found somewhere else. Not in your docs.

**Comment by richardpringle** [comment]
Okay, makes sense
@crandmck, I'm labelling this as a doc issue. I've seen a few of those pop up lately. Let me know if you want some help!

Thanks @Morriz, happy coding!

**Comment by itinance** [comment]
You need to add "prototype.":

`MyModel.beforeRemote('prototype.__create__relatedModel', ... )`

THis is valid, working code in our project:

```
MyModel.afterRemote('prototype.__create__relatedModel', function(ctx, message, next) {
}

```

**Comment by crandmck** [comment]
Let's keep this open... should be straightforward to fix.
