### ISSUE TITLE
Firing rapid calls to a many-to-many relation endpoint creates multiple DB entries

### ISSUE THREAD

**Issue by holisticode** [strongloop/loopback#2048]
I posted a question about this in the google groups:
https://groups.google.com/forum/#!topic/loopbackjs/REYjCpsePb0

But there has been no response. 
I must assume at this point it's a bug but maybe I am doing something wrong?

We have a classic followers relationship in our app.
To actually save such a relationship, the API we currently use is:

`PUT /api/user/:id/following/rel/:fk`

The relationship is defined as follows:

```
    "following": {
      "type": "hasMany",
      "model": "User",
      "foreignKey": "followSrcId",
      "through": "UserFollowers",
      "keyThrough": "followDestId"
    },  
```

If I do this via the explorer manually, there is no problem, the relationship gets added just once even if I call it several times.

But if we issue this call rapidly with the exact same parameters, the same relationship is saved multiple times.

I have a script for testing which creates users, then makes them follow each other randomly:

```
    for (var k=0; k<(FOLLOWING_FACTOR*TEST_USER_COUNT); k++) {
      var follow_src = createdUsers[Math.floor(Math.random()*createdUsers.length)];
      var follow_dest = createdUsers[Math.floor(Math.random()*createdUsers.length)];

      //make sure following oneself is not possible :)
      while (follow_src.id == follow_dest.id) {
        follow_dest = createdUsers[Math.floor(Math.random()*createdUsers.length)];
      }   

      logger.debug("ID " + follow_src.id + " follows ID " + follow_dest.id);
      api.put('/api/Users/' + follow_src.id + '/following/rel/' + follow_dest.id)
      //....
    }
```

This produces the following rows in the DB (postgres):

```
select * from userfollowers where followsrcid=1297;
 followsrcid | followdestid 
-------------+--------------
        1297 |         1298
        1297 |         1298
        1297 |         1298
        1297 |         1298
```

This would make the `following_count` utterly wrong (and useless). My hope is that there's something wrong with my script :)

I was thinking of writing a "before save" hook to the through model (UserFollowers), and first checking if the relationship exists, but that would
- deteriorate performance if it could be done automatically
- would have to return an error by not calling next() in the "before save" hook, 
  otherwise it would be saved anyway.

If this would be confirmed as a bug, the workaround we would like to most probably investigate would be to prevent something like that at the DB level, but we are not sure how right now.

**Comment by jannyHou** [comment]
hey @fablife I am trying to reproduce your issue, for a better debug, could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace the code with yours? thanks.

**Comment by fablife** [comment]
https://github.com/fablife/loopback-sandbox.git

I have the tests as test/follow.js

just run 

mocha test/follow.js

it runs on a postgres (check datasources.json)

**Important note: I have not been able to switch off ACLs for the sandbox user, so in order to run it I simply went into node_modules/loopback/common/models/user.json and removed all ACLs.**

**Comment by jannyHou** [comment]
same issue as https://github.com/strongloop/loopback/issues/2246
