### ISSUE TITLE
Can't install strongloop, npm install strongloop hangs

### ISSUE THREAD

**Issue by lucasjahn** [strongloop/loopback#2052]
Hey there,

I have a problem with the installation of Strongloop on my DigitalOcean Droplet (using Ubuntu 14.04.3 x64). I tried out different commands like you listed in the documentation

```sh
sudo npm -g --unsafe-perm install strongloop

npm -g install strongloop
```

with booth commands it gets stuck completely at this line every time

```sh
make: Entering directory '/usr/lib/node_modules/strongloop/node_modules/strong-agent/build'
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
root@lucas-main:~#   SOLINK_MODULE(target) Release/obj.target/strong-agent.node
  COPY Release/strong-agent.node
make: Leaving directory `/usr/lib/node_modules/strongloop/node_modules/strong-agent/build'
```

With the normal command 
```sh
sudo npm install -g strongloop
```
I get a lot of EACCESS failures, like this

```sh
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/4.2.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/strongloop/node_modules/heapdump/.node-gyp"
```

I contacted DigitalOcean but they said it has to be a bug on the strongloop side. :-(

Are you aware of this issue already? Or is there maybe another trick I can do? I also can't see any errors with debug mode.

Thanks guys.

**Comment by gaurav21r** [comment]
Looks like a Linux Permission issue. @lucasjahn did you try installing it on your local environment?

**Comment by lucasjahn** [comment]
exactly gaurav21r. this was what I thought too. Locally it is working like a charm (OSX). Okay mabye I try contacting them again.

**Comment by JohnnyDamtoft** [comment]
I have the very same problem. Using my OS X with Node540, sudo npm install -g strongloop is working. But then trying to install on DigitalOcean, Ubuntu14.04.3 or Ubuntu14.04.3-NodeImage, using 4.2.4 and 5.5.0 both fails the installation.

It simply hangs using node4.2.4, and is just stops with 5.5.0. Node was installed using DigitalOcean and Package Manager within Ubuntu.

I've tried to download the binary nodejs package from nodejs.org, giving the same results. I also tried with compiling the source code, giving the same result.

I also tried --unsafe-perm option, still making the npm command crash.

Below is the output from one of my Ubuntu installations. :)

`# npm install -g --unsafe-perm strongloop

> heapdump@0.3.7 install /usr/local/lib/node_modules/strongloop/node_modules/heapdump
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/heapdump/build'
  CXX(target) Release/obj.target/addon/src/heapdump.o
  SOLINK_MODULE(target) Release/obj.target/addon.node
  COPY Release/addon.node
make: Leaving directory `/usr/local/lib/node_modules/strongloop/node_modules/heapdump/build'
|
> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/strongloop/node_modules/spawn-sync
> node postinstall


> bufferutil@1.2.1 install /usr/local/lib/node_modules/strongloop/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory `/usr/local/lib/node_modules/strongloop/node_modules/bufferutil/build'
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/strongloop/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory `/usr/local/lib/node_modules/strongloop/node_modules/utf-8-validate/build'

> modern-syslog@1.1.2 install /usr/local/lib/node_modules/strongloop/node_modules/modern-syslog
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/modern-syslog/build'
  CXX(target) Release/obj.target/core/core.o
  SOLINK_MODULE(target) Release/obj.target/core.node
  COPY Release/core.node
make: Leaving directory `/usr/local/lib/node_modules/strongloop/node_modules/modern-syslog/build'

> strong-agent@2.0.2 install /usr/local/lib/node_modules/strongloop/node_modules/strong-agent
> node-gyp rebuild || exit 0

make: Entering directory `/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/build'
  CXX(target) Release/obj.target/strong-agent/src/strong-agent.o
Killed
root@n1:~#   SOLINK_MODULE(target) Release/obj.target/strong-agent.node
  COPY Release/strong-agent.node
make: Leaving directory `/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/build'`

**Comment by JohnnyDamtoft** [comment]
SOLUTION:

Doing a little more troubleshooting, I found that "permission denied" is references to memory.
- I was using a 512MB Ram Droplet, taking up all of the memory.

I resized the server, and during the global strongloop installation the servers uses about 2,4GB Ram.
- sudo npm install -g strongloop

Memory was the issue, and everything is now working as intended. :)

`browser bundle successfully generated
/usr/local/bin/slc -> /usr/local/lib/node_modules/strongloop/bin/slc.js`

**Comment by gaurav21r** [comment]
Also try activating swap file on 512MB servers. Will give the system **virtual memory **

**Comment by lucasjahn** [comment]
@JohnnyDamtoft and @gaurav21r  you are the best!

I just created a SWAP FIle over 4GB [(How To Add Swap on Ubuntu 14.04)](https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04).

Then I started the installation again with this command:

```
sudo npm -g --unsafe-perm install strongloop
```

and it is now completely installed!

Thanks a lot guys!
