### ISSUE TITLE
Config files deleted if there is a problem accessing package.json

### ISSUE THREAD

**Issue by hq-mobile** [strongloop/loopback#2053]
Steps to reproduce:

- Create a model structure (a single model with a single attribute will do)
- run the following command to cause an access problem to package.json:
sudo chown -v root package.json
- Attempt to do any model operation such as slc loopback:property
- Follow the prompts to create a new property
- Once all the prompts are completed an error will be output:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/Users/Dan/projects/Bark-Wing-Duck/test/package.json'
    at Error (native)
```

Expected:
 -config files to be left unchanged

Actual:
All -config files and -model.json files have had their contents deleted.

**Comment by jannyHou** [comment]
hey @hq-mobile I followed your steps on linux machine but the generator works fine.

I run `sudo chown -v root package.json` , not sure if prefix `--` affects something(actually I cannot run with a prefix like `--`).

**Comment by hq-mobile** [comment]
Ah sorry -- was a typo, I am running on a Mac running El Capitan. Did root own your package.json beforehand or was it your normal user?

I can try this on Ubuntu 10.04 tomorrow morning and let you know my findings. If there is anything you need me to try from my side please just let me know!

**Comment by hq-mobile** [comment]
I'm sure you are aware but this seems to be the same as issue #2054.

**Comment by jannyHou** [comment]
Thanks @hq-mobile let's update new findings and fix in https://github.com/strongloop/loopback/issues/2054
