### ISSUE TITLE
Strongloop model.json and config.js missing data after failed connector install

### ISSUE THREAD

**Issue by Joesimonsen** [strongloop/loopback#2054]
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1351](https://strongloop.zendesk.com/agent/tickets/1351)
**Priority:** N/A
**Group:** SL Support
**Assignee:** Samuel Thompson
**Support Type:** prospect
**Case Type:** problem
**Component:** strongloop_suite
**Severity:** 
**CritSit Update:** 
**GitHub ID:** 
**IBM CIN Number:** 

**Original ticket description:**

<blockquote><div class="zd-comment">
<p>I'm using a mongo db connector and have about 8 collections </p>

<p>I attempted to install the rest connector to an existing project. 
<br>It failed and several of the config JSON files were empty.  </p>

<p>Does arc create a backup files somewhere before updating connectors?</p>

<p>I could find any steps to recreate the models for my mongo db collections. </p>

<p>Any pointers would be awesome.</p>

<p>Dan Zeitman</p>
</div></blockquote>

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Samuel Thompson on 2016-02-08 at 19:25:*

<blockquote><div class="zd-comment">
<p>Hi Dan,</p>
<p>I am currently looking to see if there is a solution in Arc, but in the mean time, are you tracking these files in git? If so, you could run the following commands to grab them from the git history:</p>
<pre><code>$ git checkout "HEAD~1" model.json
$ git checkout "HEAD~1" config.json
</code></pre>
<p>Thanks,</p>
<p>Sam</p>
</div></blockquote>

**Comment by Joesimonsen** [comment]
*Comment made from Zendesk by Dan on 2016-02-08 at 19:41:*

<blockquote><div class="zd-comment">
<p>Dear Support</p>

<p>I had not start tracking yet. :( </p>

<p>I ended up rebuilding it all. I've had this problem several times in the past, where basically if you try to update an existing project connectors, and there's fail -- in my case a write permission issue on package.json -- it appears to mung up the various config and datasources files. </p>

<p>It would be great if Strongloop would have some sort - fall-back routine that would log out the errors, and then revert to the prior version if a process failed. </p>

<p>Dan Zeitman</p>
</div></blockquote>

**Comment by 0candy** [comment]
Thank you for pointing out the issue. I can reproduce this problem. Will let you know once we have a fix for it.

**Comment by akigupta131** [comment]
Any updates on this? I am finding trouble with same!
