### ISSUE TITLE
BelongsTo and Include Filter

### ISSUE THREAD

**Issue by mariohmol** [strongloop/loopback#2056]
Can't make include filter for BelongsTo Relation:

* Api Call via REST:

/api/Veiculos?filter[include]=Marca

* API Call via Angular

`Veiculos.find({filter :  include: ['Marca']}		})`

The error is:

`{"error":{"name":"Error","status":500,"message":"Relation \"Marca\" is not defined for Veiculos model","stack":"Error: Relation \"Marca\" is not defined for Veiculos model`

* My veiculos.json 

```
{
  "name": "Veiculos",
"properties": {
  "marca": {
      "type": "Number",
      "required": false,
      "length": null,
      "precision": 10,
      "scale": 0,
      "mysql": {
        "columnName": "marca",
        "dataType": "int",
        "dataLength": null,
        "dataPrecision": 10,
        "dataScale": 0,
        "nullable": "Y"
      },
      "_selectable": false
      },

"relations": {
       
       "Marca": {
         "type": "belongsTo",
         "model": "marca_veiculos",
         "foreignKey": "marca"
       }
  },
}
```

I tested include with all variations:

* Marca (field name)
* marca (model name)
* marca_veiculos (table name)

**Comment by jannyHou** [comment]
hey @mariohmol  I am trying to reproduce your problem, for a better debug, could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace it with your code? Thanks!

**Comment by mariohmol** [comment]
this was so easy to reproduce https://github.com/mariohmol/loopback-sandbox , i dont know why is working at your side 

strongloop v6.0.0 (node v4.2.2)
├── strong-arc@1.8.5 (d01942e)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by mariohmol** [comment]
I forgot that i opened this issue in the past https://github.com/strongloop/loopback-datasource-juggler/issues/783 , .. may this be related with https://github.com/strongloop/loopback-datasource-juggler/pull/329

**Comment by mariohmol** [comment]
Found the error, the problem is that attribute model must be the Model name and not the table name. This is very confusing in Docs. Anyway, this issue may help who gets the same problem. Thanks @jannyHou

**Comment by jannyHou** [comment]
@mariohmol glad to know that you fixed it! yeah and thank you we welcome any suggestions!
