### ISSUE TITLE
Custom express route under restAPI root

### ISSUE THREAD

**Issue by Reuvenc** [strongloop/loopback#2057]
Hi, I'm trying to add a custom express route under my restAPI root, but when trying to reach this address it not found.

For instance, if the restAPI root is `/api`, so the following custom route is unreachable:

```js
app.get('/api/sayHello', 
  function (req, res, next) {
    res.send('hello!');
  }
);
```

The error I'm getting is :

> "error":{"name":"Error","status":404,"message":"There is no method to handle GET /sayHello","statusCode":404,"stack":"Error: There is no method to handle GET /sayHello\n    at restUrlNotFound (/workspace/project_folder/node_modules/strong-remoting/lib/rest-adapter.js:337:17)\n    at Layer.handle [as handle_request] (/workspace/project_folder/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/workspace/project_folder/node_modules/express/lib/router/index.js:312:13)\n    at /workspace/project_folder/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/workspace/project_folder/node_modules/express/lib/router/index.js:330:12)\n    at next (/workspace/project_folder/node_modules/express/lib/router/index.js:271:10)\n    at jsonParser (/workspace/project_folder/node_modules/body-parser/lib/types/json.js:100 :40)\n    at Layer.handle [as handle_request] (/workspace/project_folder/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/workspace/project_folder/node_modules/express/lib/router/index.js:312:13)\n    at /workspace/project_folder/node_modules/express/lib/router/index.js:280:7"}}

Am I doing something wrong?
Is there any other approach to add such custom route?

Thanks in advance, 
Reuven

**Comment by Amir-61** [comment]
Hey @Reuvenc,

Did you see [this documentation](https://docs.strongloop.com/display/public/LB/Add+a+custom+Express+route)? Please follow the steps in the documentation. Also for this kind of questions we encourage that you ask your questions in our [Google community](https://groups.google.com/forum/#!forum/loopbackjs) to get a quicker response.

Thanks a lot!

**Comment by ssbrewster** [comment]
@Amir-61 that documentation only enables adding routes under `domain:port/customRoute` not adding a route to the rest namespace

related: https://github.com/strongloop/loopback/issues/631

**Comment by Reuvenc** [comment]
@Amir-61  I'm aware of your attached doc. 
My issue was solved by changing `app.get(..)` to `app.use(..)`.

Thanks,
Reuven

**Comment by shov** [comment]
.get works fine if it's above `app.use('/api', loopback.rest());`
