### ISSUE TITLE
Documentation -> PersistedModel.findOrCreate(where, data, callback)

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback#2059]
@crandmck 

https://apidocs.strongloop.com/loopback/#persistedmodel-findorcreate

According to doc, it return model instance object.  But it return array with model instance and a boolean
[ {...}, true ]

I am running this version.

├─┬ loopback@2.25.0
│ ├─┬ loopback-connector-remote@1.0.3
│ ├── loopback-phase@1.2.0
├─┬ loopback-boot@2.14.0
├─┬ loopback-component-explorer@2.1.1
│ ├─┬ loopback-swagger@2.2.3
├─┬ loopback-component-passport@1.6.0
├─┬ loopback-component-storage@1.6.1
├─┬ loopback-connector-mongodb@1.13.3
│ ├── loopback-connector@2.3.0
├─┬ loopback-datasource-juggler@2.44.0
│ ├── loopback-connector@2.3.0

**Comment by Amir-61** [comment]
Hey @mike-aungsan,

Thanks for bringing this to our attention and helping us improve the documentation; could you please let us know which connector you are using? The callback returns `err`, `data` and `info`; the latter is boolean value which shows whether a new instance is created or not. But in terms of `data` it should return an object. I just tried with memory connector as well and it confirm this; it should be consistent with all connectors; please let us know which connector you are using?

Thanks again!

**Comment by mike-aungsan** [comment]
It is in the npm list
loopback-connector-mongodb@1.13.3

**Comment by yshing** [comment]
@Amir-61 It looks like when 'findOrCreate' was used as promise, it resolves with an array `[data, isNewInstance]` which is not in the documentation...

**Comment by akkonrad** [comment]
In the case when I want to run tests against the API with memory DB connector it fails everywhere, where findOrCreate is called because of the above error. 
Any chance to fix it or it won't be updated anymore?
