### ISSUE TITLE
Documentation -> loopback-connector-rest

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback#2065]
@crandmck 
@superkhau 

Really need a few more example for loopback-connector-rest.

This page does not know anything about how to make a post request, how to use requestBuilder, restConnector, or RestResource.

There is a link to API, https://apidocs.strongloop.com/loopback-connector-rest/ 

In the example repo,
https://github.com/strongloop/loopback-example-connector/tree/rest

https://github.com/strongloop/loopback-example-connector/blob/rest/example/rest-builder-app.js
var restConnector = require('../lib/rest-builder');

But I cannot really find where is the lib folder and what is the doc for rest-builder.

I have spent a few mins and get this far...

```
var restConnector = require("loopback-connector-rest")
var req = restConnector.get('http://www.google.com')

req.invoke({}, function (err, res, response) { 
    console.log(err);
    console.log(res);
    console.log(response); 
} )
```

Thanks

**Comment by superkhau** [comment]
The example needs updating. It's at https://github.com/strongloop/loopback-connector-rest/blob/master/lib/rest-builder.js. Basically that line should be `require('loopback-connector-rest/lib/rest-builder')`. Would you like to submit a PR?

**Comment by gunjpan** [comment]
@superkhau: Could you revisit this.

**Comment by superkhau** [comment]
@gunjpan Please submit a PR with the fix as described above for the example -- `require('loopback-connector-rest/lib/rest-builder')`. The issue is the example is using a relative path via `..`.
