### ISSUE TITLE
loopback.Router.route not working as in `express`.

### ISSUE THREAD

**Issue by Freyert** [strongloop/loopback#2066]
One of my favorite express patterns is to do this (I'm doing this in a boot script. Is that bad?):

```javascript
...
var route = app.loopback.Router();

route.route('/books/:deweyDecimalNumber')
   .get(getABook)
   .put(putABook)

app.use(route);
```

However, `put` doesn't get added as a route. `get` does.

I've tried this with `post` as well and post doesn't get added either. I even attempted to use the bare `express.Router()` version. In both cases I get the `URL Not Found Error`.

Versions:
```json
{ 
"dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^0.14.0",
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.1.0",
    "loopback-datasource-juggler": "^2.39.0",
    "serve-favicon": "^2.0.1"
  }
}
```

**Comment by Freyert** [comment]
Ok just tried doing the same in `/server/server.js` and it still does not work. Tried using `app.put` as well and that didn't work either.

**Comment by gunjpan** [comment]
@Freyert : Hi there, 
> One of my favorite express patterns is to do this (I'm doing this in a boot script. Is that bad?):

It's perfectly fine, you can use `boot` scripts to add your custom logic, in your case, routes. Read more [here](https://docs.strongloop.com/display/public/LB/Add+a+custom+Express+route).

I don't know why your `put` or `post` end points were unavailable. I tried to reproduce the same, but had all my routes available and working for `put` & `post`. 
As LoopBack is built on top-of Express, you can still use the `app` object as express-way. 
I've created a sample repository for you to have a look at:
https://github.com/gunjpan/sandbox/compare/lb-2066

In there, I've registered the routes for `/ping` and `/books` paths in `server/boot/routedefintions.js` and `server/server.js` respectively and used `postman` for sending HTTP requests, and found them available.
Please make sure the handler function you register for each HTTP method follows express convention such as: `function handler(req, res, next)` 

Also, more to read on how routing works in LoopBack [here](https://docs.strongloop.com/display/public/LB/Routing)

Closing this for now. If you need any further assistance with this, please feel free to reopen it and I'll be happy to assist. Thank you.

**Comment by Freyert** [comment]
Yup looks like the problem was I wasn't actually sending a resposne. Hmm
