### ISSUE TITLE
Updating Account (base: User) Password

### ISSUE THREAD

**Issue by liamsmall** [strongloop/loopback#2067]
Created an Account model with User as the base. After following a Reset Password link, and using prototype$updateAttributes to update the users password the password is no longer hashed.

**Comment by Amir-61** [comment]
Hi @liamsmall,

This should be fixed now; please see [this](https://github.com/strongloop/loopback/issues/2029); we published loopback-datasource-juggler@2.45.1 that should fix the problem.

Thanks!

**Comment by Amir-61** [comment]
Closing this issue since it has been fixed now.

Thanks!
