### ISSUE TITLE
How do I ignore the "id" attribute in insert / update requests?

### ISSUE THREAD

**Issue by RothAndrew** [strongloop/loopback#2068]
Using MongoDB

POSTing this

```
{
  "name": "someName",
  "subject": "Foo",
  "body": "Bar",
  "id": "SomeTerribleIdIDontWant"
}
```

Will happily insert the record, including the id, into the collection. This happens even if I don't have an "id" attribute listed in my model.

How do I force a database-generated id when inserting a new record?

**Comment by katherdx** [comment]
if you don't provide primary key, By default Strongloop  use id attribute as primary key.

**Comment by RothAndrew** [comment]
I'm fine with that. I just don't want to let whoever is running the POST request get to decide what the id of the new record is. I want the database to always come up with the id. This is done correctly if you don't pass in the "id" attribute in the request body, but if you do pass it in the database will use it as the id

**Comment by mrbatista** [comment]
Set variabile forceId: true in model definition.

Il giorno lun 15 feb 2016 15:49 Andrew Roth <notifications@github.com> ha
scritto:

**Comment by RothAndrew** [comment]
The only documentation I'm able to find for `forceID` is in the relations section.

I finally got it to work by adding an "_id" attribute
```
"_id":{
      "type":"string",
      "id":true,
      "generated":true
    }
```
and putting this in my model's .js file
```
module.exports = function(yourModelNameHere) {
  yourModelNameHere.validatesAbsenceOf("_id");
};
```

**Comment by Amir-61** [comment]
@mrbatista recommendation is what I would do as well! 

If you want to prevent someone to set this auto-id value manually, set `forceId: true`. The only documentation I could find is [here](https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations) which explain `forceid` briefly. @crandmck is the best person about documentation; do we need more explanation about this in documentation?

Thanks!

**Comment by RothAndrew** [comment]
Do I put `forceID` in the JSON object for the "_id" attribute or the model itself?

**Comment by mrbatista** [comment]
Model definition, not property definition.

Il giorno lun 15 feb 2016 20:04 Andrew Roth <notifications@github.com> ha
scritto:

**Comment by crandmck** [comment]
At a minimum, we should include this information in the [model JSON file reference](https://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Relations).  It's missing any explanation of the `relations.<modelName>.options` property (and its constituents), and also appears to be missing the `relations.<modelName>.property` option.

**Comment by Casy** [comment]
You can edit or use the endpoint replaceOrCreate if the forceId is true :/

**Comment by Amir-61** [comment]
>You can't edit or use the endpoint replaceOrCreate if the forceId is true :/

Yes that is an expected behaviour; `replaceOrCreate` uses the PK and if you use `forceId: true` it means we are preventing users from passing the PK so in this case there would be no `replace` operation and it would be always `create` operation which contradicts with the end goal of `replaceOrCreate`.

**Comment by crandmck** [comment]
@Amir-61 If we need to add or change something in http://loopback.io/doc/en/lb2/Model-definition-JSON-file.html, please open a PR.... or please give me a clearer idea of what we need to do.

**Comment by Amir-61** [comment]
@crandmck I'll find some time and send a PR ASAP.
Thanks!

**Comment by Amir-61** [comment]
PR to fix doc: https://github.com/strongloop/loopback.io/pull/170

**Comment by Amir-61** [comment]
Now `forceId` behaviour is added for both LB 2.x and LB 3.x in http://loopback.io/doc/en/lb2/Model-definition-JSON-file.html and http://loopback.io/doc/en/lb3/Model-definition-JSON-file.html respectively. The difference is default value where in LB2.x by default `forceId` is set to false whereas in LB 3.x `forceId` is set to true for security reason. Related to https://github.com/strongloop/loopback-datasource-juggler/pull/982

**Comment by shaheero** [comment]
Is this still valid? I'm running loopback 3.8. I have tried putting `"forceId": false,` in the model definition both in the first level and under `"options"`, but still an update request from within the code would return `Error: id cannot be updated from function () { [native code] } to 123 when forceId is set to true`

@Amir-61 @mrbatista

**Comment by Amir-61** [comment]
@jannyHou PTAL ^

**Comment by pbalan** [comment]
@shaheero +1.

> I have **"forceId": false** in my model definition to prevent 
>`ValidationError: The ProductCategory instance is not valid. Details: `id` can't be set (value: 1)`


I tried changing this behavior using `before save` hook too, but it seems to throw similar error...

```
Error: Duplicate entry for ProductCategory.id
at Memory._createSync (/projects/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:259:17)
    at Memory.create (/projects/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:270:8)
    at invokeConnectorMethod (/projects/node_modules/loopback-datasource-juggler/lib/dao.js:169:21)
    at /projects/node_modules/loopback-datasource-juggler/lib/dao.js:472:11
    at doNotify (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at doNotify (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:155:49)
    at Function.ObserverMixin._notifyBaseObservers (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:178:5)
    at Function.ObserverMixin.notifyObserversOf (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
    at Function.ObserverMixin._notifyBaseObservers (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:176:15)
    at Function.ObserverMixin.notifyObserversOf (/projects/node_modules/loopback-datasource-juggler/lib/observer.js:153:8)
```

**My goal is to allow users to use POST for both create/update.** I understand, its a bad API design as per REST but unfortunately required to comply to this standard as other APIs are designed this way.

**Comment by Astha-Anand** [comment]
Did you have any solution for this? still present 

`  sql:
   'UPDATE `group` SET `admin`=\'function () { [native code] }\' WHERE `id`=129',`
