### ISSUE TITLE
Remote method generator generates wrong code

### ISSUE THREAD

**Issue by smirnovshina** [strongloop/loopback#2070]
The code generated by the generator:
```javascript
  "methods": {
    "testMethod": {
//...
      "http": [
        {
          "httpPath": "/test",
          "httpVerb": "get"
        }
      ]
    }
  }
```
but according [the documentation](https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Options) we have wrong keys here and it must be like this:
```javascript
      "http": [
        {
          "path": "/test",
          "verb": "get"
        }
      ]
    }
  }
```

**Comment by jannyHou** [comment]
hey @smirnovshina thanks for your suggestion, I believe `http` and `verb` are right name.
https://github.com/strongloop/generator-loopback/issues/147 to fix it.
