### ISSUE TITLE
Unable to access iOS API docs

### ISSUE THREAD

**Issue by BlaineOmega** [strongloop/loopback#2072]
When trying to access the the iOS API documentation online via https://apidocs.strongloop.com/loopback-sdk-ios/api/annotated.html I get an error "Cannot GET /loopback-sdk-ios/api/annotated.html"

![image](https://cloud.githubusercontent.com/assets/4164126/13094191/0e24e9dc-d4be-11e5-922f-8eb3209903cc.png)

**Comment by crandmck** [comment]
@bajtos @hacksparrow Any idea why this is happening?
The Android SDK API Javadocs are still there https://apidocs.strongloop.com/loopback-sdk-android/api/index.html What happened to the iOS API docs?

**Comment by crandmck** [comment]
As a workaround, you can view the docs locally this way:
```
git clone https://github.com/strongloop/loopback-sdk-ios.git
git reset --hard 897293fc316dd28ba47815afe2b1b6a2270bcd4d
```
Then open the following file in your web browser: `loopback-sdk-ios/docs/html/annotated.html`

**Comment by BlaineOmega** [comment]
Thanks for the help! Let me know when the issues is permanently resolved. This workaround will do for now. Thank you.

**Comment by crandmck** [comment]
Added https://github.com/strongloop/loopback-sdk-ios/issues/103.

**Comment by crandmck** [comment]
Close in favor of https://github.com/strongloop/loopback-sdk-ios/issues/103
