### ISSUE TITLE
Undefined is not a function at normalizeEmailCase when looking up users by multiple email addresses

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback#2077]
Try the following:

```
var emails = [
  'example1@example.com',
  'example2@example.com',
];
app.models.User.find({
      where: {
        email: {
          inq: emails
        }
      },
    });
```

Results in error:

>  undefined is not a function at normalizeEmailCase (/home/app/node_modules/loopback/common/models/user.js:605:55

This is the offending code:

```
    // Access token to normalize email credentials
    UserModel.observe('access', function normalizeEmailCase(ctx, next) {
      if (!ctx.Model.settings.caseSensitiveEmail && ctx.query.where && ctx.query.where.email) {
        ctx.query.where.email = ctx.query.where.email.toLowerCase();
      }
      next();
    });
```

This is assuming that email is a string when it may well not be, as in the example above.

**Comment by 0candy** [comment]
The where clause is expecting a string or regex, could you try?
{
    "or": [ {"email": "example1@example.com"}, {"email": "example2@example.com"}  ]
   ]
}

See docs:
https://docs.strongloop.com/display/public/LB/Where+filter

**Comment by mrfelton** [comment]
@0candy Is this not a valid where query? I don't think I should have to use the format you have suggested.

```
where: {
    email: {
        inq:[ 'example1@example.com', 'example2@example.com' ]
    }
},
```

**Comment by mrfelton** [comment]
See https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-inq

**Comment by mrfelton** [comment]
Note that query I've highlighted is not problematic if `caseSensitiveEmail` is not disabled

**Comment by 0candy** [comment]
You are right, that is a bug. Thanks for pointing it out.
