### ISSUE TITLE
Conversion failed when converting from a character string to uniqueidentifier.

### ISSUE THREAD

**Issue by margagn** [strongloop/loopback#2081]
I am following the instructions at https://docs.strongloop.com/display/public/LB/Introduction+to+User+model+authentication regarding User authentification. I already created a basic app using the built-in models and I am using SQL Server 2014 Express as the data source.

When I try to log in a user I created using API Explorer, I get the following 500 error:

```
{
  "error": {
    "name": "RequestError",
    "status": 500,
    "message": "Conversion failed when converting from a character string to uniqueidentifier.",
    "code": "EREQUEST",
    "number": 8169,
    "lineNumber": 3,
    "state": 2,
    "class": 16,
    "serverName": "E6410\\SQLEXPRESS",
    "procName": "",
    "precedingErrors": [],
    "stack": "RequestError: Conversion failed when converting from a character string to uniqueidentifier.\n    at D:\\Temp\\loopback\\office-supplies\\node_modules\\mssql\\lib\\tedious.js:692:17\n    at emitOne (events.js:77:13)\n    at Connection.emit (events.js:169:7)\n    at Parser.<anonymous> (D:\\Temp\\loopback\\office-supplies\\node_modules\\tedious\\lib\\connection.js:244:16)\n    at emitOne (events.js:77:13)\n    at Parser.emit (events.js:169:7)\n    at Parser.<anonymous> (D:\\Temp\\loopback\\office-supplies\\node_modules\\tedious\\lib\\token\\token-stream-parser.js:51:15)\n    at emitOne (events.js:77:13)\n    at Parser.emit (events.js:169:7)\n    at readableAddChunk (D:\\Temp\\loopback\\office-supplies\\node_modules\\readable-stream\\lib\\_stream_readable.js:201:16)"
  }
}
```

Any idea what is going on?

Thank you!

**Comment by loay** [comment]
Hi @margagn 
Can you please provide a repo of your app so I can reproduce the issue and work on it?
Thanks.

**Comment by loay** [comment]
Hi @margagn 
I am closing this issue for now. if you are experiencing the same behavior, please feel free to leave a comment and I will re-open the issue. Thanks.

**Comment by zekizeki** [comment]
This problem still occurs and is the same as the one described [here](https://github.com/strongloop/loopback-connector-mssql/issues/53)
