### ISSUE TITLE
Extend model using ES6 classes

### ISSUE THREAD

**Issue by moimael** [strongloop/loopback#2083]
Hi,

I'd love that the loopback documentation provide some ES6 examples, particularly on how to extend models with es6 classes.

Thanks !

**Comment by superkhau** [comment]
Timeboxed to 3 points.

**Comment by deepakrkris** [comment]
@superkhau @ritch we can use es6 features in loopback model.js files, but loopback models are themselves not es6 classes. The base model constructors in loopback are customized in every model.js with javascript function calls. So, extending model using es6 classes is not a feature, loopback supports.

**Comment by deepakrkris** [comment]
@moimael do you want to recognize ES6 classes as models, when you drop corresponding JS files somewhere in the project? There is no out of the box solution for that. 
But we can use es6 features in model.js files. I will add documentation for that.

**Comment by superkhau** [comment]
@ritch Need your confirmation here before moving into Backlog.

**Comment by mnlbox** [comment]
Guys this issue still open after 3 years. Are you any plan about this?
I want start new project Loopback 3 generate ES5 style code and I forced to modify all of it by hand and Loopback-next also not good for production. So I can choose Loopback because of this.

**Comment by jannyHou** [comment]
Hi @mnlbox we have ES6 style guide for Loopback3, see: https://loopback.io/doc/en/contrib/style-guide.html
While back to the original topic "Extend model using ES6 classes", we don't recommend that. Deepak already explained the reason and I am afraid it takes too much effort for us to refactor the Loopback 3 model builders/constructors.

**Comment by virkt25** [comment]
Also loopback-next should be production ready next month ... you can start using it now as we don't anticipate many (if any) breaking changes ... it's just about improving the UX and bug fixes.

**Comment by bajtos** [comment]
LoopBack 3 does not support ES6 class style for defining models. Please use LoopBack 4 instead.
