### ISSUE TITLE
autoupdate datasource ignores mysql.columnName

### ISSUE THREAD

**Issue by GuilhermeMedeiros** [strongloop/loopback#2085]
I have a legacy table for users that has underscore_named_columns. After running `server.dataSources.mysql.autoupdate(['Users'], ...)` all the columns were renamed to camelCase.
Now my API cannot find those columns anymore because the mysql data source respects that property.

**Comment by 0candy** [comment]
I tried to autoupdate a table in mysql with column names that had underscore and they stayed the same and didn't get renamed to camelCase.

Could you provide a sample repo for me to reproduce the issue? Also, which version of slc are you using?

**Comment by rlloyd2001** [comment]
I'm also having the same issue. autoupdate is ignoring the columnName property and creating columns with camelcase.

"locationId":{
    "type":"String",
    "required":true,
    "length":20,
    "mysql":
    {
        "columnName":"location_id",  <---- being ignored
    }
}

Here are my dependencies:

    "loopback": "^2.29.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-component-push": "^1.5.4",
    "loopback-component-storage": "^1.8.1",
    "loopback-connector-mysql": "^2.3.0",
    "loopback-datasource-juggler": "^2.39.0",

**Comment by rlloyd2001** [comment]
When I look in the 'migration.js' file on line 20 with the MySQL.prototype.autoupdate = function(models, cb) {  method, I do not see any code that checks for the "mysql" { "columnName":.....  data.

**Comment by rlloyd2001** [comment]
The "mysql": { "columnName": ".... property is documented here: https://docs.strongloop.com/display/public/LB/MySQL+connector (fyi)

**Comment by rlloyd2001** [comment]
Here is a repo for reference. https://github.com/rlloyd2001/loopback-autoupdate-column-bug

**Comment by loay** [comment]
PR is already merged. Closing the issue.
