### ISSUE TITLE
Middleware can't target specific sub-routes in rest API?

### ISSUE THREAD

**Issue by jubbens** [strongloop/loopback#2086]
I'm trying to use middleware to intercept a specific API call. This never fires from `middleware.json` in response to `POST` requests to `/api/Pictures`:

```
...
  "routes": {
    "./middleware/custom.js": {
      "paths": [
        "${restApiRoot}/Pictures"
      ],
      "methods": [
        "POST"
      ]
    },
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  },
```

However, this _does_ fire on `POST` requests to any api endpoint:  

```
...
  "routes": {
    "./middleware/custom.js": {
      "paths": [
        "${restApiRoot}"
      ],
      "methods": [
        "POST"
      ]
    },
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  },
```

I've also tried registering this at every other phase, and have had no success. Is this unintended behavior or is this not how one should accomplish this?

**Comment by gunjpan** [comment]
@jubbens : looks like the `"${restApiRoot}/Pictures"` doesn't get resolved as the variable is not resolved. I'm investigating further and it may be a bug. Would update on it.

**Comment by ashwell** [comment]
+1

I just ran into this issue while trying to setup some recaptcha middleware to only run on our user creation route. I'd rather not hardcode the the `restApiRoot` since it is subject to change in the future.

**Comment by ashwell** [comment]
@jubbens I kept looking through loopback issues and found this one, #2456 

I think that is one of the issues both of us are running into. After spending some time trying different work arounds I ended up just settling on using a boot script that adds the middleware with the express `use` function so I could set the path to a regular expression that uses `restApiRoot` and a `$` anchor to make sure it doesn't match any child routes.
