### ISSUE TITLE
Promises replacing callbacks which return multiple arguments only return the first

### ISSUE THREAD

**Issue by zbarbuto** [strongloop/loopback#2087]
from `lib/utils.js`

``` javascript
var promise = new global.Promise(function(resolve, reject) {
    cb = function(err, data) {
      if (err) return reject(err);
      return resolve(data);
    };
  });
```

Only the first (data) argument is returned - this is an issue in the case where callback would return multiple arguments.
Example: `PersistedModel.replicate` the callback returns conflicts and cps, but the promise only returns the first argument (conflicts).

**Comment by jannyHou** [comment]
hey @zbarbuto I am checking `PersistedModel.replicate`. And I think there is a similar promisified api with multiple return arguments:
check issue here: https://github.com/strongloop/loopback/issues/1959 to see more details.
I that case, we put multiple arguments in an array to ensure single data passed to promise

**Comment by jannyHou** [comment]
I think from the definition of [`PersistedModel.replicate`](https://github.com/PradnyaBaviskar/loopback/blob/dd7f7953a6b9045f94375ae0f90568ddb73a779a/lib/persisted-model.js#L896-L897)
we need to put `conflicts` and `cps` in an array in callback.promise.
