### ISSUE TITLE
Support connection strings (settings.url) in all connectors

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2089]
We should enhance all of our connectors to support connection strings passed via `settings.url`. This makes it easier to configure datasources via environment variables provided by example by BlueMix or Heroku.

```json
{
  "db": {
    "connector": "mysql",
    "url": "mysql://localhost/test"
  }
}
```

Note that configuring the url value from environment variables is out of scope of this issue, see
https://github.com/strongloop/loopback-boot/issues/4 for that part.

**Comment by bajtos** [comment]
I think it would be good to have the `url` override all other settings like `host` and `user`. That way it's possible to specify development settings via individual settings and then let the URL from the environment variable override everything when running in staging/production.

**Comment by jannyHou** [comment]
Checklist of all datasource connectors we have:
The connetors already handles url would be checked.

- [ ] Mongodb
- [ ] Mysql
- [ ] Postgresql
- [ ] Mssql
- [ ] DB2
- [ ] Cloudant
- [ ] Oracle
- [ ] Redis
- [ ] sqlite3 (N/A in this story)

**Comment by jannyHou** [comment]
**VERIFY STEPS**

This feature enables datasource using connection strings. So there are two things to verify for each connector:

- [ ] The connection string will override other config(could be verified by making them invalid, but the connection should succeed due to correct url)

- [ ] Config object without connection string still works(could be verified by make url empty)

And please check https://github.com/strongloop-internal/scrum-loopback/pull/831#issuecomment-209156739 to see the details of the format of each connector's url.

**Comment by bajtos** [comment]
Once this is verified, we should make a new release for all relevant modules (juggler, connectors, etc.)

**Comment by cgole** [comment]
@laven26 @ssh24

**Comment by ssh24** [comment]
`Verified`.

- [x] MongoDB
- [x] MySQL
- [x] MSSQL
- [x] Cloudant
- [x] Oracle
- [x] Postgresql
- [x] DB2 : there is no issue from our QA developer side. DB2 connector does not work properly for which I have created an issue https://github.com/strongloop/loopback-connector-db2/issues/32

**Comment by sm-g** [comment]
What about sqlite3? Any other way to set `foreign keys=true` in connection steing?

**Comment by jannyHou** [comment]
@sm-g I am not quite familiar with database sqlite3, I think @raymondfeng or @bajtos might be able to give you a quick answer of
> Any other way to set foreign keys=true in connection string?

I will look into it then.


> What about sqlite3?

The feature in this pr is a short-term solution. Actually we have a long-term discussion about implementing a unified NDBC interface for relational databases. I will bring "support sqlite3 connection string" into plan, and we will discuss what's the proper way to do it.

**Comment by bajtos** [comment]
I believ all related modules have been already published to npmjs.org, I am closing this issue as done.
