### ISSUE TITLE
New yeoman generator for automatic crud frontend generation

### ISSUE THREAD

**Issue by johannesjo** [strongloop/loopback#2090]
Hello there. I hope you can forgive me opening this non issue. I developed an generator for an angularjs crud interface, which automatically parses the model definitions into forms and routes. It's still pretty early in development, but a base version is working (imho pretty nicely ;)).

Check it out! 
https://github.com/johannesjo/generator-angular-auto-admin-loopback
Or for an easier start the pre built example:
https://github.com/johannesjo/angular-auto-admin-looopback

I'm posting this here, because I'm hoping that others might be interested as well in such an easy way to generate an admin interface for your api and I would be very glad for some help developing the whole thing.

Best,

Johannes

**Comment by jannyHou** [comment]
@johannesjo Thank you for your interest in loopback and the effort you spend in this generator!

@bajtos @superkhau any thoughts?

**Comment by bajtos** [comment]
@johannesjo there is already another project implementing an admin interface in AngularJS, see https://github.com/beeman/loopback-angular-admin. Perhaps you can join the efforts?

I am closing this issue as it's not an actionable task for us.

**Comment by johannesjo** [comment]
@bajitos yes I know this one. Its more of an admin interface boilerplate. I don't like the setup too much, but I'll think about a way. Thanks for mentioning.
