### ISSUE TITLE
Where clause used within include is not working correctly

### ISSUE THREAD

**Issue by j-norman** [strongloop/loopback#2091]
I've dug and dug and I have not come up with a solution to this problem so I figured it was time to report this so that you can either tell me that I am an idiot and I should be doing something else instead, or acknowledge that this is a bug so that I won't feel like I'm losing my mind.

Starting with the loopback documentation: https://docs.strongloop.com/display/public/LB/Include+filter#Includefilter-Includewithfilters

This documentation explains how a query should be constructed if you want to filter on an include (join).  this led to me writing the following query (JSON REST call) against our company table:
filter={"fields":["id","name","companyRoles"],"include":{"relation":"companyRoles","scope":{"where":{"roleDefId":"client"}}}}

This is based on the following models (trimmed down for brevity):
Company.json
`
...
  "relations": {
    "companyRoles": {
      "type": "hasMany",
      "model": "CompanyRole",
      "foreignKey": "companyId"
    }
  }
...
`

Company-role.json
`
...
  "properties": {
    "companyId": {
      "type": "String",
      "required": false,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "company_id",
        "dataType": "text",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      },
      "_selectable": true
    },
    "roleDefId": {
      "type": "String",
      "required": false,
      "length": null,
      "precision": null,
      "scale": null,
      "postgresql": {
        "columnName": "role_def_id",
        "dataType": "text",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "YES"
      },
      "_selectable": true
    }
  },
  "relations": {
    "roleDef": {
      "type": "belongsTo",
      "model": "RoleDef",
      "foreignKey": ""
    },
    "company": {
      "type": "belongsTo",
      "model": "Company",
      "foreignKey": ""
    }
  },
...
`

The key here is that the company_role table stores the role_def_id, which is just string 'key' for a particular role.  so i can do things like check if role_def_id='client' (in sql).

The problem is that the filter is not being applied correctly.  When i run this query, i get back ALL companies and only those that match the query have their companyRoles object (array) populated.  So, in the example above, the response ends up looking something like this:

`...[{"id":"11111111","name":"company 1","companyRoles":[]},{"id":"22222222","name":"company 2","companyRoles":[]},{"id":"33333333","name":"company 3","companyRoles":[{"roleDefId":"client","name":"client","companyId":"33333333","id":3}]}...`

This is bad because there is definitely the possibility of thousands of companies (or whatever other record we are setting roles on).  I CAN filter out the results in the client, but this seems broken to me?  Am I correct?  Is this in fact broken?  Or have I done something seriously wrong?  Full disclosure: I own the front end that is consuming the loopback APIs.  Someone else owns the loopback stuff.  I can get in there and tweak but its not my area of expertise: feel free to dumb down any responses.  This is also a private repo so I cannot give access, but i will provide code and/or answer any questions where possible.

...The frustrating thing for me is that it takes me 30 seconds to write the sql for this query:
`select * from company c inner join company_role cr on c.id = cr.company_id where cr.role_def_id = 'client'`

Thank you in advance for your time.

**Comment by 0candy** [comment]
@j-norman You are not losing your mind. What you are trying to do is not supported. See https://github.com/strongloop/loopback/issues/517#issuecomment-71796806

Can you confirm whether its the same issue you're having? If so, I will close this as a dup of that issue.

Thanks!

**Comment by j-norman** [comment]
I had read over that issue, but i also read over the doc that i linked above and it basically covered what i am trying to do:

`
Post.find({
  include: {
    relation: 'owner', // include the owner object
    scope: { // further filter the owner object
      fields: ['username', 'email'], // only show two fields
      include: { // include orders for the owner
        relation: 'orders', 
        scope: {
          where: {orderId: 5} // only select order with id 5
        }
      }
    }
  }
}
`

Granted, this is not a REST call (looks like its an Angular API call, which i am not using).  But, it is creating the exact type of filter that i am trying to do.  

I will re-read 517, but according to the doc, I should be able to do the query i have attempted. (an include with a where clause to filter results coming from the join)

Thank you!

**Comment by j-norman** [comment]
I discussed this with some people here and i think i understand what loopback is doing.  Basically it is joining the results of two queries.  query 1 is on the companyRoles object and only returns items that match the filter.  it then basically does a left join with the company table.  this is why companies that don't have a particular role are coming back with an empty array for the roles.  (or this would at least explain the results)  Not ideal, nor what I think people would expect (at least those thinking in terms of SQL) but at least i think i know what is going on now.

**Comment by 0candy** [comment]
Yes, that is what the results are returning. All the results from the first model plus any related model with the filter query that you specified.

An alternative is to execute native SQL, but this is not officially supported.
https://docs.strongloop.com/display/public/LB/Executing+native+SQL

**Comment by j-norman** [comment]
Closing.  I can't really say I like the behavior, but i now understand it.  You may wish to clarify your documentation found at https://docs.strongloop.com/display/public/LB/Include+filter#Includefilter-Includewithfilters because this led me to believe that this worked more like a SQL inner join.  Thanks!

**Comment by 0candy** [comment]
Sorry for the confusion. We should get the documentation clarified.

@crandmck Maybe we can clarify the documentation on this matter?

**Comment by j-norman** [comment]
Thank you so much.  Sorry if this was a bit of a bone-headed question.

**Comment by crandmck** [comment]
@j-norman @0candy I would like to add a note to that section, as suggested, but I want to make sure I have it right... Here's my draft--please let me know if this is right:

**NOTE**: When you apply filters to related models, the query returns results from the first model plus any results from related models with the filter query, similar to a "left join" in SQL.

**Comment by j-norman** [comment]
That should work.  Now users of loopback will just need to read the doc!  ;)

Thank you.

**Comment by 0candy** [comment]
@crandmck  That's right.

**Comment by crandmck** [comment]
Thanks!  Updated the doc.
>  Now users of loopback will just need to read the doc! ;)

Yep, there's the rub ;-)

**Comment by j-norman** [comment]
Thank you guys/gals.  Much appreciated.  lesson learned: when filtering such as i wanted to do, it has to flow "left to right" - then things work just fine.  (filter the primary set first, in this case the roles, and then join to the other set, in this case the companies)

Cheers!

**Comment by rurivera6** [comment]
Wow, I just ran into the same thing.  Does loopback ever intend on supporting "inner" or "right" joins?  I'm having to filter my results for the right/linked table first then having to do an "inq" clause on the left table.  Klugie work arounds everywhere I need an inner join.

**Comment by ataft** [comment]
Double Wow, I just ran into this issue as well. Doing a trace on the database, I realized that "include" is not doing any type of join, but rather executing a separate query for each model/table. At first, I was worried it was looping through the initial result set and executing a query for each row to get the include data. However, it appears that it executes the main query, then one query for each include using a clause like "WHERE [id] IN (@param1,@param2)". Then, I suppose it "joins" the data in the loopback code.

I can't imagine how this approach can possibly scale to larger datasets with many users. Hopefully I'm missing something? For now, I'll design with this in mind and "flow left to right" as j-norman said...

**Comment by developermhayden** [comment]
Just to chime in, my endpoint looks like this:
/api/v1/roles?filter= {"fields": ["id", "name", "alias"], "where": {"name": "admin"}, "include": [{"relation": "users", "fields": ["id", "name"]}]}

the include part on the users collection is not limiting the number of returned fields to "id" and "name"

**Comment by BahodurSaidov** [comment]
Triple Wow! I got the same issue here! What about solutions? Any alternative to achieve nested filter for 3rd step related models?
By the way, in my case it looks strange, from explorer i 
`include: { relation:"relatedModel",scope:{where: {id: SomeId}}}` 
even though SomeId = 2, in the console.log i see always 
`{where: {id:{inq:[1]}}} `
and it always returns that model with id==1 ..

Any explanation for this ?

**Comment by pookdeveloper** [comment]
Where in include d'osent work

![image](https://user-images.githubusercontent.com/3384734/60822280-70767d00-a1a5-11e9-86ae-e90e40a1df57.png)

this is my model:

````
{
  "name": "obras",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "foreignKeys": {
    "id_derecho_obras": {
      "name": "id_derecho_obras",
      "foreignKey": "id_derecho",
      "entityKey": "id",
      "entity": "derechos_funerarios"
    }
  },
  "properties": {
    ...
  },
  "validations": [],
  "relations": {
    "derecho": {
      "type": "hasOne",
      "model": "derechos_funerarios",
      "foreignKey": "id",
      "primaryKey": "id_derecho"
    }
  },
  "methods": {}
}
````

What's my problem??? Thankss!
