### ISSUE TITLE
Doc's Unclear in regard to Bulk Updates

### ISSUE THREAD

**Issue by CarlosCuevas** [strongloop/loopback#2093]
https://docs.strongloop.com/display/public/LB/Creating%2C+updating%2C+and+deleting+data#Creating,updating,anddeletingdata-Performingbulkupdates

There's just two links to the API reference.  The description fields for PersistedModel.createUpdates in the API reference are empty.  Some explanation + an example would be really helpful.

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
@superkhau Can someone in engineering provide this information?  IIRC, bulk updates are used with sync, but I don't know any more.  If someone can give me the basic info here, I will be glad to add it to the docs.

**Comment by superkhau** [comment]
@crandmck I don't know the answer to this one. I believe @bajtos can probably help with this one since he implemented the code in question in `persisted-model.js`.

**Comment by bajtos** [comment]
@CarlosCuevas these two methods are sort of internal, we use them in our change replication algorithm. We don't have a formal documentation yet and I am afraid that writing one is not a priority right now. Here are few pointers to get you started at least:
 - https://gist.github.com/bajtos/63b415629a341ef5d0c9#understanding-the-replication
 - http://www.slideshare.net/Bajtos/2014-07offline-data-sync-in-loop-back
 - https://www.youtube.com/watch?v=upuUTQS2DXw
 - and the source code:  [lib/persisted-model.js#L932-L1118](https://github.com/strongloop/loopback/blob/76bd587198838a0c7edc31fae6e8248700813054/lib/persisted-model.js#L932-L1118)

**Comment by CarlosCuevas** [comment]
@bajtos thanks

**Comment by crandmck** [comment]
@bajtos @superkhau Can we close this now?  If we ever intend to doc this, then we should probably keep it open track; if not, suggest we close.

**Comment by superkhau** [comment]
+1 for closing if we don't intend to doc this

**Comment by bajtos** [comment]
I think we may eventually want to document this, but I don't think that will happen any time soon. I am closing the issue for now.
