### ISSUE TITLE
ValidateAsync do not work properly if documentation is followed

### ISSUE THREAD

**Issue by mamartins** [strongloop/loopback#2095]
``` js
module.exports = function (Rate) {

    Rate.validateAsync('shopperId', relationsValidator,
        { message: 'Rate should only have a shopper or a team associated to it' }
    );

    function relationsValidator(err, done) {
        process.nextTick(function () {
            console.log(this);
            if (this.shopperId && this.teamId) {
                err();
            }
            done();
        });
    }
}
```

the `this`object since is called inside another function does not refer to the desired object but to the function itself. So the documentation is wrong as you need to add `var self = this` like other pre-defined validators have, otherwise it won't work as expected.

here: https://apidocs.strongloop.com/loopback-datasource-juggler/#validatable-validateasync

**Comment by mamartins** [comment]
after lots of debugging I found out a way to make it work.

I needed to add ```` var self = this ```` like other pre-defined validators have, otherwise it won't work

**Comment by jannyHou** [comment]
@mamartins Thank you for pointing out this.

According to the result, it's triggered but always returns false. Will look into it then, and example here also doesn't return correct result:
https://github.com/strongloop/loopback-datasource-juggler/blob/1e8fe6a0d7b5c84a3f67ad4d6a05ddaa8d1229ba/lib/validations.js#L165
