### ISSUE TITLE
Document uuidv4 option for defaultFn in model definition file

### ISSUE THREAD

**Issue by aalexgabi** [strongloop/loopback#2099]
Here https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file, uuidv4 option should be mentionned next to uuid option.

**Comment by aalexgabi** [comment]
It seems that I can't add doc label.

**Comment by 0candy** [comment]
@crandmck ^^

**Comment by crandmck** [comment]
Updated https://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Generalpropertyproperties.

**Comment by aalexgabi** [comment]
Great. Thanks!
