### ISSUE TITLE
The remote methods of relation model doesn't work?

### ISSUE THREAD

**Issue by Emiya0306** [strongloop/loopback#2101]
Follow the step:
- I create a user based User(build-in model) and a bookmark(PersistedModel).
- And then created the relation, "user" hasMany "bookmark", "bookmark" belongsTo "user". 
- After that, I open the explorer(http://localhost:3000/explorer) and use the remote method, "user/{id}/bookmarks".

I get the response is

```json
{
  "error": {
    "name": "Error",
    "status": 404,
    "message": "Shared class \"User\" has no method handling GET /56cd55e46cb45dd277906dc3/bookmarks",
    "statusCode": 404,
    "stack": "Error: Shared class \"User\" has no method handling GET /56cd55e46cb45dd277906dc3/bookmarks\n    at restRemoteMethodNotFound .......
  }
}
```

I would like to get the bookmarks only belongs to user, the solution is only write a rest api by myself?

**Comment by gunjpan** [comment]
@Emiya0306: Hi, the reason you're unable to access the bookmarks, I believe, is that you might not have setup ACLs.
> By default, access to related model methods is denied. To call these methods, you must set the permission property to "ALLOW" as described [here.](https://docs.strongloop.com/display/public/LB/Accessing+related+models)

Please setup the ACL and see if you're able to get the bookmark for your userid. _Note:_ You will need to set a token in explorer to make authenticated requests. See 'how to' [here](https://docs.strongloop.com/display/public/LB/Introduction+to+User+model+authentication#IntroductiontoUsermodelauthentication-Loginasthenewuser)

**Comment by Emiya0306** [comment]
Yeah~ I do not setup the ACLs of the bookmarks, and I think it may not effect on it.
Now I setup the ACLs for all users grant access, both user(Based on User) and bookmark. But I cannot get the remote method of users/{id}/bookmarks as well.
Here is the link of my simple demo project, here are more detials. [Bookmark Project](https://github.com/Emiya0306/bookmark-angular/tree/UserACL)
I try the model based on PersistedModel, it can work successfully. May be the question is on the Build-In User.

**Comment by gunjpan** [comment]
@Emiya0306 : Hi, apologies for a delayed reply and thank you for providing the repo. 
After further investigating, I found out following:
>By default, all related model methods have a `DENY ALL` ACL set. You need to explicitly grant access.  ACLs do not inherit from the target model's endpoint.
So, for example, even if the books model's default ACL is ALLOW `$authenticated` for `GET /books`, the route `GET /user/{id}/books `default will still be `DENY ALL`.

That means, adding following ACLs unlocked the endpoint:  GET `/users/{id}/bookmarks`:
```
   {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "__get__bookmarks"
    }
```

where `property` is the `related model method` created by LoopBack based on model relations.
FYI, following are the model methods generated for 
```
hasMany:

    __count__relatedModelNamePlural
    __create__relatedModelNamePlural
    __delete__relatedModelNamePlural
    __destroyById__relatedModelNamePlural
    __findById__relatedModelNamePlural
    __get__relatedModelNamePlural
    __updateById__relatedModelNamePlural
```
Thus, the conclusion is, you need to set ACLs for related model methods as requried. You can read more [here](https://docs.strongloop.com/display/public/LB/Accessing+related+models)

Please let me know if that helped. Thank you :)

**Comment by Emiya0306** [comment]
Yeah! It helps me and I learn a lot about relation models. It's cool! By the way, I also ignore to set the User model to "public": false, it makes 404.

Thank your very much, and here is another question about promise. Link is [here](https://github.com/strongloop/loopback/issues/2150).

**Comment by adamhenson** [comment]
It seems that I have a similar issue and opened #3462. After following the advice here and the [documentation ("Accessing related models")](https://loopback.io/doc/en/lb3/Accessing-related-models.html), my problem still persists.

I see this error message on POST request response:

```
Shared class  \"User\" has no method handling POST /594fcbeee223ce23620a3e12/accounts?access_token=Dg8qkXIHEck9fS0taCPWxklSVwD6HivN7iVU0lq0SBhaXQ8dMJmo6j8WxQGBNKRD
```

I created a [full example project here](https://github.com/adamhenson/loopback-api-example/tree/acl). Also, [here's the diff with just my ACL setup](https://github.com/adamhenson/loopback-api-example/compare/relations...acl).

**Comment by demiro** [comment]
So I have a similar problem...  I extended the User model and added a relation (belongsTo) and I am having trouble with seeing the relation work....
```

{
  "name": "user",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "client": {
      "type": "belongsTo",
      "model": "client",
      "foreignKey": ""
    }
  },
  "acls": [ {
    "accessType": "EXECUTE",
    "principalType": "ROLE",
    "principalId": "$authenticated",
    "permission": "ALLOW",
    "property": "__get__client"
  }],
  "methods": {}
}

```

In my API explorer I see the client option

> ...
> PUT /users/{id}/accessTokens/{fk}
> DELETE /users/{id}/accessTokens/{fk}
> GET /users/{id}/accessTokens/count
> GET /users/{id}/client
> ...


but, if I do try to get the client I get this:
```
{
  "error": {
    "statusCode": 404,
    "name": "Error",
    "message": "Shared class  \"User\" has no method handling GET /59ba56d99bd5962e28fc0904/client?access_token=dTVXhsZDmT6WsmN0u4hADCLNmTEUbehXqGfM3XVqojBwYgZ4u4vzQn1BaQUSdlbw",
    "stack": "Error: Shared class  \"User\" has no method handling GET /59ba56d99bd5962e28fc0904/client?access_token=dTVXhsZDmT6WsmN0u4hADCLNmTEUbehXqGfM3XVqojBwYgZ4u4vzQn1BaQUSdlbw\n    at restRemoteMethodNotFound (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\strong-remoting\\lib\\rest-adapter.js:357:17)\n    at Layer.handle [as handle_request] (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:47:12)\n    at Layer.handle [as handle_request] (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:317:13)\n    at C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at jsonParser (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\body-parser\\lib\\types\\json.js:103:7)\n    at Layer.handle [as handle_request] (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\DEVEOPMENT\\CHELSEA\\_TIMELINE\\timelina-api\\node_modules\\express\\lib\\router\\index.js:317:13)"
  }
}
```

what do I need to do?

**Comment by adamhenson** [comment]
@demiro - I've been there - feel your pain. I think the documentation guided us into that hole.

You need to remove a block from `/server/model-config.json` [detailed here](https://github.com/strongloop/loopback/issues/3462#issuecomment-311347219)... otherwise rename `user` - because this is [caused by case insensitive routing](https://stackoverflow.com/questions/44748809/loopback-how-to-create-an-extended-user-model-relation/44754490#comment76541775_44754490).

**Comment by demiro** [comment]
@adamhenson : Thanks my man! that was a quick response and actually solved the problem easily! 1000x thanks!
