### ISSUE TITLE
disableRemoteMethod("count", true) does not hide the count endpoint

### ISSUE THREAD

**Issue by yuyudhan** [strongloop/loopback#2102]
I have an extended model MyUser on User model.
Calling MyUser.disableRemoteMethod("count", true); should disable the count of user endpoint & give 404, but it gives 401 unauthorized. I have no ACLs applied here.

The disableRemoteMethod works fine on find & other methods of the MyUser model.
 ----
The disableRemoteMethod works in mischeivious ways. 
For another model createChangeStream method disables only the POST on it but not the GET

**Comment by 0candy** [comment]
Can you please provide a link to a test project for me to reproduce the issue? Thanks!
See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by jannyHou** [comment]
Should be the same issue as https://github.com/strongloop/loopback/issues/2711
Closing it as a duplicate.
