### ISSUE TITLE
config.js

### ISSUE THREAD

**Issue by giowe** [strongloop/loopback#2103]
Why can't we just use config.js instead of config.json but we can use config.env.js?

I wish to do this in my base config.js:

```
module.exports = {
  port: process.argv[2] || pkg.config.port || 7770
}
```

but I have to create 3 of them (config.development.js , config.staging.js , config.production.js )

**Comment by edachsanpro** [comment]
look the doc:
https://docs.strongloop.com/display/public/LB/Environment-specific+configuration

**Comment by giowe** [comment]
yes... as I said:
I can use both server/config.**{env}**.json/js
but just  server/config.json.
It would be useful a  server/config.js

**Comment by davidcheung** [comment]
I'm also curious as to why `config.js` isn't under the default boot list, while `config.local.js` and config.`<env>`.js works

@bajtos, @superkhau any thoughts?

**Comment by bajtos** [comment]
Hello, this is a commonly asked question. The reason why don't support `.js` extension for "master" configuration files (config, datasources, model-config, etc.) is to allow programatic editing of the configuration via loopback-workspace, for example in StrongLoop Arc. Now we have `config.json` that is easy to edit via `JSON.parse` and `JSON.stringify`. If there was `config.js`, our tooling would not be able to display and modify this configuration.

@crandmck @davidcheung could we please write this down somewhere in our docs or FAQ?

**Comment by bajtos** [comment]
Loosely related: https://github.com/strongloop/loopback-boot/issues/93

**Comment by crandmck** [comment]
Added https://docs.strongloop.com/display/APIC/LoopBack+FAQ#LoopBackFAQ-DoesLoopBacksupportJavaScriptconfigurationfiles(notjustJSON)?
