### ISSUE TITLE
allow built-in token middleware to be run multiple times

### ISSUE THREAD

**Issue by benkroeger** [strongloop/loopback#2106]
I'm loading the built-in token middleware once globally (all verbs, all paths) during the "auth" phase. However, for the use-case of linking multiple accounts (e.g. via OAuth) - and due to the fact, that my primary auth mechanism is not cookie-based - I'm also loading the token middleware specifically on the `callbackPath` for my auth providers. The latter instance of the middleware is configured to only check for a provider-specific cookie (which is set when accessing the `authPath`) - and is supposed to use that to fill `req.accessToken`. The cookie expires within a configurable amount of minutes and gets removed when the `callbackPath` is requested.

Digging [in the code](https://github.com/strongloop/loopback/blob/master/server/middleware/token.js#L99), I found that the token middleware skips when `req.accessToken !== undefined`. Unfortunately, if the first instance of the middleware can not find valid credentials, it assigns `req.accessToken = null` (which is `!== undefined`).

In your [tests](https://github.com/strongloop/loopback/blob/master/test/access-token.test.js#L182) you say that it "should skip when req.token is already present" - which is not the case when set to `null`.

Am I missing a switch somewhere?
Would you guys be okay with an PR to change the [condition](https://github.com/strongloop/loopback/blob/master/server/middleware/token.js#L99) from `req.accessToken !== undefined` to `req.accessToken && req.accessToken.id`?

**Comment by richardpringle** [comment]
Hey @benkroeger, that makes sense to me. What I suggest is to make the PR then reference this issue in the description. One of the lead maintainers will review. Mention me in the PR as well and I will make sure that it gets reviewed in a timely manner.

**Comment by bajtos** [comment]
Done - see #2108 (3.x), #2204 (2.x).
