### ISSUE TITLE
domain/api/explorer gives 404

### ISSUE THREAD

**Issue by b3nk3** [strongloop/loopback#2107]
Hi, 

I have successfully connected to my db via loopback, and it serves back properly under http://scopula.b3nk3.co.uk/api/recipes

however when I try to access the explorer
http://scopula.b3nk3.co.uk/api/explorer

I get this:

{"error":{"name":"Error","status":404,"message":"There is no method to handle GET /explorer"

**Comment by gunjpan** [comment]
@b3nk3 : If you're trying to access LoobBack Explorer, it can be accessed as follows:
`http://<your host>/explorer`. Read more on running Explorer [here](https://docs.strongloop.com/display/public/LB/Use+API+Explorer#UseAPIExplorer-RunAPIExplorer).

Hope that answers your question. Closing it for now, if you need further assistance, please feel free to reopen it and include my handle. Thank you!

**Comment by b3nk3** [comment]
I have nginx and my localhost:3000 is put through /api

Could that cause any troubles?

**Comment by gunjpan** [comment]
@b3nk3:
Re:
>I have nginx and my localhost:3000 is forwarded over to
/api

That is very limited information for me to see what's happening, but, I guess, it could be the case that the path results into: `/api/explorer` which is invalid for accessing explorer.

**Comment by b3nk3** [comment]
@gunjpan I have sorted it in the meantime. The problem was that I had the :3000 port forwarded onto a domains /api . Now I have changed it to a separate subdomain rather than /api and it works as a charm.

Thanks for answering tho.
