### ISSUE TITLE
Switch to JSON schema for definition of model properties

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2109]
Deprecate LDL (LoopBack Definition Language) in favour of JSON schema v4/Swagger Schema with LoopBack-specific extensions as needed.

**Comment by snagi** [comment]
Is there any work in progress on this feature?

**Comment by raymondfeng** [comment]
IMO, a better approach is to allow plugins in loopback-boot so that a jsonschema plugin can take care of transforming such definitions to LDL.

**Comment by raymondfeng** [comment]
BTW, loopback-boot@3.x already supports plugins. See an example at https://github.com/strongloop/loopback-boot/blob/master/test/fixtures/simple-app/plugins/tracker.js
