### ISSUE TITLE
Bug while querying nested relationships

### ISSUE THREAD

**Issue by timotheemoulin** [strongloop/loopback#2112]
[models.zip](https://github.com/strongloop/loopback/files/153726/models.zip)

Hi,

I just set up a new project based on loopback.io and angularjs.

I added a few models with relations : 
- Drink belongsTo Product
- Product belongsTo Category
- Category hasMany Products

My JSON models declarations are attached.

Via the explorer (or my code) I can easily get the list of Products (**GET /Products**) which sends me a JSON with the list of all Products with their Categories.

But when I query the Drinks (**GET /Drinks**) I get the following error.

``` shell
node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:152
        if (!arr.length) {
                ^
TypeError: Cannot read property 'length' of undefined
    at Object.async.each (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:152:17)
    at linkOneToMany (node_modules/loopback-datasource-juggler/lib/include.js:813:19)
    at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:157:13
    at _each (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:57:9)
    at Object.async.each (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:156:9)
    at targetLinkingTask (node_modules/loopback-datasource-juggler/lib/include.js:809:17)
    at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:723:21
    at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:391:17
    at node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:157:13
    at _each (node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:57:9)
```

If I remove the relation in the Product model the error is solved (but I don't get the relation so it's not good enough :/).

Is there any way to do a query trough multiple layers of relationships?

**GET /Drinks** should return something like : 

``` json
[
    {
        "date": "2016-03-01T17:50:34.000Z",
        "quantity": 1,
        "id": 1,
        "productId": 21,
        "drinkerId": 1,
        "product": {
            "name": "Expresso",
            "description": null,
            "id": 21,
            "categoryId": 1,
            "category": {
                "name": "Coffee",
                "id": 1
            }
        }
    },
    ...
]
```

Any thought?
tim

**Comment by richardpringle** [comment]
@timotheemoulin:
I just tried with your exact code and it worked fine. Which version of Loopback are you using?

**Comment by timotheemoulin** [comment]
https://github.com/timotheemoulin/loopback-coffee

Here is the full application. It should use the last version of loopback 2. Thanks for helping.

**Comment by timotheemoulin** [comment]
Hey @richardpringle, I was out of home so I couldn't check so far.
So, the exact version of loopback is 2.27.0; loopback datasource juggler 2.45.2

Tell me if you need to know anything else.

**Comment by richardpringle** [comment]
Thanks, I'll take another look

**Comment by timotheemoulin** [comment]
@richardpringle what version of loopback were you using to succeed the test?

I'm runing some tests with different versions but nothing concluent so far...

**Comment by richardpringle** [comment]
Hey @timotheemoulin, sorry about the delay. Again, I tried it out and it worked. I however, was using the memory datasource. Try that, see if it works. If it does, at least you have narrowed down the issue. 

In general, the memory datasource SHOULD function exactly the same as all the other datasources. I don't see any reason why your code wouldn't work so I'm guessing it's either an issue with the way your database is set up or records that it holds.

Try it out, let me know if you can narrow down your issue further and I'll see if I can help you from there.

**Comment by timotheemoulin** [comment]
I tried it with the "memory" connector and it seems to work. Do you know whether there is another mysql connector?

We strongly need to use a relational database. Do you think that we could/should use another database system?

Thanks for your inputs.

tim

**Comment by richardpringle** [comment]
@timotheemoulin,

Might not be a bad idea to try out another database system and see if it works, but this looks like a bug. One of LoopBack's strong points is that all PersistedModel methods *should* function the exact same no matter what the datasource is. It is possible however that *monkey-patching* the `find` function is causing a problem with the mysql-connector. 

Instead of *monkey-patching* `find`, could you use an [*access operation-hook*](https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-access)?

It would look something like this:
```node
Drink.observe('access', function(ctx, next) {
    if (!ctx.query.include) {
        ctx.query.include = "product";
    }
    next();
});
```

Let me know if that solves your issue. If not, I will take a look at the connector but I have a strong feeling that there will not be any easy fix.

**Comment by richardpringle** [comment]
Hey @timotheemoulin, have you seen this: https://docs.strongloop.com/display/public/LB/Embedded+models+and+relations
