### ISSUE TITLE
Documentation is incomplete in the "Accessing related models" page

### ISSUE THREAD

**Issue by danielrvt** [strongloop/loopback#2114]
I've been struggling for a while because this [documentation](https://docs.strongloop.com/display/public/LB/Accessing+related+models) misses the section about the "**hasAndBelongsToMany**" relation.

For what is worth, this is the part that should be found:

**hasAndBelongsToMany:**
- __link__relatedModelNamePlural
- __unlink__relatedModelNamePlural

**Comment by 0candy** [comment]
@crandmck ^

**Comment by crandmck** [comment]
I'm confused--Is this for **hasAndBelongsToMany** or **hasOne** ?   The first sentence above says the former, but below that says the latter...

**Comment by richardpringle** [comment]
@crandmck, [the ACL documentation for related models](https://docs.strongloop.com/display/public/LB/Accessing+related+models) is missing the list of method names for the **hasAndBelongsToMany** relation.

@danielrvt are you also saying that the **hasOne** list should contain the *__link__* and *__unlink__* methods as well?

@crandmck, better confirm with @raymondfeng

**Comment by danielrvt** [comment]
It's just for hasAndBelongsToMany

**Comment by crandmck** [comment]
Thanks @danielrvt I added the info you suggested above.
@raymondfeng or @richardpringle can you please confirm the information [above](#issue-137887379)...
