### ISSUE TITLE
Number of removed items in `after delete` 

### ISSUE THREAD

**Issue by zanemcca** [strongloop/loopback#2115]
I have an `after delete` hook that I need to run only once per deletion of an instance.
So I need to detect if the instance was deleted or if the delete call was an extra one.

Is there some way we can get the deletion count in `after delete`?

**Comment by richardpringle** [comment]
@zanemcca, you should know the rules. NO QUESTIONS ON GITHUB!!!! If you didn't know that, [our wiki](https://github.com/strongloop/loopback/wiki/Questions) states it. There are too many bugs and feature requests in the issues section to be able to manage questions as well.

Can we continue the discussion on [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs) or [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50) instead?
