### ISSUE TITLE
How to create Subdomain for each single user?

### ISSUE THREAD

**Issue by dineshi2it** [strongloop/loopback#2116]
I need to create an application usin loopback to create subdomain for each user as how slack does. Thanks in advance.

**Comment by richardpringle** [comment]
> ... subdomain for each user

Do you mean subdomain for each team?

Also, we are actually reserving GitHub issues for feature requests and bug reports. For further discussions and questions, please post on one of the following:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

@dineshi2it, I am going to close this question but I can also try to help if you continue the discussion in this thread. I do however advise that you post in the Google Group as well and take advantage of community knowledge there.

Good luck!

**Comment by dineshi2it** [comment]
@richardpringle Thanks, I have posted the same in google groups.
