### ISSUE TITLE
`after delete` has no indicator of the removal count 

### ISSUE THREAD

**Issue by zanemcca** [strongloop/loopback#2120]
I have created a [sandbox](https://github.com/instanews/loopback-sandbox) that outlines the problem. 
Also the `ctx.instance` is present even if the object was not actually deleted which leaves me with no indication of whether an actual delete took place.

**Comment by zanemcca** [comment]
@richardpringle Can you have a look at this?

**Comment by richardpringle** [comment]
@zanemcca took a looK, decided to throw a feature request tag on this issue.

Cheers

**Comment by zanemcca** [comment]
Perfect thanks @richardpringle
I found a workaround for now  by setting `"secureDelete" : true` in my models json file. But ideally having a count would be best.
