### ISSUE TITLE
How to search JSON data in mysql using Regular expression in Strongloop?

### ISSUE THREAD

**Issue by katherdx** [strongloop/loopback#2124]
I have stored JSON data (JSON String data) in table. I want to fetch data based on userId, userId is a property of Users Object, it is a value of speficUsers property. see below table data.  

Example: I want fetch all the records if users contain 513
My table data :

```
Table name:share

Id  name            sharedusers
1   xxxx            {"accessType":0,"permission":"1","specificUsers":
                    [{"users":["502","512","513"],"permission":"1"}]}

2   yyy             {"accessType":0,"permission":"1","specificUsers":
                    [{"users":["5","50","60"],"permission":"1"}]} 

3   zzzz            {"accessType":0,"permission":"1","specificUsers":
                    [{"users":["502","500","513"],"permission":"1"}]} 
```
**I tried following query in find() method but is not working, its showing error..**
```
{"where": {"sharedusers": {"regexp": "/"users":"[^"]*\b513\b/"}}}

{"where": {"sharedusers": {"regexp": /"users":"[^"]*\b513\b/
}}}
{"where": {"sharedusers": /"users":"[^"]*\b513\b/} }

{"where": {"sharedusers": "/"users":"[^"]*\b513\b/"} }

and also i tried restcall

filter[where][share][regexp]=/"users":"[^"]*\b513\b/
```
** My model definition:**
```

{
  "name": "share",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "sharedusers": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```
Mysql version : '5.6.27-log'

**Comment by richardpringle** [comment]
Hey @katherdx, in the future, please ask questions over in one of the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We're keeping the issues section on GitHub for bugs and feature requests only, just to keep things a little more manageable.

I suggest you play around with your regular expression, this doesn't look like a LoopBack bug. Hopefully someone from the community will be able to help you out. I tried a couple variations and couldn't get a match. I'm sure they will be a regex expert somewhere.

Also... I assume you have already seen the docs on this [but just in case...](https://docs.strongloop.com/display/APIC/Where+filter#Wherefilter-Regularexpressions)
