### ISSUE TITLE
related model gets stored in parent

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback#2127]
If I do

```
const mdl = SomeModel.findById(id, {include: 'someRelatedModel'}).then(() => mdl.save())
```

the mdl contains `someRelatedModel` as a populated property in the database.

Storage is mongo, but that is irrelevant imo. I would assume these properties get stripped before save automatically. This is a bug, no?

**Comment by richardpringle** [comment]
Hey @Morriz, interesting find. I think you're right that the `someRelatedModel` should not get stored as well. @davidcheung, do you think this is something that model validation should take care of?

**Comment by Morriz** [comment]
IMO it is owned by the related-model functionality, and as such should be abstracted away and handled there, and not have such side effects....

**Comment by richardpringle** [comment]
related to strongloop/loopback#1972

**Comment by richardpringle** [comment]
@bajtos, it looks to me like there could be a design improvement here. As far as I know, the `save` function is not *aware* of any model relations, it just sees the added field as a property. 

I think that we could improve this beyond fixing these two issues, what do you think?

**Comment by bajtos** [comment]
@richardpringle I don't know enough about this part to answer your question. Could you elaborate a bit more on what kind of design improvements you would like to make? Or perhaps what parts of design are sub-optimal?

**Comment by richardpringle** [comment]
@bajtos, change the design so that the related model wouldn't be stored as well
