### ISSUE TITLE
[QUESTION] Overwriting error messages in default models

### ISSUE THREAD

**Issue by samgavinio** [strongloop/loopback#2129]
Loopback's User model by default can either work with emails or usernames for authentication. Most apps, I think will typically use one or the other. My app, for instance only uses email addresses. When a request for login is made and there is no provided email address I don't want to return 

```
{
  "error": {
    "message": "username or email is required",
   }
}
```

I just want to say to the client app that the `email is required`. Is there an easy way to accomplish this?

The error is of course returned from the following block of `models/user.js.`

```
if (!query.email && !query.username) {
      var err2 = new Error('username or email is required');
      err2.statusCode = 400;
      err2.code = 'USERNAME_EMAIL_REQUIRED';
      fn(err2);
      return fn.promise;
}
```

I want to overwrite that tiny message over there and I can't seem to find a documented way to do that. Seems like a trivial thing but I have several other use cases for this and I think it's pretty common. I hope I don't have to overwrite the entire login remote method just to replace one tiny message. If that's the only work around, I can't imagine how I can implement i18n for our APIs.

**Comment by richardpringle** [comment]
Hey @samgavinio, we're actually reserving the issues section of GitHub for bugs and feature requests. Please post any questions in one of the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

I am going to close this issue, but I will try to help you out anyway. Please mention me directly in any additional comments.

The best way to handle error is with middleware. Take a look at [the middleware documentation for more details](https://docs.strongloop.com/display/public/LB/Defining+middleware).

You can add your custom middleware function in a boot script or even in the server.js file like so:
```node
app.middleware('final', function(err, req, res, next) {...});
```
Here, the first argument of the `app.middleware` function is the *loopback-phase* "final". The second argument is the handler function. You should easily be able to change the middleware message to your liking.

Hope that helps!

Again, I'm closing the issue, but feel free to comment in here and mention me in the comment and I will still try to help you out.

**Comment by celicoo** [comment]
This solution doesn't work.

**Comment by richardpringle** [comment]
@superkhau, I think @celicoo can use [strong-error-handler](https://github.com/strongloop/strong-error-handler) instead of my solution right?

**Comment by loay** [comment]
Hi @samgavinio @celicoo 
Is this issue still persisting?
Thanks

**Comment by celicoo** [comment]
@loay I think so, i already dropped the loopback and i strongly recommend you to do the same. There are a lot of bugs, you can't overwrite a lot of behaviours. The worst framework i ever worked it.
