### ISSUE TITLE
Making where clause dynamic in model.json

### ISSUE THREAD

**Issue by nivincp** [strongloop/loopback#2130]
I have a product.json file with relation as follows

```
"scope": {
    "include": [
      {"relation":"langs", "scope":{"where":{"id_shop":5, "id_lang": 1}}}
    ]
  }
```

Now I want to make params id_shop and id_lang dynamic like a query string from api url endpoint
/api/products/9720?id_shop=2&id+lang=3

How can I achieve this?

**Comment by Neil-UWA** [comment]
what I can think of is that you can acheive this by using beforeRemotemethod hooks or operation hooks

**Comment by nivincp** [comment]
Thanks, I figured it out using an operation hook.
