### ISSUE TITLE
Failure with user.logout()

### ISSUE THREAD

**Issue by JonForest** [strongloop/loopback#2131]
The docs suggest that I should be able to call
`user.logout()` with a user instance
https://docs.strongloop.com/display/public/LB/Logging+in+users#Logginginusers-Loggingout

When I do this with

```
app.models.MyCustomUser.findById(userId, (err, user) => {
  // user is a valid ModelConstructor object
 user.logout() // fails with: TypeError: user.logout is not a function
})
```

This a documentation issue, or am I missing the point somehow?

**Comment by richardpringle** [comment]
Hey @JonForest, the *logout* method is a static method, meaning that it is a method that belongs to the *User Class* instead of a user instance. It mentions in the docs that you references what parameters to pass into the function. Here's a reference to the correct arguments to pass to the function: [API Docs - User.logout](https://apidocs.strongloop.com/loopback/#user-logout).

@crandmck, when was the last time the "Logging+in+users" page was updated? Seems a little weird that the page suggests setting up routes with `app.post(...)`, etc.

**Comment by JonForest** [comment]
Hi @richardpringle 
This is the example cut and pasted from the docs:
```
// logout a user (server side only)
User.findOne({email: 'foo@bar.com'}, function(err, user) {
  user.logout();
});
```
That doesn't look to me like a static method, but I confess, I'm not sure what the sentence before-hand actually implies (`To logout user from the server side:`)

I was actually trying to log a user out remotely via an api call, where I don't have a user context other than an API call.  So therefore need to actually run the logout a specific user instance.  Getting hold of the accessToken is not particularly straight-forward from this position either.
Would be good to know if this is possible.

**Comment by richardpringle** [comment]
@JonForest, I think that doc page is an old one. `logout` is definitely a static method now. You can see it in the *LoopBack-component-explorer*.

So this example could help: [LoopBack-example-user-management](https://github.com/strongloop/loopback-example-user-management)

Again, it might be a little dated... (sorry!). 

So you can't log a user out without the access token, which makes sense, or else anyone that hit the api could log out the user. To get the access token in the first place, you have to hit `POST /api/Users/login` passing in a user instance, for example:
```json
{"email": "myemail@strongloop.com", "password": "somePasword"}
```
The response body will contain an `accessToken` object. From there to access any api endpoints that require the user to be authenticated, you will have to pass the `accessToken.id` as a query parameter. For example: `POST /api/Users/logout?access_token=2wvYn62Slm4CCH6KGh5CXJpn6CO6TpxGxbhafcuBADuPhSCVy6IgqKBNrNJXc1ei`

Hope that helps! We'll try and get those docs updated ASAP.

**Comment by JonForest** [comment]
Yeah, it does make sense.  Thanks for your help.
