### ISSUE TITLE
Native Node Promise methods are not available (Promise.all, Promise.race, etc)

### ISSUE THREAD

**Issue by jbcpollak** [strongloop/loopback#2132]
I am getting errors trying `Promise.all` and `Promise.race`. I am using Node 5.7.1, where the ES6 Promise API is fully implemented. I think something is playing with the global Promise object, because `Promise.all` works fine in test code that doesn't require loopback. For example the following code works fine when you drop it into `test.js` and run `node test.js`:

```
var fulfills = Promise.all([
    new Promise(function(resolve)   { setTimeout(resolve,200,"foo"); }),
    new Promise(function(resolve)   { setTimeout(resolve,100,"bar"); }),
]).then(values => {
    console.log(values)
});
```

But when you put it into a model's remote method, you get this:

```
Error:  TypeError: Promise.all is not a function
    at Function.all (native)
```

I get similar errors with Promise.race:

```
Error:  TypeError: Promise.race is not a function
    at Function.race (native)
```

I thought this might be a problem with `async-listener`, but I put a breakpoint just after it finished wrapping the promise object and injected the above code into the debug console, and it logged the correct output.

I suspect something that is require()'d after async-listener is manipulating the Promise object, but I can't find it.

**Comment by rawrmaan** [comment]
It may be `newrelic`--that was causing Promise issues for me.

**Comment by jbcpollak** [comment]
I don't have newrelic installed, although I do think it could be some other dependency interacting with loopback.

**Comment by jannyHou** [comment]
@jbcpollak in loopback3.0, we always use bluebird as the promise library, please check out doc to see more details: 
https://github.com/strongloop/loopback/blob/master/3.0-RELEASE-NOTES.md#always-use-bluebird-as-promise-library

**Comment by jbcpollak** [comment]
I saw that. As long as loopback doesn't override the global Promise implementation, I am happy. I think you can close this issue. I am not actually sure that Loopback was causing this problem for me, but it seemed the most likely culprit.
