### ISSUE TITLE
How to get affected attributes of persisted model?

### ISSUE THREAD

**Issue by technova** [strongloop/loopback#2144]
Could not find any documentation around it. Basically I need to find changed attribute/values in after save hook. 

For example: model is created with {name: "something", description:"something else"}

When I update this model with {name: "something", description:"**something something** else"}

I need to find affected attributes, in my example this is only  **"description"**

Note: I am using mongo connector.

Please suggest.

**Comment by richardpringle** [comment]
Hey @technova, we support exactly what you want to do! Unfortunately, I could not find any documentation references in the regular docs. 

Luckily, we have the API docs as well. It's always a good idea to take a look in there and see if you can spot a method name that sounds like it will do what you want.

Check out the first few methods that are listed on the [PersistedModel Class](https://apidocs.strongloop.com/loopback/#persistedmodel). There is one method called `checkpoint` and another method called `changes`. Unfortunately, the documentation is not complete but you should just be able to set a checkpoint before-save then check for changes after save. If you want to take a look how the code is actually implemented you can take a look [here](https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L849). 

Let me know if that helps. The the meantime I will throw a `doc` label on this issue and leave it open until it can get fixed.

**Comment by noderat** [comment]
Ah, well I'm glad I stumbled upon this. I had glazed over those in the API docs before and put that task in my project on hold. Documentation in confluence would be great!

**Comment by superkhau** [comment]
@richardpringle Are you planning to ping @crandmck and reassign to him? I'm assuming he needs instructions on how to write up the docs (ie. example/description from engineering), are you going to provide it for him?

**Comment by crandmck** [comment]
Yes, please provide details and example @richardpringle ... Thanks!

**Comment by richardpringle** [comment]
Sorry, didn't mean to just leave you hanging @crandmck!

Either @bajtos or @ritch would do a better job than me, I've never actually used it.

**Comment by bajtos** [comment]
> Basically I need to find changed attribute/values in after save hook. 
> For example: model is created with {name: "something", description:"something else"}
> When I update this model with {name: "something", description:"something something else"}
> I need to find affected attributes, in my example this is only "description"

I am afraid we don't support this feature. IIRC, one of the reasons is that detection of changed attributes has non-negligible performance overhead. It is also difficult to implement in a way that would work correctly when multiple clients are modifying the same record at the same time.

**Comment by bajtos** [comment]
Changes and checkpoints are used by change-replication (offline sync) algorithm. They work on model-instance level by comparing checksum of canonical JSON representation of the model instance in question, they don't distinguish individual model properties.

**Comment by bajtos** [comment]
Having wrote all above, if you are using `prototype.updateAttributes()` to make the changes, and can change the client to send only the modified properties in the `data` argument, then the following code should work for you:

```js
MyModel.observe('before save', function(ctx, next) {
  if (ctx.data) ctx.hookState.updateData = ctx.data;
  next();
});

MyModel.observe('after save', function(ctx, next) {
  if (ctx.hookState.updateData) {
    console.log('Detected partial update of the following properties', Object.keys(ctx.hookState.updateData));
  } else {
    console.log('Full save was performed, we don\'t know which properties were changes.');
  }
  next();
});
```

Your example update should be performed with the following data - notice that `name` is excluded from the data because it's not supposed to change:

```json
{
  "description":"something something else"
}
```

**Comment by technova** [comment]
Thanks @bajtos . This code has dependency on client who is sending data. But still this works for me.

**Comment by bajtos** [comment]
@technova cool, I am glad my solution works for you. In which case I think we can close this issue now.

**Comment by boyd4y** [comment]
@bajtos  is there any general way to compare the changes in hook?  since in my case, i do have a lot of logic to do like this:
modelInstance.field = xx,
modelInstance.save();

Looks like your proposal only work for UpdateAttributes.

**Comment by bajtos** [comment]
@boyd4y I don't think so. Can you rewrite your code to call `modelInstance.updateAttribute('field', 'xx')` instead?

**Comment by jbcpollak** [comment]
is there any update on this? As a generalized feature it would be very helpful. Using `updateAttribute()` is not always practical. Currently I'm considering fetching the current state of the object in `before save` and then checking for the differences in `after save`, but this is not ideal

**Comment by bajtos** [comment]
@jbcpollak 

> Is there any update on this? As a generalized feature it would be very helpful.

No update. I am not aware of any solution that would be  better than what you have described:

> Currently I'm considering fetching the current state of the object in `before save` and then checking for the differences in `after save`, but this is not ideal

**Comment by mrfelton** [comment]
We wrote the Changed mixin to provide a generalised way to accomplish this:

https://github.com/fullcube/loopback-ds-changed-mixin

**Comment by crandmck** [comment]
Cool... 

@mrfelton Would you be interested and willing to add this project to http://loopback.io/doc/en/community/index.html ?  It should be simple to do (see http://loopback.io/doc/en/community/How-to-add-a-project.html).... I can help, too, if needed.
