### ISSUE TITLE
Can not get accessToken from req object !

### ISSUE THREAD

**Issue by luckymancvp** [strongloop/loopback#2147]
I have some projects used sailjs, and I saw that loopback is very interesing. I created a simple app , and want to get current user login . But I can not get accesstoken from req object. I dont know why

Please help me !!

My repo : https://github.com/luckymancvp/stroongloop-app/blob/master/server/server.js#L14
Reference: https://docs.strongloop.com/display/public/LB/Using+current+context

**Comment by luckymancvp** [comment]
My friend helped me figured it out . Thank you

**Comment by shuhankuang** [comment]
@luckymancvp 
Hi, I can't get the req.accessToken too, 
can you please tell me the solution? thx.
