### ISSUE TITLE
findOrCreate

### ISSUE THREAD

**Issue by yahoohung** [strongloop/loopback#2148]
I have a interesting problem on loopback. It displayed wrong result when I was adding records with findOrCreate. Let's see the example.

```
for (var x = 0; x < 10; x++) {
    var Log = app.models.Log;
    Log.findOrCreate({
      where: {
        modelName: '123'
      }
    }, {
      modelName: '123'
    }, function(err, log) {});
  }
```

I think it should be create 1 record with modelName '123' only, but I got 10 finally.

Is there something wrong? Thanks.

**Comment by superkhau** [comment]
Can you provide a sample repo so we can reproduce this issue on our end?

**Comment by Amir-61** [comment]
@yahoohung You need to to use (ASYNC)[https://github.com/caolan/async] to iterate; a simple `for loop` is not going to work properly for `findOrCreate` which is async. Please see the examples [here](https://github.com/caolan/async) to see how you can use them.

Thanks!

**Comment by superkhau** [comment]
@yahoohung What are you trying to do in that example? Why are you looping x times and not using x at all? Please clarify.

**Comment by superkhau** [comment]
@yahoohung You there?

**Comment by yahoohung** [comment]
Yes. Thanks for quick response. I have fixed the problem with async and step module.

**Comment by lortega** [comment]
@yahoohung it's not a problem. LoopBack works on Node, and Node is non-blocking, which means that it sends messages to objects but doesn't wait for them to answer. If you wan't something to be done synchronous, you have to use some library like async or use callbacks.
