### ISSUE TITLE
Remote hooks of relation methods for edit request does not make sense.

### ISSUE THREAD

**Issue by Emiya0306** [strongloop/loopback#2150]
```javascript
module.exports = function(App) {
    /**
     * Remote Hook
     */
    App.beforeRemote('*.__create__roles', beforeRemoteCreateRole);

    function beforeRemoteCreateRole (context, data, next) {
        var req = context.req;
        req.body.name = req.params.id + '_' + req.body.name;
        console.dir(req.body);
        next();
  }
}
```

1. When I execute "/api/apps/56e29af2b9e2285b3792a7d7/roles" and server end edit the request.body successfully. Just like "56e29af2b9e2285b3792a7d7_RoleName", but the data in database is just "RoleName". 
Does remote hooks of relation methods have any special operations?

2. The second question is How can ACLs apply into different model instances? Just like the model "Bank", and I will create many "banks", maybe "Bank1", "Bank2". And they have many different role ACLs, so how can I define ACLs to apply different banks? The roles can also apply into different banks is better.

3. ~~Another question that ACL $owner role is only used in BelongsTo relation, it cannot be used in hasAndBelongsToMany relation, is right?~~

4. How can I add the translation work for loopback? 

> To qualify a $owner, the target model needs to have a belongsTo relation to the User model (or a model extends from User) and property matching the foreign key of the target model instance. The check for $owner is only performed for a remote method that has ':id' on the path, for example, GET /api/users/:id.

__The question 3 is solved, it can make sense on hasAndBelongsToMany relation.__

**Comment by Neil-UWA** [comment]
try this for question 1:
```
    function beforeRemoteCreateRole (context, data, next) {
        var req = context.req;
        context.args.data.name = req.params.id + '_' + req.body.name;
        next();
  }
```

**Comment by richardpringle** [comment]
@Emiya0306 What do you mean by
>How can I add the translation work for loopback?

Are you talking about the [translation of documentation](https://docs.strongloop.com/display/public/LB/Translating+documentation)?

Did @Neil-UWA's solution work?

As for applying an ACL to a specific model instance, this is not something that is supported. What you might be able to do is [partition your users into realms](https://docs.strongloop.com/display/public/LB/Partitioning+users+with+realms) and create a different realm for each bank account.

Does that make sense?

**Comment by Emiya0306** [comment]
@Neil-UWA Sorry for late reply about the issue, I'm current on weekend. And your solution works well on my question. It's very cool, thanks! But I'm little confused about why to use __context.args.data__ to edit the data, because of the relation model?

@richardpringle Yeah~ I saw the "Contributing to LoopBack documentation", and I will mail for the translation after finishing my project. 

> As for applying an ACL to a specific model instance, this is not something that is supported.

I'm a little pity for this. But the __realm__ is a good idea on user management, I will try it at once!
For ACL, I have a optional solution can be chosen. I think it can work well, but is not the best. Because the role name is unique(bankId_roleName) among bank instances. Every ACL only works on the special bank, by {principalType: "ROLE", principalId: bankId_roleName}.

For another question about PersistedModel promise. Link is here [Support promises](https://github.com/strongloop/loopback/issues/418#issue-38984704) and the last reply.

In a short about the question is:
PersistedModel.create() return the results which lose all __proto__ during the promise chain(just a json object). That means I can not get the relation model method during promise chain.
But it woks well, between on different datasource.
I has locked the location in "loopback-datasource-juggler/lib/dao.js" 
```
DataAccessObject.create = function (data, options, cb) {
  // a lot of code......

  // for chaining
  return cb.promise || obj;
};
```
Thanks! :smile:

**Comment by Emiya0306** [comment]
```javascript
var loopback = require('loopback');
var RoleMapping = loopback.RoleMapping;

module.exports = function (server) {
  var app = server.models.app;
  var user = server.models.user;

  var userData = [{
    email: "aaa@aaa.aaa",
    username: "aaa",
    password: "aaa"
  }, {
    email: "bbb@bbb.bbb",
    username: "bbb",
    password: "bbb"
  }];

  var appData = [{
    name: "app1"
  }, {
    name: "app2"
  }];

  var roleData = [{
    name: "role1"
  }, {
    name: "role2"
  }];

  var results = {};

  Promise.all([
      user.create(userData),
      app.create(appData)
    ])
    .then(function (result) {
      // promise get all results
      results.users = result[0];
      results.apps = result[1];

      // create roles of app1
      return results.apps[0].roles.create(roleData)
    })
    .then(function (result) {
      results.roles = result;
      // assign the "role1" to user "aaa"
      return results.roles[0].principals.add([
        {
          principalType: RoleMapping.USER,
          principalId: results.users[0].id
        }
      ]);
    })
    .then(function (roleMappings) {
      console.log(roleMappings);
    })
    .catch(function (err) {
      console.log(err);
    });
};
```

@Neil-UWA Sorry, the promise problem I cannot solve, results.roles[0].principals is undefined. T^T

**Comment by richardpringle** [comment]
@Emiya0306, what is this `app.create` function you are using?

**Comment by Emiya0306** [comment]
@richardpringle , app is the PersistedModel and app.create() is PersistedModel.create(). I think it is from loopback-datasource-juggler/lib/dao.js.

**Comment by richardpringle** [comment]
I believe it should look something like this:
```node
  Promise.all([
      new Promise(user.create(userData)),
      new Promise(app.create(appData))
    ])
    .then(function (result) {...
```

**Comment by Emiya0306** [comment]
Sorry for long time no reply. When I use Promise.all(), new Promise cannot get relation model as well, it just the data. app.users.add() cannot get.

**Comment by Emiya0306** [comment]
Look this [issue](https://github.com/strongloop/loopback/issues/2164#issuecomment-215645590).
