### ISSUE TITLE
No documentation on how to modularize really large applications?

### ISSUE THREAD

**Issue by PaddyMann** [strongloop/loopback#2158]
I'm new to Loopback, so sorry if I've missed something. 

I can't find anything in the documentation about how to split your (very large) application into smaller modules. Do you have any links / guidance / best practices etc. that you can share?

**Comment by richardpringle** [comment]
Hey @PaddyMann, the best place to ask questions is actually on our [Google Groups page](https://groups.google.com/forum/#!forum/loopbackjs). We're reserving the issues section on GitHub for bugs and feature requests, just to make things a little more manageable. 

I'm going to close this issue, but I'm still curious, maybe you could post in the Google Group with a little more detail and share the link here.

Cheers!

**Comment by PaddyMann** [comment]
@richardpringle ok - thanks for the advice. I've posted on the Google Group!

Should I get some good answers, I'll raise a new issue as I think this information should be added to the docs. (or let me know if there's another process I should follow to make this kind of request)

**Comment by richardpringle** [comment]
Yeah just open a new issue if you get a clear (and detailed) idea of what you are looking for in terms of docs and open up a new issue. You are welcome to mention me directly too.
