### ISSUE TITLE
Modifications of embedded models are not saved in database

### ISSUE THREAD

**Issue by Nautigsam** [strongloop/loopback#2162]
Hello, I made a sample repo of a supposed bug I am experiencing. Am I doing something wrong?
Here is the link: https://github.com/Nautigsam/loopback-embed-test

**Comment by richardpringle** [comment]
Hey @Nautigsam, thanks for posting the sample repo!

I observed some pretty strange behavior and I didn't see anything wrong with your code. When using `PUT api/Books/{id}/cover`, the `Book` instance is updated with the new cover but it does not persist to the `Pages` model. 

Definitely a bug, thanks for catching it!
