### ISSUE TITLE
Simple ACL problem

### ISSUE THREAD

**Issue by romainquellec** [strongloop/loopback#2163]
I'm currently adding some ACL to my application.

FYI, I overdrove User with Utilisateur with this code : 
`  "name": "Utilisateur",
  "base": "User",`

Just for trying, I just add some widely open ACL to "Utilisateur"

`"acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    }`

This doesn't work. I Still can't access Utilisateur instance.

`"statusCode": 401,
    "code": "AUTHORIZATION_REQUIRED",`

**Comment by romainquellec** [comment]
With : DEBUG=loopback:security:* node .

` loopback:security:role isInRole(): $everyone +45s
  loopback:security:access-context ---AccessContext--- +0ms
  loopback:security:access-context principals: [] +0ms
  loopback:security:access-context modelName Utilisateur +0ms
  loopback:security:access-context modelId 1 +0ms
  loopback:security:access-context property findById +0ms
  loopback:security:access-context method findById +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "$anonymous" +0ms
  loopback:security:access-context   ttl 1209600 +1ms
  loopback:security:access-context getUserId() null +0ms
  loopback:security:access-context isAuthenticated() false +0ms
  loopback:security:role Custom resolver found for role $everyone +0ms
  loopback:security:role isInRole(): $owner +0ms
  loopback:security:access-context ---AccessContext--- +0ms
  loopback:security:access-context principals: [] +0ms
  loopback:security:access-context modelName Utilisateur +0ms
  loopback:security:access-context modelId 1 +0ms
  loopback:security:access-context property findById +0ms
  loopback:security:access-context method findById +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "$anonymous" +0ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context getUserId() null +0ms
  loopback:security:access-context isAuthenticated() false +0ms
  loopback:security:role Custom resolver found for role $owner +0ms
  loopback:security:role isOwner(): Utilisateur 1 userId: null +0ms
  loopback:security:role isInRole(): $everyone +0ms
  loopback:security:access-context ---AccessContext--- +0ms
  loopback:security:access-context principals: [] +1ms
  loopback:security:access-context modelName Utilisateur +0ms
  loopback:security:access-context modelId 1 +0ms
  loopback:security:access-context property findById +0ms
  loopback:security:access-context method findById +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context accessToken: +0ms
  loopback:security:access-context   id "$anonymous" +0ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context getUserId() null +1ms
  loopback:security:access-context isAuthenticated() false +0ms
  loopback:security:role Custom resolver found for role $everyone +0ms
  loopback:security:acl The following ACLs were searched:  +1ms
  loopback:security:acl ---ACL--- +0ms
  loopback:security:acl model Utilisateur +0ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +1ms
  loopback:security:acl principalId $everyone +0ms
  loopback:security:acl accessType * +0ms
  loopback:security:acl permission DENY +0ms
  loopback:security:acl with score: +1ms 7495
  loopback:security:acl ---ACL--- +1ms
  loopback:security:acl model Utilisateur +1ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +1ms
  loopback:security:acl principalId $everyone +0ms
  loopback:security:acl accessType * +1ms
  loopback:security:acl permission ALLOW +0ms
  loopback:security:acl with score: +0ms 7492
  loopback:security:acl ---Resolved--- +0ms
  loopback:security:access-context ---AccessRequest--- +1ms
  loopback:security:access-context  model Utilisateur +0ms
  loopback:security:access-context  property findById +0ms
  loopback:security:access-context  accessType READ +1ms
  loopback:security:access-context  permission DENY +0ms
  loopback:security:access-context  isWildcard() false +0ms
  loopback:security:access-context  isAllowed() false +0ms`

**Comment by romainquellec** [comment]
For now, my fix is very wrong : I change the default ACL of User in loopback.

Everyone, do not do this !

**Comment by jannyHou** [comment]
@romainquellec glad to know that you figure out the right way to set ACL!
I tried to create a new user called `myuser` extending `User` model, and set ACL on it, the entire myuser.json file is:
```
{
  "name": "myuser",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```

endpoint `GET myusers/` is public to everyone.

**Comment by romainquellec** [comment]
Ok. I reversed my change and update the loopback.
Apparently, it's been fix since my last update.
