### ISSUE TITLE
Pagination in API loopback

### ISSUE THREAD

**Issue by hoangtrongphuc** [strongloop/loopback#2166]
Loopback auto create API function, but I can't not see pagination of Model with thousand record. Please add this feature.

**Comment by caffeinewriter** [comment]
You should look into the [limit](https://docs.strongloop.com/display/public/LB/Limit+filter) and [skip](https://docs.strongloop.com/display/public/LB/Skip+filter) filters.

E.g.

`/api/Test?filter[limit]=10&filter[skip]=0`
`/api/Test?filter[limit]=10&filter[skip]=10`
`/api/Test?filter[limit]=10&filter[skip]=20`

That would be 3 pages, each with 10 records.

There's actually a pagination example on the skip filter documentation page I linked above.

**Comment by MarcDiethelm** [comment]
For future refence here's an official blog post.
https://strongloop.com/strongblog/working-with-pagination-and-loopback/
