### ISSUE TITLE
Password Reset Token in the loopback.token() middleware should have a method to immediately invalidate tokens

### ISSUE THREAD

**Issue by caffeinewriter** [strongloop/loopback#2168]
Currently, when using access tokens for password resets, they remain valid even after they reset is performed, and can be reused up until the configured TTL is reached. It should be possible to immediately invalidate the token, particularly for password reset situations. It may not prove an issue with a sufficiently small TTL, but it's still something that should be addressed. 

For example:

``` javascript
app.post('/reset-password', function(req, res, next) {
    if (!req.accessToken) return res.sendStatus(401);

    if (!req.body.password
      || !req.body.confirmation
      || req.body.password !== req.body.confirmation) {
      return res.sendStatus(400, new Error('Passwords do not match'));
    }

    Users.findById(req.accessToken.userId, function (err,user) {
      if (!!err) {
        return res.sendStatus(500);
      }
      user.updateAttribute('password', req.body.password, function (err, user) {
        if (!!err) {
          return res.sendStatus(500);
        }
        // New functionality proposal: Invalidate access token
        req.accessToken.invalidate();
        return res.sendStatus(204);
      });
    });
});
```

**Comment by Morriz** [comment]
+1

**Comment by tomcooksey** [comment]
There is already a way to do this!  Just call the logout method on the user:

`User.logout(req.accessToken.id, function(err) {
                    res.send('Success');
                });`

**Comment by superkhau** [comment]
Does @tomcooksey solution work for you guys?

**Comment by caffeinewriter** [comment]
@superkhau I think that should work. Haven't had a chance to test it, but it seems like a workable solution.

**Comment by superkhau** [comment]
@caffeinewriter Can you confirm and report back? I will leave this issue open till then.
