### ISSUE TITLE
Problem resolving module path in electron runtime environment

### ISSUE THREAD

**Issue by s-a** [strongloop/loopback#2169]
Does loopback support electron runtime environment?

Some users reported problems while resolving module paths of loopback in electron runtime environment. I Tried to reproduce at...

ref: 
- https://github.com/s-a/iron-node/issues/96
- https://github.com/s-a/iron-node/issues/99

**Comment by richardpringle** [comment]
@s-a, we don't officially support the electron environment at this time, but I will leave this issue open for discussion for now. We would probably need to see a high demand to be able to officially support. 

@bajtos, what do you think? Leave this issue open for discussion?

@s-a, our priorities right now are working on new features and cleaning up this large backlog of bugs.

**Comment by bajtos** [comment]
> what do you think? Leave this issue open for discussion?

Sure, let's keep it open for now.

@s-a yes, Electron environment is not a priority for us right now. I don't mind landing a patch that will fix loopback for Electron as long as the change won't increase our maintenance costs, but we don't have bandwidth to investigate issues like this ourselves.
