### ISSUE TITLE
'this' in model instance method is strange.

### ISSUE THREAD

**Issue by samzhao2008** [strongloop/loopback#2171]
Hi, I recently use loopback to build an application, I found that this in MyModel.prototype.mymethod is not an instance of MyModel.

```js
module.exports = function (Video) {
  Video.prototype.submitTranscodeJob = function () {
       console.log(this instanceof Video) //it returns false when I have a video instance fetch from find method and called video.submitTranscodeJob().
};
```

This behavior breaks my knowledge about the PersistedModel and it takes me hours to figure out the reason. Because of the strange phenomenon, I can not call updateAttributes instance method of PersistedModel either by this.updateAttributes(params) or  Video.prototype.updateAttributes.call(this, params). Can anyone explain a little bit so that I can gain some knowledge about the framework?

**Comment by Amir-61** [comment]
Hey @samzhao2008,

Where are you adding this code? Is it in your model.js which probbaly is called `video.js`. To make triage process clear could you please provide a sample repo using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox)?

Thanks!

**Comment by samzhao2008** [comment]
Sorry, I made a mistake in my code. When I corrected it, no such a problem. Thanks

**Comment by penguinpowernz** [comment]
@samzhao2008 please can you detail the mistake that you made in your code so that others can learn from that mistake?
