### ISSUE TITLE
Best way of updating multiple Model instances

### ISSUE THREAD

**Issue by cipriancaba** [strongloop/loopback#2172]
I want to update some attributes for the instances returned by a `Model.find` query

What is the best way to achieve this? I've had a look over `createUpdates`, `bulkUpdate`, `updateAll` but these don't seem to do what I want..

Basically each of the models would need to be appended a value for a `prices` property, so if `Product.prices = [100]` before the update, after the update it will be `Product.prices = [100, newPrice]`

Datasource is postgres

Thanks

**Comment by Amir-61** [comment]
Hi @cipriancaba,

>I've had a look over createUpdates, bulkUpdate, updateAll but these don't seem to do what I want..
`createUpdate` and `bulkUpdate` were designed for change replication; the naive solution would be iterating through the result returned from `Model.find` and update them or alternatively I believe [updateAll](http://apidocs.strongloop.com/loopback/#persistedmodel-updateall) should work for you as well. If not, you should reproduce the issue by our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and we do recommend you ask this kind of questions in our [Google group](https://groups.google.com/forum/#!forum/loopbackjs) to get quicker response.

Thanks a lot!

**Comment by cipriancaba** [comment]
Thank you for your update.. I will move the question to the google group to avoid spamming the issues..

Best
