### ISSUE TITLE
Spike: improve handling of swagger spec when developing LB app in API Connect

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2175]
Make it easy for users to make changes both in LoopBack source code and in the generated swagger document in such way that changes made in both places are preserved.

**Comment by bajtos** [comment]
A suggestion from @raymondfeng - a flag to tell swagger generator to merge the output with the current swagger spec, instead of replacing the content.

**Comment by loay** [comment]
- validate the yaml file. 
- `config:set` the default properties in memory, then merge the output with current specifications.

**Comment by loay** [comment]
Taking for example an operation such as `create`. 
```apic create --type model:```
- The first model that is created will be generated in the swagger file. Assume it is name is `swagger1` and has the following data. 

```      var productData1 = {
        title1: projectInfo.name,
        filename1: productFilePath,
        apis1: apis,
      };
```

The next output must be captured in either memory or a JSON file that will capture all the output.
```      var productData2= {
        title2: projectInfo.name,
        filename2: productFilePath,
        apis2: apis,
      };
```
- A scan for duplicated to be done first. 
- Merge the info into the swagger file. No overriding should happen as a naming convention should be given to the output in order to avoid conflict. 

- rm -rf the JSON file created that captured the 2nd output before merging.

**Comment by loay** [comment]
I don't think the current code overrides for some operations, but it actually merges. I need to double check to make sure that it is true.

**Comment by loay** [comment]
it looks like it does updsate the swagger as it is in a comment by Krishna here:
https://github.ibm.com/apimesh/scrum-platform-foundation/issues/77#issuecomment-59264
but that looks like it is only for only creation. I will have to double check with Krishna and Ivy

**Comment by loay** [comment]
Apparently it does not merge. In the above mentioned bug, the swagger was not being generated at all. The feature of merging is not being implemented yet. 
@bajtos Please have a look at the proposal above. Thanks.

**Comment by bajtos** [comment]
@loay I am afraid I don't understand what you are proposing in https://github.com/strongloop/loopback/issues/2175#issuecomment-214966963.

Consider the following use scenario:
 1. Create a new LoopBack app using `apic loopback`
 2. Open the project in GUI - `apic edit`
 3. Make some changes that are persisted in the swagger yaml file, e.g. edit "Info>Title", "Info>Name", configure security, etc. This should add various `x-ibm-*` configuration into the swagger file.
 4. Close GUI, switch back to CLI
 5. Add a model via `apic create --type model`

My understanding is that last step above would drop any changes made in the GUI editor. What we want instead is to preserve the changes made in the editor and intelligently merge them with the changes made via CLI.

I don't have the latest version of APIC editor at hand. If it's possible to add new models from the GUI, then I expect there will be the same problem (non-loopback parts of swagger are dropped) and we need to fix it as part of this work too.

Now back to your proposal.

> for validating can you use the apic toolkit (i.e. apic validate <yaml_file_path>)

Sure, validation was not a part of this story.

> Taking for example an operation such as create.  `apic create --type model`
> The first model that is created will be generated in the swagger file. Assume it is name is swagger1 and has the following data.

AFAIK, there is only one swagger file relevant to this discussion, and that's `definitions/<project-name>.yaml`.

---

It looks that https://github.ibm.com/apimesh/apiconnect-cli-loopback/pull/7 has already implemented support for merging old & new swagger when updating, see https://github.ibm.com/apimesh/apiconnect-cli-loopback/blob/e849463415b75b261680a3640c5fb7d0f12c697b/lib/swagger.js#L76-L78

---

> Make it easy for users to make changes both in LoopBack source code and in the generated swagger document in such way that changes made in both places are preserved.

@kraman @ritch AFAICT, this has been already fixed in `apic` a no more work is required at our side. Could you please confirm?

**Comment by loay** [comment]
I think it is already been implemented. I tested myself. Also, I asked the QA team to double check. 
The `apic create --type model` doesn't drop any changes made in the GUI editor. 
@bajtos @raymondfeng I think we can close this one.

**Comment by bajtos** [comment]
Sounds good, I am closing this issue as done then.
