### ISSUE TITLE
Support for MySQL unsigned

### ISSUE THREAD

**Issue by PaddyMann** [strongloop/loopback#2179]
I can't see anyway to make an unsigned field in MySQL (based on the docs here: https://docs.strongloop.com/display/public/LB/MySQL+connector ).

Would be great to add support

**Comment by jannyHou** [comment]
@PaddyMann I think we support `UNSIGNED` option, see:
https://github.com/strongloop/loopback-connector-mysql/blob/b27d1ce32fc937108dbb1c61e7b681df807e35fb/lib/migration.js#L568

And see how to use `unsigned` from this test case: https://github.com/strongloop/loopback-connector-mysql/blob/b27d1ce32fc937108dbb1c61e7b681df807e35fb/test/migration.test.js#L242

**Comment by PaddyMann** [comment]
Great - thank you. Could have sworn I had tried doing it as shown in the test case without luck, but appears to work :)
