### ISSUE TITLE
way to configure HTTPS that doesn't involve writing javascript

### ISSUE THREAD

**Issue by sam-github** [strongloop/loopback#2182]
Currently, there is only a way to **implement** HTTPS, see https://docs.strongloop.com/display/LB/Preparing+for+deployment and https://github.com/strongloop/loopback-example-ssl#load-the-ssl-certificate

I expected to find that there were some json config files that the HTTPS options needed to be added into.

This is not friendly for tools, such as `apic`, that may wish to configure an app to use HTTPS without spitting javascript onto disk.

It also makes it impossible to easily **post-deploy** convert an HTTPS application to an HTTP application, or vice-versa.

What I'm hoping for is not only json config files, but _also_ environment based configuration, so that the configuration for HTTPS can be applied at boot time via environment. This may interact with https://github.com/strongloop/loopback-boot/issues/93

/to @bajtos @kraman @raymondfeng 
/cc @jgeddes2001

**Comment by bajtos** [comment]
:+1: 

Rant: this is partially a problem of Node.js core API, because it does not provide a unified HTTP/HTTPS API where switching between secure/unsecure could be done by configuration.

When it comes to HTTP clients, [request](https://www.npmjs.com/package/request) does a nice job of abstracting two different core APIs away.

For LoopBack, I am proposing to do something similar and use a module that can abstract the differences between core APIs away too. Either find one on npmjs.org, or write a new one.

Thoughts?

**Comment by sam-github** [comment]
However its done internally, either a simple conditional, or an abstraction over node core, doesn't much matter to me, as long as I can provide the information using environment variables.

**Comment by gunjpan** [comment]
Outcome of spike:
A solution on achieving this task:

- [ ] update LB generator: `slc loopback` to include option for enabling `SSL`
  - [ ] sub task: implement a new generator `slc loopback:enable-ssl` and this can be invoked during scaffolding as well.
- [ ] modify `app.listen()`(see [loopback/lib/application.js](https://github.com/strongloop/loopback/blob/69f7f0941f28f11613993ffa62f0bf91a9e23ae8/lib/application.js#L541-L586)) to support ssl option from `server/config.json`
- [ ] enable [`hsts`](https://github.com/helmetjs/hsts) middleware - by helmetjs -  for adding `Strict-Transport-Security` header to the response. ( we can agree upon what should be the default `maxAge` for telling browsers to visit by HTTPS for the next `maxAge` duration)
- [ ] update related example and docs

**Comment by sam-github** [comment]
@cgole @kjdelisle What is current place of this in backlog?

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be adding any new features.
