### ISSUE TITLE
Docs issue: "Using the datatype field/column option with MySQL" incorrectly shows to use "mysql" parameter

### ISSUE THREAD

**Issue by PaddyMann** [strongloop/loopback#2183]
Page: https://docs.strongloop.com/display/public/LB/MySQL+connector
Section: "Using the datatype field/column option with MySQL"

Issue:

Example shows to use the mysql parameter, but I've found this doesn't work and the settings should be attached at the level above.

So

    locationId":{
        "type":"String",
        "required":true,
        "length":20,
        "mysql":
        {
            "columnName":"LOCATION_ID",
            "dataType":"VARCHAR2",
            "dataLength":20,
            "nullable":"N"
        }
    }

Should be

    locationId":{
        "type":"String",
        "required":true,
        "length":20,
        "columnName":"LOCATION_ID",
        "dataType":"VARCHAR2",
        "dataLength":20,
        "nullable":"N"
    }

**Comment by Amir-61** [comment]
@crandmck PTAL ^

**Comment by Amir-61** [comment]
@PaddyMann,
I just followed documentation for `Using the datatype field/column option with MySQL` and it worked fine for me when I pass a `mysql` object like:

```
"locationId":{
    "type":"String",
    "required":true,
    "length":20,
    "mysql":
    {
        "columnName":"LOCATION_ID",
        ...
    }
}
```

If it does not work for you, please reproduce the issue using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox).

Thanks!

**Comment by Amir-61** [comment]
I'm closing this ticket now...Please feel free to reopen or create a new issue if it does not work for you...

Thanks!
