### ISSUE TITLE
dataType has no effect for primary key field

### ISSUE THREAD

**Issue by PaddyMann** [strongloop/loopback#2184]
If I have a model configured with an `id` field and a specific `dataType`, e.g.:

    {
      ...
      "idInjection": false,
      ...
      "properties": {
        "id": {
          "type": "number",
          "id": true,
          "dataType": "smallInt",
          "unsigned": true,
          "generated": true
        },
       ...

Then the `dataType` is (incorrectly) ignored and the id field is created as an `int` rather than a `smallint`. 

If I remove `"id": true` and auto-update, then the dataType gets set correctly.

Oddly, if I then re-add `"id": true`, the dataType doesn't revert back to it's incorrect state.

**Comment by gunjpan** [comment]
@PaddyMann: Could you please let me know what database you're using.
Besides that, I would recommend having a look at: [How properties can be mapped to database column](https://docs.strongloop.com/display/APIC/Model+definition+JSON+file#ModeldefinitionJSONfile-Datamappingproperties) when using relational database.

Please let me know if `mapping property` works for you. If it doesn't, a sample repo to reproduce the issue will be helpful.

And, knowing [how `id` property works in LoopBack](https://docs.strongloop.com/display/APIC/Model+definition+JSON+file#ModeldefinitionJSONfile-IDproperties) will be helpful as well.

Thank you.

**Comment by gunjpan** [comment]
@PaddyMann : hi, did the mapping work for you?

**Comment by PaddyMann** [comment]
Hi @gunjpan 

Sorry, I was off sick and lost track of this issue. I'm using MySQL.

I suspect the issue is the one further diagnosed in #2228 - another issue where the primary key field has not been auto-updating correctly when changing to and from an auto-generated value.

**Comment by gunjpan** [comment]
@PaddyMann. Hope you're feeling better now.
Closing this in favor of #2228. Please track the progress there. Thank you!
