### ISSUE TITLE
Inaccuracy in Remote Hooks Signature Docs

### ISSUE THREAD

**Issue by richardpringle** [strongloop/loopback#2185]
https://docs.strongloop.com/display/public/LB/Remote+hooks#Remotehooks-Signature

It says that "For static remote methods..."
```node
modelName.beforeRemote( methodName, function( ctx, next) { 
 ...
 next();
});
```
I believe this is true for custom static methods, but for methods such as `upsert` or `create` which are by definition static methods, they require a third argument in the callback, just like instance methods. 

@crandmck, when you get to this, please message me... the terminology is a little hairy here.

**Comment by upupzealot** [comment]
same problem,
modelName.beforeRemote( create, function( ctx, instance, next) { 
 ...
 next();
});

**Comment by crandmck** [comment]
@richardpringle Sorry I guess I missed this somehow initially.  I changed the wording in https://docs.strongloop.com/display/APIC/Remote+hooks#Remotehooks-Signature 
PTAL.

**Comment by richardpringle** [comment]
LGTM
