### ISSUE TITLE
Help create a Stormpath (user mgmt) middleware module for TEDx Amsterdam Open source Loopback Backend

### ISSUE THREAD

**Issue by dligthart** [strongloop/loopback#2187]
This middleware module for loopback will be used to offload user mgmt to SAAS party called stormpath:

https://docs.stormpath.com/nodejs/

All help on this is appreciated!

We want to utilize this module for the TEDx Open Source Backend:
https://github.com/TEDxAmsterdam/Backend/issues/2

**Comment by superkhau** [comment]
@dligthart We use GitHub issues to report bugs or keep track of feature requests. If you are looking to get input from community, etc. I suggest posting a discussion at https://groups.google.com/forum/#!forum/loopbackjs. I'm going to close this. Feel free to open a specific issue when you have something to request. See https://github.com/strongloop/loopback/wiki/Getting-help
