### ISSUE TITLE
Text field loses line break when saving to DB

### ISSUE THREAD

**Issue by PaddyMann** [strongloop/loopback#2190]
We have a `text` field in a model. When a value with line breaks is saved, the line breaks are lost on its way to MySQL.

This can be fixed with:

    function onBeforeSave (context, next) {
      context.instance.message = context.instance.message.replace(/\n/g, '\n\r');
      return next();
    }

Not ideal, so we'd like a more permanent fix for all text fields. Not sure if this is MySQL specific or not.

**Comment by Amir-61** [comment]
Hi @PaddyMann,

It seems it is working with this sample code:
```
      customers.create({
        firstName: 'foo \n bar\n baz',
        lastName: 'test'
      }, function (err, inst) {
        if (err) return done(err);
        console.log('created inst:', inst);
        customers.findById(inst.id, function(err, data){
          console.log('final result:', data)
        })
```

```
created inst: { firstName: 'foo \n bar\n baz', lastName: 'test', id: 9 }
final result: { firstName: 'foo \n bar\n baz',
  lastName: 'test',
  age: null,
  id: 9 }
```

The `\n` will be preserved in PHPMyAdmin but for somereason they are not shown in MySQL  Workbench, and in either case the result from loopback is showing line breaks...

**Comment by loay** [comment]
Hi @PaddyMann 
I tested with some boot data using `\n` and it was preserved in phpmyadmin. Now, in workbench, it doesn't make the line break but it is preserved still, as when we export the file to a csv or sql file, then import it in phpmyadmin, then it is still preserved and shows the linebreaks. 
![linebreak](https://cloud.githubusercontent.com/assets/1986928/14750857/f5444574-0894-11e6-9468-5fb04520e494.png)

unless you meant that without using `\n` and simple line breaks don't get preserved once you insert/upsert to mysql?? can you clarify please? Thanks.

**Comment by superkhau** [comment]
@Amir-61 @loay Is this a bug or still triaging?

**Comment by Amir-61** [comment]
@superkhau


No I believe it can be closed now. It does not seem a bug to me. @paddymann please feel free to re-open the issue with a repo reproducing the issue.

Thanks!
