### ISSUE TITLE
User confirm method not appending Email as UID

### ISSUE THREAD

**Issue by deviant32** [strongloop/loopback#2195]
I am using the email address as the id of my model instead of username.  When the email verification email goes out it is missing the uid entirely.  

this is what i get:
http://localhost:3000/api/clients/confirm&token=d884bacb6d4f1fb9a212dbaad84250c206519397c477d74c2da32d37a3bf39a048ce6db2e7b2a6d16965c579e702765b92de45961138a2fbedc64a35a0a2681a

**Comment by loay** [comment]
Hi @deviant32 
I am having a look. 
BTW, is your app available on github?

**Comment by loay** [comment]
Hi @deviant32 
are you still having the same issue? I cannot really reproduce on my end. 
Please have a look at these documents:
https://docs.strongloop.com/display/public/LB/Logging+in+users
and
https://docs.strongloop.com/display/public/LB/Registering+users

If you are still having the same problem, please leave a comment here. 
Also, please upload your repo or a sample repo where I can reproduce the issue and help you out. Thanks.
