### ISSUE TITLE
Should be able to filter on foreign key relations

### ISSUE THREAD

**Issue by mneil** [strongloop/loopback#2198]
I ran into an issue specific to my use case that I'm surprised loopback doesn't support since it is entirely possible to do through query string parameters alone.

I have a model, accounts. Accounts has many users. Users has many roles.

I want to get users and their roles through the account. I expect to be able to make a query like:

```
/accounts/{id}/users/{id}?filter={"include":"roles"}
```

Filter is completely ignored, it seems, when querying through a foreign key relation. If I inspect the context of the request I see that it ends up turning filter into `{"where":{"id":1}}` and includes is lost.

I feel like this should be possible. I would expect the above query to work exactly like the following would (which does work):

```
/accounts/{id}/users?filter={"where":{"id":1},"include":"roles"}
```

Alternatively I could query on `/users/{id}?filter={"include":"roles"}`. However, in my case, roles are tied to the specific account and not the user alone. This would mean I also have to add a scope to my include to look for roles where it matches my account. It's a minor issue but one that will save a lot of typing for people who integrate with my API.

Is there a way I could alter the request server side to map my url schema to the second one which is supported? Preferably a way that doesn't involve regular expressions against the request url.

**Comment by Nautigsam** [comment]
How is a role tied to an account? I think the simplest way is to make a remote method that will do exactly what you want.

**Comment by mneil** [comment]
A role belongs to an account through role mappings. So users may have many roles and may have duplicate roles through accounts.

It's not that I can't get the data I want. It's that I'm surprised that relations endpoints do not allow any additional filters. I even mentioned the alternative query, that does work. Writing out `where:{id:2}` is more that writing out `/2`. I also feel like it's less intuitive.

I would call this a feature request. I don't know where to start to add it into core or if there's a legitimate reason it isn't supported. I'm looking for guidance on both of those questions.

**Comment by superkhau** [comment]
>I would call this a feature request. I don't know where to start to add it into core or if there's a legitimate reason it isn't supported. I'm looking for guidance on both of those questions.

Sounds like a feature request that is pretty hard to implement. Let's get @bajtos and @raymondfeng's opinion on this. @bajtos @raymondfeng ^

**Comment by superkhau** [comment]
On second thought, what you propose seems possible with a bit of work. Would you like to try submitting a PR? We can discuss once you get some tests and code in place https://github.com/strongloop/loopback-datasource-juggler

**Comment by Amir-61** [comment]
>I have a model, accounts. Accounts has many users. Users has many roles.
I want to get users and their roles through the account.

Could you please provide a sample repo using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox), which reproduces the issue and explaining what you want to achieve? To me it seems you can do what you are looking for using [nested queries](https://docs.strongloop.com/display/public/LB/Nested+queries)... Just to make sure and come up with the best solution, please provide a sample repo...

Thanks :-)

**Comment by mneil** [comment]
I don't think nested queries will handle it. I've been using loopback in production for the past 8 months or so and haven't found a way to do this. I may have to break down and submit a PR to try and make this happen. I dug a bit to see if I could get it in but wasn't sure where this code belonged. 

I'm been working around it currently but it's complicating my API.

I will put together a sample repo with the issue. In the meantime, for reference.

Before I opened this ticket which is particular to includes I opened this one for other files like where https://github.com/strongloop/loopback/issues/2211#event-643759433 which was closed by 0candy (although I don't believe it should have been based on the reason). However, I think that ticket can stay closed since this one really encompasses that ticket as well.

I am asking for this to happen:

Account
```
{
 id: 1,
 name: "doesn't matter"
}
```

User:
```
{
  id: 2,
  name : "Michael"
}
```

Roles:
```
{
  id: 15,
  name: "admin"
}
```

RoleMappings
```
{
  userId: 2,
  roleId: 15
}
```

**GET** `/api/accounts/1/users?filter={"include":"roles"}`

_returns_
```
[
 {
  id: 2,
  name: "Michael",
  roles: [
   { id: 15, name: "admin" }
  ]
 }
]
```

Or

**GET** `/api/accounts/1/users/2?filter={"include":"roles"}`
```
{
 id: 2,
 name: "Michael",
 roles: [
  { id: 15, name: "admin" }
 ]
}
```

**Comment by bajtos** [comment]
Hello, I don't have enough time to read through all discussions here and in the other issue #2211. However, I remember that `findById` (`GET /api/accounts/1`) did not support `filter` argument initially, it as added later by https://github.com/strongloop/loopback-datasource-juggler/pull/564. As can be seen from the diff, this pull request addressed the issue for top-level DAO method only.

It makes perfect sense to me that relations should support `findById` with `filter` too.

I think the implementation should be reasonably easy, here is the code implementing `findById` for `hasMany` relation: https://github.com/strongloop/loopback-datasource-juggler/blob/2189b9a746071b599d6a129313b2cdd11052e36b/lib/relation-definition.js#L767-L780

**Comment by mneil** [comment]
Thanks for the links to those files. I will try to dig in next week if time allows.

**Comment by AThilenius** [comment]
It looks like filters are dropped in other places as well, like through a hasOne relationship query: https://github.com/strongloop/loopback-datasource-juggler/issues/811 I'm not sure if this is related or not but it looks like include-filters could use some love :) I'm new to Loopback or I would start looking through code.

**Comment by microfly2008** [comment]
I am expecting this implementation. Is there any update?

**Comment by bajtos** [comment]
@microfly2008 This issue is not a priority for the LoopBack core team right now. I am encouraging you to take a look at the code, implement the feature yourself and submit a pull request.
