### ISSUE TITLE
How to use http source : form

### ISSUE THREAD

**Issue by farlynd** [strongloop/loopback#2200]
Hi, i tried to write remotemethod using `http: {source: 'form'}` and got this error

```
{
  "error": {
    "name": "Error",
    "status": 400,
    "message": "fk is a required arg",
    "statusCode": 400,
    "stack": "Error: fk is a required arg\n    at new badArgumentError 
}
```

this is my code 

```
TanggalRuangan.updateA = function (fk, callback) {

        return callback(null,fk);

    };

    TanggalRuangan.remoteMethod(
        "updateA",
        {
            description: ["Update jumlah ruangan tersedia berdasarkan id dan tanggal"],
            accepts: [
                {arg: "fk", type: "string", http: {source: 'form'}, required: true, description: "Fk"}
            ],
            returns: {
                arg: "status", type: "object", root: true, description: "Return value"
            },
            // isStatic: false, /* this is to need id systematically */
            http: {verb: "put", path: "/updateA"}
        }
    );
```

i have no idea how to work with `http: {source: 'form'}`, but when i tried use http: {source: `'path'}` and set `http: {verb: "put", path: ":fk/updateA"}`, everything is fine, do i miss something?

-Farly

**Comment by bajtos** [comment]
Hi @farlynd, could you please show us the HTTP request (headers + body) that you send to call your remote method?

**Comment by bajtos** [comment]
FWIW, the http mapping of input arguments is performed here: https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L136-L140

**Comment by farlynd** [comment]
Thanks @bajtos for the response. you are right, the problem is on the header, i set this on the beforeRemote `ctx.res.set('Content-Type', 'application/x-www-form-urlencoded'); `and everything is fine.

1 quick question, how to bring a variable from before remote to remote method without using ctx.args?, for example i have a ctx.args['type']=ABCD, so i split it into var A=A,var B=B,var C=C, var D=D so i can to use it in the remote method.

**Comment by bajtos** [comment]
> 1 quick question, how to bring a variable from before remote to remote method without using ctx.args?, for example i have a ctx.args['type']=ABCD, so i split it into var A=A,var B=B,var C=C, var D=D so i can to use it in the remote method.

I think the cleanest way is to use a custom mapping function, see https://docs.strongloop.com/display/LB/Remote+methods#Remotemethods-HTTPmappingofinputarguments, and build an object containing all your variables as properties.

```js
MyModel.myMethod = function(input, cb) {
  // you have this properties available: input.A, input.B, input.C, input.D
}

MyModel.remoteMethod('myMethod', {
  accepts: {
    name: 'input',
    type: 'object',
    http: function(ctx) {
      var val = ctx.req.form.type;
      var items = val.split(); // whatever
      return {
        A: items[0],
        B: items[1],
        C: items[2],
        D: items[3]
      };
    }
  }
});
```
