### ISSUE TITLE
Trouble accessing javascript structure returned by find function with include filter

### ISSUE THREAD

**Issue by jdschreck** [strongloop/loopback#2205]
I have one model related to another with a hasMany relation.  I am using the include filter to get back a
javascript structure which should have an array objects of the first model type each of which should have a member array that lists the related model objects:

{ include: { relation: 'cssrules' }}

When I do a console.log(result) I see that it appear to be correct.  I have an array of the first model, and each of those has a member which is cssrules that is an array of objects.

If I do a console.log(JSON.stringify(result)) I see that expands out the object references in the cssrules array and correctly displays all of the information.

But when I try to accesses the structure like:
    result[i].cssrules.length
or
    result[i].cssrules[j]
I get errors about cssrules being undefined.

If I do the following:
   var tmp = JSON.stringify(result);
   result=JSON.parse(tmp);

then it seems to behave correctly, but this seems wasteful and unnecessary.  Why can't I access the
initial structure returned to me?

**Comment by jannyHou** [comment]
@jdschreck I am trying to look into this issue, could you fork sandbox: https://github.com/strongloop/loopback-sandbox and replace with your testing?
Thanks.

**Comment by jdschreck** [comment]
I will give that a try.

John

**Comment by jdschreck** [comment]
I have created https://github.com/jdschreck/loopback-sandbox which demonstrates the problem.

To run this testcase in the Explorer execute the following urls:

Model1/init
Model2/init
Model1/runQuery

There are two files present... bad.output which exhibits the problem and good.output which shows it working if I do a parse(stringify(results)). The example is configured to produce the bad output initially.

If you then uncomment line 49 of model-1.js it will run successfully.

**Comment by jannyHou** [comment]
@jdschreck Thank you for the extreme detailed sandbox to reproduce the problem.
So what happens here is when you get the raw data, the type of the included data is `Function` instead of `Object`.
You can verify this by 
```js
console.log("Here is the console.log on the raw result:");
console.log(result[0].model2s);
console.log("data type of raw result");
console.log(typeof result[0].model2s);

console.log("Here is the console.log on the parsed result:");
console.log(result[0].model2s);
console.log("data type of parsed result");
console.log(typeof result[0].model2s);
```

Console.log result:
```
Here is the console.log on the raw result:
{ [Function]
  _receiver:
   { description: 'description1',
     catalog: 'catalog1',
     name: 'MyFirstModel1',
     model2s: List [ [Object], [Object], [Object] ] },
  _scope: { where: { test1: 'MyFirstModel1' } },
  _targetClass: 'Model2',
  getAsync: [Function],
  build: [Function: bound ],
  create: [Function: bound ],
  updateAll: [Function: updateAll],
  destroyAll: [Function: destroyAll],
  findById: [Function: bound ],
  findOne: [Function: findOne],
  count: [Function: count],
  destroy: [Function: bound ],
  updateById: [Function: bound ],
  exists: [Function: bound ] }
data type of raw result
function
Here is the console.log on the parsed result:
[ { name: 'model2_instance3',
    test2: 'pqr',
    test1: 'MyFirstModel1' },
  { name: 'model2_instance4',
    test2: 'tuv',
    test1: 'MyFirstModel1' },
  { name: 'model2_instance5',
    test2: 'wxy',
    test1: 'MyFirstModel1' } ]
data type of parsed result
object

```

I cannot say is it a bug or designed in this way for other purposes. I will dig into it then update here.

**Comment by jdschreck** [comment]
Janny,
    Thanks for looking into this.  I look forward to hearing what more you 
find out.  It is unclear to me how console.log and JSON.stringify seem to 
be successful in navigating this structure to print out what we expect to 
see.

John

**Comment by jannyHou** [comment]
@jdschreck 
The name is returned by this function: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/scope.js#L176

That's why it's type is `function`.

Please check comment https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/scope.js#L162-L169 to see details

**Comment by jdschreck** [comment]
Janny,
   Sorry that answer is a little too terse for me to understand.  Can you 
tell me how I can navigate the returned structure?  I don't understand why 
JSON.stringify does not have trouble navigating the structure, but I do.

Thanks,
John

**Comment by jannyHou** [comment]
@jdschreck this property `name` is defined by Object.defineProperty(), so the value is returned by [`get`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/scope.js#L172). When you apply `JSON.stringify` to it, `JSON.stringify` will get value by function `get`. 
Is it clear now?

**Comment by jdschreck** [comment]
Janny,
    This is unfortunately not clear to me yet.  Is there a way to access the returned structure to access the list of model2s without parsing/stringifying?

John

**Comment by portokallidis** [comment]
Hello,

If i may, you can console.log the item.relation and discover the schema.
More specific if you use the `.getAsync()` method you will get a promise with the data.
 `Item.relationProp.getAsync().then((rel)=>{ //do stuff with 'rel' })`

**Comment by dan-h-ch** [comment]
I ran into a similar problem with a findById with multiple relations and sub relations. For what it's worth, JSON.parse(JSON.stringify(result)) seemed to work for me.

**Comment by Noob7** [comment]
+1 im getting this too when trying to. And landed here after an hour of scratching my head and trying out all different combinations of for and while and forEach loops and after then consoling the weird list

**Comment by jackrvaughan** [comment]
+1 Also ran into this issue.

**Comment by gabrielcabralbfr** [comment]
+1 also having trouble with this. 

Neither `JSON.parse(JSON.stringify(estudante.turma))` or `toJSON()` are working

First one throws "Unexpected token u in JSON"
Second one throws toJSON is not a function
