### ISSUE TITLE
Doc: return response body from remote method

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2209]
See https://github.com/strongloop/strong-remoting/pull/284 which implemented this new feature.

**Comment by crandmck** [comment]
OK, I think I need to talk with someone about this to understand it better.  Who?  @bajtos ?

**Comment by bajtos** [comment]
@crandmck yes, it would be me. If you point me to a doc page where to describe this new feature, then I can write the draft myself. Thoughts?

**Comment by crandmck** [comment]
From looking at the linked issues, I _think_ this adds some stuff to the returns/accepts options for remote methods (?)  If true, then we'd need to update https://docs.strongloop.com/display/APIC/Remote+methods#Remotemethods-Argumentdescriptions.

If I've misunderstood, please LMK.

**Comment by bajtos** [comment]
https://docs.strongloop.com/display/APIC/Remote+methods#Remotemethods-Argumentdescriptions
-> added a note about "file" type

https://docs.strongloop.com/display/APIC/Remote+methods#Remotemethods-Returningafile(stream)response
-> created a new level4 section describing how to return files

@crandmck please take a look and make whatever edits you find appropriate.

**Comment by crandmck** [comment]
@bajtos Your changes look fine, but I'd like to provide a reference link for Buffer and ReadableStream.
Would the best link for Buffer be https://nodejs.org/api/buffer.html  ?
And for ReadableStream https://nodejs.org/api/stream.html#stream_class_stream_readable ?

**Comment by bajtos** [comment]
> I'd like to provide a reference link for Buffer and ReadableStream.
Would the best link for Buffer be https://nodejs.org/api/buffer.html ?
And for ReadableStream https://nodejs.org/api/stream.html#stream_class_stream_readable ?

@crandmck sounds good, the two links looks good to me.

**Comment by crandmck** [comment]
OK, added those links.  I think we can close this now.
