### ISSUE TITLE
Save custom values in beforeRemote related method

### ISSUE THREAD

**Issue by lvning** [strongloop/loopback#2210]
Hi,
I'm using remote method like this:

```
Customer.beforeRemote('*.__create__orders', function(ctx, unused, next){
		var req = ctx.req;
		if (req.body.status) {throw new Error('not authed.');}
		req.body.status = 'prepay';
		req.body.createDate = Date.now();
		console.log('__create__orders invoked!', util.inspect(req.body), util.inspect(unused));
		next();
	});
```

I am trying to save custom values("status" and "createDate") in a model on MongoDB. but not successed.

Thanks for your help,

**Comment by lvning** [comment]
I fixed it,to save custom values like this

```
ctx.args.data.setAttribute('status', 'prepay');
ctx.args.data.setAttribute('createDate', Date.now());
```

And everythings working fine.

**Comment by gunjpan** [comment]
@lvning : Awesome. I was debugging at the moment with the sandbox I created to emulate your situation. Glad that it is working. Thanks for letting me know.

**Comment by lvning** [comment]
@gunjpan Thanks for your great effort:-)

Good luck!

**Comment by jamesjara** [comment]
For my case I'm getting "ctx.args.data.setAttribute('clientId', userId);  .. is not defined" , but accessing to the object directly is working, but I'm wondering if this can create a bad side effect.

`	model.beforeRemote('**', function(ctx, modelInstance, next) {
		if (ctx.req.accessToken) {
			var userId = ctx.req.accessToken.userId; 
			ctx.args.data.clientId = userId;  //this is working
       .........
`
