### ISSUE TITLE
Filter on relation doesn't respect id constraint 

### ISSUE THREAD

**Issue by mneil** [strongloop/loopback#2211]
**The setup**

User hasMany through accounts
Accounts hasMany through users

**The problem**
Retrieving users from accounts by id fails to correctly constrain the result set.

I expect `/api/accounts/1/users?filter={"where":{"id":2}}` to return 1 result - the user by id belonging to account id 1.

**What happens**
I receive 2 users, both myself and the user of id 2

What is happening is that the ctx.query.where is coerced from `{"where":{"id":2}}` to `{"where":{"id":{"inq":[1,2]}}}` where 1 is the owner of the access token being used. If I authenticate as user id 5 then the query is coerced to `{"where":{"id":{"inq":[5,2]}}}`

**How to reproduce**
I am using Ubuntu 14.04 trusty
Install Postgres 9.3.11
Create an empty database and edit `server/datasources.json` to authenticate and use that database.

Do the following:

```
git clone git@github.com:mneil/loopback-sandbox.git
npm install
slc run
```

On boot you should see 2 messages after strongloop connects 

```
auto migrate  undefined
database filled
```

This creates 2 users, roles, and an account. Open your browser to http://localhost:3000/explorer

Authenticate the explorer with 

```
{"username":"admin","password":"admin"}
```

Now GET `/api/accounts/1?filter={"include":"users"}` and see that 2 users return. < correct

**The following are incorrect**
GET `/api/accounts/1?filter={"include":"users","where":{"id":2}}` returns 2 users
GET `/api/accounts/1/users?filter={"where":{"id":2}}` returns 2 users

On another note I opened this ticket in the postgre connector repo initially. This morning I switched to the mysql connector and the same issue happens.

Either I'm doing something wrong or this issue isn't related to the two connectors but something else in loopback.

**Comment by 0candy** [comment]
Hi @mneil,

What you're trying to do is currently not supported:
See https://github.com/strongloop/loopback/issues/517#issuecomment-71796806

I am closing this as a dup of that issue.

Thanks!

**Comment by mneil** [comment]
Are these two issues the same? That issue is asking for support for nested properties - not relations. I believe issue 517 is asking for queries on complex types like postgres lists, bson/json fields or mongo subdocuments. I'm asking for filtering direct on a model when finding them through a relation (another model).

**Comment by 0candy** [comment]
If you don't think its the same issues, please feel free to re-open this issue.

**Comment by superkhau** [comment]
@mneil Can you provide a sample repo for us to reproduce this issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by Overdrivr** [comment]
@mneil @superkhau `git@github.com:mneil/loopback-sandbox.git` ?

**Comment by alexpls** [comment]
:+1: found this issue while using MySQL as well.
