### ISSUE TITLE
Include from many tables, when hasmany points to base model, is it possible?

### ISSUE THREAD

**Issue by sm-g** [strongloop/loopback#2213]
I have City with many Names on different langs, when every translated string located in its own table:
```
{
  "name": "City",
  "properties": {
    "namelstringid": {
      "type": "number",
      "required": true
    }
  },
  "relations": {
    "name": {
      "type": "belongsTo",
      "model": "lstring",
      "foreignKey": "namelstringid"
    }
  }
}
```
```
{
  "name": "lstring",
  "relations": {
    "ftses": {
      "type": "hasMany",
      "model": "LstringFtsBase",
      "foreignKey": "docid"
    }
  }
}
```
and many `lstring_ftsN` tables
```
{
  "name": "lstring_fts1",
  "base": "LstringFtsBase"
}
```

Can I make `names` relation to load all related strings with single query, `Cities?filter[where][_id]=1&filter[include][names]`?

**Comment by loay** [comment]
Hi @sm-g 
You can do a nesterd query:
https://docs.strongloop.com/display/public/LB/Nested+queries

**Comment by loay** [comment]
Hi @sm-g 
Did the nested queries fix your issue? Thanks

**Comment by loay** [comment]
I am closing this issue for now. If the problem still persists, please leave a comment and I will re-open the case. Thanks.
