### ISSUE TITLE
Authenticate: True with 3rd party integration redirects back to login page after confirmation

### ISSUE THREAD

**Issue by Upguard** [strongloop/loopback#2218]
Like the title says, I'm having problems with integrating third party authentication using loopback-component-passport. 

When I go to my login page, it redirects to auth/provider, takes me to the third party site, redirects back to my site and adds the user account. However, when I set authenticate: true on my $state, after the account is created, instead of redirecting to my dashboard, it redirects back to my /login page.

I'm assuming the $rootScope.currentUser isn't being set and these lines of code are causing the script to redirect back to the login state.

`if (next.authenticate && !$rootScope.currentUser) {
        event.preventDefault(); //prevent current page from loading
        $state.go('login');
      }`

Does this not work out of the box? Do I need to do something on my end for $rootScope.currentUser to be set?

**Comment by davidcheung** [comment]
Hi @Upguard Not sure if this helps your issue, 
What I have previously setup for my app was having a common controller (in my case **header**),
so two resource to look at for login related issues are `LoopBackAuth` and `User`


and it would have something such as 
- have login page emit an event
- have header update such event using `User model` from controller
In your case I assume `$location` would be `$state`'s equivalent 
```js
//login controller
angular.module('myapp')
.controller('LoginCtrl', function ($scope, $rootScope, $location, User) {

      User.login(
        parameters,
        postData,
        function onSuccess(res, headers) {
          $location.path('/');
          $rootScope.$emit('loginEvent', 'succesful login');
        }
      );

});
```


```js
//header controller
angular.module('myapp')
.controller('headerCtrl', function ($scope, $rootScope, $location, User) {

    $rootScope.$on( '$routeChangeSuccess', function(scope,current,previous){
      $scope.loginStatusUpdate();
    })
    //listening to login events
    $rootScope.$on('loginEvent', function (event, data) {
      $scope.loginStatusUpdate();
    });

    //check if user logged in
    //and then redirect user to login page
    //and update the header
    $scope.loginStatusUpdate = function () {
      if (!User.isAuthenticated() || !User.getCurrentId()) {
        $location.path('/login');
        $scope.isLoggedIn = false;
      }
      else {
        $scope.isLoggedIn = true;
      }
    }
});
```

And this seems like a problem with [loopback-sdk-angular](https://github.com/strongloop/loopback-sdk-angular), would like to encourage you next time posting to the corresponding repo so there is a higher chance of someone familiar with that domain addressing issues / helping.

**Comment by davidcheung** [comment]
@Upguard I am closing this issue as it might be fit better in the [sdk-angular](https://github.com/strongloop/loopback-sdk-angular) repo or are you trying to follow the [passport example](https://github.com/strongloop/loopback-example-passport) or even better in the googles forum, we try to limit the scope of github issues to be bug reports and feature requests ([See Wiki](https://github.com/strongloop/loopback/wiki/Questions)), thanks!
