### ISSUE TITLE
Questions about authentication & ACL

### ISSUE THREAD

**Issue by Cadrach** [strongloop/loopback#222]
Hi,

I have a few questions about authentication:

I have model A and A hasMany B. Also, A has a property "users" which holds links to users that should be able to access it. How can I configure B, so that it can be read & written only by users allowed to A? Example high level code:
```js
A.hasMany('b', {model: B});
A.hasMany('users', {model: User});
```
I am a bit lost for this: should I DENY all in B, and work only with hooks? But it looks like hooks only work with remote methods, so how can I protect B so that it can be listed with A only if User is in A.users?

**Comment by Amir-61** [comment]
I followed all of the conversation here and it seems all of the user's questions have been already answered; I will be closing this ticket soon...

Thanks!

**Comment by Amir-61** [comment]
I'm closing this ticket now for the user's problems seem to be resolved.
