### ISSUE TITLE
ACL DENY all properties for everyone

### ISSUE THREAD

**Issue by sbehrends** [strongloop/loopback#2222]
While following documentation like (https://github.com/strongloop/loopback-example-access-control) of ACL managment in Loopback Im having an issue in most basic Rule.

I created a sample model called Article. Added one ACL that DENY everything to unauthenticated and only allow to authenticated users. But on explorer I can still list Articles and POST new articles without any token or authentication. 

```
"acls": [
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$unauthenticated",
      "permission": "DENY"
    }
  ],
```

Any ideas?

**Comment by sbehrends** [comment]
Just to add some information.
I am extending User to a "Author" model based on User.

DEBUG=loopback:security:* node .
Does not shows any information while doing the request.

**Comment by Neil-UWA** [comment]
re-order your acls, put the deny all rule first

**Comment by gunjpan** [comment]
@sbehrends : Hi, I tried to reproduce the issue with ACL entries you provided and found that it is working fine and behavior is as expected i.e. to block access for `unauthenticated` users. 
Please give a try to the code I uploaded here: https://github.com/gunjpan/sandbox/tree/lb2222 and see if that's something you're doing. 
If not, can you provide me with a sample repo? or send a PR to that sandbox with your code?

Besides, I would recommend reading [How Access Control works in LoopBack](https://docs.strongloop.com/display/APIC/Controlling+data+access#Controllingdataaccess-Definingaccesscontrol)


@Neil-UWA : I don't believe re-arranging solves the issue as LoopBack determines the ultimate ACL by adding all the applicable ACLs with precedence rules for permission and access type to resolve any conflicts. More about precedence [here](https://docs.strongloop.com/display/APIC/Controlling+data+access#Controllingdataaccess-ACLruleprecedence)

**Comment by gunjpan** [comment]
@sbehrends : Hi, is this resolved? PTAL at previous comments and let me know if you need any further assistance. Thanks.

**Comment by gunjpan** [comment]
@sbehrends : Hi, closing this issue for now due to inactivity. If you're still facing this issue and need any further assistance, please feel free to reopen it and mention my name, I'll be happy to help :)
Thank you.

**Comment by denkan** [comment]
@gunjpan : Actually, I'm facing the same problem. Tried to lock down a bunch of models in a current project, which got ignored.

Tried with a new, clean loopback project with a simple, basic memory model - and still ignores the acls.

```
{
  "name": "denkTest",
  "base": "PersistedModel",
  ...
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }
  ]
}
```

FYI, had some trouble earlier due to issue #2292 which led me to custom installs of `generator-loopback` and `yeoman-environment`. No idea if this could be related, though.

**Comment by denkan** [comment]
Hmf... my  bad.

Apparently, the `/server/boot/autentication.js` (containing the `server.enableAuth()` call) isn't included when choosing `'empty-server'` as application type in the loopback initialization.

Without calling `server.enableAuth()` the ACL is ignored overall. Fair enough :)
