### ISSUE TITLE
Add missing unit test for token middleware

### ISSUE THREAD

**Issue by benkroeger** [strongloop/loopback#2226]
as discussed in #2108

**Comment by bajtos** [comment]
@benkroeger It's better to open a pull request directly, there is no need to create short-lived placeholder issues like this one.

**Comment by benkroeger** [comment]
just following the [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) concept here. And I need an issue in order to name my branch correctly.

**Comment by benkroeger** [comment]
landed in 2.29.1
