### ISSUE TITLE
autoupdate doesn't always work?

### ISSUE THREAD

**Issue by PaddyMann** [strongloop/loopback#2228]
I've had very mixed results with autoupdate. Sometimes it seems to work fine, othertimes not.

For example, I've tried to update a list of countries from:

```
"properties": {
  "id": {
    "type": "number",
    "id": true,
    "dataType": "smallint",
    "generated": true
  },
  "name": {
    "type": "string",
    "required": true,
    "length": 50
  }
},
```

to 

```
"properties": {
  "code": {
    "type": "string",
    "id": true,
    "dataType": "char",
    "length": 2
  },
  "name": {
    "type": "string",
    "required": true,
    "length": 50
  },
  "native": {
    "type": "string",
    "required": true,
    "length": 50
  },
  "continent": {
    "type": "string",
    "required": true,
    "dataType": "char",
    "length": 2
  }
},
```

For some reason the code column doesn't get created. If I delete the table and run `autoupdate` again then it does. By the time I've done this additional step, I've lost faith in using auto-update as part of a production release.

So 2 queries:
- Any common causes for the above type of behaviour that I can avoid?
- Is it considered best practice to avoid using auto-update for database migrations on a production database?

**Comment by loay** [comment]
Hi @PaddyMann 
Can you specify the connector you are using? loopback version if possible as well?
Also, if possible, can you provide a repo where I can reproduce your issue?
are you getting an error message or the code coulmn just doesn't get created.. Thanks

**Comment by PaddyMann** [comment]
Hi @loay 

├── loopback@2.27.0
├── loopback-boot@2.17.0
├── loopback-component-explorer@2.4.0
├── loopback-connector-mysql@2.2.1
├── loopback-datasource-juggler@2.46.0
├── loopback-ds-timestamp-mixin@3.2.2

I haven't got the time to set up a public repo this morning, but have found that if I flip between the two property lists above, then the primary key field is never set up (`id` or `code`). The primary key field is set up correctly if I drop the table and do an auto-migrate.

Are you able to advise - is auto-update generally known to be flakey? Should I avoid using it once we're past the prototyping stage?

**Comment by PaddyMann** [comment]
A separate weird undesirable behaviour I get is that I have a many-to-many relationship between another model and country. 

When I have `code` as the primary key, I'd ideally like the connecting table to have a field `countryCode` of type `CHAR(2)` (to match `code`). Instead it sets up `countryId` as a `VARCHAR(512)`.

**Comment by loay** [comment]
hi @PaddyMann 
I haven't heard any weird behavior with mysql neither had it myself. So if I test your case, it may or may not happen. 
I am testing something similar that is close to your situation. I will let you know if I find anything. In the mean time, it will be helpful if you can create a repo so we can test your case in specific. Thanks.

**Comment by loay** [comment]
Hi @PaddyMann 
I tested the auto-update with couple of different scenarios including the usage of phpMyAdmin and you are right, the code column is dropped. 

- first of all, I don't recommend the usage of code because it is a reserved mysql keyword. 
- So for the sake of testing here, I used `countryCode` and it doesn't get created unless I remove the `"id":true` part.  It happens because you switched from an auto-incremented id to another id. The causes a conflict with mysql

The way I fixed that is the same concept as in ```ALTER TABLE country DROP PRIMARY KEY, ADD PRIMARY KEY```

I used an autoupdate with the following:

```
  "properties": {
    "countryCode": {
      "type": "string",
      "dataType": "char",
      "length": 2
    },
    "name": {
      "type": "string",
      "required": true,
      "length": 50
    },
    "native": {
      "type": "string",
      "required": true,
      "length": 50
    },
    "continent": {
      "type": "string",
      "required": true,
      "dataType": "char",
      "length": 2
    }
  },
```
Notice the countrycode doesn't have the `"id": true,` 
2nd step, you add the `"id": true,`  in countrycode, and try again,  which should work fine.

**Comment by PaddyMann** [comment]
Thanks for following up @loay 

I appreciate the workaround to get around a bug. Is the plan to now fix it? 

I'm not so clear on why it happens. I have no problem running these commands in MySQL:

    -- Start with PK as auto-incrementing int
    CREATE TABLE `testtable` (
      `id` INT NOT NULL AUTO_INCREMENT,
      PRIMARY KEY (`id`));

    -- Rename PK and change to CHAR(2). Note that `code` is correctly set up as 
    -- the PK after running this command.
    ALTER TABLE `testtable` 
    CHANGE COLUMN `id` `code` CHAR(2) NOT NULL ;

    -- Revert back
    ALTER TABLE `testtable` 
    CHANGE COLUMN `code` `id` INT NOT NULL AUTO_INCREMENT ;

I'll raise a separate issue about the many-to-many middle table using a VARCHAR(512) rather than CHAR(2).

**Comment by PaddyMann** [comment]
Should I be raising these issues here or on the mysql-connector issue tracker? (or or the juggler tracker?.... not always clear where the issue stems from)

**Comment by loay** [comment]
If it is related to mysql-connector issue, then yes please use `loopback-connector-mysql` repo. 
So in this case, I would say yes. 
I will flag this one as a bug.
