### ISSUE TITLE
Angular bulk upsert throwing error

### ISSUE THREAD

**Issue by jonathanwoahn** [strongloop/loopback#2229]
First off, I just learned about Loopback about 2 weeks ago, and it has changed my life. I love it.

Second, I'm getting an error in Angular using the lbService while doing a bulk upsert:

```
angular.js:11607 Error: [$resource:badcfg] Error in resource configuration for action`upsert`. Expected response to contain an object but got an array
http://errors.angularjs.org/1.3.12/$resource/badcfg?p0=upsert&p1=object&p2=array
```

I have located the problem, in the "upsert" method in lbService for the Angular resource. When doing a bulk upsert, there is a parameter that needs to be set that current doesn't exist:

```
"upsert": {
          url: urlBase + "/TaskSessions",
          method: "PUT",
          isArray: true //<--- this does not currently exist
        },
```

I have been able to get around this issue for my application, but it needs to be fixed in the Loopback Angular SDK generator for a more permanent solution. Just thought you'd want to know

**Comment by davidcheung** [comment]
Hi @jonathanwoahn, great to hear you love loopback!
Thanks for bringing this up, the bulk `PUT` method is actually not supported at the moment, [See issue](https://github.com/strongloop/loopback/issues/2123#issuecomment-204149539) for discussion.  

There is a [temp fix](https://github.com/strongloop/strong-remoting/pull/289) to handle errors better but not the support of bulk `PUT` yet


>I have been able to get around this issue for my application

On the angular side, can you clarify abit, you are able to add `isArray: true` to `upsert` to get bulkUpdate working? or that is allowing you to catch the errors? or you are no longer using the bulk `bulkUpdate` functionality? 

Or you could perhaps open an issue in [angular-sdk](https://github.com/strongloop/loopback-sdk-angular/issues) itself too so it's easier for people working on the angular-sdk to address this.

**Comment by jonathanwoahn** [comment]
Upsert actually works with an array, but in the current state it returns an
array of all the "upserted" objects, but the Angular resource is expecting
an object - so it throws an error. But adding "isArray: true" to the upsert
method no longer throws an error. So the better idea is probably to create
a "bulkUpsert" method in the angular-sdk, and have it use the same route.
I'll open an issue over in the angular-sdk so they can handle it - should
be a super easy fix.

**Comment by bajtos** [comment]
> So the better idea is probably to create a "bulkUpsert" method in the angular-sdk, and have it use the same route.

We already have `createMany` to support batch creation, `upsertMany` would be a better name for bulk upsert.

However, as commented in https://github.com/strongloop/loopback/issues/2123, we are dropping support for bulk upsert in LoopBack 3.0, therefore I would rather not add `upsertMany` to the Angular SDK.
