### ISSUE TITLE
loopback 'authorization' header conflict

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback#2230]
When I use the 'authorization' header for basic auth (a very common scenario), then loopback mistakenly uses it's value for the accessToken lookup. This is not re-configurable, so it's killing a very common workflow.

This can be easily overcome if the current iteration going over each group of possible locations would iterate first with only the user supplied keys, and only then resort to the default lookup.

**Comment by Morriz** [comment]
So:
```
for (length = params.length; i < length; i++) {
   ...
   if (typeof id === 'string') {
      return id;
   }
}
for (i = 0, length = headers.length; i < length; i++) {
   ...
   if (typeof id === 'string') {
      return id;
   }
}
if (req.signedCookies) {
   for (i = 0, length = cookies.length; i < length; i++) {
      ...
   if (typeof id === 'string') {
      return id;
   }
}
```
would be run twice, first for the user options, then the defaults

**Comment by loay** [comment]
Can you please submit a pull request with your solution?
Also, can you point out the error message that you get or the actual behavior when the process terminates the workflow that you mentioned in your first comment?
Thanks.

**Comment by Morriz** [comment]
I am involved in 2 contracts atm and feel quite overwhelmed, so I don't see that happen in the near future. But a programmers eye will see what I mean.

**Comment by loay** [comment]
@Morriz Thanks for your suggestion. I will have a look.
