### ISSUE TITLE
loopback.getCurrentContext() is empty

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback#2231]
When I make a regular request to a custom remote method, I see that ctx does not get populated in this part (around token.js:105):
```
      req.accessToken = token || null;
      rewriteUserLiteral(req, currentUserLiteral);
      var ctx = loopback.getCurrentContext();
      if (ctx) ctx.set('accessToken', token);
```
which makes the token not available in `ctx.get('accessToken')`, even when it is properly set on `req`

bug?

**Comment by loay** [comment]
Hi @Morriz 
Please have a look at this issue: https://github.com/strongloop/loopback/issues/1676
Thanks

**Comment by loay** [comment]
Hi @Morriz 
I am closing this issue for now. If you need furhter help, please leave a comment and I will re-open the issue.
