### ISSUE TITLE
slc model generator didn't show built-in model

### ISSUE THREAD

**Issue by casamia918** [strongloop/loopback#2233]
I'm following "getting started part 2" tutorial. 
https://docs.strongloop.com/display/public/LB/Create+new+models
I'm on the "Define the Reviewer model" step and command "$slc loopback:model" to create reviewer model. 
At the generator options, the guide says to choose "User" as base class. But in my case, there are only 5 base classes - model, persistedModel, coffeeshop, review, (custom). 

Did I miss to configure slc setting? Please help.

Here is my command line capture.
![screen shot 2016-04-15 at 10 15 09 am](https://cloud.githubusercontent.com/assets/8295005/14549313/9d7bd8f2-02f9-11e6-9799-3fc72392257a.png)

[Environment]
node v5.7.0
strongloop v6.0.0
OSX 10.11.3

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
@casamia918 Did you try scrolling down with the arrow keys?  
I just tried this and it works exactly as documented.

**Comment by casamia918** [comment]
@crandmck I found the reason. I've not installed node modules, just cloned the git repository. After I excute "$npm install", the every built-in base classes are properly shown. Thanks.
