### ISSUE TITLE
Are there any http datasource connectors

### ISSUE THREAD

**Issue by devotox** [strongloop/loopback#2235]
To be able to connect to another remote api over http and get the data in some format that you can then change and model to your own api's format?

**Comment by superkhau** [comment]
- https://github.com/strongloop/loopback-connector-rest/
- https://github.com/strongloop/loopback-connector-remote

For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by devotox** [comment]
Thank you and will do that in the future
