### ISSUE TITLE
document page issue in mobile browser 

### ISSUE THREAD

**Issue by casamia918** [strongloop/loopback#2236]
This is not about the loopback's functionality issue, but about loopback's web site issue.

I'm studying loopback by reading its document page. 
https://docs.strongloop.com/

When I'm busy and in the outside, I read this page using iPhone. Hoping for responsive web page? I don't care. But the problem is, this doc's left nav menu is not shown in the mobile browser

![img_5198](https://cloud.githubusercontent.com/assets/8295005/14580884/95d594ce-0418-11e6-8360-1ccd33fd749f.PNG)

Because of this, I can't access to another doc page, except for directly opening the page url by search from google.

I can not find customer contact information on the website, so I leave this issue on this github. I wish that someone relay this issue to the website master. Thanks.

**Comment by Amir-61** [comment]
Sorry could you please explain a little bit more? Do you mean if you click on links the pages is not shown? And instead you need to sue the direct url? I tried it on my own phone it seems working... I need more info though...

Thanks!

**Comment by casamia918** [comment]
@Amir-61 

![screen shot 2016-04-17 at 8 09 08 am](https://cloud.githubusercontent.com/assets/8295005/14584156/cdf16af8-0473-11e6-833a-15e50851c290.png)

This is capture from pc's browser. Compare with the mobile version. PC version has left side menu but mobile version doesn't. I can't find menu enable button on the mobile version and this make me so annoying to link to another article.

**Comment by Amir-61** [comment]
Oh I see... Thanks for clarification... @crandmck it seems menu is this missing on mobile versions? Any thought?

Thanks :-)

**Comment by superkhau** [comment]
This has been a known issue for awhile. Is there a way to make confluence show the sidebar on mobile @crandmck?

**Comment by crandmck** [comment]
I haven't found a way to make the sidebar appear.  We're using a third-party add-on called "Spacetree" to create the navigation sidebar, and I suspect it's an issue with that.  BTW, the [default Confluence mobile view](https://confluence.atlassian.com/doc/confluence-mobile-284365706.html) is really useless -- it just shows blog posts (which we don't use), most popular pages (based on "likes", which we also don't use) and stuff like that. 

I'm hoping we can start work to move off Confluence and into a Github-sourced responsive site similar to http://expressjs.com.  But that is a longer-term goal.

In the meantime, as a workaround, I created a complete navigation tree page at
https://docs.strongloop.com/display/LB/Mobile+site+navigation.
At least you can use that to navigate to any page in the LoopBack space.  I'll create similar pages for the other spaces (at least https://docs.strongloop.com/display/SLC and https://docs.strongloop.com/display/NODE).

I know this is not great, but at least you'll be able to see the whole page hierarchy on mobile, and thus get to any page.

**Comment by superkhau** [comment]
@crandmck Thanks for the workaround, at least we can navigate around now. ;) +1 for the longer-term goal.

**Comment by superkhau** [comment]
@casamia918 That's the best we can do for now, so keep your eye our for a blog announcement when we move the docs off confluence (not sure when though since we have no idea where this "feature" lies in the roadmap ATM).
