### ISSUE TITLE
id property (stateName) cannot be updated from home to index.home

### ISSUE THREAD

**Issue by likun7981** [strongloop/loopback#2238]
I want to update the id property  , but get the error , Why can't update the Id property

**Comment by RicardoVaranda** [comment]
Can you provide some Snippets of your code so we can understand better what the issue is.

**Comment by gunjpan** [comment]
@likun7981 : Hi, as @RicardoVaranda mentioned, could you please provide some snippet of code or a sandbox repo so that we can better assist you.

**Comment by likun7981** [comment]
I change a way to achieve, thank you for your answer
