### ISSUE TITLE
More granular operation hooks API

### ISSUE THREAD

**Issue by hq-mobile** [strongloop/loopback#2239]
Hi,

Not sure if this is the right place to ask questions so feel free to close and point me to the correct place.

I'm sure there was good reason to deprecate the model hooks API from a technical standpoint, however from an api consumer point of view the API was a great place to store model logic in a readable well defined location.  Using the operation hooks API it is possible to create the same functionality but with more code. For example if you want to only do something on creation you have to write code that checks if the instance is new.

Are there any plans to have an API that is as simple and as nice as the Model Hooks API in the Operation Hooks and Remote Hooks API? 

Thanks
Dan.

**Comment by hq-mobile** [comment]
Hey,

Just to add to this a real world example so it doesn't appear I am being picky without coming across a use case where the old way worked better for my use (I appreciate that may not be the case for others). I do love the framework you guys are building, and this is in no means a blocker but just a suggestion from a user perspective.

The old Model Hooks way I would have something like
Invoice.afterCreate(savePDF)
invoice.afterCreate(sendEmail)
Invoice.afterDestroy(deleteFromPDFStore)

But now I have another function that has to determine if something is new e.g.
Invoice.observe('after save', if_new(savePDF))
Invoice.observe('after save', if_new(sendEmail))
Invoice.observe('after delete', deleteFromPDFStore))

Or worse if I want to not use my 'if_new' function I have to run after the remote e.g.
Freelancer.afterRemote('prototype.__create__business__invoices', savePDF)
Freelancer.afterRemote('prototype.__create__business__invoices', sendEmail)

From my point of view the old API is not only easier to read/organise code, but it is less prone to typos and having to work out what a remote method will be called.

**Comment by richardpringle** [comment]
Hey @hq-mobile (Dan), the best place for questions is usually as follows:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

I'm not sure that you'll find an answer there though. Maybe @bajtos could explain here?

I would give you an answer but the model hooks were deprecated before I started working on the framework :stuck_out_tongue_closed_eyes:.

I would suggest posting in the groups while you wait for your answer though. The Google Group is probably best.

**Comment by bajtos** [comment]
Let's keep the discussion here for now.

We are tracking a request for per-method hooks in https://github.com/strongloop/loopback/issues/1857. If I understand you @hq-mobile correctly, that's the feature you would like to get?

The trouble with old model hooks is that they were not invoked in all cases where they should be invoked, which causes surprises and bugs in the applications. 

Taking your code as an example, "savePDF" and "sendEmail" is not triggered when the client calls `updateOrCreate` method. This was not obvious when setting up a `beforeCreate` hook. I have to admit it's not entirely clear with the new hooks if you don't realise that `isNewInstance` can be `undefined` too, which means "we cannot tell whether this operation will be CREATE or UPDATE".

In my opinion, (model/operation/method) hooks can get us only so far, they are not a silver bullet. In your case, I think it's better to create a new custom remote methods that would call the provided DAO methods under the hood and then post-process the result as needed.

For example:

```js
Freelancer.prototype.createInvoice = function(...) {
  return this.bussinessInvoices.create(...).then(savePDF).then(sendEmail);
};

Freelancer.remoteMethod('createInvoice', {
  isStatic: false,
  accepts: ...,
  returns: ...
});
```

**Comment by bajtos** [comment]
> We are tracking a request for per-method hooks in https://github.com/strongloop/loopback/issues/1857. If I understand you @hq-mobile correctly, that's the feature you would like to get?

I pasted wrong link, here is the correct URL: https://github.com/strongloop/loopback-datasource-juggler/issues/397

I have edited my comment above to prevent future confusion.

**Comment by hq-mobile** [comment]
Yes, your understanding is correct.  Personally when building a REST API I think of things in terms of resources (models) and feel that the model based hooks made the most amount of sense.  

I also try to stick as closely as possible to CRUD operations as it makes it easy to generalise resource behaviour. If I have to provide and action/remoteMethod then I tend to handle it with an 'after' hook and a query string,

I guess what you are suggesting if thinking about the API as more action based than resource based?

**Comment by bajtos** [comment]
> I guess what you are suggesting is thinking about the API as more action based than resource based?

Well, I am suggesting to decouple the actual REST API from the implementation in LoopBack models. The fact that your API is based on resources and CRUD operations does not mean you have to map these HTTP requests directly to built-in CRUD methods. Especially when some of the built-in CRUD methods like `updateOrCreate` are difficult to implement correctly in your application domain.

In my example above, you can still map `Freelancer.prototype.createInvoice` to a RESTful URL `POST /api/freelancers/:id/invoices`.

My main concern about (over)using "after" hook is that these hooks are not invoked when you call a CRUD method directly from code, which may create surprising bugs.

Anyways, that's just me. I don't have the experience you gained while building your application, thus my advice may be wrong and not apply to your specific situation.

**Comment by hq-mobile** [comment]
No, you make a lot of sense. In theory I agree with the decoupling of the REST API to the models, however in my case (can't speak for others, and I amy be in the minority).  However given my admittedly limited experience creating REST API's I have always found they involve at least a fair amount of modelling  'resources', and then on some operations perform extra actions.  Your suggestion certainly handles that and even makes the mapping more flexible.

However one of the huge advantages I have found with Loopback is that it works out of the box, which the proposed solution certainly does not break. But also that to implement fairly common tasks the programming mental model was also what I would expect.  The newer API just feels a little less clean from an API consumer point of view and required my brain to work a little harder for my scenario.

I can also see how the after hooks not firing in all scenarios is not ideal, and could cause more confusion that the proposed solution. I have actually been bitten by this when implementing soft delete.  

I don't feel massively strongly either way as I can get both API's to do what I want, but I guess in a perfect world the API that would work best for me at present is resource based, with hooks that fire consistently when a resource operation happens whether called remotely or locally in code.  I am wondering if remote hooks and the current model hooks interface could be the sliver bullet that covers all scenarios, i.e. model hooks for common usage (super fast REST API development) and remote hooks for when the CRUD operations do not map nicely to the application domain.

Wow that's a bit of a ramble, but it has helped clear my mind. I think the first step for my scenario would be simply to not have the operation hooks fire for different scenarios such as after save firing on create and update.  For me I guess granularity is the key. Does any of that make sense?

**Comment by hq-mobile** [comment]
Just thought I'd add a more real world example based on consistency and the comment:

> My main concern about (over)using "after" hook is that these hooks are not invoked when you call a CRUD method directly from code, which may create surprising bugs.

When using the loaded operation hook, the behaviour is pretty bizarre and even more confusing than the hooks not always firing. If I am updating an object and have the hooks persist (to encrypt) and loaded (to decrypt) everything works as expected, a context with the data attribute is passed to the  loaded hook. However when performing a GET (find) it is passed a context with an instance (ModelInstance) so that I can not have generic code there either.  I have ended up with a solution like this:

`const secure_property = require('../../server/src/secure_property');

module.exports = function(BankAccount) {
  BankAccount.observe('persist', secure_property(process.env.SECURE_PROPERTY_KEY, 'data.account_number').encrypt);
  BankAccount.observe('persist', secure_property(process.env.SECURE_PROPERTY_KEY, 'data.sort_code').encrypt);
  BankAccount.observe('loaded', if_has_key('data', secure_property(process.env.SECURE_PROPERTY_KEY, 'data.account_number').decrypt));
  BankAccount.observe('loaded', if_has_key('data', secure_property(process.env.SECURE_PROPERTY_KEY, 'data.sort_code').decrypt));
  BankAccount.observe('loaded', if_has_key('instance', secure_property(process.env.SECURE_PROPERTY_KEY, 'instance.account_number').decrypt));
  BankAccount.observe('loaded', if_has_key('instance', secure_property(process.env.SECURE_PROPERTY_KEY, 'instance.sort_code').decrypt));
};`

I hope these comments are coming across as constructive, as that is how they are intended.  I am also completely open to the suggestion that I have completely misunderstood framework and operation hooks as it feels that might be the case.

**Comment by bajtos** [comment]
Sorry for the long silence.

> However when performing a GET (find) it is passed a context with an instance (ModelInstance) so that I can not have generic code there either.

This should have been fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/796/commits/3028329126702456d59b42d6a88da17effe89919.

I am going to close this issue, please open a new one if there is any other specific thing to fix/improve.
