### ISSUE TITLE
Problems with custom remote method involving unrelated models inside a transaction

### ISSUE THREAD

**Issue by paotoya757** [strongloop/loopback#2243]
Hello, I have a problem implementing transaction behavior with two unrelated models. In the script "oferta.js", I tried to load the models, and they seem to load successfully. But the issue is that the callback passed to the "Oferta.beginTransaction" function, is not being executed, which means that my transaction is not being created. Any help would be greatly apreciated. Best regards to all.

oferta.js
![image](https://cloud.githubusercontent.com/assets/7131457/14625308/87ffc776-05a7-11e6-895b-5763d52f8a60.png)

**Comment by paotoya757** [comment]
The blue arrow indicates a console.log line that is not being reached in the code.

**Comment by ffarzat** [comment]
+1

**Comment by paotoya757** [comment]
Here is the fix. Its important to propagate the transaction in this manner.
![image](https://cloud.githubusercontent.com/assets/7131457/14835941/594efccc-0bd2-11e6-9ae5-e7e9fe4e76c2.png)

**Comment by ffarzat** [comment]
Worked well. Thanks a lot.

**Comment by gunjpan** [comment]
@paotoya757 : Yes, you need to get handle of an [`app`](https://docs.strongloop.com/display/public/LB/Working+with+LoopBack+objects#WorkingwithLoopBackobjects-Gettingareferencetoanunrelatedmodel) object for getting access to an unrelated model. More about working with loopback objects [here](https://docs.strongloop.com/display/public/LB/Working+with+LoopBack+objects).
Closing now. Should you need any assistance with this issue, feel free to re-open it and mention me.
Thank you.
