### ISSUE TITLE
Is there anyway to add custom "ORDER BY"

### ISSUE THREAD

**Issue by nmklong** [strongloop/loopback#2248]
Hi,

I have been implementing a complicated query, which i had to use raw sql, now i want to use loopback's ORM to return the response, but i can't manage to alter the order by.

The idea is that i finally got an array of ids, which i would like to keep its order, i can do this by doing

`ORDER BY FIELD(id, 1399, 8833, 8989, ....)`

in sql, however, i can't alter loopback's order by

```
Product.find({
  where: ....
  ....
  order: "FIELD(......)" // Cannot modify this
}, function(err, result){
  ......
})
```

Is there any workaround you can suggest? Thank you

**Comment by superkhau** [comment]
Native is probably your best bet for a workaround. https://docs.strongloop.com/display/public/LB/Executing+native+SQL

**Comment by nmklong** [comment]
@superkhau so there is no other way? because i already used native above, now i want to use ORM so that the response looks nice and consistent with what i already declared in models files

**Comment by superkhau** [comment]
Not that I know of off the top of my head. @raymondfeng Do you know if there is another workaround?

**Comment by loay** [comment]
Hi @nmklong 
Did you try customizing your variable, then use it with the order filter?

I am not sure what are you trying to do but I can think of something that:

```var customizedField = Customized Function ();```

then within the find function itself, you can use ```order: "CustomizedField <ASC|DESC> " ```

**Comment by nmklong** [comment]
Hi @loay can you explain a bit more, where can i declare that customizedField as a function? and what should i put in the function to customize the order by statement?

As i explained above, this is my issue:

"
The idea is that i finally got an array of ids, which i would like to keep its order, i can do this by doing

ORDER BY FIELD(id, 1399, 8833, 8989, ....)

in sql, however, i can't alter loopback's order by
"

**Comment by jbcpollak** [comment]
I'm interested in something similar. Give a set of points with x and y fields, I would like to do something like this:

`ORDER BY (x-4)(x-4) + (y-3)(y-3)`

In other words, order by distance from a known point.

I realize there is the GeoPoint API, but I need to work in non-Geographical units, and there are other functions that would be handy to have accessed by the database.

**Comment by superkhau** [comment]
@jbcpollak Can you use a custom query? http://loopback.io/doc/en/lb2/Executing-native-SQL.html

**Comment by jbcpollak** [comment]
We are currently using the memory store, but I would have switched to
Postgres if query parameters were supported.

Considering all the warnings at the top of the native SQL page, in
disinclined to give it a try.

Would it be possible to have a 'native where' field in the find()
parameters, so we could stick with the existing API but inject our own
order by and where options?

**Comment by ketansp** [comment]
I need something similar. We should be able to use flexibility of sql inside loopback.
