### ISSUE TITLE
Identify foreign key?

### ISSUE THREAD

**Issue by yahoohung** [strongloop/loopback#2250]
How can we force loopback to check foreign key exist or not before save?

**Comment by jannyHou** [comment]
@yahoohung loopback defines a bunch of operations hooks for model, please check our doc https://docs.strongloop.com/display/public/LB/Operation+hooks to see details, I think what you are trying to use is `before save`

**Comment by yahoohung** [comment]
@jannyHou Thanks for your comment. Is it possible define the foreign key relationship in model.json not just do it one by one in each model?

**Comment by jannyHou** [comment]
@yahoohung Sorry what do you mean by "define the foreign key relationship in model.json"? Could you explain more about this?

From my understanding, each model has its own `modelName.json` file, when you define a relationship from this model, it contains a foreign key, and the relationship is stored in `modelName.json`

**Comment by jannyHou** [comment]
I am closing this issue here, please feel free to provide more details and reopen it if necessary. Thanks.
