### ISSUE TITLE
Does loopback.getCurrentContext() work dependably?

### ISSUE THREAD

**Issue by souluniversal** [strongloop/loopback#2251]
Wondering if loopback.getCurrentContext() actually works dependably and what the issues are. We've had non-stop problems with storing/pulling context using any sort of mechanism similar to the way that loopback.getCurrentContext() appears to work. Why? Various reasons; including everyone/every module using different Promise implementations, some of which play nicely with domains, other which don't. Native Promises don't seem to play nicely using domains.

I see various commentary here regarding loopback here, but not sure where it stands exactly how to resolve:
strongloop/loopback/issues/878
whoGloo/loopback-jwt/pull/2

Also see my extensive comments/perspective on this issue:
nodejs/node/issues/66

**Comment by 0candy** [comment]
Many users have had issues with getCurrentContext. It is unstable and there has been plans of deprecating it: https://github.com/strongloop/loopback/issues/1676

Maybe you can try the alternative to inject remote context via options.
https://github.com/strongloop/loopback/issues/1495

**Comment by 0candy** [comment]
Closing as dup of https://github.com/strongloop/loopback/issues/878

**Comment by souluniversal** [comment]
Thanks, glad I asked and thank you for the clear answer: loopback.getCurrentContext() uses CLS. CLS is definitely not dependable and context breaks in many places (I documented a bit of that here: nodejs/node#66).

Reviewed the solution.  CLS doesn't work. Domains don't work. Both break under quite a variety of conditions. This looks like a great way to get context always injected down into the models. @
