### ISSUE TITLE
Query Params standard ?

### ISSUE THREAD

**Issue by chrisamoore** [strongloop/loopback#2252]
What is the filtering (query parameters) specification for loopback called; ie. `filter[where][name]=foo` ?

What is the syntax called; Odata, hypermedia ... etc ?

And... can I enumerate the query params in the remote definitions / exposure to express them in swagger?

**Comment by chrisamoore** [comment]
There should be a config option in the remote method definition, I am assuming that Strongloop or IBM has encountered this already, and quickly have a solution for me.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterCollectionFormat possibly relevant
I guess each api endpoint on all gets should have the Filter query params added in 2.0

Logically it should hook up here https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Argumentdescriptions

**Comment by chrisamoore** [comment]
cc @raymondfeng @bajtos

**Comment by chrisamoore** [comment]
in the `loopback-component-swagger` I found this... which is kind of not explicit, which I would prefer. 
How would I go about being more explicit here ?

`console.log(swaggerObject.paths['/someroute'].get.parameters);`

```
[ { name: 'filter',
    in: 'query',
    description: 'Filter defining fields, where, include, order, offset, and limit',
    required: false,
    type: 'string',
    format: 'JSON' } ]
```

**Comment by bajtos** [comment]
Hi, the format `filter[where][name]=foo` is a short-hand for `filter={"where":{"name":"foo"}}`, see [qs](https://www.npmjs.com/package/qs#parsing-objects).

I agree we should provide more type information in the generated swagger document. I think we need to register few new types (swagger definitions), at least `FilterParameter` and `WhereParameter`. IIRC, it's possible for models to provide custom swagger definitions via `MyModel.Models` or similar. These new types would be registered in `PersistedModel.setup()` in the LoopBack repository.

**Comment by bajtos** [comment]
Here is the code describing the `filter` argument of the `find` method: https://github.com/strongloop/loopback/blob/4cd84dcd8af5f4f90ff62f506a6bf49e6fc2036b/lib/persisted-model.js#L619-L626

**Comment by chrisamoore** [comment]
@bajtos Thanks for the insight ! any way I can help ?

**Comment by bajtos** [comment]
> Thanks for the insight ! any way I can help ?

@chrisamoore you can try to tweak remoting metadata to use a different type for the `where` argument and then send a pull request with the implementation.
