### ISSUE TITLE
Cached Relations Ignored in Universal (aka Isomorphic) Loopback

### ISSUE THREAD

**Issue by dregre** [strongloop/loopback#2253]
I am playing around with universal (isomorphic) loopback.

I have a remote model called Post with a one-to-one relation to another remote model, Content.

Now consider the following:

```
Post.find({include: 'content'}, function(err, posts){
    var post = posts[0];

    post.content();
    // error: Uncaught TypeError: Cannot read property 'apply' of undefined

    post.content(function(err, post){
        console.log(post);
        // Works, but looking at my network tab a background request was submitted.
    });


});
```

In the above, I try to fetch `Post` and include `Content`.  However, when I try accessing the `content()` getter synchronously, I get an error.  When I access the `content()` method asynchronously (by providing a callback), it succeeds -- but a `fetch` is performed in the background.

If I inspect my `Post`, I notice that it indeed has a `Content` saved in its `__cachedRelations`.  Yet the synchronous getter does not work.

Broken?

**Comment by dregre** [comment]
PS:
Others seem to have run into the same issue.  See, e.g., https://groups.google.com/forum/#!topic/loopbackjs/B3kLIpnRDT4

**Comment by richardpringle** [comment]
Hey @dregre, is this isolated to isomorphic LoopBack? 
Disclaimer: I might not have the answer for you on this one, but worst case, I will find someone who does. 

I'm a little confused with calling `post.content()` as a function. Is that the proper way to use a getter to call a related model? @raymondfeng do you have any insight here?

**Comment by dregre** [comment]
Yeah, I've observed that it is isolated in isomorphic loopback.  Interestingly, the models in isomorphic loopback seem to have slightly different behavior than models in regular loopback.  For example, whereas `MyModel.find()` returns a Promise in regular loopback, in isomorphic loopback you have to pass in a callback in your call to `find()`.

To clarify the use of `Post#content()` -- Post has a relation to another model called Content; that relation is called `content` (it is a `hasOne`).

In the node API (as far as I'm aware), when you define a relation in Loopback a homonymous getter method is created in your model that allows you to get the related object.  If you `include` the relation in your query, you can retrieve the object synchronously (by calling the getter method without arguments).  If you did not use include, then you must get the object asynchronously -- you need to pass a callback.

See, e.g., "Methods added to the model" in https://docs.strongloop.com/display/APIC/BelongsTo+relations

**Comment by raymondfeng** [comment]
@ritch or @kraman You guys have more knowledge about the remote connector and how relations are implemented. Can you chime in?
