### ISSUE TITLE
Document should be updated to support relative paths in bootScripts option 

### ISSUE THREAD

**Issue by supasate** [strongloop/loopback#2258]
In [Defining boot scripts#Boot script loading order](https://docs.strongloop.com/display/public/LB/Defining+boot+scripts#Definingbootscripts-Bootscriptloadingorder), the document states that 

> With something like this:
```
...
bootOptions = { "appRootDir": __dirname, 
                "bootScripts" : [ "/full/path/to/boot/script/first.js", "//full/path/to/boot/script/second.js", ... ] };
boot(app, bootOptions);
...
```
Then the application will then execute scripts in the order specified in the bootScripts array.    Specify the **full directory path** to each script.

Actually, the bootScripts option also supports relative paths (https://github.com/strongloop/loopback-boot/blob/v2.18.1/lib/compiler.js#L70). So, the document should be updated.

**Comment by crandmck** [comment]
I added the following:
>  NOTE: You can also specify a relative directory path.

I'm assuming that addresses this issue.  If not, please tell me what else is required and reopen.  Thanks!

**Comment by supasate** [comment]
I think it's clear. Thanks @crandmck.
