### ISSUE TITLE
Argument sanitizing of related models.

### ISSUE THREAD

**Issue by casamia918** [strongloop/loopback#2263]
[Running Environment]
loopback 2.27.0

I'm trying to implement remote hook that does argument sanitize of related models. 
The example request url is PUT /users/{id}/contacts. I show you my code.

```
[models/user.json]
....
   "relations": {
    "contacts": {
      "type": "hasMany",
      "model": "contact",
      "foreignKey": "ownerId"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "$unauthenticated",
      "permission": "ALLOW",
      "property": "create"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": [
        "__create__contacts",
        "__findById__contacts",
        "__get__contacts", 
        "__updateById__contacts", 
        "__destroyById__contacts"
      ]
    }

  ],

...


```

```
[models/contact.json]
 "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "owner_gender": {
      "type": "string",
      "required": true
    },
    "friend_gender": {
      "type": "string",
      "required": true
    },
    "phone_number": {
      "type": "string",
      "required": true,
      "index": true
    },
    "friendId": {
      "type": "number"
    },
    "is_mutual": {
      "type": "boolean",
      "required": false,
      "default": false     // <- this is important in this question
    },
    "friend_enrolled": {
      "type": "boolean",
      "required": false
    }
  },

  "relations": {
    "owner": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "ownerId"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "DENY",
      "property": ["friendId", "friend_enrolled", "is_mutual", "ownerId"]
    }
  ],

  "hidden" : ["friendId", "is_mutual", "friend_enrolled", "ownerId"],


```

I want to make some private property in contact model. 
But it seems useless when request comes from relating model model, like 'users/{id}/contacts', this ACL does not block the properties. 
https://docs.strongloop.com/display/public/LB/Accessing+related+models

So I searched and found that remote hook is more proper way to do this. I wrote the simple logging remote hook to see the arguement from request.

```
[api request]
POST /users/{id}/contacts
parameters {
data : {
  "name": "friend 18 of user 1",
  "friend_gender": "m",
  "owner_gender": "m",
  "phone_number": "010-1234-0018"
}
}
```

```
[remote hook in models/user.js]
User.beforeRemote('prototype.__create__contacts', function(ctx, contact, next ){
    console.log(ctx.args);
    next();
  });
```

```
[printed log]
{ data:
   { name: 'friend 18 of user 1',
     friend_gender: 'm',
     owner_gender: 'm',
     phone_number: '010-1234-0018',
     is_mutual: false    // <- this is important in this question
    }
}
```

Look at the line where I'm commented "this is important in this question". 
The 'is_mutual' is the property which I want to make private,  like with  'friendid, friend_enrolled, ownerid'. The only different thing is that this 'is_mutual'  has default value. 
But, because of this, before the 'prototype.__create__contacts' method called, the 'is_mutual' property is set with default value, which makes the sanitizing in remote hook frustrate. 

So I come up with some idea to solve these problems.

1) Create after request hook and make response error when the request data key has one of ["friendId", "friend_enrolled", "is_mutual", "ownerId"] . (But I can't find how to make after request hook. Does this related to loopback middleware? Right?)
2) Modify model structure. Model can have public and private property. So create new model, in this case, ContactPrivate, make 1 to 1 relation, and moves all private data to this model. In this way, I can simply hide all private property from user, but it might cause extra db query burden when do some works with contact model in server. And most of all, it looks like that violate the loopback's model concept. 
3) Set default value in the remote hook, and remove default option in the property definition. In this way, remote hook can sanitize request arguments. 

Which one do I choose? Need advise. Thanks.

Added)  I found a protect properties.
https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Protectedproperties
I removed hidden option in the contact.json and added protected option.

```
  "protected" : ["friendId", "is_mutual", "friend_enrolled", "ownerId"],
```

But it's not working at all! Still the /users/{id}/contacts request get the whole property in the response body. Only hidden property working. But hidden can't block write request.

**Comment by 0candy** [comment]
So hidden property is working for you but you're trying to use remote hook? Could you please provide a sample repo to reproduce this issue?
https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by ambrt** [comment]
It seems that `"protected":["property"] ` works only when model is `included`
and not when its queried by relation using `GET /users/{id}/contacts`

**Comment by casamia918** [comment]
@0candy I created a repository to reproduce this issue.
https://github.com/casamia918/loopback-sandbox

**Model definition**

- user: opened with public api, has many contact
- contact : private model, can only access by users related method (Verb /users/1/contact/{fk}). Have 3 properties and 2 of them are protected property
```
[contact.json]
"properties": {
    "name": {
      "type": "string"
    },
    "friendId": {
      "type": "number"
    },
    "is_mutual": {
      "type": "boolean"
    }
  },
"protected": ["friendId", "is_mutual" ]
```

**Bug occur** 

When API request with GET /users/{id}/contacts, all the contact properties are responsed. The 'friendId' and 'is_mutual' properties are defiend with protected. But it does not working

**STR**

1. Clone the respository and install npm modules

2. Login with user1 (I created 2 users in boot script)
  ```
  POST /users/login
  {
    "email" : "user1@test.com",
    "password" : "asdfasdf"
  }
  ```

3. Set access token

4. Get contacts owned by user1@test.com
  ```
  GET /users/1/contacts
  ```

5. After step 4, the response body has
  ```
  [ {
      "name": "contact1 of user1",
      "friendId": 11,
      "is_mutual": false,
      "id": 17,
      "ownerId": 1
    },
    {
      "name": "contact2 of user1",
      "friendId": 21,
      "is_mutual": false,
      "id": 18,
      "ownerId": 1
    }]
  ```

  What I intended is "is_mutual" and "friendId" field is hided on the client side. But it responses full field.

6. *(Additional step)* When I change the 'protected' option to 'hidden', the 'friendId' and 'is_mutual' fields are hided in the response boy, looks like no problem. But when I update the contact, with below api request
  ```
  PUT /users/1/contacts/1
  {
      "name": "contact1 of user1",
      "friendId": 20,
      "is_mutual": true,
      "ownerId": 1
  }
  ```
  The 'is_mutual' and 'friendId' fields are updated. Which means, if someone hacks and find the hidden fields name,  he can update the hidden fields and find the hidden fields name, 
  Surely, I can add the beforehook of update methods. But write that hook to the every related model is tedious work.

**Comment by 0candy** [comment]
Thank you for the sample repo. I am able to reproduce the issue. I am labelling this as a bug. In case you're interested, feel free to contribute a PR. :)

**Comment by casamia918** [comment]
I solved this problem using loopback-ds-readonly-mixin. I've enlist the private property to readonly mixin. As the 'hidden' option is working with normal, the only important issue is to block updating of private property, and this is the perfect usage case of readonly-mixin. 

I'd be happy to contribute loopback code, but I'm also worried about mass up the code. So, someday I'll PR when I ready to contribute.
