### ISSUE TITLE
Custom Role ACL with custom AccessToken models

### ISSUE THREAD

**Issue by enceladus** [strongloop/loopback#2264]
I'm having problems restricting access to a specific role when the role has a custom AccessToken model. I have an AdminAccessToken model, inheriting from AccessToken, and an Admin model, inheriting from User. I've set up the relations between the two, and I've created Role and RoleMapping for the Admins (in an "after save" hook). Login works just fine, and the access tokens are created, but when I request a resource that's been restricted by the role, I get a 401. Any reason why this would be?

My ACL is set up [just like the docs](https://docs.strongloop.com/display/public/LB/Creating+a+default+admin+user). The only difference is that I'm not using the User model or the AccessToken model. I'm wondering if there's something hard-coded going on under the hood that I'm not accounting for.

**Comment by enceladus** [comment]
Found this in **role.js**:

```
  Role.resolveRelatedModels = function() {
    if (!this.userModel) {
      var reg = this.registry;
      this.roleMappingModel = reg.getModelByType(loopback.RoleMapping);
      this.userModel = reg.getModelByType(loopback.User);
      this.applicationModel = reg.getModelByType(loopback.Application);
    }
  };
```

Does Role support custom user models?

**Comment by davidcheung** [comment]
Hi @enceladus, looking into this, is your custom user extended from the built-in user model? or its completely custom? 
It does support extended custom user models, [our example](https://github.com/strongloop/loopback-example-access-control/blob/master/common/models/user.json) is also extending from the user model. 

It would probably be the easiest if you can provide a sample-repo so it's easier to look into the issue.

**Comment by davidcheung** [comment]
Note sure if I understood the issue completely, just another note that extended user models also inherits the ACL from parent https://github.com/strongloop/loopback/blob/master/common/models/user.json#L36-L100
so this might be what you meant by under the hood?

**Comment by davidcheung** [comment]
@enceladus closing stale issue, please reopen if this is still an issue for you, it would it ideal that you can also provide steps to reproduce. Thanks!

**Comment by codejie** [comment]
i have the same issue when I used custom User and custom AccessToken models, and I found the follow code in model.js:301, I think it is the root cause.
var ANONYMOUS = registry.getModel('AccessToken').ANONYMOUS;

**Comment by ndjathe-ndjathe** [comment]
I have the same problem. Please help!!!

**Comment by ndjathe-ndjathe** [comment]
This work for me.

In addition to custom user and accessToken models as done by @tvdstaaij in #2531 , i have added, customs role, roleMapping and acl model and make them persisted in my datasource.
I also remove the `server.enableAuth()` in the server/boot/authentication.js file.
