### ISSUE TITLE
Bug found on relational model

### ISSUE THREAD

**Issue by yahoohung** [strongloop/loopback#2267]
I have tested the following code with mysql and mongodb connector provided by loopback. (loopback-connector-mysql@2.2.1 and loopback-connector-mongodb@1.13.3)

```
GroupCategory.find({
      include: { 
        relation: 'groupTeams',
        scope: {
          where: {id: currentUser.id} 
        }
      },
      where: { teamMemberIds: {inq: [currentUser.id]} }
    }, cb);
```

In mysql, it returns all records even currentUser.id is not in teamMemberIds.
In mongodb, it returns correct results.

I have checked the debug details, I don't why it did the following statement.

```
SELECT 'id','teamMemberId','groupCategoryId' FROM 'GroupTeam' WHERE 'teamMemberId'=\'xxx\' AND 'groupCategoryId' IN (1,2,3,4,5,6,7,8,9,10,11,12,13) ORDER BY 'id'
```

Is that means, if I have 1M records in this table, then it will include all IDs in the 'in' condition?

**Comment by jannyHou** [comment]
@yahoohung looking into it. It might take some time to get it work with connectors, will update details later today or tmr.
