### ISSUE TITLE
Apiconnect and Loopback?

### ISSUE THREAD

**Issue by Rajan** [strongloop/loopback#2268]
Great to know that IBM is committed to maintaining Loopback. Will APIconnect always be an optional component or it will be a mandatory part of the loopback framework?

**Comment by raymondfeng** [comment]
It's the other way around, LoopBack is an optional but important component of IBM API Connect. 

There are 4 major components in API Connect:
-  Create (based on LoopBack for Node.js)
- Run (Laptop/on-prem/cloud)
- Manage (API management)
- Secure (Gateway/Data Power)

**Comment by Rajan** [comment]
This is great. Thank you @raymondfeng
