### ISSUE TITLE
Model Inheritance and overwriting parent properties / methods

### ISSUE THREAD

**Issue by manuschiller** [strongloop/loopback#2274]
Hi!

I want to create the the following structure for my models:

```
ParentModel:{
  anyVal1: 10,
  anyVal2: "abc",
  anyMethod: registeredRemoteMethod1,
  anyMethod: registeredRemoteMethod2
}
```

```
ChildModel1:{
  //anyVal1: 10, not set, should be inherited from ParentModel
  anyVal2: "def", // set, should overwrite ParentModel.anyVal2
  //anyMethod1: registeredRemoteMethod1, not set, should be inherited from ParentModel
  anyMethod: registeredRemoteMethod2 // // set, should overwrite ParentModel.anyMethod2
}
```

is a structure like that possible with strongloop / loopback?

**Comment by loay** [comment]
Hi @manuschiller 

Here is how to extend built-in models. 
https://docs.strongloop.com/display/public/LB/Extending+built-in+models

Here is how to extend customized models(your own models):
https://docs.strongloop.com/display/public/LB/Customizing+models#Customizingmodels-Extendinganothermodel

Please let me know if you have any questions. Regards

**Comment by manuschiller** [comment]
@loay 
thanks! Does this overwrite the basemodels (I only need to overwrite custom models) properties or methods by default if the properties / methods have the same name?

Or will I have to declare an overwrite explicitly?

**Comment by loay** [comment]
@manuschiller 
For the customized models, the 2nd link should do the trick. 
But let me answer your question with an example, which is from the documentation as well:

When you attach a model to a persistent data source, it becomes a persisted model that extends PersistedModel, and LoopBack automatically adds a set of built-in methods for CRUD operations.

Let's take the `find` method as an example. 
We will try to re-implement the  `Note.find()` to override the built-in find() method.

Let's assume you wrote a boot script for your app:

```
module.exports = function(app) {
  var Note = app.models.Note;
  var find = Note.find;
  var cache = {};
 
  Note.find = function(filter, cb) {
    var key = '';
    if(filter) {
      key = JSON.stringify(filter);
    }
    var cachedResults = cache[key];
    if(cachedResults) {
      console.log('serving from cache');
      process.nextTick(function() {
        cb(null, cachedResults);
      });
    } else {
      console.log('serving from db');
      find.call(Note, function(err, results) {
        if(!err) {
          cache[key] = results;
        }
        cb(err, results);
      });;
    }
  }
}
```

If you still require further explanation, please let me know :)

**Comment by loay** [comment]
Closing this issue. If you are still experiencing the same problem, please leave a comment and I will re-open the case. Thanks.
