### ISSUE TITLE
Model consistency between the Model and it's JSON config

### ISSUE THREAD

**Issue by rblalock** [strongloop/loopback#2275]
A very minor suggestion going through some model config:

In a model's json config, e.g. `mymodel.json`, there is an `options` object.  When the model is rendered, it is changed to `Model.settings` instead of, what I was assuming would be `Model.options`, since that's what the definition is using.  I assume it's getting merged with a few other things and that's the property that it's all attached to.  For consistency and semantic's sake, shouldn't both of them either be `options` or `settings`?

**Comment by Amir-61** [comment]
Hey @rblalock,

Thanks for helping us improve the code. I really appreciate it.

>For consistency and semantic's sake, shouldn't both of them either be options or settings?

Yes consistency is always good...

>When the model is rendered, it is changed to Model.settings

Could you please give me the link to the code or elaborate it when it is changed to `Model.settings`?

Thanks again :-)

**Comment by rblalock** [comment]
I'm not sure when it's changed, I just know that anything under the `options` object, in a model.json file gets merged in to `Model.settings` at some point and that's how you can access it programmatically.

**Comment by Amir-61** [comment]
This is some sort of `enhancement`; but since there is no `enhancement` label available in this repo, I decided to choose `feature` label. Thanks for reporting this...
