### ISSUE TITLE
Pass multiple foreign ids to __link__model

### ISSUE THREAD

**Issue by ambrt** [strongloop/loopback#2276]
Hi

I can link one existing item of related model to instance with:
`instance.__link__model(1, cb);`

Is it possible to do one call with multiple foreign ids?
Or pass array of related instances to it (like linking tags instances to item instance)

**Comment by jannyHou** [comment]
> Is it possible to do one call with multiple foreign ids?
@ambrt we support multiple primary key but not foreign key, please check issue https://github.com/strongloop/loopback/issues/2080 and keep track of further discussion there.

> Or pass array of related instances to it (like linking tags instances to item instance)
I believe you are looking for a `embedsMany` relationship from item to tags, please check our doc for more details:
https://docs.strongloop.com/display/LB/Embedded+models+and+relations#Embeddedmodelsandrelations-EmbedsManywithbelongsTo

**Comment by ambrt** [comment]
Ok @jannyHou, thanks for info.
