### ISSUE TITLE
Cannot access 'req' object in mixin

### ISSUE THREAD

**Issue by vasanthps-rm** [strongloop/loopback#2277]
Hello,

I have a mixin that looks somewhat like this:-
```
Model.updateLog = function(ctx, next) {
    console.log(ctx.req); //undefined
};
Model.observe('before save', function(ctx, next) {
    Model.updateLog(ctx, next);
});
```

Is there any other way to access the 'req' object?
I don't want to use the 'currentContext' feature available in loopback

Thanks

**Comment by davidcheung** [comment]
Hi @vasanthps-rm , you can try to use the [remote hooks](https://docs.strongloop.com/display/public/LB/Remote+hooks#Remotehooks-Contextobject) to get the `req` object

```javascript
Peasant.updateLog = function(ctx, next) {
    console.log(ctx.req); 
    next();
};


Peasant.beforeRemote('**', function(ctx, next) {
    Peasant.updateLog(ctx, next);
});
```

**Comment by davidcheung** [comment]
Also please note that we would like to encourage users to post [questions](https://github.com/strongloop/loopback/wiki/Questions) on our Google Forums as we only accept bug reports and feature requests through Github issues, closing this issue, please feel free to reopen.
