### ISSUE TITLE
Info on extending the built-in User model is confusing

### ISSUE THREAD

**Issue by amuramoto** [strongloop/loopback#2278]
In most samples and docs, the 'User' model is extended as 'user'. This is confusing and should probably be changed to something like 'customer' or 'customUser' for the purposes of examples.

Listing the pages/repos that could use updating:
- https://github.com/strongloop/loopback-example-user-management
- https://docs.strongloop.com/display/public/LB/Managing+users

**Comment by superkhau** [comment]
Another reference issue: https://github.com/strongloop/loopback-example-access-control/issues/73
