### ISSUE TITLE
Strong Loop aggregation support?

### ISSUE THREAD

**Issue by Virendra-Developer** [strongloop/loopback#2281]
How can i use aggregation or it's alternate in strong loop?

**Comment by Amir-61** [comment]
@Virendra-Developer 

If I understood you correctly, you are asking for database aggregate function? There is some documentation for some aggregate functions [here](https://docs.strongloop.com/display/public/LB/MongoDB+connector#MongoDBconnector-Aggregate(groupby)query). @crandmck @superkhau Do we have any more documentation for this?

Thanks

**Comment by crandmck** [comment]
That's all that I know of.  I don't think the standard filters support "group by" AFAIK.

**Comment by Amir-61** [comment]
@Virendra-Developer Hopefully this answers your question. Please feel free to open a specific feature request you think it will be useful. I'm closing this issue...

Thanks!
