### ISSUE TITLE
Can't install Loopback - unmet peer dependency

### ISSUE THREAD

**Issue by victorhqc** [strongloop/loopback#2285]
When I run 
```sh
npm i -g loopback
```

I get the following error `UNMET PEER DEPENDENCY loopback-datasource-juggler@^2.19.0`

![captura de pantalla de 2016-05-03 10-06-26](https://cloud.githubusercontent.com/assets/726113/14987878/fa56eb40-1116-11e6-93e5-3c1162219fc0.png)

I got Node `v6.0.0` and NPM `3.8.8`

The funny thing is that I can use loopback commands `slc loopback:command` but I'm having issues with the relation generator, and I'm pretty sure this is error is related. Any Ideas?

**Comment by victorhqc** [comment]
My bad, wrong package installed

**Comment by PremKiran** [comment]
Hi there, could you shine a little more light. Which package was wrong?

**Comment by ddbaron** [comment]
I think he means he should have installed as 
```npm install -g strongloop```

**Comment by PremKiran** [comment]
Hi there,


Thanks for your reply.I have been installing as you said "npm install -g strongloop"

Alas still getting the error. Not that I think it is troublesome, however it would be nice not to have any errors.

**Comment by victorhqc** [comment]
Just as @ddbaron 

```sh
npm install -g strongloop
```

I got confused when I was doing it, loopback is just a part of the whole strongloop environment. Try removing global path for strongloop (and possible loopback) libraries, clear cache and try again.

**Comment by PremKiran** [comment]
Hi there,
Thanks for your help guys. I finally managed to get it working. Yay!
And there was much rejoicing throughout the land.
