### ISSUE TITLE
Property setters and getters

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback#2293]
Hi guys, I would like to know how safe is the usage of **setter** and **getter** properties from model class.

This is already being used in loopback user model and can be seen here: [User Code](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L609)

Why is this not documented anywhere? Can we use it?

**Comment by crandmck** [comment]
I'll try to find time to add docs for it.  See also http://stackoverflow.com/questions/24223329/how-do-i-create-getter-and-setter-overrides

**Comment by crandmck** [comment]
@richardpringle Can you help to clarify this so I can document? Here are some questions I have:
- Why would one want to do this (examples)?
- Can you do it for any model or just for built-in models?  The example referred to above is for a built-in model.
- In `<Model>.setter['myProp'] = function(val) {};` is `val` just the value of the property being set (that you can then manipulate)?  That's what it looks like from the example in `user.js` but I want to confirm.
- As asked above, is this safe to do?

**Comment by richardpringle** [comment]
@crandmck, I would talk to @raymondfeng about this. I haven't used *setters* or *getters* within LoopBack nor have I seen them used on a user-defined model, so I don't have an example but they are generally used to *get* and *set* private variables.

The code that defines them is in the [model-builder](https://github.com/strongloop/loopback-datasource-juggler/blob/3113333cb2ab62ad3863fc5ceee856a4facb37cb/lib/model-builder.js#L250) in `loopback-datasource-juggler` if that helps at all.

@raymondfeng, would also be a good person to consult with on how much you should document and where that documentation should be located. I don't believe that using *getters/setters* is a typical use case for models for the typical LoopBack user and could confuse people starting out with LoopBack.

**Comment by crandmck** [comment]
@raymondfeng Please advise ^.
