### ISSUE TITLE
impossible to create proper unit tests

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback#2294]
I have not been able to create isolated unit tests for my models. I strongly advise to publish example tests in the code base.

However, I have a feeling this is not possible due to tight coupling of code parts.
I have tried to discuss this previously, but did not really find a listening ear.
I strongly believe the initialization of models should be synchronous, and without dependencies. Attaching of datasources, and any other dependent functionality should be done in a subsequest phase. This allows us to work with models as is, and set up proper unit tests.

**Comment by superkhau** [comment]
We have a lot of work planned for refactoring LoopBack for testing in the works. As for your proposal, it is too generic for us to act on. If you have something specific you want to fix, feel free to submit a PR or open an issue for a specific feature. See https://github.com/strongloop/loopback/wiki/Reporting-issues
