### ISSUE TITLE
remoteMethod with multiple arguments, including a model

### ISSUE THREAD

**Issue by alebarreiro** [strongloop/loopback#2295]
Is possible to have multiple arguments when we are using a model type as an argument too?

For example:

```{javascript}
module.exports = function(ServiceRequest) {
  ServiceRequest.schedule = function (serviceRequest, service, cb) {
    console.log(serviceRequest); //logs the model
    console.log('SERVICE ID', service); //logs always undefined
    cb(null, serviceRequest);
  };

  ServiceRequest.remoteMethod('schedule', {
    description: 'Make a new schedule request',
    accepts: [
      {arg: 'serviceRequest', description: 'Service Request model', type: 'ServiceRequest', http: {source: 'body'} },
      {arg: 'service', description: 'Service id', type: 'string'}
    ],
    returns: {arg: 'data', root: true},
    http: {
      path: '/schedule',
      verb: 'post'
    }
  });
};
```

Using the Strongloop API Explorer, I can see defined the endpoint with the ServiceRequest model definition, and an input to enter the serviceId. 
But in the ServiceRequest schedule function, the parameter serviceId always have the value ``undefined``, and the model have the correct value.
I think that the problem is that http source body takes the whole body request. But if I don't use http source body, the Strongloop API Explorer does not recognises the model definition in the endpoint. 

Any solution in order to use the model definition and other arguments in the same endpoint?

**Comment by richardpringle** [comment]
Hey @alebarreiro, you most definitely can!

I'm not quite sure what's going wrong in your case. `service` should be populated if you enter a value into the field in Explorer. 

You could also try passing in the `service` argument as a query string. 

Checkout the `options` argument for `sharedMethod`:
https://apidocs.strongloop.com/strong-remoting/#sharedmethod
and in particular `accepts.http.source`.

That `options` object is the same one you pass to `remoteMethod`. The query string is probably your best bet if you don't want to pass it in as a part of the request body.

Let me know if it works! Also, if you fork the [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and re-create your example, I can always take a look at the code and play around with it too.

Good luck!

**Comment by alebarreiro** [comment]
Hi @richardpringle 

Here you can find the issue: https://github.com/alebarreiro/loopback-sandbox

I have added 4 endpoints. In the first one (schedule1) you can see that the explorer recognises the model, and the service input, but in the in the function schedule1 ```service``` has the value ```undefined```.
There are 3 more examples (schedule2, schedule3, schedule4) that the explorer does not recognise the model definition. 

Add a query string is not exactly what I looking for, in this example I just using a second parameter as a string, but probably it will get complex.
Another workaround is create a model (not persisted) with all the data that I need.

Thanks!

**Comment by richardpringle** [comment]
So there's a better way to do this. A typical REST API won't force the user to submit the model instance that they want to perform an action on. I would suggest creating a prototype method instead. For example: `/api/ServiceRequest/:id/schedule`.

Although, I am aware that you haven't added any of the actual logic that you want to perform. The `schedule3` method actually worked fine for me, which made be realize that there is one thing that you are doing wrong. The `accepts[0].type` should be a [LoopBack Type](https://docs.strongloop.com/display/public/LB/LoopBack+types). There is no automated model validation that happens on the request input, so it would not be useful to have such a type of `ServiceRequest`. If you want to perform that validation, you have to use either operation hooks or remote hooks (in this case I would probably use `beforeRemote('schedule', function(...) {...})`.

I don't think that there are actually any bugs here so I am going to close this issue (just for issue tracking purposes) but I can continue to help.

Tell me what it is that you want to accomplish and I will try to advise. I think that this can be done using the PersistedModel, I don't think you need to create a bunch of custom endpoints yourself.
