### ISSUE TITLE
idInjection and forceId do not work in MongoDB embedded documents

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback#2302]
Let's say I have the following user document schema for mongodb
**app-user.json:**

``` javascript
{
  "name": "AppUser",
  "plural": "users",
  "base": "User",
  "strict": true,
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "username": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "profile": {
      "type": "embedsOne",
      "model": "UserProfile",
      "property": "userProfile",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
  },
  "acls": [],
  "methods": {}
}

```

and **userProfle Schema (user-profile.json):**

``` javascript
{
  "name": "UserProfile",
  "base": "Model",
  "strict": true,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "firstName": "string",
    "lastName": "string"
  },
  "validations": [],
  "acls": [],
  "methods": {}
}

```

_Note that I assign UserProfile to a **transient** data source and AppUser to **mongo** data source_

With this setup, the userProfile embedded document of AppUser gets assigned an id property! It ignores the forceId and idInjection settings..

In order to avoid it I have to set `id:false` in UserProfile - properties in JSON definition...

**Comment by superkhau** [comment]
Sounds like a bug, can you provide a sample repo for us to verify? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by mitsos1os** [comment]
I have created the Repo here: https://github.com/mitsos1os/loopback-sandbox

Steps to reproduce are

1. Create a new customer with POST to **/Customers** with data such as:
  ```
  {"name":"Jim"}
  ```
  The customer record gets created with id:1

2. Create an address for customer with POST to **/Customers/1/address** with data:
  ```
  {"street": "Washington st"}
  ```
You will see that the address is created with an id although `forceId` in customer.json  and `idInjection` in address.json are set to false.

Please note that this is also related to how embedded models are created with a single request for parent document. What I mean is that if I actually **did** want an id to be auto generated, then by posting a complete customer document such as:
```
{
  "name": "Jim",
  "billingAddress": {
  	"street": "Washington st"
  }
}
```
The id **should** be generated. But it is not. The same goes for `embedsMany` relationship. Maybe this could go to a different issue, but I thought it is related that's why I mention it here

**Comment by dpasqualin** [comment]
@mitsos1os , any news on this? I'm facing a similar issue.

**Comment by mitsos1os** [comment]
@dpasqualin No news yet. I think it should be in general that embedsOne relations are identified by their property from the parent model and no Id is needed whatsoever. It's **one** after all ! :-)
EmbedsMany should need the id (if selected) in order to be able to identify which from the list to refer to

**Comment by dpasqualin** [comment]
@mitsos1os , thank you for your answer, I agree with you.

**Comment by pwarelis** [comment]
I can confirm this. I dug around for a bit:

When the model is created in the registry, it gets the 'id' property from the base 'Model'.

You can set 'id': false on the embedded model to force a deletion of the inherited property further down the line in the model builder, but the call "modelDefinition.idNames()" picks up on the id field and adds one anyway.

**Comment by vkruoso** [comment]
Any updates on this? Those inconsistencies are not good the product. This also happens for other databases or it is just MongoDB? Maybe the problem is with the MongoDB connector only.

**Comment by davichoso** [comment]
Nope, same problem with RethinkDB conector, I had to write a before save hook to solve the problem.

**Comment by pwarelis** [comment]
Quickest fix for this is to make the field hidden.
