### ISSUE TITLE
Replace all instances of {href} in user.verify.

### ISSUE THREAD

**Issue by ambrt** [strongloop/loopback#2306]
I just saw that user.verify() replaces only first instance of {href} in text here:
https://github.com/strongloop/loopback/blob/6964914bab64496c789c434fec39d2914231ee23/common/models/user.js#L436

It would be better if instead of:
`options.text = options.text.replace('{href}', options.verifyHref);`

we would use:
` options.text = options.text.replace(/\{href\}/g, options.verifyHref);`

That way we could send email with live link using `<a href="{href}">verify</a>`
and in case someone wouldn't have html email then just plain text in one go.

**Comment by superkhau** [comment]
Would you like to submit a PR?

**Comment by ambrt** [comment]
Its my firs PR :) i hope i made it right  https://github.com/strongloop/loopback/pull/2310

**Comment by richardpringle** [comment]
#2310 was merged to solve this issue: closing.
