### ISSUE TITLE
Redirect url should be urlencoded

### ISSUE THREAD

**Issue by ambrt** [strongloop/loopback#2307]
The user verify link is made in such way that it provides redirect path in the middle of whole link.

The problem is that when one would use `redirect=/#/my-angular-path` then the token is treated as hash valu and isn't read by api (to verify) and api throws error.
Redirect is added on line [407](https://github.com/strongloop/loopback/blob/6964914bab64496c789c434fec39d2914231ee23/common/models/user.js#L407) and token on [431](https://github.com/strongloop/loopback/blob/6964914bab64496c789c434fec39d2914231ee23/common/models/user.js#L431).

I would just remove:

```
   '&redirect=' +
      options.redirect;
```

from line 407 and put it behind 
`options.verifyHref += '&token=' + user.verificationToken;`
on line 431

**Comment by superkhau** [comment]
Can you provide a sample repo for us to reproduce your issue?

**Comment by ambrt** [comment]
@superkhau  Here's a sample of it https://github.com/ambrt/loopback-sandbox

**Comment by superkhau** [comment]
@davidcheung Reassigning to you as this is your FA.

**Comment by davidcheung** [comment]
@ambrt if we also url encode the redirectUrl would this already not be a problem? it is altering the url?

**Comment by ambrt** [comment]
Hi @davidcheung 
Yes, I think that url encode  [here ](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L425) and url decode [here](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L790) would solve the problem.

**Comment by davidcheung** [comment]
actually i believe that would also mean if the url has parameters it will also be lost, we should fix this

**Comment by bajtos** [comment]
Closing in favour of https://github.com/strongloop/loopback/pull/3185.

**Comment by bajtos** [comment]
Fixed.
