### ISSUE TITLE
Filters On LoopBack API's on Date Field

### ISSUE THREAD

**Issue by Surender246** [strongloop/loopback#231]
Am trying to apply filter on date field on api's URL with greater than current date or less than current date or equal to current date.Please help me how to use filters on date field because i want to display only those fields using filter.Am attaching a screenshot of using the filter which gives me the error.

![errordate](https://cloud.githubusercontent.com/assets/6521334/2666825/3d1e947a-c0a4-11e3-99a2-717c2076a932.JPG)

**Comment by foodaka** [comment]
is the date format in the database a string? Does it work for comparing string dates in DB? Or does the date in DB need to be unix int?
