### ISSUE TITLE
can ACL.checkAccessForToken support customed accessType ?

### ISSUE THREAD

**Issue by roytan883** [strongloop/loopback#2314]
currently the 

```
ACL.checkAccessForToken(token, model, modelId, method, callback)
```

can't define accessType, internally it use ACL.ALL
If I call ACL.checkAccessForToken() directly, it lead the calculate score wrong, ACL rules "*" always get high score, sepcified "READ" and "WRITE" not used.

I tried passing accessType "READ", "WRITE" to this function, which used to new AccessContext internally.
Then ACL.checkAccessForToken works as expect. 
Now I can use ACL control access without HTTP. My own transport layer can use loopback Model and ACL directly, like "mqtt, websocket, nats"

I create  a modified function which works fine, maybe you can add it to main branch:

```
ACL.checkAccessForTokenRt = function(token, model, modelId, method, accessType, callback) {
    assert(token, 'Access token is required');

    var context = new AccessContext({
      accessToken: token,
      accessType:accessType,
      model: model,
      property: method,
      method: method,
      modelId: modelId
    });

    this.checkAccessForContext(context, function(err, access) {
      if (err) {
        if (callback) callback(err);
        return;
      }
      if (callback) callback(null, access.permission !== ACL.DENY);
    });
  };

===========================
with Role in boot.js

Role.registerResolver('$teamMember', function(role, context, cb) {
    if (role == '$teamMember' && context.accessToken.id == "uid333"){
      console.log("registerResolver uid333 is $teamMember")
      cb(null, true)
    }
    else {
      cb(null, false)
    }
  })
===========================
ACL config in x.json
{
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$teamMember",
      "permission": "ALLOW"
    }
============================
Now, use it without HTTP, in my own transport layer
ACL.checkAccessForTokenRt({id:'uid333'}, request.model, "", request.method, model._getAccessTypeForMethod(request.method), (err, allowed) !->
    # if allowed, then call model method directly
 )
```

**Comment by jannyHou** [comment]
@roytan883 Thanks for your suggestion, could you explain more about 
> it lead the calculate score wrong, ACL rules "*" always get high score, sepcified "READ" and "WRITE" not used.
?
I am a little confused with what `calculate score` means?

**Comment by roytan883** [comment]
@jannyHou I debug the acl.js of loopback source code, ACL internally calculate each acl principal score, choose the highed score principal as the final result true or false. 
As the doc says, the more specified rule will override Wildcard rule. But currently the result is wrong,  the wildcard rule always get highest score. The reason is 'new AccessContext' default use '*' as the accessType. 
For example, if i call 'xxx.find' it should be "READ" accessType, but when I debug it, it use '*', so it always match the wildcard rule to highest score. 
Then i create a modified checkAccessForTokenRt which can pass parameter accessType.

**Comment by roytan883** [comment]
@jannyHou 
For example, if i have those ACL for model 'project'
```
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$teamMember",
      "permission": "ALLOW"
    }
  ]
```
If i call project.find and Role match $teamMember, it should be "ALLOW". But currently, the ACL.checkAccessForToken return false. 

But my modified ACL.checkAccessForTokenRt return true, because model._getAccessTypeForMethod(request.method) pass accessType "READ" to it.

**Comment by jannyHou** [comment]
@roytan883 makes sense. It's a acl problem. Would you mind create a pr to implement it?

**Comment by biancajiang** [comment]
seeing the same pb.  

I have a "relManager" registered by Role.registerResolver and the following ACLs which works on WRITE.

"acls": [
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "WRITE",
      "principalType": "ROLE",
      "principalId": "relManager",
      "permission": "ALLOW",
      "property": "updateAll"
    }
  ]

But app.models.ACL.checkAccessForToken(myAccessToken, 'myModel', myModelId, 'updateAll') always gives me false.   I see accessType="*" in debugger and my "relManager" resolver never gets called.

**Comment by biancajiang** [comment]
Our workaround until this is fixed is using ACL.checkAccessForContext() instead with an extra "accessToken" for the context:

var context = {
         accessToken: myAccessToken,
         model: MyModel,
         property: 'updateAll',
         modelId: myModelId,
         accessType: 'WRITE'
       }

       app.models.ACL.checkAccessForContext(context, ...)
