### ISSUE TITLE
Multi level model relation and querying 

### ISSUE THREAD

**Issue by smurali1717** [strongloop/loopback#2315]
modelD.JSON
{
  "name": "modelD",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "userID": {
      "type": "string",
      "id": true
    },
    "age": {
      "type": "number"
    },
    "city": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "ModelE": {
      "type": "hasOne",
      "model": "modelE",
      "foreignKey": "userID"
    }
  },
  "acls": [],
  "methods": {}
}
------------------------------------------------------------------------------------------------------------------------------
modelE.JSON
{
  "name": "modelE",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "userID": {
      "type": "string",
      "id": true
    },
    "propertyA": {
      "type": "string"
    },
    "propertyB": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "ModelF": {
      "type": "hasOne",
      "model": "modelG",
      "foreignKey": "propertyA"
    }
  },
  "acls": [],
  "methods": {}
}
------------------------------------------------------------------------------------------------------------------------------
modelG.JSON

{
  "name": "modelG",
  "base": "modelE",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "propertyA": {
      "type": "string",
      "id": true,
      "required": true
    },
    "detail": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

In ModelD.js I am writing custom method to get nesting query but I am just getting one level output

ModelD.find({
			"include":{
				"relation":"ModelE",
				"scope":{
					"include":{
						"relation":"ModelF"
					}
				}
			}
		}, function(err, results) {
		   if(err) return cb(err);
        //err={"error":"Super error"}
        console.log("error message is " + err);
           cb(err, results);
		});

my output is:

[
  {
    "userID": "123",
    "age": 31,
    "city": "Madurai",
    "ModelE": {
      "userID": "123",
      "propertyA": "31",
      "propertyB": "Madurai"
    }
  }
]

my expetation is 

[
  {
    "userID": "123",
    "age": 31,
    "city": "Madurai",
    "ModelE": {
      "userID": "123",
      "propertyA": "31",
      "propertyB": "Madurai",
      "ModelF":{
          "propertyA":"31",
          "details":"property 31 details"
      }

    }
  }
]

Here I am not getting ModelF relation value, can you please help me to get the output

**Comment by 0candy** [comment]
Should be:
```ModelD.find({include: ['ModelE', 'ModelF']}, function() {
  ...
});```

**Comment by smurali1717** [comment]
I tried above one but I am getting the below response:
{
  "relationA": [
    {
      "userID": "123",
      "age": 31,
      "city": "Madurai"
    }
  ]
}

**Comment by 0candy** [comment]
Hi @smurali1717, I created a sample repo with a working example. The problem with your config was the model E has the wrong primary key. The primary key should be propertyA and not userId as the reference to modelF is depending on that.

https://github.com/0candy/modelrelation

**Comment by smurali1717** [comment]
Super Candy! Thank you so much for your kind help! it works like charm.
