### ISSUE TITLE
Models base class should be selected as Persisted class by default

### ISSUE THREAD

**Issue by cgole** [strongloop/loopback#2318]
Right now when you create an empty loopback server, by default the base class is Model and not Persisted. We should switch this so Persisted class is default

https://media.github.ibm.com/user/3069/files/c9efc7d2-15d6-11e6-9192-f81a3ab4b747

**Comment by raymondfeng** [comment]
It does not make sense to use `PersistedModel` as the base if no datasource is present. If you create a datasource before trying to create a model, the base will be default to `PersistedModel`.

**Comment by ritch** [comment]
Closing... this is 100% intentional.

**Comment by superkhau** [comment]
@crandmck Do you want to add a note about this somewhere in the docs regarding scaffolding models?
