### ISSUE TITLE
afterRemote never get executed on __get__identities remote method

### ISSUE THREAD

**Issue by JoeShi** [strongloop/loopback#2321]
I have a user model which `hasMany` `userIdentity`, the relationship name is `identities`. 

```
{
  "name": "user",
  "base": "User",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "accessToken",
      "foreignKey": "userId"
    },
    "identities": {
      "type": "hasMany",
      "model": "userIdentity",
      "foreignKey": "userId"
    },
    "credentials": {
      "type": "hasMany",
      "model": "userCredential",
      "foreignKey": "userId"
    }
  },
  "acls": [
    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "__get__identities"
    }
  ],
  "methods": {}
}
```

I defined the following in user model. However, when I call `GET /users/me/identities`, it returns me the correct resource, but the afterRemote never get executed.

```
  User.afterRemote('__get__identities', function (context, identities, next) {
    console.log('after __get__identities');
    next();
  })
```

I just followed the [remote hooks example](https://docs.strongloop.com/display/public/LB/Remote+hooks#Remotehooks-Examples), but not working on this method.

**Comment by gunjpan** [comment]
@JoeShi : Hey Joe, it is not invoking the remote method as `User.afterRemote('__get__identities',...` referring to a `static` method with name `__get__identities`, not an `instance`/`protoype` method.
As explained [here](https://docs.strongloop.com/display/public/LB/Accessing+related+models):LoopBack automatically creates a set of related **model methods**. 
Thus, `__get__identities` being an instance method, changing the afterRemote as following should resolve the issue:
```JavaScript
User.afterRemote('prototype.__get__identities', function (context, identities, next) {
    console.log('after __get__identities');
    next();
  })
```
or, using [Wildcard](https://docs.strongloop.com/display/public/LB/Remote+hooks#Remotehooks-Wildcards):
```JavaScript
User.afterRemote('*.__get__identities', function (context, identities, next) {
    console.log('after __get__identities');
    next();
  })
```

Closing this now, if you need further assistance with it, please feel free to reopen the issue and mention me in the comments, will be happy to assist :)

**Comment by JoeShi** [comment]
Great thanks.
