### ISSUE TITLE
[doc] Improve Model.setup() function documentation

### ISSUE THREAD

**Issue by davidcheung** [strongloop/loopback#2332]
Related to https://github.com/strongloop/loopback/issues/1485
### Objective:
- To educate users to use `model.setup()` function to customize extended models
- It behaves like a constructor, where child will automatically call the parent's constructor
### Use case
- validation inheritance
- customized user and child's setter getters
### example
- the `user.js` is probably the best example we have, in the setup function it uses **property-setters** to do [password hashing](https://github.com/strongloop/loopback/blob/aa47f79ca60349a28f5d79d64261ed99f1c74ad4/common/models/user.js#L598-L617)
- [validation of `email` & `username` uniqueness](https://github.com/strongloop/loopback/blob/aa47f79ca60349a28f5d79d64261ed99f1c74ad4/common/models/user.js#L719-L728)
- setting up [remoteMethods](https://github.com/strongloop/loopback/blob/aa47f79ca60349a28f5d79d64261ed99f1c74ad4/common/models/user.js#L690-L699)
  And all the above is rebuilt into the child model

/cc @crandmck @raymondfeng  @bajtos @richardpringle 
not sure if my information is completely accurate, PTAL

**Comment by bajtos** [comment]
@davidcheung I think your description is good.

There is one caveat of `MyModel.setup()` - it works well for changes made from code, but it doesn't work for settings defined in JSON files, for example ACLs (see https://github.com/strongloop/loopback/issues/2270) and remote methods (https://github.com/strongloop/loopback/issues/2350). I think the documentation should mention these limitations.

**Comment by crandmck** [comment]
Probably should keep this open.
