### ISSUE TITLE
How to use Group by aggregation in loopback remote method

### ISSUE THREAD

**Issue by shakeelmogify** [strongloop/loopback#2333]
```
// To fetch all surveys created by a particular user including other required details
    Survey.createdBy = function(id, cb) {
        Survey.find({
            where : {createdBy: id},
            include: {
                relation: 'group'
            }
        },
        function(err, surveys) { 
            if (err) cb(new Error('Something went wrong!'));
            cb(null, surveys);
        });
    };
    Survey.remoteMethod(
        'createdBy',
        {
            accepts: {arg: 'id', type: 'string', required: true},
            http: {path: '/createdBy/:id', verb: 'get'},
            returns: {type: 'object', root: true}
        }
    );
```
and result is as follows

```
[
  {
    "title": "Tell me about yourself",
    "publish": "yes",
    "id": "56a9011fe14fea482a6b0e17",
    "groupId": "56a63013b18000a16f41963e",
    "createdBy": "56a6384cc578273f73d594f3",
    "created": "2016-05-11T14:58:01.284Z",
    "modified": "2016-05-11T14:58:01.284Z",
    "group": {
      "name": "group 1 by user 1",
      "description": "g1",
      "id": "56a63013b18000a16f41963e",
      "imageId": "566e662949a2f16d31324f79",
      "createdBy": "56a6384cc578273f73d594f3",
      "created": "2016-01-25T14:24:19.221Z",
      "modified": "2016-01-25T14:24:19.221Z"
    }
  },
  {
    "title": "Third demo survey",
    "publish": "yes",
    "id": "56c31cc93e76fcaa41f93d7b",
    "groupId": "56a634e0b18000a16f41963f",
    "createdBy": "56a6384cc578273f73d594f3",
    "created": "2016-05-11T14:58:01.285Z",
    "modified": "2016-05-11T14:58:01.285Z",
    "group": {
      "name": "group 2 by user 1",
      "description": "g1",
      "id": "56a634e0b18000a16f41963f",
      "imageId": "566e662949a2f16d31324f79",
      "createdBy": "56a6384cc578273f73d594f3",
      "created": "2016-01-25T14:44:48.589Z",
      "modified": "2016-01-25T14:44:48.589Z"
    }
  },
  {
    "title": "Tell me about yourself",
    "publish": "no",
    "id": "56ef99e1d103db6969f40165",
    "groupId": "56a63013b18000a16f41963e",
    "createdBy": "56a6384cc578273f73d594f3",
    "created": "2016-03-21T06:51:13.746Z",
    "modified": "2016-03-21T06:51:13.745Z",
    "group": {
      "name": "group 1 by user 1",
      "description": "g1",
      "id": "56a63013b18000a16f41963e",
      "imageId": "566e662949a2f16d31324f79",
      "createdBy": "56a6384cc578273f73d594f3",
      "created": "2016-01-25T14:24:19.221Z",
      "modified": "2016-01-25T14:24:19.221Z"
    }
  },
  {
    "title": "Tell me about yourself",
    "publish": "no",
    "id": "56ef9a52710e3ad46bcfcbc8",
    "groupId": "56a63013b18000a16f41963e",
    "createdBy": "56a6384cc578273f73d594f3",
    "created": "2016-03-21T06:53:06.661Z",
    "modified": "2016-03-21T06:53:06.661Z",
    "group": {
      "name": "group 1 by user 1",
      "description": "g1",
      "id": "56a63013b18000a16f41963e",
      "imageId": "566e662949a2f16d31324f79",
      "createdBy": "56a6384cc578273f73d594f3",
      "created": "2016-01-25T14:24:19.221Z",
      "modified": "2016-01-25T14:24:19.221Z"
    }
  }
]
```
Please help me out how can i group result by **groupId**.

**Comment by richardpringle** [comment]
Wait, I'm confused about the question... @shakeelmogify, what do you mean by "group result"?

Do you want to query based on `groupId` instead of `createBy`? This is confusing because each Survey instance has the same `groupId` as well as the same `creatBy` property.

**Comment by shakeelmogify** [comment]
@richardpringle i think my question is not clear .... actually i am fetching surveys created by a particular user. Each survey belongs to a group and an user can create multiple surveys in a group. So in the result set i want to group all surveys of a group instead of repeated same group with each survey. Hope it clarifies my question. Thank you

**Comment by richardpringle** [comment]
@shakeelmogify, Can a user create surveys in multiple groups? If they can't and you don't want to include the group info you can just remove the `include` filter.

But if they can create surveys in multiple groups,  I might suggest returning an object such as:
```json
{
  {
    group: {...},
    surveys: [...]
  },
  {
    group: {...},
    surveys: [...]
  }
}
```
If you do want your response to look like that, I can help you get there.

My best suggestion for getting help is to fork a [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and set up some dummy models. Please use memory as a datasource too.

If you can, show what you want as an output in the readme (even if you can't get that to work).

**Comment by shakeelmogify** [comment]
@richardpringle, yes, an user can create surveys in multiple group and want same result object as you shown.

**Comment by richardpringle** [comment]
@shakeelmogify, instead of `cb(null, surveys)', you can create a new array of objects as suggested above and do `cb(null, newObj)`. It'll just take some vanilla JS inside the `Survey.find` callback. There currently is no "LoopBack way" to group them as suggested.

I'm going to close this issue, but that doesn't mean that the discussion has to end! If you have any other comments, just mention me and I will still respond and try to help until you get the result you want!

Good luck!
