### ISSUE TITLE
unless in path specification in middleware.json

### ISSUE THREAD

**Issue by rjrahul** [strongloop/loopback#2337]
Can we implement a feature in middleware.json to attach middlewares to a path but skip on some paths.

Requirement is to attach authentication middleware to /api endpoints but not to /api/user endpoint.

**Comment by davidcheung** [comment]
You can try to override the paths, I've had some success changing the order of my middleware as follows
```js
"routes": {
    "./middleware/mymiddleware.js": {
      "paths": "/api/test"
    },
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  }
```
and my regular `/api/{models}` still works while `/api/test` goes to the middleware
@rjrahul please let me know if this solves your problem.

**Comment by rjrahul** [comment]
@davidcheung I have a single middleware authentication which needs to be applied to all (a lot of /api/xxx paths) and skip for some (very few /api/xxx paths). Post this the continuation of other middleware (including rest middleware) needs to be done as common flow.

Your suggestion seems would work in cases where middleware would be different based on paths.

**Comment by davidcheung** [comment]
Hmmm im not too sure what would be a good way to achieve this, 
you can still override all the paths 

```ts
// middleware.json
"routes": {
    "./middleware/mymiddleware.js": {
      "${restApiRoot}"
    },
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  }
```
```js
//mymiddleware.js
modules.export = function(){
  return function (req, res, next) { 
    // you get req._parsedUrl for received request then you can do operations on it
    // do some operation on req._parsedUrl.path
    next();
  }
}
```


I guess another option would be something like [remoteMethod hooks](https://docs.strongloop.com/display/public/LB/Remote+hooks)

**Comment by rjrahul** [comment]
@davidcheung, my requirement is to skip a middleware based on path; while execute the same middleware for other paths. If a middleware is an existing middleware like loopback-component-oauth2#authenticate, the only solution I could think of was to wrap the middleware in another middleware and us it to skip the paths.

Based on your suggestion above, I could figure out my option would be to wrap the middleware in another middleware.

`
//wrap-authenticate.js
modules.export = function() {
  return function (req, res, next) {
    if (req._parsedUrl === /my condition/) {
      return next();
    }
    oAuth2.authenticate(req, res, next);
  }
}
`

This is something that [express-unless](https://github.com/jfromaniello/express-unless) provides. Can we integrate express-unless to paths endpoint?

I was thinking like

`
"routes": {
  "loopback-component-oauth2#authenticate": {
    "paths": [
      {
        "path": "/api",
        "unless": [
          "/api/un-authenticated"
        ]
      }
    ]
  }
}
`

**Comment by davidcheung** [comment]
@rjrahul wondering if youre solution worked,
 the middlewares get executed in orders (by each of them calling `next()`) 
so if you don't call `next()` and send out `res`, you should be able to bypass the default `restAdapter`

**Comment by rjrahul** [comment]
@davidcheung As I mentioned, in my original request, my requirement is to skip a middleware for few paths while executing the remaining handlers.

In the way you are suggesting, I would have to write all the middlewares executed after rest handler again to get desired behavior that is undesirable from code maintenance perspective.

Consider my middleware.json as follows

```
initial: {},
auth: {
  "loopback-component-oauth2#authenticate: {
    "paths": [
      {
        "path": "/api",
        "unless": [
          "/api/un-authenticated"
        ]
      }
    ]
  }
},
routes: {
  "loopback#rest": {}
},
final: {
  "loopback#url-not-found": {}
}
```

In this case if I inject a custom middleware before `loopback-component-oauth2` that returns the response back on /api/un-authenticated endpoint, rest handler does not invoke and therefore the API is not executed.

My requirements is slightly different than this in that I need to execute and return API response rather than returning a 403 or something generic.

Hope, I am able to make my point across to you.

**Comment by davidcheung** [comment]
In the current flow, `res` gets sent out during the `rest-middleware`, which stops it from executing the other middlewares from executing after it as well. 

@bajtos, @gunjpan any thoughts?

**Comment by bajtos** [comment]
@rjrahul's request to attach middleware to a path (e.g. `/api`) but skip it on some sub-paths (e.g. `/api/public`) make sense to me. I don't think there is any elegant solution available right now, except writing a wrapper middleware as shown in https://github.com/strongloop/loopback/issues/2337#issuecomment-223822301.

The config option `unless` sounds too generic to me, how about `excludePaths`?

```json
"routes": {
  "loopback-component-oauth2#authenticate": {
    "paths": [
      {
        "path": "/api",
        "excludePaths": [
          "/api/un-authenticated"
        ]
      }
    ]
  }
}
```

@raymondfeng what's your take?
