### ISSUE TITLE
Remove loopback#errorHandler

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2338]
AFAICT, the only purpose of `loopback#errorHandler` is to provide option `includeStack` that allows user to remove stack traces from error responses in production. However, that's not enough, as other error properties may contain sensitive information too.

We should remove the handler and tell users to use strong-error-handler instead.

To simplify upgrade from 2.x to 3.0, we should preserve the middleware factory but throw a descriptive error instead of returning a handler function.

```js
// server/middleware/error-handler.js
module.exports = function(options) {
  throw new Error('...');
};
```

**Comment by bajtos** [comment]
Here is the implementation of `loopback#errorHandler`:

https://github.com/strongloop/loopback/blob/70cec0755acc2b670987675c3bc63ecbfe9b473f/server/middleware/error-handler.js

I am also cross-posting my comments from a private chat:

If we change `loopback#errorHandler` to use strong-error-handler, then we will couple the version of loopback with the version of strong-error-handler. Then when we make a breaking change in strong-error-handler, we won't be able to upgrade it in loopback until next loopback major version.

OTOH, when people use strong-error-handler directly as a dependency of their app, then they are in control of what version they like to use and when to upgrade to a newer major version. This is a lesson that many popular frameworks learned over time. Express stopped bundling middleware since v4, grunt came to the same conclusion in v1.

**Comment by bajtos** [comment]
We also need to modify the templates in loopback-workspace, but that will be handled by https://github.com/strongloop-internal/scrum-loopback/issues/896.

**Comment by loay** [comment]
connect to: https://github.com/strongloop/loopback/pull/2411

**Comment by fizzl** [comment]
What do I need to do to use strong-error-handler?

I'm trying to upgrade an API project from 2.x to 3.x. I am getting the following error:

"Unhandled rejection Error: loopback.errorHandler is no longer available. Please use the module "strong-error-handler" instead."

**Comment by bajtos** [comment]
@Fizzl

> What do I need to do to use strong-error-handler?
>  I'm trying to upgrade an API project from 2.x to 3.x. I am getting the following error:
>  "Unhandled rejection Error: loopback.errorHandler is no longer available. Please use the module "strong-error-handler" instead."

See https://loopback.io/doc/en/lb3/Migrating-to-3.0.html#update-loopback-version and https://loopback.io/doc/en/lb3/Migrating-to-3.0.html#update-use-of-rest-error-handler

**Comment by fizzl** [comment]
Heh, already deleted my comment because I found the migration documents like 5 minutes after my original comment.

Thank you! :)
