### ISSUE TITLE
How to configure current time?

### ISSUE THREAD

**Issue by casamia918** [strongloop/loopback#2340]
When I command $ date in my mac, the output is

```
$ date
Sat May 14 06:45:57 KST 2016
```

Also, when I run node repl, I can see similar time

```
$ node
> Date()
> 'Sat May 14 2016 06:46:01 GMT+0900 (KST)'
```

But, when I run my loopback app, current time is not consistent with my local time.
This is the first few line when I execute 'slc start' at now. It should be around 6'o clock but the result is

```
2016-05-13T21:49:38.034Z pid:3049 worker:0 INFO supervisor size set to 1
2016-05-13T21:49:38.115Z pid:3049 worker:0 INFO supervisor started worker 22 (pid 4637)
2016-05-13T21:49:38.116Z pid:3049 worker:0 INFO supervisor resized to 1
```

How can I configure loopback process time to my local time?

**Comment by jannyHou** [comment]
@casamia918 If I create the model instance from script code(like script in server/boot folder), it will generate the local time, I created a sandbox to prove it, please check it here:
https://github.com/jannyHou/loopback-sandbox/tree/test/lb-date

Npm install and run the app, you will see the local time printed on console.

But the problem you report also exist, I think https://github.com/strongloop/loopback-example-mixins is a good example to reproduce it:
1. git clone example repo
2. npm install && node .
3. create a dog from endpoint `POST / Dogs`
4. from the response body we can see the date is not a local one:
```
{
  "breed": "string",
  "weight": 0,
  "age": 0,
  "id": 1,
  "createdAt": "2016-05-16T00:00:00.000Z",
  "updatedAt": "2016-05-16T15:39:26.885Z",
  "tag": "string",
  "squirrel": true
}
```
local one should be around this time:
```
{ myDate: Mon May 16 2016 11:55:28 GMT-0400 (EDT), id: 1 }
```
