### ISSUE TITLE
Using default user class has no PUT user/{id}

### ISSUE THREAD

**Issue by devotox** [strongloop/loopback#2342]
I am extending the base User class like

```
{
  "name": "user",
  "plural": "users",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
    "emailVerificationRequired": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "roles": {
      "type": "hasMany",
      "model": "role",
      "through": "RoleMapping",
      "foreignKey": "roleid"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}

```

but i get this error when trying to update a user

```
{"errors":[{"status":404,"source":"","title":"Error","code":"","detail":"Shared class \"user\" has no method handling PUT /2"}]}
```

**Comment by gunjpan** [comment]
hey @devotox, I was unable to reproduce the error. 
Could you please provide me with the steps to reproduce.
Also, I was using loopback-explorer to test the end-points and was able to make a PUT request to an existing instance of user after **logging in**, just want to make sure you're making authenticated requests.
Moreover, if you could please provide the code you have by forking [loopback-sandbox](https://github.com/strongloop/loopback-sandbox), it would be of great help to quickly resolve the issue. Thank you.

**Comment by devotox** [comment]
1. I created a model called user that extended the Base User class
2. created the database table to match the model
3. tried to update the user using the auth token that is specified to that user. 
4. Get that error

**Comment by gunjpan** [comment]
@devotox: I tried to reproduce your issue with same ACLs and couldn't reproduce it. I was able to update existing instance after logging in as that user and making an authenticated request: `PUT user/{id}` with access token.
I am unable to identify the cause without looking at the code; it'll be great if you could share your code. 
Also, please let me know what database you're using.

**Comment by devotox** [comment]
Ok am using postgres database and the code is at https://github.com/DnD-Enterprises/kids-vocab

**Comment by alihalabyah** [comment]
I'm facing the same issue but with get
