### ISSUE TITLE
Upsert operation remove the id that i've been set in instance

### ISSUE THREAD

**Issue by saggafarsyad** [strongloop/loopback#2343]
Let's say i have `OrderPayment` and `Order` model with fields 
- id
- paymentMethod
- amount
- status

The `id ` is not auto-increment. So when I add a new instance, I write the object like this
```
 var payment = {
              'id': 7,
              'paymentMethod': credit_card,
              'amount': 100,
              'status': 1
 }
```

and then i called `upsert` like this
```
OrderPayment.upsert(payment, function (err, orderPayment) {
   // add stuff here
}
```

Since `OrderPayment.id` is a foreign key to `Order.id`, it always error because failed id constraint

I track how my `payment` object changes with Operation hooks `before save`, and I find out that `id` field is always deleted before saving to database

According to strongloop API Docs, upsert is static methods. So what's the point of upsert if the id always removed?

**Comment by superkhau** [comment]
Can you provide a sample for us to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by saggafarsyad** [comment]
I think I found the problem. It seems I try to replace a PersistentModel methods in my custom Soft Delete mixins

  ```

   Model.delete = function(where, cb) {

   }
```
