### ISSUE TITLE
nestRemoting doesn't support multiple levels?

### ISSUE THREAD

**Issue by PaddyMann** [strongloop/loopback#2346]
I am trying to set up API end points like:
- /workspaces
- /workspaces/1/projects
- /workspaces/1/projects/1/sections
- /workspaces/1/projects/1/sections/1/questions

I am able to set up /workspaces and /workspaces/1/projects within my `workspace.json` config file.

I am able to get /workspaces/1/projects/1/sections to work using nestRemoting:

```
module.exports = (app) => {
  app.models.Workspace.nestRemoting('projects');
  app.models.Project.nestRemoting('sections');
  app.models.Section.nestRemoting('questions');
};
```

However, `/workspaces/1/projects/1/sections/1/questions` does not work (although `/projects/1/sections/1/questions` does)

This issue was previously raised by @A11oW in this issue https://github.com/strongloop/loopback/issues/1853 (but the issue had already been closed).

Is there anyway to nest more than 3 levels? The docs suggest it's possible but do not show any examples.

**Comment by PaddyMann** [comment]
A related but separate question...

Having read a load of issues on this:

- One level of nesting has great support. So I can call the following with no problem:
- Two levels of nesting requires nestRemoting. This works in a fundamentally different way to one level of nesting and provides limited functionality:
  - find works
  - count does not
  - It does not update the Swagger page (so anyone using this as part of their testing strategy is now screwed)
- Three levels of nesting does not work (?? - that's my question in the post above)

My question is: Are there any plans to address the issues with Loopback that seem to prevent infinite nesting that works in a consistent way?

**Comment by richardpringle** [comment]
Hey @PaddyMann, I'm not quite sure why this doesn't work. We will have to dig a little further into the issue.

**Comment by davidcheung** [comment]
here is a possible workaround for this issue https://github.com/strongloop/loopback/issues/1859#issuecomment-163037446
related https://github.com/strongloop/loopback/issues/1865, https://github.com/strongloop/loopback/issues/1866

**Comment by richardpringle** [comment]
The above workaround is not ideal...

**Comment by PaddyMann** [comment]
Thanks @richardpringle , @davidcheung 

I'm not sure if the above workaround would work here. 

For example, if I was to add a remote route to `Workspace` with the path `/workspaces/:workspaceId/projects/:projectId/sections/:sectionId/questions`, then I'd have write a custom function that gets questions that meets the other criteria. 

This would work if it was an issue I was only facing in one place, but that's not the case. And if I was to try and make the code reusable for other routes, I'd end up rewriting most of the ORM functionality which would seem a little crazy :)

But maybe I've missed something in what you're suggesting...

**Comment by bajtos** [comment]
This looks like a limitation of the current implementation of `nestRemoting` to me, thus the `feature` label is more appropriate than `bug`.

**Comment by AndreMaz** [comment]
Hello @PaddyMann how did you solve this issue?

I facing a similar issue. I want to build the following endpoint

- House/{id}/rooms/{id}/lightSensors/{id}/readings/{id}

However with `nestingRemote()` I'm only able to get to the

 - House/{id}/rooms/{id}/lightSensors/{id}

and can't go to the deeper levels such as:

-  House/{id}/rooms/{id}/lightSensors/{id}/readings
-  House/{id}/rooms/{id}/lightSensors/{id}/readings/{id}

Is there any workaround to achieve this?

**Comment by PaddyMann** [comment]
Hej @AndreMaz 

We've initially tried to reduce the number of levels involved, trying to keep it to two. The downside is you need to have additional logic in your `role-resolver` to handle the parent levels. Currently only a fraction of our API has been moved over so I'm not 100% certain this will be the long term solution.

I've also hit a number of Loopback limitations that have led us to overide the default remote methods for the majority of routes - e.g.:
- Can’t handle REST URLs more than one child deep
- Can’t apply an order on a has-many-through relation 
- has-many-through returns duplicate records
- Can’t always get hold of the current userId
- Limited support for composite keys

(so one option would be to go the whole hog and disregard the magic routes such as __get__rooms, instead handcranking them all)

**Comment by AndreMaz** [comment]
Thanks @PaddyMann 

This limitation is a huge drawback and kinda reduces the utility of the whole framework. Instead of just worrying about the data model and (supposedly) the rest of the logic were done by the framework we now have to keep in mind that only two levels are supported and use workarounds to go further...

@bajtos @pthieu @davidcheung @richardpringle is there any prediction about where (and if) this issue will be solved?

**Comment by davidcheung** [comment]
@AndreMaz I'm afraid i dont have a ETA on this feature, I will unassign myself for now as I won't have the bandwidth to work on this issue. If anyone can open a PR and give it a try would be great

#### possible things to be worked on
- [ ] need to rewrite https://github.com/strongloop/loopback/blob/4c9c6236e3ea04875034a8d7fea0e09529d1beed/lib/model.js#L898-L971 
  - handle multiple nested `__findbyid__books__pages`  regex
- [ ] traverse down from parent to get getter of child, need to ensure ACL rules applied per level
- [ ] need to rename `fk`/`nk` to be dynamic in the remoting options to avoid conflict, maybe like `pageId`, `BookId`

cc @bajtos @pthieu

**Comment by darko86** [comment]
Hi. Reading above, this seems like exact issue I'm having. I need support for more than 2 level child models e.g:

api/first/:id/second/:id/third/:id/**fourth/:id**

Is there any plan to integrate this and what are the timeframes? It seems there was no progress on this for a while. I'm sure there's a lot of people that are after this.

Is there any workaround for this??

Thanks

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be adding any new features.
