### ISSUE TITLE
update relation after add?

### ISSUE THREAD

**Issue by upupzealot** [strongloop/loopback#2351]
I have a model named User which has thousands of instances there.
Now I add a new hasOne relation to it, hope that each of them would have an "account".
And it works for new created users. 
But how can I create accounts for the existed users?

**Comment by gunjpan** [comment]
@upupzealot: Hi, adding a relation establishes a connection between two models by means of a foreign key. and to update the data, you can take the following approach:
- use [`include`](https://docs.strongloop.com/display/APIC/Include+filter) filter to query a related model and identify the instances with no accounts.
- for each of those accounts, you can create new account instances using [`create`](https://docs.strongloop.com/display/APIC/Creating%2C+updating%2C+and+deleting+data)

hope that helps. Should you have any questions/concerns, please let me know.

**Comment by upupzealot** [comment]
@gunjpan Thanks for replying. So after all I have to do that manually?
I thought there may be some auto way there.

**Comment by gunjpan** [comment]
@upupzealot :
>So after all I have to do that manually?

yes, I believe so. 
As you're adding the relation after already having Instances, by your design, it seems you want to set a generic/same account for each user w/o any account. In that case, you can iterate over the the instances - with no accounts - and set their accounts and this will be a one-time thing.

Hope that answers your question, please let me know if this is good to close. Thanks.
