### ISSUE TITLE
How to modify api description for automatically generated apis on loopback api explorer.

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback#2353]
Hi, 

Firstly, Thanks you all for a fantastic open-source.

I've a question that how to modify apis description for automatically generated apis on loopback api explorer.  For example I have an api to create friends (POST /friends/ ) and I want to add some additional description for how to use this api, what are acceptable params, etc ....

Can someone please provide a solution for this ? 
Many thanks.

**Comment by gunjpan** [comment]
@dongmai: To begin with: Is your endpoint `POST /friends/` generated by a [`remoteMethod`](https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-Howtodefinearemotemethod), if yes, you can easily provide the description while registering your method as follows:

```javascript

MyModel.remoteMethod('friends',{
  description: 'say how cool your method is',
  accepts: {...},
  returns: {...},
  http: {  path: '/', verb:'POST'}
});
```

**Comment by dongmai** [comment]
@gunjpan , Thank for the reply.

But `POST /friends/` endpoint is auto-generated when I create `friend` model.

**Comment by gunjpan** [comment]
@bajtos : Hi Miroslav, could you PTAL and advise how we can change the `description` for our built-in model methods. Thanks.

**Comment by gunjpan** [comment]
@dongmai: To modify description of `Friend` model-methods, you can do following in your `Friend.js` file:
```javascript
module.exports = function(Friend) {
  var create = Friend.sharedClass.find('create', true); // 'create' is the method name, isStatic = true
  create.description = 'Your new awesome description';
};
```

This will change the description and you can verify it in LB explorer. 
You can see which method is connected to what end-point: [Predefined remote methods](https://docs.strongloop.com/display/public/LB/Exposing+models+over+REST#ExposingmodelsoverREST-Predefinedremotemethods).

Closing this now. should you need any further assistance, please reopoen the issue and mention my GH handle, will be happy to help. Thanks.

**Comment by Kishanjay** [comment]
@gunjpan the solution you provided does not seem to hold for remoteMethods, do you maybe know how to change their descriptions as well?

example:
```JS
module.exports = function(Friend) {
  var method = Friend.sharedClass.findMethodByName('prototype.__get__cars');
  method.description = "hello"
}
```

I tried many different methodNames, but none of them seemed to work

**Comment by bajtos** [comment]
Changing remoting metadata for relation methods is tricky. IIRC, their `sharedMethod` instances are always re-created and then dropped away, therefore your changes are not persisted. Please open a new issue to track this problem.
