### ISSUE TITLE
I cannot get where like filter working.

### ISSUE THREAD

**Issue by dongmai** [strongloop/loopback#2357]
Hi,

This is my code

> 
Event.find({where : {owner_id: {like : '%573c299bbadc76612c61a469%'}} } , 
function (err, items) {
                console.log(items);
});
 

An event document in database:
> {
  "_id": ObjectId("573ec19bf4b7658720c2fe65"),
  "action_id": ObjectId("573df5620318e27b0fe3c989"),
  "friend_ids": [
    "573e94170dc277150ca28258"
  ],
  "string_friend_ids": "573e94170dc277150ca28258",
  "owner_id": ObjectId("573c299bbadc76612c61a469"),
  "started_at": 1463730588
}

The console always log `[]` . I've tried many other ways but no luck with like filter.
Can someone please take a look?

**Comment by davidcheung** [comment]
@dongmai does the code work with something other than the `like` filter? 

might be due to this https://github.com/strongloop/loopback-connector-mongodb/blob/7c717e4446f08210dec628295049835f9206a977/lib/mongodb.js#L659-L674

or a known issue https://github.com/strongloop/loopback/issues/274

**Comment by davidcheung** [comment]
possibly related : https://github.com/strongloop/loopback/issues/2355, #1874

**Comment by davidcheung** [comment]
Closing stale issue, likely to be same root cause as #2355
