### ISSUE TITLE
If we run boot process in a context, getCurrentContext fails some times when connector is still connecting to mongodb

### ISSUE THREAD

**Issue by pkgulati** [strongloop/loopback#2358]
We have tried both approach calling boot in runInContext as well as calling some individual boot scripts in runInContext. 
Why we are using getCurrentContext in boot?
Actually we have some logic in 'before save" mixins which works on context, we are basically trying to load some data in boot script for different context.

**Comment by gunjpan** [comment]
@pkgulati : Hi, I don't understand what you're trying to do. Could you please provide a sample code/repo so that I can understand well what you're trying to achieve and can help you better.

**Comment by pkgulati** [comment]
// in server.js 
    var ns = loopback.createContext('loopback');

    loopback.runInContext(function(ns, domain) {

    console.log('setting foo=bar before boot');
    ns.set('foo', 'bar');
    console.log('check after set ', loopback.getCurrentContext().get('foo'));
  
    // boot scripts mount components like REST API
    boot(app, __dirname, function() {
        console.log('boot completed');
    });

     });

    // timer.js boot script 
    var path = require('path');
    var loopback = require('loopback');
    var async = require('async');

    module.exports = function (app, next) {
    console.log('in boot script timer.js');
    var ctx = loopback.getCurrentContext();
    if (ctx) {
        var a = ctx.get('foo');
        console.log('value of foo ', a);
    } else {
        console.log('loopback context is null ');
    }

    setTimeout(function () {
        console.log('timer occured');
        var ctx = loopback.getCurrentContext();
        if (ctx) {
            console.log('loopback context is there');
            var a = ctx.get('foo');
            console.log('value of foo ', a);
        } else {
            console.log('loopback context is null ');
        }
        next();
    }, 5000);
    }

**Comment by pkgulati** [comment]
Other possibility is we write a simple mocha test script , so basically getCurrentContext works for http request but for mocha or boot scripts it does not work

      myapp.boot(app, options, function fnboot () {
           app.start();
           app.emit('started');
     });

    var ns = loopback.createContext('loopback');
    loopback.runInContext(function (ns, domain) {

    var ctx = {
        ctx: {
            foo: 'bar'
        }
    };
    ns.set('callContext', ctx);
    console.log('context 1 ', loopback.getCurrentContext().get('callContext'));
    describe('boot script', function (ns) {
        console.log('context 2  ', loopback.getCurrentContext().get('callContext'));
        this.timeout(20000);
        it('wait for boot script', function (done) {
            console.log('context 3  ', loopback.getCurrentContext().get('callContext'));
            app.on("started", function fncb () {
                done();
            });
        });
    });

    });
`

**Comment by pkgulati** [comment]
In above example I expect foo = bar when printing context 3 line, however it does not work that way

**Comment by gunjpan** [comment]
@pkgulati : https://github.com/strongloop/loopback/issues/2004 is somewhat related?!, IMO

**Comment by gunjpan** [comment]
Hi @pkgulati, closing this as we're planning to deprecate `getCurrentContext()` with a warning message as it has not been reliable. See the discussion in https://github.com/strongloop/loopback/issues/1676. Should you have any concerns about how this deprecation may affect you, please post them in the issue there. 

Thank you.
