### ISSUE TITLE
Strongloop/Loopback "inq" operator is not working on Heroku server

### ISSUE THREAD

**Issue by shakeelmogify** [strongloop/loopback#2359]
If i run following without inq operator

`/api/Installations?filter[where][userId]=572d7995a80e6d0300b3f812
`
the result is as follows

```
[
  {
    "appId": "myApp",
    "userId": "572d7995a80e6d0300b3f812",
    "deviceToken": "cjxfuAfldZ4:APA91bFwK6FTqGCgShU4cdk4mPMlFPhevhFTEzsRELUVt5lARYKvhxI8jb55SVCveYf3zjXel3Kb7JrAyoHv6e8Aob8M0SEdepRWrckKliS2Iyh3bWHWH8EIBOp",
    "deviceType": "android",
    "status": "active",
    "id": "572d7996a80e6d0300b3f813",
    "created": "2016-05-07T05:13:58.564Z",
    "modified": "2016-05-07T05:13:58.564Z"
  }
]
```

But now if i run same query with inq operator as following

`/api/Installations?filter={"where": {"userId": {"inq": ["572d7995a80e6d0300b3f812"]}}}`

it gives me empty result without any error. I have waste many hours but unable to find what could be the reason. Please help me .... Thank you.

**Comment by yshing** [comment]
It is likely due to the those ObjectId issues when using MongoDB ...

**Comment by 0candy** [comment]
Is this the same issue as https://github.com/strongloop/loopback/issues/2355?

I am closing this as a dup of that one for now, if you disagree, please reopen with more details. Thanks!
