### ISSUE TITLE
Add support for custom API Urls for exposed models

### ISSUE THREAD

**Issue by ariskemper** [strongloop/loopback#236]
Nice feature would be possibility to rewrite default urls of main and related models.

Example:
for main models like 

/api/accessTokens to /api/access-tokens

or for related models like

/api/users/{id}/bankAccount to /api/users/{id}/bank-account

There should be setting like url for a model in models.json and also as a paramater options when creating or extending a model. There is option in models.json config called plurals, but would be good to have separate settings to set custom url for model/related models and endpoints ( custom routing ).

**Comment by superkhau** [comment]
@raymondfeng @fabien Safe to close?

**Comment by superkhau** [comment]
I am closing this since the feature is already there. @ariskemper Please open a new issue if you are still running into problems.
