### ISSUE TITLE
How do I add a custom filter to my models find remote function?

### ISSUE THREAD

**Issue by peeter-tomberg** [strongloop/loopback#2367]
I'm using the built in REST API to query my model. 
I wish to add a custom filter named "specialFilter" that will perform a complex SQL query based on the value provided. For example:

```
GET /resource?filter[where][specialFilter]=madonna
```

My method should be invoked before the SQL query is sent to the database and I should be able to change the query to fit my needs.

Couldn't find anything about this on the internet, so any help is appriciated. This is related to #517 as that's the reason I'm trying to do this. 

What I currently have:

user:

``` json
{
    "id": 1,
    "name": "Peeter Tomberg"
}
```

friends:

``` json
{
    "id": 1,
    "name": "Madis Milling",
    "userId": 1
}
```

Now when I query my user resource I need to find users who are friends with Madis. Since I can't do this with the strongloops query filtering I thought about doing it manually.

**Comment by raymondfeng** [comment]
Have you tried https://docs.strongloop.com/display/APIC/Remote+hooks <https://docs.strongloop.com/display/APIC/Remote+hooks>?

**Comment by peeter-tomberg** [comment]
I cant figure out how to modify the query though

**Comment by peeter-tomberg** [comment]
I've updated my post with a more detailed question.

**Comment by peeter-tomberg** [comment]
@raymondfeng Any thoughts?

**Comment by raymondfeng** [comment]
@peeter-tomberg The `ctx.args` property should have the filter object and you should be able to update it.

**Comment by gunjpan** [comment]
@peeter-tomberg : Is it good to close?

**Comment by peeter-tomberg** [comment]
This took a while to figure out. What I was trying to achieve was a left join query using the loopback query language. According to the 2nd comment on this thread: https://groups.google.com/forum/#!topic/loopbackjs/DTpTbV6NKUQ it's not possible and I should make 2 queries instead.

What I ended up doing was something in the lines of:

```javascript
const lodash = require('lodash');
	
module.exports = (app) => {
    app.remotes().before('*.*', (context, next) => {
		const filter = JSON.parse(context.args.filter);
		const Friend = app.models.Friend;
		const friendName = lodash.get(filter, 'where.friendName');
		if (friendName) {
			delete filter.where.friendName;
			return Friend
				.find({
					where: {
						name: { like: `%${friendName}%` },
					}
				})
				.then((friends) => {
					const userIds = lodash.map(friends, 'userId');
					filter.where.id = { inq: userIds };
					context.args.filter = JSON.stringify(filter);
					next();
				})
				.catch(next);
		}
		next();
    });
});
```

Now when I query my users list and pass along ?filter.where.friendName=madis I get all users who are friends with someone named "madis". 

Is this the correct approach? Currently the only drawback I have is not being able to document these custom filters, e.g. anyone using the API explorer has no idea there is a custom filter named "friendName".

**Comment by loay** [comment]
Hi @peeter-tomberg 
Is this good to close?
Also, we are working on implementing the features of join queries and 2nd level filtering as well. 
Regards,
