### ISSUE TITLE
Can't add model with name Model

### ISSUE THREAD

**Issue by adanielyan** [strongloop/loopback#2369]
I'm trying to add a new model named ```Model```, but when I start the app I get an error 

```AssertionError: User must be a descendant of loopback.Model```

User just happened to be the first in models declaration in model-config.json.

If I rename the model ```Model``` to something else everything works fine. Is it a bug?

**Comment by Amastyer** [comment]
Naming conflicts, loopback/common/models under the model already exists

**Comment by gunjpan** [comment]
@adanielyan : that's happening due to naming conflicts as LoopBack application has a built-in model named `Model`.

**Comment by bajtos** [comment]
Ideally, LoopBack should throw a helpful error when the users tries to redefine an existing model. See https://github.com/strongloop/loopback-datasource-juggler/issues/185

OTOH, we may need some way how to redefine existing models to customize them, see the discussion in https://github.com/strongloop/loopback/issues/397.

**Comment by gunjpan** [comment]
@adanielyan: Please rename your model to something different than existing model and it should work.
For the progress re. a way to redefine existing models, please see the comment above.

Closing this for now. Should you need any further assistance with this issue, feel free to reopen and tag my name, will be happy to assist. Thank you.

**Comment by adanielyan** [comment]
Thank you for replies. So does it mean there is no way to have a model named ```Model```? I am building a db of cars, and name Model is the only meaningful name for storing car models. I can of course prefix it with something, but then I'll have to do it for all models for consistency.

**Comment by adanielyan** [comment]
@gunjpan just saw your comment. Will take a look.
