### ISSUE TITLE
Configure modelBuilder via JSON file

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2370]
Recently, I am encountering places where we would like to add configuration to `modelBuilder` instances. 
- Make strict option default to true for anonymous models: https://github.com/strongloop/loopback-datasource-juggler/issues/923 and more specifically the pull request https://github.com/strongloop/loopback-datasource-juggler/pull/940
- Configure Max Listeners at runtime https://github.com/strongloop/loopback-datasource-juggler/pull/939

At the moment, the only way to modify this configuration is via code:

``` js
app.registry.modelBuilder.settings.key = value;
```

This is not consistent with our approach where we put as much configuration as possible into JSON files.

I am thinking about two possible solutions:
1. add a new section to `server/config.json`, called e.g. `modelBuilder`.
2. add a new JSON file, e.g. `server/model-builder.json`

Then in loopback-boot, we can do:

``` js
for (var key in config.modelBuilder) {
  app.registryModelBuilder.settings[key] = config.modelBuilder[key];
}
```

@raymondfeng @ritch thoughts?

**Comment by ritch** [comment]
If its just these two settings... why don't we add them to the server config? I don't want to put any (more) references to `ModelBuilder` in the public LB api.

**Comment by bajtos** [comment]
The tricky part is that `modelBuilder` is created as part of creating an `app` instance, see: 
 - [lib/registry.js](https://github.com/strongloop/loopback/blob/6a4bd6d09f0d080716e16f022f770c8625c7020c/lib/registry.js#L26)
 - global loopback.registry: [lib/loopback.js](https://github.com/strongloop/loopback/blob/6a4bd6d09f0d080716e16f022f770c8625c7020c/lib/loopback.js#L50) 
 - local app.registry: [lib/loopback.js](https://github.com/strongloop/loopback/blob/6a4bd6d09f0d080716e16f022f770c8625c7020c/lib/loopback.js#L102).

The server config (`server/config.json`) is applied by calling `app.set(key, value)`.

This creates Catch-22 situation: we cannot apply model-builder configuration before the app is created, but we need the model-builder configuration to be available at the time when a new app is created.

I think that ideally `app.set()` should trigger an event, allowing us to add a listener propagating these custom model-builder settings to the modelbuilder.

> f its just these two settings... why don't we add them to the server config? I don't want to put any (more) references to ModelBuilder in the public LB api.

I am expecting more of these settings to be added in the juggler in the future. If we have a single model-builder config

**Comment by bajtos** [comment]
The tricky part is that `modelBuilder` is created as part of creating an `app` instance, see: 
 - [lib/registry.js](https://github.com/strongloop/loopback/blob/6a4bd6d09f0d080716e16f022f770c8625c7020c/lib/registry.js#L26)
 - global loopback.registry: [lib/loopback.js](https://github.com/strongloop/loopback/blob/6a4bd6d09f0d080716e16f022f770c8625c7020c/lib/loopback.js#L50) 
 - local app.registry: [lib/loopback.js](https://github.com/strongloop/loopback/blob/6a4bd6d09f0d080716e16f022f770c8625c7020c/lib/loopback.js#L102).

The server config (`server/config.json`) is applied by calling `app.set(key, value)`.

This creates Catch-22 situation: we cannot apply model-builder configuration before the app is created, but we need the model-builder configuration to be available at the time when a new app is created.

I think that ideally `app.set()` should trigger an event, allowing us to add a listener propagating these custom model-builder settings to the modelbuilder.

> f its just these two settings... why don't we add them to the server config? I don't want to put any (more) references to ModelBuilder in the public LB api.

I am expecting more of these settings to be added in the juggler in the future. If we have a single model-builder config object, then juggler can add new settings without any need to wait for LoopBack to start recognizing it too. This is similar to how we are configuring strong-remoting options via `app.set('remoting')`.

However, I see your concern about exposing ModelBuilder in the public LB API. Can we perhaps come up with a config option name that would make sense on its own, without any reference to ModelBuilder? E.g. `app.set('models')` or `app.set('modeling')`?

**Comment by ebarault** [comment]
> I am expecting more of these settings to be added in the juggler in the future

https://github.com/strongloop/loopback-datasource-juggler/pull/1289 would benefit from app-wide settings from the juggler.

i like `app.set('models')`, that totally makes sense to me
