### ISSUE TITLE
Release LoopBack 3.0 RC

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2371]
-  [x]  First of all, we need to change version numbers from 3.0.0-alpha.X to 3.0.0, and publish new versions of the packages - see https://github.com/strongloop-internal/scrum-loopback/issues/1062
- [x] Then we need to update downstream projects to use 3.0.0 instead of 2.x or 3.0-alpha. loopback-workspace should use `^3.0.0` instead of `^3.0.0-alpha.X` when scaffolding new projects - see https://github.com/strongloop-internal/scrum-loopback/issues/1063
- [x] Prepare documentation changes, blog posts, etc. (tracked by other GH issues)
- [x] Remove 3.0-RELEASE-NOTES from the repositories (they are living on loopback.io now)
  - [x] strong-remoting - https://github.com/strongloop/strong-remoting/pull/366
  - [x] loopback-datasource-juggler - https://github.com/strongloop/loopback-datasource-juggler/pull/1126
  - [x] loopback - https://github.com/strongloop/loopback/pull/2823
- [x] Edit versions (releases) on GitHub to mention the fact that they are RCs and also to point to release notes/migration guide.
- [x] Publish the RC announcement blog post

**Comment by bajtos** [comment]
We need to give at least a weeks, preferably two weeks notice to @crandmck so that he can get the documentation updated in time.

**Comment by dadepra** [comment]
@bajtos any news about LB V3.0?

**Comment by bajtos** [comment]
@dadepra we are delayed by a month or two, for what the estimate is worth.

**Comment by bajtos** [comment]
Status update: Yesterday, we have released `3.0.0` as a release-candidate version. Expect a production-ready GA version to be available in few weeks time.
