### ISSUE TITLE
Custom middleware phase bug

### ISSUE THREAD

**Issue by casamia918** [strongloop/loopback#2372]
https://docs.strongloop.com/display/public/LB/Defining+middleware

Loopback support 2 ways of defining middleware. One is defining in middleware.json, and other one is using JS code in the server script.

The bug is simple. Custom phase is working at middleware.json but not working at JS code. (e.g. server.js)

I wrote my custom middleware named 'logger'

```
[/server/middleware/logger.js]

module.exports = function() {
  return function logger(req,res,next) {
    var logStr = req.method + ' ' + req.path + ' ' + res.statusCode;
    console.log(logStr);
    var bodyJson = JSON.parse(JSON.stringify(req.body));
    if(bodyJson.password) bodyJson.password = "****";
    console.log(bodyJson);
    next();
  }
}
```

And I created my custom middleware phase

```
  "parse": {},
  "log": {}, // my custom phase
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  },

```

After that, it is working when define in the middleware.json file

```
  "parse": {},
  "log": {
    "./middleware/logger" : {}    // defining logger in log phase
  },
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  },

```

But when I define in server.js, it complains by saying "unknown middle phase"
Of course, in this step, I already define 'log' phase in the middleware.json
```
[server.js]
var logger = require('./middleware/logger');
app.middleware('log', logger); // error
```

**Comment by gunjpan** [comment]
@casamia918: In your `server.js`, you're trying to add the `logger` middleware [`before boot`](https://docs.strongloop.com/display/public/LB/Upgrading+applications+to+use+phases#Upgradingapplicationstousephases-Middlewareaddedbeforeboot) and as the application is not yet initialized by [`boot( )`](https://docs.strongloop.com/display/APIC/Defining+boot+scripts#Definingbootscripts-Overview), the custom phase from `middleware.json` is not available for use.
Custom phases defined in `middleware.json` are registered after the `boot( )` and thus doesn't need to be registered in `server.js`.

One thing to notice about the middleware registered before `boot(app, __dirname)` is that it usually pre-processes all the requests.

So, if you want to intercept every request by your middleware and want to mount it on a custom phase, you can do so programatically by first defining the custom phase and then registering the middleware to that phase as following:
```Javascript
[server.js]
var logger = require('./middleware/logger');
app.defineMiddlewarePhases('log');
app.middleware('log', logger);

```

OTOH, if you want to register `logger` post-boot to a custom phase: `log` in `middleware.json`, you can do so, programtically(not recommended), as:
```javascript
boot(app, __dirname, function(err) {
  if (err) throw err;
 app.middleware('log', logger());
  // start the server if `$ node server.js`
  if (require.main === module)
    app.start();
});
```
Read more about [upgrading applications to use phases](https://docs.strongloop.com/display/public/LB/Upgrading+applications+to+use+phases).

Closing this for now. Should you need any further assistance with this issue, feel free to reopen it and mention me in the comments; will be glad to help you out. Thank you :)
