### ISSUE TITLE
nestRemoting not persisting data with embedsOne relationship

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback#2376]
Let's say we have the following models in our app:
1. A User has (embedsOne) Configuration model
2. Configuration model has (embedsMany) settings Model

If I enable nestRemoting in the User model for configuration relation I am able to query endpoints as expected for settings
ex:
`/api/users/1/configuration/settings`

GET, POST correctly return the results, but the problem is that POST although it sends back a correct response, it does not actually save the instance in the database. So by posting a setting model on the previous URL we get back a setting instance as we should, but no actual setting is persisted. If we issue a GET request again no settings will be there...

The same does not apply on embedsMany. It works correctly there. For example if we had an embedsMany relation for configurations, settings get persisted correctly...
ex.
`/api/users/1/configurations/1/settings` GET, POST work as axpected.

**Comment by mitsos1os** [comment]
Actually I have found the cause for this and it is in loopback-datasource-juggler.
The problem is that the embedsOne relation does not monkey patch the .trigger function as the EmbedsMany do [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L2854) and [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/relation-definition.js#L2482)

I have also created the code needed for this to work and I could issue a pull request on datasource juggler !!, but I would like someone to give me some guidance where to do it. Master branch of juggler etc??? Thanks

**Comment by 0candy** [comment]
I am closing this one as you already opened the issue in datasource-juggler.
