### ISSUE TITLE
Loopback user super model ACL won't work

### ISSUE THREAD

**Issue by hristo-vrigazov** [strongloop/loopback#2377]
Ways to reproduce the problem:
1. Create empty loopback application (not api-server)
2. Add in memory data source
3. Add new model "person", whose base model is "user"
4. Add new ACL rule to deny all methods of person

After these steps, I expect for example 
GET /people/
or any other endpoint to answer with 401 Unauthorized.
However, the response is 200 and an array of people.

I think this is either a bug, or I am missing something.

**Comment by gunjpan** [comment]
@hristo-vrigazov : Hey Hristo, does your acl for `Person` model looks same as:
```javascript
"acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }
  ]
```
if not, then change it to above and it should work. FYI, that ACL entry is setup by using `ACL generator` to [**Deny access to all project REST endpoints**](https://docs.strongloop.com/display/APIC/Controlling+data+access#Controllingdataaccess-UsingtheACLgeneratortodefineaccesscontrol).

**Comment by hristo-vrigazov** [comment]
This is exactly how it is in my project, but it does not behave as expected. I gave you the steps to exactly reproduce the problem.

**Comment by gunjpan** [comment]
@hristo-vrigazov: ohk. It would be hard to say what's happening until I can reproduce. Could you please share your code in a sample repo for me to take a look, thanks.

**Comment by hristo-vrigazov** [comment]
The problem was that I wasn't persisting Role and Rolemapping, if anyone wants to create a project from scratch.
