### ISSUE TITLE
elemMatch doesn't work with Dates

### ISSUE THREAD

**Issue by fedebalderas** [strongloop/loopback#2380]
I'm trying to do a query over  a property which is a Date type using **elemMatch** . I've changed a little my model for this example. (sorry about my english)

My model
![screen shot 2016-05-26 at 11 13 01 am](https://cloud.githubusercontent.com/assets/5208431/15581924/19044dba-2334-11e6-92d3-ee61b9963167.png)

This query works fine:
![screen shot 2016-05-26 at 11 24 17 am](https://cloud.githubusercontent.com/assets/5208431/15581990/6cc3239a-2334-11e6-8c27-c3f8dbdf98e4.png)

But this doesn't work:
![screen shot 2016-05-26 at 11 26 22 am](https://cloud.githubusercontent.com/assets/5208431/15582085/d4782cec-2334-11e6-9935-c88c8e1dd81e.png)

Or this:
![screen shot 2016-05-26 at 11 26 59 am](https://cloud.githubusercontent.com/assets/5208431/15582107/f164bbb8-2334-11e6-9cf9-dde1f84a3fa0.png)

Any idea?

**Comment by richardpringle** [comment]
Hey @fedebalderas, could you provide a sample repo by forking [the loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and providing the steps to reproduce? It would be a huge help!

Thanks in advance :)

**Comment by fedebalderas** [comment]
It works now... We had to add a dollar sign to operators ($and, $gte, $lte).

Thanks anyway 👍

**Comment by richardpringle** [comment]
Nice! Glad it worked out.
