### ISSUE TITLE
strongloop installation failure.

### ISSUE THREAD

**Issue by eatjeff** [strongloop/loopback#2385]
I am a starter at node.js, and I have learnt to use loopback as a backend service, however, the installation fails everytime,Can somebody help?

C:\Users\Jeff\Desktop\Bootstrap Base>npm install strongloop -g
npm WARN optional dep failed, continuing modern-syslog@1.1.3

> heapdump@0.3.7 install C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump
> node-gyp rebuild

\
C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\n) \rebuild -gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
-  heapdump.cc
LINK : fatal error LNK1181: cannot open input file 'DelayImp.lib' [C:\Users\Jef
f\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump\build\addon
.vcxproj]
 yp ERR! \build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\heapdump
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> utf-8-validate@1.2.1 install C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\utf-8-validate
> node-gyp rebuild

/
C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  validation.cc
  win_delay_load_hook.c
LINK : fatal error LNK1181: cannot open input file 'DelayImp.lib' [C:\Users\Jef
f\AppData\Roaming\npm\node_modules\strongloop\node_modules\utf-8-validate\build
\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack|     at ChildProcess.emit (events.js:172:7)
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\utf-8-validate
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing heapdump@0.3.7
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> bufferutil@1.2.1 install C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil
> node-gyp rebuild

-
C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
\  win_delay_load_hook.c
\LINK : fatal error LNK1181: cannot open input file 'DelayImp.lib' [C:\Users\Jef
f\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil\build\buf
ferutil.vcxproj]
/ build error
stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
-     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
stack     at emitTwo (events.js:87:13)
     at ChildProcess.emit (events.js:172:7)
stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\bufferutil
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> spawn-sync@1.0.15 postinstall C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\spawn-sync
> node postinstall

npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!

> strong-agent@2.0.3 install C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent
> node-gyp rebuild || exit 0

\
C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-ag(node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod\) se (node-  rebuild -gyp.js" rebuild /)
Warning: Missing input files:
C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\build\..\src\features.h
-Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  strong-agent.cc
/c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-a
gent\src\counters.h(240): warning C4267: 'argument' : conversion from 'size_t'
to 'uint32_t', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_mo
dules\strongloop\node_modules\strong-agent\build\strong-agent.vcxproj]
c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-a
gent\src\counters.h(241): warning C4267: 'argument' : conversion from 'size_t'
to 'int', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_modules
\strongloop\node_modules\strong-agent\build\strong-agent.vcxproj]
|c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-a
gent\src\gcinfo.h(42): warning C4267: 'argument' : conversion from 'size_t' to
'int', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_modules\st
rongloop\node_modules\strong-agent\build\strong-agent.vcxproj]
c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-a
gent\src\gcinfo.h(44): warning C4267: 'argument' : conversion from 'size_t' to
'uint32_t', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_modul
es\strongloop\node_modules\strong-agent\build\strong-agent.vcxproj]
\c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-a
gent\src\gcinfo.h(52): warning C4267: 'argument' : conversion from 'size_t' to
'int', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_modules\st
rongloop\node_modules\strong-agent\build\strong-agent.vcxproj]
/c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-a
gent\src\heapdiff.h(144): warning C4267: 'initializing' : conversion from 'size
_t' to 'unsigned int', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm
\node_modules\strongloop\node_modules\strong-agent\build\strong-agent.vcxproj]
c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-a
gent\src\heapdiff.h(228): warning C4267: '+=' : conversion from 'size_t' to 'in
t', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_modules\stron
gloop\node_modules\strong-agent\build\strong-agent.vcxproj]
c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-a
gent\src\heapdiff.h(232): warning C4267: '-=' : conversion from 'size_t' to 'in
t', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_modules\stron
gloop\node_modules\strong-agent\build\strong-agent.vcxproj]
c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-a
gent\src\profiler.h(393): warning C4267: 'argument' : conversion from 'size_t'
to 'int', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_modules
\strongloop\node_modules\strong-agent\build\strong-agent.vcxproj]
  win_delay_load_hook.c
LINK : fatal error LNK1181: cannot open input file 'DelayImp.lib' [C:\Users\Jef
f\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent\build\s
trong-agent.vcxproj]
build error
 Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
 stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-agent
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! registry error parsing json

> strong-debugger@1.0.0 install C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger
> node-gyp rebuild

C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
-  mutex-wrap.cc
  debugger.cc
  controller.cc
..\src\debugger.cc(31): warning C4267: 'argument' : conversion from 'size_t' to
 'int', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_modules\s
trongloop\node_modules\strong-debugger\build\debugger.vcxproj]
  worker.cc
..\src\controller.cc(130): warning C4267: 'argument' : conversion from 'size_t'
 to 'int', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_module
s\strongloop\node_modules\strong-debugger\build\debugger.vcxproj]
  worker-bindings.cc
..\src\worker.cc(305): warning C4267: 'argument' : conversion from 'size_t' to
'unsigned int', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_m
odules\strongloop\node_modules\strong-debugger\build\debugger.vcxproj]
c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_modules\strong-d
ebugger\src\incoming-connection-inl.h(75): warning C4244: 'argument' : conversi
on from 'ssize_t' to 'int', possible loss of data (..\src\worker.cc) [C:\Users\
Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger\b
uild\debugger.vcxproj]
          c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_module
  s\strong-debugger\src\incoming-connection-inl.h(65) : while compiling class t
  emplate member function 'void strongloop::debugger::IncomingConnection<strong
  loop::debugger::Worker>::ReadDataCb(uv_stream_t *,ssize_t,const uv_buf_t *)'
          c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_module
  s\strong-debugger\src\incoming-connection-inl.h(29) : see reference to functi
  on template instantiation 'void strongloop::debugger::IncomingConnection<stro
  ngloop::debugger::Worker>::ReadDataCb(uv_stream_t *,ssize_t,const uv_buf_t *)
  ' being compiled
          c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_module
  s\strong-debugger\src\incoming-connection-inl.h(5) : while compiling class te
  mplate member function 'strongloop::UvError strongloop::debugger::IncomingCon
  nection<strongloop::debugger::Worker>::Init(uv_loop_t *,T *)'
          with
          [
              T=strongloop::debugger::Worker
          ]
          ..\src\worker.cc(208) : see reference to function template instantiat
  ion 'strongloop::UvError strongloop::debugger::IncomingConnection<strongloop:
  :debugger::Worker>::Init(uv_loop_t *,T *)' being compiled
          with
          [
              T=strongloop::debugger::Worker
          ]
          c:\users\jeff\appdata\roaming\npm\node_modules\strongloop\node_module
  s\strong-debugger\src\worker.h(110) : see reference to class template instant
  iation 'strongloop::debugger::IncomingConnection<strongloop::debugger::Worker
  >' being compiled
..\src\worker.cc(258): warning C4267: 'argument' : conversion from 'size_t' to
'unsigned int', possible loss of data [C:\Users\Jeff\AppData\Roaming\npm\node_m
odules\strongloop\node_modules\strong-debugger\build\debugger.vcxproj]
          ..\src\worker.cc(240) : see reference to function template instantiat
  ion 'strongloop::UvError strongloop::debugger::RejectedClient::AcceptAndRejec
|  t<strongloop::debugger::Worker>(strongloop::debugger::TcpWrap<strongloop::deb
  ugger::Worker> *)' being compiled
          ..\src\worker.cc(290) : see reference to function template instantiat
  ion 'void strongloop::debugger::RejectedClient::HandleIncomingConnection<stro
  ngloop::debugger::Worker>(strongloop::debugger::TcpWrap<strongloop::debugger:
  :Worker> *)' being compiled
  win_delay_load_hook.c
LINK : fatal error LNK1181: cannot open input file 'DelayImp.lib' [C:\Users\Jef
f\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger\buil
d\debugger.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jeff\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-debugger
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing strong-debugger@1.0.0
|

**Comment by gunjpan** [comment]
@eatjeff: Did you follow the steps to install compiler tools [here](https://docs.strongloop.com/display/SL/Installing+compiler+tools)? If not, please follow them and try to reinstall `strongloop`.

**Comment by eatjeff** [comment]
@gunjpan.thank,  I will follow this

**Comment by eatjeff** [comment]
@gunjpan, Thank you, follow your instruction, I have installed the strongloop succesfully.Cheers

**Comment by gunjpan** [comment]
@eatjeff : Great! Hope you may enjoy LoopBack :)
Closing this now.
