### ISSUE TITLE
Angular + Loopback: could not find accessToken when loging out

### ISSUE THREAD

**Issue by PJEstrada** [strongloop/loopback#2388]
I´m trying to implement a simple login on angular and loopback.

I have the login working using the following controller.

```
(function(angular){
  'use strict';


  //Module Fetch
  angular
    .module('frontend')
    .controller('LoginController',LoginController);
    LoginController.$inject = [
      '$log',
      '$location',
      'ExeboardUser',
      'LoopBackAuth'
    ];

    function LoginController(
      $log,
      $location,
      ExeboardUser,
      LoopBackAuth
    ){
      var vm = this;
      vm.user={username:'',password:''};
      vm.loggedIn = ExeboardUser.isAuthenticated();
      console.log("login"+vm.loggedIn)
      vm.login = function(){
        console.log("Logging in...");
        var user = vm.user.username;
        var password = vm.user.password;
        ExeboardUser.login({username:user,password:password})
          .$promise
          .then(function(){
            console.log("Login Succesful");
              var next = $location.nextAfterLogin || '/';
              $location.nextAfterLogin = null;
              $location.path(next);
              $location.path('/dashboard');

          },
          function(error) {
            console.log("Error login: "+error);

          });
      }

      vm.logout = function(){
        ExeboardUser.logout();

        LoopBackAuth.clearUser();
        LoopBackAuth.clearStorage();
      }


    }
})(angular)
```
When I login I succefully get the following response:

`{"id":"IzVg5NH2l4oCOskzIFrhUoSIDcvc6Ht5sy7AHgnjutB8etx2Gb77Dz1bAdFm4HVZ","ttl":1209600,"created":"2016-05-27T15:44:26.648Z","userId":1,"user":{"name":"test","last_name":"t","phestone":55485698,"realm":null,"username":"test_login","credentials":null,"challenges":null,"email":"testlogin@hotmail.com","emailVerified":null,"status":null,"created":null,"lastUpdated":null,"id":1}}`

However when calling the logout function. I´m getting this response

`
{"error":{"name":"Error","status":500,"message":"could not find accessToken","stack":"Error: could not find accessToken`

The token does appear in window.storage, but I don´t understand why the logout makes an unauthenticated request even if I already called login. Is there anything else I have to add to the logout request to make it send the access token?

**Comment by gunjpan** [comment]
@PJEstrada : Please take a look at the example [here](https://github.com/strongloop/loopback-example-user-management#how-do-you-log-out-a-user) on how to logout a user. _(Also, [PTAL at related docs](https://docs.strongloop.com/display/APIC/Logging+in+users#Logginginusers-Loggingout))_

Hope this solves your issue. Closing this for now, feel free to reopen it and mention me, in case if you're still facing it; will be happy to help. 
For future reference, we encourage you to post questions to our question [channels](https://github.com/strongloop/loopback/wiki/Questions) as we're promoting GH space for bug reporting/feature requests.
Thank you :)
