### ISSUE TITLE
Wrong error message: if a DELETE/PATCH request is made for an API which is implemented as GET

### ISSUE THREAD

**Issue by priyavivek1** [strongloop/loopback#2389]
Get a wrong error message when i try to make a delete request for an API which is implemented as GET.

it gives error: Cannot DELETE /v1/10/agreements, 
Although it should be "There is no method handling for DELETE- ResourceURI"

above case happens just for DELETE and PATCH methods, If i try to make a POST for the API implemented as GET, error message comes correct

**Comment by richardpringle** [comment]
Hey @priyavivek1, could provide a sample repo to reproduce the issue with a forked version of [loopback-sandbox](https://github.com/strongloop/loopback-sandbox)? I tried using CURL to hit some of the built-in PersistedModel endpoints and I was getting the expected error message.

**Comment by davidcheung** [comment]
assuming `v1` is your model? I would assume it to work if the relations are setup properly

Closing inactive issues, @priyavivek1 are you still facing this issue, please ping me on this issue or open a new issue with steps to reproduce
