### ISSUE TITLE
Deficiencies of DAO.save()

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2393]
1) It has "patch" semantics (instead of "replace"), which can be demonstrated on this code:

``` js
MyModel.findById(someId).then(function(inst) {
  // inst: { name: 'Miroslav', handle: 'bajtos' }
  inst.unsetAttribute('handle');
  // inst: { name: 'Miroslav' }
  inst.save().then(function() {
    // unexpectedly, the record in the datasource is still 
    // { name: 'Miroslav', handle: 'bajtos' }
  }
});
```

2) The implementation in SQL connectors does not handle the case when the record does not exist yet, but the caller has specified a value for the ID column.

**Comment by bajtos** [comment]
We would like to rework `save` to call `connector.replaceOrCreate` under the hood. That requires all connectors to provide an atomic implementation of `replaceOrCreate`, which is not yet true even for official connectors provided by the LoopBack team.

Once we have atomic `replaceOrCreate` implemented, I think the following solution would fix both issues:

1) Add a flag, either at datasource-level or model-level, to control whether `save` has update or replace semantics. E.g. `replaceOnSave`.
2) When creating datasource/attaching a model to the datasource and `replaceOnSave:true`, then throw an error if the connector does not provide atomic `replaceOrCreate`.
3) In DAO `save`, use the flag to decide whether to call `connector.save` or `connector.replaceOrCreate`.

**Comment by richardpringle** [comment]
@bajtos, when you create new issue can you throw a label on it?

I'll put "feature" on here for now but please feel free to change as necessary.

**Comment by bajtos** [comment]
> when you create new issue can you throw a label on it?

Ah of course, sorry!

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be adding any new features.
