### ISSUE TITLE
Bug when model has relation named "trigger"

### ISSUE THREAD

**Issue by ccgdesigns** [strongloop/loopback#2396]
Defining a relation as follows:

```
"relations": {
    "trigger": {
      "type": "belongsTo",
      "model": "notificationTrigger",
      "foreignKey": "triggerId"
    }
}
```

breaks the code: I am completely unable to create or save a model instance. 

> NotificationTrigger.app.models.Notification.create({...}, function(err, notif){...});
- The callback never gets called (not even with an error)
- No row is added into the database

Changing the name "trigger" to anything else fixes the issue. Maybe there should be a check to stop people like me using reserved names?

**Comment by gunjpan** [comment]
@ccgdesigns : I was able to reproduce the error, raising it as a bug. I believe there was a discussion to expose a list of reserved words, not sure where, but will update you on that. 
Meanwhile, would you like to submit a fix, I will be glad to help along the way to get your fix released.
