### ISSUE TITLE
AccessToken ACL documentation

### ISSUE THREAD

**Issue by tpflueger** [strongloop/loopback#2399]
I found it difficult to find documentation on changing the permissions of the AccessToken even though there is a table displaying the defaults.

https://docs.strongloop.com/display/public/LB/Access+token+REST+API

I was wondering if adding the exact method names tied to each of the routes might be helpful for others wanting to also change the defaults.

**Comment by richardpringle** [comment]
```
// format:
// AccessToken[method_name]
// remoting_metadata

create
{ verb: 'post', path: '/' }

find
{ verb: 'get', path: '/' }

upsert
{ verb: 'put', path: '/' }

findById
{ verb: 'get', path: '/:id' }

// should be
updateAttributes
{ verb: 'put', path: '/:id' }
// was actually (need to investigate)
updateAttributes
{ verb: 'put', path: '/' }

deleteById
{ verb: 'del', path: '/:id' }

exists
{ verb: 'get', path: '/:id/exists' }

count
{ verb: 'get', path: '/count' }

findOne
{ verb: 'get', path: '/findOne' }
```
@tpflueger, as you can see, this follows PersistedModel method-name conventions. @crandmck, maybe it would be a good idea just to add a note about following the naming conventions.

**Comment by richardpringle** [comment]
Additional methods can be found in the [API docs](https://apidocs.strongloop.com/loopback/#accesstoken).

**Comment by tpflueger** [comment]
@richardpringle I might have just misunderstood how to set the AccessToken settings on a user. I went about it by adding `__get__accessTokens` to the ACLs of a modified user model.

**Comment by richardpringle** [comment]
@tpflueger wait... you want to see the ACLs set on the user model? I'm a little confused at what you are trying to do...

**Comment by tpflueger** [comment]
@richardpringle I was trying to set the ACLs on a user model's access tokens, so that say an admin role would be able to revoke them.

**Comment by richardpringle** [comment]
@tpflueger, you want to add/remove ACLs from the REST API instead of doing by hand in the JSON?

**Comment by tpflueger** [comment]
@richardpringle I was trying to do it by hand with JSON, but I had trouble trying to find the functions that allowed access for the user to get or revoke access tokens.

**Comment by richardpringle** [comment]
@tpflueger can you fork a [loopback-sandbox](https://github.com/strongloop/loopback-sandbox), show me how you have extended the user model and what your desired outcome is?

We can definitely accomplish what you're going for here, would be easier to show you on the same codebase though.

**Comment by tpflueger** [comment]
@richardpringle I wasn't looking correctly in terms of how you can set the ACLs for relationships or the syntax was given. After looking at https://docs.strongloop.com/display/public/LB/Accessing+related+models, the suggestions clarified how each route was setup and how I could change the ACLs tied to an extended User model.

**Comment by richardpringle** [comment]
@tpflueger, completely understandable. Our docs can be a little difficult to navigate. We're working on improving them. Do you have any recommendations?

**Comment by tpflueger** [comment]
When I was doing searches for my problem, I was trying to find a quick reference to AccessToken. When I found the table at https://docs.strongloop.com/display/public/LB/Access+token+REST+API, I was hoping to find method names or documentation that talked about relations. However, if I would have read more into it or knew the actual problem I was having, I would have known that my need was to go to https://docs.strongloop.com/display/public/LB/Accessing+related+models. I think the overall problem is just getting all the related information because I'm not going to dig into documentation if I don't have to.

**Comment by crandmck** [comment]
@tpflueger  I added a pointer in https://docs.strongloop.com/display/LB/Access+token+REST+API to the related model article.  I hope that will help others in your situation.
