### ISSUE TITLE
EventSource connection limit, connection sharing

### ISSUE THREAD

**Issue by FreakTheMighty** [strongloop/loopback#2402]
With only 6 available connections in Chrome its easy to hit connection limits while using a persistent connection like `EventSource`. I think it would be helpful to support sharing event streams between multiple resources.

**Comment by gunjpan** [comment]
Hey @FreakTheMighty, that's a limitation from Chrome and two suggested solutions [here](https://groups.google.com/a/chromium.org/forum/#!topic/net-dev/0bPuXIq_M5U) would make LoopBack changeStream more robust. 
@ritch , @bajtos: thoughts on if we want to enhance `changeStream` with `http 2.0 server push` or `SPDY server push`.
FYI, GitHub also ran into this issue when they were implementing live updates.
