### ISSUE TITLE
loopback-component-oauth2 can't be installed in lastest Node npm version?

### ISSUE THREAD

**Issue by usbwc** [strongloop/loopback#2403]
$ npm i loopback-component-oauth2
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/bin/npm" "i" "loopback-component-oauth2"
npm ERR! node v6.2.1
npm ERR! npm v3.9.3

npm ERR! No compatible version found: pkginfo@^0.4.0
npm ERR! Valid install targets:
npm ERR! 0.3.1, 0.3.0, 0.2.3, 0.2.2, 0.2.1
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:

**Comment by gunjpan** [comment]
Please report this issue in: [loopback-component-oauth2](https://github.com/strongloop/loopback-component-oauth2) repository.
