### ISSUE TITLE
How can I populate the relation model?

### ISSUE THREAD

**Issue by shuhankuang** [strongloop/loopback#2405]
I didn't use rest api, how can I do than in nodejs?
User
     hasMany (Article)
Article
     belongsTo (User)

Now I have a foreignKey (creatorId) in article, looks like
```
article
{
id: xxxx,
creatorId: xxxxxxx,
title: xxxx,
content: xxxx
}
```
How can I populate the data like mongoose, 

```
{
id: xxxx
createorId: {
       id: xxxx,
       username: xxxx,
       ....
},
title: xxx
}
````

**Comment by gunjpan** [comment]
@shuhankuang : You can use `include` filter to get all data for related model. Read more about it [here](https://docs.strongloop.com/display/public/LB/Include+filter)
Also, methods added to the model when `HasMany` relation is applied can be useful too. See the [list of methods here](https://docs.strongloop.com/display/public/LB/HasMany+relations#HasManyrelations-Methodsaddedtothemodel).

Closing this issue for now. Should you need further assistance with it, feel free to reopen and mention me.
For future reference, we encourage you to keep posting questions on our [Question channels](https://github.com/strongloop/loopback/wiki/Questions) as we're trying to keep GH space limited to accept feature requests and bug reports only.
Thank you.
