### ISSUE TITLE
Update docs for nestRemoting to state that it needs to be done in boot file

### ISSUE THREAD

**Issue by cgole** [strongloop/loopback#2406]
https://docs.strongloop.com/display/public/LB/Nested+queries

in `model.js` we cannot get model’s relations since they are not loaded. Do relation related operations in boot file.

**Comment by richardpringle** [comment]
@crandmck, just needs a small note somewhere. You *can* actually do it in the `model.js` but you have to use events to make sure the model is loaded. Would be best to *recommend* that `nestRemoting` be done in a boot script.

**Comment by crandmck** [comment]
OK I added a short note to https://docs.strongloop.com/display/APIC/Nested+queries.  I'm going to close, but if you think I need to do something more @richardpringle, please reopen.
