### ISSUE TITLE
Problem while getting HasManyThrough relation with a findOne

### ISSUE THREAD

**Issue by toniopelo** [strongloop/loopback#2408]
Hi everybody! :)

I have a Group model that have two relations :
   - subGroups : hasManyThrough relation that targets a Group model (itself)
   - tracks : hasManyThrough relation that targets a Track model

I want to get a single group by its id, including its tracks and its subGroups (including the subGroups subGroups and tracks too)

I decided to do a request with a depth of 3. So I applied this filter to the findOne :

`Groups.findOne({include: [{subGroups: [{subGroups: "tracks"}, "tracks"]}, "tracks"], where: {id: id}}, function (pErr, pGroup) {});`

Problem :
I get a result but  when I do :

`console.log(pGroup);
console.log(pGroup.tracks);`

The first seems to be correct, I can see the related models.
But the second one print me a function.
And event when I try to print the typeof return, it says me : "function".

There is what I get with the second console.log :

> { [Function]
  _receiver: 
   { id: 1,
     name: 'npy',
     vignette: '',
     description: '',
     website: '',
     subGroups: List [ [Object], [Object], [Object] ],
     tracks: List [ [Object] ] },
  _scope: { where: { groupId: 1 }, collect: 'track', include: 'track' },
  _targetClass: 'Track',
  getAsync: [Function],
  build: [Function: build],
  create: [Function: bound ],
  updateAll: [Function: updateAll],
  destroyAll: [Function: destroyAll],
  findById: [Function: bound ],
  findOne: [Function: findOne],
  count: [Function: count],
  destroy: [Function: bound ],
  updateById: [Function: bound ],
  exists: [Function: bound ],
  add: [Function: bound ],
  remove: [Function: bound ] }

After that, I tried to do a single relation inclusion with subGroups only and no nested inclusion. Same thing, I get a function instead of an array of related models.

Am I silly or it's a real issue ?

Thanks :)

**Comment by toniopelo** [comment]
Problem solved : https://github.com/strongloop/loopback-datasource-juggler/issues/261
May be it should be documented in strongloop documentation ?

**Comment by tmedamin** [comment]
parse result with res.toJSON() and you will have a json
