### ISSUE TITLE
Nested API endpoints enabled using nestRemoting do not show up in loopback explorer

### ISSUE THREAD

**Issue by cgole** [strongloop/loopback#2409]
These endpoints show up in API Designer explorer but not in loopback explorer

**Comment by cgole** [comment]
I have 3 models bank, account, transaction
bank hasMany accounts
accounts belongsTo bank
account hasMany transactions
transactions belongsTo account

$ cat server/boot/nested.js 
module.exports = function (server, done) {
  var Bank = server.models.bank;
  Bank.nestRemoting('accounts');
 done()
}

Start the app and check loopback explorer. You don't see nested API endpoints like these - 
GET /banks/{id}/accounts/{nk}/transactions/{fk}
POST /banks/{id}/accounts/{nk}/transactions

but you see these in the APIConnect designer explorer.

Attaching my app - 
[bank5.zip](https://github.com/strongloop/loopback/files/303255/bank5.zip)

**Comment by davidcheung** [comment]
adding some info to this, 
it shows up in `loopback:export-api-def` but not `http://localhost:3000/explorer/swagger.json`

**Comment by sidewaiise** [comment]
Also experiencing this. Would love a solution - makes debugging and verifying that nested queries are available (and working) through REST.

**Comment by sebastianhaas** [comment]
I can confirm, it would be nice if there was a solution for this problem.

**Comment by DAVIDFlavien** [comment]
Hey,

Some news regarding this issue ? It's something that will be very helpful...

**Comment by DAVIDFlavien** [comment]
See strongloop/loopback-component-explorer#208
