### ISSUE TITLE
Change default validateUpsert to `true`

### ISSUE THREAD

**Issue by Amir-61** [strongloop/loopback#2418]
#### Model.settings.validateUpsert

Change default of Model.settings.validateUpsert to true. Fix the related comment in lib/dao.js - we cannot remove this option entirely, because it validation does not play well with advanced MongoDB operators.
https://github.com/strongloop/loopback-datasource-juggler/blob/5dca27278a37b1e2e0fa572c3ae20681cd500680/lib/dao.js#L514-L518
- [ ] Change default of Model.settings.validateUpsert to true
- [ ] CI test passes (remove test case / confirm new implementation or replacement has tests)
- [ ] Update `3.0-RELEASE-NOTES.md` indicating breaking change

See https://docs.strongloop.com/display/LB/Model+definition+JSON+file
Possibly related : https://github.com/strongloop/loopback/issues/1299

**Comment by bajtos** [comment]
Also check whether MongDB's upsert actually supports extended operators.
