### ISSUE TITLE
Role.getRoles inconsistent entities return

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback#2420]
I believe Role.getRoles functionality isn't working as expected. When issued for a user, it will return the names of dynamically resolved roles such as $authenticated, $everyone, etc.. and then for normal roles, the role id. **So you get an array of names and Ids together**. I do not see any reason for this and I find it incorrect.
- You can see that for resolved roles it adds the name [here](https://github.com/strongloop/loopback/blob/master/common/models/role.js#L404)
- But for normal roles it adds the id... [here](https://github.com/strongloop/loopback/blob/master/common/models/role.js#L439)

Any opinions???

**Comment by davidcheung** [comment]
hi @mitsos1os, it would be really helpful if you could reproduce the issue(where the `role name` and `roleId` ends up in same array) in a [sand-box](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) 

please note that in [principalId](https://github.com/strongloop/loopback/blob/42c83f69a090664bb025d89f8dd5f5a7a3ffa34e/common/models/role-mapping.json#L5) are  `strings`
```js
"acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
    }
  ]
```

**Comment by mitsos1os** [comment]
Hello @davidcheung !
I have created the sandbox here: https://github.com/mitsos1os/loopback-sandbox/tree/get-roles-return-mixed
You can see for yourself that in the end of the boot scrip for `server/boot/admin.js` the roles of an admin user are printed, and you will see that dynamic roles (simple names), are mixed with static role ids....
In my first comment you can see the lines responsible for this, but I haven't issued a pull request because I wanted to discuss first this behavior....
Thanks

**Comment by davidcheung** [comment]
Thanks for reproducing the issue, I do agree the behavior is unexpected, not sure whats the best approach to resolve this, perhaps changing
https://github.com/strongloop/loopback/blob/42c83f69a090664bb025d89f8dd5f5a7a3ffa34e/common/models/role.json#L8

```json
{
  "name": "Role",
  "properties": {

    "id": {
      "type": "string",
      "id": true,
      "generated": true 
    },
```
**right now this forces all ids into numbers**
to something like 
```json
{
  "name": "Role",
  "idInjection": true,
  "properties": {
    "id": {
      "type": "string",
      "id": true
    },
}
```

then user would be able to do 
```js
Role.create({
  id: '$someRole',
  name: 'someRole'
});
```

@raymondfeng any thoughts?

**Comment by mitsos1os** [comment]
@davidcheung I am afraid you are not right about the auto generated key...
`idInjection: true` what only does is adding an id property with also the `generated: true` property, as you can see [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model-builder.js#L286)

The `generated ` property is used by the connector to be auto completed if selected, as you can see [here](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L510)

The fact that the id gets a number for the example is because of the memory connector which uses integers for auto - id generation. If this was in mongoDb an ObjectId would be auto generated...

I believe a solution would be to either 
- actually make the id property a string but **not** generated, so that the user will have to add the id of the role in letters, such as **admin** which would also make it unique
- or to select to add the name for static roles instead of the role id as seen [here](https://github.com/strongloop/loopback/blob/master/common/models/role.js#L439), but we shoud also set the `name` property of the role to required in order to avoid situations where an empty role name is added to the list.

**Comment by davidcheung** [comment]
you're right, what i wanted to achieve was backwards compatibility,  so user can define `id`, but when its not defined to give them a auto-generated `id` (number)
but since you pointed out that it assigns the `id` as a number (in model builder), probably a bad idea to do so 

but the better solution might to be just make it `required` and `unique`( i think its [already unique](https://github.com/strongloop/loopback/blob/42c83f69a090664bb025d89f8dd5f5a7a3ffa34e/common/models/role.js#L453)) then this would be **breaking-change**, but the behavior would make more sense

**Comment by mitsos1os** [comment]
@davidcheung thanks for the notice.... I didn't know about y! I will do it from now on. Any news on this issue?

**Comment by davidcheung** [comment]
@mitsos1os no news yet on this issue, so proposal is **user will setup roles with self defined id**
example
```js
Role.create({
  id: '$someRole',
  name: 'someRole'
});
```
^^ right now this would result in `{id:1, name:'$someRole'}`

@raymondfeng @bajtos any thoughts?

**Comment by bajtos** [comment]
> no news yet on this issue, so proposal is user will setup roles with self defined id
example

@davidcheung I am afraid I am not familiar enough with this code base. I guess it's up to @raymondfeng and/or @ritch to make the call.

cc @loay @richardpringle, as they are the new owners of everything authentication-related

**Comment by davidcheung** [comment]
adding information, 
changing role creation to not-auto generate could be breaking change?

**Comment by mitsos1os** [comment]
Closed with https://github.com/strongloop/loopback/pull/2975
