### ISSUE TITLE
get all remote methods for managing permission

### ISSUE THREAD

**Issue by vinhphucit** [strongloop/loopback#2421]
Hi all,

I'm developing user, role, acl management in Loopback. I deny all requests in default and in the web ui, I will list all models and properties, remote methods in system. I spend all day but no result.
Anyone can help me list all remote methods and models in Loopback.

**Comment by gunjpan** [comment]
@vinhphucit : It's unclear to me what you're trying to do here. could you please elaborate more and provide me some code sample to better assist you. Thanks.

**Comment by vinhphucit** [comment]
Glad to see your feedback.

I'm developing admin site for my customer and that site has permission management feature. That mean users with admin role can grant permission for user.
In ACL table, loopback has model, property fields. I need to load all models and properties (find, findbyid...) to web ui, and users with admin role will choose models and properties and grant to specific user.
So  all I need now is know how I can load all model names and property names. Could you write an example function to get all models and properties in loopback?
Thanks

**Comment by gunjpan** [comment]
@vinhphucit : Hi, is the following something you're looking for: 
[Partitioning users with realms](https://docs.strongloop.com/display/APIC/Partitioning+users+with+realms)

**Comment by benkroeger** [comment]
you can get a list of all models from `app.models()`.

to compile a list of all remote methods on a model, you can run a function like this:

```
function getActiveRemoteMethods(model) {
  const activeRemoteMethods = model.sharedClass
    .methods({ includeDisabled: false })
    .reduce((result, sharedMethod) => {
      Object.assign(result, {
        [sharedMethod.name]: sharedMethod.isStatic,
      });
      return result;
    }, {});

  return activeRemoteMethods;
}
```

`sharedClass.methods` also includes remote methods from related models (if any)

**Comment by gunjpan** [comment]
@benkroeger : Thank you for chiming in :)

@vinhphucit hucit : PTAL at comments above, and see if they work for what you're trying to achieve. Closing this for now due to inactivity. Should you need further assistance with it, feel free to comment with my GH handle and I'll be happy to assist. 
Thank you and have a great day.
