### ISSUE TITLE
Add globalization to loopback repos [placeholder]

### ISSUE THREAD

**Issue by 0candy** [strongloop/loopback#2422]
Add globalization to loopback modules using [strong-globalize](https://www.npmjs.com/package/strong-globalize)

- [x] loopback   https://github.com/strongloop/loopback/pull/2407
- [x] generator-loopback  https://github.com/strongloop/generator-loopback/pull/202
- [x] loopback-datasource-juggler (Amir) https://github.com/strongloop/loopback-datasource-juggler/pull/1022
- [x] loopback-component-passport https://github.com/strongloop/loopback-component-passport/pull/165
- [x] loopback-connector-mysql https://github.com/strongloop/loopback-connector-mysql/pull/178
- [x] loopback-connector-mongodb (Janny) https://github.com/strongloop/loopback-connector-mongodb/pull/267
- [x] loopback-workspace https://github.com/strongloop/loopback-workspace/pull/299
- [x] loopback-connector-postgresql (Janny) https://github.com/strongloop/loopback-connector-postgresql/pull/152
- [x] [loopback-component-push (Simon)](https://github.com/strongloop/loopback-component-push/pull/118)
- [x] loopback-connector-mssql https://github.com/strongloop/loopback-connector-mssql/pull/89
- [x] loopback-connector https://github.com/strongloop/loopback-connector/pull/55
- [x] loopback-connector-redis (Janny) https://github.com/strongloop/loopback-connector-redis/pull/23
- [x] [loopback-component-explorer (Simon)](https://github.com/strongloop/loopback-component-explorer/pull/170)
- [x] ~~loopback-connector-remote (Gunjan)~~ No user strings to globalize
rest/pull/66)
- [x] loopback-sdk-android (Loay) https://github.com/strongloop/loopback-sdk-android/pull/103
- [x] [loopback-connector-oracle (Simon)](https://github.com/strongloop/loopback-connector-oracle/pull/68)
- [x] loopback-connector-soap (Amir) https://github.com/strongloop/loopback-connector-soap/pull/38
- [x] loopback-component-oauth2 (Loay) https://github.com/strongloop/loopback-component-oauth2/pull/37
- [x] [loopback-connector-sqlite3 (Simon)](https://github.com/strongloop/loopback-connector-sqlite3/pull/18)
- [x] [loopback-phase (Simon)](https://github.com/strongloop/loopback-phase/pull/12)
- [x] ~~loopback-api-definition (Gunjan)~~ No user strings to globalize
- [x] loopback-sdk-angular (David)https://github.com/strongloop/loopback-sdk-angular/pull/230
- [x] strong-remoting (Deepak)  https://github.com/strongloop/strong-remoting/pull/329
- [x] loopback-sdk-angular-cli (David) https://github.com/strongloop/loopback-sdk-angular-cli/pull/46
- [x] loopback-boot (David)https://github.com/strongloop/loopback-boot/pull/200
https://github.com/strongloop/loopback-boot/pull/199 (**note that this is against refactored-boot not master**)
- [x] loopback-component-storage https://github.com/strongloop/loopback-component-storage/pull/139
- [x] loopback-swagger https://github.com/strongloop/loopback-swagger/pull/51
- [x] [loopback-connector-rest (Gunjan)](https://github.com/strongloop/loopback-connector-rest/pull/66)
- [x] [loopback-connector-jsonrpc (Gunjan)](https://github.com/strongloop/loopback-connector-jsonrpc/pull/6)
- [x] loopback-connector-cloudant  https://github.com/strongloop/loopback-connector-cloudant/pull/24
- [x] strong-error-handler https://github.com/strongloop/strong-error-handler/pull/20

Backport to 2.x
- [x] loopback https://github.com/strongloop/loopback/pull/2581
- [x] loopback-datasource-juggler  https://github.com/strongloop/loopback-datasource-juggler/pull/1029
- [x] strong-remoting  https://github.com/strongloop/strong-remoting/pull/330

Release to npmjs.org:

 - [x] generator-loopback
 - [x] loopback
 - [x] loopback-boot
 - [x] loopback-component-explorer
 - [x] loopback-component-oauth2
 - [x] loopback-component-passport
 - [x] loopback-component-push
 - [x] loopback-component-storage
 - [ ] loopback-connector
 - [ ] loopback-connector-cloudant
 - [ ] loopback-connector-jsonrpc
 - [ ] loopback-connector-mongodb
 - [ ] loopback-connector-mssql
 - [ ] loopback-connector-mysql
 - [ ] loopback-connector-oracle
 - [ ] loopback-connector-postgresql
 - [ ] loopback-connector-redis
 - [ ] loopback-connector-remote
 - [ ] loopback-connector-rest
 - [ ] loopback-connector-soap
 - [ ] loopback-connector-sqlite3
 - [x] loopback-datasource-juggler
 - [x] loopback-phase
 - [x] loopback-sdk-angular
 - [x] loopback-sdk-angular-cli
 - [x] loopback-swagger
 - [x] loopback-workspace
 - [x] strong-error-handler
 - [x] strong-remoting

Ignore these modules for Q3:
~~loopback-sdk-ios~~
~~angular-live-set~~
~~loopback-oracle-builder~~
~~loopback-oracle-installer~~
~~strong-pubsub~~
~~gulp-loopback-sdk-angular~~
~~loopback-sdk-ios-codegen~~
~~loopback-filters~~
~~loopback-sdk-xamarin~~
~~grunt-loopback-sdk-angular~~
~~loopback-acl-route~~
~~loopback-policy~~

~~loopback-example-offline-sync~~
~~loopback-example-relations~~
~~loopback-example-access-control~~
~~loopback-example-app-logic~~
~~loopback-example-user-management~~
~~strong-gateway-demo~~
~~loopback-example-database~~
~~loopback-getting-started-intermediate~~
~~loopback-example-angular-live-set~~
~~loopback-example-app~~
~~loopback-example-remote~~
~~loopback-example-connector~~
~~loopback-example-ssl~~
~~loopback-android-getting-started~~
~~loopback-example-middleware~~
~~loopback-example-pubsub~~
~~loopback-getting-started~~
~~loopback-example-passport~~
~~loopback-example-angular~~
~~loopback-example-isomorphic~~
~~loopback-example-mixins~~
~~loopback-example-push~~
~~loopback-example-xamarin~~
~~loopback-ios-getting-started~~
~~loopback-example~~
~~loopback-sandbox~~

**Comment by bajtos** [comment]
@0candy please check the list of module we are going to deprecate (see https://github.com/strongloop-internal/scrum-loopback/issues/897#issuecomment-232953068) and remove them from the list of modules to globalize.

**Comment by 0candy** [comment]
Just confirmed, none of the deprecated ones are in the list.

**Comment by superkhau** [comment]
@bajtos @Setogit **Blocking question** Do we need to globalize assert/debug/test statements?

**Comment by bajtos** [comment]
> Do we need to globalize assert/debug/test statements?

No.

**Comment by bajtos** [comment]
@0candy can we close this as done?

**Comment by 0candy** [comment]
@bajtos You asked me to leave it open until all the modules are released. I moved it to the TBR column.
Feel free to close it if you don't think its necessary.

**Comment by bajtos** [comment]
Some (most) of the modules has been released, we think that's good enough for now. We will be releasing new versions when we receive translated strings.
