### ISSUE TITLE
Help with view count.

### ISSUE THREAD

**Issue by upupzealot** [strongloop/loopback#2427]
Now I have a model named "Topic", and what I want to do is to figure out how many times each topic was viewed.

If I add a logic like
`topic.updateAttribute('view_count', topic.view_count + 1)`
to a `breforeRemote('findById')` function, it will solve the problem.

But, what if I need a page to **edit** a topic. For that, I have to find the specific topic by id, and present it to user before they can edit it. And this action of "show edit page" should not count to view_count.

**Comment by davidcheung** [comment]
Hi @upupzealot, you could perhaps use a remoteMethod to call the edit, then add metadata to filter it, or vice versa. perhaps you can start a discussion on our [Google groups or stackoverflow](https://github.com/strongloop/loopback/wiki/Questions) to seek a more elegant solutions, closing this issue now as we only accept feature requests / bug reports on Github issues, please feel free to reopen the issue if you see fit.
