### ISSUE TITLE
Include related models saves unwanted data to mongo

### ISSUE THREAD

**Issue by mamartins** [strongloop/loopback#2428]
So, I have a product model which belongs to a Vat model. I added on the json the option to fetch always the vat with the product model

```
  "scope": {
    "include": [
      "vat"
    ]
  }
```

If I simply perform a save() after getting one product that has the vat embedded on it, it saves to the database the vat object in the product along with vatId.

```
        Product.findById(
            data.id,
            function (error, product) {
                product.save(function (err, savedObj) {
                    console.log(savedObj);
                });
            });
```

This console logs, log a correct object only with the vatId in it, but that is not what is only saved to the database.

database object:

```
{
  "_id": ObjectId("570696884d6906cd2dbac0a6"),
  "name": "Pasta",
  "description": "pasta",
  "createdAt": new Date(1460049544975),
  "updatedAt": new Date(1465904280495),
  "storeId": ObjectId("57069235b7747c7e2d6c6fec"),
  "vatId": ObjectId("5759aa610dd166883f80916c"),
  "vat": {
    "description": "geral",
    "value": 23,
    "id": ObjectId("5759aa610dd166883f80916c")
  }
}
```

```
product.vat(newVat);
product.save(function (err, savedObj) {
   console.log(savedObj)
   console.log(savedObj.vat); // this logs the first vat that was returned in the findById method
});
```

This can produce very strange results if I update the vat relation, where the vatId gets updated and the previously vat field added don't, also querying the relation using product.vat() returns me the vat object that was saved (how?!) and not the one that vatId references

**Comment by jannyHou** [comment]
@mamartins I am trying to reproduce your problem. Just a confirm:
all the relations you have is
`product` belongsTo `vat`
right?

> If I simply perform a save() after getting one product that has the vat embedded on it

Do you have a hasMany or embedsMany from `vat` to `product`?

**Comment by mamartins** [comment]
@jannyHou the Vat has a relation HasMany to Product and Product a BelongsTo to Product

**Comment by pbtcjasper** [comment]
We're having the same issue. We use the include filter in our query. A workaround: You can use `updateAttributes` instead of `save`. This works for us.

**Comment by mitsos1os** [comment]
This should be fixed by this [merge request](https://github.com/strongloop/loopback-datasource-juggler/pull/1259) in datasource-juggler
