### ISSUE TITLE
Capitalized Relation name causes dupes/fails on mssql

### ISSUE THREAD

**Issue by garygentry** [strongloop/loopback#2429]
I have related models (example at bottom) setup where the relation name is the same as name of the related model, both capitalized first letter.  When I do a simple api call it's returning 2 fields for each foreign key, one with a capital first letter and another with a lower first letter.

/api/Foo/1 returns:
{
 Id: 1,
 Name: "Foo1",
 barId: 2,
 BarId: 2
}

The biggest issue with this is when using mssql, both columns get generated in the sql call and Sql Server throws an error for duplicate columns. The sql that gets generated for Postgresql seems to only have one column for each fkey which is generated as all lower, but the api still returns both columns. If I name the relations lower first letter, the api returns only one field for each fkey, however my client is using capiitalized relation names so that doesn't work for me.

Is this a bug in the mssql stack or am I doing something wrong?

Models:
{
    "name": "Foo",
    "base": "PersistedModel",
    "idInjection": false,
    "properties": {
        "Id": {
            "id": true,
            "generated": true,
            "type": "Number",
        },
        "Name": {
            "type": "String",
        }
    },
    "relations": {
        "Bar": {
            "model": "Bar",
            "type": "belongsTo"
        },
    }
}

{
    "name": "Bar",
    "base": "PersistedModel",
    "idInjection": false,
    "properties": {
        "Id": {
            "id": true,
            "generated": true,
            "type": "Number",
        },
        "Name": {
            "type": "String",
        }
    },
    "relations": {
        "Foos": {
            "model": "Foo",
            "type": "hasMany"
        },
    }
}

**Comment by garygentry** [comment]
Looking at this a little closer..

In loopback-connector-mssql/mssql.js, the 'buildSelect' prototype method constructs a sql statement that includes the duplicated columns (BarId/barId) returned by loopback for the model.  Then, if the filter has a limit, as with findById, it wraps the statement in a subquery like this:

`SELECT * FROM (SELECT [Id],[BarId],[barId],ROW_NUMBER() OVER ( ORDER BY [Id]) AS RowNum FROM [dbo].[Foo] WHERE [Id]=1) AS S WHERE S.RowNum > 0 AND S.RowNum <= 1`

This is an invalid Sql Server statement (_The column 'barId' was specified multiple times for 'S'_.), selecting * from the subquery which has duplicate column names.  The subquery alone will work and return the BarId and barId as aliases, so non-limited calls succeed.

If loopback needs the upper and lower case values in the return, that could be achieved by selected both (BarId/barId) in the wrapping select but only specifying each column once in the subquery.

Hard to believe no one else has an issue with this, unless I'm way off on how the models are supposed to be defined..

Any ideas?

**Comment by loay** [comment]
Hi @garygentry 
Is you app available on github so I can reproduce the issue? Thanks.

**Comment by garygentry** [comment]
It’s not public and would take some effort to do a generic repro, but I’ve narrowed down the code that generates the invalid Sql Server statements.

In loopback-connector-mssql/mssql.js, buildSelect gets called and is passed in the duplicated columns (upper and lower first letter for the foreign key columns).  Since it’s a findById call, it’s filter.limit is true, and the buildSelect method calls applyPagination, which wraps the generated sql to call it as a subquery (pasted and highlighted the mssql code below).

That results in this command getting issued to Sql Server:

SELECT * FROM (SELECT [Id],[BarId],[barId],ROW_NUMBER() OVER ( ORDER BY [Id]) AS RowNum FROM [dbo].[Foo] WHERE [Id]=1) AS S WHERE S.RowNum > 0 AND S.RowNum <= 1

Which causes this error in Sql Server:

The column 'barId' was specified multiple times for 'S'.

Since posting the issue, I found the supportsOffsetFetch option which can be used on Sql Server 2012 or later which tries to use the OFFSET/FETCH commands instead of the above syntax.  So, I set that option, and that has a different bug.  It simply appends OFFSET/FETCH syntax to the end of the statement which does not work.  For the OFFSET statement to be valid, the ORDER BY statement needs to be called right before the OFFSET command, and instead order by is embedded in the statement as above and not right before the OFFSET.

So, I was able to hack a temp workaround by putting another ORDER BY statement right before the OFFSET FETCH and it works.  But obviously a real hack.  Relevant mssql.js code is below which includes my temp workaround.

The bigger question is why is the connector being passed duplicate properties for each fkey.  If the connector were passed a single property for each column, the connector should work.  All of my model properties and relations are defined with upper first letter.  The other side effect is the api call returns a lower and upper case version for each of those properties.  That’s not a deal-killer, but it is additional unnecessary data getting returned from the calls.

Hope this is enough…



loopback-connector-mssql/mssql.js

MsSQL.prototype.buildSelect = function(model, filter, options) {

  if (!filter.order) {
    var idNames = this.idNames(model);
    if (idNames && idNames.length) {
      filter.order = idNames;
    }
  }

  var selectStmt = new ParameterizedSQL('SELECT ' +
    this.buildColumnNames(model, filter, options) +
    ' FROM ' + this.tableEscaped(model)
  );

  if (filter) {

    if (filter.where) {
      var whereStmt = this.buildWhere(model, filter.where);
      selectStmt.merge(whereStmt);
    }

    if (filter.limit || filter.skip || filter.offset) {
      selectStmt = this.applyPagination(
        model, selectStmt, filter);
    } else {
      if (filter.order) {
        selectStmt.merge(this.buildOrderBy(model, filter.order));
      }
    }

  }
  return this.parameterize(selectStmt);
};


MsSQL.prototype.applyPagination =
  function(model, stmt, filter) {
    var offset = filter.offset || filter.skip || 0;
    if (this.settings.supportsOffsetFetch) {
      // SQL 2012 or later
      // http://technet.microsoft.com/en-us/library/gg699618.aspx
      //BEGIN GG CHANGE
      var orderBy = this.buildOrderBy(model, filter.order);
      var limitClause = buildLimit(filter.limit, filter.offset || filter.skip);
      return stmt.merge(orderBy + ' ' + limitClause);
      //END GG CHANGE
      //var limitClause = buildLimit(filter.limit, filter.offset || filter.skip);
      //return stmt.merge(limitClause);
    } else {
      // SQL 2005/2008
      // http://blog.sqlauthority.com/2013/04/14/sql-server-tricks-for-row-offset-and-paging-in-various-versions-of-sql-server/
      var paginatedSQL = 'SELECT * FROM (' + stmt.sql + MsSQL.newline +
        ') AS S' + MsSQL.newline + ' WHERE S.RowNum > ' + offset;

      if (filter.limit !== -1) {
        paginatedSQL += ' AND S.RowNum <= ' + (offset + filter.limit);
      }

      stmt.sql = paginatedSQL + MsSQL.newline;
      return stmt;
    }
  };



Models:

{
    "name": "Foo",
    "base": "PersistedModel",
    "idInjection": false,
    "properties": {
        "Id": {
            "id": true,
            "generated": true,
            "type": "Number"
        },
        "Name": {
            "type": "String",
            "required": false
        }
    },
    "validations": [],
    "relations": {
        "Bar": {
            "model": "Bar",
            "type": "belongsTo"
        },
  }
}


{
    "name": "Bar",
    "base": "PersistedModel",
    "idInjection": false,
    "properties": {
        "Id": {
            "id": true,
            "generated": true
        },
        "Name": {
            "type": "String"
        }
    },
    "validations": [],
    "relations": {
        "Foos": {
            "model": "Foo",
            "type": "hasMany"
        }
    }
}

**Comment by loay** [comment]
@garygentry Thanks, I will try to see what I can do with the details you provided.
