### ISSUE TITLE
Typo in strongloop documentation type of the Principal: "Use"

### ISSUE THREAD

**Issue by hackerunet** [strongloop/loopback#2430]
dear support I think I found a typo in API documentation regarding Type of principal, instead of User its shown "Use"
If is not a typo please explain why the principal type is Use instead of User;
regards
this is the section: http://apidocs.strongloop.com/loopback/#acl
Quote:
principalType 	String 	
```
Type of the principal; one of: Application, Use, Role.
```

**Comment by davidcheung** [comment]
related code : https://github.com/strongloop/loopback/blob/42c83f69a090664bb025d89f8dd5f5a7a3ffa34e/common/models/acl.js#L75

**Comment by crandmck** [comment]
Fixed with 01a9fa2ab2a60362d8b945a3b98569b5b4acc0ed
