### ISSUE TITLE
Provide VUE.JS support

### ISSUE THREAD

**Issue by murbanowicz** [strongloop/loopback#2431]
Hi,

I know that Angular was the biggest one and it still is,
but VueJS is trening really quickly and would be really worth to provide VueJS SDK.

**Comment by davidcheung** [comment]
Hi @mariaczi, 
Thanks for bringing this up, but we are trying to move to a more generic approach for **sdk**s, see [conversation](https://github.com/strongloop/loopback-sdk-angular/issues/188#issuecomment-203512778) for some insights to the reasons behind.

**Comment by anoop-ananthan** [comment]
Angular was the biggest thing. Now it's dead... React and Vue is the thing now.... 
Support for both would be in the greatest interest for Strongloop

**Comment by virkt25** [comment]
@anoop-ananthan Would you be interested in creating something?
