### ISSUE TITLE
Does PersistedModel fully support the Promise?

### ISSUE THREAD

**Issue by Emiya0306** [strongloop/loopback#2433]
Is PersistedModel really supported the Promise? And Promise.all cannot get relation method about the model too. Here is [the old issue](https://github.com/strongloop/loopback/issues/2150#issuecomment-199097351) I found. Thanks.

```javascript
class System {

  constructor(server) {

    this.models = server.models;
    this.adminUser = {};
    this.adminRole = {};
    this.isSetup = false;

  }

  initialize(data) {

    return this.createRoles().then((roles) => { // this.models.role.create(...).then is undefined

      this.adminRole = roles[0];
      return this.createAdminUser(data);

    }).then((admin) => {

      this.adminUser = admin;
      return this.linkAdminUser();

    }).then((result) => {

      this.initializeDone();
      return new Promise(resolve => resolve());

    });
  }

  createRoles() {
    return this.models.role.create([
      {name: 'admin', description: 'Administrator'},
      {name: 'owner', description: 'Models Owner'},
      {name: 'member', description: 'Models Member'}
    ])
  }

  createAdminUser(data) {
    return this.models.user.create(data)
  }

}
```

**Comment by Emiya0306** [comment]
I got it, because I role.create(Array data), and return Array data not Promise.

But in API doc it says `PersistedModel.create({Object}|[{Object}], callback)`, so it should be support the promise right?

**Comment by jannyHou** [comment]
@Emiya0306 I think you are trying batch create, please check this comment for details:  https://github.com/strongloop/loopback/issues/2164#issuecomment-215645590

> But in API doc it says PersistedModel.create({Object}|[{Object}], callback), so it should be support the promise right?

The doc you mention is only valid for callback signature. The doc for promise is not ready yet, and batch operations do need us to take care of in the future.

**Comment by Emiya0306** [comment]
@jannyHou Thanks very much. I get it and avoid to use batch create model.
