### ISSUE TITLE
A bug on the doc page 'Using current context'

### ISSUE THREAD

**Issue by upupzealot** [strongloop/loopback#2438]
It says

> LoopBack context is now enabled by default for REST APIs via loopback.rest() middleware. Configure it in server/config.json as follows:
```json
"remoting": {
  "context": {
    "enableHttpContext": false
  },
  ...
}
```

but actually you have to set `enableHttpContext` to `true` not `false`

link: https://docs.strongloop.com/display/APIC/Using+current+context

**Comment by seriousben** [comment]
Actually it is enabled by default. enableHttpContext only let's the req and res be added to it.

**Comment by superkhau** [comment]
@crandmck ^

**Comment by upupzealot** [comment]
@seriousben I don't think it's enabled by default.
I created a new project and the `enableHttpContext` is set to `false`.
Since the doc says I can enable it by setting it to `false`, that's weird, I think it should be `true` in the doc

**Comment by Sequoia** [comment]
> I created a new project and the `enableHttpContext` is set to `false`.

Here's my server config from a brand new scaffolded Loopback 2.34.1 application:

```js
{
  "restApiRoot": "/api",
  "host": "0.0.0.0",
  "port": 3000,
  "remoting": {
    "context": false,
    "rest": {
      "normalizeHttpPath": false,
      "xml": false
    },
    "json": {
      "strict": false,
      "limit": "100kb"
    },
    "urlencoded": {
      "extended": true,
      "limit": "100kb"
    },
    "cors": false,
    "handleErrors": false
  },
  "legacyExplorer": false
}
```

**`remoting.context.enableHttpContext` is not present**. Is this issue resolved?

**Comment by crandmck** [comment]
@bajtos Since currentContext is deprecated, should we spend time on this issue?

**Comment by bajtos** [comment]
As part of working on https://github.com/strongloop/loopback/pull/2439, I have changed the doc page a bit. Right now, new applications are scaffolded with `context: false` and the option was removed from LoopBack 3.0 completely.

I am closing this issue as fixed.
