### ISSUE TITLE
Spike: GitHub issue templates integration

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2442]
_From @superkhau on June 16, 2016 0:20_

We should take advantage of GitHub templates for repetitive community tasks. See https://github.com/blog/2111-issue-and-pull-request-templates

We should spike on this to see which parts we need and how to fit it into our goals. From what I can tell so far, this willl help with the standard community PR questions and triage questions.

_Copied from original issue: strongloop-internal/scrum-loopback#931_

**Comment by superkhau** [comment]
_From @bajtos on June 16, 2016 13:44_

You can start looking at what Node.js uses:
 - https://raw.githubusercontent.com/nodejs/node/master/.github/ISSUE_TEMPLATE.md
 - https://raw.githubusercontent.com/nodejs/node/master/.github/PULL_REQUEST_TEMPLATE.md

My main concern is how to update these files across all 20+ loopback repositories we have.

Also please move the discussion to a public issue in `strongloop/loopback` so that we can involve the community too.

**Comment by superkhau** [comment]
>My main concern is how to update these files across all 20+ loopback repositories we have.

A simple script will do it, I already maintain a master list of repos in loopback-triage for such purposes (in fact, I'm thinking about moving the master list into a public repo -- loopback-officially-supported-repos or something that exports a list as an array and that is coupled to any repos that want to use it).

**Comment by superkhau** [comment]
@bajtos After doing a bit of spiking on this, its fairly simple to integrate templates. However, I think we need to use a combination of updating CONTRIBUTING.md and ISSUE_TEMPLATES.md.

For example, we need the users to read http://loopback.io/doc/en/contrib/Reporting-issues.html when creating new issues -- this shows up as a yellow bar when creating issues (the content is from CONTRIBUTING.md).

The issue templates will help us get the answers for the common things, like link to repro repo, etc.

So the outcome is I propose two things:

1. Update CONTRIBUTING.md with content from the relevant LoopBack wiki sections (take advantage of the yellow bar that shows up when opening issues/PRs)
2. Add ISSUE_TEMPLATE.md with what we expect users to fill out when opening issues:

```
# Bug or feature request (please post questions at Google Group or ask on Gitter)

# Description

# Expected result

# Actual result (if bug)

# Link to sample repo to reproduce issue

# Node version

# LoopBack version

```

**Comment by bajtos** [comment]
> We could also take advantage of PULL_REQUEST_TEMPLATES -- might be good or annoying, basically something like:


Take a look at https://github.com/nodejs/node/blob/master/.github/PULL_REQUEST_TEMPLATE.md for inspiration.

> also take a look at ATOM for inspiration (they have tons of links etc to various sections https://github.com/atom/atom/blob/master/CONTRIBUTING.md)

Please look at https://github.com/nodejs/node/blob/master/CONTRIBUTING.md too

**Comment by superkhau** [comment]
Closing this in favour of https://github.com/strongloop/loopback/issues/2844 for CONTRIBUTING.md and #2837 for PR template integration.

**Comment by bajtos** [comment]
> Closing this in favour of #2844 for CONTRIBUTING.md and #2837 for PR template integration.

@superkhau how about the issue template? Has it already been added to all loopback projects that have issue tracker? AFAICT, https://github.com/strongloop/loopback-boot does not have it yet.

**Comment by superkhau** [comment]
>@superkhau how about the issue template? Has it already been added to all loopback projects that have issue tracker? AFAICT, https://github.com/strongloop/loopback-boot does not have it yet.

Not yet, I'm just doing them on the side (they are not in my sprint backlog ATM, but I figured it's important enough to get the ball rolling). The plan I had in my head was get the entire `.github` dir stuff done (issue+pr templates, contributing.md) then create a task to write a script to replicate the entire dir across all repos). We can switch it up to replicate ISSUE_TEMPLATE first, then land PR template, replicate across etc.
