### ISSUE TITLE
How to access loopback explorer through apache ssl?

### ISSUE THREAD

**Issue by r1b** [strongloop/loopback#2443]
We run loopback behind apache w/ssl. When I try to use the explorer it forces all requests to http:

`http://loopback.example.com:80/api/path/to/endpoint`

How can I configure the explorer to use https? I do not want to run an https server as described [here](https://github.com/strongloop/loopback-example-ssl). I only want ssl between the public internet and apache.

**Comment by r1b** [comment]
Looking at the "raw" source of one of our resources, it looks like I want to override the "basePath" in swagger:

```
{
  ...
    "basePath": "http://loopback.example.com/api",
  ...
}
```

Is this correct? Is this possible?

**Comment by davidcheung** [comment]
@r1b hope this helps, I believe you'll need to set  [component-explorer](https://github.com/strongloop/loopback-component-explorer#options) docs from `component-config.json` or `component-config.production.json` 
```
{
  "loopback-component-explorer": {
    "protocol": "https"
  }
}
```

i believe your swagger result should be something like, see [swagger specs](http://swagger.io/specification/)
```js
{
  host: "loopback.example.com",
  basePath: "/api",
  schemes: [
    "http",
    "https"
  ]
}
```

----- 
and please note that we only accept Feature requests / Bug reports on github issues, it is advised that you post questions and usage related issues on our [Google groups or stackoverflow](https://github.com/strongloop/loopback/wiki/Questions).
