### ISSUE TITLE
launch.json (vs code) for modules?

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#2444]
@bajtos @raymondfeng @superkhau @0candy 

What do you all think about adding a `launch.json` file to various projects? I'm not sure what other people are doing, so I figured we could just discuss on here. It would be nice to be able to open up any loopback repo and debug/run the tests from vs code without having to customize the launch.json file.

Maybe there is another way to do this?

**Comment by gunjpan** [comment]
I've been using VS Code for a while now for debugging test cases, and I always use `Attach` mode from default `launch.json` to connect vscode to debugger ran using `mocha --debug-brk` or similar commands.
Point: did not ever need to explicitly modify `launch.json`

**Comment by ritch** [comment]
> Point: did not ever need to explicitly modify launch.json

Cool. I'll re-open if that doesn't work well enough.

**Comment by ritch** [comment]
@gunjpan this works really well by the way thanks!!!
