### ISSUE TITLE
Variables cannot be concatenated with rest string in middleware.json

### ISSUE THREAD

**Issue by f-w** [strongloop/loopback#2456]
[Defining middleware](https://docs.strongloop.com/display/public/LB/Defining+middleware#Definingmiddleware-Usingvariablesinvalues) documented how to use variables in file `middleware.json`. It works if the variable takes entire string value, but not if the value contains other string. For example, if `clientRoot = /ext`, then following static config resolves `/ext` by `"${clientRoot}"`, but `/ext/foo` cannot be resolved by `"${clientRoot}/?*"`. If I replace `"${clientRoot}/?*"` with hard-coded `"/ext/?*"` then it works.

```
  "files": {
    "loopback#static": [
      {
        "paths": [
          "${clientRoot}",
          "/"
        ],
        "params": "$!../client/dist"
      },
      {
        "paths": [
          "${clientRoot}/?*"
        ],
        "params": "$!../client/dist"
      }
    ]
  },
```

**Comment by 0candy** [comment]
We currently replace the whole variable value and don't support having the variable as part of the path.

Another user requested the same feature: https://github.com/strongloop/loopback-boot/pull/181#issuecomment-216433322

**Comment by jdhrivas** [comment]
+1

**Comment by caiyufei** [comment]
I have the same issue , I have to use hard code now : 
  "parse": {
    "body-parser#raw": {
      "paths": [
        "/api/v1/Buckets/?*/upload"
      ]
    }
  },
But expect the following one : 
  "parse": {
    "body-parser#raw": {
      "paths": [
        "${restApiRoot}/Buckets/?*/upload"
      ]
    }
  },

**Comment by ashwell** [comment]
go away stale bot
