### ISSUE TITLE
Question about app.models

### ISSUE THREAD

**Issue by Emiya0306** [strongloop/loopback#2457]
Here I want to get all mixins models, and to do some things, so I print out all model mixins. But in models it has duplicate models in `app.models`, just like `article` and `Article`.

Is there some differences about the duplicate models? I just like to know more about this. Thanks! 😄 

```javascript
for (const modelName in app.models) {
  if(app.models.hasOwnProperty(modelName)){
    console.log(modelName, app.models[modelName].settings.mixins);
  }
}
```

**Comment by 0candy** [comment]
To retrieve the list of models, you should do:
`
var models = app.models();
models.forEach(function(Model) {
  console.log(Model.modelName); // put your change here
});
 `

**Comment by Emiya0306** [comment]
Thank you, got it!
