### ISSUE TITLE
Model.relation(modelToRelate) - not working, but not throwing error

### ISSUE THREAD

**Issue by murbanowicz** [strongloop/loopback#2460]
It is really bad issue.
I found one thread about it but I think it should be changed.

I have user and let's say group.
User can be created without group, but when he does not have group, he has to create one or get access to one.
When he is creating new one, I need to relate him with this group as owner and also relate this group with him.
Second one is simple, as it is easy to inject userId to `context.args.data.userId`.
Second one is more complicated and I did not find solution so far...

In my `common\models\group.js` I have:

```
Group.afterRemote('create', function(context, group, next) {
        var user = Group.app.models.UserModel.findById(group.userId, function(err, user) {
            if (err) {
                return next(err);
            }
            if (!user) {
                return next(new Error('No user '));
            }
            user.group(group);
            console.log(user);
        });
```

It is assigning groupId to user which is visible in console log, but it's not saving that as it is not visible in database. It is not throwing any error.
I thought that finally I found solution when I saw groupId in console but not...
Generally, based on documentation, it should be much simpler:

```
Group.afterRemote('create', function(context, group, next) {
user.group(group);
}
```

that should be all but it is not and it is not working as supposed to. Of course - AS IT SHOULD BE also does not throw any error.

Any idea?

**Comment by 0candy** [comment]
Based on your snippet, this is what I suggest. To access the user model in group.js you should require the server class:

```
var app = require('../../server/server'); 

module.exports = function(Group) {
  Group.afterRemote('create', function(context, group, next) {
    var user = app.models.UserModel.findById(group.userId, function(err, user) {
```
Not sure if you called `next();` somewhere in that block. See doc:
https://docs.strongloop.com/display/APIC/Remote+hooks#Remotehooks-Signature

If that doesn't resolve your issue, would you mind forking the sandbox with your repo so I can see the rest of the config?
https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report
Thanks!

**Comment by mariaczi** [comment]
I call next of course.
I think that it should work as I wrote:
```
Group.afterRemote('create', function(context, group, next) {
user.group(group);
}
```
without having to find etc. It's making relations useless.

**Comment by jannyHou** [comment]
@mariaczi If I understand correctly, first you complain that `user.group()` doesn't throw error when your filter is not valid, that's something we should improve in the future, it's already in our roadmap.

Then could you elaborate more about what do you expect `user.group()` do? This is the current doc for a relation method like `parentModelInstance.children()`: http://loopback.io/doc/en/lb2/HasMany-relations.html#methods-added-to-the-model
It will return you the children items but not doing "save"
