### ISSUE TITLE
nestRemoting methods not callable from code

### ISSUE THREAD

**Issue by Saganus** [strongloop/loopback#2461]
Hello.

I originally posted this in the LoopBack Google Groups page 

[https://groups.google.com/forum/#!searchin/loopbackjs/akram.shehadi/loopbackjs/QbC8k8OUM5c/32Ot4ggrAQAJ] but I think this could actually be a bug.

I've been working with nestRemoting() to enable nested queries in related models.

This mechanism is working perfectly fine when making request from HTTP, i.e. if I call 

`http://myserver/api/Photos/<id>/folder/account`

I will basically traverse up the chain from Photo to Account, as expected from my defined relations:

```
Account hasMany Folder
Folder hasMany Photo

Photo belongsTo Folder
Folder belongsTo Account
```

However I need to call this inside a role resolver, and thus I need to call from code and not an HTTP request.

My first tries are revolving around getting just the first level correctly and worry about the second level later. 

I have tried doing:

```
Photo.folder();
Photo.prototype.folder();
Photo.prototype.folder('<id>');
Photo.prototype.__get__folder();
Photo.prototype.__get__folder('<id>');
```

to no avail.

So after looking around for a while I found that I could do

`Photo.sharedClass.methods()`

since nestRemoting() is using the strong-remoting module, and found that indeed there is something defined that should allow me to traverse up the chain. If I search inside the result of methods() for a method that would return the upper leve, I found this:

```
{ fn: 
   { [Function]
     getAsync: [Function],
     update: [Function],
     destroy: [Function],
     create: [Function],
     build: [Function],
     _targetClass: 'Folder' },
  name: '__get__folder',
  aliases: [],
  isStatic: false,
  accepts: [ { arg: 'refresh', type: 'boolean', http: [Object] } ],
  returns: [ { arg: 'folder', type: 'Folder', root: true } ],
  errors: [],
  description: 'Fetches belongsTo relation folder.',
  accessType: 'READ',
  notes: undefined,
  documented: true,
  http: { verb: 'get', path: '/folder' },
  rest: {},
  shared: true,
....
...
(other stuff)
```

But I can't seem to able to execute the function fn() from the object above.

I get the following error:

```
error: uncaughtException: Cannot read property 'folder' of undefined date=Fri Jun 03 2016 16:29:06 GMT-0500 (CDT), pid=4504, uid=0, gid=0, cwd=/myproject, execPath=/usr/bin/nodejs, version=v0.12.14, argv=[node, /myproject], rss=97136640, heapTotal=80329216, heapUsed=55331216, loadavg=[1.31396484375, 0.818359375, 0.59326171875], uptime=65740
TypeError: Cannot read property 'folder' of undefined
    at BelongsTo.Relation.getCache (/myproject/node_modules/loopback-datasource-juggler/lib/relation-definition.js:290:46)
    at BelongsTo.related (/myproject/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1436:24)
    at Object.module.exports [as func] (/myproject/server/boot/101-role-resolver.js:27:22)
    at /myproject/node_modules/loopback-boot/lib/executor.js:285:9
    at iterate (/myproject/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at /myproject/node_modules/loopback-boot/node_modules/async/lib/async.js:157:25
    at /myproject/node_modules/loopback-boot/lib/executor.js:287:7
    at iterate (/myproject/node_modules/loopback-boot/node_modules/async/lib/async.js:146:13)
    at /myproject/node_modules/loopback-boot/node_modules/async/lib/async.js:157:25
    at /myproject/node_modules/loopback-boot/lib/executor.js:287:7
```

If I go to line 289 of relation-definition.js file, and we have this function:

```
Relation.prototype.getCache = function () {
  return this.modelInstance.__cachedRelations[this.definition.name];
};
```

So I tried printing this.modelInstance and got:

```
{ id: [Getter/Setter],
  name: [Getter/Setter],
  createdDate: [Getter/Setter],
  description: [Getter/Setter],
  folderId: [Getter/Setter],
  save: [Function],
  isNewRecord: [Function],
  getConnector: [Function],
  destroy: [Function],
  delete: [Function],
  remove: [Function],
  setAttribute: [Function: setAttribute],
  updateAttribute: [Function: updateAttribute],
  setAttributes: [Function: setAttributes],
  unsetAttribute: [Function: unsetAttribute],
  updateAttributes: [Function: updateAttributes],
  reload: [Function: reload],
  __findById__photos: [Function],
  __destroyById__photos: [Function],
  __updateById__photos: [Function],
  __exists__photos: [Function],
  _scopeMeta: {},
  __get__photos: [Function],
  __create__photos: [Function],
  __delete__photos: [Function],
  __update__photos: [Function],
  __findOne__photos: [Function],
  __count__photos: [Function],
  folder: [Getter],
  __get__folder: [Function] }
```

And you can see at the end that indeed we do have a "__get__folder" function, however for some reason there are no cachedRelations.

So my question is, is there anything that I need to do manually so that the cachedRelations are populated and thus I'm able to call my nestRemoting functions from within code?

Any other ideas on where I might be going wrong?

By the way, I am making sure that relations (i.e.  hasMany() and belongsTo() as well as nestRemoting()) are being set before I try to run this code, so not sure at what other point would the relations be cached after that but before the code I want to run, such that it would be undefined by the time we get there.

Finally, looking around that file I also found this:

```
/**
 * Define the method for the belongsTo relation itself
 * It will support one of the following styles:
 * - order.customer(refresh, options, callback): Load the target model instance asynchronously
 * - order.customer(customer): Synchronous setter of the target model instance
 * - order.customer(): Synchronous getter of the target model instance
 *
 * @param refresh
 * @param params
 * @returns {*}
 */
BelongsTo.prototype.related = function (condOrRefresh, options, cb) {
...
...
}
```

So it would appear as per the function comment that indeed I should be able to do

`order.customer()`

in a belongsTo relation, i.e. in my case:

`photo.folder()`

Edit:

I realized that I probably need to operate on the instance object itself and not the model, so I tried:

```
Photo.findById('af4a9dab-12f4-450d-87ee-13110e2da602',function(err, photo){
    console.log(photo);
    console.log(Object.getOwnPropertyNames(photo));
    console.log(photo.__cachedRelations);
  });
```

And the result was:

```
{ name: 'Test Photo',
  createdDate: Sun May 29 2016 19:00:00 GMT-0500 (CDT),
  description: 'string',
  projectId: '98d0bc9e-5008-4d09-9be0-5d194bd894b2',
  id: 'af4a9dab-12f4-450d-87ee-13110e2da602' }
[ '__cachedRelations',
  '__data',
  '__dataSource',
  '__strict',
  '__persisted' ]
{}
```

So the Photo exists and we can see that in the properties we do have a __cachedRelations array, but it's empty.

Thanks a lot for reading and any pointers or ideas are greatly appreciated!

Akram

**Comment by davidcheung** [comment]
I believe this is a bug as well, how and when relations are populated seems inconsistent, 
when i add new record, then the first time around I get `photo.folder()` populated 
then when the `create` is done as `update` it doesnt get `photo.folder()` anymore
issue reproduced on https://github.com/strongloop/loopback-sandbox/compare/master...davidcheung:nest-remoting-sandbox-2461?expand=1


### Scenario 1
1) creating the account
2) creating folder
3) creating photo
4) i get `photo.folder()`
![screen shot 2016-07-18 at 2 45 19 pm](https://cloud.githubusercontent.com/assets/1787590/16926796/55e02bbc-4cf8-11e6-81a5-ebd6a579803e.png)

### Scenario 2
1) findbyid for account
2) creating folder
3) creating photo
4) i dont get `photo.folder()` or `photo.__data.folder` or `photo.__cachedRelation.folder`
![screen shot 2016-07-18 at 2 41 53 pm](https://cloud.githubusercontent.com/assets/1787590/16926800/5a3c8836-4cf8-11e6-8723-35f00a8ad90e.png)

@jannyHou @Amir-61  any ideas?
