### ISSUE TITLE
User can install a connector that loopback doesn't support by accident

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback#2462]
From @qpresley 
> loopback generator may install a bad package due to a user mistyping a module name and attempting to use it without knowing they got something they weren't intending.

We should not be able to install a module that is not a lb connector.

**Comment by jannyHou** [comment]
I think as a solution, we’d better maintain a list of supported connectors in loopback-workspace, and validate the custom connector name in generator-lb.

@bajtos @ritch @raymondfeng Any thought?

**Comment by bajtos** [comment]
> We should not be able to install a module that is not a lb connector.

In my opinion, we need to allow users to use 3rd party connector, either community maintained or perhaps their proprietary one.

I guess the problem boils down to how to recognize what package (name?) is a valid connector.

**Comment by qpresley** [comment]
Does use of a 3rd party connector strictly imply that the automatic install of that connector must succeed?  What is wrong with allowing them but not installing them? @bajtos

**Comment by bajtos** [comment]
> Does use of a 3rd party connector strictly imply that the automatic install of that connector must succeed? What is wrong with allowing them but not installing them?

Well, if they configure the connector but don't install it, then the app will fail at startup, because the connector cannot be found. I think it will cause the update-swagger operation, which is run after each `apic` loopback command, to fail.

I don't mind to use a different approach and don't install 3rd party connectors automatically, as long as we find a way to make the app usable by swagger generator after adding a datasource with a 3rd party connector.

**Comment by qpresley** [comment]
I'm not sure there is a good way out of this.  The apic and loopback logic appears to require the connector to be valid yet we will not be able to come up with something that can validate that loopback-connector-db3 is not valid when the user may have meant loopback-connector-db2.  Should someone post a loopback-connector-db3 that is malicious we will have to accept that we allow this and deal with the consequences.

Closing as I don't think this is worth pursuing further.
