### ISSUE TITLE
INCR function needed.

### ISSUE THREAD

**Issue by upupzealot** [strongloop/loopback#2465]
I'm designing a view counter.
So for that reason I need a **INCR** method on the PersistedModel instance.
If I use some code like

``` js
...
Topic.findById(id, function(err, topic) {
  if(!err) {
    callback(err);
  }
  topic.updateAttribue('viewCount', topic.viewCount + 1, function(){...})
})
...
```

It would not be an atomic thing, I think.

**Comment by bajtos** [comment]
@upupzealot you are right, your implementation is not atomic. It makes sense to me to add an operator for making atomic increments & decrements. Would you like to contribute this feature yourself?

**Comment by upupzealot** [comment]
@bajtos I'm not sure, I only familiar with mongodb, to contribute this feature should update all connectors?

**Comment by bajtos** [comment]
@upupzealot no need to update all connectors. You can implement it in the connector you are using only.

However, if you are using MongoDB, then `$inc` is already supported when you enable "allowExtendedOperators" flag. See https://docs.strongloop.com/display/public/LB/MongoDB+connector#MongoDBconnector-UsingMongoDBoperatorsinupdateoperations

**Comment by upupzealot** [comment]
@bajtos I see, but I still want a common method, so that loopback users can no longer do hacks to break the beauty of it's unity.
I'll try what I can do on this.

**Comment by habbes** [comment]
What's the follow up on this? Is it a work in progress, that feature would be quite useful.

**Comment by upupzealot** [comment]
@bajtos is it on the todo list of loopback team?

**Comment by bajtos** [comment]
@upupzealot not really, would you like to contribute this improvement yourself?

**Comment by sebolio** [comment]
any news on this? it's been years
