### ISSUE TITLE
bcrypt.compare makes loopback.getCurrentContext as null, bcryptjs works

### ISSUE THREAD

**Issue by pkgulati** [strongloop/loopback#2469]
If I use loopback middleware context in session:before phase, then during user.login (using loopback passport component with local auth) loopback looses current Context while invoking bcrypt.compare (user.login->user.hasPassword), If I remove bcrypt but use bcryptjs it works perfectly. This is Mac OS.

**Comment by pkgulati** [comment]
do you recommend to use cls-bcrypt?

**Comment by gunjpan** [comment]
@pkgulati : re: `cls-bcrypt`, I am not sure about the reliability, you would need to do your own research.
re: context propogation, we have an ongoing discussion at: #1676 to deprecate it. 
Closing this issue as a duplicate, please comment over there.
