### ISSUE TITLE
Incorrect example for validatesFormatOf

### ISSUE THREAD

**Issue by JonForest** [strongloop/loopback#2472]
In the docs:
https://apidocs.strongloop.com/loopback-datasource-juggler/#validatable-validatesformatof

The example is shown as:
`User.validatesFormat('name', {with: /\w+/});`

And it should be:
`User.validatesFormatOf('name', {with: /\w+/});`

**Comment by gunjpan** [comment]
@crandmck : Hey Rand, could you PTAL. thanks.

**Comment by crandmck** [comment]
Fixed in https://github.com/strongloop/loopback-datasource-juggler/commit/45e14af4a981fcf376276babeb344ceac578186c
Note that the API docs will not reflect this change until loopback-datasource-juggler is republished to npm.
