### ISSUE TITLE
Warn when ACLs used and security not enabled

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback#2474]
If you do not `enableAuth()` in your code, ACLs are ignored by LoopBack. This tripped me up because I used a template where that line wasn't there. IMO, LoopBack should throw a warning in the console when ACLs are encountered on models but aren't being used. While I can see a possibility of someone wanting to add ACLs and not actually have them enforced, I'd think that would be in the _extreme_ minority. I think it is much more likely that someone will simply forget to enable them and would appreciate a warning.

**Comment by crandmck** [comment]
Added a warning in:
- https://docs.strongloop.com/display/APIC/Authentication%2C+authorization%2C+and+permissions
- https://docs.strongloop.com/display/APIC/Controlling+data+access

@cfjedimaster Let me know if that covers it.

**Comment by cfjedimaster** [comment]
1) For the first one, is that enough to enable auth? Ie, you define a function to do so, but you would need to run enableAuthentication to do it, right? I know it may be picky, but I can see folks being confused. 

2) Same comment applies.

**Comment by bajtos** [comment]
Cross posting from https://github.com/strongloop/loopback/issues/2466, which I'll close as a duplicate:

> @ritch 
> One way to do this is to move `enableAuth` into `config.json` which would allow `workspace` to flip the flag on for you when you start defining ACLs...

> Or prompt:
> > You are adding an access control, but auth is not enabled... Would you like to enable it?
