### ISSUE TITLE
DELETE on a related item doesn't return anything

### ISSUE THREAD

**Issue by hgouveia** [strongloop/loopback#2476]
when i do `DELETE /api/modela/id/modelb/fk` , the response is status 204  with empty body content, and should be `{ count : 1 }` like normal DELETE operation in anothers endpoints

this happend to me on mongodb 3.2 , using lastest connector, lastest loopback 2.29.0

**Comment by jannyHou** [comment]
@hgouveia I am trying to reproduce your problem, could you fork this [sandbox](https://github.com/strongloop/loopback-sandbox) and replace it with your code? Thanks.

**Comment by hgouveia** [comment]
@jannyHou , this is the fork https://github.com/hgouveia/loopback-sandbox , i already added some migration in the code to ease the process, 

to reproduce, please run the server, go to the explorer, and try to delete a comment from a post 

*Step 1*
![screenshot 57](https://cloud.githubusercontent.com/assets/668866/16847163/ec234b56-49ef-11e6-815a-696626557161.jpg)

*Step 2*
![screenshot 58](https://cloud.githubusercontent.com/assets/668866/16847168/f0a040da-49ef-11e6-9b9a-9623a7d81b45.jpg)

*Step 3*
![screenshot 59](https://cloud.githubusercontent.com/assets/668866/16847178/fea26dc0-49ef-11e6-87cf-099c4df71645.jpg)

**Comment by jannyHou** [comment]
@hgouveia Thanks i reproduced it.
I am not sure does `destroyById` also returns the `count`, from our [doc](http://apidocs.strongloop.com/loopback/#persistedmodel-destroybyid) it only callback the error msg. But from the code it should include `count` since it eventually called [`destroyAll`](https://github.com/strongloop/loopback-datasource-juggler/blob/06cac9e7d4d05983e7a0646bb35bdfdf5340d15c/lib/dao.js#L2021), which certainly returns `count`
@Amir-61 could you help confirm does `destroyById` contain `count`? Thanks.

But the bug still exist since even `DELETE/Posts/{id}/comments` doesn't return the `count`
![screen shot 2016-07-15 at 11 40 08 am](https://cloud.githubusercontent.com/assets/12554153/16880088/82ec88cc-4a81-11e6-93d7-62e55b205731.png)

**Comment by Amir-61** [comment]
>@Amir-61 could you help confirm does destroyById contain count? Thanks.

It should return `info` object indicating the number of affected/deleted items even in NoSQL connectors like `loopback-connector-mongodb`; please see [here](https://github.com/strongloop/loopback-connector-mongodb/blob/01128d046dc549c2eaa8854f3e702e622bffc746/lib/mongodb.js#L900), info object is returned by `destroyId` from `loopback-connetcor-mongodb`. If it does not return `count`, it seems a bug to me; also I suspect this can be a compatibility issue between different versions of `mongodb`; could you or @hgouveia try other mongodb versions (e.g. mongodb `2.6` and `2.4`) to see if you see the same bug with these version?

**Comment by hgouveia** [comment]
@Amir-61 @jannyHou i just tested with MongoDB 2.4.9 on my server, and same problem, i also made this test using memory db and same issue

**Comment by jackrvaughan** [comment]
I am running into this same issue; I try to remove a relation to an item by id but a status code of 204 is returned and the relation is not removed.

**Comment by jackrvaughan** [comment]
@jannyHou After some investigation, I think this could be an issue on my side.  Anytime I try to remove an item from an array within a model instance (say through PATCH `/model/id` for example), it returns the expected instance value with the item from the array removed; but when I request it again via GET `model/id` it returns the array with the item I just deleted included. 

For example, if my instance starts as:

```
{
  "name": "Jackson",
  "favorites": [
    "apples",
    "cherries"
  ],
  "id": 1
}
```

And I run PATCH `user/1` with this body:
```
{
  "name": "Jackson",
  "favorites": [
    "apples"
  ]
}
```
It returns the expected value (without cherries):
```
{
  "name": "Jackson",
  "favorites": [
    "apples"
  ],
  "id": 1
}
```

But if I run GET `user/1` again, I get this back:
 ```
{
  "name": "Jackson",
  "favorites": [
    "apples",
    "cherries"
  ],
  "id": 1
}
```

But I can't seem to reproduce this with the sandbox 😕 Would you have any ideas on what might be causing this?
