### ISSUE TITLE
destroyAll related Models of a Model not doing anything

### ISSUE THREAD

**Issue by henk-scheepers** [strongloop/loopback#2484]
I have the following Model

```
{
  "name": "ProjectTemplate",
  ...
  "relations": {
    "subsector": {
      "type": "belongsTo",
      "model": "Subsector",
      "foreignKey": ""
    },
    "projects": {
      "type": "hasAndBelongsToMany",
      "model": "Project",
      "foreignKey": ""
    }
  },
  ...
}
```

When I try to `ProjectTemplate.projects.destroyAll` the callback function doesn't return any errors, but also doesn't delete anything. I've tried this through the Explorer, NodeJS and using lbServices in an AngularJS app. Still nothing is deleted.

Any ideas why this is happening?

Thanks

**Comment by gunjpan** [comment]
@henk-scheepers : what response code do you get for the method call from Explorer? Do you have any ACLs in place?
If possible, please provide me with a sample repo to reproduce the issue.

**Comment by gunjpan** [comment]
@henk-scheepers: Is this resolved for you? if not, please provide above info.

**Comment by henk-scheepers** [comment]
Hi @gunjpan, I ended up creating a remote method that destroyed the items one by one. 

The Explorer as well as AngularJS loopback service returned a 204 status. If I understand correctly it's supposed to return a object with a count property specifying how many items were deleted.

There are currently no ACL on any of the models except for the custom user model derived from the default User model.

Providing a sample repo might be difficult at this time, but I will see what I can do.

Thanks!

**Comment by gunjpan** [comment]
@henk-scheepers : I see. Yes, you're right, it should return a count of how many objects were deleted.

**Comment by gunjpan** [comment]
@henk-scheepers : Closing this ATM due to inactivity. Please mention me in the comments to reopen it if issue still persists and you've a repo/steps to reproduce, I'll glad to assist you in resolving it. Thank you :)

**Comment by jdhrivas** [comment]
@gunjpan please reopen. 
To reproduce:
1. create a hasmany relationship between two models.
2. DELETE model1/:id/relatedModel/:id returns status 204 No Content

**Comment by gunjpan** [comment]
@jdhrivas : Could you please create a new issue and refer it. LoopBack team would be happy to help. Thank you :)

**Comment by claylua** [comment]
@gunjpan i can verify @jdhrivas steps does reproduce this issue.

Another ways to reproduce this is 

1.  create a hasmany relationship between two models. eg. A has many B
2.  on A.js create after delete observable
3.  inside this observable, delete B using destroyAll won't destroy any B entries.

something like this

`````
A.observe('after delete', function(ctx, next) {
B.destoryAll({'id':xxxxx}, function(err, info){
console.log(info); // this will return 0 no matter what you do until relationship is removed.
});
});
`````

tested on Loopback 3.0
