### ISSUE TITLE
set updatedAt property as new Date()

### ISSUE THREAD

**Issue by celicoo** [strongloop/loopback#2487]
I wonder how to set the property updatedAt of my users model in the PUT endpoint.

Thanks.

**Comment by gunjpan** [comment]
@celicoo : You can use [ `before save` operation hook](https://docs.strongloop.com/display/public/LB/Operation+hooks#Operationhooks-beforesave) to achieve that.
Let me know if that helped you and whether this is good to close.

**Comment by gunjpan** [comment]
@celicoo: is this resolved?

**Comment by yanalavishnu** [comment]
https://docs.strongloop.com/display/public/LB/Defining+mixins

Create a mixin as follows
```
'use strict';
module.exports = function(Model, options) {
  // Model is the model class
  // options is an object containing the config properties from model definition
  Model.defineProperty('createdAt', {type: Date, default: '$now'});
  Model.defineProperty('updatedAt', {type: Date, default: '$now'});

  Model.observe('before save', function event(ctx, next) { //Observe any insert/update event on Model
    if (ctx.instance) {

    } else {
      ctx.data.updatedAt = Date.now();
    }
    next();
  });
};
```

**Comment by alexda14** [comment]
[Another solution used internally by LoopBack](https://github.com/strongloop/loopback/blob/master/common/models/role.js#L30)

**Comment by gunjpan** [comment]
@celicoo : Closing as resolved as multiple solutions available in the comments and guess it's working for you. Should you need further assistance with it, feel free to ping me in comments; will be glad to help you. Thanks.
