### ISSUE TITLE
"Message: Unexpected string" error while migrating to db in StrongLoop

### ISSUE THREAD

**Issue by inv-joseph** [strongloop/loopback#2488]
Hi , I am trying to migrating my model classes to MySql DB with strongloop tool,
When I click the migrate button the following error I got.

Oops! Something is wrong
Unexpected string
Message: Unexpected string
Request: /workspace/api/DataSourceDefinitions/server.mysql/autoupdate
status: 500

Please help.

**Comment by gunjpan** [comment]
@inv-joseph : Hi, is this resolved? if not, could you please provide me a sample repo or `.json` file of the model you're trying to migrate. Also, provide me with the database/schema name from MySQL to better assist you.

**Comment by inv-joseph** [comment]
Yes, this issue is resolved.
