### ISSUE TITLE
401 Authorization Required When Accessing Models

### ISSUE THREAD

**Issue by tetter36** [strongloop/loopback#2490]
I'm running into the same issue that can be found here:
http://stackoverflow.com/questions/36082372/loopback-authentication-error

    {
      "error": {
        "name": "Error",
        "status": 401,
        "message": "Authorization Required",
        "statusCode": 401,
        "code": "AUTHORIZATION_REQUIRED",
        "stack": "Error: Authorization Required\n    at 
      }
    }

In the DEBUG log I was received a getUserId() null and therefore, an isAuthenticated() false. I realized that this is due to the fact that my User Id was 0. I was able to authenticate fine and receive an Access Token as expected, but I wasn't able to use that Access Token for authorization. When I changed the User Id to anything greater than 0, it worked as expected. 

I would recommend updating the default Id provided by Explorer to be 1 instead of 0. If that's not an option, I think it would be good to add a note to the [Introduction to User model authentication](https://docs.strongloop.com/display/public/LB/Introduction+to+User+model+authentication) and [Registering users](https://docs.strongloop.com/display/public/LB/Registering+users) to ensure that the user changes the default Id that is input when clicking the "Model Schema" in Explorer to something other than the 0 that's provided as the default Id.

**Comment by gunjpan** [comment]
@tetter36 : Yes, that looks like a bug to me, a logical lapse is in the lines below of function [`isAuthenticated()`](https://github.com/strongloop/loopback/blob/6964914bab64496c789c434fec39d2914231ee23/lib/access-context.js#L154):
 ```javascript
AccessContext.prototype.isAuthenticated = function() {
  return !!(this.getUserId() || this.getAppId()); 
};
```
for `userID=0`, it will return false. I am not sure if removing support for userID=0 is a good idea.
@bajtos @raymondfeng : Thoughts??

**Comment by gunjpan** [comment]
@tetter36 : After detailed discussion with @davidcheung, realized that we currently do not support `id` set to zero. 
Re. documentation, please follow & comment at issue #2356. I will close this issue for now as aduplicate _(removed my previous comment as irrelevant)_

Should you have any questions concerns, please follow up on 2356. Thank you.
