### ISSUE TITLE
Data mapping should happen by default during model discovery + generation

### ISSUE THREAD

**Issue by cgole** [strongloop/loopback#2493]
Instead of having to manually edit the models to add the data mapping, can we have that automated? Seems like a useful feature to have.

**Comment by cgole** [comment]
Looks like this is how discovery should work by default. Its a bug in discovery..We found it in mysql.. Not tried with other databases.

**Comment by raymondfeng** [comment]
The DB specific mappings should be there by default with discovery. See https://github.com/strongloop/loopback-connector-mysql/blob/master/test/mysql.discover.test.js#L211. Maybe the UI does not?

**Comment by gxvigo** [comment]
+1

**Comment by raymondfeng** [comment]
The loopback-workspace api seems to handle extensions correctly too. See https://github.com/strongloop/loopback-workspace/blob/master/test/model-property.js#L72

**Comment by jannyHou** [comment]
To have a more detailed context of this issue, here is the original buggy scenario:
> when column names in mysql have underscore, and you discover and generate a model the underscore is gone and so the model names dont correspond exactly to the table names.


Related to issue:  https://github.ibm.com/apimesh/scrum-api-editor/issues/814
Will verify is it fixed by issue above asap.

**Comment by bajtos** [comment]
AFAICT, this issue was fixed at the UI side.
