### ISSUE TITLE
Deprecation warning for strong-remoting getFullPath() in loopback-angular-sdk

### ISSUE THREAD

**Issue by buzai** [strongloop/loopback#2494]
Generating "lbServices" for the API endpoint "/api"
Warning: scope User.accessTokens targets class "AccessToken", which is not expos
ed
via remoting. The Angular code for this scope won't be generated.
strong-remoting deprecated getFullPath() is deprecated, use getEndpoints()[0].fu
llPath instead. eval at <anonymous> (C:\Users\chenhao\AppData\Roaming\npm\node_m
odules\strongloop\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:37:287
strong-remoting deprecated getHttpMethod() is deprecated, use getEndpoints()[0].
verb instead. eval at <anonymous> (C:\Users\chenhao\AppData\Roaming\npm\node_mod
ules\strongloop\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:94:12
strong-remoting deprecated getHttpMethod() is deprecated, use getEndpoints()[0].
verb instead. eval at <anonymous> (C:\Users\chenhao\AppData\Roaming\npm\node_mod
ules\strongloop\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:94:48
strong-remoting deprecated getFullPath() is deprecated, use getEndpoints()[0].fu
llPath instead. eval at <anonymous> (C:\Users\chenhao\AppData\Roaming\npm\node_m
odules\strongloop\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:42:130
strong-remoting deprecated getHttpMethod() is deprecated, use getEndpoints()[0].
verb instead. eval at <anonymous> (C:\Users\chenhao\AppData\Roaming\npm\node_mod
ules\strongloop\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:42:214
Saving the generated services source to "C:\\Users\\chenhao\\Desktop\\code\\loop
back-getting-started\\client\\js\\services\\lb-services.js"

**Comment by davidcheung** [comment]
@buzai Thanks for bringing this up, this is not an OS specific issue, we should update to use new method in loopback-sdk-angular
- https://github.com/strongloop/loopback-sdk-angular/blob/f002b5d2a2e959d6b2a8ddb85f7a6209ec203e72/lib/services.template.ejs#L126
- https://github.com/strongloop/loopback-sdk-angular/blob/f002b5d2a2e959d6b2a8ddb85f7a6209ec203e72/lib/services.template.ejs#L76

**Comment by buzai** [comment]
谢谢您的回答我解决了
