### ISSUE TITLE
Unable to Query data models based on relational model condition

### ISSUE THREAD

**Issue by princecharmx** [strongloop/loopback#2495]
Hi,

Scenario: modelA belongs to space
modelA has spaceId
space has field categoryTag

I want to query modelA where related model data has following data  space.categoryTag= "valuex" but I am unable to find a right way.

---
space : 
{id:"1", "categoryTag":"valuex"},
{id:"2", "categoryTag":"valuey"},
{id:"3", "categoryTag":"valuex"}
{id:"4", "categoryTag":"valuez"}

modelA:
{"id":"1", "spaceId":"1"},
{"id":"2", "spaceId":"2"},
{"id":"3", "spaceId":"3"},
{"id":"4", "spaceId":"4"}

Result after querying modelA shoud return:
{"id":"1", "spaceId":"1"},
{"id":"3", "spaceId":"3"}

Help needed

**Comment by princecharmx** [comment]
space : 
{id:"1", "categoryTag":"valuex"},
{id:"2", "categoryTag":"valuey"},
{id:"3", "categoryTag":"valuex"}
{id:"4", "categoryTag":"valuez"}

modelA:
{"id":"1", "spaceId":"1"},
{"id":"2", "spaceId":"2"},
{"id":"3", "spaceId":"3"},
{"id":"4", "spaceId":"4"}


Result after querying modelA shoud return:
{"id":"1", "spaceId":"1"},
{"id":"3", "spaceId":"3"}

**Comment by gunjpan** [comment]
@princecharmx : You can use `include` filter to query related models. Read more [here](https://docs.strongloop.com/display/APIC/Querying+related+models#Queryingrelatedmodels-Inclusion) and [here](https://docs.strongloop.com/display/APIC/Querying+related+models#Queryingrelatedmodels-Usingfiltersparameterswithincludedrelations). 
Hope that would resolve your question.

**Comment by gunjpan** [comment]
@princecharmx : Closing this for now, should you need further assistance with it, mention me in the comments and I'll be glad to help. Thank you :)

**Comment by princecharmx** [comment]
@gunjpan , that will return all modelA data with only related data restricted to matching filter.
query modelA :
```
"where: {
   "include": {
     "relation": "space",
     "scope": { 
       "where": {"categoryTag": "valueX"}
     }
   }
 }
}
```

output:
```
{"id":"1", "space":[{id:"1", "categoryTag":"valuex"}]},
{"id":"2", "space":[]},
{"id":"3", "space":[{id:"3", "categoryTag":"valuex"}]},
{"id":"4", "space":[]}
```

**Comment by cloflin** [comment]
Have you looked at:
http://www.the-cat-in-the-hack.com/posts/Loopback-Find-n-Sift/

It isn't an ideal solution (especially if you need to use a limit filter as
well) but it will work to give you the results you want.

**Comment by zy-1995** [comment]
Hello, have you solved this problem? That link is effective
