### ISSUE TITLE
How to add a special keyword to a model's prototype remote method

### ISSUE THREAD

**Issue by JoeShi** [strongloop/loopback#2497]
I have a API `POST /calendars/:calendarId/events` to create an event belongs to that calendar.

However, I'd have a get the `calendarId` before send the request. So I want to specify a special word to present the `default` calendar.

For example, I wish I can send `POST /calendars/primary/events`. Once the keyword `primary` being specified, it will add to the default calendar without knowing the primary calendar id.

I have tried to use `beforeRemote`. However, it never get invoked, instead, it gives me 404 error.

`Calendar.beforeRemote('prototype.__create__events')`

I have event tries `Calendar.afterRemoteError('prototype.*)`, also this function never get invoked.

**Comment by gunjpan** [comment]
@JoeShi: assuming the relation being `Calendar` *hasMany* `Event`, I tried to reproduce the issue, and it was working for me for api: `POST /calendars/{:id}/events`.
my remote-hook code:
```javascript
Calendar.beforeRemote('*.__create__events', function(ctx, modelInstance, next) {
    console.log('Before creating events');
    next();
  });
```
Can you please share your code in a sandbox so that I can see why it is not working for you?

**Comment by JoeShi** [comment]
Hello, @gunjpan, The sandbox is here.  https://github.com/saltyegg/loopback-sandbox. the `before remote ` does not get executed. Thank you for the help

**Comment by gunjpan** [comment]
@JoeShi : Hey, thank you for providing the sandbox. I cloned it on my local and ran it without making any changes. 
First, I did `POST /api/calendars`
then I ran: `POST api/calendars/1/events` and got the expected console output.

Are you doing the same? if not, could you please list the steps for reproducing the issue. Thanks.

**Comment by JoeShi** [comment]
Sorry, I did not describe the problem correctly. What I am expecting is use a special keyword to replace the `:calendarId`. For example, each user can have many calendars, but can have only one `primary` calendar. And the `calendar` object has a property `primary(boolean)` to identify whether it is the primary calendar.

When I try post `/api/calendars/primary/events?access_token=12312313`. On the server side, I check which calendar is the primary calendar for the user and add the event to that calendar.

It is quite similar to [Google Calendar API](https://developers.google.com/google-apps/calendar/v3/reference/events/insert). And in the description, it says ` If you want to access the primary calendar of the currently logged in user, use the "primary" keyword.`

**Comment by gunjpan** [comment]
@JoeShi : So, to achieve that, you need to design your `calendar` model in a way that it has `id` property of type `string`. That's what google calendar is doing. check out [their calender model](https://developers.google.com/google-apps/calendar/v3/reference/calendars). 

Thus, doing `POST /api/calendars/primary/events?access_token=12312313` is same as doing
`POST /api/calendars/{:id}/events`

where `primary` is one of the calendar IDs.

In LoopBack, you can also have IDs of different types. [Read more](https://docs.strongloop.com/display/APIC/Model+definition+JSON+file#ModeldefinitionJSONfile-IDproperties) about how ID properties work in LoopBack and that should solve your case.

Closing this for now. Should you need further assistance, feel free to mention me; will be glad to assist. Thank you :)

**Comment by JoeShi** [comment]
Hello, @gunjpan Thank you for the explanation. I have tried the following, add the `id` property. Did I miss something? The before remote still does not get executed. Sorry I am pretty new to loopback.

```
{
  "name": "calendar",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "id": true
    }
  },
  "validations": [],
  "relations": {
    "events": {
      "type": "hasMany",
      "model": "event",
      "foreignKey": "calendarId"
    }
  },
  "acls": [],
  "methods": {}
}
```

**Comment by gunjpan** [comment]
@JoeShi : No problem. 
As mentioned in [the doc I suggested](https://docs.strongloop.com/display/APIC/Model+definition+JSON+file#ModeldefinitionJSONfile-IDproperties):
> By default, if no ID properties are defined and the idInjection property is true (or is not set, since true is the default), LoopBack automatically adds an id property to the model

So, in your `JSON` file above, set `IdInjection` to `false`.

Let me know if that works.

**Comment by JoeShi** [comment]
Hello, @gunjpan This is my new `calendar.json` file. Still now working. The [sandbox](https://github.com/JoeShi/loopback-sandbox) is updated. Thank you.

```
{
  "name": "calendar",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "id": {
      "type": "string",
      "id": true,
      "generated": false
    }
  },
  "validations": [],
  "relations": {
    "events": {
      "type": "hasMany",
      "model": "event",
      "foreignKey": "calendarId"
    }
  },
  "acls": [],
  "methods": {}
}
```

**Comment by JoeShi** [comment]
hello, @gunjpan , If you have time, please take a look. Still not working.

**Comment by richardpringle** [comment]
@JoeShi, just looked at your sandbox and there were no models!

What happened?

What @gunjpan suggested should have worked, I've used strings as ID before (just like a unique username).

But... I think you still want that automatic ID injection and you want the ID to be a number, you just want that one special case where the keyword "primary" is replaced with an ID if the client aking the request doesn't know the ID. You can do that with middleware!

Checkout https://docs.strongloop.com/display/public/LB/Defining+middleware.

I would create the middleware at parse, remove the word "primary" from the request url and replace it with the correct ID. How you get that ID is up to you (could you a `findOne` search with the `where` filter or something like that).

Let me know if that makes sense and hopefully you can get that sandbox fixed so I can keep helping you!

**Comment by richardpringle** [comment]
The middleware would obviously have to check to see if the word "primary" was there and if it wasn't, just call `next()` right away.

**Comment by gunjpan** [comment]
@JoeShi : Closing this for now. if it is still not working for you, feel free to mention me in the comments and I'll be glad to help you. Thank you.
