### ISSUE TITLE
Model ownership and ACL

### ISSUE THREAD

**Issue by pinkra** [strongloop/loopback#2499]
Hi,
is it possible to define an owner relationship between a model and _User_ without a direct relationship in the database? For example, i have a System model that is related with User through Reseller. How can i link a System with a User considering that the belongsTo relation does not support the _through_ parameter?

**Comment by jannyHou** [comment]
@pinkra I am trying to figure out a solution with you.

> How can i link a System with a User

Could you explain what do you mean by "link a System with a User"? Why don't you use `hasMany Through` to establish the relation? Please see our doc about how to use [`hasManyThrough`](https://docs.strongloop.com/display/public/LB/HasManyThrough+relations)

And when you say "without a direct relationship in the database", could you explain more about what you are trying to avoid? Thanks.

**Comment by pinkra** [comment]
The documentation of loopback specifies that in order to use the owner principal in an ACL is necessary to write a belongsTo relation between the User model and the model the ACL will be related to (System in my case). My question is: how can i do if i cannot relate the System model to User model with a belongsTo relation (in the database the system table is linked to a reseller table that is linked to the user table)?

**Comment by jannyHou** [comment]
@pinkra I think you can try a custom role, please follow the same doc page of role owner to see how to define a custom role: https://docs.strongloop.com/display/public/LB/Defining+and+using+roles#Definingandusingroles-Dynamicroles

**Comment by pinkra** [comment]
But i wouldn't use a custom role, i would that an instance of System is accessible only by its owner..

**Comment by gijo-varghese** [comment]
@pinkra did custom roles work? I'm into the same situation

**Comment by pinkra** [comment]
@gijo-varghese haven't used.
