### ISSUE TITLE
Cannot set custom Access-Control-Allow-Origin CORS header

### ISSUE THREAD

**Issue by stephenwil** [strongloop/loopback#2500]
According to the guidance in https://docs.strongloop.com/display/public/LB/middleware.json, the
cors.param.origin can also be a function:
_Can also be set to a function, which takes the request origin as the first parameter and a callback (which expects the signature err [object], allow [bool]) as the second._

How can this be the case if the file is a .JSON file?
Can't seem to override it (e.g. with a .JS file)

**Comment by loay** [comment]
Hi @stephenwil 
Here is how to configure it with some examples: 
https://www.npmjs.com/package/cors#simple-usage-enable-all-cors-requests
Let me know if you need further assistance.

**Comment by stephenwil** [comment]
Hi,
  I'm trying to override middleware.json with middleware.local.json to apply the similar solution as per the link above so thanks. If I achieve what I'm trying I will close the issue.

**Comment by loay** [comment]
@stephenwil 
Don't worry about closing the issue. If you still need further assistance, please let me know so I can help.

**Comment by stephenwil** [comment]
All done :-), via middleware.local.js

**Comment by sotream** [comment]
@stephenwil I'll try to configure cors. Can you share your solution, please.

**Comment by ivesdebruycker** [comment]
For future reference, create file middleware.local.js:
```
var whitelist = ['http://example1.com', 'http://example2.com'];
module.exports = {
  "initial": {
    "cors": {
      "params": {
        "origin": function (origin, callback) {
          if (whitelist.indexOf(origin) !== -1) {
            callback(null, true);
          } else {
            callback(new Error('Not allowed by CORS'));
          }
        }
      }
    }
  }
};
```
Restart server

**Comment by heshamelmasry77** [comment]
Sadly the solution posted still not working .
I created the file with a .production and I added my front end app url in the wishlist but it's not working.

 I created two files .local and I left it empty and .production and I added this code.
Anyone can advice me what to do.

**Comment by noeljoaquin30** [comment]
hi, the solution is not working also. I'm using loopback 3.
please help me with this. 

thank you

**Comment by Adekoreday** [comment]
kindly check your NODE_ENV value in loopback 3.
if you add NODE_ENV = production the middleware.local.js would not be used its that of the production that would be used.
more details here
https://loopback.io/doc/en/lb3/Environment-specific-configuration.html
