### ISSUE TITLE
Loopback iOS SDK with React Native 

### ISSUE THREAD

**Issue by chandlervdw** [strongloop/loopback#2502]
Is there any way to utilize the iOS SDK in react-native? Do you guys have plans to build an npm module or the like?

**Comment by gunjpan** [comment]
@bajtos : PTAL, thanks

**Comment by bajtos** [comment]
I think it may be easier to use the isomorphic JS client instead of iOS SDK, see #1734.

> Do you guys have plans to build an npm module or the like?

I am afraid this is not on our near-term roadmap.

**Comment by gunjpan** [comment]
Thanks @bajtos for chiming in. Closing this in favor of #1734
