### ISSUE TITLE
Filters that allows for comparison of model properties

### ISSUE THREAD

**Issue by sidewaiise** [strongloop/loopback#2504]
Using loopback `where` filter would be a lot more versatile if you could do queries that relate the model's instance properties to one another:

```
{
  where: {
    modelId: id,
    someProp: {
      neq: {
        property: someOtherProp
      }
    }
  }
}
```

The `neq` I'm referencing denotes 'not equal' .. eg. someProp != someOtherProp.

Right now, If i want to compare 2 properties I need to go to SQL and do a manual query there. Can this be a feature for future release?

**Comment by mrbatista** [comment]
@sidewaiise see [this](https://docs.strongloop.com/display/public/LB/Where+filter) sections `Operators`. There is `neq` operator for your use case.

**Comment by gunjpan** [comment]
@mrbatista thanks for chiming in. 
@sidewaiise: Did above suggestion help you? The `where` filter supports _almost_ all comparison [operators](https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-Operators). 
Closing this now. Should you need further assistance with it, please mention me in the comments and I'll be happy to help. Thank you and have a great weekend :smiley_cat:

**Comment by sidewaiise** [comment]
Ok I think my point wasn't conveyed very well. Yes I'm aware there is a `neq` operator already available.

The important part is the `property: someOtherProp` part - where `someOtherProp` is actually another property name within the model. It would be similar to doing an SQL query like:

`SELECT * FROM myTable WHERE column_A != column_B;`

Does that make sense?

**Comment by FalloutPL** [comment]
@gunjpan Any update of this?

**Comment by barocsi** [comment]
it seem so far this issue persists. only mongodb connector has some thing like this with allowExtendedOperators: true setting so your can add $where "this.xxx != this.yyy"

**Comment by VictorSalles99** [comment]
no solution to this problem so far?
