### ISSUE TITLE
hasManyThrough query relation model in parent scope

### ISSUE THREAD

**Issue by holbora** [strongloop/loopback#2508]
Hi,

I have the following situation:

**Recipe.json**

```
{
  "name": "Recipe",
  "plural": "Recipes",
   [ ... ]
  "relations": {
    "categories": {
      "type": "hasMany",
      "model": "Category",
      "foreignKey": "recipeId",
      "through": "RecipeCategory"
     }
  }
  [ ... ]
}

```

**Category.json**

```
{
  "name": "Category",
  "plural": "Categories",
  [ ... ]
  "relations": {
    "recipes": {
      "type": "hasMany",
      "model": "Recipe",
      "foreignKey": "categoryId",
      "through": "RecipeCategory"
    }
  }
  [ ... ]
}
```

and the 'through' model

**RecipeCategory.json**

```
{
  "name": "RecipeCategory",
  "plural": "RecipeCategories",
   [ ... ]
  "relations": {
    "recipe": {
      "type": "belongsTo",
      "model": "Recipe",
      "foreignKey": "recipeId"
    },
    "category": {
      "type": "belongsTo",
      "model": "Category",
      "foreignKey": "categoryId"
    }
  }
   [ ... ]
}

```

I've simplified the models for readability.
My question is:

How can I get all Recipes with name like 'test' and category in category1Object, category2Object..

  Recipe.find({
          filter: {
              where: {
                name: { like: "test" }
                // how I can include HERE the condition for fetching selected category models ??
              },
              include: ['categories]
          }
      }

Thank you for any kind of help or suggestion!

**Comment by holbora** [comment]
+1

**Comment by holbora** [comment]
+1

**Comment by jannyHou** [comment]
@holbora sorry about responding late, I am looking into the solution, will update it here asap.

**Comment by jannyHou** [comment]
Please try:
```js
Recipe.find({
    where: {
      name: { like: "test" }
    },
    include: {
      relation: "categories",
      where: { 
        and: [
          { categoryId: c_id_1 },
          { categoryId: c_id_2 },
          ...
          { categoryId: c_id_n } 
        ]
      }
    }
})
```

**Comment by jannyHou** [comment]
And @holbora please check our doc of how to use filter to see more details:
https://docs.strongloop.com/display/public/LB/Querying+data

**Comment by holbora** [comment]
@jannyHou Hi, I've read the documentation, if I had found an answer, for sure it was no need to open a ticket :)

If I am trying with the code that you gave me above, it just fetches me all the recipes, without applying name/category filter.

If I am writing something like this:
`
        Recipe.find({
            filter: {
                where: {
                  name: { like: "recipe" }
                }

            },
            include: {
              relation: "categories",
              where: {
                and: [
                  { categoryId: '576500ccbae6d82c2d56fc55' }
                ]
              }
            }
        });
`

'name' filter is applied but for categories, instead of retrieving recipes which have the selected categories, it just filters the Recipe.categories array..

I hope I explained pretty clear what is the issue.

**Comment by jannyHou** [comment]
@holbora oh I misunderstood your requirement

> 'name' filter is applied but for categories, instead of retrieving recipes which have the selected categories, it just filters the Recipe.categories array..

yep this is what my query does.

I am glad that you figured out a solution, btw, could you post your solution here? Thanks :)

**Comment by holbora** [comment]
Unfortunately @jannyHou I didn't found any solution, so I limited the category search to a single one and now I am fetching all the recipes where category is the selected one; it was possible for me to do this because it's a personal project, but in other situation I don't know what I would have done.

**Comment by triadzack** [comment]
This still seems to be an issue.  I don't think it is a bug but I guess a feature request?  This is something we are trying to do in our project now and given the size of the data and number of relations can't take the same route @holbora took.

@jannyHou is there a solution for filtering the parent list by its relations?  To use the OP example; I want to return only recipes that have category "French"


Something like this

```javascript
Recipe.find({
    where: {
      'category.id': 2
    },
    include: {
      relation: "categories",
    }
})
```
