### ISSUE TITLE
Order of model properties which inherit custom model

### ISSUE THREAD

**Issue by emresebat** [strongloop/loopback#2509]
Hi

I have a model l which inherits from Entity, 

Entity properties:

``` javascript
 {
    "id": "",
    "ownerId": "",
    "active": true,
    "createdAt": "2016-07-16",
    "updatedAt": "2016-07-16"
  }
```

Payment properties

``` javascript
 {
    "orderId": "",
    "amountTypeId": 0,
    "amount": 0,
    "paymentType": 0,
    "orderItems": {}
  }
```

The order of the properties for Payment model on explorer is listed as

``` javascript
 {
    "orderId": "",
    "amountTypeId": 0,
    "amount": 0,
    "paymentType": 0,
    "orderItems": {},
    "id": "",
    "ownerId": "",
    "active": true,
    "createdAt": "2016-07-16",
    "updatedAt": "2016-07-16"
  }
```

So first own properties and then base properties, also on database level id, active, createdAt, updatedAt columns are generated last which I don't prefer.

How can I change this behaviour?

**Comment by 0candy** [comment]
Unfortunately, we don't have a way to customize the order of the properties at the moment.

**Comment by gunjpan** [comment]
@emresebat : Actually, you can achieve that by using the same `Entity` properties in `Payment` model as it will override base properties. For example, let's say, you want to move `createdAt` & `updatedAt` right after `orderId`; you can define your `Payment` model as following to achieve this:

*/common/models/Payment.json*

```javascript
{
  "name": "Payment",
  "base": "Entity",
   ...
  "properties": {
     "orderId": { type: ...},
    "createdAt": { type: ...}, // type from base model
    "updatedAt": { type: ...}, // type from base model 
    "amountTypeId": 0,
    "amount": 0,
    "paymentType": 0,
    "orderItems": {}
  }
 ...
}
```
That would reorder the `Payment` model in explorer as:
```json
{
    "orderId": "",
    "createdAt": "2016-07-16",
    "updatedAt": "2016-07-16",
    "amountTypeId": 0,
    "amount": 0,
    "paymentType": 0,
    "orderItems": {},
    "id": "",
    "ownerId": "",
    "active": true,
  }

```

Hope that resolves your case.

**Comment by emresebat** [comment]
Hi

This may work yes, but it's feels like loosing the advantage of using a base entity since you're re-defining all properties.

It's not a big deal, but it would be nice to have a method to override this behaviour.
