### ISSUE TITLE
Password validators operate on hashed password, making `length` validators useless

### ISSUE THREAD

**Issue by STRML** [strongloop/loopback#251]
Modifying the User model in the following way does not trigger a validation error when attempting to create a user with an invalid password:

``` javascript
var User = app.models.User;
User.validatesLengthOf('password', {min: 6, message: {min: 'Password is too short'}});
var u = new User({email: "foo@bar.com", password: "short"});
assert(u.isValid()) // Error
```

Tracing it with `node-inspector` shows that the length is being compared to the hashed password, which is obviously always quite long.

**Comment by bajtos** [comment]
> Password validators operate on hashed password, making `length` validators useless

@STRML is this still an issue for you? I see we landed https://github.com/strongloop/loopback/pull/941 which allows users to implement a workaround. Is that good enough?

@raymondfeng @ritch do you remember if we have any idea what a proper solution for this problem would look like?

Then there is https://github.com/strongloop/loopback/pull/941#issuecomment-98756858 mentioning this issue should be easy to fix/rework once we have the "persist" hook in place, which has happened quite some time ago - see https://github.com/strongloop/loopback-datasource-juggler/issues/559.

Perhaps that's the way to go? To keep the password plaintext all the way until the "persist" hook that is called after any validations were passed.

Thoughts?

**Comment by av-k** [comment]
For example you can use context for temp data.

`  User.beforeRemote('create' , function(ctx, user, next) {
    var context = User.app.loopback.getCurrentContext();

    if (context) {
      context.set('currentPassword', ctx.req.body.password);
    }

    next();
  });`

And after validate it:
`  User.validateAsync('password', function (err, done) {
    var context = User.app.loopback.getCurrentContext(),
          currentPassword = context.get('currentPassword');

    if (currentPassword.length < config.validations.password.min) {
      err();
    }

    done();
  }, {message: 'Password is too short (minimum 6 symbols)'});`

**Comment by JohnPhoto** [comment]
Is there any updates on this issue, what is current best practice?

I am not feeling overly confident in reimplementing a proper hashing myself and @av-k solution feels outdated now that `getCurrentContext()` is deprecated AFAIK (?)

**Comment by akapaul** [comment]
I've found another way to do this. In common model **User** there is a method called **validatePassword**. If we extend our **UserModel** from **User**, we can redefine this method in JS, like following:

```javascript
var g = require('loopback/lib/globalize');

module.exports = function(UserModel) {
  UserModel.validatePassword = function(plain) {
    var err,
        passwordProperties = UserModel.definition.properties.password;

    if (plain.length > passwordProperties.max) {
      err = new Error (g.f('Password too long: %s (maximum %d symbols)', plain, passwordProperties.max));
      err.code = 'PASSWORD_TOO_LONG';
    } else if (plain.length < passwordProperties.min) {
      err = new Error(g.f('Password too short: %s (minimum %d symbols)', plain, passwordProperties.min));
      err.code = 'PASSWORD_TOO_SHORT';
    } else if(!(new RegExp(passwordProperties.pattern, 'g').test(plain))) {
      err =  new Error(g.f('Invalid password: %s (symbols and numbers are allowed)', plain));
      err.code = 'INVALID_PASSWORD';
    } else {
      return true;
    }
    err.statusCode = 422;
    throw err;
  };
};
```

This works for me. I don't think that `g` (globalize) object is required here, but I added this, just in case. Also, I've also added my validator options in JSON definition of UserModel, because of [https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#validations](Loopback docs)

**Comment by pinicius** [comment]
Hi akapaul, I've tried your solution. This is my code:

```
module.exports = function(Investigator) {

  Investigator.validatePassword = function(plain) {
      var err,
          passwordProperties = Investigator.definition.properties.password;
      if (plain.length > passwordProperties.max) {
        err = new Error (g.f('Password too long: %s (maximum %d symbols)', plain, passwordProperties.max));
        err.code = 'PASSWORD_TOO_LONG';
      } else if (plain.length < passwordProperties.min) {
        err = new Error(g.f('Password too short: %s (minimum %d symbols)', plain, passwordProperties.min));
        err.code = 'PASSWORD_TOO_SHORT';
      } else {
        return true;
      }
      err.statusCode = 422;
      throw err;
    };

  Investigator.validatesPresenceOf('email');
  Investigator.validatePassword('password', {min: 6, max: 16, message: {min: 'Too sort', max: 'Too long'}});
  Investigator.validatesInclusionOf('type', {in: ['normal', 'boss']});
  Investigator.validatesUniquenessOf('email', {message: 'email is not unique'});

};
```
And investigator.json file:

```
{
  "name": "investigator",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "password": {
      "type": "string",
      "required": true,
      "min": 6,
      "max": 16
    },
...
}
```
My question is how can I throw a validation exception instead an Error? I'm newbie with strongloop

Thanks in advance

**Comment by akapaul** [comment]
Hi @pinicius!

You should not call the **validatePassword** method directly in model definition. This is called inside loopback code while validating User model, so the validation exception will be thrown by loopback. If you want to understand the logic, how user validation occurs, you can look inside native [User model](https://github.com/strongloop/loopback/blob/master/common/models/user.js), see lines [589](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L589), [640](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L640), [645](https://github.com/strongloop/loopback/blob/master/common/models/user.js#L645)

**Comment by pinicius** [comment]
Hi @akapaul and thanks for your quick response!

My code finally after your advise

```
module.exports = function(Investigator) {

  Investigator.validatePassword = function(plain) {
        var err,
            passwordProperties = Investigator.definition.properties.password;

        if (plain.length > passwordProperties.max) {
          err = new Error (g.f('Password too long: %s (maximum %d symbols)', plain, passwordProperties.max));
          err.code = 'PASSWORD_TOO_LONG';
        } else if (plain.length < passwordProperties.min) {
          err = new Error(g.f('Password too short: %s (minimum %d symbols)', plain, passwordProperties.min));
          err.code = 'PASSWORD_TOO_SHORT';
        } else if(!(new RegExp(passwordProperties.pattern, 'g').test(plain))) {
          err =  new Error(g.f('Invalid password: %s (symbols and numbers are allowed)', plain));
          err.code = 'INVALID_PASSWORD';
        } else {
          return true;
        }
        err.statusCode = 422;
        throw err;
      };

  Investigator.validatesInclusionOf('type', {in: ['normal', 'boss']});
  Investigator.validatesUniquenessOf('email', {message: 'email is not unique'});
  Investigator.validatesLengthOf('password', {min: 6, max: 16, message: {min: 'Too short', max: 'Too long'}});

};
```
investigator.json file:

```
{
  "name": "investigator",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "password": {
      "type": "string",
      "required": true,
      "min": 6,
      "max": 16
    },
...
}
```
However, it continues raised Error exception instead of captures it like Validation Exception.

I have defined a route for user registering like this (routes.js):

```
//create a new account
    router.post('/register', function(req, res) {
      Investigator.create({
        type: req.body.type,
        username: req.body.username,
        email: req.body.email,
        password: req.body.password
      }, function(err, accountInstance) {
        if (err) {
          console.log(err)
          res.render('register', {
            type: '',
            username: '',
            email: '',
            password: '',
            registerFailed: true,
            errorMessage: err.message
          });
        return;
       }

       res.render('login', {
         username: req.body.username,
         password: '',
         loginFailed: false
       });
      });
    });
```
What I'm doing wrong??

**Comment by akapaul** [comment]
Hi @pinicius!

What error do you see? Have you imported **g** module, using the line:
```javascript
var g = require('loopback/lib/globalize');
```

It is not required, anyway, but if you omit it, you should simplify strings you pass to Error object constructor, like passing a concatenated strings, without formatting symbols, e.g. replacing:

```javascript
err = new Error (g.f('Password too long: %s (maximum %d symbols)', plain, passwordProperties.max));
```
to
```javascript
err = new Error ('Password too long: ' + plain + ' (maximum ' + passwordProperties.max + ' symbols)');
```

Also, you should not define own routes in loopback using the way you mentioned, because it creates them from model definitions.

**Comment by pinicius** [comment]
Hi @akapaul !
> you should not define own routes in loopback using the way you mentioned, because it creates them from model definitions.

I did not know that, I supposed It would create the new models from the my model (with rewrite method)

Thanks so much, It works :) :+1:

**Comment by kooliokey** [comment]
@akapaul's suggestion works for me, except I need access to the model's other data inside this method to make sure they aren't using something like their name for their password. Suggestions for accessing this data? `this` looks to be set to the server instance, not the model.

**Comment by rashmihunt** [comment]
@STRML As per the above conversation, looks like there is solution for originally reported problem. We will be closing this soon. Let us know.

**Comment by STRML** [comment]
So your suggestion is to override `User.validatePassword`?

**Comment by rashmihunt** [comment]
@STRML As far as I can understand following above discussion, per @bajtos 
comments above https://github.com/strongloop/loopback/issues/251#issuecomment-163717176, there are couple of possible workarounds - override validatePassword(),  use 'persist' hook.

```
I see we landed https://github.com/strongloop/loopback/pull/941 which allows users to implement a workaround. Is that good enough?
…….

Then there is https://github.com/strongloop/loopback/pull/941#issuecomment-98756858 (comment) mentioning this issue should be easy to fix/rework once we have the "persist" hook in place, which has happened quite some time ago - see strongloop/loopback-datasource-juggler#559.

Perhaps that's the way to go? To keep the password plaintext all the way until the "persist" hook that is called after any validations were passed.

```

**Comment by STRML** [comment]
Sounds to me like now that `persist` is in, then there just needs to be a fix implemented that knows if you're trying to validate `'password'`, uses the right hook, then this can be closed. But it shouldn't be closed just with a workaround.

**Comment by raymondfeng** [comment]
In general, we need to have a better way to handle `calculated/transformed` properties such as `password` upon 'read/write`. I guess we should open an issue for the broader feature.

**Comment by rashmihunt** [comment]
@raymondfeng opened feature https://github.com/strongloop/loopback/issues/3468 
Will close this bug as couple of workaround available and broader feature is tracked through #3468

**Comment by jannyHou** [comment]
Hi @rashmihunt, would you mind if I close this issue and track the feature progress in your new issue https://github.com/strongloop/loopback/issues/3468?

**Comment by bajtos** [comment]
IMO, we should keep this issue open. As I understand it, #3468 will lay groundwork necessary to fix password validators. With this foundation in place, we will still need to rework the way how password are handled in LoopBack.
