### ISSUE TITLE
memory connector bad response status code

### ISSUE THREAD

**Issue by domino3d** [strongloop/loopback#2512]
Hi 
can you please change status code for Duplicate entry error from 500 to 409 ?

Here is a thing, when you put something into cloudant connector, duplicate error message returns 409
But when the same thing occur in strongloop memory connector it returns 500 with stack:

> "status": 500,
> "message": "Duplicate entry for persist_data.id",
>         "stack": "Error: Duplicate entry for persist_data.id\n    at Memory._createSync (C:\OSS telco microservices\project\persistdatasrvc\node_modules\loopback-datasource-juggler\lib\connectors\memory.js:220:15)\n ......

My suggestion is just to change ...\node_modules\loopback-datasource-juggler\lib\connectors\memory.js

from

>   if (this.collection(model)[id])
>     return fn(new Error('Duplicate entry for ' + model + '.' + idName));

to

>   if (this.collection(model)[id]){
>     var err = new Error('Duplicate entry for ' + model + '.' + idName);
>     err.status = 409;
>     return fn(err);
>     }

**Comment by superkhau** [comment]
@domino3d Would you like to submit a PR?

**Comment by loay** [comment]
Proper code is added. Issue is fixed as per this pr: https://github.com/strongloop/loopback-datasource-juggler/pull/1245
