### ISSUE TITLE
All SLC CTL commands met with http://127.0.0.1:8701" failed with Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by paperrr1** [strongloop/loopback#2513]
I can't bring anything up.  All my actions are refused.  I have absolutely no idea why.  What can I do to resolve this and avoid in the future?

**Comment by tomritsema** [comment]
Same thing here.  It seems as if the internal process manager _pm_ is down.
`slc start` in the directory where my package.json resides seemed to have started it again

**Comment by 0candy** [comment]
What version of slc are you using?

**Comment by jonesprabu** [comment]
I'm also facing this issue, the version am using as below,

root@ip-172-31-29-233:~/deliapp-server# slc -v
strongloop v6.0.1 (node v4.5.0)
âââ strong-arc@1.8.8 (fb756f2)
âââ strong-build@2.1.2 (a98f310)
âââ strong-deploy@3.1.4 (9b29df0)
âââ strong-mesh-models@8.1.0 (62e539b)
âââ strong-pm@5.2.3
âââ strong-registry@1.1.6 (f8c2339)
âââ strong-start@1.3.4 (28c261d)
âââ¬ strong-supervisor@3.3.3
â âââ strong-agent@2.0.4 (de9885e)
âââ generator-loopback@1.24.0 (f94d27e)
âââ node-inspector@0.7.4
âââ nodefly-register@0.3.3

**Comment by sendyputra** [comment]
i also have problem, there is my version. slc start is working and after slc set-size i try slc ctl but i have warning Error: connect ECONNREFUSED 127.0.0.1:8701

$ slc -v
strongloop v6.0.1 (node v6.4.0)
├── strong-arc@1.8.8 (fb756f2)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.4 (de9885e)
├── generator-loopback@1.24.0 (f94d27e)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by UnacceptableUse** [comment]
Having the same issue  
$ slc -v
strongloop v6.0.3 (node v5.9.1)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.1 (b51fc45)
├── generator-loopback@1.24.5 (de24875)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by microSoftware** [comment]
Same issue on mac.

strongloop v6.0.3 (node v7.2.1)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.1 (b51fc45)
├── generator-loopback@1.25.0 (6a0e2c0)
├── node-inspector@0.7.5 (16841d6)
└── nodefly-register@0.3.3


I tried everything. I think It's because of SqlLite but I installed it. And loopback-connector-sqlite3 as well. Help please.

**Comment by asano-shinichi** [comment]
Hi, I have same issue on Mac.
Kaspersky Internet Security causes this issue for me.

```sh
$ slc -v
strongloop v6.0.3 (node v6.9.5)
├── strong-arc@1.8.9
├── strong-build@2.1.2
├── strong-deploy@3.1.4
├── strong-mesh-models@8.1.0
├── strong-pm@5.2.4
├── strong-registry@1.1.6
├── strong-start@1.3.4
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.2
├── generator-loopback@1.25.0
├── node-inspector@0.7.5
└── nodefly-register@0.3.3
```

**Comment by loay** [comment]
@asano-shinichi so if you turn off the security app, it works fine?

**Comment by segu** [comment]
@loay Yes, it works fine.

**Comment by loay** [comment]
Thanks. Closing the issue for now. If issue persists, please feel free to leave a comment and I will re-open. Thanks.

**Comment by leehankyeol** [comment]
This happens on my AWS EC2 instance. 

`strongloop v6.0.3 (node v7.2.1)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.1 (249315b)
├── strong-pm@5.2.4
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.2 (4b9dde0)
├── generator-loopback@1.25.0 (6a0e2c0)
├── node-inspector@0.7.5 (16841d6)
└── nodefly-register@0.3.3
`

**Comment by arvput** [comment]
I am facing the same issue can anyone please explain what's going wrong with me .
output of slc start 
Error: pm failed, exit with status  1
and slc ctl gives 
Command "status" on "http://127.0.0.1:8701" failed with Error: connect ECONNREFUSED 127.0.0.1:8701

strongloop v6.0.3 (node v10.15.3)
├── strong-arc@1.8.9
├── strong-build@2.1.2
├── strong-deploy@3.1.4
├── strong-mesh-models@8.1.1
├── strong-pm@5.2.4
├── strong-registry@1.1.6
├── strong-start@1.3.4
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.2
├── generator-loopback@1.25.0
├── node-inspector@0.7.5
└── nodefly-register@0.3.3
