### ISSUE TITLE
Default value left blank for array items in property type array does not work

### ISSUE THREAD

**Issue by cgole** [strongloop/loopback#2518]
Enter an empty property name when done.
? Property name: p1
   invoke   loopback:property
? Property type: array
? The type of array items: string
? Required? Yes
? Default value[leave blank for none]: 
Warning: please enter the p1 property again. The default value provided "" is not valid for type: string

**Comment by cgole** [comment]
verified. needs a publish to npmjs

**Comment by bajtos** [comment]
Released as `generator-loopback@1.23.2`.

**Comment by sabliao** [comment]
Is this possibly not in loopback 3.0.0-alpha.2? I still get the error when I try not putting a default value for a required string type.
<img width="638" alt="screen shot 2016-07-28 at 2 42 52 pm" src="https://cloud.githubusercontent.com/assets/4286238/17230553/a03be7e2-54d1-11e6-8cf0-3b7e853827c7.png">

**Comment by bajtos** [comment]
> Is this possibly not in loopback 3.0.0-alpha.2? I still get the error when I try not putting a default value for a required string type.
> <img width="638" alt="screen shot 2016-07-28 at 2 42 52 pm" src="https://cloud.githubusercontent.com/assets/4286238/17230553/a03be7e2-54d1-11e6-8cf0-3b7e853827c7.png">

@alexpit PTAL^^

**Comment by benjaminhon** [comment]
me too

**Comment by gael-boyenval** [comment]
same problem here, i'm up to date

**Comment by dearfrankg** [comment]
Same here

**Comment by bajtos** [comment]
@benjaminhon @gael-boyenval @dearfrankg could you please post here the output of `npm ls -g generator-loopback` to verify you have the right version of generator-loopback installed?

**Comment by dearfrankg** [comment]
I installed a later version of node and all is well for me now.
