### ISSUE TITLE
Pass options through to the resetPasswordRequest event

### ISSUE THREAD

**Issue by justinwatkins** [strongloop/loopback#2521]
user.js in User.resetPassword
`UserModel.emit('resetPasswordRequest', {
          email: options.email,
          accessToken: accessToken,
          user: user
        });`

The resetPassword method already accepts an options property bag and it seems trivial to pass this back through in the event object.  It would be useful to be able to pass context data through to that email (like some site state, or my scenario the actual host name to embed in the email with a multi-host site).

You used to be able to shove the hostname in the current context and pull it out, but that is flakey at best in the current build.  I can create a pull request.

**Comment by loay** [comment]
Issue fixed as per this PR https://github.com/strongloop/loopback/pull/2992/files
Closing
