### ISSUE TITLE
Limit filter on included models results in unexpected output

### ISSUE THREAD

**Issue by achintverma** [strongloop/loopback#2524]
Assume there are two models Account and Listing. I want to pull accounts with 5 listings from each account. When make a REST call as follows: 

``` javascript
Account.find({
     where:{
        state: 'CA'
      },
      include: {
         relation: 'listing',
         scope:{
           limit: 5
         }
     }
});
```

It gives result with No Listings in few accounts but in reality there are listings under each user

**Comment by achintverma** [comment]
BTW, connector is MongoDB

**Comment by ron137** [comment]
+1

**Comment by jannyHou** [comment]
@achintverma @ron137 Can you fork https://github.com/strongloop/loopback-sandbox and replace it with your code? Thanks!

> result with No Listings in few accounts

This makes it hard for me to reproduce your problem if it doesn't happen in all instances. Thanks.

**Comment by loay** [comment]
Hi @achintverma 
Can you please provide a sample repo so we can debug the issue? Thanks.

**Comment by achintverma** [comment]
Apologies for the late response. For some reason, I didn't get any email notification for all other activities except the closure today.
