### ISSUE TITLE
 missing function from findByIdAndUpdate

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback#2527]
I have been using the presistent model to work with mongodb. I cant find the function `findByIdAndUpdate` exist upon calling this name.  referenced by http://mongoosejs.com/docs/api.html

Should this part be added?

``` javascript

Model.findByIdAndUpdate = function(id, update, options, callback) {
  if (callback) {
    callback = this.$wrapCallback(callback);
  }
  if (arguments.length === 1) {
    if (typeof id === 'function') {
      var msg = 'Model.findByIdAndUpdate(): First argument must not be a function.

'
          + '  ' + this.modelName + '.findByIdAndUpdate(id, callback)
'
          + '  ' + this.modelName + '.findByIdAndUpdate(id)
'
          + '  ' + this.modelName + '.findByIdAndUpdate()
';
      throw new TypeError(msg);
    }
    return this.findOneAndUpdate({_id: id}, undefined);
  }

  // if a model is passed in instead of an id
  if (id instanceof Document) {
    id = id._id;
  }

  return this.findOneAndUpdate.call(this, {_id: id}, update, options, callback);
};
```

**Comment by jjhesk** [comment]
`updateattribute` is the mapping.

Referencing from https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-updateattribute I cant find much sample code from the internet.

**Comment by davidcheung** [comment]
@jjhesk I belive you can also use the `PUT` method, 

@Amir-61 you are more familiar with this area, please correct me if I'm wrong, and would you know if we're missing documentations or example for this area of the code?

**Comment by Amir-61** [comment]
For LoopBack 2.x (current version), these are the endpoints:
```
PUT /myModel/{id} => updateAttribute
PUT /myModel => upsert/patchOrCreate
```
