### ISSUE TITLE
Need to change data-source according to domain name

### ISSUE THREAD

**Issue by inv-joseph** [strongloop/loopback#2529]
Hi ,
My new task in loopback is to change the data-source according to the domain name requested from user, So initially I changed all the defaut  dataSource in the model-config.json to null.
And I changed code in application.js in  project-folder/node_modules/loopback/lib/application.js

The following are added in the 

```
app.enableAuth = function(){
    var app_domains = app.get("domain");
    var ds_attach = null;
    for ( var key in app_domains){
        if(req.headers.host.includes(key))
        {
          console.log(req.headers.host+"__"+key);
          ds_attach = app_domains[key].db_src;
        }
        if(ds_attach)
          break;
    }
    Model.attachTo(eval("app.dataSources."+ds_attach));
}
```
Here I am setting the domain names and datasoure name from config file.

I am getting correct result but in some cases like Asynchronous function call this area is not called and showing the error datasource is not properly attached to some models.

This is the error I am getting.

> 

> Error: Cannot call AccessToken.findById(). The findById method has not been setup. The PersistedModel has not been correctly attached to a DataSource!
  at throwNotAttached (/home/joseph/node_projects/laplace-master/dashboard-server/node_modules/loopback/lib/persisted-model.js:55:9)
  at Function.find [as findById] (/home/joseph/node_projects/laplace-master/dashboard-server/node_modules/loopback/lib/persisted-model.js:135:3)

----------------------------------------------------------------------------------------------------------------------------------------

Here I need to now in which file and function that I need to write code for changing the datasource according to host name.

app.enableAuth in application.js is not invoking every time when the call is coming from client.
So that I cannot attacth the datasource of that particular model.

Please help to resolve these issue.

**Comment by davidcheung** [comment]
@inv-joseph please take a look at this issue https://github.com/strongloop/loopback/issues/2064#issuecomment-189308816, looks like it might be a similar use case, please let me know if that solves your issue.

**Comment by inv-joseph** [comment]
Hi David,
issue #2064 comment does not contains any solution for my problem,
this issue is resolved for me. So that Iam changing the status to close.
