### ISSUE TITLE
Discussion: Json Web Tokens

### ISSUE THREAD

**Issue by carlosfaria94** [strongloop/loopback#2536]
Instead of creating a token system, like we have here, why not follow the RFC 7519 (https://tools.ietf.org/html/rfc7519) standard? - JWT.

The JWT ecosystem is raising, and raising (https://jwt.io) and lots of libs exist and I think the ideia is really solid and powerful.

I believe that changing the actual token system in loopback (uid2), can be a headache, or not. But I think the idea is to improve.

What you think?

Thank you.

**Comment by jeff3yan** [comment]
I'd also be quite interested to know this. For my current application and ACL setup, I don't think it would be _too_ difficult to implement JWT (using Auth0 at the moment).

Does anyone know if it's possible to re-define the $owner role? Or would it be more appropriate to define a new **owner** role and have it simply retrieve roles from the JWT?

**Comment by type0lang** [comment]
+1

**Comment by loay** [comment]
Duplicate issue. Can you please use the previous issue for the discussion https://github.com/strongloop/loopback/issues/1905
Thanks.
