### ISSUE TITLE
Need help with post request?

### ISSUE THREAD

**Issue by tomgie** [strongloop/loopback#2537]
Ok so I am using php to post data to my loopback server but it just keeps doing this every time I enter a json into the body. https://gyazo.com/d35a357368e0327d3957ac78cce1ee7b

php script: http://pastebin.com/qRRKW8MT
what I sent to that php script: http://pastebin.com/iCpK7Na6

If you could help me out that would be great!

**Comment by davidcheung** [comment]
@tomgie have you tried just curling through command line(or tools like postman), does it still do the same, I don't think this is a Loopback issue.

Possible issues 
- Accept headers ( should be `application/json`)
- You might be sending the json data as a string?

We only accept feature requests and bug reports on Github issues, you can try to post on [google groups](https://github.com/strongloop/loopback/wiki/Questions) if you're still facing this issue, thanks!
