### ISSUE TITLE
Suggestion for better login fail http status code 

### ISSUE THREAD

**Issue by casamia918** [strongloop/loopback#2538]
[Running environment]
loopback@2.28.0

1

At currently, loopback respond error object of http status code 401 with almost every login failure situation. Login handling method is written at /loopback/common/models/user.js Line 177

https://github.com/strongloop/loopback/blob/master/common/models/user.js

I don't know why the response http status code is so simple. While developing client side, in general, responded error status code is used for handling popup message which will shown to user. Not so many modification needed, I suggest this error status code.

Ref. https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
userNotFoundError -> 404 Not Found
passwordInvalidError -> 422 Unprocessable Entity (WebDAV; RFC 4918)

Suggestion code is here. See bottom side of code.

```
    // Line 220
    self.findOne({where: query}, function(err, user) {
      var defaultError = new Error('login failed');
      defaultError.statusCode = 401;
      defaultError.code = 'LOGIN_FAILED';

      function tokenHandler(err, token) {
        if (err) return fn(err);
        if (Array.isArray(include) ? include.indexOf('user') !== -1 : include === 'user') {
          // NOTE(bajtos) We can't set token.user here:
          //  1. token.user already exists, it's a function injected by
          //     "AccessToken belongsTo User" relation
          //  2. ModelBaseClass.toJSON() ignores own properties, thus
          //     the value won't be included in the HTTP response
          // See also loopback#161 and loopback#162
          token.__data.user = user;
        }
        fn(err, token);
      }

      if (err) {
        debug('An error is reported from User.findOne: %j', err);
        fn(defaultError);
      } else if (user) {
        user.hasPassword(credentials.password, function(err, isMatch) {
          if (err) {
            debug('An error is reported from User.hasPassword: %j', err);
            fn(defaultError);
          } else if (isMatch) {
            if (self.settings.emailVerificationRequired && !user.emailVerified) {
              // Fail to log in if email verification is not done yet
              debug('User email has not been verified');
              err = new Error('login failed as the email has not been verified');
              err.statusCode = 401;
              err.code = 'LOGIN_FAILED_EMAIL_NOT_VERIFIED';
              fn(err);
            } else {
              if (user.createAccessToken.length === 2) {
                user.createAccessToken(credentials.ttl, tokenHandler);
              } else {
                user.createAccessToken(credentials.ttl, credentials, tokenHandler);
              }
            }
          } else {
            debug('The password is invalid for user %s', query.email || query.username);
            //////////// MY Suggestion
            var passwordInvalidError = new Error('The password is invalid for ' +query.email || query.username);
            passwordInavlidError.statusCode = 422;
            fn(passwordInavlidError);
          }
        });
      } else {
        debug('No matching record is found for user %s', query.email || query.username);
        //////////// MY Suggestion
        var userNotFoundError = new Error('No matching record is found for ' + query.email || query.username);
        userNotFoundError.statusCode = 404;
        fn(userNotFoundError);
      }
    });



```

2

 

Continuing from above suggestion, I'm wondering why the defaultError status code is 401. Refer to the http status code document, 401 stands for unauthorized request, which means the request should have authenticate header field. It is absurd because when the user requested for login, it has no authentication token yet. So http status code 400 is much better for default error .

**Comment by gunjpan** [comment]
@casamia918 : 
Statu code `401` stands for :
>Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided

Also, [`401` semantically means "unauthenticated"](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_Error). 

Re. your concern:
>Continuing from above suggestion, I'm wondering why the defaultError status code is 401.

It's also an error code response for missing or invalid authentication token ([more here](http://www.restapitutorial.com/httpstatuscodes.html)). 
Apart from that, `400` is more generic -- mostly used for Domain validation errors, missing data, etc.

Thus, `401` is used correctly here. 

Now, talking about `422` & `404`:
`422` stands for: 
>422 Unprocessable Entity
    The request was well-formed but was unable to be followed due to semantic errors

In your suggestion, you're using it for `Invalid Password` , which is inappropriate where `401` is expected 

`404` is for: 
>The requested resource could not be found but may be available in the future

Using that for authentication is misleading. 

Closing this for now. Should you have any questions/concerns, please leave a comment with my handle and will be glad to address it. Thank you.
