### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by ariskemper** [strongloop/loopback#255]
Would be good that Loopback supports localisation for current models and messages in responses.

Example:
- Change locale in headers or programmaticaly in user settings.

Proposed solution:
- Integration of i18next-node library

**Comment by tohagan** [comment]
I read this documentation but was rather confused ...

Does that mean that for all places in the Validateable API where I can specify a `message` property I can also specify now use a `code` property?  If so, its undocumented, If not, I think that what's needed. 

Example:
```
      Model.validate('expires', function(err: Function) {
        let now = new Date();
        if (this.expires < now) return err();
      }, {message: 'expire value must be a future date', code: 'future'});
```

**Comment by bajtos** [comment]
@tohagan IIRC, the `code` is set to the name of the validator as provided in the first argument of `Model.validate`. So in your example, the code will be set by LoopBack to `expires`.

> NOTE: In some cases a code property may be inadequate as in order to the build the localised error message client side, you may need to additional server side data from other records or server side logic so in an ideal universe, the code could become an error object containing the code + other data.

I see your point. Could you please open a new GitHub issue to discuss this feature and keep track of it? It is rather off-topic here.
