### ISSUE TITLE
Method "PersistedModel.createChangeStream" does not work correctly in a clustered mode

### ISSUE THREAD

**Issue by lsroman** [strongloop/loopback#2562]
Method "[PersistedModel.createChangeStream](http://apidocs.strongloop.com/loopback/#persistedmodel-createchangestream)" does not work correctly in a clustered  mode(slpmctl set-size <service> 2). 

First request call remote method /change-stream and [subscribe model](https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L1728-L1729).
Second request call method change model.

**Comment by gunjpan** [comment]
@lsroman : could you please provide me with more details of your setup and if possible a sandbox repo to reproduce it.

**Comment by gunjpan** [comment]
@lsroman: Any updates on the request above^? or is this good to close?
