### ISSUE TITLE
Pass context in 'persist' to 'after save'

### ISSUE THREAD

**Issue by carlosfaria94** [strongloop/loopback#2563]
I need to pass context from a Operation Hook (persist) to another (after save), I know the [existence][1] of the `ctx.hookState` but its not working.

    ZZ.observe('persist', (ctx, next) => {
          ctx.hookState = "pass this";
          next();
        }).catch(err => next(err));
      });

    ZZ.observe('after save', (ctx, next) => {
      console.log(ctx.hookState);
      next()
    });
    

I don't get anything in `console.log(ctx.hookState)`. What I'm doing wrong?

Thanks.

  [1]: https://docs.strongloop.com/display/APIC/Operation+hooks#Operationhooks-SharedhookStateproperty

**Comment by Amir-61** [comment]
Which method are you calling? Please provide a sample repo reproducing the issue using our [loopbakc-sandbox](https://github.com/strongloop/loopback-sandbox).

Thanks!

**Comment by carlosfaria94** [comment]
I'm calling a create method. It's here: https://github.com/carlosfaria94/loopback-sandbox

As you can see: https://github.com/carlosfaria94/loopback-sandbox/blob/master/common/models/foo.js I'm using `ctx.hookState` to pass a string between hooks, as described [here](https://docs.strongloop.com/display/APIC/Operation+hooks#Operationhooks-SharedhookStateproperty ).

Maybe I'm doing something wrong?

Thanks

**Comment by carlosfaria94** [comment]
Anything? bug?

**Comment by Amir-61** [comment]
Sorry I did not get time to verify it. @0candy since you are on triage sprint, could you please verify this based on the sandbox provided? Thanks

**Comment by 0candy** [comment]
@carlosfaria94 You can do this:
```
    Foo.observe('persist', (ctx, next) => {
        if (ctx.currentInstance) {
            ctx.hookState.x = 'pass this';
            console.log('hookState in pesist: ');
            console.log(ctx.hookState);
            next();
        } else {
            next();
        }
    });

    Foo.observe('after save', (ctx, next) => {
        if (ctx.isNewInstance) {
            console.log('hookState in after save: ');
            console.log(ctx.hookState);
            next();
        } else { 
            next();
        }
    });
```
