### ISSUE TITLE
Loopback error is not getting in android strong loop

### ISSUE THREAD

**Issue by shankarpilli** [strongloop/loopback#2568]
Hi,

In my server loopback code is like this. 

var error = new Error();
                      error.message = 'Email already in use'
                      cb(error, null);

In my android code i am wrote to catch that is 

@Override
                public void onError(Throwable throwable) {
                    //throwable.
                    Utils.showLog("NamasteUserUpdateRepository", throwable.getLocalizedMessage());
                    Utils.showLog("NamasteUserUpdateRepository", throwable.getMessage());
                    Utils.showLog("NamasteUserUpdateRepository", throwable.getCause().getMessage());
                    Toast.makeText(context, " Error :  " + throwable.getCause().getMessage(), Toast.LENGTH_SHORT).show();
                }

All all my cases i am getting 
NamasteUserUpdateRepository: Internal Server Error
NamasteUserUpdateRepository: Internal Server Error

Please tell me how can i catch.

**Comment by loay** [comment]
Hi @shankarpilli 
Can you please provide a test project with steps to reproduce the issue so I can debug? Thanks

**Comment by loay** [comment]
Hi @shankarpilli 
Is your issue fixed or do you need further assistance? Please leave a comment in case the issue is not fixed so I can investigate further. Thanks.

**Comment by shankarpilli** [comment]
Issue is not fixed. please investigate. user node in you back end. and get error message. Once that is done if possible write a post or paste code here.

**Comment by loay** [comment]
Hi @shankarpilli 
Can you provide more info so I can debug? 
The info in the first comment are not enough. Can you please provide a sample repo so I can reproduce? Thanks.

**Comment by shankarpilli** [comment]
Its very simple. You have a server and application. In your database you don't have records. so you have send error message from the server. 
How I have to wrote that in the server side and How that message get in the Android application error message.
