### ISSUE TITLE
create model with name "host" lead to error in explorer.

### ISSUE THREAD

**Issue by guodong** [strongloop/loopback#2569]
Create model with slc with name "host", then run server on port 3000, then open http://0.0.0.0:3000/explorer, error show as:resolver.js:455Uncaught TypeError: Cannot create property 'help' on string '0.0.0.0:3000'

when I change model name host to host1, everything becomes ok.

**Comment by davidcheung** [comment]
Hmm interesting, I can reproduce the same error, perhaps its because of a conflict with the [swagger specs](http://swagger.io/specification/) `host`, since node runtime doesnt throw an error. 

Might be related : https://github.com/strongloop/loopback-component-explorer/issues/135

**Comment by guodong** [comment]
Please ping me when it is fixed~ 3Q

**Comment by davidcheung** [comment]
perhaps fixed by https://github.com/strongloop/loopback-component-explorer/pull/182, 
- [ ] need to verify

**Comment by davidcheung** [comment]
looks like this is nolonger an issue in `loopback-component-explorer@3` 
![screen shot 2016-10-17 at 8 06 27 pm](https://cloud.githubusercontent.com/assets/1787590/19459975/509b176c-94a5-11e6-9ccd-1c77ca533592.png)

**Comment by davidcheung** [comment]
closing this as [loopback-workspace](https://github.com/strongloop/loopback-workspace/commit/6a5a10453ed7ad34179d259f3ac9114be66e453f) will now(once published) scaffold with new explorer

**Comment by davidcheung** [comment]
didnt notice its only lb@2.x that would get new explorer, probably still an issue
