### ISSUE TITLE
How to find which method triggered an operation hook?

### ISSUE THREAD

**Issue by eahenke** [strongloop/loopback#2575]
Is there a way to find the name of the method that triggered an operation hook from inside the hook?

Example:
```
MyModel.observe('after save', function (ctx, next)
    {
          var methodName = ctx.some_context_property;
}
```

I see that there is a methodName property in the ctx.Model.app._remotes object - but it is occasionally incorrect.  It sometimes lists `methodName` as `find` when the operation is `create`, and `find` shouldn't be able to trigger an `after save` hook.  Is there a more reliable way to access the name of the method?  Thanks in advance.

**Comment by eahenke** [comment]
If anyone else has this question, I've switched to using a remote hook instead of an observe hook for this, as the remote hook's `ctx` object more easily displays the method name.
```
MyModel.afterRemote('**', function(ctx, modelInstance, next)
{
    var methodName = ctx.method.name;
});
```

**Comment by kamal0808** [comment]
Yes, `ctx.Model` will get you what you need. It's mentioned in the official documentation. Here's a link:

https://docs.strongloop.com/display/APIC/Operation+hooks#Operationhooks-Targetmodel

**Comment by gunjpan** [comment]
@eahenke : yes, I also suggest to use `remote hooks`. Closing this as resolved. Have a good day :)

**Comment by bajtos** [comment]
It was our intentional design decision to leave out the method name from Operation Hooks context. For users wishing to execute different code depending on which DAO method was invoked, we used to think of Per-method hooks in https://github.com/strongloop/loopback-datasource-juggler/issues/397. However, we decided to reject that feature. Quoting from https://github.com/strongloop/loopback-datasource-juggler/issues/397#issuecomment-314121500:

> We don't support per-method hooks, at least not at the level provided by Model class from loopback-datasource-juggler. There are other ways how to achieve this functionality, for example by using strong-remoting's before/after hooks, or by using a 3rd party library that can wrap model methods contributed by connectors into proxies allowing injections of custom code.
