### ISSUE TITLE
Defining an Array of Enums

### ISSUE THREAD

**Issue by dschrimpsher** [strongloop/loopback#2579]
Hey guys, 
I have been using Loopback for about a year now.  I have figured out most of the tricks and tips.  However, I have a new thing today and I can't figure out how to define it. 

I need to make an array of Enums. 

I would normally define an enum as 

```
 "siteType": {
      "type": "string",
      "enum": [
        "Type I",
        "Type II",
        "ENNI Location"
      ]
    },
```

and that works fine However when I try the following

```
"accessMedia": {
      "type": [
        {
          "type": "string",
          "enum": [
            "Fiber",
            "Coax",
            "Twisted Pair"
          ]
        }
      ]
    },
```

In explorer and the swagger I get

```
accessMedia: [
   ""
]
```

Which is not what I expected.  
I know I could create an object to hold the enum but then my JSON would look like

```
accessMedia.[
   {
      somefield: Coax,
    }
   {
     somefield:Fiber,
   }
]
```

rather than

```
accessMedia[
   'Coax',
   'Fiber', 
...
]
```

Am I defining it wrong or is this intentionally not allowed.

**Comment by ritch** [comment]
I think you are looking for this feature:

https://github.com/strongloop/loopback/issues/1321

Please re-open / ping me if this isn't what you are looking for.
