### ISSUE TITLE
Nested queries with array object not working : memory-connector 

### ISSUE THREAD

**Issue by pponugo** [strongloop/loopback#2582]
When using **memory-connector**, some of the **nested queries** are not working.

For the below sample data, below are working and non working nested query examples.
> Working queries
- /api/customers?filter[where][emails.address]=howard29@seattletimes.com
- /api/customers?filter[where][customdata.obj.value]=DC893708

> Not Working queries
- /api/customers?filter[where][customdata.list.value]=67925088689

Similar issues, #517, #953
Forked repository to reproduce the issue: https://github.com/pponugo/loopback-sandbox
  
        {
          name: 'John Lennon',
          address: {
            street: '123 A St',
            city: 'San Jose',
            state: 'CA',
            zipCode: '95131',
            tags: [
                { tag: 'business' },
                { tag: 'rent' },
            ],
          },
          friends: [
            { name: 'Paul McCartney' },
            { name: 'George Harrison' },
            { name: 'Ringo Starr' },
          ],
          children: ['Sean', 'Julian'],
        }

**Comment by pponugo** [comment]
Fixed and created pull request. https://github.com/strongloop/loopback-datasource-juggler/pull/1027

**Comment by bajtos** [comment]
Fixed by #1027 and d385dfa9d.
