### ISSUE TITLE
How to get include filter array inside a find function

### ISSUE THREAD

**Issue by tmclouisluk** [strongloop/loopback#2584]
```
var filter = {
          include: 'member',
        };
        user.find(filter, function (err, instances) {
            console.log(instances[0].member);
            cb(null, instances);
        });
```

by the console.log(instances.member), i cant get the include array of each users.
Do anyone know how to get the array of members of each users?

**Comment by 0candy** [comment]
So your related model 'member' is not showing up when you query on user? 

Could you please fork the [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) with a sample repo to reproduce your issue with? Thanks!

**Comment by davidcheung** [comment]
@tmclouisluk are you still facing this issue? closing inactive issues, please ping me or open a new issue with steps to reproduce your issue, thanks
