### ISSUE TITLE
Issue with where filters, OR & AND together

### ISSUE THREAD

**Issue by mohit1993** [strongloop/loopback#2588]
Hi, i am using mysql database and trying to hit the following query...but theres an issue with and & or filters....can't make it work...please any suggestions....

api/events?filter[where][event_name][regexp]=m&filter[where][event_description][regexp]=m&filter[where][and][0][status]=approved&filter[where][and][1][start_time][gt]=1470417409303

I am trying to fetch events from database whose event_name or event_description  contains a keyword passed in query..here it is 'm'...and i only want those events which are approved by status and have start_time greater than the current time passed as epoch format....(database contains epoch time).

The issue exists because of having and & or statements together in one request. What is the solution to this problem?

Regards
Mohit Goyal

**Comment by ritch** [comment]
To try and isolate the issue, can you try encoding the same query as JSON?

eg.

```
MY_JSON={"where": {"foo": "bar"}
curl $MY_URL?filter=$MY_JSON
```

I'm not sure we support this syntax: `[and][0][status]`.

If that still doesn't work you can run that request with `DEBUG=*` set, and do some digging into what the actual query is. (DEBUG supports filtering for just your connector, strong-remoting, etc, so playing with that setting might make it easier to find the relevant info).

**Comment by davidcheung** [comment]
Closing inactive issues, we use [`qs` middleware](https://github.com/ljharb/qs/) (same as express) to parse queries, so definitely checkout the docs there to see how they parse these values, if you are still facing this issue, please ping me back on this issue or open a new one with steps to reproduce. thanks!
