### ISSUE TITLE
Upstream shelby's strong-remoting changes

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#2590]
https://github.com/strongloop/strong-remoting/compare/master...shelbys:master

There are some really useful / important changes in here that many people are asking for:

https://github.com/strongloop/loopback/issues/1321

**Comment by bajtos** [comment]
IMO, it's important to take the proper (and hard) way of understanding what each commit tries to achieve, add any missing unit tests, improve the commit message; then create a pull request and get it reviewed.
