### ISSUE TITLE
do you have a script to create user model on mySql ??

### ISSUE THREAD

**Issue by emazzu** [strongloop/loopback#2596]
Hi, how are you !!!

do you have a script to create user model on mySql ??

i would have a token column not ? 

  "realm": "string",
    "username": "string",
    "credentials": {},
    "challenges": {},
    "email": "string",
    "emailVerified": true,
    "status": "string",
    "created": "2016-08-08",
    "lastUpdated": "2016-08-08",
    "id": 0

**Comment by 0candy** [comment]
Take a look at this example:
https://github.com/strongloop/loopback-connector-mysql/blob/340a4eb0f6599bf4a31b013f4ef7097a19d401b8/example/table.sql#L27-L43

**Comment by emazzu** [comment]
thank you Ocandy !!!
