### ISSUE TITLE
user register and confirm

### ISSUE THREAD

**Issue by emazzu** [strongloop/loopback#2599]
Hi, how are you ?

I am investigate the user model !!!

I create de table on mySQL and call api register  http://192.168.0.18:3000/api/Users.

It works good, but it did not return token !!!

it should have returned a token ?? and I can confirm the user ?? sending this token ?

the confirm api, need id and token.

the confirm api, I have customize it or has logic incluided ?

Regards
Eduardo

**Comment by eisverticker** [comment]
https://github.com/strongloop/loopback-example-user-management

**Comment by emazzu** [comment]
Regards
Eduardo
