### ISSUE TITLE
for verify the email after registration, I need email connector ?

### ISSUE THREAD

**Issue by emazzu** [strongloop/loopback#2601]
Hi, how are you ?

for verify the email after registration, I need email connector ? or it is verify for strongloop ?

Regards
Eduardo

**Comment by jannyHou** [comment]
@emazzu I think you can just set `emailVerificationRequired` to true in your model.json file, please check our doc of ["Verify email"](https://docs.strongloop.com/display/public/LB/Registering+users#Registeringusers-Verifyingemailaddresses) to see details.

And also if you are interested in Email connector, please check doc page: https://docs.strongloop.com/display/public/LB/Email+connector

**Comment by 0candy** [comment]
You will need to configure LoopBack to send email for email related features

See this example on how to set it up.
https://github.com/strongloop/loopback-example-user-management#how-do-you-register-a-new-user

**Comment by Arathy-sivan** [comment]
Could you please provide email verification code in loopback4 ??

**Comment by jannyHou** [comment]
weird the verify email address page seems gone https://loopback.io/doc/en/lb4/Registering-users.html#verifying-email-addresses
@Arathy-sivan In Loopback 4 we have an in progress PR showing how to do validation, see https://github.com/strongloop/loopback-next/pull/4895

You can validate a field's format by specifying json spec for it, like
https://github.com/strongloop/loopback-next/pull/4895/files#diff-7217ca2d9cf0bb010f7e4034a7e3e9beR21

Or add custom validation logic in an interceptor, like
https://github.com/strongloop/loopback-next/blob/1cecd211c0d3302f0021eec340596fd300831c6b/examples/validation-app/src/interceptors/validate-phone-num.interceptor.ts

It may take a few minutes' time to try the example, let me know if you have any questions.
