### ISSUE TITLE
Validation error when verifying and confirming a user's identity

### ISSUE THREAD

**Issue by bekl** [strongloop/loopback#2602]
The methods `User.prototype.verify()` and `User.confirm()` used to verify and confirm a user's identity use `PersistedModel.prototype.save()` to set the verification token and `emailVerified` flag. This leads to a validation error ("Email already exists"), since the user has already been created.

&lt;project dir&gt;/common/models/user.js:

```javascript
User.prototype.verify = function(options, fn) {

  [...]

  tokenGenerator(user, function(err, token) {
    if (err) { return fn(err); }

    user.verificationToken = token;
    user.save(function(err) {
      if (err) {
        fn(err);
      } else {
        sendEmail(user);
      }
    });
  });

  [...]

User.confirm = function(uid, token, redirect, fn) {
  fn = fn || utils.createPromiseCallback();
  this.findById(uid, function(err, user) {
    if (err) {
      fn(err);
    } else {
      if (user && user.verificationToken === token) {
        user.verificationToken = null;
        user.emailVerified = true;
        user.save(function(err) {
          if (err) {
            fn(err);
          } else {
            fn();
          }
        });

  [...]
```

Fix:

```javascript
User.prototype.verify = function(options, fn) {

  [...]

  tokenGenerator(user, function(err, token) {
    if (err) { return fn(err); }

    user.updateAttribute("verificationToken", token, function(err) {
      if (err) {
        fn(err);
      } else {
        sendEmail(user);
      }
    });
  });

  [...]

User.confirm = function(uid, token, redirect, fn) {
  fn = fn || utils.createPromiseCallback();
  this.findById(uid, function(err, user) {
    if (err) {
      fn(err);
    } else {
      if (user && user.verificationToken === token) {
        user.updateAttributes({ verificationToken: null, emailVerified: true }, function(err) {
          if (err) {
            fn(err);
          } else {
            fn();
          }
        });

  [...]
```

As a side note, shouldn't `options.redirect` in `User.prototype.verify()` be encoded (using `encodeURIComponent()`)?

**Comment by joannecheah** [comment]
After implementing your fix above, i get the following error.

![image](https://cloud.githubusercontent.com/assets/19943949/17764492/3a062924-6552-11e6-9046-5388caa858d3.png)

**Comment by bekl** [comment]
Which LoopBack version and connector are you using?

**Comment by joannecheah** [comment]
"loopback": "^2.27.0"
"loopback-connector-couchbase": "^1.0.6",

**Comment by bekl** [comment]
Apparently, updateAttributes() is not implemented by loopback-connector-couchbase, but needs to be for my fix to work. This is no LoopBack issue, but one with the connector you're using and should be reported as a feature/enhancement request in the respective respository, sorry!

**Comment by joannecheah** [comment]
ok thanks for the info!

**Comment by richardpringle** [comment]
@bekl, what's the scenario exactly? When is the validation error thrown, upon calling one of those functions?

**Comment by bekl** [comment]
Right, the validation error is thrown if one of `User.prototype.verify()` or `User.confirm()` is called after the user has been created (e.g. as shown in https://github.com/strongloop/loopback-example-user-management). No error is raised if `PersistedModel.prototype.updateAttribute()` or `PersistedModel.prototype.updateAttributes()` are used as opposed to `PersistedModel.prototype.save()`.

**Comment by richardpringle** [comment]
@bekl, I just tried the example with 
```shell
├── loopback@2.31.0
└── loopback-datasource-juggler@2.50.0
```

and it worked no problem. 

@Amir-61, I believe there was talk of replacing  the `save()` function with one of the new functions that you implemented. Was this one of those places?

**Comment by richardpringle** [comment]
@bekl what version of `loopback` are you using?

**Comment by bekl** [comment]
@richardpringle I'm using

```
+-- loopback@3.0.0-alpha.2
| +-- loopback-datasource-juggler@3.0.0-alpha.5
```

**Comment by richardpringle** [comment]
@bekl, so I can reproduce your error when I have an issue logging into my smtp server. When I reconfigure the smtp server (while the original app instance is still running) and try again, I get the `email already exists` error. 

However, when I restart the server, I don't have a problem. 

Are you running into the issue out of the box, is your smtp server working? From what I've seen, as long as any errors are handled properly, it should work. With that said, the example does not handle an error well. I have submitted a PR (strongloop/loopback-example-user-management#40) for the example. 

Are there any other cases where `confirm` or `verify` aren't working for you?

**Comment by bekl** [comment]
@richardpringle Thanks for the PR! Unfortunately, the issue still persists. I suppose the problem lies in the use of `save()` and the following implicit call of `isValid()` to validate the model data (as stated on https://docs.strongloop.com/display/public/LB/Validating+model+data):

> The validation methods are invoked [...] automatically each time model instance is created [...].

The user instance is saved (and persisted to the database) on registration and then again on verification, which leads to a validation error, since `UserModel.validatesUniquenessOf('email', { message: 'Email already exists' });` in `<project dir>/common/models/user.js` fails. Therefore, the issue is not related to the email configuration, but rather to the repeated call of `save()` on the same model instance.

**Comment by richardpringle** [comment]
@bekl can you fork [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) and reproduce in the fork? Or reproduce in the example? 

What you're saying makes sense but I need to be able to reproduce the error (which I can't currently do with the example) before I can escalate this as a bug and get the fix in. As I said... everything seems to be working fine for me as long as you handle the case where there is an error with the email.

**Comment by bekl** [comment]
@richardpringle I could break down the problem to a mixin I'm using which prevents read-only properties from being updated. The mixin unsets all read-only properties on update (including the model ID if declared as such) which leads to the above validation error, my bad. Thanks for your help!

**Comment by richardpringle** [comment]
@bekl, not sure that I was much help but I'm glad your issue was resolved!
