### ISSUE TITLE
mySQL script of security models ? User - Role - RoleMapping - ACL ??

### ISSUE THREAD

**Issue by emazzu** [strongloop/loopback#2606]
Hi, how are you ?

somebody has a script to create these models ?

User - Role - RoleMapping - ACL

Regards
Eduardo

**Comment by gunjpan** [comment]
Hi @emazzu,
you can use `automigrate` method as shown in the following document to generate tables for built-in models:
[Creating database tables for built-in models](https://docs.strongloop.com/display/public/LB/Creating+database+tables+for+built-in+models)

**Comment by emazzu** [comment]
Hi @gunjpan , you are you ?

**datasources.json**
{
	"db": {
		"name": "db",
		"connector": "memory"
	},
	"mysqlSkeletonApp": {
		"name": "mysqlSkeletonApp",
		"host": "xxxxxxxxxxxx",
		"port": 3306,
		"database": "skeletonApp",
		"password": "xxxxx",
		"user": "user1",
		"connector": "mysql"
	}
}

**create-lb-tables.js**
var server = require('./server');
var ds = server.dataSources.autoM;
var lbTables = ['AccessToken', 'ACL', 'RoleMapping', 'Role'];
ds.automigrate(lbTables, function(er) {
	if (er) throw er;
	console.log('Loopback tables [' + lbTables + '] created in ', ds.adapter.name);
	ds.disconnect();
});

**the script shows an error, do you know ? what can be ??**

xmazzuce@osboxes:~/apps/a/server$ node create-lb-tables.js
/home/xmazzuce/apps/a/server/create-lb-tables.js:4
ds.automigrate(lbTables, function(er) {
  ^

TypeError: Cannot read property 'automigrate' of undefined
    at Object.<anonymous> (/home/xmazzuce/apps/a/server/create-lb-tables.js:4:3)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
    at startup (node.js:141:18)
    at node.js:980:3

**Comment by gunjpan** [comment]
@emazzu : You're running the script wrong way. It's part of the application booting process. 
See how boot-scripts are defined and their order of execution [here](https://docs.strongloop.com/display/APIC/Defining+boot+scripts).

Also, recommended-good reads:
- [how to create database schema from models](https://docs.strongloop.com/display/APIC/Creating+a+database+schema+from+models)
- [Working with LoopBack Objects](https://docs.strongloop.com/display/APIC/Working+with+LoopBack+objects) i.e. how to access `app`, `server` and `model` objects in different areas of LoopBack application.

Hope that helps :)

**Comment by emazzu** [comment]
thank you !!!

Regards
Eduardo
