### ISSUE TITLE
how loopback checked the security, is manual ??

### ISSUE THREAD

**Issue by emazzu** [strongloop/loopback#2609]
I already have the security model persisted, and add server/boot/authentication.js

module.exports = function enableAuthentication(server) {
  server.enableAuth();
};

**User**
![image](https://cloud.githubusercontent.com/assets/6100546/17602591/b2f7cfa0-5fe3-11e6-9a2d-58aa6f5b36fa.png)

**Role**
![image](https://cloud.githubusercontent.com/assets/6100546/17602606/c0467152-5fe3-11e6-828b-b0ff48257051.png)

**Role Mapping**
![image](https://cloud.githubusercontent.com/assets/6100546/17602615/caaab0f4-5fe3-11e6-81d0-28138b075bcf.png)

**ACL**
![image](https://cloud.githubusercontent.com/assets/6100546/17602622/d5bfe7fc-5fe3-11e6-8c7e-9355ff0470e0.png)

how have I to do, for apply the security ? 

Regards
Eduardo

**Comment by raymondfeng** [comment]
Once you have server/boot/authentication.js and role/roleMapping/acl defined, LoopBack should try to enforce the check for you.

**Comment by emazzu** [comment]
Fantastic !!!! Thank you !!! and if I would like to do something special or diference, I have to do the apis truth ??

Regards
Eduardo

**Comment by emazzu** [comment]
Is OK, principal ID = MASTER_WEELS and not 5 ??? 

Is OK that the principal ID and role ID are string ???

**Comment by emazzu** [comment]
Hi, the security works good, I enable de audit !!!

question ? a user by default is member of $everyone and $unauthenticated. and when the user log in, by default is member of  $everyone and $authenticated ??

if I the model ACL is empty !!! $everyone user has access to ALL or NONE ??


![image](https://cloud.githubusercontent.com/assets/6100546/17635179/66123fb2-60ac-11e6-8531-68296f9bae6e.png)

**Comment by 0candy** [comment]
You can control the data access by setting the acl on the models.
See example:
https://docs.strongloop.com/display/APIC/Controlling+data+access#Controllingdataaccess-Definingaccesscontrol

**Comment by emazzu** [comment]
Ocandy, how are you !!! would you be so kind that response this case #2617.

I can not go without it

Regards
Eduardo

**Comment by 0candy** [comment]
@emazzu Can I close this issue? Is this resolved?

**Comment by emazzu** [comment]
Regards
Eduardo

**Comment by vikasgannarapu** [comment]
I would like to know if there is a way to skip the security check while running the unit tests in loopback controllers? I'm writing the unit tests for the custom controllers and it says "unauthorized" when I'm trying to access them
