### ISSUE TITLE
Email-Verification-Link is wrong

### ISSUE THREAD

**Issue by EdmundoDelGusto** [strongloop/loopback#2611]
I always get an Email-Verification-Link like this:

http://localhost:3000/api/Physicians/confirm**?uid=**b54e163faa94f4ad68d95d1bac8ab95a**&redirect=**/#/sign-up/success**&token=**0b7738649f86ec32145c77d8a7447d8acd04340b1c17837dfb275fc4cd8c5fc28073f44dfb93da5efd98044cd8a39c36c5156518ac0948f543ec13ff6cfcd26b

First the uid, then the redirect-link and at last the token.
But this link doesn't work for me. I alway get an Error with "Invalid Token". But it works if I'm putting the token first.

http://localhost:3000/api/Physicians/confirm**?token=**0b7738649f86ec32145c77d8a7447d8acd04340b1c17837dfb275fc4cd8c5fc28073f44dfb93da5efd98044cd8a39c36c5156518ac0948f543ec13ff6cfcd26b**&uid=**b54e163faa94f4ad68d95d1bac8ab95a**&redirect=**/#/sign-up/success

I changed in loopback/common/models/user.js how loopback build the URL and now it works out for me. Don't know if it's a common problem or why there is a need to have this order.

**Comment by davidcheung** [comment]
Hi @EdmundoDelGusto, I believe the problem might be you have to escape the slashes
please let me know if that fixes the issue.

**Comment by davidcheung** [comment]
i believe this is duplicate issue as https://github.com/strongloop/loopback/issues/2307
i think the correct solution is to escape the url, closing this in favour of #2307
