### ISSUE TITLE
By overriding the builtin authentication models, ACL is not working

### ISSUE THREAD

**Issue by naveen-venkat** [strongloop/loopback#2615]
We are using loopback V2.22.0 and loopback-connector-DB2 V1.0.17. Since we are saving thr user/role/role mapping/access token in the DB2 mainframe database, have a requirement to change the build in model table/column names from mixed case to upper case.

ACL is not inherited, because we are adding the acl's in the respective models.

So the built in models have been inherited and table/column names are been updated as following,

cpt-access-token.json
```json
{
  "name": "CptAccessToken",
  "base": "AccessToken",
  "idInjection": false,
  "db2": {
    "table": "AAA"
  },
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "id": true,
      "type": "string",
      "db2": {
        "dataType": "VARCHAR",
        "dataLength": 255
      }
    },
    "USER_ID": {
      "db2": {
        "columnName": "USER_ID",
        "dataType": "BIGINT"
      }
    },
    "ttl": {
      "type": "number",
      "db2": {
        "columnName": "TTL"
      }
    },
    "created": {
      "type": "date",
      "db2": {
        "columnName": "CREATED_TIMESTAMP",
        "dataType": "TIMESTAMP"
      }
    }
  },
  "validations": [],
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "CptUser",
      "foreignKey": "USER_ID"
    }
  },
  "acls": [
    {
      "property": "aaa",
      "accessType": "*",
      "permission": "ALLOW",
      "principalType": "ROLE",
      "principalId": "$everyone"
    },
    {
      "property": "aaa",
      "accessType": "*",
      "permission": "ALLOW",
      "principalType": "ROLE",
      "principalId": "$everyone"
    }
  ],
  "methods": {}
}
```
cpt-role-mapping.json
```json
{
  "name": "CptRoleMapping",
  "base": "RoleMapping",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "db2": {
    "table": "XXX"
  },
  "properties": {
    "USER_ROLE_ID": {
      "type": "string",
      "id": true,
      "generated": true,
      "db2": {
        "columnName": "USER_ROLE_ID"
      }
    },
    "principalType": {
      "type": "string",
      "db2": {
        "columnName": "PRINCIPAL_TYPE"
      }
    },
    "principalId": {
      "type": "string",
      "db2": {
        "columnName": "PRINCIPAL_ID"
      }
    },
    "created": {
      "type": "date",
      "db2": {
        "columnName": "CREATED_BY",
        "dataType": "TIMESTAMP"
      }
    },
    "modified": {
      "type": "date",
      "db2": {
        "columnName": "LAST_UPDATED_BY",
        "dataType": "TIMESTAMP"
      }
    }
  },
  "validations": [],
  "relations": {
    "roles": {
      "type": "belongsTo",
      "model": "CptRole",
      "foreignKey": "ROLE_ID"
    },
    "user": {
      "type": "belongsTo",
      "model": "CptUser",
      "foreignKey": "USER_ID"
    }
  },
  "acls": [],
  "methods": {}
}
```

cpt-user.json
```json
{
  "name": "CptUser",
  "base": "User",
  "db2": {
    "table": "BBB"
  },
  "hidden": [
    "failedLoginAttempts",
    "isLocked"
  ],
  "ttl": 7200,
  "properties": {
    "realm": null,
    "challenges": null,
    "credentials": null,
    "emailVerified": null,
    "status": null,
    "verificationToken": null,
    "USER_ID": {
      "type": "string",
      "id": true,
      "db2": {
        "columnName": "USER_ID"
      }
    }
  },
  "validations": [],
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "CptAccessToken",
      "foreignKey": "USER_ID"
    },
    "roleMappings": {
      "type": "hasMany",
      "model": "CptRoleMapping",
      "foreignKey": "principalId"
    }
  },
  "acls": [
    {
      "property": "*",
      "accessType": "*",
      "permission": "DENY",
      "principalType": "ROLE",
      "principalId": "$everyone"
    },
    {
      "property": "loginABC",
      "accessType": "*",
      "permission": "ALLOW",
      "principalType": "ROLE",
      "principalId": "$everyone"
    },
    {
      "property": "getABC",
      "accessType": "*",
      "permission": "ALLOW",
      "principalType": "ROLE",
      "principalId": "$authenticated"
    }
  ],
  "methods": {}
}
```

When we try to login, it works because the login api acl is set to allow everyone, but when the getABC is called, it throws authorization required error though the appropriate access token is passed and the acl is set.

[debug-logs.docx](https://github.com/strongloop/loopback/files/415625/debug-logs.docx)

**Comment by richardpringle** [comment]
@naveen-venkat,

Is it possible to run the app with the following environment-variable set:
`DEBUG=loopback:security*`

**Comment by richardpringle** [comment]
@naveen-venkat, can I also see your `cpt-role.json`?

**Comment by richardpringle** [comment]
@naveen-venkat, I believe I found the problem.

I believe that if you change the instances `"foreignKey": "USER_ID"` key value pair to `"foreignKey": "userId"` and change the property of `USER_ID` on the `CptAccessToken` to `userId` while maintaining the same DB2 column mapping, the `$authenticated` role should resolve properly.

**Comment by whitehorse5353** [comment]
Hi @richardpringle , I work with @naveen-venkat. 

We got a standard column names from DB2(database), Due to that naming conventions we created a new models out of ACL, AccessToken, Role, RoleMapping and User as a base models. 

For example : 

It says `USER_ID` instead of `userId` for the standard database naming conventions. 
   
When i try to give an property name in `model.json` file like below mentioned

`some_model.json`

   ```
   "db2": {
       "table": "SOME_STANDARD_TABLE_NAME"
    },
   "properties": {   
       "userId": {                  // "userId" followed naming convention in loopback 
         "type": "string",
         "id": true,
         "db2": {
           "columnName": "USER_ID" // "USER_ID" column name in database 
         }
       },
       "someOtherProperty" : {      // "someOtherProperty" followed naming convention in loopback
          "type": "string",
          "id": true,
          "db2": {
            "columnName": "SOME_OTHER_PROPERTY" // "SOME_OTHER_PROPERTY" column name in database 
          }
       }
   }
   ```
   
Still the base models were pointing to a default relations and throwing an error.

```
"[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  \"USER_ID\" is not valid in the context where it is used.  SQLSTATE=42703\n"
```

**Comment by qpresley** [comment]
@whitehorse5353 Can you please run "export DEBUG=loopback:connector:db2" prior to running your app.  I would like to see the SQL statement which is failing with this error.

**Comment by whitehorse5353** [comment]
Hi thanks for the solution `"foreignKey": "userId"` that worked for `$authenticated`.

But before to that we had a issue in changing property name in access token model. My SQL log seems pretty big, so i am attaching the doc file for your reference.

[sql_error_stack.docx](https://github.com/strongloop/loopback/files/422997/sql_error_stack.docx)

`AccessToken.json`

```
"id": {
      "id": true,
      "type": "string",
      "db2": {
        "columnName": "ACCESS_TOKEN_ID",
        "dataType": "VARCHAR"
      }
    }
```
`error`

```
"[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  \"id\" is not valid in the context where it is used.  SQLSTATE=42703\n"
 ```

**Comment by qpresley** [comment]
@whitehorse5353: Below is the SQL that results in this error, can you open loopback-connector-db2/package.json and let me know what version you are using.  This **may** require you update the connector or move to the newer loopback-connector-db2z connector which has DB2 on z/OS specific statements.

  loopback:connector:db2 DB2.prototype.executeSQL (exit) sql="**SELECT \"id\" FROM FINAL TABLE (INSERT INTO \"T0040ACCESS_TOKEN\"(\"ACCESS_TOKEN_ID\",\"USER_ID\",\"TTL\") VALUES((?),(?),(?)))**" params=["FkQtelc0htAaDfEyjdi7KGb6tGLb7dcp7hO2zDxgGmACzewGZ7KPmK2upKQDnYDD","32",7200] err={"errors":[],"error":"[node-odbc] SQL_ERROR","message":"[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  \"id\" is not valid in the context where it is used.  SQLSTATE=42703\n","state":"42S22"} data=[] more=undefined +110ms

**Comment by whitehorse5353** [comment]
@qpresley the one we use is loopback-connector-db2 - 1.0.17

**Comment by scotdb** [comment]
You've mapped the original table AccessToken to new table T0040ACCESS_TOKEN and changed the original field called "id" to ACCESS_TOKEN_ID.   There fore the SQL which should be generated should be -

SELECT ACCESS_TOKEN_ID FROM FINAL TABLE (INSERT INTO T0040ACCESS_TOKEN (ACCESS_TOKEN_ID, USER_ID, TTL) VALUES((?),(?),(?)))

It looks like the mappings for the actual insert are working but the select from the insert is still using the original name.   Is this a problem with the mapping (it doesn't understand that the column name change also needs to be in the SELECT) or is it something missing from the mapping ?

**Comment by whitehorse5353** [comment]
@scotdb I don't think any property is missing from mapping, but i guess access token base model sets an `id` property by default in model as a primary key column. so when SQL generated this primary key column `id` is missing in database.

https://github.com/strongloop/loopback/blob/master/common/models/access-token.js#L82

**Comment by scotdb** [comment]
Looking at this a bit further, why would you want to retrieve using a FINAL TABLE a value which you already know (you are supplying it to the INSERT).   Normally you'd use FINAL TABLE to retrieve a generated value, such as an identity column.   But the field on AccessToken, originally called "id", doesn't appear to be an identity column (it seems you've defined it as VARCHAR(255).   Is this correct?   Is there something in your definition that is trying to treat this a bit like a generated identity column.   Just offering some observations from a database perspective, since I don't really know what the design intends.

You probably need to drill down to find where the SQL is being generated, and look at why it generates the SELECT .. FROM FINAL TABLE ....   As I said, it is a pointless thing to do when you have all the data anyway.

**Comment by whitehorse5353** [comment]
@scotdb the SQL query generated by loopback-connector-db2 package which internally uses ibm_db package those are core node_modules for db2, even i am not sure about generated query.

**Comment by scotdb** [comment]
It's more a case of wanting to know why it generates a SELECT FROM FINAL TABLE when there is no new data to retrieve.   It looks like something in your definition thinks there is still a generated column called id in the table, separate from the ACCESS_TOKEN_ID column.   The cpt-access-token.json near the top of this chain doesn't mentioned ACCESS_TOKEN_ID at all, so I assume you have a more recent JSON file which it would be useful to see.

**Comment by whitehorse5353** [comment]
@scotdb the `id` issue was there earlier and we parked that one for sometime to make this ACL work first. Now ACL issue is resolved and now we are trying to resolve this `id` and `ACCESS_TOKEN_ID` issue

accessToken.json

```
{
  "name": "accessToken",
  "base": "AccessToken",
  "idInjection": false,
  "db2": {
    "table": "T0040ACCESS_TOKEN"
  },
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "ACCESS_TOKEN_ID": {
      "id": true,
      "type": "string",
      "db2": {
        "columnName": "ACCESS_TOKEN_ID",
        "dataType": "VARCHAR"
      }
    },
    "userId": {
      "db2": {
        "columnName": "USER_ID",
        "dataType": "BIGINT"
      }
    },
    "ttl": {
      "type": "number",
      "db2": {
        "columnName": "TTL"
      }
    },
    "created": {
      "type": "date",
      "db2": {
        "columnName": "CREATED_TIMESTAMP"
      }
    }
  },
  "validations": [],
  "relations": {
    "pensionsUser": {
      "type": "belongsTo",
      "model": "PensionsUser",
      "foreignKey": "userId"
    }
  },
  "acls": [
    {
      "property": "find",
      "accessType": "*",
      "permission": "ALLOW",
      "principalType": "ROLE",
      "principalId": "$everyone"
    },
    {
      "property": "deleteById",
      "accessType": "*",
      "permission": "ALLOW",
      "principalType": "ROLE",
      "principalId": "$everyone"
    }
  ],
  "methods": {}
}
```

**Comment by qpresley** [comment]
@scotdb The SQL is part of the loopback connector for DB2 and was originally written to match how other connectors worked where the common case was to have loopback build the table as well which would have a generated column.  There is a pretty simple change that I'll get implemented in the connector but in the meantime you can make the change in the loopback connector you have installed by doing the following.

cd node_modules/loopback-connector-db2/lib
open db2.js
comment out the current DB2.prototype.create function and add in the following:

/**
 * Create the data model in DB2
 *
 * @param {string} model The model name
 * @param {Object} data The model instance data
 * @param {Object} options Options object
 * @param {Function} [callback] The callback function
 */
DB2.prototype.create = function(model, data, options, callback) {
  var self = this;
  var stmt = self.buildInsert(model, data, options);
  var idName = self.idName(model);
  var sql;

  if (!data[idName]) {
    sql = 'SELECT \"' + idName + '\" FROM FINAL TABLE (' +
          stmt.sql + ')';
  } else {
    sql = stmt.sql;
  }

  self.execute(sql, stmt.params, options, function(err, info) {
    if (err) {
      callback(err);
    } else {
      if (data[idName]) return callback(err, data[idName]);

      callback(err, info[0][idName]);
    }
  });
};

**Comment by whitehorse5353** [comment]
@qpresley i have added this piece of code into `db2.js` file but still i am getting an error, please refer to the attached doc file for the SQL logs. And i suspect the token is not inserting into the new column name that we added `ACCESS_TOKEN_ID`

[sql_error_stack_not_null.docx](https://github.com/strongloop/loopback/files/425062/sql_error_stack_not_null.docx)

**Comment by qpresley** [comment]
@whitehorse5353 Why did you add a new property called ACCESS_TOKEN_ID?

Can you add the following line immediately above the line "var self = this;"

debug('DB2.prototype.create: model=%j, data=%j, options=%j',
            model, data, options);

**Comment by whitehorse5353** [comment]
we don't use the `id` property which is used in `AccessToken` model, because of naming conventions we use this `ACCESS_TOKEN_ID` instead default `id`.

**Comment by qpresley** [comment]
Yes but you have changed the property name which will result in the code not working.  It should be 

"properties": {
    **"id":** {
      "id": true,
      "type": "string",
      "db2": {
        **"columnName": "ACCESS_TOKEN_ID",**
        "dataType": "VARCHAR"
      }
    },
    "userId": {
      "db2": {
        "columnName": "USER_ID",
        "dataType": "BIGINT"
      }
    },

**Comment by whitehorse5353** [comment]
@qpresley yep it works like this. But how can i patch this for other environment ?
```
**"id"**: {
"id": true,
"type": "string",
"db2": {
**"columnName": "ACCESS_TOKEN_ID",**
"dataType": "VARCHAR"
}
```

**Comment by qpresley** [comment]
I'm not sure what you mean, patch for other environment?

**Comment by whitehorse5353** [comment]
@qpresley the update which i made into `db2.js` can't be shipped right. since it's a `node_modules`

**Comment by qpresley** [comment]
Ahh .. I am making that same change in the base code and will be releasing a new version later today.

**Comment by whitehorse5353** [comment]
@qpresley ohhh that really great. Thanks

**Comment by qpresley** [comment]
@whitehorse5353:  This problem has been fixed in release 1.0.19 which is now on npmjs.org.

**Comment by whitehorse5353** [comment]
hi @qpresley did you tested the same for `DB2.prototype.destroyAll`  as well ?

**Comment by qpresley** [comment]
@whitehorse5353 The same issue doesn't exist for destroyAll.  The return value for destroyAll is a count of the number of rows deleted.  Are you seeing a problem with destroy all and if so please open a new issue in https://github.com/strongloop/loopback-connector-db2

**Comment by naveen-venkat** [comment]
Hello @qpresley, 

The you for the support, the latest version 1.0.19 fixes the create issue, but when we try to delete the token, I can see the similar issue coming up,

In db2.js as shown below, its trying to build a DELETE query with SELECT which is similar to create method which is failing, the sql query it prepares as below, 

SELECT "id" FROM OLD TABLE (DELETE FROM "T0040ACCESS_TOKEN" WHERE "ACCESS_TOKEN_ID"=(?)) 

The "id" column above in the SELECT statement should have been "ACCESS_TOKEN_ID". Can you please help us on this? Also i believe, we would be facing similar issue in update as well?

The error returned is below, 
[IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "id" is not valid in the context where it is used.  SQLSTATE=42703



/**
 * Delete all matching model instances
 *
 * @param {string} model The model name
 * @param {Object} where The where object
 * @param {Object} options The options object
 * @param {Function} cb The callback function
 */
DB2.prototype.destroyAll = function(model, where, options, cb) {
  debug('DB2.prototype.destroyAll: model=%s, where=%j, options=%j',
        model, where, options);
  var self = this;
  var stmt = self.buildDelete(model, where, options);
  var idName = self.idName(model);
  var sql = 'SELECT \"' + idName + '\" FROM OLD TABLE (' + stmt.sql + ')';
  self.execute(sql, stmt.params, options, function(err, info) {
    if (cb) {
      cb(err, {count: info.length});
    }
  });
};

Thanks,
Naveen
