### ISSUE TITLE
http/2 support

### ISSUE THREAD

**Issue by matteocrippa** [strongloop/loopback#2616]
I started adding http2 support for express, but I have to figure out how:
- set in `config.json` the protocol to be used (at I picked `http` but I'm not happy with that name);
- set `crt` and `key` for server (same as above how can we manage that?);

Here the [http/2 branch](https://github.com/matteocrippa/loopback)

**Comment by raymondfeng** [comment]
Nice. The branch is https://github.com/matteocrippa/loopback/tree/http/2.

1. I suggest that we use `protocol` in `config.json` for now. Valid values can be `http`, `https`, or `http2`.
2. In the future, we should allow an array of `endpoints` so that each endpoint can have its protocol/host/port and other configs. This way, we allow the server to bind to multiple listeners.

**Comment by matteocrippa** [comment]
@raymondfeng yep the branch is that one.

I do agree `protocol` better fit the name of the variable, I managed to upgrade the code and refactor a very little.

I also managed certs for both `https` and `http/2` and added an early implementation of tests try matching your style.

**Comment by bogomips** [comment]
Hi, 
I am working on PWA that largely uses websocket, so http2 makes the difference during the first connection when the whole application has to be served.
I am currently using apache/php with mod_h2 and a nodejs server for websocket.
It would be great to have just one technology on server side but I don't want to step back on http1's  hell : concatenations, images sprites, domain sharding,etc.
Is http2 support something that I can expect soon?
Is http2 strictly related to expressjs development or it is something that lookback team can handle on his own?
My app's future depend on it, any answer would be apreciated!

**Comment by always-akshat** [comment]
Hey, are there any updates on this ?
