### ISSUE TITLE
very close to solving security - some help ?

### ISSUE THREAD

**Issue by emazzu** [strongloop/loopback#2617]
table **user**

![image](https://cloud.githubusercontent.com/assets/6100546/17640516/6b1cb2a0-60d7-11e6-8055-8d5921e32114.png)

table **role**

![image](https://cloud.githubusercontent.com/assets/6100546/17640518/77f0e082-60d7-11e6-809f-02e2199f5ff2.png)

**table roleMapping**

![image](https://cloud.githubusercontent.com/assets/6100546/17640520/819aac3a-60d7-11e6-96fc-5325204e7dbb.png)

**table ACL**

![image](https://cloud.githubusercontent.com/assets/6100546/17640524/91de0e66-60d7-11e6-9ad9-5a94e64f75c4.png)

1
**$unauthenticated works good !!!**

2
**with log in emazzu6**

**The user is OK, the role is OK: masterWells, but it says Role Mapping found: null and isRole() false.**

**What can be ??? some idea ??**

$unauthenticated loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context getUserId() 11 +0ms
  loopback:security:access-context isAuthenticated() true +0ms
  loopback:security:role isInRole(): $everyone +2ms
  loopback:security:access-context ---AccessContext--- +0ms
  loopback:security:access-context principals: +0ms

`loopback:security:access-context principal: {"type":"USER","id":11} +0ms`

  loopback:security:access-context modelName User +0ms
  loopback:security:access-context modelId undefined +0ms
  loopback:security:access-context property count +1ms
  loopback:security:access-context method count +0ms
  loopback:security:access-context accessType READ +4ms
  loopback:security:access-context accessToken: +3ms
  loopback:security:access-context   id "FF9SRNxSw1ThwFs83jfsWWDasJL3gCW98T0QvAe3GLGwCaoWl3fPzCpW33xr1l3N" +0ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context getUserId() 11 +0ms
  loopback:security:access-context isAuthenticated() true +0ms
  loopback:security:role Custom resolver found for role $everyone +0ms

`loopback:security:role Role found: {"id":5,"name":"masterWells","description":"Access to Master Wells","created":null,"modified":null} +327ms`

  **loopback:security:role Role mapping found: null +335ms**
  **loopback:security:role isInRole() returns: false +1ms**

  loopback:security:acl The following ACLs were searched:  +0ms
  loopback:security:acl ---ACL--- +0ms
  loopback:security:acl model User +0ms
  loopback:security:acl property \* +0ms
  loopback:security:acl principalType ROLE +0ms
  loopback:security:acl principalId $everyone +0ms
  loopback:security:acl accessType \* +1ms
  loopback:security:acl permission DENY +0ms
  loopback:security:acl with score: +0ms 7495
  loopback:security:acl ---Resolved--- +0ms
  loopback:security:access-context ---AccessRequest--- +0ms
  loopback:security:access-context  model User +0ms
  loopback:security:access-context  property count +0ms
  loopback:security:access-context  accessType READ +0ms
  loopback:security:access-context  permission DENY +0ms
  loopback:security:access-context  isWildcard() false +1ms

**Comment by 0candy** [comment]
How did you define roles?
https://docs.strongloop.com/display/APIC/Defining+and+using+roles

Could you please fork the loopback-sandbox with your sample repo so I can take a look at your configurations?
https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by 0candy** [comment]
@emazzu Did you resolve the issue? Can I close this?

**Comment by emazzu** [comment]
yes, thank you !!!

Regards
Eduardo
