### ISSUE TITLE
Send the client JSON with Users.on('resetPasswordRequest')

### ISSUE THREAD

**Issue by devntd** [strongloop/loopback#2619]
I use method Users.on('resetPasswordRequest') to retrieve the password
```
 Users.on('resetPasswordRequest', function (info) {
    var html = 'abcxyz';
    Users.app.models.Email.send({
      to: info.email,
      from: 'abc@gmail.com',
      subject: 'Password reset',
      html: html
    }, function (err ,email) {
      if (err) return console.log('> error sending password reset email');
      console.log('> sending password reset email to:', info.email);
    });
  });
```
How do I send JSON formatted for client?

**Comment by gunjpan** [comment]
@devntd: you can achieve that by using `app.set('json spaces', 2)`, ideally, in `<project root>/server/server.js` and it will send a formatted JSON for all calls.

Closing this now. Should you need further assistance, please feel free to comment here with my GH handle and I'll be happy to help you  :)
Thank you and have a great day.
