### ISSUE TITLE
findOne() and count() for scopes

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#262]
Scopes defined by hasMany relations should provide the same querying shortcuts as Models do: `findOne`, `count`. These methods should be available via the REST API too.

**Comment by gunjpan** [comment]
@bajtos : I believe, we have support for `count` now, not sure about `findOne`. PTAL.

**Comment by bajtos** [comment]
Since there was no further discussion since Jul 2014, I am closing this feature request.
