### ISSUE TITLE
Generating Angular-code using lb-ng doesn't work anymore

### ISSUE THREAD

**Issue by Undrium** [strongloop/loopback#2624]
I get the following using the lb-ng command:

> undefined:25
>   throw err;
>   ^
> 
> TypeError: ejs:69
>     67|  */
>     68|   module.factory(
>  >> 69|     <%-: modelName | q %>,
>     70|     [
>     71|       'LoopBackResource', 'LoopBackAuth', '$injector',
>     72|       function(Resource, LoopBackAuth, $injector) {
> 
> meta.ctor.getEndpoints is not a function
>     at eval (eval at <anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\strongloop\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:34:314)

This causes lb-services.js not to be generated. We are currently using the latest version of Strongloop and Node. Problem with the stacktrace is that it doesn't give any clue at all where to start looking.

**Comment by Undrium** [comment]
A clean install of Strongloop removed this error! :)

**Comment by alvarp** [comment]
The same is happening to me with the following code, I call this module on boot.


```
var generator = require('loopback-sdk-angular');
var fs = require('fs');
var path = require('path');

module.exports = function (app, callback) {
    if(app.booting) {
        app.on('booted', function () {
            console.log('booted');
            generate(app, callback);
        });
    } else {
        generate(app, callback);
    }
};

function generate(app, callback) {
    var options = {
        output: './client/angular-sdk/lb-services.js', // Other task-specific options go here.
        ngModuleName: 'lbServices'
    };

    options.apiUrl = app.get('restApiRoot') || '/api';
    
    var script = generator.services(app, options.ngModuleName, '/api');

    fs.writeFile(options.output, script, {}, function (err) {
        callback(err);
    });
}
```
