### ISSUE TITLE
Wildcard remote hooks - Negation possible?

### ISSUE THREAD

**Issue by stephenwil** [strongloop/loopback#2626]
Hi,
  I'm trying to determine if I can have a remote hook but use some negation, so that for most of my remote methods I want the remote hook to run, but not (for example) any logout method.

I've tried a few regex samples, but can't seem to get them to work, and tried looking through the code to see how it's done. No luck so far.

Thanks

**Comment by stephenwil** [comment]
Oh and I know I can check the ctx.methodString, but I was looking for a neater way.

**Comment by gunjpan** [comment]
@stephenwil: Hi, in remote hooks, use case for`wildcards` is to match more than one method. 
Unfortunately, no negation is supported OOB. 
As you said, 3-4 line code: a desired method name can be easily compared against `ctx.methodString` and call `next()` upon matching method to skip it, to achieve what you're trying to do.

I'm closing this issue for now. Should you need further assistance with it, please feel free to comment with my GH handle and I'll be glad to help you out. 
Thank you and have a great day! :)
