### ISSUE TITLE
resolvers for dynamic roles not found when using app option `localRegistry`

### ISSUE THREAD

**Issue by benkroeger** [strongloop/loopback#2627]
related to #2551 

I'm using my app with the `localRegistry` and `loadBuiltinModels` options set to `true`. This is required when using `loopback#token` middleware and want to provide a custom `AccessToken` modelName to it's params.

```
const app =  loopback({ localRegistry: true, loadBuiltinModels: true }); 
```

However, I started applying ACLs (with **dynamic** roles) to my models and calling the REST API.
As it seemed like my ACLs are not being processed, I started digging and discovered that ACLs defined in a `model-definition.json` are not found by `ACL.getStaticACLs()` since it would lookup the `modelName` in the global registry `loopback.findModel(modelName)`. Luckily, @bajtos already solved that in #2551 (which hasn't been published in a 2.x release yet and I'm applying this patch manually).

This leads me to my actual problem: 
I'm using `app` with `local Registry` and `builtInModels` (no custom `Role` model).

Then I define a dynamic role named 'admin':

```
const { registry } = app;
const Role = registry.getModel('Role');
Role.registerResolver('admin', (role, context, cb) => {
    process.nextTick(() => {
      console.log('in admin role resolver');
      cb(null, false);
    });
  });
```

In one of my models, I define the following ACLs:

```
"acls": [{
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }, {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW",
      "property": "find"
    }],
```

When calling the REST API, somewhere down the line `ACL.checkAccessForContext()` gets called. 
In `common/models/acl.js` you can find this:

```
var Role = loopback.Role;
...
ACL.checkAccessForContext = function(context, callback) {
    ...
    var roleModel = registry.getModelByType(Role);
    ...
    // this happens for each previously resolved alc
    roleModel.isInRole(...);
    ...
}
...
```

Due to the scenario described above (no custom models with `Role` as baseModel), `registry.getModelByTpe(Role)` returns the provided argument as-is, which is the global `loopback.Role`

When now calling `roleModel.isInRole('admin')`, the 'admin' resolver is not recognized since it was registered on the local registry of our app instance. `isInRole()` proceeds to calling `this.findOne()` in order to try to resolve a role named 'admin' from the attached dataSource and ultimately the application *crashes* since this global `loopback.Role` has never been attached to a dataSouce

I found that, when modifying `ACL.checkAccessForContext()` to read the built-in model from it's registry and use that with `registry.getModelByType()`, my ACL works as expected.

```
ACL.checkAccessForContext = function(context, callback) {
    var registry = this.registry;
    var builtInRoleModel = registry.getModel('Role');
    ...
    var roleModel = registry.getModelByType(builtInRoleModel);
    ...
}
```

Does anyone have any objections to providing this in a PR? Am I using the localRegistry wrongly?

**Comment by bajtos** [comment]
So if I understand this correctly, then the `registry` variable in `ACL.checkAccessForContext` is pointing to the global shared registry, instead of `this.registry`. Is that correct understanding?

In that case it makes perfect sense to make the fix you are proposing, @benkroeger.

> Am I using the localRegistry wrongly?

We did not manage to complete the `localRegistry` feature to the state where we could roll it out to all LoopBack users. Issues like the one you are describing here are sort of expected.

> Does anyone have any objections to providing this in a PR?

No, please do open the pull request and mention my handle to get it reviewed quickly.

**Comment by benkroeger** [comment]
actually, the global `Role` variable in `common/models/acl.js`, which is defined very early by 

```
var Role = loopback.Role;
```

points to the `Role` model in the global registry, while I'd expect the `ACL` model to use the same registry that it is registered in (e.g. via `this.registry`).
Another test revealed that when I'm registering a custom model `CustomRole`

```
{
  "name": "CustomRole",
  "base": "Role"
}
```

in my local registry and then run 

```
const Role = loopback.Role;
const roleModel = registry.getModelByType(Role);
assert(roleModel === registry.getModel('CustomRole'), 'custom role could not be resolved by type of role');
```

throws. Rather, `Role` and `roleModel` are identical in this example.
When resolve the built-in `Role` from my local registry, it's fine:

```
const Role = registry.getModel('Role');
const roleModel = registry.getModelByType(Role);
assert(roleModel === registry.getModel('CustomRole'), 'custom role could not be resolved by type of role');
```

works.

I suspect, this is due to the each registry (`loopback` and each local registry) has their own `ModelBuilder` instance that would apply it's magic to the Model's prototype

**Comment by davidcheung** [comment]
Looks like fix has been merged, thanks! closing issue now
