### ISSUE TITLE
Exclude field filter excludes all fields

### ISSUE THREAD

**Issue by dannybster** [strongloop/loopback#2629]
Hi,

As per the docs at: https://docs.strongloop.com/display/public/LB/Fields+filter I was led to believe that an exclude filter would only exclude a particular field and include all the others. However this is not the behaviour I am seeing. I have tried:

https://appurl.com/api/messages?filter={ "fields": {"sent": false} }
https://appurl.com/api/messages?filter={ "fields": {"sent": 0} }
https://appurl.com/api/messages?filter=[fields][sent]=false
https://appurl.com/api/messages?filter=[fields][sent]=0

And all exclude all fields except a customised id field I have set named _mid.

Am I missing something obvious here?  Oh I am using the Mongodb connector.

Thanks
Dan.

**Comment by 0candy** [comment]
Based on what you have above, you're trying to only exclude the field `sent?`
Should not have `=` after filter
Try this:
`?filter[fields][sent]=false`

**Comment by dannybster** [comment]
Ah sorry that was a typo, I have the equals on the filter when using JSON so:

https://appurl.com/api/messages?filter={ "fields": {"sent": false} }
https://appurl.com/api/messages?filter={ "fields": {"sent": 0} }
https://appurl.com/api/messages?filter[fields][sent]=false
https://appurl.com/api/messages?filter[fields][sent]=0

Yep that's exactly what I am trying to do, exclude sent.

Thanks
Dan.

**Comment by 0candy** [comment]
I am not able to reproduce the problem. Could you please fork the sandbox with your sample repo so I can reproduce the issue? Thanks!
https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by dannybster** [comment]
Hi Candy,

Got to the bottom of this. It happens when applying an exclude filter for a field that exists on objects in a collection but the field is not declared in the model schema.  Might be worth adding that to the docs? I know it is probably not an intended use case but it is kind of weird behaviour.

Just in case here are the relevant parts of my setup:
"loopback": "^2.22.0"
"loopback-connector-mongodb": "^1.15.0"
"loopback-datasource-juggler": "^2.39.0"

All this was tested against a MongoDB database version 2.6.9 and 2.6.11

Anyways thanks for your help!

Thanks
Dan.

**Comment by dannybster** [comment]
Hi Candy,

Ignore the previous post, this was a red herring. So I have got to the very bottom of this now. For me using https://appurl.com/api/messages?filter[fields][sent]=0 appears work as an include filter. I have to explicitly use false. So in the docs it appears that the line:


> <true|false> signifies either true or false Boolean literal.    Use true to include the property or false to exclude it from results.
> You can also use 1 for true and 0 for false.

is incorrect?

This was exacerbated by having an "open" model schema where not all of the fields are listed and the minute an exclude filter is applied to a model it "enforces" the fields in the schema and does not return those that aren't.

Does that make sense?

Thanks
Dan.

**Comment by 0candy** [comment]
Hi Dan,
Thanks for looking into this. I have confirmed that using 0/1 does not work. Please only use true/false.

@crandmck Could you please update the doc and remove this line? Thanks!
>>>You can also use 1 for true and 0 for false.

**Comment by crandmck** [comment]
Done!  Thanks for making the update easy for me @0candy !
