### ISSUE TITLE
Role name must be unique?

### ISSUE THREAD

**Issue by ahmetcetin** [strongloop/loopback#2635]
Regarding issue #2111, #2269  which was merged to the the master branch already it looks, we're using the same role name for different realms. We have added a new property to Role model (without extending it, using loopback.Role.defineProperty) for realm name, at least two roles (user and admin) must exist with the same name on each realm. So, not the role name but role name + realm is unique in our implementation. We're using  v2.14.12 at the moment, and strangely, it allows to add a new role using the same name on linux but it fails in windows. Any idea, suggestion?

**Comment by bhayla** [comment]
You can delete the validation on the Role model for this particular scenario

delete loopback.Role.validations.name;

**Comment by ahmetcetin** [comment]
@bhayla thx! it works!
