### ISSUE TITLE
Signing CLA results in application error

### ISSUE THREAD

**Issue by azatoth** [strongloop/loopback#2637]
@rmg Got "An error occurred in the application and your page could not be served" when tried to sign the CLA (it first froze for a long time)

**Comment by gunjpan** [comment]
@azatoth : Can you try one more time? _(I experienced issues accessing GH pages this morning)_

**Comment by azatoth** [comment]
@gunjpan It seems to work now

**Comment by gunjpan** [comment]
Great. Closing now.
