### ISSUE TITLE
loopback is broken after npm update

### ISSUE THREAD

**Issue by franckysolo** [strongloop/loopback#2641]
Hello, I'm new to loopback I try few week loopback with no issue, i made a npm update today
retry loopback then i can't use the api explorer, i've got an error 
*remoting.context option was removed in version 3.0*
when i use slc loopback:model i can't let blank for default value when had a property...
something is broken!
os : Ubuntu 14.04
Commands:
slc -v
```
strongloop v6.0.1 (node v5.8.0)
├── strong-arc@1.8.8 (fb756f2)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.4 (de9885e)
├── generator-loopback@1.23.2 (ebe6d41)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Comment by gunjpan** [comment]
@franckysolo : Could you please uninstall strongloop/loopback using `npm uninstall strongloop -g` and re-install it. 
After that, try to create a new application -- at some other location in your drive -- and see if the error still persists. 
FYI, I tried to reproduce, and I was able to create a new application and run it fine. 

Please make sure that, for question:`? Which version of LoopBack would you like to use?` 
you select `2.x` as it's the stable version of LoopBack, and if you want new features -- still in alpha -- you can create `3.x` application.

**Comment by franckysolo** [comment]
@gunjpan : Hello, thanks for your reply, i worked with 3x version for previous both tests
So i uninstall strongloop, re-install it...
For info, when installing i've got npm warn for minimatch dependencies...

- Try to create another app `slc loopback` 
- new app call loop01 in new working directory (loop-workspace)
- Select api-server
- Select 3x

Press enter, on deploy i've got 2 others npm warning
` globalize@1.1.1 requires a peer of cldr-data@>=25`
and `cldrjs@0.4.4 requires a peer of cldr-data@>=25`

Then i do:
`cd loop01`
`node .`
In browser go to http://localhost:3000/explorer/, try to get Users i've got error 500
` Error: remoting.context option was removed in version 3.0.`
So i try to create a model :
```
slc loopback:model`

? Enter the model name: CoffeeShop
? Select the data-source to attach CoffeeShop to: db (memory)
? Select model's base class PersistedModel
? Expose CoffeeShop via the REST API? Yes
? Custom plural form (used to build REST URL): 
? Common model or server only? common
Let's add some CoffeeShop properties now.

Enter an empty property name when done.
? Property name: name
   invoke   loopback:property
? Property type: string
? Required? Yes
? Default value[leave blank for none]: 
Warning: please enter the name property again. The default value provided "" is not valid for type: string
```
So nothing change i've got the same behaviour...
What i'm doing wrong?

**Comment by 0candy** [comment]
The issue with not allowing blank default value has been fixed, but a new version has not yet been released.
https://github.com/strongloop/generator-loopback/pull/216
cc @bajtos

**Comment by 0candy** [comment]
Also, other users have reported that they are getting the error:
`Unhandled error for request GET /api/Users: Error: remoting.context option was removed in version 3.0. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details.
`
https://github.com/strongloop/loopback/issues/2610

**Comment by franckysolo** [comment]
@0candy ok thanks for the info
Maybe its help you, i remove my node version, install the new one then 
slc -v give me
```
strongloop v6.0.1 (node v6.4.0)
├── strong-arc@1.8.8 (fb756f2)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.4 (de9885e)
├── generator-loopback@1.23.2 (ebe6d41)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```
Re test to create api but nothing change

**Comment by bajtos** [comment]
Released `generator-loopback@1.24.0`.

**Comment by spid3r** [comment]
Hi guys,

I'm very new to loopback. Today I did my first tutorial about user management and came across the same error when I try to signup a user via the loopback user management example.
https://github.com/strongloop/loopback-example-user-management.
So when the user passes the signup info and tries to register the backend returns to following response body:
> {"error":{"statusCode":500,"name":"Error","message":"remoting.context option was removed in version 3.0. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details.","stack":"Error: remoting.context option was removed in version 3.0. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details.\n    at restApiHandler (/Users/thorstenwolf/Documents/loonone/node_modules/loopback/server/middleware/rest.js:44:15)\n    at Layer.handle [as handle_request] (/Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:312:13)\n    at /Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:330:12)\n    at next (/Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:271:10)\n    at /Users/thorstenwolf/Documents/loonone/node_modules/express-flash/lib/express-flash.js:31:7\n    at /Users/thorstenwolf/Documents/loonone/node_modules/connect-flash/lib/flash.js:21:5\n    at /Users/thorstenwolf/Documents/loonone/node_modules/express-flash/lib/express-flash.js:22:5\n    at Layer.handle [as handle_request] (/Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:312:13)\n    at /Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:330:12)\n    at next (/Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:271:10)\n    at /Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:618:15\n    at next (/Users/thorstenwolf/Documents/loonone/node_modules/express/lib/router/index.js:256:14)"}}

Even when I comment out the user.afterRemote('create', function(context, user, next) { ...
RemoteHook the problem occurs.
I followed the instructions here as well:
https://docs.strongloop.com/display/APIC/Using%20current%20context
and installed loopback context and configured the middleware like this:
...
  "initial": {
    "loopback-context#per-request": {
    },
  }
  ...
Do I need to install a former version of loopback since this seems to be an alpha or what must I do?

Thanks a lot for your help and sorry for the newbie questions.

Regards
Thorsten

**Comment by franckysolo** [comment]
@spid3r use 2x version
