### ISSUE TITLE
Not receiving typed parameters when extending the built-in User model

### ISSUE THREAD

**Issue by gemabarni** [strongloop/loopback#2643]
I'm trying to extend the built-in User model to be able to separate some types of users, as they have different authentication methods. Let's call one of the sub-models Buyers. I've registered the class in model-config and have a `buyer.json` descriptor of it, as follows:

```
{
  "name": "buyer",
  "base": "User",
  "strict": "true",
  "properties": {
  }
}
```

I've overriden the login method of Buyers and exposed it with `Buyer.remoteMethod('login', require('./loginmethod'));` from `buyer.js`. The `loginmethod.json` looks like this:

```
{
  "description": "Buyer login",
  "accessType": "EXECUTE",
  "accepts": {
    "arg": "dto",
    "type": "BuyerLoginDto",
    "description": "",
    "http": {
      "source": "body"
    }
  },
  "returns": {
    "arg": "data",
    "type": "Object",
    "root": true
  },
  "http": {
    "verb": "post",
    "path": "/login"
  },
  "isStatic": true
}
```

So the type of the dto argument inside my login function should be `BuyerLoginDto`, but after some trials and errors when trying to call `dto.isValid()` it turned out that it is just a plain object. If I remove the  `"base": "User",` line from `buyer.json`, it validates itself as it should, so probably gets the `BuyerLoginDto` type .
Btw, I'm using loopback 2.29.1

**Comment by richardpringle** [comment]
Hey @gemabarni, `accepts.type` should be a [Loopback Type](https://docs.strongloop.com/display/public/LB/LoopBack+types) as stated in the [LoopBack API documentation](https://apidocs.strongloop.com/strong-remoting/#sharedmethod). 

There are certain cases where `type` is validated against a non-LoopBack type, but it is inconsistent as far as what works and what doesn't. You should stick with LoopBack Type and perform validation on the argument manually within the method.
