### ISSUE TITLE
Version 2.22.0 crashes on any request after doing npm update

### ISSUE THREAD

**Issue by mastershil** [strongloop/loopback#2644]
Loopback shows this error 

`loopback deprecated loopback#context middleware is deprecated. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details. at node_modules/loopback/server/middleware/rest.js:60:32`

`No context available. ns.run() or ns.bind() must be called first.`

The middleware config is as same as when using version 2.21.0

**Comment by bajtos** [comment]
This should be fixed by https://github.com/strongloop/loopback/pull/2649 in `loopback@2.31.0` now.

**Comment by terehov** [comment]
Unfortunately still there even after the latest update :-( 
`Sun, 28 Aug 2016 03:20:06 GMT loopback deprecated loopback#context middleware is deprecated. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details. at node_modules/loopback/server/middleware/rest.js:60:32`

```
+-- loopback@2.31.0 
| +-- loopback-connector-remote@1.3.1 
| `-- loopback-phase@1.3.1 
|   `-- async@0.9.2 
+-- loopback-boot@2.21.0 
| +-- async@0.9.2 
| +-- lodash@3.10.1 
| `-- semver@4.3.6 
+-- loopback-component-explorer@2.5.0 
| +-- lodash@3.10.1 
| `-- loopback-swagger@2.4.3 
|   +-- async@1.5.2 
|   +-- ejs@1.0.0 
|   +-- lodash@3.10.1 
|   `-- underscore.string@2.3.3 
+-- loopback-component-storage@1.9.0 
| `-- async@0.9.2 
+-- loopback-connector-postgresql@2.6.3 
| +-- async@0.9.2 
| `-- loopback-connector@2.4.0 
|   `-- async@1.5.2 
+-- loopback-context@1.0.0 
+-- loopback-datasource-juggler@2.50.0 
| +-- async@1.0.0 
| `-- qs@3.1.0 
`-- loopback-ds-timestamp-mixin@3.4.0 

```

**Comment by bajtos** [comment]
@terehov please open a new issue and describe how to reproduce the problem locally, ideally by creating a sandbox app per [our wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).
