### ISSUE TITLE
how to define "as" relation name in JSON

### ISSUE THREAD

**Issue by benjaminhon** [strongloop/loopback#2646]
for hasOne relationships i am still getting the children as "plural"

for example, husband hasOne wife, however i still get this result during queries

```
husband.wifes

not husband.wife
```

i want to set it in the model definition in the JSON file since thats where i define everything, i cant seem to find how to do it though

**Comment by alexkolson** [comment]
What's the name of your relation? `as` will get set to the value of the name of your relation. See [`defineRelations`](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/datasource.js#L491).

**Comment by benjaminhon** [comment]
hmm, i didnt set the relation in code, only defined in the JSON file,
```
"relations": {
    "device": {
      "type": "belongsTo",
      "model": "Device",
      "foreignKey": ""
    }
  }
```
I read in the Docs that you can set the "as" relation using code, however, since i was doing all my object definitions and relations in the JSON file i thought i was best to leave it all there, i tried adding a key value pair
```
"as": "node"  // rather than nodes
```
but it doesnt work though

**Comment by 0candy** [comment]
If you're setting the relation by code, then you can use `as` to set the relation name.
`Supplier.hasOne(Account, {foreignKey: 'supplierId', as: 'account'});`
But if you're setting it in JSON, then the relation name is already specified and you don't need the `as` property.
```
  "relations": {
    "supplier_acct": {
      "type": "hasOne",
      "model": "account",
      "foreignKey": "supplierId"
    }
```
In this case, the `as` value is `supplier_acct`

**Comment by benjaminhon** [comment]
Ahh ok thanks!
