### ISSUE TITLE
Login a user with REST as datasource

### ISSUE THREAD

**Issue by Mavloper** [strongloop/loopback#2647]
I have a UserModel that has a base model USER and a REST datasource
`  "UserModel": {
    "dataSource": "mock",
    "public": true
  },
`
Data Source
`  "mock": {
    "name": "mock",
    "baseURL": "http://localhost:3000/",
    "connector": "rest"
  },
`
The UserModel
`{
  "name": "UserModel",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
`
The problem when I call /UserModel/login with a post and a body like
{"username": "test", "password": "123"}

in the mock server I only get a call without even the password to:

/UserModels?where%5Busername%5D=test&limit=1&offset=0&skip=0

I want to handle the login through REST and a backend that receives the Username and password check for them and return 200 or 401

**Comment by 0candy** [comment]
ACLs are not inherited from the base model.
See https://github.com/strongloop/loopback/issues/2270 for more info.
As a workaround for now, please copy the acls from the base model.
https://github.com/strongloop/loopback/blob/6b40c69bb3bebbf1b7651b881f6f8b139922112a/common/models/user.json#L36-L91

Closing as a dup.

**Comment by Mavloper** [comment]
same issue while logging in

**Comment by 0candy** [comment]
What do you mean by logging in? Could you fork the sandbox and give the steps that you took? Thanks!
https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by Mavloper** [comment]
I am using loopback as a middleware service connecting my front end to my back end via REST, 
I try to login a user through
` /UserModel/login` POST - with body
`{"username": "test", "password": "123"}`
the issue is that loopback map this login request to the backend as a get request like mentioned

![2](https://cloud.githubusercontent.com/assets/16214697/17787637/3efba8c2-658a-11e6-9f23-249725b404cc.png)
![1](https://cloud.githubusercontent.com/assets/16214697/17787638/3f0097c4-658a-11e6-874a-f590b8ca1b68.png)

**Comment by 0candy** [comment]
I am unable to reproduce the issue. Could you please share your config so I could see the problem? Thanks!

**Comment by Mavloper** [comment]
@0candy thank you, it was a misunderstood of the way loopback is working I didn't get that loopback it self compare and check the passwords for the user to login.
