### ISSUE TITLE
Replace By ID

### ISSUE THREAD

**Issue by devotox** [strongloop/loopback#2651]
I have this role in my json model

```javascript
        {
		"principalType": "ROLE",
		"principalId": "$authenticated",
		"permission": "ALLOW",
		"property": "replaceById"
	}, 
```

i have a custom route that  then runs the replaceById

```javascript
	router.post(`${restApiRoot}/purchased-location-transfers`, function(req, res) {
		let body = (req.body.data && req.body.data) || req.body;

		if (!req.accessToken){
			return res.status(401).json({ message: 'AUTHORIZATION REQUIRED' });
		}
		
		let attributes = Object.assign({}, body.attributes, {
			profile_id: body.relationships.profile.data.id,
			user_id: body.relationships.user.data.id
		});

		PurchasedLocation.replaceById(body.id, attributes, function(err, location) {
			if (err){ return res.status(404).json({ message: 'Error Transfering Purchase' }); }
			console.log(location);
			res.status(200).json({ message: 'Transfer Successful'});
		});
	});
```

An error is not returned and the returned value has the accurate data in the location object. But the value in the database has not changed.

**Comment by davidcheung** [comment]
hi @devotox, hmm what database are u using, would you be able to try to run it with a debug statement eg `DEBUG=loopback:connector:mysql node .`(**or the correct connector you're using**) to see the query

or perhaps provide a sandbox on how to reproduce your problem?

**Comment by devotox** [comment]
I think this may be ok. I may be ok now. I may have either been using the wrong ACL or just this method was totally off. I have been able to make this work a different way using Remote Methods. Thank you anyway i will close now
