### ISSUE TITLE
isInRole can return an object instead of a boolean

### ISSUE THREAD

**Issue by loic-ps** [strongloop/loopback#2652]
Since release 2.30.0, isInRole() can return an object instead of the expected boolean (as documented).

The problem seems to have been detected by role unit test, but the tests have been corrected with an attached note. (see 48205fb2)

Note : All works fine with 2.29.1

thanks in advance.

**Comment by Tarabyte** [comment]
https://github.com/strongloop/loopback/blob/master/common/models/role.js#L359
https://github.com/strongloop/loopback/blob/master/common/models/role.js#L368 - сauses such a behaviour because `async.some` now returns anything
https://github.com/caolan/async/blob/master/lib/some.js#L35
