### ISSUE TITLE
Rename the Model used by HasAndBelongsToMany relation

### ISSUE THREAD

**Issue by upupzealot** [strongloop/loopback#2655]
Any way to do that?

**Comment by 0candy** [comment]
```
  "relations": {
    "parts": {
      "type": "hasAndBelongsToMany",
      "model": "Part"
    },
```
The model name in the relation cannot be renamed, however, since you refer to it by relation name, you can name the relation to what you want.

**Comment by upupzealot** [comment]
@0candy that's wierd, I has a model named 'topic' and another named 'topicColumn', that makes me a table named 'topictopicColumn'.
What if I have another two models called 'topicto' and 'picColumn'.
I think  there should be a way to name the middle model myself.
Would make it a 'feature'?

**Comment by 0candy** [comment]
Reopening this issue.

So you want to rename the relation table name? Would you like to submit a PR?
