### ISSUE TITLE
Using Authorization headers in the Client SDK

### ISSUE THREAD

**Issue by Industrial** [strongloop/loopback#2657]
Hi!

I am using the Browserified bundle for the loopback client SDK. The target platform is `React` and `Redux`.

The cookies are already being set after login and fetched on page (re)load. Right after getting the cookie, I make a request to fetch the user's profile (`/users/:id`), however I don't know where to set the `Authorization` header so I keep getting 401 errors on all requests except login.

**Comment by Industrial** [comment]
This happens when I have already used `User.login()` and after that refresh the page.

**Comment by davidcheung** [comment]
@Industrial so the cookie does receive the token? but it doesnt get appended to the request?
perhaps you could do something like 
>To use cookies for authentication, add the following to server.js (before boot):
`app.use(loopback.token({ model: app.models.accessToken }));`

See more details [at docs](https://docs.strongloop.com/display/public/LB/Making+authenticated+requests#Makingauthenticatedrequests-Makingauthenticatedrequestswithaccesstokens)

Or did you mean its not working for the browserified bundle only?

**Comment by Industrial** [comment]
@davidcheung: Thanks, i'll take a look at that.

**Comment by davidcheung** [comment]
@Industrial is this issue resolved, im closing this issue now, please reopen if you see fit.
