### ISSUE TITLE
Models change source directory

### ISSUE THREAD

**Issue by gpincheiraa** [strongloop/loopback#2659]
I need change the models folder structure. According to the docs I can modify the json config file that by default is:
```
    {
      "_meta": {
        "sources": [
          "loopback/common/models/**/*",
          "loopback/server/models/**/*",
          "../common/models",
          "./models"
        ],
        "mixins": [
          "loopback/common/mixins",
          "loopback/server/mixins",
          "../common/mixins",
          "./mixins"
        ]
      },
    
      ...
    }
```
I've been trying to change to:
```
    {
      "_meta": {
        "sources": [
          "loopback/common/models/**/",
          "loopback/server/models/**/*",
          "../common/models",
          "./models"
        ],
        "mixins": [
          "loopback/common/mixins",
          "loopback/server/mixins",
          "../common/mixins",
          "./mixins"
        ]
      },
    
      ...
    }
```
But when I load the project, i get this error

    > Error: Model not found:

**How to change the models default directory for models??**

**Comment by davidcheung** [comment]
@gpincheiraa I don't think we had wildcards(`**/*`) in the default template [code](https://github.com/strongloop/loopback-workspace/blob/a6fca1ca5556f3ecf123258a10633ebaded9f5e5/templates/projects/empty-server/data.js#L46-L62)

i have been able to use other folders as follow 
```json
{
  "_meta": {
    "sources": [
      "loopback/common/models/",
      "loopback/server/models",
      "../common/models",
      "../common/models/randomfolder",
      "./models",
      "../outsiders"
    ],
```
to store my model.js in `my-application/outsiders`, hope this solves your problem. Assuming this is a question, I'm closing the issue, if you feel like theres a bug there please [file a bug report](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report). Thanks

**Comment by gvsdan** [comment]
there any update on this ?

**Comment by davidcheung** [comment]
@gvsdan the config-loader will look for folders in the "sources" to try to resolve the `model.js/model.json` do you also have issues with it not finding the models? i wasnt able to reproduce that it not resolving models files that exist, can you [fork a sandbox](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) to demonstrate the problem?
