### ISSUE TITLE
rest middleware calls deprecated context method

### ISSUE THREAD

**Issue by azatoth** [strongloop/loopback#2663]
in https://github.com/strongloop/loopback/blob/2.x/server/middleware/rest.js#L60 there is a call to loopback.context which is now deprecated.

cc @bajtos

**Comment by bajtos** [comment]
I am afraid this is necessary in order to preserve backwards-compatibility for applications relying on this feature.

I am advising to disable the built-in context middleware in `server/config.json`:

```json
{
  "remoting": {
    "context": false
  }
}
```

**Comment by bajtos** [comment]
I added a section to our documentation explaining how to get rid of that deprecation warning.

See https://docs.strongloop.com/display/APIC/Using+current+context#Usingcurrentcontext-Fixingdeprecationwarnings

@crandmck could you PTAL at the added text and edit/improve it as needed?

**Comment by crandmck** [comment]
I made some small edits/clarifications.  It seems pretty straightforward.
