### ISSUE TITLE
loopback high CPU and high bandwith traffic to mongoDB

### ISSUE THREAD

**Issue by sirmadboy** [strongloop/loopback#2672]
hi, currently i'm having an issue with loopback and mongodb database. there are two problems that i want to ask:
1. my loopback service consuming high CPU, almost 100% everytime even when idle. it make my app run really slow when retrieving data. I already apply cluster on my server but it doesn't help, every process consuming 100% cpu on each core. is there any way to lower cpu process?
2. the traffic between loopback service and mongodb server is high, around 1,5-2 mb/s each process even when idle. so assuming when i set my service into 4 clusters, it will use around 6 -8mb/s bandwith. is it normal?

I'm running loopback and mongodb on separated server on google cloud engine. my strongloop version is 6.0.1 and node version 6.4.0. thanks

**Comment by davidcheung** [comment]
Hi @sirmadboy , I haven't ran into this issue before, 

- have you tried running your application on a different machine? does the issue still persist when ran on a different machine? 

- or run a different [sample app](https://github.com/strongloop/loopback-example-database) on your machine to see if still has the same issue?
  - to see on idle does it still use up 100% cpu?

- And how much processing power and ram do these nodes have?

cc @superkhau

**Comment by sirmadboy** [comment]
Hi @davidcheung, thank you for your response.
I already did all your suggestions, but it still the same. :(
Recently I did DEBUG=*, and what I found is my loopback do rectifyAllChange every 30 seconds. I also tried clone from [https://github.com/strongloop/loopback-example-offline-sync](url), and it also does the same behaviour. I think it makes my server drain a lot of CPU usages and high traffic. Is there any way to increase the interval or maybe eliminate it? Or maybe do you have another solution?
Thanks.

**Comment by davidcheung** [comment]
maybe related: https://github.com/strongloop/loopback/issues/2794

**Comment by davidcheung** [comment]
adding info to this
https://github.com/strongloop/loopback/blob/a0bc2041599343d7a1b95f16fab466b3c583a900/lib/persisted-model.js#L1802-L1803 perhaps because `createChangeHandlers` will sometimes become immortal?

**Comment by sirmadboy** [comment]
what is the purpose of this function https://github.com/strongloop/loopback/blob/a0bc2041599343d7a1b95f16fab466b3c583a900/lib/persisted-model.js#L1610 ? 
from https://github.com/strongloop/loopback/blob/a0bc2041599343d7a1b95f16fab466b3c583a900/lib/persisted-model.js#L1587, I can see that `cleanupInterval` is set either `Model.settings.changeCleanupInterval` or 30 seconds. but right now I have no idea how to increase `cleanupInterval` except by hardcoding it. because it makes my server CPU runs so high if it always calls `rectifyAllChanges` for every 30 seconds.

**Comment by mrjrdnthms** [comment]
I also am running into this issue using the MYSQL data connector. As the number of changes in the change tables grows the cleanup function slows way down. Examining mysql it looks like 1000+ queries are being run every 30 secs with this default. 

I disabled the cleanup function by setting changeCleanupInterval to -1 in all my change tracked model config json files. What does the cleanup function do? Why does it need to be run periodically? Can I optimize the queries it makes by adding indexes to the columns of the change tables? If so which columns need indexes?

**Comment by sirmadboy** [comment]
@mrjrdnthms where do I need to put changeCleanupInterval on my model config json file. for example I have this model.json file:
``` json
{
  "name": "employee",
  "base": "PersistedModel",
  "trackChanges": true,
  "properties": {
	"id": {
	  "type": "string",
      "id": true,
	  "defaultFn": "guid"
    },
    "employee_name": {
      "type": "string"
    },
    "employee_address": {
      "type": "string"
    },
	"employee_username": {
      "type": "string"
    },
    "employee_pin": {
      "type": "string"
    },
	"completed": {
      "type": "boolean",
      "default": false
    },
    "created": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

**Comment by mrjrdnthms** [comment]
@sirmadboy You put it at the root of the json file. I would also recommend adding replaceOnPUT, forceId, persistUndefinedAsNull as I ran into other issues without those properties set. Keep in mind I'm using mysql on server and sqlite on clients.

So your model would be:
`{
  "name": "employee",
  "base": "PersistedModel",
  "trackChanges": true,
  "properties": {
	"id": {
	  "type": "string",
      "id": true,
	  "defaultFn": "guid"
    },
    "employee_name": {
      "type": "string"
    },
    "employee_address": {
      "type": "string"
    },
	"employee_username": {
      "type": "string"
    },
    "employee_pin": {
      "type": "string"
    },
	"completed": {
      "type": "boolean",
      "default": false
    },
    "created": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": [],
  "forceId": false,
  "persistUndefinedAsNull": true,
  "changeCleanupInterval": -1
}`

**Comment by sirmadboy** [comment]
@mrjrdnthms thank you for your response. after adding changeCleanupInterval to -1 in all my change tracked model and updating loopback to latest version, it solved my problem and now my loopback doesn't fire cleanup function every 30 sec.
