### ISSUE TITLE
Finding associated models for HasAndBelongsToMany ignoring the "order" filter param

### ISSUE THREAD

**Issue by sundeepgupta** [strongloop/loopback#2677]
```javascript
Account.prototype.consideratesForSummary = function() {
    const filter = {
      include: ['sender', 'room'],
      order: 'utcSeconds ASC' 
    };

    return this.receiveConsiderates(filter);
  };
```

In the example the `Account` model has a `HasAndBelongsToMany` relationship named `receiveConsiderates`. When specifying the `order` of the `receiveConsiderates`, it is ignored.

**Comment by davidcheung** [comment]
related https://github.com/strongloop/loopback-datasource-juggler/issues/166

**Comment by jannyHou** [comment]
Confirmed this is a duplicate bug of https://github.com/strongloop/loopback-datasource-juggler/issues/166

@sundeepgupta I am on fixing it, to keep issues clean and easy to track, I will update my status in issue https://github.com/strongloop/loopback-datasource-juggler/issues/166, and you can also join the discussion there. 
A workaround if you need it: https://github.com/strongloop/loopback-datasource-juggler/issues/166#issuecomment-213163882


Closing this issue now, thanks for understanding.
