### ISSUE TITLE
Docs are showing Internal Server Error

### ISSUE THREAD

**Issue by alihalabyah** [strongloop/loopback#2683]
You have an Internal Server Error error on the below link:

http://apidocs.strongloop.com/loopback-sdk-angular/#loopbackresourceprovider

**Comment by davidcheung** [comment]
@alihalabyah thanks for bringing this up, it has been fixed on the website side, and also have an issue here to track this issue now https://github.com/strongloop/loopback-sdk-angular/pull/237

Closing this issue since doc is back up now, thanks!
