### ISSUE TITLE
How to setup models with the PostgreSQL(using json、array as column data type)  

### ISSUE THREAD

**Issue by realdog** [strongloop/loopback#269]
I am using prostgresql connector, my table structure is as follows:

CREATE TABLE  tableX
(
  id serial NOT NULL, 
  g_c1 text, 
  g_c2 integer[],
  g_c3 json
  CONSTRAINT pk_tablex PRIMARY KEY (id)
)

How to setup the models?
@raymondfeng  老兄你好，我在使用postgresql  connector。但是发现这里能设置的基本数据只有7中，但是我里面要使用text，json，array三种数据类型作为字段数据类型。我发现String类型可以映射Text类型的字段，但是如果我放置的内容比较大，CHARACTER  和 CHARACTER VARYING都不能容纳的时候，字段难道会自动变成Text类型？另外我实在是找不到json，array两种数据的映射方式，请指教

**Comment by ezraroi** [comment]
What is the map for Loopback Array type?

**Comment by kreegr** [comment]
+1 Array?
