### ISSUE TITLE
Translate loopback documentation for the Portuguese

### ISSUE THREAD

**Issue by dejaneves** [strongloop/loopback#2700]
I want to contribute to the translation of the loopback documentation for the Portuguese,  what do I do?

**Comment by davidcheung** [comment]
@crandmck ^ please advice

**Comment by crandmck** [comment]
Hi @dejaneves Thanks for offering to help!

We're in the mid-final stages of migrating the LoopBack documentation to GitHub (markdown/Jekyll) from Confluence.  Once that is "done", then we can start accepting translation PRs.  See https://github.com/strongloop/loopback.io/issues/29 and https://github.com/strongloop/loopback.io/wiki for details.

I expect it will be a few weeks before we can really accept translation PRs, but once the infrastructure is in place, it should be relatively simple, and we _definitely_ such contributions!

See https://github.com/strongloop/loopback.io/issues/37 for more information on doc translation/localization.

**Comment by crandmck** [comment]
Closed in favor of https://github.com/strongloop/loopback.io/issues/38.
