### ISSUE TITLE
Is there a way to import more than 1000 instances at once?

### ISSUE THREAD

**Issue by germanamz** [strongloop/loopback#2701]
Im trying to create 1700 instance of a model with:

`Model.create([instances...], function () {});`

but this is taking a long time.

is there a way to import them more efficiently? or a need to import them with the connector?

**Comment by superkhau** [comment]
See https://docs.strongloop.com/display/public/LB/Creating+a+database+schema+from+models. For future reference, please ask questions on Google Groups, Gitter etc. See https://github.com/strongloop/loopback/wiki/Questions more for details.

**Comment by raymondfeng** [comment]
@superkhau You probably misunderstood the question as the doc link is not relavant. But for questions, it's better posted to Google Group.

**Comment by superkhau** [comment]
@raymondfeng You're right, I misread the question. It is still better suited for answering on Google groups as you said.

@germanamz What connector are you using out of curiosity? I don't believe we support bulk create (only bulk update) -- https://docs.strongloop.com/display/APIC/Creating,+updating,+and+deleting+data#Creating,updating,anddeletingdata-Creatingdata%28modelinstances%29. @raymondfeng Do you have an alternative suggestion?

**Comment by germanamz** [comment]
@superkhau im using mongo

**Comment by superkhau** [comment]
I'm curious to see how much of that is internal LoopBack code versus say another driver (say mongoose). Unfortunately, I do not have the bandwidth at the moment to run benchmarks against third party drivers. That said, you can run the code in https://github.com/strongloop/loopback-connector-mongodb/tree/master/benchmarks and get a feel for performance on your machine.
