### ISSUE TITLE
cannot PATH FK to null, keeps becoming EMPTY_STRING in ajax

### ISSUE THREAD

**Issue by benjaminhon** [strongloop/loopback#2705]
when i do a REST ajax call

```
updateBedSlot: (bedSlot) -> (dispatch) ->
    Promise.resolve(
      $.ajax
        type: "PATCH"
        data: bedSlot
        url:  "#{apiUrl}/BedSlots"
    )

// where bedSlot is
bedslot = {
 name: "BED1"
 patientId: null
}
```

but in the database the FK for patientId is "" instead of null.
anyone know why this is happening?

thanks

**Comment by jannyHou** [comment]
@benjaminhon I am trying to reproduce your issue, for a better debug, please fork sandbox and replace with your code: https://github.com/strongloop/loopback-sandbox
Thanks!  And please also include which database you are using.

**Comment by jannyHou** [comment]
hi @benjaminhon any update?

**Comment by benjaminhon** [comment]
Sry i think its a problem on my side. It should be resolved

**Comment by jannyHou** [comment]
@benjaminhon no problem :) Glad to know that you solved the issue. I am closing it here, feel free to reopen it if you have other questions.
