### ISSUE TITLE
ACL - Exposing model attributes to different roles

### ISSUE THREAD

**Issue by coen-hyde** [strongloop/loopback#2708]
Hi,

I can't see anywhere in the documentation on how to restrict/expose access to certain model attributes on a per role basis. I want an admin role who can read and write more attributes than other roles. In addition I would like to expose some of those attributes to other roles but not allow them to update those attributes. Is this possible with Loopback? And if not, do you have any suggestions how best to implement this?

Thanks,
Coen

**Comment by jannyHou** [comment]
hey @coen-hyde we are using google group for questions and github to keep track of bugs/features, please follow the rule in https://github.com/strongloop/loopback/wiki/Questions

And for your question, I believe you are looking for [DOC: How to define and use role in loopback](https://docs.strongloop.com/display/public/LB/Defining+and+using+roles), you can define your custom role to control the access on certain attributes.

I am closing issue here, if you are still confused please post it in google group and mention me there(name: Janny Hou, email: JannyHou2015@gmail.com) to have further discussion :-)
Thanks for understanding.

**Comment by yagobski** [comment]
+1

**Comment by coen-hyde** [comment]
@yagobski no. I just I didn't use strong loop.

**Comment by jannyHou** [comment]
Hi @coen-hyde apologize first, I misunderstood your question, I thought you didn't find the doc for how to use a role in loopback so I just post the link, and I didn't realize that a custom role is not the right place to filter the attributes.

Back to your question, now ACL are only applied on methods, but not properties.

As a workaround, I think you can filter attributes according to the roles in 2 steps:
1. Define your role but don't add restriction in your role function, eg: 
  - admin 
  - lead
  - member

2. Do the property filter in remote hook:
  We have an example shows how to hide password with afterRemote hook: https://docs.strongloop.com/display/public/LB/Remote+hooks#Remotehooks-Examples

I think you can check a user's role in the hook then filter properties accordingly.

Further discussion are welcomed if you still run into problem. And sorry again for not answering in time.
