### ISSUE TITLE
Promisify relation/scope methods in juggler

### ISSUE THREAD

**Issue by sundeepgupta** [strongloop/loopback#2709]
If I define a model with a custom scope like this:

``` json
  "scopes": {
    "active": {
      "where": {
          "status": "active"
      }
    }
  }
```

When I call it from client code `MyModel.active()`, this does not return a promise, it requires a callback argument.

**Comment by jannyHou** [comment]
@sundeepgupta the scope functions are not promisified yet. I will label this issue as a feature to keep track of the promisify status of relation/scope methods in juggler. Thanks for bringing it up.
And here is a placeholder shows what apis we already promisified: https://github.com/strongloop/loopback/issues/418

**Comment by sundeepgupta** [comment]
thanks @jannyHou
