### ISSUE TITLE
Fields clashing with Include

### ISSUE THREAD

**Issue by benjaminhon** [strongloop/loopback#2710]
When i do a query such as follows:

```
Node.find({
  include: {
    relation: 'device',
    scope: {
      fields: ['type', 'id'],
      include: {
        relation: 'locations',
        scope: {
          fields: ['lng', 'lat'],
          include: {
            relation: 'map',
            scope: {
              fields: ['name']
            }
          }
        }
      }
    }
  }
});
```
When i have the line **fields: ['lng', 'lat']**, then the relation *map*will not be included, however if i remove the **fields: ['lng', 'lat']**, then **map** is included again. 

in my relations:

Location belongsTo Map
Map hasMany Location

I think this is a Bug

**Comment by raymondfeng** [comment]
For relations, the id needs to be included.

**Comment by benjaminhon** [comment]
hmm

```
fields: ['lat', 'lng', 'mapId']
```

seems to work, thanks.
