### ISSUE TITLE
Calling a hidden endpoint returns 401 instead of 404(GET api/MyModels/change-stream )

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback#2711]
```
MyModel.disableRemoteMethod('createChangeStream', true);
```

Hides `POST api/MyModels/change-stream`, but is not hiding `GET api/MyModels/change-stream` anymore.

This is either a [documentation](https://docs.strongloop.com/display/public/LB/Exposing+models+over+REST#ExposingmodelsoverREST-Read-Onlyendpointsexample) issue, or some breaking change was introduced inadvertently.

See my test to highlight the issue

```
  // FAIL
  it.serial.cb('Doesnt expose GET change-stream', function(t){
    request(app)
      .get('/api/Clients/change-stream')
      .expect(404, function(err, res){
        t.end(err);
      });
  });

  // PASS
  it.serial.cb('Doesnt expose POST change-stream', function(t){
    request(app)
      .post('/api/Clients/change-stream')
      .expect(404, function(err, res){
        t.end(err);
      });
  });
```

This is happening with loopback 2.31

```
├─┬ loopback@2.31.0
│ ├── async@2.0.1
│ ├── bcryptjs@2.3.0
│ ├─┬ body-parser@1.15.2
```

EDIT: This is happening only on models deriving from User

**Comment by jannyHou** [comment]
@Overdrivr It seems hidden on my side:
I created a custom User model called `Myuser`:
My file `common/models/myuser.js`
```
'use strict';

module.exports = function(Myuser) {
  Myuser.disableRemoteMethod('createChangeStream', true);    // removes (GET|POST) /products/change-stream
};

```
And see pic below, both POST and GET are hidden.

I am using template `notes` when creating app and my strongloop version of 6.0.2. Could you try update your strongloop and create a new app to see if it's still there? If it still doesn't work please mention which template you choose. Thanks!

![screen shot 2016-09-08 at 4 12 23 pm](https://cloud.githubusercontent.com/assets/12554153/18365066/18209356-75df-11e6-8ca4-e9c149114d3f.png)

**Comment by Overdrivr** [comment]
I am using stongloop 6.0.1, I created the project with the blank template.

Actually, I didn't check before the explorer but now I noticed that the method is indeed hidden in the explorer, but doesnt return 404 anyway (it returns 401). 

@jannyHou  Does this makes sense to you ?

**Comment by jannyHou** [comment]
Thank you @Overdrivr good catch. I think it should be 404.

**Comment by Overdrivr** [comment]
@jannyHou This issue should not be closed, I'm willing to PR a test to confirm it. Let me know if you're interested, cheers

**Comment by jannyHou** [comment]
Hi @Overdrivr ok let me reopen it, and if this is still a bug in loopback@3.x, would you be interested in creating a PR to fix the issue? Thanks!

**Comment by Overdrivr** [comment]
Sure, no problem I can submit a PR. I'll keep you posted

**Comment by Overdrivr** [comment]
I didn't find the time to work on this yet, I will try next month

**Comment by dhmlau** [comment]
Marking it as `help wanted` as @Overdrivr is interested to submit a PR.

**Comment by Overdrivr** [comment]
I'm on it, next week
