### ISSUE TITLE
Installation Failure on Mac OS X

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2723]
_From @steveatkin on September 3, 2016 12:20_

Loopback connector fails to install on Mac. See screen shot.
<img width="872" alt="screen shot 2016-09-03 at 8 19 27 am" src="https://cloud.githubusercontent.com/assets/5531596/18224789/2e178e46-71af-11e6-8d4e-7eae7f99e93c.png">

_Copied from original issue: strongloop/loopback-connector-db2z#3_

**Comment by superkhau** [comment]
@steveatkin Moved your issue to this repo for tracking because I closed off the issues tab at loopback-connector-db2z.

**Comment by leocvidal** [comment]
I am having exactly the same issues when installing DB2 Loopback connector on MacOS:
![image](https://user-images.githubusercontent.com/23372208/30352461-5035e7bc-9863-11e7-98e7-52e9546fee35.png)
