### ISSUE TITLE
Strongloop issue while creating application

### ISSUE THREAD

**Issue by sumedhbhagat** [strongloop/loopback#2725]
Hello Team, I have installed Node.js, NPM and Loopback with below version. 

Node.js -->4.4.4
npm   ---->3.10.6
Strongloop -->
strongloop v6.0.2 (node v4.4.4)
├── strong-arc@1.8.8 (fb756f2)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.2.3
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.0.4 (de9885e)
├── generator-loopback@1.24.1 (7791985)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

![untitled](https://cloud.githubusercontent.com/assets/22011529/18307793/8894641c-750f-11e6-96a3-2b36385307e6.png)

Now I am trying to create the application but getting below error.

? What's the name of your application? newappr
? Enter name of the directory to contain the project: newappr
   create newappr/
     info change the working directory to newappr

? Which version of LoopBack would you like to use? 2.x (stable)
? What kind of application do you have in mind? hello-world (A project containing a controller, including a single vanilla Mes
sage and a single remote method)
**Trace: options is not being passed**
    at Function.find (C:\Users\dell\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-datasource-juggl
er\lib\dao.js:1971:17)
    at Function.Workspace.isValidDir (C:\Users\dell\AppData\Roaming\npm\node_modules\strongloop\node_modules\loopback-
workspace\common\models\workspace.js:457:13)
    at module.exports.yeoman.Base.extend.detectExistingProject (C:\Users\dell\AppData\Roaming\npm\node_modules\strongl
oop\node_modules\generator-loopback\app\index.js:200:15)
    at Object.<anonymous> (C:\Users\dell\AppData\Roaming\npm\node_modules\strongloop\node_modules\yeoman-generator\lib
\base.js:431:23)
    at C:\Users\dell\AppData\Roaming\npm\node_modules\strongloop\node_modules\run-async\index.js:26:25
    at C:\Users\dell\AppData\Roaming\npm\node_modules\strongloop\node_modules\run-async\index.js:25:19
    at C:\Users\dell\AppData\Roaming\npm\node_modules\strongloop\node_modules\yeoman-generator\lib\base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)

I have tried with Node.js version 4.4.5 with  NPM (3.10.6) and Strongloop (6.0.2). But still the same error. 

I am running this command in blank directory with admin command prompt. Not understanding why it needs to go into dao.js to check if the directory is valid or not.

Thanks

**Comment by jannyHou** [comment]
@sumedhbhagat I am trying to reproduce your problem but mine works fine:
```
? What's the name of your application? anewapp
? Enter name of the directory to contain the project: anewapp
   create anewapp/
     info change the working directory to anewapp

? Which version of LoopBack would you like to use? 2.x (stable)
? What kind of application do you have in mind? hello-world (A project containin
g a controller, including a single vanilla Message and a single remote method)
Generating .yo-rc.json


I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.
```

My config:
```
jannyhous-mbp:triage jannyhou$ node -v
v4.4.7
jannyhous-mbp:triage jannyhou$ npm -v
3.10.3

strongloop: 6.0.2
```

And I haven't seen a "Trace: options is not being passed" error before.
It goes into `dao.js` because when you use generator to create an app, it actually calls some function in [loopback-workspace](https://github.com/strongloop/loopback-workspace) to check whether the app folder is valid:
https://github.com/strongloop/loopback-workspace/blob/master/common/models/workspace.js#L457
And since loopback-workspace itself is a loopback app, `workspace` is a model in it, it will call method in `dao.js` to do CRUD operations.

Back to your problem, could you double check your working dir? Seems the directory is invalid, if you still run into this issue please try to update strongloop. Good luck!

**Comment by sumedhbhagat** [comment]
Hey JannyHou .. Thanks for replying. I was installing the strong loop package by using my company proxy. When I removed the proxy and installed the strong loop at my home, it worked. I was able to create the application.
