### ISSUE TITLE
Community contributions to keep mantaining deprecated current context feature

### ISSUE THREAD

**Issue by josieusa** [strongloop/loopback#2728]
As suggested by @bajtos in issue 1495 I'm opening a new issue for discussing the solutions which are _not_ alternative to the deprecated [current context](https://docs.strongloop.com/display/public/LB/Using+current+context) feature; that is, solutions that try to _fix_ or help with current context issues (e.g. lost context) and **not** to replace the current context feature with a similar one; for the latter kind of solutions (alternatives), please keep using issue 1495. Even if the approaches we are going to discuss here will be unofficial, I think that many people have an existing app that they don't want to refactor too heavily in order to address these issues, and therefore may be interested in trying this approach.

~This is my attempt to fix it. Please read its [README](https://github.com/josieusa/loopback-context/blob/bf874aa3376b3edc4a6ee64d93855e7420bc71c3/README.md) before trying it, because it includes a lot of info.~
~[loopback-context PR #2](https://github.com/strongloop/loopback-context/pull/2)~
~Important, I don't use it alone; I'm using it in combination with the `npm shrinkwrap`approach suggested in issue 1495 which is not perfect because it has the downside that you must be "lucky" to not get a broken install (seemingly) randomly, and it's not easy to notice at all. But once I got a working install, it's been all fine so far. Don't take this as an expert advice, it's just my own experience with it.~

~I didn't call my pull request production-ready because tests are not published, but I have some high quality tests, so its quality is better than average.~
~Maybe I'm going to gradually try it in production soon, but until then, I don't take the responsibility to recommend using it in production to anyone yet.~ OBSOLETE PR

Any Loopback users interested in further discussion of these kinds of approaches to the context issues? 
Thank you

**Comment by josieusa** [comment]
Just wanted to add (loopback-context PR #10)[https://github.com/strongloop/loopback-context/pull/10]

**Comment by josieusa** [comment]
To people watching the issue #1495, I'd like to inform that the PR is no longer a work-in-progress. It works for me. For details see the PR.

**Comment by bajtos** [comment]
https://github.com/strongloop/loopback-context/pull/11 has been landed and a new version `loopback-context@3.0.0` has been released.

I am closing this issue as done. Please open a new issue in loopback-context project if there is anything else remaining to discuss.
