### ISSUE TITLE
Shared class  \"Seller\" has no method handling POST... 

### ISSUE THREAD

**Issue by volkanozyilmaz** [strongloop/loopback#2732]
I'm getting this error when I logged in with $owner but when I logged in different user, admin (I've created it this ROLE), I can call the remote method. Seller is my User model. 

Here's my error. 

{
  "error": {
    "name": "Error",
    "status": 404,
    "message": "Shared class  \"Seller\" has no method handling POST /%7Bid%7D/licenses/take-one?access_token=9sV73DfuEuhWxQYWCzv7jGPWRBf3ExekxXU3jAioYHLzgpArNDSk3e4ngetNHuoP",
    "statusCode": 404,
    "stack": "Error: Shared class  \"Seller\" has no method handling POST /%7Bid%7D/licenses/take-one?access_token=9sV73DfuEuhWxQYWCzv7jGPWRBf3ExekxXU3jAioYHLzgpArNDSk3e4ngetNHuoP\n    at restRemoteMethodNotFound (/Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/strong-remoting/lib/rest-adapter.js:336:17)\n    at Layer.handle [as handle_request](/Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)\n    at /Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/express/lib/router/index.js:280:7\n    at Function.process_params (/Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/express/lib/router/index.js:330:12)\n    at next (/Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/express/lib/router/index.js:271:10)\n    at Function.handle (/Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/express/lib/router/index.js:176:3)\n    at router (/Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/express/lib/router/index.js:46:12)\n    at Layer.handle [as handle_request](/Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/Users/volkan/Sites/keyzy/node_modules/loopback/node_modules/express/lib/router/index.js:312:13)"
  }
}

**Comment by jannyHou** [comment]
> POST /%7Bid%7D/licenses/take-one?

From the path above I assume you are calling a relation endpoint, you have a relation like `Seller` hasMany `Licenses`.

I have to see your code for a better debug but I think our doc explains why you cannot access to it:
> If a model has a DENY ALL permission (for example a built-in model such as the User model), but related models have no ACLs, the related models will still not be accessible through the User model. So, for example, even if the books model's default ACL is ALLOW $authenticated for GET /books, the route GET /user/{id}/books default will still be DENY ALL.

And please check our doc [accessing related model](https://docs.strongloop.com/display/public/LB/Accessing+related+models) for more details.

If you still could not figure it out, please follow our process:https://github.com/strongloop/loopback/wiki/Questions to ask question and move discussion on google group, we only use github to keep track of bugs and features. Thanks for understanding!

You can close this issue and mention me (name: Janny Hou, email: JannyHou2015@gmail.com) on google group.

**Comment by volkanozyilmaz** [comment]
I changed all $everone, DENY to $everyone, ALLOW. Still, the admin can access it but $owner can't. Paste my ACL code. 

Seller
{
  "name": "Seller",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "licenses": {
      "type": "hasMany",
      "model": "License",
      "foreignKey": ""
    }
  },
  "acls": [
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "$everyone",
        "permission": "ALLOW"
      },
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "$authenticated",
        "permission": "ALLOW"
      },
      {
        "accessType": "READ",
        "principalType": "ROLE",
        "principalId": "$owner",
        "permission": "ALLOW",
        "property": "__get__licenses"
      },
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "$owner",
        "permission": "ALLOW",
        "property": "__updateById__sellers"
      }
  ],
  "methods": {}
}

License

{
  "name": "License",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "pre_text": {
      "type": "string"
    },
    "serial": {
      "type": "string",
      "required": true
    },
    "definer": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "sku": {
      "type": "belongsTo",
      "model": "Sku",
      "foreignKey": ""
    },
    "seller": {
      "type": "belongsTo",
      "model": "Seller",
      "foreignKey": ""
    }
  },
  "acls": [
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "$everyone",
        "permission": "ALLOW"
      },
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "$authenticated",
        "permission": "ALLOW"
      }
  ],
  "methods": {}
}


And I changed it like that, after that, the admin get Authorisation error and $owner has the same "No method handling" error. 

Seller
  "acls": [
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "$everyone",
        "permission": "ALLOW"
      }
  ],

License

  "acls": [
      {
        "accessType": "*",
        "principalType": "ROLE",
        "principalId": "$everyone",
        "permission": "ALLOW"
      }
  ],

**Comment by jannyHou** [comment]
@volkanozyilmaz Could you fork https://github.com/strongloop/loopback-sandbox and replace it with your code to reproduce the error? Thanks :) 
Your sample is not that easy to setup because I don't know how you define the owner, admin, etc..... It will save both your and my time to debug if I can have your code as well as the reproduce steps.
