### ISSUE TITLE
LoopBack Model code not work if in different path

### ISSUE THREAD

**Issue by ephillipe** [strongloop/loopback#2733]
My LoopBack model code not work if in different path.

My mode-config has tree folders with models:

```
"_meta": {
"sources": [
  "loopback/common/models",
  "loopback/server/models",
  "../common/models",
  "../../common/models",
  "./models"
],
"mixins": [
  "loopback/common/mixins",
  "loopback/server/mixins",
  "../common/mixins",
  "./mixins"
]
}
```

In "../../common/models" I want put my shared models. I will share the models across my micro-services. So the Logic (the code) I need put into micro-service project path.

Then I need .JSON stay in "../../common/models" and .JS stay in "../common/models" or "./models"

There are any way to do this?

**Comment by loay** [comment]
If I understand correctly, there should be no conflict if you call the right files with the right path. Unless, I missed something here, can you share a sample app with conflicting path?
Thanks.
