### ISSUE TITLE
Limit filter range like SQL command limit 5,10

### ISSUE THREAD

**Issue by yeddahsu** [strongloop/loopback#2734]
Dear all,

Does loopback support limit filter range? For example,

select * from tableA 
limit 5, 10

Thanks

**Comment by raymondfeng** [comment]
Yes. See:
- https://docs.strongloop.com/display/public/LB/Limit+filter
- https://docs.strongloop.com/display/public/LB/Skip+filter

Such directives will be translated to SQL limit or other ways for pagination.

**Comment by yeddahsu** [comment]
Yes. Thanks for your help!
