### ISSUE TITLE
if I don't want Response data which is post in,how to make it?

### ISSUE THREAD

**Issue by issmile** [strongloop/loopback#2735]
if I don't want Response data which is post in,how to make it?
as follow ,nothin happend,how to make right?

Item.observe('after save', function(ctx, next) {
  if (ctx.instance) {
    console.log('Saved %s#%s', ctx.Model.modelName, ctx.instance.id);
    console.log("ctx.instance",ctx.instance);
    ctx.instance={};
    console.log("ctx.instance",ctx.instance);
  } else {
    console.log('Updated %s matching %j',
      ctx.Model.pluralModelName,
      ctx.where);
  }
  next();
});

**Comment by jannyHou** [comment]
@issmile Sorry I am confused:
(1) What are you expecting to happen?
(2) Could you explain more about what's the meaning of `don't want Response data`? Like you don't expect it show up or exist in which place?

Thanks!

**Comment by issmile** [comment]
I don't want show up,but I have allready fix it ,thanks

**Comment by jannyHou** [comment]
@issmile Glad to know you fixed it!!
