### ISSUE TITLE
slc command not found in terminal

### ISSUE THREAD

**Issue by carter3689** [strongloop/loopback#2737]
Hello, 

I recently installed loopback for a project and tried to follow the instructions on the docs but did not have any luck running "slc loopback".

My osX path is : `/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin`

My node path is: `/usr/local/bin/node`
My npm path is : `/usr/local/bin/npm`

and the output from the `npm ls -g --depth=0` command is: 
```
/Users/joelcarter/.npm-packages/lib
├── bower@1.7.9
├── generator-angular-fullstack@4.0.1
├── generator-keystone@0.4.2
├── generator-keystonejs-builder@0.0.5
├── generator-loopback@1.24.1
├── generator-wordpress@2.0.2
├── grunt-cli@1.2.0
├── gulp@3.9.1
├── gulp-cli@1.2.2
├── johnny-five@0.9.61
├── loopback@2.34.0
├── loopback-datasource-juggler@2.51.0
├── mean-cli@0.12.10
├── nodemon@1.9.2
├── particle-cli@1.15.0
├── particle-io@0.12.0
├── semver@5.3.0
├── strongloop@6.0.2
├── webpack@1.13.1
├── webpack-dev-server@1.14.1
└── yo@1.8.4
```
Yet I keep getting a `-bash: slc: command not found` error.

Any help would be greatly appreciated.

Thanks

**Comment by jannyHou** [comment]
@carter3689 Are you able to find `slc` in `/usr/local/bin/`?

**Comment by carter3689** [comment]
@jannyHou Hey thanks for responding. No, unfortunately I didn't.

**Comment by jannyHou** [comment]
@carter3689 ideally slc should installed with strongloop together if you run `npm install -g strongloop`
Could you give me the node and npm version you are using?

And I suggest you reinstall node using instruction http://blog.teamtreehouse.com/install-node-js-npm-mac

If it still doesn't work please update here. Good luck!

**Comment by carter3689** [comment]
@jannyHou The Node version I am using is v4.5.0 
The Npm version I am using is 2.15.9

I'll try the instruction you provided and update on the status soon. Thanks

**Comment by jannyHou** [comment]
@carter3689 Sounds good. If you still don't have slc in `/usr/local/bin/` after reinstall node & strongloop globally, please try to paste your installation log here, it might give us some clue about why slc installation fails.

BTW, my npm modules are installed in `/usr/local/lib` by default, so maybe try don't use a custom npm path.
```
dc60server:loopback-sandbox jannyhou$ npm ls -g --depth=0
/usr/local/lib
├── apiconnect@2.2.16
├── generator@1.0.1
├── generator-loopback@1.24.0
├── grunt@1.0.1
├── loopback@3.0.0-alpha.3 -> /Users/jannyhou/lb/lb-project/loopback
├── loopback-connector-oracle@3.0.1
├── mocha@2.5.3
├── node-inspector@0.12.8
├── npm@3.10.3
├── npm3@1.1.0
├── strong-globalize@2.5.7
├── strongloop@6.0.2
└── tap@6.3.2
```

**Comment by jannyHou** [comment]
And please make sure you followed installation on macOS, like give folders permission, etc...:
https://docs.strongloop.com/display/SL/Installing+on+MacOS

**Comment by carter3689** [comment]
I reinstalled Node using homebrew but I received an error saying `Warning: node-6.5.0 already installed, it's just not linked` Also, regarding the custom npm path, is there a way to reset the path of npm? 

I've also followed the installation docs for folder permissions multiple times with no luck.

**Comment by jannyHou** [comment]
Interesting, seems your node and npm are not working well..... I am not a installation expert TBH lol, 
try what google says? 
https://www.google.ca/?client=safari#q=uninstall+node+mac&gfe_rd=cr

uninstall node then reinstall it.

**Comment by carter3689** [comment]
Hey Good news!! It works!!
<img width="570" alt="screen shot 2016-09-12 at 3 04 41 pm" src="https://cloud.githubusercontent.com/assets/9578509/18450865/621a139c-78fa-11e6-9c75-af19f9a8cb10.png">

I found some helpful links that helped reset my npm path that may be of help to others.
http://stackoverflow.com/questions/20934343/how-to-restore-reset-npm-configuration-to-default-values

Then I reinstalled loopback, after following the file permission tutorial again and like magic...IT WORKS!! :) 👍

**Comment by jannyHou** [comment]
@carter3689 Good Job! Thank you and Cheers 👍 

Then I am closing this issue since it's fixed. Good to know that **NPM path** is critical to install strongloop! 

My guess is maybe your custom path didn't have enough permission (you only set permission for default one but actually modules are not installed there)?

**Comment by superkhau** [comment]
@jannyHou I assume you mean to close this as fixed? Closing for you. ;)

**Comment by youngtk96** [comment]
I know this post is old but this solution did not fix my issue. **_What i did to resolve this issue is_** to make sure you are running power shell or Git Bash as an administrator. If you are on Ubuntu make sure you run SUDO
