### ISSUE TITLE
How to update device with unique field?

### ISSUE THREAD

**Issue by penguinpowernz** [strongloop/loopback#2739]
Any time I try to do a put request to my model that has this:

``` js
module.exports = function(Device) {
  Device.validatesUniquenessOf('address', {message: 'address is not unique'});
}
```

It will fail with a 422 saying: `ValidationError: The`device`instance is not valid. Details:`address`address is not unique (value: "N0")`.  Even if I haven't specified the address field in the request.

As you can see in this excerpt from the model file, the validations are empty and I have removed the `unique: true` from the address property.

``` json
{
  "name": "device",
  "description": "Models a sensor device",
  "plural": "devices",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "address": {
      "type": "string",
      "required": true,
      "index": true
    }
  },
  "validations": []
}
```

Annoying this is if I remove that validation function I get this error: `TypeError: Cannot read property 'constructor' of null`

What am I doing wrong?

**Comment by manojchandrashekar** [comment]
Which datasource are you using?

In my experience (MongoDB), just removing the `unique: true` property does not remove the index that was created on your collection when you put in the unique constraint.

I've always had to manually drop the index from the database.

**Comment by penguinpowernz** [comment]
I'm using the Redis datasource.  I have flushed the DB but it's still causing problems.

**Comment by penguinpowernz** [comment]
Hmmm.. those other errors (`TypeError: Cannot read property 'constructor' of null`) seem to only happen when running tests with mocha.

**Comment by loay** [comment]
Hi @penguinpowernz 
Can you provide a test project with steps to reproduce so I can have a look?
Thanks.
