### ISSUE TITLE
Different versions of documentation?

### ISSUE THREAD

**Issue by manojchandrashekar** [strongloop/loopback#2741]
Are these documentation sources different in content or is it just duplication?

1. http://loopback.io/doc/en/lb2/index.html
2. https://docs.strongloop.com/

**Comment by superkhau** [comment]
@manojchandrashekar New docs website is coming soon, wait for the blog announcement. ;)

**Comment by superkhau** [comment]
cc @crandmck

**Comment by crandmck** [comment]
@manojchandrashekar See http://loopback.io/doc/index.html for more background.  Once we launch the new site, of course we'll mark the old site (docs.strongloop.com) as deprecated, and probably add redirects to the new site.

**Comment by manojchandrashekar** [comment]
@crandmck @superkhau - Thank you! Yes, that definitely makes it easier for the community to contribute to the documentation.
