### ISSUE TITLE
TypeError: Cannot read property 'constructor' of null

### ISSUE THREAD

**Issue by penguinpowernz** [strongloop/loopback#2744]
When I try to access a non existent model, I get this error instead of a 404.

What have I broken?  With a quick test app I get the 404 error but not on the API that I am developing.  I'm guessing it's some configuration option somewhere.

Here's my `middleware.json` file:

``` json
{
  "initial:before": {
    "loopback#favicon": {}
  },
  "initial": {
    "compression": {
      "enabled": false
    },
    "cors": {
      "params": {
        "origin": true,
        "credentials": true,
        "maxAge": 86400
      }
    }
  },
  "session": {},
  "auth": {},
  "parse": {},
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  },
  "files": {},
  "final": {
    "loopback#urlNotFound": {}
  },
  "final:after": {
    "loopback#errorHandler": {}
  }
}
```

Here's my `middleware.json` file:

``` json
{
  "initial:before": {
    "loopback#favicon": {}
  },
  "initial": {
    "compression": {
      "enabled": false
    },
    "cors": {
      "params": {
        "origin": true,
        "credentials": true,
        "maxAge": 86400
      }
    }
  },
  "session": {},
  "auth": {},
  "parse": {},
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  },
  "files": {},
  "final": {
    "loopback#urlNotFound": {}
  },
  "final:after": {
    "loopback#errorHandler": {}
  }
}
```

Here's my `config.json` file:

``` json
{
  "restApiRoot": "/api",
  "host": "0.0.0.0",
  "port": 9933,
  "remoting": {
    "context": {
      "enableHttpContext": false
    },
    "rest": {
      "normalizeHttpPath": false,
      "xml": false
    },
    "json": {
      "strict": false,
      "limit": "100kb"
    },
    "urlencoded": {
      "extended": true,
      "limit": "100kb"
    },
    "cors": false,
    "errorHandler": {
      "debug": true,
      "log": true
    }
  },
  "legacyExplorer": false
}
```

Any my `config.local.js` file:

``` js
module.exports = {
  restApiRoot: "/api/v0",
  host: process.env.HOST || 'localhost',
  port: process.env.PORT || 9933
}
```

What did I break?

**Comment by jannyHou** [comment]
@penguinpowernz Thank you for the code, for a better debug, could you fork https://github.com/strongloop/loopback-sandbox and replace it with your code? Thanks. 

And also please include the error you got if possible, or describe it here.

**Comment by penguinpowernz** [comment]
I mucked around and now I cannot reproduce this error in my own application.

I think this is a problem with `loopback-connector-redis`, I was able to fix a similar problem in that library with this pull request: strongloop/loopback-connector-redis/pull/25

However there should probably be some input validation between the connector and the `findById` to ensure that 404 errors are pushed out.

However it appears this entire issue was probably by me not validating my input (I was getting undefined `err` and `null` model from the `findById` callback).  So you can probably close this @jannyHou  sorry for the interruption.
