### ISSUE TITLE
beforeRemote/afterRemote does not pass promise to strong remoting

### ISSUE THREAD

**Issue by tvdstaaij** [strongloop/loopback#2747]
Originally reported in [this #418 comment](https://github.com/strongloop/loopback/issues/418#issuecomment-234722434), opened this as a separate issue because @bajtos [mentioned](https://github.com/strongloop/loopback/issues/418#issuecomment-247040099) that this is a rather specific loopback problem and requested a PR.

Summary: returning a promise from beforeRemote/afterRemote hangs the remote request because the returned promise is discarded in [this piece of code](https://github.com/strongloop/loopback/blob/6752dd3af3dd1ced800f4175317a786cedb3998e/lib/model.js#L193-L221).

I attempted to fix this by simply changing `fn(ctx, ctx.result, next);` to `return fn(ctx, ctx.result, next);`. This does indeed make the request go through when returning a promise in a remote hook. But it also causes another issue: after the first remote hook that returns a promise, no further remote hooks will be executed, as if they were not registered in the first place. To illustrate with a piece of code:

``` javascript
  User.beforeRemote('login', function(ctx, _, next) {
    console.log('OK 1/5'); // Shows
    next();
  });

  User.beforeRemote('login', function(ctx, _, next) {
    console.log('OK 2/5'); // Shows
    next();
  });

  User.beforeRemote('login', function() {
    console.log('OK 3/5'); // Shows
    return Promise.resolve();
  });

  User.beforeRemote('login', function() {
    console.log('OK 4/5'); // Does NOT show
    return Promise.resolve();
  });

  User.beforeRemote('login', function(ctx, _, next) {
    console.log('OK 5/5'); // Does NOT show
    next();
  });

 // Request returns 200 but the last two handlers were skipped.
```

I have no idea what could cause this side effect though.

**Comment by bajtos** [comment]
@tvdstaaij Could you please open a pull request with your implementation and add a unit-test for the problematic case? It will make it easier for me to troubleshoot what exactly is happening under the hood.

**Comment by bajtos** [comment]
Fixed by https://github.com/strongloop/loopback/pull/2820 and https://github.com/strongloop/loopback/pull/2822
