### ISSUE TITLE
What is the best way to develop OAuth server in loopback?

### ISSUE THREAD

**Issue by yahoohung** [strongloop/loopback#2749]
I am working on a new project and planned to use loopback for the REST API portal. As I know IBM stopped support on the strongloop gateway. https://docs.strongloop.com/display/LGW/Setting+up+the+API+Gateway

What is the best options to make loopback work with OAuth server at this moment? Thanks.

**Comment by jannyHou** [comment]
@yahoohung we are using github to track features and bugs, but for questions we always keep them on google group, please follow our guide https://github.com/strongloop/loopback/wiki/Questions to ask questions :-) Thanks for understanding.

And @sam-github @ritch I think you are more familiar with gateway, any idea of "What is the best options to make loopback work with OAuth server at this moment? "? Thanks.
