### ISSUE TITLE
how to make right in get filter of RESTFUL?

### ISSUE THREAD

**Issue by issmile** [strongloop/loopback#2753]
I following the document,why it don't work ?how to make right 
![image](https://cloud.githubusercontent.com/assets/20268011/18593629/decb326e-7c6e-11e6-90f4-c7f0f796c15a.png)
![image](https://cloud.githubusercontent.com/assets/20268011/18593660/0c97c0a4-7c6f-11e6-9c6d-c966e6665e54.png)

**Comment by dancingshell** [comment]
@issmile you must wrap your query in an object and use json format try
`{ "limit": 5 } `

**Comment by issmile** [comment]
@dancingshell  but I want use it in explorer.I don't think they built explorer only for show?

**Comment by issmile** [comment]
@dancingshell thank you
