### ISSUE TITLE
Inq limit?

### ISSUE THREAD

**Issue by mcat-ee** [strongloop/loopback#2756]
Hi, in our office we've had some errors with queries involving _inq_ statements containing over 20 values.

To be clear, 20 or below values works fine. Anything over and the server appears to perform a weird transform of the array into a nonsensical object with no clear mappings to the inq array we passed in.

Has anybody else encountered this?

**Comment by superkhau** [comment]
Can you provide a sample for us to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by Amir-61** [comment]
As @superkhau suggested please reproduce the issue by our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox). Also please let us know what connector you are using?

Thanks!

**Comment by mcat-ee** [comment]
We use the following modules:

- "loopback": "2.26.0", 
- "loopback-boot": "^2.15.0",
- "loopback-component-explorer": "^2.1.0",
 - "loopback-component-migrate": latest
 - "loopback-connector": latest
 - "loopback-connector-mysql": latest
 -"loopback-connector-remote": "^1.0.3",
 - "loopback-connector-rest": "^1.10.1",
 - "loopback-datasource-juggler": "^2.39.0",
 - "loopback-ds-timestamp-mixin": "^3.2.2",

I'll try to create a sandbox version in the next 24 hours; i'll tag you once it's complete and pushed.

**Comment by mcat-ee** [comment]
If we break the query containing 20+ **inq** parameters down into multiple queries it will function as expected.

**Comment by davidcheung** [comment]
same issue as https://github.com/strongloop/loopback/issues/2824

**Comment by Amir-61** [comment]
@davidcheung Thanks!
Closing in favour of https://github.com/strongloop/loopback/issues/2824
