### ISSUE TITLE
Make it easy for community modules to provide custom data-access methods

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#2757]
I think we need an easy and solid way for LoopBack users to implement their custom data-access methods outside of LoopBack core, in an npm package that can be shared by many projects. That way the community can experiment with different flavours of DAO without waiting for our input/review/approval. The caveat I see is how to implement both 1) user/REST-facing bits at loopback/juggler level and 2) also the backing methods in all connectors the developer wants to support. Ideally allowing other community members to fill in missing implementation in other connectors that they want to use.

**Comment by Amir-61** [comment]
👍
