### ISSUE TITLE
Replace or Create works unexpected

### ISSUE THREAD

**Issue by abimelex** [strongloop/loopback#2761]
I have a model with composite primary key, but none of them is called 'id'.
Now I want to insert or update new data using replaceorcreate function for that.

My expectation was, that it checks for the primary key and if it exists, it will update the data and if not it will create. Currently it sometimes updates and sometimes create new data. What is it supposed to do, or what would be the correct function to do so?

https://apidocs.strongloop.com/loopback/#persistedmodel-replaceorcreate

**Comment by Amir-61** [comment]
Hey @abimelex,
>..., but none of them is called 'id'.

They do not need to be called `id`. 

>May expectation was, that it checks for the primary key and if it exists, it will update the data

Yes thats the current functionality. It checks the instance if the instance with that PK exists, it does the full update for that instance; otherwise it creates the instance for you.

I assume the explanation of [the doc](https://apidocs.strongloop.com/loopback/#persistedmodel-replaceorcreate) is confusing, where it says:

>Replace or insert a model instance; replace existing record if one is found, such that parameter data.id matches id of model instance; otherwise, insert a new record.


It may need to be reworded to:


>Replace or insert a model instance; replace existing record if one is found, such that the primary key of data object matches the primary key of model instance; otherwise, insert a new record.


To make the triage process easier, could you please provide a sample repo using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) to reproduce the issue?

**Comment by abimelex** [comment]
It works for sure not as described by you. I have a composite key defined as following but only the first is recognized as key. But when I rewrite it to create() it throws the already existing error. 

```
"properties": {
    "ad_id": {
        "id": 1,
        "type": "string",
        "required": true,
        "postgresql": {
            "columnName": "ad_id",
            "dataType": "character varying(255)"
        }
    },
    "adset_id": {
        "id": 2,
        "type": "string",
        "required": true,
        "postgresql": {
            "columnName": "adset_id",
            "dataType": "character varying(255)"
        }
    },
    "campaign_id": {
        "id": 3,
        "type": "string",
        "required": true,
        "postgresql": {
            "columnName": "campaign_id",
            "dataType": "character varying(255)"
        }
    },
    "date": {
      "id": 4,
      "required": true,
      "type": "Date"
    },
```

**Comment by Amir-61** [comment]
@abimelex,

could you please provide a sample repo using our loopback-sandbox to reproduce the issue?

**Comment by Amir-61** [comment]
Hey @abimelex,

Unfortunately we do not have full support for composite key. `updateOrcreate` and `replaceOrcreate` both work assuming you do not have composite keys. Please see [here](https://github.com/strongloop/loopback-datasource-juggler/blob/373e038301cf88080d0b0330f2a51ff51eedbba2/lib/dao.js#L838) and [here](https://github.com/strongloop/loopback-datasource-juggler/blob/373e038301cf88080d0b0330f2a51ff51eedbba2/lib/dao.js#L480) a PK is expected not composite keys.
