### ISSUE TITLE
How to call remote methods programatically (not through http endpoint request)

### ISSUE THREAD

**Issue by davidchriqui** [strongloop/loopback#2769]
Hi,

I'm able to add remote methods to any model but I would like to be able to call a custom remote method programatically.

I explain.

I have a custom model **customModel** with a custom remote method **customRemoteMethod** accepting one argument **arg1** with a **get** http verb.
I'm able to make a get request to **/api/customModel/customRemoteMethod** with **arg1** as query param.
I'd like to be able to call directly from my backend code this custom remote method as following :

`customModel.customRemoteMethod({ arg1: value}).then(function(data) {
console.log(data)})`

As well as you can send a get request to /api/User/findOne with query params you can call User.findOne.

Thanks for the help

**Comment by Amir-61** [comment]
@davidchriqui 
Lets say you define a remote method like:
```
  myModel.myMethod = function (cb) {
    ...
  };
  myModel.remoteMethod('myMethod', {
    returns: {arg: 'result', type: 'object'},
    http: {path: '/myMethod', verb: 'post'}
  });
```

You should be able to call `myModle.method`, is there something I'm missing in your question? Could you please create a sample repo using [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) showing what you are trying to achieve here please?

**Comment by Sigfried** [comment]
I have the same question and haven't quite tried it yet, so it's probably as easy as you say. But I'm just trying to figure out, if I've got, like you said:
```
  myModel.myMethod = function (cb) {
    ...
  };
  myModel.remoteMethod('myMethod', {
    returns: {arg: 'result', type: 'object'},
    accepts: [...],
    http: {path: '/myMethod', verb: 'post'}
  });
```
and 
```
  myModel.myOtherMethod = function (cb) {
   ...
  };
  myModel.remoteMethod('myOtherMethod', {
    returns: {arg: 'result', type: 'object'},
    accepts: [...],
    http: {path: '/myOtherMethod', verb: 'post'}
  });
```
What does the body of myOtherMethod look like so that I can do something like:
```
  myModel.myOtherMethod = function (cb, ...args) {
      var firstResults = myModel.myMethod(cb,  args);
      var ds = myModel.dataSource;
      return ds.connector.query(
           `select somethings from sometables
            where someCol = ${firstResults.someVal}
               and someOtherCol = ${args[whatever]}`,
           function(err, results) {
               cb(results)
           }
  };
```

Does my pseudocode do the job, or is there some other magic necessary to call myMethod with the appropriate arguments and make use of the results. One obvious problem with my code is that it uses the results synchronously, and they wouldn't be available that way. So what do I do with the call to myMethod? Treat it like a promise? Will it return a promise?

**Comment by privateOmega** [comment]
@Sigfried figured it out yet? I am stuck at the same point

**Comment by osazemeu** [comment]
I had similar issues and finally figured it out. The method you are passing to the new one should be promisified for this to work. I'll just paste sample code to illustrate further.

```
let installedDevices;
  Installation.findBySolarKitId = (solarKitId, status = 'active', cb) => {
    return Installation.find({})
      .then(installation => {
        installedDevices = installation;
        return installation;
      })
      .then(devType => Installation.app.models.SubscriptionPlan.find({where: {devTypeId: `${devType}`}}))
      .then(subscription => {
        return {subscription, installedDevices};
        cb(null, {subscription, installedDevices});
      })
      // TODO: return proper error object.
      .catch(err => cb(null, err));
  };
```

note that I returned something at all levels. Hope this helps someone.
