### ISSUE TITLE
Update all examples to use LoopBack 3.x instead of 2.x

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2772]
#Every project at https://github.com/strongloop/loopback-example is based on LoopBack 2.x. We need to update each and every project to use LoopBack 3.x instead.
- [x] https://github.com/strongloop/loopback-getting-started
- [x] https://github.com/strongloop/loopback-getting-started-intermediate
- [x] https://github.com/strongloop/loopback-example-database
- [x] https://github.com/strongloop/loopback-example-relations
- [x] https://github.com/strongloop/loopback-example-app-logic
- [x] https://github.com/strongloop/loopback-example-access-control
- [x] https://github.com/strongloop/loopback-example-angular-live-set
- [x] https://github.com/strongloop/loopback-example-kv-connectors
- [x] https://github.com/strongloop/loopback-example-middleware
- [x] https://github.com/strongloop/loopback-example-mixins
- [x] https://github.com/strongloop/loopback-example-offline-sync
- [x] https://github.com/strongloop/loopback-example-passport
- [x] https://github.com/strongloop/loopback-example-pubsub
- [x] https://github.com/strongloop/loopback-example-push
- [x] https://github.com/strongloop/loopback-example-ssl
- [x] https://github.com/strongloop/loopback-example-storage
- [x] https://github.com/strongloop/loopback-example-user-management
- [x] ~~https://github.com/strongloop/strong-gateway-demo~~ [ARCHIVED]
- [x] ~~https://github.com/strongloop/loopback-android-getting-started~~ [No package.json]
- [x] https://github.com/strongloop/loopback-example-angular
- [x] https://github.com/strongloop/loopback-example-isomorphic
- [x] https://github.com/strongloop/loopback-example-xamarin
- [x] ~~https://github.com/strongloop/loopback-ios-getting-started~~ [No package.json]

**Comment by bajtos** [comment]
Timeboxed to 3 story points this sprint.

**Comment by loay** [comment]
@superkhau 
I think we can cross off both: 
-  https://github.com/strongloop/loopback-ios-getting-started
- https://github.com/strongloop/loopback-android-getting-started

There is no `package.json` and I don't think there is any upgrade here, unless we will go dig in the jar files for example in Android.

**Comment by Amir-61** [comment]
Closing this issue as done...
