### ISSUE TITLE
REST api DELETE returns 200

### ISSUE THREAD

**Issue by dylanfoster** [strongloop/loopback#2774]
This behavior was changed after [this](https://github.com/strongloop/loopback/issues/1322) was filed, however, 204 is the appropriate response from a DELETE method [see here](http://www.restapitutorial.com/httpstatuscodes.html). Can we revert this, or at the very least, is there a way to override this?

**Comment by Amir-61** [comment]
@dylanfoster 

Interesting... It makes sense to me to use HTTP status code `204` for delete... I see [the PR](https://github.com/strongloop/loopback/pull/1667) which changes the behaviour was landed long time ago `Sep 28, 2015`. I believe there was a reason that @superkhau is returning `200` status code as opposed to `204`. I will let @superkhau explain that. Also @superkhau could you please confirm whether it used to be returning for successful `DELETE` operation or not?

Thanks

**Comment by Amir-61** [comment]
Yea @superkhau answer makes sense; now since we are returning `count`in the message body, `204 NO CONTENT` would not be the right HTTP status code anymore. Thanks @superkhau for clarification.

Closing this issue now.
