### ISSUE TITLE
Docs incorrect?  Observe "loaded" returns instance, not data

### ISSUE THREAD

**Issue by penguinpowernz** [strongloop/loopback#2778]
On [this page](https://docs.strongloop.com/display/public/LB/Operation+hooks) in the docs it says that observing loaded will return a context with data in it.  However that doesn't seem to be case when I am testing it, instead giving the model instance:

```js
  AlertRule.observe("loaded", function(ctx, next) {
    debug("loaded alert rule")
    debug(Object.keys(ctx))
    debug(ctx.data)
    debug(ctx.instance)
    //....
```

Gives this output:

```sh
  api:models loaded alert rule +8ms
  api:models [ 'Model', 'instance', 'isNewInstance', 'hookState', 'options' ] +0ms
  api:models undefined +0ms
  api:models { type: 'deviation', path: '/dosers/1/reading/ec', data: { upper: 1, lower: 0.5 }, dash_id: 1, active: false, id: 1 } +1ms
```

Do the docs need updating?

**Comment by superkhau** [comment]
@crandmck ^

**Comment by Amir-61** [comment]
I don't think if there is any doc issue. @penguinpowernz Could you please clarify what method you are referring to that `loaded` hook returns `instance` and not `data`?

AFAICT, all `loaded` hooks return `data` and not `instance`. Please see [loaded hook for create](https://github.com/strongloop/loopback-datasource-juggler/pull/1105), [loaded hook for updateORCreate](https://github.com/strongloop/loopback-datasource-juggler/blob/baa557116c4bf7b381fdb40e6c4eaef131909594/lib/dao.js#L573-L580) and you can see all of the other `loaded` hook in https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js

**Comment by frankorama** [comment]
I just noticed the same behaviour.  

```
  ModelName.observe('loaded', (ctx, next)=>{

    if(ctx.data){
      // The data object only exists when saving a new instance.  Otherwise, data is in an 'instance' property
      ctx.data.deleted = ctx.data.deleted || (ctx.data.deletedAt ? true : false);
    }

    if(ctx.instance){
      ctx.instance.deleted = ctx.instance.deleted || (ctx.instance.deletedAt ? true : false);
    }

    next();
  });
```

**Comment by Amir-61** [comment]
Thanks @frankmalin,

To make it clear and easier for @crandmck (our doc expert) I believe just `find*` methods (`find`, `findOne`, `findById` and `findByIds`) have `instance` in their loaded methods. All other methods provide `data` object in their `loaded` OH.

**Comment by penguinpowernz** [comment]
Thanks for confirming that @frankorama.  Any more info needed from my side?

**Comment by benkroeger** [comment]
reported same bug a while ago #1071. It's supposed to be fixed in 3.x but not backported to 2.x due to suspected breaking changes

**Comment by Amir-61** [comment]
>reported same bug a while ago #1071. It's supposed to be fixed in 3.x but not backported to 2.x due to suspected breaking changes

I believe you are right! IIRC It was fixed a while ago for LB 3.x https://github.com/strongloop/loopback-datasource-juggler/pull/796

@crandmck So When we document https://github.com/strongloop/loopback/issues/2778#issuecomment-248963090 we should mention thats the 2.x version behaviour and it is fixed now in LB 3.x. We could not backport it because it was a breaking change in 2.x.

Thanks @benkroeger for chiming in 👍

**Comment by crandmck** [comment]
Added a note to http://loopback.io/doc/en/lb2/Operation-hooks.html#loaded (v 2.x only).
