### ISSUE TITLE
Unable to install just "buffertools" on Windows 2012R2 64bit server. Added NPM debug file.

### ISSUE THREAD

**Issue by msarm** [strongloop/loopback#2787]
**Failed at the buffertools@2.1.4 install script 'node-gyp rebuild'.**

-----------------NPM debug error -----------------------
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'buffertools' ]
2 info using npm@3.10.3
3 info using node@v6.6.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData buffertools
8 silly fetchNamedPackageData buffertools
9 silly mapToRegistry name buffertools
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'buffertools',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'buffertools',
12 silly mapToRegistry   name: 'buffertools',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/buffertools
14 verbose request uri https://registry.npmjs.org/buffertools
15 verbose request no auth needed
16 info attempt registry request try #1 at 2:49:17 PM
17 verbose request id d1295a7a4cda638b
18 verbose etag "7A3XM081RG5ECFPRPHGOV5CBV"
19 http request GET https://registry.npmjs.org/buffertools
20 http 304 https://registry.npmjs.org/buffertools
21 verbose headers { date: 'Fri, 23 Sep 2016 21:49:21 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"7A3XM081RG5ECFPRPHGOV5CBV"',
21 verbose headers   age: '96',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-lax8623-LAX',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1474667361.862761,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Fri, 23 Sep 2016 21:49:21 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"7A3XM081RG5ECFPRPHGOV5CBV"',
22 silly get     age: '96',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-lax8623-LAX',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1474667361.862761,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/buffertools from cache
24 verbose get saving buffertools to C:\Users\msarm\AppData\Roaming\npm-cache\registry.npmjs.org\buffertools.cache.json
25 verbose correctMkdir C:\Users\msarm\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule buffertools@2.1.4 checking installable status
39 silly cache add args [ 'buffertools', null ]
40 verbose cache add spec buffertools
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'buffertools',
41 silly cache add   scope: null,
41 silly cache add   escapedName: 'buffertools',
41 silly cache add   name: 'buffertools',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed buffertools@latest
43 verbose addNamed "latest" is being treated as a dist-tag for buffertools
44 info addNameTag [ 'buffertools', 'latest' ]
45 silly mapToRegistry name buffertools
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'buffertools',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   escapedName: 'buffertools',
48 silly mapToRegistry   name: 'buffertools',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/buffertools
50 verbose addNameTag registry:https://registry.npmjs.org/buffertools not in flight; fetching
51 verbose get https://registry.npmjs.org/buffertools not expired, no request
52 silly addNameTag next cb for buffertools with tag latest
53 silly addNamed buffertools@2.1.4
54 verbose addNamed "2.1.4" is a plain semver version for buffertools
55 silly cache afterAdd buffertools@2.1.4
56 verbose afterAdd C:\Users\msarm\AppData\Roaming\npm-cache\buffertools\2.1.4\package\package.json not in flight; writing
57 verbose correctMkdir C:\Users\msarm\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
58 verbose afterAdd C:\Users\msarm\AppData\Roaming\npm-cache\buffertools\2.1.4\package\package.json written
59 silly loadAllDepsIntoIdealTree Finishing
60 silly loadIdealTree Finishing
61 silly currentTree npm
62 silly idealTree npm
62 silly idealTree `-- buffertools@2.1.4
63 silly generateActionsToTake Starting
64 silly install generateActionsToTake
65 silly generateActionsToTake Finishing
66 silly diffTrees action count 1
67 silly diffTrees add buffertools@2.1.4
68 silly decomposeActions action count 8
69 silly decomposeActions fetch buffertools@2.1.4
70 silly decomposeActions extract buffertools@2.1.4
71 silly decomposeActions test buffertools@2.1.4
72 silly decomposeActions preinstall buffertools@2.1.4
73 silly decomposeActions build buffertools@2.1.4
74 silly decomposeActions install buffertools@2.1.4
75 silly decomposeActions postinstall buffertools@2.1.4
76 silly decomposeActions finalize buffertools@2.1.4
77 silly executeActions Starting
78 silly install executeActions
79 silly doSerial global-install 0
80 silly doParallel fetch 1
81 verbose correctMkdir C:\Users\msarm\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
82 verbose lock using C:\Users\msarm\AppData\Roaming\npm-cache\_locks\staging-a9d188be3f24baff.lock for C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging
83 silly doParallel extract 1
84 silly extract buffertools@2.1.4
85 verbose unbuild node_modules\.staging\buffertools-e1c7ca70
86 silly gentlyRm C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging\buffertools-e1c7ca70 is being purged from base C:\Users\msarm\AppData\Roaming\npm
87 verbose gentlyRm don't care about contents; nuking C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging\buffertools-e1c7ca70
88 verbose tar unpack C:\Users\msarm\AppData\Roaming\npm-cache\buffertools\2.1.4\package.tgz
89 verbose tar unpacking to C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging\buffertools-e1c7ca70
90 silly gentlyRm C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging\buffertools-e1c7ca70 is being purged
91 verbose gentlyRm don't care about contents; nuking C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging\buffertools-e1c7ca70
92 silly gunzTarPerm modes [ '777', '666' ]
93 silly gunzTarPerm extractEntry package.json
94 silly gunzTarPerm modified mode [ 'package.json', 436, 438 ]
95 silly gunzTarPerm extractEntry .npmignore
96 silly gunzTarPerm modified mode [ '.npmignore', 436, 438 ]
97 silly gunzTarPerm extractEntry README.md
98 silly gunzTarPerm modified mode [ 'README.md', 436, 438 ]
99 silly gunzTarPerm extractEntry LICENSE
100 silly gunzTarPerm modified mode [ 'LICENSE', 436, 438 ]
101 silly gunzTarPerm extractEntry buffertools.js
102 silly gunzTarPerm modified mode [ 'buffertools.js', 436, 438 ]
103 silly gunzTarPerm extractEntry test.js
104 silly gunzTarPerm modified mode [ 'test.js', 436, 438 ]
105 silly gunzTarPerm extractEntry binding.gyp
106 silly gunzTarPerm modified mode [ 'binding.gyp', 436, 438 ]
107 silly gunzTarPerm extractEntry buffertools.cc
108 silly gunzTarPerm modified mode [ 'buffertools.cc', 436, 438 ]
109 silly gunzTarPerm extractEntry BoyerMoore.h
110 silly gunzTarPerm modified mode [ 'BoyerMoore.h', 436, 438 ]
111 silly gunzTarPerm extractEntry AUTHORS
112 silly gunzTarPerm modified mode [ 'AUTHORS', 436, 438 ]
113 silly gunzTarPerm extractEntry .mailmap
114 silly gunzTarPerm modified mode [ '.mailmap', 436, 438 ]
115 silly gentlyRm C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging\buffertools-e1c7ca70\node_modules is being purged
116 verbose gentlyRm don't care about contents; nuking C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging\buffertools-e1c7ca70\node_modules
117 silly doParallel preinstall 1
118 silly preinstall buffertools@2.1.4 C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging\buffertools-e1c7ca70
119 info lifecycle buffertools@2.1.4~preinstall: buffertools@2.1.4
120 silly lifecycle buffertools@2.1.4~preinstall: no script for preinstall, continuing
121 silly doReverseSerial remove 0
122 silly doSerial move 0
123 silly doSerial finalize 1
124 silly finalize C:\Users\msarm\AppData\Roaming\npm\node_modules\buffertools
125 silly doSerial build 1
126 silly build buffertools@2.1.4
127 info linkStuff buffertools@2.1.4
128 silly linkStuff buffertools@2.1.4 has C:\Users\msarm\AppData\Roaming\npm\node_modules as its parent node_modules
129 silly linkStuff buffertools@2.1.4 is part of a global install
130 silly linkStuff buffertools@2.1.4 is installed into a global node_modules
131 silly linkStuff buffertools@2.1.4 is installed into the top-level global node_modules
132 verbose linkBins buffertools@2.1.4
133 verbose linkMans buffertools@2.1.4
134 silly doSerial global-link 0
135 silly doParallel update-linked 0
136 silly doSerial install 1
137 silly install buffertools@2.1.4 C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging\buffertools-e1c7ca70
138 info lifecycle buffertools@2.1.4~install: buffertools@2.1.4
139 verbose lifecycle buffertools@2.1.4~install: unsafe-perm in lifecycle true
140 verbose lifecycle buffertools@2.1.4~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\msarm\AppData\Roaming\npm\node_modules\buffertools\node_modules\.bin;C:\Users\msarm\AppData\Roaming\npm\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\Git\cmd;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Git\cmd;C:\Program Files\nodejs\;C:\Users\msarm\AppData\Roaming\npm
141 verbose lifecycle buffertools@2.1.4~install: CWD: C:\Users\msarm\AppData\Roaming\npm\node_modules\buffertools
142 silly lifecycle buffertools@2.1.4~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
143 silly lifecycle buffertools@2.1.4~install: Returned: code: 1  signal: null
144 info lifecycle buffertools@2.1.4~install: Failed to exec install script
145 verbose unlock done using C:\Users\msarm\AppData\Roaming\npm-cache\_locks\staging-a9d188be3f24baff.lock for C:\Users\msarm\AppData\Roaming\npm\node_modules\.staging
146 silly rollbackFailedOptional Starting
147 silly rollbackFailedOptional Finishing
148 silly runTopLevelLifecycles Starting
149 silly runTopLevelLifecycles Finishing
150 silly install printInstalled
151 verbose stack Error: buffertools@2.1.4 install:`node-gyp rebuild`
151 verbose stack Exit status 1
151 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
151 verbose stack     at emitTwo (events.js:106:13)
151 verbose stack     at EventEmitter.emit (events.js:191:7)
151 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
151 verbose stack     at emitTwo (events.js:106:13)
151 verbose stack     at ChildProcess.emit (events.js:191:7)
151 verbose stack     at maybeClose (internal/child_process.js:877:16)
151 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
152 verbose pkgid buffertools@2.1.4
153 verbose cwd C:\Program Files (x86)\Git
154 error Windows_NT 6.2.9200
155 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "buffertools"
156 error node v6.6.0
157 error npm  v3.10.3
158 error code ELIFECYCLE
159 error buffertools@2.1.4 install:`node-gyp rebuild`
159 error Exit status 1
160 error Failed at the buffertools@2.1.4 install script 'node-gyp rebuild'.
160 error Make sure you have the latest version of node.js and npm installed.
160 error If you do, this is most likely a problem with the buffertools package,
160 error not with npm itself.
160 error Tell the author that this fails on your system:
160 error     node-gyp rebuild
160 error You can get information on how to open an issue for this project with:
160 error     npm bugs buffertools
160 error Or if that isn't available, you can get their info via:
160 error     npm owner ls buffertools
160 error There is likely additional logging output above.
161 verbose exit [ 1, true ]

**Comment by superkhau** [comment]
What are you running? `npm install -g strongloop`?

**Comment by Amir-61** [comment]
Is this still the issue?

**Comment by Amir-61** [comment]
I'm closing this issue since it seems it has been resolved. Please feel free to leave a message and we re-ropen the issue.

Thanks a lot!
