### ISSUE TITLE
How to getting references to models?

### ISSUE THREAD

**Issue by issmile** [strongloop/loopback#2788]
My English is not good .see picture ,In order to avoid misunderstanding,因为我用翻译软件问的问题
Why console.log(app.models.config) is undefine? how to make right?

![image](https://cloud.githubusercontent.com/assets/20268011/18807308/f65864bc-8275-11e6-9b71-866e9ff4c888.png)

**Comment by ChBernat** [comment]
Could you check app.models, please? Whether it has some value or is undefined.

**Comment by issmile** [comment]
@ChBernat       I follow the doc as same ,but not work.and  how to check ?     like this ? consolo.log(app.modles) see:
![image](https://cloud.githubusercontent.com/assets/20268011/18808760/9795a21e-829d-11e6-90d8-53834ac73b1e.png)

**Comment by Amir-61** [comment]
Could you try `Item.app.models.ModelB.config` in your code? If it still does not work please create a sample repo using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) to reproduce the issue.

Thanks :-)

**Comment by Amir-61** [comment]
@issmile Is your problem solved now? Is this ticket good to be closed?

**Comment by issmile** [comment]
@I found why.the reason is must be in function.thanks
