### ISSUE TITLE
Getting raw body data using loopback

### ISSUE THREAD

**Issue by yickling** [strongloop/loopback#2790]
I'm having trouble getting raw body data using loopback.
I'm currently adding the middleware via `middleware.json`
```
  "parse": {
    "body-parser#json": {}
  },
```

Most expressJS solutions suggest the use of a middleware that listens to the req.on('data') event, typically through the 'verify' function in the `body-parser` middleware.

Since the middleware is done through a JSON file I cannot provide a 'verify' function to configure the `body-parser`.

How can I achieve that raw body data? Thanks.

**Comment by yickling** [comment]
Used a separate way of getting raw body data by attaching custom middleware code to the initial:before phase of middleware. Would still love to have a way of doing that via bodyparser setup.

**Comment by DanFaudemer** [comment]
Solved this issue by telling bodyParser to send raw data on the specific route : 
```
var bodyParser = require('body-parser');
app.use('/myRoute', bodyParser.raw({type: '*/*'}));
```

**Comment by sujeshthekkepatt** [comment]
You can use the following method too, seems to work fine
  `"parse": {
    "body-parser#raw": {
      "methods": ["POST"],
      "paths": ["/your path"],
      "params": {
        "type": "application/json"
      }
    },
    "body-parser#json": {},
    "body-parser#urlencoded": {
      "params": {
        "extended": true
      }
    }
  }`
