### ISSUE TITLE
How to make relation that FK type is string

### ISSUE THREAD

**Issue by noomerzx** [strongloop/loopback#2791]
I've 2 example model on my db(mySql) is campaign and campaign_status. For example

T_Campaign
- id : integer (PK)
- name : varchar
- campaign_status : varchar (FK)

T_Campaign_Status
- status : varchar (PK)

In my loopback model has simple relation as 
- T_Campaign belongsTo T_Campaign_Status
- T_Campaign_Status hasMany T_campaign

FK is T.Campaign.campaign_status and this field is string on both model

When i called the post endpoint for inserting campaign then model validation inform me validation error status 422 and campaign_status can't be blank and value: NaN.

That look like the model need campaign_status to be insert as number. So I'm looking at the example schema on Get and Post endpoint of T_Campaign and campaign_status has data type as number even if on my campaign.json that field is specific as string.

I solve this by remove all relation on both model then the campaign_status field work properly as string but without relation some endpoint has gone and I need to use that.

So the question is what happen and how I can make my relation work with PK-FK as string not a number.

**Comment by Amir-61** [comment]
Hey @noomerzx,

To make the triage process easier, could you please provide a sample repo using https://github.com/strongloop/loopback-sandbox to reproduce the issue? It would be way easier if we see the actual code.

Thanks

**Comment by noomerzx** [comment]
I already solve this issue. The problem is I'm remove idinjection form model instead of set it false. So that why loopback alway though the FK is number.

Thx you so much by the way :)

**Comment by Amir-61** [comment]
@noomerzx 

I'm glad that the problem got resolved :-) Thanks for letting us know.

**Comment by joe-at-startupmedia** [comment]
Almost 4 years later and here I am replicating the same issue. Neither removing the idInjection property or setting it to false resolves the issue. Instead, removing the hasMany foreignkey specification is the only solution for me. 

```
   "relations": {
-    "favorites": {
-      "type": "hasMany",
-      "model": "favorite",
-      "foreignKey": "source_offer_key"
-    },

```
