### ISSUE TITLE
PersistedModel.createChangeStream doesn't clean up observers?

### ISSUE THREAD

**Issue by ywang-clarify** [strongloop/loopback#2794]
I've been trying to implement server-sent events for my custom endpoints based on the PersistedModel.createChangeStream pattern hoping to use the angular-live-set module to easily consume them on the client side. But from what I'm seeing, the code in PersistedModel.createChangeStream doesn't clean up observers?

As a test, I cloned https://github.com/strongloop/angular-live-set.git and put some console.log lines in /node_modules/loopback/lib/persisted-model.js createChangeHander function to log whenever the created change handler is called and again whenever it writes to the changes stream. Opening a few browser windows and drawing some circles in the Circle example shows that with every browser window that was opened, each new request to createChangeStream attached a new change handler as an observer on the Circle model.

I then closed all but one of the browsers. Waited a while in case there was some sort of timeout that triggered cleanup somewhere. Then drew another circle in the remaining browser. Unfortunately, what I saw was that the console logged just as many lines as it when all the browser windows were open.

In fact, sitting around with that one browser, the set of console.log outputs for each given circle increased in size over time. I think this is related to the net::ERR_INCOMPLETE_CHUNKED_ENCODING log in the chrome console which showing the request as "failed" every 2 minutes. I think a new request to Circle.createChangeStream is probably issued when that happens, creating a new observer.

I also added console.logs to the changes.on('error') and changes.on('end') listeners and they were never called.

Am I missing something? Wouldn't this eventually bog the server down?

**Comment by Amir-61** [comment]
Hey @ywang-clarify,

Thanks for filling this issue. I just wonder if you can give me steps to reproduce the issue on my end or ideally provide me with a sample repo to reproduce the issue using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox)...

>the code in PersistedModel.createChangeStream doesn't clean up observers

I'm not sure what you mean here... We have two methods to remove/clean observers which are [MyModel.removeObserver](http://apidocs.strongloop.com/loopback-datasource-juggler/#observermixin-removeobserver) to remove a single observer and [MyModel.clearObservers](http://apidocs.strongloop.com/loopback-datasource-juggler/#observermixin-clearobservers) to clear all observers at once, probably they should be used in `angular-live-set`; @davidcheung any thought on this?

Thanks!

**Comment by ywang-clarify** [comment]
Hi @Amir-61 ,

What I'm referring to is a buildup of server-side observers that continue to exist and do work after the request that triggered their creation is terminated. You can reproduce this in any loopback application that has PersistedModels. Pick any model that inherits from PersistedModel and does not override the default behavior of exposing the change-stream REST endpoint. If you have a model called MyModel, you can send a request to /api/Model/change-stream, that's handled by PersistedModel.createChangeStream(). This creates observers for MyModel.observe('after save') and 'after delete' on the server. These two observers are never removed.

The issue can be manifested by sending a few requests to the change-stream REST endpoint. Then close the browsers that issued those requests. If you attach a debugger or print some lines out to console within the function returned by createChangeHandler, you'll see that those observers are never detached.

Even if the client side does have a method of triggering cleanup of these two observers, I don't think it can be left to the client because there's always the possibility that the client exists without attempting to trigger some sort of cleanup.

**Comment by navjeetfgmnt** [comment]
Did we get anywhere with this one?

**Comment by navjeetfgmnt** [comment]
Did we came to a solution to this one?
