### ISSUE TITLE
Embedded model fields get lost during PATCH

### ISSUE THREAD

**Issue by kirgene** [strongloop/loopback#2797]
I have following relation between User and Settings models:
User - (embedsOne) - Settings
When I try to PATCH individual fields of Settings model the rest of fields get lost.

**Comment by Amir-61** [comment]
Hey @kirgene,

Could you please provide a sample repo using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) to reproduce the issue? That would help alot to triage the issue...

Thanks a lot!

**Comment by kirgene** [comment]
I've created a sample repo: https://github.com/kirgene/loopback-sandbox
Here are the steps to reproduce this issue:
1) ```git clone https://github.com/kirgene/loopback-sandbox```
2) ```npm i```
3) ```node . &```
4) ```curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"email\": \"test@test.com\",
  \"password\": \"123456\",
  \"settings\": {
    \"currency\": \"USD\",
    \"country\": \"US\"
  }
}" "http://0.0.0.0:3000/api/Players"```
5) ```curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
\"email\":\"test@test.com\",
\"password\": \"123456\"
}" "http://0.0.0.0:3000/api/Players/login"```
6) ```export TOKEN=<token_from_previous_call>```
7) ```curl -X GET --header "Accept: application/json" "http://0.0.0.0:3000/api/Players/1?access_token=$TOKEN"```
8) ```curl -X PATCH --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"settings\": {
    \"currency\": \"EUR\"
  }
}" "http://0.0.0.0:3000/api/Players/1?access_token=$TOKEN"```
9) ```curl -X GET --header "Accept: application/json" "http://0.0.0.0:3000/api/Players/1?access_token=$TOKEN"```

Compare output of step 7 and 9. You'll see ```settings``` object has fewer fields after step 8.

**Comment by Amir-61** [comment]
It seems a valid bug. I labeled it as a `bug`.

**Comment by Shereminskiy** [comment]
I have got the same issue with model:updateAll. 
Can it be somehow connected to loopback driver  like loopback-connector-mongodb?

**Comment by BoLaMN** [comment]
The issue is patch uses `$set: 'settings': object` on the root object key 'settings' so it completely over writes the object stored instead it should use `$set: 'settings.currency': object.currency` which would patch only that field. 

It's the same for all embedded relationships unfortunately, none of the patch end points work correctly due to this issue

**Comment by BoLaMN** [comment]
looked into it further and came up with https://gist.github.com/BoLaMN/b69979b6dca800fd23579c32900593ba which i wrapped around data here https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L515

works quite well 

eg 
```
  strong-remoting:shared-method - __updateById__content - invoke with [ '58ba9dcf496ebba1fa53ab41',
  { statusId: 172 },
  [Function: callback] ] +0ms
  loopback:connector:mongodb before parsed { contents:
   [ { text: null,
       artisticDiscretion: 'exact',
       category: null,
       classification: null,
       contentType: 'default',
       packagedAt: null,
       deadlines: null,
       meta: null,
       dates: null,
       statusId: 172,
       action: null,
       webIONumber: null,
       webStartDate: null,
       webEndDate: null,
       webHeight: null,
       webWidth: null,
       landingUrl: null,
       animation: null,
       id: 58ba9dcf496ebba1fa53ab41,
       orderProductId: null,
       comments: [],
       files: [] } ] } +2ms
  loopback:connector:mongodb after parsed { '$set':
   { 'contents.0.artisticDiscretion': 'exact',
     'contents.0.contentType': 'default',
     'contents.0.statusId': 172,
     'contents.0.id': 58ba9dcf496ebba1fa53ab41 } } +1ms
```

**Comment by ebarault** [comment]
hi @BoLaMN,
Would you like contributing your fix as a pull request?

**Comment by BoLaMN** [comment]
already in progress @ebarault at https://github.com/strongloop/loopback-connector-mongodb/issues/355

I need to write some tests for it still
