### ISSUE TITLE
Where has relation feature

### ISSUE THREAD

**Issue by marcoskubis** [strongloop/loopback#2801]
Would be useful a fueature that allows filter results based on your relational data. An example:

**This should return all post that has a admin user:** 

```
Posts.find({
    whereHas: {
        user: {
            where: {
                role: "admin"
            }
        }
    }
});
```

A similiar feature already exists? If not, would be nice to have.

**Comment by Amir-61** [comment]
@marcoskubis 
>This should return all post that has a admin user

This is already doable by:
```
Post.find({
  include: { // include user object
    relation: 'users', 
    scope: {
      where: {role: 'admin'} // only select user with role `admin`
    }
  }
}, function() { ... });
```

Please see include filter doc [here](https://docs.strongloop.com/display/public/LB/Include+filter) for more info.

Please let me know if that answers your question?

Thanks!

**Comment by marcoskubis** [comment]
@Amir-61 thanks for reply. But this only filter the included results, does not affect the "Posts" results.
In the example: I want return only Posts that owner is a admin user, not all.

**Comment by marcoskubis** [comment]
I'm using the Mongo connector, but a mysql examplo could be:

    SELECT * FROM posts WHERE EXISTS (SELECT * FROM users WHERE users.id=posts.user_id AND user.role='admin')
