### ISSUE TITLE
Update links in code to documentation

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#2808]
There are links to docs.strongloop.com in various places in the code that we should replace with links to the new doc site `loopback.io/doc`.

https://github.com/strongloop/loopback/search?utf8=%E2%9C%93&q=%22docs.strongloop.com%22&type=Code

NOTE: The new site will remain around for a while, but it is deprecated for LoopBack, so we _should_ update the links.

**This issue is specifically for URLs embedded in code, not in README, etc.**

In general, there is a direct mapping of old URLs to new URLs, e.g. `https://docs.strongloop.com/display/public/LB/Installing+StrongLoop` -->
`http://loopback.io/doc/en/lb2/Installing-StrongLoop.html`.  
The same mapping is true for pages in the APIC space: `https://docs.strongloop.com/display/public/APIC/Installing+StrongLoop` -->
`http://loopback.io/doc/en/lb2/Installing-StrongLoop.html`.

For 3.0-specific features, replace `lb2` with `lb3` in the URL.

There may be one or two pages that don't map that way... But all the new URLs should look like http://loopback.io/doc/en/lb2/xxx.html.

**Comment by AlexYegupov** [comment]
Also there would be great to redirect old documentation pages to the new one (using 301?) because google often points to old docs.

**Comment by crandmck** [comment]
Yes, @AlexYegupov I plan to do this, but just haven't gotten to it yet.  Will do it ASAP.

**Comment by crandmck** [comment]
> This issue is specifically for URLs embedded in code, not in README, etc.

@Amir-61 I'm going to remove the `doc` label, because this issue is for references to doc _in the code_.  Of course, it's related to docs, but IMHO it's really an engineering issue and responsibility to correct, so the `doc` label might lead someone to think it's actually documentation work...

**Comment by crandmck** [comment]
I think this is worth keeping open.  We need to address this before we stopping fixing stuff in 3.x.  At some point the redirects will stop working.
