### ISSUE TITLE
bash: slc: command not found

### ISSUE THREAD

**Issue by tianshuo** [strongloop/loopback#281]
After installing using `sudo npm -g install strong-cli`, slc cannot be found

**Comment by topazas** [comment]
I found this problem in couple Ubuntu 14 servers using node.js 4.1.2
By default somehow slc is not created or not added to PATH.
Solved this problem by adding symlink:
```code```
sudo ln -s /usr/lib/node_modules/strongloop/bin/slc.js /usr/bin/slc
```code```

**Comment by cmvee** [comment]
All, please note that strongloop-specific tooling is no longer being maintained and that the `lb` cli tool provided by the [loopback-cli](https://github.com/strongloop/loopback-cli) project now "supersedes" strongloop's "older slc tool."

**Comment by youngtk96** [comment]
I know this post is old but this solution did not fix my issue. What i did to resolve this issue is to make sure you are running power shell or Git Bash as an administrator. If you are on Ubuntu make sure you run SUDO
