### ISSUE TITLE
Loopback internal error when null is passed in url parameter, e.g. people/null/conversation

### ISSUE THREAD

**Issue by hristo-vrigazov** [strongloop/loopback#2811]
Steps to reproduce:
1. Create a loopback app
2. Add person (derive from User model) and conversation model
3. Add relation person hasMany conversation from person to conversation

POST people/something/conversation
correctly says that there is no model with such id. However,

POST people/null/conversation
shows internal error

**Comment by bajtos** [comment]
Hi @hristo-vrigazov, is this issue still relevant? What loopback version are you using?

To make it easier to help you, please create a sample application reproducing the problem - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by hristo-vrigazov** [comment]
Hi @bajtos, sorry for the late response. For some reason, I received a notification just now. The issue was present in loopback 3.0.0-alpha1 and I discovered it accidentally when calling the API from a client. Can't tell if it is still there since I am currently not using Loopback. Perhaps it's best to keep this issue closed and if someone rans into it again to reopen it.
