### ISSUE TITLE
A model with a required property of `array` type can't have empty array as a value

### ISSUE THREAD

**Issue by sundeepgupta** [strongloop/loopback#2816]
```json
    "times": {
      "type": "array",
      "required": "true",
      "default": []
    },
```

When creating a model with a property like this and without specifying a value for `times`, I get a validation error. Is this expected?  I would thing empty array is a valid value.

**Comment by jannyHou** [comment]
@sundeepgupta I think you are using an old version of `generator-loopback`. I would suggest upgrading it to latest version `generator-loopback@1.24.4`

And the latest behaviour is:

```
jannyhous-mbp:datatype jannyhou$ slc loopback:model
? Enter the model name: Arraytest
? Select the data-source to attach Arraytest to: db (memory)
? Select model's base class PersistedModel
? Expose Arraytest via the REST API? Yes
? Custom plural form (used to build REST URL): 
? Common model or server only? common
Let's add some Arraytest properties now.

Enter an empty property name when done.
? Property name: times
   invoke   loopback:property
? Property type: date
? Required? Yes
? Default value[leave blank for none]: 
```

And then you will find the following model config in your json file:
```json
{
  "name": "Arraytest",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "times": {
      "type": "date",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**Comment by jannyHou** [comment]
So theoretically
  - It should pass with blank default value
  - An array property should have a type for array items

**Comment by sundeepgupta** [comment]
Thanks @jannyHou I don't use the generator that's my mistake. I didn't know we had to specify the array element type. Thanks for pointing this out.

**Comment by jannyHou** [comment]
@sundeepgupta np :) Is the problem solved now? If yes shall we close this issue?

**Comment by charlle** [comment]
@jannyHou your model declaration still retains a validation error: `teams` can't be blank.  How does this insert an empty array into your data store without a default value?  Wouldn't the require reject it?

**Comment by charlle** [comment]
If you are trying to insert an **empty array as the default** for your data store, then I believe this is the correct declaration.
```
{
  "name": "arraytestmodel",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "times": {
      "type": [
        "date"
      ],
      "default": []
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**Comment by jannyHou** [comment]
@charlle are you using the latest generator-loopback?
I just tried
```
"properties": {
    "times": {
      "type": [
        "date"
      ],
      "required": true
    }
  },
```
and I didn't see the error.
Can you provide your `generator-loopback` version? Thanks.
