### ISSUE TITLE
Explain KV connector vs. PersistedModel style connectors

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#2818]
From https://github.com/strongloop/loopback-connector-redis/issues/16:

> We probably need some distinction between the persisted model style redis connector vs the key-value style in the docs.

Is this only relevant to Redis?  IIUC there is also a memory KV connector.

**Comment by superkhau** [comment]
Yes, KV memory also applies (same as KV redis style).

**Comment by crandmck** [comment]
I think this is worth keeping open.
