### ISSUE TITLE
Transfer loopback-example/contributor-docs to strongloop-archive

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2826]
# DO AFTER LB3 RELEASE
- [x] Change links in loopback-example to point to LB3 docs
- [x] Make sure LB3 docs contain a warning/message of sorts to ensure the user can view LB3
- [ ] Transfer ownership of both repos to strongloop-archive
- [ ] Ask @crandmck for final LGTM

**Comment by crandmck** [comment]
@superkhau Do we need to do anything further here?

**Comment by superkhau** [comment]
Nope, we already deleted the repos. We'll just continue educating the new users to look on http://loopback.io//doc/en/lb3/Tutorials-and-examples.html instead from now on.
