### ISSUE TITLE
ReferenceMany relation with additional fields

### ISSUE THREAD

**Issue by evilive3000** [strongloop/loopback#2829]
Hi, I need your help with model relations. I have two models: `Post` and `Media`. 

Examples:

**Media**  

``` javascript
{
  id: 101 
  type: "gif",
  path: "some/folder"
},
{
  id: 102, 
  type: "mp4",
  path: "some/folder"
}
```

**Post**

``` javascript
{
  id: 1, 
  title: "Apollo 13",
  content: [
    {
      mediaId: 101, 
      header: "header-1",
      description: "descr-1"
    },
    {
      mediaId: 102, 
      header: "header-2",
      description: "descr-2"
    }
  ]
},
{
  id: 2, 
  title: "2 seconds to the Moon",
  content: [
    {
      mediaId: 101, 
      header: "header-3",
      description: "descr-3"
    },
  ]
}
```

I'm going to use MongoDb. I want to describe a relation between this two models, but not sure how to do it in the right way. 

If I had only array of `mediaId`s, I'd make it through `referenceMany`. Now it's look more like `embedsMany`, but embeds many _what_?

I even tried to make something like `MediaItem` model and give it `transient` datasource. But I didn't make it works right with rest APIs.

At final I want to get one or many _posts_ with included _media_ data such as `type` and `path` fields.

Any thoughts? (_[stackoverflow](http://stackoverflow.com/questions/39877524/loopbacks-referencemany-like-relation-with-additional-fields)_)

**Comment by evilive3000** [comment]
well designed next models:


**media.json**
```javascript
{
  "name": "media",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "id": {
      "type": "number",
      "id": true,
      "generated": true
    },
    "type": "string",
    "path": "string"
  }
}
```

**content-item.json**
```javascript
{
  "name": "contentItem",
  "base": "Model",
  "properties": {
    "mediaId": {"id": true},
    "header": "string",
    "description": "string"
  },
  "relations": {
    "media": {
      "type": "belongsTo",
      "model": "media",
      "foreignKey": "mediaId"
    }
  }
}
```

**post.json**
```javascript
{
  "name": "post",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "id": {
      "type": "number",
      "id": true,
      "generated": true
    },
    "title": "string"
  },
  "relations": {
    "content": {
      "type": "embedsMany",
      "model": "contentItem",
      "options": {
        "autoId": false,
        "forceId": false,
        "validate": true
      }
    }
  }
}
```

Now if I need all posts with included relations I'm doing next:
`http://localhost:3001/api/posts?filter[include]=content` and receive data as expected:
```javascript
[
  {
    "id": 21,
    "title": "first post",
    "contentItems": [ ... contentItems ... ],
    "content": [ ... contentItems ... ]
  },
  ...
]
```

but if I want nested relation `media`, I go to:
`http://localhost:3001/api/posts?filter[include][content]=media` and receive same output as above, without expected relations.
I did try doing it in the code:
```javascript
Post.find({
  include: {
    relation: 'content',
    scope: {
      include: {
        relation: 'media',
      },
    },
  },
}, cb);
```
and nothing again. I got only embedded `content` relation. 

Only way to receive expected output is to add `scope` field in the relation description in `post.json` file.
```javascript
  "relations": {
    "content": {
      "type": "embedsMany",
      "model": "contentItem",
      "scope": {
        "include": "media"
      },
      "options": { ... }
    }
  }
```
now I getting correct result:

```javascript
{
"id": 21,
"title": "first post",
"contentItems": [{
  "mediaId": 11,
  "header": "Some picture",
  "description": "Hello World"
  }, ... ],
"content": [{
  "mediaId": 11,
  "header": "Some picture",
  "description": "Hello World",
  "media": {
    "id": 11,
    "type": "gif",
    "path": "abc/xyz"
  }
}, ... }
```

But I don't need this data every when I need `content`. What am I doing wrong? Please, need help!

**Comment by jannyHou** [comment]
Thank you @evilive3000  for providing enough details, while I still need some time to create the app on local to reproduce your error, if you have an existing app, could you fork https://github.com/strongloop/loopback-sandbox and replace with your code? Thanks!

After going through your steps I don't see anything wrong, if the nested scope doesn't work then I believe it's a bug. Ideally you don't need to define the scope in your model JSON file.

I will also take a look if there is any existing bug reported.
