### ISSUE TITLE
How to install in windows 10 i got error . my npm -v 3.10.8 & node -v 6.6.0 . I am install in three win system but got same error .

### ISSUE THREAD

**Issue by singh7889** [strongloop/loopback#2831]
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Singh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "nod                        e-pre-gyp"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! path C:\Users\Singh\AppData\Roaming\npm\node_modules\.staging\sqlite3-e34b87be
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\Singh\AppData\Roaming\npm\node_modules\.staging\sqlite3-e34b87be'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Singh\AppData\Roaming\npm\node_modules\.staging\sqlite3-e34b87be\npm-debug.log

> strong-arc@1.8.8 preinstall C:\Users\Singh\AppData\Roaming\npm\node_modules\.staging\strong-arc-bc9c3378
> node .sl-blip.js

C:\Users\Singh\AppData\Roaming\npm
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.2 (node_modules\strongloop\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":                        "win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.x (node_modules\strongloop\node_modules\strong-supervisor\node_modules\modern-s                        yslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":                        "win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 (node_modules\strongloop\node_modules\sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sqlite3@3.1.5 preinstall: `npm install node-pre-gyp`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 4294963214
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Singh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g"                         "strongloop"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.8
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! path C:\WINDOWS\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe

npm ERR! strong-arc@1.8.8 preinstall: `node .sl-blip.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the strong-arc@1.8.8 preinstall script 'node .sl-blip.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-arc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .sl-blip.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-arc
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-arc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Work\StrongLoop\Demo\ex-1\npm-debug.log
npm ERR! code 1

**Comment by raviranjan528** [comment]
I have same error . please review

**Comment by eduardongarcia** [comment]
Hi, the same with me

**Comment by davidcheung** [comment]
related https://github.com/strongloop/strong-arc/issues/1733
https://github.com/strongloop/strongloop/issues/324
https://github.com/mapbox/node-sqlite3/issues/720

**Comment by rmg** [comment]
Quick update from the various other issues:
 * strong-arc@1.8.9 has been released which completely removes the preinstall script calling sl-blip
 * strongloop@6.0.3 was released which pins sqlite3 at 3.1.4
 * sqlite3@3.1.6 was released, which makes pinning to 3.1.4 no longer necessary

In other words, this should now be working. @davidcheung or @singh7889 please re-open if you are still seeing a problem.

**Comment by singh7889** [comment]
Thanks @rmg,  I fix this issue .

**Comment by raviranjan528** [comment]
@singh7889 Thanku Mr.singh ...with your i am able to fix my issue.

**Comment by sadiss** [comment]
Thanks @singh7889 You saved my life
