### ISSUE TITLE
ACL owning object allowed for two models sharing a model

### ISSUE THREAD

**Issue by whispers16** [strongloop/loopback#2832]
Hi guys,
I have a question 
I have two models: 'user' and 'company' that have a relation with a third model 'messages', and messages have the ids of both models.

I set this ACL rule for messages: 

```
{
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW"
 }
```

but my question is can I share this ACL rule with both modules if for example user model create a message and company needs to update it? or there's any other way to share a ACL rule with messages in common?

I appreciate if someone can help me!
thanks :)

**Comment by bajtos** [comment]
@ebarault could you PTAL? I think you may know the answer from the top of your head, considering how much time you spent working on $owner role recently.

**Comment by ebarault** [comment]
@whispers16 : the ownership concept only works for models of type **User** (models inheriting from the built-in model `User`). In your case, a **company** instance can only own a `message` if **company** model is of type `User` (can call authenticated REST methods).

Still this feature will be soon available in combination with multiple user models setups (see http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#access-control-with-multiple-user-models) 

For the time being you can go with a custom role resolver that will implement your business logic.

**Comment by bajtos** [comment]
I am closing this issue since the original question seems to be answered by Eric's comment above. Feel free to reopen if you disagree.
