### ISSUE TITLE
mysql  filter where on relation 

### ISSUE THREAD

**Issue by dahuahe** [strongloop/loopback#2834]
In model A
```
{ "name": "A",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "AreaCode": {
      "type": "string",
      "default": ""
  }
  },
  "relations": {
    "B": {
      "type": "hasOne",
      "model": "B",
      "foreignKey": ""
    }
  }
}
```
In model B
```
{
  "name": "B",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "Name": {
      "type": "string",
      "default": ""
    }
  },
  "relations": {
    "A": {
      "type": "belongsTo",
      "model": "A",
      "foreignKey": ""
    }
  }
}
```
if I find A with B like this  /api/A      {filter:{include:"B"}}}  I will get this data
```
[{
id:1
AreaCode:"test1",
B:{Name:"xxxxx"}             // (if A id 1 hasOne B)
}.{
id:2
AreaCode:"test2",         //   (A id 2 don't haveOne B)
}......]
```
But I want to get this data  
```
[{
id:1
AreaCode:"test1",
B:{Name:"xxxxx"}             // (if A id 1 hasOne B) only get data A has B  
},{                                         
id:3
AreaCode:"test1",
B:{Name:"XXXX"}
}......(A hasOne B's data)]
```
so  I try find A with B like this  /api/A      
{filter:{include:"B",where:{B:{neq:''}}}}}}  or
{filter:{include:"B",where:{neq:{B:''}}}}}}
it's doesn't  work!!
How i to write filter ??or to do??

**Comment by 0candy** [comment]
@dahuahe `hasOne` does not take in a filter parameter. There is already a feature request for that.
https://github.com/strongloop/loopback/issues/2304
Closing this one as a dup.

Please let me know if you don't think its the same problem and we can reopen the issue. Thanks!

**Comment by 0candy** [comment]
See feature request https://github.com/strongloop/loopback/issues/683.
Closing this issue as a dup.
