### ISSUE TITLE
$ npm install -g apiconnect followed by npm not found?

### ISSUE THREAD

**Issue by scheung38** [strongloop/loopback#2835]
Followed instructions

```
$npm install -g apiconnect 

$npm install
```

then 

`$apic loopback
`

bash: apic: command not found

http://stackoverflow.com/questions/37388274/apic-command-not-found-strongloop

But hardly anyone answered?

Have I missed out something?

**Comment by Amir-61** [comment]
I guess this is duplicate of https://github.com/strongloop/strongloop/issues/324
Fixed by https://github.com/strongloop/strongloop/pull/325

@scheung38 Please confirm the fix and I'll close the issue then.

Thanks!

**Comment by superkhau** [comment]
node-sqlite3@3.1.6 should resolve this issue -- see https://github.com/strongloop/strongloop/commit/9599f0d16bcbd4ced276a0a1978712ed0728dcce for more info. Closing as resolved. @scheung38 Ping if you're still running into issues and we can reopen this issue then.
