### ISSUE TITLE
Pull request template integration

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2837]
Integrate PR templates into strongloop/loopback.

See https://github.com/strongloop/loopback/issues/2442#issuecomment-251377947

**Comment by superkhau** [comment]
PR at https://github.com/strongloop/loopback/pull/2843

**Comment by bajtos** [comment]
@superkhau what's the plan for adding the template to all LB projects/repositories?

**Comment by superkhau** [comment]
@bajtos Pull it into planning tmr https://github.com/strongloop/loopback/issues/2867

**Comment by superkhau** [comment]
@bajtos I also want to get a few more rounds of feedback (especially from @raymondfeng @ritch) before doing the propogation TBH. We're almost there -- I should be able to get the feedback as part of the task above.

**Comment by superkhau** [comment]
Closing in favour of #2865
