### ISSUE TITLE
request method to remove internal properties from list

### ISSUE THREAD

**Issue by lohbrand** [strongloop/loopback#2838]
Is there a method to remove hidden properties from loopback list, like

"__cachedRelations" : {
    "__data" : {
        "variable" : "d", 
        "relation" : "r", 
        "value" : "1"
    }, 
    "__dataSource" : null, 
    "__strict" : false, 
    "__persisted" : false, 
    "variable" : "d", 
    "relation" : "r", 
    "value" : "1", 
    "id" : null
}

**Comment by superkhau** [comment]
Did you read the first line of the issue template? Closing as this is a question and better suited for Gitter/Google Groups -- http://loopback.io/doc/en/contrib/Reporting-issues.html.
