### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2844]
Figure out what is needed today to make CONTRIBUTING.md better and more relevant:
- Link to official loopback.io docs
- Style guide
- ESLint guide
- etc

Work with @crandmck to see what we need to keep/what to remove, etc.

**Comment by eddiemonge** [comment]
can the CLA move to its own file with a link to it?

**Comment by eddiemonge** [comment]
An example one that has some good parts is [Yeoman's](https://github.com/yeoman/yeoman/blob/master/contributing.md)

**Comment by superkhau** [comment]
@eddiemonge Thanks for the input, we can definitely take some parts from the Yeoman example. :+1:

Might be worth adding a link to each repo that links ot the CLA signing page -- this is done via GitHub UI ATM. For example the link is https://cla.strongloop.com/agreements/strongloop/loopback.

**Comment by dhmlau** [comment]
We've revamped the contributing guidelines in https://loopback.io/doc/en/contrib/index.html. Closing as done.
