### ISSUE TITLE
Crash when invalid date

### ISSUE THREAD

**Issue by hoangtrongphuc** [strongloop/loopback#2856]
### Bug or feature request

- [x] Bug
- [ ] Feature request
### Description of feature (or steps to reproduce if bug)

When I update model relation with invalid date, whole API is crash
Eg: I have Customer model and Customer has many Campaign model, Campaign model have startDate and endDate, when I call API to __updateById__campaigns with invalid date, crash my server
### Expected result

Catch error and response status code 422 
### Actual result (if bug)

Crash server and response no content
### Additional information (Node.js version, LoopBack version, etc)

Nodejs v6, Loopback v2.34.1

**Comment by bosco-li** [comment]
@hoangtrongphuc we need a sample code to make sure we are on the same page with the problems you mentioned.

Also Is there a stacktrace you can show the error is from loopback?

Thanks.

**Comment by yunyunzai** [comment]
I think it has to do with datetime type validation specifically.
Following should propose a working solution but never merged.
[https://github.com/strongloop/loopback-datasource-juggler/pull/895/files](url)

**Comment by joostdebruijn** [comment]
I have the same behaviour with LoopBack v3.2.1. I can make an example to reproduce the bug, if needed?

**Comment by joostdebruijn** [comment]
This is fixed in strongloop/loopback-datasource-juggler#1266. This issue could be closed.
