### ISSUE TITLE
Error running loopback application

### ISSUE THREAD

**Issue by beingshashi** [strongloop/loopback#2859]
When i run `Node .` i got following error:-

/home/ubuntu/kinekt_apis/node_modules/loopback-boot/lib/compiler.js:365
    throw err;
          ^
Error: Cannot resolve path "helmet"
    at resolveAppPath (/home/ubuntu/kinekt_apis/node_modules/loopback-boot/lib/compiler.js:363:15)
    at resolveAppScriptPath (/home/ubuntu/kinekt_apis/node_modules/loopback-boot/lib/compiler.js:686:22)
    at resolveMiddlewarePath (/home/ubuntu/kinekt_apis/node_modules/loopback-boot/lib/compiler.js:563:20)
    at /home/ubuntu/kinekt_apis/node_modules/loopback-boot/lib/compiler.js:481:24
    at Array.forEach (native)
    at /home/ubuntu/kinekt_apis/node_modules/loopback-boot/lib/compiler.js:480:18
    at Array.forEach (native)
    at /home/ubuntu/kinekt_apis/node_modules/loopback-boot/lib/compiler.js:475:30
    at Array.forEach (native)
    at buildMiddlewareInstructions (/home/ubuntu/kinekt_apis/node_modules/loopback-boot/lib/compiler.js:473:15)

**Comment by davidcheung** [comment]
newly scaffolded loopback applications [should have helmet by default](https://github.com/strongloop/loopback-workspace/blob/86d5f951c518d35a30392d3c183f3ad0b2811ffd/templates/projects/empty-server/data.js#L23), perhaps you have a old scaffolded app with a new version of the middleware.json?  

`npm install --save helmet` should fix your problem.

@jannyHou thoughts?

**Comment by jannyHou** [comment]
thanks @davidcheung exactly, `helmet` is included in a default app's `package.json`.

@beingshashi Could you try `slc loopback` a new app and see if `node .` still gives you this error?
I installed strongloop with latest generator-loopback a few days ago and it works fine on my end.

If you still have problem please include the `generator-loopback` and `loopback-workspace` you are using. And give me a copy of the `package.json` in your new app. Thanks.

**Comment by beingshashi** [comment]
Hi,
@davidcheung ; i have tried what you have told and it worked also , but now i am getting different type of error , while creating relations in loopback models:-

ubuntu@ip-172-31-46-222:~/beingexpert$ slc loopback:relation
Native thread-sleep not available.
This will result in much slower performance, but it will still work.
You should re-install spawn-sync or upgrade to the lastest version of node if possible.
Check /usr/lib/node_modules/generator-loopback/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync/error.log for more details


i have no idea , what is the cause of this.

**Comment by davidcheung** [comment]
weird, never ran into this myself
would you be able to tell us what version ur `slc` and `generator loopback` is?
`npm info generator-loopback -g .version && npm info strongloop -g .version`

**Comment by beingshashi** [comment]
@davidcheung :->
ubuntu@ip-172-31-46-222:~$ npm info generator-loopback -g .version && npm info strongloop -g .version
1.24.4

6.0.3

**Comment by beingshashi** [comment]
@davidcheung @jannyHou -->
ubuntu@ip-172-31-46-222:~/kinekt_apis$ slc loopback:property
FATAL ERROR: Evacuation Allocation failed - process out of memory

not able to add property ..kindly look at the issue.

**Comment by davidcheung** [comment]
@beingshashi do u also get this behavior on other machines? or is it just one machine that you face this issue?  I leaning to think it is a problem with the environment?

**Comment by beingshashi** [comment]
@davidcheung - I have seen this behaviour in 2 windows machine and 1 Mac and 2 ubuntu , windows seems to work well when we have done environment variables but.. mac and ubuntu.. everytime i install i get same errors.. then i have to make lot of bla bla steps..to get rid of all errors and start loopback.. very frustrating.

**Comment by davidcheung** [comment]
@beingshashi I'm not sure how to reproduce that, not sure if it's the global modules having conflicts with each others, not sure if it is possible to reproduce in a [sandbox repo](https://github.com/strongloop/loopback-sandbox) that produces that problem, as the problem sounds like it could be environment related. 
http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by loay** [comment]
@beingshashi Are you still running into this issue?
