### ISSUE TITLE
User.resetPassword for different REALM

### ISSUE THREAD

**Issue by chojowliu** [strongloop/loopback#2866]
### Bug or feature request

- [ ] Bug
- [x ] Feature request
### Description of feature (or steps to reproduce if bug)

Currently, when I do User.resetPassword(email)), it will only return the first record of the match email and return the token, but it's not support to different realm with same email address.
### Expected result

Support different realm.

**Comment by beeman** [comment]
@chojowliu I've created a fix for this in the PR referenced above. Feel free to try my fix to see if it works for you.

**Comment by Monstrik** [comment]
What about 3.x fix

**Comment by beeman** [comment]
@Monstrik the fix for 3.x just landed in master

**Comment by Monstrik** [comment]
Thanks
