### ISSUE TITLE
Replicate .github dir templates across all LB projects

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2867]
- [x] Get feedback from @raymondfeng @ritch and @cgole regarding the content of https://github.com/strongloop/loopback/blob/master/.github/ISSUE_TEMPLATE.md and update accordingly (@superkhau will do this after chatting on hangout)
- [x] Copy the entire `.github` dir (you want to copy both ISSUE_TEMPLATE and PR_TEMPLATES) across all LoopBack projects (see https://github.com/strongloop/loopback-triage/blob/master/repos.json)
- [x] Create a checklist as usual to the PRs
- [x] Get @superkhau to review each PR and land them accordingly

**Comment by superkhau** [comment]
Add script to https://github.com/strongloop/loopback-scripts

**Comment by siddhipai** [comment]
PRs created for cheked repos:

[generator-loopback] (https://github.com/strongloop/generator-loopback/pull/247)

**Comment by siddhipai** [comment]
PRs created for checked repos:
- [X] [angular-live-set](https://github.com/strongloop/angular-live-set/pull/30)
