### ISSUE TITLE
findById doesn't have consistent filter like other end points

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [strongloop/loopback#2868]
Hi guys,

Why `findById` doesn't have consistent filter object like other end points!

I can't for example apply where ... only (Include, Fields) which is pretty limiting!

What if I want to return only the object from `findById` if it is owned to the called of the object?

I was adding `where` to all filters so that I guarantee it gets only the required result.

How to do this right now?!

Thanks.

**Comment by jannyHou** [comment]
@ahmed-abdulmoniem 
> What if I want to return only the object from findById if it is owned to the called of the object?

So from my understanding, let's say you have two models `User` and `Account`:
- `User` hasMany `Account`
- `Account` belongsTo `User`

And when you do `user1.accounts.findById(id, cb)`, you only want to have the account belongsTo user1.

If this is the case I think you are looking for how to restrict access to related model, please check our doc for details: http://loopback.io/doc/en/lb2/Accessing-related-models.html#restricting-access-to-related-models

Briefly, you can do this by editing `ACL` of your model.

**Comment by ahmed-abdulmoniem** [comment]
I have added ACL and it is not working from the time of this issue.

I mean findById is not returning the owned object even if you added ACL
