### ISSUE TITLE
Before delete order in inherited User model

### ISSUE THREAD

**Issue by tspoke** [strongloop/loopback#2870]
### Bug or feature request
- [x] Bug
- [x] Feature request
### Description of feature (or steps to reproduce if bug)
- Create an inherited model of Loopback User model
- Declare a before remote method in it and send error.

``` js
Members.observe("before delete", function(ctx, next) {
    return next(new Error("I don't want to delete this member :)"));
});
```
### Expected result

I expect that nothing will happen in my database.
### Actual result (if bug)

The access token is deleted in my database because in the User model there is already a observe() method on 'before delete' and it is call before mine.
https://github.com/strongloop/loopback/blob/master/common/models/user.js#L306
### What I suggest

Loopback should execute observe() methods in inherited models first or give a way to rollback previous operations.
### Additional information (Node.js version, LoopBack version, etc)

"loopback": "^2.34.1"

**Comment by bajtos** [comment]
Hello, I think there is no single ordering of observers that would work for all use cases.

Let's step back a bit and discuss the actual problem you are trying to solve. Why would you like to disable the built-in "before delete" hook that's deleting access tokens of the deleted user?

**Comment by tspoke** [comment]
Hi @bajtos 

I don't remember exactly what I wanted to do, but the original post was more about handle errors in observe() method. 

I understand that observers are just.. observers. I don't know how you want to users to use them, only as 'events hooks' with no real impact on the request; or, in a more complexe way, as methods in a global transactions.

In loopback I really feel like I want to be able to use them as transactions (before delete, delete operation, after delete). Throwing error in any of these methods should rollback the 'transaction' and keep things in a coherent state. Or, at least, if an error is throw in the before hook, revert/cancel all before hooks only.

I think this is not a bug and maybe more a question about usage : How do you want your users to use hooks?

**Comment by bajtos** [comment]
> In loopback I really feel like I want to be able to use them as transactions (before delete, delete operation, after delete). Throwing error in any of these methods should rollback the 'transaction' and keep things in a coherent state. Or, at least, if an error is throw in the before hook, revert/cancel all before hooks only.

Makes sense!

To some extend, hooks works the way you have described - when a hook observer calls `next(err)`, the operation is aborted.

Unfortunately, LoopBack does not support transactions out of the box, therefore when an operation consisting of multiple database calls (e.g. the cascading delete described above) fails in the middle, there is no easy way for rolling back the change that have been already made.

Has this answered your questions?

**Comment by tspoke** [comment]
Thank you @bajtos. I understand that's not easy and probably my use case was too much specific to spend time on it.

I think we can close this Issue :)

**Comment by danazkari** [comment]
Hello @bajtos!

Sorry to resurface this issue, but I am running into this same wall, my use case being that I want/need to block users from deleting themselves. I know that the front-end shouldn't allow it but this REST API I'm building might be used by other teams and I can't rely on their common sense 😉 

So perhaps what I'm looking for is, for the best way to avoid an accidental delete from the same user making the request, without needing to create a custom delete endpoint for users.

Does it make sense?

**Comment by bajtos** [comment]
> So perhaps what I'm looking for is, for the best way to avoid an accidental delete from the same user making the request, without needing to create a custom delete endpoint for users.
> Does it make sense?

Hello @danazkari, your request make sense. 

Since your primary concern is about REST API clients, can you use a `beforeRemote` hook to achieve what you need? You should be able to find the `id` of the user-to-be-deleted in `ctx.args`, the id of the currently-authenticated user should be in `ctx.args.options.accessToken.userId`. I am typing this from top of my head as I don't have bandwidth to verify this in an actual app. It may not work exactly as I wrote it here, sorry!
