### ISSUE TITLE
Socket IO Weird Behavior

### ISSUE THREAD

**Issue by alihalabyah** [strongloop/loopback#2875]
Hi Guys,

I have Loopback version `2.34.1` and SocketIO ver `1.5.0` and the socket is integrated according the official documentation of Loopback as per the below code snippet:

```js
// Bootstrap the application, configure models, datasources and middleware.
// Sub-apps like REST API are mounted via boot scripts.
boot(app, __dirname, function(err) {
    if (err) throw err;

    // start the server if `$ node server.js`
    // if (require.main === module)

    if (require.main === module) {
        // app.start();

        app.io = require('socket.io')(app.start(), { 
            path: '/socket.io',
            'transports': [
                'polling',
                'websocket'
            ],
            // forceNew: true
            "cookie": false
        });
        require('socketio-auth')(app.io, {
            authenticate: function(socket, value, callback) {

                    // console.log('authenticate called!');
                    var AccessToken = app.models.AccessToken;
                    //get credentials sent by the client
                    var token = AccessToken.find({
                        where: {
                            and: [{ userId: value.userId }, { id: value.id }]
                        }
                    }, function(err, tokenDetail) {
                        if (err) throw err;
                        if (tokenDetail.length) {
                            callback(null, true);
                        } else {
                            callback(null, false);
                        }
                    }); //find function..    
                } //authenticate function..
        });

        app.io.on('connection', function(socket) {
            console.log('a user connected');
            socket.on('disconnect', function() {
                console.log('user disconnected');
            });
        });
```

Whenever I start my application it will work fine with no issues and the connection will be upgraded to Websocket with a response code of `101` however the moment I try to access the rest API even by entering a wrong URL that will result in a `404` page the socket will stop working in case I reload the page, I will start getting `Finished` instead of the `101` and Chrome will start showing 

`Connection closed before receiving the handshake ...`

Do you have any idea what's going on? Seems like there is something wrong happening in Loopback at some level that force the socket to stop working but not sure what's that

**Comment by alihalabyah** [comment]
@bajtos Since as I can see you are very active here Can you please look at the above?

**Comment by bajtos** [comment]
@alihalabyah No idea what may be wrong. Could you please create a sample application that we can run locally to reproduce the problem? See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by alihalabyah** [comment]
@bajtos and everyone I want to consider this closed since the cause of the issue is another plugin I was using as per the below code to live monitor the status of the API but it's good to mention that my socket was breaking at the first rest request/hit because the socket parser somehow was listening to the http request and trying to generate a session variable in which resulting in breaking the socket forever until the app is restarted

I don't have a deep technical explanation for this but I was able to discover by disabling everything related to `socket.io` and then in the debug I have noticed the `socket.io` is being invoked at the moment of hitting the API

```
app.use(require('express-status-monitor')({
    title: 'ShopYard Status', // Default title
    path: '/status',
    spans: [{
        interval: 1, // Every second
        retention: 60 // Keep 60 datapoints in memory
    }, {
        interval: 5, // Every 5 seconds
        retention: 60
    }, {
        interval: 15, // Every 15 seconds
        retention: 60
    }]
}));
```

This could be helpful for anyone might face the same in the future

**Comment by bajtos** [comment]
@alihalabyah thank you for coming back to us and sharing the reason of the failures you were observing.

I agree with closing this issue.
