### ISSUE TITLE
MySQL Discovery Honors Foreign Keys Made To The Same Column Only Once

### ISSUE THREAD

**Issue by shaheero** [strongloop/loopback#2881]
- [x] Bug
- [ ] Feature request

I have 2 columns that reference the same column in another table through a foreign key. MySQL discovery only made one relationship and ignored the other.

**Comment by jannyHou** [comment]
Hi @shaheero if this is a MySQL issue then better to open issue in https://github.com/strongloop/loopback-connector-mysql and track discussion and fix there.

And please follow the template https://github.com/strongloop/loopback-connector-mysql/issues/new to provide more details :) Thanks.

**Comment by shaheero** [comment]
Alright.
https://github.com/strongloop/loopback-connector-mysql/issues/253
