### ISSUE TITLE
greater and less than where clause is not working togather

### ISSUE THREAD

**Issue by shyam2k16** [strongloop/loopback#2886]
Hello,

I want to fetch datewise data but i am not getting desired output.
I am using this   {"createdAt":{"gt":"2016-10-18","lt":"2016-10-21"}} in where clause to fetch data .. but it is giving all the records.
Individullay i am gtting correct response but when I am using gt and lt togheter it is giving all the data

Any help would be appreciable..

Please suggest.

**Comment by phra** [comment]
is this confirmed?
@shyam2k16 do you get the same result if you split the query object like `{"createdAt":{"gt":"2016-10-18"}, "createdAt":{"lt":"2016-10-21"}}` ?

**Comment by jannyHou** [comment]
@shyam2k16 @phra I think the right format is
```js
where: {
  and: [
    {createdAt: {gt: '2016-10-18'}},
    {createdAt: {lt: '2016-10-21'}}
  ]
}
```
Please see our doc for `where` filter to know more about how to use `and/or`:
https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-and/or

**Comment by phra** [comment]
@jannyHou yeah, i was remembering that were splitted in some way. thank you.

**Comment by jannyHou** [comment]
:+1: We use git to track features and bugs and I am closing this issue since problem solved. 
Feel free to reopen it if you have other questions :) Thanks for understanding.

**Comment by shyam2k16** [comment]
Thank you @jannyHou  .. It's working!

**Comment by ruoru** [comment]
i suggest use [between](https://loopback.io/doc/en/lb3/Where-filter.html#operators)
like this:
```js
where: {
    createdAt: between['2016-10-18', '2016-10-21'],
}
```

**Comment by ruoru** [comment]
@phra  sorry，my writing is wrong。thanks
