### ISSUE TITLE
Random Sample List

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback#2895]
### Bug or feature request

- [ ] Bug
- [x] Feature request
### Description of feature (or steps to reproduce if bug)

https://groups.google.com/forum/#!searchin/loopbackjs/random$20post%7Csort:relevance/loopbackjs/4_Rhe-jd8jM/lS03333FBwAJ

How to get random post from loopback?? I am using mongodb connector
Currently I have tried various plugins from the github and none of them is working for me. 
I know that the currently db driver from mlab is providing 3.2 and im using it.

I hope that loopback has an official function to do random sample list from a collection.

**Comment by jannyHou** [comment]
Hi @superkhau  I saw your comment in google group chat https://groups.google.com/forum/#!searchin/loopbackjs/random$20post%7Csort:relevance/loopbackjs/4_Rhe-jd8jM/lS03333FBwAJ, shall we move further discussion here?

**Comment by jjhesk** [comment]
what is the resolution for this feature so far?

**Comment by go1dfish** [comment]
I also need this feature or at least an example of a workaround for the mongo connector for now.
