### ISSUE TITLE
Customize params missing in request

### ISSUE THREAD

**Issue by pikitgb** [strongloop/loopback#2900]
HI! Guys ! how i customize my errors messages when there is params missing in my API request ?

I have something like this: 
Model.remoteMethod(
     'rest_method',
     {
         http: { verb: 'get' },
         description: '...',
         accepts: { arg: 'param_1', type: 'string', required: true, default: 'default_value' },
         returns: { arg: 'data', type: ['Model'], root: true }
     }
   );

I wanna customize the 'accepts' array, hash with an specific message when the param is missing:  
accepts: { arg: 'param_1', type: 'string', required: true, default: 'default_value' }
Default message: 
"message: <param_1> is a required argument", statusCode: 400" <- any way to make it custom? 

Best regards!.

**Comment by bosco-li** [comment]
@pikitgb Thank you for creating the issue.  You can only customized the message in `node_modules/strong-remoting/intl/en/message.json', but we do not support customized error message as an input for missing a required parameters.   Can you share with us why you like to customize the message?  Perhaps we can provide a better suggestion on how to solve the problem.

You can probably workaround the issue by creating a map for your own customer message and matches the response to a message you like as well.
