### ISSUE TITLE
Unknown property principleId is skipped for model RoleMapping

### ISSUE THREAD

**Issue by timlind** [strongloop/loopback#2908]
### Bug or feature request

- [x] Bug
- [ ] Feature request
### Description of feature (or steps to reproduce if bug)

Following instructions for using roles on the docs : http://loopback.io/doc/en/lb2/Defining-and-using-roles.html

Setting the role.principles.principleId does not persist to database (tested on postgres and mongo connector)
### Expected result

rolemapping table should have a value in the column principleid
### Actual result (if bug)

there is no value persisted to the column. the column is also of type 'text' when the user id column is of type 'integer'

`
  loopback:connector:sql Unknown property principleId is skipped for model RoleMapping +10ms
  loopback:connector:postgresql SQL: INSERT INTO "public"."rolemapping"("principaltype","roleid") VALUES($1,$2) RETURNING "id"
Parameters: ["USER",1] +1ms
  loopback:connector:postgresql {"command":"INSERT","rowCount":1,"oid":0,"rows":[{"id":5}],"fields":[{"name":"id","tableID":4414297,"columnID":1,"dataTypeID":23,"dataTypeSize":4,"dataTypeModifier":-1,"format":"text"}],"_parsers":[null],"rowAsArray":false} +587ms
`
### Additional information (Node.js version, LoopBack version, etc)

node v5.10.1
loopback 2.29.1

**Comment by jannyHou** [comment]
`principleId` ---> should be `principalId`
