### ISSUE TITLE
Throttle request in remote method

### ISSUE THREAD

**Issue by hoangtrongphuc** [strongloop/loopback#2913]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)
I want to limit request to remote method, each method has diff config for throttle request.

### Expected result
In remote method config: 
```
Person.remoteMethod(
        'greet', 
        {
          limit: {max: 40, time: 1000, delay: 1000} // max 40 request/1s with delay 1s after each request
          accepts: {arg: 'msg', type: 'string'},
          returns: {arg: 'greeting', type: 'string'}
        }
    );
```

**Comment by jannyHou** [comment]
thank you @hoangtrongphuc for the feature!

**Comment by hoangtrongphuc** [comment]
Do I need open PR to add this feature in strong-remoting ?

**Comment by jannyHou** [comment]
I think so. 
cc @gunjpan @deepakrkris Any idea or suggestion?
