### ISSUE TITLE
Override remote method, passing through current context

### ISSUE THREAD

**Issue by PaddyMann** [strongloop/loopback#2915]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

We have guidance on how to override an existing remote method (see #443), but I'm yet to find an example that allows us to pass through the current context as can easily be done when adding a new remote method.

This didn't use to cause problems as I used getCurrentContext to grab the userId. This is now deprecated with no clear solution (see #1495). 

As a result, I can't see an simple solution to this problem and would like this to be either be possible, or else the documentation updated to show how best to do this.

### Additional information (Node.js version, LoopBack version, etc)

Loopback 2.36.0

**Comment by deepakrkris** [comment]
@PaddyMann  use of getCurrentContext() is deprecated and a new approach is documented under https://loopback.io/doc/en/lb2/Using-current-context.html

@superkhau do you have any information to add here ?

**Comment by PaddyMann** [comment]
At this point I've stopped trying to overide the standard functions and instead have disabled them and created new ones.

This isn't what I'm used to with other frameworks, but it's fine. I'll update my comments on #443 to indicate this is the case.
