### ISSUE TITLE
How should I use virtual properties in loopback?

### ISSUE THREAD

**Issue by Amastyer** [strongloop/loopback#2918]
Use Object.defineProperty?

``` javascript
Object.defineProperty(MyModel.prototype, 'test', {
  get() {
    return 'test';
  },
});
```

When I call myModel.test,the result obtained is 'test'.
When I request GET /MyModel/:id, but there is no test property in the returned object.

**Comment by phra** [comment]
functions (so also ES5 getters/setters) are never serialized in JSON so you can not send it via HTTP. just use a regular property instead.

**Comment by deepakrkris** [comment]
@Amastyer adding 'test' property in the MyModel object will not add that to loopback model definitions. If you would want to add a property to a model , it would be in the model configuration json file

**Comment by deepakrkris** [comment]
@Amastyer please do let me know if you have any questions
@superkhau it seems reasonable for me to close this issue, do you agree ?
