### ISSUE TITLE
Shortcut for changing property default value

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#292]
When defining a model code-first, one can specify a dynamic default value for properties:

``` js
registrationDate: {type: Date, default: function () { return new Date() }},
```

This is not possible to achieve when using `app.boot()` and `models.json`. This is the currently recommended solution:

``` js
app.models.Todo.definition.rawProperties.created.default =
app.models.Todo.definition.properties.created.default = function() {
  return new Date();
};
```

@raymondfeng suggested there should be a helper method making this easier.

Related: https://groups.google.com/forum/#!topic/loopbackjs/tIlPMxVZXwE

**Comment by seriousben** [comment]
The following code is not a workaround since it is executed everytime causing the created date to change. It is a workaround for the updatedAt timestamp.
```
app.models.Todo.definition.rawProperties.created.default =
app.models.Todo.definition.properties.created.default = function() {
  return new Date();
};
```

**Comment by bajtos** [comment]
> The following code is not a workaround since it is executed everytime causing the created date to change.

Could you please provide more details, ideally a small example that we can run to reproduce the problem?

**Comment by inawlaljar** [comment]
Hi, Did we reach on any conclusion (and also implemented) a way to set default value for a model? 

I want to set created and lastupdated fields. 

I am currently using hooks. Let me if that's the right way to set default value.

Ta.

**Comment by bajtos** [comment]
The implementation of `$now` as a `Date` default value has landed in juggler's master: https://github.com/strongloop/loopback-datasource-juggler/pull/445

> @inawlaljar I want to set created and lastupdated fields.

You can use `$now` for the `lastupdated` field once the new juggler version is released. `created` field is tricky to get right, because `createOrUpdate` does not know in advance whether the `created` column should or should not be updated.

**Comment by bajtos** [comment]
> You can use `$now` for the `lastupdated` field once the new juggler version is released. `created` field is tricky to get right, because `createOrUpdate` does not know in advance whether the created column should or should not be updated.

My last comment was rather incorrect, let me correct.

There is no out-of-the-box way how to implement `lastupdated` model property. The right approach is to use a `before save` hook, indeed. 

The `created` property can be implemented with `default: '$now'` and it will work as long as the calls of `updateOrCreate` are always passing the full object data retrieved from the database in the "update" case.

```js
// this works and preserves the value of the "created" property
Product.findById(existingId, function(err, prod) {
  prod.name = 'renamed';
  Product.updateOrCreate(prod);
});

// this updates the value of the "created" property to the current time
var prod = new Product({ id: existingId, name: 'renamed' });
prod.updateOrCreate(prod);
```

**Comment by bajtos** [comment]
FYI, #453 implemented `defaultFn` option that accepts one of `guid`, `uuid` or `now`.

**Comment by mike-aungsan** [comment]
This property does not work.

"properties": {
  "testUuid": {
      "type": "string",
      "description": ["Just A Number field to Test defaultFn and Error Message.", 
                      "..."],
      "default": "$uuid",
      "required": false
    },
}

Anything wrong?

**Comment by bytecodedan** [comment]
I haven't quite figured it out but I have deployed a sample app on OpenShift and it fails to start because of this default feature.  However, it's fine running locally.

/var/lib/openshift/570be5c42d5271676e00002e/app-root/runtime/repo/node_modules/loopback/common/models/application.js:70
  Application.definition.rawProperties.created.default =
                                                       ^
TypeError: Cannot assign to read only property 'default' of date *

**Comment by Synryu** [comment]
@bajtos , concerning the "now" default for Date type, is there a way to set the seconds (and millisec) to 0 ?

It wasn't an issue until I had to implement a client-side generic change detector. If the user change a date or datetime and then set back the original value, a change is still detected because the secs and millisecs are gone.

**Comment by bajtos** [comment]
@Synryu have you tried `default: 0`? I don't have enough information to meaningfully help you. Please open a new issue and provide us with a small app showing how to reproduce the problem you are experiencing, per our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report).

**Comment by bajtos** [comment]
I am going to lock this conversation down. Please open new GitHub issue(s) if there is anything remaining to discuss.
