### ISSUE TITLE
Image not upload.

### ISSUE THREAD

**Issue by ghost** [strongloop/loopback#2921]
Image uploading api was stuck and in response its gives nothing..but after sometimes in command its gives request aborted..
i have use loopback for last 1 year but before 2 days upload api was stuck ..please give me solution..

**Comment by Amir-61** [comment]
Could you please let me know the steps to re-produce the issue? Or alternatively can you reproduce the issue using [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) that I can run on my local machine?

Thanks!
