### ISSUE TITLE
Remote method route without or has alias model name in path

### ISSUE THREAD

**Issue by cphpham** [strongloop/loopback#2925]
Is it possible to define a remote method route without the model name in the path?

The documentation only describes how to change method names: http://loopback.io/doc/en/lb2/Remote-methods.html#setting-a-remote-method-route

Default: GET /apiRoot/modelName/methodName
Desired: GET /apiRoot/methodName or GET /apiRoot/aliasModelName/methodName

Need some help here, who can help?

**Comment by ekta-slit** [comment]
Help on above issue will be realy helpful!

**Comment by dharmendrasdlt** [comment]
It would be great if some one can help or resolve this.. as every other API requires desired routes in REST!!

**Comment by deepakrkris** [comment]
REST endpoints can be customized using the http.path setting in model definition json : http://loopback.io/doc/en/lb2/Customizing-models.html#customizing-other-model-settings

example:
{
  "name": "modelName",
  "plural": "/",
  "http": {
    "path": "/aliasModelName" or "path": "/aliasModelName/version1"
  },
  "base": null,
  "idInjection": true,
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
