### ISSUE TITLE
Put back issues tabs

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback#2929]
For a small set of repos, we removed the issues tab and redirected users to strongloop/loopback/issues (i.e. https://github.com/strongloop/loopback-ibmdb). After this short trial period, I feel this is a clunky experience for the end users.

I am proposing we revert these changes and put the issues tabs back in and do not redirect users to strongloop/loopback/issues.

Thoughts?

@bajtos @ritch @raymondfeng @strongloop/loopback-dev

**Comment by bajtos** [comment]
> I am proposing we revert these changes and put the issues tabs back in and do not redirect users to strongloop/loopback/issues.

+1 ✖️ 💯  from me.

I find the missing "issues" link in the GitHub UI confusing, one has to go to README and then follow the link to loopback issue tracker.

I also want to grow the number of community contributors/maintainers. To help that, I think it's important to have a designated place where to keep track of issue and discussions related to each repository, without having to filter out all other discussions. I.e. if I wanted to contribute to loopback-sdk-angular only, then I would want to watch only that repository (possibly together with cli, grunt and gulp). That's not possible with a single shared issue tracker in loopback repo.

**Comment by ritch** [comment]
I agree with the idea in general.

> I am proposing we revert these changes and put the issues tabs back in and do not redirect users to strongloop/loopback/issues.

What if we start with: 

 - strong-remoting
 - loopback-datasource-juggler
 - loopback-connector-*
 - loopback-example
 - loopback-sdk-*

I'm also 👍 for just reverting entirely. Just wondering if we might have some repos that get missed during triage since no one looks at them.

**Comment by superkhau** [comment]
@ritch I'm going to propose do it entirely, don't want to be in the state where is half done/half not like now -- the trial run is over.

>Just wondering if we might have some repos that get missed during triage since no one looks at them.

Yeah, we need to draw the lines on who is taking care of which repos cross squad so we can all take ownership and not miss any repos.

**Comment by superkhau** [comment]
@sspai Take a look at https://github.com/strongloop/eslint-config-loopback

Note the following:

- We have no "issues" tab
- The first lines in the README is a warning to post issues at strongloop/loopback/issues
- package.json also redirects users to https://github.com/strongloop/eslint-config-loopback/blob/master/package.json#L20

Your task is as follows:

Go through all the repos in the strongloop org and put back the issues tab in relevant repos that are missing them:

- [ ] Pair program with @superkhau to figure out which repos are relevant and put back issues tabs (requires admin -- we can do it over Hangout)
- [ ] Remove all the warning lines the README of the affected repo
- [ ] Modify package.json's "bug" property to point at it's own issues tab (instead of loopback's)

For the last items, you will send a PR to each affected repository and ping me to review and merge accordingly.

**Comment by siddhipai** [comment]
@superkhau 
The repos which does not have issues tab are:
```
loopback-connector-kv-extreme-scale
loopback-getting-started-intermediate
loopback-connector-dashdb
eslint-config-loopback
loopback-getting-started
loopback-ibmdb
loopback-connector-mqlight
loopback-connector-informix
loopback-connector-db2z
loopback-example-kv-connectors
loopback-example
strong-swagger-ui
loopback-api-definition
strong-swagger-js
openshift-cartridge-strongloop
strong-debugger
dbload-example-app
```

**Comment by superkhau** [comment]
@siddhipai I checked off all the items and put the issues tab back for each of the above. You should be good to go with sending the PRs to each of the above.

**Comment by siddhipai** [comment]
Repo status for README.md and package.json

- [ ] https://github.com/strongloop/loopback-connector-kv-extreme-scale
- [ ] https://github.com/strongloop/loopback-getting-started-intermediate
- [ ] https://github.com/strongloop/loopback-connector-dashdb
- [ ] https://github.com/strongloop/eslint-config-loopback
