### ISSUE TITLE
The default for strict should be true

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback#2932]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Ok, technically this isn't a bug, but hear me out. Yesterday I discovered that by default. LB APIs allow you to pass unknown properties. So given a model called Cat with properties for name and age, I can send a prop called foo and LB just accepts it. I've heard the following reasons for this:

a) It is good for prototyping
b) Mongo and NoSQL dbs have no issue with it

I think this is flawed for a few reasons. First off - the fact that Mongo is behind the scenes is *not* relevant. We are talking about an API feature here. The fact that a NoSQL solution is handling the persistence is inconsequential. 

Also, I think that most APIs would disallow random properties. If I say a cat is X, Y, and Z, I should expect X,Y,Z, not some additional random data you happen to send. The API is a contract, and LB is basically saying I can send whatever I want.

I'm not saying that doesn't *ever* make sense, but it seems like for a vast majority of APIs, they would not want this behavior. 

As for reason A... well I guess I see it, but I don't think it outweighs the negatives. 

### Additional information (Node.js version, LoopBack version, etc)

**Comment by superkhau** [comment]
@cfjedimaster I agree, seems odd to default to the prototyping case. Should just reject unknown properties -- and at the HTTP level, either 400 or 422 if you want to be more precise I suppose.

**Comment by cfjedimaster** [comment]
I would argue for throwing an error, not ignoring, but I'd settle for anything but strict:false being the default. ;)

**Comment by superkhau** [comment]
I would advise against throwing an err, but return one with a descriptive message via callback -- and having strong remoting return the correct error code higher up.

**Comment by cfjedimaster** [comment]
Well I think we need to stick to what behavior we have now in terms of strict behavior. We're just talking about changing a default. I don't think what you describe is supported, is it? Or is it one of the options.

**Comment by superkhau** [comment]
No, it's not one of the options. Yes, we're on the same page of changing the default setting. I'm just curious as to this:

>Also, I think that most APIs would disallow random properties. If I say a cat is X, Y, and Z, I should expect X,Y,Z, not some additional random data you happen to send. The API is a contract, and LB is basically saying I can send whatever I want.

Are you talking about programmatic usage or via API explorer? I'm assuming we want both, ie. the error when you call `Cat.create({foo: 'invalid-property'})` and when someones performs a req via `POST /api/Cats` with json `{"foo": "invalid-property"}`.

**Comment by cfjedimaster** [comment]
Oh interesting. So... I'd expect the same behavior. If strict is false, then both "just work" (although in non-NoSQL it's going to throw an error anyway). And for the other values... yeah, I'd expect it be the same throughout.
