### ISSUE TITLE
Document what $owner checks

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback#2934]
### Bug or feature request

- [x ] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

The rules for how $owner work (
1) a relation to a model that extends user. 2) a simple property called userId. 3) a simple property called owner) are not actually documented.

**Comment by crandmck** [comment]
Could you please suggest where in the docs we should add this.  Pointers to examples, or related issues would also help.

**Comment by cfjedimaster** [comment]
Sorry for the delay in responding. I'd say maybe here: http://loopback.io/doc/en/lb2/Authentication-authorization-and-permissions.html. In the table cell that discusses $owner.

**Comment by crandmck** [comment]
Thanks @cfjedimaster So, IIUC, the table cell should be...

Dynamic role: 
 - $everyone (for all users). A relation to a model that extends user. 
- a simple property called userId. 
- a simple property called owner

Is that right?

**Comment by cfjedimaster** [comment]
Yep!

**Comment by crandmck** [comment]
Fixed, thanks!
