### ISSUE TITLE
Set default value for arg when the http.source property is body - remote methods.

### ISSUE THREAD

**Issue by FraserChapman** [strongloop/loopback#2943]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

If one defines a remote method, one can set the accepted args names, types and default values. 
However if one sets the default value for an arg where the http.source is body the default value is ignored.

### Link to sample repo to reproduce issue (if bug)

e.g.
```
Foo.remoteMethod('foo', {
    accepts: { arg: 'data', type: 'object', http: { source: 'body' }, default: '{"bar":"string"}' }
});
```
### Expected result

I would expect the data textarea in the StrongLoop API Explorer to be populated with the object.

```
{
    "bar": "string"
}
```

### Actual result (if bug)

The data textarea is empty

### Additional information (Node.js version, LoopBack version, etc)

node@v4.6.2
loopback@2.27.0
loopback-swagger@2.2.3

**Comment by deepakrkris** [comment]
@FraserChapman the 'default' field is only to populate the loopback-explorer UI screen fields, it will not auto-populate the API inputs.
https://loopback.io/doc/en/lb2/Remote-methods.html#argument-descriptions
And also to add... for field type http:body the explorer does not allow input values, so this feature is not available
