### ISSUE TITLE
With nestRemoting ACL should work for FK by default

### ISSUE THREAD

**Issue by tspoke** [strongloop/loopback#2948]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

At the moment, nestRemoting doesn't create endpoint for custom remotes. The solution, describe here (https://github.com/strongloop/loopback/issues/1859#issuecomment-163037446) is working but has a problem with ACLs.
With nestRemoting, default generated endpoints like `GET /api/Store/:id/app/:fk` do an ACL check and will prevent unauthorized users to access to the resource. This is an expected behaviour and it's great ! But, for custom endpoint forwarded from the parent Model, this check won't occured for the FK but only for the ID.

An example of a forwarding through Store to App :  

```
        Store.upload = function(ctx, id, fk, cb) {
		Store.app.models.App.upload(ctx, fk, cb);
	};
	Store.remoteMethod(
		'upload',
		{
			accepts: [
				{ arg: 'ctx', type: 'object', http: { source:'context' } },
				{ arg: 'id', type: 'Number', required: true},
				{ arg: 'fk', type: 'Number', required: true}
			],
			http: {path: '/:id/app/:fk/upload', verb: 'post'},
			returns: {
				arg: 'app', 
				type: 'Object'
			}
		}
	);
```

In this case, the ACLs will work for the ID of the store (if the key is `'id'`) but won't on the FK. I think it could be great if loopback do the same for the FK.

For now I will do a manual check to verify that the app belongs to the store, but I think it should be automatized.

**Comment by jannyHou** [comment]
This could be a sub story of supporting second level custom remote method. A propagated ACL should be applied to the related model's custom method.

**Comment by tspoke** [comment]
Maybe this feature is more a 'patch' to an not completed feature : nestRemoting.

NestRemoting should include custom remote, and if it does this ACL problem will disappear by itself.

I'm limited with loopback with nestRemoting (3 childs model depth limitation, ACL,...). This method should be more powerful, I would love to do this kind of thing with ACL check : 

```
GET api/Store/:id/app/:fk/item/:itemId/element  ...
```

**Comment by tspoke** [comment]
Does this improvement is implemented in LB 3 ? If not, it should't be close IMO
