### ISSUE TITLE
Token middleware not accepting custom model

### ISSUE THREAD

**Issue by codephobia** [strongloop/loopback#2950]
I have been trying to implement a custom access token model so that I can store additional information on the token itself (login source, ie. website, desktop app, etc), but when I do this, the access token is no longer accessible from req.accessToken, and instead returns null.

The easiest test is that you will get a 500 error on user logout, and the token will not be removed from the database, as it cannot find the access token. I've tried changing the way I init the middleware in my boot script using both of the following:

```
    app.use(loopback.token({
        model: app.models.MyAccessToken
    }));
```
And...
```
    app.middleware('auth', loopback.token({
        model: app.models.MyAccessToken
    }));
```

I even tried passing the model name as a string, since the docs say that this is an option, but upon looking at the code, it appears this is not the case.

I was able to get this working by editing the source code of loopback in `server/middleware/token.js` and replacing this:

```
    if (!TokenModel) {
      if (registry === loopback.registry) {
        TokenModel = options.model || loopback.AccessToken;
      } else if (options.model) {
        TokenModel = registry.getModel(options.model);
      } else {
        TokenModel = registry.getModel('AccessToken');
      }
    }
```
with this:
```
    if (!TokenModel) {
        TokenModel = registry.getModel('MyAccessToken');
    }
```

After that change it all works as expected.

Currently using loopback 2.27.0 and it doesn't appear that the latest version of the token.js file tackles this issue - so I haven't bothered upgrading yet.

**Comment by codephobia** [comment]
BUMP. Would really hate to change the source code in loopback to work around this. Hoping someone has a solution for me and that I am just missing something.

**Comment by jorafali** [comment]
I just posted on the google group with the same issue thinking it was coming from me trying to setup my accessToken via middleware.json.

https://groups.google.com/forum/#!topic/loopbackjs/af_wBNJz3Ps

Out of curiosity : do you know what the registry condition is actually trying to test for ?

**Comment by codephobia** [comment]
No idea, but I did notice that for me, it is the only condition firing.

**Comment by jorafali** [comment]
Another BUMP as I upgraded from LB3 to LB3.2. I had to redo the nasty hard coded fix. 
Is it not on anyone's radar because everyone else fiddles with the source code or is everyone somehow managing to never have a custom model based on AccessToken ?
