### ISSUE TITLE
firebase connector feature

### ISSUE THREAD

**Issue by jjhesk** [strongloop/loopback#2951]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)
Is that a good idea to have firebase connector the share the information from the firebase to the rest of the data pool in loopback? i think it is very demanding.

**Comment by ritch** [comment]
I would really like to implement this, but its not something we can even consider in the near term. If many people chime in asking for it we can re-open the issue, so speak up!

Feel free to build your own connector, it shouldn't be that difficult for firebase:
http://loopback.io/doc/en/lb2/Building-a-connector.html
