### ISSUE TITLE
Disabling createChangeStream doesn't hide the GET endpoint from anonymous users

### ISSUE THREAD

**Issue by cashweaver** [strongloop/loopback#2952]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Running `myModel.disableRemoteMethodByName('createChangeStream')` should cause the `GET` endpoint to return a 404/500 error. The correct error code is returned for $authenticated and $owner roles, but not for $anonymous. An $anonymous user making a request to the `GET` endpoint for `createChangeStream` receives a 401 error.

Notably the `POST createChangeStream`, `POST updateAll`, and `POST upsertWithWhere` respond appropriately with a 404. It seems this bug only occurs for non-`POST` requests

This bug occurs for other endpoints as well:
- `GET count`
- `GET findOne`
- `PUT replaceOrCreate`

### Link to sample repo to reproduce issue (if bug)

```js
// server/models/somemodel.js
module.exports = (SomeModel) => {
  SomeModel.disableRemoteMethodByName('createChangeStream');
};
```

```sh
# Start the server
$ npm start

# Issue the GET request
$ curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://localhost:3000/api/<themodel>/change-stream
```

### Expected result

404/500 status code

### Actual result (if bug)

401 status code

### Additional information (Node.js version, LoopBack version, etc)

Node v6.9.1
Loopback v3.0.0

**Comment by bosco-li** [comment]
@cashweaver Thank you for opening the issue by following the template, this helps us a lot to understand the issue.

To me this seems to be a valid error code as we do not want to expose what resources is available and what is not to an anonymous user.

@superkhau comment?

**Comment by superkhau** [comment]
I would expect 404 as suggested by @cashweaver. @bosco-li Can you verify the results (by reproducing on your machine? If you get 401, then label this issue as a bug and move to needs priority as usual.

**Comment by upupzealot** [comment]
Same problem, it seems the new method 'disableRemoteMethodByName' is not working.
It did stops the remote method from using(in code 401), but, the method still shows in the explorer.

**Comment by PaddyMann** [comment]
This behavior differs to `disableRemoteMethod` which correctly hides the endpoint, but unfortunately now raises a `deprecated` warning.

A side effect of this is that for APIs with numerous models and most of the endpoints disabled, the API explorer becomes become pretty useless as it's so painful to navigate.
