### ISSUE TITLE
When my sharding key have two fields, loopback does not support to locate a model using two fields.

### ISSUE THREAD

**Issue by elfahxh** [strongloop/loopback#2955]
### Bug or feature request

- [ x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
I created two Models,  Model-B is an embedded model in Mode-A, Model-A must have sharding key which have two fields. When I call such related method,  Model-A.Model-B.create(), will failed.
The root-cause is that, underline, it will call updateAttributes() of Model-A,  while the search filter only have "_id" field, cannot define a combined multiple keys to find Model-A from database. hence, will encounter a failure.

**Comment by jannyHou** [comment]
@elfahxh We have an issue to track "Supporting composite foreign key in loopback":
https://github.com/strongloop/loopback/issues/2080

I migrated your comment to that issue and let's keep all discussion there. I am closing this issue as a dup. Thanks for understanding.
