### ISSUE TITLE
Parameter cardId is ignored in CartItem.sum

### ISSUE THREAD

**Issue by tomers** [strongloop/loopback#2963]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
The cardId parameter is ignored in `example/client-server/models.js`.

### Expected result

```javascript
CartItem.sum = function(cartId, callback) {
  this.find({ where: { cartId: cartId }}, function(err, items) {
```

### Actual result (if bug)

```javascript
CartItem.sum = function(cartId, callback) {
  this.find({ where: { cartId: 1 }}, function(err, items) {
```

**Comment by Amir-61** [comment]
@tomers Thanks for bringing this to our attention; it is fixed now by https://github.com/strongloop/loopback/pull/2973
