### ISSUE TITLE
PersistedModel.FindOrCreate returns a collection instead of an object

### ISSUE THREAD

**Issue by danielrvt** [strongloop/loopback#2969]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

When using promises with the `FindOrCreate` static method of the `PersistedModel`, the result is a collection instead of an object, but the documentation states that the result is a single object.

```
 Enduser.findOrCreate({where: {email: userFields.email}}, {
          email: 'example@dnd1.com',
          password: 'password',
      })
      .then(user => user.createAccessToken(999999)) // This doesn't work since user is a collection.
      .then(accessToken => next(null, accessToken))
      .catch(err => {
          console.log("ERROR", err);
          next(err);
      });
```

### Expected result

The response should be a single EndUser instance as stated in: http://apidocs.strongloop.com/loopback/#persistedmodel-findorcreate

### Actual result (if bug)

[EndUserInstance]

### Additional information (Node.js version, LoopBack version, etc)

Node version: 6.9.1
Loopback version: 2.36.0

**Comment by rahpuser** [comment]
It returns an array [ object created or not, created flag ]. Not sure if there is another way to handle this ? for me it looks good

**Comment by Amir-61** [comment]
`findOrCreate` returns an array; please see https://github.com/strongloop/loopback-datasource-juggler/blob/c8ade9e9d00737e8c4be266168b579ca9d72573e/test/manipulation.test.js#L1319-L1334

This needs some doc correction; I'm labeling it as `doc` so we will get it fixed soon. Thanks!

**Comment by kjdelisle** [comment]
@raymondfeng Should this return an array or an object? It seems to me like you wouldn't want multiple items back if more than one matches the given item.
