### ISSUE TITLE
'use strict' breaks supports for db connectors in lib/applications.js

### ISSUE THREAD

**Issue by ebarault** [strongloop/loopback#2978]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Adding 'use strict' in lib/application.js on recent code style review broke the support for db connectors here : https://github.com/strongloop/loopback/blob/master/lib/application.js#L427

### Link to sample repo to reproduce issue (if bug)

any loopback example app, just npm install a db connector (e.g. mongodb) and change the db  in datasources.json to be a db of that kind

```
{
	"db": {
		"name": "db",
		"connector": "mongodb",
		"host": "localhost",
		"port": 27017,
		"database": "loopback"
	}
}
```

### Expected result

no error

### Actual result (if bug)

````
/Users/Eric/carbip/loopback_tests/loopback-example-access-control/node_modules/loopback/lib/application.js:237
    throw err;
    ^

TypeError: Cannot create data source "db": Cannot create property 'name' on string 'mongodb'
    at dataSourcesFromConfig (/Users/Eric/carbip/loopback_tests/loopback-example-access-control/node_modules/loopback/lib/application.js:427:29)
````

### Additional information (Node.js version, LoopBack version, etc)
node v7
loopback v3 https://github.com/strongloop/loopback/commit/c3ab9320127cb7726e83b9668f641f7cb2a55692

**Comment by loay** [comment]
Thanks @ebarault Looking into your PR as well.

**Comment by loay** [comment]
PR is merged. Issue is fixed.
