### ISSUE TITLE
Installation dependency issues (Linux x64)

### ISSUE THREAD

**Issue by nhubbard** [strongloop/loopback#2981]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
Installation of the `apiconnect` package fails consistently when NPM attempts to install `fsevents`.

### Expected result
API Connect installs itself and everything is hunky-dorey.

### Actual result (if bug)
Installation of API Connect fails with an error about `fsevents` being unable to install on my platform (Linux x64).

```
$ sudo npm install -g apiconnect

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/lib
└── (empty)

npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "apiconnect"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.9
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nicholas/Documents/Programming/Node/npm-debug.log
npm ERR! code 1
```

### Additional information (Node.js version, LoopBack version, etc)
Node.js version: 6.8.0
NPM version: 3.10.9

Actual logfile is attached below.
[npm-debug.txt](https://github.com/strongloop/loopback/files/610297/npm-debug.txt)

**Comment by jannyHou** [comment]
@nhubbard apiconnect doesn't support node 6.x yet. Can you try with other versions?

**Comment by jannyHou** [comment]
@nhubbard Also the following link contains OS, hardware, prerequisites, etc.. of apiconnect:
http://www-969.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=D0880A20256111E5ABE72E1847D16897#!

You can find nodejs versions under "prerequisites"

**Comment by jannyHou** [comment]
@nhubbard Any update? Hope apiconnect is working with you.

**Comment by jannyHou** [comment]
I am closing it since original question is answered. Feel free to reopen it if needed.
