### ISSUE TITLE
Cannot define configs used by Express in config.json

### ISSUE THREAD

**Issue by f-w** [strongloop/loopback#2984]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
I defined config *trust proxy* in /server/config.json. This config is recognized by Express so I expect Express uses it. 

### Expected result
Express uses *trust proxy* setting to return client ip correctly as described in https://expressjs.com/en/guide/behind-proxies.html

### Actual result (if bug)
Express doesn't use the settings, and \<Modal\>.app.get('trust proxy') returns default value *false*.

### Additional information (Node.js version, LoopBack version, etc)
LoopBack@2

**Comment by Amir-61** [comment]
To make the triage process faster, I appreciate if you provide a sample repo using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) to reproduce the issue.

Thanks!
