### ISSUE TITLE
Implement Multi-tenancy Architecture in Loopback

### ISSUE THREAD

**Issue by beingshashi** [strongloop/loopback#2986]
Hi,

I was reading this document [Multi-tenant Arch.](https://docs.stormpath.com/rest/product-guide/latest/multitenancy.html) , we have got that we also need to have the exact structure.

Now the issue is , we have been already using loopback as our backend application. And we want to move to multi-tenant system.

So question is does LoopBack supports Multi-tenant system?

If yes how can we achieve it.?

Thanks.

**Comment by superkhau** [comment]
Closing this issue in favour #2901, please continue the discussion there.
