### ISSUE TITLE
setHeader error when using accessType `WRITE` with principalId `$everyone` when doing POST /api/_modelName_/change-stream

### ISSUE THREAD

**Issue by skyserpent** [strongloop/loopback#2989]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
Error: Can't set headers after they are sent.
server-0     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
server-0     at ServerResponse.res.setHeader (/Users/me/project/node_modules/loopback-explorer/node_modules/connect/lib/patch.js:134:22)
...

This happens when I reproduce the steps in actual result below. I simply created a model named `activity` on a fresh install, went to the API explorer to hit the API `POST /api/activities/change-stream` with `options` set to `0` (just a random number I entered in options) and the terminal threw that error.

### Expected result
Not to throw that error and send a response back to the API explorer.

### Actual result (if bug)
Screenshots (in order of steps):
1. ![alt text](https://s14.postimg.org/4mzzl4ib5/Screen_Shot_2016_11_28_at_9_50_10_PM.png "Logo Title Text 1")

2. ![alt text](https://s14.postimg.org/mbn4z04oh/Screen_Shot_2016_11_28_at_9_50_27_PM.png "Logo Title Text 1")

3. ![alt text](https://s14.postimg.org/5qk3xy7/Screen_Shot_2016_11_28_at_9_49.png "Logo Title Text 1")

### Additional information (Node.js version, LoopBack version, etc)
Argon, LoopBack 2.36.0, MacBook machine

**Comment by bosco-li** [comment]
@skyserpent Thank you very much for following the template to create this issue.  Much appreciated.

For our benefit and to ensure we are on the same page, can we have an repo to see the code where you encounter this problem?
