### ISSUE TITLE
Loopback context returning undefined in afterRemote method

### ISSUE THREAD

**Issue by grandhisubrahmanyam35** [strongloop/loopback#2991]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
If i trigger any method through afterRemote , In that methods loopback-context returning undefined.

**Comment by Amir-61** [comment]
@grandhisubrahmanyam35 

Not sure where you found this hook? AFICT, loopback supports `access`, `before save`, `after save`, `before delete`, `after delete`, `loaded`, `persist` and some remote hooks like afterRemote and `beforeRemote`; for OH please see: https://loopback.io/doc/en/lb2/Operation-hooks.html and for remote hooks please see:https://loopback.io/doc/en/lb2/Remote-hooks.html#overview

If this answers your question please let us know, so we close this ticket.

Thanks!

**Comment by grandhisubrahmanyam35** [comment]
@Amir-61 Sorry, I suppose to mention **afterRemote** .

**Comment by Amir-61** [comment]
@grandhisubrahmanyam35 could you reproduce your issue using [loopback-sandbox](https://github.com/strongloop/loopback-sandbox)?

Please see: http://loopback.io/doc/en/contrib/index.html#reporting-issues

**Comment by bajtos** [comment]
Also note that loopback-context is known to not work in certain common situations, for example when there is a connection pool involved. Let' move the discussion to loopback-context issue tracker.

**Comment by bajtos** [comment]
Issue moved to [strongloop/loopback-context #22](https://github.com/strongloop/loopback-context/issues/22) via [**ZenHub**](https://www.zenhub.com/)
