### ISSUE TITLE
update patchAttributes method name in base Model User (loopback v3)

### ISSUE THREAD

**Issue by ebarault** [strongloop/loopback#2994]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Model remote method name `patchAttributes` is not valid in base model User, and should be replaced by `prototype.patchAttributes` here : https://github.com/strongloop/loopback/blob/master/common/models/user.json#L65

### Expected result

patchAttributes is activated by default for any Model extending User base model

### Actual result (if bug)

patchAttributes is not activated by default for Models extending User base model

### Additional information (Node.js version, LoopBack version, etc)
loopback v3

**Comment by Amir-61** [comment]
>patchAttributes is not activated by default for Models extending User base model
I could not reproduece this issue with LB 3.0; please try https://github.com/strongloop/loopback-getting-started-intermediate on master branch which uses LB 3.0; there `reviewer` model extends the built-in user model; and still we have patchAttributes activated for this model; could you try to reproduce this issue using [loopbakc-sandbox](https://github.com/strongloop/loopback-sandbox)? Or alternatively you can send a patch with a test verifying this ^ is the case.

Please see: http://loopback.io/doc/en/contrib/index.html

Thanks

**Comment by ebarault** [comment]
@Amir-61 
hi, i should have made it clearer, i posted it quickly while it was fresh. once should have read "patchAttributes is not **authorized** by default for smart role $owner for Models extending User base model"

but... it appears my test config misled me : although non static method now should be deactivated appending the 'prototype.' prefix (e.g. `prototype.patchAttributes` to the method name, the methods should be referred to in ACLs without the prefix (e.g. `patchAttributes`). **My bad**.

Still this is inconsistent as a naming convention and could be blocking sometime since i could have to authorize 2 methods with the same name, but one static and on registered on prototype.
Any thoughts?
