### ISSUE TITLE
validatesLenghtOf not working on array

### ISSUE THREAD

**Issue by pierreclr** [strongloop/loopback#2995]
Hi,

I have a loopback app with a model (campaign) which embeds many campaignSteps on property steps. When I try to do 

`Campaign.validatesLengthOf('steps', { max: 7 })`

I can't create a campaign with an empty steps array and loopback crashes me a validation error

Any help would be welcomed

**Comment by Amir-61** [comment]
@pierreclr Based on what you described it seems it is a bug; however in order to make the triage process easier and come up with a `bug` label, could you please reproduce the issue with [loopback-sandbox](https://github.com/strongloop/loopback-sandbox)?

Thanks a lot!

**Comment by pierreclr** [comment]
Hi @Amir-61 I did what you expect from me : here is the repo https://github.com/pierreclr/loopback-sandbox 

I created two branches to describe my bugs with the related chai tests in server/test/:testName.js
The first branch which is called bug/validate-length-embedsMany reproduce the bug I was talking about.
The second one is about a bug on default scope which I think is not a operational feature

Could you please keep me up to date on theses bugs?

Thanks a lot

**Comment by Amir-61** [comment]
@pierreclr 

I could reproduce your bug for `emedsMany`. Thanks for reporting.

>The second one is about a bug on default scope which I think is not a operational feature

Let's please focus each GH issue for a specific bug instead of having more than one issue reported. Please create a new GH issue for that. Thanks!
