### ISSUE TITLE
where in relation

### ISSUE THREAD

**Issue by rohmanahmad** [strongloop/loopback#2996]
im sorry , im new in loopback.

how to implement this.

```
CI.getInboxByCompany = function( companyId, cb){
    CI.find({
      where:{
        'R_contactCenter' : {
          "id" : 'blablabla'
        }
      },
      include: [
        "R_contact", 
        {
          'R_contactCenter' : 'R_division'
        }
      ]
    }).then(function(res){
      return cb(null, res);
    }).catch(function(err){
      return cb(null, err);
    });
  };
```

**Comment by Amir-61** [comment]
Hey @rohmanahmad,

I'm afraid we have GH issues tab just for reporting `bugs` and `feature requests`; however we have https://groups.google.com/forum/#!forum/loopbackjs where both community and LoopBack experts can both help with your questions; would you mind please ask your question there? Thanks a lot 🙇
