### ISSUE TITLE
Customise error if access permission is DENY .

### ISSUE THREAD

**Issue by iolp** [strongloop/loopback#2997]
By default, if user doesn't have specific rights to, loopback sends:
`{
  "error": {
    "name": "Error",
    "status": 401,
    "message": "Authorization Required",
    "statusCode": 401,
    "code": "AUTHORIZATION_REQUIRED",
    "stack": "Error: Authorization Required"
  }
}`
But what to do if i want send custom messages and, maybe status, about permissions requirements ?

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

That said, you can create remote methods that return whatever you need. See https://github.com/strongloop/loopback-example-app-logic#define-a-remote-method
