### ISSUE TITLE
Custom Role registerResolver

### ISSUE THREAD

**Issue by dahuahe** [strongloop/loopback#3012]
if i custom ROLE  example 
in *RoleMapping* data
> {id:1,principalType:"ROLE",principalId:"admin",roleId:1}

in *Role* data
> {id:1,name:"admin",description:"admin"}

in *User* data
>{id:1,username:"test",password:"123"}

one model have the acl
>"acls": [ {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },{
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    }]

i find if it work only use **role.registerResolver('admin',function(){})>>>>return true**
if i have many role  i must to write *many*
 **role.registerResolver(role_name_string,function(){})>>>>return true**
??
this is troublesome

**Comment by dahuahe** [comment]
somebody help

**Comment by bosco-li** [comment]
@dahuahe We do not support multiple this with our function call.

To solve your problem, a proposal is to take a look at promistify the function and use methods like promise.map to make the coding easier for you.

**Comment by pr3mar** [comment]
I have a similar problem, if I do not explicitly state the principalId of a particular user in the acls of a model, then loopback does not remap the principalId to a name of a role.
