### ISSUE TITLE
[Security] streamline errors for non-existant access token and expired access token

### ISSUE THREAD

**Issue by dkarlovi** [strongloop/loopback#3022]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

When handling an access token, Loopback will issue different error messages depending on the type of failure: 

1) when the **access token is expired**, `access-token.js` will [state](https://github.com/strongloop/loopback/blob/master/common/models/access-token.js#L110-L112) "Invalid access token", code `INVALID_TOKEN`
2) when the **access token is non-existant**, `application.js` will [state](https://github.com/strongloop/loopback/blob/master/lib/application.js#L384-L385) "Authorization Required", code `AUTHORIZATION_REQUIRED`

Both will issue HTTP status code 401 (which is correct).

As output from this actions is directly served to the remote client, it discloses the state of the supplied access token directly.

### Expected result

Streamlined error message, regardless if access token non-existant, expired or invalid in any other way. If the access token is not valid, it's invalid.

### Actual result (if bug)

Specific error messages for these two states, thereby granting a information disclosure (leak) on the state of the access token to the attacker.

**Edit**: pasted wrong URL for `application.js`, fixed.

**Comment by bosco-li** [comment]
@dkarlovi Thank you for the time you spent on creating this issue.  I'll put this as a bug in our backlog and prioritize this to work on.

**Comment by loay** [comment]
@dkarlovi 
The developer needs to know the appropriate error message in order to be able to debug in debugging/development mode. 
If you are talking about production mode. Please refer to https://github.com/strongloop/strong-error-handler
You can configure it in order not to show the sensitive information in the error message

**Comment by dkarlovi** [comment]
@loay this is not part of a stacktrace or something, this is when in production mode.
