### ISSUE TITLE
Related models don't get updated when updating a model

### ISSUE THREAD

**Issue by sffetlio** [strongloop/loopback#3024]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
I have two simple models Account and Background. Account has 
```
"relations": {
    "background": {
      "type": "belongsTo",
      "model": "Background",
      "foreignKey": ""
    }
  },
  "scope": {
    "include": [
      "background"
    ]
  }
```
Steps to reproduce:

1. Create an Account
2. Create two backgrounds
3. Use PUT /Accounts/{id} with {"backgroundId": 1} to set a background for the account. Result:
```
{
  "id": 1,
  "backgroundId": 1,
  "background": {
    "id": 1
  }
}
```
4. Use PUT /Accounts/{id} again with {"backgroundId": 2} to change the background. Result:
```
{
  "id": 1,
  "backgroundId": 2,
  "background": {
    "id": 1 //<-- notice the id here does not  change
  }
}
```

### Link to sample repo to reproduce issue (if bug)
https://github.com/sffetlio/loopback-test

### Expected result
```
{
  "id": 1,
  "backgroundId": 2,
  "background": {
    "id": 2 //<-- id should be changed
  }
}
```

### Actual result (if bug)
```
{
  "id": 1,
  "backgroundId": 2,
  "background": {
    "id": 1 //<-- notice the id here does not  change
  }
}
```

### Additional information (Node.js version, LoopBack version, etc)
node.js v6.9.1
loopback@2.36.0

**Comment by bosco-li** [comment]
@sffetlio I'm looking at the issue now will get back to you on this.  Thank you for using the template, makes things much easier and quicker.

**Comment by bosco-li** [comment]
@sffetlio I've confirmed with @raymondfeng that we do not support aggregate update over relations in one shot, at least for the current version of LB.  

A possible way to workaround this I will suggest to add custom logic in the javascript file for the model you created

**Comment by sffetlio** [comment]
@bosco-li Thanks for the comment. Actually my issue is not with the update over a relation, but the 
```
 "include": [
      "background"
    ]
```
Correct me if I'm wrong but in my example the included background object is loaded by backgroundId. And when I change the backgroundId with a PUT request, the new background object should be included and returned as a response to the PUT. This is not the case. The new backgroundId is correctly set, but the included background object is not correct. If I do a GET request after that, everything is correctly returned. The issue happens only in the PUT response that changes backgroundId.
