### ISSUE TITLE
documentation does not show that disableRemoteMethod is deprecated

### ISSUE THREAD

**Issue by emckean** [strongloop/loopback#3026]
### Bug or feature request

- [ X] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

[Documentation for disableRemoteMethod](https://loopback.io/doc/en/lb3/Exposing-models-over-REST.html) does not indicate that this method is deprecated. 

### Additional information (Node.js version, LoopBack version, etc)

In both LB 2 and 3 docs.

**Comment by crandmck** [comment]
I was not aware of this...Why do you think it's deprecated?  The 3.0 release notes still say to use it: https://loopback.io/doc/en/lb3/3.0-Release-Notes.html#clean-up-of-api-for-finding-and-disabling-remote-methods.

**Comment by crandmck** [comment]
@bajtos Can you confirm that `disableMethodByname()` is deprecated?  If so, is it for 3.0 only or both 2.x and 3.0?

**Comment by emckean** [comment]
Hi -- I was going by this [line 439](https://github.com/strongloop/loopback/blob/7f2cdc106c61723543f9fb205f8298acd5f6633e/lib/model.js)

**Comment by crandmck** [comment]
OK this should be added to the API docs as well.  But my question to @bajtos stands: just for 3.0?

**Comment by ritch** [comment]
> As part of the work on the above change, add new SharedClass methods findMethodByName and disableMethodByName in both 2.x and 3.0. The old methods find and disableMethod are deprecated in 3.0.

from https://strongloop.com/strongblog/coming-soon-loopback-3-0/

**Comment by bajtos** [comment]
> just for 3.0?

Yes, only for 3.0, as was described in the "coming-soon" blog post.

See [lib/model.js](https://github.com/strongloop/loopback/blob/18a89e556a629cb0c7367c6ca586c7fed9ea70a4/lib/model.js#L443-L447) in the 2.x branch.

**Comment by crandmck** [comment]
Updated in loopback.io docs.  Need to update API docs also.

**Comment by crandmck** [comment]
API docs are now updated: http://apidocs.strongloop.com/loopback/#model-disableremotemethodbyname

**Comment by mkohlmyr** [comment]
@crandmck fwiw, I think API docs have regressed, I can't see any note in there about `disableRemoteMethod` being deprecated, despite the logging message still being in current source.

 - https://loopback.io/doc/en/lb3/Remote-methods.html#disabling-a-remote-method
 - http://apidocs.loopback.io/loopback/#model-disableremotemethod
 - https://github.com/strongloop/loopback/blob/b77907ffa59c7031fcb3bb6dbff96894bc597ba4/lib/model.js#L526-L532
