### ISSUE TITLE
Transactions on Rectify

### ISSUE THREAD

**Issue by kobaska** [strongloop/loopback#3027]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature

Pass transaction through to rectifyOnSave and rectifyOnDelete functions which get called on the after save and after delete hooks.

**Comment by kobaska** [comment]
I see two options we could do:

1) Pass options object through to all the calls related to rectify
which means we have to add options to PersistedModel.rectifyChange, Change.rectifyAllChanges and Change.rectifyModelChanges:

PersistedModel.rectifyChange = function(id, **options**, callback) {
.....
  };

Change.rectifyModelChanges = function(modelName, modelIds, **options**, callback) {
}

2) Disable rectify when transaction exist, let the client handle rectify (Which is not great)

From : 
Model.observe('after save', rectifyOnSave);

To: 
```
Model.observe('after save', function(ctx, next) {
 if (ctx.options.transaction) {
   next();
 } else {
   rectifyOnSave(ctx, next);
 }
});
```

**Comment by kobaska** [comment]
Hey @bajtos, Can you please give your view on this, whether transaction is something you have thought about in replication scenarios?

**Comment by bajtos** [comment]
Hi @kobaska, your first proposal makes a lot of sense to me, we should add `options` argument to `rectify*` methods. This will also enable context-propagation as proposed/implemented by #3023 (see also #1495).

Would you mind contributing this improvement yourself?

**Comment by ericmorentin** [comment]
Greetings. I am a college of @kobaska. Am starting work on adding options to rectify methods this week.

**Comment by bajtos** [comment]
@ericmorentin Great, I'm looking forward to your contribution(s)!
