### ISSUE TITLE
Rename User model to BaseUser

### ISSUE THREAD

**Issue by JonnyBGod** [strongloop/loopback#3028]
### Bug or feature request
- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

As per https://loopback.io/doc/en/lb3/Using-built-in-models.html#user-model, "You must create your own custom model".

Given that, it would be better to rename the **User** model to **BaseUser** so that we could name our own model **User**.

In some cases the best name to call it in our apis is just **User**.

### Expected result
```
{
  "name": "User",
  "plural": "Users",
  "base": "BaseUser",
  ...
}
```

**Comment by RodrigoCS** [comment]
+1

**Comment by nombienombie** [comment]
+1

**Comment by Donluigimx** [comment]
> This issue has been closed due to continued inactivity. Thank you for your understanding. If you believe this to be in error, please contact one of the code owners, listed in the CODEOWNERS file at the top-level of this repository.

That means this is not happening?

**Comment by pereztechseattle** [comment]
This should be fixed!

**Comment by pereztechseattle** [comment]
I added this to my package.json.  Hope this helps someone.

"postinstall": "sed -i -e 's/User/BaseUser/g' node_modules/loopback/common/models/user.json",
