### ISSUE TITLE
Loopback remote method with Multipart request 

### ISSUE THREAD

**Issue by ayon115** [strongloop/loopback#3039]
Hello, Can anybody provide me a sample code of a loopback remote method that's a multipart request having both text and a file in it's body ?

**Comment by superkhau** [comment]
@ayon115 Please ask question using our Google Groups or Gitter, see http://loopback.io/doc/en/contrib/Reporting-issues.html#asking-questions for more details. Closing as this is not an bug/feature request.

**Comment by superkhau** [comment]
That said, how about https://groups.google.com/forum/#!searchin/loopbackjs/multipart|sort:relevance/loopbackjs/-7xumo0V8qg/tPKDfnABTXwJ
