### ISSUE TITLE
Support INNER JOIN vs LEFT JOIN definition in model relation

### ISSUE THREAD

**Issue by archenroot** [strongloop/loopback#3049]
This is possible feature request.

I would like to define either to use inner or left (outer) join when joining two models. 

This could be implementeed as:
1. either inner or left is used by default for any JOINs
or
2. Both supported at the same time, which will then require 2 methods available instead of one supported in the moment.

We have for example URI:
/parent/1/childs

So we could have something obscure like this (dummy example):
/parent/1/childsLEFT
and
/parent/1/childsINNER

But I don't think this is nice way, so we could also make LEFT join default and make a switch in the JSON model, something like this:
```
"relations": {
    "customer": {
      "type": "belongsTo",
      **"joinType: "INNER"**
      "model": "Customer",
      "foreignKey": ""
      
    }
```

But that looks to me also ugly. Now in my head I see then only extend existing type of relations like:
from existing "type": "belongsTo",

will become 2 "type": "belongsToInclusive", and "type": "belongsToExclusive",

Was just idea... need some brainstorming.

**Comment by loay** [comment]
Hi @archenroot 
Please follow up with these 2 issues:
https://github.com/strongloop/loopback/issues/517
https://github.com/strongloop/loopback/issues/683

Thannks

**Comment by loay** [comment]
closing in favor of the other 2 issues, since it is a duplicate. for additional info, please feel free to leave a comment. Thanks.
