### ISSUE TITLE
Schema autoupdate fail if property mysql.columnName contains "_" character and mysql datatype is ENUM

### ISSUE THREAD

**Issue by hishamjaved** [strongloop/loopback#3061]
### Bug or feature request

- [x ] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
If property mysql.columnName contains underscore in the name and its mysql.dataType is ENUM then it produced the following error message during autoupdate() but not in automigrate()

Error: ER_BAD_FIELD_ERROR: Unknown column 'photoType' in 'user-common'

Error prone property Syntax
"photo": {
      "type": "string",
      "mysql": {
        "columnName": "photo_type",
        "dataType": "ENUM",
        "dataLength": "'GIF','PNG','JPG','JPEG'",
        "nullable": "N"
      }
    },

Working property Syntax
"photo": {
      "type": "string",
      "mysql": {
        "columnName": "phototype",
        "dataType": "ENUM",
        "dataLength": "'GIF','PNG','JPG','JPEG'",
        "nullable": "N"
      }
    },

**Comment by jannyHou** [comment]
@hishamjaved I believe this problem is fixed in pr https://github.com/strongloop/loopback-connector-mysql/pull/226 
while we haven't released the new verson.

I am confirming the status of mysql and see when will we be ready to release it.

**Comment by jannyHou** [comment]
I label it with "blocked" due to waiting for release. Will confirm then close it after new version of mysql published.
