### ISSUE TITLE
Where is "MySQL" in list?

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#3069]
@miroslav-grabinskiy commented on [Thu Dec 29 2016](https://github.com/strongloop/loopback.io/issues/219)

In-memory db (supported by StrongLoop)
  IBM DB2 (supported by StrongLoop)
  IBM DashDB (supported by StrongLoop)
  IBM MQ Light (supported by StrongLoop)
  IBM Cloudant DB (supported by StrongLoop)
  IBM DB2 for z/OS (supported by StrongLoop)
  MongoDB (supported by StrongLoop)

Press the down-arrow key to highlight MySQL (supported by StrongLoop), then hit Enter.  

hmm, There are not mysql in list. 
what should be done to appear?

---

@crandmck commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269803146)

You should be able to "down arrow" to scroll down the list and display "MySQL".

What version are you using (type `slc -v`)?  What OS are you using (Windows, Mac)?

---

@miroslav-grabinskiy commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269804538)

6.0.3, when I press arrow keys, arrow not move :(

---

@crandmck commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269815201)

What OS are you using (Windows, Mac)?

---

@miroslav-grabinskiy commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269832578)

Windows 10.
Arrow not move, but when I press "down arrow" key, and enter, I select second element, but it's very uncomfortable, and This does not help in this menu for view other elements(

---

@crandmck commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269833441)

@smartmouse I don't think this is a doc issue, because of course this works properly (for me and others).  Can you help debug this?  Should we move the issue to another repo?

---

@smartmouse commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269834621)

@crandmck , do you mean a different issue?

---

@miroslav-grabinskiy commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269836469)

If mysql is on the list and pressing the button down, i can walk up to this point, yes, it's another issue

---

@miroslav-grabinskiy commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269836491)

How I can help debug this?

---

@smartmouse commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269838718)

Which node.js version are you using?
When you create the loopback project i.e. slc loopback, which template are you using?
api-server, helloworld, empty-server or notes?

I do not have windows 10 to reproduce , this is a window 7,
if I press down-arrow to mySql and then press enter to select, this is what I got.

<img width="1006" alt="screen shot 2016-12-30 at 7 19 35 pm" src="https://cloud.githubusercontent.com/assets/4519627/21574682/41d116a0-cec5-11e6-9bab-07c85fa4e5f2.png">

---

@miroslav-grabinskiy commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269839050)

I tried helloworld, and api-server, and I had the same problem. 6.9.1 node -v

---

@miroslav-grabinskiy commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269839185)

I will record video with problem, when i will be in my work (on Tuesday)

---

@smartmouse commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269839254)

I am using node 4.x, let me try node6.x and see if I can reproduce on windows 7, if I cannot, then it is specific to windows 10.  In the meantime, you can see if npm install -g loopback-connector-mysql works for you on windows 10 or not.
Thank you for trying out.

---

@miroslav-grabinskiy commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269839700)

Ok, I wait your test with node6.x.

---

@smartmouse commented on [Fri Dec 30 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269839968)

I tried node6.x , no issues.
I assume you are using loopback 3.
I tried both loopback v2.x and 3  , no issue.

<img width="825" alt="screen shot 2016-12-30 at 7 49 20 pm" src="https://cloud.githubusercontent.com/assets/4519627/21574867/1bebb8f6-cec9-11e6-94cc-2f1d2672f6e0.png">

---

@miroslav-grabinskiy commented on [Sat Dec 31 2016](https://github.com/strongloop/loopback.io/issues/219#issuecomment-269856787)

Ok, i will record viewo with my issue on Tuesday

---

@crandmck commented on [Tue Jan 03 2017](https://github.com/strongloop/loopback.io/issues/219#issuecomment-270180585)

> do you mean a different issue?

@smartmouse What I meant was the issues in this repo are specifically for documentation problems or issues related to the loopback.io site.  Issues with LoopBack software should be in the `loopback` repo or another more appropriate repo.

---

@smartmouse commented on [Wed Jan 04 2017](https://github.com/strongloop/loopback.io/issues/219#issuecomment-270439215)

@crandmck Do you have authority to move this issue to the loopback repo?

**Comment by loay** [comment]
There are couple of workarounds in the the other issue mentioned above by 0Candy ^^^
https://github.com/strongloop/generator-loopback/issues/69
