### ISSUE TITLE
 runincontext deprecated but whats the replacement?

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#3078]
loopback deprecated loopback.runInContext() is deprecated. See https://docs.strongloop.com/display/APIC/Using%20current%20context for more details.

That URL does not have any details about this command replacement.
According to the docs, currentcontext is discouraged, the linked examples on the docs are pointing to 404
https://github.com/strongloop/loopback/blob/master/example/context/app.js

The linked github ticket is huge, not useful at all.

So how can we access current user or mimic another user?

Right now it is done via currentContext and runInContext.

**Comment by bajtos** [comment]
See https://github.com/strongloop/loopback/pull/3023.

The documentation update is in progress, see https://github.com/strongloop/loopback.io/pull/227 (or the markdown file [here](https://github.com/strongloop/loopback.io/blob/e28628f7e83b78cd480283244d9804c9e54f9110/pages/en/lb3/Using-current-context.md)).

**Comment by bajtos** [comment]
> According to the docs, currentcontext is discouraged, the linked examples on the docs are pointing to 404
> https://github.com/strongloop/loopback/blob/master/example/context/app.js

@crandmck could you PTAL?

**Comment by crandmck** [comment]
It looks like `example/context/app.js` was removed at some point.   https://github.com/strongloop/loopback.io/pull/227/ removes this link, so it won't be an issue any longer once that PR is merged.
