### ISSUE TITLE
nestRemoting causes huge performance changes

### ISSUE THREAD

**Issue by Undrium** [strongloop/loopback#3079]
Our project has Users which need access to models further away than one step from them in relationship. A User is part of a group which in its turn has other items. 

**/Users/uid/Groups/gid/Items/iid**

The above URI shouldn't be a problem, right? The users are connected to the groups through another model, otherwise this uses normal relations. Since we only got access to **/Users/uid/Groups/gid** by default we had to use nestRemoting(). 
```
app.models.User.nestRemoting('groups');
app.models.Group.nestRemoting('items');

```
This worked, but also added 6 seconds of loading time for our application (one request to **/Users/uid/Groups/gid/Items/<iid>**). Now we have pageloads at 7-8 seconds instead of 1-2. Is there any known issues here? We are using the absolutely most simple type of relationship here. Only thing that might cause a problem is the relationship between User and Group which is a simple through model.

**Comment by Undrium** [comment]
After some deep diving into the wonderful world of debugging of NodeJS I found the perpertrator to be another Boot-script (getCurrentContext-quickfix) used from here: https://gist.github.com/ebarault/fdc39c5d07cc40f08664256f9e00905a

I know alot of people use this as a patch, so might be helpful in the future. Also, I hope this is not patched into the official version (https://github.com/strongloop/loopback/issues/1495) as it really slows down Loopback.

**Comment by davidcheung** [comment]
@Undrium interesting and thanks for bringing this up, it would be great help if you could try to upgrade to the latest LB with https://github.com/strongloop/loopback/commit/4de3aa77e35a0c2f01f3a8f58bc935962bc9ae16, (the implementation is different from the one offered from the gist) and see if there are any performance degradation, or a [sandbox](https://github.com/strongloop/loopback-sandbox) so we could have a reference point.

**Comment by Undrium** [comment]
It seems fine since it does not go through every available model-function injecting the context but lets you do it manually. What should be tested is when this is done to a larger amount of model functions or measure the difference on a single function getting it assigned. This occured to us when we started using the nestRemoting() so should probably be a model which is indirectly related as a child to another from a parent-middlechild-child perspective. 

At first glance this looks fine, not entirely sure how much more juice it demands, though.
