### ISSUE TITLE
After updating to 3.0 Rest Errors are displayed as html instead of JSON

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#3085]
Following exactly the migration guide https://loopback.io/doc/en/lb3/Migrating-to-3.0.html#update-use-of-rest-error-handler part resulted nothing but plain HTML errors and console logged errors instead of properly formatted REST error JSON.

stack:
```"dependencies": {
    "apn": "^1.7.5",
    "async": "1.0.0",
    "bluebird": "^3.0.5",
    "body-parser": "^1.14.1",
    "chance": "^0.8.0",
    "cheerio": "^0.20.0",
    "compression": "^1.0.3",
    "cookie-parser": "^1.4.0",
    "cors": "^2.5.2",
    "errorhandler": "^1.1.1",
    "express-session": "^1.12.0",
    "fs-extra": "^0.26.2",
    "helmet": "^1.3.0",
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.7.0",
    "loopback-component-passport": "^1.6.0",
    "loopback-component-storage": "^1.5.1",
    "loopback-connector-mongodb": "1.13.0",
    "loopback-context": "^1.0.0",
    "loopback-datasource-juggler": "^2.47.0",
    "loopback-ds-readonly-mixin": "^1.0.0",
    "moment": "^2.10.6",
    "mongodb": "^2.2.5",
    "multer": "^1.0.6",
    "needle": "^0.11.0",
    "node-gcm": "^0.14.0",
    "node-uuid": "^1.4.3",
    "passport-facebook": "^2.0.0",
    "quickthumb": "0.0.12",
    "random-user": "2.0.2",
    "serve-favicon": "^2.0.1",
    "slug": "^0.9.1",
    "strong-error-handler": "^1.1.1",
    "underscore": "^1.8.3",
    "winston": "^2.1.1",
    "winston-loggly": "^1.3.1"
  },```

**Comment by davidcheung** [comment]
@barocsi Loopback 3.0 is using strong-error-handler which uses [accepts](https://www.npmjs.com/package/accepts) to perform the content-negotiation,
browsers sends `Accept headers` such as `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8` which gets resolved as `text/html`. 

With that said I do agree that there seems to be a lack of customizability with the content-type (a way to force prioritize a type as long as its supported)

URLs such as `http://localhost:3000/api/Users/1?_format=json` should be always override the content type

the new error-handler hides `stacktrace` by default which you can enable in the settings depending ur error is being handled by rest-adapter ( in `config.json`  )
```json
"remoting": {
    "rest": {
      "handleErrors": false //<---false will use the middleware cycle one
    },
    "errorHandler": {
      "debug": true,
      "log": true,
      "defaultType": "application/json"
    }
}
```
or left till end of middleware cycle `middleware.json` 
```json
"final:after": {
    "strong-error-handler": {
      "params": {
        "debug": true,
        "log": true,
        "defaultType": "application/json"
      }
    }
  }
```

cc  @bajtos

**Comment by barocsi** [comment]
This makes sense, thanks!
