### ISSUE TITLE
Remote method with capitalize letter

### ISSUE THREAD

**Issue by a-legrand** [strongloop/loopback#3087]
- [X] Bug
- [ ] Feature request

When creating a remote method name containing a capital letter, reponse time is very slow

Example :
```User.addFavourite = function(XXX, cb) { ... }```
can take up to 7s
while same code with ```addfavourite``` as method name take less than 600ms

node 6.9.2
loopback 2.36.2

Worked fine with previous loopback (can't tell exact version)

**Comment by a-legrand** [comment]
"Favourite" is the name of a model in my application...
I guess it is the problem, since ```addSomethingelse``` seems to work

**Comment by davidcheung** [comment]
@a-legrand hmm that sounds weird, does the existence of that method slow down all other methods(possible routing issue)? or it is just the response time for that method itself?
would you be able to provide a sandbox reproducing the issue?

**Comment by a-legrand** [comment]
Only this method (and also "deleteFavourite", for same reason I guess) is slow.
All other methods are totally OK.
I will provide it in a sandbox asap
