### ISSUE TITLE
Extraneous refs to context files in API doc

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#3088]
There are two references to context for API docs:
- https://github.com/strongloop/loopback/blob/master/docs.json#L8
- https://github.com/strongloop/loopback/blob/master/docs.json#L14

However, `server/current-context.js` was removed and `server/middleware/context.js` does not have any API doc comments, so it seems we should just remove these two links from `docs.json`.

@bajtos

**Comment by bajtos** [comment]
Good catch @crandmck! I agree with you, both lines should be removed in the `master` branch. I think we should preserve them in `2.x`?

**Comment by crandmck** [comment]
> I think we should preserve them in 2.x?

Agree.  Just remove them in master (and thus future 3.x releases).  I'll open a PR.

**Comment by crandmck** [comment]
Fixed by #3907
