### ISSUE TITLE
2.36.2 version breaking replaceOrCreate method on User model

### ISSUE THREAD

**Issue by vijay22sai** [strongloop/loopback#3091]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
Let's say database collection is empty and when invoking User.replaceOrCreate, getting error `TypeError: Cannot read property 'email' of undefined`

the line which causes this is [here](https://github.com/strongloop/loopback/blob/v2.36.2/common/models/user.js#L844). originalUserData is an empty array(because db is empty) but it's assuming it has atleast one record.

### Additional information (Node.js version, LoopBack version, etc)

LoopBack version: 2.36.2

**Comment by vijay22sai** [comment]
@loay Can you please check this issue once. I could see the changes are done by you here https://github.com/strongloop/loopback/commit/d06190dae6b858e4da7b3ae91494e429f9adec66#diff-5d81af95449574544e7317f3eda2badeR680
Thanks.

**Comment by loay** [comment]
Hi @vijay22sai 
Thanks, I will have a look.

**Comment by duncancasemore** [comment]
Hi @loay did you get a chance to have a look at this?  We've very keen to upgrade to a later loopback release but this is holding us back at the moment.

**Comment by loay** [comment]
Hi @vijay22sai 
There was a pr that fixed this issue by @bajtos recently. Are you still experiencing the same issue? Thanks

**Comment by vijay22sai** [comment]
Hi @loay, I will check it and let you know. Thanks a lot.

**Comment by vijay22sai** [comment]
Hi @loay I was able to upgrade to latest version `2.38.0` successfully without any issues. Thank you very much for the help 👍

**Comment by duncancasemore** [comment]
Hey @loay just wanted to say thank-you for this - we're grateful for your assistance.

**Comment by loay** [comment]
@vijay22sai @duncancasemore You guys are very welcome. I am glad I could help :) Thanks for your kind words
