### ISSUE TITLE
Error building application with generator

### ISSUE THREAD

**Issue by jorgerenteria** [strongloop/loopback#3093]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Hello, 

When I try to create an application with the generator it is not possible to use the arrow keys and it is not possible to select version 3.

Can you help me?

**Comment by pierreclr** [comment]
Using APIC you can't generate LB3 app. Use the latest version of slc instead

**Comment by davidcheung** [comment]
not sure if the solution to move to `slc` would solve the problem, its likely to be a windows issue (see https://github.com/nodejs/node/issues/2996), it works on the regular `cmd` only I believe, maybe some versions of gitbash.
