### ISSUE TITLE
nativescript-loading-indicator is not working in ios.

### ISSUE THREAD

**Issue by narender56** [strongloop/loopback#3095]
Hi everyone,

I'm using nativescript-loading-indicator plugin for loader,it's working fine for android but in ios is not. It's looking some value for "mode". Can anyone please tell me what value will there for this "mode" in ios?

ios: {
    details: "Additional detail note!",
    square: false,
    margin: 10,
    dimBackground: true,
    color: "#4B9ED6",
    mode: // see iOS specific options below
  }

**Comment by k1ng440** [comment]
this is loopback.

**Comment by narender56** [comment]
Oops .... sorry
