### ISSUE TITLE
Loopback 2.37.0 Unreliable concurrent create queries

### ISSUE THREAD

**Issue by jamesjjk** [strongloop/loopback#3101]
### Bug/Feature request

- [x] Bug

I have noticed a bug in our unit tests after updating loopback to version 2.37.0 from 2.36.0. The tests in question use a mongodb persistance layer. On concurrent create / read queries (in particular the token model - which has a custom ID fields) loopback is intermittently not creating the document, whilst acknowledging through the callback.

- This is a standard local test environment, not HA / sharded / cluster. I have tested all the related modules and I get a feeling something is up with context of DOA - but not sure.

### Additional information

Versions where test FAIL:
darwin x64 
node 6.9.1
loopback@2.37.0 
loopback-connector@2.7.1
strong-remoting@2.32.3
loopback-connector-mongodb@3.0.0 
loopback-datasource-juggler@2.53.1

Versions where test PASS:
darwin x64 
node 6.9.1
loopback@2.36.0 
loopback-connector@2.7.1
strong-remoting@2.32.3
loopback-connector-mongodb@3.0.0
loopback-datasource-juggler@2.53.1

**Comment by prtkkmrsngh** [comment]
@jamesjjk Same thing with me. I'm modifying embedded model through PUT request, nothing changed
but requests acknowledge that changes are done.

Any fix for this?

**Comment by jamesjjk** [comment]
@prtkkmrsngh Try the LTS version and if you still have a problem downgrade.

**Comment by prtkkmrsngh** [comment]
Fixed it programmatically. Loopback LTS and current production version didn't help it out.

**Comment by alzab** [comment]
@prtkkmrsngh Could you possibly mention what you did to fix it? I suspect I'm seeing the same issue - my client program batch-creates a bunch of models concurrently and only one succeeds, with the rest silently not persisting but seemingly succeeding from the responses. Thanks!

**Comment by prtkkmrsngh** [comment]
@alzab I was sending `POST/PUT` request concurrently using `map` which didn't work. Calling one after another finished works. Invoking method with parameter to detect which request need to execute and once response received invoking it again with another parameter.

**Comment by alzab** [comment]
@prtkkmrsngh Ah OK I see, I ended up doing exactly the same thing today. This definitely appears to be a bug unless I'm missing something - unfortunately not tagged/assigned yet
