### ISSUE TITLE
Count on `RoleMapping` results 0 always

### ISSUE THREAD

**Issue by jmimi** [strongloop/loopback#3102]
### Bug or Not!
When I count on `RoleMapping` the result is zero. Because `principalId` is string but mongodb connector considered it's to be an object-id.
So I have to change `RoleMapping` settings as adding to that.

I couldn't find anything in documentation for `strictObjectIDCoercion`, I find that in source code at : [here](https://github.com/strongloop/loopback-connector-mongodb/blob/eff65e052d17537d82796658e0db15d09003cf0a/lib/mongodb.js#L1388)

### Additional information

```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 7.0.0
```

```
$ npm ls --prod --depth 0 | grep loopback
├── loopback@3.2.0
├── loopback-base-commons@0.0.8
├── loopback-boot@2.23.0
├── loopback-component-explorer@2.7.0
├── loopback-connector-mongodb@1.18.0 
├── loopback-datasource-juggler@2.53.1 

```

**Comment by pierreclr** [comment]
It's related to v1.18 connector mongodb and maybe the `strictObjectIDCoercion` settings not present on roleMapping.json. You should see this issue https://github.com/strongloop/loopback-connector-mongodb/issues/327

**Comment by jmimi** [comment]
@pierreclr Thanks for reply. 
I test with mongodb connector version `3.0.0` too and still the problem exists.
I override the `RoleMapping` settings and added `strictObjectIDCoercion`.
And I close this issue regarding to your open issue
