### ISSUE TITLE
AccessToken invalidation

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#3111]
This is an Epic to capture all stories for implementing AccessToken invalidation on email/password change.

**Comment by josephlaw** [comment]
Hi, got "Invalid Access Token after upgrade from 2.37.1 to 2.38.0, no idea what happen.

`error{"data":{"error":{"message":"Invalid Access Token","stack":"Error: Invalid Access Token\n    at /Users/xxxx/tmp/server/node_modules/loopback/common/models/access-token.js:117:23\n    at /Users/xxxx/tmp/server/node_modules/loopback/common/models/access-token.js:170:11\n    at Object.forward (/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:92:23)\n    at eval (eval at wrap (/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:214:20), <anonymous>:3:21)\n    at /Users/xxxx/tmp/server/node_modules/loopback-datasource-juggler/lib/dao.js:2760:17\n    at doNotify (/Users/xxxx/tmp/server/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)\n    at doNotify (/Users/xxxx/tmp/server/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)\n    at doNotify (/Users/xxxx/tmp/server/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)\n    at doNotify (/Users/xxxx/tmp/server/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)\n    at Function.ObserverMixin._notifyBaseObservers (/Users/xxxx/tmp/server/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)`

**Comment by josephlaw** [comment]
Add `"logoutSessionsOnSensitiveChanges" : true` into server/config.json to fix "Invalid Access Token" after upgrade from 2.37.1 to 2.38.0. Thanks your attention.

**Comment by bajtos** [comment]
@josephlaw hi, thank you for the feedback. Could you please open a new issue and include full steps for reproducing the issue, ideally per our [bug-reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)? Also if you could mention my GitHub handle (`@bajtos`) in the issue description, so that I get email notification.
