### ISSUE TITLE
Blog post: AccessToken invalidation

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#3113]
Write a blog post to announce the recent changes and explain the reasoning behind them.

**Comment by dhmlau** [comment]
@bajtos @loay , do we still need this blog post?  If so, I can prioritize.  Thanks.

**Comment by bajtos** [comment]
IMO the blog post does not make much sense now, considering the changes were released more than 6 months ago. I think people who may care about them have already discovered them, and those who don't care simply don't care.
