### ISSUE TITLE
CPU usage high

### ISSUE THREAD

**Issue by oneoutone** [strongloop/loopback#3117]
Hi guys,  I update my loopback-connector-mongodb to v1.18.0 with mongodb 2.2.20, and connect to mongodb ReplicaSet with url "mongodb://userame:password6@host1,host2:port/database?replicaSet=setid", then  strong-pm's CPU usage keep increasing, I tried restart the server, but cpu usage reach 100% in serval hours every time, any idea about it?

**Comment by loay** [comment]
Please refer to this previous issue: https://github.com/strongloop/loopback/issues/1469

**Comment by loay** [comment]
Hi @oneoutone 
There are few solutions to this issue in this issue https://github.com/strongloop/loopback/issues/1469
Have you tried them?
Thanks

**Comment by loay** [comment]
Closing this issue since it is a duplicate.
