### ISSUE TITLE
High CPU if using MongoDB ReplicaSet

### ISSUE THREAD

**Issue by JoeShi** [strongloop/loopback#3118]
My strong-pm instance reach 100% usage in an hour while using MongoDB ReplicaSet.

If not connecting to MongoDB without ReplicaSet, every thing is fine.

My databases.producton.json is 

```
  "mongodb": {
    "url": "mongodb://xxxx:xxxxxx@dds-1.mongodb.rds.aliyuncs.com:3717,dds-2.mongodb.rds.aliyuncs.com:3717/test?replicaSet=mgset-11111",
    "database": "test",
    "name": "mongodb",
    "connector": "mongodb",
    "allowExtendedOperators": true
  },
```

**Comment by loay** [comment]
Hi, there is an issue opened already about the same thing:
https://github.com/strongloop/loopback/issues/3117
Let's focus on one issue so we can avoid distraction. Thanks.
