### ISSUE TITLE
How to eliminate the duplicate objects when we get collections? 

### ISSUE THREAD

**Issue by narender56** [strongloop/loopback#3119]
Hi all,

 I have a collections like the following.

[{
  "id": 1,
  "name": "Peter",
  "email": "pryan0@tamu.edu",
  "gender": "Male"
}, {
  "id": 2,
  "name": "Peter",
  "email": "clee1@nhs.uk",
  "gender": "Male"
}, {
  "id": 3,
  "name": "Peter",
  "email": "ebutler2@epa.gov",
  "gender": "Male"
}],

So here name  field is duplicated,when i get this collection i want to get only one object based on that name field?

**Comment by pierreclr** [comment]
Hey @narender56 this is not an issue but a question. Could you please close it ? The answer of your question is : 
```
const bluebird = require('bluebird'); // Don't need that using loopback 3.X
cons _ = require('lodash');

MyModel.customFind = MyModel.find()
   .then(users => _.uniqBy(users, 'name'))
   .asCallback(cb);
```

**Comment by loay** [comment]
Hi @narender56 
You can also use `PersistedModel.findOne([filter], callback)`
Same as find, but limited to one result; Returns object, not collection.

In the filer, use ``` {where:{'name':'Peter'}} ``` and that should do the trick. 

Please let me know if you have any further questions.
