### ISSUE TITLE
Customize the result of changeStream

### ISSUE THREAD

**Issue by Casy** [strongloop/loopback#3122]
i did a [post in SO](http://stackoverflow.com/questions/41304697/how-can-i-edit-the-result-of-changestream-in-loopback) but nobody answer me :(

The question is pretty simple, how can i change the default changeStream response? i want to search the id of the update and return the entire object, no just the modification and his id

**Comment by bajtos** [comment]
Hi @Casy, loopback does not allow you to customise the events returned in the change stream.

I think it should be reasonably easy to implement this extension point, would you like to contribute it yourself?

Most of the code is in [lib/persisted-model.js#L1845-L1928](https://github.com/strongloop/loopback/blob/cb7e2114ecfad9d852bb8da70a44fe74d6fa0ef7/lib/persisted-model.js#L1845-L1928).

I think the easiest way is to add a static model method for customizing the change item data and then call this method before sending the data to the response stream, see https://github.com/strongloop/loopback/blob/cb7e2114ecfad9d852bb8da70a44fe74d6fa0ef7/lib/persisted-model.js#L1922

```js
// inside PersistedModel.createChangeStream
if (writeable) {
  ctx.Model.buildChangeStreamItem(change, (err, data) => {
    // TODO - handle "err" 
    changes.write(data);
  });
}

// the default implementation
PersistedModel.buildChangeStreamItem = function(change, cb) {
  cb(null, change);
};

// in your model, you can customize "buildChangeStreamItem"
// common/models/my-model.js
module.exports = function(MyModel) {
  MyModel.buildChangeStreamItem = function(change, cb) {
    MyModel.findById(change.target, (err, found) => {
      if (err) return callback(err);
      change.instance = found; // or whatever else
      cb(null, change);
    });
  }
};
```

**Comment by Casy** [comment]
@bajtos I will do it, i need time because I'm with a lot of work right now .. i will need help with the tests that i should do once i finish it, ok?

**Comment by bajtos** [comment]
> i will need help with the tests that i should do once i finish it, ok?

Sure, I'm happy to help! Take a look at the existing [change-stream tests](https://github.com/strongloop/loopback/blob/53182affef06aa23563496242b4f447f0a171069/test/change-stream.test.js) to get started.
