### ISSUE TITLE
Calling User.save() removes all current access tokens even not change user email or password.

### ISSUE THREAD

**Issue by icy90** [strongloop/loopback#3124]
#3021 
in common/models/user.js:
```js
var isFullReplaceChangingPassword = !!ctx.instance;
// ...
ctx.hookState.isPasswordChange = isPartialUpdateChangingPassword || 
  isFullReplaceChangingPassword;`
```

`ctx.instance` always true when you do `User.save()`

**Comment by davidcheung** [comment]
>@icy90 I see. Please open a new github issue for this problem, so that we can move the discussion there, and mention my handle there so that I get email notification.

@bajtos

**Comment by bajtos** [comment]
Fixed.
