### ISSUE TITLE
Include-filter via REST-API-url doesn't work as documented and returns always empty arrays

### ISSUE THREAD

**Issue by itinance** [strongloop/loopback#3125]
### Bug (apparently)

This issue describes either a lag of documentation or indeed a bug.

Given is a model "_team_" and a model "_members_". The Model _team_ has a "**hasMany**"-relation to "_members_" and "_members_" has a "**belongsTo**"-relation to "_team_".

Querying members of a team via URL can happen as follows:
`/api/teams/58810bbae544c60100fef14d/members`

Following the documentation for [include-filters](https://loopback.io/doc/en/lb2/Include-filter.html) or the linked official [relation-example](https://github.com/strongloop/loopback-example-relations) one would expect to query the whole "_team_"-entity together with its hasMany-relations like this:
`/api/teams/58810bbae544c60100fef14d?filter[include]=members`

However, while the first approach works for members of the specific team, the second approach using "filter[include]" gives an empty members-array although there are members available (which can be approved with the first URL).

The same empty result for "members" happens with the following variations:

```
api/teams/58810bbae544c60100fef14d?filter[include][members]
api/teams/58810bbae544c60100fef14d?filter[include][members]=id,name

```
Result of `/api/teams/58810bbae544c60100fef14d/members` (as expected):
```
[
   {
      "id":"ABC",
      "picture_url":"string",
      "user_id":"123456",
      "is_active":true,
      "is_admin":true,
      "teamId":"58810bbae544c60100fef14d"
   },
   {
      "id":"DEF",
      "picture_url":"string",
      "user_id":"123456",
      "is_active":true,
      "is_admin":true,
      "teamId":"58810bbae544c60100fef14d"
   },
   {
      "id":"Q2",
      "picture_url":"string",
      "user_id":"123456",
      "is_active":true,
      "is_admin":true,
      "teamId":"58810bbae544c60100fef14d"
   }
]

```
Result of `/api/teams/58810bbae544c60100fef14d?filter[include]=members`:
```
{  
   "id":"58810bbae544c60100fef14d",
   "name":"class 1",
   "description":null,
   "members":[  
   ]
}
```
**The issue:** The members-Array is always empty.

### Expected result

The expected result is a _ream_-entity with a _members_-property containing all team-members like returned with the very first url from above (/api/teams/$id/members):

```
{
   "id":"58810bbae544c60100fef14d",
   "name":"class 1",
   "description":null,
   "members":[
      {
         "id":"ABC",
         "picture_url":"string",
         "user_id":"123456",
         "is_active":true,
         "is_admin":true,
         "teamId":"58810bbae544c60100fef14d"
      },
      {
         "id":"DEF",
         "picture_url":"string",
         "user_id":"123456",
         "is_active":true,
         "is_admin":true,
         "teamId":"58810bbae544c60100fef14d"
      },
      {
         "id":"Q2",
         "picture_url":"string",
         "user_id":"123456",
         "is_active":true,
         "is_admin":true,
         "teamId":"58810bbae544c60100fef14d"
      }
   ]
}
```

Currently this property is present but contains an empty array.

### Additional information

node -e 'console.log(process.platform, process.arch, process.versions.node)'

> linux x64 4.4.5

npm ls --prod --depth 0 | grep loopback

> npm info it worked if it ends with ok
> npm info using npm@2.15.5
> npm info using node@v4.4.5
> ├── loopback@2.37.0
> ├── loopback-boot@2.23.0
> ├── loopback-component-explorer@2.7.0
> ├── loopback-connector-mongodb@1.17.0
> ├── loopback-connector-mysql@2.4.0
> ├── loopback-datasource-juggler@2.53.1
> npm info ok 
> 

### Model definition is:

**team.json:**

```
{
  "name": "team",
  "plural": "teams",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "index": false
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "e-mail": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "website": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "members": {
      "type": "hasMany",
      "model": "team_member"
    }
  },
  "acls": [],
  "methods": {}
}

```

**team_member.json:**

```
{
  "name": "team_member",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "index": true
    },
    "picture_url": {
      "type": "string",
      "index": false
    },
    "user_id": {
      "type": "string",
      "index": true
    },
    "is_active": {
      "type": "boolean",
      "index": true
    },
    "is_admin": {
      "type": "boolean",
      "index": true
    }
  },
  "validations": [],
  "relations": {
    "team": {
      "type": "belongsTo",
      "model": "team",
      "foreignKey": "id"
    }
  },
  "acls": [],
  "methods": {}
}

```

**Comment by taoyuan** [comment]
team_member.json:
```json
{
  "name": "team_member",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "index": true
    },
    "picture_url": {
      "type": "string",
      "index": false
    },
    "user_id": {
      "type": "string",
      "index": true
    },
    "is_active": {
      "type": "boolean",
      "index": true
    },
    "is_admin": {
      "type": "boolean",
      "index": true
    }
  },
  "validations": [],
  "relations": {
    "team": {
      "type": "belongsTo",
      "model": "team",
      "foreignKey": "id" <------  should be "teamId"
    }
  },
  "acls": [],
  "methods": {}
}

```

**Comment by itinance** [comment]
Thx for your quick answer. Unfortunately this will reduce the result set once more. Changing the foreignKey to "teamId" will do something else but not assign this member to the specific team. 

Both URLs will response then empty results:

`/api/teams/{id}/members`
-> empty
`/api/teams/{id}?filter[include]=members`
-> team-entity with empty array for "members"

**Comment by pierreclr** [comment]
@itinance Your models are misconfigured ... it should be something like `team_member` `hasOne` team on `teamId` and `team` `hasMany` members on `teamId`.

**Comment by itinance** [comment]
Thx @pierreclr But this will add a separate field to the "**team**"-model instead of using it's primary key "id". Any more ideas?

**Comment by pierreclr** [comment]
@itinance of course not ! The `hasMany` relation property is handle by the destination model (here `team_member`.
