### ISSUE TITLE
[2.0] RFC: registry

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#313]
**RFC: loopback.createRegistry()***

The goal of the `Registry` is to allow modules (connectors, plugins to loopback, applications, etc) to reference the same instances of objects (Constructors, functions, objects, values, etc) no matter how modules are installed.

This RFC was inspired by moving the registry APIs we currently have to its own file. This highlights a couple design flaws. [See this PR](https://github.com/strongloop/loopback/pull/308) for more.

The loopback object (from `require('loopback')`) or the `modelBuilder` should not be treated as singletons. For some background [checkout this gist](https://gist.github.com/ritch/b66c09891e3a37fc78a8).

 Instead we should create a `Registry` with a regular constructor / class. This should provide any dependencies a loopback app, plugin/module, script, etc, needs - without it directly referencing the object / class / value.

I'm thinking of something like this:

**Creating a registry**

This is done by the app. We may provide sugar around this, since it will be the same for all apps, but the app is what actually creates the registry which it will use.

```js
// there is no longer a global registry or model builder
// instead apps and modules interact with instances of loopback registries
var registry = loopback.createRegistry();
```

**Models**

All models are registered when they are defined. Below is how you would register a model. This would be added to `Model.extend()` so all models are registered. 

```js
registry.provide('MyModel', {base: Model, value: MyModel});
```

The registry would also be used to store datasources in the same way.

```js
registry.provide('db', {base: DataSource, value: loopback.createDataSource(options)});
```

The registry would support various searching / filtering required throughout loopback / juggler / connectors / and plugins. This allows any module with reference to the registry to find models, datasources, and other objects that it requires, without directly requiring them or a singleton that provides them.

For example, consider a plugin that uses `loopback.Model`. If this plugin uses npm to install loopback it will get a different instance of `loopback.Model` than the application depending on the plugin that installs its own loopback, even if the installed version of loopback is the same for the app and the plugin.

```js
// my plugin - wants to allow users to provide a custom FooBarModel or use the base class
registry.getCtorsExtending(FooBarModel) // => [ConstructorA, ConstructorB, ...]
registry.getCtorsImmediatelyExtending(FooBarModel) // => [ConstructorA, ...]

// other lookups
registry.getByName('db') // => [obj, Costructor, ...]
registry.getObject('db', DataSource) // => db (instanceof DataSource)
registry.getCtor('MyModel') // => MyModel

// runtime version checking (not sold on this yet)
registry.withRestriction('loopback', '>= 2.3.4').getCtor('MyModel') // => potentially throws InvalidVersion error
```

**Using the registry from plugins / connectors / juggler / etc**

Below illustrates several approaches to provide the registry instance to plugins / connectors / the juggler / etc.

```js
/*
Option 1:
Every object `provide`d to the registry will be assigned the registry it was provided to. Below shows how the juggler could use this to find a model by name for a connector
*/

Connector.prototype.findModelByName = function(name) {
  // `registry` is set by `Registry#provide()`
  return this.dataSource.registry().getCtor(name)
}

/*
Option 2:
Any module that requires a registry must export a function accepting a registry object.
*/

module.exports = function(registry) {
  return function MyModuleClass() {
   
  }
}
```

**Using the registry in tests**

Since the registry would no longer be a singleton, tests setup could be much simpler.

```js
beforeEach(funciton() {
  app = loopback();
  app.registry = setupRegistry(modelsJSON, datasourcesJSON);
});

// each test gets its own model constructors / datasources / etc
// `setupRegistry()` could also provide mock dataSources and other stateful objects to simplify test setup
```

A potential issue with this approach is that it hints that each `app` has its own `registry` instance. I'm not sure if that makes sense or not. Multiple apps may want to share models, hence they would share a registry.

**Conclusion**

The idea is to encapsulate the state of a loopback application into an instance of a `Registry` class. This will greatly simplify any module that interacts with that state (especially - plugins / tests / connectors / juggler / strong-remoting).

**TBD**

This is a major change and may require drastic changes. Its yet to be determined if this effort is worthwhile. We should consider what issues we continually run into that this is the cause of and use that to weigh whether or not this change is justified.

**Comment by bajtos** [comment]
@ritch what's the status of this story now that https://github.com/strongloop/loopback/pull/1212 added support for per-app registries?

**Comment by ritch** [comment]
Well we have this now:

> The idea is to encapsulate the state of a loopback application into an instance of a Registry class. This will greatly simplify any module that interacts with that state (especially - plugins / tests / connectors / juggler / strong-remoting).

I'd like to continue improving the `Registry` but for now I think we can close this issue.

**Comment by jameslk** [comment]
I've run into an issue due to the use of these singletons where I needed to have two apps (one as my primary app, and another as a remote mirror of that app so I could apply the ACL). However, due to the singletons, the remote app ends up overwriting the models in the primary app through the registry, rendering this design useless without some hacks to create multiple instances of Loopback.
