### ISSUE TITLE
updateattribute bug

### ISSUE THREAD

**Issue by codeyad** [strongloop/loopback#3134]
Hi, i created a loopback proyect with the lates version and connected my models to a mysql database, the problem is that when i try to update one of those models it updates all properties (to null) if i dont include them, so if i just whant to update ```name``` it update the whole model with empty data.

**Comment by yshing** [comment]
In 3.0 the PUT method is Replace, need to use PATCH method for updating single attributes using REST routes.

**Comment by codeyad** [comment]
Oh thanks @yshing i didnt see the Notes of the lates version, they changes the updateAttributes in PUT by replaceById.

**Comment by loay** [comment]
Thanks @yshing for providing an update. 
@codeyad I am closing the issue. If the issue is still persisting, please fell free to leave a comment and I will re-open the issue. Thanks.
