### ISSUE TITLE
Where clause = problem

### ISSUE THREAD

**Issue by kogutu** [strongloop/loopback#3141]
Hi, I have problem with this function in AngularJS:
`          Posts.find({
          "where": {
            "and": [
              {"month_year": "2017-01"},
              {"id_lek": "587ca62f8b90cb2b70b87d9b"}
            ]
          }
        }
        , function ( posts) {
          console.log( posts.length);
        });
    }`

This function always return me 1(true). In Mongo i have one record, id_lek is not change, i change month_year (in db is value: "2017-01") when I change in {"month_year": "2017-02"} this function return me True but should return 0 (false) beacuse in DB there is no such record.

Please help me! where is wrong?

**Comment by pierreclr** [comment]
`Posts.find({ filter: { "where": { "and": [ {"month_year": "2017-01"}, {"id_lek": "587ca62f8b90cb2b70b87d9b"} ] } } } , function ( posts) { console.log( posts.length); }); }`

**Comment by kogutu** [comment]
Still not working:/ Now function always return me 0 (false).
Look this is my DB Posts (one record)
![image](https://cloud.githubusercontent.com/assets/1575187/22347021/8928743e-e406-11e6-8a16-28b0e23c6d39.png)

This is from console.log (firs row is where clause who use to find function), second row is posts.length

**Comment by kogutu** [comment]
I know where is problem:
When I have id_lek with "-" on end.
![image](https://cloud.githubusercontent.com/assets/1575187/22405521/59fbcee6-e644-11e6-92be-174e3cff08bd.png)

Where clause working, when my id is without "-" where clause is not working.

Tell my why, when add "-" to the  id is work, without is don't

**Comment by siddhipai** [comment]
Hey @kogutu 
I reproduced your issue on local and I get the response as expected 

![image](https://cloud.githubusercontent.com/assets/15273582/23237177/0e58c270-f911-11e6-9318-6029d2f453f8.png)

![image](https://cloud.githubusercontent.com/assets/15273582/23237195/242a66da-f911-11e6-951b-2c0d3a1f0256.png)

Please try to reproduce it on your machine too with new data. And let us know if you get it.

**Comment by siddhipai** [comment]
This is kind of weird when I reproduced this issue with mongodb.
There is some kind of restriction with the format of the number that @kogutu is passing.

I have created a boot script which is:
![image](https://cloud.githubusercontent.com/assets/15273582/23270016/3ed6b0b0-f9a7-11e6-9706-162d4b2bb21d.png)

and if i run the code I get:

![image](https://cloud.githubusercontent.com/assets/15273582/23270960/8daab9cc-f9aa-11e6-9e6b-b12299f339b9.png)

But any other format/ same length id_lek /different length id_lek will work. for e.g

![image](https://cloud.githubusercontent.com/assets/15273582/23271054/f3ccfb02-f9aa-11e6-98db-d2db33c70a4a.png)

output:
![image](https://cloud.githubusercontent.com/assets/15273582/23271058/fa441cd6-f9aa-11e6-841c-5ab9973814e0.png)
