### ISSUE TITLE
Loopback 3.2 user observe loaded returns ctx undefined

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#3142]
I have updated loopback 2.x to 3.x, using an accessToken supplied request to load an user object from db I am receiving _undefined_ ctx.
```
User.observe('loaded', function loaded(ctx, next) {
console.log(ctx); // prints undefined now
});
```
any ideas?

**Comment by barocsi** [comment]
> Note: In LoopBack 2.x, the find* methods (find, findOne, findById and findByIds) provide instance in their loaded operation hook. All other methods provide the data object in their loaded operation hook. This difference is corrected in version 3.0

**Comment by barocsi** [comment]
But, just explain me, in 3.x for loaded there is ctx.data, for other hooks its ctx.instance...what is the reasoning behind?

**Comment by barocsi** [comment]
@bajtos bump?

**Comment by bajtos** [comment]
@barocsi How can I reproduce the problem on my machine? Could you please create a small app per our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)?

**Comment by bajtos** [comment]
Closing as abandoned. Feel free to reopen if/when you can provide us with more details as requested by my previous comment.
