### ISSUE TITLE
Loopback 3.x updateAttributes on user 'loaded' hook ctx.data contains only attribute

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#3147]
So far when calling updateAttributes on a model, the observe 'loaded' hook returned instance data properly in 2.x. 

In 3.x it only holds reference to the ctx.data containing solely the data from the updateAttribute parameters. And the ctx has a parameter (undocumented) originalUser. 

How can 'loaded' user can be accessed consistently and safely during an updateAttributes call?

```
user.updateAttribute('last_post_date', new Date(), function (err, result) {
							if (err) {
								winston.error("Post.new::update user::user.updateAttribute",
									{
										postId: post_instance.id.toString(),
										userId: user.id.toString(),
										error: err
									});
							}
							cb_update_user();
						})
```
yields a ctx containing:
```
{ _ctx: '{"data":{"last_post_date":"2017-01-27T09:54:51.568Z"},"hookState":{"isPasswordChange":false,"originalUserData":[{"id":"588b18d3cd95e72f81df6871","email":"a24@a.com"}]},"options":{},"isNewInst
ance":false}',
```
Why 'loaded' hook even returns anything other than the targeted model instance properly? I mean returning the information to be updated is not the behaviour one would expect. One would expect the whole user instance to be returned.

**Comment by barocsi** [comment]
Bump? This is still a serious problem...

**Comment by luncht1me** [comment]
I'm facing simmilar issues with updateAttribute and having validation on my model, I believe it's related.

```
	/* validate slug */
	User.validatesUniquenessOf('slug', { message: 'slug is not unique (duplicate name)' });

	/* Hooks */

	/* Set Slugs on saving a user */
	User.observe('before save', function setSlug(ctx, next) {
		console.log("slug hook", ctx.currentInstance);
		for(var k in ctx){ console.log(k)}
		if (ctx.instance) {
			console.log("instance", ctx.instance);
			ctx.instance.slug = slugify(ctx.instance.username);
		} else {
			console.log("data", ctx.data);
			ctx.data.slug = slugify(ctx.data.username);
		}
		next();
	});
```

When I try and do a `user.updateAttribute()`, the beforeSave fires again, but the `ctx.data` only has the attribute I updated. Even though my `ctx.currentInstance` does include the full user object, the `slug` validation fires, because `data` is only the attribute I've chosen to update. So, I effectively can't run `updateAttribute` if I have any kind of validation present.
