### ISSUE TITLE
ctx in beforeRemote hooks and ctx in operation hooks

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#3155]
"The context object is specific to operation hooks and does not have any relation to the context object passed to remote hooks registered via Model.beforeRemote and Model.afterRemote."

Why even we call them the same, if they purport different ways.

How can they can be connected? 

I would like to somehow figure out currentUser and pass it down to the chain so it will be received by remote and operation hook handlers.

How is this possible?

**Comment by shaheero** [comment]
I believe this is related to https://github.com/strongloop/loopback/issues/569
For your question, have a look at https://github.com/strongloop/loopback/issues/569#issuecomment-257749777
