### ISSUE TITLE
createOptionsFromRemotingContext callback?

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#3156]
I want all my models to include specific user information therefore tried to implement
```
MyModel.createOptionsFromRemotingContext = function(ctx) {
  var base = this.base.createOptionsFromRemotingContext(ctx);
  return extend(base, {
    currentUserId: base.accessToken && base.accessToken.userId,
  });
};
```
However where the framework knows If I try to async do something and its finished, so the model is populated with extra information fetched from a database? There is no callback.

Or shall we do all the async stuff in a beforeRemote mixin? Would be great, but for some reason that is called AFTER a model observe 'access' happens.

**Comment by loay** [comment]
Is this issue a duplicate? https://github.com/strongloop/loopback/issues/3157

**Comment by ebarault** [comment]
@loay : No they are different. 
Cc @bajtos: in case you'd have missed them

**Comment by bajtos** [comment]
Hello, `createOptionsFromRemotingContext` is always synchronous right now. https://loopback.io/doc/en/lb3/Using-current-context.html#customize-the-value-provided-to-options for other options how to customize the context, some of them allow async computation.

I am labelling this issue as `doc`, I think we should make it clear what extension points support async computation and which do not.
