### ISSUE TITLE
createOptionsFromRemotingContext only runs once

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#3157]
Created a mixin that adds some extra variable to the options object for supposedly all models.
for the first time it runs, and visible in an 'access' hooks ctx.options object for MODEL_A. 
However, when from the remotemethod I run another remote method (passing option properly) and that remote method tries to load another model MODEL_B, in that 'access' hook ctx.options object I can see nothing.
Supposedly createOptionsFromRemotingContext  should populate every model.
Tried to add the createOptionsFromRemotingContext directly to that other model as well, but it would not run at all.

**Comment by bajtos** [comment]
@barocsi please create a small app reproducing the problem per our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report.
