### ISSUE TITLE
[BUG] custom role resolver called regardless configuration

### ISSUE THREAD

**Issue by pierreclr** [strongloop/loopback#3159]
Hi, 

I actually encounter a problem with custom dynamic role resolve.

### Description ###

considering this ACL on a model : 
```
{
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "myCustomRole",
      "permission": "ALLOW",
      "properties": "findById"
    }
```

and the following `registerResolver` in boot folder:  
``` 
Role.registerResolver('myCustomRole', (role, context, cb) => {
   console.log('trying to resolve custom role');
});
```

### Expected result ###
We should only see 'trying to resolve custom role' on findById / READ remote call. (depending on the ACL configuration

### Actual result ###
On any remoteMethod, the resolver is called. So I need to add `if (!context.remotingContext.methodString.match(/findById/)) return cb(null, false)` to make it works 

Maybe I'm doing it the wrong way ?
@bajtos Any direction for correcting the problem ? (That way I can make a PR)

**Comment by bajtos** [comment]
> custom role resolver called regardless configuration

I am afraid I am not familiar with ACLs enough to help here.

@raymondfeng @ritch @superkhau can you help please?

@pierreclr While we are waiting for response, could you please create a small app reproducing the issue per our [bug-reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)? It will make it easier for us to investigate your issue.

**Comment by superkhau** [comment]
@pierreclr I don't see any issue with your code. What happens when you fully resolve:

```
Role.registerResolver('myCustomRole', (role, context, cb) => {
   cb(null, true)
});
```

Does the ACL kick in after resolving your user?

1. If the ACL doesn't kick in after your resolver, then it's probably a bug
2. If it does kick in, then things are working properly and failing because you didn't finish resolving the custom role resolver

As suggested by @bajtos, please provide a link to a sample repo for us to try to reproduce on our machine.

**Comment by pierreclr** [comment]
@superkhau Thank you for your answer. I now understand how the custom role resolver works ... 
Doing the following : 
``` 
Role.registerResolver('myCustomRole', (role, context, cb) => {
   // All these async functions will be called on every methods
   app.models.User.findById('myId')
      .then(user => {
         // This console log will pop on every method
         console.log(context.remotingContext.methodString);
        // Here the role is resolved but the ACL system will ignore this result regarding to its configuration
         cb(null, true);
      })
});
```

However here we are executing some unused code since we don't want to resolve this role on `updateAttributes` for example. Isn't it more performant to only execute it on the concerned methods ? Especially when we need to fetch information from the database !

**Comment by superkhau** [comment]
>Isn't it more performant to only execute it on the concerned methods

IMO, the way you're describing would be more performant (ie. the ACL should scope down to only the method being asked before trying to determine access). I don't think the current implementation operates in this fashion as you discovered. I'll definitely bring it up during our conversations on loopback-next.

cc @raymondfeng
