### ISSUE TITLE
[SUPPORT] Polymorphic realtions use case

### ISSUE THREAD

**Issue by luckylooke** [strongloop/loopback#3164]
Hello, can you give me a hint how to setup simple polymorphic relations?

Lets say we have book which belongs to author model and also belongs to publisher model. 

Thanks

PS: I was not able to do so according loopback documentation.. :/

**Comment by 0candy** [comment]
Hi @luckylooke, Have you taken a look at the getting started tutorial. It shows an example of setting up the model relations.
See https://loopback.io/doc/en/lb3/Define-model-relations.html

**Comment by luckylooke** [comment]
Thanks for link I already have done both tutorials (Getting started I, II), I didnt notice that reviews belongs to shops and reviewers as well.. so what are polymorphic relations for?? It seems that they do the same thing.

**Comment by raymondfeng** [comment]
Please check out https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/relations.test.js#L1672

**Comment by luckylooke** [comment]
@raymondfeng thanks, very good idea.. It should come to my mind. But I still dont understand use case :/ Could you point me the case where I should pick polymorphic relations instead of common relation and why? Many many thanks.

**Comment by raymondfeng** [comment]
@luckylooke See http://guides.rubyonrails.org/association_basics.html#polymorphic-associations. Polymorphic relation is only needed if you have to relate to other models with different types. For example, both Student and Teacher can borrow books.

**Comment by luckylooke** [comment]
@raymondfeng I cant see any advantage of polymorphic belongsto from common belongs to. 
"For example, both Student and Teacher can borrow books." It is same as both coffeeshops and reviewers can have reviews, like in examples here https://loopback.io/doc/en/lb3/Define-model-relations.html. It means that it also suits for statement `relate to other models with different types` So what do I get in addition by using polymorphic relation?
