### ISSUE TITLE
[SUGGESTION] `ORDER BY` optional

### ISSUE THREAD

**Issue by nmahefa** [strongloop/loopback#3168]
Hello,

It's possible to make `ORDER BY` optional ?
for example SELECT query are builded like this 

`SELECT * from "foo.foo" ORDER BY "id" `

it would be cool if we can use scope, to disable the order by like this (for example, "order" to true instead of string" ) :
`"scope": {
    "order": false 
}`

Thanks.

**Comment by raymondfeng** [comment]
Can you try `"scope": { "order": [""] }`?

**Comment by nmahefa** [comment]
In my models.json :
`"scope": { "order": [""] }`

the result output :
`SELECT \"id\",\"k\",\"u\",\"t\" FROM \"p\".\"u\" ORDER BY`.

**Comment by raymondfeng** [comment]
Hmm, that's bad. We need to filter out empty strings.

Maybe we should relax https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1476 to `filter.order != null` and normalize `false` to `""`
