### ISSUE TITLE
logoutSessionsOnSensitiveChanges Warning 

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback#3175]
### Bug/Feature request

LoopBack 2 now adds a warning when you use a User model and do NOT set logoutSessionsOnSensitiveChanges to true. This is fine and all, but you get the warning twice - once for User, and once for your model that extends User. While it is possible that a person may use User, since we always tell people to extend it, the warning should be disable for the User model itself.

### Expected result

Don't warn twice.

**Comment by cfjedimaster** [comment]
Sorry - this was LoopBack 2, not 3.

**Comment by zealseeker** [comment]
Do you know how to configure the json file of the User models and whether should we add into user.json in loopback modules or the persisted models we create? If the former, I am afraid it will warn again as long as I update loopback for fixing some bugs.

**Comment by cfjedimaster** [comment]
Well since this is apparently gone in 3 (I believe), it may be a non-issue.

**Comment by zealseeker** [comment]
I solved this problem by adding `"logoutSessionsOnSensitiveChanges": ture` in server/config.json.

**Comment by bajtos** [comment]
@cfjedimaster it makes me wonder, does your `server/model-config.json` perhaps include both the built-in `User` model and the custom user model? If that's the case, then you should remove the `User` entry from your `server/model-config.json` file. IIRC, we print the warning for each User-like model configured in the application.

**Comment by cfjedimaster** [comment]
Well to be clear, if this is gone in 3, we can close it, right?

**Comment by bajtos** [comment]
LoopBack 2.x is still a supported version and I think most people have not migrated to 3.x yet. Therefore the issue may affect many LoopBack users, IMO it's worth investigating and fixing.

**Comment by zealseeker** [comment]
Hi, @bajtos . When I set `logoutSessionsOnSensitiveChanges` as true in `config.json`, error will happen:
```
TypeError: Cannot read property 'email' of undefined
at /root/loopback/bestjobs/node_modules/loopback/common/models/user.js:884:80
```
Then I removed this line. Interestingly, the newest version did not warn again. But I think this `logoutSessionsOnSensitiveChanges` is recommanded by you, isn't it?

**Comment by cfjedimaster** [comment]
I'll check - I'm on the road this week though so its going to be hard to find time.

**Comment by bajtos** [comment]
@zealseeker please open a new issue and provide steps to reproduce the issue - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
