### ISSUE TITLE
Using custom named foreign keys breaks relations

### ISSUE THREAD

**Issue by Sturgelose** [strongloop/loopback#3181]
### Bug request

Create two simple classes, for example, Country and City.
* Country **has many** Cities
* A City **belongs to** a Country

Instead of setting the default `foreignKey` value (countryId), set it to `country`, in both relationships.

As a result, endpoints such as `GET /Cities/{id}/country` and `GET /Countries/{id}/cities/{fk}` will return either NULL or an error.

Used classes:

```
// country.json
{
  "name": "Country",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "code": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "cities": {
      "type": "hasMany",
      "model": "City",
      "foreignKey": "country"
    }
  },
  "acls": [],
  "methods": {}
}

```

```
// city.json
{
  "name": "City",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "code": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "country": {
      "type": "belongsTo",
      "model": "Country",
      "foreignKey": "country"
    }
  },
  "acls": [],
  "methods": {}
}

```

### Expected result

Return proper answer, even if I'm using custom named keys.

### Additional information

I ran all this in a clean scaffolded setup. No strange configurations. All the information was added through the questions asked in Loopback CLI.

darwin x64 7.4.0
├── loopback@3.2.1
├── loopback-boot@2.23.0
├── loopback-component-explorer@4.1.0

**Comment by alFReD-NSH** [comment]
With the current state and design of Loopback, you shouldn't name the foreignKey same as the relation. [Here's](http://stackoverflow.com/q/41556519/774086) a similar problem.
