### ISSUE TITLE
Password too long user model

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback#3184]
Suddenly loopback started to check my generated password length. Is this by design? I'm not sure that from which version it is doing this:
```
Error: Password too long: xxxx
    at Function.User.validatePassword (/srv/api/node_modules/loopback/common/models/user.js:650:13)
```

Why even 72 chars is the max passwords length? What if I am storing an OAuth hash generated by a 3rd party provider?

From which point does it event started to validate my passwords built in?

Why on earth would it started to validate the email, in a DIFFERENT module? So we re validating password in user.js but validating email throwing an error in a DAO layer at /node_modules/loopback/node_modules/loopback-datasource-juggler/lib/dao.js:3146:16 which error is not even saying anything about why the email address is invalid.
loopback-datasource-juggler is 3.10.8

**Comment by bajtos** [comment]
Hello, the restriction on the maximum password value is intentional, see https://loopback.io/doc/en/lb2/Security-advisory-08-16a-2016.html
