### ISSUE TITLE
after save - data undefined?

### ISSUE THREAD

**Issue by uhallgarn** [strongloop/loopback#3186]
Hi,

I am writing an 'after save'- hook and have some problem to read data. What I would like to do is to access data in another model, but when doing this it is undefined. Here is some code.

```
module.exports = function(Fault) {

  Fault.observe('after save', function(ctx, next) {
    ctx.Model.app.models.faulttype.find({where:{id:ctx.instance.faulttypeId}}, function(err, faulttype) {
      if (err)
        console.log(err);
      console.log(faulttype);
      console.log(faulttype.slogan);
      etc.....
}
```

I also tried to use Fault.app.models.faulttype.find instead of ctx.Model.app.models.faulttype.app as in the example above, however with same result.

I am using the ctx.Model.app.models to grab one of the other models I have (faulttype). The problem is then later when I use it. In the first console.log it is writing all attributes and values for the faulttype, but when I try to use a specific attribute, as in the second console.log where I uses faulttype.slogan I get the response that it is undefined. Don't understand why?

Any ideas/comments?

Regards,
Ulf

**Comment by farlymedicaboo** [comment]
i don't know this is the proper way, can you try to faulttype JSON.stringfy(faulttype) and then faulttype = JSON.parse(faulttype); ?

**Comment by uhallgarn** [comment]
I tried to change that, but it didn't make any difference.
Very strange that I can view the entire objetc, but not the specific attribute.
