### ISSUE TITLE
ACL is not working with datasource

### ISSUE THREAD

**Issue by NaqeebSial** [strongloop/loopback#3191]
Acl not work when datasource of acl model is changed.I have this case in my db 
  { "model":"product"
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    }

this work when i add it to product.json directly but not when i have linked acl model with datasource

**Comment by upupzealot** [comment]
same problem, do you solved this issue?
