### ISSUE TITLE
App object is Undefined

### ISSUE THREAD

**Issue by totalard** [strongloop/loopback#3194]
I shave created many boot scripts in boot directory.
Some of them  Started like this

var app = require('../server");
 console(app);

I. Getting undefined in some boot scripts and working fine in some boot scripts.

Is it a bug?   How this happening?

Somebody give me detailed info please

**Comment by siddhipai** [comment]
Hi @totalard  ,
Could you provide more details with boot scripts' codes that are failing?

**Comment by totalard** [comment]
I will do it soon. Do you still need it?

**Comment by siddhipai** [comment]
@totalard yes i do..please send it here.
