### ISSUE TITLE
Provide a "start" command

### ISSUE THREAD

**Issue by lazaridis-com** [strongloop/loopback#3200]
The `lb` command line tool should have a `start` command.

This would simplify the usage, especially for newcomers (they don't know much about the underlying stack).

Additionally, it would be more consistent in general (one command-line tool, "lb").

### Current Status

```shell
$ lb app todo
$ cd todo 
$ lb model
$ node .
```

### With "start" Command

```shell
$ lb app todo
$ cd todo 
$ lb model
$ lb start
```

**Comment by superkhau** [comment]
Issue moved to [strongloop/loopback-cli #15](https://github.com/strongloop/loopback-cli/issues/15) via [**ZenHub**](https://www.zenhub.com/)
