### ISSUE TITLE
How to create replica set in Loopback for Mongodb ?

### ISSUE THREAD

**Issue by vishnukarthikreddy** [strongloop/loopback#3201]
Hi Coders,

Am creating replica set in Loopback for Mongodb. Could anyone suggest me how to create it ?
This is my first attempt for Replication.

Thank you in advance.

Greetings,
Vishnu Karthik.

**Comment by dhmlau** [comment]
Is this something you're looking for? 
https://medium.com/towards-data-science/how-to-deploy-a-mongodb-replica-set-using-docker-6d0b9ac00e49
