### ISSUE TITLE
Connection to MongoDB fails

### ISSUE THREAD

**Issue by wohldani** [strongloop/loopback#3202]
Connecting to MongoDB has stopped working: 

> MongoError: option host is not supported

node_modules/loopback/lib/application.js:246
MongoError: Cannot create data source "mongo": Cannot initialize connector "mongodb": option host is not supported

darwin x64 4.4.6

├── loopback@2.38.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@2.7.0
├── loopback-component-passport@2.3.0
├── loopback-connector-mongodb@1.18.0
├── loopback-datasource-juggler@2.54.0
├── loopback-ds-timestamp-mixin@3.4.0

**Comment by xdgimf** [comment]
There's an [issue](https://github.com/strongloop/loopback-connector-mongodb/issues/344) on loopback-connector-mongodb
