### ISSUE TITLE
User model has no index for email attribute by default

### ISSUE THREAD

**Issue by siegiw** [strongloop/loopback#3203]
This has a major performance hit on login by email for large user scale, at least on my postgres db.
Annoying especially when using autoupdate, resulting in drop of indices that were manually created

from loopback user.json:
```
  ...
  "properties": {
    "realm": {
      "type": "string"
    },
    "username": {
      "type": "string"
    },
    "password": {
      "type": "string",
      "required": true
    },
    "email": {
      "type": "string",
      "required": true
    },
    "emailVerified": "boolean",
    "verificationToken": "string"
  },
  ...
```

I tried subclassing user and defining an appropriate index, which unfortunately results in erratic creating/destroy of the email index, possibly due to race conditions:

from common/models/user.json:
```
   ...
  "properties": {
    "email": {
      "type": "string",
      "required": true,
      "index": true
    }
  },
  ...
```

**Comment by jpradeep2003** [comment]
This is a major issue. I am wondering why it has no response whatsoever. Is nobody facing this? Is it not a valid issue? Is there an obvious workaround? Can somebody please update this issue with some useful guidance.
