### ISSUE TITLE
Suggestion: automatically register components

### ISSUE THREAD

**Issue by WebStackDev** [strongloop/loopback#3206]
Currently there seems to be no way to find out at run-time which components were loaded via component-config* files, unless each component registers itself via app.set() when it bootstraps itself (just like loopback-component-explorer does https://github.com/strongloop/loopback-component-explorer/blob/ffb09f9d4d14e3a15909255cc31bf272e0ee4cf2/index.js#L38).

As a developer, in case you need to load a third party component that does not have this self registering behavior, you cannot do a conditional check like this https://github.com/strongloop/loopback-getting-started/blob/master/server/server.js#L14. 

As far as I can tell, you could potentially programmatically parse every component-config* file in a boot script and register the problematic components yourself via app.set(). 

But wouldn't it be more convenient for this to be supported out of the box by the framework? Maybe have a standard app.loadedComponents object available on the app instance like this:

```
app.get(`loadedComponents`);
// output:
[
  { "loopback-component-explorer": { mountPath: "/explorer" } },
  { "another-component": { mountPath: "/another-component" } },
  ...
]
```

**Comment by bajtos** [comment]
@raymondfeng @davidcheung how does this fit use case into the new loopback-boot design?

**Comment by WebStackDev** [comment]
I will also post here for reference the temporary work-around as described above:

```
// Components registration boot script: ./server/boot/registerComponents.js 
'use strict';
var fs = require('fs');

module.exports = function(server) {
  var env = server.get('env');
  var componentsConfigJSON = fs.existsSync('./server/component-config.json') && require('../component-config.json') || {};
  var componentsConfigLocalJSON = fs.existsSync('./server/component-config.local.json') && require('../component-config.local.json') || {};
  var componentsConfigLocalJS = fs.existsSync('./server/component-config.local.js') && require('../component-config.local.js') || {};
  var componentsConfigEnvJSON = fs.existsSync('./server/component-config.' + env + '.json') && require('../component-config.' + env + '.json') || {};
  var componentsConfigEnvJS = fs.existsSync('./server/component-config.' + env + '.js') && require('../component-config.' + env + '.js') || {};

  server.set('loadedComponents', Object.assign({}, componentsConfigJSON, componentsConfigLocalJSON, componentsConfigLocalJS, componentsConfigEnvJSON, componentsConfigEnvJS));
};
```

```
// Usage example: ./server/server.js 
app.start = function() {
  ...
  if (app.get('loadedComponents')['loopback-component-visualizer']) {
    var visualizerPath = app.get('loadedComponents')['loopback-component-visualizer'].mountPath;
    console.log('Visualize your models at %s%s', baseUrl, visualizerPath);
  }
  ...
}
```

**Comment by raymondfeng** [comment]
Check this out - https://github.com/strongloop/loopback-boot/blob/master/lib/plugins/component.js. Now each artifact type for LoopBack can have associated handlers that process each phase of the boot lifecycle and each of them can populate more metadata to the runtime.
