### ISSUE TITLE
Connector for Microsoft Azure Table Storage

### ISSUE THREAD

**Issue by xmanemran** [strongloop/loopback#3207]
Hi all, recently I try to make a application use loopback. But we have a dependency , that is I have to use "Microsoft Azure Table Storage". There are no connector available for "Microsoft Azure Table Storage" . Can any one please tell me how I can solve this problem. If I have to make a connector than how can I do that.

**Comment by raymondfeng** [comment]
To use Microsoft Table Storage with LoopBack, you are not required to have a connector (nice to have). There is a Node.js client - https://docs.microsoft.com/en-us/azure/storage/storage-nodejs-how-to-use-table-storage. You can use it directly with LoopBack.

**Comment by xmanemran** [comment]
I all ready write 50% of it. OK man I will try to complete it  @superkhau
