### ISSUE TITLE
How i get My Related Data from model Instance

### ISSUE THREAD

**Issue by totalard** [strongloop/loopback#3210]
Dear,

truble is in node APi
Not Angular SDK

I tried Many time, i have run this code

`Post.findById(1,{
include: 'comments'
}).then(function(posts){
 //Now posts a instance of Post;
})

How i get comments related to it from the instance. ?
like **posts.comments()**

It is not working
One method is working posts.comments.getAsync()
But i Think getAsync will do a seperate query to database, What i need is to get the data that i included to Posts.

Somebody Help`

**Comment by ilkerc** [comment]
As I understood, you want to access the comments of a Post (post/{:id}/comments).
I think you should access them over comments, think "objId" as the fK

```javascript
  function foo() {
    var Comment = Share.app.models.Comment;
    Comment.find({objId: "f9ea5b80-f624-11e6-9d3e-830111e7e609"})
      .then(function(comments) {
        console.log(comments);
      })
  }
```

And I would suggest you to use the [gitter](https://gitter.im/strongloop/loopback) for your questions.
