### ISSUE TITLE
LIMIT-Parameter has strange results on included relations

### ISSUE THREAD

**Issue by MrsBookik** [strongloop/loopback#3220]
# Description/Steps to reproduce

I want to query via REST-API all records of a (parent)-model including its related models. But the latter one i want to limit to a specific amount of maximum records transfered.

#Models:

    -   DEPARTMENT
        Fields:
            - id
            - name 
            - ...
        Relations_ -> hasMany: Messages
        Relations_ -> hasMany: Members

    - MESSAGE
        Fields:
           - id
           - senderId
           - body
           - ...
    
    - MEMBER
        Fields:
           - id
           - email
           - ...

The task is to retrieve all departments, including all members, and the first (or last) message that belongs to this department.

I tried these queries (Disclaimer: i know that parameters should be url-encoded. I leave it clean here for better readability)

1.  `http://loopback-server:3000/api/departments?filter[include]=members&filter[include]=messages&filter[limit.messages]=1`

Result: The limit-parameter will be ignored here.

2.  `http://loopback-server:3000/api/departments?filter={"include":{"relation": "messages","limit":1}} `*

Result: The limit-parameter will be ignored here.

3. `http://loopback-server:3000/api/departments?filter={"include":{"relation": "messages","scope":{"limit":1, "skip":0}}}` *

Result: there are NO messages transfered any more expect on one department. Omitting the scope-and limit paramter returns all messages to the department-objects and shows that there are plenty of....

# Expected result

Being able to limit the count of included entities (and hopefully to sort them for a specific column)

# Additional information

>  node -e 'console.log(process.platform, process.arch, process.versions.node)'
`linux x64 4.2.6`

>  npm ls --prod --depth 0 | grep loopback

```
├── loopback@2.38.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@2.7.0
├── loopback-connector-mongodb@1.18.1
├── loopback-connector-mysql@2.4.1
├── loopback-datasource-juggler@2.54.0
├── loopback-ds-timestamp-mixin@3.4.0

```

**Comment by bajtos** [comment]
@MrsBookik thank you for reporting the issue.

> The task is to retrieve all departments, including all members, and the first (or last) message that belongs to this department.
> `http://loopback-server:3000/api/departments?filter={"include":{"relation": "messages","scope":{"limit":1, "skip":0}}}`
> Result: there are NO messages transfered any more expect on one department. Omitting the scope-and limit paramter returns all messages to the department-objects and shows that there are plenty of....

@strongloop/sq-lb-apex @raymondfeng while I am not very familiar with relations myself, the URL looks legit to me. Should such request work as expected by the user (do we have a bug)? Is there any other way how to implement the requested use-case?

**Comment by jannyHou** [comment]
I think the right api would be
```js
{
  include: [
    {relation: 'messages', scope: {limit: 1, skip: 0}},
    'members'
  ]
}
```

> http://loopback-server:3000/api/departments?filter={"include":{"relation": "messages","scope":{"limit":1, "skip":0}}}

Looks good to me too, it should return only one record if records exist, instead of "NO messages transfered any more "

**Comment by bajtos** [comment]
Thank you @jannyHou!

@MrsBookik Could you please create a sample app with the models and sample data you described? It will make it much easier for us to debug this issue. See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
