### ISSUE TITLE
Before create hook modelInstance

### ISSUE THREAD

**Issue by timlind** [strongloop/loopback#3223]
Documentation should be provided for what modelInstance refers to on a before remote create hook, is it invalid, is it a model instance containing the input values, or is it a model instance prior to mixing in the values from args.data, can args.data be manipulated before?
```
Model.beforeRemote('create', (ctx, modelInstance, next) => {
    // modelInstance is a plain empty object here
});
```
The current documentation specifically mentions modelInstance for the create hook, but it seems to be completely useless?

```
Instance methods and static built-in methods such as upsert() or  create() require a third argument in the callback:

_modelName_.beforeRemote( _methodName_, function( ctx, _modelInstance_, next) {
    //...
    next();
});
```

# Expected result

Documentation should indicate the use of modelInstance, or it should be null.

# Additional information

**Comment by ritch** [comment]
https://loopback.io/doc/en/lb3/Remote-hooks.html does mention it several times.

Do you have some specific suggestions? Do you mind proposing a PR against github.com/strongloop/loopback.io ??

**Comment by superkhau** [comment]
I'm going to escalate this to bug, when I reproduce on my machine, I also get an empty object as described by @timlind. I expected to get a reference to model instance that is being created (before the actual creation).

**Comment by superkhau** [comment]
1. Either docs need to explain why we get back empty object
2. Update the code to give me a proper reference to the model before insertion (and doc updates if this is the case)

**Comment by mrfelton** [comment]
Confirmed. I always just get an empty object in this argument. It would certainly be helpful if the affected model instance was readily available here instead. Currently we have to take manual steps to load the existing instance.
