### ISSUE TITLE
Remote hooks on remote methods are not working when called from other model

### ISSUE THREAD

**Issue by NaqeebSial** [strongloop/loopback#3224]
I know that remote hooks are middleware and apply only when a remote method is called from a client side, fine but what if I want to call a remote method from another model, my hooks on that remote model should work even then also because it is a part of my domain policy that whenever my  particular remote method is called a particular hook should be trigger. Remote hooks work fine on remote method when a remote method is called from a client side, but not when called from another related model.

Solution to this problem is that we should apply same remote hook logic for **address** in staff remote hook or inside **staff** remote method, but this will increase duplication of code mean if there are too many remote methods in **staff** model that require **address** model remote method there would be lot of code duplication against address model, more our models will become tightly coupled.

Is there any other solution to this problem

My code sample is

**Staff.json**
```
{
  "name": "staff",
  "base": "User",
  "idInjection": true,
  "strict":true,
  "options": {
    "validateUpsert": true
  },
  "forceId": true,
  "properties": {
    "credentials": false,
    "challenges": false,
    "status": false },
  "validations": [],
  "relations": {
    "addresses": {
      "type": "hasMany",
      "model": "address",
      "foreignKey": "userId"
    }
  },
  "acls": [],
  "methods": {}
}
```
**Staff.js**
```
module.exports = function(Staff) {  
    Staff.newstaff=function(options,cb){
        Staff.create(options.user,function(err,staff){ 
		    if(!err){
			    staff.addresses.create(options.address,function(err,add){
				    if(!err){
					    cb();
					}
				}
			}
		}
    }
    Staff.remoteMethod(
        'newstaff',
        {
            description: 'register a staff with address',
            accepts: [
               {arg: 'options', type: 'object',required:true,http:{source:'body'}}
            ],
            returns: {arg: 'engineSound', type: 'string'},
            http: {verb: 'post', path: '/newstaff'}
        }  
    );
}
```

**Address.js**
```
module.exports = function(Address) {
    Address.afterRemote("create",function(ctx,address,next){
          console.log("THIS IS CALLED WHEN ADDRESS CREATE METHOD IS CALLED FROM CLIENT SIDE, BUT I WANT TO CALL IT WHEN ADDRESS IS CREATED FROM STAFF MODEL");
next();
    })
}
```

**Comment by bajtos** [comment]
@NaqeebSial I am afraid this how remote hooks work by the definition. Please consider using [Operation Hooks](https://loopback.io/doc/en/lb3/Operation-hooks.html) instead, they were designed specifically for use cases like "do something whenever a model instance was changed", which seems to be your situation.
