### ISSUE TITLE
No way to do a count/exists with a JOIN (without writing SQL)

### ISSUE THREAD

**Issue by PaddyMann** [strongloop/loopback#3225]
# Description/Steps to reproduce

Currently `count` only takes a `where` argument rather than a `filter`. 

I'm looking to do  check that a user has a `UserProjectRole` for a given `Organization`. It needs to join `UserProjectRole` with `Project` in order to check this.

There seems to be no solution for this.

My workaround is to write SQL:

    const sql = `
      SELECT COUNT(*) AS roleExists
      FROM UserProjectRole
      INNER JOIN Project ON UserProjectRole.projectId = Project.id AND Project.deleted = 0
      WHERE UserProjectRole.deleted = 0
        AND organizationId = :organizationId
        AND userId = :userId
      LIMIT 1
    `;
    const [unnamedSql, unnamedParams] = namedPlaceholders(sql, {organizationId, userId});
    const projectRoleExists = await new Promise((resolve, reject) =>
      UserProjectRole.dataSource.connector.query(unnamedSql, unnamedParams, (err, result) => { // eslint-disable-line arrow-body-style
        return err ? reject(err) : resolve(result[0].roleExists);
      })
    );

# Expected result

I should be able to call:

    const projectRoleExists = await UserProjectRole.count({
      include: ['project'],
      where: {
        and: [
          {organizationId},
          {userId},
        ],
      },
      limit: 1,
    }).

You might need to specify the join type. A syntax like the following would work:

    const projectRoleExists = await UserProjectRole.count({
      include: [
        {relation: 'project', joinType: 'INNER JOIN'},
      ],
      where: {
        and: [
          {organizationId},
          {userId},
        ],
      },
      limit: 1,
    }).

Or even better (for my immediate use-case):

    const projectRoleExists = await UserProjectRole.exists({
      include: [
        {relation: 'project', joinType: 'INNER JOIN'},
      ],
      where: {
        and: [
          {organizationId},
          {userId},
        ],
      },
    }).

Benefits:

- Avoid SQL when it's not needed (+ the associated headaches of needing to replace named parameters)
- Avoid risk of bugs in the SQL - e.g. if I'd forgotten to think about how we handle soft-deleting (which is normally handled by a mixin)
- Remove a big confusion point for new Loopback developers about count, deleteAll, updateAll using `where` rather than `filter`
- Improve performance of `exists` style checks by allowing us to easily `limit` the `count`

**Comment by bajtos** [comment]
Hi @PaddyMann, thank you for a detailed feature request, it makes sense to me. AFAIK, LoopBack does not perform any JOIN queries right now, we are always sending several SQL commands when relations are involved. Adding support for JOIN is a non-trivial task, see https://github.com/strongloop/loopback/issues/517.

So while I wish there was an easy way how to support your use case, I am afraid it won't be available anytime soon.

**Comment by PaddyMann** [comment]
Sure - thanks for the update
