### ISSUE TITLE
New mechanism of forwarding request context via options arg does not work for model.find()

### ISSUE THREAD

**Issue by simenko** [strongloop/loopback#3228]
I am trying to access request context via new mechanism of passing "options" object from remote method down to model methods. 

I have "loaded"  operation hook on a user model:
```
user.observe('loaded', (ctx, next) => {
       // do some stuff with ctx.options
     ....
```
I have a custom remote method, taking options from request, and I have some calls to user.model.findById() and user.model.find() in this method. I forward options argument as described here: https://strongloop.com/strongblog/context-propagation-in-loopback/ 

It works for model.findById():
```
user.findById(userId, {}, options).then(.....
```

But it doesn't work for model.find():
```
user.find({/* where filter */}, options).then(.....

**Comment by bajtos** [comment]
@simenko thank you for the bug report. Could you please create a small app we can use to reproduce the problem on our side? See our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report).
