### ISSUE TITLE
Make it easy to configure custom JSON response format

### ISSUE THREAD

**Issue by OSMeteor** [strongloop/loopback#3229]
- like this  {code:200,msg:"sucess",result:{}}  format all api .  
- i can not write rest.js res

**Comment by bajtos** [comment]
Hi @OSMeteor, LoopBack does not provide direct API for customising response format. However, there are hooks that can be leveraged to achieve that - see the implementation in https://www.npmjs.com/package/loopback-component-jsonapi for inspiration.

**Comment by OSMeteor** [comment]
is good idea but i need format  code to jsonapi   @bajtos

**Comment by OSMeteor** [comment]
like this    module.exports = function (app) {
  app.remotes().after('**', function (ctx, next) {
      ctx.result = {"code":200,msg:"sss",result:ctx.result};
      next();
  })
}

**Comment by OSMeteor** [comment]
``` javascript
module.exports = function (app) {
  app.remotes().after('**', function (ctx, next) {
      ctx.result = {"code":200,msg:"sss",result:ctx.result};
      next();
  })
}
```

**Comment by bajtos** [comment]
> is good idea but i need format code to jsonapi

Have you tried https://www.npmjs.com/package/loopback-component-jsonapi ? It's a component that's adding JSON API support to LoopBack applications.
