### ISSUE TITLE
HasMany through relationship is not working when we explicitely add the id attribute

### ISSUE THREAD

**Issue by mathewvino** [strongloop/loopback#3232]
Hi there,

Here are the three tables mapping;

Notice: If  we remove the id attribute from student/course table the join relationship will work:

I am looking for the following : Give me all the courses for student:

**Will work the below url** if we remove the id attributes from both tables (Student/course).
http://localhost:3000/api/students?filter[include]=courses

**Will not  work the below url if we explicitely add the id attributes from both tables (Student/course)** below
http://localhost:3000/api/students?filter[include]=courses

Student:
************************************************************
{
  "name": "Student",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
  **"id": {
      "type": "string",
      "id": true
    },**
   "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "courses": {
      "type": "hasMany",
      "model": "Course",
      "foreignKey": "studentId",
     "through": "Studcours"
   }
  },
  "acls": [],
  "methods": {}
}

**************************************************************
2) Course 
{
  "name": "Course",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
   "id": {
      "type": "string",
      "id": true
    },
    "subject": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "students": {
      "type": "hasMany",
      "model": "Student",
      "foreignKey": "courseId",
      "through": "Studcours"
    }
  },
  "acls": [],
  "methods": {}
}

*****************************************************************************
3) mapping table: Studcours

{
  "name": "Studcours",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "startDate": {
      "type": "date"
    }
  },
  "validations": [],
  "relations": {
    "student": {
      "type": "belongsTo",
      "model": "Student",
      "foreignKey": "studentId"
    },
    "course": {
      "type": "belongsTo",
      "model": "Course",
      "foreignKey": "courseId"
    }
  },
  "acls": [],
  "methods": {}
}

Here is the output I get:

Request URL:
http://localhost:3000/api/Students/58b08334bb217da88ab673fd/courses

Response Code: 200

date": "Fri, 24 Feb 2017 22:31:03 GMT",
  "x-content-type-options": "nosniff",
  **"x-frame-options": "DENY",**
  "etag": "W/\"2-11FxOYiYfpMxmANj4kGJzg\"",
  "x-download-options": "noopen",
  "vary": "Origin",
  "content-type": "application/json; charset=utf-8",
  "access-control-allow-credentials": "true",
  "content-length": "2",
  "x-xss-protection": "1; mode=block"

thanks
Vinoj

**Comment by deepakrkris** [comment]
@mathewvino which version of loopback are you testing with, I tested your model definitions, with loopback 3.x and the relations seems to work fine with and without the id field

**Comment by mathewvino** [comment]
Deepak.

i am using the below version, for me its works  only when i am not adding any id attributes explicitely.
 loopback@3.2.1

No issues for adding records using loopback explorer. if i add the explicit id  attributes and trying to access  courses using student. Only the below link is not displaying the records.

http://localhost:3000/api/Students/58b08334bb217da88ab673fd/courses

thanks

**Comment by deepakrkris** [comment]
@mathewvino , may be this is specific to a db (like mongodb), could you please provide a sample workspace like, https://github.com/KevinMongiello/loopback_include_bug

**Comment by mathewvino** [comment]
Hi Deepak,

I made some changes making the "idInjection": false and added the id field for both student and course.

The database i am using is Mongodb. I can insert the data using strongloop explorer.

Following steps did

1) post the student  --- verified its works fine -- instering data in mongodb
2) POST /Students/{id}/courses --- insert the course using the above id -- verified and its pushing the data to both course table  and mapping table studcours table
3)GET /Students/{id}/courses ---- use the id to get the course --- This is not getting the records
below is the url
http://localhost:3000/api/Students/58b582a46c11806e94e227d7/courses


I have copied the code in github. Please take a look and let me know if i am doing something wrong

https://github.com/mathewvino/loopback_bug_3232

Thanks
Vinoj
