### ISSUE TITLE
Disable POST endpoint of replaceOrCreate method and keep PUT only

### ISSUE THREAD

**Issue by Freundschaft** [strongloop/loopback#3234]
Hi everybody,

when I have replaceOrCreate on an endpoint, it always shows me PUT and POST for replaceorcreate, I only want the PUT endpoint, but not the POSt endpoint. Is that possible?

I checked the loopback source and figured this out:

`var replaceOrCreateOptions = {
      description: 'Replace an existing model instance or insert a new one into the data source.',
      accessType: 'WRITE',
      accepts: [
        {
          arg: 'data', type: 'object', model: typeName,
          http: {source: 'body'},
          description: 'Model instance data',
        },
        {arg: 'options', type: 'object', http: 'optionsFromRequest'},
      ],
      returns: {arg: 'data', type: typeName, root: true},
      http: [{verb: 'post', path: '/replaceOrCreate'}],
    };

    if (options.replaceOnPUT) {
      replaceOrCreateOptions.http.push({verb: 'put', path: '/'});
    }
`

its kind of annoying that I always have to get both, and if I disable replaceorcreate, then I have neither the PUT nor the POST method.
Any ideas?

**Comment by bajtos** [comment]
@Freundschaft I see your point. I am afraid there is no easy way for achieving that right now.

Do you have any proposals how to support your use case? Could you perhaps contribute the change yourself?

**Comment by Freundschaft** [comment]
Hi @bajtos 

currently I am using loopback to quickly build a prototype backend, which then will be used as a blueprint by another company to implement a production grade system.
They are using swagger.json as a reference, and I only want to include interfaces that this other company needs to build, I already disabled everything I dont need, but I dont seem to be able to disable this last function.

I'll have a look on how to make that contribution, will check

**Comment by bajtos** [comment]
@Freundschaft A possible workaround: hide `replaceOrCreate` method from the API using [disableRemoteMethod()](https://loopback.io/doc/en/lb3/Exposing-models-over-REST.html), then write a custom method wrapping `replaceOrCreate` that will be exposed only on the `POST` endpoint.

**Comment by Freundschaft** [comment]
@bajtos yes thats what I ultimately did, thanks!
