### ISSUE TITLE
How to modify SOAP headers at runtime

### ISSUE THREAD

**Issue by quimarche** [strongloop/loopback#3236]
I need to generate an MD5 hash from the query parameters and add it to the SOAP headers for each request. What's the best way of doing this?

**Comment by deepakrkris** [comment]
@quimarche can you please raise the issue in loopback-connector-soap , https://github.com/strongloop/loopback-connector-soap, we have an associate looking at the issues in that repository

**Comment by deepakrkris** [comment]
@quimarche you can add a middleware script to 
- [ ] take the query parameters and create a hash
- [ ] set the hash in the context
Please refer, 
https://loopback.io/doc/en/lb3/Defining-middleware.html

If you use a custom remote method, then a custom mapping function can access the request object and create the hash,
Please refer,
http://loopback.io/doc/en/lb3/Remote-methods.html#http-mapping-of-input-arguments
