### ISSUE TITLE
HasMany through relationship is not working when we explicitely add the id attribute

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#3237]
@mathewvino commented on [Mon Feb 27 2017](https://github.com/strongloop/loopback.io/issues/295)

Hi there,

Here are the three tables mapping;

Notice: If we remove the id attribute from student/course table the join relationship will work:

I am looking for the following : Give me all the courses for student:

Will work the below url if we remove the id attributes from both tables (Student/course).
http://localhost:3000/api/Students/58b43668f905fd5f7cbfc50e/courses

Will not work the below url if we explicitely add the id attributes from both tables (Student/course) below
http://localhost:3000/api/Students/58b43668f905fd5f7cbfc50e/courses

Student:
```
{
"name": "Student",
"base": "PersistedModel",
"idInjection": true,
"options": {
"validateUpsert": true
},
"properties": {
"id": {
"type": "string",
"id": true
},
"name": {
"type": "string"
}
},
"validations": [],
"relations": {
"courses": {
"type": "hasMany",
"model": "Course",
"foreignKey": "studentId",
"through": "Studcours"
}
},
"acls": [],
"methods": {}
}
```
***********************************************************************************
Course - table

```
{
"name": "Course",
"base": "PersistedModel",
"idInjection": true,
"options": {
"validateUpsert": true
},
"properties": {
"id": {
"type": "string",
"id": true
},
"subject": {
"type": "string"
}
},
"validations": [],
"relations": {
"students": {
"type": "hasMany",
"model": "Student",
"foreignKey": "courseId",
"through": "Studcours"
}
},
"acls": [],
"methods": {}
}
```
********************************************************************
mapping table: Studcours

```
{
"name": "Studcours",
"base": "PersistedModel",
"idInjection": true,
"options": {
"validateUpsert": true
},
"properties": {
"startDate": {
"type": "date"
}
},
"validations": [],
"relations": {
"student": {
"type": "belongsTo",
"model": "Student",
"foreignKey": "studentId"
},
"course": {
"type": "belongsTo",
"model": "Course",
"foreignKey": "courseId"
}
},
"acls": [],
"methods": {}
}
```
Here is the output I get:

Request URL:
http://localhost:3000/api/Students/58b08334bb217da88ab673fd/courses

Response Code: 200

date": "Fri, 24 Feb 2017 22:31:03 GMT",
"x-content-type-options": "nosniff",
"x-frame-options": "DENY",
"etag": "W/"2-11FxOYiYfpMxmANj4kGJzg"",
"x-download-options": "noopen",
"vary": "Origin",
"content-type": "application/json; charset=utf-8",
"access-control-allow-credentials": "true",
"content-length": "2",
"x-xss-protection": "1; mode=block"

thanks
Vinoj

---

@crandmck commented on [Mon Feb 27 2017](https://github.com/strongloop/loopback.io/issues/295#issuecomment-282808926)

I don't think this is a documentation issue, so I'm going to move it to the loopback repo.

**Comment by NaqeebSial** [comment]
You can't use "idInjection": true along with custom id property because "idInjection" would create a same field name in your database so either you can use your on id in model property or "idInjection": true, in this case I would suggest you to remove id property from your model then it will work.

**Comment by mathewvino** [comment]
Hi Naqeeb,

I made some changes making the "idInjection": false and added the id field for both student and course.

The database i am using is Mongodb. I can insert the data using strongloop explorer.

Following steps did

1) post the student  --- verified its works fine -- instering data in mongodb
2) POST /Students/{id}/courses --- insert the course using the above id -- verified and its pushing the data to both course table  and mapping table studcours table
3)GET /Students/{id}/courses ---- use the id to get the course --- This is not getting the records
below is the url
http://localhost:3000/api/Students/58b582a46c11806e94e227d7/courses


I have copied the code in github. Please take a look and let me know if i am doing something wrong

https://github.com/mathewvino/loopback_bug_3232

Thanks
Vinoj

**Comment by bajtos** [comment]
@strongloop/sq-lb-apex this looks to be relations-related, could you please triage?

**Comment by bajtos** [comment]
Closing as a duplicate of https://github.com/strongloop/loopback/issues/3232
