### ISSUE TITLE
user verification resend email multiple verification tokens 

### ISSUE THREAD

**Issue by autovipdeveloper** [strongloop/loopback#3239]
each time **user.verify()** is called it adds another token to the email verification link

Thanks for registering. Please follow the link below to complete your registration.
https://192.168.0.108:80/api/Clients/confirm?uid=2&redirect=%2F&token=63e415dedbffe4fed5d9ce34f2faad465f7e379198336ae5a17b6bade48a7b19226af973cc1f569a137c0a769c6c534024ac16cc64d077f40915becc80fb3ee9&token=5d6db9b4b95199b80d303ebd01b147bacda72fe9fd74f88b05aaec50148b96518bdc9d58b79c2968353f24a1aeefdcde5bb015517dd362d24ddb203f3ec5a256&token=6305fc6d9d4bb155e98e710f70956fb0d729668afdce67641e39adb3aaa5c8952b0cdc1bb0bd42252ec72732aaf0e83edcf8fbb4c44bae5dd334f556f53b302f

**Comment by bajtos** [comment]
@autovipdeveloper thank you for the bug report. Could you please create a small app reproducing the problem, per our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)?

**Comment by bajtos** [comment]
Closed as abandoned. Feel free to reopen if/when you can provide us with more details as requested by my previous comment.
