### ISSUE TITLE
Feature Request - $owner access control for all custom resources

### ISSUE THREAD

**Issue by kevintelford** [strongloop/loopback#3241]
As suggested by @ebarault this is a separate issue from https://github.com/strongloop/loopback/issues/2366

To summarize, I've created a custom model called Posts. A user may create zero to many, and these Posts are private to the user (my actual need isn't Posts, but works well enough). Using loopback, I want to create ACLs to only allow a user to view their own Posts. Furthermore, I want to display the user their last 5 most recent Posts.

I want to issue a query to find the users last 5 Posts, AND I don't want other users to be able to see that users Posts.
`GET /api/posts?filter[where][ownerId]=123&[order]=updatedAt%20DESC&filter[limit]=5`
But how can I craft the ACL? I want to say
```
{
  "accessType": "*",
  "principalType": "ROLE",
  "principalId": "$everyone",
  "permission": "DENY",
  "property": "*"
},
{
  "accessType": "*",
  "principalType": "ROLE",
  "principalId": "$owner",
  "permission": "ALLOW",
  "property": "*"
}
```
But the $owner ACL doesn't get applied to my find query ([src](http://loopback.io/doc/en/lb3/Defining-and-using-roles.html))
>  Note:
To qualify a $owner, the target model needs to have a belongsTo relation to the User model (or a model extends from User) and property matching the foreign key of the target model instance.  The check for $owner is only performed for a remote method that has ‘:id’ on the path, for example, GET /api/users/:id.

I could change and use $authenticated, but then any authenticated user could peek into the GET request being issued and craft their own using the Authenticate header and get someone else's Posts, which is not good.

At this point the $owner ACL is only applied to some of the resources, or in other words, _sometimes security_. I suspect the reasons for the current implementation, but it'd still be nice to have $owner cover all resources.

**Comment by BoLaMN** [comment]
correct $owner only works for the related endpoints as that's how the role resolver knows what id it is, you could probably create your own role resolver that some how iterates through every possible combination that the ownerId could be provided (and/or, nested and/or statements) but its not really a performent iteration.

I normally set the model not to be public so it's only accessible through the related endpoint
