### ISSUE TITLE
Calling loopback API methods directly

### ISSUE THREAD

**Issue by sukheja-varun** [strongloop/loopback#3243]
Questions:
 Unable to call API methods using have many relation ,directly in loopback remote method.

# Description/Steps to reproduce

I have a model with relation: organisation has many folders and folder belongs organisation.
I can see API: /Organisation/{id}/folders
I want to call the methods corresponding to this API directly in my another remote methods.
Like : 
Organisation.folders(id, function (err, response) {
                cb(null, response);
            });

# Expected result
Needs folders for given organisationId.

**Comment by ebarault** [comment]
hi @sukheja-varun : as you can see in https://loopback.io/doc/en/lb2/HasMany-relations.html#methods-added-to-the-model, 
> Once you define a “hasMany” relation, LoopBack adds a method with the relation name to the declaring model class’s prototype automatically

methods are added on model class's prototype: meaning that you can do the following in your code:
```
anOrganisation.folders(id, function (err, response) {
  cb(null, response);
});
```
where `anOrganisation` is an **instance** of Organization.

doing 
```
Organisation.folders(id, function (err, response) {
  cb(null, response);
});
```
is not relevant here

you should then do something like
```
Organisation.findById(id, function (err, organization) {
  organization.folders(function (err, response) {
    cb(null, response);
  });  
});
```

**Comment by 0candy** [comment]
Hi @sukheja-varun , did @ebarault 's answer resolve your issue?

**Comment by sukheja-varun** [comment]
Hi @0candy, @ebarault answered my question and it worked perfectly

**Comment by ebarault** [comment]
Closing as solved
