### ISSUE TITLE
Avoid committing db credentials to datasources.json

### ISSUE THREAD

**Issue by timlind** [strongloop/loopback#3246]
# Description/Steps to reproduce

Datasource credentials should come from env variables and committing to source code should not be encouraged. 

A templating solution which allows reference to env variables should be implemented.

# Expected result

A templating solution which allows reference to env variables should be implemented.

# Additional information

Documentation should discourage storing credentials in source code and link to further documentation describing setting up the datasource in javascript or using template variables

**Comment by timlind** [comment]
https://github.com/timlind/loopback.io/commit/be726363b9c5aeee019f9d6b261ebe72a28be299

**Comment by ebarault** [comment]
hi @timlind ,
thanks for sharing thoughts and providing some excerpts for doc improvement.

i guess you've seen [this page](https://loopback.io/doc/en/lb3/Advanced-topics-data-sources.html) already on how to set up datasources programmatically.

you're right that in a production scenario people should avoid committing the db credentials to the source code (i assume you are referring here to the `datasources.json` file.

Although, i believe defining the datasources programmatically only would be counter productive and against LoopBack philosophy, which aims at reducing the boiler plate. 

I think we should be able to pass only the critical information through env variables, while keeping the rest in the datasources.*.json files.

@bajtos @superkhau : maybe is this already available?
@timlind : if not, would you like to contribute such a feature?

**Comment by superkhau** [comment]
>I think we should be able to pass only the critical information through env variables, while keeping the rest in the datasources.*.json files.

@ebarault Thanks for chiming in, yes this feature is available by creating a `datasources.*.js` instead. In that file, where you normally put in your credentials, use `process.env.YOUR_ENV_VAR`. 

See https://github.com/strongloop/loopback-example-offline-sync/blob/master/server/datasources.staging.js#L12.

**Comment by superkhau** [comment]
For posterity, the docs are at https://loopback.io/doc/en/lb2/Environment-specific-configuration.html.

**Comment by ebarault** [comment]
excellent, thanks @superkhau : am i wrong to think the doc is missing?
i guess it addresses your concern @timlind

**Comment by timlind** [comment]
@superkhau That's great to know. I'll avoid defining data source programmatically then. The issue that remains though (see #317) is that for someone defining a DS programmatically it is really tricky as the example in doc is not working and there is no explanation of whether a partial configuration still needs to exist in datasources.json, whether model-config.js can still be used to associate to a model, or where programmatic datasources should be defined and where they should be associated to model (i.e you can't do so in model.js using attachTo, if datasource is defined in bootscript). cc @crandmck 

Thanks for following through @ebarault

**Comment by ebarault** [comment]
for sake of completeness and keep track for a potential doc improvement PR: 

> Is it possible to define a datasource programmatically and still have the model-config link the models to it? I get an error that the DS doesn't exist when trying that

@bajtos commented: 

You have two options:
1) define your datasource before calling boot
2) assuming you only need programmatic way for providing datasource configuration, because the datasource name is static anyways, then you can export your programmatic datasource config in server/datasources.local.js

**Comment by bajtos** [comment]
There is no need to write custom `.js` files if the only requirement is to configure certain datasource properties from ENV vars. loopback-boot already provides a simple templating mechanism for that - see https://github.com/strongloop/loopback-boot/issues/4 and https://github.com/strongloop/loopback-boot/issues/4#issuecomment-213557135 in particular.

I would personally recommend to use a connection string in production to ensure that all configuration options are reset - see https://github.com/strongloop/loopback/issues/2089.

```js
// server/datasources.json
{
  "db": {
    "connector": "mysql",
    "url": "${MYSQL_DB_URL}",
    // configuration below is for Development/Test environments only
    "host": "localhost",
    "database": "my-database-name",
    // etc.
  }
}
```

Production setup:

```sh
export MYSQL_DB_URL=mysql://admin:pass@localhost/test
```

I don't know if this feature is properly documented, perhaps that's the thing to improve?

**Comment by bajtos** [comment]
Looks like https://github.com/strongloop/loopback.io/pull/319 was already opened to improve this part of our documentation 👍
