### ISSUE TITLE
enhance context passing in OWNER role resolver

### ISSUE THREAD

**Issue by ebarault** [strongloop/loopback#3250]
### Description

In regards to: https://github.com/strongloop/loopback/pull/3230

With the move to explicit context passing of an `options` object, internal calls to `find` etc needed to be updated to pass the necessary information along, too. In this case, `isOwner` calls `findById` on a Model, but does not pass an access token in `options`.

In https://github.com/strongloop/loopback/pull/3230, @bajtos fixed the content of passed options to `{accessToken: context.accessToken}` (see [here](https://github.com/strongloop/loopback/pull/3230/files#diff-733982793c3bd5e61d1a4350451fb494R185) whereas a way to customize the passed options is generally available (see [doc](https://loopback.io/doc/en/lb3/Using-current-context.html#override-createoptionsfromremotingcontext-in-your-model))

But what if a user wants extra customization on top of that to get extra parameters in the passed options? An extreme solution could be for the developer to override the whole Role model to specify his own way of registering the role resolver, but we can probably provide an easier way of customizing the passed options.

__NOTE__: We should also address other internal calls of built-in CRUD methods that would require passing options.

**Comment by bajtos** [comment]
One option is to add a new `Role` method to build the "options" object passed to `Role.isOwner`. Subclassed models then can override this method, although I am not sure how easy it is to configure LoopBack app to use own `Role` model.

```js
Role.createIsOwnerOptions = function(accessContext) {
  return {accessToken:accessContext.accessToken};
}
```

Another option that comes to my mind is to add support for 4-arg role resolvers with the signature `(role, context, options, callback)`. The catch is how to support promise-based resolvers and distinguish between `(role, context, callback)` and `(role, context, options)`?

Any other ideas?

**Comment by ebarault** [comment]
still thinking about this. For the record in #2957 i chose to use a [method that can be overriden](https://github.com/strongloop/loopback/pull/2957/files/7906fb3c382d22c034c509b9360acd303ecf4fae#diff-45d772e3be7eacd9da2cc827f5076382R579), as you suggest in your first proposition.
