### ISSUE TITLE
Excluding properties from base model does not work

### ISSUE THREAD

**Issue by skleeschulte** [strongloop/loopback#3256]
# Description/Steps to reproduce

- Extend the base User model and set `properties.realm = false` and `properties.username = null`:

```json
{
  "name": "user",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "realm": false,
    "username": null
  },
  "options": {
    "caseSensitiveEmail": false
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

- Create a new user (POST /api/users) -> realm and username can be added to the new user without error.

```json
{
  "email": "alice@email.com",
  "password": "1234",
  "realm": "myRealm",
  "username": "alice"
}
```

- Login and show own userdata (GET /api/users/1) -> realm and username are in the response.

```json
{
  "email": "alice@email.com",
  "id": 1,
  "realm": "myRealm",
  "username": "alice"
}
```

# Expected result

According to the docs ([Model definition JSON file / Exclude properties from base model](http://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#exclude-properties-from-base-model)), setting properties to false or null in a model should exclude these properties from being visible. So I would at least expect them not to be included in the response to GET /api/users/1.

In addition I wonder how I can completely remove unneeded properties from a base model, so that they cannot be set, won't be validated and no column is created for them...

# Additional information

win32 x64 6.9.1

+-- loopback@3.4.0
+-- loopback-boot@2.23.0
+-- loopback-component-explorer@4.1.1

**Comment by ebarault** [comment]
hi @skleeschulte 
- what connector do you use for your test? memory, mongodb?
- are you using strict validation over the incriminated model ? (as [here](https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#top-level-properties))

if you don't use strict and your db is NoSQL then you can add whatever property to your model with a POST, it is a standard behavior. If your db is SQL, then there's something more to dig in.

setting properties to false or null in a model + using strict is the correct way to completely remove unneeded properties inherited from base model.

**Comment by skleeschulte** [comment]
I was using the memory connector and did not use the strict validation. With `"strict": true` it is working as I expected it. Thank you!

**Comment by AbhishekBatwara** [comment]
I am extending the User model and setting below properties to false/null
    "realm": false,
    "username": null,
    "emailVerified": false,
    "verificationToken": null

Below is my model
{
  "name": "users",
  "base": "User",
  "strict": false,
  "options": {
    "idInjection": true,
    "mysql": {
      "schema": "test",
      "table": "users"
    },
  },
  "properties": {
    "realm": false,
    "username": null,
    "emailVerified": false,
    "verificationToken": null,
    "firstName": {
      "type": "String",
      "required": false,
      "length": 32,
      "precision": null,
      "scale": null,
      "mysql": {
        "columnName": "first_name",
        "dataType": "varchar",
        "dataLength": 32,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "N"
      }
    },
    "lastName": {
      "type": "String",
      "required": false,
      "length": 32,
      "precision": null,
      "scale": null,
      "mysql": {
        "columnName": "last_name",
        "dataType": "varchar",
        "dataLength": 32,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "Y"
      }
    },
    "email": {
      "type": "String",
      "required": true,
      "length": 128,
      "precision": null,
      "scale": null,
      "mysql": {
        "columnName": "email",
        "dataType": "varchar",
        "dataLength": 128,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "N"
      }
    },
    "password": {
      "type": "String",
      "required": true,
      "length": 256,
      "precision": null,
      "scale": null,
      "mysql": {
        "columnName": "password",
        "dataType": "varchar",
        "dataLength": 256,
        "dataPrecision": null,
        "dataScale": null,
        "nullable": "N"
      }
    }
  }
}


The only difference is I am using mysql database. using above approach I am able to register the user. but when I am trying to login it gives error like "login failed".
Unhandled error for request POST /api/users/login: Error: login failed

Is there anything I am missing here?
