### ISSUE TITLE
About price

### ISSUE THREAD

**Issue by EminentStar** [strongloop/loopback#3260]
# Description/Steps to reproduce

Hello, I'm Junkyu Park and a developer in Korea.
 
I'm writing this issue so that I could get some information regarding Loopback API Gateway.
 
In the below URL, there is information installing loopback api gateway in local computer.
( URL: https://strongloop.com/get-started/?S_TACT=S_OFF_CD=&cm_mmc=Website_Strongloop-_-IBM+Software_API+Connect-_-WW_WW-_-Get_started_with_npm_install&cm_mmca1=&cm_mmca2= )
I also saw the pricing policy from the below URL.
( URL: http://www-03.ibm.com/software/products/en/api-connect#othertab2 )
There are 3 types of editions.(Essentials, Professional, Enterprise)
I was wondering if I have to pay for using api-gatewaay service when I install it in local computer. (NOT IN cloud service)
 

Thank you.

# Expected result

# Additional information

**Comment by aydonat** [comment]
Hello Junkyu Park, 

You can use the free APIC Essentials Developer Toolkit to create your Loopback applications and use the microgateway in your computer. Please see https://www.npmjs.com/package/apiconnect for instructions on how to download.

Regards

**Comment by EminentStar** [comment]
Thanks.!
