### ISSUE TITLE
Role and Role-Mapping do not work with wrong data type

### ISSUE THREAD

**Issue by codejie** [strongloop/loopback#3268]
# Description/Steps to reproduce
I added a new Role and set a user to the Role, in Role-Mapping model of mongodb look like this,

{
    "_id" : ObjectId("58c228ad2dd774367b857126"),
    "principalType" : "USER",
    "principalId" : "58c1380699220526baa9477b",
    "roleId" : ObjectId("58c21117df1db02b1425882c")
}

Please note the type of principalId is STRING, this is defined in Role-Mapping model JSON, and roleId is OBJECTID, it is not in the model JSON file.

But in Role.js, the codes for checking role-mapping, it is in the below lines.(Role.js:424)

      async.some(context.principals, function(p, done) {
        var principalType = p.type || undefined;
        var principalId = p.id || undefined;
        **#var roleId = result.id.toString();
        var principalIdIsString = typeof principalId === 'string';**

        **if (principalId !== null && principalId !== undefined && !principalIdIsString) {
          principalId = principalId.toString();
        }**

        if (principalType && principalId) {
          roleMappingModel.findOne({where: {roleId: roleId,
            principalType: principalType, principalId: principalId}},
            function(err, result) {
              debug('Role mapping found: %j', result);
              done(!err && result); // The only arg is the result
            });
        } else {
          process.nextTick(function() {
            done(false);
          });
        }
      }, function(inRole) {
        debug('isInRole() returns: %j', inRole);
        if (callback) callback(null, inRole);
      });
    });

Well, it will not find the user of in Role-Mapping model, acl is failure.

# Expected result

So I cannot use custom Role in loopback. 
I think maybe Role and PrincipalId should be OBJECTID type.

# Additional information
Thanks.

**Comment by codejie** [comment]
base on [issue#3263](https://github.com/strongloop/loopback/issues/3263), I resolved the problem. please check the answer of bajtos (@bajtos).

I am not sure if my problem is a issue or not. Or the above lines were the root cause of issue#3263? because I cannot understand why those types use STRING not OBJECTID, it is not reasonable.

**Comment by ebarault** [comment]
@codejie: the new thing here compared to #3263 would be that the LoopBack's ACL system does not work out-of-box with custom roles, without specifying the `strictObjectIDCoercion` option.
```diff
    {
       name: 'RoleMapping',
       dataSource: 'db',
+      options: {
+        strictObjectIDCoercion: true,
+      },
       public: false,
     },
```

I never encountered this i believe and people's issues regarding the incorrect type of principalId are rather collateral. Would you mind providing a sandbox reproducing your issue?
(see [reporting issues](https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report))

**Comment by codejie** [comment]
Thanks for your concern, it is true that after I added 'strictObjectIDCoercion' to model-config, ROLE, ROLE-MAPPING and ACL worked. I think loopback would convert STRING to OBJECTID in right way after did like this, because I tried to change all STRING related to ROLE-MAPPING to OBJECT in loopback, it worked.

please check below my system information.

>uname -a
Darwin 192.168.0.105 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

>node --version
v6.9.5

>npm list | grep loopback
├── eslint-config-loopback@7.0.1
├─┬ loopback@3.4.0
│ ├── loopback-connector-remote@3.1.1
│ ├─┬ loopback-datasource-juggler@3.2.0
│ │ └─┬ loopback-connector@3.0.0
│ ├─┬ loopback-phase@1.4.1
│ │ ├── loopback-datatype-geopoint@1.0.0
├─┬ loopback-boot@2.23.0
├─┬ loopback-component-explorer@4.1.1
│ ├─┬ loopback-swagger@3.0.1
├─┬ loopback-connector-kv-redis@1.1.0
│ └─┬ loopback-connector@2.7.1
├─┬ loopback-connector-mongodb@1.18.1
│ ├── loopback-connector@2.7.1
├─┬ loopback-connector-rest@2.1.0
├─┬ loopback-connector-soap@4.0.0

**Comment by habbes** [comment]
Also facing this issue, used to detect roles properly, but now it doesn't. I'm not entirely sure how to go about the proposed solution of adding the option to the `RoleMapping` model, since I'm using the built-in model which is located in `node_modules` and not in my app's `models` @ebarault @codejie

**Comment by habbes** [comment]
Thanks, I figured it out, the setting is in `server/model-config.json`
