### ISSUE TITLE
Change to response object in afterError hook not formatted as expected

### ISSUE THREAD

**Issue by developermhayden** [strongloop/loopback#3269]
In my hook.js file I have:

```
remotes.afterError('**', function(ctx, next, method){
        ctx.error = {
            code: ctx.error.statusCode,
            statusCode: ctx.error.statusCode,
            error: true,
            errors: [{
                message: ctx.error.message
            }],
            data: []
        };
        return next(ctx.error);
    });
```

My response object looks like this:
```
{
  "error": {
    "statusCode": 401,
    "code": 401,
    "error": true,
    "errors": [
      {
        "message": "login failed"
      }
    ],
    "data": []
  }
}
```
Why does it NOT look like this:

```
{
    "statusCode": 401,
    "code": 401,
    "error": true,
    "errors": [
      {
        "message": "login failed"
      }
    ],
    "data": []
  }
```

Which is the same thing minus the wrapping in an error object.

**Comment by bajtos** [comment]
The error response format is controller by error-handling middleware, which is typically strong-error-handler in LoopBack 3.x and recently scaffolded LoopBack 2.x applications.

You can replace strong-error-handler with your own middleware to control the format of JSON responses.

We had considered the ability to configure the format of HTTP responses in strong-error-handler too, but didn't have bandwidth to implement it yet - see https://github.com/strongloop/strong-error-handler/issues/8. Contributions welcome!
