### ISSUE TITLE
websocket connector for loopback

### ISSUE THREAD

**Issue by joshua1** [strongloop/loopback#327]
will be nice to be able to specify REST or web sockets as the channel API to expose.for instance using socket.io or a loopback socket connector.
if there is a websockets-connector kind of plugin for loopback that will access the same methods exposed via the rest api via web sockets.

An important thing to consider: support in native SDKS - iOS, Android, Xamarin.

See also https://github.com/strongloop/strong-remoting/issues/139

**Comment by stephanMettler** [comment]
+1

**Comment by makersu** [comment]
Here's my Loopback with socket.io chat example.
https://github.com/makersu/loopbackchat

**Comment by HilkoLantinga** [comment]
Makersu, that's not what we are after. We want to use it to communicate to API's build with loopback.

**Comment by psi-4ward** [comment]
I ended up using sails.js cause getting the model create/update/delete notifications in my angular app is essential

**Comment by zephyr4434** [comment]
+1

**Comment by fusionstrings** [comment]
:+1:

**Comment by ilianaza** [comment]
+1

**Comment by makersu** [comment]
Is salis.js implementation like 3-way data binding with firebase and angular.js?
BTW, How to implement  3-way data binding with loopback?
Thanks!

**Comment by psi-4ward** [comment]
Back on loopback :smirk: 

Heres my idea / implementation to mimic the sails-way: [anguloop-example](https://github.com/psi-4ward/anguloop-example) using 
[express-websocket](https://github.com/psi-4ward/express-websocket) and angular [$httpSock](https://github.com/psi-4ward/anguloop-example/blob/master/packages/socket-test/angular/services/httpSock.js) service

@makersu theres no 3-way binding and for most usecases you dont want that but it should not a big deal to implement it. Keep in mind, this would result in many requests and database actions

**Comment by ritch** [comment]
> At the moment, both strong-remoting and LoopBack support RPC pattern only. We need to enhance both modules with PubSub semantics, preferably in a way that is transport-agnostic and thus support multiple PubSub protocols. This is our homework that must be done inside strong-remoting and loopback.

@bajtos Instead of doing this in **strong-remoting** I'd prefer to leave strong-remoting as is and introduce a new module **loopback-messaging**. This will support things like bi-directional messaging, pub sub, etc. On top of this I'd like to build `Model.subscribe()` which would notify observers of model changes.

**Comment by arik-so** [comment]
+1

**Comment by Telemakhos** [comment]
Is there an ETA for sprint65?

**Comment by altsang** [comment]
@Telemakhos sprint 65 is slated to start 3/10, we run 2 week sprints that start on a Tuesday and end on the Monday the week after

**Comment by sajjad-ser** [comment]
+1

**Comment by jorgeramos** [comment]
+1

**Comment by mrbatista** [comment]
+1

**Comment by movibe** [comment]
+ 1

**Comment by rajaraodv** [comment]
+!

**Comment by lennybr** [comment]
+1

**Comment by Ijmir** [comment]
so it is not going to be in sprint 65?

**Comment by mattaylor** [comment]
+1 for https://github.com/gritzko/swarm

**Comment by altsang** [comment]
@ljmir - this capability has actually been rolled into a pub-sub feature that @ritch has been putting the finishing touches on, we're working on examples and docs at the moment - getting there folks! thx for your patience

**Comment by movibe** [comment]
thanks @altsang !

**Comment by altsang** [comment]
boy if you guys only knew how long this has been sitting in our backlog - :stuck_out_tongue: , proof though that we really do keep tabs on stuff wanted/needed and try to work on them when we're not having to meet customer reqs

been a long time coming...

**Comment by Telemakhos** [comment]
Fantastic! Going to try this is an financial ticker we're building rather soon... Thanks to the StrongLoop team! I guess these are the packages... 

https://github.com/strongloop/strong-pubsub
https://github.com/strongloop/strong-pubsub-primus

:trollface:

**Comment by altsang** [comment]
that is correct, I'm really glad we were finally able to get this in, we're very close

a lot of the use cases are driven by our exposure to early IoT customers, aside from websocket with a Primus interface, MQTT, we're looking at STOMP next and others

**Comment by altsang** [comment]
closing this issue, folks please see strongloop/strong-pubsub#7, @ritch is putting the finishing touches on it!

**Comment by mattblang** [comment]
@altsang Wonderful news!  Like @psi-4ward, this is essential for my application.

**Comment by altsang** [comment]
@mattblang - it's out there, @ritch blogged out what it does, the next step is to marry it up with our replication capabilities to better support use cases like offline sync w/o having it be client initiated, what are you building if I may ask?

**Comment by rovyoper** [comment]
+1

**Comment by mattblang** [comment]
@altsang I am building a room tracking system with Angular that uses WebSockets to stay synced across clients.

**Comment by mattblang** [comment]
@altsang Is it correct if I say that right now `MQTT` is the only protocol supported for `pubsub`?

**Comment by altsang** [comment]
@mattblang strong-pubsub is protocol and transport independent.  You can use your own protocol or the MQTT module we built.  We're considering supporting STOMP next up depending on customer demand.  For transport, you might be interested in Primus to take advantage of wrap around websocket support.  You could even do MQTT packets through websocket using Mosquito adapter.  For more info - https://strongloop.com/strongblog/introducing-strongloops-unopinionated-pubsub/.

**Comment by danielmihai** [comment]
+1

**Comment by cyclops24** [comment]
+1

**Comment by vpedrosa** [comment]
+1

**Comment by pktippa** [comment]
+1 Much needed feature in loopback, atleast take this up in 
https://github.com/strongloop/loopback-next

**Comment by pktippa** [comment]
@bajtos done!.

**Comment by bajtos** [comment]
Thanks. Let's move further discussion to https://github.com/strongloop/loopback-next/issues/1883 then.
