### ISSUE TITLE
How to Exclude Relation from the base class

### ISSUE THREAD

**Issue by mathewvino** [strongloop/loopback#3271]
I have a Model extending the Base Model.

The Base Mode has too many properties and relation.

Is there any way we can exclude the relation. In other words I have relation in the Base Model and I don't need to show it in the Derived Model.

For properties I know that we can do  "properties": false on the derived model. How do we exclude the RELATION  from the DerivedModel

Thanks

**Comment by loay** [comment]
@mathewvino 
In the child model json file, you can leave the relation empty and that should override.

**Comment by mathewvino** [comment]
Thanks Loay, How do we do that

Let say I have the derived Model which has some relation. From the Base Model I have one relation  and I dont need to show in the derived model.

For eg From base Model  I have a relation  tags and I don't need to show in the derived model

While adding relation empty its not working. The way I added in below is

"relations": {
   **tags:null,**
     "linkedIdeas": {
      "type": "referencesMany",
      "model": "Idea",
      "foreignKey": "linkedIdeaIds",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
  }

**Comment by loay** [comment]
ok I am sorry I got a bit confused. 
If I understand correctly 
```
"relations": {
}
``` 
does not work

but 
```
"relations": {
tags:null,
}
```
works?? 
Is that what you meant?

**Comment by mathewvino** [comment]
For me its not working.
I  have added  relation like below and its not working

"relations": {
tags:null,
}

The existing relation in our child model is below. Now I need to hide the  tags relation from the parent table. How do we that. Thanks for the help

"relations": {
      "linkedIdeas": {
      "type": "referencesMany",
      "model": "Idea",
      "foreignKey": "linkedIdeaIds",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
  }

**Comment by loay** [comment]
@mathewvino I don't think that you can do that. 
the child inherited the relation already from the parent, then you cannot go back to the parent and remove that relation. The best solution is not to create the relation for the parent, but create a new relation for the child.

**Comment by raymondfeng** [comment]
In your sub-model.js, try the following:
```js
module.exports = function(baseModel) {
  delete baseModel.relations.myRelation; 
}
```

**Comment by mathewvino** [comment]
Thanks ray and loay,

I tried the above two and it seems to be not working. Please guide me if i am doing wrong.

Parent class --> has  below relation

 "relations": {
"linkedCampaigns": {
      "type": "referencesMany",
      "model": "Campaign",
      "foreignKey": "linkedCampaignIds",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
}

Child extends parent and from child we  don't want to see this  parent relation.

we already have some specific relation for the child which is already existing. But from child class I dont want o see the parent relation along with child relation.

so for child model js file  i did the following
 delete Campaign.relations.linkedCampaigns; 

but still no luck. Any help is really appreciate.

Thanks
