### ISSUE TITLE
Change.getModelId is slow

### ISSUE THREAD

**Issue by Traksewt** [strongloop/loopback#3273]
We are seeing Change.getModelId as a performance issue in our profiling when syncing many items. 
I know there is a TODO there, but I was wondering what was the purpose of creating the new model and using setId and getId for the model ID. The creation of the new model is slow due to the copying of the attributes in ModelBaseClass._initProperties (calling toObject). And the getId is slow, as it calls a toObject, which then translates all the model attributes across just to get the Id. In our testing, commenting out the model creation, setId and getId worked OK, but I assume it is in there for a reason (if people overwrite getId?).

```
Change.prototype.getModelId = function() {
    // TODO(ritch) get rid of the need to create an instance
    var Model = this.getModelCtor();
    var id = this.modelId;
    var m = new Model();
    m.setId(id);
    return m.getId();
};

```

So my questions are:
1) What is the purpose of using setId and getId instead of just returning the id variable?
2) If the get/set is needed, is there a faster way to get the Id without needing to translate all the model's attributes across in toObject? I was thinking of a simpler method similar to toObject that just did the Id.
3) Likewise, if we must create a dummy model, how can we do that faster?

**Comment by bajtos** [comment]
```js
Change.prototype.getModelId = function() {
    // TODO(ritch) get rid of the need to create an instance
    var Model = this.getModelCtor();
    var id = this.modelId;
    var m = new Model();
    m.setId(id);
    return m.getId();
};
```

@ritch you are the author of the original code and the `TODO` comment, do you happen to remember your reasoning?

> What is the purpose of using setId and getId instead of just returning the id variable?
>  I assume it is in there for a reason (if people overwrite getId?).

That seems a valid assumption to me, see the comment for `setId` method in `lib/persisted-model.js`:  _Override this method to handle complex IDs_.

Another possible use case that comes to my mind is to ensure `getModelId` returns the value correctly typed. Notice that `change.modelId` is always string, while the actual model id can be a number, a string, or even an ObjectID when using MongoDB.

> If the get/set is needed, is there a faster way to get the Id without needing to translate all the model's attributes across in toObject? I was thinking of a simpler method similar to toObject that just did the Id.
> Likewise, if we must create a dummy model, how can we do that faster?

I am afraid I don't have answers for your questions. Can you look around the code and propose a solution yourself?
