### ISSUE TITLE
Rethinkdb Connector

### ISSUE THREAD

**Issue by YounesKeraressi** [strongloop/loopback#3275]
hey maybe its not the right place to post this here, but i post this already in google groups for loopback and Gitter loopback but dint get any answer,

first of all thanks for your efforts , Please! is there an officiel RethinkDB connector for Loopback created by  RethinkDB developers?

**Comment by bajtos** [comment]
See https://strongloop.com/strongblog/rethinkdb-connector-loopback-node-js-framework/ and https://www.npmjs.com/package/loopback-connector-rethinkdb.

There is no official RethinkDB connector maintained by StrongLoop/IBM.

**Comment by YounesKeraressi** [comment]
thx dude, i already read that post and i couldn't find  loopback-connector-rethinkdb via npm install, its outdated post, about the 2nd link yes i found just few like that already i was just asking if there's an official RethinkDB connector and finally you tell me no :) thx anyway
