### ISSUE TITLE
ctx.options is empty

### ISSUE THREAD

**Issue by tomcooksey** [strongloop/loopback#3276]
# Description/Steps to reproduce
I have this observer declared as a mixin
```
Model.observe('access', function(ctx, next) {

        var at = ctx.options & ctx.options.accessToken;

        next();
    });
```

For brevity I have removed the actual logic - however the issue is that whilst this is populated when using the REST API, if I want to perform an action on a model say in a custom route then this is completely empty.

How can I get the app configured so that this is always populated?  Essentially I am adding items to req in a bunch of middleware that I then need to access within access event of the model.

I therefore configured a custom implementation of createOptionsFromRemotingContext

```
Model.createOptionsFromRemotingContext = function(ctx) {
        var base = this.base.createOptionsFromRemotingContext(ctx);
        return Object.assign(base, {
            fullCtx: ctx,
        });
    };
```

This allows me access to req when using the REST API and is exactly what I need.

It seems weird this works via the REST api but not just generally when accessing a model.  If this doesn't work and I have to do something custom when not using the REST api then this would call into question whether fundamentally loopback is fit for our purpose - the model should surely work consistently however it is accessed?

# Expected result

# Additional information

**Comment by bajtos** [comment]
Hi @tomcooksey, I am afraid I am a bit confused. You started with _whilst this is populated when using the REST API, if I want to perform an action on a model say in a custom route then this is completely empty_, but then you also want _access to req when using the REST API_, which seems unrelated to me.

Could you please create a small repository based on our sandbox repo (see our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)) showing what are you trying to accomplish?

**Comment by tomcooksey** [comment]
Sorry for the radio silence!

Essentially what I am saying is, when I am doing say:

```
organisation.updateAttributes(req.body)
                        .then(function() {
                            res.send('it worked);
                        });
```
I want access, in an 'after save' observe function, for instance, to ctx.options, however this is not present - I understand why, because I am not using the generated API for this action, however I would like some way of passing it as, in this case, the model contains a mixin that does some logic and needs access to items in the request.

I hope that is more clear?

**Comment by tomcooksey** [comment]
Don't worry - have figured out you can pass the options as second parameter in update ops - please close bug.

**Comment by bajtos** [comment]
> have figured out you can pass the options as second parameter in update ops

Yes, that's the correct solution. I am glad you have figured it out on your own! 👏
