### ISSUE TITLE
Make default scope overridable

### ISSUE THREAD

**Issue by smith64fx** [strongloop/loopback#3279]
Hey there!

# Description/Steps to reproduce

I just created a model and also a default scope for its relation:

Mother.json
```json
  "scope": {
    "include": [
      {
        "relation": "children"
      },
    ]
  }
```

When I do a normal query at /api/mother I get all children. Fine.

But when I try this:
```
/api/mother/?filter={"include": [ { "relation": "children", "scope": { "name": "Barney" } } ] }
```

I still get all children.
When I remove the default scope, my query works.

# Expected result

It would be really nice, if the default scope for "children" gets overridden, if I provide a custom scope in my query.

# Additional information

I hope you understand what I mean :)

👍 👍 👍  LOOPBACK IS AWESOME!!!

**Comment by ebarault** [comment]
hi @smith64fx, this is related to datasource-juggler

For track record, see this existing (though outdated) PR: [#787](https://github.com/strongloop/loopback-datasource-juggler/pull/787)

the overall rationale is the following:  
**for security reasons, it should not be possible to override a scope to make it more open**

in your specific case though the rationale does not apply as you narrow the scope. 

:point_right: first of all, check your code: you are missing a `where` clause in your scope:

should be 
```
"include": [ { "relation": "children", "scope": { where: { "name": "Barney" } } } ]
```
