### ISSUE TITLE
Cannot read property 'where' of undefined

### ISSUE THREAD

**Issue by tomcooksey** [strongloop/loopback#3282]
# Description/Steps to reproduce
I have some code that calls destroy() on a model instance and I am getting this error thrown:

Cannot read property 'where' of undefined

The code:

```
orderModel.findById(state.orderId)
            .then(function(order) {
                console.log('Going to destroy order');
                //return resolve();
                order.destroy()
                    .then(function() {
                        resolve();
                    }, function(e) {
                        //Even though an error is thrown, it never gets back into the promise error handler, server just dies.
                        reject(e);
                    });
            });
```

# Expected result
The model should be destroyed

# Additional information

Node version is 6.10.0

Output of npm ls

```
├── loopback@3.4.0
├── loopback-boot@2.19.0
├── loopback-connector-mysql@2.3.0
├── loopback-connector-redis@0.0.3
├── loopback-connector-sendgrid@1.2.3
├── loopback-ds-timestamp-mixin@3.3.0
├── loopback-explorer@1.8.0
```

I am completely stuck with this, I have recently upgraded from Loopback 2 so perhaps I have done something wrong in that process?

**Comment by deepakrkris** [comment]
@tomcooksey findById is not a juggler function and so will not return a dao object, to call destroy(). But by calling find() , we would get an order object and then could call destroy(). Also your implementation of promises seems to be incorrect.

```
module.exports = function(Order) {

  Order.custom = function(id, cb) {
    Order.find({where: {id: id}})
      .then(function(order) {
       order[0].destroy(function(err) {
         if(err) cb(err);
         cb(null);
       });
    });
  }

  Order.remoteMethod('custom', {
    accepts: [{
      arg: 'id',
      type: 'string',
      http: {source: 'path'}}],
    http: {
      verb: 'GET',
      path: '/custom/:id'},
    });
};
```

**Comment by tomcooksey** [comment]
Can you explain why the documentation has a method called findById then? And why it is working elsewhere in my code?

http://apidocs.strongloop.com/loopback/#persistedmodel-findbyid

**Comment by tomcooksey** [comment]
In addition, your suggested fix does not seem to work for me, provided I have implemented it correctly.  Not sure what you mean about not using promises correctly, have pasted the whole code this time:

```
return new Promise(function(resolve, reject) {
        
        var orderModel = loopback.getModelByType('Order');

        orderModel.find({
            where: {
                id: state.orderId
            }
        })
            .then(function(order) {
                console.log('Going to destroy order');

                order = order[0];

                order.destroy()
                    .then(function() {
                        resolve();
                    }, function(e) {
                        reject(e);
                    });
            });
    });

```

I still get the same error.  This is using MySQL not Mongo.

**Comment by tomcooksey** [comment]
Nevermind, I have isolated it to one of my mixins in my model - however it's not correct to say that findById does not work because it does.
