### ISSUE TITLE
Pass relationModel into SharedMethod for use in remote hooks

### ISSUE THREAD

**Issue by jsheely** [strongloop/loopback#3283]
It is useful to know exactly which model class is being referenced in a remote hook without having to look it up by doing a substring of the ```ctx.methodString```

By passing in the ```relationModel``` to the SharedMethod we can then utilize it in any operational hook

```javascript
define('__updateById__' + relationName, {
      isStatic: false,
      relationModel: relation.modelTo, // New relationModel property
      http: {verb: 'put', path: '/' + pathName + '/:fk'},
      accepts: [
        {arg: 'fk', type: 'any',
          description: format('Foreign key for %s', relationName),
          required: true,
          http: {source: 'path'}},
        {arg: 'data', type: 'object', model: toModelName, http: {source: 'body'}},
      ],
      description: format('Update a related item by id for %s.', relationName),
      accessType: 'WRITE',
      returns: {arg: 'result', type: toModelName, root: true},
    }, updateByIdFunc);
```

Then in a remote hook you could do something like
```javascript
// (POST) /api/products/1/part/1
Model.beforeRemote('**', (ctx, inst, next) => {
    let productModel = ctx.method.ctr;
    let partModel = ctx.method.relationModel;
    let data = ctx.args.data; //Contains data for a part model;

    next();
});
```

**Comment by bajtos** [comment]
@jsheely thank you for the proposal, it looks like a reasonable improvement of the current not ideal situation.

@raymondfeng @ritch @superkhau what's your opinion?

**Comment by ebarault** [comment]
what if multiple nesting levels?
// (POST) /api/products/1/part/1/subpart/1

**Comment by bajtos** [comment]
> how should we handle multiple nesting levels?

FWIW, I don't think we support nested scopes yet, see https://github.com/strongloop/loopback/issues/2346

**Comment by ebarault** [comment]
hmm i see... at least we can say it works with a depth of 3 (which is the max i've used so far with built-in methods i believe)

**Comment by dgroch** [comment]
I'm trying to update a related model via custom remote method, but I'm stuck.
Is this possible at the moment?

```
eg. say I want to create the resource at /product/1/variant/1
```

At the moment when I create a variation with `Variant.create()` it is unrelated to a Product

**Comment by bajtos** [comment]
@dgroch I am afraid your question is off-topic here. Please post questions to our mailing list (https://groups.google.com/forum/#!forum/loopbackjs) or Gitter room (https://gitter.im/strongloop/loopback) - see http://loopback.io/doc/en/contrib/Reporting-issues.html

To create a Variant instance related to a Product instance, you need something like the following (assuming Product hasMany Variants):

```js
const product = await product.findById(1);
const variant = await product.variants.create({ /* your data */ });
```

Alternatively, if you are using hasMany relation (not hasAndBelongsToMany!) and know the name of the foreign key property, then you can do something like the following:

```js
const variant = await Variant.create({ productId: 1, /* your data */ });
```

Having said that, let's stop this off-topic subthread. If my answer did not help you or if you have more questions, then please move the discussion to one of our forums.
