### ISSUE TITLE
qs.stringify expects the id as "string"

### ISSUE THREAD

**Issue by kevinbaisas** [strongloop/loopback#3284]
DB: mongo

>  dependencies:
>     "loopback": "^3.0.0",
>     "loopback-boot": "^2.6.5",
>     "loopback-component-explorer": "^4.0.0",
>     "loopback-connector-mongodb": "^1.18.1"

loopback/common/models/user.js line 435 to line 444:
```
options.verifyHref = options.verifyHref ||
      options.protocol +
      '://' +
      options.host +
      displayPort +
      urlPath +
      '?' + qs.stringify({
        uid: options.user[pkName],
        redirect: options.redirect,
      });
```

line 442 `options.user[pkName]` needs to be a string. The querystring library is converting the object id to nothing. It needs to be `options.user[pkName].toString()` for the uid to be appended. 

My code :

   ```
 Account.findById(id, (err, account) => {
     //  account.id = account.id.toString(); // tried but still not working

     // this worked tho
      var verifyHref = `${ config.protocol }://${ config.host }:${ config.port }/api/accounts/confirm?`;
      verifyHref += qs.stringify({ uid: account.id.toString(), redirect: '/api/verfied' });

      account.verify({
        type: 'email',
        to: email,
        from: 'noreply@loopback.com',
        subject: 'Thanks for registering.',
        template: path.resolve(__dirname, '../../server/views/verify_email.ejs'),
        redirect: '/api/verified',
        user: account,
        verifyHref
      }, (err, response, cb) => {
        if (err) return cb(err);
      });
    });
```

havent check the orm script (having trouble finding it) to see if the prototype getter is reinstantiating a new ObjectID even though it is overwritten

**Comment by kevinbaisas** [comment]
NVM, havent noticed my projects version is outdated. The creating an `empty-server` doesn't fetch from the latest release.

**Comment by bajtos** [comment]
Hello, this has been already fixed by https://github.com/strongloop/loopback/pull/3259 and https://github.com/strongloop/loopback/pull/3253. Please upgrade to `loopback@3.5.0`.
