### ISSUE TITLE
How to modify current context from a middleware

### ISSUE THREAD

**Issue by timlind** [strongloop/loopback#3286]
In loopback 3.0 context is passed around everywhere, i.e 'loaded' operation hook.

I want to place something on the context before a bulk (find) operation takes place, no matter which remote method or relation the model was accessed through.

How can I access - from a middleware function - the context that is passed to a 'loaded' operation hook?

@raymondfeng?

**Comment by bajtos** [comment]
Hi @timlind, I am afraid it's not possible to modify the context object directly from a middleware. Here are few options you can use instead:

 1. Modify the "options" object in a beforeRemote hook or a custom remoting phase as described in our docs - see https://loopback.io/doc/en/lb3/Using-current-context.html#customize-the-value-provided-to-options
 2. If you really have to use a middleware (why?), then your middleware should store the extra properties on the `req` (request) object and then you can use any of the approaches described in the doc link above to copy the extra properties from `req` to the `options` object.

I think this is may be frequently asked question that should be answered by our docs. Would you like to contribute that documentation patch yourself? See http://loopback.io/doc/en/contrib/doc-contrib.html to get started.

**Comment by barocsi** [comment]
Actually makes sense. If you want to have an error handler middleware and want to access the options object, how would you do that? The docs only say this:
```
module.exports = function (options) {
    return function logError(err, req, res, next) {
// where is options?
...
```

**Comment by bajtos** [comment]
> If you want to have an error handler middleware and want to access the options object, how would you do that? 

That's a good question. My recommendation is to use remoting hook `afterRemoteError` instead of an error-handler middleware.

Again, if you really need to use error-handler middleware, then you can e.g. add `afterRemoteError` hook to copy `ctx.req.args.options` to `ctx.req.options` so that your middleware can access it.

**Comment by barocsi** [comment]
I was nasty, I have this boot script
```
module.exports = function enableAuthentication(app, cb) {
    app.remotes().phases
        .addBefore('auth', 'options-from-request')
        .use(function (ctx, next) {
            var req = ctx.req;
            if (!req.accessToken) {
                return next();
            }
            var User = app.models.user;
            User.findById(req.accessToken.userId,
                function (err, user) {
                    if (err) {
                        return next(err);
                    }
                    if (!user) {
                        return next({
                            message: app.get('messages').AUTH.USER_CORRUPTED,
                            status: 401,
                            name: "Error",
                            code: "AUTH.USER_CORRUPTED"
                        });
                    }
                    if (user.deleted == true) {
                        return next({
                            message: app.get('messages').AUTH.USER_DELETED,
                            status: 401,
                            name: "Error",
                            code: "AUTH.USER_DELETED"
                        });
                    }
                    ctx.args.options = ctx.args.options ? ctx.args.options : {};
                    ctx.args.options.currentUser = user;
                    ctx.req.currentUser = {};
                    ctx.req.currentUser = user;
                    next();
                });
        });
    cb();
};
```
so I can access currentUser from any _req.currentUser_.

**Comment by barocsi** [comment]
However, additionally afterRemoteError should be placed in the docs, because right now docs insist on middleware error handling. 
https://loopback.io/doc/en/lb3/Using-strong-error-handler.html
on this URL you can find no mentioning of afterRemoteError.

I know there is a way to improve docs, so I would need to contribute there.

**Comment by bajtos** [comment]
FWIW, afterRemoteError is already documented here: https://loopback.io/doc/en/lb3/Remote-hooks.html

The page https://loopback.io/doc/en/lb3/Using-strong-error-handler.html is generated from strong-error-handler's README. To improve this document, simply send a pull request to strong-error-handler repository.

Here are instructions for contributing changes to our "main" documentation: http://loopback.io/doc/en/contrib/doc-contrib.html

**Comment by barocsi** [comment]
Clear!
What is not clear to me and apologies for it, that how can I access the app model from the afterRemoteError, https://loopback.io/doc/en/lb3/Working-with-LoopBack-objects.html#from-a-model-script does not mention this clearly.

**Comment by timlind** [comment]
@bajtos Thanks for the suggestion, although my use case is to avoid using remote hooks (because they are not run when a model is accessed from any direction in the graph), and access the context from an operation hook instead, after a middleware function has decorated the context options.

I'll eventually open up another issue for the use case, which is largely around ensuring that whenever a model query is performed there is an efficient way to load additional relations and decorating results based on the request authorised user.

**Comment by bajtos** [comment]
@timlind 

> Thanks for the suggestion, although my use case is to avoid using remote hooks (because they are not run when a model is accessed from any direction in the graph), and access the context from an operation hook instead, after a middleware function has decorated the context options.

I agree that for code that has to run even when a method is invoked locally via JavaScript API, remote hooks are not the solution. IMO, the same applies to middleware. If you are relying on a middleware function to decorate context options, then your code invoking the method via JavaScript API won't decorate it.

Have you considered decorating the context options inside the operation hook itself?

Here is a quick outline to show what I mean:

```js
MyModel.observe('access', (ctx, cb) => {
  decorate(ctx.options);
  // do the real work
});

function decorate(options) {
  // prevent repeated computation
  if (options.decorated) return;

  // decorate the options
  options.decorated = {
    // ...
  };
}
```

**Comment by timlind** [comment]
@bajtos what I actually mean is that the model decoration needs to run when being accessed via the REST api through any relation as well as directly on the model REST api. 

Perhaps the missing functionality is that there is no operation hook that executes on a bulk access operation, so that it can be used to cause a further - efficient - lookup of data related to the viewing user, regardless of which relation the model is being accessed via on the REST api.

**Comment by bajtos** [comment]
> what I actually mean is that the model decoration needs to run when being accessed via the REST api through any relation as well as directly on the model REST api.

You can use a global remoting hook that's triggered for any method on any model. I think the code will look like this:

```js
app.remotes().before('**', (ctx, next) => {
  // do stuff with ctx.args.options
  next();
});
```

(IIRC, the handler method can return a promise instead of using `next` callback too.)

See also https://loopback.io/doc/en/lb3/Remote-methods.html#formattingremote-method-responses

I think it would be great to add a new section to that page explaining how to use a global before-remote hook instead of a middleware. /cc @crandmck

**Comment by timlind** [comment]
@bajtos are you sure about that? I've tried that out and it doesn't hit the before remote when accessing a user-subclass/reset-password URL. 

Also do the model operation hooks (i.e before save / before access) always run after the next() call of a before remote?

**Comment by ebarault** [comment]
i solved this once, this could come from the order where the hooks are registered, it can be a bit tricky. If you provide a sandbox reproducing what you're trying to do, i could play around with you on this. Then when finding a solution we could enhance the doc to cover this scenario.

**Comment by timlind** [comment]
Thanks @ebarault. 

OK, I seem to be able to customise the operation context through this before remote hook. 

This is really weird though (aside from all these similar names being really confusing): ctx.args.options doesn't exist in the before remote, but if I create it, it will override the options sent to the before save operation hook, remember to put accessToken on it as well (as that is on the default options).

**Comment by bajtos** [comment]
@timlind 
> This is really weird though (aside from all these similar names being really confusing): ctx.args.options doesn't exist in the before remote, but if I create it, it will override the options sent to the before save operation hook, remember to put accessToken on it as well (as that is on the default options).

I agree this is weird, it's not how I envisioned the interaction before options-from-context and remoting-hooks. Could you please fork https://github.com/strongloop/loopback-sandbox and create a small app showing what and how are you trying to accomplish? It will help us to better understand your use case and identify any possible bugs in the current implementation.

**Comment by timlind** [comment]
@bajtos I've forked sandbox with an example of using the global remote hook to preload data for decorating in an operation loaded hook. Currently it seems the modification to ctx.data in loaded operation hook isn't affecting the resulting data sent over REST.

https://github.com/timlind/loopback-sandbox-bulk-decoration

**Comment by timlind** [comment]
see also #3336

**Comment by bajtos** [comment]
@timlind thank you for the example repo and sorry for my late response.

In [server/boot/context-decorator.js](https://github.com/timlind/loopback-sandbox-bulk-decoration/blob/20bc327c7081bff712bb24cab391c764180241b9/server/boot/context-decorator.js#L23), you have a before-remote hook modifying the `ctx` argument. This context is strong-remoting's `HttpContext`. A bit later you are modifying `ctx.args.options`, that's the right approach.

Then in [server/models/member.js](https://github.com/timlind/loopback-sandbox-bulk-decoration/blob/20bc327c7081bff712bb24cab391c764180241b9/server/models/member.js#L9), you have an operation hook reading from `ctx`. This context is a completely different object unrelated to strong-remoting's `HttpContext`. You should use `ctx.options` to access the values set by your before-remote hooks via `ctx.args.options`.

```js
    Member.observe('loaded', function(ctx, next) {
        var profile = ctx.data;

        if (ctx.options.accessToken) {
            // ERROR: this doesn't seem to be loaded by the time the hook runs
            assert(ctx.options.authorizedUser);
            // ensure related data for decoration is loaded
            assert(ctx.options.authorizedUser.favorites);
            // decorate the user profiles based on the authorised user's favorite status
            profile.isFavorited = ctx.options.authorisedUser.favorites.map((fav) => { return fav.favoritedMemberId }).indexOf(profile.id) !== -1;
        }

        next();
    });
```

The code invoking `Member.findOne` ([link](https://github.com/timlind/loopback-sandbox-bulk-decoration/blob/20bc327c7081bff712bb24cab391c764180241b9/server/models/member.js#L34)) does not make an HTTP request, it calls the method directly via JS API. This bypasses strong-remoting and before-remote hooks. You need to provide explicit `options` argument.

```js
const options = { authorizedUser, accessToken };
Member.findOne({}, options, function(e, member) { /*...*/ };
```

Let me know if this is enough information to allow you to figure out the rest yourself.

**Comment by saadismail** [comment]
@bajtos First off, sorry for bumping very old issue but my issue is quite similar to this one. Your last suggestion seem to be on the point and seems to be doing well if I am using it inside the Loopback application. But what should be done if someone need to send it through an Angular application or any other source through REST call?

I have found this: 
```To seed the “options” argument when a method is invoked via a REST call, the “options” argument must be annotated in remoting metadata with a specific value set in the “http” property.

Optionally, applications can customize the value provided to “options” when invoked via REST.```

on this page: https://loopback.io/doc/en/lb3/Using-current-context.html

However there is no example in the documentation for this. An example REST call would be really helpful. I will see if I can improve the documentation afterwards. 

Thanks in advance.

**Comment by cbullokles** [comment]
Is not clear for me if there is a path to use the context in the middleware:

I just want to check permissions to access to a particular asset, and I'll love to check using context values model and method.
I'll like to check (user, action) (cristian, model.method).

module.exports = () => {
  return async (req, res, next) => {


     return next()
  }
}

**Comment by sujeshthekkepatt** [comment]
You can use context object for hooks like ,

```
Model.beforeRemote('findById', functions checkPermission(context,instance,next) {
//you can access context here
})
```

But for this kind of permission checking, you can leverage the ACL functionality. And apply ACL to that particular function/remote method with owner-only access.
