### ISSUE TITLE
PersistedModel `updateAll` return type is not recognized by strong-remoting

### ISSUE THREAD

**Issue by Jeff-Lewis** [strongloop/loopback#3287]
All PersistedModel models' `updateAll` return type is not registered properly. 

# Description/Steps to reproduce

- set DEBUG=strong-remoting:rest-adapter
- Start loopback server with a model that inherits PersistedModel
- You should see this line once for each model that is registered 
```
strong-remoting:rest-adapter WARNING: unkown ctorOrName of type object: {"count":{"type":"number","description":"The number of instances updated"}}
```

See [persisted-model.js](https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L843-L845) as it sets the `type` to a custom object `'count: {...}'` instead of a string `'number'`.

```
returns: {
        arg: 'info',
        description: 'Information related to the outcome of the operation',
        type: {
          count: {
            type: 'number',
            description: 'The number of instances updated',
          },
        },
        root: true,
      },
```

# Expected result
- Expect to not have a warning and `updateAll` return type set as a `number`.
- Also expect "unkown" in strong-remoting's [rest-adaptor.js](https://github.com/strongloop/strong-remoting/blob/master/lib/rest-adapter.js#L638) to be spelled correctly as "unknown"... ;)

# Additional information

- Loopback 2.38.0 but appears to be in latest as well.
- win32 x64 6.10.0
"loopback": "2.38.0",
"loopback-boot": "2.23.0",
"loopback-component-explorer": "2.7.0",
"loopback-connector-mongodb": "1.18.1",
"loopback-connector-rest": "2.1.0",
"loopback-datasource-juggler": "2.54.0",

**Comment by bajtos** [comment]
Hi @Jeff-Lewis, thank you for reporting this issue.

>  expect "unkown" in strong-remoting's rest-adaptor.js to be spelled correctly as "unknown"... ;)

Could you contribute this fix yourself?

> Expect to not have a warning and updateAll return type set as a number.
 
In my understanding, the return type of `updateAll` method is described correctly - the method returns an object with a single `count` property. Unfortunately, strong-remoting's `getTypeString` method is not prepared to handle such anonymous in-place object definition.

I agree with you that LoopBack apps should not report the warning you are observing.

IMO, we need to fix `getTypeString` to correctly handle this valid use case (`updateAll` returning an anonymous object type).

Would you like to contribute this fix yourself? I am happy to help you along the way.
