### ISSUE TITLE
Circuit Breaker pattern

### ISSUE THREAD

**Issue by asaxena1993** [strongloop/loopback#3289]
Greetings,
Went thru the documentation of loopback(http://loopback.io/doc/) was not able to find anything on the circuit breakers(https://spring.io/guides/gs/circuit-breaker/).
Found these module, 
- https://www.npmjs.com/package/opossum
- https://www.npmjs.com/package/levee
Can you please advice better implementation for these modules or more npm modules? 
Also if loopback out of the box can provide some implementation for this concept?

**Comment by bajtos** [comment]
Hello @asaxena1993, I am afraid we don't have any support for Circuit Breaker pattern built into LoopBack yet.

As I see it, the circuit pattern can be applied at different levels:
 - Connectors can detect when the target system is not responsive and start returning a pre-canned success or failure response until the target system recovers.
 - The REST adapter can stop calling remote methods and start returning a pre-canned response when the remote method takes too long to respond and/or failure rate is too high. I think this is the feature described in https://spring.io/guides/gs/circuit-breaker/.

@asaxena1993 would you like to contribute this feature yourself? We can help you along the way.

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be adding any new features.
