### ISSUE TITLE
invalid token on currentUserLiteral throws 500

### ISSUE THREAD

**Issue by aaronbuchanan** [strongloop/loopback#3291]
# Description/Steps to reproduce
When loading fixtures in our dev/staging environments, our token table gets reset and all clients that were previously logged in start receiving 500 responses at currentUserLiteral endpoints with the error: 
```
500 invalid input syntax for integer: "me"
length: 91
severity: ERROR
code: 22P02
file: numutils.c
line: 62
routine: pg_atoi
error: invalid input syntax for integer: "me"
    at Connection.parseE (/.../node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/.../node_modules/pg/lib/connection.js:396:17)
    at Socket. (/.../node_modules/pg/lib/connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

In looking into this we found that the authToken was being invalidated and unset, and the default findById method was being called with our currentUserLiteral as the id which throws a SQL error. 

*update*
The cause seems to be the if on line L25 of [token.js](https://github.com/strongloop/loopback/blob/master/server/middleware/token.js#L25-L34). If the access token is not set, then this request is processed by `Model.findById`. 

# Expected result

Expected a 401 Unauthorized response

# Additional information

We've temporarily worked around this with the following:
```
const router = server.loopback.Router();
const currentUserLiteral = 'me';
router.all(
    `/api/{model}/${currentUserLiteral}`,
    catchInvalidAuthForCurrentUserLiteral
);
server.use(router);

function catchInvalidAuthForCurrentUserLiteral(req, res, next) {
  if (req.accessToken == null) res.sendStatus(401);
  else next();
}
```

Env info:
```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 6.9.5

$ npm ls --prod --depth 0 | grep loopback
├── loopback@3.4.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@4.1.1
├── loopback-component-passport@3.2.0
├── loopback-connector-postgresql@2.8.0
├── loopback-fixtures@0.0.10 invalid
```

**Comment by bajtos** [comment]
Thank you for reporting this issue and opening a pull request to contribute the fix too 🙇

**Comment by rashmihunt** [comment]
@aaronbuchanan Your PR is already merged by @bajtos  Can you go ahead and close this issue? Or we can close it.

**Comment by bajtos** [comment]
Oh, this is my fault, I forgot to close the issue after the pull requests were landed. Closing now.
