### ISSUE TITLE
Validation problem when patching a model with embedded relation

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#3295]
@ahallez commented on [Sat Feb 04 2017](https://github.com/strongloop/loopback.io/issues/268)

I have a model that includes an embedded relation (embedsMany).
The embedded model has auto generated ids.

When patching the parent model I get a validation error, saying the embedded model data shouldn't have it id's set.

Details of the models and patch below.

Is this a bug or do I have to change something to the configuration to prevent this?

The model json of the parent model
```
{
  "name": "embedTest",
  "plural": "embedTests",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "String",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "embedded": {
      "type": "embedsMany",
      "model": "embeddedTest",
      "property": "embeddedList",
      "default": [],
      "options": {
        "validate": true,
        "forceId": true,
        "autoId": true
      }
    }
  },
  "acls": [],
  "methods": {}
}
```
The model json of the embedded model
```
{
  "name": "embeddedTest",
  "plural": "embeddedTests",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "text": {
      "type": "String",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "embedded2": {
      "type": "embedsMany",
      "model": "embedded2Test",
      "property": "embeddedList2",
      "default": [],
      "options": {
        "validate": true,
        "forceId": true,
        "autoId": true
      }
    }
  },
  "acls": [],
  "methods": {}
}
```
The json data of the object being patched:
```
{
  "name": "test",
  "id": "0f6b3ca3cc97bc15c5fd8819f000395d",
  "embeddedList": [
    {
      "text": "test",
      "id": "bdddaf6db953b988d21f021f",
      "embeddedList2": []
    }
  ],
  "_rev": "4-b177733e7ca2b2dd501f9f83662391c9"
}
````

The call made to patch the object (through the explorer interface):
```
curl -X PATCH --header "Content-Type: application/json" --header "Accept: application/json" -d "{
\"name\": \"new name\"
}" "http://localhost:8080/api/embedTests/0f6b3ca3cc97bc15c5fd8819f000395d"
```

The error message returned:
```
{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "De instance `embedTest` is niet geldig. Details: `embeddedList` contains invalid item: `bdddaf6db953b988d21f021f` (`id` can't be set) (value: [ { text: 'test',\n    id:...} ]).",
    "details": {
      "context": "embedTest",
      "codes": {
        "embeddedList": [
          "invalid"
        ]
      },
      "messages": {
        "embeddedList": [
          "contains invalid item: `bdddaf6db953b988d21f021f` (`id` can't be set)"
        ]
      }
    }
  }
}
```

Edit:
I changed the options of the embedsMany relation to disable validation and then it works fine.
Still not clear to me if this is the way it should be. The documentation doesn't really go into detail about the use of the options on an embedded relation.

---

@crandmck commented on [Mon Feb 06 2017](https://github.com/strongloop/loopback.io/issues/268#issuecomment-277792235)

@superkhau I'm not sure if this is just a doc issue or if there's an underlying s/w problem.

There's an existing doc issue on "embedsMany" https://github.com/strongloop/loopback-datasource-juggler/issues/1174.

---

@superkhau commented on [Tue Feb 07 2017](https://github.com/strongloop/loopback.io/issues/268#issuecomment-277937723)

@crandmck I'm not sure off the top of my head, will have to try it out to verify the current behaviour. That said, @kjdelisle I'll leave this to you to triage.

---

@AhsanAyaz commented on [Wed Mar 15 2017](https://github.com/strongloop/loopback.io/issues/268#issuecomment-286680481)

+1. 
I just tried to add a second embedsMany relation and it is breaking the same way. 
I.e. 

`{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "The `Lexicon` instance is not valid. Details: `_keywords` contains invalid item: `58c900f3e1a7e26023eab0e3` (`id` can't be set) (value: [ ......`

---

@crandmck commented on [Wed Mar 15 2017](https://github.com/strongloop/loopback.io/issues/268#issuecomment-286792310)

@bajtos Can you say if this is a doc issue or if there's a bug?

---

@bajtos commented on [Mon Mar 20 2017](https://github.com/strongloop/loopback.io/issues/268#issuecomment-287792932)

IIUC, this problem is cause by `forceId` model setting which changed the default value from `false` to `true` in LoopBack 3.0.

Now the question is, what is the correct setup of the `id` property for embedded relations? Should embedded items have any id at all?

If they do, then we should keep `forceId:true`, in order to prevent DoS attacks where e.g. the client can submit the maximum integer value supported by the backing database as the `id` value, and thus preventing any further instance to be created, because the database cannot auto-increment beyond the maximum integer value.

`forceId` check is triggered only when the model instance is considered as "new". I think we need to fix the implementation of our embedded relations so that it marks embedded model instances as "not new" by passing `{persisted: true}` in the options of model constructor and/or `_initProperties`. Examples:

 - https://github.com/strongloop/loopback-datasource-juggler/blob/c509a9f7fe48877a2fc6d39ad98bd9007e42a560/test/persistence-hooks.suite.js#L1264-L1266
 - https://github.com/strongloop/loopback-datasource-juggler/blob/6f8ecfdf5cb72b7dc0d29e9bedc8b877f9435c1b/lib/dao.js#L782

In that light, I think this isue should be labelled as a `bug`.

---

@crandmck commented on [Mon Mar 20 2017](https://github.com/strongloop/loopback.io/issues/268#issuecomment-287808191)

> I think we need to fix the implementation of our embedded relations 

OK, since this is not a doc issue, but rather a bug, I'm going to move this from `loopback.io` repo to `loopback`.

**Comment by prtkkmrsngh** [comment]
Workaround is only making validate false. Any update on this?

**Comment by walterhuangfs** [comment]
I'm running the exact issue by turning forceId=true.  Turning validation false worries me. Any update on this? Thanks!

**Comment by Gcaya** [comment]
+1
Ran into same problem

**Comment by alzab** [comment]
+1
Same issue here too

**Comment by alzab** [comment]
@bajtos Is setting validate=false the only viable solution for now here? Seems to be the only thing that works for me (and others from the sounds of it).

**Comment by asaf050** [comment]
+1
Same issue here too

**Comment by jura-b** [comment]
+1
Same issue here too

**Comment by vituocgia** [comment]
this issue still occurs, anyone has the answer for this?

**Comment by israelglar** [comment]
No solution for this error yet?

**Comment by jura-b** [comment]
@israelglar I gave up and rewrite the CRUD on my own. I nested the object and validate with joi instead of using embedded relation.

**Comment by abouroubi** [comment]
Any news about this bug ?

**Comment by bitpod-io** [comment]
Any update on this bug ?

**Comment by maherzaidoune** [comment]
any update ??

**Comment by maherzaidoune** [comment]
i think this will help you , just  add
 "id": {
"type": "string",
"id": true,
"defaultFn": "uuid"
}
to your embedded model properties , that's help me

**Comment by jannyHou** [comment]
@everyone please try @maherzaidoune 's suggestion(Thank you Maher!) and see if it solves your problem. 

Allow me some time to reproduce the error if it's still not fixed. I will make a PR for it.

**Comment by ElHupeke** [comment]
Have same prob here. Can't solve this :-(
