### ISSUE TITLE
Optional boolean is set to false if it's not passed

### ISSUE THREAD

**Issue by ellenaua** [strongloop/loopback#3298]
I have an endpoint declared this way: 

    Campaign.updateCampaign = function (id, title, isActive, cb) {
        .....
    }
    
    Campaign.remoteMethod('updateCampaign', {
         http: {path: '/:id/updateCampaign', verb: 'POST'},
         accepts: [
             {arg: 'id', type: 'string', required: true},
             {arg: 'title', type: 'string'},
             {arg: 'is_active', type: 'boolean', required: false},
         ],
         returns: {type: 'object', root: true}
     });

Expected behavior:
- when is_active is not passed, it should be undefined

Actual behavior: 
- I get is_active as false, when don't pass it in POST method

**Comment by bajtos** [comment]
@ellenaua thank you for reporting the issue. What version of LoopBack and strong-remoting are you using?

AFAICT, in the version 3.x, optional boolean arguments are set to `undefined` when they are not provided by the caller.

See e.g. the following test cases:

> https://github.com/strongloop/strong-remoting/blob/3d697ee8af64733a59ae9cd338532df2052ab7db/test/rest-coercion/urlencoded-boolean.suite.js#L43-L45
```js
      [EMPTY_QUERY, undefined],
      ['arg', undefined],
      ['arg=', undefined],
```
