### ISSUE TITLE
Showing/returning only filtered data to a custom defined dynamic role

### ISSUE THREAD

**Issue by shaheero** [strongloop/loopback#3300]
# Description/Steps to reproduce
Building on this example to create a dynamic role in the docs
https://loopback.io/doc/en/lb3/Defining-and-using-roles.html#dynamic-roles

I am trying to return only **filtered data** (described in myFilter var below) to users of a specific role (teamMembers). The aim is to allow teamMembers to read, write or execute to only a specific set of records in a model based on the value of one of their user properties. This is the code in my `boot` folder:

```
module.exports = function(app) {
  var Role = app.models.Role;

  Role.registerResolver('$teamMember', function(role, context, cb) {
    if (context.modelName !== 'teamMember') {
      return process.nextTick(() => cb(null, false));
    }

    var myUserId = context.accessToken.userId;
    if (!myUserId) {
      return process.nextTick(() => cb(null, false));
    }
      var Member = app.models.teamMember;
      Member.count({
        userId: myUserId
      }, function(err, count) {
        if (err) return cb(err);

        if(count > 0){
          var myFilter = {where: {col1: goGetValueOfaPropertyForThisUserFromDB}};//<----- Q1
            Member.find(myFilter, function(err, result) {

	        if (err) return cb(err);
	        return cb(result, true);//<----- Q2: why gives error
          });
    	}

		else{
          return cb(null, false);
        }
      });
  });
};
```

# Result
Q1: How to get the value of a property for that logged in user?

Q2: The query gives:
```
"error":{
"statusCode": 500,
"name": "ArrayOfErrors",
"message": "Failed with multiple errors, see `details` for more information.",
"details":[
{"__cachedRelations":{},
```
along with my desired filtered data inside details. And the console prints the filtered data along with:
"Unhandled array of errors for request GET ...modelName and access token..
 [object Object]
[object Object]
[object Object]"

When I use this return instead:
```
console.log(result);
return cb(null, true);
```

No error happens and the console shows the desired filtered data normally, but the GET request gives all the data (ignoring the filter).

# Additional information

darwin x64 7.5.0
├── loopback@3.2.1
├── loopback-boot@2.23.0
├── loopback-component-explorer@4.1.0
├── loopback-connector-mysql@3.0.0

**Comment by ebarault** [comment]
> Q1: How to get the value of a property for that logged in user?
replace your Member.count() query by a Member.findById() to get the user instance instead of just asserting existence

> Q2: is goGetValueOfaPropertyForThisUserFromDB an async function? then you cannot use it right away like that

that being said, unless you'd like to submit an issue, please use the forum or gitter for questions:
  https://groups.google.com/forum/#!forum/loopbackjs
  https://gitter.im/strongloop/loopback

**Comment by shaheero** [comment]
I am suspecting Q2 is an issue. The filter is being ignored.
