### ISSUE TITLE
upsertWithWhere throwing an error that "There are multiple instance found operation will not be performed status code 400". 

### ISSUE THREAD

**Issue by virendra656** [strongloop/loopback#3301]
Iterating a huge array and setting context for each user request for upsertWithWhere throwing an error that "There are multiple instance found operation will not be performed status code 400". I get this because there are some dupes are returned by this api. But even is start  with empty collection I still get this error. So when i use async.mapLimit with 1 concurrency it works.

**Comment by diegoazh** [comment]
Same issu here. I use mysql-connector.
Why did this happen?

**Comment by Pahlawan852** [comment]
Yes also got this issue using mysql-connector

**Comment by cristianKumul** [comment]
Yes, I hava te same problem with  mysql-connector

**Comment by virendra656** [comment]
Your where clause matches multiple instances in dB?

**Comment by diegoazh** [comment]
What do you mean? In my case, the intention was update one instance if will exist or create it if not exist.

**Comment by alfredgoogle** [comment]
same issue

**Comment by sanjaybaskaran01** [comment]
Has this been resolved? or addressed?
