### ISSUE TITLE
Deny property write via ACL

### ISSUE THREAD

**Issue by zenjabroni** [strongloop/loopback#3302]
# Description/Steps to reproduce
I'm looking for a way to prevent users from updating their own `username` via `PATCH /api/users/:id`.

According to the docs for ACL it looks like this should be possible by specifying a property in the ACL like this:
```json
{
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "accessType": "WRITE",
      "property": "username"
 }
```

This, unfortunately, does not work. I'm not sure if it's a bug or the docs are worded incorrectly regarding the ACL definition.

@ebarault asked me to tag him in this based on our gitter chat earlier

**Comment by ebarault** [comment]
thanks for posting this @zenjabroni 
cc: @bajtos 

Although the ACL js states 
`@property {String} property Name of the **property**, method, scope, or relation.`

I never tested this kind of ACLs. It seems the doc is unclear about the support of this, although all examples refer to `ACL.property` of type `method`.

It appears that the given ACL does not work and does not prevent a user from patching the username property inside a given user instance.

Let's use this issue to track and discuss the investigations in ACL.js

**Comment by bajtos** [comment]
I don't think we support ACL at property level (for properties other than methods). @ritch @raymondfeng?

**Comment by zenjabroni** [comment]
FWIW, the concern I have is that using the passport social connector puts the account link in the username column like this: `facebook-token.<facebook_user_id>`.  This seems like data that users shouldn't be able to change.

**Comment by SukantGujar** [comment]
Is it established that property level ACL is not there at the moment?

**Comment by ebarault** [comment]
yes, it's not supported as of now

**Comment by SukantGujar** [comment]
Thanks @ebarault. As issues on this topic have been open since a long time (I found a closed one from 2014), is it possible to know if this feature is planned?
