### ISSUE TITLE
Using model descovery on multiple databases can cause model name overlaps

### ISSUE THREAD

**Issue by cryptk** [strongloop/loopback#3305]
Hello, I am developing an API that wraps around some pre-existing MySQL databases using discovery.  The issue that I have encountered is that some of these databases have table names that are the same (so db1.instances and db2.instances for example).  The tables do store different data, and as such should be available via different API endpoints, but the discovery results in both of them generating models named "Instances".

The solution, it would seem, is to have a way to alter how the name for a model is determined, then we could have them named Db1Instances and Db2Instances for example.  So far I have not been able to find any way to do this, and unless I am missing something, there is no way to do discovery on multiple databases that have overlapping table names and have a result where you can access both API endpoints.

I have attempted just overriding the model name in the boot script, but that results in broken relations, because it does not actually alter how a models name is determined... so the relations still point at Instances while the model was renamed to Db1Instances for example.

I am unsure if I would call this a bug or a feature request... To me it seems like a bug that you cannot use discovery on multiple databases with similar table names... It is also entirely possible that I am just missing something that is already present, but if it is, then it would likely be a documentation bug since my efforts of pouring through the user docs, api docs and even the code itself have not resulted in me determining a way to ensure that discovered models are named uniquely.

EDIT: Here is an example of my boot script.  I have 3 of them that are all the same with the exception of pointing at different datasources and giving a different list of tables in the const tables array https://gist.github.com/cryptk/b49598b3a40f2a5aedc95e1470c5ab7a

**Comment by shaheero** [comment]
I am not sure if the discovery is quite ready yet for getting _everything_ good to go by just running it. 

In my use cases, it did most of the work but manual changes were a must (among which some Booleans were discovered as numbers, added the plurals, changed the 'id' columns from being required to not because MySQL autogenerates and autoincrements them..).

Anyway, could you share your discovery boot script? It will help if someone has suggestions.

**Comment by cryptk** [comment]
Updated the original post with a link to an example of the boot script that I am using.

**Comment by shaheero** [comment]
Have a look at the file datasource.js in node_modules/loopback-datasource-juggler/lib.
In my version (3.2), in line 1432 you will find:
`          model: nameMapper('table', fk.pkTableName),`

You could manually add the current db name before running your discovery script. This will affect the model names in the relation attribute of the generated json. For example, change it to:
`           model: nameMapper('table', fk.pkTableName+'db1'),`

**Comment by cryptk** [comment]
Well, I can generate JSON and then just manually change them as needed, but that kind of defeats the purpose of using discovery.  What I am hoping to be able to accomplish is to have the API app start up, use discovery to create the API, and then use the API as discovered.  If I were to generate JSON files from the discovery, I could edit them as needed to deal with the conflicts, but then if the schema changes, I would then need to go in and re-edit all of the JSON files to match.

The situation that I am in is I am trying to create a read-only API to wrap around some pre-existing databases to create some management views of the data in the database, as well as to enable some external tools to have a controlled way to access the data in that database.  Ideally if the database schema changes, I would like to be able to just restart the loopback service and have a new API that now matches the new schema.

I am about 99% to having that completed, the only issue I am having is mostly just these few tables that are named the same in the separate databases overriding each other, when this happens I am getting the following message "Warning: overriding remoting type instances", which makes perfect sense... but if the model names were namespaced somehow based on where that model actually is located (in this case, perhaps with the datasource name), then I could avoid this issue and have my API run completely from discovered models at startup.

**Comment by shaheero** [comment]
I see what you mean.

I haven't played around the datasource.js file much, but you can try to assign the db name to a variable (e.g. var thedbname) and then use it in the line I told you about above.

`model: nameMapper('table', fk.pkTableName+thedbname),`
