### ISSUE TITLE
Created a custom model extending the base model, the data is inserted into the base model, not to the custom model.

### ISSUE THREAD

**Issue by samithks** [strongloop/loopback#3307]
How to create a 3rd party login that insert data to custom model which inherit loopback base models, using loopback-component-passport?

When created a custom model extending the base model, the data is inserted into the base model, not to the custom model.

model-config.json
```
{
  "_meta": {
    "sources": [
      "../common/models",
      "./models",
      "./node_modules/loopback-component-passport/lib/models"
    ]
  },
  "User": {
    "dataSource": "mongoDb",
    "public": false
  },
  "AccessToken": {
    "dataSource": "mongoDb",
    "public": false
  },
  "customer": {
    "dataSource": "mongoDb",
    "public": true
  },
  "accessToken": {
    "dataSource": "mongoDb",
    "public": false
  },
  "customerCredential": {
    "dataSource": "mongoDb",
    "public": false
  },
  "customerIdentity": {
    "dataSource": "mongoDb",
    "public": false
  },
  "ACL": {
    "dataSource": "mongoDb",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "mongoDb",
    "public": false
  },
  "Role": {
    "dataSource": "mongoDb",
    "public": false
  }
}
```
The passport configurator
server.js
```
passportConfigurator.init();

passportConfigurator.setupModels({
  userModel: app.models.customer,
  userIdentityModel: app.models.customerIdentity,
  userCredentialModel: app.models.customerCredential,
});
```
Models
```
customer.json
{
  "name": "customer",
  "plural": "customers",
  "base": "User",
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "accessToken",
      "foreignKey": "customerId"
    },
    "customeridentities": {
      "type": "hasMany",
      "model": "customerIdentity",
      "foreignKey": "customerId"
    },
    "customercredentials": {
      "type": "hasMany",
      "model": "customerCredential",
      "foreignKey": "customerId"
    }
  },
  "validations": [],
  "acls": [],
  "methods": []
}
```
customer-credential.json
```
{
  "name": "customerCredential",
  "plural": "customerCredentials",
  "base": "UserCredential",
  "properties": {},
  "validations": [],
  "relations": {
    "customer": {
      "type": "belongsTo",
      "model": "customer",
      "foreignKey": "customerId"
    }
  },
  "acls": [],
  "methods": []
}
```
accessToken.json
```
{
  "name": "accessToken",
  "plural": "accessTokens",
  "base": "AccessToken",
  "properties": {},
  "validations": [],
  "relations": {
    "customer": {
      "type": "belongsTo",
      "model": "customer",
      "foreignKey": "customerId"
    }
  },
  "acls": [],
  "methods": []
}
```
customerIdentity.json
```
{
  "name": "customerIdentity",
  "plural": "customerIdentities",
  "base": "UserIdentity",
  "properties": {},
  "validations": [],
  "relations": {
    "customer": {
      "type": "belongsTo",
      "model": "customer",
      "foreignKey": "customerId"
    }
  },
  "acls": [],
  "methods": []
}
```
This above is the configuration in code.

But in the database the table created were User and AccessToken not customer and accessToken.

When I remove the user and access token from the model-config.json.
```
  "User": {
    "dataSource": "mongoDb",
    "public": false
  },
  "AccessToken": {
    "dataSource": "mongoDb",
    "public": false
  }
```
The customer table and accessToken table (custom tables) were created in the mongo database. But I get the following error message in console.

Error Message

The model "accessToken" configures "belongsTo User-like models" relation with target model "User". However, the model "User" is not attached to the application and therefore cannot be used by this relation. This typically happens when the application has a custom custom User subclass, but does not fix AccessToken relations to use this new model.
But when the User and AccessToken are added to the model-config the table created in the db is not the custom dbs customer and accessToken. Its the base data models User and AccessToken.

The link to the sandbox is given below.
https://github.com/samithks/loopback-sandbox

**Comment by samithks** [comment]
https://github.com/samithks/loopback-sandbox

**Comment by samithks** [comment]
The link to the sandbox is given below.
https://github.com/samithks/loopback-sandbox

**Comment by b3rew** [comment]
Did you try to remove user and access token from the model-config.json and just use customAccessToken & customUser but you should

add this to your customUser (in your case customer)
```
"accessTokens": { //dont change this name
      "type": "hasMany",
      "model": "customAccessToken",
      "foreignKey": "userId",
      "options": {
        "disableInclude": true
      }
    }
```
and also add this to your customAccessToken (in your case accessToken)
```
"user": { //dont change this name
      "type": "belongsTo",
      "model": "customUser",
      "foreignKey": "userId"
   }
```

**Comment by ebarault** [comment]
@samithks 
just ignore the warning message and remove base User and AccessToken in your model-config.json at the moment. Please confirm whether it's working then.

**Comment by samithks** [comment]
@ebarault 

I removed the User and AccessToken the model-config.json.
```
  "accessToken": {
  "dataSource": "mongo-db",
  "public": false
  },
  "CustomerCredential": {
  "dataSource": "mongo-db",
  "public": false
  },
  "CustomerIdentity": {
  "dataSource": "mongo-db",
  "public": false
  },
  "Customer": {
  "dataSource": "mongo-db",
  "public": true
  }
```
Now the warning message is not showing and as far working properly.

**Comment by samithks** [comment]
@b3rew 
Hi,
Thanks for your reply.
Ya, I tried that already and working.
I need to use relation name as `user` in access-token and `accessTokens` in customer.json.

**Comment by shaheero** [comment]
I did everything as mentioned in this thread. Everything is working normally, but I am still getting the warning message. Any updates about that fix?

@ebarault

**Comment by shaheero** [comment]
Worth mentioning that the [docs here](http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#preparing-access-control-models) provide what's needed exactly.

I would only add that **every** model that extends the built-in User model should have this in its relations:
```
      "accessTokens": {
        "type": "hasMany",
        "model": "YourCustomAccessToken",
        "polymorphic": {
          "foreignKey": "userId",
          "discriminator": "principalType"
        },
        "options": {
          "disableInclude": true
        }
      }
```
