### ISSUE TITLE
Warning when CustomAccessToken uses a polymorphic realtion to user models

### ISSUE THREAD

**Issue by Schubbcasten** [strongloop/loopback#3308]
# Description/Steps to reproduce

I currently have an app where I have different custom User models. To implement the authentication I follwed these instruction:
http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#access-control-with-multiple-user-models
Which resulted in the following model definitions: 

```
// CustomAccessToken model
{
  "name": "CustomAccessToken",
  "base": "AccessToken",
   /*... */
  "relations": {
    "user": {
      "type": "belongsTo",
      "idName": "id",
      "polymorphic": {
        "idType": "string",
        "foreignKey": "userId",
        "discriminator": "principalType"
      }
    }
  },
  /* ... */
}
// Admin model
{
  "name": "Admin",
  "plural": "admins",
  "base": "User",
   /* ... */
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "CustomAccessToken",
      "polymorphic": {
        "foreignKey": "userId",
        "discriminator": "principalType"
      },
      "options": {
        "disableInclude": true
      }
    }
  },
  /* ... */
}
// Customer Model
{
  "name": "Customer",
  "plural": "customers",
  "base": "User",
   /* ... */
  "relations": {
    "accessTokens": {
      "type": "hasMany",
      "model": "CustomAccessToken",
      "polymorphic": {
        "foreignKey": "userId",
        "discriminator": "principalType"
      },
      "options": {
        "disableInclude": true
      }
    }
  },
  /* ... */
}
```

This then still gives the following warning:
The model "AniseAccessToken" configures "belongsTo User-like models" relation with target model "User". However, the model "User" is not attached to the application and therefore cannot be used by this relation. This typically happens when the application has a custom custom User subclass, but does not fix AccessToken relations to use this new model.

I'm not entirely sure if this is a bug or of its a mistake in the definitions on my end.

# Expected result

No warning

**Comment by ebarault** [comment]
hi @Schubbcasten,
your app seems to react as if the polymorphic relations are not available : could you post as well the content of your model-config.json in the first place?

**Comment by Schubbcasten** [comment]
```
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models",
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "CustomAccessToken": {
    "dataSource": "dEB-test",
    "public": false
  },
  "ACL": {
    "dataSource": "dEB-test",
    "public": false
  },
  "Admin": {
    "dataSource": "dEB-test",
    "public": true,
    "options": {
      "remoting": {
        "sharedMethods": {
          "patchAttributes": true,
          "replaceById": false,
          "confirm": false,
          "resetPassword": false
        }
      }
    }
  },
  "Customer": {
    "dataSource": "dEB-test",
    "public": true,
    "options": {
      "remoting": {
        "sharedMethods": {
          "patchAttributes": true,
          "replaceById": false,
          "confirm": false
        }
      }
    }
  },
  "Role": {
    "dataSource": false,
    "public": false
  },
  "User": {
    "dataSource": false,
    "public": false
  }
}`
```

**Comment by ebarault** [comment]
could you please try removing `User` from your model-config.json ?

**Comment by Schubbcasten** [comment]
that doesn't change anything, warning is still there.

**Comment by ebarault** [comment]
could you please fork a sandbox app using https://github.com/strongloop/loopback-sandbox, so we can investigate ?

**Comment by Schubbcasten** [comment]
[](https://github.com/Schubbcasten/loopback-sandbox)
Added the models that seem to produce the issue and added all dependencies.
Note:
With the sandbox version of loopback (2.22.0) the messaage doesn't show. But i think that' s because that warning was introduced with lb3. When updating the dependecies the warning shows up again.

**Comment by ebarault** [comment]
thanks, i'll review this.
Yes the warning was added with LB3, we're currently working on some improvements.

**Comment by ebarault** [comment]
hi @Schubbcasten,
I was able to reproduce your issue.
It seems there's a bug in the way the polymorphic relation "belongsTo" is implemented.
as described in the doc [here](https://loopback.io/doc/en/lb3/Polymorphic-relations.html#belongsto-polymorphic-relations), the model name seems expected which i always considered as a doc issue as the model name is unknown upfront.

Well, it appears that this is more than just a doc issue, the code expects a valid model name and you can use any here, it does not matter, it will not be used afterwards.

For now, just add it like in the following:
```
"relations": {
    "user": {
      "type": "belongsTo",
      "idName": "id",
      "model": "Customer",
      "polymorphic": {
        "idType": "string",
        "foreignKey": "userId",
        "discriminator": "principalType"
      }
    }
  },
```

We'll address the root cause in an other issue, and fix the doc

**Comment by Schubbcasten** [comment]
hi @ebarault 

Thanks a lot for your help and the clarification. I have one more quick question then. In the polymorphic doc it shows the example with the Picture model that belongs to an author. What would the model look like, if I also want the picture to belong to either an Author or a Reader?
```
// Like this?
{
  "name": "Picture",
  "base": "PersistedModel",
  ...
  "relations": {
    "someUser": {
      "type": "belongsTo",
      "polymorphic": {
        "foreignKey": "imageableId",
        "discriminator": "imageableType"
      }
    }
  },

// or like this?
{
  "name": "Picture",
  "base": "PersistedModel",
  ...
  "relations": [
    "author": {
      "type": "belongsTo",
      "model": "Author",
      "polymorphic": {
        "foreignKey": "imageableId",
        "discriminator": "imageableType"
      }
    },
    "reader": {
      "type": "belongsTo",
      "model": "Reader",
      "polymorphic": {
        "foreignKey": "imageableId",
        "discriminator": "imageableType"
      }
    }
  ],
```

**Comment by ebarault** [comment]
please, remove this unrelated question in order to keep the issue clean, and let's discuss this on gitter

**Comment by ebarault** [comment]
this is fixed in https://github.com/strongloop/loopback-datasource-juggler/pull/1289
