### ISSUE TITLE
Camel casing is removed in model name when created with slc loopback:model

### ISSUE THREAD

**Issue by kamal0808** [strongloop/loopback#3310]
# Description/Steps to reproduce
Creating a model with `slc loopback:model` removes **Camel-casing** names in `modelName.js` whereas keeps as-it-is in  `modelName.json`. 

Steps to reproduce:
- Go to terminal in your project dir and type `slc loopback:model`
- Write model name in camel casing. For example, `MyNewModel`
- Complete steps. Go to file `myNewModel.js`, you'll find module name as `Mynewmodel` instead of `MyNewModel`. 

# Expected result
- It should write module name as `MyNewModel` instead of `Mynewmodel`. 

# Additional information

`darwin x64 5.12.0`
```
├── loopback@2.27.0
├── loopback-boot@2.18.1
├── loopback-component-explorer@2.4.0
├── loopback-connector-es@1.3.4
├── loopback-connector-mongodb@1.15.2
├── loopback-datasource-juggler@2.46.0
├── loopback-ds-timestamp-mixin@3.4.0
npm ERR! invalid: options@0.0.6 /Users/kamal/dev/Blubox/node_modules/loopback/node_modules/strong-remoting/node_modules/sse/node_modules/options
```

**Comment by siddhipai** [comment]
Hi @kamal0808 ,
You can refer this link which talks more about camel-casing. So this is the expected behaviour.
https://loopback.io/doc/en/lb2/Model-definition-JSON-file.html#overview

**Comment by kamal0808** [comment]
@siddhipai Quoting from doc
> For example, if you create a model named “FooBar” with the model generator, it creates files foo-bar.json and foo-bar.js in common/models. However, the model name (“FooBar”) will be preserved via the model’s name property.

However, the model name ("FooBar") **IS NOT** preserved via the model's name property. It changes to ("Foobar"). Please don't close this issue yet.

**Comment by superkhau** [comment]
@siddhipai Please try to reproduce @kamal0808's issue and see if the behaviour if different from the docs. If so, we can escalate this to a bug.

**Comment by kamal0808** [comment]
@superkhau Are you sure this issue should be closed? I hope someone solved it but I don't see any reference to any pull request.
