### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by waleed2744** [strongloop/loopback#3311]
what is the solution of this error ?
![capture](https://cloud.githubusercontent.com/assets/26245331/24338395/eeb9ba5c-1259-11e7-85a7-6bb7dca94d24.PNG)

**Comment by bajtos** [comment]
Hello, this error is related to `forceId` setting that controls whether clients are allowed to provide their own `id` values, or whether model id must be always generated by the server.

Please provide us with steps how to reproduce the problem you are experiencing, see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report.
