### ISSUE TITLE
ACL don't persisted into datasource

### ISSUE THREAD

**Issue by upupzealot** [strongloop/loopback#3315]
ACL don't persisted into datasource

I created ACL instances by code
```js
co(function*() {
  const ACL = loopback.ACL;
  const Role = loopback.Role;
  const acl = yield ACL.create({
    model: Model.modelName,
    accessType: ACL.EXECUTE,
    principalType: ACL.ROLE,
    principalId: Role.EVERYONE,
    permission: ACL.ALLOW,
    property: '__create__comments'
  });
  console.log(acl)
}).catch(console.error);
```

the log shows I'v created ACL instances, but cant find them in the datasource(postgresql).

**Comment by upupzealot** [comment]
#3191

**Comment by ebarault** [comment]
ahh.. that's strange, ACL is just like any other built-in model in LB, it should persist to datasource. Could you share a sample app reproducing the issue?

https://github.com/strongloop/loopback-sandbox
