### ISSUE TITLE
lb-ng: command not found

### ISSUE THREAD

**Issue by sebdelvalle** [strongloop/loopback#3317]
# Description/Steps to reproduce
lb-ng

# Expected result
command should exist and allow you to generate angular services

# Additional information

linux x64 6.10.1

└── UNMET DEPENDENCY loopback-connector-sendgrid@^1.2.2
npm ERR! missing: loopback-connector-sendgrid@^1.2.2, required by Referrall@1.0.0

**Comment by bajtos** [comment]
Please install `loopback-sdk-angular-cli` via the following command:

````
$ npm install -g loopback-sdk-angular-cli
```

If the problem persists, then please provide us with steps to reproduce the problem and reopen this issue.
