### ISSUE TITLE
How to set ACLs in javascript?

### ISSUE THREAD

**Issue by upupzealot** [strongloop/loopback#3318]
Is the json file the only way to define ACLs to a model?
Can I define/change ACL settings in javascript?

**Comment by bajtos** [comment]
For a model class `MyModel`, the ACLs are stored in `MyModel.settings.acl` property. You can manipulate this value for example from a model `.js` script.

Would you mind contributing a pull request to our documentation to clarify this usage? See http://loopback.io/doc/en/contrib/doc-contrib.html to get started.

**Comment by upupzealot** [comment]
@bajtos I find an other way: use `loopback.configureModel`, like
```js
loopback.configureModel(Model, {
  dataSource: Model.dataSource,
  acls: [
    {
      accessType: 'EXECUTE',
      principalType: 'ROLE',
      principalId: '$authenticated',
      permission: 'ALLOW',
      property: '__create__comments',
    },
  ],
});
```
this will keep all configs and add the acl to existed acls to the `Model`

**Comment by ebarault** [comment]
hi, 
do you seek to have those ACLs persisted ? 
there's of course the possibility or you to create ACL instances which will be looked up as well along with ACLs defined by code.
