### ISSUE TITLE
hasManyThrough with filter on mapping table

### ISSUE THREAD

**Issue by shibusr** [strongloop/loopback#3319]
Hi all, we have three table Physician, Appointments, Patient. We are using hasmany throuhg relationship to get pysician and his patient by setting relation ship through Appointment. Now we need to filter the result by a field in Appointment table

How we can do this using loopback relations?

**Comment by bajtos** [comment]
I am afraid LoopBack does not support this feature yet, see https://github.com/strongloop/loopback/issues/466.

I am closing this issue as a duplicate.
