### ISSUE TITLE
How to change the field delete instead of id?

### ISSUE THREAD

**Issue by odedtaizi** [strongloop/loopback#3320]
I want to the delete a few rows in MySQL table using loopabck. But I don't want to use the id to delete the record. I'm trying it in Angular SDK

    ModelName.destroyById({ fieldName : myValue })
                          .$promise
                          .then(function() {
                          });

**Comment by bajtos** [comment]
You can use [`deleteAll`](http://apidocs.strongloop.com/loopback/#persistedmodel-destroyall) method. Note that this method is not exposed via REST API by default, because it makes it too easy to accidentally delete the whole table/collection.
