### ISSUE TITLE
Error: Shared class  "Supplier" has no method handling POST /57/kmRange

### ISSUE THREAD

**Issue by davidrivers93** [strongloop/loopback#3321]
Hello.

I have a related model called KmRange and a model called Supplier, Supplier hasMany KmRanges. When I try to make a save to http://localhost:3001/api/Suppliers/57/kmRange it throws me a 404 error : Shared class  "Supplier" has no method handling POST /57/kmRange.

I haved found the ACL solution but it's not working on my project. Running the project on debug mode it shows me the next flow : 

>  loopback:security:acl The following ACLs were searched:  +0ms
  loopback:security:acl ---ACL--- +1ms
  loopback:security:acl model Supplier +1ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +0ms
  loopback:security:acl principalId $everyone +0ms
  loopback:security:acl accessType EXECUTE +0ms
  loopback:security:acl permission ALLOW +0ms
  loopback:security:acl with score: +0ms 7620
  loopback:security:acl ---Resolved--- +0ms
  loopback:security:acl The following ACLs were searched:  +43ms
  loopback:security:acl ---ACL--- +0ms
  loopback:security:acl model Supplier +0ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +0ms
  loopback:security:acl principalId $everyone +0ms
  loopback:security:acl accessType EXECUTE +0ms
  loopback:security:acl permission ALLOW +0ms
  loopback:security:acl with score: +0ms 7620
  loopback:security:acl ---Resolved--- +0ms
  loopback:security:acl The following ACLs were searched:  +8ms
  loopback:security:acl ---ACL--- +1ms
  loopback:security:acl model Supplier +0ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +0ms
  loopback:security:acl principalId $everyone +0ms
  loopback:security:acl accessType EXECUTE +0ms
  loopback:security:acl permission ALLOW +0ms
  loopback:security:acl with score: +0ms 7620
  loopback:security:acl ---Resolved--- +0ms
  loopback:security:acl The following ACLs were searched:  +40ms
  loopback:security:acl ---ACL--- +0ms
  loopback:security:acl model Supplier +0ms
  loopback:security:acl property * +0ms
  loopback:security:acl principalType ROLE +0ms
  loopback:security:acl principalId $everyone +0ms
  loopback:security:acl accessType EXECUTE +0ms
  loopback:security:acl permission ALLOW +0ms
  loopback:security:acl with score: +0ms 7620
  loopback:security:acl ---Resolved--- +0ms
Error no gestionado para la solicitud POST /Suppliers/57/kmRange: Error: Shared class  "Supplier" has no method handling POST /57/kmRange
    at restRemoteMethodNotFound (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/strong-remoting/lib/rest-adapter.js:329:17)
    at Layer.handle [as handle_request] (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:317:13)
    at /Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:317:13)
    at /Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/express/lib/router/index.js:275:10)
    at /Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/body-parser/lib/read.js:129:5
    at invokeCallback (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/raw-body/index.js:262:16)
    at done (/Users/david/Desktop/projects/traqui/pricing-api-v1/node_modules/raw-body/index.js:251:7)

My ACL configuration is : 

`  "acls": [
    {
       "accessType": "*",
       "principalType": "ROLE",
       "principalId": "$everyone",
       "permission": "ALLOW",
       "property": "__create__KmRanges",
       "accessType": "*"
     }
  ],`

Any idea?

Thanks in advance.
David.

**Comment by ebarault** [comment]
hi, a problem with ACL config would throw a 401 error, not a 404.

Can you see the relation defined in swagger explorer?
It seems there's a problem in your relation/model config, that makes the related method undefined.

**Comment by davidrivers93** [comment]
Hi @ebarault 

This is the supplier.json on the API1 :  

> {
  "name": "Supplier",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "zones": {
      "type": "hasMany",
      "model": "Zone",
      "foreignKey": ""
    },
    "rates": {
      "type": "hasMany",
      "model": "Rate",
      "foreignKey": ""
    },
    "volumetricWeightRanges": {
      "type": "hasMany",
      "model": "VolumetricWeightRange",
      "foreignKey": ""
    },
    "price": {
      "type": "belongsTo",
      "model": "price"
    },
    "kmRange": {
      "type": "hasMany",
      "model": "KmRange"
    },
    "routes": {
      "type": "hasMany",
      "model": "Route",
      "foreignKey": ""
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}

We have another API (API2) that has a connector (using remote connector) for using the API1 supplier model and his related models.

Thanks for the support.
David.

**Comment by davidrivers93** [comment]
Any idea?

Thanks in advance.

**Comment by davidrivers93** [comment]
Any idea?
Thanks in advance.

**Comment by adamhenson** [comment]
I experienced a similar problem when following the ["Accessing Related Model" documentation](https://loopback.io/doc/en/lb3/Accessing-related-models.html) and opened #3462.

> When two models have a relationship between them (see Creating model relations), LoopBack automatically creates a set of related model methods corresponding to the API routes defined for the relationship.

I'm wondering if we both have issues in our attempts to use "related model methods". I see `__create__KmRanges` in this post. I have a similar method in my issue.

In my similar issue - I created a `hasMany` / `belongsTo` relationship from a `User` extended model named `user` with a model named `account` [shown in this diff](https://github.com/adamhenson/loopback-api-example/compare/master...relations), and the ACL shown [here](https://github.com/adamhenson/loopback-api-example/compare/relations...acl).

When submitting a POST request to `/users/{id}/accounts` where `{id}` is the user id, I too get a 404 with:

```
Shared class  \"User\" has no method handling POST /594fcbeee223ce23620a3e12/accounts?access_token=Dg8qkXIHEck9fS0taCPWxklSVwD6HivN7iVU0lq0SBhaXQ8dMJmo6j8WxQGBNKRD
```

**Comment by moacirosa** [comment]
In addiction to @ebarault in https://github.com/strongloop/loopback/issues/3321#issuecomment-291099917 I would suggest check if `Supplier` with _id_ `57` actually exists. It's trivial but this was my problem when I've faced something similar.
