### ISSUE TITLE
Message Model in loopback

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback#3323]
Summarized from discussion with @qpresley : 

Like PersistedModel is built with CRUD operations, it's good for loopback to have a MessageModel which talks to message services like mqlight, rabbitmq, etc...

MessageModel will integrate with basic message operations like `send` and `receive`, example see functions in [`loopback-connector-mqlight`](https://github.com/strongloop/loopback-connector-mqlight/blob/master/lib/mqlight-model.js)
 

cc @raymondfeng @ritch @bajtos @superkhau any thought? Maybe support it in loopback-next.

**Comment by superkhau** [comment]
@jannyHou I think we should definitely have something along the lines of DAO/KVAO for MAO to interface with MQ operations. We have no exact plans yet, but I recall this discussion has happened in the past. It'll take a bit of work like what we did on the KV-connectors though. ;)

**Comment by bajtos** [comment]
+1 for defining a shared API for messaging.

How do we envision to implement `receive` (or perhaps `subscribe`?) Are we expected the clients to keep a long-polling request that will be handled once a message arrives, and then expecting the client to open another long-polling connection? Do we want the clients to use WebSockets instead? Or perhaps even-stream, as we are already doing in `PersistedModel.createChangeStream` method. LoopBack does not have good support for real-time communication right now, although there has been some work done by @ritch in [strong-pubsub repositories](https://github.com/strongloop?utf8=%E2%9C%93&q=pubsub&type=&language=).

IMO, we need to start from outside here and figure out how do we want REST clients to consume a stream of events produced by messaging services.

> Maybe support it in loopback-next.

IMO, this is an incremental feature than can be added to LoopBack 3.x if we have bandwidth to work on it before loopback-next is GA.
