### ISSUE TITLE
Loopback Realtime Database + ACL Implements ?

### ISSUE THREAD

**Issue by tabvn** [strongloop/loopback#3328]
I have been working on this and i hope someone can able find this (Loopback Realtime Database and ACL Permission Implements) 
code: https://github.com/tabvn/loopbackCMS
see Video how it works: https://www.youtube.com/watch?v=z38B_iA4fJI

i hope it helps

Best regards,
Toan

**Comment by bajtos** [comment]
Thank you @tabvn for sharing. Would you like to showcase your project in http://loopback.io/doc/en/community/index.html?

There isn't much else to do about this issue, I am closing it as resolved.

**Comment by tabvn** [comment]
that is cool :) thank you @bajtos
