### ISSUE TITLE
Filter error

### ISSUE THREAD

**Issue by daordonez11** [strongloop/loopback#3329]
Hello my question is simple whenever I try to do a simple filter query on mi api y continue getting an empty array querying any String attribute in the model.

For examplo if I do:
https://apiurl/api/Moodel?filter={"where":{"bookingStatus":"123456789101123456789101"}}}
This returns empty array
If I try 
https://apiurl/api/Moodel?filter={"where":{"bookingStatus":"1234567891011234567891011"}}}
Returns every item with that value.
Couldn't find any information in the documentation

**Comment by ebarault** [comment]
hi, if no model's instance have the bookingStatus "123456789101123456789101", this is the expected behavior.

Please use the google group or the gitter channel for questions
