### ISSUE TITLE
Updating user email breaks login

### ISSUE THREAD

**Issue by jdforsythe** [strongloop/loopback#3333]
# Description/Steps to reproduce
In an angular app, using `User.prototype$updateAttributes({id: user.id}, {email: vm.newEmail})` as suggested here [https://github.com/strongloop/loopback-sdk-angular/issues/125](https://github.com/strongloop/loopback-sdk-angular/issues/125)

It also required this ACL (didn't pick up the 'updateAttributes' ACL):
```
      {
        'principalType': 'ROLE',
        'accessType': 'WRITE',
        'principalId': '$owner',
        'permission': 'ALLOW',
        'property': 'patchAttributes',
      }
```

It properly calls a PATCH to /user/:id and updates the email. The login, however, no longer works. ~~Just grasping at straws, but is the email used as a salt in the password hashing?~~

It turns out it has nothing to do with the password. It resets `user.emailVerified` to false when updating the email address. You cannot get around this by setting this property to `true` in the `updateAttributes` call.

# Expected result
Updating email address shouldn't break login

# Additional information
```
darwin x64 6.9.4

├── loopback@3.4.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@2.7.0
├── loopback-component-passport@2.3.0
├── loopback-component-storage@3.2.0
├── loopback-connector-mailgun@0.0.7
├── loopback-connector-mysql@3.0.0
npm ERR! missing: eslint-plugin-angular@^2.2.0, required by loopback-example-passport@2.0.0
npm ERR! missing: uglify-js@^2.4.19, required by jade@1.11.0
npm ERR! missing: options@latest, required by sse@0.0.6
npm ERR! missing: colour@latest, required by ascli@0.3.0
npm ERR! missing: optjs@latest, required by ascli@0.3.0
```

**Comment by bajtos** [comment]
This behaviour is intentional. If your application requires email addresses to be verified, then users must verify the new email address they entered into the system before they can login again.

You can modify your app to not require emails to be verified by changing the setting `emailVerificationRequired`, see https://loopback.io/doc/en/lb2/Registering-users.html#verifying-email-addresses for more details.
