### ISSUE TITLE
I want infinite AccessToken allow.

### ISSUE THREAD

**Issue by cheese10yun** [strongloop/loopback#3338]
I want infinite AccessToken allow.

and i try ttl value is  -1 

but faild message INVALID_TOKEN

how to infinite AccessToken allow ?

English is difficult to use. Please understand

Thank you.

**Comment by cheese10yun** [comment]
i'm resolved eternal Access Token Allow

first `AccessToken` model and User Model is should be connected by foreign key

second  allowEternalTokens : true must be declared in `user.json`(model directory)  file 


I am not accustomed to English. Please understand

Thank you.

**Comment by shaheero** [comment]
I recommend that you make a pull request to the docs to include how to do this
https://github.com/strongloop/loopback.io/edit/gh-pages/pages/en/lb3/Authentication-authorization-and-permissions.md
