### ISSUE TITLE
Access Scopes

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#3339]
# Description/Steps to reproduce

In #3313, I laid ground work for implementing scopes-based authorization. To make this implementation a first-class citizen in LoopBack world, we need to:

 - [ ] Agree on how to define scopes at app/model level - see the discussion in https://github.com/strongloop/loopback/pull/3313 for more details  
 - [ ] Implement this solution
 - [ ] Write documentation (see https://github.com/strongloop/loopback.io/pull/338 for a starter)

Next steps to consider:
 - Consider integration with our CLI tooling and `lb acl`
 - Should we describe the scopes in the Swagger document generated by loopback-swagger? (see https://github.com/strongloop/loopback/pull/3313#issuecomment-291993277)

cc @raymondfeng @ebarault @drmikecrowe

# Additional information

**Comment by ebarault** [comment]
@bajtos : regarding **defining scopes at model level** i picked the code from commit strongloop/loopback@6f9ae2a, rebased it on top of PR #3313 and pushed it to a seperate branch: https://github.com/strongloop/loopback/tree/feature/access-scopes

**Comment by pulkitsinghal** [comment]
@ebarault - how should I go about tracking if your code was ultimately merged and if this feature has solidified in 3.x?
