### ISSUE TITLE
customise host for user.verify link

### ISSUE THREAD

**Issue by timlind** [strongloop/loopback#3341]
# Description/Steps to reproduce

On heroku config.js host needs to be 0.0.0.0 so the host used for the link in the email sent by user.verify needs to be accept a host parameters, api documentation does not indicate this is possible.

Also do these emails get sent through the email datasource that is setup or another transport mechanism?

# Expected result

# Additional information

**Comment by bajtos** [comment]
`User.prototype.verify` already accepts `verifyOptions` object where you can provide your own `host` value. See https://github.com/strongloop/loopback/blob/6a4bd6d09f0d080716e16f022f770c8625c7020c/common/models/user.js#L724
