### ISSUE TITLE
polymorphic relation based on property

### ISSUE THREAD

**Issue by joeybenenati** [strongloop/loopback#3347]
I have review the loopback polymorphic relation docs (https://loopback.io/doc/en/lb3/Polymorphic-relations.html) and I am trying to determine if I can achieve a polymorphic relation that suits the following needs:

I have List, Task, and Event models. Lists can have many Tasks OR have many Events. Lists also have a type property that defines what kind of child objects it has. ie, "tasks", "events". What I'd like is to have a polymorphic "items" relation on the List model that would query whichever relation is defined by the type property. So if I queried a List with type "events" with {include: "items"} it would return Events in the items array.

Is this implementation supported by Loopback?

**Comment by joeybenenati** [comment]
or would i be able to achieve this with a custom scope?

**Comment by ebarault** [comment]
have you tried hasMany inverted polymorphic relations? as in https://loopback.io/doc/en/lb3/Polymorphic-relations.html#hasandbelongstomanypolymorphic-relations

invert allows the discriminator to be hosted by the modelFrom of a hasMany relation rather than by the modelFrom of a belongsTo relation. Although i'm not sure it will work without a through model.

**Comment by joeybenenati** [comment]
thanks, @ebarault.the inverted makes sense, but still not able to get it to work.

i've tried this List definition to no avail. does that look right? I have Tasks with `listId: 3` but when including `"items"`, the array is empty.
```
"items": {
      "type": "hasMany",
      "model": "Task",
      "polymorphic": {
        "as": "tasks",
        "foreignKey": "listId",
        "inverted": true,
        "discriminator": "type"
       } 
    },
    "items": {
      "type": "hasMany",
      "model": "Event",
      "polymorphic": {
        "as": "events",
        "foreignKey": "listId",
        "inverted": true,
        "discriminator": "type"
       } 
    }
```
