### ISSUE TITLE
New password-reset flow: docs, examples, project template

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#3349]
- [ ] Update https://github.com/strongloop/loopback-example-user-management 
   - https://github.com/strongloop/loopback-example-user-management/pull/58
- [ ] Update our documentation to reflect the changes made in https://github.com/strongloop/loopback/issues/382. Include a guide showing users how to correctly set up password-related endpoints in LoopBack applications.
  (internal task: https://github.com/strongloop-internal/scrum-asteroid/issues/131)
- [ ] Modify the template in loopback-workspace to enable the new, more secure mode
  (internal task: https://github.com/strongloop-internal/scrum-asteroid/issues/132)
- [ ] Print a warning when the feature flag is unset, to force users to make a decision whether to upgrade or stay behind.
  (internal task: https://github.com/strongloop-internal/scrum-asteroid/issues/133)
- [ ] Announce these changes to our ANN mailing list

**Comment by superkhau** [comment]
Create new timeboxed story.

**Comment by bajtos** [comment]
I don't think we will have bandwidth to do this, considering that LB 4.0 has been released.
