### ISSUE TITLE
Count not working with embedded models

### ISSUE THREAD

**Issue by prtkkmrsngh** [strongloop/loopback#3363]
All api are returning count as 0 where relations type is embedsMany.

**For example** 
In repository [loopback-example-relations](https://github.com/strongloop/loopback-example-relations)
following api returns count 0 after adding any number of emails.
http://localhost:3000/api/Customers/1/emails/count

**Comment by 0candy** [comment]
There is a bug logged for relations embedsMany count not working.

Closing this as a dup.
Please follow issue here: https://github.com/strongloop/loopback-datasource-juggler/issues/258
