### ISSUE TITLE
Inconsistent execution order between operation hook and custom strong-remoting phase hook

### ISSUE THREAD

**Issue by f-w** [strongloop/loopback#3368]
With LB3, I am trying to use [custom strong-remoting phase](http://loopback.io/doc/en/lb3/Using-current-context.html#use-a-custom-strong-remoting-phase) to inject httpContext into *args.options* in order to access HTTP headers in downstream middleware such as operation hooks. I need this injection for all methods, built-in or not, in all of my models and I think this is the least effort approach in terms of minimizing duplications - even better than mix-ins. But it turns out the execution order between operation hooks and strong-remoting phase hooks are inconsistent. To be more specific, I have tried both `.addBefore('invoke'` and `.addAfter('auth'` phases. For built-in remote methods they are executed before the operation hook `access`; for custom instance remote methods executed afterwards.

What is the correct approach in my scenario?

**Comment by bitmage** [comment]
Related to https://github.com/strongloop/loopback/issues/3434, https://github.com/strongloop/loopback/pull/3048.
