### ISSUE TITLE
customized remote method cannot return with status code 200

### ISSUE THREAD

**Issue by seanxlliu** [strongloop/loopback#3370]
Thanks for the great job.

My issue is as title. 
To reproduce the issue, creates a standard remote method and specifies the default status code as 200, like following,

```
   module.exports = function(Person){

    Person.greet = function(msg, cb) {
      cb(null, 'Greetings... ' + msg);
    }

    Person.remoteMethod('greet', {
          accepts: {arg: 'msg', type: 'string'},
          //returns: {arg: 'greeting', type: 'string'}, // remove this
          http: { status: 200}
    });
   };
```

but 'status 200' is ignored and still returns 204.
I know it is forced when returning no content. Any workaround or did I make a mistake in the code? I searched the whole repository but didn't find the code to how the default was set to 204. Please help to point the file who did the 'magic'. Any clues are appreciated.

**Comment by bajtos** [comment]
Here is the code setting the status code when the response body is missing:

https://github.com/strongloop/strong-remoting/blob/14a03ccfd9a9b4210d3e68e9a87ed76e07948b6e/lib/http-context.js#L575-L577
```js
    if (res.statusCode === undefined || res.statusCode === 200) {
      res.statusCode = 204;
    }
```

**Comment by regevbr** [comment]
I added returns: {arg: 'greeting', type: 'string'} and called the callback with empty string - sadly that is the only solution
