### ISSUE TITLE
Typo in docs -LB3- "Define the Review model"

### ISSUE THREAD

**Issue by ambrt** [strongloop/loopback#3375]
In LB3 tutorial at [Create-new-models](http://loopback.io/doc/en/lb3/Create-new-models.html), there is typo in part of creating Review model:<br>
There is:<br>
Model name: Review 
Data source: mongoDs (mongodb)
Base class: Use the down-arrow key to select PersistedModel. 
Expose **Reviewer** via the REST API? Press RETURN to accept the default, Yes.

Should be
Expose **Review** via the REST API? Press RETURN to accept the default, Yes.

**Comment by 0candy** [comment]
PR merged, closing issue.
