### ISSUE TITLE
infinite loop when overriding find (with self through)

### ISSUE THREAD

**Issue by ptrblgh** [strongloop/loopback#3377]
Sample use case: I have a model called `CuUser` (datasource: postgresql). It has a field - besides many other fields - called `admin_id` which is a self reference to the User model thorugh an id.

The self related model (admin user) needs to contain only some fields (e.g.: only name). Plus the self related user model is always needed when query happens against the api (`http://localhost:3000/api/cuusers`). That is why I ended up overrinding the find for the model.

I have created the json model and js files based on the [https://loopback.io/doc/en/lb3/HasManyThrough-relations.html#self-through](url).

CuUser.json (name property also exists but left out for brevity):
```json
{
  "name": "CuUser",
  "plural": "CuUser",
  "options": {
    "idInjection": false,
    "postgresql": {
      "schema": "public",
      "table": "cu_user"
    },
    "relations": {
      "admin": {
        "model": "CuUser",
        "type": "belongsTo",
        "foreignKey": "cuAdminId",
        "keyThrough": "cuAdminId",
        "throught": "CuAdmin"
      }
    }
  },
  "properties": {
    "cuUserId": {
      "type": "Number",
      "id": 1,
      "required": true,
      "length": null,
      "precision": 32,
      "scale": 0,
      "postgresql": {
        "columnName": "cu_user_id",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": 32,
        "dataScale": 0,
        "nullable": "NO"
      }
    },
    "cuAdminId": {
      "type": "Number",
      "required": true,
      "length": null,
      "precision": 32,
      "scale": 0,
      "postgresql": {
        "columnName": "cu_admin_id",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": 32,
        "dataScale": 0,
        "nullable": "NO"
      }
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

CuUser.js:
```js
"use strict";

module.exports = function(CuUser) {
    DuUser.once('attached', function() {
        var override = CuUser.find;
        
        CuUser.find = function(filter, callback) {
            let includes;

            includes = {
                include: {
                    relation: "admin",
                    scope: {
                        fields: ["name"]
                    }
                }
            };
            
            return override.apply(this, [includes]);
        }
    });
}
```

CuAdmin.json:
```json
{
  "name": "CuAdmin",
  "options": {
      "idInjection": false,
      "relation": {
          "admin": {
              "type": "belongsTo",
              "model": "CuUser"
          }
      }
  }
}
```

The above code ends up in an infinite loop for the api and after a while an error occurs: 
```json
{
  "error": "no response from server"
}
```

Although when I send the following query (and of course delete the code from CuUser.js):
`http://localhost:3000/api/cuuser?filter=%7B%22include%22%3A%5B%22admin%22%5D%7D`
it works as expected (the self referenced model appears).

(The presented code works with NOT self referenced relations.)

Do I miss some extra settings on the model? :)

**Comment by zbarbuto** [comment]
You're not passing the callback on:

`return override.apply(this, [includes, callback]);`

**Comment by ptrblgh** [comment]
Still no response :/.

**Comment by zbarbuto** [comment]
Possibly unrelated to your core issue, but remember that `find` has an optional `options` parameter as well, so your override could cause some issues. It might be safer to use `arguments` instead.

I just tried this in sandbox and it worked:

```
module.exports = function(Widget) {
  Widget.once('attached', function() {
    var originalFind = Widget.find;
    Widget.find = function() {
      var filter = {
        where: {
          name: 'foobar'
        }
      };
      arguments[0] = filter;
      return originalFind.apply(Widget, arguments);
    };
  });
};
```

**Comment by ptrblgh** [comment]
The other filters work as excepted (skip, where, ...). Only the **selft through relatio**n causes this kind of problem.

**Comment by zbarbuto** [comment]
Ah, I get your problem now.

The core of the issue here is that overriding `find` is very dangerous. There are a lot of different parts of loopback that end up calling `find`, including model `includes`. This is why you're getting an infinite loop.

A better solution would be to add a default scope to your `CuUser` model:

```json
 // ...
 "properties": {}
  "scope": {
    "include": {
      "relation": "admin",
      "scope": {
        "fields": ["cuAdminId", "firstName"]
      }
    }
  },
  "validations": [],
 // ...
```

**Comment by ptrblgh** [comment]
Thank you, somehow I have missed the `scope` property in the documentation.

The provided config by you covers my needs. :) Closing the issue.
