### ISSUE TITLE
[Bug] $owner works wrong on LB3

### ISSUE THREAD

**Issue by cyclops24** [strongloop/loopback#3379]
# Description/Steps to reproduce

Hi guys,
I try using below model to manage my user managment:

```
{
  "name": "Employee",
  "plural": "Employees",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
    "strict": true
  },
  "mixins": {
    "ClearBaseAcls": true
  },
  "hidden": [
    "password",
    "verificationToken"
  ],
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "family": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {},
  "acls":
    [ { "principalType": "ROLE", "principalId": "$everyone", "permission": "DENY" },
      { "principalType": "ROLE", "principalId": "$everyone", "permission": "ALLOW", "property": "login" },
      { "principalType": "ROLE", "principalId": "$everyone", "permission": "ALLOW", "property": "logout" },
      { "principalType": "ROLE", "principalId": "$everyone", "permission": "ALLOW", "property": "confirm" },

      { "principalType": "ROLE", "principalId": "admin", "permission": "ALLOW" },

      { "principalType": "ROLE", "principalId": "$owner", "permission": "ALLOW", "property": "findById" },
      { "principalType": "ROLE", "principalId": "$owner", "permission": "ALLOW", "property": "updateAttributes" }
    ],
  "methods": {}
}
```
and Also use this mixis: (`ClearBaseAcls`)
```
'use strict';

const path = require('path');
const appRoot = require('app-root-path');

function slugify(name) {
  name = name.replace(/^[A-Z]+/, s => s.toLowerCase());
  return name.replace(/[A-Z]/g, s => '-' + s.toLowerCase());
}

module.exports = (Model) => {
  const configFile = path.join('./common/models/', slugify(Model.modelName) + '.json');
  const config = appRoot.require(configFile);

  if (!config || !config.acls) {
    console.error('ClearBaseAcls: Failed to load model config from', configFile);
    return;
  }

  Model.settings.acls.length = 0;
  config.acls.forEach(r => Model.settings.acls.push(r));
};
```

# Expected result
I want only admin can create users and manage all of user management and user only can login, logout, find own profile or change own profile so now anything is OK for me.
Only `admin` can `create` new user and do anything.
`$everyone` only can `login`, `logout` and `confirm` account.
But I have some issue with `$owner` part. Because of user creation done by admin now admin is owner of any other user and nobody can't use `findById` or `updateAttributes` (update profile).
But new users can use `findById` ( GET /Employees/{id} ) (I don't know why it's worked but it's all we need) BUUUUT another issue, new users can't use `updateAttributes` ( PATCH /Employees/{id} ) and show bellow error:
```
Authorization Required
```
Why  `findById` ( GET /Employees/{id} ) worked??
Why  `updateAttributes` ( PATCH /Employees/{id} )??
Why this two not same?

Can you guide me how to fix this?

# Additional information

```
$   node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 6.10.2
$ npm ls --prod --depth 0 | grep loopback
<no output>
```

**Comment by shaheero** [comment]
+1
Somehow related to https://github.com/strongloop/loopback/issues/3348

**Comment by cyclops24** [comment]
@bajtos do you have any suggestion about this?

**Comment by cyclops24** [comment]
Finally I found a working solution:
I change this line:
```
{ "principalType": "ROLE", "principalId": "$owner", "permission": "ALLOW", "property": "updateAttributes" }
```
to below line:
```
{ "principalType": "ROLE", "principalId": "$owner", "permission": "ALLOW", "property": "patchAttributes" }
```
I found it in [this file](https://github.com/strongloop/loopback/blob/master/common/models/user.json#L65).

It's a documentation issue [here](https://apidocs.strongloop.com/loopback/#user) where `updateAttributes` changed to `patchAttributes` but it's not changed in docs.

**Comment by bajtos** [comment]
@cyclops24 I am glad you have figured out the solution yourself. Would you like to contribute the documentation fix to help future users? See http://loopback.io/doc/en/contrib/code-contrib.html to get you started.
