### ISSUE TITLE
Access Token Not generated correctly

### ISSUE THREAD

**Issue by eman6576** [strongloop/loopback#3382]
# Description/Steps to reproduce

Hello,

I am trying to generate an AccessToken instance. I first call the static method `createAccessTokenId` to generate the access token id. Then I do `new AccessToken({id: authorizationToken});` to get the instance. The problem is this instance looks like this:
`{ id: NaN, created: 2017-05-02T23:17:18.707Z, ttl: 1209600 }`. For the `id` value, it is null even though i provided the id. If i then try to use the access token in explorer for any endpoints that require authentication, I get a 401. I also tried doing `AccessToken.create`, but it still doesn't save it to my PostgresSQL database.

This is the code that i use in my Extended model of User:
```
AccessToken.createAccessTokenId(function(error, authorizationToken) {
          if (error) {
            console.log('Error generating authorization token');
            callback(error, null);
          } else {
            console.log(picksUser);
            AccessToken.destroyAll({where: {userId: picksUser.id}});
            var accessToken = new AccessToken({id: authorizationToken});
            console.log(accessToken);
            console.log('Authorization token generated')
            let json = {"token": authorizationToken};
            callback(null, json);
          }
```

# Expected result

`{ id: "<The authorization token Id generated from createAccessTokenId>", created: 2017-05-02T23:17:18.707Z, ttl: 1209600 }`

# Additional information

` node -e 'console.log(process.platform, process.arch, process.versions.node)'`:
darwin x64 6.9.4
`npm ls --prod --depth 0 | grep loopback`:
picks-loopback@1.0.0 /Users/Emanuel/Desktop/SilverLogic/picks-loopback
├── loopback@3.7.0
├── loopback-boot@2.24.0
├── loopback-component-explorer@4.2.0
├── loopback-connector-postgresql@2.8.0

**Comment by eman6576** [comment]
I was able to figure out the issue. It was an issue with my relationship with AccessToken and My User model.

**Comment by dynshon** [comment]
I have same problem, how did You resolved?
