### ISSUE TITLE
('apidocs.strongloop.com') does not exist

### ISSUE THREAD

**Issue by upupzealot** [strongloop/loopback#3383]
404 says
`404 Not Found: Requested route ('apidocs.strongloop.com') does not exist.`
Can't visit api site at this moment.
Are we changing domain?

**Comment by nVitius** [comment]
It's working for me.
<img width="1119" alt="screen shot 2017-05-03 at 12 13 21 pm" src="https://cloud.githubusercontent.com/assets/3804041/25677210/f04d9a7e-2ff9-11e7-8450-d2e59c01a611.png">

**Comment by padelagani** [comment]
@upupzealot It has now been resolved

**Comment by upupzealot** [comment]
@nVitius @padelagani thanks for replying, it's working now~
