### ISSUE TITLE
Mixins can only be used on built-in models after being used on custom models.

### ISSUE THREAD

**Issue by JustinTRoss** [strongloop/loopback#3385]
# Description/Steps to reproduce
Mixins are not defined until included on a custom model. If you use mixin on a built-in model without using the mixin on a custom model, you encounter the error: ```Error: Model <ModelName> uses unknown mixin: <MixinName>```

Debatable whether this is enhancement or bug.
#### Steps to reproduce:
1. Create a mixin
2. Create a boot script to use mixin on built-in model, like so:
```
module.exports = (app) => {
  const User = app.models.User
  app.on('started', () => { // I am emitting 'started' once server boot is complete.
    User.mixin('Test')
  })
}
```
3. Go into loopback-datasource-juggler at line 32, and log mixins to console.
```
MixinProvider.prototype.applyMixin = function applyMixin(modelClass, name, options) {
const { mixins} = this
console.log(mixins)
...
```

4. Boot your app and see the following error:
```  loopback:mixin Model "User" uses unknown mixin: Test +1ms ```

5. If you now add the following mixins config to the json of a custom component, you will see the 'Test' mixin logged to console. Additionally, your mixin will run successfully on User.

# Expected result
Expect mixins to be available for use on built-in models.

# Additional information
darwin x64 7.3.0
loopback@3.4.0
loopback-boot@2.24.0
loopback-component-explorer@2.7.0

**Comment by jonathan-casarrubias** [comment]
+1 on this request, I would like to dynamically register a mixin to all models, custom and built in, but it can not be done because of it complains about the unknown mixin issue

**Comment by adrianasz** [comment]
Is there a workaround for this? Currently no matter which model I use mixins on, I get this error.

**Comment by jonathan-casarrubias** [comment]
😢

**Comment by arondn2** [comment]
Hi @JustinTRoss. Maybe this could be a alternative:

```js
// common/models/my-model.js

var myMixin = require('../mixins/my-mixin');

module.exports = function (MyModel) {
  myMixin(MyModel, options);
};
```
