### ISSUE TITLE
demo.strongloop.com MIA (returns 404)

### ISSUE THREAD

**Issue by sanderboom** [strongloop/loopback#3387]
Original report at strongloop/loopback.io/pull/376

crandmck: 
> There was an outage yesterday, but the site is back up and should be working as documented now.
> Please try it again. I'll close this, but if you still have problems accessing, please log an issue in https://github.com/strongloop/loopback since it should be working. Thanks!

me:
> For me demo.strongloop.com is a `404 Not Found` and I don't think I am the [only one](http://www.downforeveryoneorjustme.com/demo.strongloop.com)  :worried:

**Comment by crandmck** [comment]
I can ping it.  

```
$ ping demo.strongloop.com
PING demo.strongloop.com (192.237.213.245): 56 data bytes
64 bytes from 192.237.213.245: icmp_seq=0 ttl=51 time=57.980 ms
64 bytes from 192.237.213.245: icmp_seq=1 ttl=51 time=56.951 ms
64 bytes from 192.237.213.245: icmp_seq=2 ttl=51 time=57.655 ms
```

I don't think we ever had a web server there, which is why http://demo.strongloop.com/ doesn't come back.

I just tried out the step in the [Getting Started tutorial](http://loopback.io/doc/en/lb3/Connect-your-API-to-a-data-source.html) and it worked for me.  I was able to connect to the database, read and write data there.  Did you do that?

**Comment by sanderboom** [comment]
> I just tried out the step in the Getting Started tutorial and it worked for me. I was able to connect to the database, read and write data there. Did you do that?

Not at all. I clicked when I saw the link in the docs. Sorry about the confusion.

**Comment by crandmck** [comment]
> when I saw the link in the docs.

Oh, I see!  There shouldn't be a link there--obviously it's confusing to link to a non-existent site!
I'll remove it.  Thanks for bringing it to my attention.
