### ISSUE TITLE
Check the Validations Before Updating

### ISSUE THREAD

**Issue by helloapiworld** [strongloop/loopback#3388]
Hi I am new to loopback,can anyone help me how to do PUT api validations,what ever user will provide fields using loopback explorer those values has to update in model,remaining values are to take from Model(DB).
For example i have 5 fields FirstName,LastName,UserName,Password,MobileNo
FirstName,LastName and MobileNo can user able be update anytime but not UserName and Password. I don't have an idea how to check the validations for the fields FirstName,LastName and MobileNo. If user update any of those 3 fields i have to update the existing data for the fields otherwise i have to keep the old data. Could anyone help on this how to put validations for that.

![image](https://cloud.githubusercontent.com/assets/28555338/25882981/af2b3720-3564-11e7-89f3-b4f2ce8c11a4.png)
![image](https://cloud.githubusercontent.com/assets/28555338/25882983/b358fbca-3564-11e7-9383-912009e0791b.png)

**Comment by padelagani** [comment]
@helloapiworld 

Read this - http://loopback.io/doc/en/lb3/Migrating-to-3.0.html

Make sure you ask questions at gitter (https://gitter.im/strongloop/loopback) or google group (https://groups.google.com/forum/#!forum/loopbackjs), not to create an issue.

This is not an issue.
