### ISSUE TITLE
rejectPasswordChangesViaPatchOrReplace setting will throw error when saving updates not related to password

### ISSUE THREAD

**Issue by raulmt** [strongloop/loopback#3393]
# Description/Steps to reproduce

1. Create new loopback project using 3.x
2. Set `User.settings.rejectPasswordChangesViaPatchOrReplace = true` in some way (either on boot script or, if creating a custom User class, in `options` inside your model's JSON file)
3. Try the following code:
```js
const u = new User({email: 'loopback@example.org', password: '123'});
u.save(); // works
const u2 = User.findOne(); // in empty database, gets previous user
u2.username = 'loopback'; // only changing username (or for that matter, any other attribute if you have a custom User class
u2.save(); // throws PASSWORD_CHANGE_NOT_ALLOWED error
```
# Expected result
Saves without problem.

# Actual result

Throws error.
With this, the only way to alter the user object would be through update* methods. But this also prevents you from doing things like creating relationships from user object (`user.rel.build({}); user.save();`) and in any case it doesn't feel right to get error about "password change not allowed" when you are not changing the password.

Note that even the default `verify` User method fails with this settings, because in [these lines](https://github.com/strongloop/loopback/blob/9fb67315f9b9af4ae5e61ecef479888a8a9002f9/common/models/user.js#L767-L768) it tries to do similar thing to my example (setting `verificationToken` on the instance, and then calling `save`).

# Possible solution

Not sure if this is the best solution, but it seems you already need to check wether the password is being changed or not, with an heuristic to [recognize a bcrypt hash here](https://github.com/strongloop/loopback/blob/9fb67315f9b9af4ae5e61ecef479888a8a9002f9/common/models/user.js#L1065). So maybe we could externalize that check into a function and also use it just [after this](https://github.com/strongloop/loopback/blob/9fb67315f9b9af4ae5e61ecef479888a8a9002f9/common/models/user.js#L1269) to not only determine if `password` is in the data, but also discard if it's not really a password change but the existing password in the database.

```js
const isPasswordChange = 'password' in data && !isPasswordHash(data.password);
```

If that sounds good, I could submit a PR with that if you want.

# Additional information

darwin x64 6.9.2
```
├── loopback@3.8.0
├── loopback-boot@2.24.0
├── loopback-component-explorer@4.2.0
```

**Comment by ebarault** [comment]
Hi, could you please copy paste the error?

Cc: @bajtos

Le ven. 12 mai 2017 à 15:36, Raúl Montes <notifications@github.com> a
écrit :

**Comment by raulmt** [comment]
@ebarault Sure, here it is:
```
{ Error: Changing user password via patch/replace API is not allowed. Use changePassword() or setPassword() instead.
    at rejectInsecurePasswordChange (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback/common/models/user.js:1289:17)
    at notifySingleObserver (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:104:22)
    at /Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:3025:16
    at replenish (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:881:17)
    at /Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:885:9
    at eachLimit$1 (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:3114:22)
    at Object.<anonymous> (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/node_modules/async/dist/async.js:917:16)
    at doNotify (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:101:11)
    at doNotify (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at doNotify (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)
    at Function.ObserverMixin._notifyBaseObservers (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:122:5)
    at Function.ObserverMixin.notifyObserversOf (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:120:15)
    at Function.ObserverMixin.notifyObserversOf (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:97:8)
    at Function.ObserverMixin._notifyBaseObservers (/Users/raul/dev/metabolic/test/lala2/node_modules/loopback-datasource-juggler/lib/observer.js:120:15) statusCode: 401, code: 'PASSWORD_CHANGE_NOT_ALLOWED' }
```

Thrown [here](https://github.com/strongloop/loopback/blob/9fb67315f9b9af4ae5e61ecef479888a8a9002f9/common/models/user.js#L1289).

**Comment by bajtos** [comment]
FWIW, the first save works because it short-circuits to `User.create`, see [this line](https://github.com/strongloop/loopback-datasource-juggler/blob/b34b6e0ad41e9e2935488ff95c13bf93d892d212/lib/dao.js#L2484).

We have tried to detect whether the password value changed or not, but we haven't found any reliable way. For example, when you call `bcrypt` twice on the same value, it always produces a different hash.

I suppose we could check whether the supplied hash is the very same value as the hash already stored in the database and allow the operation then. I don't remember whether there were any issues with that. Would you like to give it a try and submit a pull request?

IMO, the correct fix is to move the password field out of `User` model into a `UserPassword` model (or similar). Unfortunately that's difficult to implement in a backwards-compatible manner :(

BTW I believe this issue affects `User.replaceById` (`PUT /api/users/:id`) too.

**Comment by bajtos** [comment]
As a workaround, I am recommending to use `User.prototype.updateAttributes`:

```js
const u = new User({email: 'loopback@example.org', password: '123'});
u.save(); // works
const u2 = User.findOne(); // in empty database, gets previous user
u2.updateAttributes({username: 'loopback'});
// or even
u2.updateAttribute('username', 'loopback');
```

**Comment by raulmt** [comment]
@bajtos I agree using `updateAttribute/s` is a workaround, but note that as  I pointed out in the initial comment, we would still need to fully override `verify` method as part of the workaround, since that method is also setting the object's property directly and then calling `save`.

I don't think we can check if the existing hash is the supplied one in an easy way, because the context of this is a before save hook, so the instance you receive there for an update scenario already has the new value (and you don't have access to the database one unless you add an additional query to the database I think). So what I was suggesting, at least as a momentary fix (considering that, as you said, a more correct solution would probably imply backwards-incompatible changes) is to use the same logic currently used in the [password setter](https://github.com/strongloop/loopback/blob/9fb67315f9b9af4ae5e61ecef479888a8a9002f9/common/models/user.js#L1065). So what I can send as PR is refactoring out that heuristic there so it can be reused in both the password setter and the "isPasswordChange" logic inside this before save hook. What do you say? I will try a PR with that later this week.

Regarding a more correct solution, you mentioned extracting password to a `UserPassword` model. I wanted to mention another approach, which is the one used by convention in the Rails world (also using bcrypt): they use `password` property only as a setter, and the underlying database property is a different one (`password_digest` in their case). So when you set `password`, they hash it to `password_digest` in a before save hook, and then only `password_digest` gets stored in the database. How that helps? Because now you can assume that if `password` has a value, it's always the new value you want to (after hashing) set in the database. Retrieved User objects from database would always have an undefined `password` attribute, and `password` setter would only be called when you want to set a new one, not when retrieving from database. But still, I think even this change wouldn't be fully backwards-compatible… I'm just mentioning as an alternative approach to a more definitive solution.

**Comment by bajtos** [comment]
> as I pointed out in the initial comment, we would still need to fully override verify method as part of the workaround, since that method is also setting the object's property directly and then calling save.

Good catch 👍 I missed this part in your initial comment.

> I don't think we can check if the existing hash is the supplied one in an easy way, because the context of this is a before save hook, so the instance you receive there for an update scenario already has the new value (and you don't have access to the database one unless you add an additional query to the database I think). 

We are already making the additional query in another "before save" hook - see [common/models/user.js#L1308](https://github.com/strongloop/loopback/blob/359a6a57626f489839c07249df4202226798b506/common/models/user.js#L1308). It probably makes sense to join these two functions into a single one, so that they can share the data fetched from the database.

> So what I was suggesting, at least as a momentary fix (considering that, as you said, a more correct solution would probably imply backwards-incompatible changes) is to use the same logic currently used in the password setter.

IMO, such solution will render `rejectPasswordChangesViaPatchOrReplace` useless. The purpose of this flag is to prevent attackers from changing user's password when all the attacker have is a valid access token. If we allowed hashed password values, then the attacker could calculate the hashed password locally and then send a PUT/PATCH request using the hash of the new password to change it.

> Regarding a more correct solution, you mentioned extracting password to a UserPassword model. I wanted to mention another approach, which is the one used by convention in the Rails world (also using bcrypt): they use password property only as a setter, and the underlying database property is a different one (password_digest in their case). So when you set password, they hash it to password_digest in a before save hook, and then only password_digest gets stored in the database. How that helps? Because now you can assume that if password has a value, it's always the new value you want to (after hashing) set in the database. Retrieved User objects from database would always have an undefined password attribute, and password setter would only be called when you want to set a new one, not when retrieving from database. But still, I think even this change wouldn't be fully backwards-compatible… I'm just mentioning as an alternative approach to a more definitive solution.

This is interesting. How are they preventing HTTP clients from getting and sending the raw password_digest value?

In LoopBack, we have two kinds of updates: a partial patch updating a subset of model properties, and a full replace changing the whole record. In order to make a full replace, the client has to provide *all* model properties. In case of a User model, they would have to include password/password_digest in the data too, which is not possible because they don't have the password value/digest for security reasons. Moving the password to a different model solves this problem, because then all User properties become public.

**Comment by raulmt** [comment]
> We are already making the additional query in another "before save" hook - see common/models/user.js#L1308. It probably makes sense to join these two functions into a single one, so that they can share the data fetched from the database.

I didn't see that one… yes, makes sense then… I didn't want to **add** a new fetching, but if there is already one there…

> IMO, such solution will render rejectPasswordChangesViaPatchOrReplace useless. The purpose of this flag is to prevent attackers from changing user's password when all the attacker have is a valid access token. If we allowed hashed password values, then the attacker could calculate the hashed password locally and then send a PUT/PATCH request using the hash of the new password to change it.

You are totally right, that was a big miss on my reasoning… we are forced to compare to existing value or somehow know if it's a different value or not.

> This is interesting. How are they preventing HTTP clients from getting and sending the raw password_digest value?

In Rails the check is not exactly at model level. As you mentioned, the idea of this check is to prevent attacks coming from HTTP requests from changing the password without proper access. Rails has a feature called "strong parameters", which works like this in summary: HTTP parameters are a special object instead of a plain hash, and you need to explicitly allow properties on that special object (white list) before passing them to the model (for a model update method call, for example). So theoretically, you could allow `password_digest` there, but that would be like consciously enabling a "please hack me" feature.

Taking some inspiration from Rails, they have another model level feature that's very useful in some cases, and I think it would help for this particular case and other cases in Loopback (like avoiding the data fetch inside `prepareForTokenInvalidation` for example): they track property changes. They store not only a "dirty flag" but also the previous value of a property, for example (you can [take a look here](http://api.rubyonrails.org/classes/ActiveModel/Dirty.html) for a quick overview).

Loopback (in datasource juggler) already has in place an elaborated way to work with properties, keeping the attributes inside `__data` property, exposing `$attributeName` to get/set from there and so leaving the `attributeName` as a getter/setter Object level defined property, which can be extended through `Model.setter/getter` attribute. So it should be possible to add at least a simple per-property dirty flag tracking on the setters side that would be reset in`save` callbacks, and exposing some kind of `isDirty(attrName)` method so features like `rejectPasswordChangesViaPatchOrReplace` and `prepareForTokenInvalidation` can use without the need to re-retrieve objects from datasource.

I'm not familiar with datasource-juggler (I just found about the existence of `setter` property xD) but I think this could be done in a backwards compatible way, right? Even if initially used only for this check, it shouldn't break other existing things that won't be aware of this attr change tracking. What do you think? If you find it a good idea, I could try to make a PR for datasource-juggler first instead (although that would take me a lot more time probably :S) and then fixing this reported bug would be a lot simpler and cleaner.

**Comment by bajtos** [comment]
@raulmt sorry for the delay. Your proposal is definitely interesting, however I am not able to tell how easy/difficult it would be to implement.

**Comment by mrbatista** [comment]
This issue is not stale!
I have problem with embedsOne/embedsMany relations with `User` model.
