### ISSUE TITLE
Relations is not shown in API explorer if model's datasource is null

### ISSUE THREAD

**Issue by shenghu** [strongloop/loopback#3397]
I want to know if this is by design. Here is an example for my question, https://github.com/shenghu/loopback-example-relations/tree/investigate-nest-remote

'Customer' model has many 'Order'. If you change 

```
  "Customer": {
    "dataSource": null,
    "public": true
  },
  "Order": {
    "dataSource": null,
    "public": true
  }
```
to be 
```
  "Customer": {
    "dataSource": "db",
    "public": true
  },
  "Order": {
    "dataSource": "db",
    "public": true
  }
```

/Customers/{id}/orders/ will show up in API explorer. Is it required that datasource must not be null for API explorer to show the nested model? 

Note that when I call `app.models.Customer.hasMany(app.models.Order);` in boot script, it failed w/ error 'app.models.Customer.hasMany is not a function'

As a background that I'm looking at this is that I need an integration application which uses underlying micro-services to persist data, which means Customer or Order needn't be persist in this integration app. So I thought I could set datasource to be null. Or I could set them to be memory db. But not sure which approach is better.

**Comment by jannyHou** [comment]
Relation methods like `model.hasMany` is mixin added to model.

RelationMixin will be added when DAOMixin gets added, see: https://github.com/strongloop/loopback-datasource-juggler/blob/b39ee050f339dd45efca37eed3fabcebc840a661/lib/dao.js#L3376

And DAOMixin is added to model in a datasource function, see: https://github.com/strongloop/loopback-datasource-juggler/blob/4f335cb06f7e2b7b31757d020b63a9df6b702d85/lib/datasource.js#L768

DAO is shorten for DataAccessObject, so only after you attach a model to a datasource, that datasource will setup your model's data access and mixin those CRUD and relation functions.

**Comment by shenghu** [comment]
@jannyHou thanks for explanation. I can understand how it is coded now. But I think it is not straightforward from API modeling perspective, i.e. the .json file defines model's properties and relations. No matter whether it is attached to data source or not, API explorer should be able to show how the model is designed.

**Comment by shenghu** [comment]
Any feedback from triage?

**Comment by amismailz** [comment]
+1 Same issue here
