### ISSUE TITLE
add change-stream for model relations

### ISSUE THREAD

**Issue by Freundschaft** [strongloop/loopback#3398]
Hello everybody,

I am trying to implement the following:

a user can have multiple shops, and each shop can have multiple orders.

now i want to subscribe to the change-stream of orders, which works perfectly fine if I subscribe to all orders via change-stream, but what I actually want to do is to have a change-stream only for the orders that are added/deleted for a specific shop.

Between Shop and orders I have a hasMany and belongsTo relation.

How can I realize what I want to achieve without writing lots of custom code?

**Comment by Freundschaft** [comment]
anyone got a response?

**Comment by kamal0808** [comment]
@Freundschaft were you able to make it work for yourself?
