### ISSUE TITLE
Relationship hasAndBelongsToMany requires junction table to have `id` column

### ISSUE THREAD

**Issue by bdharrington7** [strongloop/loopback#3402]
Loopback version:
```
$ lb --version
2.4.0 (generator-loopback@3.6.0 loopback-workspace@3.40.1)
```

I created a HABTM relationship between two models, `module` and `component`, with PostgreSQL as a data store. I specified the junction table manually since the automatically generated one wasn't descriptive enough for this table. Because this junction table is a junction table for more than one table, it can have several rows that would look like duplicates when looking only at two columns:

| moduleid | componentid |
|----------|---------------|
| 1   | 1 |
| 1 | 1 |
| 1 | 2 |
| 1 | 2 |

```
{
  "name": "Module",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
...
  "relations": {
    "components": {
      "type": "hasAndBelongsToMany",
      "model": "Component",
      "throughTable": "component_junction2"
    }
  },

=======================
{
  "name": "Component",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
.....
  "relations": {
    "modules": {
      "type": "hasAndBelongsToMany",
      "model": "Module",
      "throughTable": "component_junction2"
    }
  },
```

When I was trying this out, the junction table didn't have an explicit `id` column, because if you're using the combinations of the foreign keys as a primary key, it's not really necessary to have a surrogate primary. When trying to get models from a relationship like `GET /api/Modules/1/components`, I would get the error: 

```
Unhandled error for request GET /api/Modules/1/components: error: column "id" does not exist
    at Connection.parseE (/Users/brian/bbs/dri/node_modules/pg/lib/connection.js:569:11)
    at Connection.parseMessage (/Users/brian/bbs/dri/node_modules/pg/lib/connection.js:396:17)
```
I eventually figured out that if I add a surrogate PK to the junction table, this error would not happen and I would get the results I was expecting.

Is this expected behavior, or is it something left over from maybe the `hasManyThrough` relationship?

**Comment by proreact-mj** [comment]
This is correct behaviour

If set the idInjection to true, then it will add the id field automatically. You can set it manually, but it is required for your situation. 

if you want to have duplicate moduleid/componentid id pairs in the relation table, then you need a 3rd property as ID, as the row needs a unique id (DB fundamentals for most db types) and cannot use the FKs as a composite ID if you want to allow one specific module to relate to one specific component more than once.
