### ISSUE TITLE
Can the API handle depths > 2?

### ISSUE THREAD

**Issue by bdharrington7** [strongloop/loopback#3406]
When you create a relationship between models, you can get an API generated that allows you to get models 2 levels deep:

`GET /api/Wigets/1/modules/234`

Can you return model objects to go even further?

`GET /api/Wigets/1/modules/234/instances/567/pieces` etc...

**Comment by padelagani** [comment]
@bdharrington7 

Check this if it helps you - https://loopback.io/doc/en/lb3/Nested-queries.html

**Comment by bdharrington7** [comment]
Thanks, that helps. Unfortunately it seems the level is capped at 3.
