### ISSUE TITLE
Replace the built-in ORM with another package

### ISSUE THREAD

**Issue by jeff3yan** [strongloop/loopback#3407]
I've been working around the limitations for loopback when attempting to query based on related model properties (e.g. **Customer** belongsTo **City** belongsTo **Country**, then trying to query all customers in "Portland").

This issue has been brought up in #517, #683 and many others. However, I'm not sure what the status is on any recommended workarounds besides writing native SQL.

To that point it would be convenient if I could replace the loopback ORM with another package (maybe objection.js or something backed by knex.js) which can filter on related properties.

There was this [question](http://stackoverflow.com/questions/35187931/how-to-use-loopback-datasource-connector-as-knex-js-connection) relating to providing the loopback datasource connection to use in knex, but it didn't get anywhere.

Is there any way I could incrementally remove the reliance on the built-in ORM and replace it with something else?

**Comment by bajtos** [comment]
My recommendation is to use plain models (based on `Model`, not `PersistedModel`) as controllers, and then implement any data-access methods as custom model (controller) methods backed by whatever ORM you prefer.

```js
// common/models/CustomerController.json
{
  "name": "CustomerController",
  "base": "Model",
  "methods": {
    "find": {
      "accepts": // ...
      "returns": // ...
    }
  }
}

// common/models/CustomerController.js
module.exports = function(CustomerController) {
  CustomerController.find = function(...) {
    return knex(...);
  };
}
```

We are working on making Controllers a first-class concept in https://github.com/strongloop/loopback-next.
