### ISSUE TITLE
Querying associated model exists or not

### ISSUE THREAD

**Issue by fanttm** [strongloop/loopback#3408]
I have read #1744, I know that
```
m1.m2s({
  include: [
    {
      relation: 'm3s',
      scope: {
        where: {
          someCondition: something
        }
      }
    }
  ]
})
```
This returns all m2s and includes m3s with matching condition which is perfect. And maybe some m2s has no m3s.

Then I want to get m2s that has at least 1 m3s, How can I do about it?

**Comment by padelagani** [comment]
@fanttm 

It is not currently supported in loopback, you can use *native query* if you want.
