### ISSUE TITLE
Module ./connectors/mongodb not found, will try another candidate.

### ISSUE THREAD

**Issue by birbird** [strongloop/loopback#3412]
Hi All

I try to set up mongodb datasource, the API works, but the data is not saved into mongodb.
I `set DEBUG=loopback:datasource`, then found this error 
`Module ./connectors/mongodb not found, will try another candidate.`
in log
Then I tried https://github.com/strongloop/loopback-connector-mongodb, the same problem.

Loopback 3
Windows 10
Mongodb 3.4

How can I fix it? Any help will be highly appreciated.

**Comment by dhmlau** [comment]
One thing to check is in the `server` folder:
- `datasources.json`: the information you put there can actually connect to your mongodb
- `model-config.json`: the model you're trying to persist has the right `datasource` attribute name.

**Comment by dhmlau** [comment]
Hi @birbird , any updates?

**Comment by dhmlau** [comment]
Due to inactivity, closing this issue.  Feel free to reopen it if you still encounter this issue.  Thanks.
