### ISSUE TITLE
How to use multiple custom Role Model

### ISSUE THREAD

**Issue by lynkxyz** [strongloop/loopback#3413]
I want to use two model inherited from Role model, ex: 
- MyRole1
- MyRole2
But when I config the acls, these Role seem not working. I also tried to add the built-in Role model and create some role with it but the acls still not working. 
Role model work perfectly when I change the base model of MyRole1 and MyRole2 to PersitedModel (not inheritate anymore).

So my question is if I want to use a subclass of role, how do I config the acls.

**Comment by imtosss123** [comment]
same question

**Comment by trinhvanhuy** [comment]
I have same prob too, any solution ?

**Comment by naumanahmad17** [comment]
@trinhvanhuy  @imtosss123  any solutions...
