### ISSUE TITLE
access_token null on custom middleware

### ISSUE THREAD

**Issue by mahdinai** [strongloop/loopback#3416]
hi 

server.js file:
```
app.use(cookieParser('secret'));
app.use(loopback.token({
  model: app.models.accessToken,
  cookies: ['access_token']
}));
```

custom middleware:

```
'use strict';
var user = require('../../common/proxies/UserProxy');

module.exports = status;
function status() {
  return function(req, res,next) {
    

    if (req.accessToken) { // access token is null 
      
      user.getProfile(req.accessToken.userId, function (user_res) {
        if (user_res.result) {
          next();

        }else{

          req.app.locals.msg = {
            hasMessage: true,
            Message: "",
            messageTitle: "",
            alertClassName: "alert-danger",
            app: req.app
          };

          res.redirect('/user/login');
        }
      });
  }else {

      req.app.locals.msg = {
        hasMessage: true,
        Message: "",
        messageTitle: "",
        alertClassName: "alert-danger",
        app: req.app
      };

      res.redirect('/user/login');

    }
  }


}
```
accesstoken is null in middleware , but work on route :(((

**Comment by yshing** [comment]
Please Check the doc here ..
https://docs.strongloop.com/display/public/LB/Defining+middleware

**Comment by ydomenjoud** [comment]
actually this is an excellent question : how to get current user in custom middleware ?

req.accessToken is always undefined

**Comment by bitmage** [comment]
In Loopback, there's not 1 kind of middleware, [there's about 5](https://github.com/strongloop/loopback/pull/3048#issuecomment-306671083).  So you have to sort out what order they all run in and how they interact.  Personally I dodged this complexity by [wedging my own strategy in](https://github.com/strongloop/loopback/issues/3434).  Not ideal, but at least I can reason about the order things run in.
