### ISSUE TITLE
user.changePassword(old, new, cb) deletes current accessToken

### ISSUE THREAD

**Issue by safwen1** [strongloop/loopback#3417]
Using the method should delete all the user's accessTokens except the one used to change the password.

@bajtos

**Comment by bajtos** [comment]
@safwen1 thank you for reporting the issue. How are you invoking the `changePassword` method?

 - when invoked via REST, the current access token should be injected automatically
 - when invoked from JavaScript, you have to provide the current access token via `options.accessToken`

Could you please create a small app reproducing the issue per our [bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)?

**Comment by safwen1** [comment]
This is the code for my remote method, including the workaround I used to create a new accessToken and return it as an answer.

`Appuser.prototype.updateClientPassword = function (data, options, cb) {`
    `var appuser = this;`
  ` appuser.changePassword(data.oldPassword , data.password , function (err) {`
     `if(err){`
       `console.error(err);`
       `cb(err);`
     `}else {`
       `Appuser.app.models.AccessToken.create({ 'created':Date.now() , 'userId' : appuser.id} , function (err , accessToken) {`
            `if(err){`
             ` console.error(err);`
             ` cb(err);`
            `} else {`
              `cb(null,accessToken);`
            `}`
        ` });`
    ` }`
   `})`
 ` }`

**Comment by bajtos** [comment]
Assuming that `updateClientPassword` was called via REST, or the caller has included `accessToken` in the options, then your code can be fixed as follows:

```js
Appuser.prototype.updateClientPassword = function (data, options, cb) {
  this.changePassword(data.oldPassword, data.password, options, cb);
}
```

**Comment by safwen1** [comment]
Correct ! That solved it however it is not evident from the documentation [http://apidocs.strongloop.com/loopback/#user-changepassword](url) 
that the unrequired "options" parameter is referring to the context options (The description field is empty). 

Thank you for the help @bajtos I appreciate it.

**Comment by bajtos** [comment]
> it is not evident from the documentation http://apidocs.strongloop.com/loopback/#user-changepassword
that the unrequired "options" parameter is referring to the context options (The description field is empty).

Good catch! Would you mind contributing a patch to improve this part of our API docs? Here is the line to change: [common/models/user.js#L390](https://github.com/strongloop/loopback/blob/f8db64c9c32b710b66b13f0514bbeb60129a2809/common/models/user.js#L390) and instructions for new contributors: http://loopback.io/doc/en/contrib/code-contrib.html

**Comment by safwen1** [comment]
I'm sorry I am a beginner and I have never used versionning techniques so I wouldn't know how to contribute . I suggest the description should be "The context options object used to identify the current accessToken".

**Comment by ahammad** [comment]
@bajtos I realize that this is an old thread but I just ran into the same issue. I would appreciate some input.

Here is what I have:
```
  app.post("/admin/submit-change-password", tokenVerifier, function(req, res) {
    var options = {};
    var token = req.cookie.access_token;
    var userId = req.cookie.userId;
    var data = req.body;

    AppUser.changePassword(userId, data.oldPassword, data.newPassword, function(err) {
      if(err){
        logger.error(err);
      }
      res.redirect("/");
    })
  });```

I don't know how to pass the options. I tried defining a variable in this function called "options" as follows:

```options.accessToken = token;```

But that resulted in a stack trace:

```'TypeError: Cannot use \'in\' operator to search for \'id\' in <the access token was here>',
     '    at Function.User._invalidateAccessTokensOfUsers (/Users/ahmedhammad/code/test/node_modules/loopback/common/models/user.js:1036:40)',```

Thanks

**Comment by bajtos** [comment]
@ahammad Please open a new issue and provide a small application reproducing the problem - see https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report. I don't have bandwidth to create such app myself, and without an app reproducing the problem I cannot investigate.

**Comment by ahammad** [comment]
Thanks for the response @bajtos 

I can do that in the next few days. For my issue however, do you know what the "options" parameter is supposed to look like? I was not able to find any examples of "options" anywhere. I think fundamentally, my use of "options" is flawed.

**Comment by bajtos** [comment]
There may be places expecting other access token properties to be present too, e.g. `options.accessToken.userId`. Please see this page for more information about the `options` object and how we are using it for context propagation: https://loopback.io/doc/en/lb3/Using-current-context.html

AFAICT, your `/admin/submit-change-password` is not verifying whether the access token submitted by the user is still valid. I think this may open a security vulnerability.

My recommendation is to configure `loopback#token` middleware to parse & validate the access token, see http://loopback.io/doc/en/lb3/Making-authenticated-requests.html. This middleware stores the access token object on `req.accessToken`, this is the place where the rest of LoopBack is getting that token from. It is possible to configure the token middleware to parse the token from cookies too, see https://github.com/strongloop/loopback/blob/eb3301abf23527f9f051b682600ce808ae5d828b/server/middleware/token.js#L58-L80

As for documentation, I think the page "Making authenticated requests" is missing information on how to setup cookie-based authentication, such instructions would be a good addition/contribution.

**Comment by ahammad** [comment]
Thanks for that response and the links @bajtos !

My `/admin/submit-change-password` route also has a middleware called `tokenVerifier` which does check for validity of the token using the AccessToken resolve function:

`  var AccessToken = app.models.AccessToken;
  var token = req.signedCookies.access_token;
  var userId = req.signedCookies.userId;
  var adminPath = req.path == "/admin" || req.path == "/admin/";

  AccessToken.resolve(token, function (err, accessToken) {<some page redirect logic>}`

For cookie-based authentication, you are absolutely right, I found no official documentation on it. Everything I found was collected from pages like this or Stackoverflow. I'd love to contribute to that because I am sure others will have similar issues. I just don't know for sure if my approach was correct.

How do I submit a pull request to the official documentation?

**Comment by bajtos** [comment]
> My /admin/submit-change-password route also has a middleware called tokenVerifier which does check for validity of the token using the AccessToken resolve function:

Fair enough 👍 

I still think you would be better of by leveraging the built-in token middleware from LoopBack and then simplifying your token verifier to only check whether `req.accessToken` was filled by `loopback#token`. 

> How do I submit a pull request to the official documentation?

Ah, sorry, I forgot to include the link in my previous comment. Here you go: http://loopback.io/doc/en/contrib/doc-contrib.html

**Comment by juanvillegas** [comment]
Slightly unrelated topic, but how can I keep the session alive after the user changes the password? I have tried the _logoutSessionsOnSensitiveChanges_ option but seems deprecated in Loopback 3.

**Comment by bajtos** [comment]
> how can I keep the session alive after the user changes the password

The code calling `User.changePassword` must provide the current access token in option. The code invalidating sessions will skip the session bound to the provided access token.
