### ISSUE TITLE
API documentation bug: Base Model Class properties

### ISSUE THREAD

**Issue by bpgower** [strongloop/loopback#3420]
At this doc URL:
https://apidocs.strongloop.com/loopback/#model

Scroll down to the class properties table.  The last entry has the formatting messed up.  It should have "settings.acls" under the 'Name' column, "[{string}]" under the 'Type' column and have "Array of ACLs for the model." under the 'Description' column.

![image](https://cloud.githubusercontent.com/assets/28904597/26369947/405a27a6-3fc4-11e7-8dd5-41282c53865e.png)

**Comment by bpgower** [comment]
Found the line in question:  https://github.com/strongloop/loopback/blob/master/lib/model.js#L105
is currently:
   * @property [{string}] settings.acls Array of ACLs for the model.

should probably be:
   * @property {String[]} settings.acls Array of ACLs for the model.

**Comment by 0candy** [comment]
PR merged. Closing issue.
