### ISSUE TITLE
New loopback-cli command: update/migrate the database

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#3422]
As a follow-up to the discussion in https://github.com/strongloop/loopback/issues/3395, we should implement a new loopback-cli command that will allow users to auto-update their databases and more importantly, to print (SQL) scripts needed to perform auto-update, so that users can run these scripts themselves.

Related reading: https://www.martinfowler.com/articles/evodb.html#AllDatabaseChangesAreMigrations

A possible implementation:

```
$ lb autoupdate db --dry
ALTER TABLE AccessTokens
ADD COLUMN scopes VARCHAR(255);
```

**Comment by shaheero** [comment]
Another column is needed if you follow the steps in the [docs](http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#preparing-access-control-models)
"principalType" with type VARCHAR and length 255

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be adding any new features.
