### ISSUE TITLE
Docs for PersistedModel.update?

### ISSUE THREAD

**Issue by jcolemorrison** [strongloop/loopback#3423]
There aren't currently any Docs on `PersistedModel.update` - unless I'm missing it somewhere.  I've been using it, but it'd be nice for it to be known with any nuances.  Is it just an alias for `updateAll`?

**Comment by 0candy** [comment]
Yes, it is an alias for `updateAll`.
https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L349-L352

Looks like there is only api docs for `updateAll`
http://apidocs.strongloop.com/loopback/#persistedmodel-updateall
