### ISSUE TITLE
Permissions vs. REST find/list - not applied?

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#343]
As far as I can see `enableAuth / Model.checkAccess` doesn't prevent an instance from being listed. In other words, (array) output is not filtered based on the current permissions, and thus exposes data without restrictions.

Of course there will be quite some performance impact, performing (async) checkAccess calls on the results to be returned, but Loopback should be secure by default. One should be able to at least enable/disable this kind of filtering easily.

In general it should be possible to quickly do a security audit and see all the exposed resources at a glance - currently it's easy to miss any unintentionally exposed api endpoints, as it's not clear what the Loopback default behavior actually is.

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be adding any new features.
