### ISSUE TITLE
Error in simple project

### ISSUE THREAD

**Issue by GehadElkot** [strongloop/loopback#3430]
Questions:
i built cofeeshop module as shown in this tutorial http://loopback.io/doc/en/lb3/Use-API-Explorer.html and when i click on [try it out] i found this results: 
Response Body
{
  "error": {
    "statusCode": 422,
    "name": "ValidationError",
    "message": "The `cofeeshop` instance is not valid. Details: `id` can't be set (value: 0).",
    "details": {
      "context": "cofeeshop",
      "codes": {
        "id": [
          "absence"
        ]
      },
      "messages": {
        "id": [
          "can't be set"
        ]
      }
    },
    "stack": "ValidationError: The `cofeeshop` instance is not valid. Details: `id` can't be set (value: 0).\n    at C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:355:12\n    at ModelConstructor.<anonymous> (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:528:11)\n    at ModelConstructor.next (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\hooks.js:93:12)\n    at ModelConstructor.<anonymous> (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:525:23)\n    at ModelConstructor.trigger (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\hooks.js:83:12)\n    at ModelConstructor.Validatable.isValid (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:491:8)\n    at C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:351:9\n    at doNotify (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:99:49)\n    at doNotify (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:99:49)\n    at doNotify (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:99:49)\n    at doNotify (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:99:49)\n    at Function.ObserverMixin._notifyBaseObservers (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:122:5)\n    at Function.ObserverMixin.notifyObserversOf (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:97:8)\n    at Function.ObserverMixin._notifyBaseObservers (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:120:15)\n    at Function.ObserverMixin.notifyObserversOf (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:97:8)\n    at Function.ObserverMixin._notifyBaseObservers (C:\\Users\\omar elkot\\Desktop\\2nd course\\hello-loopback\\loop\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:120:15)"
  }
}

Response Code
422
Response Headers
{
  "date": "Sat, 03 Jun 2017 12:22:32 GMT",
  "content-encoding": "gzip",
  "x-content-type-options": "nosniff",
  "x-download-options": "noopen",
  "x-frame-options": "DENY",
  "content-type": "application/json; charset=utf-8",
  "access-control-allow-origin": "http://localhost:3000",
  "transfer-encoding": "chunked",
  "connection": "keep-alive",
  "access-control-allow-credentials": "true",
  "vary": "Origin, Accept-Encoding",
  "x-xss-protection": "1; mode=block"
}

**Comment by 0candy** [comment]
Which API did you click Try it out for? Do you have a datasource configured or just using the memory connector?

**Comment by dhmlau** [comment]
@GehadElkot, are you still encountering this problem?  If so, could you please provide more details as @0candy requested?  Thanks!

**Comment by dhmlau** [comment]
Due to inactivity, I'm closing this issue.  Feel free to reopen if the issue still exists.  Thanks.

**Comment by GehadElkot** [comment]
i solved it , thanks alot .

2017-07-27 5:12 GMT+02:00 Diana Lau <notifications@github.com>:
