### ISSUE TITLE
User Acl not working

### ISSUE THREAD

**Issue by n1c01a5** [strongloop/loopback#3432]
I have created a new model `user` to extends `User` : 
`server/model-config.json` :
```
  "user": {
    "dataSource": "db",
    "model": "User",
    "public": true
  }
```
And I have changed the acl in `users.json`.
```
{
  "name": "user",
  "base": "User",
  "idInjection": true,
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
```
But any user can add a user. I would only admin can CRUD the user model.

Any idea?

**Comment by togvet** [comment]
You need to explicitly deny the 'create' action of the user with another ACL. See this topic:
[https://github.com/strongloop/loopback/issues/1340](url)
