### ISSUE TITLE
Request Timeout and mem leak with through relation GET with filter

### ISSUE THREAD

**Issue by joeybenenati** [strongloop/loopback#3435]
# Description/Steps to reproduce

Not sure if this is more of a datasource-juggler issue or not...
`"loopback": "3.8.0"`
`"loopback-datasource-juggler": "3.9.1"`

I have a hasManyThrough relation between User, ListMembership, and List models. User has many Lists through ListMembership (and vice versa). In some cases, depending on the given `where` filter (particularly with `inq` operator), the `GET /users/{id}/lists` endpoint times out and triggers a memory leak which quickly overloads the server rendering it unresponsive. this is the behavior i'm getting for different filter values. (I have been able to consistently reproduce this behavior with multiple sets of hasManyThrough relations)
```
no filter // success
{"where":{"id":{"inq":[]}}} // req timeout & mem leak
{"where":{"id":{"inq":[${non-existing or non-related listId}]}}} // req timeout & mem leak
{"where":{"id":{"inq":[${related listId}]}}} // success
{"where":{"id":{"inq":[${related listId}, ${non-existing or non-related listId}]}}} // success
{"where":{"id":{"inq":[${non-existing or non-related listId}, ${related listId}]}}} // success
```
So essentially, if the `inq` array of ids doesn't contain a listId for which a relation exists, the bug is produced.

I have since rolled back to loopback v3.6.0 / datasource-juggler v3.4.1 and the query works as expected.

# Expected result

# Additional information

darwin x64 7.2.1

├── loopback@3.8.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@4.0.0
├── loopback-component-oauth2@3.0.0
├── loopback-component-passport@3.3.0
├── loopback-connector-mysql@2.4.1
├── loopback-connector-postgresql@2.7.0
├── loopback-console@1.1.0
├── loopback-datasource-juggler@3.9.1
├── loopback-ds-timestamp-mixin@3.4.1
├── loopback-softdelete-mixin4@1.0.0

**Comment by jannyHou** [comment]
@joeybenenati Could you provide a sandbox repo according to this [procudure](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report) for bug reproduce?
I followed your steps but could not reproduce the error. I use the same `loopback@3.8.0` and `loopback-datasource-juggler@3.9.1` version as you.

And recently there is a fix for similar bug been released in juggler@3.9.2, see: https://github.com/strongloop/loopback-datasource-juggler/issues/1381, can you also try if that solves your problem? Thanks.
