### ISSUE TITLE
Loopback app won't boot if dependencies installed with NPM 5.0.3

### ISSUE THREAD

**Issue by daankets** [strongloop/loopback#3438]
# Description/Steps to reproduce
Install the latest version of NPM 5, and install your app dependencies using npm install.
Then start the application using `NODE_ENV=development node ./server/server.js`

# Expected result
The application starts and accepts incoming connections.

# Real result:
The application fails the boot fase: loopback-boot uses the semver library to check version of the installed loopback dependency. This version is no longer in the expected format when using npm 5:

`https://registry.npmjs.org/loopback/-/loopback-2.38.3.tgz` instead of just `2.38.3`.

**Comment by Setogit** [comment]
@daankets
Does the manual install work for you with npm 5.0.3 on node 8.0.0?
```
npm install https://registry.npmjs.org/loopback/-/loopback-2.38.3.tgz
```

**Comment by Setogit** [comment]
Please submit a new issue if needed.  closing  one month or older issues.  thanks!
