### ISSUE TITLE
Oracle db not generating auto id , if i give my column id:true

### ISSUE THREAD

**Issue by lokeshjain20** [strongloop/loopback#3440]
Oracle db not generating auto id if i give a column with name id(or any other name),type : string and id : true If I don't give any column with id:true , then it by default creates id column with type number and auto generates the id , but if i make any column as id:true with type change to string it do not generate id , and gives "Cannot insert null into table.column id"

**Comment by Setogit** [comment]
@lokeshjain20 When you got the error message `Cannot insert null into table.column id`, did you not only define your own `id` (primary key) but also assign some value to the `id` when you create a model?

**Comment by lokeshjain20** [comment]
while creating the model  , i do not assign any value to id column , as i expect oracle to generate it , but if id column is number it only then autogenerates the id

**Comment by Setogit** [comment]
@lokeshjain20  If you define the column with `id : true`,  you will need to explicitly assign some value to the column.

If you do not define any columns with `id : true`, the connector will define a primary key with the name `id`for you.  In creating a model in such a case, an auto-generated value will be used.

**Comment by Setogit** [comment]
Please submit a new issue if needed.  closing  one month or older issues.  thanks!
