### ISSUE TITLE
Loopback API is freezed

### ISSUE THREAD

**Issue by masalinas** [strongloop/loopback#3454]
# Description/Steps to reproduce
Sudenly all the loopback API for our production app not response to any request. We always obtain this error: 
     no response from serve 

If open the explorer and fire a simple GET from any model the system spend a minute to resolve and obtainthe previous error:
     no response from serve 

The system is under Bluemix Docker with 4 Gb and many hardisk. The problem is not from CPU, RAM or harddisk.

# Expected result

# Additional information

node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 4.7.2

npm ls --prod --depth 0 | grep loopback
anything

this is the version used in loopback from package.json:
 "loopback": "2.36.0",
    "loopback-boot": "2.23.0",
    "loopback-component-explorer": "2.7.0",
    "loopback-connector-mongodb": "1.15.2",
    "loopback-context": "1.0.0",
    "loopback-datasource-juggler": "2.51.0",
    "loopback-ssl": "0.0.9",
    "loopback-storage-service": "^1.0.4",

**Comment by manojchandrashekar** [comment]
I don't think the information you have provided is enough to guess what might be wrong. Is it possible for you to clone the application to a local machine and run it with:

```
export DEBUG=loopback:*
export NODE_ENV=development
node .
```

You will find errors on the console (if any) when you hit the API.
