### ISSUE TITLE
how do I get to know which datasource is attached to my model?

### ISSUE THREAD

**Issue by lokeshjain20** [strongloop/loopback#3459]
I am creating dynamic models in my application , and i  have more than one datasources in it , what i want is to know at run time that which model is attached to which datasource? is there any way to do it?there must be some property which mentions the name of datasource json attached to the model?

**Comment by manojchandrashekar** [comment]
Try:

```
module.exports = function(Model) {
  console.log(Model.dataSource.name);
};
```

**Comment by dhmlau** [comment]
@lokeshjain20, I believe @manojchandrashekar has answered your question.  Closing it now.
