### ISSUE TITLE
Related model shared = false vs. REST exposure

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#346]
It seems that `Model.setup` doesn't take into account when a model is not shared - the REST API endpoints are created regardless. Also, setting the generated relation method to shared = false has no effect (this is the method outlined in the docs):

```
Project.prototype['__create__history'].shared = false;
```

**Comment by bajtos** [comment]
> How would you recommend 'registering' models, so they're available from app.loopback.getModel(), yet are not exposed? I find myself using getModel in a few places, even for 'embedded' models, and I like being able to have a unified way to reach them vs. using app.models[modelName] directly.

One can set `shared: false` in `server/model-config.json` to have the model available via `app.models.MyModel` and `app.registry.getModel('MyModel')` without exposing the model via the REST API.

Here is an example of creating such model programatically:

```js
var MyModel = app.registry.createModel({ /* model definition */ });
app.model(MyModel, { public: false });
```

> Being able to selectively remove methods from REST exposure would certainly be helpful.

You can use `disableRemoteMethod` for that, see the [docs](https://docs.strongloop.com/display/LB/Exposing+models+over+REST#ExposingmodelsoverREST-HidingmethodsandRESTendpoints).

Example:

```js
var isStatic = true;
MyModel.disableRemoteMethod('deleteById', isStatic);
```

@fabien I hope that I have answered your questions, I am closing this issue. Please open a new issue if you have any more questions.
