### ISSUE TITLE
ACL is not working when calling api internally ?

### ISSUE THREAD

**Issue by fanttm** [strongloop/loopback#3463]
# Description/Steps to reproduce

I set ACL to controll access to "Listing.update_stock" by $owner.

When I call from remote without token, for example, curl http://xxx.xxx.xxx.xxx/api/listings/update_stock, it will be blocked by error authorization.

But when I call this api internally, for example, in this no need authorization api function:
```
Listing.find(xxx, function(err, lst) {
    // This call is no need authorization
    Listing.update_stock(xxxx)
})
```

If I want to make this internal api call being authorized, how can I do about it ?

**Comment by padelagani** [comment]
@fanttm ACL is for rest api calls, what is need of ACL for internal call at server ?
