### ISSUE TITLE
apply mixin to models dynamically

### ISSUE THREAD

**Issue by lokeshjain20** [strongloop/loopback#3465]
I want to apply a mixin to my models including built in models dynamically , i.e in some boot script , right now I am using modelname.mixin('<mixinName>') . This method only works if I have applied mixin property in any one of my model , but doesn't work if no model is given mixin property in model.json file.

How to resolve it?

**Comment by padelagani** [comment]
Initialize mixin in server.js file

```
require(mixin)(app)
```

**Comment by lokeshjain20** [comment]
hi @padelagani  I did not get you should I give path to mixin where you have mentioned mixin and waht should i give in app, and should i require it in a variable?

**Comment by padelagani** [comment]
@lokeshjain20 Keep that line in server.js after - var app = loopback()

```
var app = loopback()
require(mixin)(app)
```

**Comment by lokeshjain20** [comment]
@padelagani  doing this gives me error - "mixin is not defined".

**Comment by ganipadela** [comment]
In mixin define your mixin name if it is from npm module else give path of that mixin

**Comment by lokeshjain20** [comment]
giving path name , does not give any error , but still mixin does not get applied to my models , when I am doing model.mixin('mixinName') , in my boot script.

**Comment by lokeshjain20** [comment]
i got it working finally , instead of model.mixin ,  var mixin = "/path of mixin"; and then require(mixin)(<modelName>);

@padelagani  thank you for help , can you please explain what this line :require(mixin)(app/model) actualy does? Till now I have only used require with file path or module name  , but never gave two brackets after require , what does it do?

**Comment by padelagani** [comment]
@lokeshjain20  It passes loopback app instance to that mixin. 

() because that module might be function module so to initialize that we need to call in that way.

When module.exports, exports a function then we call in that way.

**Comment by padelagani** [comment]
@lokeshjain20  Can you close this issue or mark is at done
