### ISSUE TITLE
Handle calculated/transformed properties such as password upon 'read/write`

### ISSUE THREAD

**Issue by rashmihunt** [strongloop/loopback#3468]
As per @raymondfeng "In general, we need to have a better way to handle calculated/transformed properties such as password upon 'read/write`. I guess we should open an issue for the broader feature." Further details for this feature is in https://github.com/strongloop/loopback/issues/251

**Comment by JameyG-Unit** [comment]
Will this be included as a 3.x update or in LoopBack 4? (In particular with reference to issue #251). It's really made using LoopBack quite a big pain for our project development.

**Comment by bajtos** [comment]
So far, LoopBack 4 is using existing loopback-datasource-juggler for the ORM/persistence part. If things stay this way, then the changes described in this issue may become available in both 3.x and 4.x.  Having said that, I am not sure what are the plans for implementing this issue, I don't think it's on our near-term roadmap (@kjdelisle please correct me if I am wrong).
