### ISSUE TITLE
[security bug] where with undefined

### ISSUE THREAD

**Issue by sbechet** [strongloop/loopback#3469]
```
app.models.Application.find({ where: { url: undefined } }, function(err, service) { console.log(service); });
```

Always return an Application model entry?

**Comment by raymondfeng** [comment]
See https://github.com/strongloop/loopback/issues/637

> A patch to this has been released in loopback-datasource-juggler@v2.41.0 you can use it by adding normalizeUndefinedInQuery setting to your datasource config or model config (see tests for more detail). Options are:
- "nullify" which converts undefined to null
- "throw" which throws an error Unexpected```undefined```in query
- "ignore" which strips the undefined key (default function)
