### ISSUE TITLE
Setting Up environment specific configuration

### ISSUE THREAD

**Issue by dhruv004** [strongloop/loopback#3470]
# Description/Steps to reproduce

Hi can I get some help with setting environment specific configuration.
I have two files for datasource
-server/datasource.json
-server/datasource.test.json

I use the script "SET NODE_ENV=test && mocha test/*/.test.js" to run my test cases and set the node environment to test.
Loopback does not load server/datasource.test.json instead the datasource from server/datasource.json is loaded.

# Expected result
Loopback should load the environment specific config file.
Please check this [Github Repo](https://github.com/dhruv004/sample-loopback-example) for sample code.From the code If you run npm run test It loads data from local.json which is the data source for development environment.It should load data from test.json(datasource for test environment)

# Additional information
I have confirmend the environment using process.env.NODE_ENV which logs "test"
I have tried to change server/datasource.json to server/datasource.local.json, But then I get an error
WARNING: Main config file "datasources.json" is missing.
I dont understand what I am doing wrong.Am I supposed to create all the config files for the test environment like *.test.json.

Or is there a different config file where I have to define envrionment specific files.

node -e 'console.log(process.platform,process.arch,process.versions.node)'
win32 x64 6.10.3

npm ls --prod --depth 0 | grep loopback
+-- loopback@3.8.0
+-- loopback-boot@2.25.0
+-- loopback-component-explorer@4.2.0
+-- loopback-connector-mongodb@1.18.1

**Comment by bencallaway** [comment]
@dhruv004 did you find a solution for your `datasources.test.json` issue?

**Comment by dhruv004** [comment]
@bencallaway yes actually the script I was running was wrong `SET NODE_ENV=test && mocha test/*/.test.js`.Instead I had to run `SET NODE_ENV=test&& mocha test/*/.test.js`.Notice the space between test and &&
