### ISSUE TITLE
new CustomModel based on access-token model with different primary key.

### ISSUE THREAD

**Issue by z106a** [strongloop/loopback#3472]
# Description/Steps to reproduce

if create CustomModel based on AccessToken and set field "pk" as id field like this:
{
  "name": "CustomModel",
  "plural": "accessTokens",
  "base": "AccessToken",
  "idInjection": true,
  properties": {
    "pk": {
      "type": "string",
      "id": true
    }
  },
then when user try to login, in function that creates new Token receive err: 

In access-token.js :
AccessToken.createAccessTokenId(function(err, id) {
      if (err) return next(err);
      ctx.instance.id = id;
      next();
    });
  });
# Expected result
ctx.instance.pk - in ctx.

node_modules/loopback/common/models/access-token.js:76
      ctx.instance.id = id;
                      ^
TypeError: Cannot set property id of #<ModelConstructor> which has only a getter
# Additional information

darwin x64 8.1.2
├── loopback@3.8.0
├── loopback-boot@2.25.0
├── loopback-component-explorer@4.2.0
├── loopback-component-passport@3.3.0
├── loopback-connector-mongodb@1.18.1
├── loopback-graphql-relay@0.9.3

**Comment by elimcjah** [comment]
How did you resolve this issue?

**Comment by z106a** [comment]
I haven't remembered already.  Think, just remove pk field and use id field as default. Sorry. (

**Comment by eliaskibret** [comment]
how access token work
