### ISSUE TITLE
Error: Items must be an array: {}\n at new List 

### ISSUE THREAD

**Issue by sarankani** [strongloop/loopback#3475]
Hi,

I created a products model and tring to get data through api. I got records in some where query.
![success - lp-explorer-products-get-c_id 1](https://user-images.githubusercontent.com/113065/27868245-ca9906d2-61b9-11e7-8a31-92043b350a36.jpg)

In sometimes i got error refer my error screen shot 
![error - lp-explorer-products-get-c_id 2](https://user-images.githubusercontent.com/113065/27868256-d2863f54-61b9-11e7-8aa9-5b4b5372ef92.jpg)

Check my Mongo DB Data
![mongodb-screenshot](https://user-images.githubusercontent.com/113065/27868268-d8f41ce4-61b9-11e7-8cb5-dd48c6d19cf5.jpg)

#My error 
{
  "error": {
    "statusCode": 400,
    "name": "Error",
    "message": "Items must be an array: {}",
    "stack": "Error: Items must be an array: {}\n    at new List (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\list.js:35:17)\n    at List (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\list.js:17:12)\n    at ModelConstructor.ModelBaseClass._initProperties (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\model.js:355:28)\n    at ModelConstructor.ModelBaseClass (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\model.js:60:8)\n    at ModelConstructor (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\model-builder.js:196:22)\n    at ModelConstructor (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\model-builder.js:196:22)\n    at new ModelConstructor (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\model-builder.js:196:22)\n    at buildResult (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:2023:19)\n    at D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:2073:13\n    at doNotify (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:155:49)\n    at doNotify (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:155:49)\n    at doNotify (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:155:49)\n    at doNotify (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:155:49)\n    at Function.ObserverMixin._notifyBaseObservers (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:178:5)\n    at Function.ObserverMixin.notifyObserversOf (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:153:8)\n    at Function.ObserverMixin._notifyBaseObservers (D:\\api\\node_modules\\loopback-datasource-juggler\\lib\\observer.js:176:15)"
  }
}
What am I doing wrong? Please give me solution.

**Comment by sarankani** [comment]
i fixed it.

**Comment by arunbandari** [comment]
@sarankani  how did you fix it?

**Comment by natuan62** [comment]
How to fixed it ?

**Comment by Naresh-varma** [comment]
@sarankani Can we have a possible solution here, please?
