### ISSUE TITLE
How to write model code in typescript language

### ISSUE THREAD

**Issue by quyenbc** [strongloop/loopback#3476]
Hi guys, 
I want to use typescript language with loopback 3 in my project. How can I do?

**Comment by Setogit** [comment]
@quyenbc   Will you follow the issue submission form and resubmit it, please?



# Description/Steps to reproduce



# Expected result



# Additional information

**Comment by Setogit** [comment]
@quyenbc  Will you follow the issue submission form and resubmit it, please?



# Description/Steps to reproduce



# Expected result



# Additional information

**Comment by mdhanju** [comment]
@quyenbc 
loopback-next is on its way https://github.com/strongloop/loopback-next

Releases
https://github.com/strongloop/loopback-next/wiki/Upcoming-Releases

**Comment by Setogit** [comment]
@mdhanju is right. :-)  closing.
