### ISSUE TITLE
How can I create remote method to download a image binary data that stored into Mongodb?

### ISSUE THREAD

**Issue by kanghyonkyong623** [strongloop/loopback#3477]
# I would like to implement following:

When the client request GET to certain endpoint, it receive image data that stored into mongodb as binary field. It's response should not be json and just image that stream clients can use with only pointing out the url of endpoint.

# Please help me out

**Comment by Setogit** [comment]
@kanghyonkyong623  Will you follow the issue submission form and resubmit it, please?



# Description/Steps to reproduce



# Expected result



# Additional information
