### ISSUE TITLE
Allow an enabled remote method hidden from swagger and API explorer 

### ISSUE THREAD

**Issue by f-w** [strongloop/loopback#3483]
Currently to hide a remote method from swagger, the remote method has to be disabled by, for example, calling `YourModel.disableRemoteMethodByName('yourMethod')`. But doing so also closed the REST end point, essentially blocking the remote method.

Some remote methods are designed for "internal use only".  Their REST end point should be enabled, but documentation is neither necessary nor desirable. A use case is to allow spawn sub-requests and dispatch them back to load-balanced cluster. A remote method handling sub-request is thus for internal use only.

This is a feature request.

**Comment by andy2046** [comment]
@f-w did you got the answer for this ticket? thanks

**Comment by f-w** [comment]
@andy2046 , no and given that lb4 is rewritten from scratch I doubt the issue will be investigated at all.
