### ISSUE TITLE
Storing file in MS SQL

### ISSUE THREAD

**Issue by spatrame** [strongloop/loopback#3488]
I am using loopback-component-storage to upload file to file system.

I wants to store the files directly into MS SQL database. 

Please let me know how can I achieve it.

**Comment by Setogit** [comment]
@spatrame https://www.npmjs.com/package/loopback-connector-mssql#sql-server-to-loopback-types

fs.readFile  to Buffer and store it as MS SQL Binary type?  If no encoding is specified, then the raw buffer is returned.
