### ISSUE TITLE
NPM installation of loopback is throwing this error. Please help

### ISSUE THREAD

**Issue by perceptron007** [strongloop/loopback#3495]
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xmldom@0.1.19 (node_modules\loopback-cli\node_modules\xmldom):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-Yx/Ad3bv2EEYvyUXGzftTQdaCrw= integrity checksum failed when using sha1: wanted sha1-Yx/Ad3bv2EEYvyUXGzftTQdaCrw=
 but got sha1-U2O+g40F/opixRkaGHULvTlG3zc=. (2235 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: strong-soap@1.2.6 (node_modules\loopback-cli\node_modules\strong-soap):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-4trAXwjWz7yHrQWIeQF4/Tb186s= integrity checksum failed when using sha1: wanted sha1-4trAXwjWz7yHrQWIeQF4/Tb186s=
 but got sha1-pF3ZXByVAW87etKT9UCQYZzB7z0=. (4993 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ursa@0.9.4 (node_modules\loopback-cli\node_modules\ursa):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-Ciq/t9xCZ/czsPjy/H8siV1ApBM= integrity checksum failed when using sha1: wanted sha1-Ciq/t9xCZ/czsPjy/H8siV1ApBM=
 but got sha1-2rl7/iKP4+QOUP34gewYxcOWBos=. (18620 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xml-crypto@0.8.5 (node_modules\loopback-cli\node_modules\xml-crypto):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\dprop\AppData\Roaming\npm\node_modules\.staging\xml-crypto-3e561385\
.gitattributes'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fs-extra@2.1.2 (node_modules\loopback-cli\node_modules\fs-extra):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\dprop\AppData\Roaming\npm\node_modules\.staging\fs-extra-eac38cc9\CH
ANGELOG.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpath.js@1.0.7 (node_modules\loopback-cli\node_modules\xpath.js):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-fpRif1QSdsvGprArXTXpQYVls+Q= integrity checksum failed when using sha1: wanted sha1-fpRif1QSdsvGprArXTXpQYVls+Q=
 but got sha1-5j4FHoMqUT0zMapB9z1pgIBd1iU=. (4995 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xmlbuilder@8.2.2 (node_modules\loopback-cli\node_modules\xmlbuilder):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-aSSGc0ELS6QuGmE2VR0pIjNap3M= integrity checksum failed when using sha1: wanted sha1-aSSGc0ELS6QuGmE2VR0pIjNap3M=
 but got sha1-XWursqUKg1kNvFb1LMaXkSI2kRo=. (10513 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: loopback-soap@1.0.4 (node_modules\loopback-cli\node_modules\loopback-soap):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-xq1qxxDYS5ysoRttgfQipOidAUQ= integrity checksum failed when using sha1: wanted sha1-xq1qxxDYS5ysoRttgfQipOidAUQ=
 but got sha1-O6oiJIDwZgXweqrdito5zBec1gs=. (2236 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: generator-loopback@3.9.1 (node_modules\loopback-cli\node_modules\generator-loopback):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'C:\Users\dprop\AppData\Roaming\npm\node_modules\.staging\generator-loopback-5
7b4a7ba\swagger\images\explorer-api.png'

npm ERR! code EINTEGRITY
npm ERR! sha1-oBNpAQs1WNiq7SOUYV39B4D9j6w= integrity checksum failed when using sha1: wanted sha1-oBNpAQs1WNiq7SOUYV39B4D9j6w= but got sha1-cqQ1oQD68vmROHF22A6G9ZosR
50=. (4993 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dprop\AppData\Roaming\npm-cache\_logs\2017-07-15T07_49_37_804Z-debug.log

**Comment by dhmlau** [comment]
You can try to clean the cache first using this command: `npm cache clean`

If not working, you can remove the cache folder in the file system, i.e. 
`C:\Users\dprop\AppData\Roaming\npm-cache`

**Comment by dhmlau** [comment]
@perceptron007 , we believe this would fix your problem.  Closing this issue now.
If you still have this problem, feel free to reopen.  Thanks.

**Comment by Subhojit1992** [comment]
`D:\Users\Subho>npm install -g loopback-cli
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: figures@1.7.0 (node_modules\loopback-cli\node_modules\yeoman-test\node_modules\yeoman-generator\node_modules\figures):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-y+Hjr/zxzUS4DK3+0o3Hk6lwHS4= integrity checksum failed when using sha1: wanted sha1-y+Hjr/zxzUS4DK3+0o3Hk6lwHS4= but got sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=. (0 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: diff@3.4.0 (node_modules\loopback-cli\node_modules\yeoman-test\node_modules\diff):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'D:\Users\Subho\AppData\Roaming\npm\node_modules\.staging\diff-ad08b4d9\lib\patch\parse.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: decompress@3.0.0 (node_modules\loopback-cli\node_modules\decompress):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'D:\Users\Subho\AppData\Roaming\npm\node_modules\.staging\decompress-430c074d\index.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: loopback-datasource-juggler@2.55.3 (node_modules\loopback-cli\node_modules\loopback-datasource-juggler):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'D:\Users\Subho\AppData\Roaming\npm\node_modules\.staging\loopback-datasource-juggler-c5d3a09e\CHANGES.md'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: loopback-boot@2.26.2 (node_modules\loopback-cli\node_modules\loopback-boot):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'D:\Users\Subho\AppData\Roaming\npm\node_modules\.staging\loopback-boot-395d70b3\LICENSE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abbrev@1.1.1 (node_modules\loopback-cli\node_modules\abbrev):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha512-nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q== integrity checksum failed when using sha512: wanted sha512-nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q== but got sha512-z4PhNX7vuL3xVChQ1m2AB9Yg5AULVxXcg/SpIdNs6c5H0NE8XYXysP+DGNKHfuwvY7kxvUdBeoGlODJ6+SfaPg==. (0 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: buffer-crc32@0.2.13 (node_modules\loopback-cli\node_modules\buffer-crc32):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-DTM+PwDqxQqhRUq9MO+MKl2ackI= integrity checksum failed when using sha1: wanted sha1-DTM+PwDqxQqhRUq9MO+MKl2ackI= but got sha1-2jmj7l5rSw0yVb/vlWAYkK/YBwk=. (0 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: loopback-component-explorer@2.7.0 (node_modules\loopback-cli\node_modules\loopback-component-explorer):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'D:\Users\Subho\AppData\Roaming\npm\node_modules\.staging\loopback-component-explorer-225177b7\LICENSE'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluebird@3.5.1 (node_modules\loopback-cli\node_modules\bluebird):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha512-MKiLiV+I1AA596t9w1sQJ8jkiSr5+ZKi0WKrYGUn6d1Fx+Ij4tIj+m2WMQSGczs5jZVxV339chE8iwk6F64wjA== integrity checksum failed when using sha512: wanted sha512-MKiLiV+I1AA596t9w1sQJ8jkiSr5+ZKi0WKrYGUn6d1Fx+Ij4tIj+m2WMQSGczs5jZVxV339chE8iwk6F64wjA== but got sha512-iL71pBjQNttc+StagFIYx4udDBmBj/LfM8dQvbgHhObRdiMVnT/UG2SVnPqRnCvSoyjTLnwYrQsCeMKk+05wBQ==. (48048 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: lodash@3.10.1 (node_modules\loopback-cli\node_modules\cheerio\node_modules\lodash):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: sha1-W/Rejkm6QYnhfUgnid/RW9FAt7Y= integrity checksum failed when using sha1: wanted sha1-W/Rejkm6QYnhfUgnid/RW9FAt7Y= but got sha1-GEBSi8yWSmYQN8QutpWGszRqQQg=. (20428 bytes)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: yaml-js@0.1.5 (node_modules\loopback-cli\node_modules\yaml-js):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'D:\Users\Subho\AppData\Roaming\npm\node_modules\.staging\yaml-js-8dda444e\yaml.min.js'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: mute-stream@0.0.7 (node_modules\loopback-cli\node_modules\yeoman-test\node_modules\mute-stream):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime 'D:\Users\Subho\AppData\Roaming\npm\node_modules\.staging\mute-stream-1fb76f68\coverage\lcov-report\prettify.js'

npm ERR! code EINTEGRITY
npm ERR! sha1-5aSs0sEB/fPZpNB/DbxNtJ3SgXY= integrity checksum failed when using sha1: wanted sha1-5aSs0sEB/fPZpNB/DbxNtJ3SgXY= but got sha1-i82uZ/hNx9yPwnATqsezD0Mxy3A=. (928 bytes)`

**Comment by duyan90** [comment]
Still have the same issue with @Subhojit1992 . Please help us on this issue.

**Comment by dhmlau** [comment]
I've ran `npm i -g loopback-cli` as @Subhojit1992 did above, and seems like the installation was successful.  I'm using Node v6.11.0

```
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
/Users/dianalau/.nvm/versions/node/v6.11.0/bin/lb -> /Users/dianalau/.nvm/versions/node/v6.11.0/lib/node_modules/loopback-cli/bin/loopback-cli.js
- debug@2.6.7 node_modules/loopback-cli/node_modules/body-parser/node_modules/debug
- assert-plus@1.0.0 node_modules/loopback-cli/node_modules/dashdash/node_modules/assert-plus
- once@1.3.3 node_modules/loopback-cli/node_modules/duplexify/node_modules/once
- end-of-stream@1.0.0 node_modules/loopback-cli/node_modules/duplexify/node_modules/end-of-stream
- debug@2.6.7 node_modules/loopback-cli/node_modules/express/node_modules/debug
- debug@2.6.7 node_modules/loopback-cli/node_modules/finalhandler/node_modules/debug
- assert-plus@1.0.0 node_modules/loopback-cli/node_modules/getpass/node_modules/assert-plus
- assert-plus@1.0.0 node_modules/loopback-cli/node_modules/jsprim/node_modules/assert-plus
- qs@3.1.0 node_modules/loopback-cli/node_modules/loopback-datasource-juggler/node_modules/qs
- mem@1.1.0 node_modules/loopback-cli/node_modules/mem
- p-finally@1.0.0 node_modules/loopback-cli/node_modules/p-finally
- path-key@2.0.1 node_modules/loopback-cli/node_modules/path-key
- npm-run-path@2.0.2 node_modules/loopback-cli/node_modules/npm-run-path
- debug@2.6.7 node_modules/loopback-cli/node_modules/send/node_modules/debug
- mime@1.3.4 node_modules/loopback-cli/node_modules/send/node_modules/mime
- safe-buffer@5.0.1 node_modules/loopback-cli/node_modules/serve-favicon/node_modules/safe-buffer
- assert-plus@1.0.0 node_modules/loopback-cli/node_modules/sshpk/node_modules/assert-plus
- safe-buffer@5.0.1 node_modules/loopback-cli/node_modules/string_decoder/node_modules/safe-buffer
- strip-eof@1.0.0 node_modules/loopback-cli/node_modules/strip-eof
- execa@0.5.1 node_modules/loopback-cli/node_modules/execa
- cross-spawn@3.0.1 node_modules/loopback-cli/node_modules/yeoman-generator/node_modules/cross-spawn
/Users/dianalau/.nvm/versions/node/v6.11.0/lib
└─┬ loopback-cli@4.0.0 
  ├─┬ camelcase-keys@4.1.0
  │ └── quick-lru@1.1.0 
  ├── debug@2.6.9 
  └─┬ generator-loopback@5.1.1 
    ├── async@2.5.0 
    ├─┬ js-yaml@3.10.0 
    │ └── esprima@4.0.0 
    ├── loopback-bluemix@3.1.1 
    ├─┬ loopback-soap@1.0.4 
    │ └── ejs@2.5.7 
    ├── loopback-swagger@4.3.0 
    ├─┬ loopback-workspace@4.0.0 
    │ ├─┬ loopback@2.38.3
    │ │ ├─┬ body-parser@1.18.2 
    │ │ │ ├── bytes@3.0.0 
    │ │ │ ├── content-type@1.0.4 
    │ │ │ ├── http-errors@1.6.2 
    │ │ │ ├── iconv-lite@0.4.19 
    │ │ │ └── raw-body@2.3.2 
    │ │ ├── depd@1.1.1 
    │ │ ├─┬ express@4.16.2 
    │ │ │ ├── finalhandler@1.1.0 
    │ │ │ ├─┬ proxy-addr@2.0.2 
    │ │ │ │ ├── forwarded@0.1.2 
    │ │ │ │ └── ipaddr.js@1.5.2 
    │ │ │ ├─┬ send@0.16.1 
    │ │ │ │ └── mime@1.4.1 
    │ │ │ ├── serve-static@1.13.1 
    │ │ │ ├── setprototypeof@1.1.0 
    │ │ │ └── utils-merge@1.0.1 
    │ │ ├─┬ loopback-context@1.0.0
    │ │ │ └─┬ continuation-local-storage@3.2.0
    │ │ │   └── async-listener@0.6.8 
    │ │ ├─┬ nodemailer@2.7.2
    │ │ │ └─┬ libmime@3.0.0
    │ │ │   └── iconv-lite@0.4.15 
    │ │ └─┬ strong-remoting@2.33.0
    │ │   └─┬ xml2js@0.4.19 
    │ │     └── xmlbuilder@9.0.4 
    │ ├── loopback-boot@2.26.2 
    │ ├─┬ loopback-component-explorer@2.7.0
    │ │ └── cors@2.8.4 
    │ ├─┬ loopback-datasource-juggler@2.55.3 
    │ │ └─┬ loopback-connector@2.7.1
    │ │   ├── bluebird@3.5.1 
    │ │   └── msgpack5@3.5.1 
    │ ├─┬ method-override@2.3.10 
    │ │ ├── parseurl@1.3.2 
    │ │ └── vary@1.1.2 
    │ ├─┬ morgan@1.9.0 
    │ │ └── basic-auth@2.0.0 
    │ ├── semver@5.4.1 
    │ ├─┬ serve-favicon@2.4.5 
    │ │ ├── etag@1.8.1 
    │ │ └── fresh@0.5.2 
    │ └─┬ strong-error-handler@1.2.1
    │   └── accepts@1.3.4 
    ├─┬ ora@1.3.0 
    │ ├─┬ cli-cursor@2.1.0 
    │ │ └─┬ restore-cursor@2.0.0 
    │ │   └── onetime@2.0.1 
    │ └── cli-spinners@1.1.0 
    ├─┬ request@2.83.0 
    │ ├── aws-sign2@0.7.0 
    │ ├── form-data@2.3.1 
    │ ├─┬ har-validator@5.0.3 
    │ │ ├─┬ ajv@5.2.3 
    │ │ │ ├── fast-deep-equal@1.0.0 
    │ │ │ └── json-schema-traverse@0.3.1 
    │ │ └── har-schema@2.0.0 
    │ ├─┬ hawk@6.0.2 
    │ │ ├── boom@4.3.1 
    │ │ ├─┬ cryptiles@3.1.2 
    │ │ │ └── boom@5.2.0 
    │ │ ├── hoek@4.2.0 
    │ │ └── sntp@2.0.2 
    │ ├─┬ http-signature@1.2.0 
    │ │ ├── assert-plus@1.0.0 
    │ │ └─┬ jsprim@1.4.1 
    │ │   ├── extsprintf@1.3.0 
    │ │   └── verror@1.10.0 
    │ ├─┬ mime-types@2.1.17 
    │ │ └── mime-db@1.30.0 
    │ ├── performance-now@2.1.0 
    │ ├── qs@6.5.1 
    │ ├── safe-buffer@5.1.1 
    │ └── tough-cookie@2.3.3 
    ├─┬ strong-globalize@2.8.5 
    │ ├── async@1.5.2 
    │ ├── esprima@3.1.3 
    │ ├─┬ g11n-pipeline@1.5.1 
    │ │ └── swagger-client@2.1.32 
    │ ├─┬ htmlparser2@3.9.2
    │ │ └─┬ readable-stream@2.3.3 
    │ │   └── string_decoder@1.0.3 
    │ ├── optional@0.1.4 
    │ └── os-locale@1.4.0 
    ├─┬ strong-soap@1.2.6 
    │ ├─┬ httpntlm@1.7.5
    │ │ └── httpreq@0.4.24 
    │ ├── sax@1.2.4 
    │ └─┬ ursa@0.9.4
    │   ├── bindings@1.3.0 
    │   └── nan@2.7.0 
    └─┬ yeoman-generator@0.23.4
      ├─┬ cross-spawn@3.0.1 
      │ └── which@1.3.0 
      ├─┬ dateformat@1.0.12
      │ └─┬ meow@3.7.0
      │   └─┬ normalize-package-data@2.4.0 
      │     └── hosted-git-info@2.5.0 
      ├─┬ download@4.4.3
      │ ├─┬ caw@1.2.0
      │ │ └─┬ get-proxy@1.1.0
      │ │   └── rc@1.2.2 
      │ ├─┬ each-async@1.1.1
      │ │ └── onetime@1.1.0 
      │ ├─┬ gulp-decompress@1.2.0
      │ │ └─┬ gulp-util@3.0.8
      │ │   └── dateformat@2.2.0 
      │ └─┬ vinyl-fs@2.4.4
      │   ├── duplexify@3.5.1 
      │   └─┬ glob-stream@5.3.5
      │     └─┬ micromatch@2.3.11
      │       ├─┬ arr-diff@2.0.0
      │       │ └── arr-flatten@1.1.0 
      │       └── regex-cache@0.4.4 
      ├─┬ gruntfile-editor@1.2.1
      │ └─┬ ast-query@2.0.0
      │   └── escodegen-wallaby@1.6.12 
      ├─┬ nopt@3.0.6
      │ └── abbrev@1.1.1 
      ├─┬ shelljs@0.7.8
      │ ├── interpret@1.0.4 
      │ └─┬ rechoir@0.6.2
      │   └── resolve@1.4.0 
      ├─┬ yeoman-environment@1.6.6
      │ └─┬ inquirer@1.2.3
      │   ├─┬ cli-cursor@1.0.2 
      │   │ └─┬ restore-cursor@1.0.1 
      │   │   └── onetime@1.1.0 
      │   └── cli-width@2.2.0 
      └─┬ yeoman-test@1.7.0 
        ├─┬ inquirer@3.3.0 
        │ ├── ansi-escapes@3.0.0 
        │ ├─┬ chalk@2.1.0 
        │ │ ├─┬ ansi-styles@3.2.0 
        │ │ │ └─┬ color-convert@1.9.0 
        │ │ │   └── color-name@1.1.3 
        │ │ └─┬ supports-color@4.4.0 
        │ │   └── has-flag@2.0.0 
        │ ├─┬ external-editor@2.0.5 
        │ │ ├── jschardet@1.5.1 
        │ │ └── tmp@0.0.33 
        │ ├── figures@2.0.0 
        │ ├── mute-stream@0.0.7 
        │ ├── rx-lite@4.0.8 
        │ ├── rx-lite-aggregates@4.0.8 
        │ ├─┬ string-width@2.1.1 
        │ │ └── is-fullwidth-code-point@2.0.0 
        │ └─┬ strip-ansi@4.0.0 
        │   └── ansi-regex@3.0.0 
        ├── rimraf@2.6.2 
        ├─┬ sinon@2.4.1 
        │ ├── diff@3.4.0 
        │ ├── formatio@1.2.0 
        │ ├── lolex@1.6.0 
        │ ├── native-promise-only@0.8.1 
        │ ├─┬ path-to-regexp@1.7.0 
        │ │ └── isarray@0.0.1 
        │ ├── samsam@1.3.0 
        │ ├── text-encoding@0.6.4 
        │ └── type-detect@4.0.3 
        ├─┬ yeoman-environment@2.0.5 
        │ ├── debug@3.1.0 
        │ ├── diff@3.4.0 
        │ ├── globby@6.1.0 
        │ ├─┬ is-scoped@1.0.0 
        │ │ └── scoped-regex@1.0.0 
        │ ├── log-symbols@2.1.0 
        │ └── untildify@3.0.2 
        └─┬ yeoman-generator@1.1.1 
          ├─┬ chalk@1.1.3 
          │ ├── ansi-styles@2.2.1 
          │ ├─┬ strip-ansi@3.0.1 
          │ │ └── ansi-regex@2.1.1 
          │ └── supports-color@2.0.0 
          ├─┬ cross-spawn@5.1.0 
          │ └─┬ shebang-command@1.2.0 
          │   └── shebang-regex@1.0.0 
          ├── dargs@5.1.0 
          ├── dateformat@2.2.0 
          ├── debug@2.6.9 
          ├─┬ find-up@2.1.0 
          │ └─┬ locate-path@2.0.0 
          │   ├─┬ p-locate@2.0.0 
          │   │ └── p-limit@1.1.0 
          │   └── path-exists@3.0.0 
          ├─┬ github-username@3.0.0 
          │ └─┬ gh-got@5.0.0 
          │   └─┬ got@6.7.1 
          │     ├── duplexer3@0.1.4 
          │     ├── get-stream@3.0.0 
          │     ├── timed-out@4.0.1 
          │     └── unzip-response@2.0.1 
          ├─┬ mem-fs-editor@3.0.2 
          │ ├── commondir@1.0.1 
          │ └─┬ vinyl@2.1.0 
          │   ├── clone@2.1.1 
          │   ├── clone-buffer@1.0.0 
          │   ├── clone-stats@1.0.0 
          │   ├── cloneable-readable@1.0.0 
          │   ├── remove-trailing-separator@1.1.0 
          │   └── replace-ext@1.0.0 
          ├── path-exists@3.0.0 
          ├── pretty-bytes@4.0.2 
          ├─┬ read-chunk@2.1.0 
          │ └── pify@3.0.0 
          ├─┬ read-pkg-up@2.0.0 
          │ └─┬ read-pkg@2.0.0 
          │   ├─┬ load-json-file@2.0.0 
          │   │ └── strip-bom@3.0.0 
          │   └── path-type@2.0.0 
          └─┬ yeoman-environment@1.6.6 
            ├── diff@2.2.3 
            ├─┬ globby@4.1.0 
            │ └── glob@6.0.4 
            ├─┬ inquirer@1.2.3 
            │ ├── ansi-escapes@1.4.0 
            │ ├─┬ cli-cursor@1.0.2 
            │ │ └─┬ restore-cursor@1.0.1 
            │ │   └── onetime@1.1.0 
            │ ├─┬ external-editor@1.1.1 
            │ │ └── tmp@0.0.29 
            │ ├── figures@1.7.0 
            │ ├── mute-stream@0.0.6 
            │ └─┬ string-width@1.0.2 
            │   └── is-fullwidth-code-point@1.0.0 
            ├── log-symbols@1.0.2 
            └── untildify@2.1.0 

````
