### ISSUE TITLE
Date gt filter not working

### ISSUE THREAD

**Issue by sreerajkrishnank** [strongloop/loopback#3496]
I am using find query in loopback where I need to filter availabilities based on the start_time.
This is the following query I am using
    app.models.Activity.findOne({
      where: {
        id: req.params.activityName
      },
      include: {
        relation: 'availabilities',
        where: {start_time: {'gt': moment().toJSON()}}
      }
})

I also tried where: {start_time: {'gt': Date.now()}} but that's also not working for me and it's returing the whole list.
I am using loopback-mongodb connector
    "loopback-connector-mongodb": "^1.18.1",
    "loopback": "^3.0.0",

**Comment by Setogit** [comment]
@sreerajkrishnank
I would first try to make simple case work, for example, something like:
https://github.com/strongloop/loopback-datasource-juggler/blob/2.x/test/basic-querying.test.js#L293
```
      User.find({order: 'seq', where: {birthday: {'gt': new Date('1980-12-08')},
```
assuming `start_time`data type is compatible with new Date()
