### ISSUE TITLE
loopback cassandra datasource issue

### ISSUE THREAD

**Issue by aliartiza75** [strongloop/loopback#3500]
In loopback I connected a model with the cassandra datasource but when I tried to use the post endpoint of that model using the API Explorer, I got an error :
"XYZ" table is not configured in the datasource. So I created a table in keyspace myself using CQL having the same schema but still got the same error. I found two solution for this error:

 1)   auto-migration of model
 2)   create a table in keyspace using CQL.
    I have tried both of the solution but both didn't worked.

Specification:
Loopback : 2.x.x
Datasource : Cassandra

**Comment by Setogit** [comment]
@aliartiza75

Here in the test code, C* datasource is created: https://github.com/strongloop/loopback-connector-cassandra/blob/master/test/init.js#L8
and, define schema: https://github.com/strongloop/loopback-connector-cassandra/blob/master/test/cass.custom.test.js#L21

then, access the C*in various ways there.
