### ISSUE TITLE
how to override the out of the box endpoints of a model

### ISSUE THREAD

**Issue by aliartiza75** [strongloop/loopback#3501]
How to override the out of the box end points that are created when we create model using the command ( slc loopback:model ). For example I want to override this method (/dataSourceTestings/{id}/replace ), How can I do it?

**Comment by Tuetuopay** [comment]
That depends. You can either customize what happens before and after with [remote hooks](https://loopback.io/doc/en/lb3/Remote-hooks.html) if you want to extend the features (`Model.{before,after}Remote), or plainly replace it. This is Javascript, so anything is possible.

In your case :

    DataSourceTestings.prototype.replace = function(...)

You can even save it if you really need it, however I would advise using `{before,after}Remote`.

    var replaceOriginal = DataSourceTestings.prototype.replace;
    // The above

Hope this helps :)

**Comment by aliartiza75** [comment]
thanks +1:
