### ISSUE TITLE
loopback-component-push and discontinuation of GCM

### ISSUE THREAD

**Issue by Noob7** [strongloop/loopback#3502]
Google has depreciated GCM in favor of Firebase Cloud Messaging. I am re-implementing a project that has a lot of functionality built around loopback-component-push. But unfortunately google isint allowing me to create new GCM app for cloud messaging but forcing me to create FCM app. However in the loopback-component-push we have a field called gcmServerKey which requires a GCM key. Is there a way to use a FCM app with loopback component push otherwise there will be a lot of changes in my codebase as a lot of models use the notification model of loopback-component-push. Iv hit a roadblock and havent been able to find any documentation related to FCM and loopback-component-push

Please help

**Comment by Tuetuopay** [comment]
Upping this, as I will hit the same roadblock. Also, thank you as I did not see this coming.

I will be working on it, as I'll need it pretty badly.

**Comment by Tuetuopay** [comment]
UPDATE : see loopback-component-push issue 148 https://github.com/strongloop/loopback-component-push/issues/148. This module actually uses `node-gcm` that now goes through FCM. That means you can use your FCM Server Key in the `gcmServerKey` field, and it will work.

I can actually confirm this works, as I am using it right now.

**Comment by Noob7** [comment]
hey thanks man you saved my life. Was going in production next month and without this would have had to rewrite a lot of code and then tests and then issues and then suicide.  :1st_place_medal:
