### ISSUE TITLE
New Chat app with Loopback :) 

### ISSUE THREAD

**Issue by tabvn** [strongloop/loopback#3505]
Good day Loopbackers :)

While improving my loopback Skill i did a project is clone of FB messenger http://messenger.tabvn.com/

it works good. i 'm still trying test with large of visitors to see how it works

Thanks for great Framework Loopback Team.

Best regards,
Toan

**Comment by Setogit** [comment]
@tabvn - Hi, great to hear that!  Thanks for using LoopBack.  Keep up the creative work!!
