### ISSUE TITLE
Treating unknown remoting type "X" as "any" when using private model as a remote method parameter

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback#3514]
# Description/Steps to reproduce

Create a model

landing-page-data-add-member.json
```json
{
  "name": "LandingPageDataAddMember",
  "base": "AbstractModel",
  "description": "Options object for landingPage.addPerson method.",
  "excludeBaseProperties": [ "id" ],
  "properties": {
    "person": {
      "type": "String"
  }
}
```

Create another model that defines a remote method which defines an input parameter that uses the type of the previous model. eg:

landing-page.json
```json
{
  "name": "LandingPage",
  "base": "PersistedModel",
  "properties": {
    "prototype.addMember": {
      "accepts": [{
        "arg": "data",
        "type": "LandingPageDataAddMember",
        "required": true,
        "description": "Landing Page Person data.",
        "http": {
          "source": "body"
        }
      }],
```

And both models model-config.json, with the 'embedded' model set with public=false

model-config.json
```json
  "LandingPage": {
    "dataSource": "db",
    "public": true
  },
  "LandingPageDataAddMember": {
    "dataSource": "transient",
    "public": false
  },

```

When you call the remote method you get a warning like this in the console:

> Treating unknown remoting type "landingpagedataaddprospect" as "any"

If you set the model to public the warning goes away... but we don't want this model to be public.

You can suppress the warning by setting `warnOnUnknownType` to `false` in config.json:

```json
  "remoting": {
    "types": {
      "warnOnUnknownType": false
    },
```

# Expected result

The model should be registered as a known type when it is added to model-config.json, regardless of wether it is public or not.

**Comment by adhicoder** [comment]
Yes, I am facing the same problem. Would appreciate if any one could point out the reason.

**Comment by sebastianhaas** [comment]
Same here

**Comment by orosznyet** [comment]
Making it public solved the issue for me too. You can get rid of the exposed methods using [Whitelist
Mixin](https://www.npmjs.com/package/loopback-mixin-whitelist). Not the most elegant solution but it gets the job done.

```
"mixins": {
  "MethodWhitelist": {
    "expose": []
  }
}
```

**Comment by danielhanzs** [comment]
Thanks, I was trying to define in memory db inside the corresponding model another one, This solution is good for me

**Comment by sebastianhaas** [comment]
But why

**Comment by filipef101** [comment]
why does this happen? an explanation?

**Comment by TwistedLogic** [comment]
One more trick to get rid of the warning:

`"LandingPageDataAddMember": {
    "dataSource": "transient",
    "public": true,
     "options": {
       "remoting": {
         "sharedMethods": {
           "*": false
         }
       }
     }
 }
`

**Comment by ras-marques** [comment]
I would like to keep the model from being exposed on the REST API, but suppress the warning. Is there some way of doing that currently?
