### ISSUE TITLE
DISTINCT for db2

### ISSUE THREAD

**Issue by kusbrar** [strongloop/loopback#3516]
We are currently using loopback as our API. We are trying to figure out how to use DISTINCT in loopback, but didn't get much information about it. Based on the posts online looks like this functionality is not yet supported. Is there anyway to do DISTINCT currently or is there a plan to implement it in the future? Thank you for your time in advance. Xi Wang has talked to your team before regarding other inquires about using loopback.

**Comment by dhmlau** [comment]
There is no built-in functionality for that.  But you can create your own SQL statement for this purpose.  
Please see details https://loopback.io/doc/en/lb3/Executing-native-SQL.html

**Comment by dhmlau** [comment]
Closing this issue as resolved.  Please feel free to reopen if the information provided above doesn't resolve your question.  Thanks.
