### ISSUE TITLE
PersistedModel.findById() gives not final instance. Methods like save() not existing

### ISSUE THREAD

**Issue by itinance** [strongloop/loopback#3521]
In an "afterRemote"-Hook i want to find a specific model and change an attribute:

    Team.afterRemote('prototype.__create__messages', function(ctx, message, next) {
        var Message = Team.app.models.message;

       // Promises.all not required, just for debugging (i removed other code)
        const promises = Promise.all( [
            Message.findById(message.id),
        ] )

        promises.then( function(result) {
            console.log("FOUND Message ", result);

            // here i'd like to change an attribute and save the model back to database
            console.log(typeof result.save); // will print undefined
        });

How could i manipulate the found entity and save it? Save()-Method is not present. All in all findById delivers a plain JSON-object, not a real PersistedModel-Instance.

The Model was defined as:

```
{
  "name": "message",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
```

Database is a mongoDB.

Since i am not sure if this is bug or intended, i asked also on [Stackoverflow](https://stackoverflow.com/questions/45333578/loopback-persistendmodel-findbyid-gives-not-final-instance-methods-like-save).

**Comment by SippieCup** [comment]
I do am experiencing this with MongoDB.. Is this intended?

**Comment by itinance** [comment]
Yes, i use MongoDB

**Comment by SippieCup** [comment]
This is happening for all datasources, not just mongoDB and in all situations. 

`findById` does seem to be working as intended for the built-in queries though. such as default the relationships endpoint: GET Users/:id/AccessTokens/

But if you use it in any function outside of those generated ones, `findById` seems to only ever return an simple json object - not an instance of the model as the docs state, Is there an issue in the DAO?

You can replicate it easily like so:
```
"prototype.remotemethod": {
      "accepts": [],
      "returns": [
        {
          "arg": "success",
          "type": "boolean",
          "root": true,
          "description": "Returns true if successful"
        }
      ],
      "description": "a remote method",
      "http": [
        {
          "path": "/remoteMethod",
          "verb": "get"
        }
      ]
    }
```
then defining that method as as:
```
PersistedModel.prototype.remoteMethod = function (callback) {
    console.log(this);
  callback(null, true)
}
```

console.log will only print an uninstantiated object.
