### ISSUE TITLE
Feature Request: lb schema create/update/delete/migrate

### ISSUE THREAD

**Issue by andreas83** [strongloop/loopback#3525]
i wonder why the model generator don't create the db schema afterwards, feels pretty obvious...
also I miss some important cli commands like
lb schema create,update,delete,migrate

If this is not the right place to ask features request, please point me to the right location.

thx in advanced.

andreas

**Comment by Tuetuopay** [comment]
See auto-migration and auto-update https://loopback.io/doc/en/lb3/Creating-a-database-schema-from-models.html.
