### ISSUE TITLE
Error: getaddrinfo ENOTFOUND http://localhost:8080

### ISSUE THREAD

**Issue by imasif** [strongloop/loopback#3526]
when I run: node .
I'm getting this error:

> events.js:160
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: getaddrinfo ENOTFOUND http://localhost:8080
>     at errnoException (dns.js:28:10)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

I'm using latest LTS noe version 6.11.1, loopback 2.0.x

**Comment by Setogit** [comment]
@imasif -- What happens if you type `http://localhost:8080` in your browser or `curl http://localhost:8080`?
