### ISSUE TITLE
Inheriting remote methods triggers deprecation warning about use of isStatic

### ISSUE THREAD

**Issue by lehni** [strongloop/loopback#3529]
# Description/Steps to reproduce

- Define two models of which one inherits from the other
- Define a remote method in the base model (it doesn't matter wether it is static or not):

#### base-class.json
```
{
  "name": "BaseClass",
  "base": "Model",
  "methods": {
    "test": {}
  }
}
```

#### extending-class.json
```
{
  "name": "ExtendingClass",
  "base": "BaseClass"
}
```

When running the app, this deprecation warning appears:

```
strong-remoting deprecated Remoting metadata "isStatic" is deprecated. Please specify "prototype.name" in method name instead for isStatic=false
```

# Expected result

No deprecation warning should be triggered

# Additional information

Looking into what's causing this, it looks like `Registry.prototype.createModel()` / `BaseClass.extend()` is passing on `BaseClass.settings.methods` to `ExtendingClass` (merged with it with its own method definitions, which in this case here is none). 

The problem is that `Model.settings.methods` is internally using the now deprecated notation with `isStatic` boolean values. So when they get passed on, the deprecation warning is triggered, although none of the app's own code is specifying `isStatic` anywhere.

**Comment by lehni** [comment]
This is tricky to fix, due to the use of a different format internally than in the JSON file. I'd suggest to either change the internal format as well, or to somehow mark inherited methods as inherited in their settings (or perhaps better: already parsed from JSON?) and not trigger a deprecation warning for such method definitions.

**Comment by bajtos** [comment]
Hello @lehni, thank you for reporting this issue. 

I think the problem may be actually easier to fix. The `isStatic` flag is added by `Registry.prototype._defineRemoteMethods`, see [here](https://github.com/strongloop/loopback/blob/8589629e7af41dbd02a1ff2fa57d549c37656d61/lib/registry.js#L276). It looks like this method is modifying the original metadata specified in the JSON file. The inheriting model is then receiving the modified settings instead of what has been specified in the JSON file.

If my analysis is correct, then I am proposing to simply fix `_defineRemoteMethods` to create a new object before adding `isStatic` flag. E.g.


```diff
- meta.isStatic = isStatic;
+ meta = Object.assign({}, meta, {isStatic});
```

Thoughts?

**Comment by lehni** [comment]
Interesting! I will test this right now.

**Comment by lehni** [comment]
Perfect! That simple change does indeed address the issue, the deprecation warning is gone. Shall I create a PR for it, or will you?

**Comment by bajtos** [comment]
> Perfect! That simple change does indeed address the issue, the deprecation warning is gone. Shall I create a PR for it, or will you?

Lovely, I am glad my proposed fix works. Please create the pull request yourself, if you don't mind. It would be great to include a unit-test to verify the fix. You can detect deprecation warnings by setting up `process.on('deprecation')` listener.

**Comment by lehni** [comment]
@bajtos I've looked into this now. Unfortunately there are a bunch of other tests that already trigger this deprecation warning, and the event only gets triggered the first time, so I'm not receiving it. 

I tracked it down to these tests:

https://github.com/strongloop/loopback/blob/master/test/loopback.test.js#L237-L244
https://github.com/strongloop/loopback/blob/master/test/loopback.test.js#L471-L478
https://github.com/strongloop/loopback/blob/master/test/loopback.test.js#L569-L572
https://github.com/strongloop/loopback/blob/master/test/loopback.test.js#L584-L587
https://github.com/strongloop/loopback/blob/master/test/loopback.test.js#L601-L604

I don't think I can change them all to the new notation... 

The logical place for the new test would be around here I think:

https://github.com/strongloop/loopback/blob/master/test/model.test.js#L637

The problem is that these tests are executed after loopback.test.js and hence I'm not able to detect the deprecation warning. 

What to do about it?

**Comment by lehni** [comment]
I guess I could clear the `depr` cache of `strong-remoting`, but that's a bit of a hack:
```js
var deprecated = require('depd')('strong-remoting');
delete deprecated._warned;
```

**Comment by lehni** [comment]
Scratch that, it doesn't work... : /

**Comment by bajtos** [comment]
@lehni I see. Don't worry about testing deprecation warnings then, I think your approach in #3540 is actually better, as it does not rely on deprecation warnings that may change in the future.

BTW when posting links to source code, please press `y` in your browser before copying the URL. This way GitHub converts a "live" link always pointing to the latest (future) version into a permalink pointing exactly to the commit you are seeing now. The trouble with "live" links pointing to "master" branch is that as the code evolves, these links will eventually point to a wrong line number, or even a file that no longer exists.

Live link:
https://github.com/strongloop/loopback/blob/master/test/loopback.test.js#L237-L244

Permalink: https://github.com/strongloop/loopback/blob/619a0e468daefff51b61d2e8854aed401c1ae3d3/test/loopback.test.js#L237-L244

**Comment by lehni** [comment]
@bajtos that's a great great tip about the permalinks! I changed mine above as a test, and will use this from now on when referencing code in comments. Thanks for merging also.

**Comment by bajtos** [comment]
@lehni GitHub recently improved their UI, so that you no longer need to remember the keyboard shortcut. Read more here: https://github.com/blog/2415-introducing-embedded-code-snippets

**Comment by lehni** [comment]
very nice, thanks for pointing this out!
