### ISSUE TITLE
How to query using numeric id in Loopback

### ISSUE THREAD

**Issue by dhruv004** [strongloop/loopback#3530]
# Description/Steps to reproduce

I have a loopback model as

```
{       "name": "myModel",       
        "base": "PersistedModel",       
          "idInjection": true,       
          "options": {         
               "validateUpsert": true      
           },     
          "properties": {
               "name": {          
                   "type": "string",          
                   "description": "Object name"
                }
            },
           "validations": [],
           "relations": {},
           "acls": [],
           "methods": {}
} 
```

Now this is connected to a mongodb collection.This collection can have custom id in numeric like 1234 or Mongodb ObjectId when created using loopback.Now when I query using `GET http://localhost:3000/api/myModel/1234.` 

It is not able to get the object of that id.I get an error message as       

```{"status":404,"statusCode":404,"code":"MODEL_NOT_FOUND","message": "Unknown \"myModel\" id \"1234\"} ```

If my id is alphanumeric like abcd1234 then I dont get this error.Is there a way in loopback to be able to process a numeric id. The only reference I have is [this](https://stackoverflow.com/questions/30634948/loopback-get-model-using-custom-string-id-from-mongodb) that suggests to use alphanumeric ids.

**Comment by rodrigomata** [comment]
I think you can [set your model](https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#top-level-properties) as `strict: filter`, and run a constraint or create another property to handle your numeric id.

Or have you tried to do a [composite id](https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#composite-ids)?
