### ISSUE TITLE
401 AUTHORIZATION REQUIRED for the GET REQUEST TO http://localhost:3000/api/Users 

### ISSUE THREAD

**Issue by zmazouzi** [strongloop/loopback#3533]
I can't figure this out, I create an admin user, and I allow in the ACL's all the methods : read, write and execute to that model.. when i do a  GET Request to : http://localhost:3000/api/Users I get : 401 AUTHORIZATION REQUIRED 
![sfqs](https://user-images.githubusercontent.com/19895489/28825473-3e43575e-76be-11e7-8307-04a812924dbd.PNG)

**Comment by zeriss** [comment]
You should post to the [loopback google group](https://groups.google.com/forum/#!forum/loopback) for support. Don't forget to add your acl json file, it will help a lot.
