### ISSUE TITLE
How to use the out the box model 'User' methods in middleware phase

### ISSUE THREAD

**Issue by aliartiza75** [strongloop/loopback#3534]
Is there a way to use the User(model) methods like (login logout) in our code? Like in my case I want to use the User.login(....) method in the middle-ware that is defined in the route phase of middle-ware.
I tried to import the User model in this way in the middle-ware file.

var loopback = require('loopback');
var boot = require('loopback-boot');
var app = module.exports = loopback();

var  User = app.models.user;

It gives me the error that "app is undefined".

Kindly let me know is there a way to use the login etc methods in my middle-ware.

Thank you

**Comment by jdhrivas** [comment]
@aliartiza75  I do the following to access my models inside my middleware files
```
var appRoot = require('app-root-path')
var app = appRoot.require('/server/server')
var user = app.models.User
module.exports = function () { .....
```
