### ISSUE TITLE
Handling multipart/form-data with remote method

### ISSUE THREAD

**Issue by JyotiRani** [strongloop/loopback#3544]
I am using the following sample client code to send the multipart/form-data from client:

    let formData = new FormData();
    var task ={"description":"this is first test task","sequenceNumber":1,"companyId":"1"};
    formData.append('task', task);
    formData.append('attachments', data.profile_pic[0]);
    const config = {
      headers: { 'content-type': 'multipart/form-data' }
    }
    post('http://localhost:3000/api/tasks/saveAll', formData, config);

Server side is a loopback application and i have defined the following remote method to handle the above request: (I have also followed [SO](https://stackoverflow.com/questions/28523782/how-can-i-use-body-parser-with-loopback) and did the required changes)

    Tasks.remoteMethod('saveAll', {
	  accepts: [{arg: 'task', type: 'object', http: { source: 'body' }},
	          {arg: 'req', type: 'object', 'http': {source: 'req'}},
        {arg: 'res', type: 'object', 'http': {source: 'res'}}],

	  http: {verb: 'post'},
	  returns: {arg: 'task', type: 'object'}
    });
    Tasks.saveAll = function(task, req, res, cb) {
	console.log('save all remote methid called' + JSON.stringify(task));
    });         

it always returns empty object{}. How do i get the task json which i sent from client in the remote method? I need to post attachment to a different server than JSON, so need to segregate data in remote method, but unable to read the task json set by client. Please suggest whats missing.
Any example similar to this requirement would help as well.

**Comment by JyotiRani** [comment]
@dhmlau can you please help triage this issue?

**Comment by dhmlau** [comment]
@JyotiRani, can you please provide a link to a test project? It would help us accelerate the triaging process.  See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

cc @strongloop/sq-lb-apex

**Comment by bajtos** [comment]
Hello, LoopBack does provide any easy-to-use API for handling file uploads (yet). The issue https://github.com/strongloop/loopback/issues/3266 is tracking this feature request.

Having said that, it's possible to implement a remote method that will parse the raw request body and extract uploaded files, you can use our [storage component](https://github.com/strongloop/loopback-component-storage) as a reference implementation. Here is the gist (using [formidable](https://www.npmjs.com/package/formidable) to parse multipart form-data):

https://github.com/strongloop/loopback-component-storage/blob/361388bb1d5041cc301f839a877c97124c025669/lib/storage-handler.js#L28-L211

**Comment by caiyufei** [comment]
Is it supported to add formidable or multer parser middleware in middleware.json ?

**Comment by mihir83in** [comment]
+1

**Comment by muhammadsamir11** [comment]
+1

**Comment by barocsi** [comment]
+1

**Comment by b-admike** [comment]
@barocsi @muhammadsamir11 @mihir83in can you try the solution recommended by @bajtos [above](https://github.com/strongloop/loopback/issues/3544#issuecomment-321485560) or the steps in the medium post by @jackrobertscott (see https://github.com/strongloop/loopback/issues/3266#issuecomment-366107015)?

**Comment by barocsi** [comment]
Thanks, Medium post https://github.com/strongloop/loopback/issues/3266#issuecomment-366107015 worked well.

**Comment by pbalan** [comment]
@bajtos looking to upload multipart/form-data. Could it be possible without having to create a remote method? And internally use superagent/request to send file data to loopback-component-storage in original afterremote method?
