### ISSUE TITLE
duplicate records using PersistedModel.upsertWithWhere

### ISSUE THREAD

**Issue by solidstudio** [strongloop/loopback#3546]
I'm adding multiple records to an oracle db using PersistedModel.upsertWithWhere but it doesn't seem to do as expected when using the oracle connector as i'm seeing duplicate records.

**Comment by kjdelisle** [comment]
@solidstudio Would you be able to post a reproduction of the issue on GitHub? A sample application would be fine; we can configure it on our end to connect to a datasource and attempt to reproduce it that way.
