### ISSUE TITLE
why I cant get relational model object in data list ? 

### ISSUE THREAD

**Issue by onerciller** [strongloop/loopback#3551]
hi, we made rest api test with loopback however we realized that  we couldn't get to relation model in any data list  only, we can get it  through relational endpoint. 

we found the example project in following. In here, we can get relational model in data list with 
embedsMany and scope but  this time too, we can't get relation model object in relational endpoint. 

https://github.com/strongloop/loopback-example-relations

**Comment by kjdelisle** [comment]
@onerciller Would you be able to host a reproduction in the form of a GitHub repository? If we have a working example of the issue you're running into, we can help you more easily. :)
