### ISSUE TITLE
Is it possible to react natively android using loopback 3 ?

### ISSUE THREAD

**Issue by rendy14s** [strongloop/loopback#3554]
I just studied react native android. Before its i ionic 2 & 3 + loopback.

Is it possible to react natively android using loopback 3.0? If any, Is there a reference for step by step build it. Sorry, my English is bad

Regards

**Comment by kjdelisle** [comment]
LoopBack will serve up any static content you'd like: https://loopback.io/doc/en/lb3/Add-a-static-web-page.html
You'd have to create the client-side content yourself (the HTML, CSS, and JS for React) and then place it in your configured location for static content, which would serve it on the configured route(s).

With respect to _components_, there isn't a React Android component that auto-generates client-side code for you (If anyone reading this knows better, please feel free to reply with a link).

If you're feeling adventurous, you could make a component that does this! My only advice in that regard would be that you take a look at [loopback-next](https://github.com/strongloop/loopback-next) as it's the upcoming major release of Loopback. In fact, we're looking for ideas and contributors for new components, so feel free to pitch the idea here: https://github.com/strongloop/loopback-next/issues/509
