### ISSUE TITLE
Not able to access endpoint for hasMany relation

### ISSUE THREAD

**Issue by rohitcolinrao** [strongloop/loopback#3557]
I created an a model Artist that extends User.  Artist has many Posts (blogposts).  I created a relation for it and restarted the server.  I'm not seeing the endpoint /Artist/{id}/Posts in my explorer and I'm not able to access it.

Here is the error I receive when I try to access it:
Unhandled error for request POST /api/Artists/598d3b571677ee78254bf5cb/Posts?access_token=tuoe3SRrqDok8A8l4fMmbjmUqA0fGNHjC09mfdJ0Ary1nDTr2sd34KxeS3LAJnex: Error: Shared class  "Artist" has no method handling POST /598d3b571677ee78254bf5cb/Posts?access_token=tuoe3SRrqDok8A8l4fMmbjmUqA0fGNHjC09mfdJ0Ary1nDTr2sd34KxeS3LAJnex
    at restRemoteMethodNotFound (/Users/rohitcolinrao/Dev/autuur/node_modules/strong-remoting/lib/rest-adapter.js:357:17)

Here are my ACLs which in my Artist.json:

"acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "__get__Posts"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": ["__create__Posts", "__delete__Posts", "__destroyById__Posts", "__findById__Posts", "__updateById__Posts", "__get__Posts"]
    }
  ],

Any help would be greatly appreciated.

lb -v 3.1.0 (generator-loopback@4.0.1 loopback-workspace@3.42.0)

**Comment by kjdelisle** [comment]
@rohitcolinrao Please provide a reproduction in the form of an application instance that demonstrates the problem. This will drastically increase the likelihood of our seeing the problem and addressing it quickly.

**Comment by rohitcolinrao** [comment]
I figured out the problem.  it was user error.  feel free to close this.  if anyone runs into this, i had not named my relation "images" and was looking for an endpoint with "images" in the explorer.

**Comment by kjdelisle** [comment]
@rohitcolinrao Great to hear! Closing.
