### ISSUE TITLE
Transaction support for memory connector

### ISSUE THREAD

**Issue by kodepareek** [strongloop/loopback#3561]
# Description
The default memory connector has great application when testing endpoints as it makes database cleanup trivial. However transactions aren't supported by the memory connector which necessitates a lot of code juggling to keep things pristine during TDD. 

**Suggestion**: Transaction support for  the memory connector.

**Comment by kjdelisle** [comment]
@kodepareek If you'd like to make a pull request to that effect, I'd be happy to review it and help you land it. I agree that it would be a nice feature to have, but it's not something I think will find its way into our backlog in and of itself.

If you can build it, I'll help you get it landed in 3.x :)

**Comment by mbenedettini** [comment]
@kjdelisle 

I have a forked version of `loopback-datasource-juggler` in which I have added a few simple methods to the Memory connector just to make my tests pass (ie won't do any check on transaction status -although this is not easy to implement-).

Something like this:

```
Memory.prototype.beginTransaction = function(isolationLevel, cb) {
    var connector = this;
    debug('Begin a transaction with isolation level: %s', isolationLevel);
    var tx = new Transaction(connector, null);
    cb(null, tx);
};

Memory.prototype.commit = function(connection, cb) {
    debug('Commit a transaction');
    cb(null);
};

Memory.prototype.rollback = function(connection, cb) {
    debug('Rollback a transaction');
    cb(null);
};
```
