### ISSUE TITLE
Filtering related models was working, now not in 3.10.0

### ISSUE THREAD

**Issue by devpascoe** [strongloop/loopback#3566]
Previously in 3.9.0 my endpoint /api/accounts/12345/profiles?filter[where][foo]=bar would return the filtered results correctly. However in 3.10.0 zero results return.
Additionally 
```
      foo.bars({
        where: { id: 5678 }
      }, function (err, bars) {
        ...
      });
```
^ would return filtered results but instead returns all related items with no filter applied.

I consequently downgraded from 3.10.0 to 3.9.0 and everything is functioning correctly again. Perhaps something to look into with the new release.

**Comment by devpascoe** [comment]
Note above had to set loopback to 3.9.0 AND loopback-datasource-juggler to 3.6.1

**Comment by dhmlau** [comment]
@devpascoe , what's the version of `loopback-datasource-juggler` for the non-working case?  Not sure if it's related, which connector are you using?

**Comment by dhmlau** [comment]
To help us to get it resolved faster, can you provide a link to a test project? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by devpascoe** [comment]
The combo of loopback-datasource-juggler 3.9.3 and loopback 3.10.0 had the issue. Reverting to juggler 3.6.1 and loopback 3.9.0 restored functionality. The reason i was sticking around on juggler 3.6.1 was this https://github.com/strongloop/loopback-datasource-juggler/issues/1381

**Comment by devpascoe** [comment]
still happening in 3.11.1

**Comment by dhmlau** [comment]
Issue moved to [strongloop/loopback-datasource-juggler #1476](https://github.com/strongloop/loopback-datasource-juggler/issues/1476) via [**ZenHub**](https://www.zenhub.com/)

**Comment by devpascoe** [comment]
been a while but figured i'd update. Finally moving to latest loopback and juggler now after these updates. So far so good 👍
