### ISSUE TITLE
How can I apply accessScopes to default method (find/create..etc)?

### ISSUE THREAD

**Issue by yahoohung** [strongloop/loopback#3569]
# Description/Steps to reproduce
I am trying to develop a new api by using accessScopes, I have checked the docs and found it is possible to set accessScopes on remote method but not default method. Is it possible to do it on version 3.x?

# Expected result
`
        {
            "accessType": "*",
            "principalType": "ROLE",
            "principalId": "$authenticated",
            "permission": "ALLOW",
            "property": "find",
            "scopes": ["form"]
        }
`

`    "methods": {
      "find": {
        "accessScopes": ["form"]
      }
    }`

# Additional information

**Comment by kjdelisle** [comment]
@yahoohung 
>I have checked the docs and found it is possible to set accessScopes on remote method but not default method. Is it possible to do it on version 3.x?

By default method, do you mean the CRUD endpoints that are typically generated with Models? You would create your ACL entries in each of the model's .json definition files (which you can automate using the `lb acl` command in the loopback-cli tool).

See here for more information: https://loopback.io/doc/en/lb3/Controlling-data-access.html#using-the-acl-generator-to-define-access-control

**Comment by kjdelisle** [comment]
If this doesn't help, reply here and I can re-open this issue.

**Comment by mrbatista** [comment]
@yahoohungif you are interest I have found the temporary solution:
````javascript
  const findById = User.sharedClass.findMethodByName('findById');
  findById.accessScopes = ['user:admin'];
````

**Comment by RAlhawash** [comment]
@mrbatista Works with static methods, but not with any instance methods.
for example: 
```
  const method = myModule.sharedClass.findMethodByName('prototype.__get__relationName');
  method.accessScopes = ['relation_method'];
```
then when calling the rest endpoint myModule/:id/relationName with the Debug on i get
