### ISSUE TITLE
"Callback was already called" in storage component in download file url refresh

### ISSUE THREAD

**Issue by rajnesh0409** [strongloop/loopback#3575]
When i refresh file url in browser it shows this error. second time hit to same url cause this error and server stop working

**Comment by rajnesh0409** [comment]
I resolved this issue in storage component file. This issue is duo to callback hell problem. You can close this issue.

**Comment by bluestaralone** [comment]
if (fn === null) throw new Error("Callback was already called.");
I got the same problem, who can help me to solve it. Thanks.

**Comment by fedebaier** [comment]
Hey @rajnesh0409 could you explain how you solved this? I'm having the same problem and can't find a solution.
