### ISSUE TITLE
Filter Bug in EmbedsMany

### ISSUE THREAD

**Issue by EduCeratti** [strongloop/loopback#3576]
Hi friends,
I think there´s a issue when I try to filter with an EmbedsMany relation.

When i´m trying to filter this, doesn´t have any effect.

![image](https://user-images.githubusercontent.com/2271931/29570170-0920d5c8-872c-11e7-8cae-94e891e30437.png)

Here is my relation:

```
"relations": {
    "credential": {
      "type": "embedsOne",
      "model": "credential",
      "property": "credentials",
      "options": {
        "validate": true,
        "forceId": false
      }
   },
    "service": {
      "type": "embedsMany",
      "model": "service",
      "property": "services",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
  },
```

Please, anyone can help me?

**Comment by rodrigomata** [comment]
You may need to [include it](https://loopback.io/doc/en/lb3/Include-filter.html#include-with-filters) first?

**Comment by EduCeratti** [comment]
Hola Rodrigo como estás?
Me explico.. No puedo incluir los filtros de limit en esa situacion, no tiene ningún efecto si las hago.
Pero ahorita estoy resolvendo la situación con referencesMany e en la opcion de hidden, la pongo como true.. Si quieres saber mas a respecto pode hablar en el privado. Un saludo!

**Comment by rodrigomata** [comment]
Hola Eduardo, disculpa estaba fuera. Con gusto podemos ponernos en contacto y ver si te puedo ayudar. Saludos,

**Comment by josephlaw** [comment]
Hello @rodrigomata , I also got the same problem. Can you tell me how to fix it? thanks.

**Comment by rodrigomata** [comment]
Ok, so I made a relation like this:

`User.find({include: { relation: 'role', scope: {where: { admin: true }}}}, callback)`

In this case, I'm finding Users that have many roles, and only want those users with admin role. Have you already take a look at [Querying Related Models](https://loopback.io/doc/en/lb3/Querying-related-models.html)?

**Comment by josephlaw** [comment]
Thanks.  I should refer to https://github.com/strongloop/loopback-example-relations

**Comment by sebastianfelipe** [comment]
Same problem +1!

**Comment by sebastianfelipe** [comment]
Also, when you use the /Models/{id}/subModel/count it doesn't work either :/

**Comment by EduCeratti** [comment]
I think count function also doesn't macth correctly.. As @josephlaw says!

**Comment by a-legrand** [comment]
Same here, can't use embedsMany since filters don't have any effect.
/Models/{id}/subModel/count always return 0

**Comment by sebastianfelipe** [comment]
No one has been assigned to this issue yet, I think this is important @bajtos

**Comment by bajtos** [comment]
I am afraid we don't have bandwidth to look into this issue. Could you perhaps contribute the fix yourself?

The implementation of embedded relations lives here: [lib/relation-definition.js#L2017-L3088](https://github.com/strongloop/loopback-datasource-juggler/blob/a9051ef991f0d7ce1e219089ae2cf8e56ab0fb9b/lib/relation-definition.js#L2017-L3088)

**Comment by sebastianfelipe** [comment]
Ok, don't worry, I'll have a look at it 👍

**Comment by sebastianfelipe** [comment]
I finish my thesis, couldn't do it before, I will have a look at it right now. Sorry for the late.
