### ISSUE TITLE
 query all objects of an model that has not an reference to my user.

### ISSUE THREAD

**Issue by BigAlKo** [strongloop/loopback#3580]
Hello,
i 'm currently struggling with a hasandbelongstomany related model.
I want to query all objects of an model that has not an reference to my user.

For Example:
- Exam(id:1,subject: "Music")
- Exam(id:2,subject: "Science")
- Exam(id:3,subject: "History")

- Student(id:1,name:"Selichio")
- Student1 has an relation to Exam 1 and 2

Expected Query Result:
- Exam(id:3,subject: "History")

Any idea how to query this (maybe thru filters) ?
Thanks in advance =)

**Comment by Selichio** [comment]
I have the same Problem :)
I think you mean a MINUS/EXCEPT Operation.

I am in :) 

+1

**Comment by sanfeliks** [comment]
SameSame - Need help :( Greets San

+1
