### ISSUE TITLE
how to filter properties 2 

### ISSUE THREAD

**Issue by cheese10yun** [strongloop/loopback#3581]
I want to search like in two models.

That model is a hasMany relationship.

I want to search for keywords in content or images.description, but what should I do?

i want to search for keywords in content or image.description, but what can i do ?

The filter I think does not work.

```json
{
  "include": [
    {
      "relation": "images"
    }
  ],
  "where": {
    "or": [
      {
        "content": {"like": "%keyword%"}
      },
      {
        "images.description": {"like": "%keyword%"}
      }
    ]
  }
}
```

**Comment by zy-1995** [comment]
Hello, have you solved this problem? I need to implement it through REST API

**Comment by cheese10yun** [comment]
It has not yet been resolved.

It does not seem to support the public notice.

I solved this problem with native query.
