### ISSUE TITLE
Nodemailer needs update to latest v4

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback#3584]
# Description/Steps to reproduce

**Nodemailer** dependency warns for deprecation of used v2 version.
Also latest v4 encapsulates all functionality and results to less modules installation

**Comment by wzup** [comment]
> npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/

When are you going to update it? 
Does everything work with deprecated Nodemailer?

**Comment by dhmlau** [comment]
Closing in favor of https://github.com/strongloop/loopback/pull/3585
