### ISSUE TITLE
API Explorer not showing endpoints defined in boot script

### ISSUE THREAD

**Issue by TamoMaez** [strongloop/loopback#3587]
This code works and is accessible through REST calls but the endpoint doesn't show up in the explorer

Boot script example (server/boot/someFile.js)
```
module.exports = function(app) {
  var Model = app.models.Model;

  Model.greet = function(msg, cb) {
    cb(null, 'Greetings... ' + msg);
  }

  Model.remoteMethod(
    'greet', 
    {
      accepts: {arg: 'msg', type: 'string'},
      returns: {arg: 'greeting', type: 'string'}
    }
  );
};
```
Certainly not a major bug but it had my head scratching for a second

I'm using lb3

Please advise

**Comment by sebastianfelipe** [comment]
Hi man,

That's stipulated at [https://loopback.io/doc/en/lb3/Adding-remote-methods-to-built-in-models.html#additional-considerations](url)

Is not a major, is part of the functionalities of lb3. Methods defined in server/boot/something.js doesn't appear in Swagger JSON.
