### ISSUE TITLE
Show hidden fields in remote method

### ISSUE THREAD

**Issue by blacktrue** [strongloop/loopback#3596]
Hi

How to show hidden fields in a remote method?, example:

`user.findOne({fields: {password: true}}, function (err, instance) {
      console.log(instance, 'not show password is empty object {}')
    });`

**Comment by cheese10yun** [comment]
modelName.json
```json
{
  "name": "user",
  "description": "User",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "allowEternalTokens": true,
  "hidden": [
    "password"
  ],
.
.
.
```
add to hidden array
