### ISSUE TITLE
Verification mail fail when is sent more than once

### ISSUE THREAD

**Issue by sebastianfelipe** [strongloop/loopback#3599]
# Description/Steps to reproduce
When a user is already created and the verify endpoint is executed more than ONCE, then the verifyHref arrived with 2 or more tokens, the previous generated tokens and the last one. The last token is added at the end. That means, "...token=dsjadha...&token=plndsan...&token=thisisthelastone".

Thanks,
Sebastián.

**Comment by sebastianfelipe** [comment]
I found that is because the verifyOptions is passed by reference, and after the second call, that reference is replaced and change everything. The solution is copy by value the this.settings.verifyOptions (or similar) passed  by argument/parameter. I modified it to a fixed value and the problem is mitigated. Please have a look at this problem.

**Comment by sebastianfelipe** [comment]
I tested the solution, after line https://github.com/strongloop/loopback/blob/0f40ca8f8eb1ed50cc588ae72893ce2ca33d80a2/common/models/user.js#L704, add this line -> "verifyOptions = Object.assign({}, verifyOptions)" and that's it, the value copied is by value and the problem mentioned before should be solver.

Thanks,
Sebastián.

**Comment by dhmlau** [comment]
@sebastianfelipe , would you like to submit a PR?

**Comment by sebastianfelipe** [comment]
I never have done something like that before, but sure, it'd would be a pleasure :)

**Comment by dhmlau** [comment]
Sounds good.  Thanks!

**Comment by dhmlau** [comment]
Marking it as `patch-welcome` because @sebastianfelipe is planning on a PR.
