### ISSUE TITLE
HTTP REST inconsistency: create should return HTTP 201

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#360]
Apparently, POST /api/things returns HTTP 200 - however, 201 is the right code.

**Comment by wrensburg** [comment]
Any update on this issue? Almost a year now for something I would deem critical to REST patterns and service integrators.

**Comment by seriousben** [comment]
:+1:

**Comment by slyadams** [comment]
Having switched to loopback for my webservice layer I'm having to change all my tests and checks because of this inconsistency.

**Comment by brawaga** [comment]
@zbitname, PUT also can and should return 201 if the request led to instance creation. 200 for rewriting existing one only.

**Comment by bajtos** [comment]
LoopBack 3 is in Maintenance LTS mode, only critical bugs and critical security fixes will be provided. We are tracking this request for LoopBack 4 here: https://github.com/strongloop/loopback-next/issues/788
