### ISSUE TITLE
Excluding fields not working

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback#3600]
# Description/Steps to reproduce
Define a model with a name property.  Confirm that this works to ONLY return an age property:

http://localhost:3000/api/cats?filter[fields][age]=true

Reverse it to false:

http://localhost:3000/api/cats?filter[fields][age]=false

And I still get a result set of *just* age.

# Link to reproduction sandbox

https://app1-lhyucicjez.now.sh/api/cats?filter[fields][age]=false

# Expected result
A list of cats with the age property removed.

# Additional information
linux x64 8.4.0

├── loopback@3.9.0
├── loopback-boot@2.26.0
├── loopback-component-explorer@4.2.0
├── loopback-connector-mongodb@3.2.1

**Comment by cfjedimaster** [comment]
Weird, so doing

?filter[fields][age] 

does exclude. So the docs are wrong, right?

**Comment by cfjedimaster** [comment]
Nope - not stale - keep it open.

**Comment by cfjedimaster** [comment]
Nope - not stale - keep it open.

**Comment by cfjedimaster** [comment]
Nope, somebody fix it. :p

**Comment by keith666666** [comment]
Nope - not stale - keep it open.
