### ISSUE TITLE
Loopback and graphql

### ISSUE THREAD

**Issue by StasB93R** [strongloop/loopback#3601]
Hey, i was just wondering about the integration of loopback and grapql, i have seen this thread https://github.com/facebook/graphql/issues/3, but it doesnt seem to be active anymore. Is there a good and clear way that shows how to integrate loopback with graphql?
Or is it possible at all?
What r u thoughts on this?

**Comment by dhmlau** [comment]
@StasB93R , in LoopBack Next, one can create a component/extension for this integration.  Please take a look at this: https://github.com/strongloop/loopback-next/issues/512
Feel free to upvote and/or comments on [this issue](https://github.com/strongloop/loopback-next/issues/512).
Community contribution to build such extension is always welcome. 

I'd like to close this as we'd like to continue the discussion in the mentioned github issue.
