### ISSUE TITLE
Creating new hello-world has dependency warnings about deprecations

### ISSUE THREAD

**Issue by iosdev-republicofapps** [strongloop/loopback#3603]
# Description/Steps to reproduce

Follow instructions at http://loopback.io/getting-started/.  Once you hit enter you get the warning:
```
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
```

lb should update the version of nodemailer so that this warning goes away ... :-)

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
@iosdev-republicofapps , would you like to submit a PR?
