### ISSUE TITLE
Loopbackjs Querying related model of related model via rest api

### ISSUE THREAD

**Issue by imasif** [strongloop/loopback#3606]
is there any way to query related model's related model like from `post` \Get:      

> {"order": "created_at DESC","include":[{"relation": "user"]} 

 But, in my `user` model there is a relation `hasone` with `settings` model. I want to get that also, while querying from `post` \Get rest api.

**Comment by zbarbuto** [comment]
You can include related of related like so:

```
{
  "include": {
    "relation": "user",
    "scope": {
      "include": {
        "relation": "settings",
        "scope": {
          "where": {
            "someSetting": true
          }
        }
      }
    }
  }
}
```

Keep in mind this has no effect on the outer queries. I.e. You will still get all users but the users `settings` will only be included if `someSetting` is true.
