### ISSUE TITLE
Cannot pass access_token in body with default middleware order 

### ISSUE THREAD

**Issue by victor-homyakov** [strongloop/loopback#3610]
# Description/Steps to reproduce

- Create default application
- Try to POST or PUT data and send `access_token` in request body

App responses with 401.

# Expected result
200 OK

# Additional information
Auth middleware searches for `access_token` in query params and request body https://github.com/strongloop/loopback/blob/master/common/models/access-token.js#L113 
but default middleware order places `auth` before `parse` so there is no chance to find `auth_token` in the request body.

**Comment by murbanowicz** [comment]
A|ccess token has to be either in get parameter or Authorization header.
It's working correctly.

**Comment by victor-homyakov** [comment]
But `access-token.js` also looks for it in request body, the only problem is that `req.body` isn't filled yet. In other words, if I change the order of middleware and place body parser before `auth`, sending `access_token` in request body will work.
