### ISSUE TITLE
401 (Unauthorized) Error when login from extended User Model

### ISSUE THREAD

**Issue by bhandarys** [strongloop/loopback#3617]
# Description/Steps to reproduce
1. I have created a Client model that extends the built in User model.
2. I have created a Task model. The ACL for this is full access to authenticated users.
3. I have created lb-services to work with my angular framework.
4. After login, when I try to get the task, I do not find the access token placed on the URL.
5. After placing this manually, the code works fine. So the question is, Is access token handling supported for extended User models?

Simplified Code is given below -
1. Login:
  return Client
  .login({
    "username" : username,
    "password" : password
  })
  .$promise
  .then(function(response) {
        console.log("Access token is " + response.id);
        ser.currentUser = {
          id: response.user.id,
          tokenId: response.id,
          username: username
        };
        $state.go('home');
      });
2. To get tasks:
This code doesn't work:

  ser.taskList = Task
  .find({
    filter: {
      where: {
        and : [
          {"StatusCode": {"gt": statusCode}},
          {or: [
            {"CreatedUser": ser.currentUser.username},
            {"ShareWith": ser.currentUser.username}
          ]}
        ]}
      }
    });

However, if I add access token to this, I am able to get the tasks, like this:

  ser.taskList = Task
  .find({
    filter: {
      where: {
        and : [
          {"StatusCode": {"gt": statusCode}},
          {or: [
            {"CreatedUser": ser.currentUser.username},
            {"ShareWith": ser.currentUser.username}
          ]}
        ]}
      },
      access_token: ser.currentUser.tokenId
    });

# Link to reproduction sandbox
I do not have a reproduction sandbox. 

# Expected result

# Additional information
This work around works with deleteById method also.
.$deleteById({id: ser.taskList[index].id, access_token: ser.currentUser.tokenId})

However, this workaround doesn't work with $save and create methods.

Can you guide me on what I need to do differently?

I am using Windows 10. So the output of both these commands are raising exceptions.
  node -e 'console.log(process.platform, process.arch, process.versions.node)'
  npm ls --prod --depth 0 | grep loopback

Version information - 
strongloop v6.0.3 (node v6.9.1)
├── strong-arc@1.8.9 (3dd25ac)
├── strong-build@2.1.2 (a98f310)
├── strong-deploy@3.1.4 (9b29df0)
├── strong-mesh-models@8.1.1 (249315b)
├── strong-pm@5.2.4
├── strong-registry@1.1.6 (f8c2339)
├── strong-start@1.3.4 (28c261d)
├─┬ strong-supervisor@3.3.3
│ └── strong-agent@2.1.2 (4b9dde0)
├── generator-loopback@1.25.0 (6a0e2c0)
├── node-inspector@0.7.5 (16841d6)
└── nodefly-register@0.3.3

**Comment by shimks** [comment]
> I do not have a reproduction sandbox.

I am going to close this issue for now. Please consider creating a sandbox for us to help reproduce the issue.
