### ISSUE TITLE
referencesMany relation DELETE Bug: DELETE  \parents\{id}\children

### ISSUE THREAD

**Issue by solasky** [strongloop/loopback#3623]
# Description/Steps to reproduce

I have 2 models  (base: PersistedModel) setup in a referencesMany relationship such that Cat references many Dog

This creates the usual api methods, including the delete method for referenced dogs under a cat:
DELETE /Cats/{id}/dogs

but this api will delete all dogs in DB (mongo), not only the referenced ones

# Expected result

It only deletes the referenced dogs of a cat.

# Additional information

**Comment by tky20** [comment]
anyone solved this or any workaround?

**Comment by erdahuja** [comment]
Facing same issue. Please help.

**Comment by erdahuja** [comment]
@bajtos @fabien @clarkorz @ebarault @zbarbuto @nitro404 Any updates? This is a serious problem for us. We'been deeply using loopback and juggler, but unable to fix this one.

**Comment by nitro404** [comment]
This definitely sounds like a big problem, but I can't say I know much about the references relation. Are you perhaps able to work around this using a hasManyThrough relation instead in the meantime?
