### ISSUE TITLE
Loopback as a microservice and ACL

### ISSUE THREAD

**Issue by PierreRAFFA** [strongloop/loopback#3627]
Hi guys,
I have few microservices based on Loopback which can communicate each other.
Only one of them manages the users and is used as an **AuthenticationService**.
Each request between the microservices contains a **JWT**

The other ones are dedicated services and **does not have any User collections/models**.
Is there a way to use **Loopback ACL** on these microservices knowing that I can decode the JWT to get the user information ?

So far, I was thinking to create some **middlewares** such as "isAuthenticated" and "isAdmin" on each microservice but I am not sure that's the correct way.
Any idea ?
Thanks.

**Comment by sebastianfelipe** [comment]
Trying to understand your point, you have a microservice based on Loopback and you'd like to use that microservice as a discriminator (with ACLs) to other microservices? I mean, you'd like the other microservices requires the Loopback one first?
