### ISSUE TITLE
Post Method Allows all data external to model

### ISSUE THREAD

**Issue by cristianKumul** [strongloop/loopback#3631]
# Description
I'm using loopback 3.x but with all POST, the method created automatically I cant insert external data in database.

Following 

I enabled the RoleMapping model to public REST on my model-config.json file

`  "RoleMapping": {
    "dataSource": "mongoSource",
    "public": true
  }`

So now, I can see the endpoint on explorer path:

<img width="966" alt="screen shot 2017-09-28 at 10 59 18 pm" src="https://user-images.githubusercontent.com/9029434/31000395-34112694-a4a9-11e7-82d8-6bbabf723e97.png">

Everything works correctly, but for error, I sent a wrong request to this endpoint, and the endpoint has been answered with status code 200 although the model does not match the resource definition.

<img width="935" alt="screen shot 2017-09-28 at 11 03 59 pm" src="https://user-images.githubusercontent.com/9029434/31000505-020d9f50-a4aa-11e7-872f-60aeceec5b7c.png">

I tried the same steps with all POST request and I can insert other models to database.

Is there a way that you can insert only the structure defined in model.json?

I appreciate your help.

**Comment by gunjpan** [comment]
@cristianKumul  Try setting `strict: true` property in model's `RoleMapping.json` file to avoid inserting extra properties other than defined in the model.json file. 

Read more here: http://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#top-level-properties

**Comment by cristianKumul** [comment]
@gunjpan thank you, I have omitted that part of the document.
