### ISSUE TITLE
Include relation models not working

### ISSUE THREAD

**Issue by ghmendonca** [strongloop/loopback#3634]
Hi i have a problem, i have a Contrato model that has many Item model and in my Item model it has a Produto model.

So, basic, my Item belongs to one Produto and my Item belongs to one Contrato, but a Contrato can have a lot of Items. The problem is that i want to get all the Contratos with the Items and on each Item the Produto.

After reading the documentation, it seens the case:

`/customers?filter[include][reviews]=author`

So, in my case would be:

`contratos?filter[include][itens]=produto`

But the result is that the Contratos has the items but each item only has the id of the Produto and not the Produto object itself.. What i am doing wrong?

Here is the response that i am receiving:

`[
    {
        "id": 1,
        "codigoTemplate": null,
        "status": "aguardando",
        "prazoFinalizacao": "2017-11-17T02:00:00.000Z",
        "dataInicio": "2017-10-01T23:47:10.000Z",
        "dataFinalizacao": null,
        "emailComissao": "email@hotmail.com",
        "dono": null,
        "usuario": 2,
        "itens": [
            {
                "id": 1,
                "quantidade": 5,
                "contrato": 1,
                "produto": 1
            },
            {
                "id": 2,
                "quantidade": 3,
                "contrato": 1,
                "produto": 2
            }
        ]
    }
]`

My Contrato realtions:

`"relations": {
    "formandos": {
      "type": "hasMany",
      "model": "formando",
      "foreignKey": "contrato"
    },
    "itens": {
      "type": "hasMany",
      "model": "item",
      "foreignKey": "contrato"
    },
    "usuario": {
      "type": "belongsTo",
      "model": "usuario",
      "foreignKey": "usuario"
    }
  }`

My Item relations:

`"relations": {
    "itemFormando": {
      "type": "hasOne",
      "model": "itemFormando",
      "foreignKey": "item"
    },
    "produto":{
      "type": "belongsTo",
      "model": "produto",
      "foreignKey": "produto"
    }
  }`

And my Produto relations:

`"relations": {
    "item": {
      "type": "hasOne",
      "model": "item",
      "foreignKey": "produto"
    }
  }`

**Comment by SippieCup** [comment]
You should be using a `hasmanythrough` realtionship between contrato and produto through item.

**Comment by jannyHou** [comment]
The fix is in PR https://github.com/strongloop/loopback-datasource-juggler/pull/1480

Close this issue as a dup of https://github.com/strongloop/loopback/issues/3487

**Comment by ghmendonca** [comment]
@SippieCup I changed the relations to use the has many through, but didn't work, in fact, now my itens array is always empty.. I read all the topics around the #3487 but none of then worked for me, neither the documentation about the relations between physicians and patients..

@jannyHou how do I get this PR? Do I need to install the latest version of loopback and will work? I tried `npm install loopback@latest loopback-datasource-juggler@latest --save` and after the install nothing different, still not working.

**Comment by brunoescalona** [comment]
@ghmendonca could you find a solution for that? I am getting the same empty array like you.

**Comment by ghmendonca** [comment]
@brunoescalona I couldn't. I don't remember now the workaround that I used, sorry. But what I think is that this bug only happens if you use MySQL, because the docs seems to be right and no one ever answered me about this bug.

**Comment by brunoescalona** [comment]
@ghmendonca Ok thanks, I'm having the same problem with mongodb and with memory connectors. I will try to find a solution.

**Comment by brunoescalona** [comment]
@ghmendonca I found a solution for the problem. 
Here https://github.com/strongloop/loopback/issues/3831 you can find the explanation in case you need it.
I had to use the `keyThrough` property as explained in the documentation https://loopback.io/doc/en/lb3/HasManyThrough-relations.html#keythrough-in-json.
