### ISSUE TITLE
Error: Cannot migrate models not attached to this datasource: User AccessToken ACL RoleMapping Role

### ISSUE THREAD

**Issue by HarisHashim** [strongloop/loopback#3643]
Following this tutorial

[creating-database-tables-for-built-in-models](http://loopback.io/doc/en/lb3/Creating-a-database-schema-from-models.html#creating-database-tables-for-built-in-models)

# Description/Steps to reproduce
- Just follow the tutorial and execute 
```
$ node create-lb-tables.js`
```

- It just give error (as in title) until I change `var ds = server.dataSources.db;` to

```
var ds = server.dataSources.<my data source name>;
```

- After I change the data source name as in above code, now it execute and create the schema. But the execution just got stuck with the following message in the console window:

```
NaN 'mysql'
```

**Comment by dynshon** [comment]
Hello HarisHashim,
I have the same problem:

Swagger: il tipo sconosciuto viene ignorato "$new_AccessToken".
NaN 'mysql'

Did You resolved it?

**Comment by HarisHashim** [comment]
@dynshon 

The ``NaN 'mysql'`` is not solved but tablet get created anyway.

So after waiting reasonably and checking my database that table is created, I just do a CTRL-C and continue as usual.

So far I have no problem with the table schema created. 

I got a feeling that @bajtos is the right person to give some light about this issue. When googling for solution I saw something about this in another issue.

**Comment by bajtos** [comment]
Hello, I am afraid I have no idea what's going on and unfortunately don't have bandwidth to investigate right now :(

**Comment by sathish-augment** [comment]
I have Fixed....
I have not created **Products** model in loopback Application, So only get this error,

```
var ds = server.dataSources.db;
var lbTables = ['User', 'AccessToken', 'ACL', 'RoleMapping', 'Role','Products'];
ds.automigrate(lbTables, function(er) {
    if (er) throw er;
    console.log('Loopback tables [' - lbTables - '] created in ', ds.adapter.name);
    ds.disconnect();
});
```

I have removed that or else remove unwanted table in **lbTables**

should be like this

```
var ds = server.dataSources.db;
var lbTables = ['User', 'AccessToken', 'ACL', 'RoleMapping', 'Role','Products'];
ds.automigrate(lbTables, function(er) {
    if (er) throw er;
    console.log('Loopback tables [' - lbTables - '] created in ', ds.adapter.name);
    ds.disconnect();
});
```
