### ISSUE TITLE
Issue with storing GPS in a 2dSphere index

### ISSUE THREAD

**Issue by taxiIDZwaneveld** [strongloop/loopback#3648]
# Description/Steps to reproduce

i have noticed an issue with patching a GeoLocation in a mongoDb with a 2dsphere index.
Loopback seems to try to inject the GPS update as [lat,lng] while the geoPoint standard is [lng,lat]. This means a patch like

```
{
"location": {
       "gps": {
                  "lng":-122.568646854684,
                  "lat": 32.352132456464
        }
    }
}
```

Wil result in a mongoDb error,
```
MongoError: Can't extract geo keys: {location: { gps: { lat: 32.352132456464, lng: -122.568646854684 } } } can't project geometry into spherical CRS: { lat: 32.352132456464, lng: -122.568646854684 }
```

This error is generated in MongoChef when you insert the gps in lat,lng but accepts when inserting in lng,lat loopback should not switch this around.

The error is a result that the latitude can't be lower then -90 and mongo geopoint sees the first value as the longitude and the second as latitude. I suspect that when Loopback would leave the order of patching alone this would work.

# Reproduction
We need a 2dSphere index for distance calculations, just add a location to a collection, add the index to the gps field. And try to patch the index like above.

**Comment by tewris-backend** [comment]
I ran into the same error. Any fix for that?

**Comment by taxiIDZwaneveld** [comment]
Not for this issue, we patch it directly into the database. A real-workaround (loopback) in this case. But we do not really like this solution.

**Comment by tewris-backend** [comment]
Can you show me how do you patch it directly?

**Comment by taxiIDZwaneveld** [comment]
I can refer you to https://stackoverflow.com/questions/28346169/how-do-i-get-the-mongodb-connection-from-inside-loopback-io and https://docs.mongodb.com/manual/reference/method/db.collection.update/

**Comment by tewris-backend** [comment]
@taxiIDZwaneveld  Thanks a lot for you help.

I ended up setting a 'before save' hook to set the 'lng' and 'lat' to zero and a 'after save' hook to update the database directly with the correct values.

I also don't like this solution but seems to work ok.

**Comment by tuxity** [comment]
I have exactly the same problem.
Empty collections, autoupdate to create mongo indexes, and then I use a POST route on my model and I get the error.

My guess ? the mongo connector doesn't handle correctly { "lat": xxxx, "lng": xxxx } loopback object to GeoPoint object or something like that

**Comment by roshanpal** [comment]
I'm facing he exact same issue. Has anyone come found any solution for this?

**Comment by melote** [comment]
I am facing same issue, @taxiIDZwaneveld, your method seems to be failed.
