### ISSUE TITLE
This is what your docs look like when coming in from a google search

### ISSUE THREAD

**Issue by JuergenSimon** [strongloop/loopback#3649]
Hello,

something is messed up with your website setup. When using a google search (also the one in the documentation's  search box, powered by Google) it seems to be missing the CSS. 

![screen shot 2017-10-12 at 15 36 22](https://user-images.githubusercontent.com/377783/31501823-35b010f4-af63-11e7-859d-74f0fe568393.png)

**Comment by mafellows** [comment]
+1

**Comment by dhmlau** [comment]
@JuergenSimon @mafellows , thanks for reporting this.  I just checked, and it's looking fine now.

**Comment by dhmlau** [comment]
Closing it, as I believe this problem has been resolved.  Feel free to reopen if this problem persists.  Thanks.
