### ISSUE TITLE
How to authenticate with multi-model ? 

### ISSUE THREAD

**Issue by huylv69** [strongloop/loopback#3653]
Hi all,
I have 3 model : company , admin , user . Each model , I create a accesstoken table corresponding to model and set acl to them. But I just login with user ( model created first ) and query  api with it . Other model ( company and admin )  when i query to api  i have error " Authorization Required" although i have seted accesstoken after login.
Please help me ! Thank all 
![image](https://user-images.githubusercontent.com/19328632/31607001-f1f787ea-b294-11e7-8a34-866fed051a88.png)

**Comment by huylv69** [comment]
Up

**Comment by ZabdiAG** [comment]
Is this fixed or something?

**Comment by huylv69** [comment]
> Is this fixed or something?

Do you have any solution to this problem?
