### ISSUE TITLE
find and findOne is not working in loopback mysql

### ISSUE THREAD

**Issue by mukulsoftwap** [strongloop/loopback#3654]
# I have use findOne with id but no data return.
`EquipmentType.find({
            filter: {
              where: {id: parseInt($stateParams.equipmentTypeId)}
            }
          }
        ).$promise.then(function (obj) { console.log(obj); }`

## I have check the id is available in db but noting return . when i create new its working.

**Comment by viguirilo** [comment]
Probably the first argument returned is the error. It means that your request had happened successfully. 
Try to attach another argument in your callback function.

**Comment by kjdelisle** [comment]
@mukulsoftwap If you're still having this issue, would you please open a reproduction sandbox (a sample application that accurately replicates the problem you're having)?

If not, please let us know so we can close this issue.
