### ISSUE TITLE
Route not matching defined remote method

### ISSUE THREAD

**Issue by codymwalker** [strongloop/loopback#3658]
## Description/Steps to reproduce

I have defined a remote method in my `common/models/model.json` to match `PATCH /{id}`. I have a corresponding function attached to the model in the `common/models/model.js` file to handle the operation. However, rather than matching my defined method, it uses the default patch operation and simply updated my record. This behavior seems to affect all versions `>3.9.12`. If I fall back to `3.9.12`, my remote method function is called as expected. I have also tried defining my remote method inside of the `.js` file, and have the same results. I'll include methods below.

From `/common/models/service-instance.json`
```
...
  "methods": {
    ...
    "updatePlan": {
      "accepts": [
        {
          "arg": "id",
          "type": "string",
          "description": "Service Instance Id",
          "required": true,
          "http": {
            "source": "path"
          }
        },
        {
          "arg": "updateRequest",
          "type": "PlanUpdateRequest",
          "description": "Request object containing data for plan updates.",
          "required": true,
          "http": {
            "source": "body"
          }
        },
        {
          "arg": "options",
          "type": "object",
          "http": "optionsFromRequest"
        },
        {
          "arg": "authorization",
          "type": "string",
          "description": "Basic Authorization",
          "http": {
            "source": "header"
          }
        }
      ],
      "returns": [
        {
          "arg": "body",
          "type": "object",
          "root": true
        }
      ],
      "description": "Update the plan associated with a service instance",
      "http": {
        "path": "/:id",
        "verb": "patch",
        "status": 200
      }
    },
  ...
  }
```

From `common/models/service-instance.js`
```
module.exports = ServiceInstance => {
...
  ServiceInstance.updatePlan = (id, updateRequest, options) => {
    let logger = log.child({req_id: options.reqId});
    logger.trace(`ServiceInstance.updatePlan request; id: ${id}; updateRequest: ${JSON.stringify(updateRequest)}`);
    // do things before update...
  };
...
});
```

My log statements never get called, and the call immediately returns having updated the db record.

## Expected result

The `ServiceInstance.updatePlan` function should get called. Instead, the db record is automatically updated and returned.

## Additional information

```
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
darwin x64 8.1.3
```

Tested multiple versions greater than 3.9.12, including the latest 3.x release. In all cases, this issue seems to occur.

**Comment by codymwalker** [comment]
It looks that this change of behavior was introduced around 724a7d19280ca2b4eb064d69dd328f2f42338f59 based on the outputs of `npm view` for a working and non-working version

```
{ name: 'loopback',
  version: '3.9.13',
  description: 'LoopBack: Open Source Framework for Node.js',
  gitHead: '06a2b6d86be6fff60f4620c66753599888b50034',
  bugs: { url: 'https://github.com/strongloop/loopback/issues' },
  dist:
   { shasum: 'e0db40694953d92b4d98b70b16bf07790ea0d3a2',
     tarball: 'http://apic-ci-npm.hursley.ibm.com:4873/loopback/-/loopback-3.9.13.tgz' } }
```

```
{ name: 'loopback',
  version: '3.9.12',
  description: 'LoopBack: Open Source Framework for Node.js',
  gitHead: 'df87c17c08e80fe8be6ee3c96677439cd02e9268',
  bugs: { url: 'https://github.com/strongloop/loopback/issues' },
  dist:
   { shasum: 'b7d875ff3fd393dea54112467036063f6d4c0826',
     tarball: 'http://apic-ci-npm.hursley.ibm.com:4873/loopback/-/loopback-3.9.12.tgz' } }
```

**Comment by raymondfeng** [comment]
@zbarbuto Do you want to help troubleshoot this issue?

**Comment by zbarbuto** [comment]
Sure I'll take a look when I get a chance

@codymwalker out of curiosity, what happens if you disable the default update method first and then define yours in js?

```javascript
Plan.disableRemoteMethodByName('updateAttributes') // might be prototype.updateAttributes, I forget for the moment
Plan.remoteMethod('updatePlan', { /* ... */ });
```

**Comment by codymwalker** [comment]
I'll try that out.

@zbarbuto Is there a defined order in which everything executes? I currently have my application set up like this:

* I disable the old patch method in `/server/model-config.json`
* I define the new method in `/common/models/service-instance.json`
* I have the implementation in `/common/models/service-instance.js`

**Comment by zbarbuto** [comment]
It should be working the way you have it. The json file is read first to define the model and then the model instance is passed into the javascript to be extended. It works something like:

```javascript
// For each model read out of model-config
var ServerInstance = Loobpack.model.extend('ServerInstance', require('common/models/server-instance.json');
require('common/models/server-instance.js')(ServerInstance);
```

**Comment by codymwalker** [comment]
@zbarbuto It is working after throwing this into the bottom of my js file:
```
ServiceInstance.disableRemoteMethodByName('prototype.updateAttributes');
ServiceInstance.remoteMethod('updatePlan', {...});
```

**Comment by codymwalker** [comment]
Ah, looks like there's a bug in the documentation with the function name that should be disabled. Will open a PR to fix that

**Comment by codymwalker** [comment]
@zbarbuto Looks like I had the wrong remote method disabled. I was disabling `patchAttributes` in my model-config. If I change that to disabling `prototype.patchAttributes`, it works as expected.

Looks like something was changed in [this commit](https://github.com/strongloop/loopback/commit/724a7d19280ca2b4eb064d69dd328f2f42338f59) that caused my old disable statement to no longer work.

**Comment by zbarbuto** [comment]
Hi @codymwalker 

Do you believe this to be a bug introduced from the commit you referenced or is this now resolved after changing to `prototype.patchAttributes`? 

In my opinion, since patching attributes is an instance method, this is expected behaviour.
