### ISSUE TITLE
Inconsistency modifing an attribute in a beforeSave hook

### ISSUE THREAD

**Issue by andreribeirocoelho** [strongloop/loopback#366]
I'd like to modify a model attribute in a beforeSave hook. How would I do this?

Something like this:

```javascript
MyModel.beforeSave = function(next, data) {
    // change modified date attribute received here to another value
};
````
First, a tried using "this":

```javascript
MyModel.beforeSave = function(next, data) {
    this.modified = "my new value";
};
````

This only works for POSTing an instance if I change this.__data.modifed also like this: 

```javascript
MyModel.beforeSave = function(next, data) {
    this.modified = "my new value";
    this.__data.modified = "my new value";
};
```

But when I'm PUTing something this solution does not work.

In order to work with PUT I need to change "data" attribute:

```javascript
MyModel.beforeSave = function(next, data) {
    data.modified = "my new value";
};
```

In order to have a consistency attribution for both cases (POST and PUT) I tried to use "data.modified". 

This approach only works if I do this:

```javascript
MyModel.beforeSave = function(next, data) {
    data.modified = "my new value";

    if (data.__data) { // check if is a POST
        data.__data.modified = "my new value";
    }
};
```

This is pretty confusing because I do not have a consistent way of change the instance and when I'm PUTing something my instance does not have __data attribute.

To be honest I would rather just change the instance and need not change the __data attribute.

**Comment by bajtos** [comment]
We are moving away from `beforeSave/afterSave` hooks in favour of [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks) and [Per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397).

Please upgrade your project to use the new `before save` hook and open a new GH issue if you run into any problem.

```js
MyModel.observe('before save', function(ctx, next) {
  if (ctx.instance) {
    ctx.instance.modified = new Date();
  } else {
    ctx.data.modified = new Date();
  }
  next();
});
```
