### ISSUE TITLE
How to change language: strong-globalize

### ISSUE THREAD

**Issue by blacktrue** [strongloop/loopback#3661]
Hi

¿How to change language code in loopback?

in server/server.js write and not working.
```
var SG = require('strong-globalize');
SG.SetDefaultLanguage('es');
```

**Comment by raymondfeng** [comment]
Have you tried https://github.com/strongloop/strong-globalize#dynamic-language-switching-in-web-application?

**Comment by blacktrue** [comment]
I just tried and not working

add this to server/server.js

```
var SG = require('strong-globalize');
SG.SetRootDir(__dirname + '/../node_modules/loopback');
var g = SG();
g.setLanguage('es');
```

messages display in english :(

**Comment by blacktrue** [comment]
If i add this line in node_modules/loopback/lib/globalize.js before module.exports,  it works!

```
SG.SetDefaultLanguage('es');
```

**Comment by blacktrue** [comment]
It works with STRONGLOOP_GLOBALIZE_APP_LANGUAGE=es in environment var

**Comment by Jman** [comment]
But how to do this on the fly? 
Why i need to use environment var to switch language for error messages? 
How to add new languages for Validator?
Why it is so complicated to do such basic operation?

**Comment by smalesys** [comment]
I agree with @Jman, i also had a hard time to find a proper way to do it, but the doc doesn't give any clue.  Maybe a property  to set in server/config.json could be appropriate.
