### ISSUE TITLE
Cant login with model base User and connect to server.

### ISSUE THREAD

**Issue by rendy14s** [strongloop/loopback#3664]
Questions:
 I have 2 datasource, with setting this : 

1. `"db": {
    "name": "db",
    "connector": "memory",
    "file": "mydata.json"
  },`

2. `"Name": {
    "host": "XXXXXX",
    "port": 3306,
    "url": "",
    "database": "XXXXXX",
    "password": "XXXXXXX",
    "name": "Name",
    "user": "XXXXXX",
    "connector": "mysql"
  }`

Why: 
1. I cant use function login with datasource number 2. BUT if i create user / post i can do that. but login i **cant**. but  if i used datasource number 1. everything oke.

# Description/Steps to reproduce

1. I User datasource 2 : 

- Create/Post user = Success.
- Login = 401 - Login failed.

2. I user datasource 1 : 

- Create/Post user = Success.
- Login = Success

# ScreenShoot Model and datasource : 

1. Datasource : 
<img width="467" alt="screen shot 2017-10-23 at 10 10 40 pm" src="https://user-images.githubusercontent.com/10143804/31896892-0e10a150-b83f-11e7-9204-7b962980567b.png">

2. Model.json
<img width="720" alt="screen shot 2017-10-23 at 10 11 34 pm" src="https://user-images.githubusercontent.com/10143804/31896931-2dac593c-b83f-11e7-95db-6c44daf75476.png">

<img width="718" alt="screen shot 2017-10-23 at 10 06 17 pm" src="https://user-images.githubusercontent.com/10143804/31896653-8a0d79c8-b83e-11e7-98c1-4ca26cee45dd.png">
<img width="427" alt="screen shot 2017-10-23 at 10 06 25 pm" src="https://user-images.githubusercontent.com/10143804/31896657-8a54f104-b83e-11e7-8a87-fd435a762199.png">

3. model-config
<img width="747" alt="screen shot 2017-10-23 at 10 09 25 pm" src="https://user-images.githubusercontent.com/10143804/31896820-e56fa958-b83e-11e7-8efc-d3a1cbd4eff4.png">

**Comment by akkonrad** [comment]
hey @rendy14s, have you found what was causing this issue? I have exactly the same problem with mongo connector

**Comment by rendy14s** [comment]
hai @stale thanks , this issue was have close thanks.

hai @akkonrad , yes, this issue was solving. i just wrong set value of field password length. was is just 50 varchar. and i change it to 255 or max of varchar length in mysql, and its solved.

**Comment by akkonrad** [comment]
ok cool. in my case it is mongodb, so that's not the issue. thank you for quick reply :)
