### ISSUE TITLE
401  "message": "Authorization Required", with loopback 3.0, but with loopbacl 2, not !!!

### ISSUE THREAD

**Issue by emazzu** [strongloop/loopback#3665]
I have a problem with loopback 3.0. "loopback": "^2.22.0" works pefect !!!

What can be ????

  loopback:security:access-context --Context scopes of User.findOne()-- +36s
  loopback:security:access-context   method-level: ["DEFAULT"] +0ms
  loopback:security:acl --Denied by scope config-- +0ms
  loopback:security:acl Scopes allowed: List [] +1ms
  loopback:security:access-context --Context scopes of User.findOne()-- +0ms
  loopback:security:access-context   method-level: ["DEFAULT"] +0ms
  loopback:security:acl Scope required: [ 'DEFAULT' ] +0ms
  loopback:security:access-context ---AccessContext--- +0ms
  loopback:security:access-context principals: +3ms
  loopback:security:access-context principal: {"type":"USER","id":1} +0ms
  loopback:security:access-context modelName User +1ms
  loopback:security:access-context modelId undefined +0ms
  loopback:security:access-context property findOne +0ms
  loopback:security:access-context method findOne +0ms
  loopback:security:access-context accessType READ +0ms
  loopback:security:access-context --Context scopes of User.findOne()-- +0ms
  loopback:security:access-context   method-level: ["DEFAULT"] +0ms
  loopback:security:access-context accessScopes ["DEFAULT"] +0ms
  loopback:security:access-context accessToken: +3ms
  loopback:security:access-context   id "paILGVpyCTkHMjplBiEF8DPhXv7HoCMlM47Q0A9dgvpvjIKBVr48QFn50xveBORE" +0ms
  loopback:security:access-context   ttl 1209600 +0ms
  loopback:security:access-context   scopes [] +0ms
  loopback:security:access-context getUserId() 1 +3ms
  loopback:security:access-context isAuthenticated() true +0ms
# **Unhandled error for request GET /api/Users/findOne?access_token=paILGVpyCTkHMjplBiEF8DPhXv7HoCMlM47Q0A9dgvpvjIKBVr48QFn50xveBORE: Error: Authorization Required**

**Comment by dhmlau** [comment]
@emazzu , could you please provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by dhmlau** [comment]
@emazzu , do you still encounter this problem?  If so, please provide the requested information above.  Thanks.

**Comment by emazzu** [comment]
Yes, thanks you !!!!

**Comment by dhmlau** [comment]
@emazzu , glad to help. Could you please let us know the step to reproduce, and possibly a test project? https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.  Thanks.

**Comment by emazzu** [comment]
I could resolve the issue.
In the table RoleMapping I associate a user with the role for example:

Table Role Mapping
![image](https://user-images.githubusercontent.com/6100546/33604057-63b0a55e-d993-11e7-93c3-8d6d4a6b5af6.png)

Table Role
![image](https://user-images.githubusercontent.com/6100546/33603921-f9f19358-d992-11e7-887d-17a50284408c.png)

Before in the table roleMapping, I had added the role $everyone and $authenticated, when these roles are dinamic, when I removed these roles, the security worked good.

**Comment by dhmlau** [comment]
Closing as issue has been resolved.
