### ISSUE TITLE
Callback was already called.

### ISSUE THREAD

**Issue by grs4** [strongloop/loopback#3667]
Hello LB Experts 

I am struggling with "Callback was already called." 
This is resulting from because, LB API (findById, findOne, exists) return null/undefined err, in case of non existing record.  

Please let me know if there is any solution/workaround or advise the alternate methond to validate non existing record. 

Code Snippet: 

Following code is called inside operation hook.

app.models.my_model.exists(ctx.instance.my_id, function(err,flag) {
		if( err || !flag ) {
			var error = new Error();
			error.message = "ERROR : my user " + ctx.instance.my_id + " NOT found.";
			error.statusCode = 400;
			console.log(error);
			next (error);                                    
		}
	})
	
Thank you
grs4

**Comment by javaiste** [comment]
Hello,

It seems you need to add a "return" to your callback !
Try this : 
app.models.my_model.exists(ctx.instance.my_id, function(err,flag) {
if( err || !flag ) {
var error = new Error();
error.message = "ERROR : my user " + ctx.instance.my_id + " NOT found.";
error.statusCode = 400;
console.log(error);
return next (error);
}
})

**Comment by grs4** [comment]
No, it throws the same error with return as well.

**Comment by grs4** [comment]
Can someone throw some light on this ? Or is this a bug ?

**Comment by grs4** [comment]
Looks like this was fixed in juggler@2.53.0, as per 
https://github.com/strongloop/loopback-connector-mongodb/issues/285
https://github.com/strongloop/loopback-datasource-juggler/pull/1108

Is this a pending issue in 3.x ? I am stuck because of this error.
 
I am using loopback 3.x & version of juggler and postgresql connector as below

loopback-datasource-juggler@^3.9.3
loopback-connector-postgresql: "^3.1.0"
