### ISSUE TITLE
Composite key is not working to its effect 

### ISSUE THREAD

**Issue by NikhileshKshirsagar** [strongloop/loopback#367]
Following is curatedcontent model for mongo db in my project. I have defined the composite key for link and moduleId attributes. The composite key somehow has not come to its effect and allows me to insert a specific link redundantly for any given module.

```
"curatedcontent":{
    "properties":{
    "id":{
        "type":"string",
        "id":true,
        "generated":true
    },
    "link":{
        "type":"string",
        "index":{
            "unique":true
        }
    },
    "description":{
        "type":"string"
    },
    "tags":{
        "type":"array"
    },
    "datachanged":{
        "type":"boolean"
    },
    "moduleId":{
        "type":"string",
        "index":{
            "unique":true
        }
    }
},
    "options":{
        "relations":{
            "orders":{
                "type":"belongsTo",
                "model":"module",
                "foreignKey":"moduleId"
             }
        },
        "indexes":{
            "moduleid_link_index":{
                "keys":{
                "link":1,
                "moduleId":1
            },
            "options":{
                "unique":true
            }
         }
    }
},
"public":true,
"dataSource":"mongodb",
"plural":"curatedcontents"
}
```

**Comment by zanemcca** [comment]
Is it mandatory to use automigrate or autoupdate to get indexes to work?
If it is mandatory could we get a documentation update for indexes?

After some trial and error I got my composite indexes working with MongoDB by calling autoupdate at application startup.

**Comment by superkhau** [comment]
>Is it mandatory to use automigrate or autoupdate to get indexes to work?
@raymondfeng ^

>If it is mandatory could we get a documentation update for indexes?
@crandmck ^

**Comment by infonion** [comment]
Could some one confirm that Composite issue in loopback-juggler is not occuring now. I'm facing the issue in development. Your help will be really appreciated. Thanks!!!
