### ISSUE TITLE
in model.json how to give validations array ?

### ISSUE THREAD

**Issue by bhavin-00** [strongloop/loopback#3672]
In model.json file I try to give validation property to array as per document says but it doesn't work ..
How to give validations array ?..

also see i tried as per in screenshort but that didn't work
![screenshot from 2017-10-26 23-21-44](https://user-images.githubusercontent.com/31312646/32068751-c4a99fd6-baa4-11e7-90e4-5411d741d33f.png)

And following is my code file:-

![screenshot from 2017-10-26 23-57-17](https://user-images.githubusercontent.com/31312646/32070240-5d0b741c-baa9-11e7-8315-3384998d7261.png)

**Comment by itsnotme01** [comment]
Hello bahvin-00, 
I'm not a loopback representative but as it is written in the loopback documentation screenshot you shared, this feature is not yet implemented so you have to validate your model by code.

There is samples in the documentation on how to do that:
http://loopback.io/doc/en/lb3/Validating-model-data.html
