### ISSUE TITLE
Allow undefined envs in JSON config files

### ISSUE THREAD

**Issue by andrewferk** [strongloop/loopback#3682]
# Description/Steps to reproduce

Following the documentation for LoopBack 3.x, I am using an environment variable for my datasource url.

datasources.json
```json
{
  "mysql": {
    "name": "mysql",
    "connector": "mysql",
    "url": "${MYSQL_URL}"
  }
}
```

When running locally, I would like to use datasources.local.json, instead of providing the `MYSQL_URL` env.

datasources.local.json
```json
{
  "mysql": {
    "name": "mysql",
    "connector": "mysql",
    "host": "127.0.0.1",
    "port": 3306,
    "database": "mydb",
    "user": "mydbuser",
    "password": "s3cr3t"
  }
}
```

However, I get the following error: `${MYSQL_URL} does not resolve to a valid value, returned as undefined. "MYSQL_URL" must be resolvable in Environment variable or app.get().`

# Workaround

My current workaround is creating an app setting in `server/server.js` if the env does not exist.

```javascript
if (!process.env.MYSQL_URL)
  app.set('MYSQL_URL', '');
```

# Expected result

Environment variables can be undefined when being used in JSON config files.

**Comment by andrewferk** [comment]
No feedback on this?

**Comment by jannyHou** [comment]
Hi @andrewferk the warning is probably from here: https://github.com/strongloop/loopback-boot/blob/5060032d265bd457c14ea2510ecd0d017a7a2f1b/lib/executor.js#L388

I am looking into it.
