### ISSUE TITLE
Unable to Executing Code in related model !!

### ISSUE THREAD

**Issue by naumanahmad17** [strongloop/loopback#3686]
I have model Orders and Extended Users.

and the relation between two models are one to many.

extended user can have many order.

now what i want is that i want to execute some code in after create hook of order model.
when extended user create order from related model

`POST /extendedUsers/{id}/order`

following is the code in `order.js`

 ` Orders.afterRemote ('create', function (context, modelInstance, next) {`
               `  console.log('remote')`
                `  next();`
     ` });`

but i am unable to execute that code. how can i execute code in after hook??? #

**Comment by naumanahmad17** [comment]
`Extendeduser.afterRemote('prototype.__create__orders', (ctx, message, next)=> {`
   ` console.log('remoteExutese');`
     ` next();`
  `  });`

the above code also does'nt get executed.

**Comment by stanislavt** [comment]
Hi, @naumanahmad17
Here is the approach which works for me: 
```js
Extendeduser.afterRemote('*.__create__order', (ctx, message, next) => {
... your code ...
next();
});
```

pay attention, that your model relation has name `order` but you use `orders` in afterRemote hook.
