### ISSUE TITLE
LoopBack Swagger command issue

### ISSUE THREAD

**Issue by waytoharish** [strongloop/loopback#3688]
Hi,
I am facing issue when running command with valid Swagger file-
apic loopback:swagger --filename myswaggerfile

C:\Users\HarishSharma\TestmySwagger>apic loopback:swagger --filename C:\Harish\DIP\APIFramework-master\APIFramework-master\Node\account-info-swagger.yaml
? Enter the swagger spec url or file path: C:\Harish\DIP\APIFramework-master\APIFramework-master\Node\account-info-swagger.yaml
Loading C:\Harish\DIP\APIFramework-master\APIFramework-master\Node\account-info-swagger.yaml...
? Select models to be generated: (Press <space> to select, <a> to toggle all, <i> to inverse selection)
? Select the data-source to attach models to: (no data-source)
Done running LoopBack generator

Updating swagger and product definitions
Error: The LoopBack application is not loaded.
Cannot load the LoopBack application: Unexpected token -
Please fix the problem and run `apic loopback:refresh`

**Comment by dhmlau** [comment]
Summary of our investigation:
- the yaml file is valid
- the quick workaround is to remove `>-` in the yaml file.  
- no js file being generated. 

cc @raymondfeng

**Comment by raymondfeng** [comment]
@waytoharish Can you attach your swagger file here?

**Comment by raymondfeng** [comment]
Based on a private version of the swagger I received, it doesn't have a separate `definitions` and all schemas are embedded. I'll make a fix to tolerate that but adding support for embedded schemas might be a bit involved.

**Comment by dhmlau** [comment]
PR: https://github.com/strongloop/loopback-swagger/pull/112

**Comment by dhmlau** [comment]
@waytoharish , fix is in `loopback-swagger@5.4.0`.  
Is it good to close?

**Comment by dhmlau** [comment]
Verified.  See discussion in https://github.com/strongloop/loopback-swagger/issues/111
