### ISSUE TITLE
Loss of Endpoints on upgrade

### ISSUE THREAD

**Issue by privateOmega** [strongloop/loopback#3696]
# Description/Steps to reproduce

Bug: Upgrading from loopback-3.9.0 to any versions above it causes loss of some of the default Endpoints. I am unable to produce the code because it is running in production.

I've tracked the bug to the following lines in **application.js**:
**setSharedMethodSharedProperties(ModelCtor, app, config);
app.registry.configureModel(ModelCtor, config);**

Changing the order of execution of these functions cause the problem.

**Comment by SippieCup** [comment]
Are the loss of default endpoints all in the `User` Model or a model that extends it?

I recently upgraded from 3.9 to 3.16.2 and did not experience any endpoints being removed. However, I did notice that after using the CLI to generate a new model, it would overwrite any model's JSON file that extended the `User` class.

Could you provide a bit more information?

**Comment by privateOmega** [comment]
I found the loss of endpoints on models which were based on Persisted Model I think. I don't think there was any change's happening to the model's JSON file. Anyway I have pinpointed it to application.js file of loopback framework and have successfully got back the lost endpoints on changing in loopback 3.10. But after that codebase was heavily changed and being not very proficient, I was unable to locate the issue in latest versions.

**Comment by SippieCup** [comment]
What version of datasource connectors are you using? My guess is that its not being generated because its getting hung up when trying to attach models to the datasource. When you updated loopback, did you also update the datasource connectors?

If not, you should try doing that so that everything is in parity with just juggler.

**Comment by privateOmega** [comment]
Mongodb is of v1.18.1. I have tried running the app using loopback 3.9 and 3.10 out of which loopback 3.10 causes the loss. I have even resolved the issue in loopback 3.10 by editing application.js file of loopback in node_modules. So are you saying it might be a version compatibility issue?

**Comment by SippieCup** [comment]
Loopback is broken up into a few different repos as you are probably aware, I'd make sure you install  loopback-connector-mongodb v3.3.0 when you run loopback 3.16.2.

I think that will resolve the issue.

**Comment by privateOmega** [comment]
@SippieCup I am so sorry to get back to you this late, but I've tried the above approach and it doesn't work.
