### ISSUE TITLE
Event Stream Message Lost

### ISSUE THREAD

**Issue by malpower** [strongloop/loopback#3697]
Hi,
I created an application based on loopback, and i created another client program try to receive the event throw the SSE, but i found that the message will be lost with some unknown reason.

Below is the client program code:

```
const EventSource=require("eventsource");

const es=new EventSource("http://127.0.0.1/api/calls/change-stream?_format=event-stream",{headers: {"Authorization": "Basic "+Buffer.from("user:pass","utf8").toString("base64")}});
es.addEventListener("data",(data)=>
{
    console.log(data);
});
es.onerror=(e)=>
{
    console.log("e",e);
};
```

I tried 20 times on explorer to create new data, and the client only received 8 times.

Is there any thing i lost to config to the loopback program?

**Comment by bajtos** [comment]
Hello @malpower, thank you for reporting the issue. Could you please create a small app we can use to reproduce the issue locally on our computers? See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by malpower** [comment]
uh...
It's interesting, i couldnt reproduce the issue with the sandbox repo, but in our product repo, we can reproduce it whatever we use redis to store data nor using json file.

I'll continue to reproduce it, when i find the reason and it's really an issue, i  will open another.

BTW, thank you so much for your help.

**Comment by bajtos** [comment]
@malpower you are welcome! I hope you will be able to figure out the source of the bug, good luck :)
