### ISSUE TITLE
Error Access control with multiple user models . 

### ISSUE THREAD

**Issue by huylv69** [strongloop/loopback#3699]
Hi all, 
I have issues with "Access control with multiple user models" . 
I run demo project at https://github.com/beeman/loopback-example-multiple-user-models 
and read document in http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#preparing-access-control-models . 
I can login success, but when i use method or logout , server response same error : "accessToken is required to logout" or "Authorization Required" while i have logged in success . 
![image](https://user-images.githubusercontent.com/19328632/33060319-6ba0dafa-ceca-11e7-8172-a772a17cca25.png)
![image](https://user-images.githubusercontent.com/19328632/33060351-89ac2ae0-ceca-11e7-8ac8-8eb8d95112af.png)

Please help me implement access control with multiple models .
Thanks in advances

**Comment by lonewolfaka9** [comment]
having the same issue with the code anybody having luck with it ?
