### ISSUE TITLE
Use the json like filters that is available for native loopback models for remote method

### ISSUE THREAD

**Issue by rahulrsingh09** [strongloop/loopback#3701]
I have this following remote method

```
  XXX.remoteMethod('getAllGlobalFilters', {
    'description': 'List of all GlobalFilters',
    'http': {
      'path': '/getAllGlobalFilters',
      'verb': 'get'
    },
    'accepts': [
      {'arg': 'filter', 'type': 'object', 'http': {'source': 'query'}}
    ],
    'returns': {'arg': 'allGlobalFilters', 'type': 'array'}
  });


  XXX.getAllGlobalFilters = function(arg, callback) {
    console.log(arg);
    rtbSspPubFilter.find({
      where: {
        type: 15
      },
      include: [{relation: 'XXX'}]
    }, function(err, data) {
      if (err) {
        return callback(err);
      }
      return callback(null, data);
    });
  };
};
```

I want to be able to use the regular exp filters for the above how is this possible like ```{"where":{"name":{"like":%rahul%}}}```

Can we do that in remote methods

**Comment by pulkitsinghal** [comment]
What is your datasource? If you are fetching from DB then even though loopback-juggler or ORM might support the syntax ... it is up to the specific underlying connector implementation to have the actual implementation.

For example:
1. Clearly the ORM supports the syntax you asked about:
    * https://loopback.io/doc/en/lb2/Where-filter.html#like-and-nlike
    * https://loopback.io/doc/en/lb3/Where-filter.html#like-and-nlike
2. And for people using mongo connector the implementation is also present but need to look at the connector to be sure:
    * https://github.com/strongloop/loopback-connector-mongodb/blob/e7c87878e845e803a1da1b51fb804f526548fe6a/test/mongodb.test.js#L1985

**Comment by rahulrsingh09** [comment]
Yes @pulkit we can do it after a bit of researching we found out. The docs were not that helpful at start. The one thing that bothers me is the lack of functionality of querying when comming to related models like for some thing i include in my model in mysql connector or a orm connector.Any idea of that as i got a few issues on the same , but to no avail all were closed due to no time for dev

**Comment by rahulrsingh09** [comment]
Now i more interested in getting that included model filtered based on certain parameters of the included model. Like with sql joins. If you get any leads on the same i would appreciate it.
