### ISSUE TITLE
WARN deprecated nodemailer@2.7.2: 

### ISSUE THREAD

**Issue by wzup** [strongloop/loopback#3702]
```
$ npm i loopback
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
```
 What solution for this?

**Comment by dhmlau** [comment]
@wzup , please see the conclusion: https://github.com/strongloop/loopback/pull/3585.
Duplicate of https://github.com/strongloop/loopback/pull/3585

**Comment by Sambit567** [comment]
![capture](https://user-images.githubusercontent.com/33077951/35677568-249271b6-0776-11e8-9a79-5c03ab1d5733.JPG)

**Comment by digitalhemanth** [comment]
npm install -g nodemailer 

        // use this command
