### ISSUE TITLE
ENOENT: no such file or directory, open '...\strong-globalize\package.json'

### ISSUE THREAD

**Issue by wzup** [strongloop/loopback#3703]
```
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\user\appl\node_modules\strong-globalize\package.json'
```

What warn is this?

**Comment by dhmlau** [comment]
@wzup , could you please provide more information on how to reproduce the warning message you've provided above?

**Comment by dhmlau** [comment]
Closing it due to inactivity.  If problem exists, please provide more information on how to reproduce, and we'll be happy to reopen this issue.  Thanks.
