### ISSUE TITLE
GeoSearch not working 

### ISSUE THREAD

**Issue by VinaySingh1** [strongloop/loopback#3711]
Hi,

I am using loopback 3.13.0 version and mongodb . I created model for geosearch having "geolocation" property  with "lat" and "lng" fields. Loopback query used for geosearch is 

Mymodel.find({"geolocation":{"near":{"lat": 45.8846377,"lng":-95.3772806},maxDistance:100}})

I faced two issues:

1. In mongdb if any lat lng is not valid or null then it breaks the code. So I think for invalid values it should  ignore rather than break the code. It gives error  as mentioned below:
**AssertionError [ERR_ASSERTION]: lat must be a number when creating a GeoPoint**

It checks assertion in Geo.js

assert(typeof data === 'object', 'must provide a lat and lng object when creating a GeoPoint');
assert(typeof data.lat === 'number' && !isNaN(data.lat), 'lat must be a number when creating a GeoPoint');
 assert(typeof data.lng === 'number' && !isNaN(data.lng), 'lng must be a number when creating a GeoPoint');
 assert(data.lng <= 180, 'lng must be <= 180');
  assert(data.lng >= -180, 'lng must be >= -180');
  assert(data.lat <= 90, 'lat must be <= 90');
  assert(data.lat >= -90, 'lat must be >= -90');

2.  I observe that in geosearch firstly it create geopoint on all rows then it search so it makes this process very slow if it conatins about 34000 records or more.

So how to handle this issue?

**Comment by VinaySingh1** [comment]
Hi,
@fabien , @albertoleal  . Any suggestions on this issue?

**Comment by jannyHou** [comment]
Hi @VinaySingh1 which version of `loopback-connector-mongodb` are you using?

When I scaffold my app with loopback@3, the default version of mongodb connector is 1.18.1, and it doesn't seem to have the error:

./app/package.json:

```
"dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^1.3.0",
    "loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^5.0.0",
    "loopback-connector-mongodb": "^1.18.1",
    "serve-favicon": "^2.0.1",
    "strong-error-handler": "^2.0.0"
  },
```

Add a **geopoint** type property `` in model Note:

```json
{
  "name": "Note",
  "properties": {
    "title": {
      "type": "string",
      "required": true
    },
    "content": {
      "type": "string"
    },
    "geolocation": {
      "type": "geopoint"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

```

```js
'use strict';

module.exports = function sample(server) {
  var Note = server.models.Note;
  var query = {
    where: {
      geolocation: {near: {lat: 45.8846, lng: -95.377}, maxDistance: 100},
    },
  };
  Note.find(query, (err, r)  => {
    console.log(err, r);
  });
};
```

run the app with `node .`, it prints:

```
null [ { title: 'string',
    content: 'string',
    geolocation: { lat: 45, lng: -95 },
    id: '5a43cf4dfa8a5627415e13f8' } ]
```

And the explorer works well too:

endpoint: `GET/ Notes` 
filter: `{"where": {"geolocation": {"near": {"lat": 45.8846, "lng": -95.377}, "maxDistance": 100}}}`
