### ISSUE TITLE
User.verify 

### ISSUE THREAD

**Issue by ssageghi** [strongloop/loopback#3712]
Hi
I'm trying to enable email verification and it's ok on local machine
the problem is when I build the app for deployment and upload the app to server 
when user sign up and verification email send the port number is in the link and I don't want that.
(somthing like this: http://www.hostname.co:3000/api/Profiles/confirm? . . .)
I try setting the port number to 80 and it's worked on local machine and turned to  http://www.hostname.co/api/Profiles/confirm? . . .    
But on my server when try to sign-up the user instance verified itself and link in the email doesn't work 
I thinks it's bug if it's not please help how to send email that haven't port number in the link.
thanks

**Comment by shaheero** [comment]
+1

**Comment by shaheero** [comment]
Well, it is weird using port 80 on the server didn't work. Are you sure your node app is run on port 80 on the server? I am assuming you are not using HTTPS (port 443).

**Comment by ssageghi** [comment]
@shaheero I used nginx and it is listening to port 80 and make a reserve proxy to port 3000

**Comment by shaheero** [comment]
In the link that 'doesn't work' on your production server, if you replace :3000 with :80, does it work?

**Comment by ssageghi** [comment]
it worked without clicking on the link

**Comment by ssageghi** [comment]
it mean the userInstance verify itself and emailVerified in the user turn to 1 without clicking on the link

**Comment by shaheero** [comment]
How is that possible? What do you even mean? That the user.verify function is being triggered automatically after the email is sent? How is that related to mentioning the port number in the url?

**Comment by ssageghi** [comment]
I don't know but It happens to me :((((

**Comment by ssageghi** [comment]
Yes it's triggering and when i click the link the loop back say token  not valid

**Comment by shaheero** [comment]
Are you sure you don't have something in your code that is doing this automatically?

**Comment by ssageghi** [comment]
@shaheero Yes I'm pretty sure about that because on the local I can sign up and send verification email and verify that without problem but when I build that and upload to development server this happen
Is there another way to hide port number in the option that we pass to verify?
