### ISSUE TITLE
200 code for POST rather than 201 remains

### ISSUE THREAD

**Issue by Cooker-Monster** [strongloop/loopback#3713]
a __POST__ command returns a __200__ code instead of __201__.

It's a little bit strange because this nice Framework manages very more sofisticated and powerful features and that is the first ugly thing that we can see in the very beginning of a demo. 

Please note that it's the same behaviour for 3.1.0 and 4.0.0 versions

# Steps to reproduce

lb demo
cd demo
lb datasource
lb model
node.
http://localhost:3000/explorer

# Link to reproduction sandbox

# Expected result
__201__

# Additional information

**Comment by jannyHou** [comment]
@Cooker-Monster Thank you for the suggestion, seems we have an issue for it: https://github.com/strongloop/loopback/issues/360

I also created an issue in LoopBack4 for it: https://github.com/strongloop/loopback-next/issues/788
and bring the attention to my team.

I am closing this issue as a duplicate and let's keep the discussion in either story above. Thanks for understanding.
