### ISSUE TITLE
comparing string date

### ISSUE THREAD

**Issue by VinaySingh1** [strongloop/loopback#3715]
I try the Restful API using below query in loopback
mymodel.find({where:{and[{status:"A"} ,{updatedDate:{"gte":"2017-11-01"}}]}})
But I can't find any record.
I am using mongodb and in mongodb updatedDate is string datatype with date values in format "YYYY-mm-dd". 
Any suggestion?

**Comment by jannyHou** [comment]
Hi @VinaySingh1 I am trying to help you on this issue but the description is a little vague, could you fork https://github.com/strongloop/loopback-sandbox, provide your sample code with some testing data? Thanks, you can leave the datasource config as a fake one and I can test with my local mongodb database.

**Comment by VinaySingh1** [comment]
Hi @jannyHou  thanks for replying. This issue has been resolved. Actually my updatedDate has date values in string data type. So when I changed the data type to Date then this starts working properly.
