### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by vmvwebworks** [strongloop/loopback#3734]
https://github.com/strongloop/loopback-example-rest-connector/blob/master/external-server/server/model-config.json#L31

https://github.com/strongloop/loopback-example-rest-connector/blob/master/local-server/server/datasources.json#L6-L20

from
## How do you perform a GET request to a remote server?

In this example, we have a REST API exposed in model-config.json .

To make a request to the remote server, declare new datasource that uses the REST connector in the local datasources.json.
[Source](https://loopback.io/doc/en/lb3/REST-connector-example.html)

**Comment by jannyHou** [comment]
@vmvwebworks I think the example is re-organized into strongloop-community:
https://github.com/strongloop-community/loopback-example-connector

I am updating the document link.

**Comment by jannyHou** [comment]
Updated in https://github.com/strongloop-community/loopback-example-connector/pull/19
Feel free to reopen it if you have other question :)
