### ISSUE TITLE
env in loopback-cli not working 

### ISSUE THREAD

**Issue by AllaanR** [strongloop/loopback#3735]
# Description/Steps to reproduce

I have the datasources.local.json file configured inside my project. When I run `lb model` the cli only shows the datasources from datasources.json.

**Comment by privateOmega** [comment]
What have you set the NODE_ENV variable to in the env file?

**Comment by AllaanR** [comment]
I also tried to set the NODE_ENV to local and it still doesn't work.
My entire app works using the .local files, but the cli doesn't.
