### ISSUE TITLE
Incorrect Documentation for built-In model - Application

### ISSUE THREAD

**Issue by privateOmega** [strongloop/loopback#3736]
# Questions
https://stackoverflow.com/questions/34216308/use-of-the-application-model-in-loopback/39023999#39023999

# Description/Steps to reproduce
https://loopback.io/doc/en/lb3/Using-built-in-models.html#application-model
First link refers to the express application wrapper(http://apidocs.loopback.io/loopback/#application-new-application).

# Expected result
The link should refer to built-in model application(https://apidocs.strongloop.com/loopback/#application).

# Additional information
Also if possible, adding of additional information on usage of application model would be appreciated.

**Comment by diegoazh** [comment]
Hello, I have the same problem. I tryed to use application built-in model but the documentation in loopback web page is not enough and it's not clear. On the other hand, in docs I didn't find any example on how to use application model; I can't find any where on the documentation that says for make an auth request with application model follow this steps or follow this example.
I can generate an application with the the api explorer but I don't know how to use it to generate authenticated requests.
Please, can you help the community with any example or guide?
Thank you.
