### ISSUE TITLE
How to check whether data is already present in db

### ISSUE THREAD

**Issue by gaja33** [strongloop/loopback#3739]
hi. 
I have a medicine model and i want to maintain unique medicine info, Before adding new medicine i want check whether current medicine is already present in db. im using postgresql..

**Comment by jannyHou** [comment]
@gaja33 
> maintain unique medicine info

> check whether current medicine is already present in db

If your medicine have a primary key, I think you can try specify `{index: {unique: true}}` in the model property, like this test case:
https://github.com/strongloop/loopback-connector-postgresql/blob/dfb8bd3a1b0481573fd15cb4b41d38ae1b1cb51b/test/postgresql.autoupdate.test.js#L182-L186

**Comment by dhmlau** [comment]
@gaja33, does the above comment help you resolve the issue?  If so, is this GitHub issue good to close? Thanks.
