### ISSUE TITLE
Users with same id on different datasources can access one another's account

### ISSUE THREAD

**Issue by beirdostudio** [strongloop/loopback#3743]
Hello, I encountered this problem with users being able to access other users accounts with same id on different datasources.

# Description/Steps to reproduce

Create two users submodels with different datasource, create 2 users (id will be 1 for both), call get userModel/{id} while logged in with any of the users and you can access both users details

# Expected result

User not being able to access another user's account

**Comment by dhmlau** [comment]
@strongloop/sq-lb-apex , PTAL.

**Comment by jannyHou** [comment]
Hi @beirdostudio I am trying to reproduce your failure, have you tried example repo https://github.com/beeman/loopback-example-multiple-user-models?

I just tried with that repo but I had the opposite result as you described, I could not get a customer(or vendor)'s info after login. Maybe I test it in a wrong way, @strongloop/sq-lb-apex people more familiar with that example can give it a try.

My steps:
- git clone the repo, `npm i`, `node .`
- `post /Customers/login ` with customer1's credential 
  ```
  "email": "customer1@example.com", "password": "password"
  ```
- try `get /Customers/{id} ` with `id: 1`, get 401 error

**Comment by bajtos** [comment]
@beirdostudio what is your LoopBack version? We have fixed similar issues relatively recently, see e.g. https://github.com/strongloop/loopback/pull/3666 and https://github.com/strongloop/loopback/pull/3675. Could you also verify that your application is correctly configured to support multiple user models as described in our [docs](http://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#access-control-with-multiple-user-models)?

It would really help us if you could create a sample application reproducing the problem per our [Bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report).

**Comment by beirdostudio** [comment]
@bajtos sorry for the very late response, I did not follow the part of the doc where it talks about multiple user models so it's my bad, the app changed since then so it's not using different user models anymore but I'm still interested in that so as soon as I get some time on my hand, I'll make a sandbox app to try it out and report back.
@jannyHou did you forget to set the access token after logging in if you're using the explorer? I'm just saying that because I don't see it in your steps to reproduce part.

**Comment by beirdostudio** [comment]
Hello again,
So I switched back to multiple user models and configured them following the doc, now I'm getting a warning in the console:
`The app configuration follows the multiple user models setup as described in http://ibm.biz/setup-loopback-auth The built-in role resolver $owner is not currently compatible with this configuration and should not be used in production.`
When I try GET /usermodel/{id} after logging in and setting the accessToken, I get an error 401.
If I understand correctly, the dynamic role $owner doesn't work anymore with this setup, did I miss something or do I have to write a custom role resolver to be able to access the user details endpoint?
