### ISSUE TITLE
Unexpected Element is generated when model has property named "Type" in the complex object.

### ISSUE THREAD

**Issue by bhavnagyanchandani** [strongloop/loopback#3744]
when creating a model, I have an element which is a complex-type property with one element named “type” in the model. While using this model to pass the payload to the connector, than  LoopBack is not passing the expected JSON to the connector instead it is passing [object object]. Any pointers on how to fix it  or is this a known isse?
For reference, attached is the sample model file.
[operation.zip](https://github.com/strongloop/loopback/files/1597124/operation.zip)

**Comment by pbouda** [comment]
I got the same problem, my complex property looks like this:

```
  "properties": {
    "nestedActions": {
      "type": [
        {
          "value": "string",
          "description": "string",
          "type": "string",
          "label": "string"
        }
      ]
    }
  }
```

Whenever I store some nestedActions all the entries in the db array are just strings "[object Object]". If I remove the `type` property in the definition everything works fine. I use MongoDB.

**Comment by bhavnagyanchandani** [comment]
@raymondfeng - I have tried to add a simplified model for your reference:

[operation.zip](https://github.com/strongloop/loopback/files/1618840/operation.zip)

This is how it looks on Swagger UI:

![image](https://user-images.githubusercontent.com/17310585/34774579-dd6b3170-f635-11e7-8f7f-65149c961f1f.png)


This is how it is sent to the connector:
![image](https://user-images.githubusercontent.com/17310585/34774605-f3f2e000-f635-11e7-8ccf-1c37286c68d1.png)

Please Note the "[object Object]\" in the data.

Please suggest how we could resolve this. This is the issue only when we have "type" in the property name. Also, Note It is working perfectly fine with other property names.
