### ISSUE TITLE
findOrCreate method is not working when datasource is memory.

### ISSUE THREAD

**Issue by taimoor736** [strongloop/loopback#3747]
I have this function. If the Selected datasource is memory it gives me this warning.
> function findOrCreateAdminAccount() {
>     return new Promise((resolve, reject) => {
>       Account.findOrCreate({
>         where: {
>           username: adminUser.username,
>           email: adminUser.email,
>         },
>       }, adminUser).then(([adminUserResponse]) => resolve(adminUserResponse)).catch(err => reject(err));
>     });
>   }

`(node:30566) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ValidationError: The `Account` instance is not valid. Details: `email` Email already exists (value: "admin@email.com"); `username` User already exists (value: "admin").`

It works fine if the selected datasource is mongo.

**Comment by phuttipong** [comment]
I also face the same issue. Just to give more information here that findOrCreate() work well on other models. I found this issue on Model that extends Loopback.user

**Comment by kjdelisle** [comment]
@taimoor736 Would you be able to reproduce or perhaps debug the problem?

Ideally, a pull request to fix the issue would be best, though I understand if you don't have the time, or aren't interested.
