### ISSUE TITLE
npm install -g loopback-cli Win7 "ERR! 404 Not Found: pinkie-promise@^2.0.0"

### ISSUE THREAD

**Issue by mike-a** [strongloop/loopback#3749]
*** Note:  https://github.com/floatdrop/pinkie-promise/issues/4 reports pinkie-promise not being available today. Perhaps there should be a catch test to first dicover if the package is available, followed by graceful exception reporting if not.

# Description/Steps to reproduce
Installation bug...
$ npm install -g loopback-cli
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm ERR! code E404
npm ERR! 404 Not Found: pinkie-promise@^2.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Master\AppData\Roaming\npm-cache\_logs\2018-01-06T21_20_24_668Z-debug.log

Log extract...
1251 http fetch GET 404 https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz 1650ms
1252 silly fetchPackageMetaData error for pinkie-promise@^2.0.0 404 Not Found: pinkie-promise@^2.0.0
1253 verbose stack Error: 404 Not Found: pinkie-promise@^2.0.0
1253 verbose stack     at fetch.then.res (C:\Users\Master\AppData\Roaming\npm\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
1253 verbose stack     at tryCatcher (C:\Users\Master\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
1253 verbose stack     at Promise._settlePromiseFromHandler (C:\Users\Master\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
1253 verbose stack     at Promise._settlePromise (C:\Users\Master\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
1253 verbose stack     at Promise._settlePromise0 (C:\Users\Master\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
1253 verbose stack     at Promise._settlePromises (C:\Users\Master\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
1253 verbose stack     at Async._drainQueue (C:\Users\Master\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
1253 verbose stack     at Async._drainQueues (C:\Users\Master\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
1253 verbose stack     at Immediate.Async.drainQueues (C:\Users\Master\AppData\Roaming\npm\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
1253 verbose stack     at runCallback (timers.js:789:20)
1253 verbose stack     at tryOnImmediate (timers.js:751:5)
1253 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)

# Additional information

After discovering this failed installation attempt I tried a standalone install...
$ npm install --save pinkie-promise
npm ERR! code E404
npm ERR! 404 Not Found: pinkie-promise@latest

Conclusion: pinkie-promise missing when called from loopback install script.

**Comment by dhmlau** [comment]
@mike-a , I just tried it and it seems to be working for me.  You might want to give it a try as you mentioned `pinkie-promise` was not available earlier.  Thanks.

Here is my output:
```
├─┬ loopback-cli@4.1.0
│ └─┬ generator-loopback@5.5.0
│   └─┬ yeoman-generator@0.24.1
│     └─┬ find-up@1.1.2
│       └── pinkie-promise@2.0.1 
```

**Comment by dhmlau** [comment]
@mike-a, closing this issue as we believe your issue has been resolved.  Feel free to ping us again if the problem persists.  Thanks.
