### ISSUE TITLE
BelongsTo Relationship doesn't respect foreignKey

### ISSUE THREAD

**Issue by luncht1me** [strongloop/loopback#3751]
Not sure if this is intended, but it took me a moment to figure this out.

I'm using mongodb connector, for reference. All packages are updated to latest via npm.

I have a Mixin to set relationships for authors and recording modifications to a model, say a news article.
The definitions are as follows, where `m` is the target model:
```js
// Define relationships
Model.belongsTo(m, {
	foreignKey: 'authorId',
	as: 'author'
});

Model.belongsTo(m, {
	foreignKey: 'modifiedBy',
	as: 'modifiedBy'
});
```

This Mixin also includes an operation hook to update author / modifiedBy relationships:
```js
// Set author on save
Model.observe('before save', function setAuthor(ctx, next) {
	// Load in context (requires luncht1me/loopback-connector-mongodb to work)
	var lbCtx = LoopBackContext.getCurrentContext();
	var author = lbCtx.get('currentUser');
	if (ctx.instance) {
		// Newly created instance, set author
		ctx.instance.authorId = author.id;
	} else {
		// Updating an existing instance, just change the modifiedBy.
		ctx.data.modifiedBy = author.id;
	}
	next();
});
```

The thing is, I cannot get `ctx.data.modifiedBy` to save. It appears the relationship is not respecting the foreignKey I have assigned to it.

In order to get this Mixin to work, I had to use the standard default key which loopback would automatically assign via the `as` field in the relationship definition, which in this case is `modifiedById`.

So, changing `ctx.data.modifiedBy = author.id;` to `ctx.data.modifiedById = author.id;` works as intended but it was a little frustrating to figure this out as one would expect the key in the definition to be respected.

Just thought I'd bring this to attention. Is this a bug, or just the intended workings of the BelongsTo relationship? The docs indicate that the key here should be respected unless I was interpreting it incorrectly.

**Comment by rodolph66** [comment]
I'm  a beginner, working on:
windows 10
loopback latest version (4.1.0) - this the cli generated version 
 I'm trying to create two very simple models with "belongsTo" "HasMany" relations, such as Products the belong to Categories (or Devices of Types). So far every attempt in creating this relation between the two models, using the generator, or manually, by editing the .json files of the models as per the documentation, have ended up with loopback failing to launch with the following error:
![lb_relation_error](https://user-images.githubusercontent.com/9017114/35792229-81d35ee8-0a65-11e8-9efa-e3b741ef7592.png)

One thing to note is that both models have the ids generated manually 

`{
  "name": "Device",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "number",
      "id": true,
      "generated": false,
      "required": true
    },...`

I have been at this for days now and on different machines, It seems that I am missing some key configuration... Any help is appreciated.

**Comment by rodolph66** [comment]
It seems that the id's has nothing to do with this... It is still failing no matter what combination I try.
