### ISSUE TITLE
error TS2305: Module has no exported member 'get'.

### ISSUE THREAD

**Issue by aiherrera** [strongloop/loopback#3753]
Hi, I am trying loopback and following the docs, after installed, when I run **npm start** I get the following 
error: 

`src/controllers/ping.controller.ts(1,9): error TS2305: Module '"D:/back/node_modules/@loopback/rest/index"' has no exported member 'get'.`

when I look for the controller generated by the cli:

```
import {get, ServerRequest} from '@loopback/rest';
import {inject} from '@loopback/context';

/**
 * A simple controller to bounce back http requests
 */
export class PingController {
  constructor(@inject('rest.http.request') private req: ServerRequest) {}

  // Map to `GET /ping`
  @get('/ping')
  ping(): object {
    return {
      greeting: 'Hello from LoopBack',
      date: new Date(),
      url: this.req.url,
      headers: Object.assign({}, this.req.headers),
    };
  }
}
```
the compiler looks like can't find the @get module when tries to import it.
any thoughts, thanks in advance.

**Comment by raymondfeng** [comment]
The decorators have been refactored to a new module `@loopback/openapi-v2`. Please upgrade the CLI: 

`npm i -g @loopback/cli`

And regenerate your app.

**Comment by raymondfeng** [comment]
@jannyHou We might want to re-export the decorators from `@loopback/rest` to keep backward compatibility.

**Comment by jannyHou** [comment]
Sorry for replying late.
@raymondfeng Sure, making the PR now, the document&example update will be a little slower
