### ISSUE TITLE
How to learn ?

### ISSUE THREAD

**Issue by Sanbornzhang** [strongloop/loopback#3757]
If i want to learn loopback framework [ deep logic]
Where should i start

1. start with loopback source code? 
2. or something 101 doc?

**Comment by dhmlau** [comment]
@Sanbornzhang , is there anything in particular that you're interested in?  Our documentation can be found here: http://loopback.io/doc/en/lb3/.  

Please also note that we're working on the next version of LoopBack (LoopBack 4) which is currently in Developer Preview release.   It's a rewrite of the existing LoopBack framework and more extensible.  More information can be found here: http://loopback.io/doc/en/lb4/

**Comment by Sanbornzhang** [comment]
yes,  like how to register model(found form source code),how to register middleware. so i mean "If someone wants to join this project,where to start", where is the Developer doc? or flow chart(like http req -> express -> middleware acl  -> middleware parse  -> middleware router -> before hook  ...)

**Comment by dhmlau** [comment]
@Sanbornzhang , I'd suggest you check out the official documentation: http://loopback.io/doc/en/lb3/.  The [Core concepts](http://loopback.io/doc/en/lb3/LoopBack-core-concepts.html), [Getting Started](http://loopback.io/doc/en/lb3/Getting-started-with-LoopBack.html) and the [tutorials](http://loopback.io/doc/en/lb3/Tutorials-and-examples.html) would be a good place to start. 
Hope it helps.

**Comment by dhmlau** [comment]
@Sanbornzhang , does the above information help?  Is this issue good to close?  Thanks.

**Comment by dhmlau** [comment]
Closing this issue as we believe this issue has been resolved.
@Sanbornzhang , feel free to reopen if you still have outstanding questions.  Thanks.
