### ISSUE TITLE
I am working on a project  for internal use in IBM,could you please help me on sending email from IBM-email by nodejs

### ISSUE THREAD

**Issue by cjjchu** [strongloop/loopback#3763]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
@cjjchu, there is an internal community using #loopback-at-ibm Slack channel.  Feel free to contact us on that channel.  
With that, I'm closing the issue.  Thanks.
