### ISSUE TITLE
list object owned by owner

### ISSUE THREAD

**Issue by jkunwar** [strongloop/loopback#3766]
Hi!
i am very new to loopback and i am having problem with listing all objects owned by me.
here is my acl
{
"principalType": "ROLE",
"principalId": "$owner",
"permission": "ALLOW",
"property": "find"
},

but i am able to list object by id

{
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "findById"
    },

**Comment by daniloprates** [comment]
+1
