### ISSUE TITLE
How to get nested master-detail or master detail detail query in Loopback?

### ISSUE THREAD

**Issue by rsa408** [strongloop/loopback#3771]
I have category and category_subs, master-detail model, post model belongs to category_subs. In the following code, I can get master-detail of both but I don't know how to include the post to them or even attachment model of the post to the remote method.

```
module.exports = function (Category) {
    Category.categorySubs = function (id, cb) {
    Category.find({
        where: {
          id: id
        },    
        include: {
            relation: 'categorySubs',
          scope: {
              include: 'category_subs'
          }
        }
      },
      function (err, posts) {
        cb(null, posts);
      });
  }
 Category.remoteMethod('categorySubs', {
    accepts: {
      arg: 'id',
      type: 'string'
    },
    returns: {
      arg: 'ID',
      type: 'string'
    },
    http: {
      path: '/iteminfo',
      verb: 'get'
    }
  });
```

**Comment by atherdon** [comment]
@rsa408 can you post your json files, related to your models. So i can add them to my project and test your issue?

**Comment by atherdon** [comment]
btw, check this method from my project. maybe this will help you.
https://github.com/atherdon/groceristar/blob/master/server/models/department.js#L133
Result: 
![image](https://user-images.githubusercontent.com/1469198/35200741-237360ba-ff24-11e7-9579-04cb5f163a65.png)

**Comment by rsa408** [comment]
Dear @atherdon thanks for your reply  I post here the JSON of models,

**category:**
```
{
  "name": "category",
  "plural": "categories",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "categorySubs": {
      "type": "hasMany",
      "model": "category_subs",
      "foreignKey": "catgory_id"
    }
  },
  "acls": [],
  "methods": {}
}


```
**category_subs**
```
{
  "name": "category_subs",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "sub_name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "posts": {
      "type": "hasMany",
      "model": "post",
      "foreignKey": "category_sub_id"
    }
  },
  
  "acls": [],
  "methods": {}
}

```
**Post:**
```
{
  "name": "post",
  "plural": "posts",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "caption": {
      "type": "string",
      "required": true
    },
    "descriptions": {
      "type": "string",
      "required": true
    },
    "time": {
      "type": "string",
      "required": true
    },
    "date": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "user_id"
    }
  },
  "acls": [],
  "methods": {}
}



```

the fallowing code returns all a posts and category_subs 

Category.categorySubs = function (id, cb) {
   Category.find({
        where: {
          id: id
        },

        include: {
          relation: 'categorySubs',
          scope: {
              include: {
                relation : 'posts',
                scope : {
                  include : 'post'
                }
              },
              scope : {
                include : 'category_subs'
              }
          }

        }
      },
      function (err, posts) {
        cb(null, posts);
      });
  }

    Category.remoteMethod('categorySubs', {
    accepts: {
      arg: 'id',
      type: 'string'
    },
    returns: {
      arg: 'ID',
      type: 'string'
    },
    http: {
      path: '/iteminfo',
      verb: 'get'
    }
  });

**Comment by rsa408** [comment]
This return all category_subs and pots. In somewhere I had to limit posts only for selected category_sub model.
