### ISSUE TITLE
Critical crash when setting user email to undefined where case sensitive email is disabled

### ISSUE THREAD

**Issue by nitro404** [strongloop/loopback#3772]
# Description/Steps to reproduce

If you disable case sensitive emails for an extended user model and attempt to set the value of the extended model's email to undefined, the user email setter attempts to convert an undefined value to lower case and invokes the extended user created callback twice.

# Link to reproduction sandbox

https://github.com/nitro404/loopback-case-insensitive-user-email-sandbox

# Expected result

API should emit an error for the member object not having an email address.

It should also not attempt to convert an email address that is not a string to lower case or invoke the member created callback twice.

# Additional information

Upon investigation it appears as though a simple type check is missing from the user model email setter when case sensitive email addresses are disabled.

Additionally, it seems as though the case insensitive email check in the access operator of the user model does not account for patterns used in the like operator when applying a where filter to a query, ie. ctx.query.where.email.like since the email address value is currently forced to lower case.

I suspect this should be a fairly simple fix, but I'm not sure what the preferred approach might be for both of these situations. If desired, I would be happy to submit a pull request if it is quicker.

**Comment by bajtos** [comment]
@nitro404 thank you for reporting this issue. I am afraid we don't have much bandwidth right now to look into the problem. It would be great if you could go ahead and submit a pull request fixing the problem, we can discuss more details there. Thanks!

**Comment by bajtos** [comment]
Fixed by #3779.
