### ISSUE TITLE
Object.assign weird behavior with Models

### ISSUE THREAD

**Issue by michaelerobertsjr** [strongloop/loopback#3777]
# Description/Steps to reproduce
Create a remote method in a model, then attempt to merge the results of a find, with another object.  The model's data will return with getters and setters instead of the data.

Assuming you do a `user.find()` against a user model, the resulting array should be mapable and you should be able to merge the objects if needed.

Example:
```
const newData = usersReturnedFromModel.map(user =>
   Object.assign({}, user, { "new": "value"}));
console.log(JSON.stringify(newData));
```

# Expected result

Expected to get:
```
[{"Key":"2b621b2e924","tra":"t1","studentType":"FULL"}, ...]
```
# Actual result

Instead what I found was I got:
```
[{ "__cachedRelations":{},"__data":{"Key":"2b621b2e924","tra":"t1","studentType":"FULL","__strict":false,"__persisted":true }, ...]
```
I assume because object.assign is doing its process using getters and setters that the loopback getters and setters are getting borked.

# Workaround

use something like:
```
const temp = Object.assign({}, user.__data)
```

This was tricky to find in my app, and doesn't appear to be documented.  Also, my hack doesn't seem like a solid solution.

Any better way to fix this??

**Comment by raymondfeng** [comment]
Use `user.toJSON()`

**Comment by funkizer** [comment]
toJSON() would return a string right? .toObject() does what he's looking for. It's weird this is impossible to find in the docs if it even is there, I found it by looking at the source code (which is fun, but...)  :)
