### ISSUE TITLE
Bug: nestRemoting bad applied over a referencesMany Model

### ISSUE THREAD

**Issue by sebastianfelipe** [strongloop/loopback#3778]
# Description/Steps to reproduce
Supose that model A is a model which contains a relation referencesMany with model B. Then if a model C extends the model A functionalities (endpoints) using nestRemoting, we have a problem.

The error is "Error: Invalid remote method: `__exists__relatedModelBName`"

Thanks.

**Comment by JaFF92** [comment]
I am running into the same problem here. My setup is similar to @sebastianfelipe 's, after I had to change a relation type from "embedsMany" to "referencesMany":

**PersistedModelA** embedsOne **ModelB**
**ModelB** referencesMany **PersistedModelC**
**PersistedModelA**.nestRemoting("**ModelB**")

Also getting the error
"Cannot load the LoopBack application: Invalid remote method: `__exists__PersistedModelC`"

Removing nestRemoting for PersistedModelA removes the error - but also the sweet advantages of nested queries.

**Comment by israelglar** [comment]
That bug is still not solved. Any updates?

**Comment by Code-Crash** [comment]
Any Update on this issue?

**Comment by israelglar** [comment]
I submitted a PR here https://github.com/strongloop/loopback-datasource-juggler/pull/1614
But had some bugs compiling and didn't  have much time to look at it again :/

**Comment by sebastianfelipe** [comment]
Try doing this. At least, this was my patch.

```
 // Added because referencesMany bug
  ModelA.prototype.__exists__modelBs = function(fk, options, cb) {
    cb = cb || loopbackUtils.createPromiseCallback();
    let self = this
    fk = utils.validId(fk)
    let types = self['modelBIds'].map(item => utils.validId(item))
    if (types.indexOf(fk) > -1) cb()
    else {
      let error = new Error()
      error.statusCode = 404
      cb(error)
    }
    return cb.promise
  }```

And done. The inheritance is solved. But wait... that's another bug haha, but for now it solve that problem.

The new bug is found in this thread -> https://github.com/strongloop/loopback/issues/4002

Good luck!

**Comment by bajtos** [comment]
Sorry for the silence on our side. I am afraid we don't have bandwidth to investigate and fix this bug, but I am happy to help you along the way if you decide to contribute the fix yourself.

Here are is our contributing guide to get you started: https://loopback.io/doc/en/contrib/code-contrib.html

Just remember to include one or more tests that demonstrate the problem, fail with the current version and pass with your fix in place.
