### ISSUE TITLE
User logout trigger error accessToken is required

### ISSUE THREAD

**Issue by rahulrkr08** [strongloop/loopback#3785]
I am getting error on when hitting logout API.

### Query Parameter
curl -X POST http://localhost:3000/api/users/logout?access_token=$ACCESS_TOKEN

### Getting below error

{
    "error": {
        "statusCode": 401,
        "name": "Error",
        "message": "accessToken is required to logout",
        "status": 401
   }
}

**Comment by rahulrkr08** [comment]
Sorry for the wrong posting, I missed to uncomment enableAuth() function. Thanks

**Comment by Sheikh-Aman** [comment]
@rahulrkr08 Could you please tell a bit more on where did you uncomment the enableAuth() function?
Is this the default User model, or a derived one?

**Comment by vgmcglaughlin** [comment]
In case anyone else runs into this, see [this example](https://loopback.io/doc/en/lb3/Authentication-authorization-and-permissions.html#initial-setup) for calling the `enableAuth()` function on server startup.
