### ISSUE TITLE
Simultaneous requests result in pending status and no response is received

### ISSUE THREAD

**Issue by aravindvaideesh** [strongloop/loopback#3786]
Hi,

I have an issue that has been bugging me for a long time. Simultaneous requests made from front end angular application to my loopback application in the backend results in one of the requests to go into pending state. I have attached a screenshot below where the last request shows a pending state. This was reproduced by refreshing the page , so that API calls part of the entire route get called again. 
However when I do not refresh,  but come to this page from its parent route the API returns successfully. I have attached another screenshot depicting the same. 

Also I did replace my entire backend with another project written in PHP and made my API calls from the front to this PHP layer (without changing much of the front code except for the URLs) and I did not experience this problem whatsoever. I refreshed multiple times and yet all the APIs returned successfully.

Should I make any changes to my loopback app to overcome this ? It would be great if someone can help me out with this ?

Copy+paste the output of these two commands:
  darwin x64 6.11.3
 ├── loopback@2.39.0
├── loopback-boot@2.27.0
├── loopback-connector-mysql@5.2.0
├── loopback-context@3.3.0
├── loopback-datasource-juggler@2.55.3

![pending_failed](https://user-images.githubusercontent.com/32127957/35676506-05f8b926-0772-11e8-9379-ab259432ca50.png)

![success](https://user-images.githubusercontent.com/32127957/35676974-de93fc0e-0773-11e8-990b-f035ca0fa979.png)

**Comment by sugan-ysquare** [comment]
does anyone knows the root cause of the issue, if anyone knows kindly address this
