### ISSUE TITLE
Help Wanted: loopback crashes at any attempt at creating "BelongTo" "HasMany" relation

### ISSUE THREAD

**Issue by rodolph66** [strongloop/loopback#3788]
I have worked with loopback (v3) a few months back I did not encounter this before.
Any attempt at creating a BelongTo - HasMany relation between two models end up in the app/loopback failing. 

To reproduce simply create any basic two models such as Category and Product and attempt to create the described relation. 
Note there is an egghead Loopback introduction course (very concise) which creates such models and the relation described. Creating this scenario always worked in the past. This time (after many attempts) it simply does not go through.

One difference noticed from before was the addition in the generator of the two questions: "Allow relation to be nested in API" and "Disable relation from being included"

The following shows the generator steps:
![generator](https://user-images.githubusercontent.com/9017114/35818108-9832171c-0ab8-11e8-850d-1af7c340e125.jpg)

in separate terminal (win 10) the following occurs on completing the second relation steps:
![error](https://user-images.githubusercontent.com/9017114/35818151-b3779678-0ab8-11e8-8875-69bbb5dd81e3.jpg)

I have tried in so many combination to bypass this error but nothing worked. Again, this never happened during mid last year.
Finally, I am working under windows 10 and did not actually try this under macOS or Linux though both systems are available for me.

Thank You

**Comment by rodolph66** [comment]
After reviewing the older files, in which this type of relation worked seamlessly, I noted that the inclusion of the "options" property in the "relations" section of the .json file might have been the cause, since after removing the 

`      "options": {
        "nestRemoting": true,
        "disableInclude": true
      }`

The app worked again with the relation behaving as intended. For now I will continue without the options part though I read that the options was added to address some security issues.

**Comment by jannyHou** [comment]
@rodolph66 could you post the `loopback-datasource-juggler` and `loopback` version here?
And also the last version that doesn't have this problem if you know it.

**Comment by rodolph66** [comment]
Did not use loopback since Aug 2017 at which I had...
loopback ver as per package.json: 3.0.0
loopback-datasource-juggler ver: 3.9.3
Now... respectively is 3.0.0 and 3.15.0

**Comment by jannyHou** [comment]
@kjdelisle could you help take a look of this interrupt issue? Thanks!

**Comment by kjdelisle** [comment]
I can confirm that the issue is related solely to the `nestRemoting` option (using `disableInclude` exclusively doesn't cause any problems).

I'm going to start tracking down the source of the fault now.

**Comment by kjdelisle** [comment]
@rodolph66 So I'm almost certain I've found the flaw. Would you be able to clone a copy of my branch from the linked pull request and see if it solves your problem?

I've functionally tested it myself as well as made sure the test changes in the PR reproduce it, but I want to be sure that there isn't more than one issue at play here.

**Comment by kjdelisle** [comment]
@rodolph66 I've merged the fix and I'll be releasing it shortly! :tada:

**Comment by kjdelisle** [comment]
3.18.2 has been released!

**Comment by rodolph66** [comment]
Thanks, I will give it a go... Apologies for not coming back I have a full time job that has nothing to do with computing. I am now suffering with another issue. One that is again taking me days of continues trials before I decide to post something here..

**Comment by rodolph66** [comment]
Great, I just tested it out and it is now working fine. Thanks again and all the best.
