### ISSUE TITLE
Node.js and MSSQL ram spike if the model property casing is incorrect in the filter parameter

### ISSUE THREAD

**Issue by jhay07** [strongloop/loopback#3792]
I am new to loopback, installed latest version 3.0.0

I created my sample project by using the CLI. and generated my Customer model using this: https://gist.github.com/honestserpent/a09f8a625aa1b142d31b62f22fef747b looks fine so far.

I tried to do basic query like /Customers?filter[where][**Email**]=email@address.com and seems to work well. However, when i try to put an incorrect casing on the property ([**E**mail] into [**e**mail]), my nodejs app will get a memory spike as well as the MSSQL server, and will cause a crash on the nodejs app and the MSSQL service will hog the whole RAM capacity. I checked the sql profiler and it does not even execute any scripts from loopback.

Is there a configuration that handles the casing of the url in loopback or am I missing something here?

**Comment by bajtos** [comment]
Hi @jhay07, thank you for reporting the issue. Could you please provide us with detailed steps how to reproduce the problem locally on our machines? A small application based on our sandbox (see see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report) would be best.
