### ISSUE TITLE
Near filter is very slow

### ISSUE THREAD

**Issue by TuNi54** [strongloop/loopback#3794]
Hi,

I have this kind of request for my LoopBack 3 project : 

```

var here = new loopback.GeoPoint({lat:"46.44477", lng:"2.6635"});

Car.find({
      
      limit : 50,
      skip :  0,
      where : {
          testing : "false",

          coords : {
              near : here, 
              maxDistance : "50000", 
              unit : "meters"
          }
      },
      
      include : [{
        relation: "User"
      }]
```
But the response is very very slow. More than 1 min in local and 15s with Heroku. 

Is someone had the same issue ?

Database : mongodb

Thank you

**Comment by bajtos** [comment]
Hi @TuNi54, thank you for reporting the issue. We don't have bandwidth to take a close look into this problem, but I can at least give you some pointers to get you started.

The first step is to find out what query is sent to MongoDB. For example, you can run your app on your local machine with debug log enabled (`DEBUG=loopback:connector*`), make the slow query and see what the connector reported.

AFAIK, our MongoDB connector sometimes does not know how to translate a query containing "near" filter into a MongoDB query, in which case it falls back to fetching _all records_ and performing the query in-memory. This would explain the long response times you are seeing.

Possibly related issues:
 - https://github.com/strongloop/loopback/issues/2917
 - https://github.com/strongloop/loopback-connector-mongodb/issues/310
