### ISSUE TITLE
How to integrate with Object Storage Service Lite version in IBM Cloud 

### ISSUE THREAD

**Issue by TopGunBasten** [strongloop/loopback#3795]
I can custom a remote method to call ibm-cos-sdk
the api of https://github.com/IBM/ibm-cos-sdk-js#example-code

**Comment by bajtos** [comment]
Hello, I am afraid I don't understand what are you trying to achieve, @TopGunBasten.

In general, writing custom remote methods is documented here: https://loopback.io/doc/en/lb3/Remote-methods.html

In your custom remote method, you can invoke any Node.js API you like, including ibm-cos-sdk-js.

Are you perhaps looking integration between our loopback-component-storage and IBM Object Storage Service?

@raymondfeng do you have any thoughts on this?

**Comment by TopGunBasten** [comment]
hi, bajtos 
I have fixed that, but I think need a feature like storage component in loopback like integrating with AWS S3 Service
