### ISSUE TITLE
How to add custom functions to ctx.instance

### ISSUE THREAD

**Issue by xavitb3** [strongloop/loopback#3796]
I'm seeing myself needing to know if an user has a role Admin or if his account is active in "before save" and "after save" model hooks in different files and defining functions that accept the ctx.instance as a parameter and doing the checks. 

```
ApplicationUser.observe('after save', (ctx, next) => {
      const userInstance = ctx.instance;

      if (isAdmin(userInstance) && ctx.isNewInstance) {
       //do something
      }
      else {
        next();
      }
});
```

Is there a way to do something like this?

```
ApplicationUser.observe('after save', (ctx, next) => {
      const userInstance = ctx.instance;

      if (userInstance.isAdmin() && ctx.isNewInstance) {
       //do something
      }
      else {
        next();
      }
});
```

The only way I've come up is creating a custom model file that accepts an userInstance as the only parameter and returns a custom userInstance with any custom methods I want but it would be nice not to do this everytime I need my custom methods

**Comment by kjdelisle** [comment]
The [custom remoting phases](https://loopback.io/doc/en/lb3/Using-current-context.html#use-a-custom-strong-remoting-phase) are what I imagine you're looking for.

I lifted the example and tested it out on a dummy app to see what it would do.

**./server/boot/is-admin-phase.js**
```js
'use strict';

var isAdmin = require('../../lib/is-admin');

module.exports = function(app) {
  app.remotes().phases
    .addBefore('invoke', 'options-from-request')
    .use(function(ctx, next) {
      if (ctx && ctx.args && ctx.args.options && ctx.args.options.accessToken) {
        const User = app.models.User;
        User.findById(ctx.args.options.accessToken.userId, function(err, user) {
          if (err) return next(err);
          ctx.args.options.currentUser = Object.assign(user, {
            isAdmin: isAdmin,
          });
          next();
        });
      } else {
        return next();
      }
    });
};
```

**./common/models/category.js**
```js
'use strict';

module.exports = function(Category) {
  Category.observe('access', function(ctx, next) {
    // Note: This ctx object doesn't contain the "args" property you used in the custom phase!
    if (ctx.options.currentUser.isAdmin()) {
      console.log('Hurray!'); // Yay!
    }
    return next();
  });
};
```

**Comment by kjdelisle** [comment]
In my above example, the `isAdmin` function is always returning true, so it's up to you to define what makes an "admin", but the concept should hold for your use-case.

**Comment by bajtos** [comment]
I would recommend to add your custom method to User prototype. One option is to define your custom User model extending the built-in User model, see http://loopback.io/doc/en/lb3/Extending-built-in-models.html. Another option is to write a boot script that will add your custom method directly to the built-in User model, see http://loopback.io/doc/en/lb3/Adding-remote-methods-to-built-in-models.html#boot-script.
