### ISSUE TITLE
Is there a way to actually validate user/access-token on custom route?

### ISSUE THREAD

**Issue by bmrinal** [strongloop/loopback#3798]
I need to validate a custom route that I created before sending the response. is there a way to do so?

Here is how my custom route looks:

```
app.get(/^((?!\/api\/).)*$/,function(req,res){
    res.sendFile(path.resolve('client/index.html')) //this should be served only if user's access token is valid
  })
```

**Comment by bajtos** [comment]
Our built-in token middleware validates the access token and stores valid access tokens in the `request` object. I think the following code is what you want:

```js
app.get(/^((?!\/api\/).)*$/,function(req,res){
  if (!req.accessToken) {
    // reject anonymous users here
  } else {
    res.sendFile(path.resolve('client/index.html'));
  }
});
```

By default, `loopback#token` middleware should be automatically executed by `loopback#rest` middleware. I am not sure in which order the REST middleware and custom Express routes are executed, you may need to to configure `loopback#token` middleware explicitly in your `server/middleware.json` file. This middleware typically belongs to the "auth" phase. Related reading: https://loopback.io/doc/en/lb3/middleware.json.html
