### ISSUE TITLE
PersistedModel.upsert increases Heap mem until the ms crashes 

### ISSUE THREAD

**Issue by MarianZoll** [strongloop/loopback#3801]
# Description/Steps to reproduce

BUG: Heap Memory is increasing significantly until it crashes the microservice

- Cloudant is connected with the in-built cloudant connector
- Running [PersistedModel.upsert](https://apidocs.strongloop.com/loopback/#persistedmodel-upsert)(data, callback) with a large number of requests ~300.000 documents á 4.8KB size.
- After some insertion time (and continuous increase of heap-memory), the application crashes with:

![image](https://user-images.githubusercontent.com/14123913/36299262-7e334af6-12fc-11e8-9758-07a13ddbc0f8.png)

# Link to reproduction sandbox
Running upserts with a large number of docs and insertions. If necessary can produce a sample function.

# Expected result
Heap-Memory should not increase significantly or workaround should be implemented.

# Actual Results
Application crashes due to Heap Memory consumption.

With every ```RESUME```, 300 documents are added to the database. Concurrently, the current CPU and memory usage is displayed using:
```
console.log(process.cpuUsage());
console.log(process.memoryUsage());
```
![image](https://user-images.githubusercontent.com/14123913/36299186-2ea6a58c-12fc-11e8-847d-4ec7c0868adc.png)

# Additional information

If additional information and/ or snippets are required, I am happy to help.

  node -e 'console.log(process.platform, process.arch, process.versions.node)' -> `darwin x64 8.7.0`
  npm ls --prod --depth 0 | grep loopback:
```
├── loopback@3.18.1
├── loopback-boot@2.27.0
├── loopback-component-explorer@5.2.0
├── loopback-connector-cloudant@2.0.4
├── loopback-connector-mongodb@1.18.1
├── loopback-connector-rest@3.1.0
├── loopback-datasource-juggler@3.12.0
```

**THANKS FOR ANY HELP!**

**Comment by raymondfeng** [comment]
Please take heapdumps per https://strongloop.com/strongblog/how-to-heap-snapshots/ to see what objects are not GCed.

**Comment by MarianZoll** [comment]
@raymondfeng 

Took several snapshots (every 3mins). Also logged the ending of the application logic in the running system. It seems like the `PersistedModel.upserts` continue inserting documents to the cloudant after the interface call (app logic) ended. With the continous increase of heap memory due to this buffering, the apllication crahses. Screenshot below indicates the heap memory size during and after the interface logic:

Also uploaded the heapdumps to Box (only as an IBMer, you are able to access them):
https://ibm.box.com/s/81q56y09tz18pzm79wl9ixe4r45lvd06

![image](https://user-images.githubusercontent.com/14123913/36491061-83318434-1732-11e8-937b-532bd20c7d18.png)

Last attachement showing the cloudant monitoring system after the interface finished (due to the logs):
![image](https://user-images.githubusercontent.com/14123913/36587450-82a9676c-1885-11e8-9fd9-35c529fd5e6b.png)

**Comment by raymondfeng** [comment]
![image](https://user-images.githubusercontent.com/540892/37665859-6ad9da3c-2c1b-11e8-9977-90262895b5ad.png)

It seems the cloundant driver is not releasing http requests. As a result, all request/response data are kept in http ClientRequest objects. Maybe you are sending requests too fast before Cloudant can respond.
