### ISSUE TITLE
AccessToken.validate doesnt work as expected if AccessToken model stored in a database.

### ISSUE THREAD

**Issue by ninoguba** [strongloop/loopback#3802]
If the AccessToken model is stored in a DB, the created property will be stored as its UTC value. This becomes an issue when the AccessToken.validate function computes the elapsedSeconds below:

```
(now - created) / 1000
```

The now value is in local server time while the created value is in UTC.  This can make a valid accessToken (based on the TTL) become invalid as the computation of the elapsedSeconds will be wrong due to the timezone discrepancy.

Here's how I observed this when I added some logging statements:

**Scenario 1: AccessToken's datasource = DB**

```
ACCESSTOKEN: now: Fri Feb 16 2018 10:11:05 GMT-0800 (PST)
ACCESSTOKEN: created: Thu Feb 15 2018 16:00:00 GMT-0800 (PST)
ACCESSTOKEN: elapsedSeconds: 65465.495
ACCESSTOKEN: secondsToLive: 900
ACCESSTOKEN: isValid: false
```

**Scenario 2: AccessToken's datasource = memory**

```
ACCESSTOKEN: now: Fri Feb 16 2018 10:18:49 GMT-0800 (PST)
ACCESSTOKEN: created: Fri Feb 16 2018 10:18:48 GMT-0800 (PST)
ACCESSTOKEN: elapsedSeconds: 1.103
ACCESSTOKEN: secondsToLive: 900
ACCESSTOKEN: isValid: true
```

I would like to keep the AccessToken model persisted in the DB so that the tokens can remain valid on app/server restarts.   But with this issue with token validation, I can't.

Was the AccessToken designed and meant to be just persisted in memory?

**Comment by bajtos** [comment]
Hello @ninoguba, thank you for reporting this issue. The AccessToken is definitely meant to be stored in a database! It's just that we did not anticipate the timezone-related issue you have described.

Do you have an idea how to fix this problem? Would you like to contribute the fix yourself? See http://loopback.io/doc/en/contrib/code-contrib.html to get you started.
