### ISSUE TITLE
how to save json object to mongodb

### ISSUE THREAD

**Issue by nyousefzai** [strongloop/loopback#3807]
i am new to loopback, I searched on doc it was not clear 

how to save data using loopback in MongoDB?
basically how to populate?

**Comment by NorthDecoder** [comment]
There are several fully functional examples on youtube that if followed exactly will work as shown:
* by David Connelly
  -  Setting up with mongodb [01](https://www.youtube.com/watch?v=Z5pGL2QojU4)
* by IBM developer advocate Erin McKean
  - [IBM Code SF Jan 2018](https://www.youtube.com/watch?v=E94I-F5V7_4)
  - [SacJS June 2017](https://www.youtube.com/watch?v=J3tfPTyPY4c)
* Traversy Media
  - Loopback [REST](https://www.youtube.com/watch?v=UTxhKZuVaG8)

**Comment by dhmlau** [comment]
@nyousefzai , you might also wanna check out the `README` on https://github.com/strongloop/loopback-connector-mongodb.  Hope it helps.

**Comment by bajtos** [comment]
Closing as answered.
