### ISSUE TITLE
User login fails with "username" and "password" combination but succeeds with "email" and "password" combination.

### ISSUE THREAD

**Issue by oderayi** [strongloop/loopback#3811]
# Description/Steps to reproduce
In the api explorer, expand Users category, scroll to "login" method.
Input in credentials textarea: { "username": "...", "password" : "..."}. This fails.
Input in credentials textarea: { "email": "...", "password" : "..."}. This works.

**Comment by dhmlau** [comment]
@oderayi , I just tried it with loopback@3.18.2, both combinations seem to work fine. 
Which version of LoopBack are you using?  
You can run `npm ls --prod --depth 0 | grep loopback` to find out.

My output looks like this:
```
├── loopback@3.18.2
├── loopback-boot@2.27.1
├── loopback-component-explorer@5.3.0
```

**Comment by dhmlau** [comment]
Closing it due to inactivity.
@oderayi , feel free to reopen this issue if you still encounter the problem.  If that's the case, we'll need more information on the versions for the node modules.  Thanks.
