### ISSUE TITLE
Allow conditional relations

### ISSUE THREAD

**Issue by wibblymat** [strongloop/loopback#3821]
Let's say I have a Player model and a Game model. A Game represents some instance of a single player game that the player either won or lost. I would like to add a relation that gives me games where the player won.

Something like:
```json
  "relations": {
    "gamesWon": {
      "type": "hasMany",
      "model": "Game",
      "scope": {
        "where": {"win": true}
      }
    }
  }
```

As far as I can see it is not possible to add such a condition to a relation.

**Comment by bajtos** [comment]
@wibblymat thank you for reporting this idea, it makes sense to me. @raymondfeng can you think of any solution how to combine relations and scope in the current LoopBack version?
