### ISSUE TITLE
Insufficient docs for loopback-passport

### ISSUE THREAD

**Issue by Noob7** [strongloop/loopback#3824]
I am trying to implement fb login. My server needs to send access token instead of redirects and thus far i have failed to find any docs on configuring provider json to : 
1) Return json instead of redirects 
2) Run a custom verify callback to save user details

After searching i was able to find some examples of customCallback option in provider json but all the articles seem to be two years old. Any docs on customizing passport component would be really helpful

**Comment by bajtos** [comment]
> I am trying to implement fb login. My server needs to send access token instead of redirects and thus far i have failed to find any docs on configuring provider json to (etc.)

@raymondfeng could you PTAL?
