### ISSUE TITLE
Using upsert for custom datatypes.

### ISSUE THREAD

**Issue by arifsohail** [strongloop/loopback#3826]
Question:
I want to apply upsert on a custom datatype.

I have created a custom model for the time. Then I used it in another model as a datatype. But later I realized it's not working when I use upsert.
 ``` 
time = {
hours,
minutes,
seconds
}

**Comment by bajtos** [comment]
Hello, please create a small application showing how to reproduce the issue in isolation - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report. Ideally, write an automated test we can run via `npm test`, one that fails with the current LoopBack version.
