### ISSUE TITLE
async function - callback called after finished

### ISSUE THREAD

**Issue by israelglar** [strongloop/loopback#3830]
# Description/Steps to reproduce
I'm defining a async remote method and when I call the callback function with no Errors 'Callback was already called'. But if the callback has an Error, it all goes well. 

### Function with no errors:
Client receives 'ok' but server's console shows 'Error: Callback was already called.'
`Test.async_returnCB = async (cb) => {
        cb(null, "ok")
    }`

### Console:
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Callback was already called.`
`[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

### Function with Error:
Client receives Error message, and nothing shows on server's console
`Test.async_returnError = async (cb) => {let err = new Error()
        err.statusCode = 400
        cb(err)}`

### Console:
`Unhandled error for request POST /tests/async_returnError ...` The usual stuff

# Link to reproduction sandbox
https://github.com/israelglar/loopback-async-error

# Expected result
No Errors

# Additional information
linux x64 8.9.4

loopback-sandbox@1.0.0 /home/USER/loopback-sandbox
├── loopback@3.18.2
├── loopback-boot@3.1.0
├── loopback-component-explorer@5.3.0

**Comment by israelglar** [comment]
Is there a solution to this?

**Comment by bajtos** [comment]
@israelglar async functions are returning a promise which is handled by LoopBack, you must not use the callback. Simply return the value directly.

```js
Test.async_returnCB = async () => "ok";
```

To report an error, return a rejected promise or throw the error directly.

```js
Test.async_returnError = async () => {let err = new Error() err.statusCode = 400 throw err}
```
