### ISSUE TITLE
Empty array response in HasManyThrough relations with include filter

### ISSUE THREAD

**Issue by brunoescalona** [strongloop/loopback#3831]
# Description/Steps to reproduce
First at all I want to give you te version of my package.json
```
+-- compression@1.7.1
+-- cors@2.8.4
+-- eslint@2.13.1
+-- eslint-config-loopback@4.0.0
+-- helmet@1.3.0
+-- loopback@3.18.2
+-- loopback-boot@2.27.0
+-- loopback-component-explorer@4.3.0
+-- loopback-component-storage@3.3.1
+-- loopback-connector-mongodb@3.3.1
+-- loopback-datasource-juggler@3.15.4
+-- loopback-setup-remote-methods-mixin@1.0.4
+-- moment@2.20.1
+-- nsp@2.8.1
+-- serve-favicon@2.4.5
`-- strong-error-handler@1.2.1
```

I have created an application with HasManyThrough relationship. 
A ```Restaurant``` model with the following relation:
```
"laboratories": {
   "type": "hasMany",
   "model": "Laboratory",
   "foreignKey": "restaurant_id",
   "through": "LaboratoryRestaurantMapper"
}
```

A ```Laboratory``` model with the following relation:
```
"restaurants": {
   "type": "hasMany",
   "model": "Restaurant",
   "foreignKey": "laboratory_id",
   "through": "LaboratoryRestaurantMapper"
}
```
And finally a mapper ```LaboratoryRestaurantMappers``` to map both models through hasmay relations with the following relations:
```
"laboratory": {
    "type": "belongsTo",
    "model": "Laboratory",
    "foreignKey": "laboratory_id",
    "required":true
},
"restaurant": {
    "type": "belongsTo",
    "model": "Restaurant",
    "foreignKey": "restaurant_id",
    "required":true
}
```

# Expected result

When I try to get the restaurants that belong to a laboratory I always get an empty array on the relationship as follow:

`http://localhost:3000/api/v1/laboratories?filter=%7B%22include%22%3A%22restaurants%22%7D&
`
```
[
  {
    "name": "Laboratorio HPhM",
    "date": "2018-02-28T23:00:00.000Z",
    "id": "5aaaa19cc1a6094ff40e2cb0,
    "restaurants": []
  }
]
```

# Additional information

Here the mock models:
### Laboratory:
```
{
   "id":"5aaaa19cc1a6094ff40e2cb0",
   "name":"Laboratorio HPhM",
   "date":"2018-02-28T23:00:00.000Z","cif":"A123456789"
}
```

### Restaurant:

```
{
   "id":"5aaaa19bc1a6094ff40e2c79",
   "name":"Restaurante 1"
}
```
### LaboratoryRestaurantMappers
```
{
   "id":"5aaaa19cc1a6094ff40e2cb8",
   "laboratory_id":"5aaaa19cc1a6094ff40e2cb0",
   "restaurant_id":"5aaaa19bc1a6094ff40e2c79"
}
```

If someone could help me with that would be apreciate.

I have donwloaded too the appointment example and it works fine with mongodb and memory so I dont know if I am doing something wrong or is related with the versions because the example is done with loopback version 2.x.

**Comment by brunoescalona** [comment]
Solved the issue with that post in stackoverflow:
https://stackoverflow.com/questions/43120270/loopback-include-filter-fails-with-hasmanythrough-relation?rq=1

**Comment by gocreating** [comment]
The solution is not working at all

**Comment by brunoescalona** [comment]
@gocreating Di you used the `keyThrough` property? It solve the problem for me.

If not could you copy some of your json model to see if I can help you?

**Comment by gocreating** [comment]
@brunoescalona Thanks for your answer. It was my problem.
I used mongo database. The `_id` of entries of the throughModel was not wrapped with `ObjectId()`.
Just change the id string `"xxx"` to `ObjectId("xxx")` and problem solved.

**Comment by kruyvanna** [comment]
I turned on **strictObjectIDCoercion**
and it solved the problem of **ObjectId**
https://loopback.io/doc/en/lb3/MongoDB-connector.html#strictobjectidcoercion-flag

**Comment by rpvelloso** [comment]
@brunoescalona had the same problem: worked with memory db but not in SQLite. The relation array was returning empty when I changed the db to SQLite. The problem was that FKs were in camel case in SQLite, I just changed it all to lower case and it worked.
