### ISSUE TITLE
modelInstance..! How do you do that  ? 

### ISSUE THREAD

**Issue by xmanemran** [strongloop/loopback#3832]
```
module.exports = function(Representative) {
  Representative.beforeSave = function(next, modelInstance){
    console.log(modelInstance);
    console.log(Object.keys(modelInstance));
  }
};

```
Here is log 

```
{ 
name: 'string',
  address: { addressLine: 'House 51',
     localArea: 'Kunjerhat',
     subArea: 'Borhanuddin',
     city: 'Bhola',
     country: 'Bangladesh' 
  }
}

[
 '__cachedRelations',
  '__data',
  '__dataSource',
  '__strict',
  '__persisted' 
]
```

I am not expert in JavaScript. If we use `Object.defineProperties` definitely `__data` should show on console, but it not, How? 
How do you do that ? ⭕️

**Comment by pbalan** [comment]
@xmanemran What are you trying to achieve? If you want the data, you can do the following.
modelInstance.__data
However, if you want the keys for the data, you can use Object.keys on **modelInstance.__data** array.
Shortcut that works for me **modelInstance.toJSON()**
