### ISSUE TITLE
updateAll fill nulls automatically on array nested props

### ISSUE THREAD

**Issue by bmrinal** [strongloop/loopback#3840]
Models with nested properties gets nulled values on updateAll

# Description/Steps to reproduce
1. Create a model with nested property (array of objects)
2. Try to use updateAll on that model for the above nested property

The above steps results in filling of null values in all other optional model properties apart from the nested one!

**Comment by mastermunj** [comment]
Can you share a snippet to replicate the issue for better understanding?
