### ISSUE TITLE
Second Level Size in where quering

### ISSUE THREAD

**Issue by davidpestana** [strongloop/loopback#3843]
I have a model with hasMany relation  ( myModel hasMany Items )

i need filter all with only 1 item in hasMany relation

i try to filter with ...

`{"include":"items","where":{"items":{"size":1}}}`

I do not find documentation about it, what am I doing wrong?
thanks

**Comment by dhmlau** [comment]
@davidpestana , have you looked at this: https://loopback.io/doc/en/lb3/Where-filter.html?

**Comment by davidpestana** [comment]
@dhmlau Sure, but ... in "where-filter documents" do not explain how I can filter by the size of the elements included in has many relationships.

I try, using size operator than the mongoDb query but it does not work.

Thanks for everything.

**Comment by mastermunj** [comment]
Try using `scope` on include. Read about it [here](http://loopback.io/doc/en/lb3/Querying-related-models.html#using-filters-parameters-with-included-relations).

Something like:
```js
{ include: { relation: 'items', scope: { where: { size: 1 } } }}
```
