### ISSUE TITLE
Order the results by the property of the related model

### ISSUE THREAD

**Issue by babuqburst** [strongloop/loopback#3849]
I have to order the results by the property of the related model. But it is not working. Can you suggest a solution for it?

Model 1: Project
id
title

Model 2: Bids
id
rank
project_id (FK)
createDate

Model 3: Company

I have to apply the following filter to the bids list

```
var filters =  {
    	limit : 12,
	skip : 0,
	order : ['project.title ASC', 'rank ASC', 'createDate DESC']
	where : {
		and: [
			{ rank: { gte : 1 } },
			{ rank: { lte : 3 } },
		   ]
	},
include : [
		{
		  'project' : 
			{
			   'bids': [
			   'company'
			  ]
			},

		},
		'company'
	  ]

	};
```

var params = { params: { filter: filters } };

var result = $http.get( '/api/Bids', params );

console.log(result);

**Comment by mastermunj** [comment]
What exactly are you trying to achieve here?
You're querying `Bids`, which includes `company` & `project` which again includes `bids` and `company`. Same data being queried several times on several levels.

On other note, include can also accept various filters like where, order and fields. Read more about it [here](http://loopback.io/doc/en/lb3/Querying-related-models.html#using-filters-parameters-with-included-relations).

**Comment by babuqburst** [comment]
@mastermunj , 
Thank you for the reply. I agree to remove the includes associated with project filter. my concerns about order filter. I need to filter the entire results based on project title and then with the rank field of bid table.

**Comment by mastermunj** [comment]
AFAIK, combined ordering on model and it's related model is not possible in loopback as of now.
