### ISSUE TITLE
french translation problem

### ISSUE THREAD

**Issue by maherzaidoune** [strongloop/loopback#3852]
i was trying  to use lb acl command and  i found  a problem in the frensh version 
so , select the acl scope  and  select  the  access type was  ok , but when i tried to select  the role , the option i got was 
- tous les utilisateurs (all  users)
- tous  les utilisateurs authentifiés(any authenticated user)
- tous  les utilisateurs authentifiés(any authenticated user) again 
- l'utilisateur possedant l'objet (the  user  owning the  object)
- other
![loopbackerror](https://user-images.githubusercontent.com/10913540/38310569-3679a304-381d-11e8-8c0f-e38afa36074b.png)

**Comment by dhmlau** [comment]
@maherzaidoune , thanks for reporting this issue. 
In the English version (https://github.com/strongloop/loopback-workspace/blob/master/intl/en/messages.json#L160)
```
  "58f80adc7d0cb3b31e07883b93ba66ef": "Any authenticated user",
  "67e50229d1ed528e047c446ecfdc5073": "Any unauthenticated user",
```

But in French version (https://github.com/strongloop/loopback-workspace/blob/master/intl/fr/messages.json#L19)
```
"67e50229d1ed528e047c446ecfdc5073": "Tous les utilisateurs authentifiés",
```

**Comment by dhmlau** [comment]
Sent the request to the translation team.
