### ISSUE TITLE
Put method to update a single field deletes the unspecified fields and ask for required fields.

### ISSUE THREAD

**Issue by OscarVargasG** [strongloop/loopback#3856]
When i use the PUT method in any model, the method ask to fill the required fields and updated  to null value the unspecified fields, (similar behavior to a POST method). Can´t update a single field! 

# Description/Steps to reproduce
Get method:
![get](https://user-images.githubusercontent.com/8744574/38511222-b851b004-3be4-11e8-9aef-d8d2669d8490.PNG)
PUT:
![32](https://user-images.githubusercontent.com/8744574/38511229-be17bf42-3be4-11e8-9012-12bdf2dbecb1.PNG)
Response.
![response](https://user-images.githubusercontent.com/8744574/38511245-ce4d00f2-3be4-11e8-91bb-3f0d96cac3fb.PNG)

Another case is the deletion of unspecified fields

GET:
![testsswss](https://user-images.githubusercontent.com/8744574/38511790-8398b662-3be6-11e8-88f2-2f22e825691c.PNG)

PUT:
![ukkyuk](https://user-images.githubusercontent.com/8744574/38511842-acdfcec0-3be6-11e8-9a29-7a7598fbcc86.PNG)

PUT response:
![response2](https://user-images.githubusercontent.com/8744574/38511863-bd872e08-3be6-11e8-8e57-b7424f336802.PNG)

GET method again:

![errrase](https://user-images.githubusercontent.com/8744574/38511959-06ccaf3e-3be7-11e8-964a-1287c1bc3e38.PNG)

# Expected result
The expected result is a response with the updated field without modify the unspecified fields.

**Comment by dhmlau** [comment]
@OscarVargasG , nice!  
Closing this issue as resolved.  Thanks.
