### ISSUE TITLE
Inclusion filter present security issue

### ISSUE THREAD

**Issue by offlinehacker** [strongloop/loopback#386]
So let's say i have following relation `user <-groupMembers-> group`, now if i allow group owner to query users, he can also include all user tokens, and login as user, nice.

**Comment by grosem** [comment]
@fabien & @raymondfeng 

I just tested it with the latest version and it is still possible. For example like this (manager is extending the User model):

http://localhost:3000/api/events?filter={"where":{"nr":1},"include":{"relation":"manager","scope":{"include":[{"relation":"accessTokens"}]}}}

https://groups.google.com/forum/#!topic/loopbackjs/8XmsoaHpNP4 seems to be the same problem.

**Comment by fabien** [comment]
ping @raymondfeng @bajtos @ritch

**Comment by bajtos** [comment]
@raymondfeng mentioned in the mailing list that one can disable includes in model/relation settings using the option `disableInclude: true`. Does that fix the problem? 

Is it enough to change configuration of the built-in relation "User hasMany accessTokens" to prevent inclusion? Or is that just a workaround and we need to implement @raymondfeng proposal "the ACL will have to check the permissions for the included relations"?

**Comment by grosem** [comment]
From my point of view this should definitely covered by ACL.

**Comment by raymondfeng** [comment]
@bajtos User.hasMany accessTokens probably should have `disableInclude` set to `true` by default.

**Comment by bajtos** [comment]
Closing the issue as fixed by #1318.

**Comment by erikverheij** [comment]
The ability to access related objects via include is a large security hole. Essentially it makes the whole ACL useless as long as users can use the include filter. 

I suggest to add a big warning on the include documentation page. In fact I think filter.include should be disabled by default until ACL deals with it.

**Comment by fabien** [comment]
@erikverheij agreed, this should be handled with caution. 

@raymondfeng @bajtos what do you think?

A workaround for now (from the top of my head) would be:

```
Model.observe('access', function(ctx, next) {
  ctx.query.include = {}; // clear
  next();
});
```

**Comment by Shyri** [comment]
I totally agree with @erikverheij . Include feature is a nice way to avoid multiple requests from the frontend but it is a must to be handled by ACL in order to have decent security. At the moment the only solution I can see is to use "disableInclude" for all models that needs to be blocked to at least one role (other than $everyone or $unauthorized) and access them with specific requests only allowed for specific roles

**Comment by ben-girardet** [comment]
Any chance that the ACL would handle this security issue in the future ?

**Comment by dmisdm** [comment]
Has this issue essentially moved to https://github.com/strongloop/loopback/issues/1362 ??

**Comment by sebastianfelipe** [comment]
Can this "disableInclude" feature affect the client calls only and not the back-end side? Thanks.

**Comment by bajtos** [comment]
> Can this "disableInclude" feature affect the client calls only and not the back-end side? Thanks.

@sebastianfelipe I believe this flag affects all calls, including JavaScript API. If you suspect it's not working that way, then please open a new issue and provide us with a small app reproducing the problem - see http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
