### ISSUE TITLE
Migration from Loopback 2 to 3: Shared class has no method handing POST

### ISSUE THREAD

**Issue by lainz** [strongloop/loopback#3862]
We was using Loopback 2, when changed to 3 I get:
{
   "error": {
       "statusCode": 404,
       "name": "Error",
       "message": "Shared class  \"Operadores\" has no method handling POST /"
   }
}

There is a migration guide, or it should work out of the box?

**Comment by dhmlau** [comment]
@lainz, here is some information on migrating from v2 to v3: https://loopback.io/doc/en/lb3/Migrating-to-3.0.html.  

For the issue you stated above, can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by lainz** [comment]
Hi, thanks for your response. And no, I can't make a demo because I did not make the API, I'm just the one that can report the problem, I was asked to see if I can do something, sorry.

The responsible of making the API and changing it from version 2 to 3 said that he readed the migration docs, so it's maybe something we can't figure.

I understand that with a demo we can isolate the problem, but I don't have the knowledge to replicate the api. I will see if is possible to provide one.

I asked because I've seen some other bug reports with the same problem, but with no much information on what's really going on or how to fix.

I supposed that there was a concrete reason for that to happen. Like a common error code, or a common way to solve this kind of problems. A specific change on the way of making things from v2 to v3 that breaks existing code.

Anyways, thanks for your time.

**Comment by lainz** [comment]
Thanks, but I did not find any more information to provide in the week.

**Comment by dhmlau** [comment]
That's good to hear.  Thanks for updating @lainz!
