### ISSUE TITLE
Where does PersistedModel.create gets overwritten?

### ISSUE THREAD

**Issue by felpin** [strongloop/loopback#3863]
Hello,

Line 107 of `lib/persisted-model.js` attributes a function to the `PersistedModel.create`, but this function executes only another function that throws an error saying that the DataSource needs to be attached to the PersistedModel.

My question is very simple, where the PersistedModel.create is overwritten? I'm using mongodb as datasource, so I'm also using loopback-connector-mongodb package.

Looking into code, I couldn't find a line where somehow PersistedModel.create is redefined, so I think I'm missing something in the flow of loopback boot.

So... Can someone help me?

**Comment by mastermunj** [comment]
For MongoDB:

https://github.com/strongloop/loopback-connector-mongodb/blob/3116da3dfcfa5478b945f2de59d9972ce0fe4d67/lib/mongodb.js#L437

**Comment by felpin** [comment]
Ok, that line of code defines how the connector will save data to the database, but my question is where does the binding between the connector and the loopback model happens.

I'm looking for something like:

```javascript
PersistedModel.create = () => {
  MyMongoDbConnector.create();
}
```

**Comment by jannyHou** [comment]
@felpin When you call a model method like `User.create()`, it goes to [juggler's create function](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L278) first, then the one @mastermunj post in comment https://github.com/strongloop/loopback/issues/3863#issuecomment-382644655

By your description, looks like your LoopBack model is not a persistent one.

**Comment by felpin** [comment]
Thank you so much for your reply.

The code I was looking for is exactly [this](https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L278)
