### ISSUE TITLE
Scaling a Loopback Project

### ISSUE THREAD

**Issue by yawningphantom** [strongloop/loopback#3870]
# Description
My team has developed a project using Loopback and now at peak time it has over 100 concurrent users which make all the REST API's slower(some API's take almost a minute). I tried to read on the internet on how to scale a loopback project but didn't find any solution. I way hoping that the community might help me with this .   
Thanks in advance.

**Comment by virkt25** [comment]
You should be able to scale the project by just spinning up multiple instances of the application. You would need something to balance the requests across multiple instances -- if you're using IBM Cloud (Bluemix) it can do this for you automatically.

**Comment by raymondfeng** [comment]
As @virkt25 mentioned, it should be fairly easy to adopt horizontal scaling for LoopBack applications. Please check out https://github.com/strongloop/strong-supervisor. It provides a simple command to enable Node.js clustering.

**Comment by yawningphantom** [comment]
Thanks for your response.
appriciated.
