### ISSUE TITLE
Count with where? Possible bug

### ISSUE THREAD

**Issue by lainz** [strongloop/loopback#3875]
Hi, I need to filter the count of an endpoint, I need to add the company ID to retrieve only the number of elements that belongs to that company.

Whay I try to do, on Loopback 3, and fails is this:

```javascript
MyEndpoint.beforeRemote('count', function(ctx, modelInstance, next) {
    var whereClause = {id: '1234'}
    ctx.req.query.where = whereClause;
    next();
  });
```

For some reason it doesn't work. But if I set the filter in the URL, something like:

`MyEndpoint/count/where={"id":"1234"}`

It works, but I need to do it internally, not in the URL.

My question is: It is a bug, because trying to set "where" as object, as string, as object mixed with string, never works. But the url providing the 'id' always works.

This is intended, like read only, or there is another way to set the "where"?

Thanks.

**Comment by easobral** [comment]
It should be ctx.req.query.filter.where.

**Comment by easobral** [comment]
there is no req.query

**Comment by lainz** [comment]
Ok, I see, let me test again, sorry I'm new to this

**Comment by easobral** [comment]
But maybe a better solution would be to use a remoteMethod or named scope?

**Comment by lainz** [comment]
Hi, I tested it with this:
ctx.args.filter = {};
ctx.args.filter.where = whereClause;
But doesn't work as well.

How it will be using a removeMethod or named scope? I'm really new to this.

**Comment by easobral** [comment]
here is the docs for remote methods.

http://loopback.io/doc/en/lb3/Remote-methods.html

**Comment by lainz** [comment]
Thanks. I will check it out.

But back to the original question, is possible to modify the 'URL', I mean the filter, and it should work?

**Comment by easobral** [comment]
Yes. I use it to create automatic pagination.

the code I use is this and it works;

    Model.beforeRemote('**', async(ctx) => {
        const ctx_options = ctx.args.options;
        ctx_options.pagination = ctx_options.pagination || {};
        const page = ctx_options.pagination.page = Number(ctx.req.query.page) || DEFAULT_PAGE;
        const per_page = ctx_options.pagination.per_page = Number(ctx.req.query.per_page) || DEFAULT_PER_PAGE;
        ctx.args.filter = ctx.args.filter || {};
        ctx.args.filter.limit = per_page;
        ctx.args.filter.skip = page > 0 ? (page - 1) * per_page : 0;
    });
