### ISSUE TITLE
Hasone relation is returning empty 

### ISSUE THREAD

**Issue by cookiejest** [strongloop/loopback#3877]
I am getting an issue with a HasOne Relationship when trying to run the query

 GET "/triggers/{{triggerid}}/filesources" 

I receive an error:

`{
    "error": {
        "statusCode": 404,
        "name": "Error",
        "message": "Unknown \"filesource\" id \"undefined\".",
        "status": 404,
        "code": "MODEL_NOT_FOUND",
        "stack": "Error: Unknown \"filesource\" id \"undefined\".\n    at convertNullToNotFoundError (C:\\Users\\someuser\\Development\\alerts\\testapi\\node_modules\\loopback\\lib\\model.js:556:17)\n    at invokeRestAfter ...."
    }
}`

**trigger.json**
`{
  "name": "trigger",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "status": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "filesources": {
      "type": "hasOne",
      "model": "filesource",
      "foreignKey": "",
      "options": {
        "nestRemoting": true
      }
    }
  },
  "acls": [],
  "methods": {},
  "mixins": {
    "TimeStamp" : true
  }
}
`

**filesource.json**
`{
  "name": "filesource",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "type": {
      "type": "string",
      "required": true
    },
  },
  "validations": [],
  "acls": [],
  "methods": {},
  "mixins": {
    "TimeStamp" : true
  }
}
`

# Expected result
I am expecting it to return one filesource or blank array, any ideas?

**Comment by jannyHou** [comment]
@cookiejest Can you try define a `belongsTo` relation from model `filesource` to `trigger`? 

You can find the the doc of `belongsTo` here: https://loopback.io/doc/en/lb2/BelongsTo-relations.html

`hasMany` is a more popular scenario, [its doc](https://loopback.io/doc/en/lb2/HasMany-relations.html) explained why `has*` and `belongsTo` relation is always a pair. `hasOne` is like `hasMany` with constraint. 

Let me know if it still doesn't work for you.

**Comment by jannyHou** [comment]
No problem :) `HasOne` means one parent model instance can only has **ONE** child model instance.

I am closing the issue since question is solved. Feel free to reopen it if you have other questions!

**Comment by smnodame** [comment]
You should call POST first before can use PUT to update the model that using hasOne

**Comment by sujeshthekkepatt** [comment]
Can we reopen this? I am facing a similar issue. In my case, I can't convert it to hasMany relation.

### usermodel
```
{
  "name": "usermodel",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "mixins": {
   
  },
  "properties": {
    "first_name": {
      "type": "string",
      "required": true
    },
    "last_name": {
      "type": "string",
      "required": true
    },
  },
  "validations": [],
  "relations": {
    "myAnotherModel": {
      "type": "hasOne",
      "model": "my_another_model",
      "foreignKey": "",
      "options": {
        "nestRemoting": true
      }
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    },

  ],
  "methods": {
}

}
```

### my_another_model
```
{
  "name": "my_another_model",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "phone": {
      "type": "string"
    },
    "email": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
    "usermodel": {
      "type": "belongsTo",
      "model": "usermodel",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": {}
}



```


### Error Message

I get the  following error message,
```
 Unknown "my_another_model" id "undefined". (err.code=MODEL_NOT_FOUND)
    Error: Unknown "my_another_model" id "undefined".
```


Any help appreciated.
