### ISSUE TITLE
How to get userId in " before save " Hook function?

### ISSUE THREAD

**Issue by AshwanthMadhav** [strongloop/loopback#3878]

**Comment by jannyHou** [comment]
Hi @AshwanthMadhav the instance property like `userId` is passed in the hook function as `ctx`, see our doc https://loopback.io/doc/en/lb2/Operation-hooks.html#before-save

So you can get the `userId` by either `ctx.instance.userId` or `ctx.currentInstance.userId`, depends on do you save a completed model instance or update partial of an existing one.

**Comment by AshwanthMadhav** [comment]
@jannyHou  Thank you.
