### ISSUE TITLE
Track if a record was fetched (update) or newly instantiated (create).

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#388]
In reference to #126 a model currently checks if an instance is new by checking if the `id` property has been set. When this has been set explicitly - whenever a model doesn't use an automatically assigned `id` value - `isNewRecord` incorrectly returns false, even for new records. As a result, a `save()` call is unable to distinguish whether to perform `create` or `update`.

There should be a different implementation of checking 'newness' in order to incorporate this correctly.

**Comment by bajtos** [comment]
As part of our issue triage process, I am closing items that have been inactive for an extended period of time. If anybody thinks the feature proposed here is still relevant and should be prioritised, then please leave a comment to let us know.
