### ISSUE TITLE
findOrCreate function promise return something different from callback

### ISSUE THREAD

**Issue by tokidoki11** [strongloop/loopback#3880]
I was following tutorial from this link
[https://loopback.io/doc/en/lb3/Defining-and-using-roles.html](url) to define role and user
but when I try to use the promise, I found out the resolve function is returning an array of [instance, created] instead if non array as defined in API documents.

[https://apidocs.strongloop.com/loopback/#persistedmodel-findorcreate](url)

Is there any documentation that I miss?

```
// Create Role
    Role.findOrCreate({
      where: {
        name: 'administrator',
      },
    }, {
      name: 'administrator',
    }).then(([role, isCreated]) => {
      console.log(role.principals);
    }).
    catch((err) => {
      console.log(err);
      process.exit();
    });
```

**Comment by jannyHou** [comment]
Hi @tokidoki11 see the code here https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L1256-L1266

When you use the api in the `Promise` signature, the result is returned in an array. While the apidoc is generated based on the jsdoc written before the function definition, which is in a non-promise flavour.

To fix the doc, we need to create annotation for the returned value in a `Promise` signature, which  is not our high priority at this moment I am afraid. Sorry for the inconvenience. 

Let me know if you have other questions.

**Comment by tokidoki11** [comment]
OK I see
