### ISSUE TITLE
Back-end validation in loopback ?

### ISSUE THREAD

**Issue by AshwanthMadhav** [strongloop/loopback#3882]
How to set a back-end validation in loopback like Larvel Validator ?

**Comment by jannyHou** [comment]
@AshwanthMadhav Thank you for the suggestion! We appreciate your feedback.

I am new to the Laravel Validator, given a quick look it provides a rich set of rules validating the incoming data, mainly focus on the data types.

Loopback 3 has built-in model validators and also supports customized ones, see document http://loopback.io/doc/en/lb3/Validating-model-data.html, I think this is similar to Laravel.

For loopback 2 and 3, I don't think we have plan to enlarge our build-in validators, but we are implementing a new validation system for the coming major version Loopback 4! We have an epic for validation and type coerce in https://github.com/strongloop/loopback-next/issues/755, and we build a good backlog for it, feedback are welcomed!

**Comment by jannyHou** [comment]
I am closing this issue since we will add new validation features in loopback-next, feel free to reopen it or continue the discussion in https://github.com/strongloop/loopback-next/issues/755, thanks.
