### ISSUE TITLE
how to dynamically connect to database  in loopback

### ISSUE THREAD

**Issue by rockyshukla** [strongloop/loopback#3886]
how I can switch database dynamically i.e connection of each database is stored in the master database. for eg:- if the user wants his database in Mumbai region then my code check whether Mumbai database exists in the master database if yes then make the connection to Mumbai database now all model should dynamically connect to Mumbai database.if not then I m passing error message that database does not exist. now problem is that my user model create method first connected to the master database and afterward it should connect to other databases if exists in master for eg:-

            User.beforeRemote('create', function (ctx, user, next) {
               var dataname=ctx.args.data.dbname  //this line passes db name eg:-mumbai
                 User.find({where:{dbname:dataname}},function(err,res){ //this connect to master
                   if(err){
                    var err = new Error('Database Does not Exists');
                    err.statusCode = 444;
                    next(err)
                    }
                      else{ 
                    next();  //this should connected to other database if exist in master 
                      }
                  })
             });
all other methods of user model should dynamically connect to Mumbai database how would I connect to database dynamically in above code and another thing 

         "user": {
            "dataSource": "db",//what should be here i.e if connection is dynamically switch then it should be  here
               "public": true
              },
         "company": {
                "dataSource": "db",//what should be here i.e if connection is dynamically switch then it should be here 
               "public": true
                },
now ideas would be highly appreciated.

**Comment by rockyshukla** [comment]
@jannyHou I saw that solution but it does not work. let me explain this issue in detail 
1.  when my app starts it will always connect to master database -- there is no issue

2.  in login page I have 3 input named as username, password, region. from region input, I will get 
     database name -- there is no issue

    --- issue start here
3.  before login it will find database name which is getting for region input as described in 
    point 2  and search in the master database  if it finds then connect to that database name
4. after getting database name it will connect to search for the credential in that database

**Comment by cineca-catalano** [comment]
I would like to implement multitenancy in the same way.
Have you solved it?

**Comment by rockyshukla** [comment]
@cineca-catalano, no actually I did not get enough time to try but I got an idea how I can achieve that 
here is an idea
before login, I m creating session i.e stored in pgsql master table. (storing session in pgsql or any kind of database you can use express session store for eg in my case I m using pgsql so i m  going to use https://www.npmjs.com/package/connect-pg-simple  )
after that, I going to create middleware which run before entering into modal and search for database credential in session if find it will connect to that database or else it stays connect to master eg:-db.attach(session)  
at initial all modal connected to a master

**Comment by rockyshukla** [comment]
@cineca-catalano  yes it will processed concurrently if you found anything else please post solution here it will help other

**Comment by cineca-catalano** [comment]
Hi @rockyshukla,
I tried that solution but it fail when 2 request are processed concurrently.
For example:
Request 1 to model A (that need Database one)
Request 2 to model A (that need Database two)

if request 2 is made before request 1 has finished, that request 1 is made in database 2.
to switch the database I used attachTo function.

**Comment by rockyshukla** [comment]
@cineca-catalano  can you show me your sample code  so i can know you issue

**Comment by rockyshukla** [comment]
@cineca-catalano  did you find solution for this problem

**Comment by cata86** [comment]
Hi @rockyshukla,
yes I found a solution, I changed the loopback-connector-mongodb module ( we use mongodb as datasource).
On the context __ctx we added a clientId field.
On MongoDB.prototype.execute (lib/mongodb.js) function we make a new connection each time clientId change.

It is not optimal for the performances, the next step is to create a connection pool for each clientId.

**Comment by rockyshukla** [comment]
@cata86  can you post some demo code (required code to switch db) it will help me as well as other and thanks for your patience

**Comment by DarikaShasai** [comment]
@cata86 hi, would you like to post the solution or part of your solution? i have the same problem and i really appreciated if you could help me.

**Comment by vilasshetkar** [comment]
Anyone found solution on this.
I'm facing same issue. It's very urgent. Please anyone has solution please share code.

@cata86  would you like to post the solution or part of your solution? I have the same problem and I really appreciated if you could help me.
Thanks.
