### ISSUE TITLE
Loopback validation not working in Update

### ISSUE THREAD

**Issue by AshwanthMadhav** [strongloop/loopback#3888]

**Comment by dhmlau** [comment]
@AshwanthMadhav , do you have more information on how to reproduce the issue? 
It would be great if you could provide a link to a test project with steps to reproduce the issue. See http://loopback.io/doc/en/contrib/Reporting-issues.html. thanks.

**Comment by dhmlau** [comment]
Closing this issue as there is not enough information provided.  @AshwanthMadhav, when you have more information, feel free to provide it in here and I'll reopen this ticket.  Thanks.
