### ISSUE TITLE
security defect in boom 4.3.1 which is part of nested loopback (3.19.1) modules

### ISSUE THREAD

**Issue by dhavaldesai10** [strongloop/loopback#3889]
There is an security issue in boom 4.3.1 which is internally used as 
loopback (3.19.1) -> strong-remoting (3.11.0) -> request (2.85.0) -> hawk (6.0.2) -> boom (4.3.1)

loopback (3.19.1) -> loopback-connector-remote (3.3.1) -> strong-remoting (3.11.0) -> request (2.85.0) -> hawk (6.0.2) -> boom (4.3.1)

**Comment by virkt25** [comment]
@dhavaldesai10 Can you please `rm -rf node_modules` and then re-install dependencies `npm i`. 

This should install `request@2.87.0` which was released 4 days ago ... which removed it's dependency on `hawk` entirely and hence the dependency on `boom` is no longer there. This should remove any security issues. Hope this helps.

**Comment by dhavaldesai10** [comment]
Thank you @virkt25 . Looks like i have to create PR for strong-remoting to update version for request module then i can use updated version.

**Comment by virkt25** [comment]
Hmm ... 🤔 ... `strong-remoting` has `request` version prefixed with `^` so it should've picked up the minor version release. Do you maybe have a `package-lock.json` file?

Regardless let me know when you open the PR and I can help you land it.

**Comment by dhavaldesai10** [comment]
I did try to clone and create branch, made required changes but unable to push it. I am getting 403 error. Do i need to request access as a contributor?

`
"loopback": {
      "version": "3.19.1",
      "requires": {
        "async": "2.6.1",
        "bcryptjs": "2.4.3",
        "bluebird": "3.5.1",      
        "loopback-connector-remote": "3.3.1",
        "loopback-datasource-juggler": "3.21.0",
        "loopback-filters": "1.0.0",        
        "strong-globalize": "3.3.0",
        "strong-remoting": "3.11.0",

 ---------
 "strong-remoting": {
      "version": "3.11.0",
      "requires": {       
        "js2xmlparser": "1.0.0",       
        "request": "2.85.0",`

**Comment by virkt25** [comment]
Make a fork instead of a clone and then open a PR from the fork

**Comment by bajtos** [comment]
@dhavaldesai10 please read our docs to learn how to submit a pull request:
http://loopback.io/doc/en/contrib/code-contrib.html#submitting-a-pull-request

You may find this article helpful too: 
https://www.nearform.com/blog/first-time-with-open-source/

What's important: the pull request should be targeting our `master` branch. 

Having said that, I don't see why a change in strong-remoting is needed. The `request` dependency is specified [here](https://github.com/strongloop/strong-remoting/blob/032e51e1f5bf69a91bc1b89ec73f734a26c29ad2/package.json#L35) as

```
 "request": "^2.83.0",
```

As @virkt25 already mentioned, this tells `npm` to pick the latest `2.x.y` version of `request` when running `npm install`.

**Comment by dhavaldesai10** [comment]
@bajtos Thank you sharing above links. 

Changes required because we need latest version of request (2.87.0). when i do npm install it is  downloading request(2.85.0) which have module hawk contains security issue.
