### ISSUE TITLE
ACL not reset when extend user model

### ISSUE THREAD

**Issue by fgvicente** [strongloop/loopback#3895]
Hello everybody, Im try reset ACL permission when extend from User model but not work. Here is my class

{
  "name": "Usuario",
  "plural": "usuarios",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "firstname": {
      "type": "string",
      "required": true
    },
    "lastname": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "roles": {
      "type": "hasMany",
      "model": "rol",
      "foreignKey": "principalId",
      "through": "RolMapping"
    },
    "accessTokens": {
      "model": "AccessToken",
      "type": "hasMany",
      "foreignKey": "userId"
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}

**Comment by gemyero** [comment]
You can do this by access the acls array in your model's js file like this in your case :-
Usuario.settings.acls and then you can reset the acls by Usuario.settings.acls = [ ] and add your acls dynamically

**Comment by codekeyz** [comment]
For Role Based ACL, Multi-User models, do check up on this https://github.com/codekeyz/loopback-multirole-api-starter. It can be helpful
