### ISSUE TITLE
How to filter a model by a submodel using where?

### ISSUE THREAD

**Issue by felpin** [strongloop/loopback#3897]
Hello,

I am trying to use a submodel in a query and filter results based on a value in this submodel.

Let's say that I've a `Model` and a `Submodel`. I'm trying to query all models with property `p` equals `43` and `Submodel.q` equals `85`. So my query is the following:

```json
{
  "where": {
    "and": [
      {"p": 43},
      {"submodel.q": 85}
    ]
  },
  "include": ["submodel"]
}
```

But the filter above does not work. I believe it is because I'm trying to filter by a submodel and all examples state nothing about how to use it.

Can anyone help me with this query?

**Comment by felpin** [comment]
Examples: http://loopback.io/doc/en/lb3/Where-filter.html

**Comment by jeff3yan** [comment]
Are you trying to filter your base model by your submodel, or do you want to include the submodel and filter those instances?

**Comment by felpin** [comment]
First option, I'm trying to filter my base model

**Comment by jeff3yan** [comment]
Unfortunately this isn't possible due to #517. Loopback doesn't do any JOINs in its ORM. You'll have to go for another ORM in order to filter by that criteria.
