### ISSUE TITLE
using own mail server to send verification emails

### ISSUE THREAD

**Issue by AliBahramiEhsan** [strongloop/loopback#3900]
I've used [this](https://loopback.io/doc/en/lb3/Email-connector.html) to send verification emails and with a gmail acount, it's working fine. After running my own mail server ([mailcow](https://github.com/mailcow/mailcow-dockerized)) I can't use my mailing to mail. I used Thunderbird to check its functionality, and it working fine. I can send mail and receive successfully. You can see settings from Thunderbird here:
![capture](https://user-images.githubusercontent.com/33450079/40694853-b2ca2424-63d3-11e8-8c41-4e5eb6581103.PNG)
and my datasource email part:
![capture2](https://user-images.githubusercontent.com/33450079/40694920-09db46bc-63d4-11e8-8c64-e2292112f3d4.PNG)
since I can connect normally to mail server, I sense that should ask about email datasource. am I missing something?
Thanks in advance

**Comment by webocs** [comment]
If you're using port  587 you have to set secutre to false. Secure must be true only for port 465, as stated in the nodemailer doc [https://nodemailer.com/about/](https://nodemailer.com/about/)

**Comment by AliBahramiEhsan** [comment]
thanks, problem solved.
