### ISSUE TITLE
Change schema for built-models

### ISSUE THREAD

**Issue by alfredv3i** [strongloop/loopback#3902]
The built-in models like role, accesstoken etc use public schema by default. I want to use some other schema name for that. 
I can give schema in the json file for the models I have created but for the models created by loopback present in node_modules how do I change the schema?

**Comment by hacksparrow** [comment]
@alfredv3i which models in `node_modules ` are you referring to?

**Comment by visheshdh1** [comment]
I am referring to built-in models which we get with loopback, they are present in node_modules/loopback/common/models. acl, access-token, role-mappings etc.
