### ISSUE TITLE
Accessing nested model in ACL in loopback

### ISSUE THREAD

**Issue by ofir10** [strongloop/loopback#3905]
I have a model named "Customer" that base (extends) from "User" model:

```
{
  "name": "customer",
  "base": "User",
  "idInjection": true,
  "options": {
  "validateUpsert": true
},
```
This model have this relations:

```
"carts": {
  "type": "hasOne",
  "model": "cart",
  "foreignKey": "",
  "options": {
    "nestRemoting": true
  }
```
"Cart" model have this relation:

```
"products": {
"type": "hasMany",
"model": "product",
"foreignKey": ""
}
```
How can i accessing the method(GET):

> /customers/{id}/carts/products

via customer.json ACL?

I didn't find the answer here: **https://loopback.io/doc/en/lb3/Accessing-related-models.html** 
because there aren't any explain how to accessing nested model.

**Comment by webocs** [comment]
If I understand correctly, whay you're looking for is solved by declaring a EXECUTE acl over a specific property. 
For example, to deny access to everyone you need this block of ACL

```    {
      "accessType": "EXECUTE",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY",
      "property": "__get__products",
    }
```

The basic structure is __METHOD__RelatedModel  (In plural for hasmany)
