### ISSUE TITLE
directory listings

### ISSUE THREAD

**Issue by NgaNguyenDuy** [strongloop/loopback#3909]
is there any way to directory listing with static middleware in loopback?

Thanks,

**Comment by virkt25** [comment]
Have a look at: 

- http://loopback.io/doc/en/lb3/Add-a-static-web-page.html
- http://loopback.io/doc/en/lb3/Defining-middleware.html#examples

**Comment by NgaNguyenDuy** [comment]
Yes, i tried with loopback-middleware. But seem i only access by the file name. My folder clients/ have home.html, styles.css and script.js but i only access by url: ../clients/home.html ../clients/style.css ...
I want to list all the files in clients on browser, is it possible?
