### ISSUE TITLE
Force HTTPS 🔒

### ISSUE THREAD

**Issue by theel0ja** [strongloop/loopback#3915]
You seem to use Github Pages ([it supports HTTPS nowadays](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)) and Cloudflare, so you should force HTTPS with Cloudflare or Github Pages.

Cloudflare **Crypto** section:
![image](https://user-images.githubusercontent.com/5832930/40474787-9b9b0be0-5f48-11e8-87ae-b933734be6cb.png)

**Comment by rmg** [comment]
I've taken the steps to enable the SSL support in GitHub Pages. Unfortunately that means the site will be unavailable over https for up to an hour while GitHub does the ACME dance with letsencrypt.org

**Comment by rmg** [comment]
..or just the time it took to post that reply!

```
> GET / HTTP/1.1
> Host: loopback.io
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Server: GitHub.com
< Content-Type: text/html
< Location: https://loopback.io/
```

Done. 🔒
