### ISSUE TITLE
Loopback app connect to mysql google cloud

### ISSUE THREAD

**Issue by manuelsanchezaponte** [strongloop/loopback#3927]
I am trying to deploy an Loopback app to a Flexible engine in Google Cloud connecting it to a mysql database that it is in a Google Cloud SQL instance, but I can't. When I try to deploy the app I always get the same error:

Web server listening at: http://localhost:8080
Connection fails: Error: getaddrinfo ENOTFOUND /cloudsql/miampa-1be3e:us-central1:miampa-prueba2 /cloudsql/miampa-1be3e:us-central1:miampa-prueba2:3306
It will be retried for the next request.
events.js:183
      throw er; // Unhandled 'error' event

My datasources.json is:

{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "appAmpa": {
    "name": "appAmpa",
    "connector": "mysql",
    "host": "/cloudsql/miampa-1be3e:us-central1:miampa-prueba2",

    
    "database": "prueba",
    "user": "root",
    "password": "XXXXXX"
  }
}

and in the root folder of the Loopback app I have the app.yaml file:

# [START app_yaml]
runtime: nodejs  
env: flex  
beta_settings:
    cloud_sql_instances: miampa-1be3e:us-central1:miampa-prueba2
# [END app_yaml]

The app Engine and the sql instance are in the same region: us-central

Any help would be great. Thank you.

# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

I have try to find some documentation about this particular case, but I couldn't find reliable sources: One of the best is: https://medium.com/sk-geek/how-to-deploy-nodejs-loopback-server-postgresql-database-to-google-app-engine-cloudsql-2ddf8724c76c

 node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 8.11.1

npm ls --prod --depth 0 | grep loopback
├── loopback@3.20.0
├── loopback-boot@2.27.1
├── loopback-component-explorer@4.3.1
├── loopback-connector-mysql@5.2.0

**Comment by dhmlau** [comment]
@manuelsanchezaponte , I haven't tried mysql on google cloud, but the host name doesn't look quite right to me.  Another thing to try is to add `url` attribute in the datasources.json in the form of `mysql://user:password@host/db`.

**Comment by manuelsanchezaponte** [comment]
Thank you, but it didn't work. At the end I have found the solution, using:
"socketPath": "/cloudsql/miampa-1be3e:us-central1:miampa-prueba2",

:)

**Comment by dhmlau** [comment]
that's good to know!  Closing this ticket as resolved.

**Comment by calbu** [comment]
@manuelsanchezaponte : where did you add exactly that configuration ?
