### ISSUE TITLE
userid cannot be blank access  token is not an instance

### ISSUE THREAD

**Issue by R2511** [strongloop/loopback#3930]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by dhmlau** [comment]
@R2511 , could you please elaborate more on the problem you're reporting?  Also, can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.
