### ISSUE TITLE
Mixin not called on Model with no datasource

### ISSUE THREAD

**Issue by camcamd** [strongloop/loopback#3931]
# Description/Steps to reproduce

- Started from Loopback Sandbox
- Created a model CustomModel as a Model with no datasource
- Created a model CustomModelWithDb as a Model with db
- Created a mixin in server/mixins that logs ("I'm being called by model:" + Model.definition.name)
- Added the mixin in the json of the two models

# Link to reproduction sandbox

[https://github.com/camcamd/loopback-sandbox](https://github.com/camcamd/loopback-sandbox)

# Expected result

Expected to log:
"I'm being called by model: CustomModel"
"I'm being called by model: CustomModelWithDb"

Actual result is the second log only
"I'm being called by model: CustomModelWithDb"

# Additional information

versions used:
- node : 9.8.0
- npm : 5.6.0
- loopback : 3.19.2
- loopback-cli : 4.2.0
- macOS : 10.13.4

**Comment by raymondfeng** [comment]
The issue is around https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/mixins.js#L31. It expects the model has an attached datasource to apply mixins.

**Comment by raymondfeng** [comment]
@camcamd Do you want to submit a patch?
