### ISSUE TITLE
Hive DB connecting to loopback 

### ISSUE THREAD

**Issue by nayanaboppana** [strongloop/loopback#3940]
I want to connect hive database using loopback. So I tried connecting to the hive by giving others in loopback database connection. But I am unable to generate APIs by using the hive database. I want to generate APIs using the hive database also. Will loopback support hive in future progress or any development going on hive database connection in a short period?

**Comment by virkt25** [comment]
Hi, no development going on on a Hive DB connector that I'm aware of and couldn't find a community module either on `npm`. :(
