### ISSUE TITLE
return additional data of a model

### ISSUE THREAD

**Issue by apfz** [strongloop/loopback#3946]
I have searched through the docs but am unable to find how I can add additional data to my responses.

Lets say I am executing a GET call to /api/customers

I would like each customer to return the field "address" which is a concatenation of the street_name and door_number properties defined in the Customer model. 

So somewhere I need to define "address" = this.street_name + ' ' + this.door_number and add this to the response.  Can someone point me to an example of this?

**Comment by bajtos** [comment]
One options is to define a getter model property - see https://stackoverflow.com/questions/24223329/how-do-i-create-getter-and-setter-overrides#24253273

In your `common/models/customer.json` file:

```json5
{
  // ...
  "properties": {
    // ...
    "address": "string",
  },
}
```

In your `common/models/customer.js` file:

```js
Customers.getter.address = function() {
  return this.street_name + ' ' + this._door_number;
};
```

The downside of this approach is that LoopBack will try to persist this property to the backing database (at least I think so).

If you want to include the computed field in the REST API response only, then you can leverage [Remote hooks](https://loopback.io/doc/en/lb3/Remote-hooks.html). The downside is that you need to carefully design and configure your hooks to cover all different REST APIs that can return Customer instances (e.g. `GET /api/customers` but maybe also `GET /api/customer/{id}`?).

In your `common/models/customer.js` file:

```js
Customer.beforeRemote('find', addAddressToContextResult);
Customer.beforeRemote('findById', addAddressToContextResult);

function addAddressToContextResult(context, _, next) {
    if(!ctx.result) return next();

    if(Array.isArray(ctx.result)) {
      ctx.result.forEach(fillAddress);
    } else {
      fillAddres(ctx.result);
    }
    next();
}

function fillAddress(customer) {
  customer.address = customer.street_name + ' ' + customer._door_number;
}
```

I am afraid we don't yet have a first-class solution for computed properties limited to the REST layer only. In the past, we were discussing how to enhance property metadata with flags controlling which properties should be persisted to the database and which should be sent in the REST API responses (JSON bodies), but we didn't manage to implement that so far.
