### ISSUE TITLE
filter where by id (inq, like, =) does not work on has many through related model

### ISSUE THREAD

**Issue by beirdostudio** [strongloop/loopback#3951]
# Description/Steps to reproduce
Hello, 
I have these models: 
class.json
```
{
  "name": "Class",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
   ....
  },
  "validations": [],
  "relations": {
    "subjects": {
      "type": "hasMany",
      "model": "Subject",
      "foreignKey": "",
      "through": "Workspace"
    }
  },
...
}

```
workspace.json
```
{
  "name": "Workspace",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {},
  "validations": [],
  "relations": {
    "class": {
      "type": "belongsTo",
      "model": "Class",
      "foreignKey": ""
    },
    "subject": {
      "type": "belongsTo",
      "model": "Subject",
      "foreignKey": ""
    }
  },
  "acls": [],
  "methods": {}
}

```
subject.json
```
{
  "name": "Subject",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string",
      "required": true
    }
  },
  "validations": [],
  "relations": {
    "classes": {
      "type": "hasMany",
      "model": "Class",
      "foreignKey": "",
      "through": "Workspace"
    }
  },
  "acls": [],
  "methods": {}
}

```
The problem is that when I send a request to `/classes/:id/subject` with `filter: {where: {id: <id>}}` or `filter: {where: {id: {inq: [<ids>]}}}` or any filter with id, the endpoint returns nothing even though it works fine with other fields (name for example).
Just in case, I tried the `/subjects` endpoint with the same id query and it returns the subjects.
Any idea what is wrong?
I'm using the mongodb connector in case that's relevant.

# Expected result

Return the subjects related to the class filtered by id.

**Comment by bshrram** [comment]
@medanis-bentili 
did you find a solution for that ?

**Comment by medanis-bentili** [comment]
@bshrram it's been a long time so I don't really remember and I switched to koa and loopback 4 for most of my projects.
You could always write a custom remote method or a remote hook if you still have a problem.
