### ISSUE TITLE
Adding ACL rule with a wildcard match ('*') for model property doesn't work

### ISSUE THREAD

**Issue by moshemal** [strongloop/loopback#3953]
The ["Controlling data access" documentation page](https://loopback.io/doc/en/lb3/Controlling-data-access.html#acl-rule-precedence) explains how to apply a rule for all models, but adding this king of a rule doesn't work. Exploring the ACL.checkAccessForContext function, which in charge of checking if the relevant request has the permission to access, shows that there is no lookup for '*' and only for the specific model name.

# Description/Steps to reproduce

Create an ACL rule on one of the boot scripts:
```javascript
module.exports = function(app) {
  app.models.ACL.create({
      model: '*',
      property: '*',
      accessType: '*',
      principalType: 'ROLE',
      principalId: '$everyone',
      permission: 'DENY',
    });
}
```

# Link to reproduction sandbox

# Expected result
Accessing to all models (which not includes other ACL rules) would be denied. 

# Additional information

**Comment by dhmlau** [comment]
PR https://github.com/strongloop/loopback/pull/3954
