### ISSUE TITLE
Use html or json in remote method description

### ISSUE THREAD

**Issue by nguyenchilong** [strongloop/loopback#3955]
Hi LoopBack Team,
How can use json and html format in description of remote method.
e.g like this
`<pre>
Encrypt/Decrypt for Send/Receive data to server.<br />
            Params is empty only headers params.<br />
            Headers: {<br>
                locale: string |<br>
                deviceid: string,<br>
                apptoken: 'chvdscvdgvhvg'<br>
            }<br>
            <code>
               For <b style="color: red;">Error</b> Response<br>
               {<br>
                   "error": {<br>
                       errorCode: number,<br>
                       statusName: string,<br>
                       reasonName: string,<br>
                       message: {error object}<br>
                   }<br>
               }<br>
            </code><br>
            <code>
               For <b style="color: red;">Success</b> Response<br>
               {<br>
                   result: {<br>
                       statusName: string,<br>
                       statusCode: number,<br>
                       data: {
                           publicKey: key_content
                           expired: datetime 
                       }<br>
                   }<br>
               }<br>
            </code>
</pre>`

Please help me, now I using loopback version 3.x.

Thanks,

**Comment by hacksparrow** [comment]
@nguyenchilong I am not following what you mean by "description of remote method". Can you elaborate with more context what you are trying to achieve?
