### ISSUE TITLE
Spring Rest Template error :org.springframework.web.client.HttpClientErrorException: 422 

### ISSUE THREAD

**Issue by reddynr** [strongloop/loopback#3960]
# Description/Steps to reproduce
  Review review = new Review("Captical market Error",ZonedDateTime.now(),"Marker");
            List<Review> reviews= new ArrayList<Review>();
            reviews.add(review);
            HttpEntity<MyPayload> request1 = new HttpEntity<>(new ReviewPayload("OME","2018-08-03",reviews));
   HttpHeaders headers = new HttpHeaders();
           headers.add("Content-Type", "application/x-www-form-urlencoded");
   HttpEntity<String> entity = new HttpEntity<>("username=userId&password=pwd", headers);

  ResponseEntity<ReviewPayload> response = restTemplate.exchange(
                    "https://se2345.personalfg.my.com:8446//login",
                    HttpMethod.POST, entity, MyPayload.class);

 ResponseEntity<MyPayload> response2 = restTemplate
                    .exchange("https://se2345.personalfg.my.com:8446/api/reviews", HttpMethod.POST, request1, MyPayload.class);
   

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by hacksparrow** [comment]
@reddynr Can you post what you were expecting and what is happening?
