### ISSUE TITLE
Invalid property name in "where" filter drops WHERE clause from SQL returning all rows

### ISSUE THREAD

**Issue by andrewjkrueger** [strongloop/loopback#3968]
# Description/Steps to reproduce

3.22.0

0) Have a mysql-connector (not sure if this is a connector bug or loopback yet, sorry. Would think LB)
1) Perform a GET on a collection endpoint.
2) Furnish a { "where": { "invalidPropertyForModel": "doesntMatter" } } filter for a property that doesn't exist on that model.
3) Observe that no Error is thrown nor error response emitted
4) Observe that generated SQL omits WHERE clause
5) Receive all records in your table or the default scope "limit", whichever is smaller.

# Expected result

LB throws Error for bad property name in filter, responds over HTTP in kind.

Actual result: LB silently omits your invalid filter and carries on as if no "where" filter was provided.

**Comment by JustCodin** [comment]
I recently ran into this issue as well. And it seems justified to return an error as this is done in mysql when trying to query with incorrect fields. Not sure what other dbs return in this situation. This seems like it could be a relatively simple fix with a large impact.
