### ISSUE TITLE
Does loopback support sqlite?

### ISSUE THREAD

**Issue by xeoshow** [strongloop/loopback#3970]
Hello,

I am new to loopback, just would like to know if it supports sqlite?

Thanks!

Best regards, Jason

**Comment by virkt25** [comment]
See if https://www.npmjs.com/package/loopback-connector-sqlite3 suites your needs.

**Comment by virkt25** [comment]
You're right in that there is no official support as it's a community module. I've never used it myself so can't speak if it's good or not but it's worth a shot.

**Comment by xeoshow** [comment]
@virkt25 Thank you so much! I will have a try and report back.
@dhmlau Thanks for help! So, does LoopBack 4 support sqlite3 out of the box? The preivous sqlite modules still should work on LoopBack 4 ? Thanks again!

**Comment by dhmlau** [comment]
If this module (https://www.npmjs.com/package/loopback-connector-sqlite3) @virkt25 mentioned is working in LoopBack 3, it will be working in LoopBack 4.

**Comment by dhmlau** [comment]
@xeoshow , I'd like to close this issue as question answered.  If you have further issues or questions, feel free to open a new ticket. Thanks.

**Comment by shubhddn01** [comment]
Is sqlite connector really works? I'm still stuck while making out the electron build. Please let me know if it really works with loopback3 or 4, I am comfortable with both versions.

**Comment by dhmlau** [comment]
The sqlite connector is built by the community, you might want to ask in that repo: https://github.com/strongloop-community/loopback-connector-sqlite3.

**Comment by shubhddn01** [comment]
Already dropped my concern for https://github.com/strongloop-community/loopback-connector-sqlite3/issues/40 . Please let me know if anybody have the solution or I have to write wrapper for sqlite.

**Comment by zypA13510** [comment]
> The sqlite connector is built by the community

@dhmlau But according to the docs [here][1] and [here][2], it is not exactly a community connector, is it?

> officially-supported database connectors

> the official SQLite3 connector module

According to the issue linked above by shubhddn01, the connector has been broken for more than 5 years without a fix.

[1]: https://loopback.io/doc/en/lb4/Database-connectors.html
[2]: https://loopback.io/doc/en/lb4/SQLite3.html
