### ISSUE TITLE
After remote not filtering instance array

### ISSUE THREAD

**Issue by brunoescalona** [strongloop/loopback#3977]
# Description/Steps to reproduce

If I try to filter the instance array obtained, for example, in the find method in the after remote hook. The instance array is modified but the response from the server is not filtered.

```
Model.afterRemote('find', (ctx, instance, next) => {
     console.log(instance) // print the following [{number: 2}, {number: 5}, {number: 5}]
     instance = instance.filter(item => item.number == 5)
     console.log(instance) // print the following [{number: 5}, {number: 5}]
     next()
  })
```

# Expected result

The expected result for the above code should be something like:
```
[
    {
        number: 5
    },
    {
        number: 5
    }
]
```
but I get the following result:
```
[
    {
        number: 2
    },
    {
        number: 5
    },
    {
        number: 5
    }
]
```
# Additional information

If for example instead of filtering the array I add some new property or modify some object property the response obtained is the expected with the properties modified or added.

**Comment by Djinne** [comment]
isn't it ctx.result.filter?
