### ISSUE TITLE
Lack of documentation about Middleware and custom phases

### ISSUE THREAD

**Issue by sboudouk** [strongloop/loopback#3979]
# Description/Steps to reproduce

I added a custom phase to my app like so:

```
"auth": {},
  "parse": {
    "body-parser#json": {},
    "body-parser#urlencoded": {"params": { "extended": true }}
  },
  "pdfgen" : {
    "./middleware/pdfhandling": {
      "methods": ["POST"],
      "path": "/Orders"
    }
  },
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    }
  },
```

`pdfgen` is my custom phase. Despite specifing it execution only on `/Orders` and `POST` method, it keeps running on every query that my API get.

I have also tried to set it in the `routes` fields: 

```
"parse": {
    "body-parser#json": {},
    "body-parser#urlencoded": {"params": { "extended": true }}
  },
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    },
    "./middleware/pdfhandling":{
      "paths": [
        "/Orders"
      ],
      "methods": ["POST"]
    }
  },
```

This time, it is not even executed whatever the request is (in the right endpoint like `.../api/Orders` or a bad one `.../api/Whatever` , regardless of methods, POST, GET etc...). Am I doing anything wrong ? If so, the documentation really needs more examples about adding custom phases and middlewares.

Once I understand how this works, it will be a pleasure to contribute and add thoses examples.

# Expected result

I expect my middleware to run only on `/Orders` on `POST` method. Whatever I use it as a phase (What seems wrong to me since a phase must be passed each time a query is made), or in the route field in `middleware.json`.

# Additional information

`darwin x64 8.11.3`
```├── loopback@3.22.0
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.2.0
├── loopback-connector-mongodb@1.18.1```

**Comment by raymondfeng** [comment]
@sboudouk Have you checked out https://loopback.io/doc/en/lb3/Defining-middleware.html?

**Comment by raymondfeng** [comment]
It should be:
```
"pdfgen" : {
    "./middleware/pdfhandling": {
      "methods": ["POST"],
      "paths": ["/Orders"]
    }
  },
```

**Comment by sboudouk** [comment]
`"pdfgen" : {
    "./middleware/pdfhandling": {
      "methods": ["POST"],
      "paths": ["/Orders"]
    }
  },
 `

Don't work for me.  But this syntax do:

`  "pdfgen" : {
    "./middleware/pdfhandling": {
      "methods": ["POST"],
      "path": "/Orders"
    }
  },`

Any explication on this ? Also, here is the `middleware/pdfhandling`, if it can help:

`module.exports = function() {
    return function pdfMiddleware(req, res, next) {
      console.log(req.method +' '+ req.originalUrl);
      console.log("IN PDFZBREH");
      if(req.method == "POST" && req.originalUrl == "/api/Orders"){
        console.log("in if");
        var pdfBase64Promise = PDF(req.body, res);
        pdfBase64Promise.then(function(result){
          res.send(result);
        }).catch(function(error){
          res.send(error);
        });
      } else {
        console.log("in else");
        next();
      }
    };
  };
`

**Comment by raymondfeng** [comment]
What's the version of your `loopback` module? I'm very sure for LoopBack 3.x, only `paths` is supported. 

You can print out more information with `DEBUG=loopback:app` env var. See https://github.com/strongloop/loopback/blob/master/lib/server-app.js

**Comment by sboudouk** [comment]
Here are my `package.json` loopback's versions:

```
  "loopback": "^3.19.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^6.0.0",
    "loopback-connector-mongodb": "^1.18.1",
```

**Comment by raymondfeng** [comment]
1. Do you expect pdfgen to be triggered for `/api/Orders`? If so, the path needs to be `/api/Orders`.

2. I don’t see your new phase in the log

**Comment by sboudouk** [comment]
1. Yes, I expect pdfgen to be triggered when a POST is occured on `/api/Orders`. Thanks for specifying that i need to provide full api address.

2. Here is the output with debug on now:

```
> node .

  loopback:app use initial:before  favicon +0ms
  loopback:app use initial  compression +3ms
  loopback:app use initial  corsMiddleware +1ms
  loopback:app use initial  xXssProtection +0ms
  loopback:app use initial  frameguard +1ms
  loopback:app use initial  hsts +0ms
  loopback:app use initial  hidePoweredBy +0ms
  loopback:app use initial  ienoopen +0ms
  loopback:app use initial  nosniff +0ms
  loopback:app use parse  jsonParser +0ms
  loopback:app use parse  urlencodedParser +0ms
  loopback:app use routes /api restApiHandler +0ms
  loopback:app use routes /api/Orders handler +149ms
  loopback:app use final  raiseUrlNotFoundError +0ms
  loopback:app use final:after  strongErrorHandler +0ms
Web server listening at: http://localhost:3000
Browse your REST API at http://localhost:3000/explorer
```

my `/api/Orders` handler seems to be detected now, but still don't trigger when I do a POST request on the `/api/Orders` endpoint.

Here is my `middleware.json` now:

```
  "parse": {
    "body-parser#json": {},
    "body-parser#urlencoded": {"params": { "extended": true }}
  },
  "routes": {
    "loopback#rest": {
      "paths": [
        "${restApiRoot}"
      ]
    },
    "./middleware/pdfhandling": {
      "methods": ["POST"],
      "paths": ["/api/Orders"]
    }
  },
  "files": {},
```

**Comment by raymondfeng** [comment]
You need to have the middleware come before `loopback#rest`.

**Comment by sboudouk** [comment]
It's working perfectly now. Is it specified anywhere in the doc that you need to put it before `loopback#rest` and provide full api path ? 

If it is not, I can do a pull request to add better and simpler example that will surely help beginners like me.

Thanks for you help @raymondfeng
