### ISSUE TITLE
DeprecationWarning: collection.insert is deprecated

### ISSUE THREAD

**Issue by b3rew** [strongloop/loopback#3981]
# Description/Steps to reproduce
I am getting DeprecationWarning message when I try to insert data into my model
 
`(node:13177) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.`

Mongo: v3.6.3
Nodejs : v8.11.2
loopback: v3.22.1
loopback-connector-mongodb: v3.6.0

I already submitted this issue on loopback-connector-mongodb repo [here](https://github.com/strongloop/loopback-connector-mongodb/issues/455)

**Comment by alidavid0418** [comment]
I am looking for an answer for this issue, and so funny that this is opened on my birthday.

Thanks to `strongloop` contributers, I could overcome the issue by updating to `v4.2.0` for now.
I think it might be okay to close this issue.
Thanks
