### ISSUE TITLE
Loopback docs are down

### ISSUE THREAD

**Issue by CamiloTD** [strongloop/loopback#3984]
Right now the docs site is throwing an internal server eror
https://apidocs.strongloop.com/loopback
![image](https://user-images.githubusercontent.com/12549059/44864363-1764c100-ac45-11e8-8adf-d3a632e9c5d9.png)

**Comment by dhmlau** [comment]
@CamiloTD, thanks for reporting this.  It seems to be working for me.  Could you please check again?  Thanks.

**Comment by raymondfeng** [comment]
I fixed it 30 mins ago.
