### ISSUE TITLE
Referencing a Field with an Operator in Where Filter Returns No Results  (Loopback 2)

### ISSUE THREAD

**Issue by infinisuite** [strongloop/loopback#3985]
Using a field name in a where filter with an operator appears to return empty results. For example this URI will return an empty array (it should return two rows) given the SAMPLE DATA below:

`/api/customeropeninvoices/?filter={"where":{"and":[{"relationshiprowid":"139"},{"paidamount": {"lt": "totalamount"}}]}}`

However, this URI will return two rows (note that the 'totalamount' field has been replaced with a hardcoded value: 1):
`/api/customeropeninvoices/?filter={"where":{"and":[{"relationshiprowid":"139"},{"paidamount": {"lt": 1}}]}}`

And, oddly this URI will return all rows where relationship=139 (note the 'lte' operator).

`GET /api/customeropeninvoices/?filter={"where":{"and":[{"relationshiprowid":"139"},{"paidamount": {"lte": "totalamount"}}]}} `

How can 'where' filters be constructed that use field names with operators?

**SAMPLE DATA**
`[
    {
        "rowid": 35,
        "transactionid": "IN00000007",
        "totalamount": 1500,
        "paidamount": 1500,
    },
    {
        "rowid": 37,
        "transactionid": "IN00000008",
        "totalamount": 1500,
        "paidamount": 1500,
    },
    {
        "rowid": 39,
        "transactionid": "IN00000009",
        "totalamount": 1500,
        "paidamount": 0,
    },
    {
        "rowid": 41,
        "transactionid": "IN00000010",
        "totalamount": 1500,
        "paidamount": 0,
    }
]`

**Comment by raymondfeng** [comment]
`Where` does not treat `totalamount` as a field, but takes it as the string literal.
