### ISSUE TITLE
The assertions in the callback functions of test/acl.test.js doesn't affect test results 

### ISSUE THREAD

**Issue by moshemal** [strongloop/loopback#3988]
It seems that the assertions in the callback functions doesn't effect test results. For example, if I add assert(false) at line 239 the test still pass.
As Mocha documentation explains one should use the method done()
https://mochajs.org/#asynchronous-code

# Description/Steps to reproduce
Add assert(false) to one of the callbacks, for example line 239 and run the tests. The tests are expected to fail on that assertion but they don't

# Expected result
fail

**Comment by dhmlau** [comment]
Moving it to `In Progress` as there is PR #3989 to fix the issue.

**Comment by dhmlau** [comment]
PR #3989 has been merged.  Closing it as resolved.
@moshemal , thanks for your contribution! 🎉
