### ISSUE TITLE
Custom loopback connector for IBM Cloud Object Storage repo creation and code review

### ISSUE THREAD

**Issue by Conor-Quin** [strongloop/loopback#3990]
I have created my own loopback connector for IBM Cloud Object Storage (https://github.com/Conor-Quin-ibm/loopback-connector-cos) which includes an incisive README.md as discussed on slack with @bajtos and @raymondfeng .

I am now looking to contribute this code to your strongloop GitHub.

I can see that each connector is in itself it's own repo and so I am hoping to get a code review on this code and a repo to be created for this code to be used.

Thank you

**Comment by dhmlau** [comment]
@Conor-Quin-ibm , thanks for your contribution.  Since you're already working with @bajtos on this, I'm moving this to "In Progress".

**Comment by Conor-Quin-ibm** [comment]
Pull Request submitted for code review https://github.com/strongloop-community/loopback-connector-cos/pull/2
