### ISSUE TITLE
How to get userId in  middleware

### ISSUE THREAD

**Issue by kartik-ts** [strongloop/loopback#3991]
I have written custom ACL and Roles which would be managed using the database. So each time a user tries to access an API I want to check the permission. now to check the permission first thing I need is userId. How can I get userId of the current user in from the middleware. I'm writing the logic in the middleware. Please give suggestions as well.

**Comment by dhmlau** [comment]
@hacksparrow , could you PTAL? thanks.

**Comment by hacksparrow** [comment]
You can go through the code in `app.enableAuth()` that's running from `remotes.authorization` to see what you need to execute from the middleware.
