### ISSUE TITLE
inverse priority datasource files when env set 

### ISSUE THREAD

**Issue by lluisruscalleda** [strongloop/loopback#3992]
Hi I have problems with datasource files when setting an env variable, 
I need a mysql connection with different passwords for a local and a production one environment, remaining model datasbse name use

# Description
FIles
datasouce.json:
```
{
  "db": {},
  "mysql": {}
}
```
datasource.local.json:
**IMPORTANT**: db with "memory" connector for distinguish when tested
```
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "mysql": {
    "name": "mysql",
    "connector": "mysql",
    "host": "localhost",
    "port": 3306,
    "database": "database",
    "username": "root",
    "password": "pwd1"
  }
}
```
datasource.production.json:
```
{
  "db": {
    "name": "db",
    "connector": "mysql",
    "host": "localhost",
    "port": 3306,
    "database": "database",
    "username": "root",
    "password": "pwd2"
  }
}
```

Script in package.json:
`"db:connector": "set NODE_ENV=production && node server/bin/display-datasource-connector"`

server/bin/display-datasource-connector file:
```
var server = require('../server');
var ds = server.dataSources.db;
console.log('NODE_ENV: %s',process.env.NODE_ENV);
console.log('Connector: %s',ds.connector.name);
```

# Steps
`npm run db:connector`

# Expected result
```
NODE_ENV: production
Connector: db
```

# Current result
```
NODE_ENV: production
Connector: memory
```

Any bug? Any thoughts? 

Thanks in advance!

EDIT: Windows platform

**Comment by hacksparrow** [comment]
@lluisruscalleda use `export NODE_ENV=production` instead of `set NODE_ENV=production` else `NODE_ENV` value will be lost in the child process.

**Comment by lluisruscalleda** [comment]
Thanks, but I'm on Windows , export does not work. I'will search about passing to child proces
