### ISSUE TITLE
Hot Reloading

### ISSUE THREAD

**Issue by chiqui3d** [strongloop/loopback#3994]
When I'm developing one API with loopback I need to constantly change the models code for testing. Right now to make a change and test it again I need to kill the server listening and call it back, that's a waste of time.

My request is that it is applied by default every time I make a change in the models or in any file around the application, I see nothing in the documentation and neither in the next version 4.

Thanks and great work

**Comment by virkt25** [comment]
You can look into using a node module such as [`nodemon`](https://www.npmjs.com/package/nodemon) to monitor files and trigger a restart automatically.
