### ISSUE TITLE
Saving find result to a variable

### ISSUE THREAD

**Issue by kareemhossam** [strongloop/loopback#3995]
I'm trying to save find results to a variable, I looked around and couldn't find any clear answer, here is what i want to do:

```
var data;    
myModel.findOne({
            where: {
                Key: 'myKey'
            }
        }, function(err, model) {
            if (err) {
                console.log(err);
            }
            data = model;
        });
```

**Comment by israelglar** [comment]
Your code should be working. The only thing that you have to be aware of, is that javascript is asynchronous and uses callback functions.
If you want to use ``data`` after the findOne, you can use it inside the callback function.

You can see how callback works here: https://codeburst.io/javascript-what-the-heck-is-a-callback-aba4da2deced

**callback**
```
myModel.getOne = function(myKey) {
	myModel.findOne({
		where: {
			Key: myKey
		}
	}, function(err, model) {
		if (err) {
			console.log(err);
		}
		var data = model;
		// Use variable data het
	});
}
```

Or you can choose to use async/await: https://loopback.io/doc/en/lb3/Remote-methods.html#using-asyncawait

**async/await**
```
myModel.getOne = async function(myKey) {
	var data = await myModel.findOne({
		where: {
			Key: myKey
		}
	})

	// Use variable data here
}
```
