### ISSUE TITLE
Has no exported member 'ServiceMixin'.

### ISSUE THREAD

**Issue by cfaguilera20** [strongloop/loopback#3997]
# Description

npm start return the next error:

Module '"/publisher/node_modules/@loopback/service-proxy/index"' has no exported member 'ServiceMixin'.

5 import {ServiceMixin} from '@loopback/service-proxy';

**Comment by dhmlau** [comment]
@cfaguilera20 , could you please take a look at this issue: https://github.com/strongloop/loopback-next/issues/1688?  It might be a duplicate. 
Also, for all the LB4 related issues, please report it in `loopback-next` repo.  Thanks.

**Comment by cfaguilera20** [comment]
Thank you @dhmlau !
