### ISSUE TITLE
Custom Permisison in loopback

### ISSUE THREAD

**Issue by kartik-ts** [strongloop/loopback#3998]
Hi everyone, We are building an application where the permission module is designed by using ACL and RBAC. We are not using the ACL that loopback has. Instead, we are writing logic in middleware where we can check according to the permission if a user has access to a particular module(which is dynamic). I need to get a few information for that like:-

method : GET/POST/DEL/etc
Module Name: User/Role/etc
Action: update/upsert/find/delete/etc
one custom field which I would pass in every request.
how can I achieve this? Or should I be checking the permission in each module itself? Like in the client module I can use the permission using before method.
Thanks in advance.

**Comment by dhmlau** [comment]
@hacksparrow , could you PTAL?  thanks!

**Comment by kartik-ts** [comment]
What is PTAL?

**Comment by kartik-ts** [comment]
Okay. Thanks. What is your suggestion.

**Comment by hacksparrow** [comment]
It's not simple. You can go through the code in `app.enableAuth()` that's running from `remotes.authorization` to see what you need to execute from the middleware.

**Comment by codekeyz** [comment]
Do check this out. https://github.com/codekeyz/loopback-multirole-api-starter. It can be helpful creating API with multirole like Manager, Driver, User. And assign this roles in ACL
