### ISSUE TITLE
findOne not making correct request for lb4 -> lb2 service

### ISSUE THREAD

**Issue by payne-chris-r** [strongloop/loopback#3999]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result
Expecting `thingRepository.findOne({ where: { prop: "value" } })` to make a request like:
`GET /things/findOne?filter={ "where": { "prop": "value" } }`, however, it's making
`GET /things?where[prop]=value`
Is there a way to tell lb4 to use JSON formatting over bracket?
I've found this: https://loopback.io/doc/en/lb2/Exposing-models-over-REST.html
but I don't know how to tell lb to use one over the other...

# Additional information

**Comment by virkt25** [comment]
Can you try passing `JSON.stringify({where: ...})` to `findOne`? Also the LoopBack 4 repository would be a better place for this question. https://github.com/strongloop/loopback-next.

cc: @raymondfeng @bajtos I don't know of a way to change how the query is constructed by LB4. Do you?

**Comment by bajtos** [comment]
Closing in favor of https://github.com/strongloop/loopback-next/issues/1707
