### ISSUE TITLE
Add after error hook to DAO

### ISSUE THREAD

**Issue by hvlawren** [strongloop/loopback#4016]
# Description/Steps to reproduce

As discussed in the LoopBack-at-IBM channel, I would like an "after error" hook for the DAO similar to the afterRemoteError remote hook. The current afterExecute hook is not called in error conditions. This would allow for easy DB error specific error handling.

**Comment by bajtos** [comment]
@raymondfeng you are more familiar with `before execute` and `after execute` hooks provided by our connectors. Could you please advise what's the best place where to add `after error` hook? Should we add it as connector-specific hook to be consistent with before/after execute, or add it as another Operation Hook to be consistent with before/after save/delete?

@hvlawren what kind of data would you like to see in the context provided to the hook callback?

I think the following two properties should be easy to pass in the context for all operations: `Model`, `error`. 

We may be able to pass `instance` or `data`+`where` too, although I am not sure if we can find a a clean solution that supports all different operations (full replace, partial update of single/multiple instances, delete).

https://loopback.io/doc/en/lb3/Operation-hooks.html#before-save 
> Full save of a single model
> - Model - the constructor of the model that will be saved
> - instance - the model instance to be saved. The value is an instance of Model class.
>
> Partial update of possibly multiple models
> - Model - the constructor of the model that will be saved
> - where - the where filter describing which instances will be affected
> - data - the (partial) data to apply during the update

https://loopback.io/doc/en/lb3/Operation-hooks.html#before-delete
> Context properties
> 
> - Model - the constructor of the model that will be queried
> - where - the where filter describing which instances will be deleted.

**Comment by hvlawren** [comment]
Hi! I think Model and error would be sufficient for me, though I can see how other other fields may be useful for others.

I do want to make sure that like the afterRemoteError hook, the error can be replaced or updated using this new hook.

**Comment by bajtos** [comment]
Hmm, I am afraid we don't have enough time to make this feature happen before LB 4.0 GA is released, after which LB 3.x moves into Active LTS and will not accept any new features any more :(

Is there any chance you could upgrade your project from LB 3.x to LB 4.0?
