### ISSUE TITLE
How to filter Subscribers based on array of tags

### ISSUE THREAD

**Issue by gijo-varghese** [strongloop/loopback#4019]
I've two models - **subscribers** and **tags**

Sample data: 

    {
     subscribers: [
      {
       name: "User 1",
       tags: ["a","b"] 
      },
      {
       name: "User 2",
       tags: ["c","d"] 
      }
     ]
    }

I want to filter subscribers based on their tags. 

 - If I give `a` and `b` tags, User 1 should list 
 - If I give `a` and `c` tags, both User 1 and User 2 should list

Here is what I tried:

**Method 1:**

`tags` is a column in `subscribers` model with array data type

    /subscribers/?filter={"where":{"tags":{"In":["a","b"]}}} // doesn't work

**Method 2:**

Created a separate table `tags` and set `subscribers` has many `tags`.

    /subscribers/?filter={"where":{"tags":{"In":["a","b"]}}} // doesn't work

How can I achieve this in Loopback without writing custom methods?

I've **Postgresql** as the connector

**Comment by jschmold** [comment]
I personally would strongly discourage this method of filtering (JSON in the URL). I would recommend writing custom methods and using a different URL strategy.

`/subscribers?tags=a,b` is a more coherent URL, and removes the hell of URL parsing you're going to end up creating yourself.

In JS, you could easily scrub all the tags using `let tags = theTagVar.split(',')` where `theTagVar` is the values for the parameter `tag`.

**Comment by gijo-varghese** [comment]
@jschmold Thanks for the suggestion. However, there is a change that user can select multiple filters. The tag-based filter is one of them. All other filters are already supported by Loopback. For example, I need to filter subscribers based on tags, created date, gender etc. I can build a custom route as you suggested, but then I've to implement all other methods

**Comment by jschmold** [comment]
> @jschmold Thanks for the suggestion. However, there is a change that user can select multiple filters. The tag-based filter is one of them. All other filters are already supported by Loopback. For example, I need to filter subscribers based on tags, created date, gender etc. I can build a custom route as you suggested, but then I've to implement all other methods

I recommend reading up more on HTTP REST APIs. Specifically [query strings](https://en.wikipedia.org/wiki/Query_string), and [Microsoft's API guidelines](https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md). 

But to further fill you in, applying multiple filters is as easy as adding another parameter.

A GET Request
`/subscribers?tags=a,b&gender=m&createdDate=1538659629107`

A POST Request
`/subscribers`
Body
```
{
    "tags": ["a", "b"],
    "gender": "m",
    "createdDate": 1538659629107
}
```


It is generally understood with regards to any API that if you are doing a list-operation on a GET request in which you are pulling a list of filtered results of a kind of thing, you also support `page` and `limit` (pagination), and that all other query string parameters are the filters to be applied to the list operation. The default values for page and limit are generally `page = 1, limit = 25`.

A note about the date, always use a [Unix Timestamp](https://www.unixtimestamp.com/). It's the easiest to parse, is universally compatible, and prevents issues. [MomentJS](https://momentjs.com/) helps with building Dates/Times (including timezones).

**Comment by gijo-varghese** [comment]
@jschmold yup. I'm checking whether Loopback has already built this. Otherwise, it's like doing everything in Express.

**Comment by jschmold** [comment]
[It appears so](https://loopback.io/doc/en/lb3/Exposing-models-over-REST.html)

**Comment by jschmold** [comment]
Try 
`[where][tags][inq]=a&[where][tags][inq]=b`
Or the thing I suspect should work, but might not
`[where][tags][inq]=a,b`

**Comment by gijo-varghese** [comment]
@jschmold but, loopback saves `array` as `text` in DB (I use Postgres). Maybe I've to use `like`?

**Comment by gijo-varghese** [comment]
@jschmold finally found a hack, using Regex! It works!!!

{ "where": { "tags": { "regexp": "a|b" } } }
