### ISSUE TITLE
Create change stream causes issues

### ISSUE THREAD

**Issue by imike57** [strongloop/loopback#4027]
Hi,

I encounter some problem with the use of the change-stream API, the data is loaded but not after several access to the page that performs the requests.

# Description
I make requests and subscribe to two collections:
```

    // Get collection items
    this.categoriesTree$ = this.categoryTreeApi.findOne({ "order": "created DESC" }).subscribe((categoryTree: CategoryTree)=>{
      this.categoryTree = categoryTree.value;

      // Inspect collection change
      this.categoriesTreeChange$ = this.categoryTreeApi.createChangeStream().subscribe((majCategoryTree: any) => {
        console.log(majCategoryTree);
        
      }, (err: any) => {
        this.notificationsService.error('Oops ! ', 'An error occurred while listening to the changestream of categoryTreeApi : ' + err.message);
        console.error(err)
      });

    }, (err: any) => {
      this.notificationsService.error('Oops ! ', 'The Tree has not been loaded : ' + err.message);
      console.error(err)
    });

```
I unsubscibe to theses subscription while onDestroy();

I got my content during the first page loading. Everything is well loaded. 
![image](https://user-images.githubusercontent.com/24215428/46914372-cca4cb80-cf9c-11e8-9c74-40bfcfddcd92.png)

Then I just change of page to "Products" and back to "Categories" page. (Products page is empty for now)

![image](https://user-images.githubusercontent.com/24215428/46914382-fa8a1000-cf9c-11e8-813a-86df6c4a8ac8.png)

It still work well... 

But if I did it 2 times more, it no more working...  

![image](https://user-images.githubusercontent.com/24215428/46914388-1db4bf80-cf9d-11e8-9ecc-d2b6dcb6669d.png)

The request is still pending

![image](https://user-images.githubusercontent.com/24215428/46914395-32915300-cf9d-11e8-95ce-79cc3171e0d5.png)

No error in the console during some seconds or minutes sometime then : 
![image](https://user-images.githubusercontent.com/24215428/46914651-a123e000-cfa0-11e8-8085-5c324a4e5130.png)
 

I'm sure it's related to the createchangestream because if I remove these subscription it work well, but I need it to update some content in realtime.. 

I subscribe to the change subscription only when my main category subscription is ready. So it seems that it is the subscription to the changes of the previous step that cause issue. However, I am unsubscribing to this subscription to the event onDestroy (), so should not I be killed? Yet it seem still there
![image](https://user-images.githubusercontent.com/24215428/46914494-d7f8f680-cf9e-11e8-9c1b-ea8819d94948.png)

# Expected result
Be able to make connections correctly at any time after a page change when subscriptions to changestream have been previously made.

# Additional information
I use loopback 3.x 
```
\lb-server> lb --version
4.2.0 (generator-loopback@5.9.2 loopback-workspace@4.3.1)
```
SDK builder https://github.com/mean-expert-official/loopback-sdk-builder
Angular 6

**Comment by Desgaibou** [comment]
I have the same issue. Any suggestion?
Thanks
