### ISSUE TITLE
Nodemailer v1.0 - smtp transport parameter change - needs documentation update

### ISSUE THREAD

**Issue by johnsoftek** [strongloop/loopback#403]
The email examples in the documentation section *Using built-in models* need a minor change.

From the Nodemailer v1.0 release announcement:

> There was a mixup with nodemailer-smtp-connection secure option. It used to be *secureConnection* in the old Nodemailer and somehow the old option name slipped through in some parts of the new stack. This is now fixed (Nodemailer v1.0.2 and nodemailer-smtp-transport v1.0.11), so use *secure* as stated in the docs.

```javascript
// create a mail data source
var mail = loopback.createDataSource({
  connector: loopback.Mail,
  transports: [{
    type: 'smtp',
    host: 'smtp.gmail.com',
    secure: true,   // was secureConnection
    port: 465,
    auth: {
      user: 'you@gmail.com',
      pass: 'your-password'
    }
  }]
});
```

**Comment by superkhau** [comment]
@crandmck Safe to close?

**Comment by crandmck** [comment]
Yes, this is fixed -- Not sure why it wasn't closed previously.
