### ISSUE TITLE
Async method requesting twice 

### ISSUE THREAD

**Issue by marcosjosemoura** [strongloop/loopback#4030]
Hello.

My team is having this issue with async methods of loopback.
The error below is thrown in every request that we try to do.
We suspect that the problem might be in the latest version of async, but we are not able to test this theory because even when we use a previous version of Loopback, the dependencies are are updated to the latest version.

Do you guys know a way to stop Loopback from updating the async's version?

Thank you in advance.

# Description/Steps to reproduce
As example, we do a simple request that should return a JSON Object array:

<img width="1440" alt="screen shot 2018-10-16 at 11 11 38" src="https://user-images.githubusercontent.com/44201534/47022665-62269380-d134-11e8-82d6-936da615a8eb.png">

The request returns nothing, then the backend closes immediately due to the error.

<img width="1440" alt="screen shot 2018-10-16 at 11 02 33" src="https://user-images.githubusercontent.com/44201534/47022664-618dfd00-d134-11e8-9ddb-42d2a2ef5851.png">

# Additional information

### The errror thrown:

/app/node_modules/async/dist/async.js:966
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /app/node_modules/async/dist/async.js:966:32
    at /app/node_modules/async/dist/async.js:3885:13
    at interceptInvocationErrors (/app/node_modules/strong-remoting/lib/remote-objects.js:690:22)
    at /app/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at /app/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at /app/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at /app/node_modules/strong-remoting/lib/remote-objects.js:656:7
    at /app/node_modules/strong-remoting/lib/http-context.js:397:7
    at callback (/app/node_modules/strong-remoting/lib/shared-method.js:253:5)
    at /app/node_modules/loopback-datasource-juggler/lib/dao.js:2009:11
    at /app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:396:17
    at done (/app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:167:19)
    at /app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:40:16
    at /app/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:393:21
    at /app/node_modules/loopback-datasource-juggler/lib/dao.js:1986:17
    at doNotify (/app/node_modules/loopback-datasource-juggler/lib/observer.js:99:49)

output of the command node -e 'console.log(process.platform, process.arch, process.versions.node)': 
    
     darwin x64 8.11.3

output of the command npm ls --prod --depth 0 | grep loopback:

   ├── loopback@3.23.0
   ├── loopback-boot@2.27.1
   ├── loopback-component-explorer@6.3.0
   ├── UNMET DEPENDENCY loopback-connector-db2@^2.1.1
   npm ERR! missing: loopback-connector-db2@^2.1.1, required by watsonar-backend@1.0.0

**Comment by hacksparrow** [comment]
@marcosjosemoura fix has been landed via https://github.com/strongloop/loopback-ibmdb/pull/73. Please update to the latest version.
