### ISSUE TITLE
switching database cause error on 2 time url hit

### ISSUE THREAD

**Issue by rockyshukla** [strongloop/loopback#4035]
I do lots of googles but haven't found any solution for my problem so I posted over here let me showpiece of code with creating an issue (note I m using loopback-connector-sqlite3)

       'use strict';       

       //  var sqliteloopback= require('loopback-connector-sqlite')
         //var db=       

       module.exports =async  (app,cb)=> {
         
       	// app.test=async(app,cb)=>{
         var user=app.models.variant
         var models = app.models();
         var dbold = require('../server/datasources.json');
         var DataSource = require('loopback-datasource-juggler').DataSource;
         var pgsql=app.datasources.db
          var sqlite=app.datasources.dbsql       

       //----------------------------connect old ---------------------------//
       // console.log()
        await reconnect(models,pgsql)
       try{
           var usersql = await app.models.variant.find();
       }catch(err){
       		console.log(err)
       	}
             console.log("data1")
              console.log(usersql)       

       //----------------------------migration------------------------------------------//
       	await pgsql.disconnect();
         await reconnect(models,sqlite)       

       //----------------------------------end----------------------------------------//       
       
       

       //--------------------------------copy from one table to another--------------//
       	console.log('loop start')
         for(let i=0;i<usersql.length;i++){
                	console.log(usersql[i].regcity_code)
                   var datavariant={ regcity_code:usersql[i].regcity_code,
                                     company_id: usersql[i].company_id,
                                     variant_id: usersql[i].variant_id,
                                     variant_name: usersql[i].variant_name}
         
         	 try {
              	await user.create(datavariant)
              await	sqlite.finalize() 
              }catch (error) {
                console.error(error);
             }
         }
       //----------------------------------end----------------------------------------//       

       //-------------------------------------close connection -------------------------------//       

       try{
       await	sqlite.disconnect();       

       }catch(err){
       	console.log(err)
       }       
       

       }       

async function reconnect(models,db){

   console.log(db.name)
   if(db.name=="db"){
        
                               await    db.connect(function(err,con){
                                if(err){console.log(err);}
                                console.log("connected to pgsql")
                               });
      
              var lbTables = ['user', 'companytype','AccessToken','dbconnect','sequience', 'ACL', 'RoleMapping', 'Role', 'ForgotPassword','category','subcategory','brand','hsn','taxrate','variant','variantvalue','unittype','sales','saledetail','salertdetail','salesreturn','purchase','purchasertdetail','purchasedetail','purchasereturn','estshopinventory','inventorypayments','supplier','supplierdetail','stocktransfer','supplierbank','productimage','productspecification','companyproduct','userrole','shopuser','shopestablishment','companybank','companydetail','company','customer','customerbank','customerdetail','country','state','statecode','city','permissiontb','permissionpg','salepayment','mbrand','mcategory','mcompanyproduct','mhsn','mproductimage','mproductspecification','msubcategory','mtaxrate','munittype','mvariant','mvariantvalue'];
  console.log('migration waiting start')

  
     await  models.forEach(function(Model) {

       Model.attachTo(db)
   });
    }else{

         var lbTables = ['variant'];
       
     await  models.forEach(function(Model) {

       Model.attachTo(db)
   });
   await   db.automigrate(lbTables);
   }
 now problem is that after return value for eg :- suppose user hit url like 'api/download' all above code works properly but problem is that if user against hit same url it throws an error like  "Timeout in connecting after 5000 ms" i.e I do not connect to default database which is pgsql. can anybody tell me what is the issue behind this

**Comment by hacksparrow** [comment]
@rockyshukla please upload a bare-minimum project which replicates the problem you are facing. I will be able to take a better look and help you.

**Comment by rockyshukla** [comment]
@hacksparrow  here is a link of repository https://github.com/rockyshukla/loopbackdemo/tree/master/loopbackdemo
problem occur when I m trying to disconnect to pgsql  and connect to sqlite and at last line of code I m disconnecting to sqlite (both connect and disconnect not working when the user hit URL like :-localhost:3000 /download/dsdsd second time )  can you tell me what is issue

**Comment by rockyshukla** [comment]
@hacksparrow did you found issue why this happing

**Comment by rockyshukla** [comment]
@hacksparrow  please check when you get time
