### ISSUE TITLE
application-generator: when parent-dir==application name, i cannot set custom source directory

### ISSUE THREAD

**Issue by remkohdev** [strongloop/loopback#4042]
I create a directory for a project 'fdic-api'
```
mkdir fdic-api
cd fdic-api
```
for the application 'fdic-api'
inside i have a data, api, README.md directory already
inside I want to generate a loopback application with same name inside a source code directory named 'src', but i cannot use the application generator, because when the parent directory is the same name as the application name, the generator 'assumes' i m already inside the source code dir. 
```
lb fdic-api
```
i expect/want to see 
```
? What's the name of your application? fdic-api
? Enter name of the directory to contain the project: src
```
but i only see 
```
? What's the name of your application? fdic-api
? Which version of LoopBack would you like to use? 3.x (Active Long Term Support)
```
it skips me to ask for the directory to contain the project (aka source code)

**Comment by bajtos** [comment]
Can you try the following approach?

```sh
$ cd fdic-api
$ mkdir src
$ cd src
$ lb fdic-api
```

The select the current directory (`.`) as the target directory where to create the new project.

Personally, I would find it very unusual to have a LoopBack project inside `src` directory - keep in mind that LoopBack applications are Node.js projects on their own, having their `package.json` file with npm scripts like `npm test`, test files in `test`, etc.

@remkohdev What is your use case? What are you trying to accomplish?
