### ISSUE TITLE
filter relation problem

### ISSUE THREAD

**Issue by J4si3k** [strongloop/loopback#4046]
Hi,

I have a problem with filtering data in relations.

On this enpoint:
`http://localhost:8080/api/orders?filter[include]=payments&filter[include]=customers&filter[include][details]=variants&filter[include][details]=products&filter[where][id]=1`
I get the following error:
`500 Relation "0" is not defined for Orders model`

Each order relation works correctly, but the example above does not work. for example, filters that WORK GOOD:
- Orders + Payments + Customers
- Orders + Customers + Variants via Details + Products via Details
- Orders + Payments + Variants via Details + Products via Details 

NOT WORK:
- Orders + Payments + Customers + Variants via Details + Products via Details 

Relations with Orders:
- Payments one to Many,
- Customers one to Many,
- Variants Many to Many (HasManyThrough),
- Products Many to Many (HasManyThrough)

**Comment by Sharu2806** [comment]
Hi,

I am also facing same issue. I upgraded my loopback version from 2.x to 3.x and after that I started getting this issue.

Could you please help to fix this issue.

Thanks.
