### ISSUE TITLE
Schedule cron job in loopback

### ISSUE THREAD

**Issue by anandrajputSF** [strongloop/loopback#4047]
How to create schedule cron job in loopback, where can I code?  I tried to implement `node-schedule ` but not work. I don't know how to call my controller code?

**Comment by matteo-pennisi** [comment]
To solve this I've used a workaround: I've created a public endpoint and a cron job that call that endpoint  using https://cron-job.org/
Hope that it helps :)

**Comment by hacksparrow** [comment]
@anandrajputSF can you explain your requirements in detail?

**Comment by anandrajputSF** [comment]
@hacksparrow basically my requirement is connect with sql server, after some time interval fetch data from tables and log some where, if next time cron run, it will pick data from log table last run time and from this time it will again fetch data from sql server

**Comment by hacksparrow** [comment]
@anandrajputSF LoopBack does not provide an in-built solution to your specific usecase, however with [Remote hooks](https://loopback.io/doc/en/lb3/Remote-hooks.html) it can be very well achieved.

**Comment by hacksparrow** [comment]
@anandrajputSF were you able to solve your problem?

**Comment by kimoudev** [comment]
I use loopback mail connector in the hooks operation.I would like to apply cron job to execute with a time period.Someone could help me please

**Comment by nikhil-g777** [comment]
@anandrajputSF I have implemented something similar in loopback, you can do it the way you would do it in NodeJS using this package : https://www.npmjs.com/package/cron
And you can paste the code in a file in the boot folder. Here is some example code : 

`'use strict';

const CronJob = require('cron').CronJob;

module.exports = function (app) {

    function runCron() {
       //The code which you want to run in the cron job
    }

    var job = new CronJob({
        cronTime: '00 00 10 * * 0-6', // The Time at which you want the cron job to run
        onTick: runCron,
        start: false,
        timeZone: 'Asia/Kolkata'
    });
    job.start();

}`


Hope this Helps !

**Comment by nikhil-g777** [comment]
@matteo-pennisi
You could use environment variables to keep one of the instances as the main instance with an instanceNumber as 1, which would run the cron job

`if(process.env.instanceNumber == 1)
{
   job.start()
}
`

This is more like a workaround, but I believe it should solve the problem

**Comment by dtelaroli** [comment]
It would be awesome if LB would have a way to inject a component, as a service or repository, in a cron component.

**Comment by dtelaroli** [comment]
This solution has worked for me.

### Installation

```
https://www.npmjs.com/package/node-cron
$ npm install --save node-cron
```

### Create a component

```
import { CronController } from "./controller/cron.controller";
export class Cron {
  constructor(
    protected cronController: CronController,
  ) {
  }

  async start() {
    this.eachMinute();
  }

  private async eachMinute() {
    console.log('Start Cron Jobs');

    cron.schedule('* * * * *', async () => {
      await this.cronController.start();
      console.log('running a task every minute');
    });
  }
}
```

### Using Loopback DI Container to get a controller instance:

```
// index.ts
export async function main(options: ApplicationConfig = {}) {
  const app = new MyApplication(options);
  await app.boot();
  await app.start();

  const url = app.restServer.url;
  console.log(`Server is running at ${url}`);
  console.log(`Try ${url}/ping`);

  // Instanciate CronController
  const cronController = app.controller(CronController);
  
  // Get Instance
  const cronControllerInstance = await cronController.getValue(app);
  
  // Inject by constructor
  const cron = new Cron(cronControllerInstance);

  // Invoke method
  cron.start();

  return app;
}
```

**Comment by filipef101** [comment]
@dtelaroli  Does that mean that the cron is only run on one instance?

**Comment by dtelaroli** [comment]
@filipef101 you can have multiple instances into the CronController or multiples Controllers into the Cron. It's up to you.

**Comment by juanvillegas** [comment]
Just for reference, there is a package called Bull that allows assigning an ID to the Job. If running multiple instances, attempting to create a job with an ID that already is in the queue will be ignored.
https://github.com/OptimalBits/bull

**Comment by tangoat2019** [comment]
> This solution has worked for me.
> 
> ### Installation
> ```
> https://www.npmjs.com/package/node-cron
> $ npm install --save node-cron
> ```
> 
> ### Create a component
> ```
> import { CronController } from "./controller/cron.controller";
> const cron = require('node-cron');
> 
> export class Cron {
>   constructor(
>     protected cronController: CronController,
>   ) {
>   }
> 
>   async start() {
>     this.eachMinute();
>   }
> 
>   private async eachMinute() {
>     console.log('Start Cron Jobs');
> 
>     cron.schedule('* * * * *', async () => {
>       await this.cronController.start();
>       console.log('running a task every minute');
>     });
>   }
> }
> ```
> 
> ### Using Loopback DI Container to get a controller instance:
> ```
> // index.ts
> export async function main(options: ApplicationConfig = {}) {
>   const app = new MyApplication(options);
>   await app.boot();
>   await app.start();
> 
>   const url = app.restServer.url;
>   console.log(`Server is running at ${url}`);
>   console.log(`Try ${url}/ping`);
> 
>   // Instanciate CronController
>   const cronController = app.controller(CronController);
>   
>   // Get Instance
>   const cronControllerInstance = await cronController.getValue(app);
>   
>   // Inject by constructor
>   const cron = new Cron(cronControllerInstance);
> 
>   // Invoke method
>   cron.start();
> 
>   return app;
> }
> ```

This solution worked for me as well. Loopback 4 tested
