### ISSUE TITLE
loopback-cli is in Russian

### ISSUE THREAD

**Issue by Y-Less** [strongloop/loopback#4048]
# Description/Steps to reproduce

I followed the instructions from the getting started page exactly:

https://loopback.io/getting-started/

This wasn't hard, as there was only one, type this:

```
npm install -g loopback-cli
```

I got the tool, tested it, and it asks for a project name in Russian (then hangs, but that's a separate issue):

![image](https://user-images.githubusercontent.com/991078/47660489-64a6d580-db97-11e8-9998-73b7075db87f.png)

# Link to reproduction sandbox

# Expected result

Not be in Russian.  I can read it, but I much prefer English.

# Additional information

```
win32 x64 10.9.0

grep : The term 'grep' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:27
+ npm ls --prod --depth 0 | grep loopback
+                           ~~~~
    + CategoryInfo          : ObjectNotFound: (grep:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by dhmlau** [comment]
@Y-Less, that's interesting.  If you run `echo $LANG`, what does it return?

**Comment by Y-Less** [comment]
I figured out that while my Windows language is English, the system locale setting was Russian, so that non-unicode things in Russian displayed correctly.  However, I can't find how to change the language for this one program back to English, that setting was just a fall-back.

**Comment by SergiySev** [comment]
I have same issue with german Windows.

**Comment by dhmlau** [comment]
When I was testing for globalization testing (on Mac though), I used `set LANG=en_CA.UTF8` on the terminal and use the same terminal to run the application.  Maybe you wanna give it a try?
