### ISSUE TITLE
Model "Question" uses unknown mixin: Time

### ISSUE THREAD

**Issue by Salamdev** [strongloop/loopback#4049]
Hi!
I have a problem with mixins.
I described it fully in stackoverflow.
Please look at this and help me resolve this.
Also it may be a bug too.tnx
https://stackoverflow.com/questions/53047184/model-question-uses-unknown-mixin-time

**Comment by jannyHou** [comment]
@Salamdev We have a working timestamp mixin example created by community, you can take a look how it's implemented, see: https://github.com/clarkbw/loopback-ds-timestamp-mixin

**Comment by Salamdev** [comment]
Ok.By changing the mixin file name to time.js (lowercase) and mixin name in question.json to "Time" (Uppercase) it works perfectly.
