### ISSUE TITLE
Connect with SQL Server and fetch data through loopback4

### ISSUE THREAD

**Issue by anandrajputSF** [strongloop/loopback#4051]
How to connect with SQL Server and fetch data. I tried to follow step to connect with sql server from [](https://github.com/strongloop/loopback-connector-mssql)  , but i am confuse.  if am creating datasource through `lb4 datasource`. all datasource file come under **src/datasource**. In this url datasource.json created in server directory. I have not too much idea about loopback. My simple requirement is connect with sql server database and fetch some tables data.

**Comment by dhmlau** [comment]
@anandrajputSF , could you please see my reply in https://github.com/strongloop/loopback/issues/4053?  
This issue seems to be a duplicate of #4053, I'd like to close this ticket and continue the discussion over #4053. Thanks.
