### ISSUE TITLE
How to fetch data from database.

### ISSUE THREAD

**Issue by chayakornwc** [strongloop/loopback#4053]
I tried to follow step to connect database with datasource concepts , but i am confuse. if am creating datasource through lb4 datasource. all datasource file come under src/datasource. In this url datasource.json created in server directory. I have not too much idea about loopback. How to fetch some data, Or fetch some data need to creating service for data lake.

**Comment by dhmlau** [comment]
@chayakornwc, from your description, it seems like there might be some mixed-up on the LB3 vs LB4 commands.  In LoopBack 4, there is no longer `server` directory.   I'd like to point you to this tutorial (https://loopback.io/doc/en/lb4/todo-tutorial.html), in case you haven't been there. 

In short, to fetch data from database, you can run the commands below: 
- `lb4 app` to create your app scaffolding
- `lb4 model` to add your model.  This will be the model that corresponds to your data in the database
- `lb4 datasource` to add a datasource.  Select the corresponding connector for the database you're using. 
- `lb4 repository` to add a repository that binds the model and the datasource
- `lb4 controller` to add a controller that defines your REST APIs 

If you're using a sql-based database, you can create the model from discovering the schema in the database.  We're in the process of updating the documentation to provide the instruction, but you can find a preliminary instruction in [here](https://github.com/strongloop/v4.loopback.io/issues/50#issuecomment-433191443).  Hope it helps.

**Comment by chayakornwc** [comment]
thank so help @hacksparrow  @dhmlau  👍

**Comment by dhmlau** [comment]
Closing as resolved. Thanks.

**Comment by chayakornwc** [comment]
i was connected my database 
this my simple config
```
{
  "name": "posts",
  "connector": "mongodb",
  "url": "mongodb://127.0.0.1:27017",
  "host": "localhost",
  "port": 27017,
  "user": "",
  "password": "",
  "database": "admin-artlampang"
}
```
but i can post and get fake data on 
http://explorer.loopback.io/?url=http://localhost:3000/openapi.json#/PostController/get_api_posts 
what's wrong ?

**Comment by dhmlau** [comment]
Sorry to close your issue, I thought it's been resolved. 
Did you create a datasource and have the repository binds to it?  Better yet, could you please share with us a sample application?  Thanks.

**Comment by chayakornwc** [comment]
i a has many relational collection 
postcategories.repository.ts
```
import { DefaultCrudRepository, juggler, HasManyRepositoryFactory, repository } from '@loopback/repository';
import { postcategories, posts } from '../models';
import { PostsRepository } from './posts.repository';
import { MongoDataSource } from '../datasources';
import { inject, Getter } from '@loopback/core';

export class PostcategoriesRepository extends DefaultCrudRepository<postcategories, typeof postcategories.prototype._id> {
  public readonly posts: HasManyRepositoryFactory<posts, typeof postcategories.prototype._id>;

  constructor(@inject('datasources.mongo') dataSource: MongoDataSource, @repository.getter(PostsRepository) getPostsRepository: Getter<PostsRepository>, ) {
    super(postcategories, dataSource);
    this.posts = this._createHasManyRepositoryFactoryFor(
      'posts',
      getPostsRepository,
    );

  }

}

```

postcategories.model.ts

```
import { Entity, model, property, hasMany } from '@loopback/repository';
import { posts } from './posts.model'
@model()
export class postcategories extends Entity {
  @property({
    type: 'string',
    id: true,
    required: true,
  })
  _id: string;

  @property({
    type: 'string',
    required: true,
  })
  key: string;

  @property({
    type: 'string',
    required: true,
  })
  name: string;

  @property({
    type: 'number',
    required: true,
  })
  _v: number;

  @hasMany(() => posts, { keyTo: 'categories' })
  posts?: posts[];

  constructor(data?: Partial<postcategories>) {
    super(data);
  }
}

```
catoriespost-post.controller.ts
  
i wont to get post data where categories key contain the key value array type in posts collection has relate by _id key of  categoirespost collection
```
 @get('/api/categories/{categories}/posts')
  async postsCategories(@param.path.string('categories') categories: typeof postcategories.prototype._id,
    @param.query.object('filter', getFilterSchemaFor(posts)) filter: Filter): Promise<posts[]> {
    return await this.PostcategoriesRepository.posts(categories).find()
  }
```

**Comment by chayakornwc** [comment]
my results return empty array

**Comment by chayakornwc** [comment]
![class diagram](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.xml#R7Vhtb9s2EP41BtIPMUTJUpyPtpu0AzKsqIH140CJtMSVIjWKju3%2B%2Bh1FUq%2F27BVdgAE1jER8eDzy7h7enTyLNuXxg8JV8asklM%2FCgBxn0ftZGD7GAfw1wMkCCUoskCtGLIQ6YMu%2BUQe6dfmeEVoPBLWUXLNqCGZSCJrpAYaVkoeh2E7y4a4VzukE2GaYT9EvjOjCoktvlsE%2FUpYXfmcUuJkUZ19zJffC7TcLo13zsdMl9rqcfF1gIg89KHqaRRslpbZP5XFDuXGtd5td93xhtj23okLftOABZymOHxZLGkePSXrvD%2FaK%2Bd45o5K1rt1x9cm7qD6wkmMBo3WhSw4ggsedFHrrhAIYZwXj5AWf5N4cp9bgHj9aF1KxbyCP%2FWKYVtqRIUyMNsb5RnKpABDS7tUu2hplbhtFa1j2yZuNWugF19ofRXKOq5qlzeGMSIlVzsRaai1LJ%2BSteu7t3MUQtJrQUuKlffSs%2FpJl7pnjlPJ1y4WRDbVW8ivtqQ%2BaTzvjKecd%2BoxLxs1N%2Bp0qggX2fraeQoEbn1OIOcsFYBk4hsLkekoQx5lXqjQ99iBHmA9UllSrE4i42chfA3e5F6EdHrqbghInUgxvibuh7nbmreqOofDgSHorYdGEsH8Y4dVv6Z%2BQGu7ApUzk7yb8BWP1kLvDsLhYnaGg9ymnO6PBOI5B6lg5WMvKKKtwBvu%2BNDLvFx3y2TnEQIeCaboF3JzpAJkUMAn6drxhVcEIoaJhncYap%2B2tqiQTunFivIYvuHUTzONZDHZtYIy6MXyNuAJyCLAPsybqFG7FgZqbcY4PF1PCdYY4RoTJbYzwcj%2BWEIsJITKsaQ6Jw5SUlS0R%2BPSTEW%2FIiPjGHPHfMCKZMGI%2Bn%2F%2BM%2FxvG%2F2H5dvGPSYge45QsA4J3CKG2RPRiTQn0e24IvihkLgXmTx06qvQ9Ulyr7dDDmO7BLaSCrExDCsOnzyUWJ4sNJcaV%2FIaC3%2BzTababXyzutdyrjF5wD3KxAY05vRZy47h%2FDLiiHGv2Omykz4WzWbqymbgVcDzuNH8yQK%2F3CIa9B4pG%2Fe01eRSMqGRP0BGrNeX7uOad2cs1szDh5mJVAwomf%2B1Nk%2B%2BaUFuXguoIf5tABha%2Fb3KHmVv05kymundJx8y57q7VCU%2B5%2B9%2FszDwAhdDWQdPT%2B1mwkY1XpOo6AuuqMVYoY6R%2Fn%2FPnQZeP9l1OsXm29cpUt5G1XSA82EbwF9K1glOLzIKmJvwvTNsxQe7Avnfz5t3s7qxJt4VtlBfPl65RfesVpF2TxwbZKRwnsY%2BUv1KjdZhH3%2F5V6sI73Q94JUqGWWb5MK12j%2BfeiBb%2F%2Fo0Iht3PAzZjdT%2FBRE9%2FAw%3D%3D)

**Comment by dhmlau** [comment]
Thanks @chayakornwc for the information.  I'll try it out tomorrow.  Thanks!

**Comment by dhmlau** [comment]
I've created the app based on the above description in this [repo](https://github.com/dhmlau/hasmany-test). 

IIUC, here is what we're trying to do:
- CategoriesPost "hasMany" Posts, and a Posts can have multiple categories
- The basic CRUD works fine, but the endpoint ` @get('/api/categories/{categories}/posts')` that @chayakornwc added doesn't work. See https://github.com/dhmlau/hasmany-test/blob/master/src/controllers/category.controller.ts#L128

@b-admike @bajtos @raymondfeng, I'm not quite sure how it should work.  Could you please help?

**Comment by chayakornwc** [comment]
@raymondfeng  i've trying without filter schema that's i can find this relations

**Comment by chayakornwc** [comment]
@dhmlau  @raymondfeng  thanks for help 🙏
