### ISSUE TITLE
Does loopback have way to manage roles and permissions belong to different groups or areas for same role

### ISSUE THREAD

**Issue by trungdh** [strongloop/loopback#4054]
Hi, 
I'm developing a RESTful API using Loopback framework and facing a problem relate to manage permissions for same role on different groups or Areas.

For example, I have three User : **U1,U2,U3** and  **U1**,**U2** and **U3** have same manager role.
**U1**,**U2** be assigned to manage **Area1**, and **U3** is manager of **Area2**. And I have some Resources belong each Area above corresponding : **Resource1** belong to **Area1**, **Resource2** belong to **Area2**

So how can I manage permissions of managers on each Resources which belong their Area ?

I want U1,U2 has full permissions (CRUD) on Resource1 because they are manager of Area1 but only have Read permission on Resource2 and same for U3 who is manager of Area2

I think I can use Scope, Authorization Scopes and ACLs to solve my problems but I don't know how to use exactly them.

Thank you !

**Comment by codekeyz** [comment]
@trungdh Check out this https://github.com/codekeyz/loopback-multirole-api-starter
