### ISSUE TITLE
scope include with limit will ignore order

### ISSUE THREAD

**Issue by Djinne** [strongloop/loopback#4074]
Hey, I'm using MongoDB with my loopback, and using a related model with limit and order at the same time will return the data in a random order each time. 

If it just use order and the data is big enough it will only return chunks of ordered data.

{
"include":{"relation":"somemodel",
"scope":{"limit":500,"order":"someproperty" } 
}}

**Comment by maximus123123** [comment]
I solved the issue using 
```
findById(
id,
{
"include":{"relation":"somemodel",
"scope":{"limit":500,"order":"someproperty" }
})

```
instead of

```
 findOne({
where:{id:id},
"include":{"relation":"somemodel",
"scope":{"limit":500,"order":"someproperty" }
})
```
