### ISSUE TITLE
cannot get user details

### ISSUE THREAD

**Issue by jaswanth1998** [strongloop/loopback#4085]
![screenshot 2018-11-29 at 10 46 40 am](https://user-images.githubusercontent.com/25882988/49200856-9db7ad00-f3c4-11e8-977d-470a5b2c2712.png)
I was getting this error while i reterving the users

**Comment by hacksparrow** [comment]
The User model is protected by authorization. The user must be logged in and can see only the details about itself.

**Comment by jaswanth1998** [comment]
> The User model is protected by authorization. The user must be logged in and can see only the details about itself.

Thank you for your reply hacksparrow 
when i was authorized and set my access token also it is not showing the user details
