### ISSUE TITLE
Dispatch event when user failed at login

### ISSUE THREAD

**Issue by coodoo** [strongloop/loopback#409]
It would be great if when user provided incorrect credentials for login, there could be a event dispatched so that I could do some post-processing (like sending an email to the admin, or block retries for 30 minutes).

Had a quick scan of the user.js, seems at line 206 it could dispatch a event on behave of User model?

https://github.com/strongloop/loopback/blob/5bb4cde5934f02d3261a33c668615203388a1335/lib/models/user.js#L206

**Comment by bajtos** [comment]
Hey @coodoo, unfortunately there has not been a high enough demand for us to implement your feature request. I suggest taking a look at the core code and seeing if you can implement the feature yourself as we accept a lot of community contributions. If you want to open up a PR and mention me directly in a comment, I will try my best to help you get the PR landed!

I am closing this issue for now.
