### ISSUE TITLE
Cannot find a way to filter an "included" relation objects.

### ISSUE THREAD

**Issue by Yankee-by** [strongloop/loopback#4093]
LoopBack 3. NodeJS 8.
Cannot find a way to filter an "included" relation objects.

# Description/Steps to reproduce
I have several models with relations. 
**user.json**
`{
  "name": "user",
  ...,
  "relations": {
     "addresses": {
      "type": "hasMany",
      "model": "address",
      "foreignKey": "userId"
    },
    ...
   }
 }
`

**address.json**
`
{
  "name": "address",
  ...,
 "relations": {
    "messages": {
      "type": "hasMany",
      "model": "message",
      "foreignKey": "addressId",
      "through": "addressMessage",
      "keyThrough": "messageId"
    },
    ...,
  }
}
`

**address-message.json**
`{
  "name": "addressMessage",
  ...,
  "relations": {
    "messages": {
      "type": "belongsTo",
      "model": "message",
      "foreignKey": "messageId"
    },
    "addresses": {
      "type": "belongsTo",
      "model": "address",
      "foreignKey": "addressId"
    }
  },
}`

**message.json**
`{ "name": "message", ... }`

Unfiltered query:
`uri: hostname/api/users/594be4da5c86c700209bb86c/addresses`
`filter: {"include":[{"relation":"messages","scope":{"include":{"relation":"attachmentLinks"}}}]}`

It returns the valid info: 
`[
  {
    "id": "5bec425677e5fd69f82b0a10",
    "userId": "594be4da5c86c700209bb86c",
    "messages": [
      {
        "id": "5bfd27f4a94841321f1a36d7",
        "attachmentLinks": [
          {
            "id": "5bfd27f4a94841321f1a36d9"
          },
          {
            "id": "5bfd27f4a94841321f1a36da"
          }
        ]
      },
      {
        "id": "5bfd28caa94841321f1a36de",
        "attachmentLinks": [
          {
            "id": "5bfd28caa94841321f1a36e0"
          },
          {
            "id": "5bfd28caa94841321f1a36e1"
          }
        ]
      }, 
...]}
]
`
In this case I get the bunch of "messages". But I don't understand how to filter the included relations. I am trying to use this syntax: 
`uri: hostname/api/users/594be4da5c86c700209bb86c/addresses`
`filter: {"include":[{"relation":"messages","scope":{"where":{"id":"5bfd27f4a94841321f1a36d7"},"include":{"relation":"attachmentLinks"}}}]}`

And the result is the same: 
`[
  {
    "id": "5bec425677e5fd69f82b0a10",
    "userId": "594be4da5c86c700209bb86c",
    "messages": [
      {
        "id": "5bfd27f4a94841321f1a36d7",
        "attachmentLinks": [
          {
            "id": "5bfd27f4a94841321f1a36d9"
          },
          {
            "id": "5bfd27f4a94841321f1a36da"
          }
        ]
      },
      {
        "id": "5bfd28caa94841321f1a36de",
        "attachmentLinks": [
          {
            "id": "5bfd28caa94841321f1a36e0"
          },
          {
            "id": "5bfd28caa94841321f1a36e1"
          }
        ]
      }
   ...,
   ]}
]`

# Link to reproduction sandbox

# Expected result:
Will be great to get only one message filtered by "id":
`[{"id": "5bec425677e5fd69f82b0a10", "userId": "594be4da5c86c700209bb86c", "messages": [ { "id": "5bfd27f4a94841321f1a36d7", "attachmentLinks": [ { "id": "5bfd27f4a94841321f1a36d9" }, { "id": "5bfd27f4a94841321f1a36da" } ] }] }]`

# Additional information
darwin x64 9.7.1
├── UNMET DEPENDENCY @types/loopback@^3.1.0-next.1
├── UNMET DEPENDENCY @types/loopback-boot@^2.23.0-next.0
├── UNMET DEPENDENCY loopback@^3.9.0
├── UNMET DEPENDENCY loopback-boot@^2.25.0
├── UNMET DEPENDENCY loopback-component-explorer@^4.0.0
├── UNMET DEPENDENCY loopback-component-storage@^3.2.0
├── UNMET DEPENDENCY loopback-connector-mongodb@^3.2.1
├── UNMET DEPENDENCY loopback-connector-sendgrid@^2.2.1

**Comment by SippieCup** [comment]
Use scope?

**Comment by Yankee-by** [comment]
I have tried to use it: `{"include":[{"relation":"messages","scope":{"where":{"id":"5bfd27f4a94841321f1a36d7"},"include":{"relation":"attachmentLinks"}}}]}`
but it returned the same result.
