### ISSUE TITLE
can I set the LoopBack API Explorer to start with https instead of http?

### ISSUE THREAD

**Issue by ManuRodgers** [strongloop/loopback#4096]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by hacksparrow** [comment]
Yes, you can. Refer to this doc - https://loopback.io/doc/en/lb2/Preparing-for-deployment.html. And here's an example app - https://github.com/strongloop/loopback-example-ssl.
