### ISSUE TITLE
Attaching Models to Multiple Datasources

### ISSUE THREAD

**Issue by kelptape** [strongloop/loopback#4097]
## Description / Steps to reproduce / Feature proposal
[loopback-getting-started.zip](https://github.com/strongloop/loopback-next/files/2668057/loopback-getting-started.zip)
![image](https://user-images.githubusercontent.com/37275738/49808891-94670280-fd2b-11e8-91b8-87a311f471b5.png)
Using the loopback-getting-started application with @bajtos dispatcher solution added to it (Link: https://bit.ly/2UAa3gP).

## Current Behavior
@bajtos I found your dispatcher solution on attaching models to multiple datasources but I am running into an issue (Link: https://bit.ly/2UAa3gP). I recreated what you provided and currently when I try to run this I get an issue saying that Coffee is not defined. Where do I need to define the model Coffee?
## Expected Behavior
Have an application that does not require the developer to manually define models for each datasource. 

Thank you!
Clay

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by kelptape** [comment]
Sounds good, thank you @bajtos

**Comment by bajtos** [comment]
@kelptape I imported your code to our loopback-getting-started repository in a new feature branch: https://github.com/strongloop/loopback-getting-started/tree/issue-4097

The commit https://github.com/strongloop/loopback-getting-started/commit/f6ae861ffbdcc7abbef7cdd25311909b26e2d12f is fixing the issue, or at least the problems preventing the app from starting.
