### ISSUE TITLE
Callback already called on Invalid token error

### ISSUE THREAD

**Issue by PeaceRebel** [strongloop/loopback#4098]
``` 
Unhandled error for request GET /api/myendpoint?access_token=wH9JMaoZMgU5IUfvpBBBNZJsCq3Y5e4si8fdkc8ViLqOu8cS5XNig4s43XGfelOI: Error: Invalid Access Token
    at <path-to-project>/node_modules/loopback/common/models/access-token.js:184:21
    at <path-to-project>/node_modules/loopback/common/models/access-token.js:246:20
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
<path-to-project>/node_modules/async/dist/async.js:966
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at <path-to-project>/node_modules/async/dist/async.js:966:32
    at rewriteUserLiteral (<path-to-project>/node_modules/loopback/server/middleware/token.js:26:35)
    at <path-to-project>/node_modules/loopback/server/middleware/token.js:148:7
    at <path-to-project>/node_modules/loopback/common/models/access-token.js:182:13
    at <path-to-project>/node_modules/loopback/common/models/access-token.js:263:11
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

# Description/Steps to reproduce

Some how generate an invalid token, ( create a user model, get an accessToken, then rename the model and now try using the token)

# Expected result

"Error: Invalid Access Token"

# Additional information

linux x64 11.4.0

├── loopback@3.24.0
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.3.1
├── loopback-component-storage@3.5.0
├── loopback-connector-mongodb@3.9.2

**Comment by hacksparrow** [comment]
Is renaming the "User" model required to reproduce this issue? If an invalid token is all we need, we can use a random string like "abcsdfsdfsdfsdf", which is an invalid token.

Also, I noticed you are making a request to the `myendpoint` model. Do we have to rename the "User" model or some other model.

Please provide the simplest changes required to reproduce the issue, in a descriptive manner. I haven't been able to reproduce the issue with the information you provided.
