### ISSUE TITLE
csv file/spreadsheet for creating models, ACL and relationships

### ISSUE THREAD

**Issue by arunkumar413** [strongloop/loopback#4099]
Hi All,

Instead of multiple command line generators to create the models, ACLs, and relationships, can we have a .csv file template to define the models, ACL, relationships and datasources. Then with only one command loopback processes the .csv file and creates all the entities and required file structure. 

Thanks,
Arun

**Comment by dhmlau** [comment]
@arunkumar413 , we have the `--config` option to feed in a json for the cli command.  You can see examples in this docs page: https://loopback.io/doc/en/lb4/Application-generator.html.

I've captured more examples in here: https://github.com/strongloop/loopback-next/issues/1844.  Hope it helps.

**Comment by arunkumar413** [comment]
It seems that the json files are specific to a command and  not the whole application. I'd like to work with a single csv file rather than multiple json files. Also csv files are easy to work with and modify. May be add another intermediary step/tool to process the csv into  the required json files.

**Comment by dhmlau** [comment]
I think what we need here to support your usage is to be able to read one big json file with multiple model definitions.  There are utilities out there to convert csv to json like https://www.npmjs.com/package/csvtojson.

**Comment by dhmlau** [comment]
@arunkumar413 , sorry that I might've understood you here.  Are you referring to LoopBack 3 or LoopBack 4?  Thanks.

**Comment by arunkumar413** [comment]
I haven't explored loopback4 much.  I'd like this feature be in the loopback3 and loopback4 as well.
