### ISSUE TITLE
i can't use logingin method for user

### ISSUE THREAD

**Issue by taroxii** [strongloop/loopback#4121]
{"error":{"statusCode":401,"name":"Error","message":"login failed","code":"LOGIN_FAILED","stack":"Error: login failed\n    at ~/node_modules/loopback/common/models/user.js:251:26\n    at 
~/node_modules/loopback-datasource-juggler/lib/dao.js:1772:5\n   
i try to use your login method 
my model have user As Base User model what's my wrong?

**Comment by taroxii** [comment]
i can't use logingin method for user

**Comment by bajtos** [comment]
@taroxii how can we reproduce the problem on our side? Please create a small app showing the problem, see our [bug reporting instructions](https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-3x-bugs.

**Comment by aikhan** [comment]
I have the exact same problem 

The same code is running on my local machine but login is failing on the actual server for some reason.

Same line error

**Comment by bajtos** [comment]
Please run your application with `DEBUG=loopback:user` set in your environment variables and then look for `An error is reported from User.findOne` message in the debug logs.
