### ISSUE TITLE
Incorrect "fields" filter behavior if persistUndefinedAsNull=true

### ISSUE THREAD

**Issue by uniconstructor** [strongloop/loopback#4126]
# Description/Steps to reproduce

I will base my example on Loopback docs: https://loopback.io/doc/en/lb3/Fields-filter.html

1. Open json-config of the model (for example "car.json")
2. Set `persistUndefinedAsNull` property to `true`
3. Reload, open API explorer
4. Get list of records with filter: `{"fields": {"id": true, "make": true, "model": true} }`

# Expected result

(as described in docs)
```js
[{
    "id": "1",
    "make": "Nissan",
    "model": "Titan"
  }, {
    "id": "2",
    "make": "Nissan",
    "model": "Avalon"
  },
  // ...
]
```

# Actual result

```js
[{
    "id": "1",
    "make": "Nissan",
    "model": "Titan",
    "description": null,   // defined in model, has value for instance, should not be in object
    "someOtherField": null // defined in model, has value for instance, should not be in object
    // ...
  }, {
    "id": "2",
    "make": "Nissan",
    "model": "Avalon",
    "description": null,
    "someOtherField": null
    // ...
  },
  // ...
]
```

# Additional information

In my case - fields "description" and "someOtherField" defined in the model, and instances have not null content in it, but when I use "fields" filter the content of the field is replaced to null, but field itself is not removed from object as expected.

**Comment by uniconstructor** [comment]
![ignoring-problem](https://user-images.githubusercontent.com/1384545/75922146-7ecf8280-5e73-11ea-973b-09ca7fe30ad2.jpg)

Problem still persists.

I confirm this bug on latest Loopback installetion (3.26.0). Configuration and steps to reproduce are the same.

Reopening issue.

**Comment by agnes512** [comment]
_I think_ `fields` overrides the setting `persistUndefinedAsNull`.

**Comment by bajtos** [comment]
Thank you @uniconstructor for reporting the issue, it looks like a bug in the implementation of `persistUndefinedAsNull` to me. We don't have bandwidth to fix it ([LoopBack 3 is in Maintenance LTS](https://strongloop.com/strongblog/lb3-entered-maintenance-mode/)), but I am happy to help you if you decide to contribute the fix yourself.

As I understand the current implementation, when a new model instance is being created, `persistUndefinedAsNull` sets all known properties to `null` if no value was provided for them. The option `filter.fields` is handled at connector level, excluded fields are not returned from the database, the data passed to model constructor contains `undefined` values for excluded fields and then `persistUndefinedAsNull` converts them to `null`. See [`_initProperties` method](https://github.com/strongloop/loopback-datasource-juggler/blob/e026b4c4af91ebf372ed9da794c9a76beb635812/lib/model.js#L75) and the code in `find` method building model instances [here](https://github.com/strongloop/loopback-datasource-juggler/blob/8d1690e9b2c76e3d0a8336b47f133e0605cbcc9a/lib/dao.js#L1633-L1645).

AFAICT, the `options` argument passed to `_initProperties` contains `field` property set to `filter.fields`, so I think it should be relatively straightforward to change handling of `persistUndefinedAsNull` to take `fields` into account.

Ah, I think I found the problem: `_initProperties` recognizes only `fields` in array format, it does not support object style. See https://github.com/strongloop/loopback-datasource-juggler/blob/e026b4c4af91ebf372ed9da794c9a76beb635812/lib/model.js#L267-L271:

```js
  if (Array.isArray(options.fields)) {
    keys = keys.filter(function(k) {
      return (options.fields.indexOf(k) != -1);
    });
  }
```

If you decide to contribute the fix, then please remember to add test to verify it - see the existing tests for `persistUndefinedAsNull` in [test/datatype.test.js](https://github.com/strongloop/loopback-datasource-juggler/blob/8d1690e9b2c76e3d0a8336b47f133e0605cbcc9a/test/datatype.test.js#L285)

**Comment by uniconstructor** [comment]
Wow. @bajtos , thank you for such deep explanation of the problem - I will try to use this information to create a bugfix for my backend server.

Best regards, Ilia.
