### ISSUE TITLE
Need urgent help on facebook login using passport

### ISSUE THREAD

**Issue by jaswanth1998** [strongloop/loopback#4127]
HI..
I am new loopback and i am searching for Facebook login since one month and I am not getting sufficient resources
I am using angular as my front end and loopback is my backend
can any one help me on this Issue
Of connecting angular7(using api call) and loopback (third party party login).
This is very urgent to solve this issue .
Please tell how do you do it

**Comment by jannyHou** [comment]
Hi @jaswanth1998 could you share your sample app for us to help you investigate more?

**Comment by raymondfeng** [comment]
Have you checked out https://github.com/strongloop/loopback-example-passport?
