### ISSUE TITLE
Help needed for query alter

### ISSUE THREAD

**Issue by ovidius72** [strongloop/loopback#4128]
I'm trying to create a custom ACL system similar to ABAC, instead of just allowing or denying the request  it should be able filter the data based on some policies (resource, env, action, user).
If a user request "find.posts" and he is allowed to only see posts he is the owner or that belong to one of its group, or when the request come from a give IP, I should create a new query with proper conditions.

To do that I have created a custom registerResolver method.

I was able to do that just by adding a "where" clause. However, the problems come when there is already a filter or a where clause is already present in the request.
Can you please suggest me a good way to alter a query where I need to add  from basic clauses to more complex ones ?

I was also thinking to create an on the fly scope that is only valid for that single request but I'm not sure how to do that.

Thanks.

**Comment by youknowme09** [comment]
From your describe, I think two processes should be done.

1. Define a custom ACL system rules. for general model use, the entry point could be define a model [mixin](https://loopback.io/doc/en/lb3/Defining-mixins.html)

2. Verify custom ACL system rules. In the mixins, add observe acceess [operation hook](https://loopback.io/doc/en/lb3/Operation-hooks.html#access) to append extra query constraints from mixins parameter and context 

hope this help
