### ISSUE TITLE
Support for `Array of Array of Json` Object in model properties

### ISSUE THREAD

**Issue by PRAKASH-SIVAGURUNATHAN** [strongloop/loopback#4132]
We have a model as shown below

````
{
  "name": "accounts",
  "plural": "accounts",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "items": {
      "type" : [
        [
          {"itemname": {"type": "string"}}
        ]
      ]
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
````

 Loopback explorer show the below structure 
<img width="443" alt="screen shot 2019-02-07 at 5 07 37 pm" src="https://user-images.githubusercontent.com/13993128/52409238-eb564180-2afa-11e9-8198-8ab0545afcbe.png">

but during runtime operations the response of the `items` is not coming as array of array of json object as shown below

<img width="996" alt="screen shot 2019-02-07 at 5 09 07 pm" src="https://user-images.githubusercontent.com/13993128/52409295-1e003a00-2afb-11e9-832e-5d944a8848f6.png">

**Comment by dhmlau** [comment]
@hacksparrow, the PR has landed.  Is this issue good to close? Thanks.

**Comment by dhmlau** [comment]
The fix is in `loopback-datasource-juggler@4.6.0`.

**Comment by hacksparrow** [comment]
This one's not fixed. This is the `List` breaker.

**Comment by dhmlau** [comment]
@PRAKASH-SIVAGURUNATHAN, @hacksparrow has fixed it in `master` and `3.x`.  Closing this issue as resolved.  Thanks.

**Comment by snarjuna** [comment]
@dhmlau @hacksparrow Can we get this fix in version 2.x. cc: @bajtos

**Comment by dhmlau** [comment]
@snarjuna , we had a very brief chat with @PRAKASH-SIVAGURUNATHAN and indicated that the codebase is a bit different in 2.x than in 3.x/master.  @hacksparrow did some investigation and it would be a huge effort to have it fixed in 2.x as well.  If your team is planning to move to a recent version in 2 months or so (there had been some conversation about that with @RobPhippen as well), it may not worth the effort to do so.

**Comment by bajtos** [comment]
>  it may not worth the effort to do so.

+1

Especially considering that LoopBack 2.x is going end of life in about two weeks (at the end of April 2019), see https://github.com/strongloop/loopback#module-long-term-support-policy.

**Comment by snarjuna** [comment]
@dhmlau @bajtos Thanks for details. I will check with team and come back.
