### ISSUE TITLE
bulk-update method on rest api

### ISSUE THREAD

**Issue by gerardfollano** [strongloop/loopback#4133]
I am trying to figure out how to use bulk-update on rest in loopback so i can update/create multiple instances on one given api call. There is not much documentation on this particular topic that i can find. 

Can someone please provide me with a sample value (parameter: updates) for bulk-update. 

Right now my 'userDetails' table is structured with a key value column format like so: 
metaId: 1, userId: 46, metaKey: "firstName", metaValue: "Gerard"
metaId: 2, userId: 46, metaKey: "lastName", metaValue: "Follano"

Thank you!

**Comment by jannyHou** [comment]
@gerardfollano You can check doc https://loopback.io/doc/en/lb3/Creating-updating-and-deleting-data.html of the API usage of bulk update.

**Comment by gerardfollano** [comment]
@jannyHou thanks for the quick reply, but like I said there is not much there. 

I managed to get the bulk update method to show as an endpoint on rest, but i cannot for the life of me figure out how to correctly format my data to post to it successfully...
