### ISSUE TITLE
ssl on loopback4 with Heroku ACM

### ISSUE THREAD

**Issue by shahulhameedp** [strongloop/loopback#4135]
Hi,
Let me bring the context here. I've a sample domain example-domain.com.
I used Godaddy to register this one and I'm hosting this app in Heroku. To enable https accessing, I bought dyno in Hereoku which comes with a free https along with it. I think they enabling the https using letsencrypt.com, and I don't think they actually give you the path for certificate and key. Apparently loopback4 server config requires this config to force https in server.
```
rest: {
      protocol: 'https',
      key: fs.readFileSync('./key.pem'),
      cert: fs.readFileSync('./cert.pem'),
    },
```
in my case I don't have certificate or key available to refer, also as per heroku documentation it will be renewed every month or something. Is there a way to enable https protocol without key and cert path referring?

**Comment by raymondfeng** [comment]
Based on this SO Q&A - https://stackoverflow.com/questions/25148507/https-ssl-on-heroku-node-express, Heroku does SSL termination at the edge. As a result, your LB4 app should only use plain http. No `https` is needed.

**Comment by dhmlau** [comment]
Closing this issue as resolved.
