### ISSUE TITLE
How to set the "ttl" property?

### ISSUE THREAD

**Issue by heshamelmasry77** [strongloop/loopback#4138]
i have a model for room
and i am trying to add a property expire after certain time.
for example i have a 
```
    "premium": {
      "type": "boolean"
    },

```
and i want to make it expire or be false after certain amount of time.

i tried to use ttl but it never works.
```
"ttl": {
      "type": "number",
      "ttl": true,
      "default": 5,
      "description": "time to live in seconds (5 seconds by default)"
    },

```

i also checked out this issue not it never helped because nothing is working
https://github.com/strongloop/loopback/issues/733

**Comment by youknowme09** [comment]
ttl is Build-in Model AccessToken property, and that implement ttl feature.
I think you should check the detail about it, and implement like that for you Room model.
[AccessToken.js -> AccessToken.prototype.validate](https://github.com/strongloop/loopback/blob/master/common/models/access-token.js#L232)
