### ISSUE TITLE
User verification token not cleared after confirmation

### ISSUE THREAD

**Issue by johnsoftek** [strongloop/loopback#414]
User.confirm attempts to clear the verificationToken after confirmation but it does not work.

        user.verificationToken = undefined;
        user.emailVerified = true;
        user.save(function (err) {

It seems that the save function does not update fields with undefined value. Null works.

        user.verificationToken = null;

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by Amir-61** [comment]
@johnsoftek Would you like to send a patch for this fix?

Thanks.

**Comment by richardpringle** [comment]
@Amir-61 Did you reproduce this issue? I see that you are the one that put the bug label on the issue. Next time could you please add some details in a comment just in case someone else is going to make the fix.

**Comment by Amir-61** [comment]
>@Amir-61 Did you reproduce this issue? 

I believe so... It was long time ago... Someone may have already solved it by now...
