### ISSUE TITLE
How can I perform searches in loopback 4?

### ISSUE THREAD

**Issue by GermanCV** [strongloop/loopback#4140]
# How can I perform searches in loopback 4?
I'm using mongodb.

something like `$text` in mondodb
https://docs.mongodb.com/manual/reference/operator/query/text/

**Comment by hacksparrow** [comment]
The LoopBack 4 repo is at https://github.com/strongloop/loopback-next, btw.

You can use the `where` filter:

- https://loopback.io/doc/en/lb3/Where-filter.html#like-and-nlike
- https://loopback.io/doc/en/lb3/Where-filter.html#like-and-nlike
