### ISSUE TITLE
Bug in configure shared methods caused by position in model-config.json (lb3)

### ISSUE THREAD

**Issue by ayushkamadji** [strongloop/loopback#4143]
### Description/Steps to reproduce
I encountered a bug where the position of where I configured a model in model-config.json will affect whether its nested remotes will show up or not in loopback 3. 

I defined a 'user' and 'profile' model to have a has many and belongs to relation. I wanted the profile to be accessed exclusively under the owning user's REST api. Here is what I configured in model-config.json and the result. The profile endpoints are nested under the user, all good.
```
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      "loopback/server/mixins",
      "../common/mixins",
      "./mixins"
    ]
  },
  "AccessToken": {
    "dataSource": "db",
    "public": false,
    "relations": {
      "user": {
        "type": "belongsTo",
        "model": "user",
        "foreignKey": "userId"
      }
    }
  },
  ...
  ...
  "user": {
    "dataSource": "db",
    "public": true,
    "options": {
      "remoting": {
        "sharedMethods": {
          "*": false,
          "create": true,
          "login": true,
          "logout": true,
          "changePassword": true,
          "resetPassword": true,
          "setPassword": true,
          "findById": true,
          "prototype.patchAttributes": true,
          "exists": true,
          "replaceById": true,
          "deleteById": true
        }
      }
    }
  },
  "profile": {
    "dataSource": "db",
    "public": false
  }
}
```
![image](https://user-images.githubusercontent.com/8255357/53165122-7c9ddb80-3604-11e9-9d81-c6771c8a2805.png)

After working on other models without having defined relations yet. I end up with the following model-config.json. There are no changes to models/user and models/profile files. All of a sudden the nested profile endpoints are gone and do not show up in `lb export-api-def`
```
{
...
  "user": {
    "dataSource": "db",
    "public": true,
    "options": {
      "remoting": {
        "sharedMethods": {
          "*": false,
          "create": true,
          "login": true,
          "logout": true,
          "changePassword": true,
          "resetPassword": true,
          "setPassword": true,
          "findById": true,
          "prototype.patchAttributes": true,
          "exists": true,
          "replaceById": true,
          "deleteById": true
        }
      }
    }
  },
  "profile": {
    "dataSource": "db",
    "public": false
  },
  "package": {
    "dataSource": "db",
    "public": true,
    "options": {
      "remoting": {
        "sharedMethods": {
          "*": false,
          "find": true
        }
      }
    }
  },
  "orderStatus": {
    "dataSource": "db",
    "public": false
  },
  "order": {
    "dataSource": "db",
    "public": true
  },
  "orderItem": {
    "dataSource": "db",
    "public": false
  },
  "domainStatus": {
    "dataSource": "db",
    "public": false
  }
}
```
![image](https://user-images.githubusercontent.com/8255357/53165529-97248480-3605-11e9-893d-70d754716387.png)

So I tried removing the additional configs in model-config.json and the nested profile endpoints is enabled again where these new models have not been defined any relations to user or profile. And then I tried putting them back in model-config.json, **except this time I moved the "profile" config at the bottom of model-config.json (see below) and the nested profile endpoints is enabled**. I even tried moving it in between the new models and depending on where it is placed, the nested eps either show up or not.

##### enables
```
...
  "package": {
...
  },
  "orderStatus": {
    "dataSource": "db",
    "public": false
  },
  "order": {
    "dataSource": "db",
    "public": true
  },
  "orderItem": {
    "dataSource": "db",
    "public": false
  },
  "domainStatus": {
    "dataSource": "db",
    "public": false
  },
  "profile": {
    "dataSource": "db",
    "public": false
  }
}
```

```
...
  "package": {
...
  },
  "orderStatus": {
    "dataSource": "db",
    "public": false
  },
  "order": {
    "dataSource": "db",
    "public": true
  },
  "profile": {
    "dataSource": "db",
    "public": false
  },
  "orderItem": {
    "dataSource": "db",
    "public": false
  },
  "domainStatus": {
    "dataSource": "db",
    "public": false
  }
}
```
##### disables

```
...
  "package": {
...
  },
  "orderStatus": {
    "dataSource": "db",
    "public": false
  },
  "profile": {
    "dataSource": "db",
    "public": false
  },
  "order": {
    "dataSource": "db",
    "public": true
  },
  "orderItem": {
    "dataSource": "db",
    "public": false
  },
  "domainStatus": {
    "dataSource": "db",
    "public": false
  }
}
```

I would try debugging but I have no clue what debug string to use for this.

#### Additional information
linux x64 10.14.1
├── loopback@3.24.2
├── loopback-boot@2.27.1
├── loopback-component-explorer@6.3.1
├── loopback-connector-postgresql@3.6.0
├── loopback-connector-rest@3.4.1

**Comment by oOLucioleOo** [comment]
I encountered the same issue. Apparently the "*" wildcard match, or not, to the relational methods. For us it's not about the position in the json but when we set "public: true" in another model without relation with others.
