### ISSUE TITLE
Is set NODE_ENV=staging datasource.staging.js/json not loaded

### ISSUE THREAD

**Issue by taroxii** [strongloop/loopback#4147]
# Description/Steps to reproduce
 i used export NODE_ENV=staging

my default datasource.json defined to connect it localhost 
and on staging get default it datasource.json

# Expected result
connection to database successfully

# Actual result
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] becuase 
local database server is closed

# Additional information

**Comment by taroxii** [comment]
so sad

**Comment by hacksparrow** [comment]
```
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017] becuase
local database server is closed
```

Can you confirm if MongoDB is actually running on `127.0.0.1:27017`?

**Comment by dzungh0ang** [comment]
Hi @taroxii please show your start script and datasource file for each environment here
