### ISSUE TITLE
Documentation for PersistedModel has disappeared from 3.25.0/ API docs

### ISSUE THREAD

**Issue by tkrugg** [strongloop/loopback#4155]
# Description/Steps to reproduce

1. Go to https://apidocs.strongloop.com/loopback/v/3.25.0/
2. Search for Persistedmodel in the left menu

# Expected result

expected to find PeristedModel, as found in previous versions.
# Additional information

**Comment by dhmlau** [comment]
@tkrugg , is that what you're referring to? https://apidocs.strongloop.com/loopback/v/3.25.0/#persistedmodel

**Comment by tkrugg** [comment]
yup, it's fixed thanks a lot!
