### ISSUE TITLE
How to check user records active? when login

### ISSUE THREAD

**Issue by taroxii** [strongloop/loopback#4156]
When i login user model, i need check user records active = true ?

**Comment by hacksparrow** [comment]
Your problem statement is not very clear. I can help if you can describe your problem and requirements  more clearly.

**Comment by youknowme09** [comment]
Add a [remote hook](https://loopback.io/doc/en/lb3/Define-a-remote-hook.html#create-the-remote-hook)

example:
```javascript
User.afterRemote('login', function(ctx, next) {
     if (ctx.model.active) next()
     next("not active")
  });
```
