### ISSUE TITLE
Method create does not create new instance

### ISSUE THREAD

**Issue by MaryJJ** [strongloop/loopback#4157]
Nature of the issue
Hello:
I'm developing an API, with my own authentication.
I created an account model that inherits from User and I created a session model that inherits from AccessToken.
//Account
{
"name": "account",
"plural": "accounts",
"base": "User",
"idInjection": true,
"options": {
"validateUpsert": true
},
"relations": {
"roleMappings": {
"type": "hasOne",
"model": "RoleMapping",
"foreignKey": "principalId"
},
"accessTokens": {
"type": "hasMany",
"model": "session",
"foreignKey": "userId",
"options": {
"disableInclude": true
}
}}

//Session
{
"name": "session",
"plural": "sessions",
"base": "AccessToken",
"idInjection": true,
"options": {
"validateUpsert": true
},
"relations": {
"user": {
"type": "belongsTo",
"model": "account",
"foreignKey": "userId"
}
}
I have a method signin in the account model, which will verify a series of data, and if they are valid I need to create a token and return it.
My problem is that when I use the create method, if there already exists in the session table a record with the same userId replaces this instead of creating it.

async function storeSession(user) {
var Session = Account.app.models.session;
var result = await Session.create({
userId: user.id,
sfid: user.sfid,
providerId: user.providerId,
provider: user.provider,
firstName: user.firstname,
lastName: user.lastname,
email: user.email,
ipaddress: getIpAddress(),
});
return {
token: result.id,
user: {
userId: result.userId,
sfid: result.sfid,
providerId: result.providerId,
provider: result.provider,
firstName: user.firstname,
lastName: user.lastname,
email: result.email,
ipaddress: result.ipaddress
}
}
};

Expected behavior
I hope that creates a new record in the session table

Actual behavior
The method replace the record that has the same userId with a new Id

Thanks

**Comment by youknowme09** [comment]
I think you miss understand the Actual behavior

> Expected behavior
> I hope that creates a new record in the session table
> Actual behavior
> The method replace the record that has the same userId with a new Id

Actual behavior
creates a new record in the session table(get a new Id as your expect), 
then something(maybe a request with old token Id) invalid old session id in session( invalid accesstoken will be delete)
