### ISSUE TITLE
After remote hook not called when user confirms registration

### ISSUE THREAD

**Issue by johnsoftek** [strongloop/loopback#416]
user.beforeRemote('confirm', beforeConfirm) 
    user.afterRemote('confirm', afterConfirm) 

beforeConfirm is called.

afterConfirm is not called following successful remote call to User.confirm.

I am using user model based on User.

**Comment by bajtos** [comment]
Pull request in review: https://github.com/strongloop/loopback/pull/1066

**Comment by bajtos** [comment]
This should have been fixed by https://github.com/strongloop/loopback/commit/8766d4a68d014402dd8ed70295eb3b9d8a635c0d since `loopback@2.13.0`.
