### ISSUE TITLE
Unclear error message: "The connector has not been initialized"

### ISSUE THREAD

**Issue by SephReed** [strongloop/loopback#4160]
I've already posted a question about this on stackoverflow:

https://stackoverflow.com/questions/55250918/loopback-4-x-error-the-connector-has-not-been-initialized

I very well may get an answer there, but I also wanted to poke you guys for help.  Please feel free to close this issue in any case.

**Comment by hacksparrow** [comment]
> The missing "connector" property in my Postgres Db config was the issue.

Looks like this was resolved by @SephReed.
