### ISSUE TITLE
Loopback type any not includes type buffer

### ISSUE THREAD

**Issue by TexToro** [strongloop/loopback#4161]
loopback version - 3.19.0

I try to save uuid as binary in `id` column. For property id I set type - `any` and when I try to put `new Buffer(uuid.v4().replace(/-/g, ''), 'hex')` to `id` field, I obtain error 'Data too long for column id'. Problem can be solved with replacing `id` type from `any` to `buffer`, but then I have another problem - when you want to response data,  it response will be a `buffer` in `id` key, and I can't change it to string uuid.

So when I use type `any`, I expect, that this type includes `buffer` too.

**Comment by hacksparrow** [comment]
You can call the `.toString()` method on the `buffer` to get a string version of it.

```js
const b = new Buffer('A')
console.log(b)
  <Buffer 41>
const s = b.toString()
console.log(s)
  'A'
```

**Comment by TexToro** [comment]
I tried do like this in hook `afterRemote`, but loopback changed it to binary again.
