### ISSUE TITLE
not able to find "Date" format in loopback

### ISSUE THREAD

**Issue by vigneshtharani** [strongloop/loopback#4163]
my db date is = "2019-03-25"

but in loopback model file, I am not able to fetch this pattern, it returns empty value.

modelname.find({
   where : { 															  				 
        and: [{party_id: values.party_id}, {date: new Date() }]
  }
}, function(err, result){
});

**Comment by hacksparrow** [comment]
If you wrote that code on 25th. The date `2019-03-25` stored in your database, and the one generated by `new Date()` would have had differences in second (minute, or even hour) values, hence they will not match.

If you are not concerned about the hour/minute/second precision, you can strip them off by manually crafting the date format before storing or comparing.
