### ISSUE TITLE
How to use "include" filter in hasMany relation ?

### ISSUE THREAD

**Issue by rhlr** [strongloop/loopback#4166]
# Description
I have four models for handling conversations between members, `conversations` , `replies`, `members` and `profiles` .  `profiles` has a `membersId` field and `conversations` and `replies` have `createdBy` field (which contains the `membersId`). Relations are as follows: 

**conversations** `hasMany` **replies**
**members** `hasOne` **profiles**
**conversations** `belongsTo` **profiles**
**replies** `belongsTo` **profiles**

`Profiles` has the picture and name of the member which I want to include in each replies instance. Now, I want to use the `include` filter `{"include":"profiles"}` in this 
**`GET /conversations/{id}/replies`** endpoint so that each `reply` instance comes with the corresponding profile. As of now, directly including the filter returns an empty profiles array. 

I'm currently using a remote hook to iterate over each reply and get the corresponding profile by matching `createdBy` and `membersId`. This process is time consuming and everytime I have to hit a lot of requests. Also, I want to add some other models which again will need data from the `profiles` model. So, again I have to re-iterate the codes of the remote hooks on each `GET` request which is very cumbersome process. Is there any other way to handle this ? How can I achieve this in a single call ?

**Comment by youknowme09** [comment]
I have tried your case, it works . Just add filter like { "include": ["profiles"] }.
Anyway, there are two way:

1. GET /conversations/{id}     
filter = { "include" : {
  "replies": "profiles"
}}
more complex case:
filter = { "include" : {
  "replies":  { 
     "profiles": "members"  // or something nested include
  }
}}

2.YOUR VERSION GET  /conversations/{id}/replies
filter = { "include": ["profiles"] }
