### ISSUE TITLE
Custom role not work

### ISSUE THREAD

**Issue by pookdeveloper** [strongloop/loopback#4167]
Hello I put this acl restriction in my model and dosent work:
{
"accessType": "READ",
"principalType": "ROLE",
"principalId": "$admin",
"permission": "ALLOW",
"property": "find"
}

What i'm doing wrong?

  "name": "usuarios",
  "base": "User",
  "idInjection": true,
  "options": {
    "validateUpsert": true,
    "strict": true
  },
  "ttl": 9999999,
  "mixins": {
    "UpdateAutoDate": {
      "createdAt": "fecha_alta",
      "updatedAt": "fecha_modificacion",
      "required": false,
      "validateUpsert": true,
      "silenceWarnings": true,
      "fieldsNotNull": [
        "fecha_alta"
      ]
    }
  },
  "properties": {
    "nombre": {
      "type": "string"
    },
    "activo": {
      "type": "boolean"
    },
    "apellido1": {
      "type": "string"
    },
    "apellido2": {
      "type": "string"
    },
    "dni": {
      "type": "string",
      "required": true,
      "unique": true
    },
    "telefono": {
      "type": "string"
    },
    "fecha_alta": {
      "type": "date"
    },
    "fecha_modificacion": {
      "type": "date"
    }
  },
  "validations": [],
  "relations": {
    "roles": {
      "type": "hasMany",
      "model": "role",
      "foreignKey": "principalId",
      "through": "RoleMapping"
    },
    "usuario_grupos": {
      "type": "hasMany",
      "model": "usuarios_grupos",
      "foreignKey": "id_usuario"
    },
    "accessTokens": {
      "type": "hasMany",
      "model": "access_token",
      "foreignKey": "userId",
      "options": {
        "disableInclude": true
      }
    }
  },
  "acls": [
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "create"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "deleteById"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "login"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "logout"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "findById"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "patchAttributes"
    },
    {
      "principalType": "ROLE",
      "principalId": "$owner",
      "permission": "ALLOW",
      "property": "replaceById"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "verify",
      "accessType": "EXECUTE"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "confirm"
    },
    {
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "ALLOW",
      "property": "resetPassword",
      "accessType": "EXECUTE"
    },
    {
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": "changePassword",
      "accessType": "EXECUTE"
    },
    {
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW",
      "property": "setPassword",
      "accessType": "EXECUTE"
    },
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$admin",
      "permission": "ALLOW",
      "property": "find"
    }
  ],
  "methods": {}
}
Thanks

**Comment by youknowme09** [comment]
$admin is not build-in ROLE, so there is tow options:

1. StaticRoles [Add a Role](https://loopback.io/doc/en/lb3/Defining-and-using-roles.html#static-roles)
2. Dynamic Roles [Add a Role Resolver](https://loopback.io/doc/en/lb3/Defining-and-using-roles.html#dynamic-roles)

**Comment by pookdeveloper** [comment]
But if i use this dosent work: 
{
  "accessType": "EXECUTE",
  "principalType": "ROLE",
  "principalId": "admin",
  "permission": "ALLOW",
  "property": "find"
}

I have a model usuarios based in user model.
Thanks

**Comment by pookdeveloper** [comment]
I resolved that, my problem was:

When it checks the rolemapping (I actually have a model role mapping with a mixin, so it execute a sql with my mixim fields ( fecha_alta, fecha_modificacion) ), but this fields are not defined in model:

````
{
  "name": "rolemapping",
  "base": "RoleMapping",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "mixins": {
    "UpdateAutoDate": {
      "createdAt": "fecha_alta",
      "updatedAt": "fecha_modificacion",
      "required": false,
      "validateUpsert": true,
      "silenceWarnings": true,
      "fieldsNotNull": [
        "fecha_alta"
      ]
    }
  },
  "properties": {
    "id": {
      "type": "number"
    },
    "principalType": {
      "type": "string"
    },
    "principalId": {
      "type": "string"
    },
    "roleId": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {
    "role": {
      "type": "belongsTo",
      "model": "Role",
      "foreignKey": "roleId"
    }
  },
  "acls": [
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "admin",
      "permission": "ALLOW"
    }
  ],
  "methods": {}
}
````
And the sql return 0 rows !

It's much important execute de project with debug mode:
https://loopback.io/doc/en/lb3/Setting-debug-strings.html
