### ISSUE TITLE
Cannot read property 'substr' of null database connector mssql

### ISSUE THREAD

**Issue by ljcordero** [strongloop/loopback#4168]
Hi,

I get the following error when put a password that have the # sign, others special character also give me the same error.

Cannot initialize connector "mssql": Cannot read property 'substr' of null

My datasources.json is something like:

"SGI-API": {
                    "url": "mssql://test:##2019-04-01*@localhost:1433/DB-NAME",
                    "database": "DB-NAME",
                    "password":"##2019-04-01*",
                    "name": "TEST-DB",
                    "connector": "mssql",
                    "user": "test",
                }

Thanks.

**Comment by youknowme09** [comment]
you can try this 
```javascript
{
"SGI-API": {
  "host":"localhost",
  "database": "DB-NAME",
  "password":"##2019-04-01*",
  "name": "TEST-DB",
  "connector": "mssql",
  "user": "test",
 }
}
```
[SQL-Server-connecto](https://loopback.io/doc/en/lb3/SQL-Server-connector.html#connector-settings)

**Comment by ljcordero** [comment]
> you can try this
> 
> ```js
> {
> "SGI-API": {
>   "host":"localhost",
>   "database": "DB-NAME",
>   "password":"##2019-04-01*",
>   "name": "TEST-DB",
>   "connector": "mssql",
>   "user": "test",
>  }
> }
> ```
> 
> [SQL-Server-connector](https://loopback.io/doc/en/lb3/SQL-Server-connector.html#connector-settings)

without the url key, I get the following error:
UnhandledPromiseRejectionWarning: TypeError: Invalid server: undefined

Note: I don't have any problem with the url key, except for the # sign on password.

**Comment by youknowme09** [comment]
The URL with special character is invalid, so the # sign not work properly.
I dont have mssql to try this.
I suggest you can try this format url: [classic-connection-string](https://github.com/tediousjs/node-mssql#classic-connection-string)
or not to use special character in password

**Comment by ljcordero** [comment]
@youknowme09 Thanks Sr.

With classic connection string it works.
