### ISSUE TITLE
find method returns with table name 

### ISSUE THREAD

**Issue by vigneshtharani** [strongloop/loopback#4178]
[ code_table {
   __cachedRelations: {},
   __data: { id: 1, code: 'user_type', value: 'user Type' },
   __dataSource: undefined,
   __strict: false,
   __persisted: true } ]

why find method returns data like this with table name, I need only data in array?

**Comment by vigneshtharani** [comment]
FYI

**Comment by mohanasundarR** [comment]
can you share you find method code

**Comment by mohanasundarR** [comment]
if you can make a PR and share it

**Comment by vigneshtharani** [comment]
{
 "name": "code_table",
 "base": "PersistedModel",
 "idInjection": true,
 "options": {
   "validateUpsert": true
 },
 "properties": {
   "id": {
     "type": "number",
     "required": true
   },
   "code": {
     "type": "string",
     "required": true
   },
   "value": {
     "type": "string",
     "required": true
   }
 },
 "validations": [],
 "relations": {},
 "acls": [],
 "methods": {}
}

this is json file

code.find({where:{id:1}},function(err, result){
     if (err) {
       console.log(err)
     } else {
       console.log(result)
       console.log(result[0].id, 'resulttt');

     }
   });

this is an model function

**Comment by vigneshtharani** [comment]
is anything we did it wrongly?

**Comment by mohanasundarR** [comment]
"Id": {
      "type": "number",
      "mysql": {
        "columnName": "id",
        "dataType": "BIGINT",
        "dataLength": 20
      }
    }

this is the structure you have to use to define the field, here Id is user defined and columnName should be same as db columnName name

**Comment by mohanasundarR** [comment]
can you get it??

**Comment by mohanasundarR** [comment]
it will be great if you make an Pull request

**Comment by vigneshtharani** [comment]
I will check it, but it also repeated again and returns same format

**Comment by mohanasundarR** [comment]
i will try creating a basic format for json,mean while try making a Pull request

**Comment by mohanasundarR** [comment]
{
"name": "TABEL_NAME_USER_DEFINED",// should use the same name while importing in js
"base": "PersistedModel",
"idInjection": true,
"options": {
"validateUpsert": true,
"mysql": {
  "schema": "YOURDB",
  "table": "TABEL_NAME_AS_IN_BD"
}
},

"properties": {
"Id": {             //user Defined ,should use the same name inside remote methods to access this field
  "type": "number",
  "id": 1, // if auto increment use it else ignore
  "mysql": {
    "columnName": "id",// same as db
    "dataType": "BIGINT", // same as db
    "dataLength": 20  // same as db
  }
},
},
"validations": [],
"relations": {},
"acls": [],
"methods": {}
}

i tried making a basic structure for json file think this will be helpful

**Comment by hacksparrow** [comment]
Hi @vigneshtharani please share a sample app reproducing the issue, so that we can have a better idea of what's happening.
