### ISSUE TITLE
defaultFn: 'now' wrong timezone

### ISSUE THREAD

**Issue by ataft** [strongloop/loopback#4179]
Using the `defaultFn: 'now'` model property can result in the wrong time zone. As I understand, it just uses "new Date()". Is there a way to work around this or override the function to use momentjs?

**Comment by youknowme09** [comment]
Nodejs Date use operation system timezone by default.
if you want change the timezone you may set an environment variable with start script.

```bash
TZ="Europe/Amsterdam" node server.js
```

**Comment by ataft** [comment]
Perhaps, but customers of the application will not be able to do this. I realize there are many things I could do to work around this, but that's exactly what momentjs does in 1 line.

**Comment by youknowme09** [comment]
Maybe a workaround is  #292  [ref](https://github.com/strongloop/loopback/issues/292#issuecomment-69641098)
```javascript
app.models.Todo.definition.rawProperties.updated.default =
app.models.Todo.definition.properties.updated.default = function() {
  return moment();
};
```
