### ISSUE TITLE
Mark LB 2.x as EOL

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#4180]
At the end of April 2019, LoopBack 2.x goes end of life. We need to reflect this change in our documentation, project templates, etc.

## Acceptance criteria

- [x] Remove documentation for LB 2.x from our docs.

  _Alternative: keep the docs in, change the warning "LoopBack 2.x is the maintenance long-term support (LTS) release. " to mention that 2.x is no longer supported._

- [x] Remove 2.x from the list of LB versions offered by loopback-workspace. This list is used by generator-loopback and loopback-cli. 

  See [Workspace.getAvailableLBVersions()](https://github.com/strongloop/loopback-workspace/blob/6d6246777f5cb94b313d69793408a322f1d99564/common/models/workspace.js#L63-L69)

- [x] Review READMEs of all LB2/LB3 packages, update LTS section to clearly state that modules linked to LB 2.x is no longer supported. (For example, Explorer uses different major versions, 2.x hasn't been supported for ages.) 

  While changing READMEs, update LTS dates of the current Active LTS release to match the changes announced in https://strongloop.com/strongblog/lb3-extended-lts/

   Publish a new version of updated packages.

**Comment by dhmlau** [comment]
> Remove documentation for LB 2.x from our docs.
> Alternative: keep the docs in, change the warning "LoopBack 2.x is the maintenance long-term support (LTS) release. " to mention that 2.x is no longer supported.

I'd prefer we mention in the docs that 2.x is no longer supported than removing it from the docs.  I think we won't stop users from using 2.x, even though it's highly recommended to move away from it.

**Comment by dhmlau** [comment]
@bajtos, for `Review READMEs of all LB2/LB3 packages` (point 3 in the list), I realized that the connector repos don't have the LTS information.  So, I'm going to update the READMEs for the list below.  If you have a complete list or I miss any, please let me know. Thanks! 
- [ ] loopback-component-explorer
- [ ] strong-remoting
- [ ] loopback-workspace
- [ ] loopback-cli
- [ ] generator-loopback
- [ ] loopback-datasource-juggler

**Comment by dhmlau** [comment]
Closing as done.
