### ISSUE TITLE
Duplicate key value error on creating new item

### ISSUE THREAD

**Issue by dragonxsx** [strongloop/loopback#4181]
Our team have recently migrated the database from MySQL to PostgreSQL and have faced a problem on creating new items of models.

# Steps to reproduce
1. Change the data source to PostgreSQL
2. Export the data from the old MySQL database to SQL INSERT query
3. Run the query command on PostgreSQL Adminer
4. Try to creating item of any model on Loopback API Explorer (and Postman)

`
{
  "error": {
    "statusCode": 500,
    "name": "error",
    "message": "duplicate key value violates unique constraint \"post_pkey\"",
    "length": 177,
    "severity": "ERROR",
    "code": "23505",
    "detail": "Key (id)=(1) already exists.",
    "schema": "public",
    "table": "post",
    "constraint": "post_pkey",
    "file": "nbtinsert.c",
    "line": "535",
    "routine": "_bt_check_unique",
    "stack": "error: duplicate key value violates unique constraint \"post_pkey\"\n    at Connection.parseE (/home/node/app/node_modules/pg/lib/connection.js:601:11)\n    at Connection.parseMessage (/home/node/app/node_modules/pg/lib/connection.js:398:19)\n    at Socket.<anonymous> (/home/node/app/node_modules/pg/lib/connection.js:120:22)\n    at Socket.emit (events.js:193:13)\n    at Socket.EventEmitter.emit (domain.js:481:20)\n    at addChunk (_stream_readable.js:296:12)\n    at readableAddChunk (_stream_readable.js:277:11)\n    at Socket.Readable.push (_stream_readable.js:232:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:150:17)"
  }
}
`

# Additional information
The problem does not occur when creating new item on the empty database or when the data were created by Model.create()

**Comment by youknowme09** [comment]
Please refer to [reset auto increment counter in postgresql ](https://stackoverflow.com/questions/5342440/reset-auto-increment-counter-in-postgres)

--------------

If you created the table product with an id column, then the sequence is not simply called product, but rather product_id_seq (that is, ${table}_${column}_seq).

This is the ALTER SEQUENCE command you need:

```sql
ALTER SEQUENCE product_id_seq RESTART WITH 1453
```

**Comment by dragonxsx** [comment]
Thank you all for your quick and helpful support.
