### ISSUE TITLE
Unable to filter based on existence of relation

### ISSUE THREAD

**Issue by eyeswideopen** [strongloop/loopback#4185]
I want to query all entities of model User which have an existing relation to Trainer
I tried it with the $exist operator but without success:

```
    models.User.find({
      where: {
        trainer: { //tried 'trainedId as well... 
          exists: true,
        },
      },
      include: 'trainer'
    },
    function(err, resp) {
      cb(err, resp);
    });
  };
```

user.json relation:
```
    "trainer": {
      "type": "hasOne",
      "model": "trainer",
      "foreignKey": ""
    },
```
trainer.json relation:
```
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": ""
    },
```

# Expected result

Get all Users which have an existing Trainer Model

# Additional information
darwin x64 11.14.0
loopback@3.25.1
loopback-boot@2.28.0
loopback-component-explorer@5.4.0
loopback-component-passport@3.10.0
loopback-connector-mongodb@3.9.2

**Comment by youknowme09** [comment]
Hi @eyeswideopen 

Are the users have trainerId ? If so.

```javascript
 // I guess you define a custom user model name 'user' , which define  the relations
 // so change model.User to model.user 
models.user.find({  
      where: {
        trainerId: {
          exists: true,
        },
      },
      include: 'trainer'
    },
    function(err, resp) {
      cb(err, resp);
    });
```

**Comment by eyeswideopen** [comment]
Tried that as well but with no success since the foreign key (in this case userId) is stored in the Trainer Model

**Comment by youknowme09** [comment]
Maybe you can try the reverse way

```javascript
models.trainer.find({
      where : {
         userId :{
            exists: true,
          }
      },
      include: 'user'
    },
    function(err, resp) {
       let users = resp.map( t => t.user() )
       cb(err, users)
    });

```

**Comment by eyeswideopen** [comment]
That would defeat the point since there are users without a trainer but not vice versa.
The goal is to get all instances of model A (User) which DON'T have a relation to a Model B (Trainer).

But i think this is the underlying problem... the missing foreign id on the user model which makes the query for it difficult/impossible?
