### ISSUE TITLE
Loopback query with like not working properly?

### ISSUE THREAD

**Issue by ivoprotasio** [strongloop/loopback#4199]
Hello!

First of all, I'm using this Loopback Version and Loopback MSSQL Version:

- Loopback version: 3.25.1
- loopback-connector-mssql : 3.3.0

When searching for a string on a mssql database, using this format:

`?filter[where][field][like]=%value%`

It doesn't seem to find the expected value if it is encountered after a dot.

_" sVL- s. value"_

In this case, we have to query with a space behind it in order to work:

`?filter[where][field][like]=% value%`

Any advice? Am I doing something wrong?

**Comment by jppmateus** [comment]
Same problem here!
