### ISSUE TITLE
How to connect Rest server using Digest authentication client in Loopback rest connector

### ISSUE THREAD

**Issue by woodmanhu** [strongloop/loopback#4200]
## Nature of the issue 

The target REST server that I'm going to connect to get data from has Digest authentication set up for external connection. I've initialized loopback 3 project in my local machine(win10, VScode as SDK), created datasource.json and model (TestOne) under common folder. when I run the program I kept geting 401 unautherized or 403 forbidden no matter how and where I specify the authorization info. I tried to place it in datasources.json file or using node.js request package to make a call in model.beforeRemote function but none of them worked. plus I'm not even sure those are good places to put the rest connection in. 

The logic in my mind of how it will work is that:

1. connect to rest server in beforeRemote to get authenticated.

2. send request first time to get digest info (nonce number and etc..) from response.header['www-authenticate'].

3. send auth request second time with digest info to get myself authenticated.

4. I dont even have a plan yet but once authenticated I can send request to get REST data from server.

Below are my files:

```
datasources.json:
{
  "db": {
    "name": "db",
    "connector": "memory"
  },
  "TestOne": {
    "name": "TestOne",
    "baseURL": "https://url.com/",
    "crud": false,
    "connector": "rest",
    "options": {
      "headers": {
        "accept": "application/json",
        "content-type": "application/json",
      },  
      "strictSSL": false
    },
    "operations": [{
      "template": {
        "method": "GET",
        "url": "https://url.com/endpoint",
        "headers": {
"connection":"keep-alive",
          "Content-Type": "application/json;charset=UTF-8",
          "Authorization": "Digest username=\"username@company\",qop=\"auth\", realm=\"TestOne\", nonce=\"undefined\", uri=\"/TestOne/rest/endpoint\", algorithm=\"MD5\", response=\"\"",
          "cache-control": "no-cache"
        },
        "form":false,
        "responsePath": "$.results.*"
      },
      "functions":{
          "login":[]
      }
    }]
  }
}
```
```
test-one-model.js:
module.exports = function(Testonemodel) {
//set up request from request package
const request = require('request');
    Testonemodel.beforeRemote('login',function(ctx,next){
//init variable
    var nonce = "";
//set up first call option
    var InitOptions = { method: 'GET',
      url: 'https://url.com/TestOne/rest/auth',
      headers: 
      { 'connection':'keep-alive',
        Authorization: 'Digest username="username@company", realm="TestOne", nonce="undefined", uri="/TestOne/rest/auth", algorithm="MD5", response="123456789abcdefghijklmnopqrstuvw"',
        'Content-Type': 'application/json;charset=UTF-8' },
      form: false };
// first request to rest server
      request(InitOptions, function (error, response, body) {
        if (error) throw new Error(error);
        console.log(response.statusCode);//get 401
        console.log(response);
        console.log(body);// unauthorized
        var authInHeader = response.headers['www-authenticate'];
// get nonce from response header
        nonce = authInHeader.substr(authInHeader.indexOf('nonce="')+7).replace(/["]+/g,'');
        console.log(nonce);
      });

// set up second call option    
      var CounterOptions = { method: 'GET',
      url: 'https://url.com/TestOne/rest/endpoint/1234567',
      headers: 
      { 
        // 'cache-control': 'no-cache',
        'connection':'keep-alive',
        Authorization: 'Digest username="username@company", qop="auth", realm="TestOne", nonce="'+ nonce +'", uri="/TestOne/rest/endpoint/1234567", algorithm="MD5", response="123456789abcdefghijklmnopqrstuvw"',
        'Content-Type': 'application/json;charset=UTF-8' },
      form: false };
// call second time to rest server      
      request(CounterOptions, function (error, response, body) {
        if (error) throw new Error(error);
        console.log(response.statusCode);//still 401
        console.log(response);
        console.log(body);
      });
};
```

## Expected behavior
I'm expecting to get response 200 back from REST server in either the way I wrote in model.js so that it approves this way works or there is a way that I can place authentication in datasources.json so that it will automatically authenticate me every time I do Get or Post. 

## Actual behavior

Keep receiving "you are not authorized"or "your session might be timed out" all related to status code 400,401,403

Anyone knows how to use digest auth client to connect to Rest server? Any help will be appreciated! Thanks!

**Comment by dhmlau** [comment]
Transferred this issue to the `loopback` repo from `loopback.io`.

**Comment by woodmanhu** [comment]
Does anyone have any ideas?
