### ISSUE TITLE
Problem with "include" in 3 levels and a lot of data and Oracle

### ISSUE THREAD

**Issue by ericalves** [strongloop/loopback#4203]
Hi guys!

I have a problem with findAll in a model in Oracle.

I have this structure:

```
sale: {
   id_sale: 1,
   ...
   items: [
      {
         id_sale_item: 1,
         id_sale: 1,
         ...
         choice_items: [
            { 
               ... ,
               id_sale_item: 1
            },
            { ... },
            { ... }
         ],
         ...
      },
      { ... },
      { ... },
      { ... }
   ],
   ...
}
```

My query theoretically returns 196 sales, 3200 items and 32 choice_items. But i receveid a error 

> ORA-01795: maximum number of expressions in a list is 1000 error.

The problem is items.. i think loopback uses sql clause "IN" to get choice_items, because if i remove choice_items, my query works.

Has a methods to work around this? A setting in model to do this "IN" in parts.. i dont know... : /

**Comment by lndickel** [comment]
Same problem
