### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by matiasx1998** [strongloop/loopback#4209]
`C:\Users\Matias\Desktop\proy>npm install -g loopback-cli
[  ................] | fetchMetadata: sill fetchPackageMetaData error for strong-globalize@^4.1.1 Unexpected end of JSONnpm ERR! Unexpected end of JSON input while parsing near '...ncies":{"debug":"^2.2'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matias\AppData\Roaming\npm-cache\_logs\2019-05-31T19_49_26_140Z-debug.log

C:\Users\Matias\Desktop\proy>npm install -g loopback-cli
npm ERR! Unexpected end of JSON input while parsing near '...ncies":{"debug":"^2.2'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matias\AppData\Roaming\npm-cache\_logs\2019-05-31T19_52_48_226Z-debug.log

C:\Users\Matias\Desktop\proy>npm install -g @loopback/cli
npm ERR! Unexpected end of JSON input while parsing near '...ncies":{"debug":"^2.2'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matias\AppData\Roaming\npm-cache\_logs\2019-05-31T19_53_26_067Z-debug.log

C:\Users\Matias\Desktop\proy>`

**Comment by dhmlau** [comment]
@matiasx1998, which node and npm version you're on? Thanks.

**Comment by dhmlau** [comment]
Seems like you have opened a duplicate issue in `loopback-cli` repo: https://github.com/strongloop/loopback-cli/issues/87. Closing this as duplicate.
