### ISSUE TITLE
how to have frame when camers is opened ??

### ISSUE THREAD

**Issue by Banda17** [strongloop/loopback#4216]
I want a white rectangle frame to found when camera is opened how can i do that ?
i read about this but it stated that you can use CSS properties ,i am not able to fgure out how we can do it ??

**Comment by sujeshthekkepatt** [comment]
I don't think this is the right place for your question. Better ask in some CSS related forums

**Comment by Banda17** [comment]
please feel free  to comment even the issue is closed because i am still working on on it
