### ISSUE TITLE
deploy loopback app with obfuscation. is it possible?

### ISSUE THREAD

**Issue by aref-mehran** [strongloop/loopback#4217]
hi. we want to deploy our loopback app on  a local server in  factory. my boss said we should protect the code(at least minimal protection with obfuscation). i searched a lot but no progress. how can i obfuscate source code of loopback app?

**Comment by katherdx** [comment]
Any updates?

**Comment by sujeshthekkepatt** [comment]
You may need to find other solutions. This issue, I think , outside the scope of this repo. It has nothing to do with loopback. You are on your own. You may check other ways like dockerizing your app (may be😊). Consider any other solutions. It's my opinion.
