### ISSUE TITLE
how to do mysql query on two column  

### ISSUE THREAD

**Issue by ankit-devtool** [strongloop/loopback#4220]
# Description/Steps to reproduce

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by ankit-devtool** [comment]
I was getting a problem while doing query like where:{ column1 > column2 } in one table. so can anyone tell me how to do in loopback 4.

**Comment by dhmlau** [comment]
@jannyHou, could you PTAL? Thanks.

**Comment by ankit-devtool** [comment]
my requirement to do query like this.
SELECT * FROM table where data_a > data_b
i need to fetch data from one table which to have two columns of number value. so i have to compare these two columns data in like this where:{column1> column2}.

**Comment by ankit-devtool** [comment]
please provide a answer of this, how to solve this problem.

**Comment by sujeshthekkepatt** [comment]
Is this something that related to loopback or general? Whatever it is , you
can do query using loopback model or can execute raw query using your
connector methods. Also no one can understand you are saying, if you do not
explain properly. Also please read docs before asking such questions.

**Comment by ankit-devtool** [comment]
Thank you for your answer and I already mention loopback 4 query problem, so why would i ask in general query.
