### ISSUE TITLE
Why this might have happened: The server couldn't send a response: Ensure that the backend is working properly Self-signed SSL certificates are being blocked: Fix this by turning off 'SSL certificate verification' in Settings > General Proxy configured incorrectly Ensure that proxy is configured correctly in Settings > Proxy Request timeout: Change request timeout in Settings > General

### ISSUE THREAD

**Issue by espinhara** [strongloop/loopback#4222]
I am having problems in my application when running on postman sending data to my and the terminal is giving this error:
(node:5276) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'create' of undefined
    at store (C:\Users\GABRIEL\backend\src\controllers\PostController.js:12:33)
    at Layer.handle [as handle_request] (C:\Users\GABRIEL\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\GABRIEL\backend\node_modules\express\lib\router\route.js:137:13)
    at Immediate.<anonymous> (C:\Users\GABRIEL\backend\node_modules\multer\lib\make-middleware.js:53:37)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
(node:5276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by espinhara** [comment]
Can someone help me please?

**Comment by dhmlau** [comment]
@hacksparrow , could you PTAL? Thanks.

**Comment by kevinmarchese** [comment]
@espinhara  I get what you described when something is wrong in my request code, I typically have to look at the handling error. so if you're using Axios and I get this error its typically because I didn't''t add this correctly.

axios.post(url, with options)

.then (fuction (res){

}

    **})
    .catch(function (error) {
    console.log(error)**

Hope this helps
