### ISSUE TITLE
404 Unknown "user" id "reset-password"

### ISSUE THREAD

**Issue by hariaravind10** [strongloop/loopback#4223]
# Description/Steps to reproduce
Loopback remote/default methods are not accessible from production URL instead the default/remote method `users/reset-password` considering as `users/id`. It's kind of odd to see this kind of issue. Can anyone help me out on this?

But Remote/default methods working fine in the local system once moved to production I'm seeing this error.

status: 404
code: MODEL_NOT_FOUND
Error: Unknown "user" id "reset-password"
    at Function.convertNullToNotFoundError (/home/ec2-user/testtrackman/trackmanapi/node_modules/loopback/lib/persisted-model.js:91:17)
    at invokeRestAfter (/home/ec2-user/testtrackman/trackmanapi/node_modules/strong-remoting/lib/rest-adapter.js:532:25)

![image](https://user-images.githubusercontent.com/34663118/60382578-99e72880-9a82-11e9-8d5b-24d72a62347b.png)

# Link to reproduction sandbox

# Expected result is 
Expected is reset-password just like the example given by loopback guys
https://github.com/strongloop/loopback-example-user-management

# Additional information

**Comment by youknowme09** [comment]
I think correct url for user reset password  is **users/reset** not **users/reset-password**

It because example give a view  define in [route.js](https://github.com/strongloop/loopback-example-user-management/blob/master/server/boot/routes.js)

``` javascript
  //show password reset form
  app.get('/reset-password', function(req, res, next) {
    if (!req.accessToken) return res.sendStatus(401);
    res.render('password-reset', {
      redirectUrl: '/api/users/reset-password?access_token='+
        req.accessToken.id
    });
  });
```
So maybe change redirectUrl to 
```javascript
  app.get('/reset-password', function(req, res, next) {
    if (!req.accessToken) return res.sendStatus(401);
    res.render('password-reset', {
      redirectUrl: 'api/users/reset-password?access_token='+
        req.accessToken.id
    });
  });
```
