### ISSUE TITLE
Mongodb connector allows any field to be persisted in the database on PATCH requests even if its not defined in the schema

### ISSUE THREAD

**Issue by Sletheren** [strongloop/loopback#4226]
# Bug description:

Hello all, 
Noticed that loopback allows every field comming with any PATCH request to be persisted in the database even if it is not defined in the model schema.
Happens when your loopback application is connected to mongo DB using the loopback-mogodb-connector. 
Which basically shouldn't happen if we have our model type, which means any additional/extra field need to be stripped out (aka, same if you are using any model/ORM, like mongoose)

# Steps to reproduce:
- Setup a datasource using loopback-mongodb-connector. 
- create a model (name, email... Per example)
- Make a PATCH request using postman or the explorer, you can add other fields that they are not defined in the model definition.
- Retrieve the record you created, and you'll see that you have the extra fields you sent with the request back.

# Potential solutions:
- Have a setting in the model to restrict which the data that can be sent to the API on some operations, rather than manually looping through the request body and stripping out what's added...
- Have a setting (per example`force: true`) to only pick up the defined fields in the model...

**Comment by youknowme09** [comment]
I think it already define **strict** in model definition JSON

|property | Type | Default | Description
-- | -- | -- | --
strict | Boolean or String |false.If the data source is backed by a relational database, then default is true. | Specifies whether the model accepts only predefined properties or not. One of:true: Only properties defined in the model are accepted. Use if you want to ensure the model accepts only predefined properties. If you try to save a model instance with properties that are not predefined, LoopBack throws a ValidationError.false: The model is an open model and accepts all properties, including ones not predefined in the model. This mode is useful to store free-form JSON data to a schema-less database such as MongoDB."filter": Only properties defined in the model are accepted. If you load or save a model instance with properties that are not predefined, LoopBack will ignore them. This is particularly useful when dealing with old data that you wish to lose without a migration script.


[Model-definition-JSON-file](https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#top-level-properties)
