### ISSUE TITLE
Use async/await in native sql

### ISSUE THREAD

**Issue by pookdeveloper** [strongloop/loopback#4227]
How can i use native sql with async/await:
https://loopback.io/doc/en/lb3/Executing-native-SQL.html

Thanks

**Comment by sujeshthekkepatt** [comment]
You may wrap it your own promise function of you don't find corresponding doc for your datasource

**Comment by pookdeveloper** [comment]
Can you put a example?

**Comment by sujeshthekkepatt** [comment]
```
const fetchData = ()=> {
return new Promise ((resolve, reject)=>{
YourDatasource.query('query',(err,data)=>{
If(err) return reject (err);
else return resolve(data);
})});
```

You may try this. Don't forget to replace the query function with your database

**Comment by bajtos** [comment]
As @sujeshthekkepatt  wrote:

```js
const result = await new Promise((resolve, reject) => {
  dataSource.connector.execute(sqlStatement, params, options, (err, result) => {
    if (err) reject(err);
    else resolve(result);
  });
});
```

You may want to write a small helper function:

```ts
// usage
const result = await executeAsync(dataSource, sqlStatement, params, options);

// implementation
function executeAsync(dataSource, sqlStatement, params, options) {
  return new Promise((resolve, reject) => {
    dataSource.connector.execute(sqlStatement, params, options, (err, result) => {
      if (err) reject(err);
      else resolve(result);
    });
  });
}
```

FWIW: For LoopBack 4, we added `dataSource.execute` API that wraps connector's `execute` method and adds promise support, unfortunately this is not available in LB3, since this version is in LTS mode.

```js
const result = await dataSource.execute(sqlStatement, params, options);
```

See https://github.com/strongloop/loopback-datasource-juggler/pull/1671,
