### ISSUE TITLE
Loopback API data is visible in browser network traffic

### ISSUE THREAD

**Issue by cueup** [strongloop/loopback#4231]
This issue doesn't have a particular error message but to help - this is my current setup. 

App backend: Express
 App frontend: Angular

Both hosted on different server, with a mongo Atlas cloud DB. The data from the server is exposed over network traffic on the front end and I cannot figure out why. 

**Any ideas?**

**Backend Package.json**

{
  "name": "app",
  "version": "1.0.0",
  "main": "server/server.js",
  "engines": {
    "node": ">=3.0"
  },
  "scripts": {
    "lint": "eslint .",
    "start": "node .",
    "posttest": "npm run lint",
    "build:sdk": "./node_modules/.bin/lb-sdk server/server ../client/src/common/sdk -i enabled"
  },
  "dependencies": {
    "@mean-expert/loopback-component-realtime": "^1.0.2",
    "@mean-expert/loopback-sdk-builder": "^2.3.1",
    "body-parser": "^1.17.1",
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^3.10.0",
    "loopback": "^3.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^6.2.0",
    "loopback-component-storage-mongo": "^1.5.1",
    "loopback-connector-mongodb": "^3.3.1",
    "node-schedule": "^1.3.2",
    "serve-favicon": "^2.0.1",
    "stripe": "^6.28.0",
    "strong-error-handler": "^3.0.0"
  },
  "devDependencies": {
    "eslint": "^3.17.1",
    "eslint-config-loopback": "^8.0.0"
  },
  "repository": {
    "type": "",
    "url": ""
  },
  "license": "",
  "description": ""
}

**Frontend Package.json**

{
  "name": "",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "node server.js",
    "build": "ng build --prod --aot",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "docs": "npm run typedoc",
    "typedoc": "typedoc --out ./docs ./src",
    "deploy": "./heroku-deployment.sh"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.11",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@covalent/text-editor": "^2.0.0",
    "@ng-bootstrap/ng-bootstrap": "^4.1.1",
    "angular2-moment": "^1.9.0",
    "angulartics2": "^7.5.2",
    "angularx-social-login": "^1.2.6",
    "body-parser": "^1.18.3",
    "bootstrap": "^4.3.1",
    "chart.js": "^2.8.0",
    "core-js": "^2.5.4",
    "express": "^4.16.4",
    "libphonenumber-js": "^1.7.15",
    "lodash.clonedeep": "^4.5.0",
    "lodash.findindex": "^4.6.0",
    "lodash.findlastindex": "^4.6.0",
    "lodash.includes": "^4.3.0",
    "moment": "^2.24.0",
    "ng2-charts": "^2.2.3",
    "ngx-markdown": "^7.1.5",
    "ngx-toastr": "^10.0.2",
    "path": "^0.12.7",
    "pikaday": "^1.8.0",
    "pikaday-time": "^1.6.1",
    "rxjs": "~6.3.3",
    "socket.io-client": "^2.2.0",
    "tslib": "^1.9.0",
    "typescript": "~3.2.2",
    "uuid": "^3.3.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.7",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/socket.io-client": "^1.4.32",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "typedoc": "^0.14.2",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  },
  "engines": {
    "node": "10.15.0",
    "npm": "6.9.0"
  }
}

**Comment by sujeshthekkepatt** [comment]
Can you be more specific ?

**Comment by cueup** [comment]
Accidentally closed this. 

Hi Sujesh, 

So the issue is if I F12 into while viewing my app and go to Network - the network traffic linked to my Mongo Atlas going via the loopback API is visible to the public. 

This is user data from the database. 

Any idea why this is?

**Comment by sujeshthekkepatt** [comment]
I don't understand what exactly you are saying. Can you attach a screenshot or something like that? If you are saying that your API data visible on the browser network traffic tab each time an API request is made it's quite common.

**Comment by cueup** [comment]
Think this is the solution https://loopback.io/doc/en/lb3/Include-filter.html
