### ISSUE TITLE
    "message": "Unexpected token e in JSON at position 1",

### ISSUE THREAD

**Issue by Gotemperor** [strongloop/loopback#4247]
I am using angular 7 and loopback 3.
I am making a simple post http call to default Users (the one, that comes with loopback app).
i am posting a valid Json from angular
{email: "myemail@abv.bg", password: "password1%", name: "ggggggg"}

but in loopback I get  error

{
  "error": {
    "statusCode": 400,
    "name": "SyntaxError",
    "message": "Unexpected token e in JSON at position 1",
    "expose": true,
    "status": 400,
    "body": "{email: \"myemail@abv.bg\", \"password\": \"password1%\"}",
    "type": "entity.parse.failed",
    "stack": "SyntaxError: Unexpected token e in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at parse (/home/.../.../node_modules/body-parser/lib/types/json.js:89:19)\n    at /home/.../.../node_modules/body-parser/lib/read.js:121:18\n    at invokeCallback (/home/.../.../node_modules/raw-body/index.js:224:16)\n    at done (/home/.../.../node_modules/raw-body/index.js:213:7)\n    at IncomingMessage.onEnd (/home/.../.../node_modules/raw-body/index.js:273:7)\n    at emitNone (events.js:106:13)\n    at IncomingMessage.emit (events.js:208:7)\n    at endReadableNT (_stream_readable.js:1064:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"
  }
}

when I get in http://localhost:3000/explorer/ and post to Users with 
{"email": "myemail@abv.bg", "password": "password1%", "name": "ggggggg"}
it works and it creates user.
But when I send a valid json (json is created with JSON.parse(objectSend)  I get the error again...
No matter what I do I can't get pass through that error.
Can anyone please help me?

**Comment by Gotemperor** [comment]
I've tried  JSON.stringify, JSON.parse and ect.
I've added headers json in angular 7, I've added body parser in loopback, I've added cors and still nothing.
When I send to regular express app it receives the json.
What that might be?

**Comment by sujeshthekkepatt** [comment]
It may either due to malformed request data or argument path settings

**Comment by hholst80** [comment]
> i am posting a valid Json from angular
> {email: "[myemail@abv.bg](mailto:myemail@abv.bg)", password: "password1%", name: "ggggggg"}

that is not valid JSON. That is valid JSON5 though. 

Why is it not valid JSON? you need to quote email, password and name.
