### ISSUE TITLE
Got garbled characters for data is not English language while use  loopback-connector-dashdb

### ISSUE THREAD

**Issue by XiaoMLoveClassic** [strongloop/loopback#4253]
have got garbled characters when the data in dashdb is not English language, is it a defect of the connector I am using( loopback-connector-dashdb)? for the data can be showed as normal if I use jdbc to connect the dashdb, and retrieve the data.

The data response while using loopback-connector-dashdb
<img width="478" alt="Screen Shot 2019-09-16 at 11 16 44 PM" src="https://user-images.githubusercontent.com/33888835/64970358-337ee300-d8d8-11e9-8d44-f56656d57e3d.png">
The data response while using jdbc:
<img width="1158" alt="Screen Shot 2019-09-16 at 11 19 40 PM" src="https://user-images.githubusercontent.com/33888835/64970485-7b9e0580-d8d8-11e9-927a-07fbcbacdcc0.png">

**Comment by dhmlau** [comment]
@XiaoMLoveClassic, looks like someone opened the same issue in `ibm_db`: https://github.com/ibmdb/node-ibm_db/issues/579. If it can be produced using plain `ibm_db`, it's likely a `ibm_db` issue, and I'd like to close this issue. Thanks.

**Comment by dhmlau** [comment]
Closing this issue as resolved, as the issues in `ibmdb` has closed too. Thanks.
