### ISSUE TITLE
Loopback 4: DynamoDB conector? 

### ISSUE THREAD

**Issue by jotamora** [strongloop/loopback#4254]
Hello,

I have started a project in LB4 with mongoDB. After some develop, people of "data" want to change to DynamoDB. is it posible to use DynamoDB with loopback 4? There is any connector?

Any Idea of how to change from mongoDB to dynamo in a lb4 proyect? (In a reasonable way).

Any help/idea will be really appreciated. 

Thanks.

**Comment by dhmlau** [comment]
@jotamora, there is a DynamoDB connector from the community: https://loopback.io/doc/en/community/dynamo-connector.html.  

To change from mongodb to dynamo, you just need to create a new datasource with that connector, and then the repository that uses that new datasource. 

The diagram in https://loopback.io/doc/en/lb4/Repositories.html shows the relationship among the datasource, repository, connector and database.  It might be helpful for you to understand more on what needs to be updated when switching to another database.

AFAIK, it should be a simple switch.

**Comment by dhmlau** [comment]
@jotamora, I believe we've answered your question, so would like to close this issue. Please feel free to ping here if you still have other questions. Thanks.
