### ISSUE TITLE
Loop stuck loopback

### ISSUE THREAD

**Issue by gaetan-warin** [strongloop/loopback#4259]
# Description/Steps to reproduce
Hello,

i need to loop inside loopback 3 a big amount of data, but when i loop it cannot access to other endpoint.

I tryed to create a new application loopback to test,
and event from entity or from server/boot it is the same.

if i have a loop working for example
for (let i = 0; i < 85000000; i++) {
     console.log(i)
 }

I cannot do any else other rest command, and i've to wait that is finished.

Could anyone can explain me why my app doesn't work asynchronously ?

# Expected result
Still be able to do call to api when the server is processing a loop.

**Comment by raymondfeng** [comment]
It's an issue in the application code that does not yield. You'll have to make sure the code does not block the event loop, for example, divide the work in smaller trunks and use `setImmediate` or other ways to do the next batch asynchronously.
