### ISSUE TITLE
beforeRemote ctx.method.name for findOne & findById not found

### ISSUE THREAD

**Issue by clockworked247** [strongloop/loopback#4261]
Hi all,

Love Loopback!  Thanks for all the hard work.

I'm trying to manipulate a returned modelInstance before a call to findOne & findById returns.  I've tried a couple of things and haven't had any luck.

```
Model.beforeRemote('**', function(ctx, modelInstance, next) {
    var methodName = ctx.method.name;
    console.log(methodName);
})
```
 only shows "find", but not "findOne" or "findById".  Additionally, I noticed that "find" is only called for the first invocation of the find() function and not again after that.   This might be why I'm not seeing any of the other findOne/findById commands coming through this function... 

```
Model.observe('access', async function(ctx) {
    return;
  });
```
ctx has no information on what function was invoked.  per the docs it could be all, find,  findOne,  findById, exists, count, but I have no way of figuring out which one was invoked.
Additionally, there's no ctx.instance or ctx.currentInstance available... so I can't even manipulate the instance.

So, is there a way to use a remote or operation hook to catch findById or findOne instance and modify it before return?  

Thanks.

**Comment by dhmlau** [comment]
@bajtos, could you please help with this question? Thanks.
