### ISSUE TITLE
issue :any data type in loopback

### ISSUE THREAD

**Issue by Nishad1999** [strongloop/loopback#4269]
## Use Cases
creating entity with data type "any"

## Examples

"Cannot start the application. Error: Unsupported type: any"

**Comment by davidpestana** [comment]
use 'object' type in json files.

'any' is only for TypeScript notations

**Comment by bajtos** [comment]
LoopBack 3.x does recognize `type: 'any'` type, see https://github.com/strongloop/loopback-datasource-juggler/blob/6dc0abc2fbff05b15c916e2196a7cb2d493971a0/lib/types.js#L32-L40
