### ISSUE TITLE
how to filter searching in array field

### ISSUE THREAD

**Issue by joneldiablo** [strongloop/loopback#4272]
I have a service which has an array field called categories, I want filter the response of with

```
"categories":"service"}
```

```
"categories":{"in":"service"}
```

```
"categories":{"in":["service"]}
```

```
"categories":{"inq":["service"]}
```

```
"categories":{"inq":"service"}
```

nothing works o.O
my data base is postgresql

**Comment by hacksparrow** [comment]
@joneldiablo please use this sample app - https://github.com/strongloop/loopback-sandbox - to reproduce the error you are facing, and share it on GitHub.
