### ISSUE TITLE
Options is empty in operation hook

### ISSUE THREAD

**Issue by gaetan-warin** [strongloop/loopback#4273]
I would like to check the Access Token validity in an operation hook (After Save), but I don't have any options in the CTX parameter. Nor any Access Token. 

On a custom endpoint I do have the Access Token object inside the REQ parameter.

## Steps to reproduce

Insert anything from any model.
Then console.log the CTX parameter from after save hook.

## Current Behavior

No Access Token present in the parameter

![image](https://user-images.githubusercontent.com/38975327/67838944-c07da480-faf2-11e9-8fa6-45b72fe6cf2c.png)

## Expected Behavior

I expect an Access Token inside the CTX parameter

## Additional information

"dependencies": {
    "compression": "^1.0.3",
    "cors": "^2.5.2",
    "helmet": "^3.10.0",
    "loopback": "^3.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^6.2.0",
    "loopback-component-storage": "^3.6.3",
    "loopback-connector-mongodb": "^5.0.1",
    "loopback-connector-postgresql": "^3.8.0",
    "strong-error-handler": "^3.0.0"
  },

## Related Issues

https://github.com/strongloop/loopback/issues/4024

Thanks you

**Comment by bajtos** [comment]
Thank you @gaetan-warin for reporting the issue. I am afraid the information you have provided is not enough to allow us to reproduce (and debug) the issue locally. Could you please create a small application we can run to reproduce the issue? See https://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report
