### ISSUE TITLE
Cannot order relation object inside method findOne()

### ISSUE THREAD

**Issue by gaetan-warin** [strongloop/loopback#4274]
I try to order data inside a relation inside .findOne(filter)
If i put order name DESC or ASC that don't change anything. 

![image](https://user-images.githubusercontent.com/38975327/67883192-ec754600-fb43-11e9-809c-965cc388bc18.png)

`{
  "where": { "active": true, "types": { "ilike": "%employee%" }, "id": "2" },
  "fields": {
    "id": true,
    "virtualName": true,
    "active": true,
    "lastname": true,
    "firstname": true,
    "types": true,
    "phones": true,
    "cost": true,
    "contractId": true
  },
  "include": [
    {
      "relation": "groups",
      "scope": {
        "include": [
          {
            "relation": "group",
            "scope": {
              "limit": 5,
              "skip": 0,
              "order": "name desc",
              "fields": {
                "id": true,
                "virtualName": true,
                "name": true,
                "description": true,
                "users": true
              }
            }
          }
        ],
        "where": { "contactEntity": 2100, "groupEntity": 110 }
      }
    }
  ]
}
`
Here is the answer i get :
![image](https://user-images.githubusercontent.com/38975327/67883704-d320c980-fb44-11e9-96c0-df28be9522c0.png)

`{
  "active": true,
  "name": "United Focus",
  "types": ["customer"],
  "id": 2,
  "groups": [
    {
      "groupEntity": 110,
      "companyEntity": 1100,
      "id": 1,
      "groupId": "5dae0f79acb0a62504bd3e30",
      "companyId": 2,
      "group": {
        "id": "5dae0f79acb0a62504bd3e30",
        "name": "Accounting",
      }
    },
    {
      "groupEntity": 110,
      "companyEntity": 1100,
      "id": 2,
      "groupId": "5dae0f84acb0a62504bd3e31",
      "companyId": 2,
      "group": {
        "id": "5dae0f84acb0a62504bd3e31",
        "name": "HR Management",
      }
    }
  ]
}`
I would like to influence order of groups object with filter, sort skip, order,...

**### Additional information**
"dependencies": {
"compression": "^1.0.3",
"cors": "^2.5.2",
"helmet": "^3.10.0",
"loopback": "^3.22.0",
"loopback-boot": "^2.6.5",
"loopback-component-explorer": "^6.2.0",
"loopback-component-storage": "^3.6.3",
"loopback-connector-mongodb": "^5.0.1",
"loopback-connector-postgresql": "^3.8.0",
"strong-error-handler": "^3.0.0"
},

**Comment by agnes512** [comment]
@gaetan-warin  hi, are you using LB4? If so, LB4 doesn't support `scope` for `inclusion` yet.
For example, if an `Employee` belongs to a `Manager`, and a `Manager` belongs to a `Company`, you **cannot** traverse through the relations to get 
```
[Company: [
    Manager: [
        Employee: [name:... ]
        ]
    ]
]
```
We only support to include the related models like `Company:[Manager]` or `Manager:[Employee]` for now.
See https://github.com/strongloop/loopback-next/issues/3453.

**Comment by gaetan-warin** [comment]
I'm in loopback 3

**Comment by bajtos** [comment]
Thank you @gaetan-warin for reporting the issue. Please create a small application we can use to reproduce and debug the problem, see https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-3x-bugs
