### ISSUE TITLE
Project moves from one server to another

### ISSUE THREAD

**Issue by anneyking** [strongloop/loopback#4276]
Excuse me, if my project is going to move from one server to another，I have modified the IP address in config.production.json，But the client can't access it。What is this loopback framework that needs to be modified?

**Comment by hacksparrow** [comment]
> But the client can't access it

By client, I am assuming the browser. Does the new server have some sort of firewall or does it sit behind a proxy?

Looks more like a network configuration issue on the server, than a LoopBack issue to me.
