### ISSUE TITLE
SSL on Loopback 2.0

### ISSUE THREAD

**Issue by sam-artuso** [strongloop/loopback#428]
Can anyone explain to me how to change the Loopback 2.0 example application so that it works over SSL?

**Comment by mike-aungsan** [comment]
@raymondfeng 
I am having issue with example. Server is listening on port 443 but not on https protocol. 
I can reach the server at http://localhost:443/ but I cannot reach https://localhost/

**Comment by gggin** [comment]
https://github.com/strongloop/loopback-example-ssl cannot work.
how to support loopback4.0 ?
