### ISSUE TITLE
Unhandled error for request GET /images/throbber.gif: Error: Cannot GET /images/throbber.gif

### ISSUE THREAD

**Issue by hubitor** [strongloop/loopback#4280]
## Steps to reproduce

I was following this tutorial:
[Introduction to LoopBack - Using It With SQlite3](https://www.youtube.com/watch?v=ii17_TdzKPM&t=3s)

These are the steps in short:
```
1. $ npm install loopback-connector-sqlite3 --save
2. Create datasource file
3. $ lb datasource
4. Modified datasources.json
5. Modified model-config.json
6. $ npm i -g loopback-migration-tool
7. $ lb-migration migrate --ds=db sqliteDS
8. Make a POST request in API Explorer (insert a new Coffeshop)
9. Reload Browser
```

Now when I start LB with:
`$ npm start`

LB is showing an error. This was not the case with the in-memory database.

## Current Behavior

```
Unhandled error for request GET /images/throbber.gif: Error: Cannot GET /images/throbber.gif
    at raiseUrlNotFoundError (projects/loopback-getting-started/node_modules/loopback/server/middleware/url-not-found.js:21:17)
    at Layer.handle [as handle_request] (projects/loopback-getting-started/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (projects/loopback-getting-started/node_modules/express/lib/router/index.js:317:13)
    at projects/loopback-getting-started/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (projects/loopback-getting-started/node_modules/express/lib/router/index.js:335:12)
    at next (projects/loopback-getting-started/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (projects/loopback-getting-started/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (events.js:198:13)
    at SendStream.error (projects/loopback-getting-started/node_modules/send/index.js:270:17)
    at SendStream.onStatError (projects/loopback-getting-started/node_modules/send/index.js:421:12)
    at onstat (projects/loopback-getting-started/node_modules/send/index.js:726:26)
    at FSReqWrap.oncomplete (fs.js:153:21)
```
## Expected Behavior

No error after starting LB.

## Additional information
$ node -e 'console.log(process.platform, process.arch, process.versions.node)'
linux x64 10.16.1

$ npm ls --prod --depth 0 | grep loopback
loopback-getting-started@1.0.0 /home/nick/workspace/TESTS/Frameworks/Backend_Frameworks/NodeJS_Frameworks/LoopBack/LoopBack 3/loopback-getting-started
├── loopback@3.26.0
├── loopback-boot@2.28.0
├── loopback-component-explorer@6.4.0
├── loopback-connector-sqlite3@3.0.0

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by bajtos** [comment]
Thank you @hubitor for reporting the issue. Please provide a link to the reproduction sandbox, as explained in https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-3x-bugs.

**Comment by bajtos** [comment]
Please provide a link to the reproduction sandbox, as explained in https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs.

**Comment by hubitor** [comment]
Here it is:

[https://github.com/hubitor/loopback-sandbox/tree/issue4280](https://github.com/hubitor/loopback-sandbox/tree/issue4280)

I hope, I did it correctly.

**Comment by bajtos** [comment]
@hubitor thank you for the app. Here is what I tried:

1. Setup: `git clone` your project, checkout the branch, run `npm install`.

2. Run the app as-is via `npm start`. The app starts, when I go to http://localhost:3000, the page displays two items.

3. Install `loopback-migration-tool`, run `lb-migration migrate --ds=db sqliteDS`. Here is the output:

    ```
    undefined:info Starting migrate +0ms
    undefined:info Starting sqliteDS datasource's migration with migrate method +918ms
    undefined:info Models to migrate ["User","AccessToken","ACL","RoleMapping","Role","CoffeeShop"] +1ms
    undefined:info sqliteDS datasource migration have finished. +18ms
    undefined:info Migrations have ended +1ms
    ```

4. Run `npm start`. The application starts with no errors. When I go to http://localhost:3000, I see an empty page, there are no errors printed to server console, no errors are reported in the browser either.

5. Using API Explorer, create a new CoffeeShop with the following data: 

    ```json
    {
        "name": "Tower",
        "city": "Paris"
    }
    ```

6. (Re)load http://localhost:3000, a page with a single item is shown. No errors are printed to console (server, browser).

    <img width="294" alt="Screen Shot 2019-11-22 at 16 30 58" src="https://user-images.githubusercontent.com/1140553/69438536-81372200-0d45-11ea-9cbe-a2ec1ed1b2bd.png">

In the issue description, the errors says `Cannot GET /images/throbber.gif`.  Where is `throbber.gif` coming from? I am almost certain it's not a part of LoopBack.

**Comment by hubitor** [comment]
@bajtos  thanks for checking! 

Well, this is weird. I tried I a couple of times and I was always getting the same error.

> In the issue description, the errors says Cannot GET /images/throbber.gif. Where is throbber.gif coming from? I am almost certain it's not a part of LoopBack.

It seems to be related to swagger-ui:
[https://github.com/swagger-api/swagger-ui/search?q=throbber.gif&type=Issues](https://github.com/swagger-api/swagger-ui/search?q=throbber.gif&type=Issues)
