### ISSUE TITLE
Composite Id not working for embedsMany relations

### ISSUE THREAD

**Issue by ewrayjohnson** [strongloop/loopback#4282]
## Steps to reproduce
1. Create an embedsMany relation where the embedded model has a composite id as described by:
https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#composite-ids
2. Add an array of embedded objects where one (e.g. the first) of the id properties is a duplicate, but other id properties is not a duplicate.

## Current Behavior
The code errors on the first duplicate property.

## Expected Behavior
No error is generated unless all id properties are duplicate.

## Link to reproduction sandbox
Coming soon.  Please do not close.

## Additional information
The bug is here: loopback-datasource-juggler\lib\relation-definition.js @ line 2493

**Comment by dhmlau** [comment]
@jannyHou , could you please take a look? Thanks.

**Comment by ewrayjohnson** [comment]
Pull request: https://github.com/strongloop/loopback-datasource-juggler/pull/1794

**Comment by ewrayjohnson** [comment]
I am working on creating tests to show the bug and confirm the fix
