### ISSUE TITLE
how to create example documentation for Remote Method 

### ISSUE THREAD

**Issue by skt1598** [strongloop/loopback#4297]
How to create example documentaion for api's created using remote method. Example like what will the input data and what will the structure of output data.

**Comment by sujeshthekkepatt** [comment]
It's automaticallyget  generated

**Comment by skt1598** [comment]
@sujeshthekkepatt in case of remote method auto generated documentation is less. Input model example is not there. How to insert that ?

**Comment by jannyHou** [comment]
Hi @skt1598 did you create the remote method using CLI?

If so the jsdoc are automatically generated, see code https://github.com/strongloop/generator-loopback/blob/master/remote-method/index.js#L469 and https://github.com/strongloop/generator-loopback/blob/master/remote-method/index.js#L482.

Other than the auto generated docs, what else would you expect to see? Can you post some code or doc examples here?

**Comment by skt1598** [comment]
@jannyHou for example my autogenerated get api has example model 
"[
  {
    "userName": "string",
    "hashTag": "no_data",
    "userId": "string",
    "oneLineBio": "no_data",
    "location": "no_data",
    "skills": [],
    "experience": "no_data",
    "aboutMe": "no_data",
    "score": 0,
    "videoUrl": "no_data",
    "fbUrl": "no_data",
    "twitterUrl": "no_data",
    "instagramUrl": "no_data",
    "id": "string"
  }
]"

How can i generate the same for custom route

**Comment by bajtos** [comment]
@skt1598 IIUC, when you say "documentation", you are referring to what's shown by API Explorer, and you would like to improve the documentation for your custom remote method. Is that right?

At high level, you need to describe your method's `accepts` and `returns` parameters in such way that LoopBack can convert your description into meaningful Swagger spec, which will be later rendered by our API Explorer into a living documentation.

An example of a `returns` parameter: https://github.com/strongloop/loopback/blob/6a7fc529fcbf219d3a2f6b77cdf221ee5c3b1dbf/lib/persisted-model.js#L854-L864

An example of an `accepts` parameter described via a model: 
https://github.com/strongloop/loopback/blob/6a7fc529fcbf219d3a2f6b77cdf221ee5c3b1dbf/lib/persisted-model.js#L653-L658

You can read the code in [loopback-swagger:lib/specgen/route-helper.js](https://github.com/strongloop/loopback-swagger/blob/2327edb377a7fc458ea300cbc4276d7eae740cda/lib/specgen/route-helper.js) to better understand how is a remote method definition converted into a swagger spec object.

**Comment by skt1598** [comment]
@bajtos thankyou. ``` returns: { 
   arg: 'info', 
   description: 'Information related to the outcome of the operation', 
   type: { 
     count: { 
       type: 'number', 
       description: 'The number of instances updated', 
     }, 
   }, 
   root: true, 
 }, ```

The above code solved my issue.
