### ISSUE TITLE
async remothe mehtod change statusCode in begintransaction

### ISSUE THREAD

**Issue by pookdeveloper** [strongloop/loopback#4301]
## Steps to reproduce
Async remote mehtod

When i call begin transacction it change the res.statusCode to 204
![image](https://user-images.githubusercontent.com/3384734/72204700-1e2b5700-347b-11ea-96b1-21d03d26c86a.png)

## Current Behavior
Change the res.statusCode

## Expected Behavior
No change  the res.statusCode

Thanks

**Comment by youknowme09** [comment]
async ensures that the function returns a promise.
so.. you didn't return any promise for crear2 function, it's empty response content.

```javascript
xxx.crear2 = async function(req, res, options, data){
 let tx = await xxx.beginTransation.....

 return {what you want to response} 
}
```

**Comment by pookdeveloper** [comment]
Thanks @youknowme09 i will try it
