### ISSUE TITLE
Synchronous get for hasOne relation not working

### ISSUE THREAD

**Issue by ewrayjohnson** [strongloop/loopback#4302]
Synchronous get for hasOne relations does not work.  
Identical code for a belongsTo relation works.

## Steps to reproduce

Create a hasOne relation and call the synchronous get.

## Current Behavior
   const component = container.component(); //  component is undefined

## Expected Behavior
   const component = container.component();  // this should work

**Comment by agnes512** [comment]
@ewrayjohnson Hi, could you have more examples / code snippet? thanks.

**Comment by ewrayjohnson** [comment]
Working on it...

Wray Johnson
(m) 704-293-9008

**Comment by ewrayjohnson** [comment]
I’ve been busy, but work on it soon.

**Comment by deepakrkris** [comment]
@ewrayjohnson definitely need some code samples

**Comment by ewrayjohnson** [comment]
Working on some

**Comment by ewrayjohnson** [comment]
Will work now
