### ISSUE TITLE
Initial application doesn't work

### ISSUE THREAD

**Issue by AnanthGopal** [strongloop/loopback#4304]
I create a basic initial application by using this "https://loopback.io/getting-started.html" page.
I got the error When i try to run the  application  by using "npm start"(I didn't change anything in that application just create an application by using lb4 app then run the application using npm start)

**Comment by raymondfeng** [comment]
@AnanthGopal What error did you see?

**Comment by AnanthGopal** [comment]
when i run the application, i got ./dist folder not found the issue.

The issue was fixed when i update the loopback CLI Update 1.21.4 → 1.30.0
