### ISSUE TITLE
Is it possible to filter count without including the relational data?

### ISSUE THREAD

**Issue by mirfmaster** [strongloop/loopback#4311]
Hello guys, im using Loopback 3.22.0 with postgres as database

What i want to perform is getting relation data with total count of another relation from rest api
eg: 
      let filter = {
        include: ["kendaraan", "sopir", "cabang", "rute", "jam"],
        count: ["paket", "reservasi"]
      };
      await this.props.getGlobal(
        `http://localhost:3000/api/manifests?filter=${JSON.stringify(filter)}`
      );

im trying with that, but the result is null?
or im doing it wrong?

sorry im a newbie with loopback

**Comment by agnes512** [comment]
@mirfmaster I am not sure what you mean by "getting relation data with total count of another relation from rest api", could you explain more with examples? But LB3 doesn't have the `count` filter clauses. See docs: https://loopback.io/doc/en/lb3/Querying-data.html#overview

**Comment by agnes512** [comment]
Closing as inactive.
