### ISSUE TITLE
Null is not returned if there is no target object available

### ISSUE THREAD

**Issue by praneshvrp1396** [strongloop/loopback#4312]
## Steps to reproduce

I use 2 models.
Patient and Husband.
They have a relation of type `hasOne` . ie. Patient has one husband. 
But when I try to get the husband object with the below code
`await this.patientRepository.husband(id).get()`
I am getting an error as below

> {
>     "error": {
>         "statusCode": 404,
>         "name": "Error",
>         "message": "Entity not found: Husband with id \"constraint {\\\"patientId\\\":10006}\"",
>         "code": "ENTITY_NOT_FOUND"
>     }
> }

Ideally, the code should return the Husband object if it exists or null if it does not. 
## Current Behavior

Error as stated above
## Expected Behavior

null

**Comment by agnes512** [comment]
@praneshvrp1396 Hi, I believe it's intentional to throw an error if the related target is not found.

**Comment by praneshvrp1396** [comment]
But it is mentioned in the documentation that return type is the target
object or null.

**Comment by agnes512** [comment]
@praneshvrp1396 you're right, I found the inconsistent in [the code](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/relations/has-one/has-one.repository.ts#L99) and [the API docs](https://github.com/strongloop/loopback-next/blob/master/packages/repository/src/relations/has-one/has-one.repository.ts#L37). Personally I think it should return `null` or `undefined` in this case. Let me discuss with the team and get back to you later. Thanks for reporting the bug 🙏

**Comment by praneshvrp1396** [comment]
Cool. You're welcome..!

**Comment by agnes512** [comment]
@praneshvrp1396 it should throw an error if an instance was not found. By throwing an EntityNotFoundError, we make the controller implementation much easier. So it doesn't need to convert `null` to 404. The inconsistence is being fixed in https://github.com/strongloop/loopback-next/pull/4773. 
I am closing issue as it's resolved, thanks.
