### ISSUE TITLE
Passing Values to the next() in remote hooks.

### ISSUE THREAD

**Issue by boakye-agyeman** [strongloop/loopback#4320]
MyModel.afterRemote('create', function(ctx, unused,next){
var NewModel = MyModel.models.User
//Now I will pass the context variables to a variable.
// Example
var body = ctx.req.body;
username = body.Username;
email = body.email;

// I want to create an object and persist into a different model instance. I called that model at the // // top as NewModel referencing the User model.
// The creation was done by manipulating the current ctx variables.
NewModel.create({Variables to be persisted goes here}, function(err,instance){
})
})
......

Now what I want is to pass the instance of the NewModel Creation to the next in the beforeRemote hook. How do I go about it? Ill be glad to provide further details

**Comment by youknowme09** [comment]
If I'm not misunderstand ... try this

```javascript
model.exports = function(MyModel) {
    let newModelInstance = null;
    MyModel.afterRemote('create', function(ctx, unused, next) {
        var NewModel = MyModel.models.User
        var body = ctx.req.body;
        username = body.Username;
        email = body.email;
        //..
        NewModel.create({
            //Variables to be persisted goes here
        }, function(err, instance) {
            newModelInstance = instance;//for next in the beforeRemote reference
        })
    })

    MyModel.beforeRemote('create', function(ctx, unused, next) {
        console.log(newModelInstance);//should be last assign instance in memory...
    })
}
```

**Comment by deepakrkris** [comment]
@boakye-agyeman next() only takes an error argument, we cannot pass any data values into it. please take a look at https://loopback.io/doc/en/lb3/Remote-hooks.html
