### ISSUE TITLE
"Content-Type" header is overwritten

### ISSUE THREAD

**Issue by SephReed** [strongloop/loopback#4321]
## Steps to reproduce
```
export class TestController {
  @get('/hello-page', {
    description: "Static page",
    responses: {}
  })
  async getHelloPage(
    @inject(RestBindings.Http.RESPONSE) res: Response,
  ) {
    res.setHeader("Content-Type", "text/html; charset=UTF-8");
    res.setHeader("Content-Type-Test", "text/html; charset=UTF-8");
    return `<html>Hello World</html>`;
  }
}
```

## Current Behavior
Content type is `text/plain`
<img width="344" alt="Screen Shot 2020-04-20 at 2 59 27 PM" src="https://user-images.githubusercontent.com/14002040/79794246-8f4e9600-8317-11ea-8bed-324bf93ca1e7.png">

A Content-Type-Test header was also set, it is the correct `text/html; charset=UTF-8`

## Expected Behavior

Content-Type should be `text/html; charset=UTF-8`

**Comment by agnes512** [comment]
Issue moved to [strongloop/loopback-next #5168](https://github.com/strongloop/loopback-next/issues/5168) via [**ZenHub**](https://www.zenhub.com/)
