### ISSUE TITLE
How auth OpenID with passport-steam

### ISSUE THREAD

**Issue by nhatnguyen12343** [strongloop/loopback#4323]

**Comment by nhatnguyen12343** [comment]
Please help me auth  with passport-steam OpenID setup with loopback

**Comment by deepakrkris** [comment]
@nhatnguyen12343 please take a look at https://github.com/miyoda/loopback-passport-jwt/blob/master/index.js, https://github.com/strongloop/loopback-component-passport , it may not have specific instructions on `passport-steam` but must answer general questions of using passport with loopback.
