### ISSUE TITLE
How to serve static file without passing from auth

### ISSUE THREAD

**Issue by ShubhamRK96** [strongloop/loopback#4326]
I want to serve static files without passing the request from the auth in middleware.

In `middleware.json`

```json
{
  "session": {},
  "auth": {
    "./middleware/checkAuth": {}
  },
  "parse": {},
"files": {
    "loopback#static": 
      {
        "name": "images",
        "paths": [
          "/assets/images"
        ],
        "params": "$!../assets/images"
      }
}
```

I want to bypass auth for serving static files.

**Comment by bajtos** [comment]
We are recommending users to configure static assets middleware in the `files` phase to avoid performance penalty paid when a request is first passed to the static middleware and then actually handled by the REST API layer. In such case, REST API requests are slowed down by filesystem checks performed by the static middleware.

In your case, the static assets are mounted on a subpath (presumably different from your REST API endpoints). In that case it should be fine to move the static middleware to an earlier phase, e.g. `initial`.

```json
{
  "initial": {
    "loopback#static": {
      "name": "images",
      "paths": [
        "/assets/images"
      ],
      "params": "$!../assets/images"
    }
  },
  "session": {},
  "auth": {
    "./middleware/checkAuth": {}
  },
  "parse": {},
  "files": {}
}
```
