### ISSUE TITLE
The worst readable and non informatics documentation

### ISSUE THREAD

**Issue by bivanychko-intobi** [strongloop/loopback#4335]
It's totally impossible to find something on your f*cking web site. For example for now I am working on Redis KV connector. Thanking to your documentation I don't understand how I can setup Redis for my app. What I should generate except datasource and how can I call 'get/set' functions to get some cache from Redis or set some cache into my Redis.

**Comment by emonddr** [comment]
@bivanychko-intobi, your language is not appropriate. Please edit your comment using more appropriate language. Thank you. :)
