### ISSUE TITLE
prototype.updateAttributes hooks not triggered with replaceOnPUT configuration

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [strongloop/loopback#4341]
## Steps to reproduce
- Configure the project with the flag `replaceOnPUT: true`
- Create a model and declare an hook on `prototype.updateAttributes`, like this:
```javascript
Task.beforeRemote('prototype.updateAttributes', function(context, opt, next) {
  console.log('here');
})
```
- Calling the PUT on that model does not pass through that beforeRemote.

## Current Behavior
Calling the PUT on that model does not pass through that beforeRemote.
Only declaring the hook on the `prototype.patchAttributes` will resolve to the expected behaviour.

## Expected Behavior
Calling the PUT on that model should pass through the `prototype.updateAttributes` beforeRemote.

**Comment by bajtos** [comment]
Thank you @giovanni-bertoncelli for reporting the bug. Please note that LoopBack 3 is in maintenance mode, we are fixing only critical bugs and security vulnerabilities. 

Based on your report, there is a reasonable workaround for your issue, thus I don't consider it as critical and closing this issue as "won't fix".
