### ISSUE TITLE
include for role mappings to different principalTypes

### ISSUE THREAD

**Issue by nvdnkpr** [strongloop/loopback#436]
I read through the issues, the tests and the docs but I couldn't find a word about the possibility to e.g. include all users (but not applications or roles) of a role.

I found issue #332 but
1) the code described there only works if we change the `return` call to `callback` (as described by @haohello) 

2) even if it is working, what would be the best next step to embed user objects in the roles ?

**Comment by superkhau** [comment]
@raymondfeng Is this still relevant?

**Comment by mike-aungsan** [comment]
I still have similar issue extending RoleMapping, AccessToken and ACL

**Comment by behrad** [comment]
https://github.com/strongloop/loopback/issues/1879
