### ISSUE TITLE
remoteMethod() has no request parameters when POSTed to.

### ISSUE THREAD

**Issue by eabruzzese** [strongloop/loopback#440]
Hey guys,

I have a brand-new loopback project, and I'm trying to follow the getting started guide. Unfortunately, when I go to try and extend my API with a simple "greeting" method, the "msg" parameter is always undefined.

I've been fiddling with it, and it looks like the request body is completely empty:

```javascript
module.exports = function (Offer) {
  
  Offer.greet = function (message, cb) {
    console.log(message); // Undefined if the "http" and "required" are removed from the argument below.
    cb(null, 'Hello, ' + message);
  }
  
  Offer.remoteMethod(
    'greet', 
    {
      accepts: { 
        arg: 'message', 
        type: 'string', 
        required: true,
        http: function (ctx) {
          console.log(ctx.req.body); // Completely empty. Produces "{}" in the console.
          return 'World!';
        }
      },
      returns: { arg: 'result', type: 'string' },
      http: { verb: 'POST' }
    }
  );

}
```

This only seems to be an issue with POST requests. GET requests work just fine. If I leave out the ```http``` from the argument, I get a 400: "message is a required arg" error. If I remove the "required", the message is simply undefined.

I'm not sure if there's something I'm missing, or if there's a bug here, but any help you could offer would be greatly appreciated!

Thanks.

**Comment by ritch** [comment]
@superkhau I cannot reproduce this...

Here is my model.js:

```js
module.exports = function(Offer) {
  Offer.greet = function (message, cb) {
    console.log(message); // Undefined if the "http" and "required" are removed from the argument below.
    cb(null, 'Hello, ' + message);
  }

  Offer.remoteMethod(
    'greet', 
    {
      accepts: { 
        arg: 'message', 
        type: 'string'
      },
      returns: { arg: 'result', type: 'string' },
      http: { verb: 'POST' }
    }
  );
};
```

And here is what I get in the explorer:

![screen shot 2015-01-09 at 11 05 28 am](https://cloud.githubusercontent.com/assets/462228/5685496/91547708-97ef-11e4-81b4-fbc12d7a0d6a.png)

**Comment by superkhau** [comment]
@ritch I checked via the inspector in Firefox, not explorer. Try inspecting for body values via Chrome inspector and see if you get anything.

**Comment by ritch** [comment]
Looks fine to me... 

![screen shot 2015-01-09 at 12 13 24 pm](https://cloud.githubusercontent.com/assets/462228/5686565/fbbcbf0c-97f8-11e4-88ed-79dc84848ec0.png)

**Comment by ritch** [comment]
Here is what I get:

![screen shot 2015-01-09 at 12 15 44 pm](https://cloud.githubusercontent.com/assets/462228/5686607/4c4b2d5a-97f9-11e4-861b-697133c23a68.png)

Looks fine to me...

**Comment by ritch** [comment]
@eabruzzese @superkhau 

I'm assuming this has been fixed. If you guys have steps to repro or any other related issue please re-open this.

**Comment by gholias** [comment]
Im having that problem, req.body or req.params is always undefined

this is how Im using it

Participant.remoteMethod(
        'register',
        {
            http: {path: '/register', verb: 'post'},
            accepts: [
              {arg: 'req', type: 'object', 'http': {source: 'req'}},
              {arg: 'res', type: 'object', 'http': {source: 'res'}},

**Comment by arash01** [comment]
Same here

**Comment by martinjuhasz** [comment]
Yup, also happening for me on a remoteMethod using `delete` as the HTTP-Verb.
Here is a screenshot of the request and as you can see there is no `formData` appended to my request.
Works fine if i just use the API, so it looks like the swagger explorer is missing this.

![ghissue1](https://cloud.githubusercontent.com/assets/204190/12912534/8489e74e-cf19-11e5-9eae-caf5ccbe0042.png)

So propably this issue should be reopened /cc @ritch

**Comment by carlosroec** [comment]
Hey @martinjuhasz, have you found a solution for this bug?. Same issue using the verb DELETE.

**Comment by martinjuhasz** [comment]
No sorry, i don't work anymore on that project and i'm not sure if this is solved. I guess the swagger implementation has problems with uncommon http-types like `DELETE` + body data.

**Comment by jmereaux** [comment]
Same problem here with a DELETE remote method.

├── loopback@2.35.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@2.7.0
├── loopback-component-model-diagram@0.2.0
├── loopback-component-visualizer@0.1.0
├── loopback-connector-cloudant@1.0.11
├── loopback-datasource-juggler@2.53.0

The issue is marked as closed. Is there any fix available?
