### ISSUE TITLE
Loopback oAuth2 server/provider

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback#442]
Sorry to post here. But I have question.

Is there any examples or packages to implement/integrate LoopBack REST API with node-oauth2-server ?

Basically I am looking into integration node-oauth2-server with Loopback.

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
