### ISSUE TITLE
A way to override remote methods

### ISSUE THREAD

**Issue by offlinehacker** [strongloop/loopback#443]
One such example would be `deleteById`, where instead of deleting, i would set only deleted property.

**Comment by mike-aungsan** [comment]
I have similar issue. 
https://github.com/strongloop/loopback/issues/1745

**Comment by CarlosCuevas** [comment]
@veekungx's solution works for me, @raymondfeng's didn't.

**Comment by Shyri** [comment]
I was trying @veekungx's solution but server got really slow, at the end it didn't complete any request. I found out debugging that Model.on('attached'.... was being called constantly again and again. Am I doing something wrong?

 @raymondfeng's didn't work for me

Thanks

**Comment by Shyri** [comment]
I found where the problem is but I don't know how to solve it.
I need to override method find of a model and get the accessToken/userId, so I do as follows:

```javascript
Model.on('attached', function(){
      Model.find = function(filter, cb){
            var ctx = loopback.getCurrentContext();
            var userId = ctx.get('accessToken').userId;
            //[...]
     }
});
```

when method find is called, it triggers a recursive call to find over and over again. Any thoughts?

Thanks

**Comment by amaurybrisou** [comment]
The @veekungx example doesn't work as it is for me (2.22.0). this works : 

    User.on('attached',function(){
        User.find = function(filter, empty, cb){
            cb(null,['This is a overridden method'])
        }
    })

**Comment by PaddyMann** [comment]
I found overriding the `find` method also affected `findOne` etc which was undesirable.

My workaround was:

    // Override Project.find to use our bespoke Project.list
    Project.on('attached', () => {
      const origFind = Project.find.bind(Project);
      Project.find = (query, options, cb) => {
        if (typeof options === 'function' && options.name === 'callback') {
          return Project.list(query, options);
        }
        return origFind(query, options, cb);
      };
    });

    // This method is written as it would be as a standard remote method
    Project.list = (filter, cb) => {
      ...
    }

**Comment by mamartins** [comment]
I tried this for updateAttributes with no success. 

Workaround: disable method and create my own

**Comment by PaddyMann** [comment]
My solution required a little tweaking for `findById`, and the same is probably true for `updateAttributes` @mamartins 

I now have a module exposing an `overideRemoteMethod` function:


    function overideRemoteMethod (model, methodName, newFunc) {
     const origFunc = model[methodName];
     model[methodName] = (a, b, c, d) => { // eslint-disable-line
       // We rely on the remote method call having a different signature to
       // the standard call.
       switch (methodName) {
         case 'findById':
           if (typeof c === 'function' && c.name === 'callback') {
             return newFunc(a, b, {}, c);
           }
           return origFunc.call(model, a, b, c, d);
         case 'find':
         case 'count':
         default:
           if (typeof b === 'function' && b.name === 'callback') {
             return newFunc(a, {}, b);
           }
           return origFunc.call(model, a, b, c);
       }
     };
    }

(You'll probably need to add `case 'updateById'` below `case 'findById'`)

I then call it in my model:


    module.exports = (Workspace) => {
      Workspace.on('attached', () => {
        // Overide default methods to only return workspaces that the given user has
        // access to
        overideRemoteMethod(Workspace, 'find', Workspace.remoteFind);
        overideRemoteMethod(Workspace, 'count', Workspace.remoteCount);
        overideRemoteMethod(Workspace, 'findById', Workspace.remoteFindById);
        ...
      }

      Workspace.remoteFind = function (filter, options) {
        ...
      }

**Comment by mamartins** [comment]
That's a good one. 

It would be good to have a default way of doing this for all methods

**Comment by the1mills** [comment]
Try ```Model.once('attached')``` otherwise memory leaks (?)

**Comment by PaddyMann** [comment]
My above solution for overriding methods is flawed as it doesn't provide a way to get the current context (now that getCurrentContext is deprecated).

Our solution has instead been to simply disable the default methods and create new ones. For clarity and consistency, we always name them `remoteFind`, `remoteCount`, etc.

**Comment by ritch** [comment]
Lets add something like this:

```js
Model.once('attached',function(){
        Model.find = function(filter,cb){
            cb(null,'This is a overridden method')
        }
    })
```

to the docs.

**Comment by Freundschaft** [comment]
how can I disable the filter paramter this way? for my GET /api/entity endpoints I would like to disable the filter parameter

**Comment by Freundschaft** [comment]
just figured it out, its possible to just override by rebinding to the http path:

```
Model.remoteMethod('findById', {
    description: 'Find a model instance by {{id}} from the data source.',
    accessType: 'READ',
    accepts: [
      {
        arg: 'id', type: 'any', description: 'Model id', required: true,
        http: {source: 'path'}
      },
      {arg: 'options', type: 'object', http: 'optionsFromRequest'},
    ],
    returns: {arg: 'data', type: 'Model', root: true},
    http: {verb: 'get', path: '/:id'}
  });
```

**Comment by ChopperLee2011** [comment]
override remote method and override model method is different, guys!
- if you use override model method just for changing default remote method like `findById`, then you go too far, 'cause when you are using this method anywhere, you are using the new rewrite version which I think is not expect behavior.
- if you just want to override remote method, I think you'd better **disable the old one, and then create a new one **

**Comment by Freundschaft** [comment]
@ChopperLee2011 I know that its different, I'd also agree that overriding the model method usually has a lot of implications, in my case it was sufficient to override just the remote method, since i only wanted to remove the filter attribute :)

**Comment by Maransatto** [comment]
I've tried @veekungx solution too, but it seems to work as an override, but it shows me the error message: TypeError: cb is not a function

**Comment by pbalan** [comment]
+1 @Maransatto Same for me

**Comment by AMHZR** [comment]
@here i am trying to override the deleteById Method to support my need but it seems not working

> MyModel.once('attached', function () {
>         MyModel.deleteById = function (id, cb) {
>             console.log('Overridden the models deleteById remoted method');
>             console.log(id);
>             MyModel.update({'id': id}, {'deleted': true}, cb);
>         }
>     });

**Comment by abqadeer** [comment]
In case if any body tries to do that in future here is how i did it(complete MyModel file)

    'use strict';

    module.exports = function (MyModel) {

        MyModel.once('attached',function(){
            MyModel.deleteById = function(filter,auth, cb){
                cb(null,'This is a overridden method')
            }
        })
    };

Thing to note here is that cb is the third argument to `deleteById`

**Comment by bajtos** [comment]
Hello, we don't have bandwidth to describe the solution(s) outlined above in our docs, but we are happy to help you along the way if you decide to contribute such documentation. See https://loopback.io/doc/en/contrib/doc-contrib.html to get started.

In [LoopBack 4](https://strongloop.com/strongblog/loopback-4-ga), all REST API methods are code-generated as thin wrappers around the underlying Repository data-access API and can be directly edited by app developers.

**Comment by seshagiri13** [comment]
Hi,
Can somebody give me the syntax for overriding patchAttributes method for a model.I have overidden all other methods but facing issue with it

**Comment by juanvillegas** [comment]
@seshagiri13 You can always add a beforeRemote that captures everything using the *.* wildcard. Then add a breakpoint in your debugger, trigger the request you want to override, and inspect what the Context object has. The context object has a bunch of information related to the request, including the "name" loopback assigns it internally. You can use that to override it.
