### ISSUE TITLE
Dev depends on legacy loopback-boot

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#448]
The test/fixture apps are still in 1.x format, and the devDependency 'loopback-boot' is at 1.x too.

**Comment by superkhau** [comment]
@fabien Which test fixture apps are these? Is this still relevant?

**Comment by superkhau** [comment]
Nevermind found them, the've been outdated for quite awhile now. They should be updated.

**Comment by superkhau** [comment]
@Amir-61 Reassigning to you as you are the expert. We should get this one prioritized.
