### ISSUE TITLE
"scopes" defined in model's JSON file doesn't work

### ISSUE THREAD

**Issue by clarkorz** [strongloop/loopback#454]
I follow the [docs](http://docs.strongloop.com/display/LB/Model+JSON+file#ModelJSONfile-Scopes). And it doesn't work. Has it been implemented yet? 

**Update 1**

> You can also define a scope programmatically using a model's scope() method

<del>`Model.scope(...)` doesn't work either, the model **has no method 'scope'**.</del>

**Update 2**

Sorry, the **scopes** key on model's JSON actually works. But I don't see the endpoint on API Explorer, until I call `Model.remoteMethod()` for that scope definition.

**Update 3**

After define `scopes` in model's JSON file, run `slc loopback:model` will throw errors: "Error: Items must be an array".

**Comment by clarkorz** [comment]
this has been supported

**Comment by mbenaissa** [comment]
Is this point of scope is closed, it doesn't work for me.
My case is: I have a Product model, and I set in place a system that trace CRUD actions in a meta data fields (created, updated, deleted, ownerId). We can't delete instances, but only flag them in the deleted field.
Now, I want to see in the list of products only the non deleted instances {deleted:false}.
I saw the documentation for the default "scope" : http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Defaultscope
I configure it, I have the same case in fact.
But, I'm searching entities from my Angular client and I'm using REST call. expl ; /api/portal/products/?filter={"offset":0,"limit":10}
I don't want to add additional query each time in my generic functions "findContent". I want to have a unique solution for both api(node) and REST cases. Each time I want to get instances from dataSource I get only the non deleted instances.
How can I do this please?
The Get call don't use the find method of the persistentModel? if no, I will have the same problem when I setup the ACls!!!

Thx.
