### ISSUE TITLE
Include 'transports' element in JSON for 'mail' datasource in datasources.json

### ISSUE THREAD

**Issue by britztopher** [strongloop/loopback#460]
This is more of a feature request, so tag it as you see it.  But I was just talking in the forum and it seems like there isnt a way to specify which transport you are using in the definition of the email datasource.  Basically, there are only 2 fields within the `mail` datasource 

```javascript
"mail": {
    "defaultForType": "mail",
    "connector": "mail"
  }
```

however, wouldnt it be nice to be able to configure NodeMailer transports within the JSON file, so the above would now be like:

```javascript
"mail": {
    "defaultForType": "mail",
    "connector": "mail"
    "transport": 
            {
                type: 'smtp',
                host: smtp_host,
                secureConnection: true,
                port: smtp_port,
                auth: {
                    user: smtp_user,
                    pass: smtp_password
                }
            }
     }
```
This type of abstraction I think is what loopback is trying to gain with all of its JSON files for different models/datasources/configurations, so this would a nice feature and align with roadmap.  Just food for thought, but would like to know comments/questions.

**Comment by bajtos** [comment]
I am closing this issue as done by #469
