### ISSUE TITLE
How to hide base classes from RestAPI / Explorer?

### ISSUE THREAD

**Issue by tbrannam** [strongloop/loopback#465]
It appears that when User is inherited - by a user defined class (e.g. Customer) - both Customer and User are visible by default in the Explorer -- how can the User path be removed from the Explorer and or the Rest interface without affecting Customer class?

**Comment by mike-aungsan** [comment]
I can put this at user.js, model extends from build-in user, which hidden count API from API explorer and probably disable
user.sharedClass.find('count', true).shared = false

But I want to hide and disable reset API but have type error
user.sharedClass.find('reset', true).shared = false

TypeError: Cannot set property 'shared' of null

Anyway, these API should be in document somewhere. 

Many Thanks

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Parts of the above are documented:
- [sharedClass.find()](https://apidocs.strongloop.com/strong-remoting/#sharedclass-prototype-find)
- [sharedMethod](https://apidocs.strongloop.com/strong-remoting/#sharedmethod) - I notice that the `shared` class property does not have a description--I will add that.

AFAIK, there is no `reset` method of `user`, but there is a [resetPassword](https://apidocs.strongloop.com/loopback/#user-resetpassword) method, so @mike-aungsan maybe you should use that instead: 
```
user.sharedClass.find('resetPassword', true).shared = false
```

But I think the "best practice" way to do this is:
```
User.disableRemoteMethod("resetPassword", true);
```

**Comment by mike-aungsan** [comment]
@crandmck 
What is the different between those two?

For example,

// does not work
user.disableRemoteMethod('update', true)
user.disableRemoteMethod('destroyById', true)

// it work
user.sharedClass.find('update', true).shared = false
user.sharedClass.find('destroyById', true).shared = false

Thanks.

**Comment by crandmck** [comment]
Where is this code running?  Normally, it's `User` (not `user`), because you do 
```
var User = app.models.User;
```

**Comment by mike-aungsan** [comment]
I extend User model and the  name is user. 

  module.exports = function(user) {
    
    user.disableRemoteMethod('createChangeStream', true)
    
    // Update or insert a model instance
    user.disableRemoteMethod('upsert', true)
    user.disableRemoteMethod('create', true)
    user.disableRemoteMethod('resetPassword', true)
    
    user.sharedClass.find('update', true).shared = false
    user.sharedClass.find('destroyById', true).shared = false
    user.sharedClass.find('find', true).shared = false
    
  };

I just want to know the different between those two since I don't know what is sharedClass.
Anyway, I will wait your description

**Comment by Edudjr** [comment]
Check [this](https://github.com/strongloop/loopback/issues/651#issuecomment-167111395) solution from ericpietro.
