### ISSUE TITLE
Relation methods for "hasMany through" with extra properties on "through" Model

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#466]
Consider the example described in [docs](http://docs.strongloop.com/display/LB/HasManyThrough+relations) for HasManyThrough:

> The “through” model, Appointment, has two foreign key properties, physicianId and patientId, that reference the primary keys in the declaring model, Physician, and the target model, Patient.

At the moment, loopback creates relation methods like `Physician.patients` that hides the "through" model, thus make it difficult to obtain Appointment details.

Examples
1. To find a list of all patients and the appointment dates for a given physician (id), one has to query appointments:
   
   ```
   GET /appointments?filter={"include":["patient"],"where":{"physicianId":2}}
   ```
   
   It would be much nicer if one could write this instead:
   
   ```
     GET /physicians/2/appointments?filter={"include":["patient"]}
     // or even better
     GET /physicians/2/appointments
   ```
2. The current API makes it easy to add a new Patient to a Physician, but such call will not fill appointment date. IMO a more frequent use case is to add a new Appointment to a Physician, using an existing Patient.
   
   At the moment, one has to add the appointment via `Appointment.create()`. A better API would be `physician.appointments.create()`.

This issue is based on this [StackOverflow question](http://stackoverflow.com/questions/25256741/set-the-custom-properties-in-joining-model-using-loopbacks-hasmanythrough).

**Comment by XinV** [comment]
How is it going in this proposal? We really want to create the record in the through model (with extra property such as appointment date in one single API call, in order to make sure it's done in one transaction, so fail or succeed.
My guess is the suggestion from @fabien makes sense.
`
Or have some kind of convention to have a special key on data to specify this 'through' data (_appointment in this case, or perhaps even _appointment):

{ name: 'John', _appointment: { date: ... } }
`

**Comment by jamesjjk** [comment]
@XinV @bajtos Is there any update on this feature? The idea of a special key (or reserved naming) to retrieve the properties of the through model, on retrieving related data would be great!

**Comment by EvanWillms** [comment]
+1

I've ended up creating a second relationship to access extra data stored in the join table and then have to manually re-attach it.  Native support to access these properties in the primary relationship would be awesome.

```
"relations": {
    "conversations": {
      "type": "hasAndBelongsToMany",
      "model": "Conversation",
      "foreignKey": "",
      "through": "ConversationUserMap"
    },
    "conversationsMetadata": {
      "type": "hasMany",
      "model": "ConversationUserMap",
      "foreignKey": ""
    }
}
```

**Comment by WildPyromancer** [comment]
Any updates on this feature? This could prove to be extremely beneficial.

**Comment by dahuahe** [comment]
还没有解决吗？

**Comment by JonnyBGod** [comment]
This would simplify a lot f implementations.
Any news on this?

**Comment by JonnyBGod** [comment]
I just released two new mixins to take care of these features:

[loopback-set-through-properties-mixin](https://github.com/JonnyBGod/loopback-set-through-properties-mixin) allow to set through model properties

[loopback-include-through-mixin](https://github.com/JonnyBGod/loopback-include-through-mixin) allows to include model properties with queries

**Comment by proreact-mj** [comment]
Related #3415 (I think, at least the solution would most likely fix the bug)

Seems there is a inconsistency in how filters are applied through "hasMany" and "hasAndBelongsToMany" relations, when M:N through a through-model

where/include are applied to the related model

order/limit are applied to the through model

This seems to be consistent between "hasMany" and "hasAndBelongsToMany" relations.

**Comment by segnini75** [comment]
Hi, please let me know if there is any solution for this. Am actually searching for a solution.

I have 3 models user  <=> relUserContact <=> contact

user properties: name, lastname, etc.
contact properties: name, email, phone.
relUserComments: **type**, user_id, contact_id

I managed to fetch comments using filter in GET /users
Also in GET /users/{id}/contacts

Explorer sugestion is that I can create a new contact via POST /users/{id}/contacts but always fails with error:  La instancia `relUserComments` no es válida. Detalles: `type` can\'t be blank (value: undefined).

Thanks

**Comment by michaelcerne** [comment]
Was this ever resolved with an official solution?

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be adding any new features.

**Comment by marcelodive** [comment]
Does something like this exists in Loopback 4?

**Comment by bajtos** [comment]
> Does something like this exist in Loopback 4?

Not yet.

@marcelodive feel free to open a feature request in https://github.com/strongloop/loopback-next
