### ISSUE TITLE
Default ACL for scaffolded models

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#470]
@cgole ran into an issue the other day where she added an ACL to `ALLOW` access to `$authenticated` users. She was surprised to find that the API was still accessible to everyone. I think this is a common issue, although I haven't seen it posted here.

What if we provide a default ACL (configurable) when scaffolding a new model? Something like this:

``` txt
DENY EVERYONE *
```

This would effectively default the security layer to `DENY` all requests. You would then open up APIs by adding access controls.

@raymondfeng @bajtos @fabien thoughts?

**Comment by bajtos** [comment]
> What if we provide a default ACL (configurable) when scaffolding a new model? Something like this:

> ```
DENY EVERYONE *
```

> This would effectively default the security layer to DENY all requests. You would then open up APIs by adding access controls.

@ritch what's your take, is this still relevant? The issue has been opened since Aug 2014 without much activity in the last year.
