### ISSUE TITLE
Server-side MVC

### ISSUE THREAD

**Issue by luckymancvp** [strongloop/loopback#473]
Please tell me: Is loopback a MVC framework build on expresjs ?. 
1. How can I define a new controller to handle request. Or everything in loopback is model
2. How can I send more information after each request, example: timestamp. 
3. I see in app.js have a line app.enableAuth() to check token, secure app. But how to customize this app, example I want to check if request have a specific header value. 

Thanks in adavanced, loopback.io team

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

@bajtos @raymondfeng @ritch Safe to close?

**Comment by bajtos** [comment]
@superkhau I'd prefer to keep this open as an ongoing discussion about how to best support the MVC paradigm.

**Comment by superkhau** [comment]
@bajtos Sounds good.

**Comment by gavinengel** [comment]
Hmm.  The models in loopback are definitely there already in common/models.  The views I guess are not meant to be in a loopback project, as it is returning raw json from ajax/websocket.  Since routing basically follows a standard from LB/Swagger (I think), just leaves controllers.  So, are controllers needed in a REST API framework?  I think so.  In my mind it makes sense that an endpoint is not tied to a single model.  For instance, let's say I'm sharing listings from an auction website at /listings/.  In addition to a huge array of listings, I want to give out a small nested array within each array of the seller's basic info.  Not necessary, but I think it would save other hits to /users/ that my API users might write to pull info on every listing.  There would be other controllery I would do in these controller files that I don't like doing in the server.js or in the model .js files.  So  I wouldn't mind seeing a simplified controllers layer added to loopback, even if they all shared the same names like user.js but were in a common/controllers dir.

**Comment by pungoyal** [comment]
Would it not be simple enough to mount a server side MVC framework like sailsJS or locomotiveJS at a route point in loopback?

Anyone has had any luck with that?

**Comment by niallobrien** [comment]
Has anyone made any progress with this?

**Comment by ronenteva** [comment]
Now that sails future is not clear, using Loopback as a server side MVC looks like a good alternative.
I found an [article](https://github.com/shortwavapp/loopback-tutorials/tree/master/01-server-side-templates) about serving views, which worked perfect. 
However there are some things that are unclear like how to expose the controllers and services.
@kisayista I couldn't find the [boilerplate](https://github.com/auroratechnologies/loopback-example-mvc) you made, any chance you can upload it again?

**Comment by BerkeleyTrue** [comment]
@niallobrien @ronenteva We have used Loopback as a server side MVC for while now. Here is a router/controller https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/boot/nonprofits.js and the views for this controller are here https://github.com/FreeCodeCamp/FreeCodeCamp/tree/staging/server/views/nonprofits

**Comment by kisayista** [comment]
Sorry @ronenteva. I've deleted the repo from both Github and my local computer. :(

**Comment by niallobrien** [comment]
I'd assume we'd need more features for server-side rendered apps though, eg. csrf protection on forms etc.

**Comment by BerkeleyTrue** [comment]
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/middlewares/csp.js
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/middlewares/sessions.js
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/middlewares/cookie-parser.js
https://github.com/FreeCodeCamp/FreeCodeCamp/blob/staging/server/middleware.json

Loopback is just a wrapping around express that provides structure and auto-generated REST endpoints anything you can do with Express, which is an MVC, you can do with Loopback.

**Comment by ronenteva** [comment]
@kisayista No worries, thanks for letting us know.
@niallobrien I've been researching for a while now, and Loopback seems to be the best alternative in my honest opinion.
@BerkeleyTrue Thank you for sharing your use case, I find it VERY useful! :+1: 
@superkhau @bajtos I assume it's not on your roadmap, but I really think that if you'll post an official boilerplate / tutorial, you'll be seeing a lot of [confused sails users](https://github.com/balderdashy/sails/issues/3429) coming your way.

**Comment by richardpringle** [comment]
Hey guys, I'm exploring options for implementing controllers right now. Has anyone used @kisayista's implementation (I found a fork [here](https://github.com/ForkedRepoSnaphy/loopback-example-mvc))? What about @BerkeleyTrue's implementation?

Keep the discussion going, I'm interested in any more thoughts.

**Comment by pbalaga** [comment]
Probably as many others I wonder if this topic is still being explored. Loopback sets its goals clear as an API framework but - in spite of its growth - the Node ecosystem seems to be lacking a reliable MVC-based framework for building web apps (similar to RoR, ASP MVC, etc.). I would imagine this has a lot of potential.

Is that anything going on in this direction?

**Comment by superkhau** [comment]
@pbalaga There is work being done with regards to adding controllers so stay tuned. Not definitive dates on implementation, but there will be a blog post when it happens. Make sure you subscribe to get the updates/announcements. https://strongloop.com/strongblog/

**Comment by hackerunet** [comment]
Hello, I have found some material about MVC implementations but so far I think the most complete and well explained approach has been posted by https://github.com/BerkeleyTrue , so, I have a question regarding the server.js example material submitted by him. Is that aproach vaid to deliver node server up and running in a production environment?
That approach also validares and apply security suggestions shown in official loopback documentation, so, I think worths it to be posted as a solid and final respond to this issue which discuss MVC pattern on loopback based applications.

**Comment by superkhau** [comment]
>Is that aproach valid to deliver node server up and running in a production environment?

There are many ways to skin the cat, but yes that is one approach that is valid (you would do the same as you would with vanilla express routes -- see http://expressjs.com/en/guide/routing.html). The `app` in `server.js` is the same app as you get with `express()` with additional functionality. How you organize your routes (in `server/controllers`, etc) is up to you. However, I do agree we should probably have some sort of standard locations so we can all benefit from convention over configuration.

**Comment by hackerunet** [comment]
Hello, Sorry to be again adding more doubts to this topic but I have some observations about documentation and server side MVC implementation:
1) After hours of digging deeply in loopback documentation I found some differences about how to succesfully secure server side views using third parties authentication, example: loopback-component-passport, the docs here specify the need of 3 basic models creation which are: UserIdentity model, UserCredential model and ApplicationCredential model, also it says that the last model has to extend Application model (WHEN IN THE FIRST PLACE I BUILT THAT MODEL???), and in the same documentation it references an example code which is not following the official documentation explanation, so, in the first place this result TEDIOUS and ANNOYING having to research why in the example there are 3 different models and no Application model specification NOWHERE, in the example there are the following models: user-credential, user-identity and user-token model which I guess is the substitute to ApplicationCredential model. 

2) When I check the code of the example models (https://github.com/strongloop/loopback-example-passport/tree/master/common/models) i can see 
```
"base": "UserCredential",
```
so, if I use slc loopback:model I don't have a UserCredential base model to use it as it sais BASE, I can suspect the UserCredential model is on the builtin models, but no, it is not, ALL MY CLASSES EXTENDS PersistedModel. So this discordances affects negatively the learning curve of this framework and i think results in number of users running away. I do understand this requires a basic programming skills in node.js but not all of us are IBM engineers to figure out why in the heck the model.json file in the example is based on itself, accordingly to the code base: "UserIdentity" means that UserIdentity is extending itself??
here is the code: user-identity.json
```
{
  "name": "userCredential",
  "plural": "userCredentials",
  "base": "UserCredential",
  "properties": {},
  "validations": [],
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    }
  },
  "acls": [],
  "methods": []
}
```

3) Loopback created middleware.json file to order all middleware functions in a global file with a global context and it's great but, why LAZY coders that submits examples to Loopback official documentations do such things as this: server.js file in https://github.com/strongloop/loopback-example-passport/blob/master/server/server.js
```
// to support JSON-encoded bodies
app.middleware('parse', bodyParser.json());
// to support URL-encoded bodies
app.middleware('parse', bodyParser.urlencoded({
  extended: true,
}));

// The access token is only available after boot
app.middleware('auth', loopback.token({
  model: app.models.accessToken,
}));

app.middleware('session:before', loopback.cookieParser(app.get('cookieSecret')));
app.middleware('session', loopback.session({
  secret: 'kitty',
  saveUninitialized: true,
  resave: true,
}));
```
WHY? WHY loopback coders breaks up the default loopback modularity attempt to organize everything in well documented and specified files schema?
So, this are my observations as newbie coder AND possible next ex possible loopback coder.
Regards.

**Comment by hackerunet** [comment]
Also Can Anyone help me out on this? 
in this example https://github.com/strongloop/loopback-example-passport/blob/master/server/server.js
providers.json file setup a local strategy which has the following configuration:
```
{
  "local": {
    "provider": "local",
    "module": "passport-local",
    "usernameField": "email",
    "passwordField": "password",
    "authPath": "/auth/local",
    "successRedirect": "/app",
    "failureRedirect": "/login",
    "failureFlash": true
  }
}
```
It means that my post from login will submit username and password to the url /auth/local , so, When I do this I get nothing at all following all instructions from
https://docs.strongloop.com/display/public/LB/Third-party+login+using+Passport
https://github.com/strongloop/loopback-example-passport

So, I need to know 
1) How can I get the flash messages back to /login url which is serving a view
2) How to pass a callback to the login process in order to console.log everything and see outputs
This is my server login url:
```
app.get('/login', function(req, res, next) {
  res.render('public/login.ejs',
  {
    user:req.user,
    url: req.url,
    layout:'layouts/public.ejs'
  });
});
```
I have nothing declared in server.js that handles the /auth/local so I'm counting on passport loopback component. 
also, Why in this example: https://github.com/strongloop/loopback-example-passport
We see an after signup auto login function and not a single basic login function working with passport using a local strategy?, is not very clear this part in the example, but if someone can help me to understand this will be great.
regards
server.js script:
```
'use strict';

// Basic variables declaration for environment
var loopback = require('loopback');
var boot = require('loopback-boot');
var app = module.exports = loopback();
var expressLayouts = require('express-ejs-layouts');

// Passport configurators..
var loopbackPassport = require('loopback-component-passport');
var PassportConfigurator = loopbackPassport.PassportConfigurator;
var passportConfigurator = new PassportConfigurator(app);

/*
 * body-parser is a piece of express middleware that
 *   reads a form's input and stores it as a javascript
 *   object accessible through `req.body`
 *
 */
var bodyParser = require('body-parser');

/**
 * Flash messages for passport
 *
 * Setting the failureFlash option to true instructs Passport to flash an
 * error message using the message given by the strategy's verify callback,
 * if any. This is often the best approach, because the verify callback
 * can make the most accurate determination of why authentication failed.
 */
var flash      = require('express-flash');

// attempt to build the providers/passport config
var config = {};
try {
  config = require('../config/providers.json');
} catch (err) {
  console.trace(err);
  process.exit(1); // fatal
}

// -- Add your pre-processing middleware here --

// Setup the view engine (jade)
var path = require('path');
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');
app.use(expressLayouts);
// boot scripts mount components like REST API
boot(app, __dirname);
// to support JSON-encoded bodies
app.middleware('parse', bodyParser.json());
// to support URL-encoded bodies
app.middleware('parse', bodyParser.urlencoded({
  extended: true
}));

// The access token is only available after boot
app.middleware('auth', loopback.token({
  model: app.models.accessToken,
}));

app.middleware('session:before', loopback.cookieParser(app.get('cookieSecret')));
app.middleware('session', loopback.session({
  secret: 'k4m1k4z3!!2016@@@',
  saveUninitialized: true,
  resave: true
}));
passportConfigurator.init();

// We need flash messages to see passport errors
app.use(flash());

passportConfigurator.setupModels({
  userModel: app.models.smart_account,
  userIdentityModel: app.models.smart_identity,
  userCredentialModel: app.models.smart_credential
});
for (var s in config) {
  var c = config[s];
  c.session = c.session !== false;
  passportConfigurator.configureProvider(s, c);
}
var ensureLoggedIn = require('connect-ensure-login').ensureLoggedIn;

app.get('/login', function(req, res, next) {
  res.render('public/login.ejs',
  {
    user:req.user,
    url: req.url,
    layout:'layouts/public.ejs'
  });
});

app.get('/signup', function(req, res, next) {
  res.render('public/signup.ejs', {
    user: req.user,
    url: req.url
  });
});

app.post('/signup', function(req, res, next) {
  var User = app.models.smart_account;

  var newUser = {};
  newUser.email = req.body.email.toLowerCase();
  newUser.username = req.body.username.trim();
  newUser.password = req.body.password;

  User.create(newUser, function(err, user) {
    if (err) {
      req.flash('error', err.message);
      return res.redirect('back');
    } else {
      // Passport exposes a login() function on req (also aliased as logIn())
      // that can be used to establish a login session. This function is
      // primarily used when users sign up, during which req.login() can
      // be invoked to log in the newly registered user.
      req.login(user, function(err) {
        if (err) {
          req.flash('error', err.message);
          return res.redirect('back');
        }
        return res.redirect('/app');
      });
    }
  });
});

app.get('/logout', function(req, res, next) {
  req.logout();
  res.redirect('/login');
});

app.get('/app', ensureLoggedIn('/login'), function(req, res, next) {
  res.render('private/app.ejs', {
    user: req.user,
    url: req.url,
  });
});

app.start = function() {
  // start the web server
  return app.listen(function() {
    app.emit('started');
    var baseUrl = app.get('url').replace(/\/$/, '');
    console.log('Web server listening at: %s', baseUrl);
    if (app.get('loopback-component-explorer')) {
      var explorerPath = app.get('loopback-component-explorer').mountPath;
      console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
    }
  });
};

// start the server if `$ node server.js`
if (require.main === module) {
  app.start();
}

```

**Comment by frastlin** [comment]
Hello,
I would like to request that a "MVC Server" be placed in the "? What kind of application do you have in mind? (Use arrow keys)" part of the "slc loopback" command.
There currently doesn't seem to be any kind of guidance on creating an MVC framework with Loopback. I would love to see something that can compare to what Sails currently has. I feel Loopback is much much more active than Sails, there is way more focus given to Loopback than Sails and there are many other little things that really make Loopback attractive. The only thing that is keeping me from switching completely is the lack of official MVC support. It should not be too difficult to implement as:
https://github.com/ForkedRepoSnaphy/loopback-example-mvc

already has the controller part of mvc.
I would also love to see a "getting started" example be in the readme of each configuration type.

**Comment by bajtos** [comment]
We will be adding support for controllers in the next major version of LoopBack. Stay tuned!
