### ISSUE TITLE
Data fixtures loading

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback#475]
I have quick questions. Is there any possibility or any guidance how to load fixtures with loopback?

For example - reload fixtures for testing.

or

Have base fixtures what should be loaded when you re-create project. For CI or new developer.

I mean I need to load default data somehow.. For example city list using loopback models.

Thanks

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by poldridge** [comment]
+1
