### ISSUE TITLE
How do I disable relations / remove them from the Explorer?

### ISSUE THREAD

**Issue by STRML** [strongloop/loopback#477]
Since updating, I am now seeing the

`/user/{id}/accessTokens/{fk}` routes in the API Explorer. I don't want to expose these. How do I prevent them from being publicly invoked and remove them from the Explorer?

**Comment by superkhau** [comment]
This issue appears to be resolved at https://github.com/strongloop/strong-remoting/issues/94. Closing. @STRML Please open a new issue if you are still having problems with this.
