### ISSUE TITLE
Idea: Additional 'byType: boolean'  in JSON files to extend built-in models much easier

### ISSUE THREAD

**Issue by nvdnkpr** [strongloop/loopback#479]
**As an simple use case**
With the current `User` - `AccessToken` relation, if I currently want to extend the `AccessToken` model to `MyAccessToken`, I have to extend `User` to `MyUser` too. 
Otherwise it would still relate to the old `AccessToken` model instead of relating to the new `MyAccessToken` model. 

**Idea**
An additional boolean attribute `byType` (default is true) which (if true) indicates that this relation' counter model should be searched via the `loopback.getModelByType` method or (if false) should be referred (like it does right now) directly by name.

So in the use case above this would mean that both relations would relate to the "newest" counter model in the inheritance chain: 
- `User` then has many `MyAccessToken` (the newest `AccessToken` model)
- `MyAccessToken` belongs still to `User` (the untouched and therefore newest `User` model)

**Little Background:**
I'm re-rewriting the Role & RoleMapping model with polymorphic relations. 
  - The `RoleMapping` model as the through model currently relates to the built-in Role-model.
  - The `Role`, the `User` and the `Application` model are modeled as many-to-many polymorphic relations with the `RoleMapping` as through model.

**I know it's possible without this feature, but ...**
... as soon as  the `User` model get's extended to a `MyUser` model (and I guess that happens in like 98% of all loopback projects :smile:), the `Role` model (because of its polymorphic relation to `User`) must get extended too. And with this central change of `Role` the other related models `Application` and `RoleMapping` have to get extended too.

**Comment by bajtos** [comment]
@nvdnkpr IIRC, one can reconfigure relations of built-in models in `server/model-config.json`. Source code: https://github.com/strongloop/loopback/blob/88d41f84fd8eac997a31388ccdbd3ce026ab0dfe/lib/registry.js#L181-L191

An example of `server/model-config.json` (I didn't tested it myself though):

```json
{
  "MyUser": {
    "public": true,
    "dataSource": "db",
  },
  "AccessToken": {
    "public": false,
    "dataSource": "db",
    "relations": {
      "user": {
        "type": "belongsTo",
        "model": "MyUser",
        "foreignKey": "userId"
      }
  }
}
```

I am closing this issue as no longer relevant, feel free to reopen if the solution outlined above does not work for you.
