### ISSUE TITLE
Cant get roles to work

### ISSUE THREAD

**Issue by romuloctba** [strongloop/loopback#484]
Hey I have created a role, and added rolemapping to the role and for the user (being principalId the user's id)
Well, when i do `slc strongloop:acl`  it shows me only these roles: unregistered, logged in and owner, it does not show the role i created.

How can I set ACL to a role that i created?

Btw, it works ok with mongodb? In my search for this solution i saw some guys complaining it wouldn't work because mongo is not relational.....

thanks for any help

**Comment by superkhau** [comment]
@romuloctba Are you still running into issues with this? Can I close this?

**Comment by romuloctba** [comment]
Please, do. Thank you

2016-02-04 18:12 GMT-02:00 Simon Ho <notifications@github.com>:

**Comment by superkhau** [comment]
@romuloctba TY. Closing.
