### ISSUE TITLE
Cannot set the boolean column to 'false'

### ISSUE THREAD

**Issue by fibers** [strongloop/loopback#485]
I use loopback to create a restful service and the mysql schema is following:
<pre>
 CREATE TABLE `user_reports` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `is_new` tinyint(1) NOT NULL,
) ENGINE=InnoDB
</pre>

It's OK to POST a new record with the data on loopback explorer website
<pre>{"user_id":1,"product_id":1,"is_new":0}</pre> 
Response Body
<pre>
{
  "id": 1,
  "user_id": 1,
  "reporter_id": 1,
  "is_new": false
}
</pre>

But when I use Postman or Curl to create a new record with the same data. I receive the response body 
Response Body
<pre>
{
  "id": 1,
  "user_id": 1,
  "reporter_id": 1,
  "is_new": true
}
</pre>
It seems that the field 'is_new' always be true no matter which value I provide.

Is it a bug or may I miss something?

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report
