### ISSUE TITLE
consider renaming loopback for seo

### ISSUE THREAD

**Issue by HansHammel** [strongloop/loopback#496]
Loopback is a nice peace of technology, but searching for help is quite hard, because of lots of network stuff related results when searching for "loopback". Changing the name of your product on the next major release could help solving this (IMHO) big issue (for searching and gaining popularity). So, consider renaming loopback for search engine optimization. This would even help new developers to distinguish the new release (and it's breaking changes) from the various, abandoned advices on "loopback" in forums, etc.

**Comment by superkhau** [comment]
@altsang Is this still relevant?

**Comment by superkhau** [comment]
@chandadharap @bajtos Can I close this issue? It's been around for more than a year and I don't think it'll be resolved anytime soon.

**Comment by superkhau** [comment]
Closing as per conversation with @chandadharap.
