### ISSUE TITLE
Error: The middleware loopback.favicon is not installed.

### ISSUE THREAD

**Issue by diproart** [strongloop/loopback#500]
Clean install LoopBack 2.0.0
        
        slc loopback favicon-missing
        cd  favicon-missing  
        slc run

throw error

         loopback/favicon-missing/node_modules/loopback/lib/express-middleware.js:18
         throw new Error(msg);
                 ^
          Error: The middleware loopback.favicon is not installed.
          Run `npm install --save serve-favicon` to fix the problem.

But after install `npm install --save serve-favicon` nothing to change
If use express 4.8.4 in loopback dependencies all ok.

**Comment by superkhau** [comment]
@diproart Has the issue been resolved? Can I close it?

**Comment by OwenBrotherwood** [comment]
@superkhau I use Windows 8.1 node v0.12.1 npm 2.5.1
No problem running running @diproart or @inDream scenarios.

**Comment by superkhau** [comment]
@OwenBrotherwood Thanks for confirming! ;) Closing.

@diproart @inDream Comment again if you are still having issues.
