### ISSUE TITLE
API delete on a scope should return the number of items deleted

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#502]
The remoting enabled `__delete__<rel>` methods should return the number of items deleted. I'm not sure if all connectors provide this information (the memory adaptor does not, it seems).

**Comment by Amir-61** [comment]
>@raymondfeng there's currently no REST API feedback for delete operations. I even think the statusCode is always 204, regardless if anything has been delete. Is this on purpose (security)?

I believe https://github.com/strongloop/loopback/pull/1667 now solves this problem and now we return 200 HTTP status code as well. CC: @superkhau 

Related: https://github.com/strongloop/loopback/issues/2774#issuecomment-249039009

Closing this issue now.
