### ISSUE TITLE
Error during "npm install -g strongloop"

### ISSUE THREAD

**Issue by bigmeech** [strongloop/loopback#506]
Hi, i cant seem to figure out why i cant successfully install the strongloop module. I have python installed and can run the python command without issues. I'm also running the commands with admin rights. Here is my npm error log

```shh
> node-syslog@1.1.7 install C:\Users\Janer\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-supervisor\node_modules\node-syslog
> node-gyp rebuild

C:\Users\Janer\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-supervisor\node_modules\node-syslog>node "C:\node\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:988:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:779:34)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\node\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Janer\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-supervisor\node_modules\node-syslog
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm http 304 https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/lynx
npm http 304 https://registry.npmjs.org/cycle
npm http 304 https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/eyes
npm http 304 https://registry.npmjs.org/verror/1.1.0
npm http 304 https://registry.npmjs.org/keypress
```

this seems to happen about 10 to 15 times during the install processes causing it to fail completely. Any ideas why i'm experiencing this?

I'm running Windows7.

**Comment by superkhau** [comment]
@bigmeech Has the issue been resolved? Can I close it?

**Comment by OwenBrotherwood** [comment]
@superkhau I doubt that others face this issue at the moment, others maybe 

One could maybe cherry pick the comment for https://github.com/strongloop/loopback/issues/506#issuecomment-54684498 , and see if something like it is present in the documentation

**Comment by superkhau** [comment]
@OwenBrotherwood You're right, this should be marked as `triage` + `waiting` instead of `bug`. Updated. I don't think this is an issue ATM either, but just making sure all parties had a chance to speak before closing this prematurely.

**Comment by balajicheenu** [comment]
This is still an issue. Doesn't work on Windows 7. Asking for Visual Studio. 

\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-pm\node_modules\strong-supervisor\node_modules\heapdump\build\binding.sln : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) ins
tall Microsoft Visual Studio 2008.

**Comment by OwenBrotherwood** [comment]
@balajicheenu 
Please read the requirements. It needs what it is asking for
https://docs.strongloop.com/display/SL/Installing+Node+and+StrongLoop+on+Windows#InstallingNodeandStrongLooponWindows-Installprerequisites

@superkhau 
You should probably close this as, after installing strongloop many times on Windows (different versions) there are not the problems indicated.

**Comment by superkhau** [comment]
@balajicheenu Did you do the things outlined in the error? I assume you need the Visual C++ component installed.

**Comment by superkhau** [comment]
I'm going to close this, please reopen if you guys are still running into issues.
