### ISSUE TITLE
suggested way of integrating Elasticsearch Data View

### ISSUE THREAD

**Issue by gebrits** [strongloop/loopback#508]
First of all, hello Loopback community!
Coming from SailsJS which is already better then 99%, I must say I was blown away with the infra-stuff that Loopback offers. Going to put some time in getting the know the framework and hopefully building good stuff with it!

To that end you may see some questions coming the couple of days, most of which will be architecture related. Since those type of questions generally lack proper answers on Stackoverflow in my experience, I thought I post them here. I hope that's okay. 

First off:

This may go against the suggested best practice of Distributed data sources in that 'latent ahead-of-time denormalization' is discouraged. (see http://strongloop.com/strongblog/nodejs-loopback-deployd-api-serve/) 

However, for various use-cases I'll be needing the flexibility of a Elasticsearch (ES) endpoint for querying. I imagine this ES-index to be eagerly fed by by main data-source (or collection of data-sources). For the pattern-lovers the ES-index would be an[ Eager Read Derivation](http://martinfowler.com/bliki/EagerReadDerivation.html). 

Idea would be to enable the query-endpoint by exposing a 'remote method(s)' on the model-class specifically for this purpose. To say in semi REST-terms this would generally be called `/<model>/search`. **Would that be the 'loopback'-way of exposing the readonly-endpoint? **

For indexing (CUD) Elasticsearch, the ideal way would be: 

1. whenever a change happens to the main datasource (or collection of datasources) this is afterwards exposed as an **event** on a 'river of changes'. This would be push-based. As an alternative (in case ES was offline or has to play catch-up) a pull-endpoint would be available to request these change-events from a particular marking (point in time or id-based) . 
2. ES would happily start indexing based on the change-events + the schemas it maintains for indexing.

**question**: Does the notion of such  a 'change river' exist? If not, would you be open for such an addition or does this go directly against Loopback best practices? Other/better ways on how to tackle this?

**Comment by yagobski** [comment]
Hi, Iam working on the new version of the Elastic Connector can help to have multiple index management and synch between models and ES based on events. To finish this module i need some architecture advices to make create/delete the first mapping and the index All feature. Any suggestions?

**Comment by bajtos** [comment]
Hello, as part of our triage process, I am closing issues that have been inactive for extended period of time. Please let us know if you are still keen to work on the ElasticSearch connector, so that we can reopen this discussion.
