### ISSUE TITLE
Relation REST API should support creation of multiple items at once

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#509]
The -toMany relations could support POSTing an array of models to be created and associated. We should establish a convention for handling validation errors in this scenario. Of course, those inserts will be far from atomic, but it will certainly be a valuable option to have.

Based on this thread: https://groups.google.com/forum/#!topic/loopbackjs/CASU0BCDzS0

**Comment by chinookproject** [comment]
I had the same question (aka problem) that I don't wanted to create a separate POST request for something that should really be POSTed once. Basically like described in this thread: https://groups.google.com/forum/#!topic/loopbackjs/yqpTRkJMzpI

Seeing that this was asked 2 years ago I'm now wondering what the progress is for this feature? It's obviously not picked up yet. But what are the plans? Will this be released anytime soon?
