### ISSUE TITLE
Model should not implement the PersistedModel sharedCtor

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#511]
[This](https://github.com/strongloop/loopback/blob/master/lib/models/model.js#L122) is legacy from loopback 1.x. Instead this `sharedCtor` should be moded to `PersistedModel` and a more generic version should be added to `Model`.

**Comment by bajtos** [comment]
> This is legacy from loopback 1.x. Instead this sharedCtor should be moved to PersistedModel and a more generic version should be added to Model.

@ritch we haven't found time to make this change in the last 1.5 years, I am not sure if it is still relevant. Thoughts?
