### ISSUE TITLE
urlNotFound middleware outputs a full stacktrace?

### ISSUE THREAD

**Issue by HansHammel** [strongloop/loopback#514]
I don't know if this is because I updated my strongloop version, but the urlNotFound middleware gives me a full stacktrace on 404's, while it was just a single, nice coloured hint before? Am I mistaken? If this is intended, how to I  get a simple hint? Any configuration options? Thanks.

**Comment by zane-insta** [comment]
I am having this issue as well. I have tried disabling stack trace using 
NODE_ENV=production
and
disableStackTrace=true
but neither option seemed to disable the stacktrace.

**Comment by bajtos** [comment]
"urlNotFound" reports a regular error which is later processed in the same way as other errors. You can disable stack traces via `server/config.json`, see [Remoting Properties](http://docs.strongloop.com/display/LB/config.json?src=search#config.json-Remotingproperties) for more details.
