### ISSUE TITLE
No way to specify flags in search methods

### ISSUE THREAD

**Issue by daankets** [strongloop/loopback#515]
Currently doing a search like this:

`GET /someResource?filter[where][name][like]=regex`

Does not allow to specify any flags, like (for example) case insensitivity. I would like to suggest this solution:

`GET /someResource?filter[where][name][like/i]=regex`

This would allow us to use full regex features in searches.

**Comment by superkhau** [comment]
See The regexp operator has been implemented already (see https://docs.strongloop.com/display/public/LB/Where+filter). Closing.
