### ISSUE TITLE
Console message when running tests

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#518]
I believe the recent change regarding not having to attach a datasource, causes a message to log during testing: `The configuration of`MyTestModel`is missing`dataSource`property.
Use`null`or`false`to mark models not attached to any data source.`.

This might very well be intentional, but it's confusing.

**Comment by OwenBrotherwood** [comment]
Does this issue have any relation to https://github.com/strongloop/loopback/issues/1059 
I do not understand the issue :( 

possible "not bug"

**Comment by superkhau** [comment]
@fabien Do you know if this bug still exists? Can you submit a sample repo to reproduce if that is the case?
