### ISSUE TITLE
Where is native DB query

### ISSUE THREAD

**Issue by johnsoftek** [strongloop/loopback#521]
In Hacker News, https://news.ycombinator.com/item?id=7796196, it was said of Loopback:

> We allow you to execute native query using dataSource.connector.query(query, params, cb). We're considering to promote it to dataSource level and fully document it.

Is this feature available? Example?

**Comment by likun7981** [comment]
where is native query?

**Comment by biliboss** [comment]
@likun7981 you can try
`dataSource.connector.query(sql, params, cb);`

**Comment by likun7981** [comment]
@biliboss thx  ,I found it .
