### ISSUE TITLE
Multiple User child Models problem

### ISSUE THREAD

**Issue by glesage** [strongloop/loopback#527]
Hi All,

I've got 2 separate models that both inherit from the User model: Driver & Agent.
When I login with the first created user of each, the response I get is:

Agent/Login

```
{
  "id": "55EFKiN0ZtUGgh4mefU4s7DRM9KvyogV7dg14iQEjjD1tNSZK276HBZRVTCpGIFd",
  "ttl": 1209600,
  "created": "2014-09-02T19:02:27.411Z",
  "userId": 1
}
```

Driver/Login

```
{
  "id": "pL9qucXRAq9E6YKyAFRBMXc0K4FcTpFYQh9ZxqLN2p3DSDn9A6U3u3zDK57enEz9",
  "ttl": 1209600,
  "created": "2014-09-02T19:03:24.995Z",
  "userId": 1
}
```

Why is the "userId" always 1? It makes it impossible to trace back the user based on the token and such... also, once I log in a driver the agent that was logged in probably gets his accessToken overridden...

Please advise!

Thanks

**Comment by kukobumpero** [comment]
I'm also suffering with this right now... I'm new to loopback and expected to have "class table inheritance" as the default behaviour etc. It's quite hard for my head to accept that extending "person" into a "customer" generates two tables with **absolutely no connection**, independent id's and customer literally repeats all of person's properties/fields etc...

I guess I will have to do some "copy" and "paste" for business logic and work with relationships instead...

Any plans to implement "CTI" into the juggler?
