### ISSUE TITLE
user.js login include

### ISSUE THREAD

**Issue by Coobaha** [strongloop/loopback#528]
if we pass includes to [user.login](https://github.com/strongloop/loopback/blob/master/lib/models/user.js#L157) that don't have `toLowerCase` method - we will get unhandled error and crashed server.

for example `['Users', 'Posts']`

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by Coobaha** [comment]
@superkhau its already merged

**Comment by superkhau** [comment]
@Coobaha ty
