### ISSUE TITLE
Relation remote methods should not be defined using a resolver

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#533]
[This](https://github.com/strongloop/loopback/blob/master/lib/models/model.js#L209) means all relation remote methods will be defined every time `sharedClass.methods()` is called. I'd like to remove this and instead implement it in a hook that runs after the model is setup. This will make the list of `sharedClass.methods()` static and make things like `sharedClass.find(...).shared = false` work for all cases.

[Here is a proposal for that hook.](https://github.com/strongloop/loopback/pull/532)

**Comment by bajtos** [comment]
@ritch the link in the issue description is no longer valid :( I can also see that some work has been already done on this matter, see https://github.com/strongloop/loopback/issues/410#issuecomment-64675247. Is this proposal still relevant today?

**Comment by loay** [comment]
@ritch @bajtos 
Is this issue still valid or shall we close the issue?
Thanks.

**Comment by bajtos** [comment]
Since the issue was opened more than two years ago and there was very little discussion since then, I am closing it. @ritch feel free to reopen if you think this is still valid.
