### ISSUE TITLE
Where operators in PersistedModel.find()

### ISSUE THREAD

**Issue by ian-lewis-cs** [strongloop/loopback#535]
Hi,

I cannot find any information on how to filter by IS NULL.

http://docs.strongloop.com/display/LB/Where+filter#Wherefilter-Operators

Example:

```
SELECT foo 
FROM baz
WHERE  bar IS NULL
```

Any suggestions?

Many thanks,
Ian

**Comment by superkhau** [comment]
@ian-lewis-cs Has the issue been resolved? Can I close it?

Also, please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
