### ISSUE TITLE
hasAndBelongsToMany self-relation

### ISSUE THREAD

**Issue by epaminond** [strongloop/loopback#537]
Say I have Product model, which is supposed to have relatedProducts reference. I've tried to define it in this way:
```json
"relatedProducts": {
  "type":       "hasAndBelongsToMany",
  "model":      "Product",
  "foreignKey": "relatedProductId"
}
```
When adding new related product, loopback creates new joint-collection ProductProduct and adds there documents, that have reference only with one of products:
```json
{
  "_id" : ObjectId("5408889a61fa75aa5ff92614"),
  "productId" : ObjectId("5408872821e507bd5e64baae")
}
```

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
