### ISSUE TITLE
Validation for REST requests

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback#542]
How can I set up custom validation for each type of requests.

At this moment model supports global validation rules. But how can I define what rules to use depend on REST request.

For example 

I want to validate uniqueness of username on user creation and skip it on user update.

Or I want to be able to register user without password. But update user password call should execute password validation.

something like 
```
{
 'validationRules': {
  'password': ...
  'username': ...
  'name':...,
 'email':...
 },
 'validationRest': {
 'login': ['password', 'username'],
 'registration': ['email'],
 'upsert': ['password', 'name']
 }
}
```

Thanks

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
