### ISSUE TITLE
What are the correct perms for an $owner to create a model? 

### ISSUE THREAD

**Issue by frankcarey** [strongloop/loopback#546]
I want to do something that should be very common. I want Users to be able to create models that they own, and that can only be accessed and altered by them (the owners). I've been trying to create a model ACL that would permit this, but when I try to create a new model (which I set the userId to be the logged in user) the ACL (in debug) fails.

Any advice on settings this up?

Does the current isOwner not permit this common behavior? - IsOwner REQUIRES a modelID, so I'm guessing that it doesn't kick in for NEW models.. only for models that already exist, which makes sense if it's doing a findByID to look it up.

I figure I can do ALLOW on create method, but would that allow users to create models with an arbitrary owner? 

--Thanks

**Comment by superkhau** [comment]
@frankcarey Has the issue been resolved? Can I close it?

**Comment by bomattin** [comment]
@superkhau I'm not sure. This problem described in this issue still exists (at Loopback 2.19.1), but I'm not sure if the StrongLoop/Loopback team considers this 'working as intended'. To me, it seems absurd to do ownership checks only on ID-containing routes.

For example, if I have a Client which hasOne Profile, and I want a User to be able to make a new profile s/he owns:

* POST /Profiles will not check ownership
* POST /Client/:id/Profiles will check ownership, but only on Client, not profiles. This is...serviceable, but not great.
* POST /Users/:id/createProfile as a remote method, which I can get to do whatever I want, but seems hideously inefficient all things considered.

**Comment by superkhau** [comment]
@raymondfeng ^ Thoughts?

**Comment by superkhau** [comment]
@raymondfeng ^

**Comment by dancingshell** [comment]
+1
We have pilots (extended from User) that have many flights with the hasMany and belongsTo relationships defined. I would like to be able to call Flight.create() with $owner ACL defined and have flight creation be restricted to `flight.pilotId = current logged in userId`

currently, I have to define this restriction in a before save method hook

**Comment by ahmed-abdulmoniem** [comment]
Any news on the create method guys? @superkhau @raymondfeng

**Comment by superkhau** [comment]
No new from from me yet, I haven't had the bandwidth to look into it TBH. Let's bump it to a major for now so it gets considered during planning.

**Comment by ahmed-abdulmoniem** [comment]
Thanks

**Comment by TheBoroer** [comment]
Just like @dancingshell i'm using a before save hook to check if the authenticated user is creating a model with their own user ID (and not some other user's id).

Since this issue is still open, i'm guessing this still isn't in lb3? Is there a better way that I missed? Before save does the job, but just requires some extra code. 

Thanks!
