### ISSUE TITLE
Ready Event / Hooks

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#551]
We need a ready event to ensure all models have been setup and will not be changed. This can be used to get a snapshot of the app for the explorer and other hooks can be used to ensure modifications happen before the ready event.

See https://github.com/strongloop/loopback/pull/532

Related:

#410
strongloop/strong-remoting#94
https://github.com/strongloop/loopback/issues/477

**Comment by superkhau** [comment]
@ritch Is this still relevant?
