### ISSUE TITLE
Expose `PersistedModel.findOrCreate` via remoting

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#554]
- Add remoting metadata for the following `PersistedModel` methods:
  - `findOrCreate`
  - `findByIds`
- Describe these methods in the Confluence documentation
- Add them to the list of methods asserted in `test/model.test.js`

**Comment by richardpringle** [comment]
@bajtos, Is this still an issue?

**Comment by bajtos** [comment]
@richardpringle I don't know. Could you please take [loopback-example-app](https://github.com/strongloop/loopback-example-app), open the explorer and check if `findOrCreate` and `findByIds` are listed?

**Comment by richardpringle** [comment]
> @richardpringle I don't know. Could you please take loopback-example-app, open the explorer and check if findOrCreate and findByIds are listed?

@bajtos, they aren't

**Comment by bajtos** [comment]
@richardpringle then the answer to your original question, "Is this still an issue?", is pretty clear now :) Yes, this feature still needs to be implemented.
