### ISSUE TITLE
"embedsMany" cause problem with related model.

### ISSUE THREAD

**Issue by veekungx** [strongloop/loopback#556]
It ever worked when I used loopback below 2.8.9.
Is this feature gone in 2.9.1?

``` javascript
"addresses" : {
          "type" : "embedsMany",
          "model" : "Address",
          "options": {
              "validate": true,
              "autoId": true
          }
      }
```

**Comment by brunocascio** [comment]
I have same problem:

Ref to question: https://github.com/strongloop/loopback-datasource-juggler/issues/336#issuecomment-76734453

**Comment by mailuser41** [comment]
Yes it is still a bug.

**Comment by james-gardner** [comment]
@veekungx Can this be re-opened? I am still seeing this issue.
