### ISSUE TITLE
User cannot register if registration email lost or not sent

### ISSUE THREAD

**Issue by johnsoftek** [strongloop/loopback#561]
Email verification of a new user upon registration is documented at http://docs.strongloop.com/display/LB/Using+built-in+models#Usingbuilt-inmodels-Verifyingemailaddresses.

This technique works well but there is a problem if the registration email fails to be sent or the user loses the email or the user does not verify the email by following the link before the verification token expires. If the user attempts to register again, a 422 error is returned: user already exists. But there is no mechanism to request another verification email.

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

@bajtos @raymondfeng @ritch PTAL
