### ISSUE TITLE
Suppress stack traces from `loopback.errorHandler` output in production

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#564]
strong-remoting was recently fixed to exclude the stack trace from the error response when `process.env.NODE_ENV === 'development'`.

However, `loopback.errorHandler` used by the scaffolded `server/server.js` does not support this feature.

We should modify `loopback.errorHandler` to return middleware that does not print stack traces when running in production.

**Comment by chinuy** [comment]
Is there any timeline you want to put this implemented?

**Comment by bajtos** [comment]
Not really. Would you mind contributing this feature yourself?

**Comment by pasindud** [comment]
shouldn't this be set by a config.json ? or any other flag

**Comment by bajtos** [comment]
> shouldn't this be set by a config.json ? or any other flag

Now that the error-handling middleware is configured in `server/middleware.json`, it should be reasonably easy to modify the handler factory to accept an `options` argument which would specify the behaviour.

**Comment by digitalsadhu** [comment]
So looking around a bit, I understand that express errorhandler is for development only and provides no options for disabling stack traces. It looks to me that 1 idea might be to wrap express errorhandler to either return the errorhandler middleware if we are not in production or to provide a custom piece of errorhandler middleware (without stack traces) if we are. Does that sound like the right approach @bajtos ?
