### ISSUE TITLE
Why can't i use Token Access to request /Users

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#567]
Hello everybody,

I'm new commer in loopback, so i want to use Token Access to request API, anyone can tell me step to do this on my app. Thanks a lot.

Currrently i have done some step like below but i can't use Token:
1- POST new User (username, password) 
2- POST login User (with username, password is created in 1) i can get Token here.
3- Copy Token in 2 and set in Explorer screen
4- GET Users with Token 2 but it shows error messages Authorise Required

{
  "error": {
    "name": "Error",
    "status": 401,
    "message": "Authorization Required",
    "statusCode": 401,
    "stack": "Error: Authorization Required\n    at /var/www/nodejs/api/node_modules/loopback/lib/application.js:338:21\n    at /var/www/nodejs/api/node_modules/loopback/lib/models/model.js:292:5\n    at /var/www/nodejs/api/node_modules/loopback/lib/models/acl.js:443:19\n    at /var/www/nodejs/api/node_modules/loopback/node_modules/async/lib/async.js:254:17\n    at done (/var/www/nodejs/api/node_modules/loopback/node_modules/async/lib/async.js:135:19)\n    at /var/www/nodejs/api/node_modules/loopback/node_modules/async/lib/async.js:32:16\n    at /var/www/nodejs/api/node_modules/loopback/node_modules/async/lib/async.js:251:21\n    at /var/www/nodejs/api/node_modules/loopback/node_modules/async/lib/async.js:575:34\n    at /var/www/nodejs/api/node_modules/loopback/lib/models/acl.js:426:15\n    at /var/www/nodejs/api/node_modules/loopback/lib/models/role.js:308:17"
  }
}

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
