### ISSUE TITLE
BUG GET \parents\{pk}\children\count on embedsMany and referencesMany

### ISSUE THREAD

**Issue by veekungx** [strongloop/loopback#568]
when declared relation like this

```
{
     name : "Parent"
     relations: {
        "type": "embedsMany",
      "model": "Child"
     }
}
```

then call
**GET /parents/{pk}/children/count**

It count on **Child collection** instead of **sub-document**

**Comment by barocsi** [comment]
+1

**Comment by MarkAndrewJohnson** [comment]
It appears we have now encocuntered the same issue with ReferencesMany

**Comment by MarkAndrewJohnson** [comment]
@fabien would you now have a resolution for this issue?

**Comment by pierreclr** [comment]
We encounter the same issue on loopback 2.22, any progress on a possible fix ?

**Comment by Fercho191** [comment]
I have the same problem, I try and write something right ring but I can not function that I write in the script of the model.

**Comment by rashmihunt** [comment]
Adding P1 as many community members are reporting in multiple areas - embedsMany, ReferencesMany.

**Comment by dhmlau** [comment]
@fabien , saw you assigned it to yourself.  Are you planning to submit a PR?

**Comment by fabien** [comment]
@dhmlau it's been since 2014 - still working with Loopback, but unable to set aside time for a PR right now.

**Comment by kjdelisle** [comment]
There have been recent changes to how count is returned in some connectors; if you can provide an example repository in GitHub to demonstrate the issue, we can revisit it but at this time this is not a priority for us.
