### ISSUE TITLE
How to get current authenticated user

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback#569]
In requeest I have valid access token so user available in beforeRemote as part of ctx

But how can I get userId from inside of function.  For example:

model.js

```
var loopback = require('loopback');

module.exports = function(someModel) {

someModel.getUserId = function(callback) {
    // ??? How ???
    var userId = loopback.request.getUserId();
};
```

spent 3 hours on it and can't find easy solution... Basically how can I get user ID from any place in the code?

**Comment by bajtos** [comment]
> It seems like I want to retrieve loopback.getCurrentContext() in remote method and this would fail. Nevertheless, this works with model hook.

It's quite hard to help you without seeing the code you are running. If you are using MongoDB, then you may be affected by the following bug: #809.

**Comment by drmikecrowe** [comment]
For those coming on this thread later, I managed to get the req context using the remoteMethod() arguments:

```js
...
accepts: [
        {arg:"req", type:"Object", required: true, http: function(ctx) { return ctx.req; }},
...

Model.myfun = function(req, cb) {
}
```

**Comment by danmo** [comment]
This one does it for me:

    var loopback = require('loopback');
    var user = loopback.getCurrentContext().get('currentUser');

**Comment by rhymn** [comment]
@danmo Sw33t, this works for me. Thank you

**Comment by rhymn** [comment]
LoopBack is really amazing!

**Comment by ekussberg** [comment]
I have tested it like this:

```
var loopback = require('loopback');
    var lctx = loopback.getCurrentContext();
    var userId = lctx.active.http.req.accessToken.userId;
    console.log(userId);

    var loopback = require('loopback');
    var user = loopback.getCurrentContext().get('currentUser');
    console.log(user);
```

Output is following: user - undefined. 

```
"loopback": "^2.16.3",
    "loopback-boot": "^2.4.0",
    "loopback-component-passport": "^1.3.0",
    "loopback-component-storage": "^1.4.0",
    "loopback-connector-mongodb": "^1.8.0",
    "loopback-datasource-juggler": "^2.25.1",
    "loopback-explorer": "^1.7.2",
```

**Comment by bajtos** [comment]
> I have tested it like this:
> (...)
> Output is following: user - undefined. 
> (...)

@ekussberg Please open a new GH issue and provide a sample app reproducing the problem per [Wiki instructions](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

**Comment by ekussberg** [comment]
@bajtos this is the example of code i used:
```
ShoppingCart.getSessionCart = function (cb) {
    // Get the current session
    var lctx = loopback.getCurrentContext();
    var request = lctx.active.http.req;
    var ipAddress = request.connection.remoteAddress;
    var sessionID = request.sessionID;

    console.log("Get session cart!");
    console.log('From ip address: ', ipAddress);
    console.log('For session: ', sessionID);

  };

  ShoppingCart.remoteMethod(
    'getSessionCart',
    {
      description: "Function used to retrieve the cart for the session",
      returns: {type: 'Object', root: true},
      http: {verb: 'get'}
    }
  );
```

**Comment by ppbntl19** [comment]
following -http://docs.strongloop.com/display/public/LB/Using+current+context
     
      var loopback = require('loopback');
      var user = loopback.getCurrentContext().get('currentUser');     
     console.user(user);
output- undefined

    "loopback-boot": "^2.6.5",
    "loopback-connector-mongodb": "^1.11.3",
    "loopback-datasource-juggler": "^2.33.1",
    "serve-favicon": "^2.0.1"

**Comment by pulkitsinghal** [comment]
@ppbntl19 - please join https://gitter.im/strongloop/loopback to get quick answers on already closed issues

**Comment by joe-at-startupmedia** [comment]
I am having issues with this implementation using the following:

server/server.js

```
app.use(loopback.context());
app.use(loopback.token());
app.use(function (req, res, next) {

  accessToken = req.query.access_token || false;
  if (!accessToken) return next();
  var loopbackContext = loopback.getCurrentContext();
  if (loopbackContext) {
    loopbackContext.set('accessToken', accessToken);
    console.log(loopbackContext);
    next();
  }
});
```
redemption.js
```
var loopback = require('loopback');
module.exports = function(Redemption) {

  Redemption.updateSubscriberSavings = function(params, callback) {
    redemption = params.redemption;
    var ctx = loopback.getCurrentContext();
    var accessToken = ctx && ctx.get('accessToken') || {};
    console.log(ctx);
 ...
```
server.js output:

```
{ name: 'loopback',
  active: { accessToken: 'XU2WDH02ApOHqqFkYeHguoWm9q0x3KtfoJ7YpgrLvNvI3kYvReDFVkEYofwqrETD' },
  _set: [ null ],
  id:
   { create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
```
model output:
```
 { name: 'loopback',
  active: {},
  _set: [ null ],
  id:
   { create: [Function],
     flags: 15,
     before: [Function],
     after: [Function],
     error: [Function],
     uid: 2,
     data: null } }
```

**Comment by superkhau** [comment]
@joe-at-startupmedia As stated by @pulkitsinghal, please join https://gitter.im/strongloop/loopback to get quick answers on already closed issues.

**Comment by psi-4ward** [comment]
Ive the same issue

**Comment by Sandy1088** [comment]
This is how I've implemented it 
app.start = function() {
  // start the web server
  return app.listen(function() {
    app.emit('started');
    var baseUrl = app.get('url').replace(/\/$/, '');
    console.log('Web server listening at: %s', baseUrl);
    if (app.get('loopback-component-explorer')) {
      var explorerPath = app.get('loopback-component-explorer').mountPath;
      console.log('Browse your REST API at %s%s', baseUrl, explorerPath);
    }
  });
};

app.use(loopback.context());
app.use(loopback.token());
app.use(function setCurrentUser(req, res, next) {
  if (!req.accessToken) {
    return next();
  }
  app.models.User.findById(req.accessToken.userId, function(err, user) {
    if (err) {
      return next(err);
    }
    if (!user) {
      return next(new Error('No user with this access token was found.'));
    }
    var loopbackContext = loopback.getCurrentContext();
    if (loopbackContext) {
      loopbackContext.set('currentUser', user);
    }
    next();
  });
});


However i keep getting the currentUser as null,

**Comment by Sandy1088** [comment]
This seems like an unresolved bug.....or maybe I'm doing something horribly wrong!!!!

**Comment by drish** [comment]
@drmikecrowe best solution IMHO, :+1: for that.

**Comment by drish** [comment]
@drmikecrowe solution resolves what was asked in this issue.

**Comment by raymondfeng** [comment]
To receive the http context, there are potentially two options (assuming there is no reliable way to retrieve the current context associated with the invocation chain):

1. Via the parameter injection. What @drmikecrowe proposes supports that.

2. Via the model class injection. You can get it using `this.context`.One of the limitation is that the model class is a singleton. We can relax that by supporting a setting so that we can create new (subclassing) or reuse pooled classes of the model as the receiver. That will allow the runtime to inject context into the class object itself and remote methods can access it via `this.context`.

**Comment by Sandy1088** [comment]
loopback.getCurrentContext() returns null in boot script itself...

**Comment by johannesjo** [comment]
Could someone please explain me @drmikecrowe method? I'm really not sure where the whole 'accepts' part should go.

**Comment by drmikecrowe** [comment]
@johannesjo -- I added the current user to the current context in server/server.js like @Sandy1088 above:

	app.use(function setCurrentUser(req, res, next) {
		if (!req.accessToken) {
			return next();
		}
		app.models.User.findById(req.accessToken.userId, function(err, user) {
			if (err) {
				return next(err);
			}
			if (!user) {
				return next(new Error('No user with this access token was found.'));
			}
			var loopbackContext = loopback.getCurrentContext();
			if (loopbackContext) {
				req.accessToken.currentUser = user;
				loopbackContext.set('currentUser', user);
			}
			next();
		});
	});

My other solution was in remote methods:


	user.remoteMethod('methodName', {
			accepts: [
				{arg: 'req', type: 'object', required: true, http: {source: 'req'}}
			],
			returns: {arg: 'user', type: 'object', root: true},
			http:    {verb: 'post', path: '/methodName'}
		}
	);


	user.methodName = Bluebird.promisify(function methodName(req, cb) {
		var context            = loopback.getCurrentContext();
		var currentUser        = req.accessToken && req.accessToken.currentUser || context && context.get('currentUser');
		// .....
	});

**Comment by johannesjo** [comment]
@drmikecrow thank you very much for explaining!

**Comment by Mad-Head** [comment]
someModel.getUserId = function(id, cb) {
        cb(null, id);
    };

    someModel.getUserId(
        'getClientUser',
        {
            accepts: {arg: 'id', type: 'string'},
            returns: {arg: 'User', type: 'array'},
            http: {verb: 'get'}
        }
    );

    someModel.beforeRemote('getUserId', function (context, unused, next) {
        var req = context.req;

        req.remotingContext.args.id = req.accessToken.userId;

        next();
    });

**Comment by mariohmol** [comment]
I'm having this problem when owner has the same id.. in example a user may want to update the profile data... so i check if the user.id in update is the same in accesstoken

>     user.beforeRemote('upsert', function (context, model, next) {
> 	    var req = context.req;
> 	    var userobject = context.req.body;
> 	    var userID = req.accessToken.userId;
> 	    if(userobject && userobject._id!=null && userobject._id!=req.accessToken.userId){
> 	    	var error = new Error();
> 			error.statusCode = 401;
> 			error.message = 'Authorization Required';
> 			error.code = 'AUTHORIZATION_REQUIRED';
> 			next(error);
> 	    } else next();
> 	   });

**Comment by SamuelBonilla** [comment]
The solution for get current authenticated user:  

var loopback = require('loopback');
module.exports = function(Model) {    
    Model.observe('before save', function(ctx, next) {
        if (ctx.instance) {
            var ctxs = loopback.getCurrentContext();
            ctx.instance.date = new Date();
            ctx.instance.id_user = ctxs.active.accessToken["userId"];
            console.log('currentUser.infotmation: ', ctxs.active.accessToken);
        } else {
        }
        next();
    });
};

// Console output for ctxs.active.accessToken

{ id: 'vcrl8INUAk99MCbTHPB8zA9fuR0gDCLGi0f4DbqYvAIoMOLPVrc4PVYuWDJLUJGv',
  ttl: 1209600,
  created: Tue Jun 14 2016 23:48:08 GMT+0000 (UTC),
  userId: 13 }

**Comment by renanwilliam** [comment]
@SamuelBonilla do you have to set any other param in server.js? I have exactly the same code and it's returning null

**Comment by SamuelBonilla** [comment]
@renanwilliam I don't have other code in serrver.js. getCurrentContext() return null when the user is not authenticated you need to pass the accessToken to the api endponint

**Comment by chinuy** [comment]
maybe 'downgrade' your nodejs to v0.12 and see if the issue existed. You may refer this discussion:
https://github.com/strongloop/loopback/issues/878#issuecomment-215673421

**Comment by jankcat** [comment]
For those looking for a solution to finding out the authenticated user in a remote method (now that currentContext is deprecated), the groundwork is laid out at the following link: https://docs.strongloop.com/display/public/LB/Remote+methods#Remotemethods-HTTPmappingofinputarguments

Here is my example snippet:
```js
  MyObject.remoteMethod(
    'myMethod',
    {
      http: {path: '/myMethod', verb: 'get'},
      accepts: [
        {arg: 'someArgument', type: 'string'},
        {
          arg: 'accessToken',
          type: 'object',
          http: function(ctx) {
            return ctx.req.accessToken;
          }
        }
        ],
      returns: {arg: 'someResponse', type: 'string'}
    }
  );
  MyObject.myMethod = function(someArgument, accessToken, cb) {
    // ...
	// accessToken.userId
	// ...
    cb(null, "Response blah blah...");
  }
```

**Comment by yagobski** [comment]
Any other solution to get current connected user inside the model?

**Comment by ataft** [comment]
@jankcat Thanks, this example worked perfectly! Exactly what I was looking for after reading too many pages of back and forth on the issue. I couldn't figure this out from the current 3.0 documentation, so I created a pull request to add your example to the documentation.

**Comment by bajtos** [comment]
@ataft thank you for the pull request to improve our documentation!

As I commented there, while the example shown in this issue is a valid one, it is also using a different approach than we implemented for context propagation.

Here is a better example:

```js
// common/models/my-model.js
module.exports = function(MyModel) {
  MyModel.log = function(messageId, options) {
    const Message = this.app.models.Message;
    return Message.findById(messageId, options)
      .then(msg => {
        const userId = options && options.accessToken && options.accessToken.userId;
        const user = userId ? 'user#' + userId : '<anonymous>';
        console.log('(%s) %s', user, msg.text));
      });
  };

// common/models/my-model.json
{
  "name": "MyModel",
  // ...
  "methods": {
    "log": {
      "accepts": [
        {"arg": "messageId", "type": "number", "required": true},
        {"arg": "options", "type": "object", "http": "optionsFromRequest"}
      ],
      "http": {"verb": "POST", "path": "/log/:messageId"}
    }
  }
}
```

**Comment by jmwohl** [comment]
I'm probably misunderstanding something here, as I'm pretty new to Loopback. But do the examples above imply that _every_ model method that needs access to the authenticated user must implement this explicitly? This seems like a lot of overhead for an extremely common situation. Is there any way to just make the authenticated user, if it exists, available in ALL remote methods?

**Comment by bajtos** [comment]
> I'm probably misunderstanding something here, as I'm pretty new to Loopback. But do the examples above imply that every model method that needs access to the authenticated user must implement this explicitly?

Yes, that's correct - see http://loopback.io/doc/en/lb3/Using-current-context.html

> This seems like a lot of overhead for an extremely common situation. Is there any way to just make the authenticated user, if it exists, available in ALL remote methods?

We tried to use continuation-local-storage as a Node.js replacement for ThreadLocalStorage, unfortunately it turned out there is no reliable implementation of CLS available in Node.js land :(

The solution based on "options" argument is the only robust and reliable approach we have found. However, if you can find a better way, then please let us know!

**Comment by jmwohl** [comment]
@bajtos Ok, thanks. 

I haven't looked under the hood, so not sure how complicated it would be to implement, but one thought would be to offer a setting at the model level that populates the options from request automatically for all methods. It just seems like such a common need — I can't remember ever working on an app where I _didn't_ need access to the user in the controllers (remote methods, in this case). Maybe something like:

```javascript
// common/models/my-model.json
{
  "name": "MyModel",
  "includeOptionsFromRequest": true,
  ...
}
```

**Comment by barocsi** [comment]
Coming from 2.x + current context I am not able to port this implementation to the following cases, and the documentations concept is soo confusing...
options object
optionsFromRequest (that is converted) what? Really? What about options not coming from a request but from an internal test run?

.getCurrentContext
.runInContext (for testing)
.set('xx',value)

the example about getting current user
```
// common/models/my-model.js
module.exports = function(MyModel) {
  MyModel.observe('access', function(ctx, next) {
    const token = ctx.options && ctx.options.accessToken;
    const userId = token && token.userId;
    const user = userId ? 'user#' + userId : '<anonymous>';

    const modelName = ctx.Model.modelName;
    const scope = ctx.where ? JSON.stringify(ctx.where) : '<all records>';
    console.log('%s: %s accessed %s:%s', new Date(), user, modelName, scope);
    next();
  });
};
``
 is not in relation with
2.x middleware, it does not even return current user object but some token and thats it,
```
  server.middleware('auth', loopback.token({
                                             model: server.models.accessToken,
                                             currentUserLiteral: 'me'
                                           }));
```

according to #569 is not acceptable since all framework has this very basic foundation to simply have a shorthand for accessing the current user.

Is there an example of middleware or component for 3.x so we can simply, by using options can retrieve currentUser reference? I mean in a large app there are hundreds of remote methods, shall we need to rewrite all of them? I'm sure there is a better way other than messing up the community with bad design and another bad design.

**Comment by bajtos** [comment]
@barocsi I am afraid I don't understand very well your comment. I'll try to answer as best as I can.

> What about options not coming from a request but from an internal test run?

```
.getCurrentContext
.runInContext (for testing)
.set('xx',value)
```

When you are invoking a method from code (e.g. in a test), you need to build and pass the `options` object explicitly. For example:

```js
it('does something with current user', function() {
  return User.login(CREDENTIALS)
    .then(token => {
      const options = {accessToken: token};
      return MyModel.customMethod(someArgs, options);
    })
    .then(result => {
      // verify customMethod worked as expected
    });
```

> it does not even return current user object but some token

The `options` value contain the same token as set by LoopBack 2.x. You can retrieve the current user e.g. by calling `options.accessToken.user()` method.

>  I mean in a large app there are hundreds of remote methods, shall we need to rewrite all of them?

Yes, all remote methods that want to access current context must be modified to accept `options` argument.

The lack of a solution for ThreadLocalStorage is a limitation of Node.js platform. There is some work in progress on this front, but it's still far from getting into a state where it could be used in production. I am highly encouraging you to get involved in the discussion and work in Node.js core, here are few links to get you started:

 - https://github.com/nodejs/node-eps/pull/18
 - https://github.com/nodejs/diagnostics/issues/29
 - and https://www.npmjs.com/search?q=cls-hooked which is using the new API in development

**Comment by gdeckert** [comment]
@bajtos - thank you for this information. Two points that aren't entirely clear - 

1) to make use of options, will I need to migrate from LoopBack 2.x to LoopBack 3.0?

2) Are only operation hooks affected by this issue ('before save', 'after save', etc), or are all remote methods subject to continuation passing issues?  (i.e. would I have to update every place where I'm currently referencing req.accessToken?)

**Comment by bajtos** [comment]
@gdeckert 

> to make use of options, will I need to migrate from LoopBack 2.x to LoopBack 3.0?

You can pass context via options in LoopBack 2.x as long as you enable this feature, see http://loopback.io/doc/en/lb3/Using-current-context.html#annotate-options-parameter-in-remoting-metadata:

_In LoopBack 2.x, this feature is disabled by default for compatibility reasons. To enable, add "injectOptionsFromRemoteContext": true to your model JSON file._

> Are only operation hooks affected by this issue ('before save', 'after save', etc), or are all remote methods subject to continuation passing issues? (i.e. would I have to update every place where I'm currently referencing req.accessToken?)

I think the code which can access `accessToken` directly via the incoming`req` object should not need any changes. You _can_ upgrade it to use `options.accessToken` instead of `req.accessToken`, but it shouldn't be required.  I use "should" because it's hard to tell for me without seeing your code.

**Comment by antarasi** [comment]
Elegant way of getting userId from acccessToken by request object in remote method:
```JavaScript
  MyModel.register = function(req, param, cb) {
    var userId = req.accessToken.userId;

    console.log(userId); 
    cb(null, ...);
  };

  MyModel.remoteMethod(
    'register',
    {
      accepts: [
        { arg: 'req', type: 'object', http: {source: 'req'} }, // <----
        { arg: 'param', type: 'string', required: true },
      ]
    }
```
