### ISSUE TITLE
How to validate GeoPoint-type property

### ISSUE THREAD

**Issue by projectxmaker** [strongloop/loopback#571]
Hi,

I'm trying to use custom validation for a GeoPoint-type property, but it's always validated by validation defined by built-in geopoint type.

Specfically, in my model I define a property like below

```html
    "location": {
      "type": "geopoint"
    },
```

I tried to implement a validation for 'location' property in MyModel.setup() as below:

```html
    // location
    function validateLocation(err) {
      // The latitude point in degrees. Range: -90 to 90.
      // The longitude point in degrees. Range: -90 to 90.
      if (this.location) {
        var abc = this.location.toString();
        var values = abc.split(",");
        if (values.length == 2 
            && validator.isNumeric(values[0]) 
            && validator.isNumeric(values[1])
            && values[0] >= -90 && values[0] <= 90
            && values[1] >= -90 && values[0] <= 90)
        {
          // fine
        }else {
          err();
        }
      }
    }
    MyModel.validate('location', validateLocation, {message: 'Invalid Location'});
```

submitted info for 'location' is "abc,ccc"

built-in validation of geopoint always is executed before the validation I did setup in MyModel.setup() and throw error in terminal like below 

```html
AssertionError: lat must be a number when creating a GeoPoint
```

----
if I applied incorrect validation approach, thanks for any help :(

**Comment by bajtos** [comment]
> I'm trying to use custom validation for a GeoPoint-type property, but it's always validated by validation defined by built-in geopoint type.

@projectxmaker @raymondfeng is this issue still relevant?

**Comment by loay** [comment]
Closing this issue in favor of this: https://github.com/strongloop/loopback-datasource-juggler/issues/103
