### ISSUE TITLE
LoopBack Email Model: SMTPConnection._formatError

### ISSUE THREAD

**Issue by dashby3000** [strongloop/loopback#572]
I have created a model named `email`, it uses the LoopBack built-in model `Email` as a base.  I added a custom method to the model `email` called sendEmail.  The sendEmail function looks like this:

email.sendEmail = function(msg, cb) {
    this.send(JSON.parse(msg), function(err, mail) {
        if (err != null) { return cb(err, null); }
        return cb(null, {
            status: 'email sent'
        });
    });
};

I test the call out using Explorer by sending the following message:

{"to": "dennis@strongloop.com", "cc" : "dennis.ashby@strongloop.com", "from": "dennis.ashby@ebrainiacs.com", "subject": "Email from StrongLoop!", "text": "Sent from LoopBack on my laptop! I will send code over this morning.", "html": "Sent from <em>LoopBack</em> on my laptop! I will send code over this morning."}

I get this response:

{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Greeting never received",
    "code": "ETIMEDOUT",
    "stack": "Error: Greeting never received\n    at SMTPConnection._formatError (/Users/dashby/workarea/StrongLoop2.0/MailDemoAPI/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:361:15)\n    at SMTPConnection.<anonymous> (/Users/dashby/workarea/StrongLoop2.0/MailDemoAPI/node_modules/loopback/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:301:37)\n    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)"
  }
} 	

Similar code used to work in LB1.0.  I can manually connect to the the SMTP server using Telnet, so I do not believe it is a connectivity issue.

**Comment by JoshElias** [comment]
I'm also having this problem. Have you found a solution yet?

**Comment by akoren** [comment]
Any solution? the email connector doesn't seem to be working.

**Comment by raymondfeng** [comment]
What is your email connector setting?

**Comment by akoren** [comment]
Here it is:

    "Email": {
		"name": "mail",
		"defaultForType": "mail",
		"connector": "mail",
		"transports": [
		  {
			"type": "SMTP",
			"host": "smtp.gmail.com",
			"secureConnection": true,
			"port": 465,
			"auth": {
			  "user": "name@gmail.com",
			  "pass": "pass"
			}
		  }
		]
      }

**Comment by raymondfeng** [comment]
Do you want to try?

```
"Email": {
    "name": "mail",
    "defaultForType": "mail",
    "connector": "mail",
    "transports": [
      {
        "type": "SMTP",
        "host": "smtp.gmail.com",
        "secure": true,
        "port": 465,
        "auth": {
          "user": "name@gmail.com",
          "pass": "pass"
        }
      }
    ]
  }
```

**Comment by akoren** [comment]
Yes :) changing from 'secureConnection' to 'secure' did the trick (also changing to port 587 works), however in order for that to actually work, I had to turn on the "access for less secure apps" option on the gmail side, otherwise the response would be:

    { [Error: Invalid login]
      code: 'EAUTH',
      response: '534-5.7.14 
     Please log in via your web browser and then try again.  Learn more at      https://support.google.com/mail/answer/78754 v8sm25207797wjr.15 - gsmtp',
      responseCode: 534 }

Is there a formal way to keep the account secure?

Thanks

**Comment by raymondfeng** [comment]
Please follow the instruction at https://github.com/andris9/Nodemailer#using-gmail.

**Comment by raymondfeng** [comment]
@crandmck We probably should document this.

**Comment by crandmck** [comment]
Added http://docs.strongloop.com/display/LB/Email+connector#Emailconnector-UsingGMail.
