### ISSUE TITLE
It's still possible create relation Objects of User when logged User was deleted.

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#580]
When i'm using Explorer to test ACLs i see this case:
It's still possible create relation Objects of User when logged User was deleted.
Case:
- User has many Books (userId)
- Books belong to User (userId)

Step like below:
- Create User
- Login User
- Delete logged User (in case still logged - Token is set)
- Create Book (in case still logged - Token is set) - It's still can do this why ?

I don't know why when deleting User, you don't delete AccessToken so when i create Book it can use userId of Token to create Book but User of userId is not available. ?

**Comment by bajtos** [comment]
@loay please back-port the fix to 2.x, the issue is not "done" until then.

**Comment by loay** [comment]
- [ ] Fix security issue: https://github.com/strongloop/loopback/pull/2492
- [ ] backport: https://github.com/strongloop/loopback/pull/2540
-  [ ] address issue concerning test case.
- [ ] backport after fixing test cases.
