### ISSUE TITLE
how can i create tables User, AccessToken, ACL, RoleMapping, ROLE,... in Mysql

### ISSUE THREAD

**Issue by yagobski** [strongloop/loopback#591]
I want to use MySQL to manage Users. By default Loopback use DB dataSource. I have installed MySQL connector and all my custom models works good with mysql when i change datasource. 

I want to use Mysql for Users model too. Do you have sql file with all schema for Users model?
Or there is automatic command can generate for me User, AccessToken, ACL, RoleMapping, ROLE,... tables.

Thanks

**Comment by nivincp** [comment]
Can we customise the table names for built in models? For example I'd like to name the built in User model as users in my mysql database and AccessToken as access_tokens. I understand it can be done for custom models using model.json. Just wondering how to do it with built in models?

**Comment by charlie-s** [comment]
@nivincp Seems to me that the only way to customize the name is to redefine the model. Hoping for another method.

**Comment by danielmihai** [comment]
How do you create the default loopback model acls, roles, rolemapping etc. ? 

after using loopback autoupdate to create the array of default models, the values for User acls in the acls table were not created, in fact, only the model tables (with fields) were created, but no properties of the model were persisted (like acls). 

How can I achieve that?

**Comment by ninoguba** [comment]
I'm experiencing the same thing as @danielmihai described.  I can see the User, Role, RoleMapping tables on my mongodb datasource but the ACL, and AccessToken are not "migrated".  Anybody figured this out?

**Comment by danielmihai** [comment]
I made a boot script which does this on app startup. Take a look at the boot scripts in my loopback prototype repo if you'd like. I had to extend the basic User etc. models. Kind of ugly and imo defeats the scope of loopback

**Comment by ninoguba** [comment]
Thanks @danielmihai your boot scripts gave me some ideas but I ended up just leaving ACL and AccessTokens in memory while the rest connected to a sql datasource.  Works great so far.  Do you guys see any issues with this approach?

**Comment by nivincp** [comment]
Probably it'll clear the data inside these tables if it's configured in memory after a script restart.

**Comment by ninoguba** [comment]
Since the ACL and AccessTokens are in memory, I believe they are already automatically reset after every script restart.

**Comment by vkachan** [comment]
Started playing with Loopback and MySQL database and found that automigrate/autoupdate doesn't create **relations** between tables as well as ACL records for my models. I'm just wondering has anyone solved that somehow? I don't want to put this into the boot script as this makes usage of the relation generator and ACL generators kinda needless.

**Comment by danielmihai** [comment]
I did it like that. 

Daniel M. Colceag

**Comment by vkachan** [comment]
@danielmihai, I dived deep into the code of **loopback-connector-mysql** and I found that logic does not exist there, only creation of the tables. Thereby it seem like creation of the fk's and ACL records is manual job :(

**Comment by Vandivier** [comment]
I'm having this issue in loopback 3. I'm reviewing Daniel's solution but at first glance the API is loopback 2 (app.models(), etc) and it's postgresql.

Here's what I'm seeing and here's the [repro](https://github.com/Vandivier/ella-api/tree/repro-automigrate-native-model).

![image](https://user-images.githubusercontent.com/5559355/34647391-97bd7d10-f34f-11e7-984e-2bfeed60e51a.png)

The below code is my automigrate.js in /boot:

    module.exports = async function (app) {
    const oEllaDB = app.dataSources.EllaDB;
    const Item = app.models.Item;
    const EllaUser = app.models.EllaUser;

    const oEllaUserJohn = { // for testing/developing only. remove before production.
        'password': '1234', // #amyschumerbelike
        'role-name': 'developer', // TODO: autogenerate
        'username': 'john'
    }

    oEllaDB.automigrate(['User', 'Application', 'Role', 'ACL', 'RoleMapping', 'AccessToken'], function(){}); // ref: https://github.com/strongloop/loopback/issues/591

    // first autoupdate the `EllaUser` model to avoid foreign key constraint failure
    oEllaDB.automigrate('EllaUser', function (err) {
        if (err) throw err;

        EllaUser.create(oEllaUserJohn);

        console.log('\nAutomigrated table `EllaUser`.');

        oEllaDB.automigrate('Item', function (err) {
            if (err) throw err;
            console.log('\nAutomigrated table `Item`.');
            // at this point the database table `Item` should have foreign key `userId` or `ellaUserId`
        });
    });
    };

**Comment by andrewpaulino** [comment]
Has any solutions came up, or are going to have to manually recreate all the tables with our SQL DB. I am assuming the reason I can't login is because mySQL DB has no reference to the accessTokens?

**Comment by yongqiangyue** [comment]
app.dataSources.mysqlDs.automigrate(['User', 'Application', 'Role', 'ACL',
        'RoleMapping', 'AccessToken'], function(err) {
        if (err) throw err; // must have
    });
