### ISSUE TITLE
Not being able to expose ACL API in a satisfactory way...

### ISSUE THREAD

**Issue by Acaspita** [strongloop/loopback#592]
Hi guys,

I'm exposing ACL API and I'm not getting Access controls model configurations (Not one registry). Should this be the right working.

Later, I've added the "options" entry to acl in model-config.json:

```
"acl": {
    "public": true,
    "options": {
      "base": "ACL"
    },
    "dataSource": "db"
  },
```

But I'm getting the following error when running node server/server.js:

```
  C:\Users\Acaspita\Documents\MyApp\node_modules\loopback-boot\lib\compiler.js:84
  throw new Error(
        ^
  Error: The data in model-config.json is in the unsupported 1.x format.
  at assertIsValidModelConfig (C:\Users\Acaspita\Documents\MyApp\node_modules\loopback-boot\lib\compiler.js:84:13)
  at compile (C:\Users\Acaspita\Documents\MyApp\node_modules\loopback-boot\lib\compiler.js:37:3)
```

Moreover, I've added the options/base attribute to common/models/acl.json, besides an ALLOW permission to a working role I've defined, but I get another error:

```
C:\Users\Acaspita\Documents\MyApp\node_modules\loopback-boot\node_modules\toposort\index.js:29
      throw new Error('Cyclic dependency: '+JSON.stringify(node))
            ^
Error: Cyclic dependency: "ACL"
    at visit (C:\Users\Acaspita\Documents\MyApp\node_modules\loopback-boot\node_modules\toposort\index.js:29:13)
```

 Then, I remove common/models/acl.json file, and I get access to it at /explorer..., but isn't it a security thread to led this model open to access? I'm not being able to limit access to only a role for a particular already working role.

Is it possible to control model ACLs through API, asigning it particular configuration through all the pertaining files?

Shouldn't I visualize permissions assigned to role principalType in ACL API?

Best regards,

**Comment by loay** [comment]
Hi @Acaspita 
Are you still having the same issue. Here is a documentation for ACL:
https://docs.strongloop.com/display/public/LB/Controlling+data+access

Please let me know if you are still having the same question.
