### ISSUE TITLE
LoopBack Components

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#594]
@raymondfeng @bajtos @fabien @altsang @chandadharap @sam-github @rmg (and anyone else)

- [Placeholder repo for examples](https://github.com/strongloop/loopback-example-component)
- [In progress documentation](https://github.com/strongloop/loopback-example-component/wiki)
- Please keep comments / suggestions / discussions in [the issues section](https://github.com/strongloop/loopback-example-component/issues) 
- [Here is a list of issues](https://github.com/strongloop/loopback-example-component/issues/4) needed to implement components

**Comment by superkhau** [comment]
@ritch Is this still relevant?

**Comment by bajtos** [comment]
We are tracking the progress using "#Epic: Components" milestone, see the [list of open stories](https://github.com/search?utf8=%E2%9C%93&q=milestone%3A%22%23Epic%3A+Components%22+user%3Astrongloop+is%3Aopen&type=Issues&ref=searchresults).

I believe it's ok to close this issue now.
