### ISSUE TITLE
Inconsistent API for remote methods and hooks

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#597]
As of LoopBack 2.0, there is a new method for defining remote method metadata `Model.remoteMethod`. To configure a prototype method, one has to supply a flag `isStatic`:

```js
Model.remoteMethod('foo', { isStatic: false, ... });
```

A) This is inconsistent with the approach we have already in place for hooks ([docs](http://docs.strongloop.com/display/LB/Defining+remote+hooks)), where we prefix the method name with `prototype.`:

```js
Model.beforeRemote('prototype.foo', ...);
```

B) The usage of this API - e.g. `('find', true)` - is very ambiguous. What does `true` mean? One has to be very familiar with the API to understand what is the intent of such code snippet.

---

We should modify `Model.remoteMethod` to support the `prototype.foo` notation too.

Since both `Model.remoteMethod` and `Model.beforeRemote` are thin wrappers around strong-remoting API, we should fix this problem in strong-remoting too.

**Comment by bajtos** [comment]
Actually, I find `sharedClass.find` name rather ambiguous, a better name would be `sharedClass.findMethod`. That reveals a backwards-compatible solution: create a new method `sharedClass.findMethod` accepting a single string (`prototype.foo` or `foo`) and deprecate the `find` method.

Unfortunately fixing `disableRemoteMethod` is still a breaking change.

**Comment by bajtos** [comment]
@0candy in reference to https://github.com/strongloop-internal/scrum-loopback/issues/617, here is what I would like you to implement:

1. Create a new function `SharedClass.prototype.findMethod` that could be invoked like `findMethod('create')` and `findMethod('prototype.updateAttributes')` - the first call should find a static method, the second call a prototype method. Implement this function in both 2.x and 3.0 branches.
2. Deprecate `SharedClass.prototype.find` in 3.0 only
3. Modify `SharedClass.prototype.disableRemoteMethod` to accept a single string argument (to follow the signature of `findMethod`), in 3.0 only - this is a breaking change that needs an entry in 3.0 release notes.
4. Compile a list of other places that use `isStatic` when searching for a method, so that we can discuss whether we should change them too (3.0 only).
5. Take a look at places in LoopBack (Model, PersistedModel) that are affected by these API changes, rework the LoopBack API to follow the new strong-remoting API (3.0 only).
6. (This may be a part of the previous item.) Take a look at how remoting metadata is specified in `common/models/my-model.json`. IIRC, at the moment we require `isStatic` to be always present, to prevent confusion. With the new changes in place, we can remove that constraint and allow users to encode the flag static/prototype in the method name. See the discussion in https://github.com/strongloop/loopback/pull/1163 for more details.

@0candy could you perhaps convert the above list into a checklist in https://github.com/strongloop-internal/scrum-loopback/issues/617, so that we can more easily track the progress?

**Comment by bajtos** [comment]
@0candy what's the status of this story? I think most of the items outlined above have been already finished.

strongloop-internal/scrum-loopback#617 mentions few remaining items, but they seem to be finished too, judging by linked issues.

I think we can close this story as done now, what do you think?

**Comment by 0candy** [comment]
@bajtos Yes, this story can be closed. Earlier, I didn't close it as the modules weren't released yet. But just confirmed that they have all been merged and released. Closing this story.

**Comment by Acaspita** [comment]
Please, document this to be able to understand it and use it.
