### ISSUE TITLE
Access model properties on client at runtime

### ISSUE THREAD

**Issue by mrjrdnthms** [strongloop/loopback#598]
We have all this good info in the model.json file like its properties, relations, and validations. I'd like to be able to access that data at runtime in my angular app. With it we can do many cool things like output forms dynamically based on the properties of the model. This has nice benefits like syncing validation on the front end with database, etc.

Is there currently a way to get the model properties at runtime within the Angular sdk? I was hoping properties, etc. would be available on the $resource created for the model by lbServices but that doesn't look like it is the case. 

I am guessing its not currently supported so this is a feature suggestion. Would be nice if the tasks associated with lbServices generation could add these model properties, relations, and validations as accessible properties of the $resource object for use in the client apps at runtime.

If its not possible, does anyone have a recommendation for how I should implement this myself in the mean time? Can I hook into the $recourse creation for each model somehow and append the json object?

Best. Loopback is awesome.

**Comment by lukeblechlmbww** [comment]
@mrjrdnthms, thank-you for the Grunt file, it was exactly what I was looking for!

I did happen to come across a bug in the npm grunt-loopback-angular-addmodeldata package, where if you have model names of CamelCase that get converted to camel-case.json, it would not find the .json file. I have a fix in case others who come across this ticket have the same issue, but the git link on the npm page to https://github.com/mrjrdnthms/loopback-angular-admin doesn't appear to be active or correct so filing an issue via npm will not go through.

For those interested in the fix, you can replace the "if" condition starting around line 47 in node_modules/grunt-loopback-angular-addmodeldata/tasks/loopback_angular_addModelData.js with:
```
if (models[modelName].public){

	modelName = modelName.charAt(0).toUpperCase() + modelName.slice(1);

	// Get the model JSON file name that would be created by slc model generator
	// CamelCaseModelName will become camel-case-model-name.json
	var modelJSONFileName = String(modelName.split(/(?=[A-Z][a-z]+)/).join('-')+".json").toLowerCase();

	grunt.log.ok('Check '+modelName);
	try {
		var model = require(path.resolve(options.modelDir+modelJSONFileName));
		for (var prop in model.properties) {
			model.properties[prop].key = prop;
		}
		var regex = new RegExp("(module\\.factory\\([\\s]*\""+modelName+"\"[\\s\\S]*?)(return R;)");
		var replace = '$1'+'R.model='+JSON.stringify(model)+';\n\n'+'$2';
		serviceFile = serviceFile.replace(regex,replace);
	} catch (e) {
		grunt.log.ok('Did not find a model.json file for ' + modelName);
	}

}
```

Keep in mind if you do a hard-coded replace of this package and you "npm install" again your changes will be overwritten.
