### ISSUE TITLE
custom remote method doesn't check for `accepts type`

### ISSUE THREAD

**Issue by gebrits** [strongloop/loopback#603]
Given a remote method defined as (partial):

`accepts: [{ arg: 'payload', type: ['object'], http: { source: 'body' }, required: true}] ,`

I expected the method to return a `400 bad request` or something when the argument `payload` (i.e.: the body of the post in the case) isn't an array of objects. However, it seems to take any valid json. 

Is this expected?

**Comment by bajtos** [comment]
Closing as a duplicate of https://github.com/strongloop/loopback/issues/2092 where a more recent discussion is taking place.
