### ISSUE TITLE
PUT nested resource allows for setting wrong fk. Bug?

### ISSUE THREAD

**Issue by gebrits** [strongloop/loopback#606]
Given the endpoint `PUT /A/<x>/B` with fk on B: `B.Aid`, it's allowed to set `B.Aid` to something else then `x`. This is a bug imho. 

For ref:  `POST /A/<x>/B` does correctly fix  `B.Aid` to be `x`. Irregardless of what's defined in the POST body. This seems like the way to go.

**Comment by rashmihunt** [comment]
@gebrits Do you still need this fix? Would you be able to submit a fix patch?
