### ISSUE TITLE
partial update (patch) not supported?

### ISSUE THREAD

**Issue by gebrits** [strongloop/loopback#607]
It seems that PUT does a complete update on a resource, and that a partial update (i.e.: patch) isn't supported out of the box. Is that correct? 

Browsing through the code (`persisted-model.js`) I found a couple of interesting methods: `createUpdates` and `bulkUpdate`. Could this be (mis)used to update a single resource based on the deltas for said resource, or is there a better way?

**Comment by amok** [comment]
> i.e.: toplevel resources allow to do partial updates through PUT.
But does it fit REST spec?

**Comment by jbcpollak** [comment]
I'd like to see PATCH support for partial updates - It would fit the RESTful pattern better than using PUT.

**Comment by Dragomir-Ivanov** [comment]
Yes, I need this too. But remember that PATCH needs to contain object diff, not just the new resource value. And I guess they need to provide some kind of sequence numbering, so mitigating updating already modified resource. Much like CouchDB works. Complex stuff, but WEB needs it.

**Comment by allebdev** [comment]
Yes, I need it too. It would be great!

**Comment by tatemz** [comment]
If it is helpful: here is the spec for PATCHing JSON objects

https://tools.ietf.org/html/rfc6902

**Comment by kyleraymorgan** [comment]
I believe this is the most current RFC for HTTP PATCH:

https://www.rfc-editor.org/rfc/rfc7396.txt
