### ISSUE TITLE
`Model.upsert` does not trigger `changed` event

### ISSUE THREAD

**Issue by coodoo** [strongloop/loopback#617]
Take saving of object for example, there are two ways to do it:

1. Static method

  `MyModel.upsert({...}, cb)`

2. Instance method

  `aModel.save(cb)`

They both served the same purpose but only the later will trigger a `changed` event which is critical for syncing to work, hence I'm wondering what's the guide line on when to use which approach? Thanks.

**Comment by bajtos** [comment]
This should be fixed by #1048

**Comment by bajtos** [comment]
Actually, this issue is not related to #1048 nor replication, as the change tracking algorithm does not use `changed` events.

A workaround is to use the new `after save` hook instead of `changed` event.

**Comment by bajtos** [comment]
I am proposing to not fix this issue and deprecate model events instead, in the same way as we are going to deprecate the old hooks "beforeSave/afterSave". The new operation hooks already cover all functionality offered by model events, and by keeping the number of overlapping APIs low, we will spent less time on their maintenance.

@ritch @raymondfeng @fabien @clarkorz  any objections?

**Comment by ritch** [comment]
Sounds good. We should print an error when someone binds the deprecated events.

**Comment by bajtos** [comment]
> We should print an error when someone binds the deprecated events.

I'd rather print a deprecation warning via [depd](https://www.npmjs.com/package/depd) in the same way as express does.

**Comment by bajtos** [comment]
@pungoyal @clarkorz You were discussing a new "created" event in #838. We would like to deprecate events in favour of Operation hooks. Is there any use case (beyond not-yet-implemented "ctx.isNewInstance") where you cannot replace your event-based implementation with an operation hook?

**Comment by pungoyal** [comment]
@bajtos We have not followed the discussion about operational hooks. What would be a good place to get a grasp?

**Comment by bajtos** [comment]
@pungoyal http://docs.strongloop.com/display/LB/Operation+hooks

**Comment by bajtos** [comment]
The events were marked as deprecated by strongloop/loopback-datasource-juggler#473. Please upgrade your code to use the new Operations hook.
