### ISSUE TITLE
Dynamic properties in JSON payloads

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#618]
As a developer, I want to add dynamic (computed) properties to my model. Such properties should be exposed in javascript API (e.g. `MyModel.dynamic`) and also in the JSON payload used by REST.

See #600 for background.

**Comment by yuanyong** [comment]
Any solution for this?

**Comment by acao** [comment]
Currently you can fake this with model hooks, but there should be an api for computed/dynamic properties. A standard feature of most ODMs nowadays.

**Comment by mrfelton** [comment]
See https://github.com/fullcube/loopback-ds-computed-mixin

**Comment by acao** [comment]
Oh very nice, thanks!

**Comment by jmwohl** [comment]
@mrfelton's solution seems reasonable... any plans to add this integrate something like this into the loopback codebase?

**Comment by rblalock** [comment]
This is a very common use case that could be made elegant in LB.  I like the approach @mrfelton took in his mixin: https://github.com/fullcube/loopback-ds-computed-mixin

What would be really great is if it doesn't have to specified in the mixin object but in the properties of the model themselves.  Here's a concept:

```javascript
// Model.json
{
    "name": "Item",
    "properties": {
		"name": {
	      "type": "string"
	  },
		"email": {
			"type": "string"
		},
		"info": {
			"type": "string",
			"computed": "computeInfo"
		}
    }
}

// Model.js
Item.computeInfo = function computeInfo(item) {
	// e.g. returns: "info: "Rick, myemail@email.com"
	return item.name + ', ' + item.email;
};

// Computed only inside .json (no .js needed, just expressions and str replacement)
{
    "name": "Item",
    "properties": {
		// ...
		"info": {
			"type": "string",
			"computed": "{name}, {email}"
		}
    }
}
```

**Comment by rblalock** [comment]
Another comment on this that is semi-related - I just realized Loopback has this functionality where you can define a defaultFn - https://github.com/strongloop/loopback/issues/292 (source: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/model.js#L288-L313) .  Only 3 use cases are supported and supporting a custom function isn't supported yet.  If and when support for allowing a custom defaultFn comes, it'd probably be good to keep the above suggestions consistent with this  as well, to keep it congruent.

**Comment by Biax2099** [comment]
I'm agree with @rblalock !!! it would be very convenient to be able to create dynamic properties.

**Comment by toniopelo** [comment]
Any update on this ?
