### ISSUE TITLE
Rework built-in models to use `Model.remoteMethod`

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#622]
Rework all built-in models to register remoting metadata via `Model.remoteMethod` instead of `loopback.remoteMethod` and pass method name instead of method function as the first argument.

That way it will be easier to override methods in subclassing models - see #619.

**Comment by loay** [comment]
@bajtos 
I see the PR already merged. Can I close this one?
Thanks.

**Comment by bajtos** [comment]
@loay I am proposing to mark `loopback.remoteMethod` as deprecated. The deprecation message should include instructions what to do instead - either call `Model.remoteMethod` or even better, place the metadata into "methods" in the model JSON file.

Thoughts?

**Comment by bajtos** [comment]
Other than that (or after that is landed?), this issue can be closed, indeed.

**Comment by loay** [comment]
I misunderstood, I thought the PR merged before is what was required.
