### ISSUE TITLE
How to format the response returned to client ?

### ISSUE THREAD

**Issue by projectxmaker** [strongloop/loopback#624]
Hi,

I would like to re-format the response returned to client.

I know we could use afterRemote hook, but if doing so, I have to do it every single Models, one by one.

Is there any other solution in that I only need to change the code at place and it will be applied to all Models, something likes that ?

Thanks for any help.

**Comment by mike-aungsan** [comment]
How to format the response returned from Remote methods to client?

How to response just a String from Remote methods to client?

    module.exports = function(Test) {
        
        Test.teamMembers = function(sthId, aName, cb) {
            cb(err, 'want to return just a String')
        }

        
        Test.remoteMethod('format', {
            accepts: [
                {arg: 'sthId', type: 'string'},
                {arg: 'aName', type: 'string'}
            ],

            http: {verb: 'get'},
            returns: {type: 'string'}
            
        })
        
    }

**Comment by Noob7** [comment]
Hey,
Maybe im too late but from the remote method documentation on loopback i could find this:

**Formatting remote method responses**
You can reformat the response returned by all remote methods by adding a boot script that modifies the object returned by app.remotes() as follows:
/server/boot/hook.js
module.exports = function(app) {
  var remotes = app.remotes();
  // modify all returned values
  remotes.after('**', function (ctx, next) {
    ctx.result = {
      data: ctx.result
    };
 
    next();
  });
};

**Comment by virendra656** [comment]
If you just want to format all errors then make handler in hook.js  as suggested by @projectxmaker  it worked for me.

module.exports = function(server) {
  var remotes = server.remotes();
  var opts = remotes.options || {};
  opts.errorHandler = {
    'handler': function restErrorHandler(err, req, res, next) {

              }
  }
  remotes.options =  opts;
}

**Comment by amenadiel** [comment]
Thanks @virendra656 
In my case, I needed to intercept well meant MongoError instances that shouldn't be served with status 500, they were more 409 (ish). This worked perfecly.

**Comment by shallker** [comment]
As note, for Loopback 3.X

```js
// /server/boot/wrap-error.js
module.exports = function (app) {
  var remotes = app.remotes();

  remotes.options.rest = remotes.options.rest || {}
  remotes.options.rest.handleErrors = false;

  app.middleware('final', FinalErrorHandler);

  function FinalErrorHandler(err, req, res, next) {
    res.status(400).send({
      code: 400,
      message: err.message,
      data: {},
      result: "fail"
    }).end();
  }
};
```

```js
// /server/boot/wrap-success.js
module.exports = function (app) {
  var remotes = app.remotes();

  remotes.after('**', function (ctx, next) {
    ctx.result = {
      code: 200,
      message: ctx.methodString + " success",
      data: ctx.result,
      result: "success"
    };

    next();
  });
};
```
