### ISSUE TITLE
Add model strict property to Troubleshooting / FAQ or other xrefs

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#629]
I don't know why we don't prevent user set informations which are not defined in Model.json.

Ex: When i create Book model with properties are "name" and "description" but when i request POST method to create Book i provide informations like below:

``` html
{
  "name":"Book 1",
  "description":"This is a book 1",
  "abcdef":"This is other information which is not defined in Model.json"
}
```

=> As you can see that "abcdef" is not defined in Book.json but it still be inserted to "Book" collection of mongodb. Please tell me how to prevent it if it not a bug ?

**Comment by cookejames** [comment]
Its very annoying that this works in creation but not update - I've had to create a boot script that intercepts updates and removes properties not defined on the model from the request.

**Comment by fabien** [comment]
@cookejames see: https://github.com/strongloop/loopback-datasource-juggler/pull/666

**Comment by cookejames** [comment]
@fabien thanks for the pull request - looks like you've just done exactly what I did
