### ISSUE TITLE
Feature Request: Return Role Name in Role.getRoles (from principals)

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback#632]
In the current Roles model, the getRoles method returns the `id` when [fetching role mappings via principal](https://github.com/strongloop/loopback/blob/0fda4c4193a6354dc5152c364b3e2c9bef87e8f2/lib/models/role.js#L467-L469). It would be nice it resolved this to the actual role name.

This requires more callbacks to track in `inRoleTasks` but shouldn't be too difficult to add the calls in.

**Comment by greaterweb** [comment]
Closing.

**Comment by ebarault** [comment]
@batjos: would you know if this feature request has been considered, or will be at some point? It would indeed be nice that getRoles return actual role names rather than their ids

**Comment by ebarault** [comment]
referring to [this url](https://github.com/strongloop/loopback/blob/0fda4c4193a6354dc5152c364b3e2c9bef87e8f2/lib/models/role.js#L467-L469)

this simple modification would do the trick
`
if (principalType && principalId) {
        // Please find() treat undefined matches all values
        inRoleTasks.push(function(done) {
          roleMappingModel.find({
              where: {principalType: principalType, principalId: principalId},
              include: ['role']
          }, function(err, mappings) {
            debug('Role mappings found: %s %j', err, mappings);
            console.log(mappings);
            if (err) {
              if (done) done(err);
              return;
            }
            mappings.forEach(function(m) {
              var _m = m.toJSON();
              addRole(_m.role.name);
            });
            if (done) done();
          });
        });
      }
`
