### ISSUE TITLE
findOne() returns non-empty result if a value of filtering criteria is undefined

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback#637]
Basic cases:

1. Car.findOne(function(err, car) {...}) - no filtering applied
2. Car.findOne({ where: { number: "" }}, function(err, car) {...}) - filtering by empty value;

Question:

* Car.findOne({ where: { number: undefined }}, function(err, car) {...}) - filtering is not applied, same as case 1. The question is whether it should it behave like case 2 instead.

Could you please clarify whether this is an expected behavior.

Some more details:
* undefined properties seem to be removed from query here: https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/dao.js#L512
* sample code with tests: https://gist.github.com/voitau/f03ea7564ee77ac5b6a5

**Comment by esco** [comment]
:+1: 

Silently stripping out undefined values can have catastrophic outcomes for MongoDB queries.

```
var userId; // undefined due to application logic error

User.update({ where: { id: userId } }, { email: "new@gmail.com" })
```

The result of the above code is that all users in the database will have their email updated. Although this also requires an application error, this is not an expected outcome for the developer in any circumstance.

**Comment by jrschumacher** [comment]
To add to this a worse outcome which we have experienced was a rouge client bug removed all documents from our collection: `User.destroyAll({ id: undefined });`

cc @raymondfeng

**Comment by jrschumacher** [comment]
I would prefer the ability to set a configuration to:

1. Throw an error if undefined is found in a query `throw new Error("Undefined is an unacceptable query value");`
2. Convert `undefined` values to `null`
3. Work as it does now

**Comment by raymondfeng** [comment]
@jrschumacher +1. Do you want to submit a patch?

**Comment by jrschumacher** [comment]
@raymondfeng if you can point me to which method is stripping the undefined values I will have a patch you you by Wednesday! Spent 4 hours tracing through code and not a hair close.

**Comment by kblcuk** [comment]
@jrschumacher it's [in datasource-juggler](https://github.com/strongloop/loopback-datasource-juggler/blob/311c7fc07cb671d667f26a786016fde7db83598d/lib/utils.js#L294)

Keep in mind that it is used internally as well, and sometimes _should_ strip undefined values.

**Comment by jrschumacher** [comment]
@kblcuk thanks! I'll keep that in mind.

**Comment by esco** [comment]
@jrschumacher great idea

**Comment by jrschumacher** [comment]
@raymondfeng can you look at strongloop/loopback-datasource-juggler#725 and give me some feedback.

**Comment by jrschumacher** [comment]
@voitau @esco a patch to this has been released in [loopback-datasource-juggler@v2.41.0](https://github.com/strongloop/loopback-datasource-juggler/releases/tag/v2.41.0) you can use it by adding `normalizeUndefinedInQuery` setting to your datasource config or model config (see tests for more detail). Options are:

- `"nullify"` which converts undefined to `null`
- `"throw"` which throws an error `Unexpected `\``undefined`\`` in query`
- `"ignore"` which strips the undefined key (default function)

@bajtos this issue can probably be closed now?

**Comment by esco** [comment]
Excellent:exclamation: :+1: thanks guys

**Comment by voitau** [comment]
Thank you!

**Comment by reduxdj** [comment]
This framework is a total piece of crap.

**Comment by bilal68** [comment]
can we make findOne should return null if no condition is matched? cuz now it returnz empty object to me

**Comment by bajtos** [comment]
@bilal68 please open a new issue to discuss the problem you are experiencing, and include a small application we can use to reproduce it - see https://loopback.io/doc/en/contrib/Reporting-issues.html#loopback-4x-bugs
