### ISSUE TITLE
Can't remove properties within before* hooks.

### ISSUE THREAD

**Issue by CoreMaker** [strongloop/loopback#643]
I've tried to remove redundant properties that are not defined in my MODEL.json. And the redundant properties are being passed in by the client via RESTful APIs. It seems like I just can't do that. Below is what I'm trying to do:

```
MODEL.beforeSave = function(next, data) {
   if (data.startups) {
      data.startups = null;
      delete data.startups;
   }

   next();
};
```

**Comment by bajtos** [comment]
I am closing this issue, we are moving away from `beforeSave/afterSave` hooks in favour of [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks) and [Per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397).

Please upgrade your project to use the new `before save` hook and open a new GH issue if you run into any problem.
