### ISSUE TITLE
Batch and Tree based Upsert and Delete...

### ISSUE THREAD

**Issue by tonysoft** [strongloop/loopback#644]
Now that LoopBack is working on filter/include to any depth of Relationships for example:

`http://localhost:3000/api/Students/1/teachers?filter={"include": {"relation": "classes", "scope": {"include": "students"}}}
`

would return "ALL Teachers related to a specific Student return ALL Classes related to each Teacher and for each of these Classes ALL Students related to the Class".

The results look like the sample JSON below.

Once this JSON hits the Client, it might display a Tree View Edit Form where fields from any Teacher, Class, or Student could be edited.  The Client Logic would expose which records were editable.  In some "admin" mode, perhaps all of the records would be editable.

I proposed that a PUT (Upsert) to .../api/Teachers could pass in the JSON Below and, if an ARRAY rather than an Object is passed in the BODY, a Deep Batch Modification (Upsert or Delete) would take place on any Object decorated with UPSERT or DELETE OPERATION properties.   This should be self explanatory from the decorated JSON below...  The Client will be totally responsible for specifying the OPERATION based on UX actions.

```[
  {
    "OPERATION": "UPSERT",
    "firstName": "Issac",
    "lastName": "Roth",
    "department": "Computer Science",
    "id": 1,
    "classes": [
      {
        "subject": "LoopBack",
        "id": 1,
        "teacherId": 1,
        "students": [
          {
            "OPERATION": "UPSERT",
            "firstName": "Tony",
            "lastName": "Sukiennik",
            "major": "Economics",
            "id": 1
          },
          {
            "OPERATION": "DELETE_RELATION",
            "firstName": "Dennis",
            "lastName": "Ashby",
            "id": 8
          }
        ]
      },
      {
        "OPERATION": "DELETE",
        "subject": "REST APIs",
        "id": 3,
        "teacherId": 1,
        "students": []
      }
    ]
  }
]
```

**Comment by bajtos** [comment]
I am closing this issue, since there were not enough people asking for this enhancement and it clearly was not a priority for us so far. We can reopen it again later when there is more demand.
