### ISSUE TITLE
Include HTTP 422 ValidationError response in swagger for PersistedModel

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#647]
When https://github.com/strongloop/loopback-explorer/pull/61 is landed, loopback-explorer will be able to describe error responses of any API route. Shared methods can describe these errors via `errors` field in remoting metadata.

We should modify `PersistedModel` to include description of `422 ValidationError` for all methods which are validating the model data.

**Comment by sasanrose** [comment]
I know this is a very old issue, but is there a  work around for this now in lb4?
