### ISSUE TITLE
Inconsistent between GET and DELETE on related models

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#665]
DELETE /Customers/{id}/thankBooks
- This doesn't have filter

GET /Customers/{id}/thankBooks
- This have filter

I think we need to apply filter for DELETE method instead of delete all records of related model.

**Comment by loay** [comment]
@bluestaralone 
Is that issue still relevant?

You can use
```
DELETE /Customers/{id}/thankBooks/{fk}
```

to delete a specific record of a thankBooks of the customer mode. 
let me know if that's not what you are looking for.

**Comment by bluestaralone** [comment]
@loay 
Arcording to your way, we just delete only one record, but my need is deleting multiple records.

**Comment by loay** [comment]
@bluestaralone 
I thought that's what you were looking for. 

So basically the current workaround would be:

delete the whole records for customers would be:
```
DELETE /Customers/{id}/thankBooks
```

delete specific thankBooks with a specific ID: 

```
DELETE /Customers/{id}/thankBooks/{fk}
```

delete multiple records of thankBooks with a specific condition:

```
PersistedModel.destroyAll([where], callback)
```

Another example from the documentation:
https://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-Whereclauseforupdatesanddeletes

To delete all records where the cost property is greater than 100:
```
productModel.destroyAll( { cost: {gt: 100} }, function(err, obj) { ... } )
```

I guess you were looking to add the filter in the API explorer page, correct?
