### ISSUE TITLE
Is there any way to validate model?

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback#670]
How can I validate model before creating it. I know "create" validates model automatically.

But what if I have to validate 2 models and then if both are valid - create them. Otherwise to throw an error. Something like:

```
    models.creditCard({
        name:'test'
    }).validate(function (err, data) {
        if (! err) {
            models.creditCard.create({
                name: 'test'
            }, function (err, data) {

            }l
        }   
    })
```

Thanks

**Comment by marcellodesales** [comment]
You guys need to update one of the sample codes with validation... It is NOT clear where to add them.
