### ISSUE TITLE
Multiple "User" child model - Revisited!!

### ISSUE THREAD

**Issue by veekungx** [strongloop/loopback#678]
The issue #527 opened by @glesage talk about multiple models based from "User" model that can both login.

I have some question about this.

**Issue** 1. The overriden AccessToken.
@glesage found out when you create each models with MySQL. The id will be always 1.

@glesage
> It makes it impossible to trace back the user based on the token and such... also, once I log in a driver the agent that was logged in probably gets his accessToken overridden...

**Question 1.1**
Does it affect the Role ,RoleMapping, ACL features?

RoleMapping is bind "principalId" with "roleId" I think it will be overriden too.

**Question 1.2.1**
 Can I use different prefix on each model to solve this problem?
ex.
```
Agent
id : AG1
id : AG2
...

Driver
id : DR1
id : DR2
```
**Question 1.2.2**
If it can does LB can define prefix and use with autoincrement id?

**Question 1.3**
If not use method from **question 1.2.1**.
Can polymorphic model solve RoleMapping issue?

ex
**RoleMapping**
```
   "id": ...,
  "principalType": "ROLE",
  "principalId": "1",             (assume  Agent id 1)
  "roleId": 1,                    (assume "Agent" role id)
  "ownerId" : 1,                 (assume Agent id 1)
  "ownerType" : "Agent"

  "id": ...,
  "principalType": "ROLE",
  "principalId": "1",             (assume  Driver id 1)
  "roleId": 2,                    (assume "Driver" id) 
  "ownerId" : 1,                  (assume  Driver id 1)
  "ownerType" : "Driver"
```

**Issue 2**. Recommend by @clarkorz  and @johnsoftek 

@johnsoftek
> I think that having two isolated user models is not the best data model.
You should have a User model and login using the User table and relate User
to AccessToken. Also implement Driver and Agent models that belongTo User
to handle business rules for those sub-types.

@clarkorz 
> If you really need multiple kinds of users, then I suggest to consider the built-in User model as an Account or Identity, no more. Then create separated models for Agent and Driver, and setup polymorphic belongsTo + polymorphic hasOne against User model. Or, you could mix them into User model, then use roles to distinguish.

**Question 2.1**
I'm not clear on

> Then create separated models for Agent and Driver, and setup polymorphic belongsTo + polymorphic hasOne against User model

Could you please give me some code or example how to do that?

Thank you.

**Comment by bajtos** [comment]
Hello, as part of our triage process, I am closing issues that have been inactive for extended period of time. Please leave a comment if you think this issue is still relevant and should be reopened.
