### ISSUE TITLE
How can I get account's role in "beforeRemote"?

### ISSUE THREAD

**Issue by Spark-star** [strongloop/loopback#684]
I created a model Account which extend from "User", I also covered the relations with "AccessToken" like this 

```
"accessTokens": {
      "type": "hasMany",
      "model": "AccessToken",
      "foreignKey": "accountId"
    }
```

My question is how can  I get the account's role in "beforeRemote"?

the code like this :

```
Account.beforeRemote('method', function(ctx, next) { 
   
if( role = 'admin' ) { can update  something }
else{ only can update one property , for example: name}
next(); 
  });
```

How can I get the "role" ?
Thanks

**Comment by bigktmbig** [comment]
Thank you so much!. It's greate.

**Comment by loay** [comment]
This document should help as well: 
https://docs.strongloop.com/display/LB/Remote+hooks

Closing this issue for now. If you still have an issue with the same subject, please feel free to leave the comment and I will re-open the issue. Thanks.

**Comment by LinhTran1** [comment]
Now you can use this:
`ctx.args.options.authorizedRoles`

Remember to apply "strictObjectIDCoercion" option with true value to the following models in model-config.json:

- Role

- ACL

- RoleMapping
