### ISSUE TITLE
loopback-explorer should pick up `hideRemoteMethod` called after the explorer was initialized

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#686]
```
// works, User.login is hidden
User.disableRemoteMethod('login', true);
app.use(explorer(app, { basePath: '/' }));

// does not work, User.login is shown in the UI
app.use(explorer(app, { basePath: '/' }));
User.disableRemoteMethod('login', true);
```

See also https://github.com/strongloop/loopback-explorer/pull/22, strongloop/loopback#402 and https://github.com/strongloop/loopback/issues/651

**Comment by supasate** [comment]
@bajtos Let's me take this. (Anyway, I'm a beginner to this community. If I do something wrong, please advise.)

I'll send one PR to this repo to make Loopback emits 'remoteMethodDisabled' event and one PR to loopback-component-explorer to re-create the swagger object when this event fired.

**Comment by bajtos** [comment]
> I'll send one PR to this repo to make Loopback emits 'remoteMethodDisabled' event and one PR to loopback-component-explorer to re-create the swagger object when this event fired.

Awesome, thank you for the contribution. I can see the first pull request was already landed :)

**Comment by bajtos** [comment]
Released in `loopback@2.28.0` and `loopback-component-explorer@2.5.0`. Enjoy :)

**Comment by supasate** [comment]
@bajtos In loopback-component-explorer, should we change the loopback version in devDependency to be "^2.28.0" to make it more explicit about minimum requirement?

**Comment by bajtos** [comment]
> In loopback-component-explorer, should we change the loopback version in devDependency to be "^2.28.0" to make it more explicit about minimum requirement?

That's a good idea, could you please contribute that change yourself?

I am closing this issue as resolved.

**Comment by supasate** [comment]
@bajtos Done. I made a PR at strongloop/loopback-component-explorer#159.
