### ISSUE TITLE
Question about geopoint

### ISSUE THREAD

**Issue by Spark-star** [strongloop/loopback#687]
I used the "near" method to get accords neared me, it works well.
But I want the response also have the "distance" property which I want display in my application.
I think I could use the traversal the content which I filter by "near" by "GeoPoint.distanceBetween" method to  get the distance between each accord and me.

Is there a method which can get the accords near some point and also can compute the distance between them?  

Thanks

**Comment by 0candy** [comment]
Did you try GeoPoint.distanceBetween(pointA, pointB, options)?
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/geo.js#L181

**Comment by loay** [comment]
@Spark-star 
You can also have a look at these document:
https://docs.strongloop.com/display/public/LB/GeoPoint+class
Closing this issue, please feel free to leave a comment if you have a further question, and we will re-open. Thanks.
