### ISSUE TITLE
Enhance validation docs

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#693]
Per https://groups.google.com/forum/#!topic/loopbackjs/WC7oZG9Obhg, we need to improve [Validating model data](http://docs.strongloop.com/display/LB/Validating+model+data) which doesn't have much now.  It's an important topic.

**Comment by grosem** [comment]
Just tried to edit http://docs.strongloop.com/display/LB/Validatable+class. Unfortunately the page is not loading in Chrome or Firefox when in edit mode. Anybody else with that problem?
Some validation methods (e.g. Validatable.validateAsync) are linked, but not documented.

**Comment by crandmck** [comment]
Hm, I can view the page fine in Chrome.  What do you mean "in edit mode" -- do you mean you are logged in to the wiki and editing the page?

The content of this page is created by a custom Confluence macro that renders the content from http://apidocs.strongloop.com/loopback-datasource-juggler/#validatable into the page on docs.strongloop.com.  If you just want to view the API doc, try that page instead.

**Comment by grosem** [comment]
Yes, I tried editing it in the wiki. Didn't know about the macro.

Still, some methods are missing there.

**Comment by crandmck** [comment]
Do you mean that some methods are missing from http://apidocs.strongloop.com/loopback-datasource-juggler/#validatable ?  If so, what?  It _should_ include all the methods in 
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/validations.js

**Comment by grosem** [comment]
I noticed validate and validateAsync missing, but didn't compare all of them. Thanks.

**Comment by crandmck** [comment]
Thanks, this appears to be an issue with strong-docs the custom module we use to generate API docs.  I'm investigating.

**Comment by crandmck** [comment]
Fixed in https://github.com/strongloop/loopback-datasource-juggler/commit/e81415cedae3d0bd3de0603fb29e2fbd094ea3d8.  Note that http://apidocs.strongloop.com will be updated the next time loopback-datasource-juggler is npm published.

**Comment by grosem** [comment]
Great, thanks.

**Comment by crandmck** [comment]
>Jordan Kasper [8:12 AM] 
....when can I use `isValid()`???
Dennis Ashby [8:12 AM] 
You can do it on a before save. The model is loaded at that point
OR you have to load the data into the model… which is one of my questions above… if I have the JSON, is there an easy way to populate the Model?

**Comment by jakerella** [comment]
Note for the docs, to add validation to model for creation or saving you _do not_ need to call `isValid()` yourself in the MyModel.js file. You can add validation by simply adding the validator calls:

In MyModel.js  
```js
module.exports = function(MyModel) {
  MyModel.validatesLengthOf('name', { min: 5, message: { min: 'Name should be 5+ characters' } });
  ...
};
```

The `isValid()` is just an additional way to check validity ad-hoc.

**Comment by crandmck** [comment]
Added the above to http://docs.strongloop.com/display/LB/Validating+model+data#Validatingmodeldata-Usingvalidationmethods.

**Comment by jakerella** [comment]
Great start! Thanks Rand.

**Comment by crandmck** [comment]
@jakerella If you have further specific suggestions, please add.  Also, please edit the doc yourself when you have spare cycles!  Thanks!

**Comment by nelzomal** [comment]
@crandmck 
I am learning validation from http://docs.strongloop.com/display/LB/Validating+model+data#Validatingmodeldata-Usingvalidationmethods.
The validation is quite easy to use. 
But as @jakerella pointed out, it's confusing that we don't necessary need to call isValid. It will be great if some validation examples could be add into https://github.com/strongloop/loopback-faq-user-management.

Besides, when I try 
user.validatesLengthOf('password', {min: 10, message: {min: 'Password is too short'}}); 
in server/model/user.js file.

The hashed password is checked instead of the original user input. I wonder if we could validate password input before hashing.

Thank you very much for the wonderful validation function.

**Comment by crandmck** [comment]
@raymondfeng: from above ^ .. Can you comment?
> when I try 
`user.validatesLengthOf('password', {min: 10, message: {min: 'Password is too short'}}); `
in `server/model/user.js` file, the hashed password is checked instead of the original user input. I wonder if we could validate password input before hashing.

**Comment by alexw23** [comment]
Just noticed that `unless` and `if` is missing from documentation - will submit a PR

**Comment by crandmck** [comment]
Hi @alexw23, if you're talking about doc on docs.strongloop.com, you don't submit a PR.  You can edit it directly: see [Contributing to LoopBack documentation ](https://docs.strongloop.com/display/LB/Contributing+to+LoopBack+documentation).  OTOH, if you mean  [API docs](http://apidocs.strongloop.com/) Then you would use a PR for changes to the doc comments in the source code.
