### ISSUE TITLE
How to get list of permission on current user.

### ISSUE THREAD

**Issue by veekungx** [strongloop/loopback#697]
Hi I would like to get the list of permission like this.
```javascript
{
    "GET /model"  :            "ALLOW",
    "GET /model/{id}" :        "ALLOW",
    "POST /model/{id}/child" :  "DENY"
    ....
}
```
or 

```javascript
{
    "GET /model"  :            true,
    "GET /model/{id}" :        true,
    "POST /model/{id}/child" :  false
    ....
}
```

or something like this 
Could you guide me how to do that?
thank you.

**Comment by loay** [comment]
Hi @veekungx 
Here is the controlling data document to help you out: 
https://docs.strongloop.com/display/LB/Controlling+data+access

If you have any other question related to that topic, please feel free to leave a comment and I will re-open the issue for further assistance. Thanks.
