### ISSUE TITLE
Per-model prefix for the REST path (e.g. version or domain)

### ISSUE THREAD

**Issue by wascou** [strongloop/loopback#698]
Hi,

I haven't found the answer in the issues stack neither in the documentation, so here's my question.
Is it possible to prefix all routes to API exposed resources by a string which can be used either to scope the API by domain either for versioning purpose ?

Cheers and good job guys.

Max

**Comment by bajtos** [comment]
#1039 added a test to verify and document this contract. I am closing this issue a resolved.
