### ISSUE TITLE
Inheriting Remote Hooks

### ISSUE THREAD

**Issue by wtfribley** [strongloop/loopback#702]
I have two models:

**/common/models/parent.json**

``` js
{
  "name": "Parent",
  "base": "PersistedModel",
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

**/common/models/parent.js**

``` js
module.exports = function(Parent) {
  Parent.afterRemote('**', function(ctx, result, next) {
    console.log('after remote ', ctx.methodString);
    next();
  });
};
```

**/common/models/child.json**

``` js
{
  "name": "Child",
  "base": "Parent",
  "properties": {},
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": []
}
```

I would expect that the Parent's `afterRemote` hook is invoked when any of the Child's remote methods are called -- i.e. that hooks are inherited. Should I not expect this? Is there an alternate way for models to share hooks?

**Comment by rus0000** [comment]
Seems same with a `remoteMethod` as well. It only works if defined inside overloaded setup method in parent model.

@bajtos Some questions about example:
**/common/models/parent.js**
1.
`Parent.base.apply(this, arguments);` - doesn't work
`Parent.base.setup.apply(this, arguments);` - works

2.
Why need to call `Parent.setup();` if it  is
>called whenever the model is extended

**Comment by bajtos** [comment]
ad 1) Good catch, I have updated my comment above. It was a typo on my side.

ad 2) IIRC, loopback calls only one setup method. Consider the following inheritance hierarchy: Model -> PersistedModel -> YourBase -> YourModel. When `YourModel` is created, loopback will call `YourBase.setup` and it's up to that method to call `PersistedModel.setup`.

**Comment by rus0000** [comment]
2) Sorry for annoyance. It's still not clear to me.
In our example we have inheritance chain: `Model -> PersistedModel -> Parent -> Child`

Loopback calls Child.setup, which is probably missing, therefore Parent.setup is invoked by searching prototype chain, as we have defined it with  `Parent.setup = function() { ...` .
In `Parent.setup` we call base class method with `Parent.base.setup.apply(this, arguments);` which is defined in `PersistedModel.setup`. That's fine. 

But why there is a call of `Parent.setup();` at the end of an example. Why to call itself immediately after definition?

**Comment by bajtos** [comment]
> But why there is a call of `Parent.setup()`; at the end of an example. Why to call itself immediately after definition?

AFAIK, LoopBack does not call setup function when a new model is defined. In other words, if your `Child` model provides a `setup` function, it is called only when somebody extends (inherits from) your Child, but not when the Child is defined as a standalone model. See #550.

> Sorry for annoyance. It's still not clear to me.

No worries, I am happy to explain. Is there anything else to explain in order to make this matter more clear?

**Comment by rus0000** [comment]
OK. We provide setup function for Parent. It is called by Loopback when the Parent is extended. But why need to call it explicitly in a moment of definition?

**Comment by bajtos** [comment]
> But why need to call it explicitly in a moment of definition?

Because if you do not call it explicitly, then it won't be called for your leaf (non-base) model. You can verify this yourself by adding the following `Car` model to your app:

```js
// common/models/car.json
{
  "name": "Car"
}

// common/models/car.js
module.exports = function(Car) {
  Car.setup = function() {
    console.log('setup');
  };
};

// server/model-config.json
{
  "Car": {
    "dataSource": "db" 
  }
}
```

**Comment by davidcheung** [comment]
@bajtos yeah that was the conclusion ([more info](https://github.com/strongloop/loopback/issues/1485#issuecomment-218292069))
 I was testing it the other day and couldn't reach my use case, I think the very last child will need to recursively call their parents constructor, but from the **base -> child** direction, but that [isnt the behavior](https://github.com/strongloop/loopback-datasource-juggler/blob/795952c1823936c37b8dc037e043dd9168c87c5e/lib/model-builder.js#L415-L418) 
I need to do a little more investigation into this issue but yes I think we shouldn't do both **inherit** AND **build**.

**Comment by bajtos** [comment]
LoopBack version 3 is in LTS, we won't be making breaking changes like this one.

**Comment by itsdun1** [comment]
does setup() inheritence also works with afterRemoteError()
