### ISSUE TITLE
invalid readable-stream and string_decoder

### ISSUE THREAD

**Issue by conradwt** [strongloop/loopback#706]
Hi, I have installed the strongloop module by doing the following:

```
npm install -g strongloop
```

Now, I'm seeing the following error messages when listing the globally installed modules:

```
$ npm list -g

npm ERR! invalid: readable-stream@1.0.27-1 /opt/local/lib/node_modules/strongloop/node_modules/npm/node_modules/sha/node_modules/readable-stream
npm ERR! invalid: string_decoder@0.10.25-1 /opt/local/lib/node_modules/strongloop/node_modules/npm/node_modules/sha/node_modules/readable-stream/node_modules/string_decoder
```

Lastly, here's my current setup:

```
$ npm -v 
2.1.5

$ node -v
v0.10.33
```

**Comment by bajtos** [comment]
As part of our issue triage process, we are closing items that have been inactive for an extended period of time. Feel free to reopen this issue if you can reproduce it using the latest version.
