### ISSUE TITLE
don't rely on [function].name

### ISSUE THREAD

**Issue by bitmage** [strongloop/loopback#711]
[function].name is not available in IE10, or any other IE version. It returns undefined.  We need to find a workaround in order to guarantee cross browser support.  Also, we should be running the tests in SauceLabs or some other cross browser environment.

Further info/discussion here:

https://github.com/strongloop/loopback-datasource-juggler/pull/348

**Comment by bajtos** [comment]
Closing as a duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/375
