### ISSUE TITLE
hasOne relation doc

### ISSUE THREAD

**Issue by ezraroi** [strongloop/loopback#718]
Hi,
there is not documentation for the hasOne relation, i am trying to use it but for some reason i am getting null when querying with the explorer

**Comment by jbrw1984** [comment]
Any movement on this? Or should we just use the 'belongsTo' relationship?

**Comment by crandmck** [comment]
Sorry I haven't gotten to this.  Will try to carve out some time to improve it.  

I nneed to talk with Raymond... Here is something from him from chat re diff. btw 'hasOne` and `belongsTo` (for my notes):
>belongsTo: An order belongs to a user (user owns the order)
hasOne: a customer has one profile

**Comment by jbrw1984** [comment]
My question is - does this affect the $owner role? For example, right now I have multiple 'belongsTo' relations on a single model, even though a few should probably be better categorized as a 'hasOne' relation. In this case, how is the $owner role determined?

**Comment by crandmck** [comment]
@raymondfeng Can you answer the above?

**Comment by crandmck** [comment]
Updated http://docs.strongloop.com/display/LB/HasOne+relations as best as I could.  I have a number of questions inline in the article.  PTAL when you have a moment.

**Comment by raymondfeng** [comment]
HasOne relation doesn't play a role in deciding `$owner` role.

**Comment by raymondfeng** [comment]
Doc reviewed and updated.
