### ISSUE TITLE
Technical review of relations docs

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#719]
The relations docs need a tech review.  In particular:

 - Need a JSON example for [hasManyThrough](http://docs.strongloop.com/display/LB/HasManyThrough+relations)
 - Answer question in http://docs.strongloop.com/display/LB/Polymorphic+relations
 - Check correctness of JavaScript code samples for all relations.

**Comment by harshil93** [comment]
Please add the JSON examples of a Self Through relationship. I am unable setup self through relationship through JSON.
