### ISSUE TITLE
Delete item by id alway return 204

### ISSUE THREAD

**Issue by NgaNguyenDuy** [strongloop/loopback#723]
Hi,

When i delete a items by id i alway get status is 204 (include id not exists). How to check if i delete unsuccessful?

Thank,

**Comment by Amir-61** [comment]
Hi @NgaNguyenDuy,

Sorry to get back to you late! This tickets seems pretty old and probably it has been solved by now; I tried to re-produce the issue and it seems it is working now; however, I need to double check it with you; if you still have the same problem could you please let me know what datasource (db-connector) you are using? Please update us on this. 

Also possibly sharing a Repo to re-produce the issue can help us!
Thanks a lot!

**Comment by Amir-61** [comment]
I'm closing this ticket due to inactivity.

Please feel free to open an issue if you see the same issue; however it should be solved by now.

Thanks!
