### ISSUE TITLE
id gets converted to null during Model.upsert if defined

### ISSUE THREAD

**Issue by jorgeramos** [strongloop/loopback#724]
I have exported my mongodb collection data into a JSON array which I'm processing to take into account a new schema and uploading to a different database. When I'm executing the Reservation.upsert command, if I declare the id property with mongodb's 24 byte string, the record is created but the id is set to null. If I omit the id property, then everything works fine. Can you please advise what may be going wrong?

BTW, as a test, I also tried Airline.upsert with data that has the defined id and that went through fine as expected.

##### Processed Reservation data before uploading
```json
{
  "id": "526ad8fd0dcd100000000515",
  "token": "UJKERD",
  "other_fields": "...",
  "departureFlightId": "532072a2ea6dad0000000055",
  "returnFlightId": "536a5b36d6d418000000026b"
}
```
#####  Logged response from mongodb after record inserted. Notice the id is null but the defined relations like departureFlightId are showing up properly
```json
{
  "id": null,
  "token": "UJKERD",
  "other_fields": "...",
  "departureFlightId": "532072a2ea6dad0000000055",
  "returnFlightId": "536a5b36d6d418000000026b"
}
```

**Comment by Amir-61** [comment]
Hi @jorgeramos,

Please share the repo or re-produce the issue using [loopback-sandbox](https://github.com/geekguy/loopback-sandbox). Also, for this type of question we encourage you if you can ask the question on  our [Google community](https://groups.google.com/forum/#!forum/loopbackjs)...

Thanks!

**Comment by Amir-61** [comment]
I'm closing this ticket due to inactivity. Please feel free to open a new ticket if you face the same issue.

Thanks!
