### ISSUE TITLE
How can i use method password to generate new password ?

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#727]
Currently, i see that in user.js we have method :
```javascript
UserModel.setter.password = function(plain) {
    var salt = bcrypt.genSaltSync(this.constructor.settings.saltWorkFactor || SALT_WORK_FACTOR);
    this.$password = bcrypt.hashSync(plain, salt);
  }
```
How can i use this method ?

**Comment by loay** [comment]
Hi @bluestaralone  
Is this issue still relevant or it has been fixed?
Thanks

**Comment by loay** [comment]
Hi @bluestaralone 
The issue is closed for now. If you are still running into problems, feel free to leave a comment and I will reopen the issue.
Thanks.
