### ISSUE TITLE
How to define method in relation?

### ISSUE THREAD

**Issue by Spark-star** [strongloop/loopback#728]
Hi, everyone.
I want to know how to define method in relation?

In my app:
A hasmany B, B blongsTo A ;
The route "/a/:id/B/:fk" , Corresponding method  is "updateById__bs"
Can I define method "test" in relation "hasMany", that can display "/a/:id/B/:fk/test" which corresponding method is "test_bs", and how?
THX

**Comment by superkhau** [comment]
@Spark-star Has the issue been resolved? Can I close it?
