### ISSUE TITLE
Multiple hasAndBelongsToMany relations between the same two models

### ISSUE THREAD

**Issue by wtfribley** [strongloop/loopback#732]
**common/models/me.json**

``` js
{
  "name": "Me",
  "base": "PersistedModel",
  "properties": {}
  "relations": {
    "aunts": {
      "type": "hasAndBelongsToMany",
      "model": "Relative",
      "foreignKey": ""
    },
    "uncles": {
      "type": "hasAndBelongsToMany",
      "model": "Relative",
      "foreignKey": ""
    }
  }
}
```

**common/models/relative.js**

``` js
{
  "name": "Relative",
  "base": "PersistedModel",
  "properties": {},
  "relations": {}
}
```

This kind of relationship -- i.e. multiple relationships between the same two models -- works for `hasMany` relationships. But that same behavior appears to be unsupported for `hasAndBelongsToMany`. Are there plans to add support? Is there a way to "manually" set up this kind of relationship?

**Comment by dancingshell** [comment]
@raymondfeng can you shed light on if this is possible to do with just the json model definitions?

genre.json
```
"posts": {
  "type": "hasAndBelongsToMany",
  "model": "Post"
},
```

post.json
```
"genres": {
  "type": "hasAndBelongsToMany",
  "model": "Genre"
},
```

this results in the table in postgres `genrepost`. what I really want is the table `postgenre`. when I add `"through": "postGenre"` to both definitions and migrate the models dont get created.

**Comment by hyperd** [comment]
@raymondfeng @wtfribley sorry to bring this issue back but is this feature currently available? Seems that `hasAndBelongsToMany` relations are omitting the `through` model that's specified
