### ISSUE TITLE
How can i use ttl attribute of property ?

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#733]
```JSON
"ttl": {
      "type": "number",
      "ttl": true,
      "default": 5,
      "description": "time to live in seconds (5 seconds by default)"
    },
```
As you see in the JSON i set ttl for current model is 5 seconds but it wasn't deleted automatically.

**Comment by superkhau** [comment]
@Spark-star Is this issue good to close?

**Comment by Amir-61** [comment]
Is this ticket good to close?

**Comment by Amir-61** [comment]
I'm closing this ticket due to in activity for months. Please feel free to open it if you run into the same issue.

Thanks!

**Comment by redevill** [comment]
Boy you guys are useless

**Comment by redevill** [comment]
Quite a legit problem -> to be able to set the ttl to a value of your choosing, and you have no answer?

On your client side you can Hack it in: this.http.post('api/user/login', {email: email, password: password})

**Comment by redevill** [comment]
Posted too soon... but anyway - you can add it to the credential json object - as a hack.

**Comment by redevill** [comment]
Alternately: You can have a common model that overrides the login function.
*.js file
module.exports = Employees => {
    Employees.on('dataSourceAttached', model => {
        const login = Employees.login;
        Employees.login = function (credentials, include, cb) {
            credentials.ttl = MyCustomTTLValue;
            return login.call(this, credentials, include, cb);
        };
    });
};

*.json specify the user as base
{
  "name": "employees",
  "base": "User", ... etc

**Comment by oderayi** [comment]
@redevill

 You're doing a better job than the loopback team. Thanks man! Works for me!

**Comment by heshamelmasry77** [comment]
@behindtheshadow  and how your .json looks like ?
for example what i am trying to approach is to have a ttl or whatever property and it expire after certian time.
i added as you said :  in my .js
```
'use strict';

module.exports = function(Room) {
  Room.settings.ttl = 5;
};

```
and on my .json i added
```
"ttl": {
      "type": "number",
      "ttl": true,
      "default": 5,
      "description": "time to live in seconds (5 seconds by default)"
    }
```

but nothing happened
