### ISSUE TITLE
How can i set multiple include with filter on include models ?

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#735]
``` javascript
Post.find({
  include: {
    relation: 'owner', // include the owner object
    scope: { // further filter the owner object
      fields: ['username', 'email'], // only show two fields
      include: { // include orders for the owner
        relation: 'orders', 
        where: {orderId: 5} // only select order with id 5
      }
    }
  }
}, function() { ... });
```

As your example in document i just see that it supports to include only one model and submodel but i want to include more than one how can i do that ? Please help me, thanks much.

**Comment by beat84** [comment]
And if the relation is a HasManyThrough type, how can I include a filter on the through model?
For instance:
Model A has Model C through Model B.
Model B has modelAId and modelCId obviously, and a boolean field (filteringFld).
Is it possible querying it to get all the Model C for Model A where the filteringFld of Model B is true?

**Comment by roychoo** [comment]
yeah i wan to know this too.

**Comment by F3L1X79** [comment]
I'd like to know too, if this is possible. Thanks by advance.

**Comment by lesterzone** [comment]
It's possible to include `where` on filter and includes ? I researched but no luck.

```js
Book.find(
{
  where: {userId: id},
  include: {
    relation: 'owner',
    where: {id: ownerId }
  }
}, function() {....});
```

I'm missing something? I tried 


```js
Book.find(
{
  where: {userId: id},
  include: {
    relation: 'owner',
    scope: {
      where: {id: ownerId }
    }
  }
}, function() {....});
```

Thank you.

**Comment by hellsan631** [comment]
I believe you can use a scope for that 'where' filter.

```
Book.find(
{
  where: {userId: id},
  include: {
    relation: 'owner',
    scope: {
       where: {id: ownerId }
    }
  }
}, function() {....});
```

On another note, It seems like, currently, the filters are bugged when you send them in as objects instead of array's.

Example system:

I have 3 objects. Locations, Media, and People. Each location hasMany Media, and each Media belongsTo Person (a very basic gallery).

I want to get a list of each location, each locations media, and each of those media's person, to use for a category filter for each location. This is a lot of data for a big system, so I want to limit each of the include scopes only to one field, 'category', for both media and person.

```json
{
  "relation": "media",
  "scope": {
	"fields": {"id": true, "category": true, "personId": true, "person": true},
	"include": {
	  "relation": "person",
	  "scope": {
		"fields": {"id": true, "category": true},
	  }
	}
  }
}
```

Returns (Actual)

```js
Locations = [
  {
    id: 123,
	category: 'guide'
    media: [
	  {itemId: 123},
	  {itemId: 123},
	  {itemId: 123}
	]
  }
]
```

Returns (Expected)

```js
Locations = [
  {
    id: 123,
	category: 'marina'
    media: [
	  {id: 124, category:'freshwater', person: {id: 1, category: 'guide'}},
	  {id: 125, category:'fly-fishing', person: {id: 1, category: 'guide'}},
	  {id: 126, category:'freshwater', person: {id: 2, category: 'lodge-resort'}},
	]
  }
]
```

As a work around, I have to use a fields filter that uses both arrays AND an object. This filter correctly produces the above expected results.

```json
/* This Works */
{
  "relation": "media",
  "scope": {
	"fields": ["id", "category", "person", "personId"], /*I need to include both Person and PersonID fields for this to work*/
	"include": {
	  "relation": "person",
	  "scope": {
		"fields": {"id": true, "category": true},
	  }
	}
  }
}
```

**Comment by lesterzone** [comment]
Thanks @hellsan631 we have locked versions and looks like it's not possible with our versions.

**Comment by sonia1588** [comment]
Hi,

I have a couple of queries on field filters 
1. I tried following query to exclude date property from response as below. Which is not working.
{"include": { "relation": "orders","scope": { "fields": {"date":false}}} }

2.  fields filters doesn't works with embedded relations.However it works with where filter using dot notation. I tried as below
{"fields":{"billingAddress.street":true}}

**Comment by renegat59** [comment]
Hi!
I have a very simple query that is failing the same way as @bluestaralone. I can't figure out what I can do. The code:

>
Recipe.find({
      fields: {
        title: true,
        slug: true
      },
      include: {
        relation: 'tags'
      }
    }, function(err, recipes){
      cb(err, recipes);
    });

Recipe has relation "hasAndBelongsToMany" to Tag. With this query I am always getting empty tags. When I run the same query without "include" then the Tags are propagated. Any ideas what I am doing wrong?

**Comment by hellsan631** [comment]
@renegat59 try including the fields you want for tags as well.

ex: 
```js
const filter = {
      fields: {
        title: true,
        slug: true
      },
      include: {
        relation: 'tags',
        scope: {
          fields: {"id": true, "text": true} //or what ever tag fields you have
        }
      }
    };

Recipe
  .find(filter)
  .then((recipies) => {
    // might be populated with recipes and tags
  });
```

**Comment by Moelgaard85** [comment]
Here is the fix to have fields filter on the main filter and at the same time, have an include relation (also with field filters if wanted). Solution is to include the foreign key as a field, because that field is needed to "connect" the relation:

NOT WORKING: 
```
filter: {
   fields: ['id', 'title'],
   include: {
     'relation': 'Resources',
     'scope': {
       'fields': ['type', 'path']
     }
   }
}
```
WORKING:
```
filter: {
   fields: ['id', 'title', 'resourceId'],
   include: {
     'relation': 'Resources',
     'scope': {
       'fields': ['type', 'path']
     }
   }
}
```

**Comment by style2joy** [comment]
As in @Moelgaard85's example above I noticed if 'resourceId' is null then property for related object/array doesn't get created. it will help if the result is consistent and include all properties even when blank

**Comment by amandeep33** [comment]
How to include only one property from included relation model as property only not as object.
For eg:
```
"scope": {
    "include": [
      {
        "relation": "brand",
        "scope": {
          "fields": "brandname"
        }
      }
    ]
  }
```
is returning:
```
"brand": {
    "brandid": 1,
    "brandname": "Audi"
  }
```
but I want this as:
`brand:"Audi"`
Any Help?

**Comment by hellsan631** [comment]
@amandeep33 	

your best bet is to write a little function that takes the data for each object and manipulates it like you want. Your not going to get your data like that from loopback.

```js
mutateBrand({ brand }) {
  return brandname;
}

brands = brands.map(mutateBrand);
```
