### ISSUE TITLE
How to set  the "ttl" property?

### ISSUE THREAD

**Issue by Spark-star** [strongloop/loopback#736]
Hi ,everyone
I want to create a 'accessToken' which more than '129600'.
I define 'ttl' equal '31449600' in my 'account' model which extend from 'user' model.

In my opinion , when I log in  the 'accessToken' should like this
 {
"id": "8BDly7JTas4kOmddwsqdy44oZrOEmc6xJHEE0geWQGkrGvkJZyeS4xy3pXSpaxMnBhU",
  "ttl": 31449600,
  "created": "2014-11-04T10:22:05.700Z",
  "userId": "5457240cac1da089335c43a9"
}
but it doesn't , the 'ttl' is remain '129600'.

How can I override the ttl?
THX

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by heshamelmasry77** [comment]
@superkhau  you didn't do anything helpful just closed his issue which can help me now in 2019 if someone answered it :S
