### ISSUE TITLE
Move Component System docs to Confluence 

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#748]
When we are ready to release, move the following to Confluence, edit, and integrate with other docs:
https://github.com/strongloop/loopback-example-component/wiki.

NOTE: Moved from https://github.com/strongloop-internal/scrum-loopback/issues/33

**Comment by bajtos** [comment]
The loopback-example-component link no longer works. I am closing this issue as no longer relevant. @crandmck feel free to reopen.
