### ISSUE TITLE
Doc navigation doesn't display on mobile

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#749]
There is no way to navigate the docs on mobile devices hence making the docs useless when browsing on a mobile device/tablet. Jimmy's metrics for the last 6 months:
- 99% of current users are viewing on desktop, making this ticket less of a priority
- 1% of users are on mobile (its possible they are trying to view the docs, failing and giving up)

So it may not be a priority.  In any case, the best way to address this is likely via a Confluence add-on, e.g. http://www.refinedwiki.com/en/display/products/mobile-interface-confluence.aspx

NOTE: Moved to https://github.com/strongloop-internal/scrum-loopback/issues/49

**Comment by bajtos** [comment]
Hello, as part of our triage process, I am closing issues that have been inactive for extended period of time. Please leave a comment if you think this issue is still relevant and should be reopened.
