### ISSUE TITLE
Improve docs for model mixins

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#750]
Since the API docs don't show the inheritance hierarchy, we need to document manually the properties and methods that each kind of model gets.  Ideally, we could show all properties and methods available for a given object, included inherited ones, ala JavaDoc.

We currently have these:
 - http://docs.strongloop.com/display/LB/Model+property+reference
 - http://docs.strongloop.com/display/LB/Connected+model+class
 - http://docs.strongloop.com/display/LB/Basic+model+object

But these are scattered and need to be consolidated coherently.

NOTE: Moved from https://github.com/strongloop-internal/scrum-loopback/issues/37

**Comment by teone** [comment]
As I had some trouble finding `mixin` documentation, here is an example: https://github.com/clarkbw/loopback-mixins-example

from: https://github.com/strongloop/loopback/issues/1349

**Comment by crandmck** [comment]
Thanks.  We just added http://docs.strongloop.com/display/LB/Defining+mixins, and I'll be working on adding more asap.

**Comment by clarkbw** [comment]
I moved my example repo to https://github.com/strongloop/loopback-example-mixins /cc @teone

**Comment by gunjpan** [comment]
@bajtos / @crandmck :In [Connected model object docs](https://docs.strongloop.com/display/LB/Connected+model+object)
>In addition to the methods of the Basic model object, the following are mixed in when a model is connected to a data source:
    `RelationMixin` class
    `PersistedModel` class

Besides above two classes, I noticed that `Basic model` object also gets `static` and `instance` methods of [`DataSource` class](https://apidocs.strongloop.com/loopback-datasource-juggler/#datasource).
Could you please verify it so that I can make changes in the docs?!

**Comment by gunjpan** [comment]
@crandmck : Please review the draft for [**Defining mixins**](https://docs.strongloop.com/display/LB/Defining+Mixins+-+Draft)
It's a copied page and restricted from Public.
Thank you.

**Comment by crandmck** [comment]
I reviewed your draft and made a few small edits.  It LGTM, so I copied it into https://docs.strongloop.com/display/LB/Defining+mixins and removed your hidden draft page.
Thanks!
