### ISSUE TITLE
When i set fields on main filter, all of include info is disappeared

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#753]
Bug: When i set fields on main filter, all of include info is disappeared.
Ex: In my example when i run find function i just got only 'title', 'description' and don't have 'owner' info. at least if it is empty please show null value or something like that.

``` javascript
Book.find(
{
  where: {userId: id},              
  fields: ['title', 'description'],
  include: {
    relation: 'owner',
    scope: {fields: ['id', 'name']}
  }
}, function() {....});
```

@raymondfeng 
@bajtos 
I moved this bug into new one. Please check and fix it. Thanks much.

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by benmarten** [comment]
+1

**Comment by raymondfeng** [comment]
@bluestaralone Can you try to add the foreign keys of the relation to your fields?

**Comment by benmarten** [comment]
Thanks Raymond!

That works :)

    {
        "fields": [
            "name",
            "userId"
        ],
        "where": {
            "createdDate": {
                "gte": "2015-05-18T00:00:00.000Z"
            }
        },
        "include": {
            "relation": "user",
            "scope": {
                "fields": [
                    "firstName",
                    "email"
                ]
            }
        }
    }

**Comment by bluestaralone** [comment]
@raymondfeng : Thanks, i know the reason why it doesn't work. now i know how to correct it.

**Comment by bajtos** [comment]
IMO, LoopBack should add the foreign keys automatically. I am reopening this issue to keep track of that.

**Comment by fabien** [comment]
@bajtos +1

**Comment by bluestaralone** [comment]
@bajtos :+1:
