### ISSUE TITLE
Ability to specify Notes and Description for resolved relation functions

### ISSUE THREAD

**Issue by brainthinks** [strongloop/loopback#765]
This feature is potentially related to #209, but is a little different in that it does not seek to define new methods, but rather override properties of dynamically generated (resolved) remote methods.

The problem I am having is that after developing the necessary API, I do not have the ability to put any kind of additional notes in the Swagger docs for other developers (or for my future self) for resolved relation remote methods.  

I am currently able to access all non-resolved methods to edit them as follows:

``` javascript
var methodName = 'create';
var isStatic = true;
var method = Model.sharedClass.find(methodName, isStatic);
  if (method) {
    if (method.fn) {
      method.fn.notes = 'my notes';
      method.fn.description = 'my description';
    }
    method.notes = 'my notes';
    method.description = 'my description';
  }       
}
```

But since the resolved relation functions are generated every time they are asked for (via the resolver that is registered in `loopback/lib/model.js`), I cannot simply edit the notes and descriptions of the remote method definitions that are returned above, as they do not persist.

Currently, I do not know of a way to specifiy my own Notes and Descriptions for remote methods that are resolved relations.

I imagine that whatever you guys end up implementing for #209 will address this problem, but in the mean time, I think implementing the ability to add Notes and Descriptions overrides to resolved relation remote methods can be achieved separately, even if only temporarily (until #209 is fully implemented).  In this way, I will be able to give other devs and my future self any additional information directly in the Swagger docs, as I can for all other non-resolved methods.

A potential solution for this is to define the necessary overrides in the `model.json` file.  As an example, I am currently defining them in the `_remoteDocs` property, and accessing them via `Model.settings._remoteDocs`.  However, my implementation is incapable of touching the resolved relation remote method definitions that are defined in the following methods from `model.js`:

```
Model.belongsToRemoting()
Model.hasOneRemoting()
Model.hasManyRemoting()
Model.scopeRemoting()
```

It looks like I may be able to update the `Model.prototype[methodName]` for the first 3 functions (though I did not test this because it was not part of my specific use case), but for `scopeRemoting`, which is the use case I am currently dealing with, there is no way for me to override any of the options that get passed to `define()`, and there is no function that is passed in as `define`'s last parameter, so I cannot attach notes to that.

I think that you could add the following lines to each of the options json objects passed as the second parameter to `define()` inside of the `scopeRemoting` function:

``` javascript
// ...
// Perform necessary checks to ensure _remoteDocs and subsequent properties actually exist
// ...
description: this.settings._remoteDocs['__get__' + scopeName].description || 'Queries ' + scopeName + ' of ' + this.modelName + '.',
notes: this.settings._remoteDocs['__get__' + scopeName].notes : undefined,
// ...
```

And the corresponding `model.json` file would contain:

``` javascript
// ...
"methods": [],
"_remoteDocs": {
  '__get__buildings' : {
    'notes': 'my notes',
    'description': 'my description'
  }
}
```

at the end.  Such a solution would allow one to define their own description and notes on a per-function and per-model basis as it would be contained inside the model-specific json file.

**Comment by microvnhaxor** [comment]
![image](https://user-images.githubusercontent.com/7679875/29803782-665a99f0-8ca8-11e7-8112-2e60e8174c41.png)

I develop my API based on yours. But I want to edit the description for the Relational Model in the case above.

I want to edit the descriptions of relational models

Hope you can help me
