### ISSUE TITLE
Ability to hide model properties from Swagger and loopback-datasource-juggler independently

### ISSUE THREAD

**Issue by brainthinks** [strongloop/loopback#768]
Currently, one can mark model properties as hidden from `loopback-datasource-juggler` independent from what is hidden from `loopback-explorer`/Swagger.  This is evident in the source code by looking at `ModelBaseClass.isHiddenProperty` in `loopback-datasource-juggler/lib/model.js`:

``` javascript
// ...
var hiddenProperties = settings && (settings.hiddenProperties || settings.hidden);
// ...
```

I can set hidden properties in both `hiddenProperties` and `hidden` in my `model.json` file, and those properties will not be sent in responses containing the model in question.  If I choose to use the `hidden` property, those properties will also be hidden from Swagger, as seen in the `isHiddenProperty` function defined in `loopback-explorer/lib/model-helper`:

``` javascript
// ...
definition.settings.hidden.indexOf(propName) !== -1
// ...
```

What this means is that you have the ability to hide properties in responses that contain the models, but they will still show up in Swagger.  This feature would be fine if it were a two way street, meaning I could hide properties from Swagger but have them exist in model-containing responses.  Perhaps if the `isHiddenProperty` did a check on an additional, unique settings property:

``` javascript
// ...
definition.settings.hidden.indexOf(propName) !== -1 || definition.settings.hiddenFromExplorer.indexOf(propName) !== -1 
// ...
```

With such an implementation, I could hide a property completely by putting it in the `hidden` array, hide properties from being displayed in Swagger by putting those properties in `hiddenFromExplorer`, and prevent things from being returned in model-containing responses by putting those properties in the `hiddenProperties` array.

The best use case for this in my opinion is the ID field.  All of my IDs are auto-generated, so I don't want them to display in explorer/Swagger.  However, I do want the ID returned in my responses as it is necessary for many operations.

**Comment by seanxlliu** [comment]
I think we should re-open this thread to address the feature requirement

**Comment by bajtos** [comment]
@seanxlliu with LoopBack 4.0 GA publicly available, LoopBack 3 has moved into Active LTS mode and does not accept any new features (see our [Long Term Support policy](https://loopback.io/doc/en/contrib/Long-term-support.html)).

Feel free to open a new issue in [loopback-next](https://github.com/strongloop/loopback-next/issues/new) to discuss this feature requirement for LoopBack 4 and beyond.
