### ISSUE TITLE
Anonymous user support

### ISSUE THREAD

**Issue by reflog** [strongloop/loopback#770]
It would be extremely useful to provide support for anonymous users.

One of the scenarios is ecommerce use: we want to keep some information about the user even before he authenticated/signed up. It would be useful to create a User account with no info, except an id and allow converting it into a full-fledged account later on. This account could be used for storing  a shopping cart or some custom pre-login data.

For additional discussion on the subject, please see: 

https://groups.google.com/forum/#!topic/loopbackjs/BBJwezNljdM

**Comment by mercuriete** [comment]
+1
It would be nice if this feature came out the box on the framework.
I will try to implement this as you suggested.
Thank you for develop this amazing product. :)

**Comment by xinbenlv** [comment]
+1, will be very helpful. Thank you for the development

**Comment by dheavy** [comment]
Bumping on this thread. Thanks for keeping us updated whenever you can.

**Comment by jorgenfb** [comment]
This would really help create a better user experience. Only require the user to log in when needed, not before trying your application.

**Comment by philipheinser** [comment]
@raymondfeng Any updates on this one?

**Comment by elropero** [comment]
Bump

**Comment by noorrgb** [comment]
would be great to have this feature. Whats the current status of it?
