### ISSUE TITLE
How to add remote methods to the User model

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback#776]
I'd like to expose a method as rest api method but the documentation seems to be mostly referring to loopback 1.0. and my attempts were not successful. I'm using strongloop v2.9.2.

my intention is to expose the api as :

```
/users/{id}/mycarddetails/{fk}
```
- The api is supposed to be a wrapper for `/users/{id}/mycards/{fk}` with {include: "details" } as filter. 
- The api should return an instance of mycard with a relation "details" (mycard -> card-details) expanded.
- The api is restricted to the $owner.

The basic code I wrote (models/user.js):

```
module.exports = function(User) {

  User.mycarddetails = function(fk, cb) {
    cb(null, { name: 'test'});
  };

  User.remoteMethod(
    'mycarddetails',
    {
      description: 'Get the user card details by id',
      accepts: [
        //{ arg: 'id', type: 'number', required: true, description: 'User id'},
        { arg: 'fk', type: 'number', required: true, description: 'Foreign key for mycards' },
      ],
      http: { verb: 'get', path: '/mycarddetails/{fk}'},
      isStatic: false,
      returns: { arg: 'UserCard', type: 'object'}
    }
  );

};
```

This is what I get as a result:
![screen shot 2014-11-10 at 1 05 01 pm](https://cloud.githubusercontent.com/assets/2038264/4980983/1914bc26-6905-11e4-8614-1602e98595cc.png)

Notice that 1) the request url is not properly generated. 2) the method is not mapped.

I know things changed a bit around in loopback 2.0. What is your suggestion in this case?

**Comment by inawlaljar** [comment]
It's not working for me. signup doesn't showup in the explorer. Can anyone please help? 

module.exports = function(User) {

	User.prototype.signup = function(userData, callback){
		// Validate data
		// Save data - User
		// Create role mapping
		// return token
	}

User.remoteMethod(
    'signup', 
    {
      accepts: [{ arg: 'userData', type: 'object' }],
      returns: { arg: 'token', type: 'object' },
      http: { verb: 'post' }
    });
}

**Comment by jbcpollak** [comment]
@inawlaljar you probably already figured this out, but you are missing `isStatic: true`:

```
 User.remoteMethod(
    'signup', 
   {
     isStatic: false,
     accepts: [{ arg: 'userData', type: 'object' }],
     returns: { arg: 'token', type: 'object' },
     http: { verb: 'post' }
   });
}
```

**Comment by diegomoura637** [comment]
im using loopback over strongloop, when i make the remote method from my model user.js, exactly the same way than you makes, nothing happen, i need to setup any other file to it work?

**Comment by superkhau** [comment]
@diegomoura637 Please open your own new issue for us to resolve it. We usually don't check closed issues. However, in your case you need to extend the builtin User model to add remote methods. See https://github.com/strongloop/loopback-example-user-management/blob/master/common/models/user.json#L2-L3 and https://github.com/strongloop/loopback-example-user-management/blob/master/common/models/user.js#L4.
