### ISSUE TITLE
Insert Relationship Data - MSSQL

### ISSUE THREAD

**Issue by bitmage** [strongloop/loopback#781]
I'm unsure how to insert relationship data.  This is similar to https://github.com/strongloop/loopback/issues/705.

I'm using MSSQL for my data storage.

I have a Project with:

```json
  "relations": {
    "owner": {
      "type": "belongsTo",
      "model": "Owner",
      "foreignKey": "owner_id"
    },
    "contacts": {
      "type": "hasAndBelongsToMany",
      "model": "Contact",
      "foreignKey": "contact_ids"
    }
```

I have an `import` remote method, and I'd like to be able to save the models related to a Project without a long string of callbacks and/or using async.

I tried a POST to /projects, embedding the Owner and Contacts data:

```json
{
  "project": {
    "name": "My Project",
    "owner": {
      "name": "Texas"
    },
    "contacts": [
      {
        "first_name": "Bob",
        "last_name": "McKenzie"
      }
    ]
  }
}
```

No Owner record was created and the owner_id was not set.  I also tried creating a remote method called `import` and utilizing the build method:

```javascript
Project["import"] = function(body, done) {

  var project = new Project(body.project);
  project.owner.build(body.owner);
  project.contacts.build(body.contacts);

  return project.save(done);
};
```

But also in this case the Project was saved, but not the Owner or Contacts.

  1.  Am I supposed to be able to submit embedded documents?
  2.  Am I using the build method wrong?  Shouldn't it persist data when save() is called?
  3.  What is the recommended practice for this?  I can't find any documentation around *saving* model relationships, only about querying for them once they exist.

**Comment by raymondfeng** [comment]
I assume it's fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/352
