### ISSUE TITLE
how can i remove e-mail verification in the loopback framework?

### ISSUE THREAD

**Issue by LiuZeming** [strongloop/loopback#791]
user's  email  is not necessary in our business, i want to modify this value to other , how can i do it ?

**Comment by superkhau** [comment]
@bajtos @raymondfeng @ritch PTAL

**Comment by bajtos** [comment]
This is not supported at the moment, see https://github.com/strongloop/loopback/issues/820#issuecomment-76133701. Let's move the discussion to #1137.
