### ISSUE TITLE
Use of Express error pages

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback#797]
The default Express error pages are being used to display the errors. This can be potentially confusing for some developers, why they are seeing "Express", while they are using LoopBack.

A LoopBack formatted error page will also make LoopBack look better :)

**Comment by loay** [comment]
Hi @hacksparrow 
I don't think this is an issue anymore since the introduction of the `strong-error-handler`, unless you mean in a specific spot where it is still persisting.
