### ISSUE TITLE
Deprecate model hooks in docs

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#800]
Per https://groups.google.com/forum/#!topic/loopbackjs/rCodNgRjqow add examples of other model hooks to http://docs.strongloop.com/display/LB/Model+hooks.  Also explain that  the results are stored in ctx.result, not ctx.res. 

Ideally, all the model hooks would be added to the API docs as well.

**Comment by bajtos** [comment]
We are moving away from `beforeUpdate/afterUpdate` hooks in favour of [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks) and [Per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397).

@superkhau @crandmck is this issue still relevant?

**Comment by crandmck** [comment]
> We are moving away from beforeUpdate/afterUpdate hooks in favour of Operation hooks and Per-method hooks.

In that case, I will change this issue to be deprecating model hooks, if that is what we're doing.

**Comment by crandmck** [comment]
I added a note to the model hooks page. Closing this.
