### ISSUE TITLE
How can I access the belongsTo relation object from the afterCreate method?

### ISSUE THREAD

**Issue by djabif** [strongloop/loopback#803]
When I try to access an object in the afterCreate() hook method, I can't access to its belongsTo relations.

This is my model decision.json with a belongsTo relation named "profile"

``` json
{
  "name": "decision",
  "plural": "decisions",
  "base": "PersistedModel",
  "properties": {
    .....
    "profile_id": {
      "type": "string",
      "required": true
    }
  ...
  },
  "validations": [],
  "relations": {
    "profile": {
      "type": "belongsTo",
      "model": "UserProfile",
      "foreignKey": "profile_id"
    }
  },
  "acls": [],
  "methods": []
}
```

I have defined the afterCreate as follows. I can access the created object with the "this", and it has the "profile_id" property set correctly. 

``` javascript
Decision.afterCreate = function(next) {
      console.log(this); // this is the created object
}
```

Then when I try to access the <b>profile</b> of this object I get the following error:

``` javascript
this.profile(function(err, profile) {
    console.log(profile);
}
```

``` bash
TypeError: Object #<ModelConstructor> has no method 'profile'
```

How can I access the belongsTo relation object from the afterCreate method?

Thanks!

**Comment by zanemcca** [comment]
@superkhau I have the same issue except the related model I need to retrieve is done through a polymorphic relation. How do you recommend getting it?

**Comment by superkhau** [comment]
@zanemcca Not sure as I am not too familiar with polymorphic relations. @fabien Can you chime in here?

**Comment by zanemcca** [comment]
Thanks for the reply @superkhau. For the record I have a hackish solution where I use a switch statement on the polymorphic type property to find the appropriate model to query then I use the solution you gave above.

I am wondering though if there is anyway to get the order.customer() call to work within a hook as @djabif has asked? Could I define the hook in a different place that would load after the relations are known so that the API will work?

**Comment by fabien** [comment]
@zanemcca are you currently using `Model.observe('after save')`? It's odd that the relation accessor wouldn't work in this case.

**Comment by zanemcca** [comment]
@fabien Yes I am trying to access it from Model.observe('after save'). The ctx.instance.consumable is undefined and  ctx.instance.__get__consumable() returns undefined as well.

**Comment by jimmylimm** [comment]
The docs should really be updated to reflect this. Just spent at least 2 hours trying to figure out what was wrong with my model. Please update the loopback docs. Thanks @fabien @superkhau

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
@sequoia would you be able to take a look at this and determine what needs to be done re docs?
