### ISSUE TITLE
Add support for hierarchical phases

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback#805]
LoopBack usually builds a tree of express middleware to handle incoming HTTP requests, see an example at:

https://github.com/strongloop/loopback-gateway/wiki/Middleware-routes-in-loopback-gateway

We need to have a way to build and reference phases in a hierarchy. For example, we need to inject a middleware that audits all /api/users access. 

One idea is to allow a qualified phase name such as 'rest:user'.

**Comment by bajtos** [comment]
I believe this has been already implemented in #794. @raymondfeng feel free to reopen if you think there is more to implement as part of this user story.
