### ISSUE TITLE
About missing(?) methods/routes on relations

### ISSUE THREAD

**Issue by clarkorz** [strongloop/loopback#810]
### HasManyThrough
On the HasManyThrough relation, there are **link**, **unlink**, and **exists** methods, which can access  the through model. But I would like to be able to retrieve the through model, something like: 

```
GET /api/physicians/1/patients/1/rel ------ get *THE* appointment between patient 1 and physician 1
```

### HasOne
On the HasOne relation, there is only one method remoted currently: **get**. But I hope that **create**, **update**, **destroy** could be remoted too:
```
PUT /api/people/1/passport ---------- create A passport for the person or update *THE* passport of the person
DELETE /api/people/1/passport ------- destroy *THE* passport of the person
```

**Comment by bajtos** [comment]
Hey @clarkorz, I am afraid there has not been a high enough demand for us to implement this feature request. If this is still relevant to you then I suggest taking a look at the core code and seeing if you can implement the feature yourself. If you want to open up a PR and mention me directly in a comment, I will try my best to help you get the PR landed!
