### ISSUE TITLE
Support for throttling and metering? any recommendations on how to implement?

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback#815]
One of the essential requirements for a public api is the ability to apply throttling and metering to protect against abuse and performance degradation.

This is not necessarily best implemented as part of the framework as the scope might be big. I wanted to know your thought on the subject. Here's some points:

- Throttling and metering should be user or role specific. so that api calls from other components within a PaaS or microservice architecture can be excluded from any throttling constraints.
- Thinking about it from a commercial standpoint, Premium users can have different settings.
- It should have the ability to store usage per user for metering purposes. e.g. 100,000 calls per month per user for a basic plan.

I'm not looking for a quick answer. Please consider it a chance to jad on the topic and for other to provide their opinions.

**Comment by superkhau** [comment]
@simoami Is this good to close?

**Comment by simoami** [comment]
Yes, Thanks for the clarifications!
