### ISSUE TITLE
Documentation: Persisted Model page has inconsistent information

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback#818]
1. List of methods at the top has a link to not existing method: ```PersistedModel.update```
2. ```PersistedModel.updateAll``` has incorrect example: ```Employee.update(...)```, which I suppose is coming from here: https://github.com/strongloop/loopback/blob/master/lib/persisted-model.js#L229-229
3. It may be subjective (and more difficult to do, if the doc is generated from code), but the list of methods at the top has mixed methods of Model and Model instance, what make less readable.

**Comment by crandmck** [comment]
I believe all of these issues have been fixed: http://apidocs.strongloop.com/loopback/#persistedmodel no longer lists `update`; Example for `updateAll` is now correct; Ritchie enhanced strong-docs so it now separates static and instance methods.
