### ISSUE TITLE
Where do I find my access token??

### ISSUE THREAD

**Issue by dstroot** [strongloop/loopback#823]
What do I enter here:
![image](https://cloud.githubusercontent.com/assets/1438457/5065113/717730d0-6dcc-11e4-9435-e029bcbf1a3f.png)

Yes... I've searched.

**Comment by hvadotnarola** [comment]
while sending request for get user by id, how can token can be set, which i got from login response ? or its like manually we have to append in query string ?

**Comment by totymedli** [comment]
Here is a little summary from what I found out about authentication in LoopBack:

To get an access token you have to POST your user model's `login` route. The access token will be in the response's `id` field. You can also search for it in your database's `AccessToken` table. Just filter it by your user's id.

If you use Passport with LoopBack, you have to use the route you set in the `providers.json` file's `authPath` property. In this case the access token will be saved in a cookie called `access-token`. You can setup LoopBack to search for the access token in the cookie by placing the following code into `server.js`:

```js
app.use(loopback.token({
  cookies: ['access-token'],
  headers: ['access-token', 'X-Access-Token'],
  params: ['access-token', 'access_token']
}));
```

This code will also look for the token in the request header and the URI parameters. Feel free to remove the techniques you don't want to use when searching for the access token.

**Comment by janbaykara** [comment]
@totymedli to clarify, if I want to `User.logout()` with a passport+loopback setup, does `loopback.token()` store the accessToken as a property anywhere?

**Comment by totymedli** [comment]
@janbaykara The access token is stored in the cookies:
- `document.cookie` on the frontend
- `req.headers.cookie` on the backend

So you can retrieve it from there and call the logout endpoint with it.

Example for cookie retrieval on the backend in a route:

```js
module.exports = function (server) {
  let router = server.loopback.Router()
  router.get('/', (req, res) => {
    res.send(req.headers.cookie)
  })
  server.use(router)
}
```

**Comment by janbaykara** [comment]
Sure. I just found I had to use regex to acquire the actual accessToken. Namely:
```
var accessToken = req.headers.cookie.match(/access_token=s%3A([A-z0-9]+)/);
```
I assumed loopback would have had some kind of helper method to acquire it.
