### ISSUE TITLE
Document `Model.definition.settings.hidden`

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#832]
See https://github.com/strongloop/loopback-datasource-juggler/pull/100 and https://github.com/strongloop/loopback/issues/233

Example of how to use the setting can be found in the built-in User model: [common/models/user.json](https://github.com/strongloop/loopback/blob/7a877e91fe69c005077e56c67744c1d88e063182/common/models/user.json#L32)

**Comment by crandmck** [comment]
@bajtos Can you explain what it means for a prop. to be "hidden"?

**Comment by bajtos** [comment]
@crandmck A hidden property is not send in the JSON data returned in the server response. An example of a hidden property is `User.password`.

**Comment by crandmck** [comment]
OK, thanks @bajtos.  I added to http://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Hiddenproperties.  
Is the value of the "hidden" key always an array of strings?  Can it be anything else? I assume that each string must match the name of a property, right? 

This is minimal reference documentation.  If you have any suggestions of where else to mention it in the docs, please let me know.

**Comment by bajtos** [comment]
> Is the value of the "hidden" key always an array of strings? Can it be anything else? I assume that each string must match the name of a property, right?

Yes, it's always an array of strings and the strings must match existing property names.

> This is minimal reference documentation. If you have any suggestions of where else to mention it in the docs, please let me know.

I think it makes sense to mention this in places where we are describing REST API exposed by Models and also in the place where we show how to hide remote methods from the API.

**Comment by crandmck** [comment]
OK, I added that info, and cross-referenced from:
 - [Exposing models over REST](http://docs.strongloop.com/display/LB/Exposing+models+over+REST#ExposingmodelsoverREST-Hidingproperties)
 - [Security considerations](http://docs.strongloop.com/display/LB/Security+considerations#Securityconsiderations-Hidingproperties)

I'm going to go ahead and close this since we're trying to wrap up the sprint.  Let me know if you think I need to xref anywhere else.
