### ISSUE TITLE
Improve remote hooks doc

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#839]
- In beforeRemote/afterRemote, there are just a few examples listed, with no clear rules for the method filter, and examples don't even all work... I tried using "*.save" in an afterRemote hook for when I called user.$save() using the angular API.  By using setting it to *, I found that ctx.methodName was set to user.upsert when I call user.$save().  Through trial and error, I found that using "upsert" triggers the hook.  I tried *.upsert, user.upsert, User.upsert and prototype.upsert...none of which worked.  
- What exactly are the rules for wildcards?  what is the difference between *, ** and *.*?
- Could we get a list of the default method names?  Which ones pass data into the second callback arg, and what is the data?  Where would I look in the code to find this?
- It seems that the second arg is usually (always?) the same as ctx.result.  I'm assuming it's better to modify the data in ctx.result?
- There is a note that the value of ctx.result may not always be available.  Does this mean just that not all methods return data, or that sometimes they do, but it's not available in the ctx?
- The ctx object, itself:  The page says that it provides a set of consistant APIs, but nothing about what those APIs are.  From examples on the page, I can see: methodName, result, req, res, and req.accessToken. ...by printing it to the console I can see several other properties, but not really sure how to, or if I even should be using them...

**Comment by kidwm** [comment]
I have spent much time to find out how to set a hook for `PUT /api/Models`, more examples or method list would help.

**Comment by crandmck** [comment]
@kidwm I will try to prioritize this work.  If you have any helpful examples or insights based on the time you spent, or even specific questions, I would greatly appreciate you sharing them here.

**Comment by kidwm** [comment]
This is the snippet of my use case.
`Transaction.afterRemote('prototype.updateAttributes', function(context, model, next) {
    if (context.req.body.status == 'finish' )
      model.list().forEach(function(item) {
        item.doneAt = new Date();
        item.save();
    next();
  });`

**Comment by crandmck** [comment]
@ritch - I updated docs based on our discussion.  Pls review when you have a moment.

**Comment by ritch** [comment]
LGTM (although all I looked at was https://docs.strongloop.com/display/LB/Remote+methods)

**Comment by crandmck** [comment]
Actually @ritch the article in question is https://docs.strongloop.com/display/LB/Remote+hooks.
Sorry, I should have linked you to it.

**Comment by ritch** [comment]
Looked at the diff and it all checks out. :+1: LGTM

**Comment by crandmck** [comment]
Thanks!
