### ISSUE TITLE
Question: how can you add created/updated properties that automatically populate?

### ISSUE THREAD

**Issue by tanis2000** [strongloop/loopback#844]
I would like to add created/updated properties to a model and define rules for them so that if it's a new object, created and updated will be set to new Date(). And if it's an update, only updated would be set to new Date().

Is there a way to accomplish this with Loopback's models?

**Comment by superkhau** [comment]
Please post questions to https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.
