### ISSUE TITLE
Error: Invalid workspace: no facets found.

### ISSUE THREAD

**Issue by panduroab** [strongloop/loopback#845]
Hi, I can create and run a new loopback project, but when I try to create a new Module into the path project this error aperce:

**slc loopback:model**

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Invalid workspace: no facets found.
    at /usr/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/models/workspace.js:262:10
    at /usr/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback-datasource-juggler/lib/dao.js:833:7
    at /usr/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:345:7
    at process._tickCallback (node.js:419:13)
```

I have Ubuntu 14.04 and strongloop v2.9.2

```
strongloop v2.9.2 (node v0.10.33)
├── strong-build@1.0.1-2
├─┬ strong-supervisor@1.1.1
│ └── strong-agent@1.0.3
├── node-inspector@0.7.4
├── strong-deploy@1.0.0
├── strong-pm@1.3.1
├── strong-registry@1.1.2
├── nodefly-register@0.3.3
└── generator-loopback@1.5.1
```

I tried uninstall and install strongloop again but it didn't work, what else I can try?

Thanks

**Comment by superkhau** [comment]
@panduroab Did @Cosmin-Parvulescu's solution work for you? Is this good to close?

**Comment by dmasson** [comment]
Mac OSX 10.10.05, .. I double checked executing the command on the project directory, getting same error, ..

**Comment by dmasson** [comment]
No, It wasn's a typo, .. after checking out:

git clone https://github.com/strongloop/loopback-getting-started.git

I run (inside the loopback-getting-started directory):

slc loopback:datasource

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /Users/danielmasson
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Invalid workspace: no facets found.
    at /usr/local/lib/node_modules/strongloop/node_modules/generator-loopback/node_modules/loopback-workspace/common/models/workspace.js:287:14
    at /usr/local/lib/node_modules/strongloop/node_modules/loopback-datasource-juggler/lib/dao.js:1519:9
    at Object.async.each (/usr/local/lib/node_modules/strongloop/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:153:20)
    at allCb (/usr/local/lib/node_modules/strongloop/node_modules/loopback-datasource-juggler/lib/dao.js:1455:13)
    at /usr/local/lib/node_modules/strongloop/node_modules/loopback-datasource-juggler/lib/connectors/memory.js:372:7
    at doNTCallback0 (node.js:419:9)
    at process._tickDomainCallback (node.js:389:13)
    at process.<anonymous> (/usr/local/lib/node_modules/strongloop/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:19:15)

**Comment by JakePeyser** [comment]
Same error when running [this workshop step](https://github.com/IBM-Bluemix/real-time-tone-analysis/tree/master/WORKSHOP/STEP3-DATABASE) on a Windows 7 machine. Everyone else, even other Windows 7 users, was able to complete the steps successfully.

```
C:\MyTestLoopBack>slc loopback:model

events.js:141

      throw er; // Unhandled 'error' event

      ^

 

Error: Invalid workspace: no facets found.

    at C:\Users\AC06752\AppData\Roaming\npm\node_modules\strongloop\node_modules

\generator-loopback\node_modules\loopback-workspace\common\models\workspace.js:2

87:14

    at C:\Users\AC06752\AppData\Roaming\npm\node_modules\strongloop\node_modules

\loopback-datasource-juggler\lib\dao.js:1561:9

    at Object.async.each (C:\Users\AC06752\AppData\Roaming\npm\node_modules\stro

ngloop\node_modules\loopback-datasource-juggler\node_modules\async\lib\async.js:

153:20)

    at allCb (C:\Users\AC06752\AppData\Roaming\npm\node_modules\strongloop\node_

modules\loopback-datasource-juggler\lib\dao.js:1497:13)

    at C:\Users\AC06752\AppData\Roaming\npm\node_modules\strongloop\node_modules

\loopback-datasource-juggler\lib\connectors\memory.js:435:7

    at nextTickCallbackWith0Args (node.js:415:9)

    at process._tickDomainCallback (node.js:385:13)

    at process.<anonymous> (C:\Users\AC06752\AppData\Roaming\npm\node_modules\st

rongloop\node_modules\loopback\node_modules\continuation-local-storage\node_modu

les\async-listener\index.js:19:15)
```
