### ISSUE TITLE
ACLs for model properties

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback#846]
I've come across several [code](https://github.com/strongloop/loopback/blob/master/test/acl.test.js#L230-L241) [samples](http://apidocs.strongloop.com/loopback-datasource-juggler/#datasource-prototype-createmodel) hinting at the ability to declare ACLs per-property:

```
      name: {
        type: String,
        acls: [
          {principalType: ACL.USER, principalId: 'u001',
            accessType: ACL.WRITE, permission: ACL.DENY},
          {principalType: ACL.USER, principalId: 'u001',
            accessType: ACL.ALL, permission: ACL.ALLOW}
        ]
      }
```

However, it seems that ACLs declared this way in my model.json are not being applied. Am I doing this wrong, or is it as of yet unimplemented?

**Comment by yagop** [comment]
Any update on this.
