### ISSUE TITLE
Failing user.test.js test

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback#852]
I generated a project with `slc loopback` and copy/pasted the `./node_modules/loopback/test/user.test.js` into its test directory. I also setup `Makefile` and ran `npm install loopback-testing --save-dev` ... my goal was to see the test succeed as a sanity check.

But instead it failed:

```
User "before each" hook:
     AssertionError: cannot autoAttach model "PersistedModel". No dataSource found of type db
      at Function.registry.autoAttachModel (node_modules/loopback/lib/registry.js:417:5)
      at Function.<anonymous> (node_modules/loopback/lib/registry.js:408:12)
      at Array.forEach (native)
      at Function.registry.autoAttach (node_modules/loopback/lib/registry.js:403:23)
      at Context.<anonymous> (test/user.test.js:20:14)
```

Googling yielded a remote reference to issue #155 but I'm not sure how it applies here. Thoughts?

**Comment by superkhau** [comment]
Please create a test project on Github to reproduce the issue as per https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by pulkitsinghal** [comment]
I will but it may take me 2 weeks before I get around to it :(

**Comment by superkhau** [comment]
Any help is appreciated. ;) We'll see what we can do in terms of priority.

**Comment by 0candy** [comment]
@pulkitsinghal  Is this issue still reproducible for you?

**Comment by pulkitsinghal** [comment]
Ok so I started working on this via loopback-sandbox but now I see that loopback-testing itself is going away and although I don't know what will replace it ... I guess there isn't much point in taking this forward.
