### ISSUE TITLE
Can't Use HasManyThrough When The From And To Models Are The Same 

### ISSUE THREAD

**Issue by idosh** [strongloop/loopback#859]
I want to implement a followers-followee mechanism (like Twitter).
I defined these relations in my user model:

    "followers": {
         "type": "hasMany",
         "model": "User",
         "foreignKey": "followerId",
         "through": "Follower"
     },
     "follows": {
        "type": "hasMany",
        "model": "User",
        "foreignKey": "followeeId",
        "through": "Follower"
     }

and this relation in my followers table:
     "follower": {
        "type": "belongsTo",
        "model": "User",
        "foreignKey": "followerId"
     },
     "followee": {
        "type": "belongsTo",
        "model": "User",
        "foreignKey": "followeeId"
     }

When I try to add a new follower only one foreign key is being set because the two foreign keys are resolved to same key (in my case to the followerId key) in the `throughKeys` method.

**Comment by PymZoR** [comment]
Same issue here.

**Comment by raymondfeng** [comment]
Duplicate of https://github.com/strongloop/loopback-datasource-juggler/pull/394
