### ISSUE TITLE
Replication and paging

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#866]
Consider the case when the server database has thousands of records, but we want to replicate only subset of them (a first page, let's say 1-10 out of 1000), incrementally adding more pages when requested while online.

A possible solution is some sort of lazy replication, where only a subset of records is replicated and there is an API to fetch more records.

**Comment by BerkeleyTrue** [comment]
is there any update on this? Would love to get pagination work. Currently trying to run this with 2500 model instances crashes completely. Pagination would solve this issue.

**Comment by bajtos** [comment]
AFAICT, the current implementation discards all filter fields except where. See [persisted-model.js#L809-L812](https://github.com/strongloop/loopback/blob/70ca7c51b465c0b282a7e4663e83a6d47b29b3d1/lib/persisted-model.js#L809-L812).

@BerkeleyTrue I am afraid the offline sync is not a high priority for us at the moment. Do you have any ideas on how the pagination could be implemented under the hood? Could you contribute this feature yourself?

**Comment by BerkeleyTrue** [comment]
I Would love too but currently operating two other projects and actively converting a site to loopback from mongoose/express/custom routes. This would have to wait a couple of weeks.
