### ISSUE TITLE
Default model value erase unset values when upserting

### ISSUE THREAD

**Issue by PuKoren** [strongloop/loopback#867]
When upserting, the default model values erases the fields that are not updated.
This behaviour is not the same when using mongodb connector or memory connector

Exemple:
My model defined as:

``` json
{
  "name": "Device",
  "plural": "Devices",
  "base": "PersistedModel",
  "properties": {
    "deviceId": {
      "type": "string",
      "id": true,
      "required": true
    },
    "culture": {
      "type": "string"
    },
    "phoneNumber": {
      "type": "string"
    },
    "imei": {
      "type": "string"
    },
    "createdAt": {
      "type": "date"
    },
    "updatedAt": {
      "type": "date"
    }
  }
}
```

And using default value for createdAt with:  

``` javascript
Device.definition.rawProperties.createdAt.default =
Device.definition.properties.createdAt.default = function() {
    return new Date();
};
```

And creating a model instance with:

``` javascript
this.upsert({
            'deviceId': 'PHONE_UNIQUE_ID',
            'culture': 'EN_UK',
            'imei': 'UNIQUE_IMEI',
            'phoneNumber': '+44940395039',
            'updatedAt': new Date()
        });
```

The resulting data in the memory database is:

``` json
{
    "_id": "PHONE_UNIQUE_ID",
    "culture": "EN_UK",
    "phoneNumber": "+44940395039",
    "imei": "UNIQUE_IMEI",
    "updatedAt": {
        "$date": "2014-11-26T13:53:43.783Z"
    },
    "createdAt": {
        "$date": "2014-11-26T13:53:43.783Z"
    }
}
```

This seems ok to me, and when I try to update the model 10 seconds later using the same upsert call, I have the following result in memory:

``` json
{
    "_id": "PHONE_UNIQUE_ID",
    "culture": "EN_UK",
    "phoneNumber": "+44940395039",
    "imei": "UNIQUE_IMEI",
    "updatedAt": {
        "$date": "2014-11-26T13:53:53.783Z"
    },
    "createdAt": {
        "$date": "2014-11-26T13:53:53.783Z"
    }
}
```

As you can see createdAt is updated with the default value (new Date()).

Is it expected behaviour?

**Comment by PuKoren** [comment]
I fixed this using new "observe" method, as below:
```js
MyModel.observe('before save', function updateTimestamp(ctx, next) {
    if (ctx.instance) {
      ctx.instance.createdAt = new Date();
      ctx.instance.updatedAt = new Date();
    } else {
      ctx.data.updatedAt = new Date();
    }
    next();
  });
```

**Comment by superkhau** [comment]
@PuKoren Is this good to close?

**Comment by PuKoren** [comment]
If using `Device.definition.properties.createdAt.default` is considered as deprecated then I think it is good to close

**Comment by superkhau** [comment]
@bajtos @raymondfeng @ritch PTAL

**Comment by bajtos** [comment]
In general, there is no way for an atomic `upsert` to tell in advance whether it will create a new record (and therefore default values should be generated) or update an existing record (in which case the default values should not be generated).

Your workaround works only as long are your application does only one of the following:
 - either send a request without an id, thus triggering a regular create at the juggler level
 - send a request with an existing id, thus triggering an update inside the database

If you send a request with an id that does not exist, upsert will trigger a create inside the database but the "created" property won't be initialized.

---

Also IIRC, different connectors implement the "update" case of "upsert" in different ways. Some replace all model attributes (i.e. delete attributes not included in the request body), some replace only the attributes included in the request body (via updateAttributes).

---

I don't think there is much we can do about this code-wise. The best solution I can think of is describing the caveats of using "upsert" for models with properties with default values in our documentation.

@raymondfeng Thoughts?

**Comment by PuKoren** [comment]
Yeah finally found a solution for the issue (but this works only using mongodb):

```js
Model.upsert(
  {
    id: "my_id",
    '$set': {
        //my values to upsert
       updatedAt: new Date() 
    },
    '$setOnInsert': {
       createdAt: new Date()
    }
  });
```

Hope this can help

**Comment by bajtos** [comment]
Re-labelling as `doc`, although I am not entirely sure how to best document this.
