### ISSUE TITLE
Review and update "Email REST API" docs

### ISSUE THREAD

**Issue by hacksparrow** [strongloop/loopback#876]
http://docs.strongloop.com/display/LB/Email+REST+API.

Note that this article is not yet published.

**Comment by bajtos** [comment]
@crandmck PTAL, is this still relevant?

**Comment by crandmck** [comment]
@sequoia Can you look at this?

**Comment by Sequoia** [comment]
Reviewing Docs. I will step thru each of the features described and note if anything doesn't work. When that's finished I should be able to recommend publishing and/or merging the two pages.

**Comment by Sequoia** [comment]
Reviewing [the new version of what @crandmck linked](http://loopback.io/doc/en/lb2/Email-connector.html) and [the new version of what @hacksparrow linked](http://loopback.io/doc/en/lb2/Email-REST-API.html) (which is, incidentally, *published*).

**Comment by Sequoia** [comment]
# Observations
* http://loopback.io/doc/en/lb2/Email-REST-API.html This page was clearly scaffolded & never fleshed out. Not clear why you’d have an “email” API, email is usually accessed thru another model.
  * Email has no rest endpoints `"Shared class  \"Email\" has no method handling POST /"`
* The top level Using Built-in Models page has [a section describing how to use the built-in email model](http://loopback.io/doc/en/lb2/Using-built-in-models.html#email-model) that overlaps with the built-in email model page.
* **Email model is a pass-thru to nodemailer** 👈  docs can be found there

# Actions
* [ ] note that the settings are pass-thru to https://github.com/nodemailer/nodemailer#setting-up
* [ ] remove this page: http://loopback.io/doc/en/lb2/Email-REST-API.html 
* [ ] Merge [this section on email](http://loopback.io/doc/en/lb2/Using-built-in-models.html#email-model) into [this page on email](http://loopback.io/doc/en/lb2/Email-connector.html) then remove the section (redundant, not placed as meaningfully)

**Comment by crandmck** [comment]
Sounds like a plan.

> remove this page: http://loopback.io/doc/en/lb2/Email-REST-API.html

When you do this, be sure to also remove it from the sidebar `yml`.  Also remove from any of the translated sidebars as well.
