### ISSUE TITLE
Is it possible to make a case-insensitive query ?

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#877]
@bajtos 
@raymondfeng 
Currently, i can't make query on filter with text in case-insensitive. Please tell me how can i do it ?
Example result of searching with text "Computer" is different from "computer". i want to make it the same. Please help me, thanks much.

I suggest solution for processing like and nlike in mongodb.js as below:
```javascript
     } else if (spec === 'like') {
        var match = cond.match(new RegExp('^/(.*?)/([gimy]*)$'));
        var regex = new RegExp(match[1], match[2]);
        query[k] = {$regex: regex};
      } else if (spec === 'nlike') {
        var match = cond.match(new RegExp('^/(.*?)/([gimy]*)$'));
        var regex = new RegExp(match[1], match[2]);
        query[k] = {$not: regex};
```
It's better than:
```javascript
     } else if (spec === 'like') {
        query[k] = {$regex: new RegExp(cond)};
      } else if (spec === 'nlike') {
        query[k] = {$not: new RegExp(cond)};
```
------------------------------------------------
@crandmck : This document is very simple, it is not enough information about where filter with regex text. Please update it to make more clear for "like" operator in each connector. Because i don't know what kind of regex will support for what connector ? Thanks much.
http://docs.strongloop.com/display/public/LB/Where+filter#Wherefilter-likeandnlike

**Comment by bluestaralone** [comment]
@raymondfeng : I don't know if this problem is solved jet ?

**Comment by avijohnson** [comment]
Could you guys post a simple example of a "like" query in loopback for MongoDB connector? Please refer me to one if already exists. Thx.

**Comment by bajtos** [comment]
See https://groups.google.com/d/msg/loopbackjs/riXYU_DhG3c/rXGowuYvLMYJ

```js
var pattern = new RegExp('.*'+query+'.*', "i"); /* case-insensitive RegExp search */ 
Post.find({ where: {title: { like: pattern} } }, 
```

Via the REST API - see https://github.com/strongloop/loopback-connector-mongodb/pull/86

```
?filter={"where":{"title":{"like":"someth.*","options":"i"}}}
```

**Comment by crandmck** [comment]
Since this seems to be a common question, I added it to the docs: http://docs.strongloop.com/display/LB/MongoDB+connector#MongoDBconnector-Case-insensitivequery

@bajtos - PTAL.

**Comment by bajtos** [comment]
> Since this seems to be a common question, I added it to the docs: http://docs.strongloop.com/display/LB/MongoDB+connector#MongoDBconnector-Case-insensitivequery

LGTM, though I am not very familiar with MongoDB internals. @raymondfeng could you please take a look too?

**Comment by jcsmesquita** [comment]
I got this working with the mongo connector. Is there any chance we could make it work for the built-in memory connector as well?

**Comment by bajtos** [comment]
> @jcsmesquita Got this working with the mongo connector. Is there any chance we could make it work for the built-in memory connector as well?

Can you contribute the feature yourself?

**Comment by bajtos** [comment]
> > @jcsmesquita Got this working with the mongo connector. Is there any chance we could make it work for the built-in memory connector as well?

> Can you contribute the feature yourself?

Unless @raymondfeng objects, see one of his comments above:

> I would like to introduce a new regexp operator to the query filter and support it across DB connectors consistently. Overriding like/nlike can cause confusions.

**Comment by jcsmesquita** [comment]
@bajtos 
My use-case was to use the memory connector for local development and testing but now I realise that's not ideal since I should mimic the production server as much as possible. I've decided to leave the memory connector and use the mongo one instead.

**Comment by bajtos** [comment]
> My use-case was to use the memory connector for local development and testing but now I realise that's not ideal since I should mimic the production server as much as possible. I've decided to leave the memory connector and use the mongo one instead.

@jcsmesquita that makes a lot of sense.

The promise of LoopBack and the Memory connector is to allow developers to use memory connector for unit-tests to get super-fast feedback loop during Red-Green-Refactor cycle, and then run the same test suite against MongoDB (or SQL) to verify the behaviour in production. 

Therefore I think it still makes sense to implement support for case-insensitive and/or regex queries in the memory connector.

**Comment by soltrinox** [comment]
I used a second field... and added an OR statement ... for ANGULAR.JS API

Using this model..
`[
  {
    "name": "",
    "parent": "",
    "seo": "",   // lowercase-no-sapces
    "type": "",
    "id": "objectid"   
  }
]`

`     $scope.loadCats = function(val) {
       return $http.get('//api.com/api/Categories', {
         params: {
           filter: {
               where : {
                 or : [
                     {  name : {
                        like : val
                       }
                     },
                     {   seo : {
                       like : val
                     }
                   }
                 ]
              }
           }
         }
       }).then(function(response){
         return response.data.map(function(item){
           return item.name;
         });
       });
     };`

**Comment by Amir-61** [comment]
I label this ticket as a feature for `Memory` connector.

Thanks!

**Comment by raymondfeng** [comment]
The memory connector already supports `regexp` operator which can have `/i` option.

**Comment by Amir-61** [comment]
Thanks @raymondfeng,
Cool! So I will be closing this ticket soon!

**Comment by crandmck** [comment]
Note that this is documented: https://docs.strongloop.com/display/LB/Where+filter#Wherefilter-Regularexpressions.
