### ISSUE TITLE
REST 'filter' scopes should be chainable

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback#880]
You can currently do `/api/messages/received` and `/api/messages/unread` but cannot chain both into `/api/messages/received/unread` to combine one or N scopes together, which is already supported in plain JS. Additionally, we might support `/api/messages?scopes[]=received&scopes[]=unread`.

**Comment by loay** [comment]
Hi @fabien,
is it issue still relevant? I mean: is it already implemented?
Thanks

**Comment by marcoskubis** [comment]
Thanks @fabien for mixin. @loay I think it's not implemented yet. It is a must-have feature, this is very useful.

**Comment by TrevorPage** [comment]
Sorry to sound stupid here, but can anyone point me to the documentation (or code) that shows scopes being used in a REST API query? Or is this a feature long gone in an older Loopback version? All I can find references for now are the use of scopes within Include filters.

**Comment by yalmasri** [comment]
this didn't solve the problem for me:
```
User.scope('active', { where: { status: 'active' } })
User.scope('suspended', { where: { status: 'suspended' } })
```
the mixin will merge the 2 scopes and produce `and` query, and this is not the correct solution:
```
{ where: { and: [ { status: 'active' }, { status: 'suspended' } ] } }
```

while the correct query should be:
```
{ where: { and: [ { or: [ { status: 'active' }, { status: 'suspended' } ] } ] } }
```
