### ISSUE TITLE
ACL Permission Precedence

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#89]
/to @raymondfeng 

Given the following ACL and a request to `POST /myModel` (`MyModel.create()`) the resulting permission is `DENY`.

``` js
[
   {
      principalType:'ROLE',
      principalId:'$everyone',
      permission:'DENY'
   },
   {
      principalType:'ROLE',
      principalId:'$everyone',
      property:'create',
      permission:'ALLOW'
   }
]
```

**Comment by daankets** [comment]
I have exactly the same case, and even stranger: when I use the API explorer to invoke the create, I get an 401, but in the application, the 'afterCreate' hook that I registered is executed successfully. So are the beforeCreate and beforeSave hooks.
I do NOT succeed in overriding the DENY($everyone,*,ALL) with ALLOW($everyone, create,EXECUTE).

**Comment by daankets** [comment]
@ritch, @raymondfeng : Never mind... seems like it DID work after all. However, a faulty role resolver was blocking the method from returning [No content], and instead caused the 401.
