### ISSUE TITLE
default scope cause error in GET /item/{ID} + questions

### ISSUE THREAD

**Issue by antoinegomez** [strongloop/loopback#893]
Hello,

An update regarding my post in issue #773

I have a problem with the scope configuration in the model where I want to include a dependent model by default.

In this exemple I have a model user and user-profile. I don't expose user-profile on the REST API and I want to include the data of this model in the user one when I fetch some users.

I tryed to understand what's the best way to do that with loopback but expect playing with "include", which is working fine when using filters I have some problems:

- When I GET one entity via (GET /users/1) I cannot set any filters. They only work on top level routes (GET /users) right ? So I am forced to use the top level route with a where id = 1 filter.
- When I define a scope to include user-profile it works very well on the top level route but when I try to get one user via /users/1 I have this error:

```javascript
  "error": {
    "name": "Error",
    "status": 500,
    "message": "Relation \"user-profile\" is not defined for user-profile model",
    "stack": "Error: Relation \"user-profile\" is not defined for user-profile model\n    at processIncludeItem (/home/antoine/workspace/users/node_modules/loopback-datasource-juggler/lib/include.js:144:10)\n    at /home/antoine/workspace/users/node_modules/loopback-datasource-juggler/lib/include.js:118:5\n    at /home/antoine/workspace/users/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:125:13\n    at Array.forEach (native)\n    at _each (/home/antoine/workspace/users/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:46:24)\n    at Object.async.each (/home/antoine/workspace/users/node_modules/loopback-datasource-juggler/node_modules/async/lib/async.js:124:9)\n    at Function.Inclusion.include (/home/antoine/workspace/users/node_modules/loopback-datasource-juggler/lib/include.js:117:9)\n    at /home/antoine/workspace/users/node_modules/loopback-datasource-juggler/lib/include.js:217:30\n    at /home/antoine/workspace/users/node_modules/loopback-datasource-juggler/lib/relation-definition.js:1667:11\n    at /home/antoine/workspace/users/node_modules/loopback-datasource-juggler/lib/dao.js:858:5"
  }
}
```

What I would like to do with this example is to serve data like this:

```javascript
  {
    "username": "antoine",
    "is_active": true,
    "firstname": "Antoine",
    "lastname": "Gomez"
  }
```
Instead of:

```javascript
  {
    "username": "antoine",
    "is_active": true,
    "user-profile": {
      "user_id": 1,
      "firstname": "Antoine",
      "lastname": "Gomez"
    }
  }
```

Maybe loopback is not meant to deal with these type of MySQL tables and layout and cannot be able to do that.
I would love to be able to hydrate the data before sending it back to the user.

Maybe I should write my own routes and calling the right methods for each of them instead of relying on the default behaviour. Regardless of that I guess there is something wrong with scope or maybe not configured well on my side and I have created a sample project with a SQL file to reproduce, you can fetch it from here:

https://github.com/antoinegomez/loopback-debug

**Comment by ningsuhen** [comment]
+1. When I set the default scope of a model (Product) to include the user model in 
```json
"scope":{
  "include":"owner"
}
```
And call 
```js
Product.findOne({
  where:{
    id:'<someId>'
  },
  include:'someOtherRelation'
}
```
it throws the error
```
Error: Relation "someOtherRelation" is not defined for user model
```
I'll try to fix this. Any Pointers?

**Comment by ningsuhen** [comment]
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/utils.js#L84:L86
```js
 var saved = base.include;
base.include = {};
base.include[update.include] = saved;
```
After applyScope, the query of the above example becomes 
```js
{
  where:{
    id:'<someId>'
  },
  include:{
    owner:'someOtherRelation'
  }

}
```
Merging scopes seems like a big pain considering the various formats supported.

**Comment by ningsuhen** [comment]
@antoinegomez , can you verify and close this? Should be fixed by https://github.com/strongloop/loopback-datasource-juggler/releases/tag/v2.26.3

**Comment by gunjpan** [comment]
@antoinegomez : Closing this as should have been fixed. If it still persists, please feel free to comment with my GH handle and I'll reopen it.
