### ISSUE TITLE
afterSave remote hook doesn't show error when call next(new Error('aaa'));

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback#896]
This code below is not show error when create new Car: POST /Cars
```javascript
Car.afterSave = function(next) {
    next(new Error('aaaa'));
 }
```
This code response to client as "success" of create new car.
How can i stop process "create new car" if i have problem after save it.?

**Comment by bajtos** [comment]
I am closing this issue, we are moving away from `beforeSave/afterSave` hooks in favour of [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks) and [Per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397).

Please upgrade your project to use the new `after save` hook and open a new GH issue if you run into any problem.
