### ISSUE TITLE
Per-method validation rules

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback#898]
Can I have different subset of validation rules for different methods?

I mean for /create one set of rules
for   /update  different set of rules.

or

isValid() would be able to use defined set of rules. So if I create custom remote method I can apply different validations to it.

Thanks

**Comment by j0nathan-ll0yd** [comment]
+1

**Comment by marcellodesales** [comment]
+1

**Comment by clarkorz** [comment]
If you just want different rules set for **create** and **update**, you can try conditional validation in *some cases*. 

`Model.prototype.isNewRecord()` can be use to check if the instance has been persisted.

e.g.:
```
// if inst.isNewRecord() returns true (for create) then title is required
Post.validatesPresenceOf('title', { if: 'isNewRecord' }); 

// if inst.isNewRecord() returns false (for update) then title is required
Post.validatesPresenceOf('title', { unless: 'isNewRecord' }); 
```

the value of `if` and `unless` could be a property or function name on the instance

**Comment by bajtos** [comment]
I am afraid it's not possible to reliably distinguish between UPDATE and CREATE when running operations like `updateOrCreate` and `replaceOrCreate`, therefore there is now way how to implement a validation that is called only on update/only on create.

**Comment by pookdeveloper** [comment]
https://github.com/pookdeveloper/loopback-3-tips-tricks/blob/master/README.md
