### ISSUE TITLE
Initial work to internationalize LoopBack docs

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#901]
Need to define how we are going to provide content in multiple languages.  We should investigate if there are any good Confluence plugins for this; e.g. https://marketplace.atlassian.com/plugins/com.k15t.scroll.scroll-translations.

As a provisional plan, we will add a space for each language for which we have localized content.  It looks like this will be at least Japanese and Russian; so e.g. JP and RU spaces.  These spaces' permissions will be set the same as LB so that community users can edit.  However, we will not enabled the community workflow, because the translators should be able to update localized articles without review by me.

Then we need to: Add multi-language navigation; Adding a space disclaimer stating that it's a 3d-party translation and may be outdated; Link to source / English page, if possible.  

Also need to write a basic translator's guide and announce on mailing list, etc.

**Comment by chandadharap** [comment]
Is this a priority atm?

**Comment by ijroth** [comment]
It isn't, but when discussed it was a small item that would pay dividends in terms of the community so that's why it was scheduled to work on. (If I remember the discussion from last week.)

**Comment by crandmck** [comment]
OK, I created spaces for Japanese and Russian docs that initially contain copies of the English LoopBack docs (as of yesterday):
- http://docs.strongloop.com/display/JA/LoopBack
- http://docs.strongloop.com/display/RU/LoopBack

I also created a custom macro to display a link to the the source (English) article, and the date the translated page was last updated; I added this as a space header to those spaces.  

Also added http://docs.strongloop.com/display/ALLDOCS/Other+languages to the "All documentation" space to act as an index of all localized content.

Was there interest in any other languages?

I also added http://docs.strongloop.com/display/LB/Translating+documentation as an initial guide for translators.

This is most of the work for LoopBack.  Now I just need to email the people who were interested in translating to Japanese and Russian, and also make an announcement on the GG.
@ijroth @altsang please review all this, and when you give the thumbs-up, I will send email and post to GG.

For Express, there is a separate issue: https://github.com/strongloop/expressjs.com/issues/287.

**Comment by altsang** [comment]
looks good, although we need some reference to the version of the products and API, in general we actually need the version displayed for each of the components - LoopBack 2.X so that we can reference the translation back to a specific version

**Comment by crandmck** [comment]
I added 2.x to the space-wide headers and emailed the volunteer translators.  Will post to GG soon, then we can close this one.

**Comment by crandmck** [comment]
Posted to GG https://groups.google.com/forum/#!topic/loopbackjs/6aCJQ3ySD3E
