### ISSUE TITLE
What is equivalent to ORDER BY RAND()?

### ISSUE THREAD

**Issue by yagobski** [strongloop/loopback#902]
Hi,

There is any alternative to do Order by RAND() in filter?
http://docs.strongloop.com/display/public/LB/Order+filter

I see only order ASC and DESC.

I am using MYSQL connector.

Thanks

**Comment by loay** [comment]
Thanks for reporting the issue. 
There is a workaround for that case, but we will need to add the RAND to all the connectors.

**Comment by superkhau** [comment]
Is this a feature or still in triage? I assume u need to remove the triage label?

**Comment by loay** [comment]
@superkhau Done

**Comment by superkhau** [comment]
ty

**Comment by kjdelisle** [comment]
Why can't a user take the result set after it's returned and shuffle it? Supporting this across the SQL connectors (some of which don't support it) doesn't make any sense to me.

Far more importantly, there's quite a bit of talk out there on StackOverflow and the like explaining that `ORDER BY RAND()` does exactly what you would expect it to; it will first get the set of results required by your `SELECT` and then filter them accordingly.  If you only intend to grab a subset of the initially selected-for rows, you're still going to be handling ALL of the rows that fall under the first `SELECT` call, meaning you've found a very inefficient way to randomize your result set.

If you're going to be doing that, then there's no reason why you can't just utilize your favourite in-place shuffle implementation in the model's .js file.
