### ISSUE TITLE
Incorrect distance calculation in the GeoPoint class

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback#904]
In reference to the code at:
https://github.com/strongloop/loopback-datasource-juggler/blob/master/lib/geo.js#L248

```js
function geoDistance(x1, y1, x2, y2, options) {
  // Convert to radians
  x1 = x1 * DEG2RAD;
  y1 = y1 * DEG2RAD;
  x2 = x2 * DEG2RAD;
  y2 = y2 * DEG2RAD;

  var a = Math.pow(Math.sin(( y2 - y1 ) / 2.0), 2);
  var b = Math.pow(Math.sin(( x2 - x1 ) / 2.0), 2);
  var c = Math.sqrt(a + Math.cos(y2) * Math.cos(y1) * b);

  var type = (options && options.type) || 'miles';

  return 2 * Math.asin(c) * EARTH_RADIUS[type];
}
```

Whoever wrote this function flipped longitude and latitude while calculating the  haversine function.

For reference, the Haversine formula is described here: http://en.wikipedia.org/wiki/Haversine_formula

Proof:

```
geoDistance(40.77492964101182,-73.90950187151662, 40.7753227,-73.909217, {type: 'meters'})
33.91341032860474

// it should be 49.856135113670085
```

![screen shot 2014-12-09 at 2 19 13 am](https://cloud.githubusercontent.com/assets/2038264/5353627/53b09f34-7f4a-11e4-92d3-1eb866bb1f11.png)

![screen shot 2014-12-09 at 2 19 46 am](https://cloud.githubusercontent.com/assets/2038264/5353634/6ac3eb4a-7f4a-11e4-981f-f9aea95a1734.png)

**Comment by framp** [comment]
+1

**Comment by 0candy** [comment]
Fix merged, closing issue.
