### ISSUE TITLE
200 statues should not be returned with bad config [GoDaddy]

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#914]

**Comment by bajtos** [comment]
@chandadharap @dashby3000 ping, could you please fill in more details? We still don't have enough information on what is requested in this issue and thus we can't provide any effort estimate.

**Comment by chandadharap** [comment]
Dennis said to close:
Upon digging deeper, it this better described the requirement https://github.com/strongloop/strong-remoting/issues/186

closing.
