### ISSUE TITLE
Adding to the model the count of related model instances

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback#917]
Based on google groups conversation: https://groups.google.com/forum/#!topic/loopbackjs/Vrrl1Zi3q64/discussion

Let's assume there are two models: Chapter and Book, which hasMany Chapters via chapters relation.
Requirement is to list all Books with the count of Chapters for each of them in one REST API query. Example:

Request: `GET /Books`
Response:

```
[
  {
    bookid: 1,
    chaptersCount: 3
  },
  {
    bookid: 2,
    chaptersCount: 12
  },
  {
    bookid: 3,
    chaptersCount: 7
  }
]
```

where chaptersCount is the number of related Chapters for this book.

Some options:
- persistent: maintain count of chapters in each book additionally and update it whenever new chapter is added or removed to/from this book. Advantage: possibility to use this field for sorting.
- not persistent: use remote method hook and for each book in result set to do a count of chapters. Something like a scope for relation would be a good alternative. But instead of getting the full list there will be a count. Disadvantage: can not be used for sorting.

Is there any way to achieve any of these options without a lot of custom coding? If not, I wonder if it makes sense to implement it in the framework.

**Comment by ksivamuthu** [comment]
+1

**Comment by dennari** [comment]
+1

**Comment by bteres** [comment]
+1

**Comment by maelena87** [comment]
+1

**Comment by ciokan** [comment]
+1

**Comment by JonnyBGod** [comment]
+1

**Comment by exromany** [comment]
+1

**Comment by dot-louis** [comment]
+1

**Comment by karissa** [comment]
+1

**Comment by framp** [comment]
+1

**Comment by zanemcca** [comment]
+1

**Comment by dh376** [comment]
+1

**Comment by ahmed-abdulmoniem** [comment]
+1

**Comment by felipetoffolo1** [comment]
+1

**Comment by upupzealot** [comment]
+1

**Comment by mamartins** [comment]
+1

**Comment by ahmed-abdulmoniem** [comment]
+1

**Comment by waldemarzahn** [comment]
+1

**Comment by e-part** [comment]
+1

**Comment by UzverNumber47** [comment]
+1

**Comment by jannyHou** [comment]
Thank you all for the feedback :)
Please add your 👍 reaction on the top comment instead of posting new "+1" 
We are using vote system https://www.bountysource.com/teams/strongloop/issues to list issues with high numbers of thumb ups

**Comment by wzl002** [comment]
+1

**Comment by jwebcat** [comment]
This would be fantastic +1

**Comment by luisfavila** [comment]
+1

**Comment by bugdanov** [comment]
:+1:

**Comment by byronmejia** [comment]
Status update?

**Comment by jwebcat** [comment]
Don't expect any update for a long time, this project is like molasses on a
winter day.

**Comment by PhilippeCorreges** [comment]
Hello. 
As this Finally been implemented?

Thanks and Regards

**Comment by demiro** [comment]
I hope this is not dead because this is desperate needed.... especially in the world of comments/posts with reaction counting (likes, dislikes, etc).

Is there a status update on this?

**Comment by ahadortiz** [comment]
I need this function, too.
Any updates?

**Comment by ahadortiz** [comment]
I found a mixin: [loopback-counts-mixin](https://www.npmjs.com/package/loopback-counts-mixin)
It looks like what I'm looking for.

**Comment by byronmejia** [comment]
@ahadortiz - this issues has been up since 2014. If you want to try a reliable, stronger contender, may I suggest [Strapi](https://github.com/strapi/strapi/).

_I am not associated with strapi in any ways. Strapi just ended up being the option we used in the past when loopback's pitfalls ended up being too much._

**Comment by dodevup** [comment]
A simple and quick workaround for this is to replace the "hasMany" relation by a "referencesMany" relation like this :
`"relations": {
    "chapters": {
      "type": "referencesMany",
      "model": "chapter",
      "foreignKey": "chapterIds",
      "options": {
        "validate": true,
        "forceId": false
      }
    }
}
`

So you will be able to count how many ids there are in the chapterIds property like this :
`book.chapterIds.length`.
This count can then be done either client-side or server-side if you create an observer or afterRemote .
