### ISSUE TITLE
 `slc loopback:relation` to define a m2m relationship + through table has confusing behavior

### ISSUE THREAD

**Issue by AndrewJHart** [strongloop/loopback#922]
Hey Guys, 

After discussing this in the forum it appears this is not the desired behavior so Im pursuing a patch/enhancement. I've also not added to the docs yet because I wasn't sure - guess i'm a little hesitant :/ I will gladly do so though - just need some feedback. 

When running `slc loopback:relation` to define a m2m relationship with a through table, I found the behavior a bit confusing. I'm rather new to loopback so perhaps thats the cause, but ideally I believe it should still be documented.. e.g. Using the example in the docs we have 3 models: Physician, patient, &  appointments. Assuming we have already used the generator to create these 3 models - one would think that running the `relation` cmd, choosing `Physician`, `hasMany`, `patient` and lastly choosing _yes_ to the question `Choose a through model` would produce output in each model's json "relations" like so: 

``` javascript
// physician.json
  "relations": {
    "patients": {
      "type": "hasMany",
      "model": "Patient",
      "foreignKey": "patientId",
      "through": "Appointment"
    },

// patient.json
  "relations": {
    "physicans": {
      "type": "hasMany",
      "model": "Physician",
      "foreignKey": "physicianId",
      "through": "Appointment"
    },

// appointment.json
  "relations": {
    "physician": {
      "type": "belongsTo",
      "model": "Physician",
      "foreignKey": "physicianId"
    },
    "patient": {
      "type": "belongsTo",
      "model": "Patient",
      "foreignKey": "patientId"
    }
```

However the only output that gets written is to the source model's json file; ergo, one must run the generator 4 times to get the proper relationships established (or manually edit them). 

Should not the generator write to all 3 model configs when a user chooses to use a `through` table? Although, I can somewhat see the potential for error if the generator were to assume too much, however when configuring a `through` model there should always be 2 Foreign Keys on it. Wouldn't it at least be pertinent to  add the `belongsTo` relationships to the `through` models (appointments.json) config file?

Anyway, it didn't take long to figure out why my queries were failing but mentioning this in the docs - something about running the generator once for each model for hasMany and twice for the through model would save some time and avoid confusion for future adopters of loopback.

**Comment by smartmouse** [comment]
@crandmck if we add a bit more steps under the example before each .json file, that may help the user. I tried it out and  @AndrewJHart  has a good point.  Let me ao a PR and you can review for me but now we will be using lb relation in the new doc

**Comment by smartmouse** [comment]
The changes have been merged with @crandmck 's help and  we are closing this. Thanks
