### ISSUE TITLE
Update docs with examples from user mgmt FAQ repo

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#929]
Review  https://github.com/strongloop/loopback-faq-user-management/ for code examples and other stuff to add to docs, e.g. password reset.

**Comment by crandmck** [comment]
> we are trying to see if the related docs at: https://docs.strongloop.com/display/public/LB/Managing+users has something missing or a place to improve..

@gunjpan Yes, that's correct.  I wrote the doc before this example was created, and there may be some code snippets that we could use in the docs, e.g. for registering users, logging in, etc.

**Comment by gunjpan** [comment]
@crandmck : I've made improvements/changes that I found would be helpful and references to the example repo. Could you please review them and advise if any updates required.

Also, please note that the steps to [register with third-party system] (https://docs.strongloop.com/display/public/LB/Registering+users#Registeringusers-Registeringusersthroughathird-partysystem) are lengthy and thus I believe, it's better to just provide a reference where it's explained well.

Please review and verify if this story is good to close. Thank you.

**Comment by crandmck** [comment]
I made a few small edits, otherwise LGTM.  
Thanks!
