### ISSUE TITLE
Globalize error messages

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback#932]
It would be useful to have the ability to configure the error messages for some of the existing remote methods. For example, in the case where [email verification is required](https://github.com/strongloop/loopback/blob/cb2f40bb86905439434a358debbd2e044a2de1ca/common/models/user.js#L190), there doesn't seem to be a way to supply, intercept or configure the value. There is no presence of `details` as seen in model [validation errors](http://docs.strongloop.com/display/public/LB/Validating+model+data) which makes localization and custom messages tricky client side.

I've considered the approach of using the message itself as the key in a localization table (eg `{ "some loopback message": "my custom message" }` but this approach has a few drawbacks. 

* less dynamic and requires the advanced knowledge of all available error messages
* from version to version, if the message is changed or new messages are added it's tricky to maintain the localization table

Open to suggestions as well if there is a best practices way of handling this that is not immediately apparent to me.

Thanks!

**Comment by greaterweb** [comment]
I'll revisit this soon, the PR for 944 was merge in today. PR I created for 931 is ready, rebased against loopback master yesterday. Once that is merged in I'll continue work on this.

**Comment by bajtos** [comment]
For posterity, the issue was fixed by the commit a028d9d19, released as `loopback@2.11.0`.
