### ISSUE TITLE
Replication: Changes not tracked when using custom id property

### ISSUE THREAD

**Issue by ritch** [strongloop/loopback#933]
With a model definition similar to the following (attached to mongodb on the server):

```js
{
  properties: {
    myIdProperty: {
      id: true,
      type: 'Number'
    },
    ...
  }
}
```

Changes are being tracked with the `_id` (`ObjectID`) instead of the value of the `id` field ('myIdProperty'). This completely breaks replication.

**Comment by ritch** [comment]
With some deeper digging... it looks like this is a property definition we cannot support with mongodb out of the box.

The model should instead use the default `id` configuration. This will avoid the issue where changes are not saved with the correct id.

/cc @dashby3000 @raymondfeng

**Comment by bajtos** [comment]
Related: https://github.com/strongloop/loopback/issues/981
