### ISSUE TITLE
Role.isOwner and relation name collision

### ISSUE THREAD

**Issue by Va1** [strongloop/loopback#934]
Hey, guys!

On one of my models, the name of the relation was "owner" with the primary key of "identityId", and $owner role resolver was not working when I used it in ACLs. I was wandering why and dug into the sources. So, here's what I've found:

https://github.com/strongloop/loopback/blob/7c96aec9af579f697b8755b53bd9be1b628f939b/common/models/role.js#L159

In my case, the value of inst.owner is the function, not the integer as expected. So, I am getting match(...) === false every time on line 161. 

But, for example, when I change relation name to "theOwner", all works fine, because following code (starting at line 165) executes.

I wander why you are checking for inst.owner on line 159 and whether the relation name of "owner" is really dangerous to use?

Thank you!

**Comment by bajtos** [comment]
This has been fixed by https://github.com/strongloop/loopback/pull/1201 (v2.15.0)
