### ISSUE TITLE
MySQL error 'ER_TOO_BIG_ROWSIZE' when automigrating to create the 'Application' table

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback#937]
After including the Application built-in model to the model-config.json and running automigrate, loopback fails to create the Application table in MySQL.

```
{ [Error: ER_TOO_BIG_ROWSIZE: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs]
  code: 'ER_TOO_BIG_ROWSIZE',
  errno: 1118,
  sqlState: '42000',
  index: 0 }
```

This seems like a pretty huge issue since it prevents MySQL users from being able to utilize loopback's built in OAuth2 support.

Any ideas for workarounds?

**Comment by raymondfeng** [comment]
I believe that the issue has been fixed. Please reopen if it's not.
