### ISSUE TITLE
Documentation for Database discovery API is incorrect (references "relations" key in options)

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback#938]
The documentation for the Database discovery API (http://docs.strongloop.com/display/public/LB/Database+discovery+API#DatabasediscoveryAPI-discoverSchemas) mentions that passing "relations: true" will scour and build all relations.

This is incorrect as the actual key to use is "associations: true"

**Comment by raymondfeng** [comment]
We actually support both `associations` and `relations`.
