### ISSUE TITLE
FIX: Invalid User Tests

### ISSUE THREAD

**Issue by greaterweb** [strongloop/loopback#944]
There appear to be a number of issues present with the [User model tests](https://github.com/strongloop/loopback/blob/36e1f6840ca681439f9424eb3eef098aaf98e6e8/test/user.test.js).

 - [x] [`invalidCredentials`](https://github.com/strongloop/loopback/blob/36e1f6840ca681439f9424eb3eef098aaf98e6e8/test/user.test.js#L14) are actually valid (see [`validCredentialsEmailVerified`](https://github.com/strongloop/loopback/blob/36e1f6840ca681439f9424eb3eef098aaf98e6e8/test/user.test.js#L11))
 - [x] test using `invalidCredentials` should actually fail but it doesn't (broader problem, see below)
 - [x] use off `.expect` needs to be paired with logic in the `.end` callback (eg. `if (err) return done(err);`) when testing REST calls, this is not applied to all instances. to confirm these are failing, change one of the `.expect` values and note the test still passes
 - [x] could also extend to create API test where there are only REST tests, for example there is only a REST test for `invalidCredentials` and nothing specific for API call

Regarding the point of `.expect` usage, it's probably worth looking into any other REST unit tests to make sure they are correct in implementation.

A question in general. There is both vanilla `assert` statements and chai `expect` statements, which is the preferred approach for testing?

Additional tests to add
- [x] check reset password fails without email address (API and REST)
- [x] reset password over REST

**Comment by raymondfeng** [comment]
@greaterweb Thank you for making efforts to improve the tests. Sorry for the delay as some of us were on holidays. 

A few comments:

- Good catch to the `invalidCredential`
- Good catch to the end(), which will receive an error if the expected status code doesn't match
- For the content type test, we should set it to something like `text/html`

Can you create a pull request from your repo? It would be simpler to add inline comments with the PR.

**Comment by greaterweb** [comment]
@raymondfeng I rebased my fix branch with the current loopback master and created the pull request.

Please feel free to add your comments to the PR and I'll adjust accordingly.

**Comment by greaterweb** [comment]
Closing as PR has been merged.
