### ISSUE TITLE
Suggestion: Post including related data

### ISSUE THREAD

**Issue by bkniffler** [strongloop/loopback#948]
I suggest implementing a possibility to handle new/updated/removed associated child data when posting an item.

Lets say we have a "Shelf" and a "Book" model with a 1:n relation, I'd like to be able to post from the client:
```
[Shelf]
{
 name:"Shelf 1",
 books: [{ name:"Book 1" },{ name:"Book 2" }]
}
```
Currently, this scenario must be handled either client-side, posting shelf and on response, posting the associated books; or server-side with custom methods or by using hooks (which is what I'm trying atm):
```
.beforeSave = function (next, item) {
        // Store books in ctx
        next();
    }
.afterSave = function (next, item) {
        // compare ctx.books and item.books
        // delete items not present in ctx.books, but in item.books 
        // add items not present in item.books but in ctx.books
        // possibly update those books present in both
        next();
    }
```
I wouldn't consider this a very clean solution and when done in a generic, plug-and-playable way, there are a few things to take care of (like handling all relations, 1:1, 1:n or n:n). But in my opinion, with a product that generates such complete rest apis as Loopback does, this should be a build-in feature. How do you guys see this? Do you have a better idea? Would you consider implementing this?

**Comment by bkniffler** [comment]
Any news on this? Isn't posting an object with related data a case that many devs encounter with real-life business applications? How do you guys handle this kind of scenario in a DRY way?

- Document with Tags
- Order with Products
- ...

**Comment by fabien** [comment]
@bkniffler if you're still looking for a solution, I probably can extract a mixin to handle this.

**Comment by bkniffler** [comment]
Sure, I'd be happy to see a suggestion for this problem, and I imagine it'd be helpful for others too. Thanks!
