### ISSUE TITLE
Integrate middleware phases doc

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#950]
Clean up http://docs.strongloop.com/display/LB/Using+middleware+phases and integrate with the rest of the docs: eliminate duplication, add x-links, etc.

This affects quite a few articles:
* http://docs.strongloop.com/display/public/LB/Add+a+static+web+page
* http://docs.strongloop.com/display/LB/Defining+middleware
* http://docs.strongloop.com/display/LB/Using+middleware+phases
* http://docs.strongloop.com/display/LB/server.js and http://docs.strongloop.com/display/LB/Project+layout+reference

And probably many others.

**Comment by crandmck** [comment]
I'm still working on the rest of the documents, but @bajtos please review this article: http://docs.strongloop.com/display/LB/Defining+middleware+using+phases.  You must login to Confluence to view it.  Once approved, it will replace http://docs.strongloop.com/display/LB/Defining+middleware and http://docs.strongloop.com/display/LB/Using+middleware+phases.

**Comment by bajtos** [comment]
> Is it still useful to describe these different kinds of middleware, or should we just reduce it to "error-handling mw" and "other mw"?

Let's keep the description there.

> If you register middleware with the legacy Express API, then it is executed at the beginning of the routes phase.

The Express API is not necessarily legacy, because the new phase-based API does not cover all Express API, e.g. methods like `app.post` or `app.route` don't have a phase-enabled variant.

I am proposing to rephrase the sentence: *If you register middleware (or routes) with the Express API, etc.*

**Comment by bajtos** [comment]
> Can you use the ID syntax with all of these, eg. loopback#csrf ??

You can, but since we are recommending against using these compatibility shortcuts in new applications, it's IMO better to not mention them at all.

And since you must have the package installed to use the shortcut, there isn't really any reason to prefer the id `loopback.csrf` over the id `csurf`.

**Comment by bajtos** [comment]
> err - V8 error object. See V8 JavaScript stack trace API.

This feels misleading to me. 

First of all, there is no guarantee that `err` is an instance of `Error`, it may be anything (e.g. a string message). However, the convention is to pass an error object, so it may be ok to stick to that in this page.

Secondly, "V8 error object" sounds like the value is something internal to V8. Typically, the error is created by user code.

Last but not least, the stack trace API is a very low level affair that very few developers use.

My proposal:

*err - Error description, usually an instance of `Error`.*

If we want to add external links, then the following articles are IMO more suitable than the stack trace API.
 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error
 - https://www.joyent.com/developers/node/design/errors
 - https://docs.nodejitsu.com/articles/errors/what-is-the-error-object

It is probably best to create a new page in Confluence describing Errors and start linking to this page from other places where we have an err object (that means almost all API docs). That way we can keep the content (and external links) in one place, making updates easy.

**Comment by bajtos** [comment]
>> There are some things to look out for when using middleware, mostly to do with middleware declaration order.  Be aware of the order of your middleware registration when using "catch-all" routes.  

> Not clear to me if this caveat still applies generally or only to middleware registered using the old Express API.

It still applies. For example, if you register `loopback#urlNotFound` in `initial` phase, your application will return 404 for all request.

**Comment by bajtos** [comment]
I have finished the review. The article is well written!

**Comment by crandmck** [comment]
Thanks, Miroslav.  I incorporated all your comments.  This page is now published as http://docs.strongloop.com/display/LB/Defining+middleware.  Upgrade instructions are in http://docs.strongloop.com/display/LB/Upgrading+applications+to+use+phases.

As suggested, I also created http://docs.strongloop.com/display/LB/Error+object that we can start linking to from various places.  It would be nice to add some more info here on error handling, etc.

**Comment by bajtos** [comment]
LGTM, feel free to close this issue as resolved.

**Comment by chandadharap** [comment]
resolved. closing.
