### ISSUE TITLE
package.json corruption after running slc loopback:acl

### ISSUE THREAD

**Issue by jrschumacher** [strongloop/loopback#951]
After running `slc loopback:acl` my package.json is corrupted.

![screenshot](https://cloud.githubusercontent.com/assets/46549/5543748/ff44c6e0-8ac6-11e4-8b59-14cc4bff0a81.png)

The change results in all dependencies being overwritten and looking like this.

```json
{
  "name": "my-package",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
    "gulp": "^3.5.6",
    "gulp-sass": "^0.7.1",
    "gulp-concat": "^2.2.0",
    "gulp-minify-css": "^0.3.0",
    "gulp-rename": "^1.2.0"
  },
  "devDependencies": {
    "bower": "^1.3.3",
    "gulp-util": "^2.2.14",
    "shelljs": "^0.3.0"
  }
}

```

**Comment by raymondfeng** [comment]
@superkhau Can you try to reproduce the problem?

**Comment by superkhau** [comment]
@jrschumacher Thanks for the report!
@raymondfeng I will try to reproduce it.

**Comment by superkhau** [comment]
@jrschumacher Can you post the complete package.json so I can use it to reproduce the exact issue?

**Comment by jrschumacher** [comment]
@superkhau I used `slc` to create a new project

**Comment by bajtos** [comment]
@jrschumacher do you have another `package.json` file in your project tree (besides node_modules dependencies)? It's possible you have run into https://github.com/strongloop/loopback-workspace/issues/181

**Comment by jrschumacher** [comment]
@bajtos yes that's exactly my scenario. I can remove the other project from my repo, but is there another solution?

**Comment by bajtos** [comment]
I see. I am closing this issue as a duplicate then. I am not aware of any other solution ATM. The good news is that strongloop/loopback-workspace#181 has pretty high priority for us.
