### ISSUE TITLE
Automatically cast remote method argument to ObjectID

### ISSUE THREAD

**Issue by alFReD-NSH** [strongloop/loopback#952]
Seems like right now we have to manually cast ObjectID input arguments. It'd be nice to have that.

**Comment by pthieu** [comment]
@alFReD-NSH: This might take a while for us to get to. To speed up the process, you can do one of two things:
 1. If you still require this, open a new issue using the `New issue` button and fill in the template provided to you
 2. Open a PR adding this functionality yourself and we will review and merge.

Will close this issue now as it's been over a year. Please use option `#1` if you still require this.
