### ISSUE TITLE
Feature Request: Generate nodejs client for loopback

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback#958]
Please add the tooling to generate nodejs client for loopback.

The google group discussion on this topic can be found here: https://groups.google.com/forum/#!topic/loopbackjs/QpDBiAmXZog

**Comment by pulkitsinghal** [comment]
> Why not use something like https://github.com/swagger-api/swagger-js?
@doublemarked - I felt like on the fly code would be more of a pain to debug than getting a file spit out that I could then tweak for any kinks.

**Comment by pulkitsinghal** [comment]
FYI: I filed another issue with https://github.com/wcandillon/swagger-js-codegen/issues/34 in my quest to get a perfect out-of-the-box javascript client for loopback ... I wouldn't need to do this if the `nickname` field generated by loopback's swagger spitting code was a bit more accommodating. I think @doublemarked also posed a question/comment for the authors above regarding the convention being followed.

**Comment by bajtos** [comment]
> @pulkitsinghal Any advice on how to workaround "nickname":"prototype.updateAttributes" from the swagger spec and get it to be "nickname":"updateAttributes"? Why was this particular nickname hard-coded this way compared to the other which weren't ... what was the original motivation behind it?

As @doublemarked explained above, these nick names are not hard-coded, they are generated from remoting metadata:

>  The updateAttributes method is picking up this prototype prefix due to it being an instance method. 

Can you pre-process the swagger metadata produced by LoopBack and fix nickname fields to whatever convention works well for you, before you pass the swagger metadata to codegen?

For example, loopback-sdk-angular renames `prototype.updateAttributes` to `prototype$updateAttributes`.

Regarding the second question:

> Why does the remote interface for PersistedModel use the static methods for all remote routes except for updateAttributes (PUT)? Probably there is a good reason beyond my understanding of the code.

I am not entirely sure, @raymondfeng or @ritch should be more competent to answer this question.

**Comment by doublemarked** [comment]
@bajtos, I have some thoughts regarding the nicknames - 

  1. The nicknames are currently mapping to the internal models/methods, but this is essentially meaningless to an API consumer. Nicknames are a property of the REST API and thus should reflect the functionality described by the REST API. I would expect the nickname to closely match the behavior of the route. 
  2. Following from #1, the nickname is exposing internal code information (model names, method names, etc) which I think should be avoided. 

Lastly - I want to plug https://github.com/swagger-api/swagger-js again, which is a vendor-provided JS client for Swagger-described APIs. A good barometer for success may be whether a LB-backed API is usable cleanly by Swagger JS.

**Comment by bajtos** [comment]
@doublemarked I don't mind changing the format of swagger nicknames generated by loopback (loopback-explorer) as long as the existing clients are either not affected or have a reasonably easy upgrade path (ping @STRML).

What do you propose?

/cc @ritch @raymondfeng

**Comment by bajtos** [comment]
The Swagger spec v2.0 does not place any restriction on the format of operation ids, see [the spec](https://github.com/OAI/OpenAPI-Specification/blob/d599df756d5f3d9c7af403ca12937c0f4cf3a9ab/versions/2.0.md#fixed-fields-5):

> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is recommended to follow common programming naming conventions.

Other codegenerators (e.g swagger-codegen) typically sanitise operation ids before creating a method name, I think swagger-js-codegen should do the same.

I am closing this issue, feel free to open a new one if you have a specific and detailed proposal on what should be changed in the swagger produced by LoopBack.
