### ISSUE TITLE
Document all remoting properties in server/config.json

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#959]
Need to describe all the properties you can set in the remoting section of `config.json`.  See
http://docs.strongloop.com/display/LB/config.json#config.json-Remotingproperties.

**Comment by crandmck** [comment]
@ritch PTAL

**Comment by ritch** [comment]
Can you add the defaults for `rest.supportedTypes`? I couldn't find them if they are there.

**Comment by ritch** [comment]
Otherwise LGTM.... @bajtos should probably take a look as he added a lot of the `remoting` options.

**Comment by bajtos** [comment]
> rest.xml	 - If true, then 'xml' is added to the supported content types. Then, the API will then respond with XML when the HTTP request "accepts" type is 'xml'.

A more correct phrasing: when the HTTP request "accepts" type *contains* 'xml'.

**Comment by bajtos** [comment]
Other than that, the section LGTM.

**Comment by ritch** [comment]
After @bajtos change this should be done

**Comment by crandmck** [comment]
Made all noted changes.
