### ISSUE TITLE
Connecting to sqlite for use within node-webkit

### ISSUE THREAD

**Issue by slawo** [strongloop/loopback#961]
Is there a way to use loopback within a node-webkit application with sqlite as the backend?

If no, how difficult would it be to add sqlite support to loopback?

Would there be any other issue with using loopback in a node-webkit environment?

**Comment by raymondfeng** [comment]
You may try https://github.com/jugglingdb/sqlite3-adapter and port it to LB. The migration should be trivial.

**Comment by mikeblakeney** [comment]
just wondering if anyone has made any progress on this connector.  I'd love to jump in help with it.  I'm particularly interest in it's application to mobile devices...

**Comment by slawo** [comment]
@mikeblakeney I have not seen any port of this connector. Currently we're evaluating other options. If we chose to use loopback we'll probably have to do a port next year, if there are no new on this front.

**Comment by raymondfeng** [comment]
It should be fairly straightforward to port https://github.com/jugglingdb/sqlite3-adapter to LoopBack.

**Comment by fabien** [comment]
Someone has created this: https://github.com/Synerzip/loopback-connector-sqlite

**Comment by lforge** [comment]
slawo, I would very much like to hear from your update on this.  I may have a need to do the same thing.  So any experiences that you can share is appreciated.  Thanks.

**Comment by JpCapdevila** [comment]
Im trying to use loopback in a node-webkit project but it is crashing when loopback is starting.

I tried to run loopback using this 2 alternatives:

1) - Require server.js from index.html

    <script type="text/javascript">
      var loopbackApp = require('../server/server.js');
    </script>

2) - Use the "node-main" property of the package.json

    "node-main" : "server/server.js"

No luck so far, here is the error trace:

    [551:0602/162111:ERROR:nw_shell.cc(335)] TypeError: Cannot set property 'title' of undefined
        at Object.<anonymous>     (/Users/kat/WebstormProjects/gidDocumentAnalyzer/node_modules/loopback/lib/loopback.js:184:29)
        at Module._compile (module.js:451:26)
        at Object.Module._extensions..js (module.js:469:10)
        at Module.load (module.js:346:32)
        at Function.Module._load (module.js:301:12)
        at Module.require (module.js:356:17)
        at require (module.js:375:17)
        at Object.<anonymous>     (/Users/kat/WebstormProjects/gidDocumentAnalyzer/node_modules/loopback/index.js:5:33)
        at Module._compile (module.js:451:26)
        at Object.Module._extensions..js (module.js:469:10)

I think the problem has to do something with the relative paths on the include statements in loopback.js.

Any advice?

Thanks!

**Comment by acao** [comment]
I'm getting this issue with electron.

The errorHandler comes from mixin(express). I'm guessing that there is some native node.js module missing in the runtime to load either of these.

Have you found a way to get around this issue yet?

**Comment by acao** [comment]
From what I'm reading, Express 4 removes the errorHandler and assumes a seperate module is used, so it should not be available on the mixin in lib/loopback.js, am I right?

Possibly this error is suppressed on the server? Strange because I've seen the client work in the browser before.

**Comment by acao** [comment]
Can the title of this issue be changed, or should a new one be created? This doesn't have anything to do with sqlite, it is an issue with loopback in general in nw.js/electron.js environments that may stem from issues with the loopback lib itself.

**Comment by acao** [comment]
I've figured out how to get past this issue. It turns out, we are improperly loading the loopback isomorphic client, causing loopback-boot to be confused into thinking it is loading the server.

The proper solution to this is to ensure you have a build task that bundles the lbclient properly first using browserify (see: offline sync example), and then allows it to be loaded properly as an node module.

Electron will only load the node module if you include it in your package.json - you can specify a local using the file:/path approach.  I think this is true.

Here is a messy example of an electron.js app properly using the loopback isomorphic client:
https://github.com/acao/electron-react-loopback-example
