### ISSUE TITLE
Don't overwrite non-null values when creating the built-in Applciation model

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback#966]
Right now the built-in `Application` model overrides values that a developer might want to specify explicitly: https://github.com/strongloop/loopback/blob/7c96aec9af579f697b8755b53bd9be1b628f939b/common/models/application.js#L88-L92

It would be great if any non-null values provided as `options` to `Application.register` were not overwritten: https://github.com/strongloop/loopback/blob/7c96aec9af579f697b8755b53bd9be1b628f939b/common/models/application.js#L112-L116

I'm guessing it will be as simple as a null check in the `Application.beforeCreate` method but I could be wrong so I will let the loopback gurus weigh-in :)

**Comment by loay** [comment]
Hi @pulkitsinghal 
We will have a look into that.
