### ISSUE TITLE
Key mismatch on column with value 0

### ISSUE THREAD

**Issue by cabolanoz** [strongloop/loopback#967]
The error I'm facing is the next one;

**Key mismatch: OpsItinerary.itinerary_status_ind: 0, GenIndicatorValue.ind_value: 0**

For some reasons, loopback cannot create a relation since the source and target value starts with 0, the identity value should be greater than that. I have some other relations with this target entity with values like 1 or 2 and the api performs exactly as I expect.

**Comment by shouvik** [comment]
Yep I encountered this issue as well. I though this had something to do with me using the foreign key as the primary key on a document. This bug made me realize this is just for 0. Thanks!

**Comment by gunjpan** [comment]
Closing as fix merged.
