### ISSUE TITLE
Get roles of users when find() users

### ISSUE THREAD

**Issue by chinajuanbob** [strongloop/loopback#968]
How do I get roles of users when GET /users?
Expected result will be something like:
users:[{
  username:...
  roles: ['admin', '...']
},{...
}]
Thanks!

**Comment by cesarbolanos** [comment]
You have to make a relation to your role's model. Assuming you have mapped the two tables, edit the "relations" tag of your user model and add the linked role to it. Should something like this;

"relations":{
     "roles": {
          "type": "hasMany", // Assuming you have a one to many relationship between the user and roles
          "mode": "YourRoleModelName",
          "foreignKey": "role_id" // This is the key from you user model that points to your role model
     }
}

Then, assuming that you're using the REST API, you have to include this relationship. It should be something like this;

/Users?filter[where][user_id]=1&filter[include]=roles

**Comment by chinajuanbob** [comment]
Thanks for the reply!

Is it possible to use internal Role and RoleMapping models in this way?

Thanks!

**Comment by superkhau** [comment]
@chinajuanbob Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. Closing.

**Comment by cto-oneva** [comment]
Close the question when you don't know the answer :)

**Comment by zhenyanghua** [comment]
@chinajuanbob Here is an example that just use internal Role and RoleMapping to get the roles from user id. [https://gist.github.com/zhenyanghua/d24ea57cd70e69bcb82dc3bc8f14ea74](https://gist.github.com/zhenyanghua/d24ea57cd70e69bcb82dc3bc8f14ea74)
