### ISSUE TITLE
Update example apps to use middleware phases

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#971]
All the example apps use the old way of defining middleware.  However, with the advent of [middleware phases](http://docs.strongloop.com/display/LB/Using+middleware+phases), there have been some changes that affect all the examples.  Here is a summary of the changes:
* `server/server.js`
* New `server/middleware.json` defines middleware.

See http://docs.strongloop.com/display/LB/Using+middleware+phases#Usingmiddlewarephases-Upgradingexistingprojects for details.

**Comment by chandadharap** [comment]
Highest priority.

**Comment by superkhau** [comment]
`loopback-example-database` will be split into 5 seperate examples (one for each connector)

**Comment by superkhau** [comment]
Done https://github.com/strongloop/loopback-example-mysql

**Comment by superkhau** [comment]
Create example repo to make tracking examples easier. See https://github.com/strongloop/loopback-example

**Comment by superkhau** [comment]
Done https://github.com/strongloop/loopback-example-angular

**Comment by superkhau** [comment]
WIP https://github.com/strongloop-internal/scrum-loopback/issues/122

**Comment by crandmck** [comment]
This is a separate issue, but is actuallyl part of this issue: https://github.com/strongloop/loopback-getting-started/issues/3.

It should the the top-priority since it affects Getting Started.

**Comment by superkhau** [comment]
Example repos are also being updated for errors
