### ISSUE TITLE
indexes in model.json

### ISSUE THREAD

**Issue by gagan-bansal** [strongloop/loopback#977]
Are defining indexes in model.json file supported? As this is described in [documentation of Model definition](http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Indexes)
In my case its ignored, I am defining index like this:
```javascript
"indexes": {
  "name_age_index": {
    "keys": {"name": 1, "age": -1}
  },
  "age_index": {"age": -1}
}
```
and this also is ignored:
```javascript
{
  "name": { "type": "String", "index": true },
  "email": { "type": "String", "index": {"unique": true} },
  "age": "Number"
}
```

**Comment by seriousben** [comment]
You need to call `app.datasource.db.autoupdate()`.

**Comment by gagan-bansal** [comment]
where should I add this line. I tried in
`` server/server.js``
after the boot script i.e after
``boot(app, __dirname);``
but there is an error
``TypeError: Cannot read property 'db' of undefined``

**Comment by gagan-bansal** [comment]
I am able to achieve the unique index with [validation](http://docs.strongloop.com/display/public/LB/Validatable+class#validatable-validatesuniquenessof) of the model in ``model.js`` 
```
module.exports = function(MyModel) {
  MyModel.validatesUniquenessOf('title');
};
```
but still to create index (not unique) on any property I need to define the index in ``model.json``.
And defining index in ``model.json`` is more simple. So still I need to resolve the issue.

**Comment by seriousben** [comment]
I have a script that I run after deployments:
```
var app = require('./server.js');

var dataSource = app.dataSources['db'];

dataSource.on('connected', function() {
  dataSource.autoupdate(function(err) {
    if (err) {
      console.error('Database could not be autoupdated', err);
      dataSource.disconnect();
      return;
    }
    console.log('Database autoupdated');
    dataSource.disconnect();
  });
});
```

**Comment by gagan-bansal** [comment]
Thank you, it worked for me. 
So technically which one is better to use, or which one is more efficient - defining index in model.json or using unique validation? 
Does unique validation also rely on mongodb (or database unique index)? if yes I think both are same.

**Comment by seriousben** [comment]
validation does a simple find.

Glad that it helped, you can chose this now :)
