### ISSUE TITLE
Fix checkpoint implementation

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#985]
The REST API uses one checkpoint id. In practice, the client checkpoint number will be different than the server-side number. (Think about two clients connected to the same server).

#1157

 - [x]  `Model.replicate` will accept two `since` values - one for the source model, another for the target model. The single `since` value will remain supported for backwards compatibility with a deprecation warning.

 - [x] Either associate changes with CP+1, or bump the CP as the first step in the `replicate` method. I prefer the latter as otherwise the method `Checkpoint.current()` does not make sense anymore.

 - [x] Modify `replicate` to return the current CP in the callback, probably for both source and target models. (I need to give this some more thoughts.)

 - [x] Write integration tests to verify that the scenarios I have identified while working on this issue are fixed by the changes above.

#1176

 - [x] Improve change detection to reduce the amount of false conflicts
 - [x] Write integration tests for common replication scenarios for single server with multiple clients.

#1187

 - [x] Write integration tests for conflict scenarios for single server with multiple clients.

Out of scope:

 - Rework the `Change` model to keep a history of changes instead of the last record only. Possibly rework the `PersistedModel.diff` and/or `PersistedModel.changes` to return a history of changes too.

**Comment by BerkeleyTrue** [comment]
This is something I am running into now, but haven't thought of a way to fix. What about adding local/remote checkpoint values to the Change model?

**Comment by bajtos** [comment]
> What about adding local/remote checkpoint values to the Change model?

That would not work as you can have multiple clients for the same server/model/change.

Here is what I'd like to implement instead: when a replication is finished, the new checkpoint should be created as `max(localCheckpoint, remoteCheckpoint)+1`.

**Comment by bajtos** [comment]
Uff, this issue is much more complex than I initially thought.

Problems we need to address:

 1. Ensure that no changes are added to the checkpoint that is being
   synchronized while the replication is in progress.

    *Example:*

     ```
     Code1: start replication of CP 1
     Code1: get the list of changes (diff): A, B, C
     Code2: make a new change D
     Code2: D is associated with the current CP 1
     Code1: finish the replication, create CP2
     ```

    *The problem:*

    The next run will consider change D as already synchronized

    *Solution:*

    Increment the checkpoint before querying for the list of changes,
    i.e. as the first step of the `diff` method.

 2. When the second step of replication (conflict resolution + batch update)
   is aborted, e.g. because there are conflicts or because update fails,
   the subsequent replication should process all changes that were not
   synchronized yet.

     Since the remote checkpoint was already incremented by `diff` in
     the first step, the client must remember the checkpoint to use as the
     `since` argument for replication, it cannot rely on the value provided
     by the remote party.

     *Solution:*

     Keep a list of checkpoints, one checkpoint for each remote party,
     plus one checkpoint used for local updates.

Below is a step-by-step example illustrating the proposed solution:

 - There are two clients ClientA and ClientB syncing with a single Server.
 - The tables show checkpoint values.

@BerkeleyTrue @ritch Thoughts? Can you find any weak spots in my proposal?

#### Initial state

|ClientA|Server|ClientB|
|---|---|---|
|local:0|local:0|local:0|

#### Replicate Server->ClientA

1. ClientA sets `since` to `ClientA:Server`, which is 0
2. Server calculates diff since 0 and increases `server:local` to 1
3. ClientA applies changes and sets `ClientA:Server` to 1

|ClientA|Server|ClientB|
|---|---|---|
|local:0|**local:1**|local:0|
|**Server:1**| | |

#### Replicate ClientA->Server

1. Server sets `since` to `Server:ClientA`, which is 0
2. ClientA calculates diff since 0 and increases `ClientA:local` to 1
3. Server applies changes and sets `server:ClientA` to 1

|ClientA|Server|ClientB|
|---|---|---|
|**local:1**|local:0|local:0|
|Server:1|**ClientA:1**| |

#### Replicate Server->ClientB

1. ClientB sets `since` to `ClientB:Server`, which is 0
2. Server calculates diff since 0 and increases `server:local` to 2
3. ClientB applies changes and sets `ClientB:Server` to 2

|ClientA|Server|ClientB|
|---|---|---|
|local:1|**local:2**|local:0|
|Server:1|ClientA:1|**Server:2**|

#### Replicate ClientB->Server

1. Server sets `since` to `Server:ClientB`, which is 0
2. ClientB calculates diff since 0 and increases `ClientB:local` to 1
3. Server applies changes and sets `server:ClientB` to 1

|ClientA|Server|ClientB|
|---|---|---|
|local:1|local:2|**local:1**|
|Server:1|ClientA:1|Server:2|
| |**ClientB:1**| |

#### Replication Server->ClientA aborted due to conflicts

1. ClientA sets `since` to `ClientA:Server`, which is 1
2. Server calculates diff since 1 and increases `server:local` to 3
3. Conflicts detected, the replication is aborted
4. Conflicts are resolved locally

|ClientA|Server|ClientB|
|---|---|---|
|local:1|**local:3**|local:1|
|Server:1|ClientA:1|Server:2|
| |ClientB:1| |

#### Replication Server->ClientA after conflicts

1. ClientA sets `since` to `ClientA:Server`, which is 1
2. Server calculates diff since 1 and increases `server:local` to 4
3. ClientA applies changes and sets `ClientA:Server` to 1

|ClientA|Server|ClientB|
|---|---|---|
|local:1|**local:4**|local:1|
|**Server:4**|ClientA:1|Server:2|
| |ClientB:1| |

**Comment by ritch** [comment]
> The next run will consider change D as already synchronized

This is certainly an issue. Perhaps the checkpoint for a change should always be set ahead of the current checkpoint. 

```
Code2: D is associated with the current CP + 1 (2)
```

> aborted due to conflicts

`Model.replicate()` is never aborted. Conflicting changes are never replicated. It is up to user code to fix the model in a way that it can be replicated.

We should not be updating the checkpoint of a conflicting change... It should basically be discarded from replication. Once the model is fixed the next `replicate()` call should replicate the change without conflict and set the correct checkpoint.

**Comment by bajtos** [comment]
Thanks @ritch for review.

> `Model.replicate()` is never aborted. Conflicting changes are never replicated (perhaps this is what you are referring to?). It is up to user code to fix the model(s) in a way that it can be replicated. Then they must call conflict.resolve().

A) The current implementation stops the replication if there is a conflict. Even though the response contains non-conflicting deltas, they are not applied.

B) A database write may fail, the client may crash, there are many reasons why the replication may not finish successfully.

In all of these cases, the subsequent run of the replication must pick again all changes that were not successfully replicated last time.

> This is certainly an issue. Perhaps the checkpoint for a change should always be set ahead of the current checkpoint.

How do you want to handle the situations where two clients are performing a simultaneous sync and there is an update in progress (creating a change associated with CP+1)? Yes, the first client will use `since=CP+1` for the next replication and pick up the change. However, the second client will use `since=CP+2` and thus it will miss this change (unless I am mistaken).

I need to analyse this approach in more depth to see if it can work. I'll look at it when this issue gets closer to being planned for the sprint.

**Comment by bajtos** [comment]
> > The next run will consider change D as already synchronized

> This is certainly an issue. Perhaps the checkpoint for a change should always
be set ahead of the current checkpoint.

Here is a problem of that approach.

Because you are associating changes with the next checkpoint (CP+1), the latest changes will be replicated twice: once for "since=CP" and then again for "since=CP+1".

This is not only a performance degradation, it will cause false conflicts to be reported:

If a client does not replicate for a while, while other clients and/or the server make multiple changes to the same model, we won't be able to tell that the change we are replicating for the second time has been already applied, since we are not keeping a full history of changes.

Example:

```
ClientA replicates from Server since CP=0
ClientA receives a change X, associates it with CP=1
ClientA updates the latest CP to CP=1
...time passes, the server has a change Z based on Y based on X
Server replicates changes from ClientA since CP=1
  change X is received from ClientA
  server is at change Z with prev=Y
  -> conflict
```

My conclusion is that the only reliable solution is the approach described in https://github.com/strongloop/loopback/issues/985#issuecomment-69737416, I'll start working on the implementation soon.

**Comment by ritch** [comment]
The problem mentioned in your last comment **is not related to checkpoints**. This is because **we only track the latest revision**. If we add TTL support to juggler we can track more changes and allow the juggler to clean them up.

Let me be explicit about the purpose of checkpoints. They are a simple counter for each set of model changes (remember there isn't a client and a server just Model to Model replication). It allows you to specify the changes you wish to be replicated. The replication algorithm uses this number to reduce the number of changes it includes during `diff()`. 

The issue with the existing `since` option is that it specifies the checkpoint value to be used when filtering both local and remote changes. I think we could add a bit more control that will allow you to specify both values.

I'd like to keep `replicate()` as magic free as possible. It should give you ultimate control over what is happening. Sure this makes implementing things like bi-replication a bit tough... but we can make that simple in another module or method.

**Comment by bajtos** [comment]
We had a long chat with @ritch and came to the following conclusions:

 - Checkpoints should be an optional optimisation, the replication must work even without them.

 - In order to get that, we must modify change-tracking to keep a history of all changes with a configurable TTL to prevent the changelog from becoming too lonng

 - The checkpoint manipulation should be moved outside of `.replicate()` call. That way both legs of bidirectional replication can use the same filter:

    ```js
    var since = // determine the value
    Local.replicate(Remote, since);
    Remote.replicate(Local, since);
    // update CP on both sides (Local, Remote)
    ```
 - The "since" value should be computed as "min(localCP, remoteCP)" . The new CP value should be computed as "max(localCP, remoteCP)+1".

We were also discussing how to make this changes without breaking backwards compatibility, a possible solution is to create a new module providing the new implementation of `replicate()` and possibly also change-tracking.

This comment is capturing the discussion only, I still need to verify that the proposed solution does not have any holes.

**Comment by bajtos** [comment]
> The new CP value should be computed as "max(localCP, remoteCP)+1".

This will not work in the way how it's proposed in my comment.

```
0. assume remoteCp=10, localCP=2
1. begin the replication
2. a local change X is added with CP=localCP+1=3
3. the replication is finished, the new CP is set to max(localCP, remoteCP)+1=11
4. X won't be picked up by the next replication run (since=11),
    because it's associated with a CP that has been already replicated (CP 3)
```

> The issue with the existing `since` option is that it specifies the checkpoint value to be used when filtering both local and remote changes. I think we could add a bit more control that will allow you to specify both values.

Yes, allowing different values for local and remote `since` may work. In other words, the checkpoints will remain specific to each peer (Model replicated), i.e. CP 4 for ModelA refers to a different set of changes than CP 4 for Model B.

In the simple client-server setup where the replication is always initiated by the client, it should be enough to keep a pair of [local,remote] checkpoints at the client.

```js
// persisted state
localStorage.syncState = { local: 0, remote: 0 };

// single sync run
var localSince = syncState.local;
var remoteSince = syncState.remote;
LocalModel.replicate(
  RemoteModel,
  { source: localSince, target: remoteSince },
  function(err, result) {
    syncState.local = result.sourceCheckPoint;
    syncState.remote = result.targetCheckPoint;

    RemoteModel.replicate(LocalModel,
      // notice source/target checkpoints are swapped
      // It should be also possible to optimise this by setting one of source/target
      // to the new value returned above
      { source: remoteSince, target: localSince },
      function(err, result) {
        syncState.remote = result.sourceCheckPoint;
        syncState.local = result.targetCheckPoint;
      done();
    });
  });
```

**Comment by bajtos** [comment]
Based on my previous comment, below is a list of tasks I need to implement to fix this issue. I'll copy it to the issue description.

 - `Model.replicate` will accept two `since` values - one for the source model, another for the target model. The single `since` value will remain supported for backwards compatibility with a deprecation warning.

 - Either associate changes with CP+1, or bump the CP as the first step in the `replicate` method. I prefer the latter as otherwise the method `Checkpoint.current()` does not make sense anymore.

 - Modify `replicate` to return the current CP in the callback, probably for both source and target models. (I need to give this some more thoughts.)

 - Rework the `Change` model to keep a history of changes instead of the last record only. Possibly rework the `PersistedModel.diff` and/or `PersistedModel.changes` to return a history of changes too.

 - Write integration tests to verify that the scenarios I have identified while working on this issue are fixed by the changes above.

 - As for TTL for Changes, I'll leave that out of scope of the replication core. The `Checkpoint` model has a `time` property that can be used by the application to perform a time-based cleanup.

**Comment by bajtos** [comment]
>  Rework the `Change` model to keep a history of changes instead of the last
>  record only. Possibly rework the `PersistedModel.diff` and/or
>  `PersistedModel.changes` to return a history of changes too.

Here is an outline of a possible solution based on our yesterday's
discussion with @ritch.

 - Keep a set of changes we have seen, plus one record (rev,prev)
  for the last change (HEAD). The set can be stored using the existing
  data model by reserving a special value of "prev" or "checkpoint" for
  the historical records.

 - During the replication, the source sends a full list of changes
   made since the last checkpoint, plus the source HEAD.

 - The target model applies the current version of the "diff" algorithm.

 - If the simple diff algorithm detects a conflict, then we check the list
   of source changes. If the set of target changes is a subset of source
   changes, then this is not a conflict.

I am rather reluctant to implement this proposal from several reasons:

 - It adds substantial complexity and "magic" to the replication process,
   making it more difficult to troubleshoot.

 - While the new version should reduce the amount of false conflicts, it still
   cannot prevent all of them.

 - On the other hand, it's possible that the new algorithm will not detect
   a true conflict, especially in situations where the same revision of the
   model is repeated multiple times in the history of changes.

 - The solution increases the amount of data that need's to be stored, and
   what's even more important, the amout of data exchanged during the
   replication run.

To put it a different way, the current implementation is very cautious and
prefers to rather report a false conflict than to make an incorrect merge.
The more time I spend thinking about this problem, the more I am convinced
that the current approach is the right solution for v1.0.

Thoughts?

**Comment by ritch** [comment]
> To put it a different way, the current implementation is very cautious and
prefers to rather report a false conflict than to make an incorrect merge.
The more time I spend thinking about this problem, the more I am convinced
that the current approach is the right solution for v1.0.

I'm torn on this. I prefer the simplicity of the current `change` data structure and `conflict.resolve()`. I don't want to have to deal with "false conflicts" though.

This reminds me of node's `stream.pipe()`. Its such a simple API and yet it has lead to so many headaches. Maybe trying to keep the API simple here will lead to the same evil "magic".

Is there a way we can expose some of this (thorough detection of seemingly false conflicts) through API so that we can defer the simplicity concern to some wrapper or user? I can't think of anything specific at the moment. Perhaps we can allow a custom function that determines conflicts and one for storing changes? The downside is the huge amount of added complexity which we are trying to avoid in the first place.

**Comment by bajtos** [comment]
> Is there a way we can expose some of this (thorough detection of seemingly false conflicts) through API so that we can defer the simplicity concern to some wrapper or user? I can't think of anything specific at the moment. Perhaps we can allow a custom function that determines conflicts and one for storing changes? The downside is the huge amount of added complexity which we are trying to avoid in the first place.

Plus the added complexity is placed on the shoulders of LoopBack users :( To me, it feels like "we could not figure out ourselves how to get this working, so dear user, go figure it out yourself".

Tomorrow, I'll continue working on small improvements of the current approach and writing more big-picture unit tests, in order to get a better picture of which scenarios works well and when we are detecting false conflicts. Hopefully that will give us more insights on how serious the issue of false conflicts really is.

**Comment by bajtos** [comment]
> I'm torn on this. I prefer the simplicity of the current change data structure and `conflict.resolve().`

:+1: 

On the other hand, I think `conflict.resolve` is just an API, it should be possible to keep the user-facing API simple regardless of the complexity of the underlying implementation.

> I don't want to have to deal with "false conflicts" though. I guess the issue with the current change tracking is that we don't store enough information to avoid false conflicts.

Exactly. My dislike for "false conflicts" started this whole issue, but I still haven't found a way how to solve this efficiently.

**Comment by bajtos** [comment]
One more idea to consider, though not for v1.0. It seems to me that most of our difficulties described above stem from our desire to implement a generic peer-to-peer replication, which is a very complex problem. What if we pivoted to a multiple-clients & single-server scenario, where the clients always sync changes with the server, the sync is always initiated by the client, and there is always only a single server (in the sense of a single server database, not necessarily a single server process)? I think this should allow us to make stronger assumption and thus keep the implementation details simpler.

**Comment by bajtos** [comment]
@ritch based on my work in #1176, I am regaining confidence about our current implementation. As long as the clients are keeping track of checkpoints and send correct `since` filters, the usual scenarios seem to work correctly. Yes, it means that checkpoints are no longer an optional optimisation not affecting the observed behaviour, but IMO that's fine for now.

I'd like to add few more tests verifying that resolved conflicts are correctly replicated too and then call this issue done. Any objections?

**Comment by ritch** [comment]
No objections

**Comment by bajtos** [comment]
Done.

**Comment by BerkeleyTrue** [comment]
woot!

**Comment by bajtos** [comment]
@BerkeleyTrue have you had a chance to verify this new implementation? Does it work better for you? The docs haven't been updated yet (see #988), but check out the unit-tests added by linked PRs, they should show how to use the API.

**Comment by BerkeleyTrue** [comment]
@bajtos Working on migrating to new version. Will be working on it for the next couple of hours.
