### ISSUE TITLE
High-level REST API for replication

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#987]
The current version of the REST replication protocol is too chatty. There are two many messages and too much data being exchanged between the client and the server during a two-way sync, the reason is that the replication algorithm is invoking lots of fine-grained methods. We should build a set of replication methods providing a higher-level REST API where only few requests are needed to perform a full sync.

**Comment by pthieu** [comment]
@bajtos: you mentioned you've split https://github.com/strongloop/loopback/issues/1020 into three stories. Can you link this issue to the associated story? If not, can you close?

**Comment by bajtos** [comment]
The three stories created from #712 are listed in 712's description: #985, #986 and #987 (this one). Yes, "last story" in https://github.com/strongloop/loopback/issues/712#issuecomment-69324255 is referring to this issue (#987).
