### ISSUE TITLE
Documentation for replication and offline data access & sync

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback#988]
Review the current documentation and extend it as necessary, so that the following information is available:

 - how to setup replication
 - how to setup an offline-capable client
 - how the replication algorithm works under the hood
 - a list of caveats and known issues

Possibly useful document: https://gist.github.com/BerkeleyTrue/f960946ba72814006651

**Comment by crandmck** [comment]
Cf http://docs.strongloop.com/display/LB/Synchronization

**Comment by crandmck** [comment]
In discussion, we determined that Miroslav needs to complete his work on the API, then add some eng. docs.  At that point (next sprint) it will likely be ready for me to start working on the docs.

**Comment by bajtos** [comment]
Related: https://groups.google.com/forum/#!topic/loopbackjs/IG0YhOhPz-0

**Comment by bajtos** [comment]
Resizing down to 3 story points. I'll collect list of resources/comments for @crandmck so that he can write the user documentation himself. I'll still need to write down developer documentation describing how the replication works under the hood.

**Comment by bajtos** [comment]
> - how to setup replication
> - how to setup an offline-capable client
> - how the replication algorithm works under the hood
> - a list of caveats and known issues

I wrote down answers to https://gist.github.com/bajtos/63b415629a341ef5d0c9

@ritch could you please review? The text is not meant to be a final version to be published, just a source of information for @crandmck.

@crandmck I am reassigning this story to you. Let me know if there is anything else you need from me  or @ritch in order to finish the documentation.

**Comment by bajtos** [comment]
I have updated the gist, users should set `strict: "throw"` instead of `strict: true`.

**Comment by bajtos** [comment]
Upcoming changes to incorporate in the gist and/or the doc page:
 - https://github.com/strongloop/loopback/pull/1251Improve error handling in replication
 - https://github.com/strongloop/loopback-datasource-juggler/pull/542 Add model setting "defaultToNull"

**Comment by crandmck** [comment]
Progress on this was delayed due to my jury duty and strong-pm.io, but FYI I am working on draft content to merge into existing docs at http://docs.strongloop.com/display/LB/Sync+doc+updates.  Will look at above also.

**Comment by bajtos** [comment]
Instructions update based on https://github.com/strongloop/loopback/issues/1215:

- Set the option "trackChanges" to true.
- Change the id property to an auto-generated GUID
- Enable "strict" and "persistUndefinedAsNull" flags.

**Comment by chandadharap** [comment]
Is this a story for Rand or Miro?

**Comment by bajtos** [comment]
This story is for Rand now. I have already prepared the documentation draft - see https://gist.github.com/bajtos/63b415629a341ef5d0c9

**Comment by crandmck** [comment]
I added Miroslav's writeup to http://docs.strongloop.com/display/LB/Synchronization and made the above changes.  Other than some revision and editing, not sure what else needs to be done.  Meeting with Ritchie tomorrow to try to resolve.

**Comment by bajtos** [comment]
Update based on https://github.com/strongloop/loopback-datasource-juggler/pull/562:

 - set the "strict" flag to "validate" instead of "throw"

**Comment by bajtos** [comment]
@crandmck I'll review the document (hopefully on Thursday) and let you know if there is anything missing.

**Comment by bajtos** [comment]
I have reviewed the document and added information about the improvements I have implemented recently ([diff](http://docs.strongloop.com/pages/diffpagesbyversion.action?pageId=3836343&selectedPageVersions=18&selectedPageVersions=16)).

@crandmck could you please review my changes and improve the text as needed?

I think the doc page is good for now and this story can be closed as resolved once you finish your editing/cleanup.

**Comment by crandmck** [comment]
Thanks! Made some minor wording and formatting edits.  LGTM.
