### ISSUE TITLE
beforeValidate hook does not seem to pass changes made to modelInstance on in the chain

### ISSUE THREAD

**Issue by stringbeans** [strongloop/loopback#990]
I have a model "Student" with a required field "statusId"

When I create the student, I do not set the statusId and I want to be able to set a statusId by default in the model hook.

To do this properly, I need to set it in the beforeValidate hook (otherwise the validation will catch that this required field is missing and spit back an error).

```
Student.beforeValidate = function(next, modelInstance) {
    modelInstance.statusId = 1;
    next()
};
```

However, I still get a validation error back when I do this. I'm using loopback 2.8.6

**Comment by fabien** [comment]
You should try to not set `required: true` on the `statusId` but instead try the following:

```
Student.validatesPresenceOf('statusId', { 
  unless: function() {
    return this.isNewRecord();
  }
});
```

**Comment by aantipov** [comment]
Try to use `this` instead of `modelInstance `
See https://github.com/strongloop/loopback/issues/1036

**Comment by bajtos** [comment]
Also note that we are moving away from `beforeValidate/afterValidate` hooks in favour of [Operation hooks](http://docs.strongloop.com/display/LB/Operation+hooks) and [Per-method hooks](https://github.com/strongloop/loopback-datasource-juggler/issues/397).

Please upgrade your project to use the new `before save` hook and open a new GH issue if you run into any problem.

**Comment by aantipov** [comment]
@bajtos please see also this issue https://github.com/strongloop/loopback/issues/755

**Comment by bajtos** [comment]
@aantipov good catch, I left a comment there.
