### ISSUE TITLE
REST upsert with where instead of by id

### ISSUE THREAD

**Issue by Nutelac** [strongloop/loopback#991]
It's possible to create upsert via REST, with where parameters, like when updating?

I tried

```
path: '/?where[prop1]=42&where[prop2]=24'
method: PUT
data: {"prop1":"42", "prop2": "24", "foo": "bar"}
```

But this just create new record, even when record with **prop1=42** and **prop2=24** exists.

Thank you.

**Comment by pthieu** [comment]
@Nutelac: Do you still need this? While this may not be a complex task, it's relatively low priority so this might take a while for us to get to. To speed up the process, you can do one of two things:
 1. If you still require this, open a new issue using the `New issue` button and fill in the template provided to you
 2. Open a PR adding this functionality yourself and we will review and merge.

Will close this issue now as it's been over a year. Please use option `#1` if you still require this.

**Comment by nishain-de-silva** [comment]
hey you can try `upsertWithWhere` in REST, for example, BASE_URL/upsertWithWhere and then in GET params add `where` param and set your criteria and on `body` set your data. The request should be `POST`
