### ISSUE TITLE
Any good way to set system wide IDs?

### ISSUE THREAD

**Issue by imkven** [strongloop/loopback#994]
I define custom ID inside the `boot` folder. My problem is every time I created new persistent model, I need define in here. Any better way to do it system wide?

```javascript
module.exports = function(app) {
  var Worker = app.models.Worker;
  Worker.beforeCreate = function(next, inst) {
    inst.id = genRandomId();
    next();
  };
}
```

**Comment by ritch** [comment]
Can you clarify what you mean by system wide?

**Comment by imkven** [comment]
I want built-in users ID able to customize too. Any where allow me to define once will override all models ID (Include built-in model ID)?

Now, I do it in manual, I create a boot script:
```
var crypto = require('crypto');
var uuid = require('node-uuid');

module.exports = function(app) {
  var Item= app.models.Item;
  var User= app.models.User;

  Item.beforeCreate = function(next, inst) {
    inst.id = parseInt(crypto.createHash('sha1').update(uuid.v4()).digest('hex'), 16).toString(36);
    next();
  };

  User.beforeCreate = function(next, inst) {
    inst.id = parseInt(crypto.createHash('sha1').update(uuid.v4()).digest('hex'), 16).toString(36);
    next();
  };
}
```

But, I don't think this is the best way to handle it, because it will override default beforeCreate() from user model.

**Comment by petermetz** [comment]
+1 I want to be able to POST records without an ID attribute and make those receive a generated random ID that is unique on the database level not just in the table.

**Comment by raymondfeng** [comment]
The property can have a `defaultFn` flag set to `uuid`. See https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Generalpropertyproperties
