### ISSUE TITLE
Add info on how to "skin" or brand API Explorer

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback#997]
From Dennis:

>You can customize Explorer to fit your organization's themes. In another words (IBM) you call it changing the themes and skins of the page. 
If doc is there I cannot find it.  I know it used to be this summer and easy to find - it probably just got lost in the reshuffling of the docs. If I have a vote in the matter, it should be in the Getting Started guide.  It is a basic question and showing a developer how to modify Explorer to look like their company's brand before showing their boss the API is, believe it or not, a big selling point. 

Affects http://docs.strongloop.com/display/LB/Use+API+Explorer and other articles.

**Comment by crandmck** [comment]
You can provide your own CSS file that will be used by the explorer instead of the file shipped by us

See `options.uiDirs`.

http://stackoverflow.com/questions/28073421/how-to-modify-the-strongloops-loopback-explorer-css/28088915#28088915

**Comment by bjrmatos** [comment]
if i understand correctly customizing the explorer UI would be the same as customizing Swagger UI files? if that is correct, a simple example and links to resources that explain about Swagger UI would be be really cool!

**Comment by Vandivier** [comment]
what about the text? Eg change page title from 'LoopBack API Explorer' to 'My Service Library'
